import { articleContent, type ArticleSection } from "./article-content";
import { articleClosers, articleExpansions, missingSpreadsheetSection, type LocalArticleLang } from "./article-expansions";

const baseArticleTranslations: Record<LocalArticleLang, Record<string, ArticleSection[]>> = {
  de: {
    "spreadsheet-without-buying-blind": [
      {heading:"Eine Tabelle ist eine Auswahlliste, kein Versprechen",paragraphs:["Eine gute Superbuy-Tabelle ordnet verstreute Produktfunde und macht sie prüfbar. Sie beweist weder Verkäuferzuverlässigkeit noch Bestand, aktuelle Optionen oder einen dauerhaft gültigen Preis.","Der offizielle Ablauf trennt Artikelzahlung, chinesischen Inlandsversand, Verkäuferlieferung, Lagerprüfung und internationale Paketeinreichung. Genau diese Entscheidungen sollte die Tabelle getrennt dokumentieren."]},
      {heading:"Die genaue Produktentscheidung vor der Zahlung festhalten",paragraphs:["Neben dem Link gehören aktueller Titel, Farbe, Größe, Menge, Optionsbezeichnung, Artikelpreis, angezeigter Inlandsversand und Prüfdatum. Bei gemischten Listings sollte die gewünschte Variante zusätzlich beschrieben werden.","Beim erneuten Öffnen werden Hauptbild und Optionen mit der Notiz verglichen. Wurde das Listing ersetzt oder die Variante entfernt, geht die Zeile zurück auf „Prüfen“."],bullets:["Aktuelles Ziel und Prüfdatum","Exakter Optionsname, Farbe, Größe und Menge","Artikelpreis und angezeigter Inlandsversand","Kurze Notiz zum Bildabgleich","Eine Frage für die Lagerprüfung"]},
      {heading:"Plattformgebühren vom Produktpreis trennen",paragraphs:["Die aktuelle Superbuy-Gebührenseite nennt den Standardkauf bei Taobao, Tmall, JD.com und 1688 gebührenfrei. Trotzdem können Artikelpreis, Inlandsversand und optionale Services anfallen.","Verwende deshalb keine Spalte „Endpreis“. Trenne Produkt, Inlandsversand, Zusatzservices und einen späteren internationalen Versandwert, weil Paketdaten erst im Lager vollständig werden."]},
      {heading:"Lagerfotos als neue Belege nutzen",paragraphs:["Die aktuelle Startseite nennt drei kostenlose QC-Fotos nach Lagereingang. Diese Bilder zeigen den für die Bestellung eingegangenen Artikel und sind damit relevanter als reine Verkäuferwerbung.","Sie können Farbe, Menge, Form, sichtbare Ausrichtung und Schäden zeigen, aber nicht sicher Echtheit, Material, Komfort, Haltbarkeit oder Passform beweisen. Für 1688 nennt Superbuy einen anderen QC-Standard."]},
      {heading:"QC in eine Entscheidung verwandeln",paragraphs:["Vor der Lagerankunft sollte pro Artikel eine entscheidende Frage notiert werden, etwa Sohlenzustand, Brustweite, Druckposition oder Vollständigkeit eines Sets.","Nach Sichtung folgt eine konkrete Aktion: für das Paket akzeptieren, Detailfoto anfordern, Auffälligkeit klären, bei Berechtigung Rückgabe beantragen oder auf einen weiteren Artikel warten."]},
      {heading:"Das 90-Tage-Lagerfenster bewusst nutzen",paragraphs:["Superbuy nennt aktuell 90 Tage kostenlose Lagerung. Danach listet die Gebührenseite Tageskosten pro Artikel, eine Standardhöchstdauer von 180 Tagen und eine buchbare Verlängerung.","Trage Lagereingang und geplantes Paketdatum ein. Ältere Artikel mit offenen QC- oder Rückgabefragen werden zuerst bearbeitet, damit die Frist nicht unbemerkt abläuft."]},
      {heading:"Konsolidierung spart nicht automatisch",paragraphs:["Geeignete Bestellungen können laut Superbuy kostenlos konsolidiert werden und dadurch günstiger sein. Ein größeres Paket kann jedoch Volumengewicht, Grenzen oder Einschränkungen auslösen.","Gruppiere nach Gewicht, Maßen, Zerbrechlichkeit, Batterien, Flüssigkeiten und Verpackungsbedarf. Vergleiche nach Lagereingang die tatsächlich verfügbaren Linien statt immer ein einziges großes Paket zu wählen."]},
      {heading:"Ein Statussystem verhindert Fehlbestellungen",paragraphs:["Nutze eindeutige Stati wie Fund, Listing geprüft, Option bestätigt, gekauft, im Inlandsversand, Lagerprüfung, Beleg nötig, paketbereit, eingereicht und abgeschlossen.","Die kleinste brauchbare Vorlage enthält Linkstatus, Bildabgleich, Option, Preisreferenz und QC-Frage. Vor Zahlung wird die Live-Seite erneut geöffnet und der nächste Schritt festgelegt."]}
    ],
    "qc-photo-checklist": [
      {heading:"Was Superbuy-QC-Fotos tatsächlich zeigen",paragraphs:["Superbuy nennt derzeit drei kostenlose QC-Fotos nach Lagereingang. Der Leitfaden beschreibt außerdem Prüfung, Bereitstellung der Fotos im Nutzerkonto und Kontakt bei Auffälligkeiten.","Diese Bilder dokumentieren Sichtbares wie Identität, Menge, Farbe, Form, gezeigte Maße und offensichtliche Schäden. Echtheit, innere Konstruktion, Material oder Dauer lassen sich damit nicht sicher beweisen."]},
      {heading:"Vor Qualität zuerst die Identität prüfen",paragraphs:["Zuerst werden Produktart, gewählte Farbe, Menge und sichtbare Option mit Listing und Kaufnotiz verglichen. Bei Paaren und Sets muss die erwartete Stückzahl stimmen.","Wenn die Option nicht erkennbar ist, fordere ein gezieltes Foto von Etikett, Größenangabe, Modellcode oder Zubehör an, bevor kleine Verarbeitungsdetails bewertet werden."],bullets:["Produktart und Modell","Farbe und sichtbare Variante","Menge, Paare und Setbestandteile","Größenetikett oder Optionsmerkmal","Zubehör der gewählten Option"]},
      {heading:"Maße mit einem eigenen Artikel vergleichen",paragraphs:["Größenetiketten unterscheiden sich. Vergleiche Lagermaße mit einem vertrauten Kleidungsstück oder Schuh, der an denselben Punkten gemessen wurde.","Notiere Wert und Messpunkt. Flache Breite ist nicht Körperumfang; fehlt eine entscheidende Abmessung, ist ein Detailfoto besser als eine Vermutung."]},
      {heading:"Verarbeitung nach Produktkategorie prüfen",paragraphs:["Bei Kleidung zählen Nähte, Fäden, Druck, Stickerei, Symmetrie, Reißverschlüsse und Flecken. Bei Schuhen werden Paarvergleich, Sohle, Zehenform, Klebespuren und Ferse geprüft.","Bei Taschen und Zubehör sind Ecken, Verschlüsse, Riemen und Kleinteile wichtig. Formuliere beobachtbare Abweichungen statt allgemeiner Urteile wie „schlechte Qualität“."]},
      {heading:"Wann ein Detailfoto sinnvoll ist",paragraphs:["Ein Detailfoto lohnt sich, wenn es eine konkrete offene Entscheidung beantwortet: Größenetikett, Brustmaß, Reißverschluss, Sohlenlabel oder alle Zubehörteile in einem Bild.","Die Gebührenseite verwendet aktuell CN¥3 in ihrem Beispiel, Preise können sich jedoch ändern. Entscheidend ist, ob das Bild einen teureren Fehler vor internationalem Versand verhindert."]},
      {heading:"1688 und Sonderartikel vorsichtig behandeln",paragraphs:["Superbuy weist für 1688 auf einen anderen QC-Standard hin. Bei manchen Elektronik-, Karten-, Modell- oder versiegelten Artikeln kann die Prüfung auf sichtbare Unversehrtheit begrenzt sein.","Bei zerbrechlichen, maßgefertigten, gebrauchten oder technisch komplexen Artikeln müssen vor Kauf strengere Fragen und Rückgaberisiken dokumentiert werden."]},
      {heading:"Pass-, Anfrage- oder Rückgabeentscheidung zeitnah treffen",paragraphs:["„Pass“ bedeutet, dass die vorher definierten sichtbaren Fragen beantwortet wurden. „Anfrage“ bedeutet, dass ein fehlendes Bild die Entscheidung ändern kann; „Rückgabe“ setzt aktuelle Berechtigung voraus.","Die veröffentlichten Bedingungen nennen für geeignete Agentenprodukte einen Fünf-Tage-Rahmen mit Grenzen und Ausnahmen. Verkäuferregeln und Produktart müssen sofort geprüft werden."]},
      {heading:"Eine wiederholbare QC-Checkliste",paragraphs:["Prüfe immer in derselben Reihenfolge: Identität, Menge, Option, Maße, Verarbeitung, Oberfläche, Vollständigkeit und ein kategorietypisches Risiko.","Trenne Wissen und Unbekanntes: Farbe sichtbar passend, Maß akzeptabel, Material oder Haltbarkeit unbestätigt. So wird QC nicht fälschlich als vollständige Verifizierung dargestellt."]},
      {heading:"Lagerzeit als Teil der Qualitätskontrolle",paragraphs:["Die aktuellen 90 kostenlosen Lagertage geben Zeit für weitere Einkäufe und Prüfung. Notiere Eingang, Fotoprüfung, Rückfrage und endgültige Entscheidung.","Priorisiere Artikel mit Rückgaberisiko, fehlenden Maßen oder Auffälligkeiten. So ist bei Paketeinreichung bereits dokumentiert, warum jeder Artikel versendet wird."]},
      {heading:"Häufige QC-Fehler vermeiden",paragraphs:["Vergleiche Lagerbilder mit dem exakten Listing, nicht mit Influencerbildern oder anderen Verkäufern. Beleuchtung kann Farbe verändern; bei wichtigen Farbabfragen ist ein klares Foto nötig.","Akzeptiere nicht automatisch, nur weil der Artikel bereits im Lager liegt. Probleme lassen sich vor internationalem Versand meist günstiger untersuchen und gegebenenfalls lösen."]}
    ],
    "shipping-cost-planning": [
      {heading:"Warum der Produktpreis nicht die Lieferkosten vorhersagt",paragraphs:["Superbuy trennt Artikel, Inlandsversand und Produktservices von der späteren internationalen Paketgebühr. Diese hängt von Endgewicht, Linie und Ziel ab.","Eine USD-Preisreferenz ist daher kein Endkostenangebot. Vor Lagereingang fehlen Packmaß, geprüftes Gewicht, Berechtigung und gewählte Verpackung."]},
      {heading:"Versanddepot und Endanpassung verstehen",paragraphs:["Das internationale Depot wird laut Leitfaden aus Schätzgewicht, Versandart und Ziel berechnet. Nach dem Verpacken prüft der Beförderer Größe und Gewicht.","Abweichungen werden nach Versand über das Superbuy-Konto ausgeglichen. Notiere Schätzung und Enddaten getrennt, damit spätere Kalkulationen vergleichbar bleiben."]},
      {heading:"Tatsächliches und Volumengewicht unterscheiden",paragraphs:["Tatsächliches Gewicht kommt von der Waage; Volumengewicht bewertet den belegten Raum. Ein leichtes, großes Paket kann deshalb wie ein schwereres berechnet werden.","Divisor und Rundung unterscheiden sich je Linie. Verpackung nur entfernen, wenn Volumenvorteil, Schutz und Wert der Originalverpackung sinnvoll abgewogen wurden."]},
      {heading:"Nach Kompatibilität konsolidieren, nicht nach Größe",paragraphs:["Kostenlose Konsolidierung kann wiederholte Grundkosten und Verpackung reduzieren. Sie kann aber Volumen, Gewicht oder Einschränkungen erhöhen.","Notiere für Paketgruppen Gewicht, Maße, Zerbrechlichkeit, Batterien, Flüssigkeiten und Originalkartons. Vergleiche nach Lagereingang mindestens zwei sinnvolle Gruppierungen."]},
      {heading:"Berechtigte Linien statt Werbepreise vergleichen",paragraphs:["Superbuy nennt 100+ Linien und 200+ Länder und Regionen, doch ein konkretes Paket sieht nur die nach Ziel, Eigenschaften, Gewicht und Maßen verfügbaren Linien.","Vergleiche am selben Tag Preis, Laufzeitspanne, Abrechnungsgewicht, Tracking, Einschränkungen und Versicherung. Drittanbieter- und Zollzeiten dürfen nicht garantiert werden."]},
      {heading:"Verpackungsservices gezielt einsetzen",paragraphs:["Der Leitfaden nennt Verpackungsentfernung, Verstärkung und Versicherung. Sie lösen unterschiedliche Probleme und sollten nicht automatisch gewählt werden.","Weiche Ware braucht oft wenig Zusatzschutz, Zerbrechliches eher Verstärkung. Bei Versicherung sind Bedingungen, Ausschlüsse und Versicherungswert zu prüfen."]},
      {heading:"Zoll und Steuern sind zielabhängig",paragraphs:["Zölle und MwSt. hängen laut Gebührenseite von Ziel, Warenart und Deklaration ab. Bedingungen warnen vor Verzögerung, Rücksendung oder Beschlagnahme.","Prüfe aktuelle Einfuhrregeln und Beschränkungen für das Zielland. Keine Tabelle kann eine steuerfreie Zustellung seriös versprechen."]},
      {heading:"Mit drei Schätzungen planen",paragraphs:["Nutze Fundschätzung, Lagerschätzung und Live-Angebot bei Paketeinreichung. Erst die letzte Stufe basiert auf der tatsächlichen Gruppe und verfügbaren Linie.","Halte Inlands- und internationalen Versand getrennt und ergänze Services. Das Ziel ist keine frühe perfekte Zahl, sondern bessere Daten in jeder Phase."]},
      {heading:"Checkliste vor der Paketeinreichung",paragraphs:["Bestätige QC-Status aller Artikel, vollständige Adresse, sinnvolle Gruppierung und Linienberechtigung. Prüfe Gewicht, Volumen, Verpackung, Versicherung und Zollinformationen.","Speichere Linie, Angebot, Datum und Tracking. Nach Zustellung werden Endkosten, Laufzeit und Anpassungen verglichen, damit die nächste Schätzung auf Belegen beruht."]},
      {heading:"Häufige Fehler bei der Versandplanung",paragraphs:["Vermeide feste Versandbeträge vor Lagerdaten, die billigste Linie ohne Detailprüfung, automatische Vollkonsolidierung und garantierte Lieferzeiten.","Berechne neu, wenn Gruppe, Maße oder Beförderungsbedingungen wechseln. Nutze den Live-Rechner und lies vor Zahlung die aktuellen Liniendetails."]}
    ]
  },
  fr: {
    "spreadsheet-without-buying-blind": [
      {heading:"Un tableur est une sélection, pas une promesse",paragraphs:["Un bon tableur Superbuy organise des trouvailles dispersées et les rend vérifiables. Il ne prouve ni la fiabilité du vendeur, ni le stock, ni l’option actuelle, ni un prix permanent.","Le parcours officiel sépare paiement de l’article, livraison locale, expédition du vendeur, contrôle en entrepôt et colis international. Le tableur doit conserver ces décisions séparément."]},
      {heading:"Enregistrer la décision produit exacte avant paiement",paragraphs:["À côté du lien, notez titre actuel, couleur, taille, quantité, libellé de l’option, prix, livraison locale affichée et date de contrôle. Décrivez la vignette choisie pour les annonces mixtes.","À la réouverture, comparez image principale et options avec votre note. Si l’annonce ou la variante a changé, repassez la ligne au statut « à vérifier »."],bullets:["Destination actuelle et date","Nom exact de l’option, couleur, taille et quantité","Prix et livraison locale affichée","Note de correspondance d’image","Une question pour le contrôle en entrepôt"]},
      {heading:"Séparer les frais de plateforme du prix produit",paragraphs:["La page de frais actuelle indique que l’achat standard est gratuit sur Taobao, Tmall, JD.com et 1688. Le prix, la livraison locale et les services optionnels restent possibles.","Évitez une colonne unique « coût final ». Séparez article, livraison locale, options et estimation internationale, car les données du colis arrivent plus tard."]},
      {heading:"Utiliser les photos d’entrepôt comme nouvelles preuves",paragraphs:["La page d’accueil annonce trois photos QC gratuites après réception. Elles montrent l’unité reçue et sont plus pertinentes que la galerie promotionnelle du vendeur.","Elles peuvent confirmer couleur, quantité, forme et dommages visibles, mais pas sûrement authenticité, matière, confort, durée ou coupe. Superbuy indique une norme QC différente pour 1688."]},
      {heading:"Transformer le QC en décision",paragraphs:["Avant l’arrivée, écrivez une question décisive : état de la semelle, largeur, placement du motif ou nombre de composants.","Après les photos, choisissez une action précise : accepter, demander une image, clarifier une anomalie, retourner si éligible ou attendre un autre article."]},
      {heading:"Utiliser volontairement les 90 jours de stockage",paragraphs:["Superbuy indique actuellement 90 jours gratuits. La page de frais mentionne ensuite un tarif quotidien par article, une limite standard de 180 jours et un service de prolongation.","Notez date d’arrivée et date cible du colis. Traitez d’abord les articles anciens avec questions QC ou retour afin de ne pas perdre la fenêtre."]},
      {heading:"Le regroupement n’économise pas toujours",paragraphs:["Les commandes éligibles peuvent être consolidées gratuitement et parfois coûter moins cher. Un colis plus grand peut toutefois déclencher poids volumétrique, limites ou restrictions.","Regroupez selon poids, dimensions, fragilité, batteries, liquides et emballage. Comparez les lignes réellement disponibles après réception."]},
      {heading:"Un système de statuts évite les achats accidentels",paragraphs:["Utilisez découverte, annonce contrôlée, option confirmée, acheté, transit local, contrôle entrepôt, preuve requise, prêt, soumis et terminé.","Le modèle minimum contient état du lien, image, option, prix et question QC. Juste avant paiement, rouvrez la page et fixez l’action suivante."]}
    ],
    "qc-photo-checklist": [
      {heading:"Ce que représentent réellement les photos QC",paragraphs:["Superbuy annonce trois photos QC gratuites après l’arrivée. Le guide décrit inspection, affichage des images dans le compte et contact lorsqu’un problème est constaté.","Ces images documentent identité, quantité, couleur, forme, mesures visibles et dommages apparents. Elles ne prouvent pas sûrement authenticité, structure interne, matière ou durée."]},
      {heading:"Vérifier l’identité avant la qualité",paragraphs:["Commencez par type, couleur, quantité et option, comparés avec l’annonce et la note d’achat. Pour une paire ou un ensemble, vérifiez le nombre de pièces.","Si l’option reste invisible, demandez une image ciblée de l’étiquette, de la taille, du code modèle ou des accessoires avant les petits détails."],bullets:["Type et modèle","Couleur et variante visible","Quantité, paires et composants","Étiquette de taille ou repère d’option","Accessoires de l’option choisie"]},
      {heading:"Comparer les mesures avec un article personnel",paragraphs:["Les étiquettes varient. Comparez les mesures d’entrepôt avec un vêtement ou une chaussure familière mesuré aux mêmes points.","Notez valeur et point de mesure. Une largeur à plat n’est pas un tour de corps ; demandez une photo si une dimension décide du résultat."]},
      {heading:"Contrôler la construction selon la catégorie",paragraphs:["Pour les vêtements, observez coutures, fils, impression, broderie, symétrie, fermeture et taches. Pour les chaussures, comparez la paire, semelle, bout, colle et talon.","Pour sacs et accessoires, inspectez coins, fermetures, sangles et petites pièces. Décrivez une différence observable plutôt qu’un jugement vague."]},
      {heading:"Quand demander une photo détaillée",paragraphs:["Elle est utile si elle répond à une décision précise : étiquette, mesure de poitrine, fermeture, semelle ou accessoires réunis.","La page de frais emploie actuellement CN¥3 dans son exemple, mais le prix peut changer. L’image doit éviter une erreur plus coûteuse."]},
      {heading:"Traiter 1688 et les articles spéciaux avec prudence",paragraphs:["Superbuy signale une norme QC différente pour 1688. Certains appareils, cartes, modèles ou produits scellés peuvent n’être contrôlés que visuellement.","Pour les articles fragiles, personnalisés, d’occasion ou techniques, documentez avant achat des questions plus strictes et les limites de retour."]},
      {heading:"Décider rapidement : accepter, demander ou retourner",paragraphs:["Accepter signifie que les questions visibles définies ont reçu une réponse. Demander signifie qu’une image peut changer le choix ; retourner exige l’éligibilité actuelle.","Les conditions publiées décrivent un cadre de cinq jours pour certains produits, avec limites et exceptions. Vérifiez immédiatement vendeur, type de produit et option après-vente."]},
      {heading:"Une checklist QC répétable",paragraphs:["Suivez toujours identité, quantité, option, mesures, construction, surface, complétude et risque propre à la catégorie.","Séparez connu et inconnu : couleur correspondante, mesure acceptable, matière ou durée non confirmée. Le QC ne devient pas une certification totale."]},
      {heading:"Utiliser le stockage dans le contrôle qualité",paragraphs:["Les 90 jours gratuits actuels laissent du temps pour d’autres achats et pour l’inspection. Notez arrivée, revue, question et décision.","Traitez d’abord retour incertain, mesure absente ou anomalie. Lors du colis, chaque article possède déjà une raison documentée."]},
      {heading:"Éviter les erreurs QC fréquentes",paragraphs:["Comparez avec l’annonce exacte, pas avec un influenceur ou un autre vendeur. La lumière modifie la couleur ; demandez une image claire si elle est décisive.","N’acceptez pas automatiquement parce que l’article est déjà stocké. Les problèmes coûtent généralement moins cher à examiner avant l’expédition internationale."]}
    ],
    "shipping-cost-planning": [
      {heading:"Pourquoi le prix produit ne prédit pas le coût livré",paragraphs:["Superbuy sépare article, transport local et services du coût international ultérieur, calculé selon poids final, ligne et destination.","Une référence USD n’est donc pas un prix livré. Avant l’entrepôt, dimensions, poids vérifié, éligibilité et emballage restent incomplets."]},
      {heading:"Comprendre l’acompte et l’ajustement final",paragraphs:["Le guide calcule l’acompte avec poids estimé, méthode et destination. Après emballage, le transporteur vérifie taille et poids.","La différence est ajustée sur le compte après expédition. Conservez estimation et données finales séparément pour comparer correctement."]},
      {heading:"Distinguer poids réel et volumétrique",paragraphs:["Le poids réel vient de la balance ; le poids volumétrique facture l’espace occupé. Un colis léger et grand peut donc être tarifé comme plus lourd.","Diviseur et arrondis varient selon la ligne. Retirez l’emballage seulement après comparaison entre volume, protection et valeur de la boîte."]},
      {heading:"Regrouper par compatibilité, pas par quantité",paragraphs:["La consolidation gratuite peut réduire les frais de base et l’emballage, mais aussi augmenter volume, poids ou restrictions.","Pour chaque groupe, notez poids, dimensions, fragilité, batteries, liquides et boîtes. Comparez au moins deux regroupements après réception."]},
      {heading:"Comparer les lignes éligibles, pas les tarifs publicitaires",paragraphs:["Superbuy annonce 100+ lignes et 200+ pays et régions, mais un colis ne voit que les options compatibles avec destination, attributs, poids et taille.","Comparez le même jour prix, délai estimé, règle de poids, suivi, restrictions et assurance. Ne garantissez ni transporteur tiers ni douane."]},
      {heading:"Choisir les services d’emballage selon le besoin",paragraphs:["Le guide mentionne retrait d’emballage, renforcement et assurance. Chaque service répond à un risque différent.","Les textiles demandent souvent peu de protection ; le fragile peut nécessiter un renfort. Pour l’assurance, lisez conditions, exclusions et valeur assurée."]},
      {heading:"Traiter douane et taxes selon la destination",paragraphs:["Droits et TVA dépendent de la destination, de la catégorie et de la déclaration. Les conditions avertissent de retards, retours ou saisies.","Vérifiez règles et restrictions actuelles du pays. Aucun tableur ne peut garantir honnêtement une livraison sans taxe."]},
      {heading:"Planifier avec trois estimations",paragraphs:["Utilisez estimation de découverte, estimation d’entrepôt et devis réel à la soumission. Seule la dernière s’appuie sur le groupe et les lignes actuels.","Séparez livraison locale et internationale, puis ajoutez les services. L’objectif est d’améliorer les données à chaque étape."]},
      {heading:"Checklist finale avant soumission",paragraphs:["Confirmez QC, adresse, groupe et éligibilité. Vérifiez poids réel et volumétrique, emballage, assurance et informations douanières.","Enregistrez ligne, devis, date et suivi. Après réception, comparez coût final, durée et ajustement pour améliorer l’estimation suivante."]},
      {heading:"Éviter les erreurs de planification courantes",paragraphs:["Évitez un montant fixe avant l’entrepôt, la ligne la moins chère sans détails, le regroupement automatique et les délais garantis.","Recalculez si groupe, dimensions ou conditions changent. Utilisez le calculateur en direct et lisez les règles de ligne avant paiement."]}
    ]
  },
  es: {
    "spreadsheet-without-buying-blind": [
      {heading:"Una hoja es una lista de candidatos, no una promesa",paragraphs:["Una buena hoja Superbuy organiza hallazgos dispersos y permite revisarlos. No prueba fiabilidad del vendedor, stock, opción actual ni precio permanente.","El flujo oficial separa pago del artículo, envío nacional, despacho del vendedor, inspección de almacén y paquete internacional. La hoja debe registrar cada decisión por separado."]},
      {heading:"Registrar la decisión exacta antes de pagar",paragraphs:["Junto al enlace guarda título actual, color, talla, cantidad, texto de opción, precio, envío nacional mostrado y fecha. En listados mixtos describe también la miniatura elegida.","Al reabrir, compara imagen y opciones con la nota. Si el listado fue sustituido o la variante desapareció, devuelve la fila a «revisar»."],bullets:["Destino actual y fecha","Nombre exacto de opción, color, talla y cantidad","Precio y envío nacional mostrado","Nota de coincidencia de imagen","Una pregunta para el almacén"]},
      {heading:"Separar tarifas de plataforma y precio",paragraphs:["La página actual indica compra estándar gratuita en Taobao, Tmall, JD.com y 1688. Aun así puede haber precio, envío nacional y servicios opcionales.","No uses una sola columna de «coste final». Separa producto, entrega nacional, opciones y estimación internacional, porque los datos del paquete llegan después."]},
      {heading:"Usar fotos de almacén como nueva evidencia",paragraphs:["La página actual anuncia tres fotos QC gratuitas tras la recepción. Muestran la unidad recibida y son más relevantes que las fotos promocionales.","Pueden confirmar color, cantidad, forma y daños visibles, pero no autenticidad, material, comodidad, duración o ajuste. Superbuy señala otra norma QC para 1688."]},
      {heading:"Convertir el QC en una decisión",paragraphs:["Antes de la llegada escribe una pregunta decisiva: suela, ancho de prenda, posición de impresión o contenido del conjunto.","Después elige una acción: aceptar, pedir foto, aclarar anomalía, devolver si es elegible o esperar otro artículo."]},
      {heading:"Usar con intención los 90 días de almacén",paragraphs:["Superbuy indica 90 días gratis. La página de tarifas añade cargo diario por artículo, máximo estándar de 180 días y servicio de extensión.","Registra llegada y fecha objetivo. Resuelve primero artículos antiguos con dudas QC o posible devolución para no perder la ventana."]},
      {heading:"Consolidar no siempre ahorra",paragraphs:["Los pedidos elegibles pueden consolidarse gratis y a veces ahorrar. Un paquete mayor puede activar peso volumétrico, límites o restricciones.","Agrupa por peso, medidas, fragilidad, baterías, líquidos y embalaje. Compara las líneas realmente disponibles después de la recepción."]},
      {heading:"Un sistema de estados evita compras equivocadas",paragraphs:["Usa estados como hallazgo, listado revisado, opción confirmada, comprado, tránsito nacional, revisión, evidencia necesaria, listo, enviado y cerrado.","El modelo mínimo contiene estado del enlace, imagen, opción, precio y pregunta QC. Antes de pagar reabre la página y define la siguiente acción."]}
    ],
    "qc-photo-checklist": [
      {heading:"Qué representan realmente las fotos QC",paragraphs:["Superbuy anuncia tres fotos QC gratis tras llegar al almacén. La guía describe inspección, publicación en la cuenta y contacto si se detecta un problema.","Las imágenes documentan identidad, cantidad, color, forma, medidas visibles y daños aparentes. No prueban autenticidad, estructura interna, material o duración."]},
      {heading:"Comprobar identidad antes que calidad",paragraphs:["Empieza por tipo, color, cantidad y opción, comparados con el listado y la nota de compra. En pares y conjuntos confirma todas las piezas.","Si no se ve la opción, pide una imagen específica de etiqueta, talla, código o accesorios antes de revisar detalles pequeños."],bullets:["Tipo y modelo","Color y variante visible","Cantidad, pares y componentes","Etiqueta de talla o marcador de opción","Accesorios de la opción elegida"]},
      {heading:"Comparar medidas con un artículo propio",paragraphs:["Las etiquetas varían. Compara las medidas de almacén con una prenda o zapato conocido medido en los mismos puntos.","Guarda valor y punto de medida. Un ancho plano no es contorno corporal; si falta una medida decisiva, pide una foto."]},
      {heading:"Revisar construcción según la categoría",paragraphs:["En ropa observa costuras, hilos, impresión, bordado, simetría, cremalleras y manchas. En calzado compara el par, suela, puntera, pegamento y talón.","En bolsos y accesorios revisa esquinas, cierres, correas y piezas. Describe diferencias visibles en vez de usar juicios vagos."]},
      {heading:"Cuándo pedir una foto detallada",paragraphs:["Es útil si responde una decisión concreta: etiqueta, medida de pecho, cremallera, suela o accesorios juntos.","La página de tarifas usa actualmente CN¥3 en su ejemplo, pero el precio puede cambiar. La foto debe evitar un error más caro."]},
      {heading:"Tratar 1688 y artículos especiales con cautela",paragraphs:["Superbuy indica una norma QC distinta para 1688. Algunos electrónicos, tarjetas, modelos o productos sellados solo permiten revisión exterior.","Para artículos frágiles, personalizados, usados o técnicos, documenta preguntas más estrictas y límites de devolución antes de comprar."]},
      {heading:"Decidir pronto: aceptar, pedir o devolver",paragraphs:["Aceptar significa que las preguntas visibles quedaron resueltas. Pedir significa que una imagen puede cambiar la decisión; devolver requiere elegibilidad actual.","Las condiciones publicadas describen un marco de cinco días para productos elegibles, con límites. Comprueba de inmediato vendedor, categoría y opción posventa."]},
      {heading:"Una lista QC repetible",paragraphs:["Sigue identidad, cantidad, opción, medidas, construcción, superficie, contenido y riesgo específico de categoría.","Separa conocido y desconocido: color coincide, medida aceptable, material o duración sin confirmar. QC no equivale a certificación total."]},
      {heading:"Usar el almacenamiento como parte del QC",paragraphs:["Los 90 días gratis actuales dejan tiempo para más compras e inspección. Registra llegada, revisión, pregunta y decisión.","Prioriza posible devolución, medida ausente o anomalía. Al crear el paquete, cada artículo tendrá una razón documentada."]},
      {heading:"Evitar errores QC frecuentes",paragraphs:["Compara con el listado exacto, no con influencers u otros vendedores. La luz cambia el color; pide una foto clara si es decisivo.","No aceptes automáticamente porque ya está en el almacén. Investigar antes del envío internacional suele ser más barato."]}
    ],
    "shipping-cost-planning": [
      {heading:"Por qué el precio no predice el coste entregado",paragraphs:["Superbuy separa artículo, envío nacional y servicios del coste internacional posterior, calculado por peso final, línea y destino.","Una referencia USD no es precio entregado. Antes del almacén faltan dimensiones, peso verificado, elegibilidad y embalaje."]},
      {heading:"Entender depósito y ajuste final",paragraphs:["La guía calcula el depósito con peso estimado, método y destino. Después del embalaje, el transportista verifica tamaño y peso.","La diferencia se ajusta en la cuenta tras el envío. Guarda estimación y datos finales por separado."]},
      {heading:"Distinguir peso real y volumétrico",paragraphs:["El peso real viene de la báscula; el volumétrico cobra el espacio. Un paquete ligero y grande puede facturarse como más pesado.","Divisor y redondeo varían por línea. Retira embalaje solo tras comparar volumen, protección y valor de la caja."]},
      {heading:"Consolidar por compatibilidad, no por cantidad",paragraphs:["La consolidación gratuita puede reducir costes base y embalaje, pero también aumentar volumen, peso o restricciones.","Anota peso, dimensiones, fragilidad, baterías, líquidos y cajas. Compara al menos dos agrupaciones después de la llegada."]},
      {heading:"Comparar líneas elegibles, no tarifas publicitarias",paragraphs:["Superbuy anuncia 100+ líneas y 200+ países y regiones, pero cada paquete solo ve opciones compatibles con destino, atributos, peso y tamaño.","Compara el mismo día precio, rango, regla de peso, seguimiento, límites y seguro. No garantices tiempos de terceros o aduanas."]},
      {heading:"Elegir servicios de embalaje según la necesidad",paragraphs:["La guía menciona retirada, refuerzo y seguro. Cada servicio responde a un riesgo diferente.","La ropa suele requerir menos protección; lo frágil puede necesitar refuerzo. Lee condiciones, exclusiones y valor asegurado."]},
      {heading:"Tratar aduanas e impuestos según destino",paragraphs:["Aranceles e IVA dependen de destino, categoría y declaración. Las condiciones advierten de retraso, devolución o confiscación.","Comprueba reglas y restricciones actuales. Ninguna hoja puede garantizar honestamente entrega sin impuestos."]},
      {heading:"Planificar con tres estimaciones",paragraphs:["Usa estimación inicial, estimación de almacén y cotización real al enviar. Solo la última usa grupo y líneas actuales.","Separa envío nacional e internacional y añade servicios. El objetivo es mejorar los datos en cada etapa."]},
      {heading:"Lista final antes de enviar",paragraphs:["Confirma QC, dirección, agrupación y elegibilidad. Revisa peso real y volumétrico, embalaje, seguro y aduanas.","Guarda línea, cotización, fecha y seguimiento. Tras la entrega compara coste, tiempo y ajuste para mejorar el siguiente cálculo."]},
      {heading:"Evitar errores habituales de envío",paragraphs:["Evita importe fijo antes del almacén, línea más barata sin detalles, consolidación automática y fechas garantizadas.","Recalcula si cambian grupo, medidas o condiciones. Usa el calculador en vivo y lee las reglas antes de pagar."]}
    ]
  },
  it: {
    "spreadsheet-without-buying-blind": [
      {heading:"Un foglio è una selezione, non una promessa",paragraphs:["Un buon foglio Superbuy organizza prodotti dispersi e li rende controllabili. Non prova affidabilità del venditore, disponibilità, opzione attuale o prezzo permanente.","Il flusso ufficiale separa pagamento, spedizione nazionale, invio del venditore, controllo in magazzino e pacco internazionale. Il foglio deve registrare ogni decisione separatamente."]},
      {heading:"Registrare la decisione esatta prima del pagamento",paragraphs:["Accanto al link salva titolo, colore, taglia, quantità, testo dell’opzione, prezzo, spedizione nazionale e data. Per inserzioni miste descrivi anche la miniatura scelta.","Quando riapri, confronta immagine e opzioni con la nota. Se l’inserzione è cambiata o la variante è sparita, riporta la riga a «controllare»."],bullets:["Destinazione corrente e data","Nome esatto dell’opzione, colore, taglia e quantità","Prezzo e spedizione nazionale mostrata","Nota sulla corrispondenza dell’immagine","Una domanda per il controllo in magazzino"]},
      {heading:"Separare commissioni e prezzo del prodotto",paragraphs:["La pagina attuale indica acquisto standard gratuito su Taobao, Tmall, JD.com e 1688. Restano possibili prezzo, spedizione nazionale e servizi opzionali.","Non usare una sola colonna «costo finale». Separa articolo, consegna nazionale, opzioni e stima internazionale, perché i dati del pacco arrivano dopo."]},
      {heading:"Usare le foto di magazzino come nuove prove",paragraphs:["La pagina attuale indica tre foto QC gratuite dopo l’arrivo. Mostrano l’unità ricevuta e sono più pertinenti delle immagini promozionali.","Possono confermare colore, quantità, forma e danni visibili, ma non autenticità, materiale, comfort, durata o vestibilità. Superbuy segnala uno standard QC diverso per 1688."]},
      {heading:"Trasformare il QC in una decisione",paragraphs:["Prima dell’arrivo scrivi una domanda decisiva: suola, larghezza, posizione della stampa o completezza del set.","Dopo le foto scegli un’azione: accettare, chiedere un’immagine, chiarire un’anomalia, restituire se idoneo o attendere un altro articolo."]},
      {heading:"Usare consapevolmente i 90 giorni di deposito",paragraphs:["Superbuy indica 90 giorni gratuiti. La pagina tariffe aggiunge costo giornaliero per articolo, massimo standard di 180 giorni e servizio di estensione.","Registra arrivo e data obiettivo. Risolvi prima gli articoli più vecchi con dubbi QC o possibile restituzione."]},
      {heading:"Il consolidamento non fa sempre risparmiare",paragraphs:["Gli ordini idonei possono essere consolidati gratis e talvolta costare meno. Un pacco maggiore può attivare peso volumetrico, limiti o restrizioni.","Raggruppa per peso, misure, fragilità, batterie, liquidi e imballaggio. Confronta le linee realmente disponibili dopo l’arrivo."]},
      {heading:"Un sistema di stati evita acquisti sbagliati",paragraphs:["Usa stati come scoperta, inserzione verificata, opzione confermata, acquistato, transito nazionale, revisione, prova necessaria, pronto, inviato e chiuso.","Il modello minimo contiene stato link, immagine, opzione, prezzo e domanda QC. Prima del pagamento riapri la pagina e definisci l’azione successiva."]}
    ],
    "qc-photo-checklist": [
      {heading:"Cosa rappresentano davvero le foto QC",paragraphs:["Superbuy indica tre foto QC gratuite dopo l’arrivo in magazzino. La guida descrive ispezione, pubblicazione nell’account e contatto in caso di problemi.","Le immagini documentano identità, quantità, colore, forma, misure visibili e danni evidenti. Non provano autenticità, struttura interna, materiale o durata."]},
      {heading:"Controllare l’identità prima della qualità",paragraphs:["Inizia da tipo, colore, quantità e opzione, confrontati con inserzione e nota d’acquisto. Per coppie e set conferma tutti i pezzi.","Se l’opzione non è visibile, chiedi una foto mirata di etichetta, taglia, codice o accessori prima dei piccoli dettagli."],bullets:["Tipo e modello","Colore e variante visibile","Quantità, coppie e componenti","Etichetta taglia o indicatore opzione","Accessori dell’opzione scelta"]},
      {heading:"Confrontare le misure con un articolo proprio",paragraphs:["Le etichette variano. Confronta le misure di magazzino con un capo o una scarpa familiare misurata negli stessi punti.","Registra valore e punto di misura. Una larghezza piatta non è circonferenza; se manca una misura decisiva, chiedi una foto."]},
      {heading:"Controllare la costruzione per categoria",paragraphs:["Per l’abbigliamento osserva cuciture, fili, stampa, ricamo, simmetria, zip e macchie. Per le scarpe confronta coppia, suola, punta, colla e tallone.","Per borse e accessori controlla angoli, chiusure, cinghie e piccoli pezzi. Descrivi differenze visibili invece di giudizi vaghi."]},
      {heading:"Quando richiedere una foto dettagliata",paragraphs:["È utile se risponde a una decisione precisa: etichetta, misura torace, zip, suola o accessori insieme.","La pagina tariffe usa attualmente CN¥3 nel suo esempio, ma il prezzo può cambiare. La foto deve evitare un errore più costoso."]},
      {heading:"Trattare 1688 e articoli speciali con cautela",paragraphs:["Superbuy segnala uno standard QC diverso per 1688. Alcuni elettronici, carte, modelli o prodotti sigillati consentono solo controllo esterno.","Per articoli fragili, personalizzati, usati o tecnici, documenta domande più severe e limiti di reso prima dell’acquisto."]},
      {heading:"Decidere presto: accettare, chiedere o restituire",paragraphs:["Accettare significa che le domande visibili sono state risolte. Chiedere significa che una foto può cambiare la scelta; restituire richiede idoneità attuale.","Le condizioni pubblicate descrivono cinque giorni per prodotti idonei, con limiti. Controlla subito venditore, categoria e opzione post-vendita."]},
      {heading:"Una checklist QC ripetibile",paragraphs:["Segui identità, quantità, opzione, misure, costruzione, superficie, completezza e rischio specifico della categoria.","Separa noto e ignoto: colore corrisponde, misura accettabile, materiale o durata non confermati. QC non è certificazione totale."]},
      {heading:"Usare il deposito come parte del QC",paragraphs:["Gli attuali 90 giorni gratuiti lasciano tempo per altri acquisti e ispezione. Registra arrivo, revisione, domanda e decisione.","Dai priorità a possibile reso, misura mancante o anomalia. Alla creazione del pacco ogni articolo avrà una ragione documentata."]},
      {heading:"Evitare errori QC frequenti",paragraphs:["Confronta con l’inserzione esatta, non con influencer o altri venditori. La luce cambia il colore; chiedi una foto chiara se è decisivo.","Non accettare automaticamente perché è già in magazzino. Indagare prima della spedizione internazionale costa spesso meno."]}
    ],
    "shipping-cost-planning": [
      {heading:"Perché il prezzo non prevede il costo consegnato",paragraphs:["Superbuy separa articolo, spedizione nazionale e servizi dal successivo costo internazionale, calcolato su peso finale, linea e destinazione.","Un riferimento USD non è un prezzo consegnato. Prima del magazzino mancano dimensioni, peso verificato, idoneità e imballaggio."]},
      {heading:"Capire deposito e rettifica finale",paragraphs:["La guida calcola il deposito con peso stimato, metodo e destinazione. Dopo l’imballaggio, il vettore verifica dimensioni e peso.","La differenza viene regolata sull’account dopo l’invio. Conserva stima e dati finali separatamente."]},
      {heading:"Distinguere peso reale e volumetrico",paragraphs:["Il peso reale viene dalla bilancia; quello volumetrico addebita lo spazio. Un pacco leggero e grande può costare come uno più pesante.","Divisore e arrotondamento variano per linea. Rimuovi imballaggio solo dopo aver valutato volume, protezione e valore della scatola."]},
      {heading:"Consolidare per compatibilità, non quantità",paragraphs:["Il consolidamento gratuito può ridurre costi base e imballaggio, ma può aumentare volume, peso o restrizioni.","Annota peso, dimensioni, fragilità, batterie, liquidi e scatole. Confronta almeno due gruppi dopo l’arrivo."]},
      {heading:"Confrontare linee idonee, non tariffe pubblicitarie",paragraphs:["Superbuy indica 100+ linee e 200+ paesi e regioni, ma ogni pacco vede solo opzioni compatibili con destinazione, attributi, peso e misura.","Confronta nello stesso giorno prezzo, intervallo, regola di peso, tracking, limiti e assicurazione. Non garantire tempi di terzi o dogana."]},
      {heading:"Scegliere servizi di imballaggio secondo il bisogno",paragraphs:["La guida menziona rimozione, rinforzo e assicurazione. Ogni servizio risponde a un rischio diverso.","I tessili richiedono spesso poca protezione; il fragile può richiedere rinforzo. Leggi condizioni, esclusioni e valore assicurato."]},
      {heading:"Trattare dogana e tasse per destinazione",paragraphs:["Dazi e IVA dipendono da destinazione, categoria e dichiarazione. Le condizioni avvertono di ritardo, ritorno o confisca.","Controlla regole e restrizioni correnti. Nessun foglio può garantire onestamente consegna senza tasse."]},
      {heading:"Pianificare con tre stime",paragraphs:["Usa stima iniziale, stima di magazzino e quotazione reale all’invio. Solo l’ultima usa gruppo e linee correnti.","Separa spedizione nazionale e internazionale e aggiungi i servizi. L’obiettivo è migliorare i dati in ogni fase."]},
      {heading:"Checklist finale prima dell’invio",paragraphs:["Conferma QC, indirizzo, gruppo e idoneità. Controlla peso reale e volumetrico, imballaggio, assicurazione e dogana.","Salva linea, preventivo, data e tracking. Dopo la consegna confronta costo, tempo e rettifica per la prossima stima."]},
      {heading:"Evitare errori comuni di spedizione",paragraphs:["Evita importo fisso prima del magazzino, linea più economica senza dettagli, consolidamento automatico e date garantite.","Ricalcola se cambiano gruppo, misure o condizioni. Usa il calcolatore live e leggi le regole prima del pagamento."]}
    ]
  }
};

export const articleTranslations: Record<LocalArticleLang, Record<string, ArticleSection[]>> = Object.fromEntries(
  Object.entries(baseArticleTranslations).map(([language, articles]) => {
    const lang = language as LocalArticleLang;
    const completedArticles = Object.fromEntries(
      Object.entries(articleContent).map(([slug, englishSections]) => {
        const baseSections = articles[slug] || [];
        const localizedSections = slug === "spreadsheet-without-buying-blind"
          ? [...baseSections, missingSpreadsheetSection[lang]]
          : baseSections;
        const expansions = articleExpansions[lang][slug];

        const sections = englishSections.map((englishSection, index) => {
          const localized = localizedSections[index] || englishSection;
          const paragraphs = [...localized.paragraphs];
          const expansion = expansions[index];
          if (expansion && paragraphs.length) {
            paragraphs[paragraphs.length - 1] = `${paragraphs[paragraphs.length - 1]} ${expansion}`;
          }
          return {
            ...localized,
            paragraphs,
            bullets: localized.bullets || englishSection.bullets
          };
        });

        const finalSection = sections[sections.length - 1];
        const finalParagraph = finalSection?.paragraphs.length - 1;
        const closer = articleClosers[lang][slug];
        if (finalSection && finalParagraph >= 0 && closer) {
          finalSection.paragraphs[finalParagraph] = `${finalSection.paragraphs[finalParagraph]} ${closer}`;
        }

        return [slug, sections];
      })
    );
    return [lang, completedArticles];
  })
) as Record<LocalArticleLang, Record<string, ArticleSection[]>>;
