import type { ArticleSection } from "./article-content";

export type LocalArticleLang = "de" | "fr" | "es" | "it";

export const missingSpreadsheetSection: Record<LocalArticleLang, ArticleSection> = {
  de: {
    heading: "Die praktische Vorlage mit fünf Feldern",
    paragraphs: [
      "Für die kleinste brauchbare Version genügen neben jedem Produkt fünf Felder: aktueller Linkstatus, Bildabgleich, gewünschte Variante, aktuelle Preisreferenz und eine konkrete QC-Frage. Wenn die Auswahlliste wächst, kommen Prüfdatum und nächste Aktion hinzu.",
      "Die letzte Kontrolle erfolgt unmittelbar vor der Zahlung. Öffne das Ziel erneut, bestätige die exakte Variante, prüfe Artikelpreis und chinesische Inlandszustellung und lege fest, welche sichtbaren Nachweise du nach dem Lagereingang benötigst."
    ]
  },
  fr: {
    heading: "Le modèle pratique en cinq champs",
    paragraphs: [
      "Pour une version minimale réellement utile, conservez cinq champs à côté de chaque produit : état actuel du lien, correspondance de l’image, option souhaitée, prix de référence actuel et une question QC précise. Ajoutez la date de contrôle et l’action suivante lorsque la sélection grandit.",
      "Le dernier contrôle se fait juste avant le paiement : rouvrez la destination, confirmez l’option exacte, vérifiez le prix et la livraison intérieure en Chine, puis décidez quelle preuve visible devra être obtenue après l’arrivée à l’entrepôt."
    ]
  },
  es: {
    heading: "La plantilla práctica de cinco campos",
    paragraphs: [
      "Para una versión mínima que siga siendo útil, conserva cinco campos junto a cada producto: estado actual del enlace, coincidencia de imagen, opción prevista, precio de referencia actual y una pregunta QC concreta. Añade fecha de revisión y siguiente acción cuando crezca la selección.",
      "La última comprobación se realiza justo antes de pagar: abre de nuevo el destino, confirma la variante exacta, revisa el precio y el envío nacional en China, y decide qué prueba visible necesitarás después de la llegada al almacén."
    ]
  },
  it: {
    heading: "Il modello pratico a cinque campi",
    paragraphs: [
      "Per una versione minima ma davvero utile, conserva cinque campi accanto a ogni prodotto: stato attuale del link, corrispondenza dell’immagine, opzione prevista, prezzo di riferimento corrente e una domanda QC precisa. Aggiungi data di controllo e azione successiva quando la selezione cresce.",
      "L’ultimo controllo avviene subito prima del pagamento: riapri la destinazione, conferma la variante esatta, verifica prezzo e consegna nazionale in Cina e stabilisci quale prova visibile servirà dopo l’arrivo in magazzino."
    ]
  }
};

export const articleExpansions: Record<LocalArticleLang, Record<string, string[]>> = {
  de: {
    "spreadsheet-without-buying-blind": [
      "Für die Praxis bedeutet das: Eine Zeile darf nur das behaupten, was am eingetragenen Datum tatsächlich geprüft wurde. Ein erreichbarer Link bestätigt weder Bestand noch Verkäuferleistung. Notiere deshalb neben der Quelle immer die offene Frage und die nächste Prüfstufe. So bleibt die Tabelle auch Wochen später verständlich und verhindert, dass eine alte Momentaufnahme wie eine dauerhafte Empfehlung behandelt wird. Genau diese Trennung zwischen Fund, Bestellung, Lagerbeleg und Versandentscheidung macht die Recherche belastbar.",
      "Besonders bei Sammelangeboten kann derselbe Link viele Farben, Größen oder völlig unterschiedliche Artikel enthalten. Ein Screenshot der gewählten Miniatur und der genaue Optionswortlaut schaffen eine nachvollziehbare Referenz. Werden Preis oder Variante später verändert, lässt sich die Abweichung sofort erkennen. Vor der Zahlung sollte außerdem geprüft werden, ob der angezeigte Inlandsversand für Menge und Ziel noch gilt. Erst danach erhält die Zeile den Status „Option bestätigt“; zuvor bleibt sie eine zu prüfende Entdeckung.",
      "Diese Aufteilung verhindert, dass ein niedriger Artikelpreis einen falschen Eindruck vom Gesamtbudget erzeugt. Die kostenlose Standardbeschaffung ist eine bestimmte Serviceaussage und keine Zusage kostenloser Lieferung. Bei Sonderbeschaffung, Gebrauchtwaren oder Zusatzleistungen können andere Regeln gelten. Halte deshalb Betrag, Währung, Prüfdatum und Kostenart getrennt fest. Die spätere internationale Schätzung sollte niemals rückwirkend als Produkteigenschaft erscheinen, denn sie hängt vom tatsächlichen Paket und den zu diesem Zeitpunkt verfügbaren Linien ab.",
      "Bei der Auswertung hilft eine Beweistabelle mit drei Spalten: sichtbar bestätigt, auf dem Foto unklar und fotografisch nicht prüfbar. Ein korrektes Farbbild kann zum Beispiel die Variante stützen, während Material oder Komfort offenbleiben. Wenn eine Messung kaufentscheidend ist, sollte die Anfrage den Messpunkt genau benennen. Fotos sind damit keine Dekoration, sondern ein neuer Datensatz nach Wareneingang. Die Tabellenzeile wird erst nach dieser Prüfung aktualisiert und behält die ursprüngliche Annahme für den Vergleich.",
      "Eine gute Entscheidung nennt sowohl Beobachtung als auch Konsequenz: etwa „Größenetikett sichtbar, Brustmaß fehlt – Detailfoto anfordern“. Dadurch kann eine zweite Person die Entscheidung nachvollziehen. Priorisiere Fragen, die eine Rückgabe oder die Paketbildung verändern würden, statt beliebig viele Nahaufnahmen zu sammeln. Speichere Antwortdatum und Ergebnis. Sobald die nötige Information vorliegt, wird die Zeile eindeutig auf akzeptieren, nachfragen, gegebenenfalls Rückgabe beantragen oder bis zum Eintreffen weiterer Artikel warten gesetzt.",
      "Rechne intern nicht nur mit dem kostenlosen Zeitraum, sondern mit einem früheren persönlichen Stichtag. Dieser Puffer lässt Zeit für Detailbilder, Kommunikation, mögliche Rückgabe und erneute Paketplanung. Sortiere die Tabelle nach Lagereingang, damit der älteste Artikel sichtbar bleibt. Falls eine Verlängerung nötig sein könnte, prüfe Preis und Verfügbarkeit im aktuellen Konto rechtzeitig. Die veröffentlichten 90 und 180 Tage sind Planungsdaten, ersetzen aber keine Kontrolle des konkreten Auftragsstatus und der jeweils gültigen Bedingungen.",
      "Ein sinnvoller Vergleich testet mindestens zwei Paketgruppen: alles zusammen und eine Aufteilung nach Einschränkung oder Volumen. Entfernte Schuhkartons können Volumen senken, aber Schutz oder Wiederverkaufswert verändern. Batterien, Flüssigkeiten, empfindliche Teile und bestimmte Produktmerkmale können die Routenauswahl einschränken. Trage daher nicht pauschal „konsolidieren“ ein, sondern die Annahmen hinter der Gruppierung. Erst Lagergewicht, Maße und verfügbare Versandoptionen zeigen, ob Zusammenlegen tatsächlich Kosten oder nur Verwaltungsschritte reduziert.",
      "Statuswerte funktionieren nur, wenn jeder Nutzer dieselbe Definition verwendet. Ergänze deshalb eine kleine Legende und erlaube keinen Sprung von „gefunden“ direkt zu „versandbereit“. Jede Änderung braucht Datum und möglichst einen kurzen Grund. Abgelaufene Preis- oder Routenprüfungen werden automatisch wieder offen. So verhindert die Tabelle versehentliche Bestellungen aus veralteten Favoritenlisten und liefert zugleich eine ehrliche Historie: was bekannt war, was später durch Lagerfotos bestätigt wurde und warum eine bestimmte Paketentscheidung getroffen wurde.",
      "Diese fünf Felder sind bewusst kompakt, decken aber den gesamten Entscheidungsweg ab. Wer mehr Detail benötigt, ergänzt Verkäufernotiz, Inlandsversand, Lagerdatum, Gewicht, Maße und Paketgruppe, ohne die Kernlogik zu verändern. Verwende einheitliche Formate für Datum und Währung und verlinke immer auf die aktuell überprüfbare Zielseite. Die Vorlage soll keine Live-Daten vortäuschen; sie soll deutlich zeigen, wann ein Wert zuletzt kontrolliert wurde und welche Handlung als Nächstes erforderlich ist."
    ],
    "qc-photo-checklist": [
      "Der wichtigste Grundsatz lautet deshalb: QC ist eine Sichtprüfung mit begrenztem Umfang. Formuliere vorab eine Frage, die ein Foto tatsächlich beantworten kann, und vermeide Aussagen über Echtheit oder Haltbarkeit, wenn dafür kein Nachweis existiert. Vergleiche immer mit der beim Kauf gespeicherten Variante, nicht mit einem beliebigen Werbebild. Werden Abweichungen entdeckt, dokumentiere das konkrete Merkmal, die betroffene Ansicht und den Zeitpunkt, damit die spätere Anfrage oder Rückgabeentscheidung nachvollziehbar bleibt.",
      "Arbeite in einer festen Reihenfolge und hake zuerst grobe Identitätsmerkmale ab. Bei einem Set gehören Anzahl und Zubehör genauso zur Identität wie Farbe oder Größe. Erst wenn diese Punkte passen, lohnt sich die Prüfung von Nähten, Drucken oder kleinen Oberflächenfehlern. Fehlt eine Kennzeichnung, sollte die Detailfoto-Anfrage genau sagen, welches Etikett vollständig lesbar sein muss. Das spart Zeit und verhindert, dass eine technisch gute Aufnahme am falschen Teil die eigentliche Unsicherheit nicht löst.",
      "Lege das eigene Vergleichsstück flach und miss es mit derselben Linienführung wie auf dem angeforderten Lagerfoto. Notiere bei jeder Zahl, ob sie Breite, Umfang oder gerade Länge bezeichnet. Kleine Abweichungen können durch Stoffspannung oder Kamerawinkel entstehen; entscheide deshalb vorher, welcher Toleranzbereich akzeptabel ist. Bei Schuhen kann eine Einlegesohlenlänge hilfreicher sein als die gedruckte Größe. Eine Messung ist erst dann nützlich, wenn Methode, Einheit und Entscheidungsschwelle gemeinsam dokumentiert sind.",
      "Erstelle je Kategorie eine kurze Fehlerliste, statt alle Produkte gleich zu beurteilen. Kleidung braucht andere Blickpunkte als Schuhe, Taschen oder empfindliches Zubehör. Prüfe beide Seiten eines Paars, symmetrische Bauteile und belastete Befestigungspunkte miteinander. Lichtreflexe oder Falten in der Verpackung sind noch kein Mangel; offene Nähte, fehlende Teile oder deutlich unterschiedliche Formen sind konkrete Beobachtungen. Beschreibe Position und Ausmaß, damit die nächste Kommunikation nicht nur aus dem unklaren Wort „Qualität“ besteht.",
      "Eine präzise Fotoanfrage enthält Motiv, Perspektive und Zweck. Statt „mehr Details“ lautet sie beispielsweise: „Größenetikett frontal und vollständig lesbar fotografieren, um die bestellte Variante abzugleichen“. Prüfe vor dem Buchen den aktuell angezeigten Preis der Zusatzleistung und ob die Verpackung geöffnet werden darf. Der wirtschaftliche Maßstab ist der mögliche vermiedene Fehler: Ein gezieltes Bild kann sinnvoll sein, wenn es über Rückgabe, Paketaufnahme oder eine teure internationale Sendung entscheidet.",
      "Bei Sonderartikeln sollte die Risikonotiz bereits vor dem Kauf angelegt werden. Halte fest, welche Funktion nicht geprüft werden kann, ob die Originalverpackung geschlossen bleiben muss und ob der Verkäufer Rückgaben ausschließt. Für 1688 gilt laut Superbuy ein abweichender QC-Standard; daher darf derselbe Status nicht automatisch dieselbe Prüftiefe bedeuten. Elektronik, Sammlerstücke, Modelle und kundenspezifische Ware verlangen oft sichtbare Vollständigkeitskontrollen, können aber Funktions- oder Echtheitsfragen offenlassen. Diese Grenzen gehören sichtbar in die Entscheidung.",
      "Kontrolliere das Datum der Lagerbenachrichtigung und öffne die aktuelle After-Sales-Funktion sofort, wenn ein Problem relevant ist. Das veröffentlichte Fünf-Tage-Rahmenwerk gilt nur für berechtigte Käufe und enthält Ausnahmen; es ist keine pauschale Garantie. Sichere die betreffende Ansicht, beschreibe Abweichung und gewünschte Lösung sachlich. Warte nicht auf die spätere Paketbildung. Je früher die Entscheidung fällt, desto eher kann noch zwischen zusätzlichem Nachweis, Verkäuferklärung, möglicher Rückgabe oder akzeptiertem Versand gewählt werden.",
      "Damit die Checkliste wiederholbar bleibt, erhält jeder Prüfpunkt nur drei mögliche Ergebnisse: bestätigt, unklar oder nicht fotografisch prüfbar. Ergänze bei „unklar“ die nächste konkrete Aktion. So wird ein grüner Gesamtstatus nicht aus fehlenden Daten abgeleitet. Bewahre die ursprüngliche Listing-Notiz zusammen mit den Lagerergebnissen auf und trenne sichtbare Fakten von Interpretation. Diese Methode macht unterschiedliche Produkte vergleichbar, ohne so zu tun, als könne eine Standardaufnahme Material, Funktion und langfristige Nutzung vollständig zertifizieren.",
      "Nutze den Lagerzeitraum als Arbeitsplan, nicht als Wartezone. Eine Wochenübersicht zeigt neu eingetroffene Artikel, offene Fotoanfragen, mögliche Rückgaben und bereits freigegebene Positionen. Ältere oder fristkritische Fälle stehen oben. Wenn mehrere Einkäufe zusammen versendet werden sollen, darf kein einzelner ungeklärter Artikel die gesamte Gruppe unbemerkt verzögern. Ein dokumentierter Abschluss pro Artikel erleichtert später die Paketwahl und verhindert hektische Entscheidungen kurz vor Ablauf von Lager- oder After-Sales-Fristen.",
      "Zwei Gegenprüfungen helfen besonders: Passt die Aufnahme wirklich zur bestellten Listing-Variante, und würde die beobachtete Abweichung die eigene Entscheidung verändern? Bei Farbfragen sollten mehrere Ansichten und die Beleuchtung berücksichtigt werden. Bei vermeintlichen Schäden muss zwischen Verpackung, Staub, Falte und Produktfehler unterschieden werden. Akzeptiere umgekehrt nichts nur wegen bereits investierter Zeit. Ein sachliches Evidenzprotokoll vor internationalem Versand ist meist günstiger als eine ungelöste Überraschung nach der Zustellung."
    ],
    "shipping-cost-planning": [
      "Für die Budgetplanung werden deshalb Produktentscheidung und Paketentscheidung getrennt. Die frühe Tabelle darf einen Planungskorridor enthalten, aber keine scheinbar genaue Endsumme. Kennzeichne Annahmen zu Gewicht, Abmessungen, Route und Wechselkurs ausdrücklich. Sobald Lagerdaten vorliegen, ersetzt du diese Werte durch gemessene Angaben. Eventuelle Einfuhrkosten bleiben eine eigene destinationsabhängige Position. So kann der Leser erkennen, welcher Betrag aktuell beobachtet, welcher geschätzt und welcher erst nach Paketbildung bestimmbar ist.",
      "Speichere sowohl den hinterlegten Betrag als auch die endgültige Abrechnung, statt nur die Differenz zu überschreiben. Notiere dazu Datum, gewählte Linie, geschätztes und bestätigtes Gewicht sowie die gemeldeten Maße. Nur so lässt sich später beurteilen, ob eine Abweichung durch Verpackung, Volumengewicht, Rundungsregel oder Routentausch entstand. Eine einzelne Erstattung ist keine allgemeine Versandformel. Sie beschreibt nur die Abrechnung dieses konkreten Pakets nach der Überprüfung durch den Transportdienstleister.",
      "Berechne das Volumengewicht ausschließlich mit dem für die konkrete Linie veröffentlichten Divisor und den dort geltenden Rundungsregeln. Ein Beispiel aus einer anderen Route kann irreführen. Teste vor der Einreichung, wie Kartonentfernung, Vakuumierung oder Aufteilung die Maße verändern könnten, und stelle dem möglichen Preisvorteil den Schutzbedarf gegenüber. Dokumentiere tatsächliches Gewicht und drei Außenmaße getrennt. Der höhere abrechnungsrelevante Wert entscheidet häufig, doch die jeweils angezeigte Routenregel bleibt maßgeblich.",
      "Eine kompatible Gruppe berücksichtigt nicht nur Gewicht, sondern auch Größe, Zerbrechlichkeit, Produktattribute und gewünschten Schutz. Erstelle vorab zwei oder drei Szenarien und vergleiche nach Lagereingang die dafür real verfügbaren Linien. Ein kleines eingeschränktes Teil kann die Optionen eines großen Standardpakets reduzieren. Umgekehrt können zwei Sendungen doppelte Grundkosten erzeugen. Die Tabelle soll diese Zielkonflikte sichtbar machen und die Entscheidung mit aktuellen Paketdaten begründen, statt Konsolidierung als automatische Sparfunktion zu präsentieren.",
      "Vergleiche Routen immer für denselben Warenkorb, dasselbe Ziel und möglichst denselben Zeitpunkt. Neben dem Preis gehören Gewichtsintervall, Volumenregel, Tracking, Laufzeitspanne, Versicherung, Größenlimit und Produkteinschränkungen in die Zeile. Die Zahl der allgemein beworbenen Linien sagt nicht, welche Optionen dieses Paket tatsächlich erhält. Vermeide garantierte Zustelldaten, weil Übergaben, Zoll und lokale Zustellung außerhalb einer einfachen Kalkulation liegen. Entscheidend ist die aktuelle Auswahl im Paketformular samt vollständiger Bedingungen.",
      "Jede Zusatzverpackung sollte einem benannten Risiko zugeordnet werden. Kantenschutz oder Verstärkung kann für Zerbrechliches sinnvoll sein, während unnötiges Material Gewicht und Volumen erhöht. Das Entfernen von Schuh- oder Produktkartons spart möglicherweise Platz, verändert aber Schutz und Aufbewahrungswert. Prüfe auch Versicherungsumfang, Ausschlüsse und Wertgrenzen statt nur den Aufpreis. Halte die gewählte Maßnahme und den Grund fest; so lässt sich nach der Zustellung beurteilen, ob sie beim nächsten Paket wieder sinnvoll ist.",
      "Erstelle für das Zielland eine eigene Prüfreihe mit Warenart, deklarierter Beschreibung, möglicher Steuer, Dokumentenbedarf und verbotenen oder eingeschränkten Eigenschaften. Verlasse dich nicht auf Erfahrungsberichte aus einem anderen Land oder auf eine pauschale „tax free“-Aussage. Vorschriften und Behördenentscheidungen können sich ändern. Nutze offizielle Zollinformationen und die aktuellen Routenbedingungen, mache ehrliche Angaben und plane einen finanziellen sowie zeitlichen Puffer. Keine Tabelle kann eine kontrollfreie oder abgabenfreie Zustellung garantieren.",
      "Die erste Schätzung dient nur der Kaufplanung, die zweite nutzt Lagergewicht und Maße, und die dritte ist das aktuelle Angebot bei der tatsächlichen Paketeinreichung. Speichere alle drei mit Datum und Annahmen, statt frühere Werte zu löschen. So wird sichtbar, an welcher Stelle die Prognose besser oder schlechter wurde. Ergänze Produktkosten, chinesische Inlandszustellung und optionale Dienste getrennt. Eine lernende Historie ist wertvoller als eine einzelne Endzahl ohne Erklärung.",
      "Vor dem Absenden sollte jede Position einen abgeschlossenen QC-Status besitzen. Prüfe Empfängeradresse, Telefonnummer, Artikelgruppe, Einschränkungen, Gewicht, Maße, Verpackungswunsch, Versicherung und Zollerklärung in einer festen Reihenfolge. Vergleiche mindestens die passenden Routen, nicht nur die zuerst angezeigte. Speichere anschließend Linie, Angebot, Datum und Tracking. Nach Zustellung werden endgültige Belastung, Anpassung und tatsächliche Laufzeit ergänzt; damit liefert das Paket verwertbare Daten für die nächste Planung.",
      "Typische Fehler entstehen durch falsche Sicherheit: ein pauschaler Kilopreis, ein altes Screenshot-Angebot, die billigste Überschrift ohne Detailregeln oder eine garantierte Ankunftszeit. Rechne erneut, sobald sich Gruppe, Verpackung, Maße, Ziel oder Produktattribute ändern. Trenne Plattformangaben von Erfahrungen einzelner Nutzer und kennzeichne jede Beobachtung mit Datum. Die zuverlässigste Planung bleibt ein gestufter Prozess, der die Live-Kalkulation kurz vor Zahlung überprüft und Unsicherheiten offen ausweist."
    ]
  },
  fr: {
    "spreadsheet-without-buying-blind": [
      "En pratique, une ligne ne doit affirmer que ce qui a réellement été contrôlé à la date indiquée. Un lien actif ne confirme ni le stock ni la fiabilité du vendeur. Ajoutez donc la question encore ouverte et l’étape de vérification suivante. La feuille reste ainsi compréhensible plusieurs semaines plus tard et une ancienne capture n’est pas transformée en recommandation permanente. Séparer découverte, achat, preuve d’entrepôt et décision d’expédition rend la recherche beaucoup plus fiable.",
      "Les annonces regroupées peuvent proposer sous un même lien des couleurs, tailles et même des articles sans rapport. Enregistrez la miniature choisie et le libellé exact de l’option. Une modification ultérieure devient immédiatement visible. Avant de payer, vérifiez aussi que la livraison intérieure affichée correspond toujours à la quantité et à la destination. La ligne ne passe à « option confirmée » qu’après ce contrôle ; auparavant, elle reste une découverte qui demande une validation actuelle.",
      "Cette séparation évite qu’un prix d’article faible crée une fausse impression du budget total. Le service d’achat standard gratuit est une règle de service précise, pas une promesse de livraison gratuite. Les achats spéciaux, les produits d’occasion et les options payantes peuvent suivre d’autres règles. Notez montant, devise, date et nature du coût dans des champs distincts. L’estimation internationale dépend du colis réel et des lignes disponibles plus tard ; elle ne doit jamais être présentée comme une propriété fixe du produit.",
      "Pour analyser les images, utilisez trois colonnes : confirmé visuellement, incertain sur la photo et impossible à prouver par une photo. La couleur peut être visible alors que la matière et le confort restent inconnus. Si une mesure influence l’achat, la demande doit nommer exactement le point à mesurer. Les photos deviennent ainsi un nouveau jeu de données après réception, pas une décoration. Conservez l’hypothèse initiale afin de pouvoir la comparer avec la preuve reçue.",
      "Une bonne décision associe observation et conséquence, par exemple : « étiquette visible, largeur manquante — demander une photo détaillée ». Une autre personne peut alors comprendre le raisonnement. Donnez la priorité aux questions susceptibles de modifier un retour ou la composition du colis, plutôt qu’à une accumulation d’images. Notez la date de réponse et concluez clairement : accepter, demander une preuve, signaler l’anomalie, solliciter un retour si possible ou attendre un autre article.",
      "Fixez une échéance personnelle antérieure à la fin de la période gratuite. Cette marge laisse du temps pour une photo supplémentaire, un échange avec le vendeur, un éventuel retour et une nouvelle organisation du colis. Triez la feuille par date d’arrivée afin que le produit le plus ancien reste visible. Si une prolongation peut être nécessaire, contrôlez assez tôt son prix et sa disponibilité dans le compte. Les limites publiées servent à planifier, mais l’état réel de chaque commande reste prioritaire.",
      "Une comparaison sérieuse teste au moins deux groupes : tout réunir et séparer selon les restrictions ou le volume. Retirer des boîtes peut réduire la taille, mais aussi modifier la protection et la valeur de conservation. Batteries, liquides, pièces fragiles et certains attributs limitent parfois les routes. N’écrivez donc pas simplement « consolider » : notez les hypothèses du regroupement. Seuls le poids, les dimensions et les choix réellement affichés après réception permettent de savoir si la consolidation réduit le coût.",
      "Les statuts ne sont utiles que si leur définition reste identique pour tous. Ajoutez une courte légende et interdisez le passage direct de « trouvé » à « prêt à expédier ». Chaque changement reçoit une date et une raison. Un ancien contrôle de prix ou de route redevient ouvert. La feuille évite alors les achats accidentels depuis de vieux favoris et conserve un historique honnête : ce qui était connu, ce que les photos ont confirmé et pourquoi le colis a été organisé de cette manière.",
      "Ces cinq champs restent volontairement compacts tout en couvrant le parcours de décision. Pour davantage de détail, ajoutez vendeur, livraison intérieure, date d’entrepôt, poids, dimensions et groupe de colis sans modifier la logique centrale. Utilisez des formats cohérents pour la date et la devise, et gardez une destination contrôlable. Le modèle ne doit pas simuler des données en direct : il doit montrer quand chaque valeur a été vérifiée et quelle action précise doit suivre."
    ],
    "qc-photo-checklist": [
      "Le principe central est simple : le QC est un contrôle visuel limité. Formulez avant l’arrivée une question qu’une image peut réellement résoudre et évitez toute conclusion sur l’authenticité ou la durée de vie sans preuve adaptée. Comparez toujours avec l’option exacte enregistrée lors de l’achat. En cas d’écart, notez le détail observable, la vue concernée et la date. Cette trace rend une demande complémentaire ou une décision de retour beaucoup plus claire.",
      "Suivez toujours le même ordre et commencez par l’identité générale. Dans un ensemble, le nombre de pièces et les accessoires font partie de l’identité autant que la couleur ou la taille. Les coutures et petits défauts viennent ensuite. Si un marquage manque, précisez dans la demande quelle étiquette doit être entièrement lisible. Une photo techniquement nette du mauvais endroit ne résout rien ; une consigne ciblée économise du temps et évite une nouvelle demande inutile.",
      "Mesurez votre propre article à plat avec la même méthode que celle demandée à l’entrepôt. Pour chaque valeur, indiquez largeur, circonférence ou longueur droite. L’angle de l’appareil et la tension du tissu peuvent produire une petite variation ; définissez donc une tolérance avant de voir le résultat. Pour une chaussure, la longueur de semelle intérieure peut être plus utile que la pointure imprimée. Une mesure n’est exploitable que si méthode, unité et seuil de décision sont enregistrés ensemble.",
      "Créez une courte liste de risques par catégorie au lieu d’évaluer tous les produits de la même façon. Vêtement, chaussure, sac et accessoire fragile exigent des points de vue différents. Comparez les deux côtés d’une paire, les éléments symétriques et les attaches soumises à l’effort. Un reflet ou un pli d’emballage n’est pas automatiquement un défaut ; une couture ouverte, une pièce absente ou deux formes nettement différentes sont des observations concrètes. Décrivez emplacement et importance.",
      "Une demande précise indique le sujet, l’angle et l’objectif : par exemple, photographier l’étiquette de taille de face et en entier pour vérifier l’option commandée. Contrôlez le prix actuel du service et la possibilité d’ouvrir l’emballage. La bonne comparaison n’est pas seulement le coût de la photo, mais l’erreur qu’elle peut éviter. Une image ciblée est rationnelle lorsqu’elle décide d’un retour, de l’intégration au colis ou d’un envoi international coûteux.",
      "Pour un article spécial, créez la note de risque avant le paiement. Indiquez les fonctions impossibles à tester, l’obligation éventuelle de garder l’emballage fermé et les limites de retour du vendeur. Superbuy précise que 1688 suit un standard QC différent ; un même statut ne signifie donc pas toujours la même profondeur de contrôle. Électronique, objets de collection, modèles et produits personnalisés peuvent permettre une vérification de présence, tout en laissant fonction et authenticité inconnues.",
      "Vérifiez la date de notification d’arrivée et ouvrez immédiatement l’option après-vente lorsqu’un défaut compte. Le cadre publié de cinq jours concerne les achats admissibles et comporte des exceptions ; ce n’est pas une garantie universelle. Conservez la vue pertinente, décrivez l’écart et la solution souhaitée. N’attendez pas la création du colis. Une décision rapide laisse encore le choix entre preuve supplémentaire, clarification du vendeur, demande de retour possible ou acceptation éclairée.",
      "Pour rendre la méthode reproductible, donnez à chaque contrôle trois résultats possibles : confirmé, incertain ou non vérifiable par photo. Pour « incertain », ajoutez l’action suivante. Un statut vert ne doit jamais résulter d’une absence de données. Conservez la note du listing avec les résultats d’entrepôt et séparez fait visible et interprétation. Des produits différents deviennent comparables sans prétendre qu’une image standard peut certifier la matière, le fonctionnement et l’usage à long terme.",
      "Transformez le stockage en calendrier de travail. Une vue hebdomadaire montre les nouvelles arrivées, demandes de photos ouvertes, retours possibles et articles déjà approuvés. Les cas anciens ou soumis à une échéance passent en premier. Si plusieurs achats doivent voyager ensemble, un seul article non résolu ne doit pas bloquer silencieusement le groupe. Une conclusion documentée pour chaque produit facilite ensuite le choix du colis et évite les décisions précipitées à l’approche des délais.",
      "Deux questions finales sont particulièrement utiles : l’image correspond-elle vraiment à la variante achetée, et l’écart observé changerait-il votre décision ? Pour une couleur, examinez plusieurs vues et l’éclairage. Pour un dommage supposé, distinguez emballage, poussière, pli et défaut réel. À l’inverse, n’acceptez pas un produit uniquement parce que du temps a déjà été investi. Un journal de preuves avant l’expédition internationale coûte généralement moins cher qu’une surprise non résolue après livraison."
    ],
    "shipping-cost-planning": [
      "Séparez donc décision d’achat et décision de colis. La feuille initiale peut montrer une fourchette de planification, jamais un total final faussement précis. Identifiez clairement les hypothèses de poids, dimensions, route et taux de change. Remplacez-les par les mesures d’entrepôt dès qu’elles existent. Les éventuels frais d’importation restent une ligne distincte liée à la destination. Le lecteur voit ainsi ce qui est observé, ce qui est estimé et ce qui ne sera calculable qu’après la formation du colis.",
      "Conservez le dépôt et le règlement final au lieu d’écraser la première valeur. Ajoutez date, ligne choisie, poids estimé, poids confirmé et dimensions déclarées. Cette comparaison permet d’expliquer une différence par l’emballage, le poids volumétrique, l’arrondi ou un changement de route. Un remboursement observé sur un colis ne devient pas une formule universelle. Il décrit seulement l’ajustement de cet envoi précis après la vérification du transporteur.",
      "Calculez le poids volumétrique avec le diviseur et les règles d’arrondi publiés pour la ligne choisie, jamais avec un exemple provenant d’une autre route. Testez l’effet possible du retrait des boîtes, de la compression ou de la séparation, puis opposez l’économie au besoin de protection. Enregistrez poids réel et trois dimensions extérieures séparément. La valeur facturable la plus élevée est souvent déterminante, mais la règle affichée au moment du choix reste la référence.",
      "Un groupe compatible tient compte du poids, du volume, de la fragilité, des attributs et de la protection souhaitée. Préparez deux ou trois scénarios, puis comparez les lignes réellement disponibles après l’arrivée. Un petit produit restreint peut réduire les options du grand colis ; deux envois peuvent au contraire doubler certains frais de base. La feuille doit rendre ce compromis visible et justifier le choix avec les données actuelles, plutôt que de présenter la consolidation comme une économie automatique.",
      "Comparez les routes pour le même contenu, la même destination et au même moment. Outre le prix, notez tranche de poids, formule volumétrique, suivi, délai indicatif, assurance, limites de taille et restrictions de produit. Le nombre de lignes annoncé globalement ne dit pas lesquelles accepteront ce colis. Évitez les dates garanties, car transferts, douane et livraison locale restent variables. La référence utile est la sélection actuelle du formulaire de colis avec ses conditions complètes.",
      "Associez chaque option d’emballage à un risque nommé. Renforcement et protection des angles peuvent aider un article fragile, tandis qu’un matériau inutile augmente poids et volume. Retirer une boîte de chaussures économise parfois de la place mais modifie protection et valeur de conservation. Lisez aussi plafond, exclusions et base d’indemnisation de l’assurance. Notez le service choisi et sa raison ; après réception, vous pourrez juger objectivement s’il mérite d’être utilisé à nouveau.",
      "Créez une vérification propre au pays de destination : type de marchandise, description déclarée, taxe possible, documents et caractéristiques interdites ou limitées. Ne transposez pas un témoignage provenant d’un autre pays et méfiez-vous d’une promesse générale « sans taxe ». Les règles et décisions administratives changent. Consultez les informations douanières officielles et les conditions actuelles de la route, déclarez honnêtement et prévoyez une marge financière et temporelle. Aucune feuille ne peut garantir l’absence de contrôle ou de prélèvement.",
      "La première estimation sert à décider l’achat, la deuxième utilise poids et dimensions d’entrepôt, la troisième correspond au devis actuel lors de la soumission. Gardez les trois valeurs avec date et hypothèses au lieu de supprimer les anciennes. Vous verrez où la prévision s’améliore. Ajoutez séparément produit, livraison intérieure et services optionnels. Un historique qui apprend de chaque colis est plus utile qu’un chiffre final isolé sans contexte.",
      "Avant l’envoi, chaque produit doit avoir un résultat QC terminé. Vérifiez dans un ordre fixe adresse, téléphone, groupe, restrictions, poids, dimensions, emballage, assurance et déclaration. Comparez toutes les routes adaptées, pas seulement la première affichée. Enregistrez ensuite ligne, devis, date et suivi. Après livraison, ajoutez montant final, ajustement et durée réelle. Le colis devient alors une source de données concrète pour améliorer la prochaine estimation.",
      "Les erreurs courantes viennent d’une précision imaginaire : prix fixe au kilo, ancienne capture, tarif principal sans règles ou arrivée garantie. Recalculez dès que groupe, emballage, dimensions, destination ou attributs changent. Séparez les informations de la plateforme des expériences individuelles et datez chaque observation. La planification la plus fiable reste progressive : elle contrôle le calculateur en direct juste avant le paiement et montre clairement les incertitudes encore présentes."
    ]
  },
  es: {
    "spreadsheet-without-buying-blind": [
      "En la práctica, una fila solo debe afirmar lo que se comprobó realmente en la fecha indicada. Un enlace activo no confirma existencias ni rendimiento del vendedor. Añade siempre la pregunta abierta y el siguiente paso de verificación. Así, semanas después, la hoja sigue siendo comprensible y una captura antigua no se convierte en recomendación permanente. Separar hallazgo, compra, evidencia de almacén y decisión de envío hace que la investigación sea mucho más sólida.",
      "Los listados combinados pueden incluir bajo un mismo enlace colores, tallas e incluso artículos distintos. Guarda la miniatura y el texto exacto de la opción elegida. Cualquier cambio posterior será reconocible. Antes de pagar, comprueba además que el envío nacional mostrado sigue correspondiendo a la cantidad y destino. La fila solo pasa a «opción confirmada» después de esa revisión; hasta entonces continúa siendo un descubrimiento pendiente de validación actual.",
      "Separar conceptos evita que un precio bajo del artículo cree una impresión falsa del presupuesto total. La compra estándar gratuita es una regla concreta del servicio, no una promesa de entrega gratuita. Compras especiales, segunda mano y servicios adicionales pueden tener condiciones diferentes. Registra importe, moneda, fecha y tipo de coste por separado. La estimación internacional depende del paquete real y de las líneas disponibles más adelante, por lo que nunca debe presentarse como característica fija del producto.",
      "Para revisar imágenes usa tres columnas: confirmado visualmente, poco claro en la foto e imposible de probar mediante fotografía. El color puede quedar respaldado mientras material y comodidad siguen sin respuesta. Si una medida decide la compra, la solicitud debe nombrar exactamente el punto de medición. Las fotos se convierten así en nuevos datos tras la recepción, no en decoración. Conserva la expectativa original para compararla con la evidencia que llega al almacén.",
      "Una buena decisión une observación y consecuencia: por ejemplo, «etiqueta visible, falta ancho de pecho; pedir foto detallada». Otra persona puede entender el razonamiento. Prioriza preguntas que podrían cambiar una devolución o la composición del paquete, en lugar de acumular primeros planos. Guarda fecha y resultado. Cuando exista la información necesaria, marca con claridad aceptar, pedir prueba, consultar la anomalía, solicitar devolución si corresponde o esperar otro artículo.",
      "Define un límite personal anterior al final del periodo gratuito. Ese margen deja tiempo para fotografías, comunicación, posible devolución y reorganización del paquete. Ordena la hoja por fecha de llegada para mantener visible el artículo más antiguo. Si pudiera necesitarse una ampliación, revisa pronto su precio y disponibilidad dentro de la cuenta. Los 90 y 180 días publicados sirven para planificar, pero no sustituyen la comprobación del estado real de cada pedido y de las condiciones vigentes.",
      "Una comparación útil prueba al menos dos agrupaciones: todo junto y una división por restricción o volumen. Retirar cajas puede reducir tamaño, pero cambia protección y valor de conservación. Baterías, líquidos, fragilidad y determinados atributos pueden limitar las rutas. No anotes simplemente «consolidar»; registra las hipótesis de la agrupación. Solo el peso, las medidas y las opciones mostradas después de la recepción revelan si unir artículos reduce el coste o solamente el número de gestiones.",
      "Los estados funcionan cuando todos usan la misma definición. Añade una pequeña leyenda y no permitas saltar de «encontrado» a «listo para enviar». Cada cambio necesita fecha y motivo. Las revisiones antiguas de precio o ruta vuelven a quedar abiertas. La hoja evita compras accidentales desde favoritos desactualizados y conserva un historial honesto: qué se sabía, qué confirmaron después las fotos de almacén y por qué se tomó una decisión concreta de paquete.",
      "Los cinco campos son compactos, pero cubren el camino completo de decisión. Si hace falta más detalle, añade vendedor, envío nacional, llegada, peso, medidas y grupo de paquete sin alterar la lógica central. Usa formatos consistentes de fecha y moneda y enlaza siempre a un destino comprobable. La plantilla no debe fingir datos en vivo: debe mostrar cuándo se revisó cada valor y qué acción específica corresponde a continuación."
    ],
    "qc-photo-checklist": [
      "El principio central es que el QC es una inspección visual limitada. Formula antes de la llegada una pregunta que una fotografía pueda resolver y evita conclusiones sobre autenticidad o duración sin la prueba adecuada. Compara siempre con la opción exacta guardada al comprar. Si existe una diferencia, registra el rasgo visible, la vista afectada y la fecha. Ese historial vuelve más clara cualquier petición adicional o decisión de devolución.",
      "Sigue siempre el mismo orden y empieza por la identidad general. En un conjunto, la cantidad y los accesorios forman parte de la identidad tanto como el color o la talla. Costuras y pequeños defectos se revisan después. Si falta una marca, indica qué etiqueta debe verse completa y legible. Una foto nítida del lugar equivocado no resuelve la duda; una instrucción dirigida evita tiempo perdido y una segunda solicitud.",
      "Mide tu propia prenda en plano con el mismo método solicitado al almacén. Junto a cada cifra indica si es anchura, contorno o longitud recta. El ángulo de cámara y la tensión del tejido pueden causar diferencias pequeñas, por lo que conviene definir antes una tolerancia. En calzado, la longitud de plantilla puede ser más útil que la talla impresa. Una medida solo sirve cuando método, unidad y límite de decisión están documentados juntos.",
      "Crea una lista breve de riesgos por categoría en vez de valorar todos los productos igual. Ropa, zapatos, bolsos y accesorios frágiles requieren vistas diferentes. Compara ambos lados de un par, elementos simétricos y puntos de unión sometidos a carga. Un reflejo o una arruga del embalaje no es automáticamente un defecto; una costura abierta, una pieza ausente o dos formas claramente distintas sí son observaciones concretas. Describe ubicación y extensión.",
      "Una solicitud precisa especifica objeto, ángulo y propósito: por ejemplo, fotografiar de frente la etiqueta completa para confirmar la variante. Comprueba el precio actual del servicio y si el paquete puede abrirse. La comparación correcta no es solo cuánto cuesta la foto, sino qué error puede evitar. Una imagen dirigida tiene sentido cuando decide una devolución, la inclusión en el paquete o un envío internacional costoso.",
      "Para artículos especiales crea la nota de riesgo antes de pagar. Indica qué funciones no se pueden probar, si el embalaje debe permanecer cerrado y qué límites de devolución impone el vendedor. Superbuy señala un estándar QC diferente para 1688; por eso el mismo estado no significa siempre igual profundidad. Electrónica, coleccionables, modelos y productos personalizados pueden permitir comprobar apariencia y contenido, pero dejar sin resolver funcionamiento o autenticidad.",
      "Revisa la fecha de notificación del almacén y abre inmediatamente la función posventa cuando el problema sea importante. El marco publicado de cinco días corresponde a compras elegibles y tiene excepciones; no es una garantía universal. Guarda la imagen, describe la diferencia y la solución solicitada. No esperes a formar el paquete. Actuar pronto mantiene abiertas las opciones de prueba adicional, aclaración del vendedor, posible devolución o aceptación informada.",
      "Para repetir la checklist, asigna a cada punto solo tres resultados: confirmado, incierto o no verificable por foto. En «incierto» añade la acción siguiente. Un estado verde nunca debe salir de la ausencia de datos. Conserva la nota original del listado junto con el resultado de almacén y separa hechos de interpretación. Así se comparan categorías distintas sin fingir que una imagen estándar certifica material, función y uso prolongado.",
      "Convierte el almacenamiento en calendario de trabajo. Una revisión semanal muestra llegadas nuevas, fotos pendientes, posibles devoluciones y artículos aprobados. Los casos antiguos o con fecha límite se atienden primero. Si varias compras viajarán juntas, un solo artículo sin resolver no debería detener al grupo en silencio. Una conclusión documentada por producto facilita la selección del paquete y evita decisiones apresuradas cerca del final de los plazos.",
      "Haz dos comprobaciones finales: ¿la imagen corresponde realmente a la variante comprada y la diferencia observada cambiaría tu decisión? Para el color, revisa varias vistas y la iluminación. Para un supuesto daño, distingue embalaje, polvo, pliegue y defecto real. Tampoco aceptes automáticamente porque ya invertiste tiempo. Un registro objetivo de evidencia antes del envío internacional suele ser más barato que una sorpresa sin resolver después de la entrega."
    ],
    "shipping-cost-planning": [
      "Separa decisión de compra y decisión de paquete. La hoja inicial puede contener un rango de planificación, nunca un total final falsamente exacto. Marca las hipótesis de peso, medidas, ruta y tipo de cambio. Sustitúyelas por datos de almacén cuando existan. Los posibles costes de importación quedan en otra línea ligada al destino. De este modo se distingue qué importe fue observado, cuál es una estimación y cuál solo podrá conocerse al formar el paquete.",
      "Conserva depósito y liquidación final, sin sobrescribir el primer valor. Añade fecha, línea, peso estimado, peso confirmado y dimensiones. La comparación permite explicar una diferencia por embalaje, peso volumétrico, redondeo o cambio de ruta. Un reembolso observado en un envío no se convierte en fórmula general. Solo describe el ajuste de ese paquete concreto después de la verificación del transportista.",
      "Calcula el peso volumétrico con el divisor y el redondeo publicados para la línea elegida, nunca con un ejemplo de otra ruta. Prueba el efecto de retirar cajas, comprimir o dividir y compáralo con la protección necesaria. Guarda por separado peso real y tres medidas exteriores. A menudo se factura el valor aplicable más alto, pero la regla que aparece al seleccionar la línea es siempre la referencia actual.",
      "Un grupo compatible considera peso, volumen, fragilidad, atributos y protección. Prepara dos o tres escenarios y compara las líneas realmente disponibles después de la llegada. Un artículo pequeño restringido puede reducir opciones del paquete grande; dos envíos pueden duplicar costes base. La hoja debe mostrar ese conflicto y justificar la elección con datos actuales, en lugar de presentar consolidación como ahorro automático.",
      "Compara rutas para el mismo contenido, destino y momento. Además del precio, anota tramo de peso, fórmula volumétrica, seguimiento, plazo orientativo, seguro, límites y restricciones. El número global de líneas anunciadas no revela cuáles aceptarán el paquete. Evita fechas garantizadas porque conexiones, aduanas y reparto local varían. La referencia útil es la selección actual del formulario con sus condiciones completas.",
      "Vincula cada servicio de embalaje con un riesgo concreto. Refuerzo y protección pueden ayudar a lo frágil, mientras el material innecesario aumenta peso y volumen. Retirar cajas ahorra espacio pero cambia protección y valor de conservación. Lee también límites, exclusiones e indemnización del seguro. Registra el servicio elegido y su motivo; después de la entrega podrás decidir con datos si merece repetirse.",
      "Crea una comprobación específica para el país: tipo de mercancía, descripción, posible impuesto, documentos y características restringidas. No extrapoles una experiencia de otro destino ni una promesa general «sin impuestos». Las reglas cambian. Consulta información aduanera oficial y condiciones actuales de la ruta, declara honestamente y reserva margen de dinero y tiempo. Ninguna hoja puede garantizar ausencia de control, retraso o cobro.",
      "La primera estimación apoya la compra, la segunda usa peso y medidas de almacén, y la tercera es la cotización actual al enviar. Guarda las tres con fecha e hipótesis. Así se ve dónde mejora la previsión. Separa producto, entrega nacional y servicios opcionales. Un historial que aprende de cada paquete es más útil que una cifra final aislada sin explicación.",
      "Antes de enviar, cada artículo debe tener un QC cerrado. Comprueba en orden dirección, teléfono, grupo, restricciones, peso, medidas, embalaje, seguro y declaración. Compara todas las rutas aptas, no solo la primera. Guarda línea, cotización, fecha y seguimiento. Tras la entrega añade cargo final, ajuste y duración real para convertir el paquete en datos útiles para la siguiente planificación.",
      "Los errores habituales nacen de una precisión imaginaria: tarifa fija por kilo, captura antigua, precio principal sin reglas o llegada garantizada. Recalcula cuando cambie grupo, embalaje, dimensiones, destino o atributos. Separa información oficial de experiencias individuales y fecha cada observación. La planificación más fiable es progresiva, revisa el calculador en vivo justo antes de pagar y muestra claramente la incertidumbre restante."
    ]
  },
  it: {
    "spreadsheet-without-buying-blind": [
      "In pratica una riga deve affermare soltanto ciò che è stato davvero controllato alla data indicata. Un link attivo non conferma disponibilità o affidabilità del venditore. Registra quindi la domanda ancora aperta e il prossimo passaggio di verifica. Il foglio resterà comprensibile anche dopo settimane e una vecchia schermata non diventerà una raccomandazione permanente. Separare scoperta, acquisto, prova di magazzino e decisione di spedizione rende la ricerca molto più solida.",
      "Le inserzioni miste possono raccogliere nello stesso link colori, taglie e perfino articoli diversi. Salva la miniatura e il testo esatto dell’opzione scelta. Ogni modifica successiva sarà riconoscibile. Prima del pagamento verifica anche che la consegna nazionale mostrata valga ancora per quantità e destinazione. La riga passa a «opzione confermata» soltanto dopo questo controllo; fino ad allora resta una scoperta che richiede una validazione attuale.",
      "Separare le voci impedisce che un prezzo basso crei un’idea sbagliata del budget totale. L’acquisto standard gratuito è una regola specifica del servizio, non una promessa di consegna gratuita. Acquisti speciali, usato e servizi extra possono seguire condizioni diverse. Registra importo, valuta, data e tipo di costo in campi distinti. La stima internazionale dipende dal pacco reale e dalle linee disponibili più avanti, quindi non deve apparire come proprietà fissa del prodotto.",
      "Per valutare le immagini usa tre colonne: confermato visivamente, poco chiaro nella foto e impossibile da provare con una fotografia. Il colore può risultare coerente mentre materiale e comfort restano ignoti. Se una misura influenza la scelta, la richiesta deve nominare il punto preciso. Le foto diventano così nuovi dati dopo la ricezione, non decorazione. Conserva l’ipotesi iniziale per confrontarla con la prova arrivata in magazzino.",
      "Una buona decisione unisce osservazione e conseguenza, per esempio: «etichetta visibile, larghezza mancante — chiedere foto dettagliata». Un’altra persona può seguire il ragionamento. Dai priorità alle domande che cambierebbero un reso o la composizione del pacco, invece di accumulare primi piani. Salva data e risultato. Quando l’informazione è sufficiente, scegli chiaramente accettare, chiedere prova, chiarire l’anomalia, richiedere reso se idoneo o attendere un altro articolo.",
      "Stabilisci una scadenza personale precedente alla fine del periodo gratuito. Il margine lascia tempo per fotografie, comunicazione, eventuale reso e nuova organizzazione del pacco. Ordina il foglio per data di arrivo per mantenere visibile l’articolo più vecchio. Se può servire un’estensione, controllane in anticipo prezzo e disponibilità nell’account. I 90 e 180 giorni pubblicati sono riferimenti di pianificazione, ma non sostituiscono lo stato concreto dell’ordine e le condizioni correnti.",
      "Un confronto utile prova almeno due gruppi: tutto insieme e una divisione per restrizione o volume. Rimuovere scatole può ridurre le dimensioni, ma cambia protezione e valore di conservazione. Batterie, liquidi, fragilità e determinati attributi possono limitare le linee. Non scrivere soltanto «consolidare»: registra le ipotesi del gruppo. Solo peso, misure e opzioni mostrate dopo l’arrivo indicano se l’unione riduce davvero il costo o soltanto il numero di operazioni.",
      "Gli stati funzionano quando tutti condividono la stessa definizione. Aggiungi una breve legenda e impedisci il salto diretto da «trovato» a «pronto per la spedizione». Ogni variazione deve avere data e motivo. Vecchi controlli di prezzo o linea tornano aperti. Il foglio evita acquisti accidentali da preferiti superati e conserva una cronologia onesta: ciò che era noto, ciò che le foto hanno confermato e perché è stata scelta una determinata composizione del pacco.",
      "I cinque campi sono compatti ma coprono l’intero percorso decisionale. Se occorre più dettaglio, aggiungi venditore, consegna nazionale, arrivo, peso, dimensioni e gruppo senza cambiare la logica centrale. Usa formati coerenti per data e valuta e collega sempre una destinazione verificabile. Il modello non deve simulare dati live: deve mostrare quando ogni valore è stato controllato e quale azione specifica deve seguire."
    ],
    "qc-photo-checklist": [
      "Il principio centrale è che il QC è un controllo visivo limitato. Formula prima dell’arrivo una domanda che una foto possa davvero risolvere ed evita conclusioni su autenticità o durata senza prove adeguate. Confronta sempre con l’opzione esatta salvata all’acquisto. Se emerge una differenza, annota il particolare visibile, la vista interessata e la data. Questa traccia rende più chiara una richiesta aggiuntiva o una decisione di reso.",
      "Segui sempre lo stesso ordine e inizia dall’identità generale. In un set, quantità e accessori fanno parte dell’identità quanto colore e taglia. Cuciture e piccoli difetti vengono dopo. Se manca un’indicazione, specifica quale etichetta deve apparire completa e leggibile. Una foto nitida del punto sbagliato non risolve il dubbio; un’istruzione mirata evita tempo perso e una seconda richiesta.",
      "Misura un tuo articolo in piano con lo stesso metodo richiesto al magazzino. Accanto a ogni valore indica larghezza, circonferenza o lunghezza retta. Angolo della fotocamera e tensione del tessuto possono produrre piccole differenze, quindi definisci prima una tolleranza. Per le scarpe, la lunghezza della soletta può essere più utile della taglia stampata. Una misura serve solo quando metodo, unità e soglia decisionale sono documentati insieme.",
      "Crea una breve lista di rischi per categoria invece di giudicare tutti i prodotti allo stesso modo. Abiti, scarpe, borse e accessori fragili richiedono viste diverse. Confronta i due lati di una coppia, elementi simmetrici e punti di fissaggio sotto sforzo. Un riflesso o una piega dell’imballaggio non è automaticamente un difetto; cucitura aperta, pezzo mancante o forme chiaramente differenti sono osservazioni concrete. Descrivi posizione ed estensione.",
      "Una richiesta precisa specifica soggetto, angolo e scopo: per esempio, fotografare frontalmente l’intera etichetta per confermare la variante. Controlla il prezzo corrente del servizio e se la confezione può essere aperta. Il confronto corretto non è solo il costo della foto, ma l’errore che può evitare. Un’immagine mirata è sensata quando decide un reso, l’inclusione nel pacco o una costosa spedizione internazionale.",
      "Per un articolo speciale prepara la nota di rischio prima di pagare. Indica quali funzioni non possono essere testate, se l’imballaggio deve restare chiuso e quali limiti di reso applica il venditore. Superbuy segnala uno standard QC diverso per 1688; lo stesso stato non rappresenta quindi la stessa profondità. Elettronica, collezionabili, modelli e prodotti personalizzati possono permettere un controllo visivo e di completezza, lasciando funzione e autenticità irrisolte.",
      "Controlla la data di notifica del magazzino e apri subito la funzione post-vendita quando il problema conta. Il quadro pubblicato di cinque giorni riguarda acquisti idonei e contiene eccezioni; non è una garanzia universale. Conserva la vista rilevante, descrivi la differenza e la soluzione richiesta. Non aspettare la creazione del pacco. Agire presto mantiene disponibili prova aggiuntiva, chiarimento del venditore, possibile reso o accettazione consapevole.",
      "Per rendere ripetibile la checklist, assegna a ogni punto tre esiti: confermato, incerto o non verificabile in foto. Per «incerto» aggiungi l’azione seguente. Uno stato verde non deve nascere dall’assenza di dati. Conserva la nota originale dell’inserzione con i risultati del magazzino e separa fatti visibili e interpretazione. Categorie diverse diventano confrontabili senza fingere che un’immagine standard certifichi materiale, funzione e uso nel tempo.",
      "Trasforma il deposito in un calendario di lavoro. Una revisione settimanale mostra nuovi arrivi, foto in sospeso, possibili resi e articoli approvati. I casi più vecchi o con scadenza hanno priorità. Se più acquisti devono viaggiare insieme, un solo articolo non risolto non dovrebbe bloccare il gruppo in silenzio. Una conclusione documentata per prodotto facilita la scelta del pacco ed evita decisioni affrettate vicino ai termini.",
      "Fai due controlli finali: l’immagine corrisponde davvero alla variante acquistata e la differenza osservata cambierebbe la tua scelta? Per il colore considera più viste e l’illuminazione. Per un presunto danno distingui confezione, polvere, piega e difetto reale. Non accettare automaticamente solo perché hai già investito tempo. Un registro oggettivo prima della spedizione internazionale costa spesso meno di una sorpresa irrisolta dopo la consegna."
    ],
    "shipping-cost-planning": [
      "Separa la decisione di acquisto dalla decisione sul pacco. Il foglio iniziale può indicare un intervallo di pianificazione, mai un totale finale falsamente preciso. Segnala le ipotesi su peso, misure, linea e cambio e sostituiscile con dati di magazzino quando disponibili. Eventuali costi d’importazione restano una voce separata legata alla destinazione. Così è chiaro quale importo è osservato, quale stimato e quale sarà calcolabile solo dopo la formazione del pacco.",
      "Conserva deposito e regolazione finale senza sovrascrivere il primo valore. Aggiungi data, linea scelta, peso stimato, peso confermato e dimensioni. Il confronto permette di spiegare una differenza con imballaggio, peso volumetrico, arrotondamento o cambio di linea. Un rimborso osservato su un invio non diventa una formula generale: descrive soltanto la rettifica di quel pacco dopo la verifica del vettore.",
      "Calcola il peso volumetrico con divisore e arrotondamento pubblicati per la linea scelta, mai con l’esempio di un’altra rotta. Prova l’effetto di rimozione scatole, compressione o divisione e confrontalo con la protezione necessaria. Registra separatamente peso reale e tre misure esterne. Spesso conta il valore fatturabile maggiore, ma la regola mostrata al momento della selezione rimane il riferimento corrente.",
      "Un gruppo compatibile considera peso, volume, fragilità, attributi e protezione. Prepara due o tre scenari e confronta le linee realmente disponibili dopo l’arrivo. Un piccolo prodotto soggetto a restrizioni può ridurre le opzioni del pacco grande; due invii possono duplicare costi base. Il foglio deve mostrare questo compromesso e motivare la scelta con dati attuali, non presentare il consolidamento come risparmio automatico.",
      "Confronta le linee per lo stesso contenuto, la stessa destinazione e lo stesso momento. Oltre al prezzo, annota fascia di peso, formula volumetrica, tracking, tempi indicativi, assicurazione, limiti e restrizioni. Il numero globale di linee pubblicizzato non dice quali accetteranno quel pacco. Evita date garantite perché transiti, dogana e consegna locale variano. Il riferimento utile è la selezione corrente nel modulo con tutte le condizioni.",
      "Collega ogni servizio di imballaggio a un rischio specifico. Rinforzo e protezione possono aiutare il fragile, mentre materiale inutile aumenta peso e volume. Rimuovere scatole fa risparmiare spazio ma cambia protezione e valore di conservazione. Leggi anche massimali, esclusioni e base di indennizzo dell’assicurazione. Registra servizio e motivo; dopo la consegna potrai valutare con dati se usarlo di nuovo.",
      "Crea un controllo specifico per il paese: tipo di merce, descrizione, possibile imposta, documenti e caratteristiche limitate. Non trasferire automaticamente un’esperienza di un’altra destinazione o una promessa generica «senza tasse». Le regole cambiano. Consulta fonti doganali ufficiali e condizioni correnti della linea, dichiara onestamente e prevedi margine economico e temporale. Nessun foglio può garantire assenza di controlli, ritardi o addebiti.",
      "La prima stima sostiene la decisione di acquisto, la seconda usa peso e misure di magazzino, la terza è il preventivo corrente all’invio. Conserva tutte con data e ipotesi. Diventa visibile dove la previsione migliora. Separa prodotto, consegna nazionale e servizi opzionali. Una cronologia che impara da ogni pacco è più utile di un importo finale isolato senza spiegazione.",
      "Prima dell’invio ogni articolo deve avere un QC concluso. Controlla in ordine indirizzo, telefono, gruppo, restrizioni, peso, misure, imballaggio, assicurazione e dichiarazione. Confronta tutte le linee idonee, non soltanto la prima. Salva linea, preventivo, data e tracking. Dopo la consegna aggiungi addebito finale, rettifica e durata reale per trasformare il pacco in dati utili alla pianificazione successiva.",
      "Gli errori comuni nascono da una precisione immaginaria: tariffa fissa al chilo, vecchia schermata, prezzo principale senza regole o arrivo garantito. Ricalcola quando cambiano gruppo, imballaggio, dimensioni, destinazione o attributi. Separa informazioni ufficiali da esperienze individuali e data ogni osservazione. La pianificazione più affidabile è progressiva, ricontrolla il calcolatore live subito prima del pagamento e mostra chiaramente l’incertezza restante."
    ]
  }
};

export const articleClosers: Record<LocalArticleLang, Record<string, string>> = {
  de: {
    "spreadsheet-without-buying-blind": "Führe vor jeder Nutzung zusätzlich eine kurze Aktualitätsprüfung durch: Zielseite erreichbar, gewünschte Option sichtbar, Preis und Inlandszustellung neu gelesen, offene QC-Frage noch relevant und Status mit Datum versehen. Wird eine Annahme nicht mehr bestätigt, bleibt die Zeile erhalten, erhält aber wieder den Prüfstatus. So gehen frühere Recherchen nicht verloren und werden dennoch nicht als aktuelle Tatsache ausgegeben. Eine belastbare Tabelle ist deshalb kein möglichst großer Linkkatalog, sondern ein transparentes Entscheidungsprotokoll. Sie hilft dem Leser, eine Auswahl einzugrenzen, die Live-Seite selbst zu kontrollieren, Lagerbelege richtig einzuordnen und erst danach die Versandgruppe zu bilden. Dieser Ablauf schützt besser vor Blindkäufen als ein pauschales Häkchen mit der Bezeichnung „verifiziert“.",
    "qc-photo-checklist": "Schließe jede Prüfung mit einem kurzen Satz ab, der Fakten und Grenzen zusammenfasst: welche Variante sichtbar war, welche Maße passten, welcher Fehler nicht erkennbar war und welche Aktion daraus folgt. Wenn keine weitere Aufnahme nötig ist, dokumentiere auch diesen Grund. Bei einer Unregelmäßigkeit sollten Bild, Nachricht und Zeitfenster gemeinsam überprüft werden, bevor der Artikel in ein internationales Paket gelangt. Die Checkliste ist damit kein Qualitätssiegel, sondern ein Verfahren zur Verringerung sichtbarer Unsicherheit. Sie funktioniert am besten, wenn Fragen vor dem Lagereingang definiert, Fotos systematisch statt emotional betrachtet und offene Punkte rechtzeitig innerhalb der jeweils verfügbaren After-Sales-Optionen behandelt werden.",
    "shipping-cost-planning": "Nach jeder Zustellung lohnt sich eine kurze Nachkalkulation. Vergleiche ursprüngliche Annahme, Lagerdaten, eingereichten Betrag, endgültige Anpassung, tatsächliche Laufzeit und Zustand der Verpackung. Markiere, welche Abweichung durch Volumen, Zusatzschutz, Routenauswahl oder eine unzutreffende Gewichtsschätzung entstand. Verwende diese Erfahrung nur als Ausgangspunkt für die nächste Sendung, nicht als garantierten Tarif. Preise, Linien, Grenzen und Zielregeln können sich ändern. Eine gute Versandtabelle arbeitet daher mit datierten Szenarien und aktualisiert sich in drei Stufen. Sie verspricht keinen festen Endpreis, sondern macht Entscheidungen prüfbar und zwingt dazu, unmittelbar vor der Zahlung die aktuelle Kalkulation, alle Einschränkungen und die destinationsabhängigen Zollinformationen erneut zu lesen. Bewahre außerdem Trackingereignisse und Verzögerungsgründe auf. So lässt sich später zwischen angekündigter und beobachteter Laufzeit unterscheiden, ohne aus einem einzelnen Paket eine allgemeine Zusage abzuleiten."
  },
  fr: {
    "spreadsheet-without-buying-blind": "Avant chaque utilisation, effectuez un contrôle d’actualité rapide : page accessible, option souhaitée visible, prix et livraison intérieure relus, question QC toujours pertinente et statut daté. Si une hypothèse n’est plus confirmée, conservez l’historique mais replacez la ligne en révision. La recherche précédente n’est pas perdue et n’est pas non plus présentée comme une vérité actuelle. Une feuille fiable n’est donc pas le plus grand catalogue de liens possible ; c’est un journal de décision transparent. Elle aide à réduire la sélection, vérifier la page en direct, interpréter correctement les preuves de l’entrepôt puis former le colis. Cette méthode protège davantage contre l’achat à l’aveugle qu’une simple coche « vérifié ».",
    "qc-photo-checklist": "Terminez chaque contrôle par une phrase qui réunit faits et limites : variante visible, mesures acceptables, défaut impossible à observer et action suivante. Lorsqu’aucune image supplémentaire n’est nécessaire, notez aussi pourquoi. En présence d’une anomalie, examinez ensemble photo, message et délai disponible avant de placer l’article dans un colis international. La checklist n’est pas un label de qualité ; c’est une méthode pour réduire l’incertitude visible. Elle fonctionne lorsque les questions sont définies avant l’arrivée, que les photos sont étudiées systématiquement plutôt qu’émotionnellement et que les points ouverts sont traités assez tôt selon les options après-vente réellement disponibles.",
    "shipping-cost-planning": "Après la livraison, faites un court bilan : hypothèse initiale, données d’entrepôt, dépôt, ajustement final, durée réelle et état de l’emballage. Identifiez si l’écart venait du volume, de la protection, de la route ou d’une estimation de poids incorrecte. Cette expérience sert de point de départ, jamais de tarif garanti pour l’envoi suivant. Prix, lignes, limites et règles de destination évoluent. Une bonne feuille d’expédition utilise donc des scénarios datés et progresse en trois estimations. Elle ne promet pas un coût final fixe ; elle rend les décisions vérifiables et oblige à relire, juste avant le paiement, le calcul actuel, les restrictions complètes et les informations douanières propres à la destination."
  },
  es: {
    "spreadsheet-without-buying-blind": "Antes de usar una fila realiza una revisión rápida de actualidad: destino accesible, opción prevista visible, precio y envío nacional releídos, pregunta QC aún relevante y estado con fecha. Si una hipótesis ya no se confirma, conserva el historial pero devuelve la fila a revisión. La investigación anterior no se pierde ni se presenta como hecho actual. Una hoja fiable no es el catálogo con más enlaces, sino un registro transparente de decisiones. Ayuda a reducir la selección, comprobar la página en vivo, interpretar correctamente la evidencia del almacén y solo después formar el paquete. Ese proceso protege mejor frente a compras a ciegas que una casilla genérica llamada «verificado».",
    "qc-photo-checklist": "Cierra cada revisión con una frase que reúna hechos y límites: variante visible, medidas aceptadas, aspecto imposible de observar y acción siguiente. Si no hace falta otra imagen, registra también el motivo. Cuando exista una anomalía, revisa conjuntamente la fotografía, el mensaje y el tiempo disponible antes de añadir el artículo a un envío internacional. La checklist no es un sello de calidad; es un método para reducir incertidumbre visible. Funciona mejor cuando las preguntas se definen antes de la llegada, las fotos se analizan de manera sistemática y los puntos abiertos se resuelven pronto mediante las opciones posventa realmente disponibles para ese pedido.",
    "shipping-cost-planning": "Después de la entrega prepara una breve conciliación: hipótesis inicial, datos del almacén, depósito, ajuste final, duración real y estado del embalaje. Señala si la diferencia vino de volumen, protección, línea o una estimación de peso equivocada. Usa esa experiencia como punto de partida, no como tarifa garantizada para el siguiente paquete. Los precios, rutas, límites y reglas del destino cambian. Una buena hoja de envíos trabaja con escenarios fechados y tres estimaciones sucesivas. No promete un coste final fijo: vuelve comprobables las decisiones y obliga a revisar justo antes del pago el cálculo actual, las restricciones completas, el alcance del seguro y la información aduanera específica del país. Conserva también el seguimiento y cualquier incidencia para distinguir tiempo anunciado de tiempo observado. Si una nueva agrupación cambia dimensiones o atributos, vuelve a calcular desde cero en lugar de reutilizar el importe anterior. La precisión real proviene de actualizar los datos, no de mostrar una cifra temprana con demasiados decimales."
  },
  it: {
    "spreadsheet-without-buying-blind": "Prima di usare una riga esegui un controllo rapido di attualità: destinazione raggiungibile, opzione prevista visibile, prezzo e consegna nazionale riletti, domanda QC ancora pertinente e stato datato. Se un’ipotesi non è più confermata, conserva la cronologia ma riporta la riga in revisione. La ricerca precedente non va persa e non viene presentata come fatto corrente. Un foglio affidabile non è il catalogo con più link, ma un registro trasparente di decisioni. Aiuta a restringere la scelta, controllare la pagina live, interpretare la prova del magazzino e solo dopo comporre il pacco. Questo processo protegge dagli acquisti alla cieca più di una generica casella «verificato».",
    "qc-photo-checklist": "Chiudi ogni revisione con una frase che riunisca fatti e limiti: variante visibile, misure accettate, aspetto non osservabile e azione successiva. Se non serve un’altra immagine, registra anche il motivo. In presenza di un’anomalia, considera insieme foto, messaggio e tempo disponibile prima di inserire l’articolo in una spedizione internazionale. La checklist non è un marchio di qualità; è un metodo per ridurre l’incertezza visibile. Funziona quando le domande vengono definite prima dell’arrivo, le foto sono analizzate sistematicamente e i punti aperti vengono risolti presto tramite le opzioni post-vendita realmente disponibili per quel singolo ordine. Mantieni infine separati il fatto osservato, la tua interpretazione e la decisione presa: questa distinzione evita che un dubbio venga trasformato per errore in una certezza.",
    "shipping-cost-planning": "Dopo la consegna prepara una breve riconciliazione: ipotesi iniziale, dati di magazzino, deposito, rettifica finale, durata reale e stato dell’imballaggio. Indica se la differenza è nata da volume, protezione, linea o stima del peso errata. Usa l’esperienza come punto di partenza, non come tariffa garantita per il prossimo pacco. Prezzi, linee, limiti e regole della destinazione cambiano. Un buon foglio di spedizione lavora quindi con scenari datati e tre stime successive. Non promette un costo finale fisso: rende verificabili le decisioni e impone di rileggere subito prima del pagamento il calcolo corrente, tutte le restrizioni, la copertura assicurativa e le informazioni doganali del paese. Conserva inoltre tracking e incidenti per distinguere i tempi annunciati da quelli osservati. Se un nuovo gruppo modifica misure o attributi, ricalcola da zero invece di riutilizzare l’importo precedente. La vera precisione deriva dall’aggiornamento dei dati, non da una cifra precoce mostrata con troppi decimali. Registra anche eventuali cambi di rotta, oneri alla consegna e motivi di ritardo, indicando la fonte. Questi dettagli aiutano a migliorare il prossimo scenario senza trasformare una singola esperienza in una promessa universale. Prima di inviare, riapri sempre il preventivo live: è l’unico confronto coerente con quel gruppo, quelle dimensioni e quel momento."
  }
};
