export const fullTranslations: Record<string, Record<string, any>> = {
  de: {
    displayDate:"25. Aug. 2026", updated:"Routenprüfung · 25. Aug. 2026", copyright:"Unabhängige Tabellenrecherche", productNames:["Schuhe","Hoodie 55","T-Shirts 55","Jacken 55","Hosen / Shorts 55","Accessoires 54"],
    readGuide:"VOLLSTÄNDIGEN RATGEBER LESEN →", factCheck:"FAKTENCHECK", nextDecision:"NÄCHSTE ENTSCHEIDUNG", factChecked:"Fakten geprüft", checked:"GEPRÜFT", review:"PRÜFEN", live:"AKTUELL", flow:"Link → QC → Paket",
    legal:"Preis, Verfügbarkeit, Optionen und Versandberechtigung vor der Bestellung prüfen.",
    researchSource:"Recherchegrundlage: Superbuy Shopping-Agent-Leitfaden, Service & Gebühren, Hilfe-Center, offizieller Ablauf und Nutzungsbedingungen. Fakten geprüft am 25. Aug. 2026; aktuelle Kontobedingungen haben Vorrang.",
    findsCheckTitle:"So liest du jeden aktuellen Fund", findsCheckText:"Nutze die Karten als Vorauswahl und prüfe dann vor einer Kaufentscheidung das aktuelle Ziel.",
    findsRows:[["Quellbild abgleichen","Nutze das Kartenbild zur Identifikation und bestätige, dass das aktuelle Ziel weiterhin dasselbe Hauptprodukt zeigt."],["Genaue Option bestätigen","Prüfe Farbe, Größe, Menge, Preis und Verkäufer-Versand auf der aktuellen Seite. Eine Routenprüfung fixiert keine dieser Angaben."],["Routenstatus und Qualität trennen","Das Prüfdatum zeigt, wann das Ziel kontrolliert wurde. Es ist keine Garantie für Qualität, Echtheit oder Passform."],["Lagerentscheidung planen","Lege vor der Bestellung fest, welches sichtbare Detail, Maß oder Zubehör in den QC-Fotos erscheinen muss, damit du den Artikel behältst."]],
    spreadsheetRows:[["Aktuelle Route","Zielseite öffnen und bestätigen, dass sie noch zum vorgesehenen Produkt führt."],["Genaue Option","Aktuelle Farbe, Größe, Menge und Optionsbezeichnung festhalten – nicht nur den Produkttitel."],["Kosten der ersten Stufe","Artikelpreis, chinesischen Inlandsversand und optionale Produktservices getrennt erfassen."],["Lagerbelege","QC-Ergebnis, gewünschte Maße und sichtbare Abweichungen dokumentieren."],["Lagerfrist","Eingangsdatum im Lager mit dem aktuellen kostenlosen 90-Tage-Zeitraum abgleichen."],["Paketgruppe","Nur Artikel zusammenfassen, die nach Gewicht, Maßen und Beschränkungen zusammenpassen."],["Nächster Schritt","Klare Statuswerte verwenden: prüfen, kaufen, Lager abwarten, Beleg anfordern, zurückgeben, Paket oder abgeschlossen."]],
    guideRows:[["1 · Produkt einreichen","Aktuelle Produktroute öffnen, genaue Option wählen und Artikelpreis plus angezeigten Inlandsversand bezahlen."],["2 · Einkauf durch Agent","Der Einkaufsagent kontaktiert den Verkäufer und kauft den Artikel; fehlende Angaben können per Nachricht oder E-Mail angefordert werden."],["3 · Lagerprüfung","Nach Ankunft wird der Artikel geprüft und fotografiert. Die aktuelle Startseite nennt drei kostenlose QC-Fotos."],["4 · Lagerentscheidung","Der offizielle Leitfaden nennt derzeit 90 Tage kostenlose Lagerung, damit weitere Artikel vor der Paketbildung eintreffen können."],["5 · Paket einreichen","Geeignete Lagerartikel auswählen, Zieladresse eingeben und die für dieses Paket verfügbaren Linien vergleichen."],["6 · Endgültiger Versand","Internationales Versanddepot bezahlen; nach Prüfung von Größe und Gewicht wird der Endbetrag angepasst."]],
    qcRows:[["Identität zuerst","Artikelart, Modell, Farbe, Menge, Größenetikett und sichtbare Option abgleichen."],["Drei Standardfotos","Die aktuelle Superbuy-Startseite nennt drei kostenlose QC-Fotos nach Lagereingang."],["Maße","Lagermaße mit einem bekannten Artikel vergleichen, der an denselben Punkten gemessen wurde."],["Sichtbare Verarbeitung","Ausrichtung, Nähte, Druck, Beschläge, Sohlen, Flecken, Schäden und Paarvergleich prüfen."],["Detailbeleg","Ein gezieltes Detailfoto nur anfordern, wenn die fehlende Ansicht die Entscheidung ändern kann."],["Prüfgrenzen","Fotos beweisen weder Echtheit noch innere Qualität, Material, Komfort oder Haltbarkeit; für 1688 gilt ein anderer QC-Standard."]],
    shippingRows:[["Zwei Kostenstufen","Artikel- und Inlandsversandkosten getrennt von der internationalen Paketgebühr halten."],["Depot und Endbetrag","Das Depot basiert auf Schätzgewicht, Linie und Ziel; endgültige Maße und Gewicht können eine Kontokorrektur auslösen."],["Abrechnungsgewicht","Tatsächliches und Volumengewicht vergleichen, da leichte, große Pakete nach Raumbedarf berechnet werden können."],["Konsolidierung","Geeignete Lagerbestellungen können kostenlos zusammengefasst werden; ein großes Paket ist aber nicht immer am günstigsten."],["Verpackungsservices","Verpackungsentfernung, Verstärkung und Versicherung passend zum Risiko auswählen."],["Linienberechtigung","Verfügbare Linien hängen von Ziel, Artikelmerkmalen, Gewicht, Maßen und aktuellen Beförderungsbedingungen ab."],["Zoll und Steuern","Zoll, MwSt., Deklaration und Importregeln sind zielabhängig; keine Tabelle kann steuerfreie Zustellung garantieren."]],
    faqRows:[["Was ist eine Superbuy-Tabelle?","Ein unabhängiger Produktindex für aktuelle Routen, Optionen, Preisreferenzen, QC-Fragen und Paketentscheidungen."],["Erhebt Superbuy eine Einkaufsgebühr?","Die aktuelle Gebührenseite nennt den Standardkauf bei Taobao, Tmall, JD.com und 1688 gebührenfrei. Sonder-, Gebrauchtwaren- und Zusatzservices haben eigene Regeln."],["Sind die Preise endgültig?","Nein. USD-Beträge sind Referenzen; Live-Option, Artikelpreis, Inlandsversand und gewählte Services vor Zahlung prüfen."],["Bedeutet ein geprüfter Link geprüfte Qualität?","Nein. Der Status bestätigt nur die geprüfte Zielseite. Qualitätsentscheidungen benötigen Lagerbelege und bleiben begrenzt."],["Wie viele kostenlose QC-Fotos gibt es?","Die aktuelle Superbuy-Startseite nennt drei kostenlose QC-Fotos nach Lagereingang."],["Wie lange ist die Lagerung kostenlos?","Die aktuelle Gebührenseite nennt 90 kostenlose Tage, danach eine tägliche Gebühr pro Artikel und standardmäßig maximal 180 Tage."],["Kann ich Bestellungen kombinieren?","Geeignete Lagerartikel können kostenlos konsolidiert werden. Die Ersparnis hängt von Größe, Gewicht, Beschränkungen und Linien ab."],["Warum kann sich das Versanddepot ändern?","Das Depot nutzt Schätzgewicht, Linie und Ziel. Nach Prüfung von Paketgröße und Gewicht wird neu berechnet."],["Beweisen QC-Fotos Echtheit oder Passform?","Nein. Sie dokumentieren Sichtbares, aber nicht sicher Echtheit, Material, Komfort, Haltbarkeit oder Passform."],["Ist dies die offizielle Plattform?","Nein. Diese unabhängige Recherche verkauft nicht und wickelt weder Zahlung noch Versand ab. Aktuelle Regeln immer im Konto prüfen."]]
  },
  fr: {
    displayDate:"25 août 2026", updated:"Route contrôlée · 25 août 2026", copyright:"Recherche indépendante par tableur", productNames:["Chaussures","Sweat 55","T-Shirts 55","Vestes 55","Pantalons / Shorts 55","Accessoires 54"],
    readGuide:"LIRE LE GUIDE COMPLET →", factCheck:"VÉRIFICATION DES FAITS", nextDecision:"PROCHAINE DÉCISION", factChecked:"Faits vérifiés", checked:"VÉRIFIÉ", review:"À CONTRÔLER", live:"ACTUEL", flow:"Lien → QC → Colis",
    legal:"Vérifiez le prix, la disponibilité, les options et l’éligibilité d’expédition avant de commander.",
    researchSource:"Base de recherche : guide Shopping Agent, Services et frais, centre d’aide, parcours officiel et conditions Superbuy. Faits vérifiés le 25 août 2026 ; les règles actuelles du compte prévalent.",
    findsCheckTitle:"Comment lire chaque sélection actuelle", findsCheckText:"Utilisez les cartes comme présélection, puis vérifiez la destination active avant toute décision d’achat.",
    findsRows:[["Comparer l’image source","Utilisez l’image de la carte pour identifier l’article, puis confirmez que la destination active montre toujours le même produit principal."],["Confirmer l’option exacte","Vérifiez couleur, taille, quantité, prix et livraison du vendeur. Un contrôle de route ne fige aucune de ces informations."],["Séparer route et qualité","La date indique quand la destination a été contrôlée. Elle ne garantit ni qualité, ni authenticité, ni coupe."],["Préparer la décision en entrepôt","Avant de commander, définissez le détail visible, la mesure ou l’accessoire qui devra apparaître sur les photos QC pour conserver l’article."]],
    spreadsheetRows:[["Route actuelle","Ouvrez la destination et confirmez qu’elle mène toujours au produit prévu."],["Option exacte","Notez couleur, taille, quantité et libellé actuel de l’option, pas seulement le titre."],["Coût de première étape","Séparez prix de l’article, livraison locale chinoise et services optionnels."],["Preuves d’entrepôt","Consignez résultat QC, mesures demandées et différences visibles."],["Délai de stockage","Suivez l’arrivée à l’entrepôt par rapport aux 90 jours gratuits actuels."],["Groupe de colis","Regroupez seulement les articles compatibles après poids, dimensions et restrictions."],["Action suivante","Utilisez un statut clair : vérifier, acheter, attendre, demander une preuve, retourner, colis ou terminé."]],
    guideRows:[["1 · Soumettre le produit","Ouvrez la route actuelle, choisissez l’option exacte et payez l’article plus la livraison locale affichée."],["2 · Achat par l’agent","L’agent contacte le vendeur et achète l’article ; les informations manquantes peuvent être demandées par message ou e-mail."],["3 · Contrôle en entrepôt","À l’arrivée, l’article est inspecté et photographié. La page d’accueil actuelle annonce trois photos QC gratuites."],["4 · Décision de stockage","Le guide officiel indique actuellement 90 jours gratuits pour attendre d’autres articles avant le colis."],["5 · Soumettre un colis","Sélectionnez les articles éligibles, saisissez la destination et comparez les lignes proposées pour ce colis."],["6 · Expédition finale","Payez l’acompte international ; le montant final est ajusté après vérification de la taille et du poids."]],
    qcRows:[["Identité d’abord","Vérifiez type, modèle, couleur, quantité, étiquette de taille et option visible."],["Trois photos standard","La page d’accueil Superbuy indique actuellement trois photos QC gratuites après réception."],["Mesures","Comparez les mesures d’entrepôt avec un article connu mesuré aux mêmes endroits."],["Construction visible","Contrôlez alignement, coutures, impression, accessoires, semelles, taches, dommages et cohérence de la paire."],["Preuve détaillée","Demandez une photo ciblée seulement si la vue manquante peut changer la décision."],["Limites du contrôle","Les photos ne prouvent pas authenticité, qualité interne, matière, confort ou durée ; 1688 suit une norme QC différente."]],
    shippingRows:[["Deux étapes de coût","Séparez prix de l’article et livraison locale du coût du colis international."],["Acompte et montant final","L’acompte utilise poids estimé, ligne et destination ; taille et poids finaux peuvent produire un ajustement."],["Poids facturable","Comparez poids réel et volumétrique, car un colis léger et encombrant peut être facturé au volume."],["Regroupement","Les commandes éligibles peuvent être regroupées gratuitement, mais un grand colis n’est pas toujours moins cher."],["Services d’emballage","Retrait d’emballage, renforcement et assurance doivent répondre au risque réel du colis."],["Éligibilité des lignes","Les lignes dépendent de la destination, des attributs, du poids, des dimensions et des conditions actuelles."],["Douane et taxes","Droits, TVA, déclaration et restrictions sont propres à la destination ; aucune feuille ne garantit une livraison sans taxe."]],
    faqRows:[["Qu’est-ce qu’un tableur Superbuy ?","Un index indépendant qui enregistre routes, options, références de prix, questions QC et décisions de colis."],["Superbuy facture-t-il l’achat ?","La page actuelle indique que l’achat standard est gratuit sur Taobao, Tmall, JD.com et 1688. Les services spéciaux, d’occasion et optionnels ont d’autres règles."],["Les prix sont-ils définitifs ?","Non. Les montants USD sont indicatifs ; vérifiez option, prix, livraison locale et services avant paiement."],["Un lien contrôlé signifie-t-il qualité vérifiée ?","Non. Il confirme seulement la route. La qualité exige des preuves d’entrepôt et reste partiellement inconnue."],["Combien de photos QC gratuites ?","La page d’accueil actuelle annonce trois photos QC gratuites après réception en entrepôt."],["Combien de stockage gratuit ?","La page de frais indique 90 jours gratuits, puis un tarif quotidien par article et une limite standard de 180 jours."],["Puis-je regrouper les commandes ?","Les articles éligibles peuvent être consolidés gratuitement. L’économie dépend du volume, du poids, des restrictions et des lignes."],["Pourquoi l’acompte d’expédition change-t-il ?","Il repose sur poids estimé, ligne et destination, puis est recalculé après vérification de la taille et du poids."],["Les photos prouvent-elles authenticité ou taille ?","Non. Elles documentent le visible, mais pas sûrement authenticité, matière, confort, durée ou coupe."],["Est-ce la plateforme officielle ?","Non. Cette ressource indépendante ne vend pas et ne traite ni paiement ni expédition. Vérifiez toujours les règles du compte."]]
  },
  es: {
    displayDate:"25 ago 2026", updated:"Ruta revisada · 25 ago 2026", copyright:"Investigación independiente en hoja", productNames:["Calzado","Sudadera 55","Camisetas 55","Chaquetas 55","Pantalones / Shorts 55","Accesorios 54"],
    readGuide:"LEER LA GUÍA COMPLETA →", factCheck:"VERIFICACIÓN DE DATOS", nextDecision:"SIGUIENTE DECISIÓN", factChecked:"Datos verificados", checked:"REVISADO", review:"REVISAR", live:"ACTUAL", flow:"Enlace → QC → Paquete",
    legal:"Verifica precio, disponibilidad, opciones y elegibilidad de envío antes de comprar.",
    researchSource:"Base de investigación: guía de Shopping Agent, Servicios y tarifas, Centro de ayuda, flujo oficial y condiciones de Superbuy. Datos revisados el 25 ago 2026; prevalecen las reglas actuales de la cuenta.",
    findsCheckTitle:"Cómo leer cada hallazgo actual", findsCheckText:"Usa las tarjetas como preselección y verifica el destino activo antes de decidir una compra.",
    findsRows:[["Comparar la imagen de origen","Usa la imagen de la tarjeta para identificar el artículo y confirma que el destino activo todavía muestra el mismo producto principal."],["Confirmar la opción exacta","Comprueba color, talla, cantidad, precio y envío del vendedor. Revisar la ruta no fija ninguno de estos datos."],["Separar ruta y calidad","La fecha registra cuándo se revisó el destino. No garantiza calidad, autenticidad ni ajuste."],["Planificar la decisión de almacén","Antes de pedir, decide qué detalle visible, medida o accesorio debe aparecer en las fotos QC para conservar el artículo."]],
    spreadsheetRows:[["Ruta actual","Abre el destino y confirma que todavía corresponde al producto previsto."],["Opción exacta","Registra color, talla, cantidad y texto actual de la opción, no solo el título."],["Coste de primera etapa","Separa precio del artículo, envío nacional en China y servicios opcionales."],["Evidencia de almacén","Registra resultado QC, medidas solicitadas y diferencias visibles."],["Plazo de almacén","Controla la llegada respecto a los 90 días gratuitos actuales."],["Grupo de paquete","Agrupa solo artículos compatibles tras conocer peso, dimensiones y restricciones."],["Siguiente acción","Usa estados claros: revisar, comprar, esperar almacén, pedir evidencia, devolver, paquete o cerrado."]],
    guideRows:[["1 · Enviar producto","Abre la ruta actual, elige la opción exacta y paga el artículo más el envío nacional mostrado."],["2 · Compra del agente","El agente contacta al vendedor y compra el artículo; puede pedir datos faltantes por mensaje o correo."],["3 · Inspección en almacén","Al llegar, el artículo se inspecciona y fotografía. La página actual indica tres fotos QC gratis."],["4 · Decisión de almacenamiento","La guía oficial indica 90 días gratis para esperar otros artículos antes de crear el paquete."],["5 · Enviar paquete","Selecciona artículos elegibles, introduce el destino y compara las líneas disponibles para ese paquete."],["6 · Envío final","Paga el depósito internacional; el importe final se ajusta tras verificar tamaño y peso."]],
    qcRows:[["Identidad primero","Comprueba tipo, modelo, color, cantidad, etiqueta de talla y opción visible."],["Tres fotos estándar","La página actual de Superbuy indica tres fotos QC gratis tras llegar al almacén."],["Medidas","Compara medidas de almacén con un artículo conocido medido en los mismos puntos."],["Construcción visible","Revisa alineación, costuras, impresión, herrajes, suelas, manchas, daños y consistencia del par."],["Evidencia detallada","Pide una foto concreta solo si la vista ausente puede cambiar la decisión."],["Límites del QC","Las fotos no prueban autenticidad, calidad interna, material, comodidad o duración; 1688 usa otra norma QC."]],
    shippingRows:[["Dos etapas de coste","Mantén artículo y envío nacional separados del coste internacional."],["Depósito y coste final","El depósito usa peso estimado, línea y destino; tamaño y peso finales pueden generar un ajuste."],["Peso facturable","Compara peso real y volumétrico porque un paquete ligero y grande puede cobrarse por espacio."],["Consolidación","Los pedidos elegibles pueden consolidarse gratis, pero un paquete grande no siempre es más barato."],["Servicios de embalaje","Retirada de embalaje, refuerzo y seguro deben elegirse según el riesgo."],["Elegibilidad de líneas","Las líneas dependen del destino, atributos, peso, dimensiones y condiciones actuales."],["Aduanas e impuestos","Aranceles, IVA, declaración y restricciones dependen del destino; ninguna hoja garantiza envío sin impuestos."]],
    faqRows:[["¿Qué es una hoja Superbuy?","Un índice independiente que registra rutas, opciones, precios de referencia, preguntas QC y decisiones de paquete."],["¿Superbuy cobra por comprar?","Su página actual indica compra estándar gratuita en Taobao, Tmall, JD.com y 1688. Servicios especiales, de segunda mano y opcionales tienen otras reglas."],["¿Los precios son definitivos?","No. Los importes USD son referencias; confirma opción, precio, envío nacional y servicios antes de pagar."],["¿Enlace revisado significa calidad verificada?","No. Solo confirma la ruta revisada. La calidad requiere evidencia de almacén y mantiene límites."],["¿Cuántas fotos QC gratis?","La página actual de Superbuy indica tres fotos QC gratuitas tras la recepción."],["¿Cuánto almacenamiento gratis?","La página de tarifas indica 90 días gratis, después cargo diario por artículo y máximo estándar de 180 días."],["¿Puedo combinar pedidos?","Los artículos elegibles pueden consolidarse gratis. El ahorro depende de tamaño, peso, restricciones y líneas."],["¿Por qué cambia el depósito de envío?","Usa peso estimado, línea y destino; se recalcula tras verificar tamaño y peso finales."],["¿Las fotos prueban autenticidad o ajuste?","No. Documentan lo visible, pero no garantizan autenticidad, material, comodidad, duración o ajuste."],["¿Es la plataforma oficial?","No. Este recurso independiente no vende ni procesa pagos o envíos. Comprueba siempre las reglas actuales."]]
  },
  it: {
    displayDate:"25 ago 2026", updated:"Rotta verificata · 25 ago 2026", copyright:"Ricerca indipendente su foglio", productNames:["Scarpe","Felpa 55","T-Shirt 55","Giacche 55","Pantaloni / Shorts 55","Accessori 54"],
    readGuide:"LEGGI LA GUIDA COMPLETA →", factCheck:"VERIFICA DEI FATTI", nextDecision:"PROSSIMA DECISIONE", factChecked:"Fatti verificati", checked:"VERIFICATO", review:"DA CONTROLLARE", live:"ATTUALE", flow:"Link → QC → Pacco",
    legal:"Verifica prezzo, disponibilità, opzioni e idoneità di spedizione prima dell’ordine.",
    researchSource:"Base di ricerca: guida Shopping Agent, Servizi e tariffe, Centro assistenza, flusso ufficiale e condizioni Superbuy. Fatti verificati il 25 ago 2026; prevalgono le regole correnti dell’account.",
    findsCheckTitle:"Come leggere ogni selezione attuale", findsCheckText:"Usa le schede come preselezione e verifica la destinazione attiva prima di decidere l’acquisto.",
    findsRows:[["Confronta l’immagine sorgente","Usa l’immagine della scheda per identificare l’articolo e conferma che la destinazione attiva mostri ancora lo stesso prodotto principale."],["Conferma l’opzione esatta","Controlla colore, taglia, quantità, prezzo e spedizione del venditore. La verifica della rotta non blocca questi dati."],["Separa rotta e qualità","La data indica quando è stata controllata la destinazione. Non garantisce qualità, autenticità o vestibilità."],["Pianifica la decisione in magazzino","Prima dell’ordine, decidi quale dettaglio visibile, misura o accessorio deve comparire nelle foto QC per conservare l’articolo."]],
    spreadsheetRows:[["Rotta attuale","Apri la destinazione e conferma che porti ancora al prodotto previsto."],["Opzione esatta","Registra colore, taglia, quantità e testo corrente dell’opzione, non solo il titolo."],["Costo prima fase","Separa prezzo articolo, spedizione nazionale cinese e servizi opzionali."],["Prove di magazzino","Registra esito QC, misure richieste e differenze visibili."],["Finestra di deposito","Controlla l’arrivo rispetto agli attuali 90 giorni gratuiti."],["Gruppo pacco","Raggruppa solo articoli compatibili dopo peso, dimensioni e restrizioni."],["Azione successiva","Usa stati chiari: controllare, acquistare, attendere, chiedere prove, restituire, pacco o chiuso."]],
    guideRows:[["1 · Invia il prodotto","Apri la rotta attuale, scegli l’opzione esatta e paga articolo più spedizione nazionale mostrata."],["2 · Acquisto dell’agente","L’agente contatta il venditore e acquista; può chiedere informazioni mancanti via messaggio o e-mail."],["3 · Controllo in magazzino","All’arrivo, l’articolo viene ispezionato e fotografato. La pagina attuale indica tre foto QC gratuite."],["4 · Decisione di deposito","La guida ufficiale indica 90 giorni gratuiti per attendere altri articoli prima del pacco."],["5 · Invia il pacco","Seleziona articoli idonei, inserisci la destinazione e confronta le linee mostrate per quel pacco."],["6 · Spedizione finale","Paga il deposito internazionale; l’importo finale viene regolato dopo verifica di dimensioni e peso."]],
    qcRows:[["Prima l’identità","Controlla tipo, modello, colore, quantità, etichetta taglia e opzione visibile."],["Tre foto standard","La pagina attuale Superbuy indica tre foto QC gratuite dopo l’arrivo in magazzino."],["Misure","Confronta le misure di magazzino con un articolo noto misurato negli stessi punti."],["Costruzione visibile","Controlla allineamento, cuciture, stampa, ferramenta, suole, macchie, danni e coerenza della coppia."],["Prova dettagliata","Richiedi una foto mirata solo se la vista mancante può cambiare la decisione."],["Limiti QC","Le foto non provano autenticità, qualità interna, materiale, comfort o durata; 1688 usa uno standard QC diverso."]],
    shippingRows:[["Due fasi di costo","Mantieni articolo e spedizione nazionale separati dal costo internazionale."],["Deposito e importo finale","Il deposito usa peso stimato, linea e destinazione; dimensioni e peso finali possono generare una rettifica."],["Peso fatturabile","Confronta peso reale e volumetrico perché un pacco leggero e grande può essere tariffato per spazio."],["Consolidamento","Gli ordini idonei possono essere consolidati gratis, ma un grande pacco non è sempre più economico."],["Servizi di imballaggio","Rimozione imballo, rinforzo e assicurazione vanno scelti in base al rischio."],["Idoneità delle linee","Le linee dipendono da destinazione, attributi, peso, dimensioni e condizioni correnti."],["Dogana e tasse","Dazi, IVA, dichiarazioni e limiti dipendono dalla destinazione; nessun foglio garantisce consegna senza tasse."]],
    faqRows:[["Cos’è un foglio Superbuy?","Un indice indipendente che registra rotte, opzioni, riferimenti di prezzo, domande QC e decisioni sul pacco."],["Superbuy applica una commissione d’acquisto?","La pagina attuale indica servizio standard gratuito su Taobao, Tmall, JD.com e 1688. Servizi speciali, usato e opzioni hanno altre regole."],["I prezzi sono definitivi?","No. Gli importi USD sono riferimenti; verifica opzione, prezzo, spedizione nazionale e servizi prima di pagare."],["Link controllato significa qualità verificata?","No. Conferma solo la rotta. La qualità richiede prove di magazzino e conserva limiti."],["Quante foto QC gratuite?","La pagina attuale Superbuy indica tre foto QC gratuite dopo l’arrivo."],["Quanto deposito gratuito?","La pagina tariffe indica 90 giorni gratuiti, poi costo giornaliero per articolo e massimo standard di 180 giorni."],["Posso combinare ordini?","Gli articoli idonei possono essere consolidati gratis. Il risparmio dipende da dimensioni, peso, limiti e linee."],["Perché cambia il deposito di spedizione?","Usa peso stimato, linea e destinazione; viene ricalcolato dopo verifica di dimensioni e peso."],["Le foto provano autenticità o vestibilità?","No. Documentano il visibile, ma non garantiscono autenticità, materiale, comfort, durata o vestibilità."],["È la piattaforma ufficiale?","No. Questa risorsa indipendente non vende e non gestisce pagamenti o spedizioni. Verifica sempre le regole correnti."]]
  }
};
