import type { Article } from "./articles-data";
import type { Language } from "./site-data";

export const spreadsheetMaintenanceArticles: Record<Language, Article> = {
  en: {
    slug: "build-reliable-sugargoo-spreadsheet-fields-dates-evidence",
    title: "Build a Reliable Sugargoo Spreadsheet: Essential Fields, Dates and Evidence",
    dek: "A maintenance system for product routes, variants, price-check dates, evidence limits and change history—without treating a spreadsheet entry as a quality guarantee.",
    label: "Spreadsheet data control", published: "September 2, 2026", readTime: "14 min read", primaryKeyword: "Sugargoo spreadsheet maintenance",
    sourceLine: "Research checked September 2, 2026 against Sugargoo's current public buying, QC, warehouse and shipping guidance; variable fields must be rechecked in the live interface.",
    visual: { title: "The minimum trustworthy record", items: [
      {label:"Identity",value:"Platform + product ID",note:"A title alone is not unique"},
      {label:"Selection",value:"Variant snapshot",note:"Colour, size, version and quantity"},
      {label:"Freshness",value:"Last checked date",note:"Price and availability can change"},
      {label:"Evidence",value:"Source + limitation",note:"Record what the evidence can prove"}
    ]},
    sections: [
      {heading:"Define the spreadsheet as a dated research index",body:["A reliable Sugargoo spreadsheet is not a permanent catalogue and it is not a promise that a product is available, accurate or good. It is a dated index of routes you researched. Each row should help another reader reopen the same source, identify the intended option, see when key fields were checked and understand which claims remain unverified. That definition changes the maintenance goal: preserve traceability rather than keeping every cell looking complete.","Separate discovery from purchase evidence. A card or source listing can support a product route, displayed option and checked price at a particular moment. It cannot prove what a seller will dispatch, what the warehouse will receive or which international line will accept the eventual parcel. Those later facts belong to order, QC and parcel records. Linking the records is useful; collapsing them into one ‘verified’ label is misleading."]},
      {heading:"Give every row a stable identity block",body:["Begin with source platform, original product URL, product ID or item code where visible, seller or shop URL, internal row ID and the date the route was opened successfully. Keep the original URL rather than only a redirected purchasing link. A product title is descriptive, not unique: sellers can reuse titles, listings can change and two options under one page may be materially different. The identity block should survive a later price or title update.","Use status values that describe the route, not the product: active when the exact page opens and the intended option is visible; changed when an important field differs from the saved record; unavailable when the page or option cannot be selected; and review needed when the result is ambiguous. Never upgrade active to ‘trusted seller’ or ‘verified quality’. Route access proves access. It does not certify the seller, stock, material, batch or received unit."]},
      {heading:"Capture the exact variant without ambiguous shorthand",body:["Create separate columns for seller option text, your normalized colour, size, version or model, quantity, and any customization. Save the option as displayed as well as your interpretation. ‘Black M’ may be clear in one language but ambiguous when a listing combines a colour code, model name and size. A screenshot or short text snapshot should show which selector values produced the checked price. If the listing has no clear option mapping, label the row review needed rather than guessing.","Variant records should be atomic. One row can represent one exact option or a parent row can link to child rows for each option, but a single row should not silently blend prices, weights or QC concerns across many versions. If ten colours share a page, do not assume they share stock or the same photographed details. Record only the option you actually checked, then add other variants as separate observations when they matter."]},
      {heading:"Timestamp price and availability as observations",body:["Use fields for displayed item price, currency, quantity used for that price, domestic delivery when shown, option selected, check date and evidence reference. Keep item price separate from total buying cost. A spreadsheet cannot know the final payment amount without current option pricing, domestic freight, applicable service choices, payment conversion and later international shipping. If a value is missing, use unknown—not zero—because zero falsely lowers comparisons.","A change policy makes maintenance consistent. Recheck a row before featuring it, before using it in a shortlist and before purchase. Log the new observation rather than overwriting history invisibly: previous value, new value, timestamp, field changed and reviewer note. Small price differences can be noise; a different product ID, seller, minimum quantity or option structure is a route change. Preserve the former record so readers can see why the status changed."]},
      {heading:"Add evidence fields and explicit confidence limits",body:["For each meaningful claim, store evidence type, capture date, source location and limitation. A source listing can evidence seller-presented specifications and current selector text. Warehouse QC images can evidence visible identity and condition of one received unit. A tape photograph can evidence a visible measurement if placement and scale are readable. None of these alone proves authenticity, composition, durability or that every future batch will match.","Use confidence labels tied to completeness, not product quality. Complete identity means platform, product ID, route and seller are recorded. Complete variant means the exact selection and quantity are unambiguous. Fresh price means the chosen option was checked within your stated review interval. Adequate evidence means the claim has a relevant source and limitation. A row may score highly for data completeness while the product remains an uncertain purchase; that distinction is the point."]},
      {heading:"Record QC focus and shipping attributes as questions",body:["Before purchase, add a QC-focus field that converts category risks into answerable checks. Shoes may need pair symmetry, size labels, insole length, sole alignment and included accessories. Clothing may need measured width and length, print placement or embroidery edges. Bags may need dimensions, closure, strap attachments and hardware count. These are inspection priorities, not claims that a defect exists or that a standard photo set will answer everything.","Add a shipping-attribute field only for evidence you can support: visible battery, liquid, fragile construction, magnet, unusually large form or another attribute shown in the current source. Mark unconfirmed when uncertain. Route eligibility, fees, volumetric treatment and restrictions are live parcel-stage decisions, so the spreadsheet should direct the reader to recheck the current estimator or parcel interface rather than publishing a fixed route recommendation."]},
      {heading:"Use a change log that preserves dead routes",body:["Do not delete a row merely because the source dies. Change its status, record the failure date and reason, and keep its product ID, seller and prior evidence. A dead route is useful history: it prevents the same broken link from being re-added and shows whether a replacement is truly the same source or only a similar image. If you add a replacement, give it a new row and link it to the former row with a relationship such as alternative—not identical.","Schedule reviews by risk. Featured rows and volatile options deserve more frequent checks than archived research. Rows with no product ID, unclear variants, old prices or unexplained seller changes go to the top of the queue. Use a dashboard count for active, review needed, changed and unavailable rows, but always allow the underlying dated evidence to explain the count. A green dashboard without auditable rows is decoration."]},
      {heading:"Run the publication audit before a row goes live",body:["Confirm that the route opens, the source platform and product ID agree, the exact option is selectable, price evidence carries a date, unknown costs are not shown as zero, image rights are clear and no row claims verified quality. Check that any item image maps to the recorded source and that descriptive text does not turn a seller statement into an editorial fact. Remove private order data, addresses, payment details and tracking numbers from public records.","Finish with four decisions: publish when identity, option and date are clear; publish with a warning when the route works but an important field remains explicitly unknown; hold when the option mapping is ambiguous; archive when the route no longer supports the record. This system makes a finds database useful without pretending it is timeless. The best Sugargoo spreadsheet maintenance habit is not adding more rows—it is making every surviving row explain what was checked, when, and what still needs verification."]}
    ]
  },
  de: {
    slug:"build-reliable-sugargoo-spreadsheet-fields-dates-evidence",title:"Eine verlässliche Sugargoo-Tabelle: Felder, Daten und Belege",dek:"Ein Pflegesystem für Produktwege, Varianten, Preisprüfdaten, Beleggrenzen und Änderungshistorie – ohne Qualitätsgarantie.",label:"Spreadsheet-Datenkontrolle",published:"2. September 2026",readTime:"14 Min. Lesezeit",primaryKeyword:"Sugargoo Spreadsheet Pflege",sourceLine:"Recherche am 2. September 2026 anhand aktueller öffentlicher Sugargoo-Hinweise geprüft; variable Felder sind live zu bestätigen.",visual:{title:"Der kleinste verlässliche Datensatz",items:[{label:"Identität",value:"Plattform + Produkt-ID",note:"Titel sind nicht eindeutig"},{label:"Auswahl",value:"Varianten-Snapshot",note:"Farbe, Größe, Version, Menge"},{label:"Aktualität",value:"Letztes Prüfdatum",note:"Preis und Bestand ändern sich"},{label:"Beleg",value:"Quelle + Grenze",note:"Nur Nachweisbares behaupten"}]},sections:[
      {heading:"Die Tabelle als datierten Rechercheindex definieren",body:["Eine verlässliche Sugargoo-Tabelle ist weder ewiger Katalog noch Versprechen zu Verfügbarkeit, Richtigkeit oder Qualität. Sie ist ein datierter Index recherchierter Wege. Jede Zeile muss dieselbe Quelle wieder öffnen, die geplante Option identifizieren, Prüfdaten zeigen und Ungeklärtes benennen. Ziel ist Rückverfolgbarkeit, nicht scheinbar vollständige Zellen.","Trennen Sie Entdeckung und Kaufbeleg. Listing oder Karte belegen zu einem Zeitpunkt Route, Option und angezeigten Preis. Sie beweisen nicht, was versandt, im Lager empfangen oder für eine internationale Linie zugelassen wird. Diese Fakten gehören in Bestell-, QC- und Paketdaten. Verknüpfen ist sinnvoll; ein gemeinsames ‘verifiziert’ ist irreführend."]},
      {heading:"Jeder Zeile einen stabilen Identitätsblock geben",body:["Erfassen Sie Plattform, Original-URL, sichtbare Produkt-ID, Verkäufer- oder Shop-URL, interne Zeilen-ID und Datum des erfolgreichen Öffnens. Bewahren Sie die Originaladresse statt nur eines Einkaufs-Redirects. Ein Titel ist nicht eindeutig; Verkäufer verwenden ihn erneut und Optionen unterscheiden sich. Die Identität muss Preis- und Titeländerungen überstehen.","Status beschreibt die Route: aktiv, wenn Seite und Option sichtbar sind; geändert bei abweichenden Kernfeldern; nicht verfügbar bei fehlender Auswahl; Prüfung nötig bei Mehrdeutigkeit. Machen Sie daraus nie ‘vertrauenswürdiger Verkäufer’ oder ‘geprüfte Qualität’. Zugriff zertifiziert weder Bestand, Material, Charge noch empfangene Einheit."]},
      {heading:"Die exakte Variante ohne Kürzel erfassen",body:["Separate Spalten für Verkäufertext, normalisierte Farbe, Größe, Version oder Modell, Menge und Anpassung. Speichern Sie Original und Interpretation. ‘Schwarz M’ kann bei Farbcode, Modell und Größe mehrdeutig sein. Ein Snapshot muss zeigen, welche Auswahl den Preis erzeugte. Bei unklarer Zuordnung: Prüfung nötig, nicht raten.","Varianten bleiben atomar. Eine Zeile steht für eine Option oder ein Elternsatz verknüpft einzelne Kindzeilen. Vermischen Sie Preise, Gewichte und QC-Fragen nicht über Versionen. Zehn Farben auf einer Seite bedeuten nicht gleichen Bestand oder gleiche Details. Erfassen Sie nur wirklich Geprüftes."]},
      {heading:"Preis und Verfügbarkeit als Beobachtung datieren",body:["Felder: Artikelpreis, Währung, Preis-Menge, sichtbarer Inlandsversand, gewählte Option, Datum und Beleg. Trennen Sie Artikelpreis vom Gesamtkauf. Ohne aktuelle Option, Inlandsfracht, Dienste, Umrechnung und spätere internationale Fracht ist kein Endbetrag bekannt. Unbekannt ist nicht null.","Protokollieren Sie neue Beobachtungen statt Historie zu überschreiben: alter Wert, neuer Wert, Zeitpunkt, Feld und Notiz. Vor Hervorhebung, Shortlist und Kauf erneut prüfen. Eine neue Produkt-ID, Verkäufer, Mindestmenge oder Optionsstruktur ist ein Routenwechsel. Der alte Satz erklärt später den Status."]},
      {heading:"Belegfelder und Grenzen ergänzen",body:["Speichern Sie je Aussage Belegtyp, Datum, Ort und Grenze. Das Listing belegt Verkäuferangaben und Auswahltext. Lagerbilder belegen sichtbare Identität und Zustand einer Einheit. Ein Maßfoto belegt eine lesbare Messung. Nichts davon allein beweist Echtheit, Zusammensetzung, Haltbarkeit oder zukünftige Chargen.","Bewerten Sie Datenvollständigkeit, nicht Qualität: vollständige Identität, eindeutige Variante, frischer Preis und passender Beleg. Eine Datenzeile kann vollständig und der Kauf dennoch unsicher sein. Genau diese Trennung macht die Bewertung ehrlich."]},
      {heading:"QC-Fokus und Versandattribute als Fragen führen",body:["Formulieren Sie prüfbare QC-Prioritäten. Schuhe: Paarsymmetrie, Größenetikett, Einlegesohlenlänge, Sohle, Zubehör. Kleidung: Maße, Druckposition, Stickkante. Taschen: Abmessungen, Verschluss, Riemenansatz, Metallteile. Das sind Fragen, keine behaupteten Mängel und keine Zusage, dass Standardbilder alles zeigen.","Tragen Sie Versandattribute nur mit Beleg ein: Batterie, Flüssigkeit, zerbrechlich, Magnet, großes Format oder sichtbares Merkmal. Sonst ‘unbestätigt’. Routen, Gebühren, Volumenbehandlung und Grenzen sind Live-Paketentscheidungen; die Tabelle verweist auf aktuelle Prüfung statt feste Empfehlung."]},
      {heading:"Tote Wege im Änderungsprotokoll erhalten",body:["Löschen Sie eine Zeile nicht bei toter Quelle. Ändern Sie Status, Ausfalldatum und Grund, behalten Sie ID, Verkäufer und alte Belege. Historie verhindert erneutes Hinzufügen und zeigt, ob Ersatz identisch oder nur ähnlich ist. Ersatz erhält eine neue Zeile mit Beziehung ‘Alternative’, nicht ‘identisch’.","Prüfen Sie nach Risiko. Hervorgehobene und volatile Optionen häufiger als Archive. Fehlende ID, unklare Variante, alter Preis oder Verkäuferwechsel kommen nach oben. Ein Dashboard darf Zustände zählen, muss aber auf datierte Belege führen. Grün ohne Audit ist Dekoration."]},
      {heading:"Vor Veröffentlichung die Zeile auditieren",body:["Prüfen Sie Route, Plattform, ID, wählbare Option, datierten Preis, unbekannte Kosten statt Null, Bildrechte und fehlende Qualitätsbehauptungen. Bild und Quelle müssen zusammenpassen; Verkäufertext darf nicht zu redaktioneller Tatsache werden. Entfernen Sie private Bestellung, Adresse, Zahlung und Tracking.","Vier Entscheidungen: veröffentlichen bei klarer Identität, Option und Datum; mit Warnung bei ausdrücklich unbekanntem Feld; halten bei mehrdeutiger Zuordnung; archivieren bei nicht mehr passender Route. Gute Pflege bedeutet nicht mehr Zeilen, sondern dass jede erklärt, was wann geprüft wurde und was offen bleibt."]}
    ]},
  es: {
    slug:"build-reliable-sugargoo-spreadsheet-fields-dates-evidence",title:"Crea una hoja Sugargoo fiable: campos, fechas y pruebas",dek:"Sistema de mantenimiento para rutas, variantes, fechas de precio, límites de evidencia e historial, sin prometer calidad.",label:"Control de datos",published:"2 de septiembre de 2026",readTime:"14 min de lectura",primaryKeyword:"mantenimiento hoja Sugargoo",sourceLine:"Investigación revisada el 2 de septiembre de 2026 con guías públicas actuales; los campos variables deben confirmarse en directo.",visual:{title:"El registro mínimo fiable",items:[{label:"Identidad",value:"Plataforma + ID",note:"El título no es único"},{label:"Selección",value:"Captura de variante",note:"Color, talla, versión, cantidad"},{label:"Vigencia",value:"Fecha revisada",note:"Precio y disponibilidad cambian"},{label:"Prueba",value:"Fuente + límite",note:"Solo demuestra lo registrado"}]},sections:[
      {heading:"Define la hoja como índice de investigación fechado",body:["Una hoja Sugargoo fiable no es catálogo permanente ni promesa de disponibilidad, exactitud o calidad. Es un índice fechado de rutas investigadas. Cada fila debe reabrir la fuente, identificar opción, mostrar fechas y dejar claros los límites. El objetivo es trazabilidad, no rellenar todas las celdas.","Separa descubrimiento y compra. Una ficha prueba ruta, opción y precio mostrado en un momento. No prueba qué enviará el vendedor, qué recibirá el almacén ni qué línea aceptará el paquete. Eso pertenece a registros de pedido, QC y envío. Vincularlos ayuda; llamarlo todo ‘verificado’ engaña."]},
      {heading:"Da a cada fila una identidad estable",body:["Registra plataforma, URL original, ID visible, página del vendedor, ID interno y fecha de apertura. Conserva la fuente, no solo un redireccionamiento. Un título no es único: puede reutilizarse y las opciones cambian. La identidad debe sobrevivir a precio o nombre nuevos.","El estado describe la ruta: activa si abre y muestra opción; cambiada si difiere un campo; no disponible si no se selecciona; revisar si hay ambigüedad. Nunca lo conviertas en vendedor fiable o calidad verificada. Acceso no certifica stock, material, lote ni unidad recibida."]},
      {heading:"Captura la variante exacta",body:["Usa columnas para texto del vendedor, color normalizado, talla, versión, cantidad y personalización. Guarda texto e interpretación. ‘Negro M’ puede mezclar código, modelo y talla. Una captura debe mostrar qué selectores produjeron el precio. Si no se entiende, marca revisar.","Una fila representa una opción exacta o enlaza filas hijas. No mezcles precios, pesos o riesgos entre versiones. Diez colores en una página no comparten necesariamente stock o detalles. Solo registra la opción realmente comprobada."]},
      {heading:"Fecha precio y disponibilidad como observaciones",body:["Guarda precio, moneda, cantidad, entrega nacional visible, opción, fecha y prueba. El precio del artículo no es coste total. Faltan transporte nacional, servicios, conversión y envío internacional. Usa desconocido, no cero.","Vuelve a revisar antes de destacar, comparar y comprar. Añade valor anterior, nuevo, hora, campo y nota en vez de borrar historia. ID, vendedor, MOQ o estructura nuevos son cambio de ruta. El registro anterior explica la decisión."]},
      {heading:"Añade pruebas con límites explícitos",body:["Por afirmación registra tipo, fecha, ubicación y límite. El anuncio prueba especificaciones declaradas. QC prueba identidad y condición visible de una unidad. Una cinta legible prueba una medida. Nada prueba por sí solo autenticidad, composición, duración o futuros lotes.","Puntúa integridad de datos, no calidad: identidad completa, variante clara, precio reciente y prueba pertinente. Una fila puede estar completa y el producto seguir incierto; esa separación es necesaria."]},
      {heading:"Formula QC y atributos de envío como preguntas",body:["Convierte riesgos en controles: zapatos, simetría, talla, plantilla, suela y accesorios; ropa, medidas y colocación; bolsos, dimensiones, cierre, correas y piezas. Son prioridades, no defectos afirmados ni promesa de que las fotos estándar respondan.","Marca batería, líquido, frágil, imán o volumen solo con evidencia; si no, sin confirmar. Rutas, tarifas, volumen y restricciones se deciden en la interfaz actual del paquete, no con recomendación fija en la hoja."]},
      {heading:"Conserva rutas muertas en el historial",body:["No borres una ruta caída. Registra estado, fecha y motivo, manteniendo ID, vendedor y pruebas. Evita reintroducirla y permite comparar un reemplazo. El reemplazo recibe fila nueva y relación alternativa, no idéntica.","Revisa según riesgo. Destacados y opciones volátiles primero; archivos después. Sin ID, variante dudosa, precio antiguo o vendedor cambiado suben en prioridad. El panel debe enlazar a las pruebas fechadas."]},
      {heading:"Audita antes de publicar",body:["Confirma apertura, plataforma, ID, opción, precio fechado, desconocidos no convertidos en cero, derechos de imagen y ausencia de promesas de calidad. El texto del vendedor no es hecho editorial. Elimina pedido, dirección, pago y tracking privados.","Publica con identidad, opción y fecha claras; publica con aviso si lo desconocido está explícito; retén si la opción es ambigua; archiva si la ruta dejó de corresponder. El mejor mantenimiento no añade más filas: hace que cada una diga qué se revisó, cuándo y qué falta."]}
    ]},
  fr: {
    slug:"build-reliable-sugargoo-spreadsheet-fields-dates-evidence",title:"Construire un tableur Sugargoo fiable : champs, dates et preuves",dek:"Un système de maintenance pour routes, variantes, dates de prix, limites de preuve et historique, sans garantie de qualité.",label:"Contrôle des données",published:"2 septembre 2026",readTime:"14 min de lecture",primaryKeyword:"maintenance tableur Sugargoo",sourceLine:"Recherche vérifiée le 2 septembre 2026 avec les guides publics actuels ; confirmer les champs variables dans l’interface active.",visual:{title:"Le dossier fiable minimal",items:[{label:"Identité",value:"Plateforme + ID",note:"Le titre n’est pas unique"},{label:"Sélection",value:"Capture de variante",note:"Couleur, taille, version, quantité"},{label:"Actualité",value:"Date de contrôle",note:"Prix et disponibilité changent"},{label:"Preuve",value:"Source + limite",note:"Ne prouve que le champ"}]},sections:[
      {heading:"Définir le tableur comme index daté",body:["Un tableur Sugargoo fiable n’est ni catalogue permanent ni promesse de disponibilité, exactitude ou qualité. C’est un index daté de routes étudiées. Chaque ligne doit rouvrir la source, identifier l’option, montrer les dates et déclarer l’inconnu. Le but est la traçabilité, pas des cellules artificiellement remplies.","Séparez découverte et achat. Une fiche prouve route, option et prix affiché à un moment. Elle ne prouve pas ce que le vendeur enverra, ce que l’entrepôt recevra ou quelle ligne acceptera le colis. Ces faits appartiennent aux dossiers commande, QC et colis. Les relier aide ; tout appeler ‘vérifié’ trompe."]},
      {heading:"Donner une identité stable à chaque ligne",body:["Enregistrez plateforme, URL originale, ID visible, page vendeur, ID interne et date d’ouverture. Gardez la source, pas seulement une redirection. Un titre n’est pas unique ; vendeurs et options changent. L’identité doit survivre à un nouveau prix ou titre.","Le statut décrit la route : active si page et option sont accessibles ; modifiée si un champ change ; indisponible si l’option disparaît ; à revoir si ambiguë. N’en faites jamais un vendeur fiable ou une qualité vérifiée. L’accès ne certifie ni stock, matière, lot ni unité reçue."]},
      {heading:"Capturer la variante exacte",body:["Utilisez des colonnes pour texte vendeur, couleur normalisée, taille, version, quantité et personnalisation. Gardez texte et interprétation. ‘Noir M’ peut mélanger code, modèle et taille. Une capture montre quels sélecteurs donnent le prix. Si la correspondance est floue, marquez à revoir.","Une ligne représente une option précise ou relie des lignes enfants. Ne mélangez pas prix, poids ou risques entre versions. Dix couleurs ne partagent pas forcément stock et détails. N’enregistrez que l’option réellement contrôlée."]},
      {heading:"Dater prix et disponibilité",body:["Stockez prix, devise, quantité, livraison intérieure visible, option, date et preuve. Le prix article n’est pas le coût total : transport intérieur, services, conversion et international restent séparés. Inconnu ne veut pas dire zéro.","Recontrôlez avant mise en avant, sélection et achat. Ajoutez ancien, nouveau, heure, champ et note sans effacer l’historique. Nouvel ID, vendeur, minimum ou structure signifie route différente. L’ancien dossier explique le changement."]},
      {heading:"Ajouter des preuves et leurs limites",body:["Pour chaque affirmation, indiquez type, date, emplacement et limite. La fiche prouve les spécifications du vendeur. Le QC prouve l’identité et l’état visible d’une unité. Une photo de ruban lisible prouve une mesure. Rien ne prouve seul authenticité, composition, durée ou futurs lots.","Évaluez la complétude des données, pas la qualité : identité complète, variante claire, prix récent, preuve pertinente. Une ligne peut être complète et l’achat rester incertain. Cette distinction protège la décision."]},
      {heading:"Formuler QC et attributs d’envoi comme questions",body:["Transformez les risques en contrôles : chaussures, paire, étiquette, semelle intérieure, semelle et accessoires ; vêtements, mesures et placement ; sacs, dimensions, fermeture, attaches et pièces. Ce sont des priorités, pas des défauts affirmés ni une promesse photographique.","N’indiquez batterie, liquide, fragile, aimant ou volume qu’avec preuve ; sinon non confirmé. Routes, tarifs, poids volumétrique et restrictions sont des décisions de colis actives, pas des recommandations fixes du tableur."]},
      {heading:"Conserver les routes mortes",body:["Ne supprimez pas une source morte. Notez statut, date et raison, gardez ID, vendeur et preuves. L’historique empêche sa réintroduction et distingue un remplacement similaire d’une source identique. Le remplacement a une nouvelle ligne liée comme alternative.","Révisez selon le risque. Les éléments en vedette et variantes volatiles d’abord ; archives ensuite. ID absent, variante floue, vieux prix ou changement vendeur montent dans la file. Le tableau de bord doit renvoyer aux preuves datées."]},
      {heading:"Auditer avant publication",body:["Confirmez ouverture, plateforme, ID, option, prix daté, inconnus non remplacés par zéro, droits d’image et absence de promesse de qualité. Une déclaration vendeur ne devient pas un fait éditorial. Retirez commande, adresse, paiement et suivi privés.","Publiez si identité, option et date sont claires ; publiez avec avertissement si l’inconnu est explicite ; retenez si la variante est ambiguë ; archivez si la route ne correspond plus. Une bonne maintenance n’ajoute pas seulement des lignes : chacune explique quoi, quand et ce qui reste à vérifier."]}
    ]},
  it: {
    slug:"build-reliable-sugargoo-spreadsheet-fields-dates-evidence",title:"Crea un foglio Sugargoo affidabile: campi, date e prove",dek:"Sistema di manutenzione per percorsi, varianti, date prezzo, limiti delle prove e storico, senza garanzie di qualità.",label:"Controllo dati",published:"2 settembre 2026",readTime:"14 min di lettura",primaryKeyword:"manutenzione foglio Sugargoo",sourceLine:"Ricerca verificata il 2 settembre 2026 sulle guide pubbliche attuali; i campi variabili vanno confermati live.",visual:{title:"Il record minimo affidabile",items:[{label:"Identità",value:"Piattaforma + ID",note:"Il titolo non è unico"},{label:"Selezione",value:"Snapshot variante",note:"Colore, taglia, versione, quantità"},{label:"Attualità",value:"Data controllo",note:"Prezzo e disponibilità cambiano"},{label:"Prova",value:"Fonte + limite",note:"Dimostra solo il campo"}]},sections:[
      {heading:"Definisci il foglio come indice datato",body:["Un foglio Sugargoo affidabile non è catalogo permanente né promessa di disponibilità, accuratezza o qualità. È un indice datato di percorsi studiati. Ogni riga deve riaprire la fonte, identificare l’opzione, mostrare date e dichiarare i limiti. L’obiettivo è tracciabilità, non celle apparentemente complete.","Separa scoperta e acquisto. Una scheda prova percorso, opzione e prezzo mostrato in un momento. Non prova cosa spedirà il venditore, cosa riceverà il magazzino o quale linea accetterà il pacco. Questi fatti appartengono a ordine, QC e pacco. Collegarli aiuta; chiamare tutto ‘verificato’ inganna."]},
      {heading:"Dai a ogni riga un’identità stabile",body:["Registra piattaforma, URL originale, ID visibile, pagina venditore, ID interno e data di apertura. Mantieni la fonte e non solo un redirect. Il titolo non è unico; venditori e opzioni cambiano. L’identità deve restare dopo variazioni di prezzo o nome.","Lo stato descrive il percorso: attivo se pagina e opzione aprono; cambiato se un campo differisce; non disponibile se non selezionabile; da rivedere se ambiguo. Non trasformarlo in venditore affidabile o qualità verificata. L’accesso non certifica stock, materiale, lotto o unità ricevuta."]},
      {heading:"Cattura la variante esatta",body:["Usa colonne per testo venditore, colore normalizzato, taglia, versione, quantità e personalizzazione. Salva testo e interpretazione. ‘Nero M’ può mescolare codice, modello e misura. Uno snapshot deve mostrare i selettori del prezzo. Se la mappa è poco chiara, segna da rivedere.","Una riga rappresenta un’opzione o collega righe figlie. Non mescolare prezzi, pesi o rischi tra versioni. Dieci colori non condividono necessariamente stock o dettagli. Registra solo l’opzione davvero controllata."]},
      {heading:"Data prezzo e disponibilità",body:["Salva prezzo, valuta, quantità, consegna interna visibile, opzione, data e prova. Il prezzo articolo non è costo totale: trasporto interno, servizi, conversione e invio internazionale sono separati. Sconosciuto non significa zero.","Ricontrolla prima di evidenziare, selezionare e comprare. Aggiungi vecchio, nuovo, ora, campo e nota senza cancellare la storia. Nuovo ID, venditore, minimo o struttura significa percorso cambiato. Il vecchio record spiega la decisione."]},
      {heading:"Aggiungi prove e limiti espliciti",body:["Per ogni affermazione registra tipo, data, posizione e limite. L’inserzione prova specifiche dichiarate. Il QC prova identità e condizione visibile di un’unità. Una foto con metro leggibile prova una misura. Nulla prova da solo autenticità, composizione, durata o lotti futuri.","Valuta completezza dei dati, non qualità: identità, variante, prezzo recente e prova pertinente. Una riga può essere completa mentre l’acquisto resta incerto. È una distinzione necessaria."]},
      {heading:"Scrivi QC e attributi di spedizione come domande",body:["Trasforma i rischi in controlli: scarpe, simmetria, taglia, soletta, suola e accessori; abiti, misure e posizione; borse, dimensioni, chiusura, attacchi e pezzi. Sono priorità, non difetti dichiarati né promessa che le foto standard rispondano.","Segna batteria, liquido, fragile, magnete o volume solo con prova; altrimenti non confermato. Rotte, tariffe, volume e limiti sono decisioni live del pacco, non raccomandazioni fisse del foglio."]},
      {heading:"Conserva i percorsi morti",body:["Non cancellare una fonte morta. Registra stato, data e motivo, mantenendo ID, venditore e prove. La storia evita di riaggiungerla e distingue un sostituto simile da uno identico. Il sostituto ha nuova riga collegata come alternativa.","Controlla per rischio. Elementi in evidenza e opzioni volatili prima degli archivi. ID mancante, variante incerta, vecchio prezzo o cambio venditore salgono in coda. Il pannello deve portare alle prove datate."]},
      {heading:"Fai l’audit prima di pubblicare",body:["Conferma apertura, piattaforma, ID, opzione, prezzo datato, sconosciuti non trasformati in zero, diritti immagini e nessuna promessa di qualità. Una frase del venditore non diventa fatto editoriale. Rimuovi ordine, indirizzo, pagamento e tracking privati.","Pubblica con identità, opzione e data chiare; con avviso se l’incognito è esplicito; sospendi se la variante è ambigua; archivia se la rotta non corrisponde. La buona manutenzione non aggiunge solo righe: ciascuna spiega cosa è stato controllato, quando e cosa manca."]}
    ]}
};
