import { Locale } from "@/lib/site-data";
import { extraArticles } from "@/lib/articles-extra";
import { fullLocalizedArticles } from "@/lib/articles-full";

export const articleSlugs = [
  "sugargoo-spreadsheet-guide-2026",
  "sugargoo-qc-photo-checklist",
  "sugargoo-shipping-weight-guide-2026",
  "sugargoo-review-2026",
] as const;
export type ArticleSlug = (typeof articleSlugs)[number];
export function isArticleSlug(value: string): value is ArticleSlug { return articleSlugs.includes(value as ArticleSlug); }

export type Article = { title: string; description: string; category: string; readTime: string; published: string; sections: { heading: string; paragraphs: string[] }[] };

export const articles: Record<Locale, Record<ArticleSlug, Article>> = {
  en: {
    "sugargoo-shipping-weight-guide-2026": {
      title: "Sugargoo Shipping in 2026: Actual Weight, Volumetric Weight and Better Parcel Decisions",
      description: "A practical guide to chargeable weight, packaging, consolidation and route comparison before submitting an international parcel.",
      category: "Shipping strategy", readTime: "12 min read", published: "August 31, 2026",
      sections: [
        { heading: "Why a kilogram is not always a kilogram", paragraphs: [
          "The number on a warehouse scale is only one part of an international shipping calculation. Many parcel lines compare actual weight with a dimensional or volumetric weight, then use the higher value or another route-specific billing rule. This matters because two parcels that both weigh four kilograms can have very different prices. A compact box of dense items may remain close to its scale weight, while a large box containing light jackets, shoes with boxes or padded accessories may occupy enough aircraft or truck space to be billed as a heavier parcel. The useful question is therefore not simply ‘How many kilograms do I have?’ but ‘What weight will this particular line charge after it sees my dimensions and contents?’",
          "A spreadsheet cannot answer that question permanently because shipping routes, divisors, minimum increments, restrictions and destination coverage can change. The correct workflow is to use product discovery for finding items, warehouse data for understanding the parcel and the live shipping estimator for comparing currently eligible lines. Any guide that publishes one universal cost per kilogram without the destination, dimensions, product type and date is leaving out the variables that make the estimate meaningful. Treat examples as a way to learn the calculation, never as a quote for your own parcel."
        ]},
        { heading: "Actual weight and volumetric weight", paragraphs: [
          "Actual weight is measured on a scale after the selected products and packaging are assembled. Volumetric weight converts the outer dimensions of the parcel into a billing weight. A common-looking formula multiplies length, width and height and divides the result by a route-specific divisor, but the divisor and rounding method belong to the carrier or line. A 50 × 35 × 25 centimetre parcel has a volume of 43,750 cubic centimetres. Dividing by 5,000 gives 8.75 kilograms; dividing by 6,000 gives about 7.29 kilograms. If the scale shows only five kilograms, a line applying either example may still charge from the larger volumetric figure.",
          "Do not transfer a divisor from one guide or route to another. Some lines use different formulas, volume limits, minimum charges or increments. Some estimates are preliminary until the warehouse confirms final packaging. Read the rule beside the live route and check whether the interface displays both estimated actual and volumetric values. When a parcel is close to a tier boundary, small changes to a box can matter. That does not mean every box should be removed; it means dimensions deserve the same attention as the scale reading."
        ]},
        { heading: "Packaging is a cost and protection decision", paragraphs: [
          "Packaging choices influence both sides of the decision. Removing an unnecessary retail box can reduce outer volume and sometimes actual weight. Folding soft clothing efficiently can also reduce empty space. On the other hand, fragile shoes, electronics or structured accessories may need protection that adds material and dimensions. Choosing the smallest possible parcel is not a saving if the goods arrive crushed, wet or damaged. The correct choice depends on product fragility, the value you place on original packaging and the handling conditions of the eligible line.",
          "Before submitting, separate requirements from preferences. If a box is essential for protection, keep it. If it is wanted only for presentation, compare its likely volume cost and decide knowingly. Ask for packaging actions that the live interface actually offers and check their current descriptions. Avoid vague notes that can be interpreted in several ways. If precise dimensions are important, use the platform’s current rehearsal or pre-shipment measurement option when available, then compare routes again using the confirmed package data rather than the earlier product-only estimate."
        ]},
        { heading: "When consolidation helps—and when it does not", paragraphs: [
          "Consolidation combines several warehouse items into one international parcel. It can be efficient because the parcel may pay one base handling or first-weight charge instead of repeating it across multiple small shipments. Shared outer packaging can also use space better. This is why buyers often wait for several orders before submitting a parcel. But consolidation is not automatically cheaper. Combining bulky items can create a large box that moves into volumetric billing, a higher weight tier or a size restriction. One restricted item can also remove otherwise suitable lines from the comparison.",
          "Use scenarios rather than slogans. Compare the live estimate for one consolidated parcel with two sensible groups, especially when the products differ in size, fragility or restrictions. Do not split parcels into arbitrary tiny units, because repeated base charges can erase any dimensional benefit. Equally, do not force every item into one oversized parcel merely because ‘consolidation saves money.’ The best grouping is the one that remains eligible, protects the contents and produces a reasonable chargeable weight under the current routes available to your destination."
        ]},
        { heading: "Filter eligibility before comparing price", paragraphs: [
          "A low headline rate is irrelevant if the line cannot accept the parcel. Start by entering the correct destination and region, then apply the product attributes requested by the current estimator. Batteries, liquids, cosmetics, magnetic items, branded goods, food, oversize dimensions and other categories may affect which routes appear. The exact classifications and acceptance rules can change, and customs law also depends on the destination. A third-party spreadsheet should never promise that a product is universally shippable.",
          "Once the list is limited to eligible routes, compare more than price. Review the displayed delivery range as an estimate, the tracking method, maximum dimensions, compensation or insurance options, tax handling information and any route notices. A faster line may be worthwhile for a deadline; a slower tracked line may suit a flexible parcel. Neither choice is automatically correct. Keep screenshots or order records of the terms shown when you submit, but understand that carrier scans and customs processing can still create events outside the agent’s control."
        ]},
        { heading: "Build a parcel comparison sheet", paragraphs: [
          "A small comparison table prevents one attractive number from dominating the decision. Record the parcel’s confirmed or estimated actual weight, dimensions, calculated volumetric weight for each candidate line, chargeable weight, quoted total, tracking type, displayed delivery range and important restrictions. Add the date because rates and route availability can change. If the quote is based on estimated dimensions, label it clearly and update the table after final packaging. This turns shipping selection into a reproducible decision rather than a guess.",
          "Also compare the cost in relation to the contents. Very low-value bulky items may create poor parcel economics even when their product price looked attractive. This does not mean they should never be purchased; it means product and logistics costs should be considered together. A good find is not simply the cheapest listing. It is a product route that still makes sense after domestic delivery, options, inspection outcome, packaging and international shipping are included."
        ]},
        { heading: "A final pre-submission checklist", paragraphs: [
          "Before confirming the parcel, verify that every included item has been accepted after QC, the destination address is complete, declared information follows the current process and local law, and the selected line accepts the contents. Check whether packaging requests are reflected, whether the estimate uses final or preliminary dimensions and whether insurance or value limits matter for your order. Review the chargeable weight rather than looking only at the warehouse scale total.",
          "Finally, read the live line notice one more time. This is where temporary delays, destination exclusions or special handling rules are most likely to appear. The purpose of planning is not to predict an exact delivery day; it is to avoid preventable surprises. Keep product discovery, warehouse evidence and parcel selection as three separate decisions, and use the newest information available at each stage."
        ]},
      ],
    },
    "sugargoo-qc-photo-checklist": {
      title: "How to Read Sugargoo QC Photos: A Warehouse Inspection Checklist",
      description: "A structured method for checking variants, measurements, construction and visible defects before accepting a warehouse item.",
      category: "QC method", readTime: "11 min read", published: "August 29, 2026",
      sections: [
        { heading: "QC begins with the order record", paragraphs: [
          "Warehouse quality-control photos are most useful when they are compared with a precise order, not with a vague memory of a seller image. Open the current order record and confirm the product route, selected color, size, model, quantity and any instructions that were accepted. If the source listing offered several similar variants, note the details that distinguish yours. A clean-looking photo cannot compensate for receiving the wrong option. Variant accuracy should be the first pass before discussing stitching, shape or cosmetic details.",
          "Public Sugargoo guidance has described standard QC photos as part of the warehouse process, but the exact current service, number of views and optional paid images should always be confirmed in the live interface. Standard views are designed to provide a general record. They may not show the inside of a shoe, a garment measurement, a small accessory or a defect hidden by the camera angle. Treat the standard set as a starting dataset and request additional evidence only when it can change the accept-or-return decision."
        ]},
        { heading: "Use a three-pass inspection", paragraphs: [
          "The first pass checks identity: correct item type, color family, size marking, model and included components. The second pass checks overall construction: silhouette, symmetry, panel alignment, print placement and obvious damage. The third pass examines decision-specific details such as a requested measurement, material surface, closure, sole, hardware or accessory. Separating these passes reduces the chance that an attractive overall image distracts from a wrong size label or missing component.",
          "Move through all available views before zooming into one suspicious area. Camera distance and a wide-angle lens can change proportions near the edge of the frame. Warehouse lighting can make cream look white or dark colors appear washed out. A single image is rarely enough to judge subtle color accuracy. Compare the item across several photos and use the source listing only as a reference, remembering that seller lighting and editing may also differ."
        ]},
        { heading: "What to inspect on clothing", paragraphs: [
          "For clothing, confirm the marked size and then inspect the overall cut. Compare left and right sides, shoulder alignment, sleeve length, collar shape, pocket placement, hem, prints and embroidery. Look for skipped stitches, loose threads that indicate a larger seam problem, stains, holes, pulled fabric or visibly uneven panels. A few removable threads are not the same as an open seam, so describe what you see rather than using a broad label such as ‘bad quality.’",
          "Fit cannot be proved by the size tag. When measurements matter, request a photo with a tape placed along the exact dimension—garment length, chest width, waist, sleeve or another relevant line. Specify where the measurement should start and end. Compare the photographed value with a garment that fits you, not only with a generic international size. Seller charts can use different measurement methods, and manufacturing tolerance may create a small difference. The goal is to identify differences large enough to change your decision."
        ]},
        { heading: "What to inspect on shoes and accessories", paragraphs: [
          "For shoes, review the pair together before inspecting details. Compare overall shape, left-right symmetry, size labels, sole alignment, toe shape, heel position, stitching and visible glue. Check whether requested laces, insoles, dust bags or boxes are present when they were part of the selected option. Perspective can make the shoe closest to the lens look larger, so use top and rear views to confirm a suspected asymmetry. For fit, an insole measurement is more useful than relying only on the printed size.",
          "For bags and accessories, examine hardware color, closure function when visible, strap and handle attachment, edge finishing, alignment of panels or patterns, and surface damage. Small jewellery or hardware details may require a close-up. Electronics and battery products require additional functional and shipping considerations that a visual photo cannot fully resolve. A QC image can document appearance; it cannot guarantee long-term performance or remove route restrictions."
        ]},
        { heading: "Ask for an additional photo with a purpose", paragraphs: [
          "An extra photo should answer one defined question. Good requests include: show the size label close enough to read; measure the insole from heel to toe; photograph the mark beside a neutral reference; show the zipper closed; or place both shoes level and photograph them from the rear. Avoid requests such as ‘check everything’ or ‘make sure quality is perfect.’ They do not tell the warehouse what evidence you need and can produce another image that still leaves the decision unresolved.",
          "Use annotations when the interface permits, or describe the location precisely: left sleeve near the cuff, outer side of the right shoe, lower corner of the back panel. If you suspect damage, ask for one wider context photo and one close-up. The wider view proves where the issue is; the close-up shows its nature. Decide in advance what result would make you keep or return the item so that the new photo leads to action rather than another round of uncertainty."
        ]},
        { heading: "Distinguish visible facts from interpretation", paragraphs: [
          "Strong QC notes state observable facts: the print sits lower on the left side; the measured length is 67 centimetres; a dark mark appears on the right panel; the selected blue option arrived in black. Weak notes jump directly to claims such as ‘seller is a scam’ or ‘this is definitely perfect.’ A warehouse image shows one item at one moment. It cannot establish the seller’s entire history, prove material composition through appearance alone or guarantee how the product will wear over time.",
          "This distinction also improves dispute communication. A concise description paired with the relevant photo is easier to evaluate than emotional language. Keep the order option, listing screenshot when relevant and QC image together. If a difference may come from lighting or angle, ask for confirming evidence before treating it as a defect. If the issue is clear and material, act within the current order timeline rather than waiting until parcel submission."
        ]},
        { heading: "Accept, request evidence or return", paragraphs: [
          "Every QC review should end in one of three states. Accept when the ordered variant is correct and visible issues fall within what you are willing to keep. Request evidence when one important, answerable question remains. Start the return or after-sales process when a clear mismatch or unacceptable defect is documented and the current order is eligible. Do not keep requesting photos when the existing evidence already supports your decision; delay can reduce the time available to act.",
          "Return windows, seller acceptance, domestic shipping and service charges can vary. Check the live order page and current platform terms for the specific transaction. A general article cannot promise that every item is returnable. The best protection is to choose the correct option, write verifiable instructions, inspect promptly and communicate the exact issue with evidence."
        ]},
        { heading: "Save a reusable QC routine", paragraphs: [
          "Create a short checklist for the products you buy most often. Clothing may require size label, chest, length, print alignment and stains. Shoes may require pair symmetry, size labels, insole length, sole alignment and accessories. Bags may require measurements, closure, hardware and surface condition. Use the same order each time so that an attractive first impression does not skip a basic check.",
          "A spreadsheet is useful before purchase because it organizes discovery. QC is useful after warehouse arrival because it provides evidence about your specific unit. Keeping those roles separate is the central habit. A link can be active and the item can still arrive with a problem; an unknown listing can sometimes arrive correctly. Make the warehouse decision from the warehouse record, not from hype around the original find."
        ]},
        { heading: "Use images that prove something", paragraphs: [
          "Images make an article more convincing only when their source, date and purpose are clear. A sharp warehouse photo showing the ordered unit, a measurement with the tape visible, or a side-by-side comparison of the listing option and the received variant can support a specific conclusion. A generic product photo, a blurred repost or a decorative delivery image adds visual weight without adding evidence. Never present a seller image as if it were the QC record for a buyer's actual item.",
          "When sharing or saving QC evidence, protect personal and order information. Crop account names, addresses, tracking numbers and unrelated order details while preserving the area needed to understand the issue. Keep the uncropped original privately in case support needs it. Add a short caption stating what the image demonstrates and what it does not. This makes the visual useful to readers, support staff and future comparison without turning one photograph into a broader claim about every unit or seller batch."
        ]},
      ],
    },
  } as Record<ArticleSlug, Article>,
  de: {} as Record<ArticleSlug, Article>, es: {} as Record<ArticleSlug, Article>, fr: {} as Record<ArticleSlug, Article>, it: {} as Record<ArticleSlug, Article>,
};

function localizedArticle(locale: Locale, shipping: {title:string; description:string; category:string; readTime:string; published:string; sections:{heading:string; paragraphs:string[]}[]}, qc: {title:string; description:string; category:string; readTime:string; published:string; sections:{heading:string; paragraphs:string[]}[]}) {
  articles[locale]["sugargoo-shipping-weight-guide-2026"] = shipping;
  articles[locale]["sugargoo-qc-photo-checklist"] = qc;
}

localizedArticle("de",
  {title:"Sugargoo-Versand 2026: tatsächliches Gewicht, Volumengewicht und bessere Paketentscheidungen",description:"Praxisleitfaden zu Abrechnungsgewicht, Verpackung, Konsolidierung und Linienvergleich vor der internationalen Paketeinreichung.",category:"Versandstrategie",readTime:"12 Min. Lesezeit",published:"31. August 2026",sections:[
    {heading:"Warum ein Kilogramm nicht immer ein Kilogramm ist",paragraphs:["Die Zahl auf der Lagerwaage ist nur ein Teil der internationalen Versandberechnung. Viele Linien vergleichen tatsächliches Gewicht mit Volumen- oder Dimensionsgewicht und verwenden den höheren Wert oder eine eigene Abrechnungsregel. Zwei Vier-Kilogramm-Pakete können daher sehr unterschiedliche Preise haben: eine kompakte Sendung bleibt nahe am Waagengewicht, während eine große Schachtel mit leichten Jacken oder Schuhkartons wie ein schwereres Paket berechnet werden kann.","Eine Tabelle kann diese Frage nicht dauerhaft beantworten, weil Routen, Divisoren, Rundung, Beschränkungen und Zielabdeckung wechseln. Nutze die Produktsuche zum Finden, Lagerdaten für das Paket und den aktuellen Rechner zum Vergleich geeigneter Linien. Ein universeller Kilopreis ohne Ziel, Maße, Produkttyp und Datum lässt die entscheidenden Variablen weg."]},
    {heading:"Tatsächliches und volumetrisches Gewicht",paragraphs:["Das tatsächliche Gewicht wird nach Zusammenstellung von Produkten und Verpackung gewogen. Das Volumengewicht übersetzt die Außenmaße mit einem linienspezifischen Divisor. Ein Paket mit 50 × 35 × 25 Zentimetern umfasst 43.750 Kubikzentimeter. Geteilt durch 5.000 sind das 8,75 Kilogramm, geteilt durch 6.000 rund 7,29 Kilogramm. Zeigt die Waage fünf Kilogramm, kann trotzdem der höhere Volumenwert gelten.","Übertrage keinen Divisor blind von einer Linie auf eine andere. Formeln, Mindestgebühren, Schritte und Größenlimits unterscheiden sich. Lies die Regel direkt bei der aktuellen Route und prüfe, ob beide Gewichte angezeigt werden. Kleine Maßänderungen können an Tarifgrenzen wichtig sein, doch Schutz darf nicht allein für ein kleineres Volumen geopfert werden."]},
    {heading:"Verpackung ist Kosten- und Schutzentscheidung",paragraphs:["Unnötige Verkaufskartons zu entfernen kann Volumen und Gewicht senken. Weiche Kleidung lässt sich oft effizient falten. Zerbrechliche Schuhe, Elektronik oder strukturierte Accessoires benötigen dagegen Schutz, der Material und Maße hinzufügt. Das kleinste Paket ist kein Gewinn, wenn der Inhalt beschädigt ankommt.","Trenne Anforderungen von Vorlieben. Behalte notwendige Schutzverpackung; bei reiner Präsentationsverpackung kannst du den möglichen Volumenpreis bewusst abwägen. Verwende nur aktuell angebotene Verpackungsoptionen. Wenn Maße entscheidend sind, nutze eine verfügbare Vorabmessung und vergleiche danach mit den bestätigten Daten erneut."]},
    {heading:"Wann Konsolidierung hilft",paragraphs:["Konsolidierung verbindet mehrere Lagerartikel zu einem internationalen Paket. Eine gemeinsame Grund- oder Erstgewichtsgebühr und eine effizientere Außenverpackung können sparen. Doch ein großer, sperriger Karton kann Volumenabrechnung, eine höhere Stufe oder Größenbeschränkung auslösen. Ein beschränkter Artikel kann zudem geeignete Linien für alle anderen entfernen.","Vergleiche deshalb Szenarien: ein Gesamtpaket gegen zwei sinnvolle Gruppen, besonders bei unterschiedlichen Größen, Empfindlichkeiten oder Beschränkungen. Willkürlich viele Kleinpakete wiederholen Grundgebühren; ein erzwungenes Riesenpaket kann ebenso teuer sein. Die beste Gruppierung bleibt geeignet, schützt den Inhalt und erzeugt ein vertretbares Abrechnungsgewicht."]},
    {heading:"Eignung vor Preis filtern",paragraphs:["Ein niedriger Satz ist nutzlos, wenn die Linie den Inhalt nicht akzeptiert. Gib Zielregion und Produktmerkmale korrekt ein. Batterien, Flüssigkeiten, Kosmetik, magnetische Produkte, Übergröße und weitere Kategorien können die Auswahl verändern. Genaue Regeln ändern sich; keine Drittseite kann universelle Versandfähigkeit garantieren.","Vergleiche nach dem Filtern nicht nur den Preis, sondern auch angezeigten Lieferbereich, Tracking, Maximalmaße, Versicherung, Steuerhinweise und Routennachrichten. Schnell oder günstig ist keine automatische Qualitätswertung. Speichere die bei Einreichung gezeigten Bedingungen, ohne daraus ein garantiertes Zustelldatum abzuleiten."]},
    {heading:"Eine Vergleichstabelle anlegen",paragraphs:["Notiere tatsächliches Gewicht, Maße, Volumengewicht pro Linie, Abrechnungsgewicht, Gesamtangebot, Tracking, angezeigten Zeitraum, Einschränkungen und Datum. Kennzeichne vorläufige Maße und aktualisiere sie nach finaler Verpackung. So wird die Auswahl nachvollziehbar statt impulsiv.","Betrachte den Versand im Verhältnis zum Inhalt. Sehr günstige, sperrige Waren können nach Logistik unattraktiv werden. Ein guter Fund ist nicht nur die billigste Produktseite, sondern eine Route, die nach Inlandsversand, Optionen, QC, Verpackung und internationalem Versand weiterhin Sinn ergibt."]},
    {heading:"Checkliste vor der Einreichung",paragraphs:["Bestätige angenommene QC-Ergebnisse, vollständige Adresse, aktuelle Deklarationsanforderungen und Eignung der Linie. Prüfe Verpackungswünsche, finale oder vorläufige Maße, Versicherungs- und Wertgrenzen sowie das Abrechnungsgewicht statt nur die Waagensumme.","Lies die aktuelle Linienmeldung ein letztes Mal. Temporäre Verzögerungen oder Sonderregeln erscheinen dort am ehesten. Planung soll keinen exakten Liefertag vorhersagen, sondern vermeidbare Überraschungen reduzieren. Produktsuche, Lagernachweis und Paketauswahl bleiben getrennte Entscheidungen."]},
  ]},
  {title:"Sugargoo-QC-Fotos lesen: Checkliste für die Lagerprüfung",description:"Strukturierte Methode zur Prüfung von Variante, Maßen, Verarbeitung und sichtbaren Mängeln vor der Annahme.",category:"QC-Methode",readTime:"11 Min. Lesezeit",published:"29. August 2026",sections:[
    {heading:"QC beginnt mit dem Bestelldatensatz",paragraphs:["Lagerfotos sind am nützlichsten, wenn sie mit einer präzisen Bestellung verglichen werden. Öffne den aktuellen Datensatz und bestätige Produktweg, Farbe, Größe, Modell, Menge und angenommene Hinweise. Bei ähnlichen Varianten notierst du die unterscheidenden Details. Ein sauberes Foto gleicht eine falsche Option nicht aus.","Öffentliche Hilfen beschreiben Standard-QC-Fotos als Teil des Lagerprozesses, doch Umfang und Zusatzbilder müssen in der aktuellen Oberfläche geprüft werden. Standardansichten zeigen oft keinen Innenraum, kein Maß oder ein verdecktes Detail. Nutze sie als Ausgangspunkt und fordere nur Belege an, die die Annahme- oder Rückgabeentscheidung verändern können."]},
    {heading:"Prüfung in drei Durchgängen",paragraphs:["Der erste Durchgang prüft Identität: Typ, Farbe, Größenkennzeichnung, Modell und Teile. Der zweite prüft Gesamtverarbeitung: Form, Symmetrie, Ausrichtung, Druck und Schäden. Der dritte betrachtet entscheidungsspezifische Details wie Maße, Oberfläche, Verschlüsse, Sohle oder Zubehör. Diese Trennung verhindert Ablenkung durch ein attraktives Gesamtbild.","Sieh alle Ansichten an, bevor du einen Bereich stark vergrößerst. Weitwinkel und Abstand verändern Proportionen, Licht verändert Farben. Vergleiche mehrere Fotos und nutze Verkäuferbilder nur als Referenz, denn auch sie verwenden andere Beleuchtung und Bearbeitung."]},
    {heading:"Kleidung prüfen",paragraphs:["Bestätige die Größe und prüfe Schnitt, Symmetrie, Schultern, Ärmel, Kragen, Taschen, Saum, Druck und Stickerei. Suche nach offenen Nähten, Flecken, Löchern, gezogenen Fasern und deutlich ungleichen Teilen. Einzelne lose Fäden sind nicht automatisch ein struktureller Nahtfehler; beschreibe die Beobachtung genau.","Das Etikett beweist keine Passform. Bitte bei wichtigen Maßen um ein Foto mit Maßband an der genauen Linie. Vergleiche den Wert mit einem passenden Kleidungsstück, nicht nur mit einer allgemeinen Größe. Relevant sind Unterschiede, die deine Entscheidung tatsächlich verändern."]},
    {heading:"Schuhe und Accessoires prüfen",paragraphs:["Prüfe Schuhe zuerst als Paar: Form, Symmetrie, Größenetiketten, Sohlenausrichtung, Zehenform, Ferse, Nähte und Kleber. Kontrolliere enthaltenes Zubehör. Für Passform ist eine Einlegesohlenmessung hilfreicher als die gedruckte Größe allein.","Bei Taschen und Accessoires prüfst du Hardwarefarbe, Verschluss, Befestigungen, Kanten, Muster und Oberflächenschäden. Kleine Details brauchen Nahaufnahmen. Elektronik und Batterien bringen Funktions- und Versandfragen mit, die ein optisches Foto nicht lösen kann."]},
    {heading:"Zusatzfotos mit klarem Zweck",paragraphs:["Gute Anfragen beantworten eine Frage: Größenetikett lesbar zeigen, Einlegesohle messen, eine Markierung neben neutraler Referenz fotografieren, Reißverschluss schließen oder beide Schuhe eben von hinten zeigen. „Alles prüfen“ oder „perfekte Qualität“ liefert keine klare Aufgabe.","Beschreibe die Stelle präzise und fordere bei Schäden eine Kontextansicht plus Nahaufnahme. Entscheide vorher, welches Ergebnis zum Behalten oder Zurückgeben führt. So erzeugt das neue Bild eine Handlung statt weiterer Unsicherheit."]},
    {heading:"Fakten von Deutung trennen",paragraphs:["Starke QC-Notizen nennen Beobachtbares: Druck links tiefer, Länge 67 Zentimeter, dunkle Stelle rechts, Blau bestellt und Schwarz erhalten. Schwache Notizen springen zu Aussagen über den gesamten Verkäufer oder absolute Perfektion. Ein Foto zeigt einen Artikel zu einem Zeitpunkt.","Sachliche Sprache erleichtert die Kommunikation. Verbinde Bestelloption, relevante Angebotsansicht und QC-Foto. Bei möglicher Licht- oder Winkelwirkung verlangst du Bestätigung; bei klarem wesentlichem Problem handelst du innerhalb der aktuellen Frist."]},
    {heading:"Annehmen, Beleg anfordern oder zurückgeben",paragraphs:["Jede Prüfung endet in einem dieser Zustände. Nimm an, wenn Variante und sichtbarer Zustand akzeptabel sind. Fordere Beleg an, wenn eine wichtige beantwortbare Frage offen ist. Starte Rückgabe, wenn ein klarer Mangel dokumentiert und die Bestellung berechtigt ist. Verzögere nicht mit unnötigen Fotos.","Rückgabefrist, Verkäuferzustimmung und Gebühren variieren. Prüfe den aktuellen Auftrag. Den besten Schutz bieten korrekte Option, überprüfbare Hinweise, schnelle Prüfung und genaue Belege."]},
    {heading:"Eine wiederverwendbare Routine",paragraphs:["Erstelle je Produkttyp eine kurze Liste. Kleidung: Größe, Brust, Länge, Druck, Flecken. Schuhe: Symmetrie, Etiketten, Einlegesohle, Sohle, Zubehör. Taschen: Maße, Verschluss, Hardware, Oberfläche. Nutze immer dieselbe Reihenfolge.","Die Tabelle organisiert die Suche vor dem Kauf; QC liefert Belege nach Ankunft. Halte diese Rollen getrennt. Ein aktiver Link garantiert keinen fehlerfreien Artikel. Triff die Lagerentscheidung aus dem Lagerdatensatz, nicht aus der Begeisterung um den Fund."]},
    {heading:"Bilder verwenden, die etwas belegen",paragraphs:["Bilder überzeugen nur mit klarer Quelle, Datum und Zweck. Ein scharfes Lagerfoto, ein sichtbares Maßband oder der Vergleich zwischen bestellter Option und empfangener Variante stützt eine konkrete Aussage. Ein beliebiges Produktbild oder unscharfer Repost ist kein Beleg. Verkäuferbilder dürfen nicht als QC des konkreten Artikels erscheinen.","Schütze Namen, Adressen, Trackingnummern und fremde Auftragsdaten. Bewahre das Original privat auf und veröffentliche eine saubere, beschriftete Fassung. Die Bildunterschrift soll sagen, was das Foto zeigt und was nicht; ein einzelnes Bild beweist nicht jede Einheit oder Charge."]},
  ]}
);

// Spanish, French and Italian versions preserve the same sections and decision logic.
localizedArticle("es",
  {title:"Envíos Sugargoo en 2026: peso real, peso volumétrico y mejores decisiones",description:"Guía práctica sobre peso facturable, embalaje, consolidación y comparación de líneas.",category:"Estrategia de envío",readTime:"12 min de lectura",published:"31 de agosto de 2026",sections:[
    {heading:"Por qué un kilo no siempre es un kilo",paragraphs:["La báscula es solo una parte del cálculo. Muchas líneas comparan peso real y volumétrico y cobran el mayor u otra regla propia. Dos paquetes de cuatro kilos pueden tener precios distintos: uno compacto puede conservar su peso real, mientras una caja grande con prendas o cajas de zapatos puede facturarse como más pesada.","Una hoja no puede responder de forma permanente porque cambian rutas, divisores, redondeos y restricciones. Usa la búsqueda para descubrir, los datos del almacén para comprender el paquete y el estimador activo para comparar. Un precio universal por kilo sin destino, dimensiones, producto y fecha omite las variables clave."]},
    {heading:"Peso real y volumétrico",paragraphs:["El real se mide tras reunir artículos y embalaje. El volumétrico convierte dimensiones exteriores con un divisor de la línea. Un paquete de 50 × 35 × 25 cm tiene 43.750 cm³: dividido entre 5.000 son 8,75 kg y entre 6.000, 7,29 kg. Aunque la báscula marque cinco, puede cobrarse el volumen.","No copies un divisor de otra ruta. Fórmulas, mínimos, incrementos y límites cambian. Lee la regla junto a la línea activa y comprueba ambos valores. Pequeños cambios importan cerca de un tramo, pero no sacrifiques protección solo por reducir volumen."]},
    {heading:"Embalaje: coste y protección",paragraphs:["Quitar cajas innecesarias puede reducir volumen y peso; doblar ropa blanda aprovecha espacio. Zapatos, electrónica o accesorios estructurados pueden necesitar protección adicional. El paquete más pequeño no ahorra si el contenido llega dañado.","Separa requisitos de preferencias. Conserva embalaje necesario y valora conscientemente el coste de presentación. Usa acciones disponibles en la interfaz. Si las dimensiones importan, utiliza una medición previa cuando esté disponible y vuelve a comparar con datos confirmados."]},
    {heading:"Cuándo ayuda consolidar",paragraphs:["Combinar artículos puede evitar repetir cargos base y aprovechar mejor la caja, pero un paquete grande puede activar volumen, otro tramo o límites de tamaño. Un artículo restringido también puede eliminar líneas aptas para los demás.","Compara un paquete conjunto con dos grupos razonables. Muchos paquetes pequeños repiten cargos; uno enorme puede ser igual de caro. La mejor agrupación es elegible, protege el contenido y produce un peso facturable razonable."]},
    {heading:"Elegibilidad antes del precio",paragraphs:["Una tarifa baja no sirve si la línea rechaza el contenido. Introduce destino y atributos correctos. Baterías, líquidos, cosmética, imanes, gran tamaño y otras categorías cambian la selección. Ningún tercero puede prometer envío universal.","Después compara plazo mostrado, seguimiento, dimensiones máximas, seguro, impuestos y avisos, además del precio. Guarda las condiciones del momento sin convertirlas en una fecha garantizada."]},
    {heading:"Construye una tabla de comparación",paragraphs:["Anota peso real, dimensiones, volumen por línea, peso facturable, total, seguimiento, rango, restricciones y fecha. Marca medidas provisionales y actualiza tras el embalaje final. Así la elección es reproducible.","Relaciona logística y contenido. Un artículo barato y voluminoso puede dejar de ser atractivo. Un buen hallazgo sigue teniendo sentido después de envío nacional, opciones, QC, embalaje y transporte internacional."]},
    {heading:"Lista final",paragraphs:["Confirma artículos aceptados, dirección, declaración actual, elegibilidad, embalaje, medidas, seguro y peso facturable. Revisa el aviso de la línea una vez más por retrasos o reglas temporales.","Planificar no predice el día exacto; evita sorpresas prevenibles. Mantén descubrimiento, evidencia de almacén y selección de paquete como decisiones separadas con la información más reciente."]},
  ]},
  {title:"Cómo leer fotos QC de Sugargoo: lista de inspección",description:"Método estructurado para revisar variante, medidas, construcción y defectos antes de aceptar.",category:"Método QC",readTime:"11 min de lectura",published:"29 de agosto de 2026",sections:[
    {heading:"El QC empieza en el pedido",paragraphs:["Compara las fotos con un pedido preciso. Confirma ruta, color, talla, modelo, cantidad e instrucciones. Si había variantes parecidas, identifica los detalles que distinguen la tuya. Una foto limpia no compensa recibir la opción incorrecta.","Las guías públicas describen fotos QC estándar, pero el servicio actual y las imágenes adicionales se confirman en la interfaz. Las vistas generales pueden omitir interior, medidas o zonas ocultas. Pide evidencia extra solo cuando pueda cambiar la decisión."]},
    {heading:"Inspección en tres pasadas",paragraphs:["Primero identidad: tipo, color, talla, modelo y piezas. Después construcción: silueta, simetría, alineación, estampado y daños. Finalmente detalles de decisión: medidas, superficie, cierre, suela, herrajes o accesorios.","Mira todas las vistas antes de ampliar. Distancia, lente y luz alteran proporción y color. Compara varias fotos y usa el anuncio solo como referencia, pues también puede tener iluminación y edición distintas."]},
    {heading:"Ropa",paragraphs:["Confirma talla y revisa corte, hombros, mangas, cuello, bolsillos, dobladillo, estampado y bordado. Busca costuras abiertas, manchas, agujeros y paneles desiguales. Describe hechos; unos hilos sueltos no equivalen siempre a una costura rota.","La etiqueta no prueba el ajuste. Pide cinta en la medida exacta y compara con una prenda que te quede bien. Las tablas usan métodos diferentes; céntrate en diferencias capaces de cambiar tu decisión."]},
    {heading:"Calzado y accesorios",paragraphs:["Revisa el par: forma, simetría, etiquetas, suela, puntera, talón, costuras y pegamento. Comprueba accesorios. Para el ajuste, una plantilla medida es más útil que la talla impresa.","En bolsos revisa herrajes, cierres, asas, cantos, patrones y superficie. Los detalles pequeños necesitan acercamiento. Una foto no garantiza rendimiento electrónico ni elimina restricciones de batería."]},
    {heading:"Pide una foto con propósito",paragraphs:["Solicita una prueba concreta: etiqueta legible, plantilla medida, marca junto a referencia, cremallera cerrada o ambos zapatos nivelados. “Comprueba todo” no define evidencia.","Describe la zona con precisión y pide contexto más acercamiento para un daño. Decide antes qué resultado te haría aceptar o devolver para que la nueva foto lleve a una acción."]},
    {heading:"Hechos frente a interpretación",paragraphs:["Notas fuertes dicen: estampado más bajo a la izquierda, longitud 67 cm, marca oscura a la derecha, azul pedido y negro recibido. Unas fotos no prueban toda la historia del vendedor ni la composición del material.","El lenguaje claro mejora la disputa. Une opción, anuncio y foto. Si puede ser luz o ángulo, pide confirmación; si el problema es claro, actúa dentro del plazo actual."]},
    {heading:"Aceptar, pedir prueba o devolver",paragraphs:["Acepta cuando variante y estado son adecuados; pide evidencia si queda una pregunta importante; inicia devolución si hay diferencia clara y el pedido es elegible. No alargues con fotos innecesarias.","Plazos, aceptación y gastos varían. Revisa el pedido activo. Elegir bien, dar instrucciones comprobables e inspeccionar pronto ofrece la mejor protección."]},
    {heading:"Rutina reutilizable",paragraphs:["Crea una lista por producto: ropa con talla y medidas; zapatos con simetría e plantilla; bolsos con cierre y herrajes. Sigue siempre el mismo orden.","La hoja organiza el descubrimiento; el QC aporta evidencia de tu unidad. Un enlace activo no garantiza un artículo perfecto. Decide desde el registro del almacén, no desde la fama del hallazgo."]},
    {heading:"Usa imágenes que demuestren algo",paragraphs:["Una imagen convence si tiene fuente, fecha y objetivo. Una foto nítida de almacén, una cinta visible o la comparación entre opción y variante recibida respalda una conclusión. Una foto genérica o borrosa no es evidencia; nunca presentes la imagen del vendedor como QC del artículo real.","Oculta nombres, direcciones, seguimiento y datos ajenos, conservando el original en privado. Añade un pie que explique qué demuestra y qué no. Una foto no prueba todas las unidades o lotes."]},
  ]}
);

localizedArticle("fr",
  {title:"Livraison Sugargoo en 2026 : poids réel, poids volumétrique et meilleures décisions",description:"Guide pratique du poids facturable, de l’emballage, du regroupement et du choix de ligne.",category:"Stratégie livraison",readTime:"12 min de lecture",published:"31 août 2026",sections:[
    {heading:"Pourquoi un kilo n’est pas toujours un kilo",paragraphs:["La balance n’est qu’une partie du calcul. De nombreuses lignes comparent poids réel et volumétrique et facturent le plus élevé ou une autre règle. Deux colis de quatre kilos peuvent coûter différemment : l’un compact reste proche de la balance, l’autre encombrant est facturé comme plus lourd.","Un tableau ne peut pas figer la réponse car routes, diviseurs, arrondis et restrictions changent. Utilisez la recherche pour découvrir, les données d’entrepôt pour comprendre le colis et l’estimateur actif pour comparer. Un prix universel au kilo sans destination, dimensions, produit et date est incomplet."]},
    {heading:"Poids réel et volumétrique",paragraphs:["Le réel est pesé après assemblage. Le volume convertit les dimensions avec le diviseur de la ligne. Un colis de 50 × 35 × 25 cm représente 43 750 cm³ : 8,75 kg avec 5 000 ou 7,29 kg avec 6 000. Même à cinq kilos sur la balance, le volume peut être facturé.","Ne copiez pas un diviseur d’une autre route. Formules, minimums, paliers et limites varient. Lisez la règle active et comparez les deux valeurs. Les petits changements comptent près d’un palier, sans sacrifier la protection."]},
    {heading:"Emballage, coût et protection",paragraphs:["Retirer une boîte inutile réduit parfois volume et poids ; plier les vêtements optimise l’espace. Chaussures, électronique ou accessoires structurés peuvent nécessiter une protection supplémentaire. Le plus petit colis n’économise rien si le contenu arrive endommagé.","Séparez besoin et préférence. Gardez la protection nécessaire et évaluez le coût de présentation. Utilisez les actions proposées en direct. Si les dimensions comptent, demandez une mesure préalable disponible et recommencez la comparaison."]},
    {heading:"Quand le regroupement aide",paragraphs:["Regrouper peut éviter plusieurs frais de base et mieux employer l’emballage, mais un gros colis peut déclencher volume, autre palier ou limite de taille. Un article restreint peut aussi retirer des lignes adaptées aux autres.","Comparez un colis unique à deux groupes cohérents. Trop de petits colis répètent les frais ; un très grand peut coûter autant. Le bon groupe reste éligible, protège le contenu et donne un poids facturable raisonnable."]},
    {heading:"Éligibilité avant prix",paragraphs:["Un tarif bas ne sert à rien si la ligne refuse le contenu. Entrez destination et attributs corrects. Batteries, liquides, cosmétiques, aimants, grandes tailles et autres catégories modifient les routes. Aucun tiers ne peut promettre une expédition universelle.","Comparez ensuite délai affiché, suivi, dimensions, assurance, taxes et avis en plus du coût. Gardez les conditions visibles au moment de la soumission sans les transformer en date garantie."]},
    {heading:"Tableau de comparaison",paragraphs:["Notez poids réel, dimensions, volume par ligne, poids facturable, total, suivi, plage, restrictions et date. Marquez les mesures provisoires et actualisez-les après emballage. La décision devient reproductible.","Reliez logistique et contenu. Un article bon marché et volumineux peut devenir peu intéressant. Une bonne sélection reste logique après livraison nationale, options, QC, emballage et transport international."]},
    {heading:"Contrôle final",paragraphs:["Confirmez articles acceptés, adresse, déclaration actuelle, éligibilité, emballage, mesures, assurance et poids facturable. Relisez l’avis de la ligne pour les règles temporaires.","Planifier ne prédit pas un jour exact ; cela évite des surprises. Gardez découverte, preuve d’entrepôt et choix du colis comme trois décisions distinctes fondées sur les données les plus récentes."]},
  ]},
  {title:"Lire les photos QC Sugargoo : liste d’inspection en entrepôt",description:"Méthode structurée pour vérifier variante, mesures, construction et défauts avant acceptation.",category:"Méthode QC",readTime:"11 min de lecture",published:"29 août 2026",sections:[
    {heading:"Le QC commence par la commande",paragraphs:["Comparez les photos à une commande précise. Confirmez route, couleur, taille, modèle, quantité et instructions. Pour des variantes proches, notez les détails distinctifs. Une photo propre ne compense pas une mauvaise option.","Les guides publics décrivent des photos QC standard, mais service actuel et vues supplémentaires se vérifient en direct. Les vues générales peuvent omettre intérieur, mesure ou zone cachée. Demandez un complément seulement s’il change la décision."]},
    {heading:"Inspection en trois passages",paragraphs:["D’abord l’identité : type, couleur, taille, modèle et pièces. Ensuite la construction : silhouette, symétrie, alignement, impression et dommages. Enfin les détails décisifs : mesure, surface, fermeture, semelle, métal ou accessoires.","Regardez toutes les vues avant de zoomer. Distance, objectif et lumière modifient proportion et couleur. Comparez plusieurs photos et utilisez l’annonce seulement comme référence."]},
    {heading:"Vêtements",paragraphs:["Confirmez taille puis coupe, épaules, manches, col, poches, ourlet, impression et broderie. Cherchez coutures ouvertes, taches, trous et panneaux inégaux. Décrivez les faits : quelques fils ne signifient pas toujours une couture cassée.","L’étiquette ne prouve pas la coupe. Demandez un mètre sur la dimension exacte et comparez à un vêtement adapté. Les tableaux utilisent des méthodes différentes ; ciblez les écarts qui changent votre décision."]},
    {heading:"Chaussures et accessoires",paragraphs:["Examinez la paire : forme, symétrie, étiquettes, semelle, pointe, talon, coutures et colle. Vérifiez les accessoires. Une semelle intérieure mesurée vaut mieux que la taille imprimée pour la coupe.","Pour les sacs, contrôlez métal, fermetures, attaches, bords, motifs et surface. Les petits détails exigent un gros plan. Une photo ne garantit pas la durée d’un appareil ni l’absence de restriction batterie."]},
    {heading:"Une photo avec un objectif",paragraphs:["Demandez une preuve précise : étiquette lisible, semelle mesurée, marque avec référence, fermeture fermée ou chaussures alignées. « Tout vérifier » ne définit aucune preuve.","Décrivez la zone et demandez contexte plus gros plan pour un dommage. Décidez avant quel résultat mène à garder ou retourner afin que la nouvelle photo produise une action."]},
    {heading:"Faits et interprétation",paragraphs:["Une bonne note dit : impression plus basse à gauche, longueur 67 cm, marque sombre à droite, bleu commandé et noir reçu. Une photo ne prouve pas toute l’histoire du vendeur ni la composition du matériau.","Un langage clair aide le dossier. Associez option, annonce et photo. Si lumière ou angle est possible, confirmez ; si l’écart est clair, agissez dans le délai."]},
    {heading:"Accepter, demander ou retourner",paragraphs:["Acceptez si variante et état conviennent ; demandez une preuve si une question importante reste ouverte ; retournez si un écart clair est documenté et éligible. Ne retardez pas avec des photos inutiles.","Délais, accord vendeur et frais varient. Consultez la commande active. Bon choix, instructions vérifiables et contrôle rapide offrent la meilleure protection."]},
    {heading:"Routine réutilisable",paragraphs:["Créez une liste par produit : vêtements avec taille et mesures, chaussures avec symétrie et semelle, sacs avec fermeture et métal. Gardez le même ordre.","Le tableau organise la découverte ; le QC prouve l’état de votre unité. Un lien actif ne garantit pas un article parfait. Décidez à partir du dossier d’entrepôt, pas du bruit autour de la sélection."]},
    {heading:"Utiliser des images qui prouvent",paragraphs:["Une image convainc avec une source, une date et un but. Photo nette d’entrepôt, mesure visible ou comparaison option-unité reçue soutient une conclusion. Une photo générique ou floue n’est pas une preuve ; ne présentez jamais l’image vendeur comme QC de l’article réel.","Masquez noms, adresses, suivi et données étrangères, en gardant l’original privé. Ajoutez une légende disant ce que l’image démontre et ne démontre pas. Une photo ne représente pas chaque unité ou lot."]},
  ]}
);

localizedArticle("it",
  {title:"Spedizione Sugargoo 2026: peso reale, volumetrico e decisioni migliori",description:"Guida pratica a peso fatturabile, imballaggio, consolidamento e confronto delle linee.",category:"Strategia di spedizione",readTime:"12 min di lettura",published:"31 agosto 2026",sections:[
    {heading:"Perché un chilo non è sempre un chilo",paragraphs:["La bilancia è solo una parte del calcolo. Molte linee confrontano peso reale e volumetrico e fatturano il maggiore o un’altra regola. Due pacchi da quattro chili possono costare diversamente: uno compatto resta vicino al peso reale, uno grande con articoli leggeri può essere fatturato come più pesante.","Un foglio non può fissare la risposta perché rotte, divisori, arrotondamenti e restrizioni cambiano. Usa la ricerca per trovare, i dati di magazzino per capire il pacco e lo stimatore attivo per confrontare. Un prezzo universale al chilo senza destinazione, dimensioni, prodotto e data è incompleto."]},
    {heading:"Peso reale e volumetrico",paragraphs:["Il reale viene pesato dopo aver assemblato prodotti e imballaggio. Il volume converte le dimensioni con il divisore della linea. Un pacco 50 × 35 × 25 cm ha 43.750 cm³: 8,75 kg con 5.000 o 7,29 kg con 6.000. Anche se la bilancia segna cinque, può valere il volume.","Non copiare un divisore da un’altra rotta. Formule, minimi, scatti e limiti variano. Leggi la regola attiva e confronta entrambi i pesi. Piccole variazioni contano vicino a una fascia, senza sacrificare la protezione."]},
    {heading:"Imballaggio: costo e protezione",paragraphs:["Rimuovere scatole inutili può ridurre volume e peso; piegare capi morbidi usa meglio lo spazio. Scarpe, elettronica o accessori strutturati possono richiedere protezione aggiuntiva. Il pacco più piccolo non fa risparmiare se il contenuto arriva danneggiato.","Separa necessità e preferenze. Mantieni la protezione essenziale e valuta il costo della confezione di presentazione. Usa le azioni offerte nell’interfaccia. Se le misure contano, richiedi una misurazione preliminare disponibile e confronta di nuovo."]},
    {heading:"Quando consolidare aiuta",paragraphs:["Unire articoli può evitare più costi base e usare meglio l’imballaggio, ma un pacco grande può attivare volume, altra fascia o limite dimensionale. Un articolo ristretto può eliminare linee adatte agli altri.","Confronta un pacco unico con due gruppi sensati. Troppi piccoli ripetono i costi; uno enorme può essere altrettanto caro. Il gruppo migliore resta idoneo, protegge il contenuto e produce un peso fatturabile ragionevole."]},
    {heading:"Idoneità prima del prezzo",paragraphs:["Una tariffa bassa non serve se la linea rifiuta il contenuto. Inserisci destinazione e attributi corretti. Batterie, liquidi, cosmetici, magneti, grandi dimensioni e altre categorie cambiano la scelta. Nessun sito terzo può promettere spedizione universale.","Poi confronta intervallo, tracking, dimensioni, assicurazione, tasse e avvisi oltre al prezzo. Conserva le condizioni mostrate al momento senza trasformarle in una data garantita."]},
    {heading:"Crea una tabella di confronto",paragraphs:["Annota peso reale, dimensioni, volume per linea, peso fatturabile, totale, tracking, intervallo, restrizioni e data. Segna misure provvisorie e aggiorna dopo l’imballaggio. La scelta diventa ripetibile.","Collega logistica e contenuto. Un articolo economico e voluminoso può perdere convenienza. Una buona selezione ha ancora senso dopo consegna interna, opzioni, QC, imballaggio e spedizione internazionale."]},
    {heading:"Controllo finale",paragraphs:["Conferma articoli accettati, indirizzo, dichiarazione corrente, idoneità, imballaggio, misure, assicurazione e peso fatturabile. Rileggi l’avviso della linea per regole temporanee.","Pianificare non predice un giorno esatto; evita sorprese prevenibili. Mantieni scoperta, prova di magazzino e scelta del pacco come tre decisioni separate con dati aggiornati."]},
  ]},
  {title:"Come leggere le foto QC Sugargoo: checklist di magazzino",description:"Metodo strutturato per controllare variante, misure, costruzione e difetti prima di accettare.",category:"Metodo QC",readTime:"11 min di lettura",published:"29 agosto 2026",sections:[
    {heading:"Il QC parte dall’ordine",paragraphs:["Confronta le foto con un ordine preciso. Conferma percorso, colore, taglia, modello, quantità e istruzioni. Se esistono varianti simili, annota i dettagli distintivi. Una foto pulita non compensa l’opzione sbagliata.","Le guide pubbliche descrivono foto QC standard, ma servizio attuale e immagini extra vanno verificati nell’interfaccia. Le viste generali possono non mostrare interno, misura o area nascosta. Chiedi prove extra solo se cambiano la decisione."]},
    {heading:"Tre passaggi di controllo",paragraphs:["Prima identità: tipo, colore, taglia, modello e pezzi. Poi costruzione: forma, simmetria, allineamento, stampa e danni. Infine dettagli decisivi: misura, superficie, chiusura, suola, hardware o accessori.","Guarda tutte le viste prima di ingrandire. Distanza, lente e luce cambiano proporzioni e colore. Confronta più foto e usa l’inserzione solo come riferimento."]},
    {heading:"Abbigliamento",paragraphs:["Conferma taglia e controlla taglio, spalle, maniche, collo, tasche, orlo, stampa e ricamo. Cerca cuciture aperte, macchie, fori e pannelli disuguali. Descrivi i fatti: fili sciolti non significano sempre una cucitura rotta.","L’etichetta non prova la vestibilità. Chiedi il metro sulla dimensione esatta e confronta con un capo che veste bene. Le tabelle usano metodi diversi; concentrati sulle differenze che cambiano la scelta."]},
    {heading:"Scarpe e accessori",paragraphs:["Controlla la coppia: forma, simmetria, etichette, suola, punta, tallone, cuciture e colla. Verifica gli accessori. Una soletta misurata è più utile della sola taglia stampata.","Per borse controlla hardware, chiusure, attacchi, bordi, motivi e superficie. I dettagli piccoli richiedono primi piani. Una foto non garantisce durata elettronica né elimina restrizioni batteria."]},
    {heading:"Una foto con uno scopo",paragraphs:["Chiedi una prova precisa: etichetta leggibile, soletta misurata, segno con riferimento, zip chiusa o scarpe allineate. “Controlla tutto” non definisce una prova.","Descrivi l’area e richiedi contesto più primo piano per un danno. Decidi prima quale risultato porta ad accettare o restituire, così la foto produce un’azione."]},
    {heading:"Fatti e interpretazione",paragraphs:["Una buona nota dice: stampa più bassa a sinistra, lunghezza 67 cm, segno scuro a destra, blu ordinato e nero ricevuto. Una foto non prova tutta la storia del venditore o la composizione del materiale.","Un linguaggio chiaro aiuta la pratica. Collega opzione, inserzione e foto. Se può dipendere da luce o angolo, conferma; se il problema è chiaro, agisci entro il termine."]},
    {heading:"Accetta, chiedi o restituisci",paragraphs:["Accetta se variante e stato sono adeguati; chiedi prova se resta una domanda importante; restituisci se la differenza è documentata e idonea. Non ritardare con foto inutili.","Finestre, consenso e costi variano. Controlla l’ordine attivo. Scelta corretta, istruzioni verificabili e controllo rapido sono la protezione migliore."]},
    {heading:"Routine riutilizzabile",paragraphs:["Crea una lista per prodotto: abbigliamento con taglia e misure, scarpe con simmetria e soletta, borse con chiusura e hardware. Segui sempre lo stesso ordine.","Il foglio organizza la scoperta; il QC prova lo stato della tua unità. Un link attivo non garantisce un articolo perfetto. Decidi dal record di magazzino, non dall’hype della selezione."]},
    {heading:"Usare immagini che dimostrano",paragraphs:["Un’immagine convince con fonte, data e scopo. Foto nitida di magazzino, misura visibile o confronto tra opzione e variante ricevuta sostiene una conclusione. Una foto generica o sfocata non è prova; non presentare l’immagine del venditore come QC dell’articolo reale.","Nascondi nomi, indirizzi, tracking e dati estranei, conservando l’originale in privato. Aggiungi una didascalia su cosa dimostra e cosa non dimostra. Una foto non rappresenta ogni unità o lotto."]},
  ]}
);

for (const locale of Object.keys(extraArticles) as Locale[]) {
  Object.assign(articles[locale], extraArticles[locale]);
}

for (const locale of ["de", "es", "fr", "it"] as const) {
  Object.assign(articles[locale], fullLocalizedArticles[locale]);
}
