export const orderStatusArticles = {
  en: {
    title: "Sugargoo Order Status Guide: Purchased, Shipped, Received and Stored",
    description: "Read Sugargoo order status labels as dated workflow evidence, separate seller dispatch from parcel shipping, and know what to verify before acting.",
    category: "Order workflow",
    readTime: "13 min read",
    published: "September 2, 2026",
    sections: [
      { heading: "Start by identifying what the status belongs to", paragraphs: [
        "A Sugargoo order status is useful only when you know which object it describes. A purchasing order concerns an individual marketplace item: the chosen seller, variant and quantity. A warehouse record concerns the physical item received in China. A parcel record concerns one or more stored items grouped for international shipping. The word shipped can therefore describe a seller sending one item domestically or a completed parcel leaving for its destination. Those are different journeys, identifiers and next actions.",
        "Before interpreting any label, record the page, order number, seller or source item, selected variant, displayed status and the exact date and time. If you are looking at a parcel, add its parcel number and tracking number separately. This small header prevents the most common diagnostic error: using an international tracking expectation to judge a seller dispatch, or assuming a warehouse item has entered a parcel merely because another item in the same haul is ready."
      ]},
      { heading: "Read Purchased as a procurement checkpoint", paragraphs: [
        "Purchased generally indicates that the buying stage has moved beyond an unpaid request, but it should not be treated as proof of seller dispatch, warehouse receipt or successful QC. The current order detail is the controlling evidence. Confirm that the source listing, colour, size, version, quantity and any purchase remark still match the request. Also preserve the amount and timestamp shown for the item, because later seller changes can make an old product page a poor record of what was ordered.",
        "The sensible action at this point is observation, not parcel planning. Look for a seller shipment event or a dated update in the order record. If the status remains unchanged longer than expected, first distinguish a genuine delay from a weekend, preorder, customised item or seller-side handling period that was disclosed before payment. Do not invent a universal deadline. Use the current order detail and support instructions, and provide the precise order number and last event if you need an investigation."
      ]},
      { heading: "Treat seller Shipped as domestic movement", paragraphs: [
        "When an item-level order shows that the seller has shipped, the item is normally moving toward the purchasing warehouse, not toward your final address. This stage may have a domestic tracking record, but it is not the international parcel tracking number. Save the seller-dispatch date and any domestic carrier event displayed. A label-created event is weaker evidence than a physical acceptance or movement scan, so keep the wording of the event rather than translating it into a stronger claim.",
        "The next useful checkpoint is warehouse receipt. Avoid submitting support requests that say only ‘tracking is stuck’. State whether the concern is seller dispatch, domestic carrier movement or warehouse intake, and give the last dated event. If several items were bought together, track each item independently. One seller may dispatch quickly while another is still preparing the order, and a combined parcel cannot be assessed until every item you intend to include has reached an actionable warehouse state."
      ]},
      { heading: "Separate Received from inspection approval", paragraphs: [
        "Received should be read as evidence that the warehouse has logged an incoming item, not as a quality certificate. Identity, option, quantity and visible condition still need review. Match the warehouse record to the original order before examining fine details: compare the product, colour, size label, quantity and any included parts. Then review the available QC images. Sugargoo's public QC guidance describes standard photos after warehouse arrival, but the live order interface determines what is actually available for a specific item.",
        "Create a short discrepancy record if anything is unclear. Name the expected field, the observed field and the image or record that supports the concern. ‘Wrong item’ is weak; ‘order says black, size 42, but image 3 shows a blue size-41 label’ is investigable. Request only the extra angle or measurement needed to close the uncertainty. Do not claim that photographs prove authenticity, material composition, comfort or durability; they prove only what is visibly captured."
      ]},
      { heading: "Use Stored as readiness evidence, not a shipping promise", paragraphs: [
        "Stored usually marks a warehouse state in which the received item is associated with your account and can be managed for later action. It does not mean the item is already packed for export, eligible for every route or protected by a final parcel arrangement. Check that returns or exchanges have been resolved, the QC decision is recorded and the item is actually selectable when you create a parcel. If a storage date or countdown appears, save it because warehouse rules are time-sensitive.",
        "At this stage, build an item-level readiness table with four columns: order ID, warehouse status, unresolved issue and intended parcel group. Mark an item ready only when its identity and keep decision are clear. A mixed table is normal: some items may be stored, one may await a measurement and another may be in a return workflow. Keeping those states separate prevents a convenient ‘select all’ action from moving an unresolved item into international shipping."
      ]},
      { heading: "Build a dated status ledger instead of taking one screenshot", paragraphs: [
        "A single screenshot captures appearance, not progression. Use a simple ledger with timestamp, object type, identifier, exact displayed status, last physical event, evidence saved, expected next checkpoint and action owner. Add a new row only when the evidence changes. This makes quiet periods visible without treating every quiet period as a problem. It also shows whether the next step belongs to the seller, a domestic carrier, warehouse intake, your own QC decision or parcel submission.",
        "For example, an item can move from Purchased on Monday to seller Shipped on Wednesday, show a domestic acceptance scan on Thursday, and be Received on Friday. A second item may still be Purchased. The correct conclusion is not that the first parcel is delayed; no international parcel exists yet. The useful decision is whether to wait for the second item, investigate its seller stage, or eventually ship the first item separately after both warehouse and route conditions are known."
      ]},
      { heading: "Escalate with evidence tied to the last verified event", paragraphs: [
        "Escalation should begin with the last fact, not the desired outcome. Provide the order or parcel identifier, exact variant, current status, last dated scan or interface update, the date you checked, and one clear question. Attach the minimum screenshots that prove those fields while hiding unrelated personal information. If the issue is a mismatch, include the order selection and the relevant warehouse image. If the issue is movement, include the event history rather than a cropped status word.",
        "Use decision thresholds based on evidence. Investigate when the interface requests action, a disclosed seller date has passed, an expected checkpoint is contradicted by tracking, or support guidance indicates a case should be opened. Continue monitoring when there is no new contradictory evidence and the current stage still belongs to another party. Because service windows and interface wording can change, verify the live instruction instead of copying a deadline from an old guide or community post."
      ]},
      { heading: "Run the four-state audit before creating a parcel", paragraphs: [
        "Before parcel submission, audit every intended item in sequence. Purchased asks whether the requested identity and variant were procured. Seller Shipped asks whether domestic movement is evidenced. Received asks whether the warehouse logged the correct physical item. Stored asks whether your keep decision is complete and the item is available for parcel management. Any unresolved answer stays visible in the ledger rather than being smoothed over by a later status label.",
        "The final rule is simple: a status is a checkpoint, not a guarantee. Preserve exact wording, dates and identifiers; distinguish item, warehouse and parcel objects; and ask for the next verifiable event. This method remains useful even if Sugargoo changes a label, because it is based on evidence ownership and workflow sequence. Recheck the current account interface before acting, especially where a button, deadline, service option or policy can change."
      ]}
    ]
  },
  de: {
    title: "Sugargoo-Bestellstatus: Gekauft, versandt, empfangen und eingelagert",
    description: "Sugargoo-Statusmeldungen als datierte Prozessbelege lesen, Verkäuferversand vom Paketversand trennen und vor jeder Aktion gezielt prüfen.",
    category: "Bestellablauf", readTime: "13 Min. Lesezeit", published: "2. September 2026",
    sections: [
      {heading:"Zuerst klären, zu welchem Objekt der Status gehört",paragraphs:["Ein Sugargoo-Bestellstatus ist nur nützlich, wenn klar ist, welches Objekt er beschreibt. Eine Einkaufsbestellung betrifft einen einzelnen Marktplatzartikel mit Verkäufer, Variante und Menge. Ein Lagereintrag betrifft den in China eingegangenen physischen Artikel. Ein Paketeintrag betrifft einen oder mehrere eingelagerte Artikel für den internationalen Versand. ‘Versandt’ kann daher den Inlandsweg des Verkäufers oder den Export eines fertigen Pakets meinen – zwei verschiedene Wege mit anderen Kennungen und nächsten Schritten.","Notieren Sie vor jeder Deutung Seite, Bestellnummer, Verkäufer oder Quellartikel, gewählte Variante, angezeigten Status sowie Datum und Uhrzeit. Bei einem Paket kommen Paket- und Trackingnummer getrennt hinzu. So vermeiden Sie, internationale Tracking-Erwartungen auf einen Verkäufertransport anzuwenden oder anzunehmen, ein Lagerartikel sei schon im Paket, nur weil ein anderer Artikel derselben Sammlung bereit ist."]},
      {heading:"Purchased als Beschaffungs-Kontrollpunkt lesen",paragraphs:["Purchased zeigt im Allgemeinen, dass die Beschaffung über eine unbezahlte Anfrage hinaus ist. Es beweist jedoch weder Verkäuferversand noch Lagereingang oder erfolgreiche QC. Maßgeblich ist das aktuelle Bestelldetail. Prüfen Sie Quellangebot, Farbe, Größe, Version, Menge und Kaufanmerkung. Speichern Sie Betrag und Zeitpunkt, da spätere Änderungen der Verkäuferseite kein verlässlicher Beleg für die damalige Auswahl sind.","Jetzt ist Beobachtung sinnvoll, nicht Paketplanung. Achten Sie auf ein datiertes Versandereignis des Verkäufers. Bleibt der Status länger unverändert, unterscheiden Sie eine echte Verzögerung von Wochenende, Vorbestellung, Individualanfertigung oder zuvor genannter Bearbeitung. Erfinden Sie keine allgemeine Frist. Nutzen Sie Bestelldetail und aktuelle Support-Hinweise; nennen Sie bei einer Untersuchung Bestellnummer und letztes Ereignis."]},
      {heading:"Seller Shipped als Inlandsbewegung behandeln",paragraphs:["Zeigt eine Artikelbestellung den Verkäuferversand, bewegt sie sich gewöhnlich zum Einkaufs­lager und nicht zur Endadresse. Ein mögliches Inlands-Tracking ist nicht die internationale Paketnummer. Speichern Sie Versanddatum und angezeigte Ereignisse. Eine elektronisch erzeugte Sendung ist schwächer als eine physische Annahme oder Bewegung; bewahren Sie daher den exakten Wortlaut auf, statt ihn zu einer stärkeren Aussage umzudeuten.","Der nächste sinnvolle Kontrollpunkt ist der Lagereingang. Schreiben Sie nicht nur ‘Tracking hängt’, sondern benennen Sie Verkäufer, Inlands-Carrier oder Lagerannahme und das letzte datierte Ereignis. Verfolgen Sie bei mehreren Käufen jeden Artikel einzeln. Verkäufer arbeiten unterschiedlich schnell, und eine Sammelsendung lässt sich erst beurteilen, wenn alle vorgesehenen Artikel einen handlungsfähigen Lagerstatus erreicht haben."]},
      {heading:"Received von einer Freigabe der Prüfung trennen",paragraphs:["Received belegt die Erfassung eines eingegangenen Artikels, ist aber kein Qualitätszertifikat. Identität, Option, Menge und sichtbarer Zustand bleiben zu prüfen. Gleichen Sie zuerst Produkt, Farbe, Größenetikett, Menge und Zubehör mit der Bestellung ab und lesen Sie dann die verfügbaren QC-Bilder. Öffentliche Sugargoo-Hinweise beschreiben Standardfotos nach Lagereingang; für den Einzelfall gilt die aktuelle Bestelloberfläche.","Bei Unklarheit erstellen Sie einen kurzen Abweichungsnachweis: erwartetes Feld, beobachtetes Feld und stützendes Bild. ‘Falscher Artikel’ ist schwach; ‘Bestellung schwarz, Größe 42, Bild 3 zeigt blaues Etikett Größe 41’ ist untersuchbar. Fordern Sie nur den nötigen Winkel oder das Maß an. Fotos belegen keine Echtheit, Materialzusammensetzung, Bequemlichkeit oder Haltbarkeit, sondern nur sichtbar Erfasstes."]},
      {heading:"Stored als Bereitschaft, nicht als Versandversprechen nutzen",paragraphs:["Stored bezeichnet gewöhnlich einen Lagerzustand, in dem der Artikel Ihrem Konto zugeordnet und weiter verwaltet werden kann. Er ist noch nicht automatisch exportfertig verpackt, für jede Route geeignet oder endgültig geschützt. Prüfen Sie abgeschlossene Retouren oder Umtausche, die dokumentierte QC-Entscheidung und die tatsächliche Auswahlmöglichkeit beim Erstellen eines Pakets. Speichern Sie ein angezeigtes Lagerdatum, da Regeln zeitabhängig sind.","Führen Sie eine Tabelle mit Bestell-ID, Lagerstatus, offenem Problem und vorgesehener Paketgruppe. Markieren Sie einen Artikel erst als bereit, wenn Identität und Behalten-Entscheidung klar sind. Gemischte Zustände sind normal: ein Artikel ist eingelagert, einer wartet auf ein Maß, ein anderer befindet sich im Rückgabeprozess. Diese Trennung verhindert, dass ‘alles auswählen’ einen ungeklärten Artikel in den Export bringt."]},
      {heading:"Ein datiertes Statusprotokoll statt eines Einzelbilds führen",paragraphs:["Ein Screenshot zeigt einen Zustand, aber keinen Verlauf. Protokollieren Sie Zeit, Objekttyp, Kennung, exakten Status, letztes physisches Ereignis, gespeicherten Beleg, nächsten Kontrollpunkt und zuständige Partei. Ergänzen Sie nur bei neuer Evidenz. Dadurch bleiben Ruhephasen sichtbar, ohne jede Pause zum Problem zu erklären, und es wird klar, ob Verkäufer, Inlands-Carrier, Lager, Ihre QC-Entscheidung oder die Paketeinreichung am Zug sind.","Beispiel: Montag Purchased, Mittwoch Seller Shipped, Donnerstag physische Annahme, Freitag Received. Ein zweiter Artikel ist noch Purchased. Daraus folgt keine Verzögerung eines internationalen Pakets, denn es existiert noch nicht. Entscheiden Sie vielmehr, ob Sie warten, den Verkäuferstatus untersuchen oder den ersten Artikel später getrennt senden – erst nachdem Lager- und Routenbedingungen bekannt sind."]},
      {heading:"Mit Belegen zum letzten bestätigten Ereignis eskalieren",paragraphs:["Beginnen Sie eine Eskalation mit der letzten Tatsache, nicht dem gewünschten Ergebnis. Nennen Sie Bestell- oder Paketkennung, exakte Variante, Status, letztes datiertes Ereignis, Prüfdatum und eine klare Frage. Hängen Sie nur notwendige Belege an und blenden Sie fremde persönliche Daten aus. Bei einer Abweichung gehören Auswahl und relevantes Lagerbild dazu; bei Bewegung die Ereignishistorie statt eines ausgeschnittenen Statusworts.","Ermitteln Sie anhand von Evidenz: Handeln, wenn die Oberfläche eine Aktion verlangt, ein offengelegtes Verkäuferdatum überschritten ist, Tracking dem erwarteten Kontrollpunkt widerspricht oder aktuelle Hilfe zur Fallöffnung rät. Weiter beobachten, wenn kein Widerspruch vorliegt und die Stufe noch bei einer anderen Partei liegt. Prüfen Sie Live-Anweisungen, weil Fristen und Wörter sich ändern können."]},
      {heading:"Vor der Paketerstellung den Vier-Status-Audit ausführen",paragraphs:["Prüfen Sie jeden vorgesehenen Artikel der Reihe nach. Purchased: Wurde die angeforderte Identität und Variante beschafft? Seller Shipped: Ist Inlandsbewegung belegt? Received: Hat das Lager den richtigen physischen Artikel erfasst? Stored: Ist die Behalten-Entscheidung abgeschlossen und der Artikel in der Paketverwaltung verfügbar? Jede offene Antwort bleibt sichtbar und wird nicht durch einen späteren Status verdeckt.","Ein Status ist ein Kontrollpunkt, keine Garantie. Bewahren Sie Wortlaut, Daten und Kennungen; trennen Sie Artikel-, Lager- und Paketobjekte; fragen Sie nach dem nächsten überprüfbaren Ereignis. Diese Methode bleibt auch bei neuen Bezeichnungen brauchbar, weil sie Prozessfolge und Belegverantwortung nutzt. Prüfen Sie vor dem Handeln stets die aktuelle Oberfläche, besonders bei Schaltflächen, Fristen, Diensten und Richtlinien."]}
      ,{heading:"Praktische Belegnotizen für jeden Übergang",paragraphs:["Halten Sie zusätzlich fest, welche Partei den nächsten Schritt kontrolliert und welche Evidenz einen echten Übergang bestätigen würde. Nach Purchased ist das beispielsweise ein datierter Verkäuferversand und nicht nur eine allgemeine Erwartung. Nach Seller Shipped ist ein physisches Inlandsereignis stärker als die bloße elektronische Ankündigung. Nach Received zählen Zuordnung, sichtbare Identität und Ihre QC-Entscheidung. Nach Stored ist entscheidend, ob der Artikel auswählbar und ohne offene Rückgabe- oder Messfrage für die vorgesehene Paketgruppe bereit ist.","Wenn Angaben widersprüchlich wirken, bewahren Sie beide Versionen mit Datum auf. Überschreiben Sie einen früheren Status nicht, denn gerade der Verlauf erklärt eine Verzögerung. Notieren Sie, ob die Änderung von der Bestellseite, dem Tracking, einer Lagermeldung oder einer Support-Antwort stammt. So können Sie eine Behauptung wie ‘seit fünf Tagen unverändert’ durch eine nachvollziehbare Chronologie ersetzen und vermeiden, einen Hinweis aus einem anderen Auftrag versehentlich auf den aktuellen Artikel zu übertragen.","Schützen Sie bei jedem gespeicherten oder geteilten Nachweis persönliche Daten. Für eine Untersuchung genügen normalerweise die relevante Kennung, Variante, Statuszeile, Zeit und das betroffene Bild. Adresse, Zahlungsdaten, Kontostand und fremde Bestellungen gehören nicht in einen öffentlichen Screenshot. Bewahren Sie vollständige Originale privat auf, falls der Support sie ausdrücklich benötigt. Die veröffentlichte oder geteilte Version sollte nur das zeigen, was die konkrete Frage beantwortet, und darf keine garantierte Lösung oder Bearbeitungszeit versprechen."]}
      ,{heading:"Kurzer Abschlusscheck",paragraphs:["Prüfen Sie, dass jede Anfrage nur eine Prozessphase, die richtige Kennung, das letzte datierte Ereignis und eine klare Frage enthält. Getrennte Fälle bleiben verständlich und lassen sich fortschreiben, wenn der nächste erwartete Beleg nicht erscheint."]}
    ]
  },
  es: {
    title:"Guía de estados de pedido Sugargoo: comprado, enviado, recibido y almacenado",description:"Lee los estados Sugargoo como pruebas fechadas, separa el envío del vendedor del paquete internacional y verifica el siguiente paso.",category:"Flujo del pedido",readTime:"13 min de lectura",published:"2 de septiembre de 2026",
    sections:[
      {heading:"Identifica primero a qué objeto pertenece el estado",paragraphs:["Un estado de Sugargoo solo sirve si sabes qué objeto describe. El pedido de compra corresponde a un artículo, vendedor, variante y cantidad. El registro de almacén corresponde a la unidad física recibida en China. El registro de paquete agrupa uno o más artículos almacenados para envío internacional. Por eso ‘enviado’ puede significar que el vendedor inició el trayecto nacional o que un paquete terminado salió al destino: recorridos, identificadores y acciones distintos.","Antes de interpretar la etiqueta, registra página, número de pedido, vendedor o artículo de origen, variante, estado exacto, fecha y hora. Si revisas un paquete, añade por separado número de paquete y seguimiento. Esta cabecera evita aplicar expectativas de tracking internacional al despacho del vendedor o asumir que un artículo ya está en un paquete porque otro artículo del mismo conjunto está listo."]},
      {heading:"Lee Purchased como punto de control de compra",paragraphs:["Purchased suele indicar que la compra avanzó más allá de una solicitud sin pagar, pero no demuestra despacho del vendedor, recepción ni QC aprobada. Manda el detalle actual. Verifica enlace, color, talla, versión, cantidad y observación; conserva importe y hora porque un cambio posterior del anuncio no documenta bien lo elegido.","En esta fase observa, no planifiques el paquete. Busca un evento fechado del vendedor. Si no cambia, separa un retraso de fin de semana, preventa, personalización o plazo comunicado. No inventes una fecha universal. Usa el detalle y la ayuda actuales, e identifica pedido y último evento al pedir investigación."]},
      {heading:"Trata Seller Shipped como movimiento nacional",paragraphs:["Cuando el pedido del artículo muestra envío del vendedor, normalmente viaja al almacén, no a tu dirección final. El seguimiento nacional no es el del paquete internacional. Guarda fecha y eventos exactos. Una etiqueta electrónica es una prueba más débil que una aceptación o movimiento físico; conserva el texto real sin exagerarlo.","El siguiente punto es la recepción. No digas solo ‘tracking parado’: indica si hablas del vendedor, transportista nacional o entrada de almacén y aporta el último evento. Sigue cada artículo por separado. Los vendedores pueden avanzar a ritmos distintos y la consolidación solo se evalúa cuando todos los artículos previstos tienen un estado accionable."]},
      {heading:"Separa Received de la aprobación de inspección",paragraphs:["Received demuestra que el almacén registró una entrada, no certifica calidad. Revisa identidad, opción, cantidad y condición visible. Compara producto, color, etiqueta de talla, unidades y piezas antes de los detalles de QC. La guía pública describe fotos estándar tras la llegada; la interfaz actual determina qué hay para el artículo concreto.","Si existe una duda, registra campo esperado, campo observado e imagen. ‘Artículo incorrecto’ es débil; ‘pedido negro talla 42, imagen 3 azul talla 41’ es investigable. Solicita solo el ángulo o medida necesarios. Las fotos no prueban autenticidad, composición, comodidad o duración, únicamente lo visible."]},
      {heading:"Usa Stored como preparación, no promesa de envío",paragraphs:["Stored suele indicar que el artículo está asociado a tu cuenta y puede gestionarse. No significa embalado para exportación, apto para todas las rutas o protegido por una decisión final. Confirma devoluciones, decisión QC y selección real al crear paquete. Guarda cualquier fecha de almacenamiento porque las reglas dependen del tiempo.","Crea una tabla con ID, estado, problema pendiente y grupo de paquete. Marca listo solo cuando identidad y decisión estén claras. Es normal mezclar estados: almacenado, esperando medida o en devolución. Así ‘seleccionar todo’ no arrastra un artículo sin resolver."]},
      {heading:"Mantén un registro fechado, no una captura aislada",paragraphs:["Una captura muestra apariencia, no progresión. Registra hora, tipo de objeto, identificador, estado exacto, último evento físico, prueba, siguiente control y responsable. Añade filas cuando cambia la evidencia. Distinguirás una pausa normal y sabrás si actúa vendedor, transportista, almacén, tu decisión QC o la creación del paquete.","Ejemplo: Purchased el lunes, Seller Shipped el miércoles, aceptación jueves y Received viernes; otro artículo sigue Purchased. No hay retraso del paquete internacional porque aún no existe. Decide si esperar, investigar al vendedor o enviar separado cuando conozcas condiciones de almacén y ruta."]},
      {heading:"Escala desde el último hecho verificado",paragraphs:["Aporta identificador, variante, estado exacto, último evento fechado, fecha de revisión y una pregunta. Adjunta lo mínimo ocultando datos ajenos. Para discrepancias incluye selección e imagen; para movimiento, historial completo y no una palabra recortada.","Actúa si la interfaz lo exige, vence una fecha comunicada, el tracking contradice el siguiente control o la ayuda vigente indica abrir caso. Observa si no hay contradicción y la fase pertenece a otra parte. Comprueba instrucciones en directo porque ventanas y textos cambian."]},
      {heading:"Haz la auditoría de cuatro estados antes del paquete",paragraphs:["Purchased pregunta si se compró identidad y variante. Seller Shipped pregunta si existe movimiento nacional. Received pregunta si el almacén registró el artículo correcto. Stored pregunta si la decisión está cerrada y el artículo es gestionable. Cada respuesta pendiente queda visible.","Un estado es control, no garantía. Guarda texto, fechas e IDs; separa artículo, almacén y paquete; busca el siguiente evento verificable. La técnica resiste cambios de etiqueta porque sigue la secuencia y el dueño de la evidencia. Revisa siempre la interfaz actual antes de actuar."]}
      ,{heading:"Notas prácticas de evidencia para cada transición",paragraphs:["Añade quién controla el siguiente paso y qué prueba confirmaría un cambio real. Después de Purchased, busca un despacho fechado del vendedor, no una expectativa general. Después de Seller Shipped, una aceptación física del transportista nacional pesa más que una etiqueta electrónica. Después de Received, importan la asociación con tu pedido, la identidad visible y tu decisión QC. Después de Stored, comprueba que el artículo sea seleccionable y que no exista una devolución, medida o discrepancia pendiente antes del grupo de paquete previsto.","Cuando dos datos parezcan contradecirse, conserva ambos con fecha. No sobrescribas el estado anterior: la secuencia es la que permite explicar un retraso. Anota si el dato procede de la página del pedido, del seguimiento, del almacén o de una respuesta de soporte. Así puedes sustituir ‘lleva días parado’ por una cronología investigable y evitas atribuir al artículo actual una alerta que pertenece a otro pedido del mismo haul.","Protege los datos personales en toda evidencia guardada o compartida. Para investigar suelen bastar identificador pertinente, variante, estado, hora e imagen afectada. Dirección, pago, saldo y otros pedidos no deben aparecer en una captura pública. Conserva el original completo en privado por si soporte lo solicita. La copia compartida debe limitarse a responder la pregunta concreta y nunca prometer resultado o tiempo de resolución.","Usa una pequeña revisión antes de enviar una consulta: una sola fase del flujo, un identificador correcto, un último hecho fechado, una pregunta y el resultado que necesitas confirmar. No mezcles una demora del vendedor con una consulta sobre tracking internacional, ni una foto QC con una reclamación de transporte. Separar los casos reduce la ambigüedad y conserva un historial que puede reutilizarse si el siguiente evento tampoco aparece."]}
      ,{heading:"Documenta también la decisión de esperar",paragraphs:["Si todavía no actúas, anota qué evidencia revisaste, por qué el silencio sigue siendo compatible con la fase y qué nuevo evento activará otra comprobación. Así evitas consultas repetidas y no conviertes la ausencia de un escaneo en promesa de entrega o pérdida confirmada."]}
    ]
  },
  fr: {
    title:"Statut de commande Sugargoo : acheté, expédié, reçu et stocké",description:"Interprétez les statuts Sugargoo comme des preuves datées, distinguez l’envoi vendeur du colis international et vérifiez la prochaine étape.",category:"Cycle de commande",readTime:"13 min de lecture",published:"2 septembre 2026",
    sections:[
      {heading:"Identifier d’abord l’objet concerné par le statut",paragraphs:["Un statut Sugargoo n’est utile que si son objet est clair. La commande d’achat concerne un article, un vendeur, une variante et une quantité. Le dossier d’entrepôt concerne l’article physique reçu en Chine. Le dossier colis regroupe des articles stockés pour l’international. « Expédié » peut donc désigner le trajet intérieur du vendeur ou le départ d’un colis final : parcours, identifiants et actions différents.","Avant toute interprétation, notez page, commande, vendeur ou article source, variante, libellé exact, date et heure. Pour un colis, ajoutez séparément numéro de colis et suivi. Cette en-tête évite d’appliquer les attentes d’un suivi international au vendeur ou de croire qu’un article est déjà emballé parce qu’un autre article du lot est prêt."]},
      {heading:"Lire Purchased comme contrôle d’approvisionnement",paragraphs:["Purchased indique généralement que l’achat a dépassé la demande non payée, sans prouver l’envoi vendeur, la réception ou un QC accepté. Le détail actuel fait foi. Vérifiez source, couleur, taille, version, quantité et remarque, puis conservez montant et heure car une page vendeur modifiée décrit mal le choix initial.","Il faut observer, pas encore planifier le colis. Cherchez un événement vendeur daté. En cas d’attente, distinguez retard, week-end, précommande, personnalisation ou délai annoncé. N’inventez pas de date universelle. Utilisez le détail et l’aide actuels, en donnant numéro et dernier événement pour une enquête."]},
      {heading:"Traiter Seller Shipped comme trajet intérieur",paragraphs:["Au niveau de l’article, l’envoi vendeur va normalement vers l’entrepôt et non vers l’adresse finale. Le suivi intérieur n’est pas celui du colis international. Gardez date et événements exacts. Une étiquette électronique est moins probante qu’une prise en charge ou un mouvement physique ; ne renforcez pas son sens.","Le prochain contrôle est la réception. Évitez « suivi bloqué » seul : précisez vendeur, transporteur intérieur ou entrée d’entrepôt et le dernier événement. Suivez chaque article séparément. Les vendeurs avancent différemment et un regroupement ne s’évalue que lorsque tous les articles visés ont un statut exploitable."]},
      {heading:"Séparer Received de l’acceptation de l’inspection",paragraphs:["Received prouve l’enregistrement d’une arrivée, pas la qualité. Contrôlez identité, option, quantité et état visible. Comparez produit, couleur, étiquette de taille, quantité et accessoires, puis les images QC. Les informations publiques décrivent des photos standard après l’arrivée ; l’interface active décide du dossier précis.","En cas d’écart, notez champ attendu, champ observé et image. « Mauvais article » est faible ; « noir taille 42 commandé, image 3 bleue taille 41 » est examinable. Demandez seulement l’angle ou la mesure utile. Les photos ne prouvent ni authenticité, composition, confort ni durabilité, seulement le visible."]},
      {heading:"Utiliser Stored comme préparation, non promesse",paragraphs:["Stored signale généralement un article lié au compte et gérable. Il n’est pas forcément emballé, admissible à toutes les routes ou protégé par un choix final. Vérifiez retours, décision QC et sélection réelle lors de la création. Sauvegardez toute date de stockage car les règles sont temporelles.","Tenez un tableau ID, statut, problème ouvert et groupe de colis. Ne marquez prêt qu’après identité et décision. Des états mixtes sont normaux : stocké, mesure attendue, retour en cours. Cela empêche « tout sélectionner » d’exporter un article non résolu."]},
      {heading:"Créer un journal daté plutôt qu’une seule capture",paragraphs:["Une capture montre un état, pas son évolution. Consignez heure, type d’objet, identifiant, libellé, dernier mouvement physique, preuve, prochain contrôle et responsable. Ajoutez une ligne quand la preuve change. Vous distinguerez une pause normale et saurez si l’action revient au vendeur, transporteur, entrepôt, à votre QC ou au colis.","Exemple : Purchased lundi, Seller Shipped mercredi, prise en charge jeudi, Received vendredi ; le second article reste Purchased. Aucun colis international n’est retardé puisqu’il n’existe pas. Choisissez d’attendre, d’enquêter ou de séparer plus tard après connaissance des conditions de stockage et de route."]},
      {heading:"Escalader à partir du dernier fait confirmé",paragraphs:["Donnez identifiant, variante, statut, dernier événement daté, date de vérification et une question. Joignez le minimum en masquant les données sans rapport. Pour un écart, sélection et image ; pour le mouvement, historique plutôt qu’un mot recadré.","Agissez si l’interface le demande, si une date annoncée est dépassée, si le suivi contredit le prochain contrôle ou si l’aide exige un dossier. Surveillez sans contradiction lorsque l’étape appartient encore à un tiers. Les délais et termes changent : vérifiez l’instruction actuelle."]},
      {heading:"Auditer les quatre états avant de créer le colis",paragraphs:["Purchased : identité et variante achetées ? Seller Shipped : mouvement intérieur prouvé ? Received : bon article physique enregistré ? Stored : décision terminée et article disponible ? Toute réponse ouverte reste visible au lieu d’être masquée par un statut ultérieur.","Un statut est un contrôle, pas une garantie. Gardez mots, dates et identifiants ; séparez article, entrepôt et colis ; recherchez le prochain événement vérifiable. La méthode survit aux changements d’étiquette grâce à la séquence et au responsable de la preuve. Relisez toujours l’interface active avant d’agir."]}
      ,{heading:"Notes pratiques de preuve à chaque transition",paragraphs:["Ajoutez la partie qui contrôle la prochaine étape et la preuve qui confirmerait une véritable transition. Après Purchased, recherchez un envoi vendeur daté plutôt qu’une attente générale. Après Seller Shipped, une prise en charge physique du transporteur intérieur vaut davantage qu’une étiquette électronique. Après Received, vérifiez l’association à votre commande, l’identité visible et la décision QC. Après Stored, contrôlez que l’article est sélectionnable et qu’aucune mesure, anomalie ou procédure de retour ne reste ouverte avant son groupe de colis.","Lorsque deux informations semblent contradictoires, conservez les deux avec leur date. N’écrasez pas l’ancien statut : c’est la chronologie qui permet de comprendre un retard. Notez si l’information vient de la commande, du suivi, de l’entrepôt ou d’une réponse du support. Vous remplacez ainsi ‘bloqué depuis plusieurs jours’ par un dossier examinable et vous évitez d’attribuer au mauvais article une alerte appartenant à une autre commande du même ensemble.","Protégez les données personnelles dans chaque preuve enregistrée ou partagée. Pour enquêter, l’identifiant utile, la variante, la ligne de statut, l’heure et l’image concernée suffisent généralement. Adresse, paiement, solde et commandes sans rapport ne doivent pas apparaître dans une capture publique. Gardez l’original complet en privé si le support le demande. La copie partagée doit répondre uniquement à la question précise et ne jamais promettre un résultat ou un délai de traitement.","Avant d’envoyer une demande, vérifiez qu’elle ne concerne qu’une phase, qu’elle contient la bonne référence, le dernier fait daté et une question unique. Ne mélangez pas un délai vendeur avec du suivi international, ni une photo QC avec une réclamation de transport. Des dossiers séparés réduisent l’ambiguïté et laissent une chronologie réutilisable si le prochain événement n’apparaît toujours pas."]}
      ,{heading:"Documenter aussi la décision d’attendre",paragraphs:["Si vous n’agissez pas encore, notez la preuve contrôlée, pourquoi le silence reste compatible avec l’étape et quel événement déclenchera un nouvel examen. Une pause documentée évite les demandes répétées et ne transforme pas l’absence de scan en promesse de livraison ou en perte confirmée.","Pour plusieurs articles, créez une ligne par objet avant tout résumé de groupe. Le résumé peut compter les éléments achetés, en trajet intérieur, reçus ou stockés, mais doit toujours conduire aux commandes qui le composent. Sans cette relation, l’avancement des autres masque facilement l’article bloqué.","Lors de la création du colis, archivez la dernière copie du tableau article et ouvrez un nouveau dossier avec l’identifiant colis. Le cycle international a ensuite ses propres événements, son transporteur et ses responsabilités. Cette frontière empêche de confondre l’envoi du vendeur avec le départ international plusieurs jours plus tard."]}
    ]
  },
  it: {
    title:"Stato ordine Sugargoo: acquistato, spedito, ricevuto e stoccato",description:"Leggi gli stati Sugargoo come prove datate, separa la spedizione del venditore dal pacco internazionale e verifica il passo successivo.",category:"Flusso ordine",readTime:"13 min di lettura",published:"2 settembre 2026",
    sections:[
      {heading:"Identifica prima l’oggetto a cui appartiene lo stato",paragraphs:["Uno stato Sugargoo è utile solo se sai cosa descrive. L’ordine di acquisto riguarda articolo, venditore, variante e quantità. La registrazione di magazzino riguarda l’unità fisica ricevuta in Cina. Il pacco raggruppa articoli stoccati per l’invio internazionale. ‘Spedito’ può quindi indicare il tragitto interno dal venditore o la partenza del pacco finale: viaggi, identificatori e azioni diversi.","Prima di interpretare annota pagina, numero ordine, venditore o articolo sorgente, variante, testo esatto, data e ora. Per un pacco aggiungi separatamente numero pacco e tracking. Eviti così di applicare aspettative internazionali al trasporto del venditore o di pensare che un articolo sia già nel pacco perché un altro elemento dello stesso haul è pronto."]},
      {heading:"Leggi Purchased come controllo di approvvigionamento",paragraphs:["Purchased in genere indica che l’acquisto ha superato una richiesta non pagata, ma non prova spedizione del venditore, ricezione o QC approvato. Fa fede il dettaglio corrente. Verifica sorgente, colore, taglia, versione, quantità e nota; conserva importo e ora perché una pagina venditore modificata non documenta bene la selezione originale.","Qui serve osservare, non pianificare il pacco. Cerca un evento datato del venditore. Se non cambia, distingui ritardo, weekend, preordine, personalizzazione o tempo dichiarato. Non inventare una scadenza universale. Usa dettaglio e assistenza attuali, indicando ordine e ultimo evento per l’indagine."]},
      {heading:"Tratta Seller Shipped come movimento nazionale",paragraphs:["A livello articolo, l’invio del venditore normalmente va al magazzino e non all’indirizzo finale. Il tracking domestico non è quello internazionale. Salva data ed eventi esatti. Un’etichetta elettronica è prova più debole di presa in carico o movimento fisico; conserva il testo senza rafforzarlo.","Il controllo successivo è la ricezione. Non scrivere solo ‘tracking fermo’: indica venditore, vettore interno o ingresso in magazzino e l’ultimo evento. Segui ogni articolo separatamente. I venditori hanno ritmi diversi e il consolidamento si valuta solo quando tutti gli articoli previsti hanno uno stato gestibile."]},
      {heading:"Separa Received dall’approvazione dell’ispezione",paragraphs:["Received dimostra che il magazzino ha registrato l’arrivo, non certifica la qualità. Controlla identità, opzione, quantità e condizione visibile. Confronta prodotto, colore, etichetta taglia, unità e accessori prima del dettaglio QC. Le guide pubbliche descrivono foto standard dopo l’arrivo; l’interfaccia attuale decide il caso specifico.","Per un dubbio annota campo atteso, osservato e immagine. ‘Articolo sbagliato’ è debole; ‘ordine nero 42, immagine 3 blu 41’ è indagabile. Chiedi solo angolo o misura necessari. Le foto non provano autenticità, composizione, comfort o durata, ma solo ciò che mostrano."]},
      {heading:"Usa Stored come prontezza, non promessa di spedizione",paragraphs:["Stored di solito indica un articolo associato all’account e gestibile. Non significa già imballato, ammesso su ogni rotta o protetto da una scelta finale. Verifica resi, decisione QC e selezionabilità quando crei il pacco. Salva eventuali date di deposito perché le regole dipendono dal tempo.","Crea una tabella con ID, stato, problema aperto e gruppo previsto. Segna pronto solo quando identità e decisione sono chiare. Stati misti sono normali: stoccato, misura attesa, reso in corso. Così ‘seleziona tutto’ non esporta un articolo irrisolto."]},
      {heading:"Mantieni un registro datato, non un solo screenshot",paragraphs:["Uno screenshot mostra uno stato, non il progresso. Registra ora, tipo oggetto, ID, testo, ultimo evento fisico, prova, controllo successivo e responsabile. Aggiungi una riga quando cambia l’evidenza. Distinguerai pause normali e saprai se tocca a venditore, corriere, magazzino, tua decisione QC o invio pacco.","Esempio: Purchased lunedì, Seller Shipped mercoledì, presa in carico giovedì, Received venerdì; un secondo articolo resta Purchased. Non esiste ancora un pacco internazionale in ritardo. Decidi se attendere, indagare o separare più avanti dopo aver verificato condizioni di magazzino e rotta."]},
      {heading:"Fai escalation dall’ultimo fatto verificato",paragraphs:["Fornisci identificatore, variante, stato esatto, ultimo evento datato, data di controllo e una domanda. Allega il minimo oscurando dati estranei. Per discrepanze servono selezione e immagine; per movimento, cronologia completa e non una parola ritagliata.","Agisci se l’interfaccia lo richiede, una data dichiarata è superata, il tracking contraddice il prossimo controllo o l’aiuto corrente indica di aprire un caso. Continua a monitorare senza contraddizioni se la fase appartiene a un’altra parte. Testi e finestre cambiano: verifica sempre l’istruzione live."]},
      {heading:"Esegui l’audit dei quattro stati prima del pacco",paragraphs:["Purchased: identità e variante acquistate? Seller Shipped: movimento interno provato? Received: articolo fisico corretto registrato? Stored: decisione completata e articolo disponibile? Ogni risposta aperta resta visibile e non viene nascosta da un’etichetta successiva.","Uno stato è un controllo, non una garanzia. Conserva parole, date e ID; separa articolo, magazzino e pacco; cerca il prossimo evento verificabile. Il metodo resiste ai cambi di etichetta perché segue sequenza e proprietario della prova. Ricontrolla l’interfaccia attuale prima di agire."]}
      ,{heading:"Note pratiche di prova per ogni passaggio",paragraphs:["Aggiungi chi controlla il prossimo passo e quale prova confermerebbe una transizione reale. Dopo Purchased cerca una spedizione datata del venditore, non una semplice aspettativa. Dopo Seller Shipped, una presa in carico fisica del corriere interno vale più di un’etichetta elettronica. Dopo Received contano l’associazione al tuo ordine, l’identità visibile e la decisione QC. Dopo Stored verifica che l’articolo sia selezionabile e senza reso, misura o discrepanza aperti prima di assegnarlo al gruppo pacco.","Quando due dati sembrano in conflitto, conserva entrambi con la data. Non sovrascrivere lo stato precedente, perché la sequenza spiega il ritardo. Annota se il dato arriva dalla pagina ordine, dal tracking, dal magazzino o da una risposta di assistenza. In questo modo ‘fermo da giorni’ diventa una cronologia indagabile ed eviti di attribuire all’articolo corrente un avviso che appartiene a un altro ordine dello stesso haul.","Proteggi i dati personali in ogni prova salvata o condivisa. Per un’indagine bastano normalmente identificatore pertinente, variante, riga di stato, orario e immagine coinvolta. Indirizzo, pagamento, saldo e altri ordini non devono comparire in uno screenshot pubblico. Conserva l’originale completo in privato se il supporto lo richiede. La copia condivisa deve rispondere solo alla domanda precisa e non promettere mai risultato o tempo di gestione.","Prima di inviare una richiesta, controlla che riguardi una sola fase, contenga il riferimento corretto, l’ultimo fatto datato e una domanda unica. Non mescolare ritardo del venditore e tracking internazionale, né foto QC e reclamo di trasporto. Separare i casi riduce l’ambiguità e mantiene uno storico riutilizzabile se anche il prossimo evento non appare."]}
      ,{heading:"Documenta anche la decisione di attendere",paragraphs:["Se non agisci subito, annota quale prova hai controllato, perché il silenzio è ancora compatibile con la fase e quale evento farà partire una nuova verifica. Una pausa documentata evita richieste duplicate e non trasforma l’assenza di una scansione in promessa di consegna o perdita confermata.","Con più articoli crea una riga per ciascun oggetto prima del riepilogo. Il totale può contare acquistati, in viaggio interno, ricevuti e stoccati, ma deve sempre portare agli ordini che lo compongono. Altrimenti il progresso degli altri nasconde facilmente l’elemento bloccato.","Quando crei il pacco archivia l’ultima copia della tabella articoli e apri un nuovo record con l’identificatore del pacco. Il ciclo internazionale ha eventi, vettore e responsabilità propri. Mantenere questo confine impedisce di confondere lo ‘spedito’ del venditore con la partenza internazionale avvenuta giorni dopo.","Alla revisione successiva confronta il nuovo evento con quello atteso, non con un’idea generica di velocità. Se corrisponde, aggiorna cronologia e responsabile. Se contraddice la fase o richiede un’azione, apri un caso preciso con i documenti già organizzati. Il metodo non promette un esito, ma rende ogni passaggio leggibile."]}
    ]
  }
} as const;
