import { Locale } from "@/lib/site-data";
import { faqAnswerExpansions, pageIntroExpansions, pageSectionExpansions } from "@/lib/page-content-expansions";

export const pageSlugs = ["spreadsheet", "finds", "guide", "qc", "shipping", "faq", "articles"] as const;
export type PageSlug = (typeof pageSlugs)[number];
export function isPageSlug(value: string): value is PageSlug { return pageSlugs.includes(value as PageSlug); }

type PageCopy = { index: string; kicker: string; title: string; intro: string; note: string; sections: { title: string; body: string }[] };

export const pageContent: Record<Locale, Record<PageSlug, PageCopy>> = {
  en: {
    spreadsheet: { index: "01", kicker: "Live catalog routes", title: "A spreadsheet that behaves like a useful shop index.", intro: "Browse visual product cards, open the exact destination and treat every price as a reference until the current listing is confirmed. The aim is faster discovery without pretending that a link alone proves quality.", note: "Images and product destinations are matched to the live catalog.", sections: [
      { title: "What route checked means", body: "A route-checked badge only means the destination responded and matched the displayed record when reviewed. It does not certify the seller, material, batch, authenticity, availability or final warehouse result. Those questions must still be answered from the current listing and your own QC photos." },
      { title: "Why reference prices are labeled", body: "Marketplace prices can change with options, domestic delivery, promotions and exchange rates. We show an indicative USD conversion to help scanning, then send you to the live record for the current amount. The checkout and parcel estimate remain the authoritative values." },
      { title: "How to use the list", body: "Start with a category or search, open several candidates, compare option notes and save only the routes that still match your requirements. Once an item reaches the warehouse, make a new decision from the inspection images instead of relying on the spreadsheet thumbnail." },
    ]},
    finds: { index: "02", kicker: "Curated discovery", title: "Fewer claims. Better product decisions.", intro: "Finds are grouped for browsing speed, not presented as guaranteed recommendations. Every candidate should survive three checks: the live listing, the selected option and the warehouse evidence.", note: "A find is a starting point, not an endorsement.", sections: [
      { title: "Shortlist by use, not hype", body: "Choose the category, size range, material cues and budget that matter to you before opening dozens of items. A smaller comparison set makes it easier to notice option differences, domestic shipping costs and seller notes that can be missed during fast scrolling." },
      { title: "Keep listing and QC separate", body: "A polished seller image describes the offer; warehouse photos describe what actually arrived. Do not let a good thumbnail substitute for measurements, construction details, color accuracy or visible defects in the item stored for your order." },
      { title: "Re-check before paying", body: "Product routes may expire, redirect or expose different variants later. Confirm the title, options, price and seller information on the destination page every time you return to a saved find. Never assume an older screenshot represents the current listing." },
    ]},
    guide: { index: "03", kicker: "Start-to-parcel guide", title: "Know where each decision belongs.", intro: "A China shopping agent workflow has several separate stages. Product discovery, purchase, warehouse inspection and international parcel submission solve different problems, so evidence from one stage should not be mistaken for another.", note: "This independent guide explains the workflow; the live interface controls your order.", sections: [
      { title: "1. Find and inspect the source listing", body: "Use a product route or search result to reach the current listing. Review the selected color, size, model, quantity and seller notes. Product images can help identify the intended option, but they do not show the exact unit that will arrive at the warehouse." },
      { title: "2. Place the order with precise notes", body: "Confirm the option and add only useful instructions that can be checked. If a measurement, color detail or accessory matters, state it clearly. Vague requests such as ‘best quality’ are difficult to verify and do not replace selecting the correct listing option." },
      { title: "3. Review the warehouse evidence", body: "When the item arrives, compare the QC photos with the ordered option. Look for the whole item, labels only when relevant, visible defects, color consistency and requested measurements. Ask for an additional image when the standard views cannot answer a material question." },
      { title: "4. Build the parcel deliberately", body: "After accepting the item, compare available shipping lines for the destination, product type, size and chargeable weight. Packaging choices, consolidation and volumetric weight can change the estimate. The live parcel interface should always decide the final route." },
    ]},
    qc: { index: "04", kicker: "Warehouse photo method", title: "Read QC photos as evidence, not decoration.", intro: "Quality control is most useful when every photo answers a specific question. A structured checklist prevents buyers from approving an item because the first image simply looks clean.", note: "Standard photos have limits; request an extra view when a decision cannot be made.", sections: [
      { title: "Confirm the ordered variant", body: "Start with the basics: item type, color, size marking, model and included pieces. Compare them with the exact option in the order record. If the listing has several similar variants, small labels or design details may be the only reliable separator." },
      { title: "Inspect shape, symmetry and construction", body: "Use front, back and side views to compare alignment, panel shape, stitching paths, print placement and visible glue or surface damage. Lighting and lens angle can distort color or proportion, so use more than one view before drawing a conclusion." },
      { title: "Request measurable evidence", body: "For fit-sensitive products, ask for a ruler or tape measure in the same frame as the relevant dimension. A written size label cannot prove the actual garment length or insole measurement. Measurement photos are especially useful when seller charts are inconsistent." },
      { title: "Decide before the return window closes", body: "Record the issue clearly and act within the live order timeline. Do not wait for parcel submission to question a visible warehouse defect. Return eligibility, seller response and fees can differ by listing, so check the current order page rather than relying on a general rule." },
    ]},
    shipping: { index: "05", kicker: "Parcel planning", title: "Compare chargeable weight, not just kilograms.", intro: "International lines can bill from actual weight, volumetric weight or another route-specific rule. The cheapest-looking rate is not meaningful until the parcel dimensions, product restrictions and destination are known.", note: "Always confirm the current line rules and estimate in the live parcel tool.", sections: [
      { title: "Actual versus volumetric weight", body: "Actual weight comes from the scale. Volumetric weight converts parcel dimensions into a billing weight using the line’s divisor. A light but bulky parcel can therefore cost more than a compact parcel with the same scale weight. The applicable formula belongs to the selected route." },
      { title: "Packaging changes the calculation", body: "Removing unnecessary boxes may reduce volume, while reinforcement can increase dimensions and weight. Decide from the product’s fragility and the route rules rather than always choosing the smallest or strongest package. A damaged item is not a saving." },
      { title: "Consolidation is not automatically cheaper", body: "Combining items can reduce repeated base charges, but a larger parcel may enter a different weight tier or trigger volumetric billing. Compare the live estimate for one consolidated parcel against sensible splits before submission." },
      { title: "Restrictions come before price", body: "A line may exclude a product type, battery, liquid, size or destination even when its headline rate looks attractive. Filter for eligibility first, then compare estimated cost, tracking, delivery range, insurance options and the current terms shown for that route." },
    ]},
    faq: { index: "06", kicker: "Plain answers", title: "Questions worth answering before payment.", intro: "These answers separate product discovery from the agent’s transaction and warehouse process. They avoid fixed promises where the live listing, destination or parcel details can change the result.", note: "The FAQ is educational and does not replace current platform terms.", sections: [] },
    articles: { index: "07", kicker: "Research desk", title: "Practical articles for the decisions spreadsheets skip.", intro: "Long-form guides focus on inspection, parcel economics and workflow mistakes. Facts that can change are framed as checks to perform in the live interface rather than permanent promises.", note: "Independent editorial content with dated research and clearly labeled evidence.", sections: [] },
  },
  de: {
    spreadsheet: { index:"01", kicker:"Aktive Katalogwege", title:"Eine Tabelle, die wie ein nützlicher Shop-Index funktioniert.", intro:"Durchsuche visuelle Produktkarten, öffne das genaue Ziel und behandle jeden Preis als Richtwert, bis das aktuelle Angebot bestätigt ist. Ziel ist schnellere Entdeckung, ohne einen Link mit Qualitätsnachweis zu verwechseln.", note:"Bilder und Produktziele sind dem Live-Katalog zugeordnet.", sections:[
      {title:"Was „Weg geprüft“ bedeutet",body:"Das Kennzeichen bedeutet nur, dass das Ziel beim letzten Check erreichbar war und zum gezeigten Datensatz passte. Es bestätigt weder Verkäufer, Material, Charge, Echtheit, Verfügbarkeit noch das spätere Lagerergebnis. Diese Punkte müssen im aktuellen Angebot und anhand deiner QC-Fotos geprüft werden."},
      {title:"Warum Preise als Richtwerte erscheinen",body:"Marktplatzpreise können sich durch Optionen, Inlandsversand, Aktionen und Wechselkurse ändern. Die USD-Umrechnung erleichtert den Vergleich; der aktuelle Betrag steht auf der Zielseite. Checkout und Paketschätzung bleiben maßgeblich."},
      {title:"So nutzt du die Liste",body:"Beginne mit Kategorie oder Suche, öffne mehrere Kandidaten und vergleiche Optionen und Verkäuferhinweise. Speichere nur passende, erreichbare Wege. Nach Ankunft im Lager triffst du eine neue Entscheidung anhand der Inspektionsbilder statt anhand des Tabellenfotos."},
    ]},
    finds:{index:"02",kicker:"Kuratierte Entdeckung",title:"Weniger Behauptungen. Bessere Produktentscheidungen.",intro:"Fundstücke sind zum schnellen Stöbern gruppiert und keine garantierten Empfehlungen. Jeder Kandidat muss drei Prüfungen bestehen: aktuelles Angebot, gewählte Option und Lagernachweis.",note:"Ein Fundstück ist ein Ausgangspunkt, keine Empfehlung.",sections:[
      {title:"Nach Nutzen statt Hype auswählen",body:"Lege Kategorie, Größenbereich, Materialmerkmale und Budget fest, bevor du viele Artikel öffnest. Eine kleine Vergleichsgruppe macht Unterschiede bei Optionen, Inlandsversand und Verkäuferhinweisen leichter sichtbar."},
      {title:"Angebot und QC getrennt bewerten",body:"Verkäuferbilder beschreiben das Angebot; Lagerfotos zeigen, was tatsächlich angekommen ist. Ein gutes Vorschaubild ersetzt keine Messungen, Konstruktionsdetails, Farbkontrolle oder sichtbare Mängel am eingelagerten Artikel."},
      {title:"Vor Zahlung erneut prüfen",body:"Produktwege können auslaufen, umleiten oder später andere Varianten zeigen. Bestätige Titel, Optionen, Preis und Verkäufer bei jedem erneuten Öffnen. Ein älterer Screenshot ist kein Beleg für das aktuelle Angebot."},
    ]},
    guide:{index:"03",kicker:"Vom Fund bis zum Paket",title:"Wisse, an welcher Stelle welche Entscheidung fällt.",intro:"Ein Einkaufsagent-Ablauf besteht aus getrennten Stufen. Produktsuche, Kauf, Lagerprüfung und internationale Paketeinreichung lösen verschiedene Probleme; Belege aus einer Stufe ersetzen nicht die nächste.",note:"Dieser unabhängige Leitfaden erklärt den Ablauf; die Live-Oberfläche steuert die Bestellung.",sections:[
      {title:"1. Quellangebot prüfen",body:"Öffne das aktuelle Angebot über Produktweg oder Suche. Kontrolliere Farbe, Größe, Modell, Menge und Verkäuferhinweise. Bilder zeigen die beabsichtigte Variante, aber nicht das konkrete Stück, das im Lager ankommt."},
      {title:"2. Präzise Bestellhinweise geben",body:"Bestätige die Option und ergänze nur überprüfbare Wünsche. Nenne wichtige Maße, Farben oder Zubehörteile klar. Vage Forderungen wie „beste Qualität“ lassen sich kaum prüfen und ersetzen keine korrekte Auswahl."},
      {title:"3. Lagernachweise auswerten",body:"Vergleiche nach Ankunft die QC-Fotos mit der bestellten Option. Prüfe Gesamtansichten, relevante Kennzeichnungen, sichtbare Fehler, Farbkonsistenz und angeforderte Maße. Fordere ein Zusatzfoto an, wenn Standardansichten eine wichtige Frage offenlassen."},
      {title:"4. Paket bewusst zusammenstellen",body:"Vergleiche nach Annahme die verfügbaren Linien für Ziel, Produkttyp, Größe und abrechenbares Gewicht. Verpackung, Konsolidierung und Volumengewicht verändern die Schätzung. Die Live-Paketansicht entscheidet über die endgültige Route."},
    ]},
    qc:{index:"04",kicker:"Methode für Lagerfotos",title:"QC-Fotos als Belege lesen, nicht als Dekoration.",intro:"Qualitätskontrolle hilft am meisten, wenn jedes Foto eine konkrete Frage beantwortet. Eine feste Checkliste verhindert Zustimmung nur wegen eines sauberen ersten Bildes.",note:"Standardfotos haben Grenzen; fordere bei offenen Entscheidungen eine Zusatzansicht an.",sections:[
      {title:"Bestellte Variante bestätigen",body:"Prüfe zuerst Artikeltyp, Farbe, Größenkennzeichnung, Modell und enthaltene Teile. Vergleiche alles mit der genauen Bestelloption. Bei ähnlichen Varianten können kleine Etiketten oder Designdetails den Unterschied zeigen."},
      {title:"Form, Symmetrie und Verarbeitung",body:"Nutze Vorder-, Rück- und Seitenansichten für Ausrichtung, Panel-Form, Nähte, Druckposition und sichtbare Klebe- oder Oberflächenschäden. Licht und Perspektive können Farbe und Proportion verzerren; vergleiche mehrere Ansichten."},
      {title:"Messbare Belege anfordern",body:"Bei passformkritischen Artikeln sollte Maßband oder Lineal zusammen mit dem relevanten Maß im Bild liegen. Ein Größenetikett beweist keine tatsächliche Länge oder Einlegesohle. Messfotos helfen besonders bei widersprüchlichen Größentabellen."},
      {title:"Vor Ende des Rückgabezeitraums entscheiden",body:"Beschreibe das Problem klar und handle innerhalb der aktuellen Bestellfrist. Warte nicht bis zur Paketeinreichung, um einen sichtbaren Mangel anzusprechen. Bedingungen und Gebühren können je Angebot abweichen."},
    ]},
    shipping:{index:"05",kicker:"Paketplanung",title:"Vergleiche abrechenbares Gewicht, nicht nur Kilogramm.",intro:"Internationale Linien können nach tatsächlichem Gewicht, Volumengewicht oder einer streckenspezifischen Regel abrechnen. Der günstigste Satz ist erst bei bekannten Maßen, Beschränkungen und Ziel relevant.",note:"Aktuelle Linienregeln und Schätzungen immer im Live-Paketwerkzeug bestätigen.",sections:[
      {title:"Tatsächliches und Volumengewicht",body:"Das tatsächliche Gewicht kommt von der Waage. Volumengewicht übersetzt die Paketmaße mit dem Divisor der Linie in ein Abrechnungsgewicht. Ein leichtes, großes Paket kann dadurch teurer sein als ein kompaktes Paket mit gleichem Waagengewicht."},
      {title:"Verpackung ändert die Rechnung",body:"Unnötige Kartons zu entfernen kann Volumen senken; Verstärkung kann Maße und Gewicht erhöhen. Entscheide nach Zerbrechlichkeit und Linienregeln, nicht grundsätzlich für die kleinste oder stärkste Verpackung."},
      {title:"Konsolidierung ist nicht automatisch günstiger",body:"Zusammenlegen kann Grundgebühren sparen, doch ein größeres Paket kann eine andere Gewichtsstufe oder Volumenabrechnung auslösen. Vergleiche die Live-Schätzung eines Gesamtpakets mit sinnvollen Aufteilungen."},
      {title:"Beschränkungen vor Preis",body:"Eine Linie kann Produkttyp, Batterie, Flüssigkeit, Größe oder Ziel ausschließen. Filtere zuerst nach Eignung und vergleiche danach Kosten, Tracking, Lieferbereich, Versicherung und die aktuell angezeigten Bedingungen."},
    ]},
    faq:{index:"06",kicker:"Klare Antworten",title:"Fragen, die vor der Zahlung beantwortet werden sollten.",intro:"Die Antworten trennen Produktsuche vom Transaktions- und Lagerprozess des Agenten. Sie vermeiden feste Versprechen, wenn Angebot, Ziel oder Paketdetails das Ergebnis verändern können.",note:"Die FAQ dient der Orientierung und ersetzt keine aktuellen Plattformbedingungen.",sections:[]},
    articles:{index:"07",kicker:"Recherche",title:"Praktische Artikel für Entscheidungen, die Tabellen überspringen.",intro:"Ausführliche Leitfäden behandeln Prüfung, Paketökonomie und typische Ablauffehler. Veränderliche Fakten werden als Live-Prüfungen formuliert, nicht als dauerhafte Versprechen.",note:"Unabhängige Inhalte mit datierter Recherche und klar gekennzeichneten Belegen.",sections:[]},
  },
  es: {} as Record<PageSlug, PageCopy>,
  fr: {} as Record<PageSlug, PageCopy>,
  it: {} as Record<PageSlug, PageCopy>,
};

// Localized pages preserve the complete information structure. The remaining
// locales are filled below to keep every route independent and fully translated.
Object.assign(pageContent.es, {
  spreadsheet:{index:"01",kicker:"Rutas activas",title:"Una hoja que funciona como un índice de tienda útil.",intro:"Explora tarjetas visuales, abre el destino exacto y trata cada precio como referencia hasta confirmar el anuncio actual. El objetivo es descubrir más rápido sin fingir que un enlace demuestra calidad.",note:"Imágenes y destinos están vinculados al catálogo activo.",sections:[{title:"Qué significa ruta comprobada",body:"La etiqueta solo indica que el destino respondió y coincidía con el registro mostrado al revisarlo. No certifica vendedor, material, versión, autenticidad, disponibilidad ni resultado del almacén. Esas cuestiones deben comprobarse en el anuncio y en tus fotos de QC."},{title:"Por qué el precio es orientativo",body:"Opciones, envío nacional, promociones y cambio pueden alterar el importe. La conversión USD facilita comparar, pero el importe vigente está en la página de destino. El pago y la estimación de paquete son los valores definitivos."},{title:"Cómo usar la lista",body:"Empieza por categoría o búsqueda, abre varios candidatos y compara opciones y notas. Guarda solo rutas activas que cumplan tus requisitos. Cuando el artículo llegue al almacén, decide de nuevo a partir de las imágenes de inspección."}]},
  finds:{index:"02",kicker:"Selección para descubrir",title:"Menos afirmaciones. Mejores decisiones.",intro:"Los hallazgos se agrupan para navegar rápido, no como recomendaciones garantizadas. Cada candidato debe superar tres controles: anuncio activo, opción elegida y evidencia del almacén.",note:"Un hallazgo es un punto de partida, no un respaldo.",sections:[{title:"Elige por utilidad, no por fama",body:"Define categoría, tallas, señales de material y presupuesto antes de abrir decenas de artículos. Una lista corta facilita detectar diferencias de opciones, envío nacional y notas del vendedor."},{title:"Separa anuncio y QC",body:"La imagen del vendedor describe la oferta; las fotos del almacén muestran lo recibido. Una miniatura atractiva no sustituye medidas, construcción, color ni defectos visibles del artículo almacenado."},{title:"Comprueba antes de pagar",body:"Las rutas pueden caducar, redirigir o mostrar otras variantes. Confirma título, opciones, precio y vendedor cada vez que vuelvas. Una captura antigua no representa necesariamente el anuncio actual."}]},
  guide:{index:"03",kicker:"De la búsqueda al paquete",title:"Sabe dónde corresponde cada decisión.",intro:"El flujo de un agente tiene etapas separadas. Descubrir, comprar, inspeccionar en almacén y enviar internacionalmente resuelven problemas distintos; la evidencia de una etapa no sustituye a la siguiente.",note:"Esta guía independiente explica el proceso; la interfaz activa controla el pedido.",sections:[{title:"1. Revisa el anuncio de origen",body:"Abre el anuncio actual mediante la ruta o la búsqueda. Comprueba color, talla, modelo, cantidad y notas. Las imágenes identifican la variante pretendida, pero no la unidad exacta que llegará al almacén."},{title:"2. Da instrucciones precisas",body:"Confirma la opción y añade solo instrucciones comprobables. Indica con claridad medidas, colores o accesorios importantes. Peticiones vagas como “mejor calidad” no pueden verificarse y no sustituyen una selección correcta."},{title:"3. Evalúa la evidencia del almacén",body:"Compara las fotos QC con la opción pedida. Revisa vistas completas, marcas relevantes, defectos, color y medidas solicitadas. Pide una foto adicional cuando las vistas estándar no resuelvan una duda material."},{title:"4. Prepara el paquete con intención",body:"Compara líneas para destino, tipo de producto, tamaño y peso facturable. Embalaje, consolidación y peso volumétrico cambian la estimación. La herramienta activa debe decidir la ruta final."}]},
  qc:{index:"04",kicker:"Método para fotos de almacén",title:"Lee las fotos QC como evidencia, no decoración.",intro:"El control sirve cuando cada imagen responde a una pregunta. Una lista estructurada evita aprobar un artículo solo porque la primera foto parece limpia.",note:"Las fotos estándar tienen límites; solicita otra vista si falta evidencia.",sections:[{title:"Confirma la variante",body:"Comprueba tipo, color, talla, modelo y piezas incluidas frente a la opción exacta. En variantes parecidas, una etiqueta pequeña o detalle de diseño puede ser la única diferencia fiable."},{title:"Forma, simetría y construcción",body:"Usa vistas frontal, posterior y lateral para alineación, forma, costuras, estampado y daños. La iluminación y el ángulo pueden distorsionar color y proporción, así que compara varias vistas."},{title:"Pide evidencia medible",body:"Para productos sensibles al ajuste, pide regla o cinta en el mismo plano que la medida. Una etiqueta de talla no prueba la longitud real o la plantilla. Las fotos con medidas ayudan cuando las tablas son inconsistentes."},{title:"Decide antes de cerrar la devolución",body:"Describe el problema y actúa dentro del plazo activo. No esperes al paquete para cuestionar un defecto visible. Elegibilidad, respuesta y gastos varían por anuncio; revisa el pedido actual."}]},
  shipping:{index:"05",kicker:"Planificación del paquete",title:"Compara peso facturable, no solo kilos.",intro:"Las líneas pueden cobrar por peso real, volumétrico u otra regla. La tarifa más baja no significa nada hasta conocer dimensiones, restricciones y destino.",note:"Confirma siempre reglas y estimación en la herramienta de paquete activa.",sections:[{title:"Peso real y volumétrico",body:"El peso real viene de la báscula. El volumétrico convierte dimensiones mediante el divisor de la línea. Un paquete ligero pero grande puede costar más que uno compacto con el mismo peso real."},{title:"El embalaje cambia el cálculo",body:"Quitar cajas innecesarias reduce volumen; reforzar puede aumentar tamaño y peso. Decide según fragilidad y reglas, no eligiendo siempre el paquete más pequeño o fuerte."},{title:"Consolidar no siempre abarata",body:"Combinar puede reducir cargos base, pero un paquete grande puede entrar en otro tramo o activar volumen. Compara la estimación consolidada con divisiones razonables."},{title:"Restricciones antes que precio",body:"Una línea puede excluir tipo de producto, batería, líquido, tamaño o destino. Filtra primero la elegibilidad y después compara coste, seguimiento, plazo, seguro y condiciones actuales."}]},
  faq:{index:"06",kicker:"Respuestas claras",title:"Preguntas que conviene resolver antes de pagar.",intro:"Las respuestas separan descubrimiento del proceso de transacción y almacén. Evitan promesas fijas cuando el anuncio, destino o paquete pueden cambiar el resultado.",note:"El FAQ es educativo y no sustituye condiciones actuales.",sections:[]},
  articles:{index:"07",kicker:"Mesa de investigación",title:"Artículos prácticos para decisiones que una hoja omite.",intro:"Las guías extensas tratan inspección, economía del paquete y errores de flujo. Los datos cambiantes se plantean como comprobaciones en vivo, no promesas permanentes.",note:"Contenido editorial independiente escrito para compradores.",sections:[]},
});

Object.assign(pageContent.fr, {
  spreadsheet:{index:"01",kicker:"Routes actives",title:"Un tableau qui fonctionne comme un véritable index boutique.",intro:"Parcourez les cartes, ouvrez la destination exacte et considérez chaque prix comme indicatif jusqu’à confirmation de l’annonce. L’objectif est de découvrir plus vite sans prétendre qu’un lien prouve la qualité.",note:"Images et destinations correspondent au catalogue actif.",sections:[{title:"Sens de « route contrôlée »",body:"Le badge indique seulement que la destination répondait et correspondait au dossier lors du contrôle. Il ne certifie ni vendeur, matière, version, authenticité, disponibilité ni résultat d’entrepôt. Vérifiez ces points sur l’annonce et vos photos QC."},{title:"Pourquoi un prix indicatif",body:"Options, livraison nationale, promotions et change peuvent modifier le montant. La conversion USD facilite le tri, mais le prix actuel reste celui de la page cible. Le paiement et l’estimation colis font foi."},{title:"Comment utiliser la liste",body:"Commencez par une catégorie ou une recherche, ouvrez plusieurs candidats et comparez options et notes. Gardez uniquement les routes actives adaptées. À l’arrivée en entrepôt, décidez de nouveau à partir des photos d’inspection."}]},
  finds:{index:"02",kicker:"Découverte sélectionnée",title:"Moins d’affirmations. De meilleures décisions.",intro:"Les sélections accélèrent la navigation sans devenir des recommandations garanties. Chaque candidat doit passer trois contrôles : annonce active, option choisie et preuve d’entrepôt.",note:"Une sélection est un point de départ, pas une approbation.",sections:[{title:"Choisir selon l’usage",body:"Définissez catégorie, taille, matière et budget avant d’ouvrir trop d’articles. Une liste courte permet de mieux voir les variantes, frais nationaux et notes vendeur."},{title:"Séparer annonce et QC",body:"L’image vendeur décrit l’offre ; les photos d’entrepôt montrent l’article reçu. Une belle miniature ne remplace ni mesures, construction, couleur ni défauts visibles."},{title:"Recontrôler avant paiement",body:"Les routes peuvent expirer, rediriger ou changer de variante. Confirmez titre, options, prix et vendeur à chaque retour. Une ancienne capture ne décrit pas forcément l’annonce actuelle."}]},
  guide:{index:"03",kicker:"De la recherche au colis",title:"Savoir où appartient chaque décision.",intro:"Le parcours d’un agent comprend plusieurs étapes. Découverte, achat, inspection et soumission internationale répondent à des problèmes différents ; une preuve d’une étape ne remplace pas la suivante.",note:"Ce guide indépendant explique le parcours ; l’interface active contrôle la commande.",sections:[{title:"1. Examiner l’annonce source",body:"Ouvrez l’annonce actuelle par la route ou la recherche. Vérifiez couleur, taille, modèle, quantité et notes. Les images identifient l’option prévue, pas l’unité exacte livrée à l’entrepôt."},{title:"2. Donner des instructions précises",body:"Confirmez l’option et ajoutez seulement des demandes vérifiables. Mentionnez clairement mesure, couleur ou accessoire. « Meilleure qualité » est trop vague et ne remplace pas le bon choix."},{title:"3. Lire les preuves d’entrepôt",body:"Comparez les photos QC avec l’option commandée. Contrôlez vues générales, repères utiles, défauts, couleur et mesures. Demandez une photo supplémentaire si une question importante reste ouverte."},{title:"4. Composer le colis",body:"Comparez les lignes selon destination, type, dimensions et poids facturable. Emballage, regroupement et poids volumétrique modifient l’estimation. L’outil actif décide de la route finale."}]},
  qc:{index:"04",kicker:"Méthode photo d’entrepôt",title:"Lire les photos QC comme des preuves.",intro:"Le contrôle est utile lorsque chaque photo répond à une question. Une méthode structurée évite d’approuver uniquement parce que la première image paraît propre.",note:"Les vues standard ont des limites ; demandez un complément si nécessaire.",sections:[{title:"Confirmer la variante",body:"Vérifiez type, couleur, taille, modèle et pièces incluses par rapport à l’option. Sur des variantes proches, une petite étiquette ou un détail peut être le seul repère fiable."},{title:"Forme, symétrie et construction",body:"Utilisez face, dos et profil pour l’alignement, la forme, les coutures, le placement et les dommages. Éclairage et angle déforment parfois couleur et proportion ; comparez plusieurs vues."},{title:"Demander une mesure visible",body:"Pour la coupe, demandez règle ou mètre dans la même image que la dimension. Une étiquette ne prouve pas la longueur réelle. Les photos mesurées aident lorsque les tableaux sont incohérents."},{title:"Décider avant la fin du retour",body:"Décrivez le problème et agissez dans le délai actif. N’attendez pas la soumission du colis pour signaler un défaut visible. Conditions, réponse vendeur et frais varient selon l’annonce."}]},
  shipping:{index:"05",kicker:"Planification colis",title:"Comparer le poids facturable, pas seulement les kilos.",intro:"Une ligne peut facturer le poids réel, volumétrique ou une règle propre. Le tarif affiché n’a de sens qu’avec dimensions, restrictions et destination.",note:"Confirmez toujours les règles et l’estimation dans l’outil colis actif.",sections:[{title:"Poids réel et volumétrique",body:"Le poids réel vient de la balance. Le volumétrique convertit les dimensions avec le diviseur de la ligne. Un colis léger mais encombrant peut coûter plus qu’un colis compact de même poids réel."},{title:"L’emballage change le calcul",body:"Retirer des boîtes réduit parfois le volume ; renforcer augmente parfois dimensions et poids. Décidez selon fragilité et règles, pas systématiquement pour le plus petit ou le plus solide."},{title:"Regrouper n’est pas toujours moins cher",body:"La consolidation réduit certains frais de base, mais un gros colis peut passer dans un autre palier ou déclencher le volume. Comparez le devis groupé à des séparations raisonnables."},{title:"Restrictions avant le prix",body:"Une ligne peut exclure type de produit, batterie, liquide, taille ou destination. Filtrez d’abord l’éligibilité, puis comparez coût, suivi, délai, assurance et conditions affichées."}]},
  faq:{index:"06",kicker:"Réponses claires",title:"Les questions à résoudre avant paiement.",intro:"Ces réponses séparent la découverte du processus de transaction et d’entrepôt. Elles évitent les promesses fixes lorsque annonce, destination ou colis changent le résultat.",note:"Cette FAQ est éducative et ne remplace pas les conditions actuelles.",sections:[]},
  articles:{index:"07",kicker:"Bureau de recherche",title:"Des articles pratiques pour les décisions ignorées par les tableaux.",intro:"Les guides longs traitent inspection, économie du colis et erreurs de parcours. Les faits variables deviennent des vérifications à faire en direct, jamais des promesses permanentes.",note:"Contenu éditorial indépendant pour les acheteurs.",sections:[]},
});

Object.assign(pageContent.it, {
  spreadsheet:{index:"01",kicker:"Percorsi attivi",title:"Un foglio che funziona come un vero indice di negozio.",intro:"Sfoglia schede visive, apri la destinazione esatta e considera ogni prezzo indicativo finché l’inserzione non è confermata. L’obiettivo è trovare più velocemente senza fingere che un link provi la qualità.",note:"Immagini e destinazioni corrispondono al catalogo attivo.",sections:[{title:"Cosa significa percorso controllato",body:"Il badge indica solo che la destinazione rispondeva e coincideva con il record al controllo. Non certifica venditore, materiale, versione, autenticità, disponibilità o risultato di magazzino. Verifica questi aspetti nell’inserzione e nelle foto QC."},{title:"Perché il prezzo è indicativo",body:"Opzioni, consegna interna, promozioni e cambio possono variare l’importo. La conversione USD facilita il confronto, ma il prezzo attuale è sulla pagina di destinazione. Checkout e stima pacco fanno fede."},{title:"Come usare la lista",body:"Parti da categoria o ricerca, apri più candidati e confronta opzioni e note. Salva solo percorsi attivi adatti. Quando l’articolo arriva in magazzino, decidi di nuovo usando le immagini di ispezione."}]},
  finds:{index:"02",kicker:"Scoperta selezionata",title:"Meno affermazioni. Decisioni migliori.",intro:"Le selezioni velocizzano la navigazione, non sono raccomandazioni garantite. Ogni candidato deve superare tre controlli: inserzione attiva, opzione scelta e prova di magazzino.",note:"Una selezione è un punto di partenza, non un’approvazione.",sections:[{title:"Scegli per uso, non per hype",body:"Definisci categoria, taglia, materiale e budget prima di aprire molti articoli. Una rosa corta rende più visibili differenze di opzione, spedizione interna e note del venditore."},{title:"Separa inserzione e QC",body:"La foto del venditore descrive l’offerta; le foto di magazzino mostrano ciò che è arrivato. Una miniatura bella non sostituisce misure, costruzione, colore o difetti visibili."},{title:"Ricontrolla prima di pagare",body:"I percorsi possono scadere, reindirizzare o cambiare variante. Conferma titolo, opzioni, prezzo e venditore ogni volta. Una vecchia schermata non rappresenta necessariamente l’inserzione attuale."}]},
  guide:{index:"03",kicker:"Dalla ricerca al pacco",title:"Sapere dove appartiene ogni decisione.",intro:"Il flusso di un agente ha fasi separate. Scoperta, acquisto, ispezione e invio internazionale risolvono problemi diversi; la prova di una fase non sostituisce quella successiva.",note:"Questa guida indipendente spiega il percorso; l’interfaccia attiva controlla l’ordine.",sections:[{title:"1. Esamina l’inserzione",body:"Apri l’offerta attuale dal percorso o dalla ricerca. Controlla colore, taglia, modello, quantità e note. Le immagini identificano l’opzione prevista, non l’unità esatta che arriverà in magazzino."},{title:"2. Dai istruzioni precise",body:"Conferma l’opzione e aggiungi solo richieste verificabili. Specifica misura, colore o accessorio importante. Richieste vaghe come “migliore qualità” non sono controllabili e non sostituiscono la scelta corretta."},{title:"3. Valuta le prove di magazzino",body:"Confronta le foto QC con l’opzione ordinata. Controlla viste complete, segni rilevanti, difetti, colore e misure. Chiedi una foto aggiuntiva se le viste standard non risolvono una domanda importante."},{title:"4. Costruisci il pacco con criterio",body:"Confronta linee per destinazione, tipo, dimensione e peso fatturabile. Imballaggio, consolidamento e volume cambiano la stima. Lo strumento attivo deve decidere la rotta finale."}]},
  qc:{index:"04",kicker:"Metodo foto di magazzino",title:"Leggi le foto QC come prove, non decorazioni.",intro:"Il controllo è utile quando ogni foto risponde a una domanda. Una lista strutturata evita approvazioni basate solo su una prima immagine pulita.",note:"Le foto standard hanno limiti; chiedi un’altra vista se manca una prova.",sections:[{title:"Conferma la variante",body:"Controlla tipo, colore, taglia, modello e pezzi inclusi rispetto all’opzione. Tra varianti simili, una piccola etichetta o dettaglio può essere l’unico separatore affidabile."},{title:"Forma, simmetria e costruzione",body:"Usa fronte, retro e lato per allineamento, forma, cuciture, stampa e danni. Luce e angolo possono alterare colore e proporzione; confronta più viste."},{title:"Chiedi prove misurabili",body:"Per la vestibilità, chiedi righello o metro nella stessa foto della misura. L’etichetta non prova la lunghezza reale. Le foto misurate aiutano quando le tabelle sono incoerenti."},{title:"Decidi prima della scadenza del reso",body:"Descrivi il problema e agisci entro la finestra attiva. Non aspettare il pacco per contestare un difetto visibile. Idoneità, risposta e costi variano per inserzione."}]},
  shipping:{index:"05",kicker:"Pianificazione pacco",title:"Confronta il peso fatturabile, non solo i chili.",intro:"Le linee possono fatturare peso reale, volumetrico o un’altra regola. La tariffa più bassa non significa nulla finché non conosci dimensioni, restrizioni e destinazione.",note:"Conferma sempre regole e stima nello strumento pacco attivo.",sections:[{title:"Peso reale e volumetrico",body:"Il peso reale viene dalla bilancia. Il volumetrico converte le dimensioni con il divisore della linea. Un pacco leggero ma grande può costare più di uno compatto con lo stesso peso reale."},{title:"L’imballaggio cambia il calcolo",body:"Rimuovere scatole può ridurre volume; rinforzare aumenta talvolta dimensioni e peso. Decidi secondo fragilità e regole, non scegliendo sempre il pacco più piccolo o robusto."},{title:"Consolidare non è sempre più economico",body:"Unire può ridurre costi base, ma un pacco grande può entrare in un’altra fascia o attivare il volume. Confronta la stima consolidata con divisioni ragionevoli."},{title:"Restrizioni prima del prezzo",body:"Una linea può escludere tipo di prodotto, batteria, liquido, dimensione o destinazione. Filtra prima l’idoneità, poi confronta costo, tracking, tempi, assicurazione e condizioni attuali."}]},
  faq:{index:"06",kicker:"Risposte chiare",title:"Domande da risolvere prima del pagamento.",intro:"Le risposte separano la scoperta dal processo di transazione e magazzino. Evitano promesse fisse quando inserzione, destinazione o pacco possono cambiare il risultato.",note:"Le FAQ sono educative e non sostituiscono le condizioni attuali.",sections:[]},
  articles:{index:"07",kicker:"Scrivania di ricerca",title:"Articoli pratici per le decisioni che i fogli saltano.",intro:"Le guide approfondite trattano ispezione, economia del pacco ed errori di flusso. I fatti variabili diventano controlli da fare in diretta, non promesse permanenti.",note:"Contenuto editoriale indipendente scritto per chi acquista.",sections:[]},
});

export const faqCopy: Record<Locale, { q: string; a: string }[]> = {
  en:[
    {q:"Is this an official Sugargoo website?",a:"No. This is an independent product-discovery and educational site. It does not process orders, payments, warehouse requests, returns or parcels."},
    {q:"Does route checked mean the product is verified?",a:"No. It only describes the destination check. Seller reliability, material, options and the item that reaches your warehouse require separate review."},
    {q:"Why can the live price differ from the USD value shown here?",a:"The displayed USD value is a reference conversion. Options, domestic delivery, promotions and exchange rates can change the current amount."},
    {q:"Can a spreadsheet guarantee product quality?",a:"No. A spreadsheet helps discovery. Quality decisions depend on the current listing, the selected option and the warehouse QC evidence for your specific item."},
    {q:"How many free QC photos does Sugargoo provide?",a:"Sugargoo's official 2025 QC guides describe five standard product photos and say unclear free QC or parcel images can be raised for a free retake. Confirm the current service on the active order because scope can change."},
    {q:"How long is Sugargoo warehouse storage?",a:"Sugargoo's official August 2025 storage guide described 100 free days. It listed extensions at CNY 8 per order per month, purchasable for up to 180 days at a time. Check the current account terms before relying on those figures."},
    {q:"How long can a Sugargoo return or refund take?",a:"Official 2025 guidance described warehouse-stage returns commonly taking 7–15 business days after seller verification and refunds reaching the Sugargoo balance within a range that can extend to 15 days. Eligibility and timing depend on the transaction."},
    {q:"Which Sugargoo payment methods are available?",a:"Official public guidance has listed cards, Alipay+, Wise, bank transfer, Apple Pay, Google Pay and several regional methods. Availability, fees and currency conversion differ by country and checkout, so use the methods shown in the live payment screen."},
    {q:"How should I choose a shipping line?",a:"Enter the destination, product type, weight and dimensions in the current parcel tool, filter eligible routes, then compare chargeable weight, cost, tracking and current terms."},
    {q:"Do you sell the products shown?",a:"No. Product cards open their corresponding live catalog records. This site is not a marketplace and does not take payment."},
  ],
  de:[
    {q:"Ist dies eine offizielle Sugargoo-Website?",a:"Nein. Dies ist eine unabhängige Seite für Produktsuche und Orientierung. Sie verarbeitet keine Bestellungen, Zahlungen, Lageranfragen, Rückgaben oder Pakete."},
    {q:"Bedeutet „Weg geprüft“, dass das Produkt verifiziert ist?",a:"Nein. Es beschreibt nur die Zielprüfung. Verkäufer, Material, Optionen und das eingelagerte Stück müssen separat bewertet werden."},
    {q:"Warum kann der Live-Preis abweichen?",a:"Der USD-Wert ist eine Richtumrechnung. Optionen, Inlandsversand, Aktionen und Wechselkurse können den aktuellen Betrag verändern."},
    {q:"Kann eine Tabelle Qualität garantieren?",a:"Nein. Sie hilft bei der Suche. Die Entscheidung hängt vom aktuellen Angebot, der gewählten Option und den QC-Belegen deines Artikels ab."},
    {q:"Wie viele kostenlose QC-Fotos gibt es?",a:"Offizielle Sugargoo-Leitfäden von 2025 beschreiben fünf Standardfotos und eine kostenlose Wiederholung unklarer kostenloser QC- oder Paketbilder. Prüfe den aktuellen Auftrag, da sich der Umfang ändern kann."},
    {q:"Wie lange ist die Lagerung kostenlos?",a:"Der offizielle Leitfaden vom August 2025 nannte 100 kostenlose Tage und Verlängerungen zu 8 CNY pro Auftrag und Monat, bis zu 180 Tage je Kauf. Bestätige die aktuellen Kontobedingungen."},
    {q:"Wie lange dauern Rückgabe und Erstattung?",a:"Offizielle Hinweise von 2025 beschrieben häufig 7–15 Arbeitstage nach Verkäuferprüfung und bis zu 15 Tage bis zur Gutschrift im Sugargoo-Guthaben. Eignung und Zeit hängen von der Transaktion ab."},
    {q:"Welche Zahlungsarten sind verfügbar?",a:"Öffentliche Hinweise nennen Karten, Alipay+, Wise, Banküberweisung, Apple Pay, Google Pay und regionale Methoden. Verfügbarkeit, Gebühren und Wechselkurs hängen von Land und Checkout ab."},
    {q:"Wie wähle ich eine Versandlinie?",a:"Gib Ziel, Produkttyp, Gewicht und Maße im aktuellen Paketwerkzeug ein, filtere geeignete Linien und vergleiche Abrechnungsgewicht, Kosten, Tracking und Bedingungen."},
    {q:"Verkauft diese Seite die Produkte?",a:"Nein. Karten öffnen die entsprechenden Live-Katalogeinträge. Diese Seite ist kein Marktplatz und nimmt keine Zahlungen an."},
  ],
  es:[
    {q:"¿Es una web oficial de Sugargoo?",a:"No. Es un sitio independiente de descubrimiento y educación. No procesa pedidos, pagos, solicitudes de almacén, devoluciones ni paquetes."},
    {q:"¿Ruta comprobada significa producto verificado?",a:"No. Solo describe el control del destino. Vendedor, material, opciones y artículo recibido necesitan revisión separada."},
    {q:"¿Por qué puede variar el precio?",a:"El valor USD es una conversión orientativa. Opciones, envío nacional, promociones y cambio pueden alterar el importe actual."},
    {q:"¿Una hoja garantiza calidad?",a:"No. Ayuda a descubrir. La calidad depende del anuncio, la opción elegida y la evidencia QC de tu unidad."},
    {q:"¿Cuántas fotos QC gratuitas hay?",a:"Las guías oficiales de 2025 describen cinco fotos estándar y repetición gratuita de imágenes gratuitas poco claras. Confirma el servicio actual en el pedido."},
    {q:"¿Cuánto tiempo es gratuito el almacén?",a:"La guía oficial de agosto de 2025 describió 100 días gratis y extensiones de 8 CNY por pedido y mes, hasta 180 días por compra. Confirma las condiciones actuales."},
    {q:"¿Cuánto tarda una devolución o reembolso?",a:"La guía de 2025 describió habitualmente 7–15 días laborables tras la verificación y hasta 15 días para el saldo Sugargoo. Elegibilidad y tiempo dependen de la operación."},
    {q:"¿Qué métodos de pago existen?",a:"La información pública ha listado tarjetas, Alipay+, Wise, transferencia, Apple Pay, Google Pay y métodos regionales. Disponibilidad, comisiones y cambio varían por país y pago."},
    {q:"¿Cómo elegir línea de envío?",a:"Introduce destino, tipo, peso y dimensiones en la herramienta activa, filtra rutas válidas y compara peso facturable, coste, seguimiento y condiciones."},
    {q:"¿Vendéis estos productos?",a:"No. Las tarjetas abren registros del catálogo activo. Este sitio no es un mercado ni acepta pagos."},
  ],
  fr:[
    {q:"Est-ce un site officiel Sugargoo ?",a:"Non. C’est un site indépendant de découverte et d’éducation. Il ne traite ni commande, paiement, demande d’entrepôt, retour ou colis."},
    {q:"Route contrôlée signifie-t-il produit vérifié ?",a:"Non. Cela décrit seulement le contrôle de destination. Vendeur, matière, options et article reçu nécessitent une évaluation séparée."},
    {q:"Pourquoi le prix peut-il varier ?",a:"Le montant USD est une conversion indicative. Options, livraison nationale, promotions et change peuvent modifier le prix actuel."},
    {q:"Un tableau garantit-il la qualité ?",a:"Non. Il aide à découvrir. La qualité dépend de l’annonce, de l’option et des preuves QC de votre unité."},
    {q:"Combien de photos QC gratuites ?",a:"Les guides officiels 2025 décrivent cinq photos standard et la reprise gratuite d’images gratuites peu claires. Confirmez le service actuel dans la commande."},
    {q:"Combien de temps le stockage est-il gratuit ?",a:"Le guide officiel d’août 2025 décrivait 100 jours gratuits et une extension à 8 CNY par commande et mois, jusqu’à 180 jours par achat. Vérifiez les conditions actuelles."},
    {q:"Combien de temps prend un retour ou remboursement ?",a:"Le guide 2025 décrivait souvent 7–15 jours ouvrés après vérification et jusqu’à 15 jours vers le solde Sugargoo. Éligibilité et délai dépendent de l’opération."},
    {q:"Quels moyens de paiement existent ?",a:"Les informations publiques ont cité cartes, Alipay+, Wise, virement, Apple Pay, Google Pay et moyens régionaux. Disponibilité, frais et change varient selon pays et paiement."},
    {q:"Comment choisir une ligne ?",a:"Saisissez destination, type, poids et dimensions dans l’outil actif, filtrez les routes éligibles puis comparez poids facturable, coût, suivi et conditions."},
    {q:"Vendez-vous les produits ?",a:"Non. Les cartes ouvrent les dossiers du catalogue actif. Ce site n’est pas une marketplace et n’accepte aucun paiement."},
  ],
  it:[
    {q:"È un sito ufficiale Sugargoo?",a:"No. È un sito indipendente di scoperta e informazione. Non gestisce ordini, pagamenti, richieste di magazzino, resi o pacchi."},
    {q:"Percorso controllato significa prodotto verificato?",a:"No. Descrive solo il controllo della destinazione. Venditore, materiale, opzioni e articolo ricevuto richiedono valutazioni separate."},
    {q:"Perché il prezzo può cambiare?",a:"Il valore USD è una conversione indicativa. Opzioni, spedizione interna, promozioni e cambio possono modificare l’importo attuale."},
    {q:"Un foglio garantisce la qualità?",a:"No. Aiuta a trovare. La qualità dipende dall’inserzione, dall’opzione scelta e dalle prove QC della tua unità."},
    {q:"Quante foto QC gratuite sono previste?",a:"Le guide ufficiali 2025 descrivono cinque foto standard e ripetizione gratuita di immagini gratuite poco chiare. Conferma il servizio attuale nell’ordine."},
    {q:"Quanto dura il deposito gratuito?",a:"La guida ufficiale di agosto 2025 descriveva 100 giorni gratuiti ed estensione a 8 CNY per ordine al mese, fino a 180 giorni per acquisto. Verifica i termini attuali."},
    {q:"Quanto richiede reso o rimborso?",a:"La guida 2025 descriveva spesso 7–15 giorni lavorativi dopo verifica e fino a 15 giorni verso il saldo Sugargoo. Idoneità e tempo dipendono dalla transazione."},
    {q:"Quali metodi di pagamento sono disponibili?",a:"Le informazioni pubbliche hanno elencato carte, Alipay+, Wise, bonifico, Apple Pay, Google Pay e metodi regionali. Disponibilità, commissioni e cambio variano per paese e checkout."},
    {q:"Come scelgo una linea?",a:"Inserisci destinazione, tipo, peso e dimensioni nello strumento attivo, filtra le rotte idonee e confronta peso fatturabile, costo, tracking e condizioni."},
    {q:"Vendete i prodotti mostrati?",a:"No. Le schede aprono i record del catalogo attivo. Questo sito non è un marketplace e non accetta pagamenti."},
  ],
};

for (const locale of ["de", "es", "fr", "it"] as const) {
  for (const [slug, additions] of Object.entries(pageSectionExpansions[locale])) {
    const page = pageContent[locale][slug as PageSlug];
    additions?.forEach((addition, index) => {
      if (page.sections[index]) page.sections[index].body += addition;
    });
  }
  faqCopy[locale].forEach((item, index) => {
    item.a += faqAnswerExpansions[locale][index] ?? "";
  });
  pageContent[locale].faq.intro += pageIntroExpansions[locale].faq;
  pageContent[locale].articles.intro += pageIntroExpansions[locale].articles;
}
