import type { ArticleContent } from "./article-data";

export const articleDe: Record<string, ArticleContent> = {
  "litbuy-spreadsheet-guide": {
    title: "Eine LitBuy-Tabelle nutzen, ohne das ursprüngliche Listing zu verlieren",
    deck: "Ein vollständiger Arbeitsablauf, der Fund, Quellseite, Bild, Preis, Variante und Produktidentität vom ersten Klick bis zur erneuten Prüfung zusammenhält.",
    readTime: "13 Min. Lesezeit",
    sections: [
      { heading: "Die Route ist Teil des Produkts", paragraphs: [
        "Ein Tabellenfund ist nur dann nützlich, wenn er zuverlässig zu genau dem Listing zurückführt, das in der Zeile beschrieben wird. Ein Produktname allein ist kein stabiler Beleg: Namen werden gekürzt, übersetzt, wiederverwendet oder vom Verkäufer verändert. Auch ein allgemeiner Kategorielink reicht nicht, weil der Leser den Artikel erneut suchen müsste. Behandle deshalb Ziel-URL, Quell-ID, Produktbild und neutrale Bezeichnung als gemeinsames Identitätspaket. Zeigt nur ein Bestandteil auf einen anderen Artikel, ist die Zeile noch nicht veröffentlichungsreif.",
        "Auf litbuys.store öffnet das Produktbild eine lokale Detailseite, während die Aktion zum zugeordneten Datensatz im Hauptkatalog führt. Die Detailseite wiederholt Quell-ID, CNY-Preis, USD-Richtwert und Prüfdatum. Diese Angaben garantieren keinen dauerhaften Bestand, machen aber sichtbar, was tatsächlich abgeglichen wurde. Wenn ein Verkäufer seine Seite ändert, lässt sich erkennen, welches Feld veraltet ist. Eine heimliche Umleitung auf irgendeinen ähnlichen Artikel würde zwar einen Klick retten, aber den wichtigsten Wert der Tabelle zerstören: eine nachvollziehbare Produktidentität."
      ]},
      { heading: "Identität vor Präsentation erfassen", paragraphs: [
        "Beginne immer auf der Quellseite und nicht beim Design der Karte. Speichere die saubere Produkt-URL ohne unnötige Trackingparameter und erfasse die Produkt- oder Datensatz-ID in einem eigenen Feld. Schreibe danach eine sachliche Bezeichnung, die nur sichtbare Merkmale nennt, etwa Sweatshirt, Trikot oder Umhängetasche. Erfinde keine Modellnamen, Materialien oder Qualitätsversprechen, die das Listing nicht eindeutig bestätigt. Eine kurze überprüfbare Bezeichnung ist für Nutzer und Suchmaschinen wertvoller als ein dekorativer Titel mit unbelegten Eigenschaften.",
        "Ordne anschließend das genaue Bild dieser Quellseite zu. Ähnliche schwarze Hoodies, weiße Schuhe oder Sporttrikots sind nicht austauschbar; sie können andere IDs, Verkäufer, Varianten und Preise besitzen. Vergleiche Silhouette, Farbstellung, Aufdruck, Hintergrund und sichtbares Zubehör. Wenn das Listing mehrere Optionen enthält, vermerke, ob die Tabellenabbildung nur eine Variante zeigt. Die sichtbare Quell-ID hilft später, doppelte Einträge zu erkennen oder die Spur wiederzufinden, falls LitBuy oder der Quellkatalog das URL-Format ändert."
      ]},
      { heading: "Bilder als Beleg abgleichen", paragraphs: [
        "Öffne Bild und Zielseite gleichzeitig in ausreichender Größe. Prüfe denselben Ausschnitt, Hintergrund, Farbton, Panelaufbau, Druck und dieselben mitgelieferten Teile. Ein scheinbar ähnliches Foto ist nicht genug. Besonders bei Produkten mit vielen Farb- oder Setvarianten muss deutlich sein, welche Option das Bild repräsentiert und ob der angezeigte Preis zu dieser Option gehört. Das Bild dient als Wegweiser zur Produktidentität; es ist weder eine Bestandszusage noch ein Beweis, dass alle sichtbaren Varianten zum gleichen Preis erhältlich sind.",
        "Speichere Bilder in einer sinnvollen Webgröße und verwende beschreibenden Alternativtext, ohne die Produktbelege durch starke Filter, ausgetauschte Hintergründe oder irreführende Zuschnitte zu verändern. Wenn ein Bild ausfällt, müssen Name, ID und Ziel weiterhin verständlich bleiben. Umgekehrt darf ein schönes zwischengespeichertes Bild einen entfernten Datensatz nicht aktuell erscheinen lassen. Verfügbarkeit, Varianten, Verkäuferhinweise und endgültiger Preis werden immer auf der aktuellen Zielseite erneut geprüft."
      ]},
      { heading: "Richtpreis und Endpreis trennen", paragraphs: [
        "Ein Tabellenpreis ist eine Momentaufnahme. Speichere zuerst den CNY-Wert der Quellseite, denn dieser zeigt, was zum Prüfzeitpunkt im Listing stand. Ein zusätzlicher USD-Wert hilft beim Vergleichen, muss jedoch ausdrücklich als Richtumrechnung gekennzeichnet werden. Wechselkurs, Verkäuferänderungen, Größe, Farbe, Bundle, chinesischer Inlandversand und Aktionen können den späteren Betrag verändern. Die USD-Angabe auf litbuys.store ist daher keine Checkout-Offerte und schon gar keine Schätzung des vollständigen internationalen Gesamtpreises.",
        "Prüfe außerdem den Optionswähler. Manche Listings zeigen einen niedrigen Startpreis, der zu Zubehör, einer Anzahlung oder der billigsten Variante gehört und nicht zur abgebildeten Konfiguration. Wenn sich die Optionen erst nach Interaktion offenbaren, dokumentiere den gewählten Stand vorsichtig und fordere den Leser zur Prüfung der Live-Seite auf. LitBuy arbeitet als Einkaufs- und Weiterleitungsdienst: Produktzahlung und internationaler Paketversand sind getrennte Stufen. Eine günstige Produktzeile darf deshalb nicht als gelandeter Gesamtpreis erscheinen."
      ]},
      { heading: "Veraltete und defekte Datensätze erkennen", paragraphs: [
        "Keine Tabelle bleibt automatisch aktuell. Verkäufer entfernen Waren, ersetzen Bilder, ändern Optionen und verschieben Katalogsysteme. Jeder Eintrag braucht ein sichtbares Prüfdatum und einen erneuten Abgleich in sinnvollen Abständen. Teste nicht nur, ob die Seite technisch lädt. Auch eine Soft-Fehlerseite kann einen normalen Status zurückgeben. Bestätige, dass erwartetes Bild, Quell-ID, Artikelidentität und Preisbereich noch vorhanden sind. Häufig besuchte Einträge sollten öfter geprüft werden als selten geöffnete Datensätze.",
        "Wenn ein Datensatz scheitert, leite ihn nicht still auf eine Kategorie um. Markiere ihn als nicht verfügbar, behalte die alte ID für die Nachvollziehbarkeit oder ersetze ihn erst nach einem vollständigen Neuabgleich. Sind mehrere Hostnamen oder Parameter-Versionen derselben Seite vorhanden, wähle eine saubere kanonische Route. Diese Pflege reduziert doppelte URLs, schützt die interne Verlinkung und verhindert, dass Nutzer auf derselben Karte zu unterschiedlichen oder unpassenden Produkten gelangen."
      ]},
      { heading: "Vom Verzeichnis zum Live-Katalog", paragraphs: [
        "Nutze die Tabelle, um nach Kategorie, Produktart und Richtbudget zu filtern, nicht um die Kaufentscheidung abzuschließen. Öffne zuerst die lokale Detailseite und gleiche Bild, Quell-ID, Preisbasis und Prüfdatum ab. Wechsle erst danach zum Hauptkatalog. Dort werden aktuelle Optionen, Verkäuferhinweise, Maße, Bestand und endgültiger Preis erneut geprüft. Fehlt eine wichtige Angabe, suche mit der Produkt-ID oder einem neutralen Begriff, statt einer alten Bildschirmaufnahme oder einem verkürzten Titel zu vertrauen.",
        "Halte die Zahl externer Ziele bewusst klein. Ein Produktverzeichnis wird schwer prüfbar, wenn identische Schaltflächen zu verschiedenen Plattformen, Kurzlinks oder unnötigen Zwischenstationen führen. Auf dieser Website bleiben Produkt-, Kategorie- und Suchaktionen innerhalb eines Hauptkatalogs. Die Grenze ist dadurch verständlich: litbuys.store ordnet, erklärt und dokumentiert; der verlinkte Katalog kontrolliert die aktuellen Listingdaten und die nächsten Schritte."
      ]},
      { heading: "Ein wiederholbarer Sieben-Schritte-Check", paragraphs: [
        "Verwende für jede neue Zeile dieselbe Reihenfolge: Quellseite öffnen; saubere URL und ID speichern; neutral benennen; genaues Bild zuordnen; Quellpreis und Optionen erfassen; Prüfdatum hinzufügen; und Bildroute sowie externe Aktion auf Desktop und Mobilgerät testen. Die Reihenfolge stellt Identität vor Gestaltung. Wenn ein Schritt unklar bleibt, wird der Eintrag nicht veröffentlicht. Das ist langsamer als automatisches Kopieren, verhindert aber kostspielige Fehlzuordnungen und stärkt die Qualität des gesamten Verzeichnisses.",
        "Teste zuletzt den Leserweg vollständig: Suche verwenden, Kategorie öffnen, Produktkarte auswählen, Detailseite lesen, Ziel aufrufen und zurücknavigieren. Die Sprache muss auf derselben Seite erhalten bleiben, und mobile Karten dürfen keinen horizontalen Bildlauf erzwingen. Gute SEO entsteht hier nicht durch ständige Wiederholung von „LitBuy Spreadsheet“, sondern durch nützliche indexierbare Datensätze, klare interne Pfade, ehrliche Aktualisierungssignale und Ziele, die die Aussage der Karte tatsächlich erfüllen."
      ]}
    ]
  },
  "litbuy-qc-photo-checklist": {
    title: "LitBuy-QC-Fotos: Was Lagerbilder zeigen können und was nicht",
    deck: "Eine vollständige Prüfreihenfolge für Schuhe, Kleidung, Taschen und Zubehör mit einer klaren Grenze zwischen sichtbarem Beleg und Vermutung.",
    readTime: "13 Min. Lesezeit",
    sections: [
      { heading: "Definieren, was QC beweisen kann", paragraphs: [
        "Ein QC-Foto zeigt einen Artikel, aus einem Winkel, unter einer bestimmten Beleuchtung und zu einem bestimmten Zeitpunkt. Es kann Gesamtform, sichtbare Verarbeitung, Markierungen, relative Farbe, Schmutz, Risse und Verpackungszustand dokumentieren. Es kann auch zeigen, ob Größen- oder Variantenetikett zum Auftrag passt. Ein Foto bestätigt jedoch weder Haltbarkeit, genaue Faserzusammensetzung, versteckte Konstruktion, Tragekomfort, Geruch noch zukünftige Funktion. Trenne deshalb jede sichtbare Beobachtung von Schlussfolgerungen, die das Bild nicht tragen kann.",
        "Diese Grenze entspricht den veröffentlichten LitBuy-Rückerstattungsbedingungen. Dort wird die grundlegende Lager-QC als Prüfung von Menge, sichtbarem Erscheinungsbild und offensichtlichen äußeren Mängeln beschrieben. Sie ist kein Labortest und kein Echtheitszertifikat. Formuliere präzise: „Die linke Naht wirkt im Frontbild höher“ ist überprüfbar; „schlechte Qualität“ ist zu allgemein. Nenne Ansicht, Stelle und zusätzlich benötigten Beleg, damit eine gezielte Nachaufnahme statt einer vagen Meinungsfrage entsteht."
      ]},
      { heading: "Mit Silhouette und Symmetrie beginnen", paragraphs: [
        "Prüfe zuerst vollständige Vorder-, Seiten- und Rückansichten, bevor du Logos oder einzelne Nähte vergrößerst. Gesamtproportionen zeigen Fehler, die bei Detailfokus übersehen werden: unterschiedliche Schuhformen, ungleich hohe Kragen, verdrehte Stoffbahnen, verschobene Taschen oder eine Tasche, die nicht gerade steht. Vergleiche links und rechts anhand stabiler Bezugspunkte wie Mittellinie, Oberkante, Sohle, Saum oder Griffansatz. Perspektive kann täuschen; behandle einen Unterschied erst als belastbar, wenn er in mehreren Ansichten erkennbar ist.",
        "Bei Schuhen vergleichst du Zehenform, Fersenstand, Seitenteile, Sohlenverklebung und beide Exemplare miteinander. Bei Kleidung folgen Schulterlinie, Ärmellänge, Saum, Knopfleiste und Druckposition. Taschen brauchen den Vergleich von Griffhöhe, Klappe, Paspelierung und Boden. Zubehör verlangt oft Vorder- und Rückseite, weil Verschlüsse hinter der Hauptfläche liegen. Große Strukturabweichungen sind meist wichtiger als ein einzelner loser Faden; löse deshalb Identität und Form vor dekorativen Kleinigkeiten."
      ]},
      { heading: "Konstruktion in fester Reihenfolge lesen", paragraphs: [
        "Nutze jedes Mal denselben Pfad: Silhouette, Hauptflächen, Nähte, Kanten, Verschlüsse, Beschläge, Oberfläche und Etiketten. Wiederholung verhindert, dass ein attraktives Hauptbild praktische Probleme verdeckt. Verfolge lange Nähte von Anfang bis Ende und achte auf plötzliche Abstandsänderungen, Falten oder ausgelassene Stiche. Prüfe geklebte Kanten auf sichtbare Ablösung und lackierte Kanten auf deutlichen Überlauf. Reißverschlüsse, Druckknöpfe und Schnallen sollten, wenn möglich, offen und geschlossen sichtbar sein.",
        "Überinterpretiere keine Kompressionsartefakte. Lagerbilder werden häufig verkleinert, nachgeschärft oder mit einem Telefon aufgenommen; eine unscharfe Linie beweist keine fehlerhafte Naht. Wenn die Stelle deine Entscheidung verändert, fordere ein nahes, gut beleuchtetes Foto mit genauer Orts- und Handlungsangabe an: innere linke Naht, geschlossener Reißverschluss oder Sohlenrand von der Seite. Präzise Anfragen erzeugen Belege. Die allgemeine Frage, ob „alles gut“ sei, erzeugt nur eine schwer überprüfbare Meinung."
      ]},
      { heading: "Maße sind stärker als Größenbuchstaben", paragraphs: [
        "Ein Größenetikett bestätigt nur den angebrachten Buchstaben oder die Zahl, nicht die tatsächliche Passform. Verkäufer, Schnittmuster und Kategorien verwenden unterschiedliche Standards. Vergleiche messbare Werte mit einem eigenen, ähnlich genutzten Artikel. Bei Oberteilen helfen Brustweite, Schulter, Rückenlänge und Ärmel. Hosen benötigen flache Bundweite, Leibhöhe, Innenbein und Öffnung. Taschen werden über Breite, Höhe, Tiefe und Griffabstand geprüft. Bei Schuhen ist die Innen- oder Einlegesohlenlänge wertvoller als eine isolierte Größenangabe.",
        "Ein gutes Messfoto zeigt das gesamte Band, den Nullpunkt und den Endpunkt auf einem möglichst flach liegenden Artikel. Eine Nahaufnahme nur einer Zahl kann falsch gelesen werden. Berücksichtige Dehnung, Materialdicke und unterschiedliche Messmethoden. Vergleiche mit der Größentabelle des Listings, wenn sie vorhanden ist, und erlaube eine vernünftige Toleranz. Wenn Passform entscheidend ist, liefert eine klare Messung mehr Nutzen als mehrere dekorative Detailbilder ohne Maßstab."
      ]},
      { heading: "Farbe und Etiketten vorsichtig behandeln", paragraphs: [
        "Lager-LEDs, automatischer Weißabgleich, Kontrast und Bildschirmdarstellung können Farben deutlich verschieben. Vergleiche mehrere Winkel und neutrale Referenzen wie weißes Papier, grauen Boden oder ein Maßband. Wenn Farbe kaufentscheidend ist, bitte um eine Aufnahme bei neutralerer Beleuchtung, akzeptiere aber verbleibende Bildschirmunterschiede. Ein Foto kann zuverlässiger zeigen, dass zwei Flächen voneinander abweichen, als beweisen, dass ein Produkt exakt einem kommerziellen Farbnamen entspricht.",
        "Etiketten helfen bei Größe, Farbcode, Produktkennung und Pflegehinweisen. Sie authentifizieren weder Herkunft noch Materialbehauptung. Prüfe, ob Auftrag, Anhänger und eingenähtes Label intern übereinstimmen, und lasse unbelegte Aussagen ausdrücklich offen. Wenn ein Listing das Material nur vage beschreibt, verwandle eine Nahaufnahme des Etiketts nicht in Gewissheit. Notiere, was sichtbar ist, und halte die Schlussfolgerung innerhalb der vorhandenen Beweise."
      ]},
      { heading: "Verpackung vor dem Versand prüfen", paragraphs: [
        "Verpackung beeinflusst sowohl Zustand als auch abrechenbares Volumen. Achte auf eingedrückte Kartons, scharfe ungeschützte Beschläge, Feuchtigkeitsspuren, ungeschützte Oberflächen und lose Teile. Entscheide, ob eine Verkaufsbox wirklich schützt oder nur Platz beansprucht. Entfernen kann Volumen senken, zugleich aber Schuhe, Hüte oder empfindliches Zubehör destabilisieren. Verstärkung, Kantenschutz oder Trennung sind sinnvoll, wenn sie ein sichtbares Risiko lösen; sie sollten nicht blind als Standard gewählt werden.",
        "Bestätige vor der internationalen Paketeinreichung nochmals Menge und Optionen anhand Auftrags-ID und erkennbarem Detail. Bei mehreren ähnlichen Farben oder Größen entstehen leicht Verwechslungen. Eine letzte Inventarnotiz benennt Quell-ID, ausgewählte Variante und ein unterscheidbares Merkmal. Sichtbare Probleme werden jetzt gemeldet, solange der Artikel im Lager erreichbar und die Entscheidung umkehrbar ist. Nach Übergabe an den internationalen Transport sind zusätzliche Bilder, Verkäuferretouren und andere Abhilfen oft schwieriger."
      ]},
      { heading: "Eine verhältnismäßige Entscheidung treffen", paragraphs: [
        "Teile Befunde in bestätigte Abweichung, sichtbare Unvollkommenheit und offene Frage. Eine falsche Größe oder ein anderes Produkt ist eine bestätigte Abweichung. Ein loser Faden oder kleiner Fleck ist sichtbar, aber seine Bedeutung hängt von Stelle und Erwartung ab. Ein Schatten oder unscharfer Rand ist eine offene Frage und braucht bessere Belege. Diese Einteilung verhindert, dass jede Kleinigkeit dieselbe Reaktion auslöst, und richtet Aufmerksamkeit auf Identität, Passform, Funktion und Transportsicherheit.",
        "Dokumentiere Foto, genaue Stelle und gewünschten nächsten Schritt. Akzeptiere, wenn die Belege deine Kriterien erfüllen; fordere ein gezieltes Bild an, wenn die Unsicherheit wesentlich ist; oder pausiere das Paket bei falscher Identität oder größerem sichtbarem Schaden. Kein Foto garantiert zukünftige Leistung. Ziel ist bescheidener und nützlicher: aus einer schnellen Sichtprüfung eine wiederholbare, evidenzbasierte Entscheidung zu machen, bevor der teure und weniger umkehrbare internationale Versand beginnt."
      ]}
    ]
  },
  "litbuy-shipping-weight-guide": {
    title: "LitBuy-Versandkosten: tatsächliches, volumetrisches und abrechenbares Gewicht",
    deck: "Verstehe Gewichtsarten, Verpackung, Erstgewicht, Rehearsal und routenspezifische Regeln, bevor ein Rechnerwert zum Paketbudget wird.",
    readTime: "14 Min. Lesezeit",
    sections: [
      { heading: "Drei Gewichte, eine Rechnung", paragraphs: [
        "Versandschätzungen werden unklar, wenn das Wort Gewicht mehrere Berechnungen meint. Das tatsächliche Gewicht ist der Wert des fertig gepackten Pakets auf einer Waage. Das Volumengewicht wandelt den beanspruchten Raum in eine gewichtsähnliche Zahl um, üblicherweise über Länge mal Breite mal Höhe geteilt durch einen routenspezifischen Divisor. Das Abrechnungsgewicht ist der Wert, den die Linie nach Vergleich, Regeln und Rundung tatsächlich für den Gewichtsanteil der Rechnung verwendet.",
        "Darum können zwei Pakete mit denselben Waren unterschiedliche Angebote erhalten. Ein dichtes, kompaktes Paket wird eher vom Waagengewicht bestimmt; ein leichter großer Karton vom Volumen. Derselbe Karton kann bei zwei Linien andere Volumenwerte erzeugen, weil Divisoren, Einheiten oder Messkonventionen abweichen. Übernimm niemals einen allgemeinen Divisor ungeprüft. Lies die aktuelle Regel der konkreten Route und kläre, ob Außenmaße vor oder nach endgültiger Verpackung verwendet werden."
      ]},
      { heading: "Ohne falsche Genauigkeit rechnen", paragraphs: [
        "Für eine einfache Schätzung verwendest du die äußeren Maße des gepackten Pakets in der geforderten Einheit. Multipliziere Länge, Breite und Höhe, teile durch den aktuellen Routendivisor und vergleiche das Ergebnis mit dem tatsächlichen Gewicht. Danach folgt die Rundungs- oder Abrechnungsstufe. Ein Wert von 2,01 Kilogramm kann je nach Dienst als 2,1, 2,5 oder 3 Kilogramm zählen. Viele Dezimalstellen machen einen Rechner nicht genau, wenn die Eingaben nur einen unverpackten Artikel beschreiben.",
        "Behandle frühe Produktgewichte als Planungssignal. Sie können Schutzmaterial, Außenkarton, Verkäuferverpackung und Konsolidierung ausschließen. Maße können Schätzwerte oder reine Produktmaße sein. Arbeite deshalb während des Einkaufs mit Bereichen: wahrscheinlich tatsächliches Gewicht und plausible Kartongröße. So erkennst du, ob der Inhalt eindeutig dicht, eindeutig sperrig oder nah genug an einer Schwelle liegt, dass eine Rehearsal-Messung die beste Route verändern könnte."
      ]},
      { heading: "Verpackung verändert beide Seiten", paragraphs: [
        "Das Entfernen einer Verkaufsbox kann das Volumengewicht senken, aber die leichteste Verpackung ist nicht automatisch die beste. Schuhe, Hüte, Glas, strukturierte Taschen und frei liegende Beschläge brauchen möglicherweise Unterstützung gegen Druck und Stöße. Weiche Kleidung lässt sich enger falten oder komprimieren, kann dabei jedoch knittern; außerdem reduziert Kompression die später gemessenen Außenmaße nicht immer so stark wie erwartet. Bewerte die Schutzfunktion jeder Schicht, bevor du ihre Entfernung verlangst.",
        "Konsolidierung bringt einen weiteren Zielkonflikt. Zusammenlegen kann doppelte Außenkartons und Grundgebühren sparen, aber ein ungünstig geformtes Gesamtpaket kann die längste Seite vergrößern oder eine Übergrößenregel auslösen. Prüfe, ob geteilte Pakete andere Routen, Versicherungslimits oder Mindestgebühren haben. Das Ziel ist weder grundsätzlich ein einzelner Karton noch der kleinstmögliche Karton, sondern eine Form, die den Inhalt schützt und innerhalb der Größen- und Abrechnungsregeln der gewählten Linie bleibt."
      ]},
      { heading: "Die Route statt der Schlagzeile lesen", paragraphs: [
        "Ein beworbener Kilopreis beschreibt selten das vollständige Angebot. Routen können Erstgewicht, Fortsetzungsstufen, Mindestabrechnung, maximale Länge, Umfangsgrenzen, eingeschränkte Warenkategorien und Zielzuschläge besitzen. Einige Dienste berechnen Volumen für jedes Paket, andere wenden Sonderregeln auf bestimmte Formen an. Laufzeiten sind häufig Bereiche und keine Zusage, besonders bei Zollkontrolle, Kapazitätsänderung, Feiertagen oder lokaler Zustellung.",
        "Vergleiche alle Routen mit denselben Paketannahmen. Notiere Ziel, tatsächliches Packgewicht, Außenmaße, Berechnung des Abrechnungsgewichts, enthaltene Leistungen und sichtbare Zuschläge. Wenn ein Angebot geschätzte Maße und ein anderes Rehearsal-Daten verwendet, ist der Vergleich nicht kontrolliert. Trenne zudem reine Transportkosten vom Gesamtauftrag: chinesischer Inlandversand, optionale Prüfung, Verpackung, Versicherung, Zahlungsumrechnung, Steuern und Zölle können außerhalb der Gewichtszeile liegen."
      ]},
      { heading: "Rehearsal zum richtigen Zeitpunkt nutzen", paragraphs: [
        "Eine Vorverpackungs- oder Rehearsal-Messung ist besonders wertvoll, wenn das Paket sperrig, nahe einer Routengrenze oder wahrscheinlich zwischen tatsächlicher und volumetrischer Abrechnung wechselt. Sie ersetzt Vermutungen über konsolidierte Maße durch ein gemessenes Paket und kann zeigen, ob das Entfernen einer großen Box oder die Trennung eines starren Artikels neue Routen eröffnet. Bei einem kleinen dichten Paket weit entfernt von Schwellen ist der Zusatznutzen geringer, obwohl gemessene Packdaten immer besser als Produktannahmen sind.",
        "Behandle Rehearsal nicht als Versprechen, dass jeder Carrier exakt gleich misst. Endgültige Handhabung, Rundung und Nachmessung können Abweichungen erzeugen. Halte einen Puffer, statt das gesamte Budget bis auf den letzten Cent einer Schätzung zu verplanen. Wenn die Messung deutlich höher ausfällt, ändere Verpackung, Aufteilung oder Route vor der Einreichung. Das ist die letzte praktische Phase, in der die Konfiguration ohne Rückruf eines bereits laufenden Pakets verändert werden kann."
      ]},
      { heading: "LitBuy-spezifische Regelprüfungen", paragraphs: [
        "Der LitBuy-Versandrechner erklärt, dass die Erstgewichtseinheit das Mindestgewicht ist, das eine Route berechnet. Ein leichteres Paket wird trotzdem als vollständige erste Einheit abgerechnet; weiteres Gewicht folgt den Fortsetzungsstufen der Linie. Deshalb verändert eine kleine Gewichtsreduzierung nicht automatisch den Preis, wenn das Paket im selben Abrechnungsband bleibt. Erfasse Erstgewicht, Fortsetzungseinheit, maximale Maße und Warenbeschränkungen, bevor du Schutz nur wegen weniger Gramm entfernst.",
        "Die veröffentlichte Versandrichtlinie nennt für die Lagerbearbeitung eines Pakets üblicherweise ein bis drei Werktage, ohne Wochenenden und Feiertage. Das ist die Zeit vor der Übergabe, keine internationale Lieferzusage. Carrier-Transit, Zoll, Wetter und Zielzustellung sind getrennte Phasen. Rückerstattungen hängen laut Richtlinie von bestätigtem Zustellfehler oder einem zurückgesandten und wieder empfangenen Paket ab; das Überschreiten einer unverbindlichen Schätzung allein ist keine automatische Erstattungszusage."
      ]},
      { heading: "Ein vollständiges Paketbudget bauen", paragraphs: [
        "Teile das Budget in Produktkosten, chinesische Inlandbewegung, optionale Leistungen, internationalen Transport, Risikopuffer und Zielgebühren. USD-Werte in einer Fundtabelle sind Richtumrechnungen; Wechselkurs und Zahlungsanbieter verändern den abgerechneten Betrag. Steuern und Zölle hängen von Land, Waren, Route und Erklärung ab und dürfen nicht als universeller Prozentsatz erfunden werden. Verwende die geltenden Behörden- oder Routeninformationen, wenn diese Gebühren für deine Entscheidung wesentlich sind.",
        "Kennzeichne jeden Wert als bekannt, angeboten oder angenommen: tatsächliches Packgewicht bekannt, Außenmaße geschätzt, Divisor aus aktueller Routenseite, Ferngebiet unbekannt. Ein sinnvoller Puffer deckt Messabweichung, Rundung und ausgewiesene Zuschläge, statt eine schwache Schätzung zu verstecken. Bestätige vor Einreichung Ziel, Inhalt, Einschränkungen, Maße, Abrechnungsgewicht, Schutzanweisungen und Erklärung. Entscheidend ist nicht das leichteste irgendwo angezeigte Gewicht, sondern das abrechenbare Paket unter der tatsächlich gewählten Route."
      ]}
    ]
  }
};
