const updates = [
 {
 slug:'usfans-spreadsheet-guide-2026',
 heading:{en:'Turn the shortlist into a size check',de:'Aus der Auswahl wird eine Größenprüfung',es:'Convierte la selección en una comprobación de talla',fr:'Passer de la sélection à la vérification des tailles',it:'Dalla selezione alla verifica della taglia'},
 body:{
 en:'Use separate comparison rows for shoes and hoodies. For shoes, record the exact colorway, selected label and the measurement method. For hoodies, add chest width, body length and whether the chart measures the garment or recommends a body size. Save the listing date beside the price. The new category guides below turn this record into a practical warehouse check. A catalog entry is a starting point; it does not establish current stock, product authenticity or the condition of the unit you will receive.',
 de:'Verwende getrennte Vergleichszeilen für Schuhe und Hoodies. Notiere bei Schuhen die genaue Farbvariante, die gewählte Größenangabe und die Messmethode. Ergänze bei Hoodies Brustweite, Rückenlänge und ob die Tabelle Kleidungsmaße oder empfohlene Körpermaße nennt. Halte neben dem Preis das Datum des Angebots fest. Die unten verlinkten Ratgeber übertragen diese Angaben auf die Lagerprüfung. Ein Katalogeintrag ist ein Ausgangspunkt; er belegt weder aktuellen Bestand noch Echtheit oder Zustand des gelieferten Artikels.',
 es:'Usa filas separadas para comparar calzado y sudaderas. En el calzado, registra el color exacto, la talla elegida y el método de medición. En las sudaderas, añade ancho de pecho, largo y si la tabla mide la prenda o recomienda medidas corporales. Guarda la fecha junto al precio. Las guías de categoría enlazadas convierten estos datos en una comprobación práctica en almacén. Una entrada del catálogo no acredita existencias actuales, autenticidad ni el estado de la unidad recibida.',
 fr:'Séparez les lignes de comparaison pour les chaussures et les sweats. Pour les chaussures, notez le coloris exact, la taille choisie et la méthode de mesure. Pour les sweats, ajoutez la largeur de poitrine, la longueur et précisez si le tableau mesure le vêtement ou conseille une morphologie. Notez la date avec le prix. Les guides ci-dessous transforment ces données en contrôle à l’entrepôt. Une référence de catalogue ne prouve ni le stock actuel, ni l’authenticité, ni l’état de l’article reçu.',
 it:'Usa righe separate per confrontare scarpe e felpe. Per le scarpe annota colore esatto, taglia scelta e metodo di misurazione. Per le felpe aggiungi larghezza del torace, lunghezza e se la tabella riporta misure del capo o misure corporee consigliate. Salva la data accanto al prezzo. Le guide di categoria collegate trasformano questi dati in un controllo pratico in magazzino. Una voce del catalogo non dimostra disponibilità attuale, autenticità o condizioni dell’unità ricevuta.'},
 links:['usfans-shoe-finds-sizing-qc','usfans-hoodie-finds-size-charts']
 },
 {
 slug:'usfans-shipping-cost-guide',
 heading:{en:'Separate the price estimate from the delivery clock',de:'Preisschätzung und Lieferdauer getrennt betrachten',es:'Separa el presupuesto del plazo de entrega',fr:'Distinguer estimation du prix et délai de livraison',it:'Separare preventivo e tempi di consegna'},
 body:{
 en:'A freight estimate answers a cost question, not a delivery-date question. Keep the selected route, packed weight and dimensions beside the quote, then record seller dispatch, warehouse arrival and carrier acceptance separately. If one item is still awaiting purchase or domestic delivery, the international transit estimate has not begun for that item. Use the stage guide to identify the unfinished step and the tracking guide to interpret the next observable event.',
 de:'Eine Frachtschätzung beantwortet eine Kostenfrage, keine Frage zum Liefertermin. Speichere Versandroute, Paketgewicht und Maße zusammen mit dem Angebot. Erfasse Verkäufer-Versand, Lagereingang und Übergabe an den Transportdienst getrennt. Wartet ein Artikel noch auf Kauf oder Inlandsversand, hat seine internationale Transportzeit noch nicht begonnen. Der Ablauf-Ratgeber hilft, den offenen Schritt zu erkennen; der Tracking-Ratgeber erklärt das nächste beobachtbare Ereignis.',
 es:'Un presupuesto de transporte responde a una pregunta de coste, no de fecha de entrega. Guarda ruta, peso y dimensiones del paquete junto al presupuesto; registra por separado salida del vendedor, llegada al almacén y aceptación del transportista. Si un artículo aún espera compra o transporte nacional, su tránsito internacional no ha comenzado. La guía de etapas ayuda a localizar el paso pendiente y la de seguimiento a interpretar el siguiente evento observable.',
 fr:'Un devis de transport renseigne sur le coût, pas sur la date de livraison. Conservez la ligne choisie, le poids et les dimensions du colis avec le devis, puis notez séparément l’expédition du vendeur, l’arrivée en entrepôt et la prise en charge du transporteur. Si un article attend encore son achat ou son transport intérieur, son trajet international n’a pas commencé. Le guide des étapes permet de repérer l’action inachevée et celui du suivi d’interpréter le prochain événement observable.',
 it:'Un preventivo di trasporto risponde a una domanda sui costi, non sulla data di consegna. Conserva tratta scelta, peso e dimensioni del pacco insieme al preventivo; registra separatamente spedizione del venditore, arrivo in magazzino e presa in carico del corriere. Se un articolo attende ancora acquisto o trasporto nazionale, il suo transito internazionale non è iniziato. La guida alle fasi identifica il passaggio incompleto; quella al tracking spiega il successivo evento osservabile.'},
 links:['usfans-shipping-time-stages','usfans-tracking-order-status']
 },
 {
 slug:'how-to-read-usfans-qc-photos',
 heading:{en:'Choose the category check that changes your decision',de:'Die entscheidende Kategorieprüfung wählen',es:'Elige la comprobación que cambia tu decisión',fr:'Choisir le contrôle adapté à votre décision',it:'Scegliere il controllo che cambia la decisione'},
 body:{
 en:'A shoe label, hoodie chest measurement and jersey customization need different evidence. Open the relevant category guide before requesting more images. For a printed jersey, compare every character and number with the saved order; a general front view may not show an incorrect accent or digit. If the unit differs from the ordered option, preserve the listing and order evidence before changing its status. The returns guide explains how to organize a request without assuming approval.',
 de:'Ein Schuhgrößenetikett, die Brustweite eines Hoodies und die Personalisierung eines Trikots benötigen unterschiedliche Belege. Öffne den passenden Ratgeber, bevor du weitere Fotos anforderst. Vergleiche bei einem bedruckten Trikot jedes Zeichen und jede Ziffer mit der Bestellung; eine Gesamtansicht zeigt falsche Akzente oder Ziffern möglicherweise nicht. Weicht der Artikel von der Bestellung ab, sichere Angebot und Bestellnachweis, bevor du seinen Status änderst. Der Rückgabe-Ratgeber erklärt die Dokumentation einer Anfrage, ohne eine Genehmigung vorauszusetzen.',
 es:'La etiqueta de un zapato, el ancho de una sudadera y la personalización de una camiseta requieren pruebas distintas. Consulta la guía de categoría antes de pedir más fotos. En una camiseta impresa, compara cada carácter y número con el pedido guardado; una vista general puede ocultar un acento o dígito incorrecto. Si la unidad difiere de lo pedido, conserva la ficha y el comprobante antes de cambiar su estado. La guía de devoluciones explica cómo documentar la solicitud sin dar por hecha su aprobación.',
 fr:'Une étiquette de chaussure, la largeur d’un sweat et la personnalisation d’un maillot nécessitent des preuves différentes. Consultez le guide adapté avant de demander des photos supplémentaires. Pour un maillot imprimé, comparez chaque caractère et numéro avec la commande sauvegardée : une vue générale peut masquer un accent ou chiffre incorrect. Si l’article diffère de la commande, conservez la fiche et le justificatif avant de modifier son statut. Le guide des retours explique comment documenter une demande sans présumer son acceptation.',
 it:'L’etichetta di una scarpa, la larghezza di una felpa e la personalizzazione di una maglia richiedono prove diverse. Consulta la guida di categoria prima di chiedere altre foto. Su una maglia stampata confronta ogni carattere e numero con l’ordine salvato: una vista generale potrebbe nascondere un accento o una cifra errati. Se l’unità differisce dall’ordine, conserva inserzione e conferma prima di cambiarne lo stato. La guida ai resi spiega come documentare la richiesta senza presumere che venga accettata.'},
 links:['usfans-football-jersey-finds-sizing','usfans-returns-refunds-evidence']
 },
 {
 slug:'usfans-review-what-to-check',
 heading:{en:'Evaluate the service at the stage you can observe',de:'Den Service anhand beobachtbarer Schritte bewerten',es:'Evalúa el servicio en la etapa observable',fr:'Évaluer le service à une étape observable',it:'Valutare il servizio nella fase osservabile'},
 body:{
 en:'Keep product quality, agent handling and carrier performance separate in your assessment. A seller delay does not establish a customs delay; a clear QC image does not prove durability. Record what happened, which party controlled that step and what evidence supports the conclusion. If a decision depends on recovering funds or meeting a deadline, read the current route or return conditions before payment. These guides do not document a first-hand purchase or promise an outcome.',
 de:'Trenne Produktqualität, Abwicklung durch den Vermittler und Transportleistung. Eine Verzögerung beim Verkäufer belegt keine Zollverzögerung; ein klares QC-Foto beweist keine Haltbarkeit. Notiere Ereignis, zuständige Partei und den Beleg für deine Schlussfolgerung. Hängt deine Entscheidung von einer Erstattung oder einem Termin ab, lies vor der Zahlung die aktuellen Versand- oder Rückgabebedingungen. Diese Ratgeber dokumentieren keinen eigenen Kauf und versprechen kein Ergebnis.',
 es:'Separa calidad del producto, gestión del agente y rendimiento del transportista. Un retraso del vendedor no demuestra un retraso aduanero; una foto QC clara no prueba durabilidad. Registra lo ocurrido, quién controlaba esa etapa y qué pruebas sostienen la conclusión. Si la decisión depende de recuperar dinero o cumplir una fecha, lee las condiciones actuales de la ruta o devolución antes de pagar. Estas guías no documentan una compra propia ni prometen un resultado.',
 fr:'Distinguez qualité du produit, traitement par l’intermédiaire et prestation du transporteur. Un retard du vendeur ne prouve pas un retard douanier ; une photo QC nette ne démontre pas la durabilité. Notez l’événement, la partie responsable de cette étape et les preuves étayant votre conclusion. Si votre décision dépend d’un remboursement ou d’une échéance, lisez les conditions actuelles avant de payer. Ces guides ne relatent pas un achat personnel et ne promettent aucun résultat.',
 it:'Distingui qualità del prodotto, gestione dell’agente e prestazioni del corriere. Un ritardo del venditore non dimostra un ritardo doganale; una foto QC nitida non prova la durata del prodotto. Registra evento, responsabile della fase e prove a sostegno della conclusione. Se la decisione dipende dal recupero del denaro o da una scadenza, leggi le condizioni attuali della tratta o del reso prima di pagare. Queste guide non documentano un acquisto personale e non promettono risultati.'},
 links:['usfans-shipping-time-stages','usfans-returns-refunds-evidence']
 },
 {
 slug:'usfans-warehouse-evidence-gap-map',
 heading:{en:'Connect a missing view to a specific action',de:'Eine fehlende Ansicht mit einer konkreten Handlung verbinden',es:'Relaciona la vista que falta con una acción',fr:'Associer la vue manquante à une action précise',it:'Collegare la vista mancante a un’azione concreta'},
 body:{
 en:'For each gap, write the question, the requested view and the decision it could change. For example: “Does the received jersey match the ordered number? Please show the complete back print straight on.” Keep a separate row for a shipping or refund question: another photo will not establish a carrier handover or confirm a refund. The category and returns guides below help distinguish a visible mismatch from a process question.',
 de:'Notiere für jede Lücke die Frage, die gewünschte Ansicht und die Entscheidung, die sie ändern könnte. Beispiel: „Entspricht die Nummer auf dem Trikot der Bestellung? Bitte den gesamten Rückenaufdruck gerade fotografieren.“ Erfasse Versand- oder Erstattungsfragen getrennt: Ein weiteres Foto belegt keine Übergabe an den Transportdienst und bestätigt keine Erstattung. Die folgenden Kategorie- und Rückgabe-Ratgeber unterscheiden sichtbare Abweichungen von Verfahrensfragen.',
 es:'Para cada laguna, escribe la pregunta, la vista solicitada y la decisión que podría cambiar. Por ejemplo: «¿Coincide el número de la camiseta con el pedido? Muestra de frente todo el estampado trasero». Separa las dudas sobre envío o reembolso: otra foto no acredita la entrega al transportista ni confirma un reembolso. Las guías siguientes distinguen una discrepancia visible de una cuestión de procedimiento.',
 fr:'Pour chaque lacune, notez la question, la vue demandée et la décision qu’elle pourrait modifier. Exemple : « Le numéro du maillot correspond-il à la commande ? Merci de montrer l’intégralité de l’impression dorsale de face. » Séparez les questions de livraison ou de remboursement : une autre photo ne prouve ni remise au transporteur ni remboursement. Les guides ci-dessous distinguent une différence visible d’une question de procédure.',
 it:'Per ogni lacuna annota domanda, vista richiesta e decisione che potrebbe cambiare. Per esempio: «Il numero sulla maglia corrisponde all’ordine? Mostra tutta la stampa posteriore frontalmente». Separa le domande su spedizione o rimborso: un’altra foto non dimostra la consegna al corriere né conferma un rimborso. Le guide seguenti distinguono una difformità visibile da una questione di procedura.'},
 links:['usfans-football-jersey-finds-sizing','usfans-returns-refunds-evidence']
 },
 {
 slug:'usfans-warehouse-photo-angle-map',
 heading:{en:'Match shoe angles before judging asymmetry',de:'Schuhansichten vor dem Symmetrievergleich angleichen',es:'Iguala los ángulos antes de juzgar la simetría',fr:'Comparer des angles équivalents avant de juger la symétrie',it:'Confrontare angoli equivalenti prima di valutare la simmetria'},
 body:{
 en:'A left shoe photographed from above and a right shoe tilted toward the camera are not a fair shape comparison. Request the pair together on the same surface, then compare equivalent heel, side and toe views. Mark the precise area of concern rather than sending an unannotated screenshot. The shoe guide connects those views with size-label checks and cost planning, while keeping authenticity and comfort outside what a photograph can prove.',
 de:'Ein linker Schuh von oben und ein zur Kamera geneigter rechter Schuh erlauben keinen fairen Formvergleich. Bitte um ein Foto beider Schuhe auf derselben Fläche und vergleiche entsprechende Fersen-, Seiten- und Vorderansichten. Markiere die betroffene Stelle, statt einen unkommentierten Screenshot zu senden. Der Schuh-Ratgeber verbindet diese Ansichten mit Größenetiketten und Kostenplanung. Echtheit und Tragekomfort bleiben außerhalb dessen, was ein Foto beweisen kann.',
 es:'Un zapato izquierdo visto desde arriba y uno derecho inclinado hacia la cámara no permiten comparar bien la forma. Pide ver el par sobre la misma superficie y compara vistas equivalentes de talón, lateral y puntera. Marca la zona concreta en vez de enviar una captura sin anotaciones. La guía de calzado relaciona estas vistas con etiquetas de talla y costes, sin presentar autenticidad o comodidad como hechos demostrables mediante una foto.',
 fr:'Une chaussure gauche vue du dessus et une droite inclinée vers l’appareil ne permettent pas une comparaison fiable. Demandez une photo de la paire sur la même surface, puis comparez des vues équivalentes des talons, côtés et pointes. Marquez la zone concernée plutôt que d’envoyer une capture sans annotation. Le guide chaussures relie ces vues aux étiquettes de taille et aux coûts, sans présenter authenticité ou confort comme prouvés par une photo.',
 it:'Una scarpa sinistra fotografata dall’alto e una destra inclinata verso la fotocamera non consentono un confronto corretto della forma. Chiedi una foto della coppia sulla stessa superficie, poi confronta viste equivalenti di tallone, lato e punta. Segna la zona precisa invece di inviare uno screenshot senza annotazioni. La guida alle scarpe collega queste viste a etichette e costi, senza trattare autenticità o comodità come dimostrabili da una fotografia.'},
 links:['usfans-shoe-finds-sizing-qc','usfans-warehouse-measurement-photo-evidence']
 },
 {
 slug:'usfans-warehouse-size-tag-evidence',
 heading:{en:'Keep the label and garment dimensions in separate fields',de:'Etikett und Kleidungsmaße getrennt festhalten',es:'Registra por separado etiqueta y medidas de la prenda',fr:'Séparer taille d’étiquette et dimensions du vêtement',it:'Tenere separati etichetta e misure del capo'},
 body:{
 en:'Record “label received” separately from chest width, body length and sleeve measurement. This distinguishes an incorrect dispatched size from a correctly labelled garment whose cut does not suit you. In the hoodie guide, compare the seller chart with a garment you own using the same endpoints. For jerseys, also record fan or player version and customization; a matching size letter does not make different cuts interchangeable.',
 de:'Notiere „erhaltene Etikettengröße“ getrennt von Brustweite, Länge und Ärmelmaß. So unterscheidest du eine falsch versandte Größe von einem korrekt beschrifteten Kleidungsstück, dessen Schnitt nicht passt. Vergleiche im Hoodie-Ratgeber die Verkäufertabelle mit einem eigenen Kleidungsstück an denselben Messpunkten. Halte bei Trikots zusätzlich Fan- oder Spielerversion und Personalisierung fest; derselbe Größenbuchstabe macht unterschiedliche Schnitte nicht austauschbar.',
 es:'Registra «talla recibida en la etiqueta» por separado del ancho de pecho, largo y manga. Así distingues una talla enviada incorrectamente de una prenda bien etiquetada cuyo corte no te sirve. La guía de sudaderas compara la tabla del vendedor con una prenda propia usando los mismos puntos. En camisetas de fútbol, anota también versión de aficionado o jugador y personalización; una misma letra de talla no hace equivalentes cortes distintos.',
 fr:'Notez séparément la taille reçue sur l’étiquette, la largeur de poitrine, la longueur et la mesure de manche. Cela distingue une mauvaise taille expédiée d’un vêtement correctement étiqueté dont la coupe ne vous convient pas. Le guide sweats compare le tableau du vendeur à un vêtement personnel avec les mêmes points de mesure. Pour les maillots, notez aussi version supporter ou joueur et personnalisation : une même lettre ne rend pas les coupes interchangeables.',
 it:'Registra la taglia ricevuta sull’etichetta separatamente da larghezza del torace, lunghezza e manica. Distinguerai una taglia spedita errata da un capo correttamente etichettato ma con taglio inadatto. La guida alle felpe confronta la tabella del venditore con un capo posseduto usando gli stessi punti. Per le maglie annota anche versione tifoso o giocatore e personalizzazione: la stessa lettera non rende equivalenti tagli diversi.'},
 links:['usfans-hoodie-finds-size-charts','usfans-football-jersey-finds-sizing']
 },
 {
 slug:'usfans-warehouse-measurement-photo-evidence',
 heading:{en:'Resolve a measurement mismatch before requesting a remedy',de:'Messabweichungen vor einer Reklamation klären',es:'Aclara una discrepancia de medidas antes de reclamar',fr:'Clarifier une différence de mesure avant une réclamation',it:'Chiarire una differenza di misure prima di reclamare'},
 body:{
 en:'Save the seller chart with its measurement convention and place the warehouse image beside it. Check endpoints, units and whether the fabric was stretched. If those conditions differ, request a comparable measurement before calling the item defective. If a comparable view still shows the concern, preserve the original image and explain the difference precisely. The returns guide shows how to assemble that evidence without assuming that a photo automatically creates a right to return.',
 de:'Speichere die Verkäufertabelle samt Messmethode und lege das Lagerfoto daneben. Prüfe Messpunkte, Einheiten und ob der Stoff gedehnt wurde. Weichen diese Bedingungen ab, bitte um eine vergleichbare Messung, bevor du einen Mangel annimmst. Bleibt die Auffälligkeit bei gleicher Methode bestehen, sichere das Originalfoto und beschreibe die Abweichung genau. Der Rückgabe-Ratgeber zeigt, wie du die Belege zusammenstellst, ohne aus einem Foto automatisch einen Rückgabeanspruch abzuleiten.',
 es:'Guarda la tabla del vendedor con su método de medición y compárala con la imagen del almacén. Comprueba extremos, unidades y si el tejido estaba estirado. Si las condiciones difieren, pide una medida comparable antes de considerar defectuosa la prenda. Si la diferencia persiste, conserva la imagen original y descríbela con precisión. La guía de devoluciones explica cómo reunir las pruebas sin asumir que una foto concede automáticamente derecho a devolver.',
 fr:'Conservez le tableau du vendeur avec sa méthode de mesure et placez la photo d’entrepôt à côté. Vérifiez points de départ et d’arrivée, unités et éventuel étirement du tissu. Si les conditions diffèrent, demandez une mesure comparable avant de conclure à un défaut. Si l’écart persiste, conservez la photo originale et décrivez-le précisément. Le guide des retours explique comment réunir ces preuves sans supposer qu’une photo donne automatiquement droit au retour.',
 it:'Salva la tabella del venditore con il metodo di misurazione e affianca la foto del magazzino. Controlla estremi, unità e se il tessuto è stato teso. Se le condizioni differiscono, chiedi una misura confrontabile prima di considerare difettoso il capo. Se la differenza persiste, conserva l’immagine originale e descrivila con precisione. La guida ai resi spiega come raccogliere le prove senza presumere che una foto dia automaticamente diritto al reso.'},
 links:['usfans-hoodie-finds-size-charts','usfans-returns-refunds-evidence']
 }
];
export function improveArticle(article,language,blueprints){
 const update=updates.find(x=>x.slug===article.slug);
 if(!update)return article;
 const related=[...(article.related||[])];
 for(const slug of update.links){
  const path=`/articles/${slug}`;
  if(!related.some(x=>x[1]===path))related.push([blueprints.find(x=>x.slug===slug).title[language],path]);
 }
 return {...article,datePublished:article.datePublished||'2026-09-01',dateModified:'2026-10-02',sections:[...article.sections,[update.heading[language],update.body[language]]],related};
}
