import type { Article } from "./article-data";

type ArticleKey = "qcArticle" | "shippingArticle" | "storageArticle";

export const deArticleSections: Record<ArticleKey, Article["sections"]> = {
  qcArticle: [
    ["Was ein Kakobuy-Spreadsheet tatsächlich leisten sollte", [
      "Viele Menschen suchen nach einem „Kakobuy Spreadsheet“ und erwarten eine möglichst große Produktliste. Größe allein ist jedoch kein Qualitätsmerkmal. Eine brauchbare Tabelle verbindet eine klare Produktbeschreibung mit einem erreichbaren Ziel, hält den sichtbaren Preis sowie den Variantenkontext fest und ermöglicht es, später zur ursprünglichen Grundlage zurückzukehren. Sie darf nicht behaupten, ein Angebot sei sicher, authentisch oder hochwertig, nur weil jemand es in eine Tabelle aufgenommen hat. Das Spreadsheet dient der Suche und Dokumentation; die Kaufentscheidung bleibt beim Käufer.",
      "Unsere Aufnahmeregel ist deshalb einfach: Kartenbild, Produktname und Zielseite müssen beim Prüfen denselben Artikel beschreiben. Eine Route wird entfernt oder erneut kontrolliert, wenn sich das Ziel verändert, verschwindet oder ein anderes Produkt zeigt. Preise sind Momentaufnahmen und keine Versprechen, weil Verkäufer Angebote bearbeiten und Wechselkurse schwanken können. Diese engere Methode liefert vielleicht weniger Funde als eine ungefilterte Social-Media-Liste, gibt aber jedem Ergebnis eine nachvollziehbare Funktion im Kaufprozess.",
    ]],
    ["Den offiziellen Kakobuy-Ablauf in Entscheidungen zerlegen", [
      "Kakobuys öffentliches Einsteigermaterial beschreibt den üblichen Agentenablauf: ein Produkt auf einem chinesischen Marktplatz auswählen, den Link kopieren, bei Kakobuy einfügen, die gewünschten Optionen bestimmen, den Artikel bezahlen, Lagereingang und Qualitätsprüfung abwarten und anschließend ein internationales Paket einreichen. Diese Reihenfolge ist wichtig, weil Artikelzahlung und internationaler Versand in verschiedenen Phasen bezahlt werden. Wer alles als einen einzigen Checkout betrachtet, kann Kosten und Verzögerungen schlechter zuordnen.",
      "Ein sorgfältiger Käufer hält an vier Punkten an. Tor eins ist das Quellangebot: Sind Artikel, Verkäufer und Option verständlich? Tor zwei ist der Bestelldatensatz: Stimmen Größe, Farbe, Menge und ausgewählte Variante? Tor drei sind die Lagerbelege: Passt der fotografierte Artikel sichtbar zu diesem Datensatz? Tor vier ist das Paket: Sind Verpackung, Route, Deklaration und endgültige Schätzung akzeptabel? Das Spreadsheet ist besonders wertvoll, wenn es korrekte Informationen von einem Tor zum nächsten trägt.",
    ]],
    ["Den Bestelldatensatz vor der Zahlung anlegen", [
      "Speichern Sie die genaue Quell-URL, den Angebotstitel, die gewählte Variante, die Menge, den vom Verkäufer angezeigten Preis sowie jede Größentabelle oder Optionsabbildung, die Ihre Wahl beeinflusst hat. Ergänzen Sie ein Datum, weil Live-Angebote verändert werden. Wenn eine Farbe nur durch eine Nummer oder ein kleines Vorschaubild gekennzeichnet ist, halten Sie auch dieses Detail fest. Beim Eintreffen der Lagerfotos ist Erinnerung ein schlechter Maßstab; ein kompakter Datensatz erlaubt den Vergleich mit der wirklich bestellten Auswahl.",
      "Achten Sie besonders auf übersetzte Optionen. Maschinenübersetzungen können Materialnamen, Sets und Farbbezeichnungen mehrdeutig machen. Raten Sie nicht, wenn zwei Varianten ähnlich wirken. Öffnen Sie die Quelle, vergleichen Sie die Optionsbilder und verwenden Sie eine Bestellnotiz nur dann, wenn sie eine echte Unklarheit löst. Lange oder widersprüchliche Notizen können neue Fehler erzeugen. Fehlt ein notwendiges Maß beim Verkäufer, bleibt das ein Unsicherheitsfaktor und darf nicht als exakte Passformprognose ausgegeben werden.",
    ]],
    ["Den Preis als Kostenstapel lesen", [
      "Der Produktpreis ist nur die erste Ebene. Bei einem Agentenkauf können außerdem die inländische Lieferung vom Verkäufer zum Lager, Gebühren des Zahlungskanals, optionale Zusatzleistungen und später der internationale Versand anfallen. Kakobuys Seite Services & Fees sagt derzeit, dass der grundlegende Einkaufsagentenservice außer Artikelkosten und Versand keine Handling-Gebühr erhebt, während optionale Leistungen zusätzlich kosten können. Die Zahlungshilfe nennt aktuell für PayPal 3,5 Prozent plus 0,30 US-Dollar. Das sind aktuelle Plattformbedingungen, keine dauerhaften Konstanten.",
      "Diese Trennung ist für öffentliche Ratgebertexte wichtig, weil die Wiederholung eines attraktiven Produktpreises ohne den restlichen Kostenstapel den Leser täuscht. Unsere USD-Angaben sind ungefähre Umrechnungen sichtbarer CNY-Preise und schließen Services sowie Transport aus. Prüfen Sie vor der Zahlung den Live-Checkout und die gewählte Zahlungsmethode. Prüfen Sie vor der Paketeinreichung die aktuelle Schätzung erneut. Wenn ein aktueller Kakobuy-Hinweis und ein alter Leitfaden voneinander abweichen, hat die Live-Seite Vorrang.",
    ]],
    ["Was Kakobuy beim Lagereingang nach eigener Aussage prüft", [
      "Kakobuy erklärt auf seiner öffentlichen Startseite, dass nach dem Eintreffen im Lager eine Qualitätsprüfung sichtbare Punkte wie Mängel, Größe und Farbe abdeckt. Das ist nützlich, bedeutet aber nicht, dass jedes Material, jedes Maß oder verborgene Konstruktionsdetail verifiziert wird. Lagerfotos sind Belege für das, was die Kamera zeigen kann. Sie beweisen weder langfristige Haltbarkeit, Komfort, Zusammensetzung noch Echtheit und zeigen keinen Fehler, der in Sohle, Futter oder Elektronik verborgen ist.",
      "Die Plattformmitteilung vom 10. Mai 2026 zu Problemen bei der Anzeige bestimmter QC-Bilder erinnert daran, den physischen Artikel von der Benutzeroberfläche zu trennen. Laut Mitteilung beeinflusste das Anzeigeproblem weder die Lagerung noch die normale Paketeinreichung. Wenn ein Bild fehlt oder nicht lädt, sollte das Fehlen daher weder als Annahme noch als Ablehnung gewertet werden. Prüfen Sie die Seite erneut, kontaktieren Sie bei Bedarf den Support und warten Sie auf entscheidungsrelevante Belege.",
    ]],
    ["Eine QC-Prüfung in drei Ebenen verwenden", [
      "Ebene eins ist die Identität. Bestätigen Sie Menge, bestellte Farbe, Größenschild, Variante, sichtbares Zubehör und die Grundform. Wenn eine falsche Option erscheint, stoppen Sie und dokumentieren Sie sie. Ebene zwei ist die Verarbeitung. Bei Schuhen: Zehenprofil, Absatzhöhe, Paneele, Sohle, Nähte und starken Kleber vergleichen. Bei Kleidung: Vorder- und Rückseite, Kragen, Ärmel, Druck oder Stickerei, Nähte, Flecken und Löcher prüfen. Bei Taschen und Accessoires: Maße, Metallfarbe, Verschlüsse, Ecken und Kantenfinish kontrollieren.",
      "Ebene drei sind entscheidungsspezifische Belege. Fragen Sie, was Ihre Antwort von akzeptieren zu zurückgeben ändern könnte. Hängt die Passform von der Brustweite ab, ist ein Linealfoto nützlicher als ein weiteres Schönheitsbild. Geht es um den Verschluss einer Tasche, fordern Sie diesen Winkel statt eines beliebigen Nahfotos an. Perspektive kann Proportionen verzerren, daher mehrere Ansichten vergleichen. Beschreiben Sie Probleme nach Ort und sichtbarem Merkmal, etwa „rechter Absatz, Außenkante, getrennte Naht“, statt nur „schlechte Qualität“ zu schreiben.",
    ]],
    ["Lagerzeit nicht mit Rückgabezeit verwechseln", [
      "Kakobuys öffentliche Informationen bewerben derzeit 100 Tage kostenlose Lagerung. Das gibt Zeit, auf weitere Artikel zu warten und ein konsolidiertes Paket zu planen, ist aber kein 100-tägiges Rückgabefenster des Verkäufers. Rückgabe und Austausch richten sich nach dem jeweiligen Verkäufer, dem Bestellstatus, dem Artikelzustand und dem Plattformablauf. Kakobuy veröffentlicht außerdem eine „5-Day Return/Exchange Guarantee“, die als vom Verkäufer angebotene After-Sales-Leistung für unterstützte Drittanbieterprodukte beschrieben wird. Sie gilt nicht automatisch für jedes Produkt.",
      "Prüfen Sie den Artikel sofort nach dem Lagereingang. Ist eine Abweichung sichtbar, sichern Sie das betreffende Bild, nennen Sie die ausgewählte Option und erklären Sie den Unterschied, solange die Bestellung leicht nachverfolgbar ist. Vermeiden Sie irreversible Änderungen, bevor Sie den Artikel akzeptieren. Verkäuferablehnung, inländischer Rückversand und die erneute Reise eines Austauschprodukts können das Ergebnis beeinflussen. Kakobuys Hilfe weist darauf hin, dass ein Austausch je nach Verkäufer ungefähr 7 bis 20 Tage bis zur erneuten Einlagerung benötigen kann.",
    ]],
    ["Eine praktische Entscheidungsregel für jeden Spreadsheet-Fund", [
      "Akzeptieren Sie, wenn der fotografierte Artikel zur dokumentierten Variante passt, kein entscheidender sichtbarer Mangel vorliegt und die verbleibende Unsicherheit zum Preis vertretbar ist. Fordern Sie Belege an, wenn ein fehlender Winkel oder ein Maß die Entscheidung tatsächlich verändern kann. Öffnen Sie After-Sales, wenn eine klare, belegbare Abweichung oder ein sichtbarer Mangel vorliegt und die Bestellung noch berechtigt ist. Ein Artikel sollte nicht wegen eines unvorteilhaften Kamerawinkels abgelehnt werden; die Identität ungeprüft zu akzeptieren macht die QC hingegen wertlos.",
      "Nach der Annahme ergänzen Sie Ankunftsdatum, geschätztes Gewicht, Verpackungsbedarf und Ihre Paketfrist im Spreadsheet. Prüfen Sie die Zielroute erneut, bevor Sie den Fund weitergeben. So wird die Tabelle von einer statischen Liste zu einem kleinen Prüfprotokoll. Das unterstützt auch bessere Google-Inhalte: Jede Empfehlung kann mit Methode, Einschränkungen und aktuellen Quellenkontrollen erklärt werden, statt mit leeren Aussagen wie „bester Verkäufer“, „1:1 Qualität“ oder „garantiert sicher“ zu werben.",
    ]],
  ],
  shippingArticle: [
    ["Warum der Estimator ein Planungswerkzeug und kein Endpreis ist", [
      "Kakobuy stellt eine Seite zur Schätzung der Versandkosten bereit. Dort sollten aktuell verfügbare Routen verglichen werden, bevor ein endgültiges Paket existiert. Eine Schätzung basiert dennoch auf Eingaben und Linienregeln statt auf dem fertig gepackten Karton. Verkäuferverpackung, Umpacken im Lager, Artikelkategorie und Abrechnungsverfahren des Transporteurs können das Ergebnis verändern. Nutzen Sie den Estimator für Szenarien und einen Budgetbereich; kopieren Sie keine einzelne Zahl in einen Artikel und nennen Sie sie den dauerhaften Preis für ein Land.",
      "Ein sinnvoller Vergleich beginnt mit Zielland, realistischem Packgewicht und ungefähren Abmessungen. Notieren Sie außerdem Verfügbarkeit, Einschränkungen, Tracking, Entschädigungsregeln und angezeigte Währung. Wiederholen Sie die Prüfung direkt vor der Paketeinreichung, weil Liniennamen, Rabatte und Betriebshinweise wechseln können. Kakobuys eigene Historie aus Routen- und Trackingmeldungen zeigt, warum dauerhafte Artikel die Entscheidungsweise erklären und den Leser für die endgültige Auswahl zu den Live-Informationen zurückführen sollten.",
    ]],
    ["Istgewicht und Volumengewicht verstehen", [
      "Istgewicht ist der Wert auf der Waage nach dem Packen. Volumengewicht wandelt den beanspruchten Raum in einen Abrechnungswert um, häufig als Länge mal Breite mal Höhe geteilt durch einen linienspezifischen Divisor. Manche Linien berechnen den höheren Wert aus Ist- und Volumengewicht, andere verwenden Schwellen, Rundungsschritte oder Kategorien. Der genaue Divisor muss aus den aktuellen Routendetails stammen und nicht aus einem alten Screenshot in sozialen Medien.",
      "Dichte Produkte wie gefaltete Kleidung liegen oft näher am Istgewicht. Große Schuhe, starre Geschenkboxen, gepolsterte Jacken und Hohlraumfüllung können viel mehr Platz als Masse erzeugen. Deshalb können zwei Pakete mit gleichem Waagengewicht unterschiedliche Schätzungen erhalten. Erfassen Sie beim Vergleich sowohl Gewicht als auch Maße. Zeigt die Oberfläche nur eine frühe Schätzung, lassen Sie einen Puffer für die endgültige Lagermessung und die Abrechnungsstufen des Transporteurs.",
    ]],
    ["Den vollständigen Kostenstapel vor dem Versand abbilden", [
      "Die internationale Gebühr kommt zu früheren Kosten hinzu: Produktpreis, mögliche Inlandslieferung des Verkäufers, Gebühren des Zahlungskanals und optionale Lagerleistungen. Kakobuys Seite Services & Fees sagt derzeit, dass der grundlegende Einkaufsagentenservice außer Artikel und Versand keine Handling-Gebühr verlangt; Zusatzdienste können gewählt werden. Dieselbe offizielle Rubrik nennt eine Gebühr für die Paketdeklaration von gewöhnlich 8 RMB, abhängig von der Versandmethode. Diese Aussagen sollten bei der Einreichung live überprüft werden.",
      "Fassen Sie unterschiedliche Zahlen nicht zu einer erfundenen „Gesamtgebühr in Prozent“ zusammen. Eine Zahlungsgebühr ist nicht dasselbe wie ein Wechselkursaufschlag; Inlandslieferung ist keine internationale Fracht; optionale Verstärkung ist keine Agenten-Handling-Gebühr; und Einfuhrabgaben im Zielland sind nicht automatisch in der Versandschätzung enthalten. Ein transparentes Budget trennt jede Ebene und markiert unbekannte Werte. So lassen sich Routen vergleichen, ohne dass ein attraktiver Ausgangspreis die tatsächlichen Gesamtkosten verdeckt.",
    ]],
    ["Verpackung als Kosten- und Schutzentscheidung behandeln", [
      "Das Entfernen eines Schuhkartons kann die Maße reduzieren, nimmt dem Artikel aber Struktur und möglicherweise Präsentations- oder Wiederverkaufswert. Vakuumverpackung kann weiche Kleidung komprimieren, ist jedoch ungeeignet für Produkte, die stark knittern oder ihre Form behalten müssen. Verstärkung erhöht Gewicht und manchmal Volumen, kann bei zerbrechlichem Inhalt oder vielen Transportübergaben dennoch sinnvoll sein. Es gibt keine universelle Regel „alle Verpackungen entfernen“; die richtige Wahl hängt vom Produkt und den Folgen eines Schadens ab.",
      "Teilen Sie Verpackung in drei Gruppen. Notwendige Verpackung schützt Form, Glas, Beschläge oder feuchtigkeitsempfindliches Material. Nützliche Verpackung hält Kleinteile zusammen oder identifiziert die Variante. Dekorative Verpackung verbessert die Präsentation, bietet aber wenig Transportschutz. Wenn Volumen das Problem ist, entfernen Sie zuerst die dritte Gruppe. Prüfen Sie bei einem Zusatzservice den aktuellen Preis und formulieren Sie das Ziel präzise. „Retail-Schuhkartons entfernen, innere Schuhstützen behalten“ ist umsetzbarer als „billig, aber sicher verpacken“.",
    ]],
    ["Während der Lagerzeit bewusst konsolidieren", [
      "Kakobuys offizielle Informationen bewerben 100 Tage kostenlose Lagerung und verbinden diese ausdrücklich damit, mehrere Artikel zu kaufen und gemeinsam zu versenden. Konsolidierung kann wiederholte Außenverpackungen und mehrere kleine internationale Pakete vermeiden. Sie schafft außerdem Zeit, auf kompatible Artikel zu warten. Größer bedeutet jedoch nicht automatisch günstiger: Ein übergroßer Karton kann Volumenabrechnung auslösen, ein Linienlimit überschreiten oder eingeschränkte und gewöhnliche Produkte so mischen, dass weniger Routen verfügbar sind.",
      "Gruppieren Sie Produkte nach Ziel, Dringlichkeit, Zerbrechlichkeit und Linienkompatibilität. Eine langsame, preiswerte Kleidungsbestellung gehört nicht zwangsläufig zu einem dringenden oder empfindlichen Artikel. Vergleichen Sie möglichst zwei Paketszenarien: eine konsolidierte Box und eine sinnvolle Aufteilung. Berücksichtigen Sie in beiden Fällen die Verpackungswünsche. Das Ziel ist nicht die kleinste Anzahl an Paketen, sondern die niedrigsten akzeptablen Gesamtkosten für Schutz, Geschwindigkeit und Risiko, die Sie wirklich benötigen.",
    ]],
    ["Linienberechtigung ändert sich nach Produkt und Ziel", [
      "Batterien, Flüssigkeiten, Magnete, Markenware, lebensmittelähnliche Produkte und weitere sensible Kategorien können die angezeigten Linien reduzieren oder besondere Behandlung erfordern. Auch Zielland und laufender Transportbetrieb beeinflussen die Auswahl. Versprechen Sie niemals, dass eine Route einen bestimmten Artikel akzeptiert, nur weil eine frühere Sendung funktioniert hat. Nutzen Sie die aktuelle Schätzseite und nach der Lagerklassifizierung die Paketoberfläche. Wirkt die Klassifizierung falsch, fragen Sie vor der Zahlung beim Support nach.",
      "Zeitabhängige Plattformmeldungen sind als datierte Belege zu behandeln. Kakobuy veröffentlichte beispielsweise am 30. Juni 2026 ein Update zu EU Duty-Free Shipping Lines. Das bestätigt eine damalige betriebliche Änderung, rechtfertigt aber keine dauerhafte Aussage, dass jedes zukünftige EU-Paket zollfrei sein werde. In Ratgebertexten sollte das Datum genannt, auf mögliche Änderungen hingewiesen und eine zeitlich begrenzte Aktion oder Aktualisierung nicht in ein ewiges Plattformmerkmal verwandelt werden.",
    ]],
    ["Zoll, Deklaration und Steuern im Zielland", [
      "Eine Versandlinie kann Transport und Zollabwicklung unterstützen, doch der Käufer bleibt dafür verantwortlich, die Regeln des Ziellandes zu verstehen und wahrheitsgemäße Angaben zu machen. Deklarierter Wert, Produktbeschreibung, Menge und lokale Schwellen können die Bewertung beeinflussen. Bezeichnungen wie tax-free oder duty-paid müssen nach ihren aktuellen Bedingungen gelesen werden. Kein unabhängiger Leitfaden kann garantieren, dass ein Paket keine Kontrolle, Gebühr oder Verzögerung erlebt, und Unterbewertung darf nicht als Versandtrick empfohlen werden.",
      "Prüfen Sie bei wichtigen Werten oder Produktbeschränkungen die Zollbehörde des Ziellandes. Bewahren Sie Kauf- und Zahlungsbelege auf, verwenden Sie korrekte Empfängerdaten und kontrollieren Sie die Deklaration vor der Einreichung. Wenn Kakobuy einen optionalen Deklarationsservice oder linienspezifische Hinweise zeigt, lesen Sie genau, was enthalten ist. Die offizielle Gebührenseite nennt derzeit gewöhnlich 8 RMB je nach Versandmethode; das ist ein Plattformservice und nicht die mögliche staatliche Einfuhrabgabe.",
    ]],
    ["Die abschließende Paketcheckliste", [
      "Prüfen Sie vor der Zahlung Empfängername, Adresse, Telefonnummer und Postleitzahl; Artikel und Mengen; Klassifizierung eingeschränkter Produkte; gewünschte Verpackung; gepackte oder geschätzte Maße; Regel für das Abrechnungsgewicht; Tracking und Entschädigung; Deklaration und angezeigte Gesamtsumme. Speichern Sie Paketnummer und Routendetails. Diese Dokumentation ist nützlicher als ein allgemeines Lieferversprechen, wenn Tracking später pausiert oder ein Supportgespräch erforderlich wird.",
      "Wählen Sie die Route nach Ihrer Toleranz für Kosten, Verzögerung und Verlust und nicht nur nach der kürzesten angezeigten Schätzung. Lieferfenster sind Schätzungen, weil Zoll, Flugkapazität, saisonales Volumen und lokale Übergabe nicht vollständig vom Einkaufsagenten gesteuert werden. Ein guter Kakobuy-Versandleitfaden erklärt, wie aktuelle Optionen verglichen werden. Er verspricht keine universell billigste Linie, keine garantierte Tageszahl und keinen Divisor für jedes Zielland.",
      "Verfolgen Sie nach der Zahlung Ereignisse statt eine erfundene tägliche Bewegung zu erwarten. Exportabfertigung, Flugzuteilung, Zollbearbeitung und Übergabe an den lokalen Dienst können stille Phasen verursachen. Vergleichen Sie das letzte Ereignis mit dem aktuellen Trackingmuster der Route und kontaktieren Sie bei einer deutlich längeren Pause den Support mit der Paketnummer. Verwenden Sie die Laufzeit eines anderen Käufers nicht als Deadline: Gleich benannte Routen können an verschiedenen Tagen starten, andere Zolllasten treffen und in unterschiedliche lokale Netze übergehen.",
    ]],
  ],
  storageArticle: [
    ["Was die Aussage zu 100 Tagen Lagerung bedeutet", [
      "Kakobuys öffentliche Servicebeschreibung und das Einsteigermaterial bewerben derzeit 100 Tage kostenlose Lagerung. Dieselben Informationen empfehlen, weitere Artikel zu kaufen und gemeinsam zu versenden, um internationale Versandkosten zu sparen. Das ist eine konkrete Plattformaussage, die am 29. August 2026 geprüft wurde. Dennoch sollte sie im Konto und in der aktuellen Hilfe bestätigt werden, weil Lagerbedingungen nach Veröffentlichung eines Artikels aktualisiert werden können.",
      "Die Lagerzeit beginnt, nachdem ein Artikel vom Lager angenommen wurde, nicht bei der Entdeckung oder Bezahlung. Verschiedene Produkte können daher unterschiedliche Eingangszeiten und Resttage haben. Führen Sie einen einfachen Tracker mit Bestellnummer, Produkt, Lagerdatum, QC-Status, Rückgabeentscheidung, geschätztem Gewicht und persönlicher Paketfrist. Setzen Sie die eigene Frist vor das Plattformlimit, damit ein vergessener Artikel oder eine Supportverzögerung keine überhastete Entscheidung erzwingt.",
    ]],
    ["Die verschiedenen Fristen vor der Entscheidung trennen", [
      "Es gibt mindestens vier Uhren. Die Verkäufer-Versandzeit läuft zwischen Kauf und Lieferung zu Kakobuy. Die After-Sales-Frist bestimmt Stornierung, Rückgabe oder Austausch. Die Lagerfrist regelt, wie lange ein angenommener Artikel verbleiben darf. Die internationale Transportzeit beginnt erst nach Paketeinreichung und Übergabe an die gewählte Logistikroute. Diese Fristen können sich überschneiden, doch eine verlängert nicht automatisch die andere.",
      "Der häufigste Fehler ist die Annahme, 100 Tage Lagerung bedeuteten 100 Tage Rückgaberecht. Das stimmt nicht. Die Lagerzeit ist ein Warehouse-Service, während die Rückgabe von Verkäuferteilnahme, Bestellstatus, Zustand und Kakobuy-Prozess abhängt. Prüfen Sie sofort, auch wenn der Artikel wochenlang lagern soll. Die längere Lagerzeit eignet sich am besten für Konsolidierung und Routenplanung, nachdem der Artikel Ihre Prüfung bestanden hat.",
    ]],
    ["Stornierung hängt vom Bestellstatus ab", [
      "Kakobuys veröffentlichte Stornierungshinweise unterscheiden nach Status. Laut Hilfetext kann der Käufer bei „paid“ den Kundenservice zur Stornierung kontaktieren. Bei „Processing“ kann der Einkauf bereits abgeschlossen sein, auch wenn der Händler noch nicht versandt hat; die Stornierung wird dann zu einem anderen betrieblichen Vorgang. Sobald ein Verkäufer versendet hat oder der Artikel eingetroffen ist, handelt es sich nicht mehr um die einfache Rücknahme einer unberührten Zahlung.",
      "Handeln Sie schnell und verwenden Sie präzise Angaben: Bestellnummer, gewünschte Aktion und Grund. Bestellen Sie nicht doppelt, bevor die erste Stornierung bestätigt ist. Hat der Verkäufer bereits angenommen oder versandt, können inländische Rücksendekosten oder Ablehnung folgen. Deshalb sollte ein Leitfaden Status erklären und nicht „kostenlose Stornierung“ versprechen. Der Live-Bestelldatensatz und die Supportantwort bestimmen, was in der konkreten Transaktion möglich ist.",
    ]],
    ["Sofort nach dem Lagereingang prüfen", [
      "Kakobuys öffentliche Startseite sagt, dass die Qualitätsprüfung nach Ankunft sichtbare Punkte wie Mängel, Größe und Farbe abdeckt. Bestätigen Sie zuerst die Identität: Menge, bestellte Option, Farbe, Größenschild und sichtbares Zubehör. Prüfen Sie danach Form, Verarbeitung und Schäden. Speichern Sie jedes relevante Verkäufermaß oder Optionsbild. Ein schneller Vergleich ist verlässlicher, als nach dem Eintreffen mehrerer anderer Produkte die Bestellung rekonstruieren zu müssen.",
      "QC-Fotos verringern sichtbare Unsicherheit, zertifizieren aber weder Echtheit, Material, Komfort, Elektronikfunktion noch langfristige Haltbarkeit. Fordern Sie nur eine Ansicht oder ein Maß an, das die Entscheidung wirklich verändern kann. Wenn die Oberfläche ein Bild nicht zeigt, erinnern Sie sich an Kakobuys Mitteilung vom 10. Mai 2026, die ein Anzeigeproblem von Lagerung und Paketeinreichung trennte. Bestätigen Sie die Belege, statt einen Darstellungsfehler mit einem verlorenen Artikel gleichzusetzen.",
    ]],
    ["Die Bezeichnung 5-Day Return/Exchange richtig verstehen", [
      "Kakobuy besitzt eine offizielle Hilfeseite mit dem Titel „What is 5-Day Return/Exchange Guarantee?“. Dort wird sie als besondere After-Sales-Leistung beschrieben, die von Verkäufern für unterstützte Drittanbieterprodukte angeboten wird. Diese Formulierung ist wichtig: Es ist eine an den Verkäufer gebundene Deckung und kein Beweis dafür, dass jedes Angebot aus beliebigem Grund zurückgegeben werden kann. Prüfen Sie, ob der konkrete Artikel die Leistung trägt und lesen Sie die aktuellen Bedingungen.",
      "Ein Austausch erzeugt eine zweite inländische Reise. Kakobuys Hilfetext sagt, dass das Produkt zum Verkäufer zurückgeht und erneut versandt wird und die Einlagerung je nach Verkäufer ungefähr 7 bis 20 Tage dauern kann. Das ist keine garantierte Bearbeitungszeit. Bestand, Verkäuferreaktion, Inlandstransport und eine weitere Lagerprüfung können sie beeinflussen. Wenn Zeit wichtiger ist als das Behalten des Artikels, vergleichen Sie Austausch, Rückgabe mit Neubestellung und Annahme als getrennte Entscheidungen.",
    ]],
    ["Berechtigung erhalten und den Antrag sachlich formulieren", [
      "Vermeiden Sie irreversible Zusatzarbeiten, Entfernen von Etiketten oder Entsorgen wichtiger Verpackung vor der Annahmeentscheidung. Rückgabeberechtigung kann von Zustand und Verkäuferregeln abhängen. Beschreiben Sie bei einem Problem die bestellte Variante, die fotografierte Variante, das konkrete Bild und den sichtbaren Unterschied. „Größenschild zeigt 42, Bestellung sagt 44“ ist umsetzbar. „Sieht fake aus“ ist kein präziser Lager-Mängelbericht und verlangt vom Support Schlussfolgerungen, die ein Foto nicht belegen kann.",
      "Rechnen Sie mit möglichem Inlandversand, Verkäuferablehnung oder nicht erstattbaren Servicekosten. Bei einem sichtbaren Verkäuferfehler dokumentieren Sie ihn; bei Käuferpräferenz oder einer Größenwahl entgegen dem Angebot kann das Ergebnis anders ausfallen. Behaupten Sie niemals, dass ein Spreadsheet-Link eine kostenlose Rückgabe garantiert. Eine kuratierte Route kann nur die Originalquelle bewahren und den Vergleich erleichtern, solange der Plattformprozess noch offen ist.",
    ]],
    ["Die Lagerzeit für ein besseres Paket nutzen", [
      "Sobald ein Artikel akzeptiert ist, wird Lagerzeit zu Planungszeit. Warten Sie auf kompatible Produkte, vergleichen Sie die kombinierte Schätzung, entscheiden Sie über notwendige Retail-Verpackung und prüfen Sie Linienberechtigung. Kakobuys eigenes Einsteigermaterial verbindet den 100-Tage-Service mit dem Zusammenfassen von Artikeln. Das mögliche Sparen entsteht durch weniger doppelte Außenverpackung und nicht durch eine Garantie, dass jedes größere Paket billiger ist.",
      "Berechnen Sie bei sperrigen oder gemischten Sendungen mindestens zwei Szenarien: konsolidiert und sinnvoll geteilt. Trennen Sie zerbrechliche Ware von komprimierbaren Artikeln, Dringendes von Produkten, die warten können, und routenempfindliche Artikel, wenn sie gewöhnliche Linien blockieren. Beobachten Sie das älteste Lagerdatum und lassen Sie Zeit für Umpacken oder Support. Eine persönliche Frist etwa zwei Wochen vor dem beworbenen Limit bietet Puffer, ohne die offizielle Regel zu verändern.",
    ]],
    ["Eine einfache wöchentliche Lagerroutine", [
      "Sortieren Sie einmal pro Woche alle Lagerartikel in fünf Zustände: QC ausstehend, weitere Belege nötig, After-Sales offen, für Paket akzeptiert oder für Konsolidierung halten. Notieren Sie nächste Aktion und Datum. Prüfen Sie offene After-Sales-Fälle häufiger, weil Verkäuferfristen kürzer als die Lagerzeit sein können. Öffnen Sie den Estimator erneut, wenn sich das wahrscheinliche Paket ändert. Entfernen Sie tote Produktlinks aus öffentlichen Spreadsheets, statt Besucher auf fremde Ziele zu schicken.",
      "Diese Routine macht aus passivem Warten einen kontrollierten Ablauf. Sie erzeugt auch bessere redaktionelle Inhalte: Fakten tragen Daten, Plattformangaben werden zugeordnet, variable Bedingungen gekennzeichnet und Käuferentscheidungen erklärt. Das hilft Suchbesuchern mehr als eine kopierte Hilfeseite oder erfundene Rezension. Für die einzelne Transaktion bleiben Live-Konto, Bestellstatus und aktuelle Hilfe von Kakobuy maßgeblich; der Leitfaden bietet den Rahmen, sie sorgfältig zu lesen.",
      "Nähert sich ein Artikel Ihrer persönlichen Frist, entscheiden Sie anhand der vorhandenen Belege, statt auf ein perfektes zukünftiges Paket zu warten. Klären Sie offene QC-Fragen, prüfen Sie After-Sales und vergleichen Sie Versand mit und ohne den Artikel. Blockiert ein günstiger Artikel alle geeigneten Routen, kann eine getrennte Entscheidung billiger sein, als ihn in die Hauptbox zu zwingen. Reichen Sie akzeptierte Artikel rechtzeitig ein und speichern Sie Screenshots von Lagerliste und Paketantrag, damit Daten und Anweisungen im Supportgespräch nachvollziehbar bleiben.",
    ]],
  ],
};
