import type { Article } from "./article-data";

type ArticleKey = "qcArticle" | "shippingArticle" | "storageArticle";

export const esArticleSections: Record<ArticleKey, Article["sections"]> = {
  qcArticle: [
    ["Qué debe hacer realmente una hoja de cálculo de Kakobuy", [
      "Muchas personas buscan una «hoja de cálculo de Kakobuy» esperando una lista enorme de productos. El tamaño, por sí solo, no garantiza calidad. Una hoja útil relaciona una descripción clara con un destino activo, registra el precio visible y el contexto de la variante, y permite volver después a la evidencia original. Nunca debe insinuar que un anuncio es seguro, auténtico o de gran calidad solo porque alguien lo añadió a una tabla. La hoja sirve para descubrir y documentar; la decisión de compra sigue siendo del comprador.",
      "Nuestra regla de inclusión es sencilla: al comprobarlo, la imagen de la tarjeta, el nombre del producto y la página de destino deben describir el mismo artículo. Una ruta se elimina o se revisa si cambia, desaparece o muestra otro producto. Los precios son capturas de un momento, no promesas, porque los vendedores modifican anuncios y los tipos de cambio varían. Este método más estricto quizá ofrezca menos hallazgos que una lista social sin filtrar, pero da a cada resultado una función rastreable dentro del proceso de compra.",
    ]],
    ["Separar el flujo oficial de Kakobuy en decisiones", [
      "El material público para principiantes de Kakobuy describe el flujo habitual de un agente: elegir un producto en un mercado chino, copiar el enlace, pegarlo en Kakobuy, seleccionar las opciones necesarias, pagar el artículo, esperar su llegada y control de calidad en el almacén y, después, enviar un paquete internacional. La secuencia importa porque el artículo y el transporte internacional se pagan en etapas diferentes. Tratarlo todo como una sola compra dificulta saber a qué decisión corresponde cada coste o retraso.",
      "Un comprador disciplinado se detiene en cuatro puntos. El primero es el anuncio de origen: ¿se entienden artículo, vendedor y opción? El segundo es el registro del pedido: ¿son correctos talla, color, cantidad y variante? El tercero es la evidencia del almacén: ¿el artículo fotografiado coincide visiblemente con ese registro? El cuarto es el paquete: ¿son aceptables embalaje, ruta, declaración y cálculo final? La hoja resulta más valiosa cuando transporta información exacta de un punto al siguiente.",
    ]],
    ["Crear el registro del pedido antes de pagar", [
      "Guarda la URL exacta, el título del anuncio, la variante elegida, la cantidad, el precio mostrado por el vendedor y cualquier tabla de tallas o imagen de opciones que influyera en tu elección. Añade la fecha porque los anuncios activos cambian. Si un color solo se identifica mediante un número o una miniatura, conserva también ese detalle. Cuando lleguen las fotos del almacén, la memoria es una referencia deficiente; un registro compacto permite comparar lo recibido con lo que realmente se eligió, no con una publicación parecida vista días antes.",
      "Presta especial atención a las opciones traducidas. La traducción automática puede volver ambiguos los materiales, conjuntos y colores. No adivines cuando dos variantes se parecen. Abre la página de origen, compara las imágenes de opciones y usa una nota de pedido solo si resuelve una ambigüedad real. Las notas largas o contradictorias pueden crear errores nuevos. Si el vendedor no aporta una medida necesaria, trata esa ausencia como incertidumbre en vez de inventar una predicción exacta de ajuste.",
    ]],
    ["Leer el precio como una suma de capas", [
      "El precio del producto es solo la primera capa. Una compra mediante agente también puede incluir envío nacional del vendedor al almacén, cargo del medio de pago, servicios opcionales y, más tarde, transporte internacional. La página Services & Fees de Kakobuy indica actualmente que el servicio básico de agente no añade una comisión de gestión aparte del artículo y el envío, mientras que los servicios opcionales pueden costar más. Su ayuda de pagos muestra ahora para PayPal un cargo del 3,5 % más 0,30 USD. Son condiciones actuales, no constantes permanentes.",
      "Esta distinción es importante para una guía pública porque repetir un precio atractivo sin el resto de costes confunde al lector. Nuestras cifras en USD son conversiones aproximadas de precios visibles en CNY y excluyen servicios y transporte. Antes de pagar, revisa el checkout activo de Kakobuy y el método elegido. Antes de enviar el paquete, consulta de nuevo el estimador. Si una condición visible de Kakobuy contradice una guía antigua, debe prevalecer la página actual.",
    ]],
    ["Qué dice Kakobuy que ocurre al llegar al almacén", [
      "La página pública de Kakobuy dice que, después de que los productos lleguen al almacén, el control de calidad cubre problemas visibles como defectos, talla y color. Es útil, pero no significa que se verifiquen todos los materiales, medidas o detalles ocultos de fabricación. Las fotografías del almacén son evidencia de lo que puede mostrar la cámara. No prueban durabilidad, comodidad, composición o autenticidad, ni revelan un defecto oculto dentro de una suela, un forro o un componente electrónico.",
      "El aviso de la plataforma del 10 de mayo de 2026 sobre problemas recientes al mostrar ciertas imágenes de QC recuerda que hay que separar el artículo físico de la interfaz que lo presenta. El aviso decía que el problema visual no afectaba al almacenamiento ni al envío normal de paquetes. Si falta una imagen o no carga, no interpretes la ausencia como aprobación o rechazo. Vuelve a comprobar la página, contacta con soporte cuando sea necesario y espera la evidencia decisiva.",
    ]],
    ["Utilizar una revisión de QC en tres niveles", [
      "El primer nivel es la identidad. Confirma cantidad, color pedido, etiqueta de talla, variante, accesorios visibles y forma general. Si aparece una opción equivocada, detente y documéntala. El segundo nivel es la construcción. En calzado, compara puntera, altura del talón, alineación de paneles, forma de la suela, costuras y exceso de pegamento. En ropa, revisa vistas frontal y posterior, cuello, mangas, posición de estampado o bordado, costuras, manchas y agujeros. En bolsos y accesorios, comprueba medidas, color de herrajes, cierres, esquinas y acabado de bordes.",
      "El tercer nivel es la evidencia específica para decidir. Pregunta qué podría cambiar tu respuesta de aceptar a devolver. Si el ajuste depende del ancho del pecho, una foto con regla importa más que otra foto estética. Si preocupa el cierre de un bolso, solicita ese ángulo y no un primer plano genérico. La perspectiva puede distorsionar proporciones, así que compara varias vistas antes de declarar una asimetría. Describe el problema por ubicación y rasgo observable —«talón derecho, borde exterior, costura separada»— en vez de usar etiquetas vagas como «mala calidad».",
    ]],
    ["No confundir el tiempo de almacenamiento con el de devolución", [
      "La información pública de Kakobuy anuncia actualmente 100 días de almacenamiento gratuito. Esto permite esperar otros artículos y preparar un paquete consolidado, pero no equivale a 100 días para devolver al vendedor. La devolución o el cambio dependen del vendedor concreto, el estado del pedido, el estado del artículo y el procedimiento de la plataforma. Kakobuy también publica una «5-Day Return/Exchange Guarantee», descrita como servicio posventa del vendedor para artículos compatibles de mercados externos. No debe presentarse como cobertura universal.",
      "Inspecciona pronto cuando el pedido llegue al almacén. Si hay una diferencia visible, conserva la imagen relevante, indica la opción elegida y explica la diferencia mientras el pedido aún sea fácil de rastrear. Evita modificaciones irreversibles antes de aceptarlo. La negativa del vendedor, el envío nacional de devolución y el tiempo que tarda un reemplazo en volver al almacén pueden cambiar el resultado. La ayuda de Kakobuy señala que un producto cambiado puede tardar aproximadamente entre 7 y 20 días en almacenarse de nuevo, según el vendedor.",
    ]],
    ["Una regla práctica para decidir cada hallazgo", [
      "Acepta cuando el artículo fotografiado coincide con la variante registrada, no aparece un defecto visible decisivo y la incertidumbre restante es razonable para el precio. Pide evidencia cuando un ángulo o una medida ausente pueda cambiar realmente la decisión. Abre una solicitud posventa cuando exista una diferencia clara y documentable o un defecto visible y el pedido siga siendo elegible. Rechazar por un ángulo fotográfico poco favorecedor desperdicia tiempo; aceptar sin comprobar la identidad anula todo el propósito del QC.",
      "Tras aceptar, actualiza la hoja con la fecha de llegada, el peso estimado, las necesidades de embalaje y tu fecha límite para el paquete. Vuelve a comprobar el enlace de destino antes de compartirlo. Así la hoja pasa de lista estática a pequeño registro de auditoría. También favorece un mejor contenido para Google: cada recomendación se puede explicar con método, reservas y fuentes actuales, en lugar de afirmaciones vacías como «mejor vendedor», «calidad 1:1» o «seguridad garantizada».",
    ]],
  ],
  shippingArticle: [
    ["Por qué el estimador sirve para planificar, no como precio final", [
      "Kakobuy ofrece una página de estimación de gastos de envío, el lugar adecuado para comparar las rutas disponibles antes de que exista el paquete definitivo. Una estimación sigue dependiendo de los datos introducidos y de las reglas de la ruta, no de la caja ya embalada. El embalaje del vendedor, el reempaquetado del almacén, la categoría del artículo y el método de facturación del transportista pueden cambiar el resultado. Úsala para comparar escenarios y crear un intervalo presupuestario; no publiques una cifra como precio permanente para un país.",
      "La comparación útil comienza con el destino, un peso embalado realista y medidas aproximadas. Después anota disponibilidad, restricciones, seguimiento, compensación y moneda mostrada. Repite la consulta justo antes de enviar el paquete porque pueden cambiar nombres de líneas, descuentos y avisos operativos. El propio historial de actualizaciones de Kakobuy —incluidos avisos de rutas y seguimiento— demuestra por qué un artículo duradero debe explicar el método y remitir a los datos actuales para la elección final.",
    ]],
    ["Entender el peso real y el volumétrico", [
      "El peso real es la lectura de la báscula una vez embalado. El peso volumétrico convierte el espacio ocupado en una cifra facturable, normalmente multiplicando largo por ancho por alto y dividiendo por un divisor específico de la ruta. Algunas líneas cobran el mayor entre peso real y volumétrico; otras aplican umbrales, redondeos o reglas de categoría diferentes. El divisor exacto debe proceder de los detalles actuales de la ruta, no de una captura antigua en redes sociales.",
      "Los productos densos, como la ropa doblada, suelen acercarse más al peso real. El calzado voluminoso, las cajas rígidas, los abrigos acolchados y el relleno protector pueden ocupar mucho más espacio de lo que su masa sugiere. Por eso dos paquetes con el mismo peso en báscula pueden dar estimaciones distintas. Registra peso y dimensiones al comparar. Si la interfaz solo muestra una estimación preliminar, deja margen para la medición final del almacén y los incrementos de facturación del transportista.",
    ]],
    ["Desglosar todos los costes antes del envío", [
      "El cargo internacional se suma a costes anteriores: precio del producto, posible entrega nacional del vendedor, cargos del medio de pago y cualquier servicio opcional del almacén. La ayuda Services & Fees de Kakobuy indica actualmente que el servicio básico de agente no tiene comisión de gestión aparte del artículo y del envío, aunque se pueden elegir servicios de valor añadido. La misma sección oficial dice que la declaración aduanera del paquete suele costar 8 RMB según el método de envío. Comprueba estas condiciones en la página activa al enviar.",
      "No combines cifras distintas en un único «porcentaje de comisión». Un cargo de pago no es lo mismo que el margen de cambio; el envío nacional no es transporte internacional; el refuerzo opcional no es una comisión del agente; y los impuestos cobrados en destino no están necesariamente incluidos en la estimación. Un presupuesto transparente separa cada capa y marca los valores desconocidos. Así es más fácil comparar rutas y evitar que un precio atractivo oculte el coste total puesto en destino.",
    ]],
    ["El embalaje es una decisión de coste y protección", [
      "Quitar una caja de zapatos puede reducir las dimensiones, pero también elimina estructura y puede disminuir el valor de regalo o reventa. Envasar al vacío comprime prendas blandas, pero no conviene a artículos que se arrugan mucho o dependen de su forma. El refuerzo añade masa y a veces volumen, aunque puede ser sensato para contenido frágil o un viaje con muchas transferencias. No existe una regla universal de «quitar todo el embalaje»; la elección depende del producto y de las consecuencias del daño.",
      "Clasifica el embalaje en tres grupos. El esencial protege forma, vidrio, herrajes o materiales sensibles a humedad. El útil agrupa piezas pequeñas o identifica la variante. El decorativo mejora la presentación pero protege poco durante el transporte. Retira primero el tercer grupo cuando el problema sea el volumen. Si solicitas un servicio, revisa su precio actual y explica el objetivo. «Quitar cajas de zapatos; conservar soportes interiores» es más práctico que «hacerlo barato pero seguro».",
    ]],
    ["Consolidar de forma deliberada durante el almacenamiento", [
      "La información oficial de Kakobuy anuncia 100 días de almacenamiento gratuito y relaciona expresamente ese tiempo con comprar más artículos y enviarlos juntos. Consolidar puede reducir cajas exteriores repetidas y evitar varios paquetes internacionales pequeños. También permite esperar productos compatibles. Sin embargo, más grande no siempre significa más barato: una caja sobredimensionada puede activar el peso volumétrico, superar un límite o mezclar productos restringidos y normales de modo que reduzca las rutas disponibles.",
      "Agrupa por destino, urgencia, fragilidad y compatibilidad de ruta. Un pedido lento y barato de ropa no siempre debe viajar con algo urgente o frágil. Cuando sea posible, compara al menos dos escenarios: una caja consolidada y una división lógica. Incluye las preferencias de embalaje en ambos. El objetivo no es usar el menor número de paquetes, sino alcanzar el menor coste total aceptable con la protección, velocidad y riesgo que realmente necesitas.",
    ]],
    ["La elegibilidad de la línea cambia según producto y destino", [
      "Baterías, líquidos, imanes, productos de marca, artículos parecidos a alimentos y otras categorías sensibles pueden reducir las líneas mostradas o exigir tratamiento especial. La disponibilidad también depende del destino y de las operaciones actuales. Nunca prometas que una ruta aceptará un artículo concreto solo porque un envío anterior funcionó. Usa el estimador actual y la interfaz del paquete después de que el almacén clasifique los productos. Si la clasificación parece errónea, pregunta a soporte antes de pagar en vez de suponer que aparecerá otra ruta.",
      "Los avisos sensibles al tiempo deben tratarse como evidencia fechada. Kakobuy publicó, por ejemplo, una actualización sobre líneas EU Duty-Free el 30 de junio de 2026. Confirma un cambio operativo de ese momento; no permite afirmar para siempre que todos los futuros paquetes europeos estarán libres de aranceles. En una guía práctica, indica la fecha, explica que las condiciones pueden cambiar y evita convertir una promoción o actualización temporal en característica permanente.",
    ]],
    ["Aduanas, declaración e impuestos de destino", [
      "Una línea puede ayudar con transporte y tramitación aduanera, pero el comprador sigue siendo responsable de entender las reglas del destino y facilitar datos veraces. El valor declarado, la descripción, la cantidad y los umbrales locales influyen en la evaluación. Las etiquetas tax-free o duty-paid deben leerse según sus condiciones vigentes. Ninguna guía independiente puede garantizar que un paquete evite inspecciones, cargos o retrasos, ni debe presentar la infravaloración como truco de envío.",
      "Consulta la autoridad aduanera del destino cuando importen el valor o las restricciones. Conserva comprobantes de compra y pago, usa datos exactos del destinatario y revisa la declaración antes de enviarla. Si Kakobuy muestra un servicio opcional de declaración o instrucciones de una línea, lee qué incluyen. Services & Fees indica actualmente que la declaración suele costar 8 RMB según el método; es un servicio de plataforma, no el arancel que pueda exigir la autoridad del destino.",
    ]],
    ["Lista final de comprobación del paquete", [
      "Antes de pagar, verifica nombre, dirección, teléfono y código postal del destinatario; lista y cantidades; clasificación de artículos restringidos; embalaje solicitado; dimensiones medidas o estimadas; regla de peso facturable; seguimiento y compensación; declaración; y total mostrado. Guarda el número del paquete y una captura de la ruta. Ese registro sirve más que una promesa genérica si el seguimiento se detiene o hace falta hablar con soporte.",
      "Elige la ruta que encaje con tu tolerancia a coste, retraso y pérdida, no solo la que muestre el plazo más corto. Las ventanas de entrega son estimaciones porque aduanas, capacidad aérea, volumen estacional y entrega local no están bajo control completo del agente. Una buena guía de envío de Kakobuy enseña a comparar opciones vivas. No proclama una línea universalmente más barata, un número garantizado de días ni un divisor válido para todos los destinos.",
      "Después del pago, sigue eventos en lugar de actualizar esperando movimiento diario. La salida de exportación, asignación de vuelo, aduanas y entrega al operador local pueden crear periodos silenciosos. Compara el último evento con el patrón de seguimiento indicado y contacta con soporte, con el número de paquete, si la pausa supera claramente la orientación actual. No uses el plazo de otro comprador como fecha límite: rutas con el mismo nombre pueden salir en días distintos, afrontar cargas aduaneras diferentes y entrar en redes locales distintas.",
    ]],
  ],
  storageArticle: [
    ["Qué significa la afirmación de 100 días de almacenamiento", [
      "La introducción pública del servicio y el material para principiantes de Kakobuy anuncian actualmente 100 días de almacenamiento gratuito en su almacén. El mismo material anima a comprar más artículos y enviarlos juntos para ahorrar costes internacionales. Es una afirmación concreta de la plataforma, comprobada el 29 de agosto de 2026. Aun así, debe confirmarse en la cuenta y ayuda actuales porque la política puede actualizarse después de publicar un artículo.",
      "El almacenamiento empieza cuando el almacén acepta un artículo, no cuando lo descubres o pagas al vendedor. Por tanto, diferentes productos pueden tener fechas de llegada y días restantes distintos. Crea un seguimiento sencillo con número de pedido, producto, fecha de almacén, estado de QC, decisión de devolución, peso estimado y fecha personal para el paquete. Fija tu plazo antes del límite de la plataforma para que un artículo olvidado o un retraso de soporte no obligue a decidir deprisa.",
    ]],
    ["Separar los distintos relojes antes de decidir", [
      "Hay al menos cuatro relojes. El de despacho del vendedor transcurre entre compra y entrega a Kakobuy. El de posventa controla la elegibilidad de cancelación, devolución o cambio. El del almacén determina cuánto puede permanecer un artículo aceptado. El de tránsito internacional empieza solo después de enviar el paquete y entregarlo a la ruta elegida. Pueden solaparse, pero uno no prolonga automáticamente otro.",
      "El error más común es pensar que 100 días de almacenamiento crean 100 días para devolver. No es así. El almacenamiento es un servicio del almacén; la devolución depende del vendedor, el estado del pedido, el estado del artículo y el procedimiento de Kakobuy. Inspecciona pronto aunque pienses guardar durante semanas. El periodo largo sirve mejor para consolidar y planificar rutas una vez superada tu revisión.",
    ]],
    ["La cancelación depende del estado del pedido", [
      "La guía de cancelación publicada por Kakobuy distingue estados. Su ayuda dice que, si el pedido aparece como «paid», el comprador puede contactar con atención al cliente para cancelarlo. Si aparece «Processing», el agente puede haber realizado ya la compra aunque el comerciante aún no lo haya enviado, por lo que la cancelación se convierte en otra solicitud operativa. Una vez enviado o recibido, ya no equivale a anular un pago intacto.",
      "Actúa rápido y aporta datos precisos: número de pedido, acción solicitada y motivo. No hagas un pedido duplicado hasta que se confirme la cancelación. Si el vendedor ya aceptó o envió, puede aplicarse devolución nacional o rechazo. Por eso una guía debe explicar estados y no prometer «cancelación gratuita». El registro activo del pedido y la respuesta de soporte determinan qué es posible en esa transacción.",
    ]],
    ["Inspeccionar inmediatamente al llegar al almacén", [
      "La página pública de Kakobuy dice que el control de calidad cubre problemas visibles, incluida talla, color y defectos, después de la llegada. Usa ese momento para confirmar primero identidad: cantidad, opción, color, etiqueta de talla y accesorios visibles. Después revisa forma, construcción y daños. Guarda las medidas o imágenes del vendedor que importen. Una comparación rápida es más fiable que reconstruir el pedido cuando ya hayan llegado otros productos.",
      "Las fotos de QC reducen la incertidumbre visible; no certifican autenticidad, composición, comodidad, funcionamiento eléctrico o durabilidad. Si falta una vista o medida crítica, pide solo lo que pueda cambiar la decisión. Si no aparece una imagen, recuerda que el aviso de Kakobuy del 10 de mayo de 2026 separó un problema de visualización de las funciones de almacenamiento y envío. Confirma la evidencia en vez de suponer que el artículo físico se perdió.",
    ]],
    ["Entender la etiqueta 5-Day Return/Exchange", [
      "Kakobuy tiene una página oficial titulada «What is 5-Day Return/Exchange Guarantee?». La describe como un servicio posventa especial ofrecido por vendedores para productos compatibles de mercados externos. La redacción importa: es cobertura vinculada al vendedor, no prueba de que cualquier anuncio pueda devolverse por cualquier motivo. Comprueba que el artículo incluye el servicio y lee las condiciones vigentes antes de incorporarlo a tu decisión.",
      "Un cambio añade un segundo trayecto nacional. La ayuda de Kakobuy dice que el producto vuelve al vendedor y se envía de nuevo, y que puede tardar aproximadamente entre 7 y 20 días en regresar al almacén según el vendedor. No es un plazo garantizado. Stock, respuesta del vendedor, transporte y otra revisión pueden alterarlo. Si el tiempo importa más que conservar el artículo, compara cambio, devolución y nueva compra, y aceptación como opciones separadas.",
    ]],
    ["Mantener la elegibilidad y describir hechos", [
      "Evita trabajos irreversibles de valor añadido, quitar etiquetas o desechar embalaje importante antes de decidir. La elegibilidad puede depender del estado y las reglas del vendedor. Al informar de un problema, identifica la variante pedida, la fotografiada, la imagen exacta y la diferencia observable. «La etiqueta dice 42; el pedido dice 44» permite actuar. «Parece falso» no es un informe preciso de defecto y exige que soporte infiera hechos que una foto quizá no demuestre.",
      "Cuenta con posibles gastos nacionales, negativa del vendedor o servicios no reembolsables. Si hay un error visible del vendedor, documéntalo; si se trata de preferencia personal o de talla elegida contra la información del anuncio, el resultado puede ser distinto. Nunca afirmes que un enlace de hoja garantiza devolución gratuita. Una selección puede conservar la ruta original y facilitar la comparación mientras siga abierto el proceso de plataforma, nada más.",
    ]],
    ["Usar el almacenamiento para construir un paquete mejor", [
      "Una vez aceptado el artículo, el almacén se convierte en espacio de planificación. Espera productos compatibles, compara la estimación conjunta, decide qué embalaje comercial hace falta y revisa rutas. El material para principiantes de Kakobuy relaciona sus 100 días con combinar artículos. El ahorro potencial procede de evitar cajas exteriores repetidas y componentes fijos, no de una garantía de que todo paquete mayor sea más barato.",
      "Prueba al menos dos escenarios si el envío es voluminoso o mixto: consolidado y dividido con lógica. Separa objetos frágiles de los comprimibles, urgentes de los que pueden esperar y sensibles a rutas si bloquean líneas normales. Sigue la fecha de almacén más antigua y deja tiempo para reempaquetado o soporte. Un plazo personal unas dos semanas antes del límite anunciado da margen práctico sin cambiar la regla oficial.",
    ]],
    ["Una rutina semanal sencilla para el almacén", [
      "Una vez por semana, clasifica los artículos en cinco estados: esperando QC, falta evidencia, posventa abierto, aceptado para paquete o reservado para consolidar. Anota la siguiente acción y fecha. Revisa más a menudo los casos posventa porque los plazos del vendedor pueden ser más cortos que el almacenamiento. Vuelve al estimador cuando cambie el paquete probable. Retira enlaces muertos de hojas públicas en vez de dejar que una guía envíe a destinos no relacionados.",
      "Esta rutina transforma la espera pasiva en operaciones controladas. También produce mejor contenido editorial: los hechos tienen fechas, las afirmaciones se atribuyen, las condiciones variables se identifican y las decisiones se explican. Es más útil para una visita de búsqueda que copiar el centro de ayuda o inventar una reseña. La cuenta activa, el estado del pedido y la ayuda actual de Kakobuy siguen mandando en cada transacción; la guía aporta el marco para leerlos bien.",
      "Cuando un artículo se acerque a tu fecha personal, decide con la evidencia disponible en vez de esperar un paquete futuro perfecto. Cierra preguntas de QC, comprueba si posventa sigue abierto y compara el envío con y sin el artículo. Si algo barato bloquea todas las rutas adecuadas, una decisión separada puede costar menos que forzarlo en la caja principal. Envía los artículos aceptados con tiempo para embalaje y medición antes del límite anunciado, y conserva capturas del almacén y la solicitud para recuperar fechas e instrucciones al hablar con soporte.",
    ]],
  ],
};
