import type { Locale } from "./site-data";

export type CorePageKey = "spreadsheet" | "finds" | "guide" | "qc" | "shipping";
type CoreSection = [title: string, body: string];

export const corePageCopy: Record<Locale, Record<CorePageKey, CoreSection[]>> = {
  en: {
    spreadsheet: [
      ["Use fields that preserve the buying decision", "A useful Kakobuy spreadsheet records the source URL, listing title, seller, selected option, quantity, visible CNY price and date checked. Add the exact color or size label instead of a simplified nickname. The aim is not to collect the greatest number of links; it is to preserve enough context to reopen the live listing and understand what was selected. A row should never imply authenticity, quality or seller reliability merely because it appears in the catalog."],
      ["Separate a price snapshot from the final cost", "Record the seller price as a dated snapshot and keep domestic delivery, payment charges, optional services and international freight in separate fields. A converted USD value is useful for comparison, but it is not a checkout guarantee. Exchange rates and seller prices change. Recheck the live listing before ordering and use Kakobuy's current estimator only when destination, item category and realistic parcel measurements are available. This keeps a product-discovery page from competing with a full shipping-cost guide."],
      ["Map every option to later warehouse evidence", "Save the ordered variant in the same wording and order used by the source listing. When QC views become available, compare quantity, color, size tag, visible accessories and broad shape with that saved record. Mark a missing view as missing evidence, not as approval. If a measurement or angle could change the decision, request that specific evidence. The spreadsheet should link the discovery record to the warehouse decision without pretending that a photograph proves material, durability, comfort or authenticity."],
      ["Maintain links instead of publishing a frozen dump", "Add a last-checked date and a simple state such as active, changed, unavailable or replaced. If a destination opens a different product, remove the route until it is verified again. Preserve the original source rather than silently swapping in a similar listing. A replacement deserves its own review because seller, options and price may differ. This maintenance rule makes the spreadsheet auditable and reduces dead links, stale prices and duplicate rows while keeping the original search intent focused on verified product records."],
    ],
    finds: [
      ["Start each find with a clear search need", "Choose a category, use case, size requirement and budget before opening product cards. A useful find answers a defined need instead of relying on hype or an unexplained popularity label. Search results should lead to the exact matching product record, not to a copied cart or unrelated agent. Check whether the product image, title, visible option and destination still describe the same item. When the evidence does not align, leave the find unpublished until the route can be checked again."],
      ["Verify the live destination, not only the card", "A card is a dated editorial snapshot. The source listing controls the available variants, seller price and current stock. Reopen it before ordering, confirm the selected option and save any size chart or option image that affected the choice. Do not treat an old screenshot as proof that a listing still exists. If the live destination redirects, changes category or shows a different product, the find has failed verification even when the old image still looks attractive."],
      ["Handle dead and changed links transparently", "Mark a failed route with the date and observed problem. Do not redirect the card silently to a merely similar product because the replacement may have different sizing, materials, seller conditions or packaging. Search by descriptive attributes or source identifiers, then evaluate the new listing as a separate candidate. When no reliable replacement exists, keep the category available and remove only the broken card. That protects the rest of the catalog without manufacturing continuity that the source evidence cannot support."],
      ["Keep recommendation language within the evidence", "A listing can be relevant and correctly mapped without being proven safe, authentic or high quality. Describe observable information: category, visible design, listed options, dated price and exact destination. Reserve QC judgments for warehouse evidence and shipping judgments for the parcel stage. Never invent sales counts, customer consensus or personal ownership. This narrower vocabulary helps the finds page rank for product discovery while avoiding overlap with the site's QC, shipping and long-form article pages."],
    ],
    guide: [
      ["Build a source record before product payment", "Open the exact marketplace listing and record the URL, seller-displayed title, selected variant, quantity, current CNY price and date. Compare option thumbnails carefully when translated names are unclear. Kakobuy's public purchasing flow separates product ordering from later international parcel submission, so keep the two payments and their evidence separate. A spreadsheet card or social post can help discovery, but the live listing and current Kakobuy order screen remain the records to verify before payment."],
      ["Treat seller dispatch and warehouse intake as different events", "A seller-sent status does not prove that the warehouse has received or inspected the item. Keep the domestic shipment reference with the order and wait for the warehouse record. At intake, compare quantity, selected color or size, visible accessories and condition with the saved order. Kakobuy's public material describes visible inspection limits; photographs cannot prove electronics function, long-term durability, comfort or authenticity. Record what is shown and clearly mark what remains unknown."],
      ["Release a parcel only after the item record is complete", "Resolve decision-critical mismatches before submitting international shipping. Confirm which orders are included, recipient details, packaging instructions, packed measurements and the routes currently available for that destination and item classification. The advertised warehouse-storage period is not the same as a seller return window, so do not postpone an open after-sales issue simply because storage remains available. A parcel decision should follow the current order evidence, not a generic timeline copied from another shipment."],
      ["Use a short audit trail when something is unclear", "Save the page, visible status, date and identifier connected to the problem. For an item question, begin with the order record; for a submitted package, add the parcel number; for carrier events, use the displayed tracking reference and carrier. Ask support for one clear action and redact personal details before sharing evidence. A small change log prevents later screenshots from replacing earlier observations and helps distinguish seller, warehouse, platform and carrier stages without guessing."],
    ],
    qc: [
      ["Check identity before workmanship", "Begin with the information that can make every later inspection irrelevant: quantity, ordered color, size tag, variant name, included accessories and broad product shape. Compare the warehouse view with the saved order record, not with memory or another seller's photo. If the item identity is wrong, document the mismatch before spending time on small construction details. Use observable language such as location, color and measurement rather than broad labels such as perfect, bad or guaranteed authentic."],
      ["Review visible construction by category", "For shoes, compare toe profile, heel height, panel alignment, sole shape, stitching and obvious glue. For clothing, inspect front and back views, seams, print or embroidery placement, stains, holes and visible measurements. For bags and accessories, check dimensions, hardware color, closures, corners and edge finish. Lighting and perspective can change color and apparent symmetry, so compare several views. A photograph supports only what the camera can show; it does not establish material composition, comfort or durability."],
      ["Request only evidence that could change the decision", "A missing angle is not automatically a defect. Identify the uncertainty and ask for the smallest useful view: a ruler across the chest, the opposite heel, a close-up of a clasp or a complete accessories layout. Save the request and response with the order number. If a platform notice explains a display fault, separate that interface problem from the physical item. Do not accept or reject merely because one image failed to load; wait for decision-critical evidence when it can still affect after-sales action."],
      ["Keep inspection, return and parcel claims separate", "A visible seller mismatch at warehouse intake follows a different evidence path from international transit damage or a missing carrier scan. Check the current seller-backed eligibility and Kakobuy process for the exact order before describing a return as available or free. Do not confuse the site's long warehouse-storage period with the shorter after-sales decision. Preserve original order options, relevant QC views and dated messages, then resolve an open item-level issue before combining the item into an international parcel."],
    ],
    shipping: [
      ["Use the estimator with realistic inputs", "Start with the destination, item category, estimated packed weight and approximate dimensions. The result is a planning snapshot, not the final charge, because the finished carton and eligible lines may differ after warehouse packing. Save the date and the assumptions used. Avoid publishing a permanent price per kilogram or a universal delivery time. Reopen Kakobuy's current estimator before parcel payment, especially when the item classification, destination or parcel size has changed."],
      ["Compare actual and dimension-based billing", "Actual weight is the scale reading of the packed parcel. Some lines can also use a dimension-based calculation that reflects the space occupied by the carton. Read the divisor, rounding rule and threshold shown for the selected live route; do not borrow one from an old guide. Bulky boxes, shoes and padded items can produce a different chargeable result from dense folded clothing even at the same scale weight. Record both measurements when comparing parcel options."],
      ["Compare routes as complete service records", "Review only the lines currently displayed for the exact destination and product classification. Record the line name, billing basis, eligibility limits, tracking information, estimated range, compensation terms and quote date. A headline price or fastest-looking estimate is not enough. Batteries, liquids, magnets, branded goods or oversized packaging may change availability. Dated platform notices can explain a temporary change, but they should not be converted into a permanent promise for every future parcel."],
      ["Recheck the final parcel before payment", "Confirm contents, address, packaging instructions, final weight, dimensions, selected route and declaration details on the submission screen. Keep optional services and destination taxes separate from freight so the cost stack remains understandable. If a number is not shown, mark it unknown instead of filling it from another shipment. Save the parcel snapshot and current official source date. This gives the shipping page a repeatable method without copying the deeper examples used in the long shipping-calculator article."],
    ],
  },
  de: {
    spreadsheet: [
      ["Felder verwenden, die die Kaufentscheidung erhalten", "Eine nützliche Kakobuy-Tabelle speichert Quell-URL, Angebotstitel, Verkäufer, gewählte Variante, Menge, sichtbaren CNY-Preis und Prüfdatum. Farbe und Größe werden genau wie im Angebot notiert, nicht als vereinfachter Spitzname. Ziel ist nicht die größte Linkmenge, sondern genug Kontext, um das Live-Angebot wiederzufinden und die Auswahl zu verstehen. Eine Tabellenzeile beweist weder Echtheit, Qualität noch Zuverlässigkeit des Verkäufers."],
      ["Preissnapshot und Gesamtkosten trennen", "Der Verkäuferpreis ist ein datierter Snapshot. Inlandslieferung, Zahlungsgebühren, optionale Leistungen und internationaler Versand gehören in getrennte Felder. Eine USD-Umrechnung erleichtert Vergleiche, ist aber keine Checkout-Garantie. Wechselkurs und Angebotspreis können sich ändern. Prüfen Sie das Live-Angebot vor der Bestellung erneut und nutzen Sie den aktuellen Kakobuy-Rechner erst mit Ziel, Artikelkategorie und realistischen Paketmaßen. So bleibt die Seite eine Produkttabelle statt einer zweiten Versandkostenanleitung."],
      ["Jede Variante mit den Lagerbelegen verknüpfen", "Speichern Sie die bestellte Variante in derselben Reihenfolge und Bezeichnung wie im Quellangebot. Sobald QC-Ansichten vorliegen, vergleichen Sie Menge, Farbe, Größenetikett, sichtbares Zubehör und Grundform mit diesem Datensatz. Eine fehlende Ansicht ist fehlender Beleg, keine Freigabe. Fordern Sie nur das Maß oder den Blickwinkel an, der die Entscheidung ändern kann. Fotos beweisen weder Material, Haltbarkeit, Komfort noch Echtheit."],
      ["Links pflegen statt eine starre Sammlung zu veröffentlichen", "Ergänzen Sie Prüfdatum und Status wie aktiv, geändert, nicht verfügbar oder ersetzt. Öffnet das Ziel ein anderes Produkt, wird die Route bis zur erneuten Prüfung entfernt. Ersetzen Sie die Quelle nicht still durch ein ähnliches Angebot; Verkäufer, Optionen und Preis können abweichen. Ein Ersatz erhält eine eigene Kontrolle. Dadurch bleibt die Tabelle nachvollziehbar, reduziert tote Links, veraltete Preise und Dubletten und konzentriert sich weiterhin auf überprüfbare Produktdatensätze."],
    ],
    finds: [
      ["Jeden Fund mit einem klaren Bedarf beginnen", "Legen Sie Kategorie, Verwendungszweck, Größenanforderung und Budget fest, bevor Sie Produktkarten öffnen. Ein sinnvoller Fund beantwortet einen konkreten Bedarf und nicht nur einen Hype-Begriff. Das Ziel muss zum beschriebenen Produkt führen, nicht zu einem kopierten Warenkorb oder fremden Agenten. Prüfen Sie, ob Bild, Titel, sichtbare Variante und Ziel weiterhin denselben Artikel zeigen. Bei Abweichungen bleibt der Fund unveröffentlicht, bis die Route erneut geprüft ist."],
      ["Das Live-Ziel statt nur die Karte prüfen", "Eine Karte ist ein datierter redaktioneller Snapshot. Das Quellangebot bestimmt Varianten, Verkäuferpreis und Verfügbarkeit. Öffnen Sie es vor der Bestellung erneut, bestätigen Sie die Auswahl und speichern Sie relevante Größentabellen oder Optionsbilder. Ein alter Screenshot belegt keine aktuelle Verfügbarkeit. Wenn das Ziel umleitet, die Kategorie wechselt oder ein anderes Produkt zeigt, ist die Prüfung fehlgeschlagen, auch wenn das alte Kartenbild attraktiv bleibt."],
      ["Tote und veränderte Links transparent behandeln", "Markieren Sie eine fehlerhafte Route mit Datum und beobachtetem Problem. Leiten Sie die Karte nicht still auf ein nur ähnliches Produkt um, denn Größen, Material, Verkäuferbedingungen und Verpackung können anders sein. Suchen Sie anhand beschreibender Merkmale oder Quellkennungen und bewerten Sie den Ersatz als neuen Kandidaten. Gibt es keinen zuverlässigen Ersatz, bleibt die Kategorie bestehen und nur die fehlerhafte Karte wird entfernt. So entsteht keine erfundene Kontinuität."],
      ["Empfehlungen auf belegbare Aussagen begrenzen", "Ein korrekt zugeordnetes Angebot ist damit noch nicht als sicher, echt oder hochwertig bewiesen. Beschreiben Sie nur beobachtbare Angaben: Kategorie, sichtbares Design, gelistete Optionen, datierter Preis und genaues Ziel. QC-Aussagen gehören zu Lagerbelegen, Versandurteile zur Paketphase. Erfinden Sie keine Verkaufszahlen, Kundenmeinung oder eigene Nutzung. Diese engere Sprache stärkt die Produktsuche, ohne mit QC-, Versand- und Artikelseiten um dieselbe Suchabsicht zu konkurrieren."],
    ],
    guide: [
      ["Vor der Produktzahlung einen Quelldatensatz anlegen", "Öffnen Sie das genaue Marktplatzangebot und speichern Sie URL, Verkäufertitel, Variante, Menge, aktuellen CNY-Preis und Datum. Vergleichen Sie Optionsbilder, wenn übersetzte Namen unklar sind. Der öffentliche Kakobuy-Ablauf trennt Produktbestellung und spätere internationale Paketeinreichung; deshalb bleiben beide Zahlungen und Belege getrennt. Tabellenkarten und Posts helfen bei der Suche, maßgeblich sind vor der Zahlung das Live-Angebot und der aktuelle Bestelldatensatz."],
      ["Händlerversand und Lagereingang unterscheiden", "Ein Status zum Händlerversand beweist nicht, dass das Lager den Artikel erhalten oder geprüft hat. Bewahren Sie die Inlandsreferenz bei der Bestellung auf und warten Sie auf den Lagereintrag. Vergleichen Sie beim Eingang Menge, Farbe oder Größe, sichtbares Zubehör und Zustand mit der Bestellung. Kakobuy beschreibt Grenzen der Sichtprüfung: Fotos beweisen weder Gerätefunktion, Haltbarkeit, Komfort noch Echtheit. Notieren Sie Sichtbares und markieren Sie Unbekanntes ausdrücklich."],
      ["Ein Paket erst mit vollständigem Artikeldatensatz freigeben", "Klären Sie entscheidende Abweichungen vor der internationalen Einreichung. Bestätigen Sie enthaltene Bestellungen, Empfängerdaten, Verpackungsanweisungen, Packmaße und aktuell verfügbare Linien für Ziel und Klassifizierung. Die beworbene Lagerzeit ist nicht die Rückgabefrist des Verkäufers. Verschieben Sie einen offenen After-Sales-Fall deshalb nicht nur wegen verfügbarer Lagerzeit. Die Paketentscheidung folgt dem aktuellen Bestellbeleg und keiner allgemeinen Zeitleiste aus einer anderen Sendung."],
      ["Bei Unklarheit ein kurzes Prüfprotokoll führen", "Speichern Sie Seite, sichtbaren Status, Datum und die zum Problem gehörende Kennung. Für einen Artikel beginnt die Prüfung mit der Bestellnummer, für ein eingereichtes Paket mit der Paketnummer und für Carrier-Ereignisse mit Trackingreferenz und Carrier. Bitten Sie den Support um eine klare Handlung und schwärzen Sie persönliche Daten. Ein kleines Änderungsprotokoll trennt Händler-, Lager-, Plattform- und Carrier-Phasen, ohne spätere Screenshots rückwirkend als frühere Belege darzustellen."],
    ],
    qc: [
      ["Identität vor Verarbeitung prüfen", "Beginnen Sie mit Menge, Farbe, Größenetikett, Variantenname, Zubehör und Grundform. Vergleichen Sie die Lageransicht mit dem gespeicherten Bestelldatensatz, nicht mit Erinnerung oder einem Foto eines anderen Verkäufers. Ist die Identität falsch, dokumentieren Sie diese Abweichung, bevor Sie kleine Verarbeitungsdetails prüfen. Verwenden Sie beobachtbare Angaben zu Stelle, Farbe und Maß statt pauschaler Wörter wie perfekt, schlecht oder garantiert echt."],
      ["Sichtbare Verarbeitung je Kategorie prüfen", "Bei Schuhen zählen Zehenprofil, Absatzhöhe, Paneelausrichtung, Sohlenform, Nähte und auffälliger Kleber. Bei Kleidung prüfen Sie Vorder- und Rückseite, Nähte, Druck oder Stickerei, Flecken, Löcher und sichtbare Maße. Bei Taschen und Accessoires zählen Maße, Metallfarbe, Verschlüsse, Ecken und Kanten. Licht und Perspektive verändern Farbe und Symmetrie. Fotos belegen nur Sichtbares, nicht Materialzusammensetzung, Komfort oder Haltbarkeit."],
      ["Nur entscheidungsrelevante Belege anfordern", "Ein fehlender Winkel ist nicht automatisch ein Defekt. Benennen Sie die Unsicherheit und fordern Sie die kleinste nützliche Ansicht an: Brustmaß mit Lineal, gegenüberliegende Ferse, Verschlussdetail oder vollständiges Zubehör. Speichern Sie Anfrage und Antwort bei der Bestellnummer. Erklärt ein Plattformhinweis einen Anzeigefehler, trennen Sie Oberfläche und physischen Artikel. Ein nicht geladenes Bild ist weder Annahme noch Ablehnung; warten Sie auf Belege, solange sie die Entscheidung noch ändern können."],
      ["Prüfung, Rückgabe und Paketanspruch trennen", "Eine sichtbare Händlerabweichung im Lager folgt einem anderen Weg als internationaler Transportschaden oder fehlender Carrier-Scan. Prüfen Sie die aktuelle Verkäuferberechtigung und den Kakobuy-Prozess der konkreten Bestellung, bevor Sie eine Rückgabe als möglich oder kostenlos bezeichnen. Verwechseln Sie die lange Lagerzeit nicht mit der kürzeren After-Sales-Frist. Bewahren Sie Optionen, relevante QC-Ansichten und datierte Nachrichten auf und lösen Sie den Artikelfall vor der internationalen Paketeinreichung."],
    ],
    shipping: [
      ["Den Rechner mit realistischen Eingaben nutzen", "Beginnen Sie mit Ziel, Artikelkategorie, geschätztem Packgewicht und ungefähren Maßen. Das Ergebnis ist ein Planungssnapshot, keine Endrechnung, weil fertiger Karton und zulässige Linien nach dem Packen abweichen können. Speichern Sie Datum und Annahmen. Veröffentlichen Sie keinen dauerhaften Kilopreis oder universelle Laufzeit. Öffnen Sie den aktuellen Kakobuy-Rechner vor der Paketzahlung erneut, besonders nach Änderungen bei Klassifizierung, Ziel oder Paketgröße."],
      ["Istgewicht und maßbasierte Abrechnung vergleichen", "Das Istgewicht ist der Waagenwert des gepackten Pakets. Manche Linien berücksichtigen zusätzlich den Raum des Kartons. Lesen Sie Divisor, Rundungsregel und Schwelle der aktuell gewählten Linie und übernehmen Sie nichts aus einem alten Leitfaden. Sperrige Kartons, Schuhe und gepolsterte Waren können bei gleichem Waagengewicht anders abgerechnet werden als dichte Kleidung. Speichern Sie Gewicht und Maße gemeinsam, wenn Sie Paketvarianten vergleichen."],
      ["Linien als vollständige Leistungsdatensätze vergleichen", "Vergleichen Sie nur Linien, die für das konkrete Ziel und die Produktklassifizierung angezeigt werden. Notieren Sie Namen, Abrechnungsbasis, Grenzen, Tracking, Schätzbereich, Ausgleichsbedingungen und Angebotsdatum. Preis oder kürzeste Zeit allein reichen nicht. Batterien, Flüssigkeiten, Magnete, Markenware oder große Verpackung können die Auswahl ändern. Datierte Plattformhinweise erklären vorübergehende Änderungen, sind aber kein dauerhaftes Versprechen für zukünftige Pakete."],
      ["Das fertige Paket vor der Zahlung erneut prüfen", "Bestätigen Sie Inhalt, Adresse, Verpackungsanweisungen, Endgewicht, Maße, Linie und Deklaration auf der Einreichungsseite. Optionale Leistungen und Zielsteuern bleiben getrennt von der Fracht, damit der Kostenaufbau verständlich ist. Fehlt ein Wert, wird er als unbekannt markiert statt aus einer anderen Sendung übernommen. Speichern Sie Paketsnapshot und Prüfdatum. So bietet die Seite eine wiederholbare Methode, ohne die ausführlichen Beispiele des langen Rechnerartikels zu kopieren."],
    ],
  },
  es: {
    spreadsheet: [
      ["Usa campos que conserven la decisión de compra", "Una hoja útil de Kakobuy registra URL fuente, título, vendedor, opción elegida, cantidad, precio CNY visible y fecha de revisión. Guarda color y talla exactamente como aparecen, no como un apodo simplificado. El objetivo no es reunir más enlaces, sino conservar el contexto necesario para volver a la ficha y entender la elección. Una fila no demuestra autenticidad, calidad ni fiabilidad del vendedor por el simple hecho de estar en el catálogo."],
      ["Separa la captura de precio del coste final", "Guarda el precio del vendedor como captura fechada y separa envío nacional, cargos de pago, servicios opcionales y transporte internacional. La conversión a USD ayuda a comparar, pero no garantiza el checkout. Tipo de cambio y precio pueden variar. Revisa la ficha antes del pedido y usa el estimador vigente de Kakobuy con destino, categoría y medidas realistas. Así la página sigue siendo de descubrimiento y no compite con una guía completa de costes."],
      ["Relaciona cada opción con la evidencia del almacén", "Conserva la variante con el mismo texto y orden de la ficha fuente. Cuando aparezcan las vistas QC, compara cantidad, color, etiqueta de talla, accesorios visibles y forma general con el registro. Una vista ausente es evidencia ausente, no aprobación. Solicita solo la medida o el ángulo que pueda cambiar la decisión. La hoja conecta el hallazgo con el almacén sin afirmar que una foto demuestra material, durabilidad, comodidad o autenticidad."],
      ["Mantén los enlaces en lugar de publicar una lista congelada", "Añade fecha de revisión y estado: activo, cambiado, no disponible o sustituido. Si el destino muestra otro producto, retira la ruta hasta verificarla. No cambies silenciosamente la fuente por una ficha parecida; vendedor, opciones y precio pueden diferir. Una sustitución requiere su propia revisión. Esta regla reduce enlaces muertos, precios antiguos y duplicados, y mantiene la intención centrada en registros de producto comprobables."],
    ],
    finds: [
      ["Empieza cada hallazgo con una necesidad clara", "Define categoría, uso, talla y presupuesto antes de abrir tarjetas. Un hallazgo útil responde a una necesidad, no a una etiqueta de moda sin explicación. El resultado debe llevar al producto exacto, no a un carrito copiado ni a otro agente. Comprueba que imagen, título, opción visible y destino siguen describiendo el mismo artículo. Si no coinciden, no publiques el hallazgo hasta revisar de nuevo la ruta."],
      ["Verifica el destino en vivo, no solo la tarjeta", "Una tarjeta es una captura editorial fechada. La ficha fuente controla variantes, precio y stock. Ábrela antes de pedir, confirma la opción y guarda la tabla de tallas o imagen relevante. Una captura antigua no prueba que el anuncio siga activo. Si el destino redirige, cambia de categoría o muestra otro producto, la verificación ha fallado aunque la imagen antigua continúe siendo atractiva."],
      ["Gestiona enlaces muertos y cambiados con transparencia", "Marca la ruta fallida con fecha y problema observado. No redirijas en silencio a un producto solo parecido: talla, material, condiciones y embalaje pueden cambiar. Busca por atributos descriptivos o identificadores de origen y evalúa el reemplazo como candidato independiente. Si no existe uno fiable, conserva la categoría y retira solo la tarjeta rota. Así no se inventa una continuidad que las fuentes no sostienen."],
      ["Limita la recomendación a lo que demuestra la evidencia", "Una ficha bien asignada no queda probada como segura, auténtica o de alta calidad. Describe datos observables: categoría, diseño visible, opciones, precio fechado y destino exacto. Reserva los juicios QC para la evidencia del almacén y el envío para la fase del paquete. No inventes ventas, consenso de clientes ni experiencia propia. Este lenguaje ayuda a la búsqueda de productos sin solapar las páginas de QC, envío y artículos."],
    ],
    guide: [
      ["Crea un registro fuente antes del pago", "Abre la ficha exacta y guarda URL, título del vendedor, variante, cantidad, precio CNY y fecha. Compara miniaturas cuando la traducción de opciones resulte ambigua. El flujo público de Kakobuy separa pedido del producto y presentación posterior del paquete internacional; conserva ambos pagos y pruebas por separado. Una hoja o publicación ayuda a descubrir, pero la ficha viva y el pedido actual son los registros que deben confirmarse antes de pagar."],
      ["Distingue envío del vendedor y entrada en almacén", "Que el vendedor haya enviado no demuestra que el almacén haya recibido o inspeccionado. Conserva la referencia nacional y espera el registro de entrada. Compara cantidad, color o talla, accesorios y estado con el pedido. La información pública de Kakobuy limita la inspección a lo visible; las fotos no prueban funcionamiento, duración, comodidad o autenticidad. Anota lo que aparece y marca expresamente lo que sigue desconocido."],
      ["Libera el paquete solo con el registro completo", "Resuelve diferencias decisivas antes del envío internacional. Confirma pedidos incluidos, destinatario, instrucciones, medidas embaladas y rutas disponibles para destino y clasificación. El almacenamiento anunciado no equivale al plazo de devolución del vendedor; no retrases una incidencia posventa porque aún quede almacenamiento. La decisión del paquete debe seguir la evidencia actual del pedido, no una cronología genérica copiada de otro envío."],
      ["Usa un historial breve cuando algo no esté claro", "Guarda página, estado visible, fecha e identificador relacionado. Para un artículo empieza por el pedido; para un paquete presentado añade el número de paquete; para eventos de transporte usa seguimiento y transportista. Pide al soporte una acción concreta y oculta datos personales. Un historial pequeño impide que capturas posteriores sustituyan observaciones anteriores y separa vendedor, almacén, plataforma y transportista sin adivinar."],
    ],
    qc: [
      ["Comprueba identidad antes que acabado", "Empieza por cantidad, color, etiqueta de talla, variante, accesorios y forma general. Compara la vista del almacén con el pedido guardado, no con la memoria ni con la foto de otro vendedor. Si la identidad es incorrecta, documenta la diferencia antes de estudiar detalles menores. Usa lenguaje observable sobre ubicación, color y medida en lugar de expresiones generales como perfecto, malo o auténtico garantizado."],
      ["Revisa la construcción visible por categoría", "En calzado compara puntera, altura del talón, paneles, suela, costuras y pegamento evidente. En ropa revisa frente, espalda, costuras, impresión o bordado, manchas, agujeros y medidas visibles. En bolsas y accesorios, dimensiones, color de herrajes, cierres, esquinas y bordes. Luz y perspectiva cambian color y simetría. Una foto solo prueba lo visible, no composición, comodidad o durabilidad."],
      ["Solicita solo evidencia que pueda cambiar la decisión", "Un ángulo ausente no es automáticamente un defecto. Define la duda y pide la vista mínima útil: regla en el pecho, talón opuesto, detalle del cierre o accesorios completos. Guarda solicitud y respuesta con el pedido. Si un aviso explica un fallo de pantalla, separa la interfaz del artículo físico. Una imagen que no carga no significa aceptar ni rechazar; espera la evidencia decisiva mientras aún pueda afectar la posventa."],
      ["Separa inspección, devolución y reclamación de paquete", "Una diferencia visible del vendedor en almacén sigue un camino distinto al daño internacional o a un escaneo ausente. Revisa elegibilidad del vendedor y proceso Kakobuy del pedido antes de decir que una devolución existe o es gratuita. No confundas almacenamiento largo con posventa más corta. Conserva opciones, vistas QC y mensajes fechados, y resuelve la incidencia del artículo antes de incluirlo en el paquete internacional."],
    ],
    shipping: [
      ["Usa el estimador con datos realistas", "Empieza con destino, categoría, peso embalado estimado y dimensiones aproximadas. El resultado es una captura de planificación, no el cargo final, porque caja y rutas pueden variar tras el embalaje. Guarda fecha y supuestos. No publiques un precio permanente por kilo ni un plazo universal. Reabre el estimador actual de Kakobuy antes de pagar, sobre todo si cambian clasificación, destino o tamaño."],
      ["Compara peso real y facturación dimensional", "El peso real es la lectura de la báscula. Algunas líneas consideran también el espacio de la caja. Lee divisor, redondeo y umbral de la ruta seleccionada y no los copies de una guía antigua. Cajas voluminosas, zapatos y artículos acolchados pueden facturarse de forma distinta a ropa densa con el mismo peso. Registra peso y medidas juntos al comparar opciones de paquete."],
      ["Compara rutas como registros completos", "Revisa solo las líneas mostradas para el destino y la clasificación concretos. Guarda nombre, base de cobro, límites, seguimiento, intervalo estimado, compensación y fecha. Precio o plazo más corto no bastan. Baterías, líquidos, imanes, marcas o embalajes grandes pueden cambiar disponibilidad. Un aviso fechado explica cambios temporales, pero no crea una promesa permanente para futuros paquetes."],
      ["Vuelve a revisar el paquete final antes del pago", "Confirma contenido, dirección, instrucciones, peso, medidas, ruta y declaración en la pantalla de presentación. Mantén servicios opcionales e impuestos del destino separados del flete. Si falta un dato, márcalo desconocido en vez de copiarlo de otro envío. Guarda la captura y la fecha oficial. Así la página ofrece un método repetible sin duplicar los ejemplos profundos del artículo largo sobre la calculadora."],
    ],
  },
  fr: {
    spreadsheet: [
      ["Utiliser des champs qui conservent la décision", "Un tableur Kakobuy utile enregistre URL source, titre, vendeur, variante, quantité, prix CNY visible et date de contrôle. Gardez couleur et taille exactement comme sur la fiche. Le but n'est pas d'accumuler les liens, mais de conserver assez de contexte pour rouvrir l'offre et comprendre le choix. Une ligne ne prouve ni authenticité, qualité ou fiabilité du vendeur simplement parce qu'elle figure dans le catalogue."],
      ["Séparer l'instantané de prix du coût final", "Le prix vendeur reste un instantané daté. Livraison locale, frais de paiement, services facultatifs et transport international occupent des champs distincts. La conversion USD aide à comparer sans garantir le paiement. Taux et prix évoluent. Revérifiez la fiche avant de commander et utilisez l'estimateur Kakobuy actuel avec destination, catégorie et mesures réalistes. La page reste ainsi consacrée à la découverte plutôt qu'à une seconde analyse complète des frais."],
      ["Relier chaque option aux preuves d'entrepôt", "Conservez la variante avec le même libellé et le même ordre que la source. À l'arrivée des vues QC, comparez quantité, couleur, étiquette de taille, accessoires visibles et forme générale au dossier. Une vue absente est une preuve manquante, pas une validation. Demandez seulement la mesure ou l'angle susceptible de changer la décision. Le tableur relie découverte et entrepôt sans prétendre qu'une photo prouve matière, durée, confort ou authenticité."],
      ["Entretenir les liens plutôt que publier une liste figée", "Ajoutez une date et un état : actif, modifié, indisponible ou remplacé. Si la destination affiche un autre produit, retirez la route jusqu'à nouvelle vérification. Ne remplacez pas silencieusement la source par une offre similaire ; vendeur, options et prix peuvent différer. Un remplacement mérite son propre contrôle. Cette règle réduit liens morts, prix anciens et doublons tout en maintenant une intention centrée sur des dossiers produits vérifiables."],
    ],
    finds: [
      ["Commencer chaque sélection par un besoin clair", "Définissez catégorie, usage, taille et budget avant d'ouvrir les cartes. Une bonne sélection répond à un besoin, pas à une étiquette de mode inexpliquée. Le résultat doit mener au produit exact, non à un panier copié ou à un autre agent. Vérifiez que l'image, le titre, l'option visible et la destination décrivent toujours le même article. Sinon, gardez la sélection hors ligne jusqu'au nouveau contrôle."],
      ["Vérifier la destination en direct, pas seulement la carte", "Une carte est un instantané éditorial daté. La fiche source commande variantes, prix vendeur et stock. Rouvrez-la avant de commander, confirmez l'option et gardez le guide des tailles ou l'image utile. Une ancienne capture ne prouve pas la disponibilité actuelle. Si la destination redirige, change de catégorie ou montre un autre produit, la vérification échoue même si l'ancienne image reste séduisante."],
      ["Traiter clairement les liens morts ou modifiés", "Marquez la route défaillante avec date et problème observé. Ne redirigez pas silencieusement vers un produit seulement similaire : taille, matière, conditions et emballage peuvent varier. Cherchez avec des attributs descriptifs ou des identifiants source, puis évaluez le remplacement comme nouveau candidat. Sans remplacement fiable, conservez la catégorie et retirez seulement la carte cassée. Vous n'inventez ainsi aucune continuité non prouvée."],
      ["Limiter la recommandation aux preuves disponibles", "Une offre correctement reliée n'est pas pour autant prouvée sûre, authentique ou haut de gamme. Décrivez seulement catégorie, design visible, options, prix daté et destination exacte. Réservez les jugements QC aux preuves d'entrepôt et le transport à la phase colis. N'inventez ni ventes, consensus client ou expérience personnelle. Cette formulation sert la découverte sans concurrencer les pages QC, livraison et articles."],
    ],
    guide: [
      ["Créer un dossier source avant de payer", "Ouvrez la fiche exacte et gardez URL, titre vendeur, variante, quantité, prix CNY et date. Comparez les miniatures lorsque les options traduites sont ambiguës. Le parcours public Kakobuy sépare commande produit et soumission ultérieure du colis international ; conservez paiements et preuves séparés. Un tableur aide à découvrir, mais la fiche en direct et la commande actuelle sont les dossiers à confirmer avant tout paiement."],
      ["Distinguer envoi vendeur et réception en entrepôt", "Un statut d'envoi vendeur ne prouve pas la réception ou le contrôle. Conservez la référence locale et attendez le dossier d'entrée. Comparez quantité, couleur ou taille, accessoires et état avec la commande. Les informations publiques Kakobuy limitent l'inspection au visible ; les photos ne prouvent fonctionnement, durée, confort ou authenticité. Notez ce qui apparaît et marquez clairement ce qui reste inconnu."],
      ["Valider le colis seulement avec un dossier complet", "Résolvez les écarts décisifs avant l'expédition internationale. Confirmez commandes incluses, destinataire, instructions, mesures emballées et lignes disponibles pour la destination et la catégorie. Le stockage annoncé n'est pas le délai de retour vendeur ; ne reportez pas un dossier après-vente parce que du stockage reste disponible. La décision colis suit les preuves de la commande actuelle, non une chronologie générique copiée d'un autre envoi."],
      ["Garder un court journal lorsque la situation est floue", "Conservez page, statut visible, date et identifiant concerné. Pour un article, commencez par la commande ; pour un colis soumis, ajoutez le numéro de colis ; pour le transport, utilisez suivi et transporteur affichés. Demandez au support une action précise et masquez les données personnelles. Un petit journal empêche les captures tardives de remplacer les observations antérieures et sépare vendeur, entrepôt, plateforme et transporteur sans supposition."],
    ],
    qc: [
      ["Contrôler l'identité avant la finition", "Commencez par quantité, couleur, étiquette de taille, variante, accessoires et forme générale. Comparez la vue d'entrepôt au dossier de commande, non à votre mémoire ou à la photo d'un autre vendeur. Si l'identité est fausse, documentez l'écart avant les petits détails. Employez des termes observables sur l'emplacement, la couleur et la mesure plutôt que parfait, mauvais ou authenticité garantie."],
      ["Examiner la construction visible par catégorie", "Pour les chaussures, comparez forme avant, talon, panneaux, semelle, coutures et colle évidente. Pour les vêtements, inspectez avant, dos, coutures, impression ou broderie, taches, trous et mesures visibles. Pour sacs et accessoires, vérifiez dimensions, métal, fermetures, coins et bords. Lumière et perspective modifient couleur et symétrie. Une photo prouve le visible, jamais composition, confort ou durée."],
      ["Demander uniquement la preuve qui peut changer la décision", "Un angle absent n'est pas automatiquement un défaut. Définissez l'incertitude et demandez la vue minimale : règle sur la poitrine, talon opposé, détail de fermeture ou accessoires complets. Gardez demande et réponse avec la commande. Si un avis explique une panne d'affichage, séparez interface et article physique. Une image non chargée n'impose ni acceptation ni refus ; attendez la preuve décisive tant qu'elle peut encore modifier l'après-vente."],
      ["Séparer inspection, retour et réclamation colis", "Un écart vendeur visible en entrepôt suit un autre parcours qu'un dommage international ou un scan absent. Vérifiez l'éligibilité vendeur et le processus Kakobuy de la commande avant d'annoncer un retour possible ou gratuit. Ne confondez pas stockage long et après-vente plus court. Gardez options, vues QC et messages datés, puis résolvez le problème de l'article avant de l'intégrer au colis international."],
    ],
    shipping: [
      ["Utiliser l'estimateur avec des données réalistes", "Commencez avec destination, catégorie, poids emballé estimé et dimensions approximatives. Le résultat est un instantané de planification, non le prix final, car carton et lignes peuvent changer après emballage. Gardez date et hypothèses. Ne publiez ni tarif permanent au kilo ni délai universel. Rouvrez l'estimateur Kakobuy avant paiement, surtout après changement de classification, destination ou taille."],
      ["Comparer poids réel et facturation dimensionnelle", "Le poids réel est la mesure de la balance. Certaines lignes utilisent aussi l'espace occupé par le carton. Lisez diviseur, arrondi et seuil de la ligne actuelle ; ne les copiez pas d'un ancien guide. Cartons volumineux, chaussures et produits rembourrés peuvent être facturés différemment de vêtements denses au même poids. Conservez poids et dimensions ensemble lorsque vous comparez des colis."],
      ["Comparer les lignes comme dossiers de service complets", "Étudiez seulement les lignes affichées pour la destination et la classification exactes. Gardez nom, base de calcul, limites, suivi, plage estimée, compensation et date. Prix ou délai le plus court ne suffisent pas. Batteries, liquides, aimants, marques ou gros emballage changent parfois l'offre. Un avis daté explique un changement temporaire sans créer de promesse permanente pour tous les futurs colis."],
      ["Revérifier le colis final avant paiement", "Confirmez contenu, adresse, instructions, poids, dimensions, ligne et déclaration sur l'écran de soumission. Séparez services facultatifs et taxes de destination du fret. Si une valeur manque, notez inconnue au lieu de la copier d'un autre envoi. Gardez l'instantané et la date de la source officielle. La page offre ainsi une méthode répétable sans dupliquer les exemples approfondis de l'article long sur le calculateur."],
    ],
  },
  it: {
    spreadsheet: [
      ["Usare campi che conservano la decisione", "Un foglio Kakobuy utile registra URL fonte, titolo, venditore, variante, quantità, prezzo CNY visibile e data. Salva colore e taglia esattamente come nella scheda, non con nomi semplificati. L'obiettivo non è raccogliere più link, ma conservare il contesto necessario per riaprire l'offerta e capire la scelta. Una riga non prova autenticità, qualità o affidabilità del venditore solo perché compare nel catalogo."],
      ["Separare l'istantanea del prezzo dal costo finale", "Il prezzo del venditore è un'istantanea datata. Consegna nazionale, costi di pagamento, servizi opzionali e trasporto internazionale restano separati. La conversione USD aiuta il confronto, non garantisce il checkout. Cambio e prezzo possono variare. Ricontrolla la scheda prima dell'ordine e usa lo stimatore Kakobuy con destinazione, categoria e misure realistiche. Così la pagina resta dedicata alla scoperta senza duplicare una guida completa ai costi."],
      ["Collegare ogni opzione alle prove di magazzino", "Conserva la variante con lo stesso testo e ordine della fonte. Quando compaiono le viste QC, confronta quantità, colore, etichetta taglia, accessori e forma con il record. Una vista assente è una prova mancante, non un'approvazione. Chiedi solo misura o angolo capaci di cambiare la decisione. Il foglio collega scoperta e magazzino senza sostenere che una foto dimostri materiale, durata, comfort o autenticità."],
      ["Mantenere i link invece di pubblicare un elenco congelato", "Aggiungi data e stato: attivo, cambiato, non disponibile o sostituito. Se la destinazione mostra un altro prodotto, rimuovi la rotta fino a nuova verifica. Non cambiare silenziosamente la fonte con una scheda simile; venditore, opzioni e prezzo possono differire. Un sostituto richiede un controllo autonomo. Questa regola riduce link morti, prezzi vecchi e duplicati mantenendo l'intento su record verificabili."],
    ],
    finds: [
      ["Iniziare ogni prodotto da un'esigenza chiara", "Definisci categoria, uso, taglia e budget prima di aprire le schede. Un risultato utile risponde a un bisogno, non a una moda senza spiegazione. Deve portare al prodotto esatto, non a un carrello copiato o a un altro agente. Controlla che immagine, titolo, opzione e destinazione descrivano ancora lo stesso articolo. Se non coincidono, non pubblicare finché la rotta non viene verificata di nuovo."],
      ["Verificare la destinazione live, non solo la scheda", "Una scheda è un'istantanea editoriale datata. La fonte controlla varianti, prezzo e disponibilità. Riaprila prima dell'ordine, conferma l'opzione e salva tabella taglie o immagine utile. Una vecchia schermata non prova che l'offerta esista ancora. Se il destino reindirizza, cambia categoria o mostra un altro prodotto, la verifica fallisce anche quando la vecchia immagine rimane attraente."],
      ["Gestire con trasparenza link morti e modificati", "Segna la rotta fallita con data e problema. Non reindirizzare in silenzio a un prodotto solo simile: taglia, materiale, condizioni e imballaggio possono variare. Cerca tramite attributi descrittivi o identificatori fonte e valuta il sostituto come nuovo candidato. Se non esiste un'alternativa affidabile, conserva la categoria e rimuovi soltanto la scheda rotta. In questo modo non inventi continuità che le fonti non dimostrano."],
      ["Limitare la raccomandazione a ciò che è dimostrabile", "Una scheda correttamente collegata non è automaticamente sicura, autentica o di alta qualità. Descrivi dati osservabili: categoria, design visibile, opzioni, prezzo datato e destinazione esatta. Riserva i giudizi QC alle prove di magazzino e quelli di spedizione alla fase pacco. Non inventare vendite, consenso clienti o esperienza personale. Questo linguaggio serve la ricerca prodotti senza sovrapporre QC, spedizione e articoli."],
    ],
    guide: [
      ["Creare un record fonte prima del pagamento", "Apri la scheda esatta e salva URL, titolo venditore, variante, quantità, prezzo CNY e data. Confronta le miniature se la traduzione delle opzioni è ambigua. Il flusso pubblico Kakobuy separa ordine prodotto e successivo invio del pacco internazionale; conserva pagamenti e prove separati. Un foglio aiuta a scoprire, ma la scheda live e l'ordine attuale sono i record da verificare prima di pagare."],
      ["Distinguere invio del venditore e ingresso in magazzino", "Lo stato di invio del venditore non prova ricezione o ispezione. Conserva il riferimento nazionale e attendi il record di ingresso. Confronta quantità, colore o taglia, accessori e stato con l'ordine. Le informazioni pubbliche Kakobuy limitano l'ispezione a ciò che è visibile; le foto non provano funzionamento, durata, comfort o autenticità. Registra ciò che appare e marca chiaramente ciò che rimane sconosciuto."],
      ["Svincolare il pacco solo con il record completo", "Risolvi le differenze decisive prima della spedizione internazionale. Conferma ordini inclusi, destinatario, istruzioni, misure imballate e linee disponibili per destinazione e classificazione. Il deposito pubblicizzato non equivale alla finestra di reso del venditore; non ritardare un caso post-vendita perché resta spazio di deposito. La decisione sul pacco segue le prove dell'ordine attuale, non una cronologia generica copiata da un'altra spedizione."],
      ["Usare un breve registro quando qualcosa non è chiaro", "Salva pagina, stato visibile, data e identificatore relativo al problema. Per un articolo inizia dall'ordine; per un pacco presentato aggiungi il numero pacco; per gli eventi di trasporto usa tracking e corriere mostrati. Chiedi al supporto un'azione chiara e oscura i dati personali. Un piccolo registro separa venditore, magazzino, piattaforma e corriere senza trasformare schermate successive in prove precedenti."],
    ],
    qc: [
      ["Controllare l'identità prima della lavorazione", "Inizia da quantità, colore, etichetta taglia, variante, accessori e forma. Confronta la vista di magazzino con l'ordine salvato, non con memoria o foto di un altro venditore. Se l'identità è errata, documenta la differenza prima dei piccoli dettagli. Usa termini osservabili su posizione, colore e misura invece di parole generiche come perfetto, cattivo o autenticità garantita."],
      ["Rivedere la costruzione visibile per categoria", "Per le scarpe confronta punta, tallone, pannelli, suola, cuciture e colla evidente. Per i capi esamina fronte, retro, cuciture, stampa o ricamo, macchie, fori e misure visibili. Per borse e accessori controlla dimensioni, metallo, chiusure, angoli e bordi. Luce e prospettiva cambiano colore e simmetria. Una foto prova solo il visibile, non composizione, comfort o durata."],
      ["Richiedere solo prove che possano cambiare la decisione", "Un angolo assente non è automaticamente un difetto. Definisci l'incertezza e chiedi la vista minima: righello sul torace, tallone opposto, dettaglio chiusura o accessori completi. Salva domanda e risposta con l'ordine. Se un avviso spiega un problema di visualizzazione, separa interfaccia e articolo fisico. Un'immagine che non carica non impone accettazione o rifiuto; attendi la prova decisiva finché può influire sul post-vendita."],
      ["Separare ispezione, reso e reclamo del pacco", "Una differenza del venditore visibile in magazzino segue un percorso diverso dal danno internazionale o da una scansione assente. Controlla idoneità del venditore e processo Kakobuy dell'ordine prima di definire un reso disponibile o gratuito. Non confondere il deposito lungo con una finestra post-vendita più breve. Conserva opzioni, viste QC e messaggi datati, quindi risolvi il problema dell'articolo prima di inserirlo nel pacco internazionale."],
    ],
    shipping: [
      ["Usare lo stimatore con dati realistici", "Inizia con destinazione, categoria, peso imballato stimato e dimensioni approssimative. Il risultato è un'istantanea di pianificazione, non il costo finale, perché scatola e linee possono cambiare dopo l'imballaggio. Salva data e ipotesi. Non pubblicare un prezzo fisso al chilo o un tempo universale. Riapri lo stimatore Kakobuy prima del pagamento, soprattutto dopo cambi di classificazione, destinazione o dimensione."],
      ["Confrontare peso reale e calcolo dimensionale", "Il peso reale è la lettura della bilancia. Alcune linee considerano anche lo spazio della scatola. Leggi divisore, arrotondamento e soglia della rotta corrente e non copiarli da una vecchia guida. Scatole voluminose, scarpe e articoli imbottiti possono produrre un addebito diverso da vestiti densi allo stesso peso. Registra insieme peso e misure quando confronti le opzioni del pacco."],
      ["Confrontare le linee come record completi", "Valuta soltanto le linee mostrate per destinazione e classificazione esatte. Salva nome, base di calcolo, limiti, tracking, intervallo stimato, compensazione e data. Prezzo o tempo più breve non bastano. Batterie, liquidi, magneti, marchi o imballaggi grandi possono modificare la disponibilità. Un avviso datato spiega un cambiamento temporaneo, ma non crea una promessa permanente per pacchi futuri."],
      ["Ricontrollare il pacco finale prima del pagamento", "Conferma contenuto, indirizzo, istruzioni, peso, misure, linea e dichiarazione nella schermata di invio. Mantieni servizi opzionali e tasse di destinazione separati dal trasporto. Se manca un valore, segnalo come sconosciuto invece di copiarlo da un'altra spedizione. Salva l'istantanea e la data ufficiale. Così la pagina offre un metodo ripetibile senza duplicare gli esempi approfonditi dell'articolo lungo sul calcolatore."],
    ],
  },
};
