import type { Locale } from "./site-data";
import type { IdentifierArticle } from "./order-identifiers-article";

const sources = [
  {label:"Kakobuy official homepage and public service flow",url:"https://www.kakobuy.com/"},
  {label:"Kakobuy official purchasing-flow information",url:"https://www.kakobuy.com/index/information?information_id=12"},
  {label:"Kakobuy official service terms",url:"https://www.kakobuy.com/index/information?information_id=15"},
];

export const domesticReceiptArticleData:Record<Locale,IdentifierArticle>={
  en:{title:"Kakobuy Seller Sent vs Warehouse Received: Record the Domestic Delivery Leg",tag:"Parcel records & workflow control",read:"15 min operations guide",reviewed:"Official sources reviewed 10 Sep 2026",lede:"Seller sent and warehouse received are different checkpoints. Build a dated domestic-delivery record that shows what left the seller, which reference moved, what the warehouse acknowledged and what remains unknown.",sources,sections:[
    ["Define the domestic leg without inventing an arrival",["For this record, the domestic leg begins when credible evidence links the correct seller shipment to movement toward Kakobuy's warehouse. It ends when a warehouse-facing record acknowledges receipt of the relevant package or item. Kakobuy's public buying flow places seller dispatch before warehouse inspection and later parcel submission, but the exact wording, page layout and intermediate carrier events may change. Save the live labels rather than replacing them with a remembered sequence. Seller sent is evidence of a seller-side or account-side state; warehouse received is a later event. Neither label by itself proves that every expected item, quantity or accessory is present. Define the two boundaries before opening the account so a new tracking number, delivery scan or warehouse card does not get stretched into a claim it cannot support." ]],
    ["Start with an item-to-package map",["Create one row for every ordered item and variant. Record the Kakobuy order label, a redacted order reference, source listing description, selected option, quantity and the seller package or domestic tracking reference when shown. If the seller combines several items, link each item row to the shared package reference without deleting the separate item identities. If the seller splits an order, create a new package row for each reference and mark which items are expected inside. A map is stronger than a single tracking cell because it preserves one-to-many and many-to-one relationships. Use neutral aliases in any shared example, such as ORDER-A, ITEM-2 and DOMESTIC-PACKAGE-1. Full identifiers, account links, phone numbers and address data belong only in the private working record." ]],
    ["Treat a tracking number as a reference, not movement",["Record the time a domestic reference first appears separately from the first carrier event. A number can exist before a carrier accepts the package, and a seller statement can precede a physical scan. For every check, save the source page, displayed wording, event time if shown, location if shown and your checked-at time. Classify the observation as reference displayed, carrier acceptance evidenced, carrier movement evidenced, delivery scan displayed or warehouse receipt evidenced. These are editorial evidence labels, not official Kakobuy status names. If a carrier page cannot recognize the number, record that result instead of calling the shipment lost. If the account later replaces the reference, append the new mapping and retain the old one as unresolved or superseded only when the evidence supports that conclusion." ]],
    ["Separate carrier delivery from warehouse intake",["A domestic carrier event translated as delivered may indicate arrival at a receiving point, but it does not automatically establish completed item intake. The warehouse may still need to associate the package with an order, open or sort it, count contents and create a visible record. Conversely, a warehouse item card can appear even when the public carrier trail is incomplete. Preserve both sources and their timestamps. Write carrier delivery displayed at 14:10 and warehouse receipt first observed at 18:40 rather than claiming a four-and-a-half-hour processing standard. One case cannot establish a universal Kakobuy intake time. The useful fact is the observed gap and whether the correct item mapping eventually closed it. Do not convert the gap into delay unless a current account instruction or dated official rule supplies a relevant deadline." ]],
    ["Use a minimum domestic-delivery table",["Recommended fields are item alias, exact variant, expected quantity, order-reference label, seller-package label, redacted domestic reference, first-reference time, latest carrier event, carrier event time and zone, delivery location wording, warehouse-receipt wording, first warehouse observation, evidence filename, confidence, discrepancy and next check. Keep unknown as a legitimate value. Do not enter the current time into a missing event field just to complete the row. Preserve the displayed time zone; if none appears, store the time exactly as shown and mark the zone unknown. The confidence field should describe the mapping: unlinked reference, item-to-package mapping claimed, movement evidenced, carrier delivery displayed or warehouse receipt matched. It is not a rating of the seller, carrier or platform.","Make the table append-only. When a status changes, add a new observation with its own checked-at time instead of replacing the earlier text. Keep screenshots or exports under filenames that identify the item alias, source and observation date without exposing the full order number. A simple pattern such as ITEM-2_account_2026-09-10 keeps the evidence sortable. If you correct a mistaken mapping, retain the original row, label it corrected and link to the replacement. This preserves why an earlier decision looked reasonable at the time. Calculate elapsed time only between two events that each have reliable timestamps; never substitute screenshot creation time for the event time. An auditable table should let another reviewer reproduce the conclusion from the stored sources rather than trust the latest cell color." ]],
    ["Reconcile split, combined and partial arrivals",["When one domestic package is expected to contain several items, warehouse receipt of one item does not prove the package was complete. Mark each item matched, not yet visible or unexpected. When several packages arrive together, do not attach every warehouse item to the first delivered reference; use labels, dates and any visible mapping. A partial intake can be a normal intermediate state or a real discrepancy, and the record should distinguish those possibilities without choosing one prematurely. Append observations instead of overwriting them. If an item appears under a different order or package reference, save the exact screen context and ask a narrow mapping question. This article stops at receipt evidence: deciding whether the variant is correct or defective belongs to the later warehouse review, not to the domestic-delivery record." ]],
    ["Investigate a delivery-without-receipt gap",["Begin with the last defensible event. Confirm that the domestic reference belongs to the expected seller package, that the carrier page is current, and that the displayed destination wording is consistent with a warehouse delivery rather than another address. Note whether multiple order rows share the reference and whether a replacement reference appeared. Then check the Kakobuy order and warehouse pages for a newly created item record. If the gap matters, prepare a concise evidence pack containing redacted order and package labels, item description and option, carrier reference, last event text, event time, check times and the missing warehouse mapping. Ask whether that package can be matched to the order. Do not allege loss, theft or misdelivery when the only fact is that two systems have not yet shown the same event." ]],
    ["Close the record with a precise receipt boundary",["Close the domestic leg for an item when the correct item or package is defensibly matched to a warehouse receipt record. If the warehouse card appears but the exact carrier handoff remains undocumented, record receipt evidenced and carrier handoff time unknown. If the carrier says delivered but no item mapping exists, keep the leg open. If only some expected contents appear, close matched items separately and leave the rest unresolved. Save a read-only snapshot with the close date, evidence list and remaining unknowns. The close statement should say what was established, not what probably happened: ITEM-2 matched to warehouse receipt on the account; exact physical handoff time not shown. That language remains useful even if the interface changes later." ]],
    ["Hand the verified record to the next workflow",["Before moving on, audit for duplicated scans, overwritten references, missing time zones, variant labels copied from the wrong row and exposed personal data. Link the verified receipt row to the later intake or warehouse-readiness record rather than copying the entire domestic history into every file. The next workflow can compare quantity, option and visible condition, but it should inherit the item identity and evidence boundary established here. Keep platform facts separate from case observations: the official public flow explains the general order of stages, while your dated record shows what one account displayed. This method does not promise seller speed, carrier scans or warehouse timing. It creates a reproducible answer to a narrower question: which seller package was tied to which item, what evidence showed movement, and when did a warehouse record acknowledge it?" ]],
  ],faqs:[["Does seller sent mean the carrier has the package?","Not necessarily. Record a carrier acceptance or movement event separately."],["Does delivered mean warehouse received?","No. Keep the carrier delivery event separate until a warehouse record matches the package or item."],["What if only one item appears?","Close the matched item and leave the other expected contents unresolved."],["How long should intake take?","Use current account instructions and dated official information; do not publish a universal waiting period."]]},
  de:{title:"Kakobuy: Vom Verkäufer versandt oder im Lager eingegangen?",tag:"Paketdaten & Ablaufkontrolle",read:"15-Minuten-Ablaufleitfaden",reviewed:"Offizielle Quellen geprüft am 10. Sep. 2026",lede:"Verkäuferversand und Lagereingang sind getrennte Prüfpunkte. Ein datiertes Inlandsprotokoll zeigt Paketbezug, Bewegung, Lagerbestätigung und offene Lücken.",sources,sections:[
    ["Den Inlandsabschnitt klar abgrenzen",["Der Abschnitt beginnt mit glaubwürdigem Beleg, dass die richtige Verkäufersendung Richtung Kakobuy-Lager bewegt wurde, und endet mit einer Lagerbestätigung für Paket oder Artikel. Der öffentliche Ablauf ordnet Versand vor Lagerprüfung ein, doch Live-Begriffe werden wörtlich gespeichert. Verkäufer versandt beweist nicht den vollständigen Inhalt; Lagereingang beweist nicht automatisch jede erwartete Position."]],
    ["Artikel und Pakete zuerst zuordnen",["Führen Sie je Artikel und Variante eine Zeile mit Bestelllabel, geschwärzter Referenz, Menge und Verkäuferpaket. Bei Zusammenfassung bleiben einzelne Artikelzeilen erhalten; bei Teilung entsteht je Referenz eine Paketzeile. Geteilte Beispiele nutzen neutrale Kürzel, während vollständige IDs und Adressdaten privat bleiben."]],
    ["Trackingnummer nicht mit Bewegung verwechseln",["Speichern Sie erstes Erscheinen der Nummer getrennt von Carrier-Annahme oder Bewegung. Erfassen Sie Seite, Wortlaut, Ereigniszeit, Ort und Prüfzeit. Belegstufen sind Referenz angezeigt, Annahme, Bewegung, Zustellscan oder Lagereingang. Eine nicht erkannte Nummer ist ein Prüfergebnis, kein Verlustbeweis."]],
    ["Carrier-Zustellung und Lageraufnahme trennen",["Ein Zustellscan kann einen Empfangspunkt belegen, aber noch keine abgeschlossene Artikelaufnahme. Das Lager muss Paket und Bestellung eventuell erst zuordnen. Umgekehrt kann ein Lagerdatensatz trotz lückenhaftem Tracking erscheinen. Speichern Sie beide Zeiten, ohne aus einem Einzelfall einen allgemeinen Bearbeitungsstandard abzuleiten."]],
    ["Eine Mindesttabelle verwenden",["Felder sind Artikelalias, Variante, Menge, Bestell- und Paketlabel, geschwärzte Inlandsreferenz, erste Referenzzeit, letztes Carrier-Ereignis, Zeitzone, Zustellwortlaut, Lagerwortlaut, erste Lagerbeobachtung, Datei, Belegstärke, Abweichung und nächster Check. Unbekannt bleibt zulässig; fehlende Ereignisse werden nicht erfunden.","Die Tabelle bleibt append-only: Statusänderungen erhalten neue Zeilen statt alte Texte zu ersetzen. Dateien nennen Artikelalias, Quelle und Datum ohne vollständige Bestellnummer. Korrekturen behalten die alte Zuordnung und verweisen auf den Ersatz. Zeitabstände werden nur aus zwei belastbaren Ereigniszeiten berechnet, nicht aus dem Screenshot-Zeitpunkt."]],
    ["Teil-, Sammel- und Mehrfachankünfte abstimmen",["Bei einem Sammelpaket beweist ein sichtbarer Artikel nicht vollständigen Inhalt. Markieren Sie jede Position als zugeordnet, noch nicht sichtbar oder unerwartet. Mehrere Pakete werden nicht pauschal der ersten Referenz zugeordnet. Varianten- oder Mängelentscheidungen gehören in die spätere Lagerprüfung."]],
    ["Lücke nach Zustellscan untersuchen",["Prüfen Sie Paketzuordnung, aktuelle Carrier-Seite, Zielwortlaut, gemeinsame Referenzen und mögliche Ersatznummern. Suchen Sie danach in Bestellung und Lager. Für Support reichen geschwärzte Labels, Artikel, Option, letztes Ereignis und die fehlende Zuordnung. Behaupten Sie keinen Verlust, solange nur zwei Systeme noch nicht übereinstimmen."]],
    ["Mit präziser Eingangsgrenze schließen",["Schließen Sie eine Artikelzeile erst, wenn sie nachvollziehbar einem Lagereingang entspricht. Ist nur das Lager sichtbar, bleibt die Übergabezeit unbekannt; ist nur Zustellung sichtbar, bleibt der Abschnitt offen. Teilinhalte werden getrennt geschlossen. Die Nur-Lese-Version nennt Belege, Datum und Restlücken."]],
    ["An den nächsten Ablauf übergeben",["Prüfen Sie Duplikate, überschriebene Referenzen, Zeitzonen, falsche Variantenzeilen und Datenschutz. Verknüpfen Sie den bestätigten Eingang mit dem späteren Intake-Datensatz. Offizielle Seiten erklären die allgemeine Reihenfolge; Ihr datiertes Protokoll erklärt den konkreten Beleg, ohne Geschwindigkeit oder Lagerzeit zu versprechen."]],
  ],faqs:[["Bedeutet Verkäuferversand Carrier-Besitz?","Nicht zwingend; Annahme oder Bewegung separat belegen."],["Ist zugestellt gleich Lagereingang?","Nein, erst bei passender Lagerzuordnung."],["Nur ein Artikel sichtbar?","Den passenden schließen, übrige offenlassen."],["Wie lange dauert die Aufnahme?","Nur aktuelle Kontohinweise und datierte offizielle Angaben verwenden."]]},
  es:{title:"Kakobuy: enviado por el vendedor frente a recibido en almacén",tag:"Registros de paquete y control",read:"Guía operativa de 15 minutos",reviewed:"Fuentes oficiales revisadas el 10 sep 2026",lede:"El envío del vendedor y la recepción del almacén son controles distintos. Registra paquete, movimiento, aceptación y vacíos con fecha.",sources,sections:[
    ["Definir el tramo nacional",["Empieza cuando una prueba creíble vincula el paquete correcto con movimiento hacia el almacén y termina cuando un registro de almacén reconoce el paquete o artículo. Conserva los términos vivos de Kakobuy. Enviado no prueba contenido completo y recibido no prueba todas las piezas esperadas."]],
    ["Crear un mapa artículo-paquete",["Mantén una fila por artículo, variante y cantidad con etiqueta de pedido, referencia oculta y paquete del vendedor. Si se combina, conserva identidades; si se divide, crea una fila por paquete. Los ejemplos compartidos usan alias y los identificadores completos quedan privados."]],
    ["Tratar el tracking como referencia",["Separa la aparición del número del primer evento del transportista. Guarda página, texto, hora, lugar y momento de consulta. Clasifica referencia mostrada, aceptación, movimiento, entrega o recepción de almacén. Un número no reconocido no demuestra pérdida."]],
    ["Separar entrega y entrada en almacén",["Un escaneo de entrega puede indicar un punto receptor sin demostrar que terminó la asociación del artículo. El registro de almacén también puede aparecer con tracking incompleto. Conserva ambos tiempos y no conviertas la diferencia de un caso en un plazo universal."]],
    ["Usar una tabla mínima",["Incluye alias, variante, cantidad, etiquetas, referencia oculta, primera aparición, último evento, zona horaria, texto de entrega, recepción, primera observación, archivo, confianza, diferencia y próxima revisión. Desconocido es válido y no se rellenan hechos ausentes.","La tabla es acumulativa: cada cambio recibe una fila nueva. Nombra los archivos con alias, fuente y fecha sin revelar el pedido completo. Conserva la asignación original cuando la corrijas y enlaza el reemplazo. Calcula tiempo solo entre dos eventos con marcas fiables, no con la hora de la captura."]],
    ["Conciliar llegadas parciales y combinadas",["Un artículo visible no prueba que un paquete combinado estuviera completo. Marca cada pieza como vinculada, aún no visible o inesperada. No asignes varios paquetes al primer tracking. La decisión de variante o defecto pertenece a la revisión posterior."]],
    ["Investigar entrega sin recepción",["Confirma relación del paquete, página actual del transportista, destino, referencias compartidas y reemplazos. Revisa pedido y almacén. Si consultas soporte, aporta etiquetas ocultas, artículo, opción, último evento y relación que falta, sin afirmar pérdida sin prueba."]],
    ["Cerrar con un límite preciso",["Cierra el artículo cuando se vincule de forma defendible al registro del almacén. Si solo aparece almacén, deja desconocida la entrega exacta; si solo aparece entrega, mantén abierto. Cierra por separado los contenidos parciales y guarda una copia fechada de solo lectura."]],
    ["Entregar el registro al siguiente proceso",["Audita duplicados, referencias sobrescritas, zonas, variantes y privacidad. Vincula la recepción confirmada al registro de entrada posterior. La fuente oficial explica la secuencia general; el registro fechado demuestra el caso sin prometer velocidad."]],
  ],faqs:[["¿Enviado significa posesión del transportista?","No necesariamente; registra aceptación o movimiento aparte."],["¿Entregado significa recibido?","No hasta que el almacén lo vincule."],["¿Solo aparece un artículo?","Cierra ese artículo y deja los demás abiertos."],["¿Cuánto tarda?","Usa instrucciones actuales, no un plazo universal."]]},
  fr:{title:"Kakobuy : expédié par le vendeur ou reçu à l’entrepôt",tag:"Dossiers colis et contrôle",read:"Guide opérationnel de 15 minutes",reviewed:"Sources officielles vérifiées le 10 sept. 2026",lede:"Expédition vendeur et réception entrepôt sont deux contrôles distincts. Consignez le colis, le mouvement, la réception et les lacunes avec leurs dates.",sources,sections:[
    ["Définir le trajet intérieur",["Le trajet commence lorsqu’une preuve relie le bon colis à un mouvement vers l’entrepôt et se termine lorsqu’un dossier d’entrepôt reconnaît le colis ou l’article. Conservez les libellés Kakobuy en direct. Expédié ne prouve pas le contenu complet et reçu ne prouve pas toutes les pièces attendues."]],
    ["Créer la correspondance article-colis",["Gardez une ligne par article, variante et quantité avec libellé de commande, référence masquée et colis vendeur. En cas de regroupement, conservez les identités; en cas de division, créez une ligne par colis. Les exemples partagés utilisent des alias et les identifiants complets restent privés."]],
    ["Traiter le suivi comme une référence",["Séparez l’apparition du numéro du premier événement transporteur. Notez page, texte, heure, lieu et heure de contrôle. Classez référence affichée, acceptation, mouvement, livraison ou réception entrepôt. Un numéro non reconnu ne prouve pas une perte."]],
    ["Séparer livraison et admission",["Un scan livré peut viser un point de réception sans prouver l’admission de l’article. Un dossier d’entrepôt peut aussi apparaître malgré un suivi incomplet. Conservez les deux heures sans transformer l’écart d’un cas en délai universel."]],
    ["Tenir une table minimale",["Champs : alias, variante, quantité, libellés, référence masquée, première apparition, dernier événement, fuseau, texte de livraison, réception, première observation, fichier, confiance, écart et prochain contrôle. Inconnu reste valide et aucun événement absent n’est inventé.","La table reste cumulative : chaque changement crée une ligne. Nommez les fichiers avec alias, source et date sans exposer la commande complète. Une correction conserve l’ancienne association et pointe vers la nouvelle. Calculez une durée seulement entre deux événements horodatés de façon fiable."]],
    ["Rapprocher les arrivées partielles",["Un article visible ne prouve pas qu’un colis groupé était complet. Marquez chaque pièce associée, non visible ou inattendue. N’attachez pas plusieurs colis au premier suivi. Variante et défaut relèvent du contrôle d’entrepôt suivant."]],
    ["Étudier une livraison sans réception",["Vérifiez le lien colis, la page transporteur actuelle, la destination, les références partagées et remplacements. Contrôlez commande et entrepôt. Pour le support, fournissez libellés masqués, article, option, dernier événement et lien manquant sans alléguer une perte."]],
    ["Fermer avec une limite précise",["Fermez l’article lorsqu’il correspond défendablement au dossier d’entrepôt. Si seul l’entrepôt apparaît, l’heure de remise reste inconnue; si seule la livraison apparaît, gardez ouvert. Fermez séparément les contenus partiels et archivez une copie datée."]],
    ["Transmettre au processus suivant",["Auditez doublons, références écrasées, fuseaux, variantes et confidentialité. Reliez la réception confirmée au dossier d’admission. La source officielle explique l’ordre général; votre dossier daté prouve le cas sans promettre de vitesse."]],
  ],faqs:[["Expédié signifie-t-il remis au transporteur ?","Pas forcément; prouvez acceptation ou mouvement séparément."],["Livré signifie-t-il reçu ?","Non, pas avant l’association par l’entrepôt."],["Un seul article apparaît ?","Fermez-le et gardez les autres ouverts."],["Quel délai d’admission ?","Utilisez les instructions actuelles, jamais un délai universel."]]},
  it:{title:"Kakobuy: spedito dal venditore o ricevuto in magazzino",tag:"Registri pacco e controllo",read:"Guida operativa di 15 minuti",reviewed:"Fonti ufficiali verificate il 10 set 2026",lede:"Spedizione del venditore e ricezione del magazzino sono controlli distinti. Registra pacco, movimento, ricezione e lacune con data.",sources,sections:[
    ["Definire la tratta nazionale",["La tratta inizia quando una prova collega il pacco corretto al movimento verso il magazzino e termina quando un record di magazzino riconosce pacco o articolo. Conserva le etichette live. Spedito non prova il contenuto completo e ricevuto non prova ogni pezzo atteso."]],
    ["Creare una mappa articolo-pacco",["Mantieni una riga per articolo, variante e quantità con etichetta ordine, riferimento oscurato e pacco venditore. Se combinato, conserva le identità; se diviso, crea una riga per pacco. Gli esempi condivisi usano alias e gli identificativi completi restano privati."]],
    ["Trattare il tracking come riferimento",["Separa la prima comparsa del numero dal primo evento del corriere. Salva pagina, testo, ora, luogo e momento del controllo. Classifica riferimento mostrato, accettazione, movimento, consegna o ricezione. Un numero non riconosciuto non prova perdita."]],
    ["Separare consegna e ingresso",["Una scansione consegnato può indicare un punto di ricezione senza provare l’associazione dell’articolo. Un record di magazzino può apparire con tracking incompleto. Conserva entrambi gli orari senza trasformare il divario di un caso in uno standard universale."]],
    ["Usare una tabella minima",["Campi: alias, variante, quantità, etichette, riferimento oscurato, prima comparsa, ultimo evento, fuso, testo consegna, ricezione, prima osservazione, file, fiducia, discrepanza e prossimo controllo. Sconosciuto è valido e gli eventi mancanti non si inventano.","La tabella resta cumulativa: ogni cambiamento crea una nuova riga. Nomina i file con alias, fonte e data senza esporre l’ordine completo. Una correzione conserva la vecchia associazione e rimanda a quella nuova. Calcola intervalli solo tra due eventi con orari affidabili."]],
    ["Riconciliare arrivi parziali e combinati",["Un articolo visibile non prova che un pacco combinato fosse completo. Segna ogni pezzo abbinato, non ancora visibile o inatteso. Non collegare più pacchi al primo tracking. Variante e difetto appartengono al controllo successivo."]],
    ["Indagare consegna senza ricezione",["Conferma legame del pacco, pagina attuale del corriere, destinazione, riferimenti condivisi e sostituzioni. Controlla ordine e magazzino. Per il supporto fornisci etichette oscurate, articolo, opzione, ultimo evento e collegamento mancante senza affermare perdita."]],
    ["Chiudere con un limite preciso",["Chiudi l’articolo quando corrisponde in modo difendibile al record di magazzino. Se compare solo il magazzino, l’ora di consegna resta ignota; se compare solo consegna, resta aperto. Chiudi separatamente i contenuti parziali e salva una copia datata."]],
    ["Passare al flusso successivo",["Controlla duplicati, riferimenti sovrascritti, fusi, varianti e privacy. Collega la ricezione verificata al record di ingresso. La fonte ufficiale spiega l’ordine generale; il registro datato dimostra il caso senza promettere velocità."]],
  ],faqs:[["Spedito significa che il corriere lo possiede?","Non sempre; registra accettazione o movimento a parte."],["Consegnato significa ricevuto?","No, finché il magazzino non lo abbina."],["Compare un solo articolo?","Chiudilo e lascia aperti gli altri."],["Quanto dura l’ingresso?","Usa istruzioni attuali, non tempi universali."]]},
};

const parityAdditions: Record<Exclude<Locale, "en">, string[]> = {
  de: [
    "Definieren Sie beide Grenzen vor dem Öffnen des Kontos, damit eine neue Nummer, ein Zustellscan oder eine Lagerkarte nicht mehr beweisen soll, als tatsächlich angezeigt wird. Ein Lagereintrag ist noch kein Beleg für jede Menge, Variante oder Zubehörposition. Oberflächen und Zwischenereignisse können sich ändern; deshalb bleibt der aktuelle Wortlaut Bestandteil des Belegs.",
    "Eine solche Karte bildet sowohl eine gemeinsame Referenz für mehrere Artikel als auch mehrere Pakete für eine Bestellung ab. Die Beziehung darf nicht in einer einzelnen Trackingzelle verschwinden. Notieren Sie Quellenbeschreibung und ausgewählte Option, damit eine spätere Lagerkarte mit dem richtigen Artikel verglichen werden kann. Private Kontolinks, Telefonnummern und vollständige Referenzen erscheinen niemals in freigegebenen Beispielen.",
    "Wenn die Kontoseite später eine andere Nummer zeigt, ergänzen Sie eine neue Zuordnung, statt die erste zu überschreiben. Kennzeichnen Sie alt nur dann als ersetzt oder ungeklärt, wenn der Beleg dies rechtfertigt. Die verwendeten Belegstufen sind redaktionelle Kategorien und keine erfundenen offiziellen Kakobuy-Statusnamen; sie halten Beobachtung und Schlussfolgerung getrennt.",
    "Schreiben Sie beispielsweise Carrier-Zustellung angezeigt um 14:10 und Lagereingang erstmals um 18:40 beobachtet. Behaupten Sie daraus weder eine garantierte viereinhalbstündige Aufnahme noch eine Verzögerung. Der belastbare Wert liegt im beobachteten Abstand und darin, ob die Zuordnung später geschlossen werden konnte. Eine Frist stammt nur aus einem aktuellen, datierten Kontohinweis oder einer offiziellen Regel.",
    "Der Vertrauenswert bewertet ausschließlich die Zuordnung, etwa nicht verknüpfte Referenz, behauptete Artikel-Paket-Beziehung, belegte Bewegung, angezeigte Zustellung oder passender Lagereingang. Er bewertet weder Verkäufer noch Carrier. Speichern Sie Bildschirmbelege unter neutralen Namen wie ITEM-2_account_2026-09-10. Eine korrigierte Zeile bleibt erhalten, wird als korrigiert markiert und verweist auf den Ersatz, damit ein Prüfer den damaligen Entscheidungsgrund nachvollziehen kann.",
    "Treffen mehrere Pakete zugleich ein, darf nicht jede sichtbare Position automatisch der ersten Zustellreferenz zugeordnet werden. Nutzen Sie Etiketten, Zeitpunkte und die tatsächlich angezeigte Abbildung. Eine Teilaufnahme kann ein normaler Zwischenstand oder eine Abweichung sein; der Datensatz hält beide Möglichkeiten offen. Er stoppt bewusst vor der Qualitäts- oder Variantenentscheidung.",
    "Beginnen Sie immer mit dem letzten belastbaren Ereignis und prüfen Sie, ob die Zielbeschreibung überhaupt zu einem Lagereingang passt. Erfassen Sie auch Prüfzeitpunkte und die fehlende Lagerbeziehung. Die Supportfrage lautet eng, ob dieses Paket der konkreten Bestellung zugeordnet werden kann. Die Wörter Verlust, Diebstahl oder Fehlzustellung sind ohne zusätzlichen Beleg nicht gerechtfertigt.",
    "Bei nur teilweise sichtbarem Inhalt schließen Sie die passenden Artikel einzeln und lassen den Rest offen. Die Abschlussformulierung beschreibt ausschließlich Festgestelltes, zum Beispiel ITEM-2 dem Lagereintrag im Konto zugeordnet; genaue physische Übergabezeit nicht angezeigt. Zusammen mit Belegliste, Abschlussdatum und offenen Punkten entsteht eine schreibgeschützte Momentaufnahme, die auch nach einer Oberflächenänderung verständlich bleibt.",
    "Der folgende Intake- oder Readiness-Datensatz übernimmt die verifizierte Artikelidentität, statt die gesamte Inlandshistorie zu kopieren. Prüfen Sie vorher doppelte Scans, fehlende Zeitzonen und falsch kopierte Varianten. Offizielle Seiten erklären nur die allgemeine Reihenfolge, während das datierte Protokoll zeigt, was dieses Konto anzeigte. Es verspricht keine Geschwindigkeit, sondern liefert eine reproduzierbare Zuordnung.",
  ],
  es: [
    "Define ambos límites antes de abrir la cuenta para que un número nuevo, un escaneo o una tarjeta de almacén no se conviertan en una afirmación excesiva. Una recepción no demuestra por sí sola todas las cantidades, variantes o accesorios. La interfaz y los eventos intermedios pueden cambiar, por lo que el texto vivo de la pantalla debe conservarse como parte de la prueba.",
    "El mapa representa tanto varios artículos unidos a una referencia como varios paquetes de un mismo pedido. Esa relación no debe desaparecer en una sola celda de tracking. Guarda descripción de origen y opción elegida para comparar la tarjeta posterior con el artículo correcto. En ejemplos compartidos nunca aparecen enlaces de cuenta, teléfonos ni referencias completas.",
    "Si la cuenta muestra después otro número, añade el nuevo enlace sin borrar el anterior. Marca una referencia como sustituida o no resuelta solo cuando la evidencia lo permite. Las categorías de prueba son etiquetas editoriales y no nombres oficiales inventados de Kakobuy; su propósito es separar lo observado de la conclusión.",
    "Escribe entrega del transportista mostrada a las 14:10 y recepción vista por primera vez a las 18:40. No lo conviertas en un estándar de cuatro horas y media ni en un retraso. El dato útil es la diferencia observada y si la relación se cerró. Solo una instrucción de cuenta actual o regla oficial fechada puede aportar un plazo relevante.",
    "La confianza describe exclusivamente el mapeo: referencia sin vincular, relación declarada, movimiento probado, entrega mostrada o recepción coincidente. No califica vendedor, carrier ni plataforma. Usa nombres neutrales como ITEM-2_account_2026-09-10. Si corriges una relación, conserva la fila inicial, márcala como corregida y enlaza el reemplazo para mantener el razonamiento histórico.",
    "Cuando llegan varios paquetes juntos, no asignes todas las tarjetas al primer tracking; usa etiquetas, fechas y relaciones visibles. Una entrada parcial puede ser un estado normal o una discrepancia real, y el registro no debe elegir antes de tiempo. Este método termina en la prueba de recepción; la corrección de variante o defecto pertenece a la revisión posterior.",
    "Empieza por el último evento defendible y comprueba que el texto del destino sea coherente con una entrega al almacén. Incluye horas de consulta y la relación exacta que falta. La pregunta de soporte debe limitarse a si el paquete puede asociarse al pedido concreto. Sin pruebas adicionales no afirmes pérdida, robo ni entrega incorrecta.",
    "Si solo aparece parte del contenido, cierra por separado los artículos coincidentes y deja los demás abiertos. La frase final solo dice lo demostrado: ITEM-2 asociado a la recepción de la cuenta; hora física exacta no mostrada. Guarda una instantánea de solo lectura con fecha, lista de pruebas e incógnitas para que siga siendo comprensible si cambia la interfaz.",
    "El registro de entrada siguiente hereda la identidad verificada y enlaza el historial, en vez de copiarlo en todos los archivos. Antes, busca escaneos repetidos, zonas ausentes y variantes pegadas en la fila equivocada. La página oficial explica el orden general; el registro fechado explica esta cuenta. No promete velocidad, sino una asignación reproducible.",
  ],
  fr: [
    "Définissez les deux limites avant d’ouvrir le compte afin qu’un nouveau numéro, un scan ou une carte d’entrepôt ne devienne pas une affirmation excessive. Une réception ne prouve pas à elle seule toutes les quantités, variantes ou accessoires. L’interface et les événements intermédiaires peuvent changer ; le libellé en direct doit donc rester dans la preuve.",
    "La carte représente aussi bien plusieurs articles liés à une référence que plusieurs colis issus d’une commande. Cette relation ne doit pas disparaître dans une seule cellule de suivi. Gardez description source et option choisie afin de comparer la future carte au bon article. Aucun lien de compte, téléphone ou identifiant complet ne figure dans un exemple partagé.",
    "Si le compte affiche plus tard un autre numéro, ajoutez la nouvelle correspondance sans effacer l’ancienne. Déclarez une référence remplacée ou non résolue uniquement si les éléments l’autorisent. Les niveaux de preuve sont des catégories éditoriales, pas des statuts Kakobuy inventés ; ils séparent ce qui est observé de ce qui est conclu.",
    "Écrivez livraison transporteur affichée à 14 h 10 et réception entrepôt observée à 18 h 40. N’en faites ni une norme de quatre heures trente ni un retard. L’information défendable est l’écart observé et la fermeture éventuelle du rapprochement. Seule une instruction de compte actuelle ou une règle officielle datée peut fixer une échéance pertinente.",
    "Le niveau de confiance décrit uniquement la correspondance : référence non liée, relation déclarée, mouvement prouvé, livraison affichée ou réception associée. Il ne note ni vendeur ni transporteur. Nommez les fichiers comme ITEM-2_account_2026-09-10. En cas de correction, conservez la ligne initiale, marquez-la corrigée et liez la nouvelle afin de préserver le raisonnement historique.",
    "Lorsque plusieurs colis arrivent ensemble, ne rattachez pas toutes les cartes au premier suivi ; utilisez étiquettes, dates et relations visibles. Une admission partielle peut être un état normal ou une anomalie, et le dossier conserve les deux possibilités. La méthode s’arrête à la réception : variante et défaut relèvent du contrôle ultérieur.",
    "Partez du dernier événement défendable et vérifiez que le libellé de destination correspond bien à un entrepôt. Ajoutez les heures de contrôle et la relation manquante. La question au support demande seulement si ce colis peut être rattaché à la commande précise. Sans autre preuve, perte, vol ou mauvaise livraison ne sont pas des conclusions permises.",
    "Si une partie seulement apparaît, fermez séparément les articles associés et laissez le reste ouvert. La conclusion dit uniquement ce qui est établi : ITEM-2 associé à une réception du compte ; heure physique exacte non affichée. Archivez une copie en lecture seule avec date, liste de preuves et inconnues, utilisable même après une modification de l’interface.",
    "Le prochain dossier d’admission hérite de l’identité vérifiée et pointe vers l’historique au lieu de tout recopier. Recherchez auparavant scans dupliqués, fuseaux absents et variante collée dans la mauvaise ligne. La source officielle explique l’ordre général ; votre dossier daté décrit ce compte. Il ne promet pas la vitesse, mais une correspondance reproductible.",
  ],
  it: [
    "Definisci entrambi i confini prima di aprire l’account, così un nuovo numero, una scansione o una scheda di magazzino non diventano affermazioni eccessive. La ricezione non prova da sola quantità, varianti o accessori completi. Interfaccia ed eventi intermedi possono cambiare; il testo live della pagina deve quindi restare parte della prova.",
    "La mappa rappresenta sia più articoli collegati a un riferimento sia più pacchi per un ordine. Questa relazione non deve sparire in una sola cella tracking. Conserva descrizione della fonte e opzione scelta per confrontare la futura scheda con l’articolo corretto. Negli esempi condivisi non compaiono link account, telefoni o riferimenti completi.",
    "Se l’account mostra poi un altro numero, aggiungi il nuovo legame senza cancellare il precedente. Segna un riferimento come sostituito o irrisolto solo se la prova lo consente. I livelli di evidenza sono categorie editoriali e non nomi ufficiali Kakobuy inventati; servono a separare osservazione e conclusione.",
    "Scrivi consegna del corriere mostrata alle 14:10 e ricezione vista alle 18:40. Non trasformare il caso in uno standard di quattro ore e mezza o in un ritardo. Il dato difendibile è l’intervallo osservato e l’eventuale chiusura del collegamento. Solo un’istruzione account corrente o una regola ufficiale datata può indicare una scadenza rilevante.",
    "La fiducia descrive soltanto la mappatura: riferimento non collegato, relazione dichiarata, movimento provato, consegna mostrata o ricezione abbinata. Non valuta venditore o corriere. Usa nomi neutrali come ITEM-2_account_2026-09-10. Se correggi una relazione, conserva la riga iniziale, segnala la correzione e collega la sostituzione per mantenere il ragionamento storico.",
    "Quando arrivano più pacchi insieme, non associare ogni scheda al primo tracking; usa etichette, date e relazioni visibili. Un ingresso parziale può essere normale o una vera discrepanza e il registro conserva entrambe le possibilità. Il metodo termina alla prova di ricezione; variante e difetto appartengono al controllo successivo.",
    "Parti dall’ultimo evento difendibile e verifica che il testo della destinazione sia coerente con una consegna al magazzino. Includi gli orari di controllo e il legame mancante. La domanda al supporto chiede solo se quel pacco può essere associato all’ordine preciso. Senza altre prove non affermare perdita, furto o consegna errata.",
    "Se appare solo parte del contenuto, chiudi separatamente gli articoli abbinati e lascia aperti gli altri. La frase finale dice solo quanto provato: ITEM-2 associato alla ricezione account; ora fisica esatta non mostrata. Archivia una copia in sola lettura con data, elenco prove e incognite, utile anche dopo un cambio di interfaccia.",
    "Il registro di ingresso successivo eredita l’identità verificata e collega la cronologia invece di copiarla ovunque. Prima controlla scansioni duplicate, fusi mancanti e varianti nella riga sbagliata. La fonte ufficiale spiega l’ordine generale; il registro datato descrive questo account. Non promette velocità, ma crea una corrispondenza riproducibile.",
  ],
};

for (const lang of ["de", "es", "fr", "it"] as const) {
  domesticReceiptArticleData[lang] = {
    ...domesticReceiptArticleData[lang],
    sections: domesticReceiptArticleData[lang].sections.map((section, index) => [
      section[0],
      section[1].map((paragraph, paragraphIndex) => paragraphIndex === section[1].length - 1 ? `${paragraph} ${parityAdditions[lang][index]}` : paragraph),
    ]),
  };
}
