import type { Locale } from "./site-data";
import type { IdentifierArticle } from "./order-identifiers-article";

const sources = [
  {label:"Kakobuy official homepage and public service flow",url:"https://www.kakobuy.com/"},
  {label:"Kakobuy official purchasing-flow information",url:"https://www.kakobuy.com/index/information?information_id=12"},
  {label:"Kakobuy official service introduction",url:"https://www.kakobuy.com/index/information?information_id=3"},
];

export const orderTimelineArticleData:Record<Locale,IdentifierArticle>={
  en:{
    title:"Build a Kakobuy Order Timeline: The Minimum Fields Worth Recording",
    tag:"Parcel records & workflow control",read:"15 min operations guide",reviewed:"Official sources reviewed 2 Sep 2026",
    lede:"A useful Kakobuy order timeline records what changed, where the status appeared and when it was observed. Use a small set of stable fields to reconstruct the path from purchase request to parcel handoff without inventing missing events.",sources,
    sections:[
      ["A timeline is an evidence log, not a delivery forecast",[
        "A Kakobuy order timeline should answer three questions: what object was observed, what the page actually said and when the observation was made. It should not predict when a seller will dispatch, when warehouse intake will finish or when a parcel will arrive. Kakobuy’s public buying flow distinguishes product order, warehouse receipt and inspection, parcel submission and international transport. That sequence supports stage labels, but the public pages do not publish one guaranteed duration for every seller, account, item or route.",
        "The strongest timeline preserves uncertainty. If the account shows an order but no seller-dispatch event, record the order observation and leave dispatch unverified. If a warehouse record appears without a visible receipt time, record the first time you saw it and label the actual receipt time unknown. A timeline becomes misleading when blank cells are filled with assumed dates or when a later status is copied backward to create a smooth story.",
      ]],
      ["Use one row per observed change",[
        "Create a new row whenever a visible status, identifier, page context or decision changes. Do not edit the previous row in place. The minimum columns are checked-at time, object type, object ID label, redacted reference, source page, exact status wording, normalized stage, evidence file, interpretation and next check. The exact wording preserves what Kakobuy displayed; the normalized stage helps sort different labels without replacing them.",
        "For example, a private record can state that ORDER-A was observed on the order page at 10:15 with the displayed wording saved in a screenshot. A later row can record a warehouse page observation at 16:40. The second row does not prove what happened between those moments. It only proves that the new state was visible by the second check. This distinction is essential when an operational page updates after the underlying physical event.",
      ]],
      ["Keep object type and identifier label together",[
        "An order number, warehouse item reference, parcel number and carrier tracking reference identify different objects. Your timeline should never store a bare number without its visible label. Record the object type in one field and the exact interface label in another. This prevents a parcel reference from being used to explain one item, or a carrier reference from being treated as evidence that the platform parcel was already packed.",
        "One order can later map into a parcel with other orders. When that relationship becomes visible, add a mapping row rather than replacing the order reference. Keep order-to-warehouse, order-to-parcel and parcel-to-tracking links as separate facts. If a relationship is not shown, use ‘not verified’ instead of inferring it from close dates, similar digits or the fact that only one parcel is currently open.",
      ]],
      ["Record three times instead of one",[
        "Use event time, displayed update time and checked-at time as separate fields. Event time is the time the described action occurred when the page or carrier explicitly provides it. Displayed update time is a timestamp attached to the status by the interface. Checked-at time is when you personally observed the page. Many records will have only the third field, and that is acceptable. It gives a defensible boundary: the status was visible at that moment.",
        "Store times with a time zone. A useful format is ISO 8601, such as 2026-09-02T10:15:00+08:00, because it sorts correctly and preserves the offset. Do not silently convert a seller, platform or carrier timestamp unless its zone is known. If you add a local display column for convenience, keep the original value too. Date-only screenshots should remain date-only evidence rather than being assigned an invented hour.",
      ]],
      ["Normalize stages without erasing the source wording",[
        "A compact stage set can make the log usable: purchase requested, seller processing, domestic dispatch evidenced, warehouse receipt evidenced, warehouse record available, parcel submitted, carrier reference available and carrier event evidenced. These are editorial categories, not official Kakobuy status names. The status column must retain the current interface wording so another reader can audit the classification.",
        "Use ‘evidenced’ deliberately. A parcel-submission record does not prove carrier acceptance; a tracking reference does not prove a physical scan; a warehouse photo does not automatically establish the time the seller delivered. When one page changes from an internal workflow state to another, record that transition as a page observation. Promote it to a physical-event stage only when the underlying evidence supports the stronger claim.",
      ]],
      ["Attach privacy-safe evidence and a source pointer",[
        "Each row needs a source pointer that another careful reader could follow: account section, page label, screenshot filename or saved PDF, and the capture time. Use a naming pattern such as object-stage-checkedat-version. Keep the original file privately. For any shared copy, redact names, addresses, phone numbers, account identifiers, payment details, complete order or tracking numbers, QR codes and browser tokens.",
        "A screenshot is not self-explanatory. Add a short note describing the relevant area and why it matters. Avoid cropping so tightly that the page context disappears, but do not retain unrelated private data merely for context. When the status is text that can be copied accurately, store the text alongside the image. If an interface requires login, note that the record came from an authenticated account page rather than implying it was public policy.",
      ]],
      ["Log decisions and the next check",[
        "A timeline is more useful when it records what the observation changed. Add a decision field with values such as no action, verify variant, wait for seller update, review warehouse record, hold parcel submission or check carrier page. These are the user’s workflow decisions, not claims that Kakobuy instructed the action. Keep the reason brief and tie it to the evidence row.",
        "Add a next-check condition rather than an invented deadline. Examples are ‘after a new account status appears,’ ‘when the warehouse record becomes available’ or ‘after a carrier reference is shown.’ A calendar reminder can support the user’s own workflow, but it must not be presented as an official service time. If a live help page or account notice shows a relevant deadline, capture that separate dated source instead of copying it into every order.",
      ]],
      ["Audit the record before relying on it",[
        "Check for duplicate rows, overwritten history, missing time zones, unlabeled IDs, unexplained stage promotions and evidence files that cannot be opened. Every conclusion should point to one or more rows. A gap is allowed; a hidden gap is not. If two pages appear inconsistent, preserve both observations and their timestamps, then state the narrow conflict. Do not delete the older row simply because a newer page looks more current.",
        "The minimum viable Kakobuy order timeline is intentionally small: one row per observed change, separate object and ID fields, exact source wording, three possible timestamps, a normalized stage, privacy-safe evidence, interpretation and next check. It does not guarantee that the process will be quick. It gives the buyer a reproducible account of what was visible, what remains unknown and which record supports the next operational decision. Before closing the record, export a read-only copy and verify that filenames still open, references remain text rather than scientific notation, and the latest row has a clear next-check condition. Keep that snapshot with the same version label used in the evidence folder. If the process later changes, append a new row and version instead of rewriting the closed snapshot. This final control makes the timeline suitable for a support question, a personal audit or a handoff to someone helping with the account.",
      ]],
    ],
    faqs:[
      ["Should I record every time I open the account?","No. Add a row when a status, identifier, mapping, evidence file or workflow decision changes. A repeated check with no change is useful only when the absence itself matters."],
      ["What if the page shows no timestamp?","Record your checked-at time and label the event or update time unknown. Do not manufacture a time from memory."],
      ["Can I combine order and parcel events in one column?","Keep one timeline but separate object type, visible label and reference. Add an explicit mapping row when an order is shown inside a parcel."],
      ["How do I share the timeline safely?","Redact personal data, account details, complete references, QR codes and payment information. Share only the rows and evidence needed for the question."],
    ],
  },
  de:{
    title:"Kakobuy-Bestellzeitlinie erstellen: Die wichtigsten Felder",tag:"Paketdaten & Ablaufkontrolle",read:"15-Minuten-Ablaufleitfaden",reviewed:"Offizielle Quellen geprüft am 2. Sep. 2026",lede:"Eine brauchbare Kakobuy-Bestellzeitlinie hält fest, was sich geändert hat, auf welcher Seite der Status erschien und wann er beobachtet wurde. Wenige stabile Felder rekonstruieren den Ablauf ohne erfundene Ereignisse.",sources,
    sections:[
      ["Zeitlinie als Belegprotokoll, nicht als Prognose",["Die Zeitlinie beantwortet: Welches Objekt wurde gesehen, was sagte die Seite und wann wurde es beobachtet? Sie verspricht weder Händler-Versand noch Lagereingang oder Zustellung. Der öffentliche Ablauf trennt Bestellung, Lager, Paketeinreichung und internationalen Transport, nennt aber keine garantierte Dauer für jeden Fall.","Erhalte Unsicherheit. Fehlt ein Versandereignis, bleibt es unbestätigt. Erscheint ein Lagerdatensatz ohne Eingangszeit, speichere die erste Beobachtung und kennzeichne die tatsächliche Zeit als unbekannt. Leere Felder dürfen nicht mit vermuteten Daten gefüllt werden."]],
      ["Eine Zeile pro sichtbarer Änderung",["Lege bei Änderung von Status, Kennung, Seitenkontext oder Entscheidung eine neue Zeile an. Mindestfelder sind Prüfzeit, Objekttyp, sichtbare ID-Bezeichnung, geschwärzte Referenz, Quellseite, exakter Statuswortlaut, normalisierte Phase, Belegdatei, Interpretation und nächster Check.","Eine spätere Lagerbeobachtung beweist nicht den genauen Vorgang zwischen zwei Prüfungen. Sie zeigt nur, dass der neue Zustand spätestens beim zweiten Check sichtbar war. Diese Grenze bleibt erhalten, auch wenn eine operative Seite verzögert aktualisiert wird."]],
      ["Objekttyp und Kennungsbezeichnung zusammenführen",["Bestellnummer, Lagerreferenz, Paketnummer und Carrier-Tracking stehen für verschiedene Objekte. Speichere nie eine nackte Nummer. Objekttyp und exakte Oberfläche-Bezeichnung verhindern, dass eine Paket-ID einen Einzelartikel oder eine Tracking-ID das Packen beweisen soll.","Wenn die Zuordnung sichtbar wird, ergänze eine Mapping-Zeile. Halte Bestellung-zu-Lager, Bestellung-zu-Paket und Paket-zu-Tracking getrennt. Bei fehlender Anzeige lautet der Wert „nicht verifiziert“, nicht eine Vermutung aus Datum oder ähnlichen Ziffern."]],
      ["Drei Zeiten getrennt erfassen",["Trenne Ereigniszeit, angezeigte Aktualisierungszeit und eigene Prüfzeit. Viele Zeilen haben nur die Prüfzeit; das ist zulässig und belegt, dass der Status dann sichtbar war.","Speichere Zeitzone und Originalwert, möglichst ISO 8601. Konvertiere fremde Zeitstempel nur bei bekannter Zone. Ein reines Datum bleibt ein Datum und erhält keine erfundene Uhrzeit."]],
      ["Phasen normalisieren, Wortlaut erhalten",["Nutze kompakte Arbeitsphasen wie Kauf angefragt, Händlerbearbeitung, Inlandsversand belegt, Lagereingang belegt, Lagerdatensatz verfügbar, Paket eingereicht, Trackingreferenz verfügbar und Carrier-Ereignis belegt. Das sind redaktionelle Kategorien, keine offiziellen Statusnamen.","Eine Paketeinreichung beweist keine Carrier-Annahme, eine Trackingreferenz keinen physischen Scan und ein Lagerfoto keine genaue Lieferzeit. Stärke eine Aussage nur, wenn die Belege die stärkere Phase tragen."]],
      ["Datenschutzsichere Belege anhängen",["Jede Zeile nennt Kontobereich, Seitenlabel, Dateiname und Aufnahmezeit. Nutze ein Schema aus Objekt, Phase, Prüfzeit und Version. Originale bleiben privat; geteilte Kopien schwärzen Namen, Adressen, Telefon, Konto, Zahlung, vollständige Referenzen, QR-Codes und Tokens.","Ein Screenshot braucht eine kurze Kontextnotiz. Erhalte genug Seitenkontext, aber keine unnötigen privaten Daten. Bei Login-Seiten notiere, dass der Beleg aus dem authentifizierten Konto stammt und keine öffentliche Richtlinie ist."]],
      ["Entscheidung und nächsten Check protokollieren",["Erfasse, was die Beobachtung änderte: keine Aktion, Variante prüfen, Händler-Update abwarten, Lagerdatensatz prüfen, Paketeinreichung halten oder Carrier-Seite prüfen. Das sind Nutzerentscheidungen, keine Plattformanweisungen.","Formuliere Bedingungen statt erfundener Fristen: nach neuem Kontostatus, wenn der Lagerdatensatz erscheint oder sobald eine Carrier-Referenz sichtbar ist. Offizielle Fristen werden als eigene datierte Quelle gespeichert."]],
      ["Vor Nutzung auditieren",["Prüfe Duplikate, überschriebene Geschichte, fehlende Zeitzonen, unbeschriftete IDs, unbegründete Phasenwechsel und unlesbare Belege. Lücken sind erlaubt, versteckte Lücken nicht. Widersprüche bleiben mit beiden Zeitstempeln erhalten.","Die Mindestzeitlinie nutzt eine Zeile pro Änderung, getrennte Objekte, Originalwortlaut, drei mögliche Zeiten, normalisierte Phase, geschützte Belege, Interpretation und nächsten Check. Sie verspricht keine Geschwindigkeit, sondern zeigt belegt, unbekannt und nächste Entscheidung."]],
    ],faqs:[["Jeden Kontobesuch protokollieren?","Nein, nur relevante Änderungen oder bewusst geprüfte Nichtänderungen."],["Kein Zeitstempel sichtbar?","Eigene Prüfzeit speichern und Ereigniszeit als unbekannt markieren."],["Bestell- und Paketereignisse kombinieren?","Eine Zeitlinie ist möglich, aber Objekttypen und Mapping bleiben getrennt."],["Sicher teilen?","Personen-, Konto-, Zahlungs-, QR- und vollständige Referenzdaten schwärzen."]]
  },
  es:{
    title:"Crea una cronología de pedidos Kakobuy: campos mínimos",tag:"Registros de paquete y control",read:"Guía operativa de 15 minutos",reviewed:"Fuentes oficiales revisadas el 2 sep 2026",lede:"Una cronología útil registra qué cambió, dónde apareció el estado y cuándo se observó. Un conjunto pequeño de campos reconstruye el proceso sin inventar eventos ausentes.",sources,
    sections:[
      ["Un registro de pruebas, no un pronóstico",["La cronología responde qué objeto se vio, qué dijo la página y cuándo. No promete despacho, entrada en almacén ni entrega. El flujo público separa pedido, almacén, presentación del paquete y transporte, pero no fija una duración garantizada para todos los casos.","Conserva la incertidumbre. Si no aparece el despacho, queda sin verificar. Si el registro de almacén no muestra hora, guarda tu primera observación y marca la hora real como desconocida. No rellenes huecos con fechas supuestas."]],
      ["Una fila por cambio observado",["Añade fila cuando cambie estado, identificador, contexto o decisión. Campos mínimos: hora de consulta, objeto, etiqueta ID, referencia oculta, página, texto exacto, fase normalizada, archivo, interpretación y próxima revisión.","Una observación posterior no prueba el momento exacto entre dos consultas; solo prueba que el estado era visible al segundo control. Mantén esta frontera cuando la interfaz se actualice tarde."]],
      ["Guardar objeto y etiqueta juntos",["Pedido, artículo de almacén, paquete y seguimiento son objetos distintos. No guardes números sin etiqueta. El tipo y el nombre visible evitan usar un paquete para explicar un artículo o un tracking para probar embalaje.","Añade una fila de correspondencia cuando aparezca la relación. Separa pedido-almacén, pedido-paquete y paquete-tracking. Si no se muestra, escribe no verificado y no deduzcas por fechas o dígitos."]],
      ["Separar tres tiempos",["Registra hora del evento, hora mostrada de actualización y hora de consulta. Muchas filas solo tendrán la tercera, que demuestra cuándo el estado estaba visible.","Incluye zona horaria y conserva el valor original, preferiblemente ISO 8601. No conviertas una hora si desconoces su zona. Una captura con solo fecha no recibe una hora inventada."]],
      ["Normalizar sin borrar el texto fuente",["Puedes usar fases editoriales: compra solicitada, vendedor procesando, despacho nacional probado, recepción probada, registro de almacén disponible, paquete presentado, tracking disponible y evento de transportista probado. No son estados oficiales.","Presentar paquete no prueba aceptación del transportista; una referencia no prueba escaneo; una foto no fija la hora de entrega. Eleva la fuerza de la fase solo cuando la evidencia lo permite."]],
      ["Adjuntar pruebas seguras",["Cada fila apunta a sección de cuenta, página, archivo y hora. Usa nombres por objeto-fase-hora-versión. Guarda originales en privado y oculta nombre, dirección, teléfono, cuenta, pago, referencias completas, QR y tokens.","Añade una nota de contexto a la captura. Conserva suficiente página sin guardar datos irrelevantes. Indica cuándo la fuente es una página autenticada y no una política pública."]],
      ["Registrar decisión y próxima revisión",["Anota la consecuencia: ninguna acción, verificar variante, esperar vendedor, revisar almacén, pausar paquete o consultar transportista. Son decisiones del usuario, no instrucciones oficiales.","Usa condiciones, no plazos inventados: tras nuevo estado, cuando aparezca el registro o al mostrarse tracking. Una fecha oficial se guarda en su propia fuente fechada."]],
      ["Auditar antes de confiar",["Busca duplicados, historial sobrescrito, zonas ausentes, IDs sin etiqueta, cambios de fase sin prueba y archivos rotos. Los huecos son aceptables si son visibles. Mantén observaciones contradictorias con sus horas.","La cronología mínima usa una fila por cambio, objetos separados, texto original, tres tiempos posibles, fase normalizada, prueba privada, interpretación y próximo control. No promete rapidez; muestra lo confirmado y desconocido."]],
    ],faqs:[["¿Registrar cada visita?","No; registra cambios o una comprobación sin cambio cuando esa ausencia sea relevante."],["¿Sin hora visible?","Guarda la hora de consulta y marca la hora del evento como desconocida."],["¿Pedido y paquete juntos?","Sí, pero separa objetos y añade una fila de correspondencia."],["¿Cómo compartir?","Oculta datos personales, cuenta, pago, QR y referencias completas."]]
  },
  fr:{
    title:"Créer une chronologie de commande Kakobuy : les champs essentiels",tag:"Dossiers colis et contrôle",read:"Guide opérationnel de 15 minutes",reviewed:"Sources officielles vérifiées le 2 sept. 2026",lede:"Une chronologie utile note ce qui a changé, où l’état est apparu et quand il a été observé. Quelques champs stables reconstruisent le processus sans inventer les événements manquants.",sources,
    sections:[
      ["Un journal de preuves, pas une prévision",["La chronologie répond : quel objet, quel texte et quelle heure d’observation ? Elle ne promet ni expédition vendeur, ni réception entrepôt, ni livraison. Le flux public distingue commande, entrepôt, soumission du colis et transport, sans durée garantie universelle.","Préservez l’incertitude. Sans événement d’expédition, il reste non vérifié. Si l’entrepôt n’affiche pas l’heure de réception, notez votre première observation et laissez l’heure réelle inconnue. Ne remplissez pas les vides par supposition."]],
      ["Une ligne par changement observé",["Ajoutez une ligne quand l’état, l’identifiant, le contexte de page ou la décision change. Champs minimum : heure de contrôle, objet, libellé ID, référence masquée, page, texte exact, étape normalisée, fichier, interprétation et prochain contrôle.","Une observation ultérieure ne prouve pas le moment exact entre deux contrôles. Elle prouve seulement que le nouvel état était visible au second contrôle, même si l’interface s’est mise à jour en retard."]],
      ["Associer type d’objet et libellé",["Commande, article d’entrepôt, colis et suivi sont distincts. Ne conservez jamais un numéro sans libellé. Le type et le nom visible empêchent d’utiliser un colis pour expliquer un article ou un suivi pour prouver l’emballage.","Ajoutez une ligne de correspondance quand le lien apparaît. Séparez commande-entrepôt, commande-colis et colis-suivi. Si le lien n’est pas montré, notez non vérifié au lieu d’inférer par dates ou chiffres."]],
      ["Séparer trois heures",["Distinguez heure de l’événement, heure de mise à jour affichée et heure de votre contrôle. Beaucoup de lignes n’auront que la troisième ; elle établit quand l’état était visible.","Conservez fuseau et valeur originale, idéalement ISO 8601. Ne convertissez pas sans connaître le fuseau. Une capture datée sans heure reste une preuve à la date seulement."]],
      ["Normaliser sans effacer le libellé source",["Utilisez des étapes éditoriales : achat demandé, vendeur en traitement, expédition nationale prouvée, réception prouvée, dossier entrepôt disponible, colis soumis, suivi disponible et événement transporteur prouvé. Ce ne sont pas des statuts officiels.","Soumettre un colis ne prouve pas l’acceptation transporteur ; une référence ne prouve pas un scan ; une photo ne fixe pas l’heure de livraison. Renforcez l’étape uniquement avec une preuve suffisante."]],
      ["Joindre des preuves respectueuses de la vie privée",["Chaque ligne pointe vers section du compte, page, fichier et heure. Nommez les fichiers objet-étape-heure-version. Gardez les originaux privés et masquez nom, adresse, téléphone, compte, paiement, références complètes, QR et jetons.","Ajoutez une note de contexte à chaque capture. Gardez assez de page pour comprendre sans conserver de données inutiles. Indiquez quand la source est une page authentifiée et non une règle publique."]],
      ["Consigner décision et prochain contrôle",["Notez l’effet : aucune action, vérifier la variante, attendre le vendeur, examiner l’entrepôt, retenir le colis ou consulter le transporteur. Ce sont des décisions utilisateur, pas des instructions officielles.","Définissez une condition plutôt qu’un délai inventé : après un nouvel état, à l’apparition du dossier ou lorsque le suivi est montré. Toute échéance officielle garde sa propre source datée."]],
      ["Auditer avant utilisation",["Cherchez doublons, historique écrasé, fuseaux absents, IDs sans libellé, promotions d’étape non prouvées et fichiers illisibles. Les lacunes sont admises si elles restent visibles. Conservez les deux observations contradictoires.","La chronologie minimale a une ligne par changement, des objets séparés, le texte original, trois temps possibles, une étape normalisée, une preuve protégée, une interprétation et un prochain contrôle. Elle montre le confirmé et l’inconnu sans promettre la vitesse."]],
    ],faqs:[["Faut-il noter chaque visite ?","Non, seulement les changements ou un contrôle sans changement lorsque cette absence compte."],["Aucun horodatage ?","Notez votre heure de contrôle et laissez l’heure de l’événement inconnue."],["Commande et colis ensemble ?","Oui dans une chronologie, mais avec objets séparés et une ligne de correspondance."],["Partager sans risque ?","Masquez données personnelles, compte, paiement, QR et références complètes."]]
  },
  it:{
    title:"Creare una timeline ordine Kakobuy: i campi minimi",tag:"Registri pacco e controllo",read:"Guida operativa di 15 minuti",reviewed:"Fonti ufficiali verificate il 2 set 2026",lede:"Una timeline utile registra cosa è cambiato, dove è apparso lo stato e quando è stato osservato. Pochi campi stabili ricostruiscono il processo senza inventare eventi mancanti.",sources,
    sections:[
      ["Un registro di prove, non una previsione",["La timeline risponde: quale oggetto, quale testo e quale ora di osservazione? Non promette spedizione del venditore, ingresso in magazzino o consegna. Il flusso pubblico separa ordine, magazzino, invio del pacco e trasporto, senza una durata garantita universale.","Mantieni l’incertezza. Senza evento del venditore, la spedizione resta non verificata. Se il magazzino appare senza ora di ricezione, salva la prima osservazione e lascia sconosciuta l’ora reale. Non riempire i vuoti con date presunte."]],
      ["Una riga per cambiamento osservato",["Aggiungi una riga quando cambia stato, identificatore, contesto o decisione. Campi minimi: ora controllo, oggetto, etichetta ID, riferimento oscurato, pagina, testo esatto, fase normalizzata, file, interpretazione e prossimo controllo.","Un’osservazione successiva non prova il momento esatto tra due controlli. Dimostra solo che il nuovo stato era visibile al secondo controllo, anche se l’interfaccia è stata aggiornata tardi."]],
      ["Tenere insieme oggetto ed etichetta",["Ordine, articolo di magazzino, pacco e tracking sono oggetti distinti. Non salvare numeri senza etichetta. Tipo e nome visibile evitano di usare un pacco per spiegare un articolo o un tracking per provare l’imballaggio.","Aggiungi una riga di mappatura quando appare la relazione. Separa ordine-magazzino, ordine-pacco e pacco-tracking. Se il legame non è mostrato, scrivi non verificato invece di dedurre da date o cifre."]],
      ["Separare tre tempi",["Registra ora evento, ora di aggiornamento mostrata e ora del tuo controllo. Molte righe avranno solo la terza, che dimostra quando lo stato era visibile.","Conserva fuso e valore originale, preferibilmente ISO 8601. Non convertire senza conoscere il fuso. Una schermata con sola data non riceve un’ora inventata."]],
      ["Normalizzare senza cancellare il testo fonte",["Usa fasi editoriali: acquisto richiesto, venditore in lavorazione, spedizione nazionale provata, ricezione provata, record magazzino disponibile, pacco inviato, tracking disponibile ed evento vettore provato. Non sono stati ufficiali.","Inviare il pacco non prova l’accettazione; un riferimento non prova una scansione; una foto non fissa l’ora di consegna. Rafforza la fase soltanto con prova sufficiente."]],
      ["Allegare prove sicure",["Ogni riga punta a sezione account, pagina, file e ora. Nomina i file oggetto-fase-ora-versione. Conserva gli originali privati e oscura nome, indirizzo, telefono, account, pagamento, riferimenti completi, QR e token.","Aggiungi una nota di contesto. Mantieni abbastanza pagina per capire, senza dati inutili. Segnala quando la fonte è una pagina autenticata e non una regola pubblica."]],
      ["Registrare decisione e prossimo controllo",["Annota l’effetto: nessuna azione, verificare variante, attendere venditore, esaminare magazzino, trattenere pacco o controllare vettore. Sono decisioni dell’utente, non istruzioni ufficiali.","Usa condizioni, non scadenze inventate: dopo un nuovo stato, quando appare il record o quando viene mostrato il tracking. Una scadenza ufficiale conserva la propria fonte datata."]],
      ["Verificare il registro prima dell’uso",["Cerca duplicati, storia sovrascritta, fusi mancanti, ID senza etichetta, promozioni di fase non provate e file illeggibili. I vuoti sono ammessi se visibili. Mantieni entrambe le osservazioni in conflitto.","La timeline minima usa una riga per cambiamento, oggetti separati, testo originale, tre tempi possibili, fase normalizzata, prova protetta, interpretazione e prossimo controllo. Mostra confermato e sconosciuto senza promettere velocità."]],
    ],faqs:[["Registrare ogni visita?","No, solo cambiamenti o controlli senza cambiamento quando l’assenza è rilevante."],["Nessun orario visibile?","Salva l’ora del controllo e lascia sconosciuta l’ora dell’evento."],["Ordine e pacco insieme?","Sì in una timeline, ma con oggetti separati e una riga di mappatura."],["Condivisione sicura?","Oscura dati personali, account, pagamento, QR e riferimenti completi."]]
  }
};
