import type { Locale } from "./site-data";
import type { ProArticle } from "./pro-article-data";

export type IdentifierArticle = ProArticle & { faqs: Array<[string,string]> };

const sources = [
  {label:"Kakobuy official homepage and public service flow",url:"https://www.kakobuy.com/"},
  {label:"Kakobuy official purchasing-flow information",url:"https://www.kakobuy.com/index/information?information_id=12"},
  {label:"Kakobuy official service introduction",url:"https://www.kakobuy.com/index/information?information_id=3"},
];

export const orderIdentifiersArticleData:Record<Locale,IdentifierArticle>={
  en:{
    title:"Kakobuy Order Number, Parcel Number and Tracking Number: Which ID to Use",
    tag:"Parcel records & workflow control",read:"14 min operations guide",reviewed:"Official sources reviewed 31 Aug 2026",
    lede:"A Kakobuy order number, parcel number and carrier tracking number identify different records. Map each ID to the object, stage and page it belongs to before you search, reconcile items or describe a status problem.",sources,
    sections:[
      ["Three identifiers, three different objects",[
        "Start with the object, not the digits. An order record represents a purchase-level item or seller transaction before it becomes part of an international package. A parcel record represents the package assembled from one or more warehouse items. A carrier tracking reference represents the shipment after a logistics provider accepts or registers it. The exact labels and formats can vary in the live interface, so this guide does not publish a permanent prefix, length or example that could quickly become false.",
        "Kakobuy’s public flow supports the stage distinction: users submit product orders, goods arrive at the warehouse for inspection, and selected items are later submitted for global shipping. The public service introduction also points users to package tracking from the account area. Those statements support a workflow map, but they do not prove that every account, route or carrier exposes the same fields at the same time. Record the label exactly as your current page shows it and keep the page context with the value.",
      ]],
      ["Use the order number for item-level questions",[
        "Use the order-side identifier when the question is about a purchased item before parcel submission: which listing was bought, which color or size was selected, whether the seller dispatched it, whether the warehouse received it, or which warehouse record belongs to it. Keep the source URL, ordered option, quantity and order-page status beside that ID. This turns the number into a usable record instead of an isolated string copied into a note.",
        "One parcel can contain several orders, so a parcel number is usually too broad when only one item is unclear. Conversely, an order number cannot describe the whole international package once multiple items have been consolidated. If support or your own audit asks what happened to a specific warehouse item, begin with the order record and then link it to any later parcel. Do not infer that nearby items share the same seller, status or after-sales eligibility merely because they will ship together.",
      ]],
      ["Use the parcel number for the submitted package",[
        "Use the parcel-side identifier when the question concerns the submitted package as a unit: which orders were included, which address snapshot was used, which packaging instructions were recorded, when submission occurred, or what package-level status the Kakobuy account shows. Save a contents manifest that maps every included order ID to this parcel ID. The map matters more than memorizing either number because it lets you reconstruct what the package was supposed to contain.",
        "A parcel record can exist before a carrier event is visible. Packing, confirmation and dispatch are operational handoffs, not synonyms. Do not label a parcel as moving internationally merely because it has been created in the account. Record the exact displayed status, the capture time and the page name. If the wording is ambiguous, write ‘parcel record created; carrier acceptance not yet evidenced’ rather than converting an internal status into a transport claim.",
      ]],
      ["Use the tracking number for carrier events",[
        "Use the tracking reference when the question is about carrier scans or transport events after the shipment enters a logistics network. Search it on the carrier surface identified by the current shipment record, not on an unrelated carrier chosen from memory. Save the carrier name as displayed, the tracking reference, the lookup URL or page name, the first observed event and the access date. A tracking number without its carrier and date can be difficult to interpret if a route uses handoffs.",
        "Do not treat every logistics-looking code as the final tracking number. A parcel ID, internal waybill, route reference or last-mile reference may coexist. A handoff can also introduce a second reference later. Keep each value in its own labeled field and record the relationship only when the live Kakobuy or carrier page shows it. If no carrier result appears, preserve that negative observation with a timestamp; do not declare the parcel lost or invent a waiting period from another route.",
      ]],
      ["Build a one-row identifier map",[
        "Create one row per parcel and use separate columns for parcel ID, included order IDs, carrier, current tracking reference, last-mile reference if explicitly shown, Kakobuy status, carrier event, page checked and checked-at time. Use ‘not shown’, ‘not assigned’ and ‘not checked’ as different values. Not shown means the page did not display a field; not assigned means the page explicitly says no value exists yet; not checked means your record is incomplete. That vocabulary prevents missing evidence from becoming a fictional status.",
        "For privacy-safe examples, use structural placeholders such as ORDER-A, PARCEL-1 and TRACK-X, never a realistic string that could belong to someone. A sample row might map ORDER-A and ORDER-B to PARCEL-1 while TRACK-X remains not shown. The example teaches relationships without pretending to be a customer record. In your private log, preserve the exact value, but redact most characters before sharing and never publish an address, phone number, account ID, QR code or complete tracking reference.",
      ]],
      ["Choose the ID from the question you are asking",[
        "Ask ‘what object and stage does this question concern?’ For an incorrect variant recorded at warehouse intake, use the order ID. For a package missing one expected order before submission, use the parcel ID plus the contents map and the relevant order ID. For a carrier scan that has not updated, use the tracking reference plus carrier and last observed event. For a mismatch between Kakobuy and carrier pages, provide both parcel and tracking identifiers with separate timestamps instead of forcing one status to overwrite the other.",
        "When writing to support, lead with a short issue statement, then the smallest useful identifier set. Include the account-page label exactly, not your own renamed field. Add the observed status, page, date and the action you want checked. More identifiers are not automatically better: unrelated order numbers can obscure the affected record, while a tracking number alone may not let the platform locate the source parcel. The goal is an auditable link, not a dump of every code in the account.",
      ]],
      ["Reconcile status without guessing",[
        "Two pages can be accurate while showing different layers. Kakobuy may show an internal parcel workflow state while a carrier page shows transport events. Compare the event meaning and timestamp before calling them contradictory. Record each statement verbatim enough to preserve meaning, but do not copy private data. If the carrier page has no result and the account shows only an internal status, the defensible conclusion is that no carrier event was verified at the check time.",
        "Keep a change log instead of editing history in place. Each entry should contain checked-at time, source page, identifier used, observed wording and the next decision. A new carrier scan adds a row; it does not erase the earlier no-result observation. This gives you a reproducible timeline and prevents a later screenshot from being presented as if it existed earlier. It also makes account-to-carrier handoffs easier to explain without publishing route or delivery-time promises.",
      ]],
      ["Final identifier checklist",[
        "Before relying on a code, verify six points: the copied value is complete; its visible label is saved; the page and account context are known; the object is order, parcel or carrier shipment; the observation has a date and time; and any cross-reference is supported by the live record. Re-copy rather than manually retyping long values, then compare the beginning and end. Store identifiers as text so spreadsheet software does not remove leading zeros or convert them to scientific notation.",
        "Stop when the relationship is not evidenced. Do not guess that a code is tracking because a third-party search accepts it, or that a parcel contains an order because the dates are close. Return to the current official account flow, capture the labels that are actually visible and ask for the missing mapping with the smallest relevant set of redacted details. A good record tells you which ID supports which operational fact—and clearly marks what remains unknown.",
      ]],
    ],
    faqs:[
      ["Is a Kakobuy parcel number the same as a tracking number?","Treat them as separate fields unless the current Kakobuy record explicitly shows they are the same. A parcel ID identifies the platform package; a tracking reference supports carrier events."],
      ["Which number should I give for one warehouse item?","Start with the order-side identifier and the exact item or variant. Add the parcel ID only if that order has already been mapped into a submitted parcel."],
      ["Why can a parcel exist before tracking works?","A platform parcel record can be created during packing or submission before a carrier reference or event is visible. Record the displayed state without inventing a transport event."],
      ["Can I publish my tracking number when asking for help?","Avoid posting complete identifiers publicly. Redact most characters and remove names, addresses, phone numbers, account data and QR codes."],
    ],
  },
  de:{title:"Kakobuy-Bestellnummer, Paketnummer und Trackingnummer: Welche ID wofür?",tag:"Paketdaten & Ablaufkontrolle",read:"14-Minuten-Ablaufleitfaden",reviewed:"Offizielle Quellen geprüft am 31. Aug. 2026",lede:"Bestellnummer, Paketnummer und Carrier-Trackingnummer bezeichnen unterschiedliche Datensätze. Ordne jede ID zuerst Objekt, Phase und Seite zu.",sources,sections:[
    ["Drei Kennungen für drei Objekte",["Beginne beim Objekt, nicht bei den Ziffern. Der Bestelldatensatz steht für einen gekauften Artikel oder Händlerauftrag vor dem internationalen Paket. Der Paketdatensatz steht für die aus Lagerartikeln zusammengestellte Sendung. Die Trackingreferenz steht für Ereignisse beim Logistikdienstleister. Live-Bezeichnungen und Formate können sich ändern; deshalb veröffentlicht dieser Leitfaden keine dauerhaften Präfixe oder Längen.","Der öffentliche Kakobuy-Ablauf trennt Bestellung, Lagereingang mit Prüfung und spätere internationale Paketeinreichung. Die Servicebeschreibung verweist außerdem auf Paketverfolgung im Kontobereich. Das stützt die Phasenkarte, beweist aber keine identischen Felder für jedes Konto oder jede Linie. Speichere daher die sichtbare Bezeichnung und den Seitenkontext zusammen mit dem Wert."]],
    ["Bestellnummer für Artikelfragen",["Nutze die Bestellkennung bei Fragen zu Angebot, Variante, Menge, Händler-Versand oder Lagereingang. Speichere Quell-URL, bestellte Option und sichtbaren Status neben der ID. So wird aus einer Nummer ein brauchbarer Datensatz.","Ein Paket kann mehrere Bestellungen enthalten. Die Paketnummer ist daher zu grob, wenn nur ein Artikel unklar ist; die Bestellnummer beschreibt umgekehrt nicht das ganze konsolidierte Paket. Beginne beim betroffenen Bestelldatensatz und verknüpfe ihn anschließend mit dem späteren Paket."]],
    ["Paketnummer für die eingereichte Sendung",["Nutze die Paketkennung für Inhalt, Adresssnapshot, Verpackungsanweisungen, Einreichung und den paketweiten Kakobuy-Status. Eine Inhaltsliste sollte jede enthaltene Bestell-ID der Paket-ID zuordnen. Diese Abbildung ist wichtiger als das Auswendiglernen der Nummern.","Ein Paketdatensatz kann vor dem ersten Carrier-Ereignis existieren. Packen, Bestätigen und Versenden sind Übergaben, keine Synonyme. Speichere Wortlaut, Uhrzeit und Seite. Bei Unklarheit schreibe: Paketdatensatz erstellt; Carrier-Annahme noch nicht belegt."]],
    ["Trackingnummer für Carrier-Ereignisse",["Nutze die Trackingreferenz für Scans und Transportereignisse. Suche beim im aktuellen Datensatz genannten Carrier und speichere Carriername, Referenz, Seite, erstes Ereignis und Datum. Eine Nummer ohne Carrier und Zeit ist bei Übergaben schwer einzuordnen.","Nicht jeder Logistikcode ist die endgültige Trackingnummer. Paket-ID, interner Frachtbrief, Linienreferenz und letzte Meile können nebeneinander bestehen. Halte jeden Wert in einem beschrifteten Feld und verknüpfe ihn nur, wenn Live-Seite oder Carrier die Beziehung zeigt."]],
    ["Eine Kennungszeile anlegen",["Lege pro Paket eine Zeile an: Paket-ID, Bestell-IDs, Carrier, aktuelle Trackingreferenz, letzte Meile falls sichtbar, Kakobuy-Status, Carrier-Ereignis, geprüfte Seite und Prüfzeit. Unterscheide „nicht angezeigt“, „nicht vergeben“ und „nicht geprüft“.","Verwende in Beispielen Platzhalter wie ORDER-A, PARCEL-1 und TRACK-X. Im privaten Protokoll bleibt der exakte Wert erhalten; vor jeder Weitergabe werden Zeichen, Adresse, Telefon, Konto und QR-Code geschwärzt."]],
    ["ID nach der Frage auswählen",["Frage zuerst nach Objekt und Phase. Falsche Variante beim Lagereingang: Bestell-ID. Fehlender erwarteter Inhalt vor Einreichung: Paket-ID plus Inhaltskarte und betroffene Bestell-ID. Fehlender Carrier-Scan: Trackingreferenz, Carrier und letztes Ereignis.","Im Supportfall beginne mit einem kurzen Problem, dann der kleinsten nützlichen ID-Gruppe. Füge sichtbare Bezeichnung, Status, Seite, Datum und gewünschte Prüfung hinzu. Viele unbeteiligte Nummern verdecken den betroffenen Datensatz."]],
    ["Status ohne Raten abgleichen",["Kakobuy und Carrier können unterschiedliche Ebenen korrekt darstellen. Vergleiche Bedeutung und Zeitstempel. Zeigt die Carrierseite kein Ergebnis und das Konto nur einen internen Status, lautet die belegbare Aussage: Zum Prüfzeitpunkt wurde kein Carrier-Ereignis verifiziert.","Führe ein Änderungsprotokoll statt Geschichte zu überschreiben: Prüfzeit, Quelle, verwendete ID, Wortlaut und nächste Entscheidung. Ein neuer Scan ergänzt eine Zeile und löscht die frühere Beobachtung nicht."]],
    ["Abschließende Kennungsprüfung",["Prüfe vollständigen Wert, sichtbare Bezeichnung, Seite, Objektklasse, Zeitstempel und belegte Querverknüpfung. Kopiere lange Werte und vergleiche Anfang und Ende. Speichere sie als Text, damit Tabellen keine führenden Nullen entfernen.","Stoppe bei unbelegter Beziehung. Ein Code wird nicht allein dadurch zu Tracking, dass eine fremde Suche ihn akzeptiert. Kehre zum aktuellen Kontodatensatz zurück und frage mit möglichst wenigen geschwärzten Daten nach der fehlenden Zuordnung."]]],faqs:[["Sind Paketnummer und Trackingnummer identisch?","Behandle sie getrennt, solange der aktuelle Datensatz keine Gleichheit zeigt."],["Welche Nummer gehört zu einem Lagerartikel?","Beginne mit der Bestellkennung; ergänze die Paket-ID erst nach belegter Zuordnung."],["Warum existiert ein Paket vor dem Tracking?","Der interne Paketdatensatz kann vor Carrier-Referenz oder Scan entstehen."],["Darf ich Tracking öffentlich posten?","Nein. Schwärze die meisten Zeichen und alle personenbezogenen Daten."]]},
  es:{title:"Número de pedido, paquete y seguimiento de Kakobuy: qué ID usar",tag:"Registros de paquete y control",read:"Guía operativa de 14 minutos",reviewed:"Fuentes oficiales revisadas el 31 ago 2026",lede:"El número de pedido, el número de paquete y la referencia del transportista identifican registros distintos. Asigna cada ID a su objeto, fase y página.",sources,sections:[
    ["Tres identificadores, tres objetos",["Empieza por el objeto, no por los dígitos. El pedido representa un artículo o compra antes del paquete internacional; el paquete representa los artículos reunidos en almacén; el seguimiento representa eventos del transportista. Las etiquetas y formatos pueden cambiar, por lo que no publicamos prefijos o longitudes permanentes.","El flujo público de Kakobuy separa pedido, llegada e inspección en almacén y presentación posterior del paquete. La introducción del servicio también dirige al seguimiento desde la cuenta. Esto respalda el mapa de fases, pero no garantiza los mismos campos en toda cuenta o ruta. Guarda la etiqueta visible y la página junto al valor."]],
    ["Número de pedido para el artículo",["Usa la ID de pedido para ficha comprada, variante, cantidad, envío del vendedor o recepción de almacén. Guarda URL fuente, opción y estado visible con la ID.","Un paquete puede incluir varios pedidos. El número de paquete es demasiado amplio para un solo artículo y el pedido no describe todo el paquete consolidado. Empieza por el pedido afectado y enlázalo después con el paquete."]],
    ["Número de paquete para el envío presentado",["Usa la ID de paquete para contenido, dirección guardada, instrucciones de embalaje, presentación y estado de paquete en Kakobuy. Un manifiesto debe mapear cada pedido incluido al paquete.","El registro de paquete puede existir antes de un evento del transportista. Embalado, confirmado y despachado no son sinónimos. Guarda texto, hora y página; si falta prueba, escribe que la aceptación del transportista aún no está verificada."]],
    ["Seguimiento para eventos del transportista",["Usa la referencia de seguimiento para escaneos y eventos de transporte. Consulta al transportista mostrado y guarda nombre, referencia, página, primer evento y fecha.","No todo código logístico es el seguimiento final. Pueden coexistir ID de paquete, guía interna, referencia de ruta y última milla. Mantén campos separados y enlázalos solo cuando la página vigente muestre la relación."]],
    ["Crear una fila de correspondencias",["Una fila por paquete: ID de paquete, IDs de pedido, transportista, seguimiento, última milla si aparece, estado Kakobuy, evento, página y hora. Distingue «no mostrado», «no asignado» y «no revisado».","En ejemplos usa ORDER-A, PARCEL-1 y TRACK-X. Conserva el valor real solo en privado y oculta caracteres, dirección, teléfono, cuenta y QR antes de compartir."]],
    ["Elegir la ID según la pregunta",["Pregunta qué objeto y fase intervienen. Variante incorrecta en entrada: pedido. Contenido esperado ausente antes de presentar: paquete más manifiesto y pedido. Escaneo parado: seguimiento, transportista y último evento.","Para soporte, describe el problema y aporta el conjunto mínimo. Incluye etiqueta visible, estado, página, fecha y comprobación solicitada. Volcar todos los códigos puede ocultar el registro relevante."]],
    ["Conciliar estados sin adivinar",["Kakobuy y el transportista pueden mostrar capas distintas. Compara significado y hora. Si el transportista no devuelve resultado y la cuenta solo muestra estado interno, concluye que no se verificó evento de transportista en ese momento.","Mantén un registro de cambios: hora, fuente, ID, texto y próxima decisión. Un nuevo escaneo añade una fila y no borra la observación anterior."]],
    ["Lista final",["Comprueba valor completo, etiqueta, página, objeto, hora y relación demostrada. Copia valores largos y guárdalos como texto para conservar ceros iniciales.","Detente si la relación no está probada. Que una búsqueda acepte el código no lo convierte en seguimiento. Vuelve al registro actual y solicita la correspondencia con pocos datos redactados."]]],faqs:[["¿Paquete y seguimiento son lo mismo?","Trátalos como campos separados salvo que la página vigente indique lo contrario."],["¿Qué número uso para un artículo?","Empieza por la ID de pedido y añade el paquete tras mapearlo."],["¿Por qué hay paquete antes de seguimiento?","El registro interno puede existir antes de la referencia o el escaneo."],["¿Puedo publicar el seguimiento?","No completo; oculta caracteres y datos personales."]]},
  fr:{title:"Numéro de commande, colis et suivi Kakobuy : quel identifiant utiliser ?",tag:"Registres colis & contrôle",read:"Guide opérationnel de 14 minutes",reviewed:"Sources officielles vérifiées le 31 août 2026",lede:"Commande, colis et référence transporteur identifient des dossiers différents. Associez chaque ID à son objet, son étape et sa page.",sources,sections:[
    ["Trois identifiants, trois objets",["Commencez par l’objet, non par les chiffres. La commande représente un article acheté avant le colis international ; le colis représente les articles assemblés en entrepôt ; le suivi représente les événements du transporteur. Les libellés et formats peuvent changer : ce guide ne fige ni préfixe ni longueur.","Le parcours public Kakobuy sépare commande, réception et contrôle en entrepôt, puis soumission du colis. La présentation du service renvoie aussi au suivi depuis le compte. Cela confirme les étapes, sans garantir des champs identiques pour chaque compte ou ligne. Gardez le libellé visible et la page avec la valeur."]],
    ["Numéro de commande pour l’article",["Utilisez l’ID de commande pour la fiche achetée, la variante, la quantité, l’envoi vendeur ou la réception. Conservez URL source, option et statut visible.","Un colis peut contenir plusieurs commandes. Le numéro de colis est trop large pour un seul article et la commande ne décrit pas tout le colis. Commencez par la commande concernée puis reliez-la au colis."]],
    ["Numéro de colis pour l’envoi soumis",["Utilisez l’ID de colis pour le contenu, l’adresse enregistrée, les instructions d’emballage, la soumission et le statut Kakobuy. Un manifeste doit relier chaque commande incluse au colis.","Le dossier colis peut exister avant un événement transporteur. Emballage, confirmation et expédition ne sont pas synonymes. Gardez texte, heure et page ; sans preuve, notez que l’acceptation transporteur n’est pas encore établie."]],
    ["Suivi pour les événements transporteur",["Utilisez la référence de suivi pour les scans et événements de transport. Interrogez le transporteur affiché et gardez nom, référence, page, premier événement et date.","Tout code logistique n’est pas le suivi final. ID colis, bordereau interne, route et dernière étape peuvent coexister. Séparez les champs et ne créez le lien que si la page actuelle le montre."]],
    ["Construire une ligne de correspondance",["Une ligne par colis : ID colis, commandes, transporteur, suivi, dernière étape si affichée, statut Kakobuy, événement, page et heure. Distinguez « non affiché », « non attribué » et « non vérifié ».","Pour un exemple, utilisez ORDER-A, PARCEL-1 et TRACK-X. Gardez la vraie valeur en privé et masquez caractères, adresse, téléphone, compte et QR avant partage."]],
    ["Choisir l’ID selon la question",["Demandez quel objet et quelle étape sont concernés. Mauvaise variante à l’entrée : commande. Contenu attendu absent avant soumission : colis, manifeste et commande. Scan bloqué : suivi, transporteur et dernier événement.","Au support, donnez un problème bref et le minimum d’identifiants. Ajoutez libellé, statut, page, date et contrôle souhaité. Trop de codes peuvent masquer le dossier utile."]],
    ["Rapprocher les statuts sans supposer",["Kakobuy et le transporteur peuvent montrer des couches différentes. Comparez sens et horodatage. Si le transporteur ne renvoie rien et le compte montre seulement un statut interne, concluez qu’aucun événement transporteur n’a été vérifié à cet instant.","Tenez un journal : heure, source, ID, texte et décision suivante. Un nouveau scan ajoute une ligne sans effacer l’observation précédente."]],
    ["Contrôle final",["Vérifiez valeur complète, libellé, page, objet, heure et lien démontré. Copiez les longues valeurs et stockez-les comme texte pour conserver les zéros initiaux.","Arrêtez-vous si la relation n’est pas prouvée. Un moteur qui accepte un code n’en fait pas un suivi. Revenez au dossier actuel et demandez la correspondance avec peu de données masquées."]]],faqs:[["Colis et suivi sont-ils identiques ?","Traitez-les séparément sauf indication explicite de la page actuelle."],["Quel numéro pour un article ?","Commencez par la commande et ajoutez le colis après correspondance."],["Pourquoi un colis avant le suivi ?","Le dossier interne peut précéder référence ou scan transporteur."],["Puis-je publier le suivi ?","Pas en entier ; masquez caractères et données personnelles."]]},
  it:{title:"Numero ordine, pacco e tracking Kakobuy: quale ID usare",tag:"Registri pacco e controllo",read:"Guida operativa di 14 minuti",reviewed:"Fonti ufficiali verificate il 31 ago 2026",lede:"Numero ordine, numero pacco e riferimento del corriere identificano record diversi. Collega ogni ID a oggetto, fase e pagina.",sources,sections:[
    ["Tre identificatori, tre oggetti",["Parti dall’oggetto, non dalle cifre. L’ordine rappresenta un articolo acquistato prima del pacco internazionale; il pacco rappresenta gli articoli riuniti in magazzino; il tracking rappresenta gli eventi del corriere. Etichette e formati possono cambiare, quindi la guida non fissa prefissi o lunghezze.","Il flusso pubblico Kakobuy separa ordine, arrivo e controllo in magazzino e successiva presentazione del pacco. La descrizione del servizio rimanda anche al tracking nell’account. Ciò sostiene la mappa delle fasi, non campi identici per ogni account o linea. Salva etichetta visibile e pagina con il valore."]],
    ["Numero ordine per l’articolo",["Usa l’ID ordine per inserzione, variante, quantità, invio del venditore o ricezione. Conserva URL fonte, opzione e stato visibile.","Un pacco può includere più ordini. Il numero pacco è troppo ampio per un solo articolo e l’ordine non descrive tutto il pacco consolidato. Parti dall’ordine interessato e collegalo poi al pacco."]],
    ["Numero pacco per la spedizione presentata",["Usa l’ID pacco per contenuto, indirizzo salvato, istruzioni di imballaggio, invio e stato Kakobuy. Un manifesto deve associare ogni ordine incluso al pacco.","Il record pacco può esistere prima di un evento del corriere. Imballato, confermato e spedito non sono sinonimi. Salva testo, ora e pagina; senza prova, indica che l’accettazione del corriere non è verificata."]],
    ["Tracking per gli eventi del corriere",["Usa il riferimento di tracking per scansioni ed eventi di trasporto. Cerca presso il corriere mostrato e salva nome, riferimento, pagina, primo evento e data.","Non ogni codice logistico è il tracking finale. ID pacco, lettera di vettura interna, rotta e ultimo miglio possono coesistere. Mantieni campi separati e collegali solo quando la pagina corrente mostra la relazione."]],
    ["Creare una riga di mappatura",["Una riga per pacco: ID pacco, ordini, corriere, tracking, ultimo miglio se visibile, stato Kakobuy, evento, pagina e ora. Distingui «non mostrato», «non assegnato» e «non controllato».","Negli esempi usa ORDER-A, PARCEL-1 e TRACK-X. Conserva il valore vero in privato e oscura caratteri, indirizzo, telefono, account e QR prima di condividere."]],
    ["Scegliere l’ID dalla domanda",["Chiedi quale oggetto e fase sono coinvolti. Variante errata all’ingresso: ordine. Contenuto atteso assente prima dell’invio: pacco, manifesto e ordine. Scansione ferma: tracking, corriere e ultimo evento.","Al supporto fornisci un problema breve e il minimo di ID. Aggiungi etichetta, stato, pagina, data e controllo richiesto. Troppi codici possono nascondere il record utile."]],
    ["Conciliare gli stati senza ipotesi",["Kakobuy e corriere possono mostrare livelli diversi. Confronta significato e ora. Se il corriere non dà risultati e l’account mostra solo stato interno, concludi che nessun evento del corriere è stato verificato a quell’ora.","Mantieni un registro modifiche: ora, fonte, ID, testo e prossima decisione. Una nuova scansione aggiunge una riga senza cancellare l’osservazione precedente."]],
    ["Controllo finale",["Verifica valore completo, etichetta, pagina, oggetto, ora e collegamento provato. Copia i valori lunghi e salvali come testo per mantenere gli zeri iniziali.","Fermati se la relazione non è provata. Un motore che accetta il codice non lo rende tracking. Torna al record attuale e chiedi la mappatura con pochi dati oscurati."]]],faqs:[["Numero pacco e tracking sono uguali?","Trattali separatamente salvo indicazione esplicita della pagina attuale."],["Quale numero per un articolo?","Parti dall’ordine e aggiungi il pacco dopo la mappatura."],["Perché un pacco prima del tracking?","Il record interno può precedere riferimento o scansione."],["Posso pubblicare il tracking?","Non completo; oscura caratteri e dati personali."]]},
};
