import type { Locale, PageKey } from "./site-data";

type IndependentPage = Exclude<PageKey, "home" | "qcArticle" | "shippingArticle" | "storageArticle">;

export const seoPageIntro: Record<Locale, Record<IndependentPage, [string, string]>> = {
  en: {
    spreadsheet: ["Kakobuy Spreadsheet 2026", "A checked product index that keeps images, prices and destination routes aligned—and explains what still needs verifying before you order."],
    finds: ["Kakobuy Finds With Checked Product Routes", "Browse current product records whose card image and destination were reviewed together. Prices remain dated snapshots, not final landed costs."],
    guide: ["How to Buy With Kakobuy: Step-by-Step Guide", "Follow the official agent sequence from Chinese marketplace link to item payment, warehouse QC and international parcel submission."],
    qc: ["Kakobuy QC Photo Guide", "Use a repeatable inspection method for identity, shape, construction and decision-critical evidence before the parcel leaves the warehouse."],
    shipping: ["Kakobuy Shipping Calculator and Weight Guide", "Compare live routes with realistic weight and dimensions, understand volumetric billing, and separate platform services from destination taxes."],
    faq: ["Kakobuy Fees, Storage and Returns FAQ", "Clear, dated answers based on Kakobuy's public help pages, with variable fees and policies described as snapshots rather than guarantees."],
    articles: ["Kakobuy Guides and Research", "Long-form, source-checked guides covering the Kakobuy spreadsheet, QC photos, shipping cost, 100-day storage and seller returns."],
  },
  de: {
    spreadsheet: ["Kakobuy Spreadsheet 2026", "Geprüfte Produktwege mit passenden Bildern, Preisen und Zielen – plus klare Hinweise, was vor der Bestellung noch geprüft werden muss."],
    finds: ["Kakobuy-Funde mit geprüften Zielen", "Aktuelle Datensätze, deren Kartenbild und Ziel gemeinsam kontrolliert wurden. Preise bleiben datierte Momentaufnahmen."],
    guide: ["Mit Kakobuy bestellen: Schritt für Schritt", "Vom chinesischen Produktlink über Artikelzahlung und Lager-QC bis zur Einreichung des internationalen Pakets."],
    qc: ["Kakobuy QC-Foto-Leitfaden", "Identität, Form, Verarbeitung und entscheidende Belege vor dem Versand systematisch prüfen."],
    shipping: ["Kakobuy Versandkosten- und Gewichtsleitfaden", "Live-Linien mit realistischen Maßen vergleichen, Volumengewicht verstehen und Plattformdienste von Einfuhrabgaben trennen."],
    faq: ["Kakobuy Gebühren, Lagerung und Rückgaben", "Datierte Antworten aus öffentlichen Kakobuy-Hilfeseiten; variable Regeln werden nicht als Garantien dargestellt."],
    articles: ["Kakobuy Leitfäden und Recherche", "Ausführliche, quellengeprüfte Beiträge zu Spreadsheet, QC, Versand, 100 Tagen Lagerung und Verkäufer-Rückgaben."],
  },
  es: {
    spreadsheet: ["Hoja Kakobuy 2026", "Índice revisado que mantiene alineados imagen, precio y destino y explica qué verificar antes de pedir."],
    finds: ["Hallazgos Kakobuy con rutas revisadas", "Registros actuales cuya imagen y destino se comprobaron juntos. Los precios son capturas fechadas, no costes finales."],
    guide: ["Cómo comprar con Kakobuy: paso a paso", "Del enlace del marketplace chino al pago, QC de almacén y envío del paquete internacional."],
    qc: ["Guía de fotos QC de Kakobuy", "Método repetible para identidad, forma, construcción y evidencia decisiva antes del envío."],
    shipping: ["Calculadora y guía de peso Kakobuy", "Compara rutas con peso y medidas realistas, entiende el volumétrico y separa servicios de impuestos de destino."],
    faq: ["Comisiones, almacén y devoluciones Kakobuy", "Respuestas fechadas basadas en la ayuda pública, sin convertir términos variables en garantías."],
    articles: ["Guías e investigación Kakobuy", "Artículos extensos y revisados sobre hoja, QC, envío, 100 días de almacén y devoluciones del vendedor."],
  },
  fr: {
    spreadsheet: ["Tableur Kakobuy 2026", "Index vérifié où image, prix et destination restent alignés, avec les contrôles à faire avant commande."],
    finds: ["Sélections Kakobuy aux routes vérifiées", "Fiches actuelles dont l'image et la destination ont été contrôlées ensemble. Les prix sont des instantanés datés."],
    guide: ["Acheter avec Kakobuy : guide étape par étape", "Du lien de marketplace chinoise au paiement, au QC d'entrepôt et à la soumission du colis international."],
    qc: ["Guide des photos QC Kakobuy", "Méthode répétable pour identité, forme, fabrication et preuve décisive avant expédition."],
    shipping: ["Calculateur et guide de poids Kakobuy", "Comparez les lignes avec poids et dimensions réalistes et séparez services de plateforme et taxes de destination."],
    faq: ["Frais, stockage et retours Kakobuy", "Réponses datées issues des pages d'aide publiques, sans transformer des conditions variables en garanties."],
    articles: ["Guides et recherches Kakobuy", "Articles longs et vérifiés sur le tableur, le QC, la livraison, les 100 jours de stockage et les retours vendeur."],
  },
  it: {
    spreadsheet: ["Foglio Kakobuy 2026", "Indice verificato che mantiene allineati immagine, prezzo e destinazione e indica cosa controllare prima dell'ordine."],
    finds: ["Prodotti Kakobuy con percorsi verificati", "Schede attuali con immagine e destinazione controllate insieme. I prezzi sono istantanee datate."],
    guide: ["Come comprare con Kakobuy: guida passo passo", "Dal link del marketplace cinese al pagamento, QC di magazzino e invio del pacco internazionale."],
    qc: ["Guida alle foto QC Kakobuy", "Metodo ripetibile per identità, forma, costruzione e prova decisiva prima della spedizione."],
    shipping: ["Calcolatore e guida peso Kakobuy", "Confronta linee con peso e misure realistiche e separa servizi di piattaforma e tasse di destinazione."],
    faq: ["Costi, deposito e resi Kakobuy", "Risposte datate basate sulle pagine pubbliche, senza trasformare termini variabili in garanzie."],
    articles: ["Guide e ricerche Kakobuy", "Articoli lunghi verificati su foglio, QC, spedizione, 100 giorni di deposito e resi del venditore."],
  },
};

export const officialFaqs: Record<Locale, Array<[string, string]>> = {
  en: [
    ["Is this website Kakobuy?", "No. Kakobuy VIP is an independent research and discovery site. It does not process orders or hold customer funds."],
    ["What is the public Kakobuy buying flow?", "Kakobuy's beginner material describes copying a product link from a Chinese marketplace, pasting it into Kakobuy, selecting and paying for the item, waiting for warehouse arrival and quality checking, then submitting an international parcel."],
    ["Does Kakobuy currently advertise free warehouse storage?", "Yes. Its public service introduction and beginner guide currently state 100 days of free warehouse storage. This was checked on 29 August 2026; confirm the live account policy before relying on it."],
    ["Does Kakobuy charge a basic shopping-agent handling fee?", "Its Services & Fees help page currently says the basic shopping-agent service adds no handling charge apart from item cost and shipping. Optional value-added services can cost extra."],
    ["How long can a seller return or refund take?", "Kakobuy's 5-Day Return/Exchange help page says the process usually takes 7–15 days depending on seller confirmation, and relevant return shipping can be deducted. This is guidance, not a guaranteed completion time."],
    ["What does Kakobuy warehouse QC cover?", "Kakobuy's help page says inspectors can check appearance and whether accessories are complete, but cannot power on equipment to test quality. Photos also do not prove material, durability, comfort or authenticity."],
    ["Is the 5-Day Return/Exchange Guarantee universal?", "No. Kakobuy describes it as an after-sales service offered by sellers on supported third-party marketplace products. Eligibility depends on the exact item and current terms."],
    ["Is a shipping estimate the final cost or delivery guarantee?", "No. Final cost can change with packed weight, dimensions, route rules, classification and services. Delivery windows can also change because of customs, carrier capacity and local handoff."],
  ],
  de: [
    ["Ist diese Website Kakobuy?", "Nein. Kakobuy VIP ist eine unabhängige Recherche- und Suchseite und verarbeitet keine Bestellungen oder Kundengelder."],
    ["Wie beschreibt Kakobuy den Kaufablauf?", "Produktlink eines chinesischen Marktplatzes kopieren, bei Kakobuy einfügen, Artikel wählen und bezahlen, Lagereingang mit Qualitätsprüfung abwarten und anschließend das internationale Paket einreichen."],
    ["Gibt es aktuell kostenlose Lagerung?", "Die öffentlichen Informationen nennen derzeit 100 Tage kostenlose Lagerung. Geprüft am 29. August 2026; aktuelle Kontobedingungen erneut bestätigen."],
    ["Gibt es eine Basis-Handling-Gebühr?", "Die Gebührenseite nennt derzeit keine zusätzliche Handling-Gebühr neben Artikel und Versand. Optionale Zusatzdienste können kosten."],
    ["Wie lange kann Rückgabe oder Erstattung dauern?", "Kakobuy nennt üblicherweise 7–15 Tage je nach Bestätigung des Verkäufers; relevante Rücksendekosten können abgezogen werden. Das ist keine garantierte Abschlusszeit."],
    ["Was deckt die Lager-QC ab?", "Laut Kakobuy können Prüfer Aussehen und Vollständigkeit des Zubehörs kontrollieren, Geräte aber nicht einschalten. Fotos beweisen weder Material, Haltbarkeit, Komfort noch Echtheit."],
    ["Gilt die 5-Tage-Rückgabe immer?", "Nein. Kakobuy beschreibt sie als Verkäuferleistung für unterstützte Marktplatzprodukte; die genaue Bestellung muss berechtigt sein."],
    ["Ist die Versandschätzung garantiert?", "Nein. Packgewicht, Maße, Linienregeln und Dienste können Kosten ändern; Zoll und Übergaben können die Laufzeit ändern."],
  ],
  es: [
    ["¿Esta web es Kakobuy?", "No. Kakobuy VIP es un sitio independiente de investigación y descubrimiento; no procesa pedidos ni guarda fondos."],
    ["¿Cuál es el flujo público de compra?", "Copiar el enlace de un marketplace chino, pegarlo en Kakobuy, elegir y pagar, esperar llegada y QC, y enviar el paquete internacional."],
    ["¿Hay almacenamiento gratuito?", "La información pública indica actualmente 100 días gratuitos. Revisado el 29 de agosto de 2026; confirma la política en vivo."],
    ["¿Existe comisión básica de agente?", "La ayuda dice actualmente que no añade handling fee aparte de artículo y envío. Los servicios opcionales pueden costar."],
    ["¿Cuánto puede tardar una devolución o reembolso?", "Kakobuy indica normalmente 7–15 días según la confirmación del vendedor; puede deducirse el envío de devolución. No es un plazo garantizado."],
    ["¿Qué cubre el QC?", "Kakobuy dice que el inspector revisa apariencia y accesorios, pero no puede encender equipos para probarlos. Las fotos no prueban material, duración, comodidad o autenticidad."],
    ["¿La devolución de cinco días es universal?", "No. Se describe como servicio de vendedores en productos compatibles y depende del artículo y los términos."],
    ["¿El estimado de envío es final?", "No. Peso embalado, medidas, ruta, clasificación y servicios cambian coste; aduana y transportistas cambian plazos."],
  ],
  fr: [
    ["Ce site est-il Kakobuy ?", "Non. Kakobuy VIP est un site indépendant de recherche et de découverte ; il ne traite pas les commandes ou fonds."],
    ["Quel est le parcours d'achat public ?", "Copier un lien de marketplace chinoise, le coller dans Kakobuy, choisir et payer, attendre l'arrivée et le QC, puis soumettre le colis international."],
    ["Le stockage est-il gratuit ?", "Les informations publiques indiquent actuellement 100 jours gratuits. Vérifié le 31 août 2026 ; confirmez la règle en direct."],
    ["Y a-t-il des frais d'agent de base ?", "L'aide indique actuellement aucun handling fee en plus de l'article et du transport. Les services optionnels peuvent coûter."],
    ["Combien de temps peut prendre un retour ou remboursement ?", "Kakobuy indique généralement 7 à 15 jours selon la confirmation du vendeur ; les frais de retour concernés peuvent être déduits. Ce délai n'est pas garanti."],
    ["Que couvre le QC ?", "Kakobuy indique que l'inspecteur vérifie l'apparence et les accessoires, mais ne peut pas allumer un appareil pour le tester. Les photos ne prouvent ni matière, durée, confort ou authenticité."],
    ["Le retour cinq jours est-il universel ?", "Non. Il est décrit comme un service de vendeurs sur produits compatibles et dépend de l'article et des conditions."],
    ["L'estimation de livraison est-elle finale ?", "Non. Poids, dimensions, ligne, classification et services changent le coût ; douane et transporteurs changent les délais."],
  ],
  it: [
    ["Questo sito è Kakobuy?", "No. Kakobuy VIP è un sito indipendente di ricerca e scoperta; non gestisce ordini o fondi."],
    ["Qual è il flusso pubblico?", "Copiare un link da un marketplace cinese, incollarlo in Kakobuy, scegliere e pagare, attendere arrivo e QC, poi inviare il pacco internazionale."],
    ["Il deposito è gratuito?", "Le informazioni pubbliche indicano ora 100 giorni gratuiti. Verificato il 29 agosto 2026; conferma la regola live."],
    ["C'è una commissione base dell'agente?", "L'aiuto indica ora nessun handling fee oltre articolo e spedizione. I servizi opzionali possono costare."],
    ["Quanto può durare un reso o rimborso?", "Kakobuy indica in genere 7–15 giorni secondo la conferma del venditore; i costi di reso pertinenti possono essere detratti. Non è un termine garantito."],
    ["Cosa copre il QC?", "Kakobuy dice che l'ispettore controlla aspetto e accessori, ma non può accendere un dispositivo per provarlo. Le foto non dimostrano materiale, durata, comodità o autenticità."],
    ["Il reso cinque giorni è universale?", "No. È descritto come servizio dei venditori su prodotti compatibili e dipende dall'articolo e dai termini."],
    ["La stima di spedizione è finale?", "No. Peso, misure, linea, classificazione e servizi cambiano il costo; dogana e vettori cambiano i tempi."],
  ],
};
