import type { Locale } from "./site-data";
import type { IdentifierArticle } from "./order-identifiers-article";

const sources = [
  {label:"Kakobuy official homepage and public service flow",url:"https://www.kakobuy.com/"},
  {label:"Kakobuy official purchasing-flow information",url:"https://www.kakobuy.com/index/information?information_id=12"},
  {label:"Kakobuy official service terms",url:"https://www.kakobuy.com/index/information?information_id=15"},
];

export const sellerHandoffArticleData:Record<Locale,IdentifierArticle>={
  en:{title:"Kakobuy Purchased vs Seller Sent: Documenting the First Handoff",tag:"Parcel records & workflow control",read:"15 min operations guide",reviewed:"Official sources reviewed 4 Sep 2026",lede:"Purchased and seller sent describe different evidence states. Record the order acceptance, seller-side movement and warehouse receipt separately so a status label never becomes an invented physical event.",sources,sections:[
    ["Define the first handoff before reading a status",["The first handoff is the transition from a Kakobuy purchasing record to credible evidence that the third-party seller has released the goods into domestic delivery. It is not the same as placing an order, allocating payment, creating a label, reaching the warehouse or approving QC. Kakobuy’s public buying guide separates submitting a purchasing order, the platform’s purchase from the seller, seller shipment and later warehouse inspection. That sequence is useful as a framework, but the exact account wording can vary and should always be saved verbatim.","Treat every displayed state as a claim with a source. A purchase-page label can establish what the account displayed at a particular check time. A seller or domestic-carrier event may support physical movement. A warehouse intake record supports a later stage. Do not merge these sources into one smooth narrative when the intermediate evidence is absent. The record should make the gap obvious rather than filling it with a guessed dispatch time. Write the handoff criterion before checking the account: the correct item needs a traceable domestic reference and a meaningful acceptance or movement event. A later warehouse receipt can close the handoff, but it cannot recreate an exact dispatch time that was never shown." ]],
    ["Create one order identity before tracking movement",["Start with the exact source listing, selected option, quantity, paid product record and Kakobuy order identifier as the interface labels it. Save a privacy-safe reference, not an unlabeled string. If several products came from one seller, retain an item-level row for each because options, stock decisions and dispatch events can differ even when the seller later combines domestic packages.","Record the checked-at time and page context. A screenshot of a spreadsheet card or marketplace image cannot replace the account record. If the seller changes price, stock or an option before purchase completes, preserve the old observation and add a new row describing the decision. Do not overwrite the original request, because it explains why the final purchase record may differ. Use neutral aliases when sharing a case: ORDER-A, ITEM-1 and DOMESTIC-REF-1 are enough to explain the mapping. Keep full references privately and never publish account tokens, payment details, names, addresses, phone numbers or unredacted QR codes." ]],
    ["Separate requested, purchased and seller sent",["Use three editorial stages while retaining the exact source wording: purchase requested, purchase evidenced and seller dispatch evidenced. Purchase requested means the instruction exists. Purchase evidenced means the current account shows that Kakobuy completed or recorded the seller-side purchase according to the visible state. Seller dispatch evidenced requires a stronger event, such as a domestic-carrier acceptance or movement record tied to the correct item or seller package.","These are research labels, not promised official status names. A label translated as purchased does not prove that a carrier holds the goods. A tracking number alone may be only pre-advice. Likewise, a seller message claiming shipment is evidence of a statement, not automatically evidence of a physical scan. Store both the claim and the supporting event so their strength remains clear. If the interface changes language, preserve the original wording and add a separate plain-language interpretation. Do not replace the source phrase with your stage label. Another reader can then re-evaluate the classification without losing what the page actually displayed." ]],
    ["Use a minimum handoff table",["Create columns for checked-at time, order ID label, redacted reference, item and variant, displayed status, seller package or domestic reference label, event time if shown, latest scan wording, source page, evidence filename, confidence and next check. Keep timestamps with their displayed time zone; if no zone is shown, retain the original value and avoid conversion.","Confidence should describe the evidence, not the seller. Use account label only, reference created, carrier acceptance evidenced, carrier movement evidenced, or warehouse receipt evidenced. A confidence label must never become a seller score or delivery guarantee. When two items share one domestic reference, link both rows to that reference without claiming they travelled together until the evidence shows it. Keep a discrepancy field for a reference shown on one page but absent on another, an option mismatch, an unrecognized carrier record or one missing item. Each discrepancy needs an owner, next evidence check and dated resolution." ]],
    ["Read domestic tracking conservatively",["A newly displayed reference can be useful, but it does not prove movement. Look for the current carrier page, event wording, timestamp and location when available. Save the first credible acceptance or movement event separately from the time the number first appeared in the account. If the carrier cannot identify the reference, record that result and check the account again later rather than declaring the parcel lost.","Do not publish a universal waiting period. Seller handling, marketplace systems and domestic carriers vary, and Kakobuy’s public pages do not establish one guaranteed dispatch clock for every item. Use event-based next checks: after the account label changes, when a carrier event appears, or when the warehouse record becomes visible. If the live order supplies a deadline or action, save that dated instruction with the order. A quiet reference is not proof of delay. It can reflect pre-advice, an unscanned handoff or an unmatched number. Report only the observable condition and date; escalate when a live instruction or material planning need makes the gap consequential." ]],
    ["Distinguish split, combined and replaced references",["A seller may send items separately, combine several items, or replace an early logistics reference. Record each observed mapping as a dated row. Never delete the earlier reference merely because a new one appears. Mark it superseded only when the interface, seller or carrier evidence supports that interpretation. An unexplained replacement remains an open question.","For combined domestic delivery, the package reference can map to multiple order rows while every item retains its own identity and variant. At warehouse receipt, reconcile contents item by item. One package arriving does not prove that every expected item was inside, and one item appearing in the warehouse does not prove that all items under the domestic reference arrived. Version the mapping whenever it changes. A short dated note is auditable. Overwriting a spreadsheet cell with the newest number erases the evidence path used by earlier decisions." ]],
    ["Escalate a narrow evidence question",["If progress appears stuck, prepare a compact evidence pack: redacted order reference, item description and option, purchase observation, current status wording, seller or carrier reference, latest verified event and check times. State the missing transition precisely. Ask whether the seller dispatch event or mapping can be confirmed, rather than alleging loss or delay without a supported baseline.","Keep screenshots, copied status text and any response in chronological order. A support reply about one order is case-specific unless it links to a public rule. Do not turn it into an evergreen platform promise. If the item is still within a live seller after-sales decision, follow the current account controls and policy rather than assuming that a long warehouse-storage period extends seller eligibility. Separate the desired answer from the evidence request. A specific mapping question is answerable. A broad accusation combines classification, timing and responsibility without a verified baseline and invites an overbroad reply." ]],
    ["Close the handoff only with a defensible boundary",["Close the first handoff as evidenced when the correct order maps to credible seller-to-warehouse movement or a warehouse receipt record. If the warehouse record appears first, write that warehouse receipt is evidenced while the exact seller dispatch time remains unknown. Later evidence can fill the gap by appending a row; it should not rewrite the earlier observation.","Before closing, audit for unlabeled identifiers, overwritten statuses, missing time zones, variant mismatches, duplicated carrier events and unredacted personal data. Export a read-only snapshot with a version date. The resulting record does not predict speed. It identifies what the interface said, which event supports physical movement, what remains unknown and which evidence justifies the next decision. Link the closed handoff to the later warehouse timeline instead of copying all rows. The first record answers whether seller movement was evidenced; the next answers what arrived and when it became actionable. This keeps later parcel events outside the seller-stage audit." ]],
  ],faqs:[["Does purchased mean the seller shipped?","No. Preserve the purchase state and require separate dispatch or movement evidence."],["Is a tracking number enough?","It proves that a reference was displayed. Physical movement needs a relevant carrier event or later receipt evidence."],["What if warehouse receipt appears first?","Record receipt as evidenced and leave the exact dispatch time unknown."],["Can I share the record?","Share only redacted references and the minimum evidence needed for the question."]]},
  de:{title:"Kakobuy: Gekauft oder vom Verkäufer versandt?",tag:"Paketdaten & Ablaufkontrolle",read:"15-Minuten-Ablaufleitfaden",reviewed:"Offizielle Quellen geprüft am 4. Sep. 2026",lede:"Gekauft und vom Verkäufer versandt sind verschiedene Belegzustände. Dokumentieren Sie Kauf, Händlerbewegung und Lagereingang getrennt.",sources,sections:[
    ["Die erste Übergabe definieren",["Die erste Übergabe führt vom Kaufdatensatz zum glaubwürdigen Beleg, dass der Drittanbieter die Ware in den Inlandsversand gegeben hat. Bestellung, Zahlung, Label, Lagereingang und QC sind andere Schritte. Der öffentliche Kakobuy-Ablauf trennt Kaufauftrag, Einkauf, Händler-Versand und Lagerprüfung.","Behandeln Sie jeden sichtbaren Status als datierte Aussage seiner Quelle. Kontoseite, Händler- oder Carrier-Ereignis und Lagereintrag haben unterschiedliche Beweiskraft. Fehlende Zwischenschritte bleiben sichtbar."]],
    ["Zuerst eine eindeutige Bestellidentität",["Speichern Sie Quellangebot, Variante, Menge, Zahlungsbeleg und beschriftete Bestellreferenz. Mehrere Artikel desselben Händlers behalten getrennte Zeilen.","Notieren Sie Prüfzeit und Seite. Ändern sich Preis, Bestand oder Option, wird eine neue Zeile ergänzt statt die ursprüngliche Anforderung zu überschreiben."]],
    ["Angefragt, gekauft und versandt trennen",["Nutzen Sie redaktionelle Phasen: Kauf angefragt, Kauf belegt und Händler-Versand belegt. Die letzte Phase verlangt ein stärkeres Ereignis wie Carrier-Annahme oder Bewegung.","Diese Phasen sind keine offiziellen Statusnamen. Gekauft beweist keinen Carrier-Besitz; eine Referenz kann nur Vorankündigung sein. Speichern Sie Aussage und Ereignis getrennt."]],
    ["Eine Mindesttabelle führen",["Felder: Prüfzeit, ID-Label, geschwärzte Referenz, Artikel/Variante, Statuswortlaut, Inlandsreferenz, Ereigniszeit, Scantext, Quelle, Datei, Belegstärke und nächster Check.","Belegstärke bewertet den Nachweis, nicht den Händler: Kontolabel, Referenz erstellt, Annahme, Bewegung oder Lagereingang belegt."]],
    ["Inlandstracking vorsichtig lesen",["Eine neue Referenz beweist keine Bewegung. Prüfen Sie Carrier-Seite, Ereignistext, Zeit und Ort. Speichern Sie erste Annahme getrennt vom ersten Erscheinen der Nummer.","Keine universelle Wartezeit veröffentlichen. Nutzen Sie ereignisbasierte Prüfungen und sichern Sie jede live angezeigte Frist separat."]],
    ["Geteilte, kombinierte und ersetzte Referenzen",["Jede Zuordnung erhält eine datierte Zeile. Alte Referenzen werden nicht gelöscht und nur mit Beleg als ersetzt markiert.","Bei Sammelversand bleiben Artikelidentitäten getrennt. Ein eingetroffenes Paket beweist nicht automatisch vollständigen Inhalt."]],
    ["Eine enge Belegfrage eskalieren",["Bereiten Sie Bestellreferenz, Variante, Kaufbeobachtung, Status, Carrier-Referenz, letztes Ereignis und Prüfzeiten geschwärzt vor. Fragen Sie nach der fehlenden Zuordnung.","Antworten sind fallspezifisch, sofern sie nicht auf eine öffentliche Regel verweisen. Live-After-Sales-Bedingungen bleiben maßgeblich."]],
    ["Die Übergabe sauber schließen",["Schließen Sie sie bei glaubwürdiger Bewegung oder Lagereingang. Erscheint das Lager zuerst, bleibt die exakte Versandzeit unbekannt.","Prüfen Sie unbeschriftete IDs, überschriebenen Verlauf, Zeitzonen, Varianten, Duplikate und Datenschutz. Exportieren Sie eine datierte Nur-Lese-Version."]],
  ],faqs:[["Bedeutet gekauft bereits versandt?","Nein, der Versand braucht einen eigenen Beleg."],["Reicht eine Trackingnummer?","Sie belegt eine Referenz, nicht zwingend Bewegung."],["Lager zuerst sichtbar?","Lagereingang belegen und Versandzeit unbekannt lassen."],["Sicher teilen?","Nur geschwärzte Mindestbelege teilen."]]},
  es:{title:"Kakobuy: comprado frente a enviado por el vendedor",tag:"Registros de paquete y control",read:"Guía operativa de 15 minutos",reviewed:"Fuentes oficiales revisadas el 4 sep 2026",lede:"Comprado y enviado por el vendedor son estados de evidencia distintos. Registra compra, movimiento y recepción por separado.",sources,sections:[
    ["Definir el primer traspaso",["El primer traspaso va del registro de compra a una prueba creíble de que el vendedor entregó el artículo al transporte nacional. Pedido, pago, etiqueta, almacén y QC son pasos distintos. El flujo público de Kakobuy los separa.","Trata cada estado como una afirmación fechada de su fuente. Cuenta, vendedor, transportista y almacén tienen distinta fuerza. No inventes transiciones ausentes."]],
    ["Crear una identidad de pedido",["Guarda enlace fuente, variante, cantidad, pago y referencia etiquetada. Mantén una fila por artículo aunque el vendedor agrupe envíos.","Registra hora y página. Si cambia precio, stock u opción, añade una fila sin borrar la solicitud original."]],
    ["Separar solicitado, comprado y enviado",["Usa fases editoriales: compra solicitada, compra probada y despacho probado. La última requiere aceptación o movimiento vinculado al artículo correcto.","No son nombres oficiales. Comprado no prueba posesión del transportista; una referencia puede ser aviso previo. Conserva afirmación y evento."]],
    ["Usar una tabla mínima",["Incluye hora, etiqueta ID, referencia oculta, artículo, variante, texto de estado, referencia nacional, evento, escaneo, fuente, archivo, confianza y próxima revisión.","La confianza describe la evidencia, no al vendedor: etiqueta, referencia creada, aceptación, movimiento o recepción probada."]],
    ["Leer el seguimiento con cautela",["Una referencia nueva no prueba movimiento. Comprueba página del transportista, texto, hora y lugar. Separa el primer evento del primer registro del número.","No publiques una espera universal. Usa condiciones de revisión y guarda cualquier plazo vivo como fuente aparte."]],
    ["Referencias divididas, combinadas o sustituidas",["Añade una fila por cada relación observada. No borres referencias anteriores ni las marques sustituidas sin evidencia.","Un envío combinado mantiene identidades separadas. La llegada de un paquete no prueba que contenga todos los artículos."]],
    ["Escalar una pregunta precisa",["Prepara referencia oculta, variante, compra, estado, referencia logística, último evento y horas. Pregunta por la transición que falta.","Una respuesta de soporte es específica del caso salvo enlace a política pública. Sigue las condiciones vigentes de posventa."]],
    ["Cerrar con un límite defendible",["Cierra cuando haya movimiento creíble o recepción. Si aparece primero el almacén, deja desconocida la hora exacta de despacho.","Audita IDs, historial, zonas, variantes, duplicados y privacidad. Exporta una versión de solo lectura con fecha."]],
  ],faqs:[["¿Comprado significa enviado?","No; exige una prueba separada."],["¿Basta un tracking?","Prueba una referencia, no necesariamente movimiento."],["¿Almacén primero?","Registra recepción y deja el despacho desconocido."],["¿Compartir?","Solo evidencia mínima y censurada."]]},
  fr:{title:"Kakobuy : acheté ou expédié par le vendeur",tag:"Dossiers colis et contrôle",read:"Guide opérationnel de 15 minutes",reviewed:"Sources officielles vérifiées le 4 sept. 2026",lede:"Acheté et expédié par le vendeur sont deux états de preuve. Séparez achat, mouvement et réception.",sources,sections:[
    ["Définir le premier transfert",["Le premier transfert va du dossier d’achat à une preuve crédible que le vendeur a remis l’article au transport intérieur. Commande, paiement, étiquette, entrepôt et QC sont distincts. Le parcours public Kakobuy les sépare.","Chaque statut est une affirmation datée de sa source. Compte, vendeur, transporteur et entrepôt n’ont pas la même force. Gardez les lacunes visibles."]],
    ["Créer une identité de commande",["Conservez source, variante, quantité, paiement et référence libellée. Gardez une ligne par article même si le vendeur regroupe.","Notez heure et page. En cas de changement de prix, stock ou option, ajoutez une ligne sans écraser la demande initiale."]],
    ["Séparer demandé, acheté et expédié",["Utilisez des phases éditoriales : achat demandé, achat prouvé, expédition vendeur prouvée. La dernière exige acceptation ou mouvement lié au bon article.","Ce ne sont pas des statuts officiels. Acheté ne prouve pas la possession par le transporteur ; une référence peut être une préannonce."]],
    ["Tenir une table minimale",["Champs : heure, libellé ID, référence masquée, article/variante, texte du statut, référence locale, événement, scan, source, fichier, confiance et prochain contrôle.","La confiance décrit la preuve, pas le vendeur : libellé, référence créée, acceptation, mouvement ou réception prouvée."]],
    ["Lire le suivi avec prudence",["Une nouvelle référence ne prouve pas un mouvement. Vérifiez page transporteur, texte, heure et lieu. Séparez première acceptation et première apparition du numéro.","Ne publiez pas de délai universel. Utilisez des conditions de contrôle et conservez toute échéance affichée comme source distincte."]],
    ["Références divisées, groupées ou remplacées",["Ajoutez une ligne par relation observée. Ne supprimez pas l’ancienne référence et ne la marquez remplacée qu’avec preuve.","Un envoi groupé garde des identités séparées. Un colis arrivé ne prouve pas que tous les articles sont présents."]],
    ["Escalader une question étroite",["Préparez référence masquée, variante, achat, statut, référence logistique, dernier événement et heures. Demandez la transition manquante.","Une réponse support reste propre au cas sans lien vers une règle publique. Suivez les conditions après-vente en direct."]],
    ["Clore avec une limite défendable",["Clôturez avec un mouvement crédible ou une réception. Si l’entrepôt apparaît d’abord, laissez l’heure d’expédition inconnue.","Auditez IDs, historique, fuseaux, variantes, doublons et confidentialité. Exportez une version datée en lecture seule."]],
  ],faqs:[["Acheté signifie expédié ?","Non, il faut une preuve distincte."],["Un tracking suffit ?","Il prouve une référence, pas forcément le mouvement."],["Entrepôt visible d’abord ?","Prouvez la réception et gardez l’expédition inconnue."],["Partager ?","Seulement les preuves minimales masquées."]]},
  it:{title:"Kakobuy: acquistato o spedito dal venditore",tag:"Registri pacco e controllo",read:"Guida operativa di 15 minuti",reviewed:"Fonti ufficiali verificate il 4 set 2026",lede:"Acquistato e spedito dal venditore sono stati di prova distinti. Registra acquisto, movimento e ricezione separatamente.",sources,sections:[
    ["Definire il primo passaggio",["Il primo passaggio va dal record di acquisto alla prova credibile che il venditore abbia consegnato l’articolo al trasporto interno. Ordine, pagamento, etichetta, magazzino e QC sono fasi diverse. Il flusso pubblico Kakobuy le separa.","Ogni stato è un’affermazione datata della sua fonte. Account, venditore, vettore e magazzino hanno forza diversa. Mantieni visibili i vuoti."]],
    ["Creare un’identità ordine",["Salva fonte, variante, quantità, pagamento e riferimento etichettato. Mantieni una riga per articolo anche se il venditore raggruppa.","Registra ora e pagina. Se prezzo, stock o opzione cambiano, aggiungi una riga senza cancellare la richiesta iniziale."]],
    ["Separare richiesto, acquistato e spedito",["Usa fasi editoriali: acquisto richiesto, acquisto provato e spedizione venditore provata. L’ultima richiede accettazione o movimento legato all’articolo giusto.","Non sono stati ufficiali. Acquistato non prova il possesso del vettore; un riferimento può essere solo preavviso. Conserva affermazione ed evento."]],
    ["Usare una tabella minima",["Campi: ora, etichetta ID, riferimento oscurato, articolo/variante, testo stato, riferimento interno, evento, scansione, fonte, file, confidenza e prossimo controllo.","La confidenza descrive la prova, non il venditore: etichetta, riferimento creato, accettazione, movimento o ricezione provata."]],
    ["Leggere il tracking con prudenza",["Un nuovo riferimento non prova movimento. Controlla pagina vettore, testo, ora e luogo. Separa prima accettazione dalla prima comparsa del numero.","Non pubblicare un’attesa universale. Usa condizioni di controllo e salva ogni scadenza live come fonte separata."]],
    ["Riferimenti divisi, combinati o sostituiti",["Aggiungi una riga per ogni relazione osservata. Non cancellare riferimenti vecchi né marcarli sostituiti senza prova.","Una spedizione combinata mantiene identità separate. L’arrivo di un pacco non prova che contenga tutti gli articoli."]],
    ["Escalare una domanda precisa",["Prepara riferimento oscurato, variante, acquisto, stato, riferimento logistico, ultimo evento e orari. Chiedi la transizione mancante.","Una risposta del supporto vale per il caso senza un link a regola pubblica. Segui le condizioni post-vendita attuali."]],
    ["Chiudere con un limite difendibile",["Chiudi con movimento credibile o ricezione. Se appare prima il magazzino, lascia sconosciuta l’ora esatta di spedizione.","Verifica ID, storia, fusi, varianti, duplicati e privacy. Esporta una versione datata in sola lettura."]],
  ],faqs:[["Acquistato significa spedito?","No, serve una prova separata."],["Basta un tracking?","Prova un riferimento, non necessariamente movimento."],["Magazzino prima?","Registra la ricezione e lascia ignota la spedizione."],["Condividere?","Solo prove minime oscurate."]]}
};
