import type { Locale } from "./site-data";
import type { IdentifierArticle } from "./order-identifiers-article";

const sources = [
  { label: "Kakobuy official homepage and public service flow", url: "https://www.kakobuy.com/" },
  { label: "Kakobuy official purchasing-flow information", url: "https://www.kakobuy.com/index/information?information_id=12" },
  { label: "Kakobuy official service terms", url: "https://www.kakobuy.com/index/information?information_id=15" },
];

export const warehouseIntakeArticleData: Record<Locale, IdentifierArticle> = {
  en: {
    title: "Kakobuy Warehouse Received vs Stored: An Intake Record Checklist",
    tag: "Warehouse records & data quality",
    read: "15 min operations guide",
    reviewed: "Official sources reviewed 12 Sep 2026",
    lede: "A warehouse receipt event and a stored, inventory-ready item record answer different questions. Use this checklist to document the intake gap without inventing a status, deadline or inspection result.",
    sources,
    sections: [
      ["Define received and stored as evidence boundaries", [
        "Begin with the exact wording visible in the current Kakobuy account. This guide uses received for evidence that a seller package or item has reached a warehouse-facing intake point, and stored for evidence that a usable item record has appeared in the warehouse inventory. Those are editorial boundaries, not permanent Kakobuy status names. The public buying flow places warehouse arrival before inspection and later parcel submission, but it does not prove that every account exposes the same intermediate labels. Save the live label, page, date and time rather than translating it into a stronger claim. A domestic carrier delivery scan may support arrival at a receiving point; it does not by itself prove that the correct item has been identified, counted or made available. Likewise, a stored item card does not automatically prove that every expected accessory, quantity or option is correct. The purpose of the boundary is to show what changed between two systems while leaving quality review, return eligibility and storage deadlines to their own current records.",
      ]],
      ["Carry forward the verified item identity", [
        "Start the intake record from the item-to-package map created during the domestic-delivery stage. Copy only verified identifiers: a private order reference, a neutral item alias, the source listing description, selected option, expected quantity and the domestic package reference when shown. Preserve one row per ordered item even when a seller combined several items in one package. If one order was split, keep separate package rows and link them to the relevant item aliases. Do not build the intake record from a carrier number alone, because one number may cover several contents and a warehouse card may use a different label. In a shared or support-ready version, redact full order numbers, account links, names, phone numbers, addresses and tracking references. Use stable aliases such as ITEM-A and PACKAGE-2 so screenshots and notes can be matched without exposing private data. If the mapping is uncertain, mark it unconfirmed; do not attach the newest warehouse card to the nearest order simply because their dates look similar.",
      ]],
      ["Create an append-only intake timeline", [
        "Record each observation as a new event instead of replacing the previous status. Useful fields are item alias, package alias, source page, exact displayed label, displayed event time, displayed time zone, checked-at time, evidence filename, mapping confidence and next action. Keep displayed time separate from checked-at time: a screenshot captured today may show an event from yesterday. If no time zone is shown, preserve the text as displayed and mark the zone unknown. Recommended evidence stages are carrier delivery displayed, warehouse receipt displayed, item identity matched, warehouse record usable and unresolved intake gap. These are internal classifications for the log, not claims about Kakobuy's official terminology. An append-only timeline shows that a package could be visible at one checkpoint before an item record became usable. It also prevents a later stored state from erasing the earlier uncertainty. Correct mistakes with a new row that points to the superseded entry; never silently rewrite the evidence history.",
      ]],
      ["Test whether the warehouse record is actually usable", [
        "A warehouse entry is useful when it can be tied to the intended item and supports the next permitted action. Confirm that the record has a defensible identity link, that the expected item is distinguishable from other arrivals and that the account presents whatever action or detail is currently available for that record. Do not publish a fixed list of buttons, photo counts or status labels because the interface and service scope can change. Instead, capture what the live account shows: the record title, linked order label, option text if present, quantity if present, visible intake date and available next-step controls. Separate missing from not yet checked. Missing means a field was examined and not displayed; not checked means the audit is incomplete. A card with a thumbnail is not automatically a completed inspection, and an inspection image is not proof of material, fit, authenticity or hidden condition. This checklist closes only the data-readiness question: can the reviewer identify and work with the correct warehouse record without guessing?"]],
      ["Reconcile partial, combined and duplicate intake", [
        "Use a small reconciliation table with expected item aliases on the left and observed warehouse records on the right. Mark each relationship matched, possible, duplicated, unexpected or unresolved. When one seller package contains several items, the first visible card does not prove that all contents were processed. When several packages arrive close together, do not assign every card to the first carrier delivery event. Compare order labels, item descriptions, option text, package relationships and timestamps. A duplicate-looking card may represent a second quantity, a reprocessed record or a true duplicate; preserve both until the live account evidence distinguishes them. An unexpected item should not be silently substituted for a missing one. Record it as unexpected and leave the expected row open. This stage intentionally stops before detailed variant and quantity validation, which belongs to the next dedicated workflow. Here, the goal is narrower: every usable warehouse record has a traceable source row, and every expected source row has an explicit current disposition."]],
      ["Investigate received-but-not-stored without inventing delay", [
        "When receipt evidence exists but no usable warehouse record can be matched, begin with the last defensible event. Recheck that the domestic reference belongs to the expected seller package, that the delivery wording points to a warehouse receiving location and that no replacement package reference appeared. Then search the current order and warehouse views using the verified order label and item description. Note whether the package contains several items or whether another arrival could explain the visible card. Record the gap as receipt displayed; warehouse item record not matched as of the checked-at time. Do not call it lost, missing, delayed or overdue unless a current official instruction or account-specific support response supplies a relevant basis. This run could not verify a universal Kakobuy intake interval from the public pages, so the article publishes none. If the gap matters, prepare a concise question asking whether PACKAGE-2 can be associated with ITEM-A. Include the evidence dates and redacted identifiers, not speculation about cause."]],
      ["Build a minimum support-ready evidence pack", [
        "A useful evidence pack contains a one-sentence issue statement, redacted order and package labels, the item description and selected option, the last domestic event, the first warehouse-facing receipt evidence, every checked-at time and a screenshot showing the missing or ambiguous mapping. Add a compact timeline rather than a folder of unexplained images. Name files with the item alias, source and date, such as ITEM-A_warehouse_2026-09-12. Crop only when the crop preserves the relevant page label and context; obscure unrelated personal data without hiding the field being discussed. Ask one operational question at a time: can this received package be matched to this order, or which warehouse record corresponds to this item? A case-specific reply can help resolve the record, but it should not be republished as a universal platform policy. Save the reply with its date, scope and referenced identifiers. The evidence pack should allow another reviewer to understand the mismatch without needing access to the whole account."]],
      ["Close the intake record and hand off cleanly", [
        "Close intake for an item only when the correct warehouse record is defensibly matched and usable for the next decision. Write a narrow close statement: ITEM-A matched to warehouse record W-2 on the account; first usable observation 12 September 2026; quantity and condition review remain separate. If only a receipt event exists, leave intake open. If some items are matched and others are not, close them separately. Freeze a read-only snapshot containing the event log, mapping table, evidence list, close date and unresolved fields. Then link that snapshot to the next record instead of copying the entire history into every worksheet. Before handoff, check for overwritten timestamps, unsupported assumptions, duplicated cards, mixed package identities and exposed personal data. The result is not a guarantee that the item is correct, returnable or ready to ship. It is a reproducible answer to a smaller question: which expected item became which usable warehouse record, which evidence supports that link and what remained unknown at the time of review."]],
    ],
    faqs: [
      ["Does carrier delivery mean the item is stored?", "No. Keep carrier delivery, warehouse receipt and a usable item record as separate observations."],
      ["How long should warehouse intake take?", "Use current account instructions or a dated case-specific answer. This guide does not publish a universal interval."],
      ["Does a warehouse card prove the option and quantity are correct?", "No. It supports identity mapping; detailed option, quantity and condition checks are separate."],
      ["What should I share with support?", "Share the smallest redacted identifier set, a dated timeline and the exact missing mapping—never unrelated account or address data."],
    ],
  },
  de: {
    title: "Kakobuy-Lager: Eingegangen oder eingelagert? Intake-Protokoll",
    tag: "Lagerdaten & Datenqualität", read: "15-Minuten-Ablaufleitfaden", reviewed: "Offizielle Quellen geprüft am 12. Sep. 2026",
    lede: "Lagereingang und ein nutzbarer Lagerdatensatz beantworten verschiedene Fragen. Diese Prüfliste dokumentiert die Lücke ohne erfundene Statusnamen oder Fristen.", sources,
    sections: [
      ["Eingegangen und eingelagert als Beleggrenzen", ["Beginnen Sie mit dem Wortlaut im aktuellen Konto. Eingegangen bezeichnet hier einen Beleg am Empfangspunkt; eingelagert einen nutzbaren Artikelbestand. Das sind redaktionelle Grenzen, keine dauerhaften Kakobuy-Status. Ein Carrier-Scan beweist nicht Identifizierung oder Vollständigkeit, eine Lagerkarte nicht jede Variante oder jedes Zubehör. Speichern Sie Seite, Text, Datum und Uhrzeit und trennen Sie Qualitätsprüfung, Rückgabe und Lagerfrist."]],
      ["Verifizierte Artikelidentität übernehmen", ["Übernehmen Sie nur geprüfte Bestellreferenz, neutralen Artikelalias, Angebotsbeschreibung, Option, Menge und Paketbezug. Kombinierte Sendungen behalten einzelne Artikelzeilen; geteilte Bestellungen eigene Paketzeilen. Vollständige IDs, Kontolinks, Namen, Telefone, Adressen und Trackingdaten bleiben privat. Unsichere Beziehungen heißen unbestätigt und werden nicht allein nach zeitlicher Nähe zugeordnet."]],
      ["Eine append-only Intake-Zeitleiste führen", ["Jede Beobachtung erhält eine neue Zeile mit Alias, Seite, Live-Label, Ereigniszeit, Zeitzone, Prüfzeit, Datei, Zuordnungsstärke und nächster Aktion. Ereignis- und Screenshotzeit bleiben getrennt. Interne Stufen wie Zustellung angezeigt, Lagereingang angezeigt, Identität zugeordnet und Lagerdatensatz nutzbar sind keine erfundenen offiziellen Status. Korrekturen verweisen auf alte Einträge, statt sie lautlos zu ersetzen."]],
      ["Prüfen, ob der Lagerdatensatz nutzbar ist", ["Ein Eintrag ist nutzbar, wenn er dem richtigen Artikel zugeordnet werden kann und die aktuell sichtbaren nächsten Aktionen unterstützt. Erfassen Sie Live-Titel, Bestelllabel, Option, Menge, Intake-Datum und verfügbare Steuerelemente, ohne feste Buttons oder Fotozahlen zu behaupten. Fehlend und nicht geprüft sind verschiedene Werte. Ein Vorschaubild ist kein abgeschlossener QC-Nachweis."]],
      ["Teil-, Sammel- und Doppelaufnahmen abstimmen", ["Vergleichen Sie erwartete Aliase mit beobachteten Karten und markieren Sie passend, möglich, doppelt, unerwartet oder offen. Eine erste Karte beweist keinen vollständigen Sammelinhalt; nahe Ankunftszeiten beweisen keine Paketzuordnung. Ein unerwarteter Artikel ersetzt keinen fehlenden. Detaillierte Varianten- und Mengenprüfung folgt später; hier zählt die nachvollziehbare Quellenbeziehung."]],
      ["Eingang ohne Einlagerung untersuchen", ["Prüfen Sie Paketbezug, Zielwortlaut, Ersatzreferenzen sowie aktuelle Bestell- und Lageransichten. Schreiben Sie: Eingang angezeigt; Lagerdatensatz zum Prüfzeitpunkt nicht zugeordnet. Ohne aktuelle offizielle Grundlage heißt die Lücke weder verloren noch verspätet. Eine Supportfrage bittet nur um Zuordnung des geschwärzten Pakets zum Artikel und enthält die relevanten Daten."]],
      ["Ein minimales Support-Belegpaket bauen", ["Enthalten sind ein kurzer Problemsatz, geschwärzte Labels, Artikel und Option, letztes Inlandsereignis, erster Lagereingangsbeleg, Prüfzeiten und die unklare Zuordnung. Dateien tragen Alias, Quelle und Datum. Fragen Sie jeweils nur nach einer Beziehung. Eine fallbezogene Antwort bleibt fallbezogen und wird mit Datum und Umfang gespeichert."]],
      ["Intake schließen und sauber übergeben", ["Schließen Sie erst bei belastbarer Zuordnung zu einem nutzbaren Lagerdatensatz. Teilartikel werden getrennt geschlossen; reine Eingangsereignisse bleiben offen. Frieren Sie Zeitleiste, Mapping, Belege, Datum und Restlücken ein. Die Übergabe verspricht weder Richtigkeit, Rückgabe noch Versandbereitschaft, sondern dokumentiert genau die bewiesene Artikel-Lager-Beziehung."]],
    ], faqs: [["Bedeutet Carrier-Zustellung eingelagert?","Nein, Zustellung, Lagereingang und nutzbare Karte bleiben getrennt."],["Wie lange dauert Intake?","Nur aktuelle Kontohinweise oder datierte fallbezogene Auskunft verwenden."],["Beweist eine Lagerkarte Option und Menge?","Nein, die Detailprüfung ist ein eigener Ablauf."],["Was erhält der Support?","Nur geschwärzte relevante IDs, Zeitleiste und fehlende Zuordnung."]],
  },
  es: {
    title: "Kakobuy: recibido frente a almacenado, lista de registro de entrada", tag: "Registros de almacén y calidad de datos", read: "Guía operativa de 15 minutos", reviewed: "Fuentes oficiales revisadas el 12 sep 2026", lede: "La recepción y un registro utilizable de inventario responden preguntas distintas. Documenta la diferencia sin inventar estado o plazo.", sources,
    sections: [
      ["Definir recibido y almacenado como límites", ["Empieza con el texto exacto de la cuenta. Recibido significa aquí evidencia en un punto de entrada; almacenado, una ficha utilizable de inventario. Son límites editoriales, no estados oficiales permanentes. Un escaneo no prueba identificación o contenido completo y una ficha no prueba cada opción o accesorio. Guarda página, texto, fecha y hora y separa QC, devolución y plazo de almacenamiento."]],
      ["Heredar la identidad verificada", ["Copia solo referencia verificada, alias, descripción, opción, cantidad y vínculo de paquete. Los envíos combinados conservan filas por artículo y los divididos filas por paquete. IDs completos, enlaces, nombres, teléfonos, direcciones y tracking quedan privados. Una relación incierta se marca sin confirmar y no se asigna por fechas parecidas."]],
      ["Crear una cronología acumulativa", ["Cada observación añade fila con alias, página, etiqueta viva, hora del evento, zona, consulta, archivo, confianza y siguiente acción. La hora del evento no es la de la captura. Etapas internas como entrega mostrada, recepción mostrada, identidad vinculada y ficha utilizable no son nombres oficiales inventados. Una corrección enlaza el registro sustituido."]],
      ["Comprobar que la ficha es utilizable", ["Una entrada sirve cuando se vincula al artículo correcto y permite la siguiente acción visible. Guarda título, etiqueta de pedido, opción, cantidad, fecha y controles que realmente aparezcan, sin fijar botones o número de fotos. Ausente y no revisado son valores distintos. Una miniatura no demuestra inspección completa ni material, ajuste o autenticidad."]],
      ["Conciliar entradas parciales, combinadas y duplicadas", ["Compara alias esperados y fichas observadas; marca coincidente, posible, duplicada, inesperada o abierta. La primera ficha no prueba un paquete combinado completo, y la proximidad temporal no prueba relación. Un artículo inesperado no sustituye al que falta. La revisión detallada de opción y cantidad pertenece al siguiente proceso."]],
      ["Investigar recibido pero no almacenado", ["Revisa relación de paquete, destino, referencias sustitutas y vistas actuales de pedido y almacén. Escribe: recepción mostrada; ficha de almacén no vinculada a la hora consultada. Sin base oficial actual no afirmes pérdida o retraso. Pregunta únicamente si el paquete censurado puede asociarse al artículo e incluye fechas relevantes."]],
      ["Preparar un paquete mínimo para soporte", ["Incluye una frase, etiquetas censuradas, artículo y opción, último evento nacional, primera evidencia de recepción, horas de consulta y captura de la relación ausente. Nombra archivos con alias, fuente y fecha. Formula una sola pregunta. Una respuesta específica del caso no se convierte en política universal."]],
      ["Cerrar la entrada y transferirla", ["Cierra solo al vincular de forma defendible el artículo con una ficha utilizable. Cierra parciales por separado y deja abierta la mera recepción. Congela cronología, mapa, lista de pruebas, fecha y vacíos. El resultado no garantiza corrección, devolución o envío; demuestra una relación concreta y sus límites."]],
    ], faqs: [["¿Entrega del carrier significa almacenado?","No; entrega, recepción y ficha utilizable son hechos distintos."],["¿Cuánto tarda la entrada?","Usa instrucciones actuales o respuesta fechada del caso."],["¿La ficha prueba opción y cantidad?","No; la revisión detallada es separada."],["¿Qué comparto con soporte?","Solo IDs censurados, cronología y relación que falta."]],
  },
  fr: {
    title: "Kakobuy : reçu ou stocké, checklist du dossier d’admission", tag: "Dossiers entrepôt & qualité des données", read: "Guide opérationnel de 15 minutes", reviewed: "Sources officielles vérifiées le 12 sept. 2026", lede: "Une réception et une fiche de stock exploitable répondent à deux questions. Documentez l’écart sans inventer statut ni délai.", sources,
    sections: [
      ["Définir reçu et stocké comme limites", ["Commencez par le libellé exact du compte. Reçu désigne ici une preuve au point d’admission ; stocké, une fiche d’inventaire exploitable. Ce sont des limites éditoriales, pas des statuts officiels permanents. Un scan ne prouve ni identification ni contenu complet, et une carte ne prouve pas chaque option ou accessoire. Gardez page, texte, date et heure; séparez QC, retour et échéance de stockage."]],
      ["Transmettre l’identité vérifiée", ["Copiez seulement référence vérifiée, alias, description, option, quantité et lien colis. Les envois groupés gardent une ligne par article, les divisions une ligne par colis. Identifiants complets, liens, noms, téléphones, adresses et suivis restent privés. Une relation incertaine demeure non confirmée et ne se déduit pas de dates voisines."]],
      ["Créer une chronologie sans écrasement", ["Chaque observation ajoute une ligne avec alias, page, libellé, heure, fuseau, contrôle, fichier, confiance et action suivante. L’heure d’événement diffère de celle de capture. Livraison affichée, réception affichée, identité associée et fiche exploitable sont des catégories internes, non des statuts Kakobuy inventés. Une correction pointe vers l’entrée remplacée."]],
      ["Vérifier que la fiche est exploitable", ["Une entrée sert quand elle est reliée au bon article et permet l’étape actuelle. Relevez titre, libellé commande, option, quantité, date et commandes réellement visibles, sans figer boutons ou nombre de photos. Absent et non vérifié sont différents. Une vignette ne prouve ni inspection terminée, ni matière, coupe ou authenticité."]],
      ["Rapprocher admissions partielles et doublons", ["Comparez alias attendus et fiches observées; marquez associé, possible, doublon, inattendu ou ouvert. La première fiche ne prouve pas un colis groupé complet et des dates proches ne prouvent pas le lien. Un article inattendu ne remplace pas le manquant. Le contrôle détaillé d’option et quantité appartient au processus suivant."]],
      ["Examiner reçu mais non stocké", ["Revérifiez relation colis, destination, référence de remplacement, commande et entrepôt actuels. Écrivez : réception affichée ; aucune fiche associée à l’heure du contrôle. Sans base officielle actuelle, ne concluez ni perte ni retard. Demandez seulement si le colis masqué peut être lié à l’article et fournissez les dates utiles."]],
      ["Préparer un dossier minimal pour le support", ["Ajoutez une phrase, libellés masqués, article et option, dernier événement intérieur, première preuve de réception, heures de contrôle et capture du lien absent. Nommez les fichiers par alias, source et date. Posez une question à la fois. Une réponse propre au cas ne devient jamais une règle générale."]],
      ["Clore l’admission et transmettre", ["Fermez seulement lorsque l’article correspond de façon défendable à une fiche exploitable. Les partiels se ferment séparément; une réception seule reste ouverte. Figez chronologie, table, preuves, date et inconnues. Le dossier ne garantit ni conformité, retour ou expédition; il établit la relation prouvée et ses limites."]],
    ], faqs: [["Livré signifie-t-il stocké ?","Non; livraison, réception et fiche exploitable restent séparées."],["Quel délai d’admission ?","Utilisez l’instruction actuelle ou une réponse datée du cas."],["La fiche prouve-t-elle option et quantité ?","Non; le contrôle détaillé est distinct."],["Que transmettre au support ?","Uniquement les identifiants masqués, la chronologie et le lien manquant."]],
  },
  it: {
    title: "Kakobuy: ricevuto o stoccato, checklist del record di ingresso", tag: "Registri magazzino e qualità dati", read: "Guida operativa di 15 minuti", reviewed: "Fonti ufficiali verificate il 12 set 2026", lede: "Ricezione e scheda di inventario utilizzabile rispondono a domande diverse. Registra il divario senza inventare stato o tempi.", sources,
    sections: [
      ["Definire ricevuto e stoccato come confini", ["Parti dal testo esatto nell’account. Ricevuto indica qui una prova al punto di ingresso; stoccato una scheda inventario utilizzabile. Sono confini editoriali, non stati ufficiali permanenti. Una scansione non prova identificazione o contenuto completo e una scheda non prova ogni opzione o accessorio. Salva pagina, testo, data e ora; separa QC, reso e scadenza di deposito."]],
      ["Ereditare l’identità verificata", ["Copia solo riferimento verificato, alias, descrizione, opzione, quantità e legame pacco. Le spedizioni combinate mantengono righe per articolo, quelle divise righe per pacco. ID completi, link, nomi, telefoni, indirizzi e tracking restano privati. Una relazione incerta è non confermata e non viene assegnata per vicinanza di date."]],
      ["Creare una cronologia append-only", ["Ogni osservazione aggiunge una riga con alias, pagina, etichetta live, ora evento, fuso, controllo, file, fiducia e prossima azione. L’ora dell’evento è distinta da quella dello screenshot. Consegna mostrata, ricezione mostrata, identità abbinata e scheda utilizzabile sono categorie interne, non stati Kakobuy inventati. Una correzione collega la voce sostituita."]],
      ["Verificare che la scheda sia utilizzabile", ["Una voce serve quando è collegata all’articolo corretto e consente l’azione successiva visibile. Registra titolo, etichetta ordine, opzione, quantità, data e controlli davvero presenti, senza fissare pulsanti o numero di foto. Mancante e non controllato sono diversi. Una miniatura non prova ispezione completa, materiale, vestibilità o autenticità."]],
      ["Riconciliare ingressi parziali e duplicati", ["Confronta alias attesi e schede osservate; segna abbinato, possibile, duplicato, inatteso o aperto. La prima scheda non prova il contenuto completo di un pacco combinato e date vicine non provano un legame. Un articolo inatteso non sostituisce quello mancante. Il controllo dettagliato di opzione e quantità appartiene al flusso successivo."]],
      ["Indagare ricevuto ma non stoccato", ["Ricontrolla legame pacco, destinazione, riferimenti sostitutivi, viste ordine e magazzino. Scrivi: ricezione mostrata; scheda non abbinata all’ora del controllo. Senza base ufficiale attuale non dichiarare perdita o ritardo. Chiedi solo se il pacco oscurato può essere collegato all’articolo e includi le date."]],
      ["Preparare un pacchetto minimo per assistenza", ["Includi una frase, etichette oscurate, articolo e opzione, ultimo evento nazionale, prima prova di ricezione, orari di controllo e cattura del legame mancante. Nomina i file con alias, fonte e data. Poni una domanda per volta. Una risposta specifica del caso non diventa una policy generale."]],
      ["Chiudere l’ingresso e passarlo", ["Chiudi solo quando l’articolo è collegato in modo difendibile a una scheda utilizzabile. I parziali si chiudono separatamente; la sola ricezione resta aperta. Congela cronologia, mappa, prove, data e incognite. Il record non garantisce correttezza, reso o spedizione; documenta il legame provato e i limiti."]],
    ], faqs: [["Consegnato significa stoccato?","No; consegna, ricezione e scheda utilizzabile restano separate."],["Quanto dura l’ingresso?","Usa istruzioni attuali o una risposta datata del caso."],["La scheda prova opzione e quantità?","No; il controllo dettagliato è separato."],["Cosa condivido con l’assistenza?","Solo ID oscurati, cronologia e collegamento mancante."]],
  },
};

const parityAdditions: Record<Exclude<Locale, "en">, string[]> = {
  de: [
    "Der öffentliche Kaufablauf ordnet Ankunft vor Prüfung und späterer Paketeinreichung ein, belegt aber keine identischen Zwischenlabels in jedem Konto. Speichern Sie daher den sichtbaren Wortlaut, statt ihn in eine stärkere Aussage zu übersetzen. Ein nutzbarer Datensatz beantwortet nur die Frage, ob der richtige Artikel ohne Raten weiterbearbeitet werden kann; Material, Echtheit, versteckte Schäden und Rückgaberechte bleiben außerhalb dieser Grenze.",
    "Bauen Sie die Aufnahme niemals aus einer Trackingnummer allein auf, weil ein Paket mehrere Inhalte umfassen kann und das Lager andere Labels verwenden kann. Stabile Kürzel wie ITEM-A und PACKAGE-2 halten Notizen und Screenshots zusammen. Ist ein Mapping ungeklärt, bleibt es offen. Die zeitlich nächste Lagerkarte ist kein Beweis für die sachlich richtige Beziehung.",
    "Fehlt eine Zeitzone, bleibt die Uhrzeit exakt wie angezeigt und erhält das Merkmal unbekannte Zone. Die Historie erklärt damit, dass ein Paket an einem Kontrollpunkt sichtbar war, bevor der Lagerdatensatz nutzbar wurde. Ein späterer Status darf frühere Unsicherheit nicht löschen. Dadurch kann ein anderer Prüfer nachvollziehen, wann welche Schlussfolgerung überhaupt zulässig war.",
    "Die Prüfung erfasst nur tatsächlich angezeigte Felder und Aktionen. Eine fehlende Menge bedeutet, dass das Feld geprüft und nicht dargestellt wurde; nicht geprüft bedeutet eine Lücke im Audit. Weder Vorschaubild noch Foto beweisen automatisch eine abgeschlossene Inspektion. Schließen Sie nur die Datenbereitschaft: Identität und aktueller Handlungsweg müssen ohne Vermutung verständlich sein.",
    "Eine scheinbar doppelte Karte kann eine zweite Menge, Neuverarbeitung oder echtes Duplikat sein. Bewahren Sie beide, bis Kontoangaben sie unterscheiden. Nutzen Sie Bestelllabel, Beschreibung, Option, Paketbezug und Zeiten gemeinsam. Jede erwartete Zeile braucht einen ausdrücklich aktuellen Zustand, und jeder nutzbare Lagereintrag eine nachvollziehbare Herkunft.",
    "Suchen Sie mit dem verifizierten Bestelllabel und der Artikelbeschreibung und prüfen Sie, ob eine Sammelsendung oder andere Ankunft die sichtbare Karte erklärt. Diese Recherche konnte keine allgemeine Kakobuy-Aufnahmedauer aus den öffentlichen Seiten bestätigen, daher wird keine veröffentlicht. Der belastbare Satz benennt nur die Beobachtung und den Zeitpunkt.",
    "Ein kompakter Zeitstrahl ist hilfreicher als ein Ordner unerklärter Bilder. Zuschneiden ist nur sinnvoll, wenn Seitenlabel und Kontext erhalten bleiben; schwärzen Sie andere persönliche Daten. Speichern Sie eine Supportantwort mit Datum, Umfang und den betroffenen Aliasen. Sie löst möglicherweise diesen Fall, beschreibt aber keine allgemeine Plattformregel.",
    "Die Abschlussformulierung kann lauten: ITEM-A dem Lagerdatensatz W-2 im Konto zugeordnet; erstmals nutzbar am 12. September 2026; Mengen- und Zustandsprüfung getrennt. Prüfen Sie vor Übergabe überschriebenen Zeiten, Annahmen, Duplikate, vermischte Pakete und Datenschutz. So bleibt die Aussage klein, aber reproduzierbar.",
  ],
  es: [
    "El flujo público sitúa la llegada antes de la inspección y de la posterior presentación del paquete, pero no demuestra etiquetas intermedias idénticas en todas las cuentas. Conserva el texto visible y no lo conviertas en una afirmación más fuerte. Una ficha utilizable solo responde si el artículo correcto puede continuar sin adivinar; material, autenticidad, defectos ocultos y devolución quedan fuera.",
    "Nunca construyas la entrada solo desde un tracking, porque un paquete puede cubrir varios contenidos y el almacén puede usar otra etiqueta. Alias estables como ITEM-A y PACKAGE-2 unen notas y capturas. Si el vínculo no está probado, queda abierto. La tarjeta con fecha más cercana no demuestra la relación correcta.",
    "Si no aparece zona horaria, guarda la hora literal y marca zona desconocida. El historial muestra que un paquete pudo ser visible en un control antes de que la ficha fuera utilizable. Un estado posterior no borra la incertidumbre anterior. Así otro revisor puede reproducir qué conclusión era defendible en cada momento.",
    "Registra únicamente campos y acciones realmente visibles. Cantidad ausente significa que se revisó y no apareció; no revisada señala que el audit está incompleto. Ni miniatura ni foto prueban inspección finalizada. Cierra solo la preparación de datos: identidad y siguiente acción deben poder entenderse sin suposiciones.",
    "Una ficha aparentemente duplicada puede ser una segunda unidad, un reproceso o un duplicado real. Conserva ambas hasta que la cuenta las distinga. Combina etiquetas de pedido, descripción, opción, relación de paquete y horas. Cada fila esperada necesita disposición actual explícita y cada ficha utilizable un origen trazable.",
    "Busca con la etiqueta verificada y la descripción y comprueba si un paquete combinado u otra llegada explica la tarjeta visible. Esta revisión no pudo verificar en las páginas públicas un plazo universal de entrada Kakobuy, por lo que no publica ninguno. La frase defendible describe solo observación y hora.",
    "Una cronología compacta es mejor que una carpeta de imágenes sin explicar. Recorta solo si se conserva contexto y etiqueta de página; oculta datos ajenos. Guarda cualquier respuesta con fecha, alcance y alias afectados. Puede resolver ese caso, pero no se presenta como política de toda la plataforma.",
    "La frase final puede decir: ITEM-A asociado a ficha W-2; primera observación utilizable el 12 de septiembre de 2026; cantidad y condición pendientes de flujo separado. Antes de transferir, busca horas sobrescritas, suposiciones, duplicados, paquetes mezclados y datos expuestos. El resultado es limitado pero reproducible.",
  ],
  fr: [
    "Le parcours public place l’arrivée avant l’inspection et la soumission ultérieure du colis, sans prouver des libellés intermédiaires identiques pour chaque compte. Conservez donc le texte visible plutôt que de le renforcer. Une fiche exploitable répond seulement à la capacité de poursuivre sans deviner; matière, authenticité, défaut caché et retour restent hors de cette limite.",
    "Ne construisez jamais l’admission depuis un suivi seul : un colis peut couvrir plusieurs contenus et l’entrepôt employer un autre libellé. Des alias stables comme ITEM-A et PACKAGE-2 relient notes et captures. Si la correspondance manque, elle reste ouverte. La carte chronologiquement la plus proche n’est pas une preuve.",
    "Sans fuseau affiché, gardez l’heure littérale et marquez le fuseau inconnu. L’historique montre qu’un colis pouvait être visible à un contrôle avant que sa fiche devienne exploitable. Un statut ultérieur n’efface pas l’incertitude antérieure. Un autre examinateur peut ainsi reproduire la conclusion permise à chaque moment.",
    "Relevez uniquement les champs et actions visibles. Quantité absente signifie vérifiée mais non affichée; non vérifiée signifie audit incomplet. Ni vignette ni photo ne prouvent une inspection terminée. Fermez seulement la disponibilité des données : identité et étape suivante doivent être compréhensibles sans supposition.",
    "Une carte ressemblant à un doublon peut représenter une seconde unité, un retraitement ou un vrai doublon. Gardez les deux jusqu’à distinction par le compte. Croisez libellé, description, option, colis et heures. Chaque ligne attendue reçoit un état actuel explicite et chaque fiche exploitable une origine traçable.",
    "Recherchez avec le libellé vérifié et la description, puis examinez si un regroupement ou une autre arrivée explique la carte. Cette recherche n’a pas pu confirmer un délai Kakobuy universel dans les pages publiques, donc aucun n’est publié. La formule défendable décrit seulement l’observation et son heure.",
    "Une chronologie compacte vaut mieux qu’un dossier d’images inexpliquées. Recadrez seulement si contexte et libellé restent visibles; masquez les autres données privées. Archivez toute réponse avec date, portée et alias concernés. Elle peut résoudre le cas sans devenir une politique générale.",
    "La clôture peut indiquer : ITEM-A associé à la fiche W-2; première disponibilité le 12 septembre 2026; quantité et état soumis à un autre contrôle. Avant transfert, cherchez heures écrasées, hypothèses, doublons, colis mélangés et données exposées. La conclusion reste limitée, mais reproductible.",
  ],
  it: [
    "Il flusso pubblico colloca l’arrivo prima dell’ispezione e del successivo invio del pacco, ma non prova etichette intermedie identiche per ogni account. Conserva quindi il testo visibile senza rafforzarlo. Una scheda utilizzabile risponde solo alla possibilità di procedere senza ipotesi; materiale, autenticità, difetti nascosti e reso restano fuori.",
    "Non costruire l’ingresso dal solo tracking: un pacco può contenere più articoli e il magazzino usare un’altra etichetta. Alias stabili come ITEM-A e PACKAGE-2 collegano note e schermate. Se il mapping non è provato, resta aperto. La scheda con data più vicina non dimostra una relazione.",
    "Se manca il fuso, conserva l’ora letterale e indica zona sconosciuta. La cronologia mostra che il pacco poteva essere visibile a un controllo prima che la scheda fosse utilizzabile. Uno stato successivo non cancella l’incertezza precedente. Un altro revisore può così riprodurre la conclusione consentita in ogni momento.",
    "Registra soltanto campi e azioni visibili. Quantità mancante significa controllata ma non mostrata; non controllata indica audit incompleto. Né miniatura né foto provano ispezione completata. Chiudi solo la prontezza dei dati: identità e passo successivo devono essere comprensibili senza supposizioni.",
    "Una scheda simile a un duplicato può essere seconda quantità, rielaborazione o vero doppione. Conserva entrambe finché l’account le distingue. Combina etichetta ordine, descrizione, opzione, relazione pacco e tempi. Ogni riga attesa ha uno stato attuale esplicito e ogni scheda utilizzabile un’origine tracciabile.",
    "Cerca con etichetta verificata e descrizione e valuta se un pacco combinato o altro arrivo spiega la scheda. La ricerca non ha potuto confermare un tempo universale Kakobuy dalle pagine pubbliche e quindi non ne pubblica. La frase difendibile descrive solo osservazione e orario.",
    "Una cronologia compatta vale più di immagini senza spiegazione. Ritaglia solo mantenendo contesto ed etichetta; oscura altri dati personali. Salva ogni risposta con data, ambito e alias coinvolti. Può risolvere quel caso, ma non diventa una policy universale.",
    "La chiusura può dire: ITEM-A collegato alla scheda W-2; prima osservazione utilizzabile 12 settembre 2026; quantità e condizione in un controllo separato. Prima del passaggio cerca orari sovrascritti, ipotesi, duplicati, pacchi mescolati e dati esposti. Il risultato è limitato ma riproducibile.",
  ],
};

for (const lang of ["de", "es", "fr", "it"] as const) {
  warehouseIntakeArticleData[lang] = {
    ...warehouseIntakeArticleData[lang],
    sections: warehouseIntakeArticleData[lang].sections.map((section, index) => [
      section[0],
      section[1].map((paragraph, paragraphIndex) => paragraphIndex === section[1].length - 1 ? `${paragraph} ${parityAdditions[lang][index]}` : paragraph),
    ]),
  };
}
