export const articleResearch = {
  en: {
    sourceNote: "Research basis checked 01 Sep 2026: the USFans Beginner’s Guide, Shipping Fee Estimation page, Help Center and current product-page notices. Customer-review claims are identified separately and are not treated as verified service facts.",
    dives: {
      "usfans-spreadsheet-guide-2026": [
        ["Build a worksheet that another buyer could audit", "Use one row per exact variant, not one row per broad product family. At minimum, capture the source URL, marketplace, seller name or identifier, item price, domestic delivery, selected color and size, physical measurements, date checked, and the warehouse evidence you will need. Add a status field such as discovery, shortlisted, ordered, received, accepted, returned or archived. That status makes stale links visible instead of silently mixing them with live candidates. In the notes column, distinguish seller statements from things you personally confirmed. A seller image can support identification, but it cannot prove that the unit delivered later will match. Record the rejection reason as carefully as the selection reason: missing chart, ambiguous version, weak return terms, unsuitable material or a parcel that is likely to be too bulky. This structure creates an audit trail from search result to warehouse decision. It also supports useful page updates. When a source route changes, you can update one dated row instead of rewriting an unsupported recommendation."],
        ["Model the two-stage cost before calling a find cheap", "A purchasing-agent order normally contains at least two transport stages: the seller sends the item domestically to the warehouse, and the warehouse later sends a parcel internationally. The first shipping amount shown during product ordering therefore may not represent delivery to your home. Build a cost range with item price, domestic freight, any service or optional inspection charge, packing choices, estimated international freight, insurance and possible destination taxes. Keep known numbers separate from estimates. For example, do not add an exact-looking international price until you have realistic weight and packed dimensions. A low-cost jacket with a large presentation box can be less economical than a slightly higher-priced compact item because international lines may charge by volumetric weight. Use the same exchange-rate date and destination when comparing candidates. The objective is not perfect prediction; it is preventing a visible item price from being mistaken for landed cost. Recalculate immediately before payment and again before parcel submission."],
        ["Use red flags that lead to a concrete action", "A red flag is useful only when it changes what you do. If the size chart lacks units, ask for clarification or remove the listing. If the selected variant is not pictured, require a warehouse photo that identifies it. If seller photos are inconsistent, keep a screenshot and compare the received unit against the exact ordered option. If the source page changes price or seller, mark the row for re-verification rather than preserving an outdated badge. Category-specific rules improve the sheet: shoes need a size basis and, when possible, an insole measurement; garments need physical dimensions; bags need interior and hardware views; electronics need realistic acknowledgment that external photos cannot confirm battery health or internal components. Do not use labels such as “1:1,” “best batch” or “verified” unless you can define and document the test. Neutral fields—evidence available, uncertainty remaining, next action—are more defensible and more useful to readers."],
        ["Maintain the page like a living index", "Set a review cadence based on how quickly the source changes. High-interest or promotional listings deserve more frequent checks than stable guides. On every material update, confirm that the route still opens, the seller and variant still match, the visible price is current, and the item has not moved into a restricted shipping category. Date the change and keep a short reason. Archive dead routes rather than silently redirecting them to unrelated products. For search quality, a smaller page with current, descriptive entries is stronger than a huge table of copied titles and expired links. Group entries by real buyer intent—running-style shoes, heavyweight hoodies, compact accessories—not only by seller vocabulary. Give each group a short original explanation of what must be checked. This helps a reader decide and gives search engines substantive context. The spreadsheet then earns repeat visits because it is maintained, not because it promises a permanent collection of “best finds.”"],
      ],
      "usfans-shipping-cost-guide": [
        ["Work a real volumetric-weight example", "Suppose a packed parcel measures 40 × 30 × 20 centimetres and weighs 2.5 kilograms on a scale. Using the formula currently shown by the USFans estimator, volumetric weight is 40 × 30 × 20 ÷ 6000, which equals 4.0 kilograms. Because 4.0 is higher than 2.5, the planning assumption is a 4.0-kilogram chargeable weight before any route-specific rounding. Now test a smaller packed size. At 36 × 28 × 16 centimetres, the volume result is about 2.69 kilograms. Protection and feasibility still matter, but the comparison shows why removing empty space can be more valuable than shaving a few grams. Do not apply this example blindly to every route: divisors, minimum increments and eligibility can vary. Use it as a diagnostic. If the estimate looks unexpectedly high, inspect the three dimensions, box choice and billing rule before assuming the scale weight or price is wrong."],
        ["Separate DDP, non-DDP and restricted-item decisions", "The official estimator explains DDP as a route where duties and taxes are included and the consignee normally does not need to take action. On a non-DDP route, the recipient may need to provide documents or pay duties and taxes. That distinction affects both budget and workload; it is not merely a label beside the transit time. Customs inspection can still create delays outside the carrier’s direct control. Check destination rules and declaration requirements using current official sources before submission. Route eligibility also changes when a parcel contains liquids, powders, pastes, gels, glass or ceramic, screens, loose or high-power batteries, food, supplements, perishables, illegal or infringing goods, or unsafe packaging—the categories listed by the estimator at the time of review. Acceptance and insurance treatment can differ. Ask before buying a restricted item, because discovering the limitation after warehouse arrival leaves fewer and often more expensive choices."],
        ["Reconcile the estimate with the final invoice", "USFans currently says the final shipping cost on self-operated lines commonly fluctuates around plus or minus five to ten percent. Its explanation points to actual versus volumetric weight, final packed dimensions, route availability and carrier price adjustments. Treat that range as a planning disclosure, not a guarantee that every difference will stay inside it. Save the estimator inputs, timestamp, destination, route, packing services and displayed price. When the parcel is packed, compare the final length, width, height and scale weight with the saved values. A difference usually becomes understandable when those inputs are aligned. If not, ask support for the billing weight, rounding rule and added service line rather than sending a vague complaint. A good shipping guide should teach this reconciliation process because a precise estimate without recorded assumptions is difficult to audit and easy to misremember."],
        ["Choose consolidation with a parcel rehearsal", "The beginner guide currently states that USFans provides 90 days of free storage, so buyers can hold items and consolidate them. Consolidation may reduce repeated base charges, but it is not automatically cheaper. Several light shoe boxes can create a large volume; one restricted item can remove an otherwise suitable route; extra reinforcement can change dimensions. Before submitting, list each item’s approximate weight, compressibility, protection need and restriction status. Sketch one realistic outer carton and calculate its volume. Then compare an alternative such as box removal, splitting a fragile item, or shipping a time-sensitive piece separately. Keep arrival dates visible so the storage window does not become an afterthought. The best parcel is the one that balances chargeable weight, protection, route eligibility, customs treatment and urgency for that basket—not necessarily the parcel containing the maximum number of items."],
      ],
      "how-to-read-usfans-qc-photos": [
        ["Use the five-day notice as a decision clock", "A current USFans product notice says that a buyer dissatisfied after warehouse arrival can apply for a return within five days, with the agent negotiating with the seller. Seller rules, exclusions and return freight can still affect the outcome, so the window should trigger a disciplined review rather than a promise of automatic refund. Start when the arrival notice is received. Confirm the ordered variant and quantity, then review the widest views for wrong item, color, size tag, damage and obvious construction problems. On the same day, list missing decision-critical evidence and request only the views needed to resolve it. Compare new photos promptly and record accept, additional evidence or return request with the date. Do not wait until parcel rehearsal to revisit an unresolved defect. A short clock favors a consistent checklist and clear language. “Ruler across chest width” or “front-facing photo of both heels” is easier to act on than “please check quality.”"],
        ["Use category measurement templates", "For clothing, record chest width, body length, shoulder width and sleeve length according to how the seller chart defines them; doubled flat width is not always stated as body circumference. For trousers, check waist method, rise, inseam and leg opening. For shoes, confirm the ordered size system and request insole length when fit risk justifies it. For bags, useful dimensions include width, height, depth and strap drop. Accessories may need hole spacing, chain length or hardware diameter. Place your target measurement, seller value and warehouse evidence in three adjacent columns. Allow for stated measurement tolerance and fabric behavior instead of demanding impossible precision. The purpose is to identify a material mismatch before international shipping, not to create a pseudo-laboratory test. A ruler photo is powerful when its start point, end point and garment position are visible; a cropped ruler with no context may create more uncertainty."],
        ["Build a visual evidence pack for disputes", "Save the order variant, source-page snapshot, seller chart, original QC set, additional-photo request, response and timestamps in one folder or note. When reporting a problem, use paired evidence: reference image beside warehouse image, expected measurement beside visible ruler, or left item beside right item from the same angle. Mark the relevant area without hiding it. Describe an observable difference—stain near the lower seam, heel heights differ, ordered black but received navy—rather than claiming a cause you cannot prove. This pack helps support understand the request and makes seller negotiation more concrete. It also protects your own judgment from memory drift. Keep in mind that photographs are limited by lighting, lens, compression and angle. Strong evidence shows the same feature from comparable positions and acknowledges what remains unknown."],
        ["Know what QC cannot certify", "The current product pages advertise three to seven free HD QC photos. These images can document visible identity, color, quantity, general shape, labels, seams, hardware and obvious damage when the angles are useful. They cannot by themselves establish authenticity, fibre composition, smell, hidden mold, internal electronics, battery condition or long-term durability. A powered-on screen photo shows one moment, not future reliability. A close-up of a label does not authenticate an item. Use additional evidence when a visible decision can be resolved, and avoid asking photography to answer non-visual questions. This boundary is important for both buyers and honest SEO content: describing QC as a certificate overstates the service. The accurate promise is narrower—warehouse imagery gives the buyer evidence about the received unit before deciding whether to keep, query or attempt a return."],
      ],
      "usfans-review-what-to-check": [
        ["Separate official facts from marketing conclusions", "The official workflow supports purchasing links from Taobao, 1688 and Weidian, warehouse receipt, inspection photos, storage and international parcel submission. Current product pages advertise three to seven free HD QC photos and state a purchase-handling window of 09:00–18:00 UTC+8 after payment. The beginner guide states 90 days of free storage, and a current product notice describes a five-day return-application window after arrival. These are verifiable descriptions of process. They do not prove that every seller dispatches quickly, every photograph catches every defect, every return is accepted or every parcel clears customs without delay. A useful USFans review preserves that boundary. It tests whether the documented tools help a particular buyer manage an order; it does not convert service features into an all-purpose verdict about seller quality or guaranteed delivery."],
        ["Read independent ratings with their current warnings", "On 01 Sep 2026, the USFans Trustpilot page did not show a normal company score because Trustpilot displayed a guideline-breach notice and said it had removed fake reviews. The page showed 716 reviews in total, including 691 from the previous twelve months, with a displayed distribution of 76 percent five-star and 14 percent one-star. Those numbers describe a dated platform snapshot, not independently verified order outcomes. The Apple App Store page showed 3.3 out of 5 from 97 ratings on the same check date. Review text on both platforms included positive reports about support, QC, packaging and delivery, and negative reports involving cost expectations, refunds, delays or returns. Treat every account as customer testimony. Look for detailed, recent patterns and distinguish the domestic warehouse stage from the later international parcel stage. Do not average away contradictory experiences or repeat an allegation as established fact."],
        ["Run a small-order test that produces evidence", "Before committing a valuable or bulky basket, use a small replaceable item to test the workflow. Choose something with clear measurements and no unusual shipping restriction. Before payment, save the source page, selected variant, domestic freight and return note. Record how long purchase handling and seller dispatch actually take for this order. At arrival, inspect the included photos, request one precise measurement if needed and observe response quality. Rehearse the international parcel with realistic dimensions, then compare the estimate with the final bill and tracking. This does not guarantee a future order, but it replaces borrowed confidence with first-hand evidence. Evaluate each stage separately: marketplace seller, agent purchasing, warehouse evidence, packing, carrier and customs. If a failure occurs, this separation tells you where it happened and whether the service still fits your risk tolerance."],
        ["Use a conditional verdict, not a universal score", "A defensible verdict answers a specific question: is the current USFans workflow suitable for this destination, product category, parcel size, deadline and tolerance for seller or customs uncertainty? Buyers who value pre-shipment photos and consolidation may find the tools useful. Buyers expecting the initial domestic freight to cover delivery home, automatic returns or certainty from a star rating may be disappointed. Compare alternatives with the same basket, packing choices, route type and destination rather than comparing headline item prices. Check current terms again at payment and parcel submission because notices and route availability can change. Keep screenshots and dates. The evidence supports a cautious process recommendation—research the seller, start small, use QC deliberately, calculate chargeable weight and keep a reserve for variation. It does not support calling every experience safe, fraudulent, cheap or expensive."],
      ],
    },
    visuals: {
      "usfans-spreadsheet-guide-2026": ["A five-field verification row", [["Source", "Exact route + seller"], ["Variant", "Color · size · version"], ["Measure", "Physical dimensions"], ["Evidence", "QC view required"], ["Cost", "Domestic + international assumptions"]]],
      "usfans-shipping-cost-guide": ["Worked chargeable-weight example", [["Packed size", "40 × 30 × 20 cm"], ["Actual weight", "2.50 kg"], ["Volume weight", "40 × 30 × 20 ÷ 6000 = 4.00 kg"], ["Planning weight", "4.00 kg before route rounding"]]],
      "how-to-read-usfans-qc-photos": ["QC evidence matrix", [["Shoes", "Shape · symmetry · insole"], ["Clothing", "Chest · length · seams"], ["Bags", "Edges · hardware · interior"], ["Electronics", "Visible condition only"]]],
      "usfans-review-what-to-check": ["Evidence hierarchy", [["Official page", "Process and current terms"], ["Warehouse photo", "Visible received unit"], ["Customer review", "Attributed experience, not verified fact"], ["Your test order", "Order-specific evidence"]]],
    },
  },
  de: {
    sourceNote: "Recherchebasis geprüft am 01.09.2026: USFans-Einsteigerleitfaden, Versandkostenrechner, Hilfe-Center und aktuelle Produkthinweise. Kundenberichte werden getrennt gekennzeichnet und nicht als verifizierte Servicefakten behandelt.",
    dives: {
      "usfans-spreadsheet-guide-2026": [
        ["Eine prüfbare Tabelle aufbauen", "Nutze eine Zeile pro exakter Variante und erfasse Quell-URL, Marktplatz, Verkäufer, Artikelpreis, Inlandsversand, Farbe, Größe, Maße, Prüfdatum und benötigte Lagerbelege. Ein Status wie entdeckt, ausgewählt, bestellt, eingetroffen, akzeptiert, retourniert oder archiviert trennt aktuelle Kandidaten von Altlasten. Kennzeichne Verkäuferangaben als solche und dokumentiere auch Ausschlussgründe. Ein Bild hilft bei der Identifikation, beweist aber nicht die spätere gelieferte Einheit. So entsteht eine nachvollziehbare Kette von der Suche bis zur Lagerentscheidung."],
        ["Zweistufige Kosten statt nur Artikelpreis", "Bei einem Agentenauftrag gibt es typischerweise Inlandsversand zum Lager und später internationalen Versand. Der erste Versandbetrag ist daher nicht automatisch die Lieferung nach Hause. Trenne bekannte Werte und Schätzungen: Artikel, Inlandsfracht, Dienste, Verpackung, internationale Fracht, Versicherung und mögliche Abgaben. Nutze für Vergleiche dasselbe Wechselkursdatum, Ziel und dieselben Verpackungsannahmen. Ein günstiger, voluminöser Artikel kann wegen Volumengewicht teurer sein als eine kompakte Alternative. Rechne vor Zahlung und vor Paketeinreichung erneut."],
        ["Warnsignale mit einer Handlung verbinden", "Fehlen Einheiten in der Größentabelle, frage nach oder streiche das Angebot. Ist die Variante nicht abgebildet, verlange einen eindeutig zuordenbaren Lagerbeleg. Ändern sich Preis oder Verkäufer, markiere die Zeile zur Neuprüfung. Schuhe brauchen Größenbasis und möglichst Innenlänge, Kleidung physische Maße, Taschen Innen- und Hardwareansichten. Äußere Fotos von Elektronik bestätigen keine Batterie oder Bauteile. Vermeide unbelegte Begriffe wie „1:1“ oder „verifiziert“; Felder für Beleg, Unsicherheit und nächsten Schritt sind aussagekräftiger."],
        ["Den Index als lebende Seite pflegen", "Prüfe stark nachgefragte und rabattierte Angebote häufiger. Kontrolliere Route, Verkäufer, Variante, Preis und Versandbeschränkungen und datiere wesentliche Änderungen. Tote Links sollten archiviert und nicht auf andere Produkte umgeleitet werden. Für Suchqualität ist ein kleiner, aktueller Index mit eigenen Erklärungen wertvoller als tausende kopierte Titel. Gruppiere nach echter Suchabsicht und erkläre je Gruppe, was zu prüfen ist. Wiederkehrender Nutzen entsteht durch Pflege, nicht durch eine dauerhafte Bestenliste."],
      ],
      "usfans-shipping-cost-guide": [
        ["Ein echtes Volumengewicht berechnen", "Ein Paket mit 40 × 30 × 20 cm und 2,5 kg ergibt nach der aktuellen USFans-Formel 40 × 30 × 20 ÷ 6000 = 4,0 kg Volumengewicht. Da 4,0 höher als 2,5 ist, dient vor routenspezifischer Rundung 4,0 kg als Planungsgewicht. Bei 36 × 28 × 16 cm wären es rund 2,69 kg. Der Vergleich zeigt den Wert kleinerer Außenmaße, solange Schutz und Machbarkeit erhalten bleiben. Teiler, Mindestschritte und Regeln können je Route abweichen; prüfe deshalb immer die aktuelle Linie."],
        ["DDP, Nicht-DDP und Einschränkungen trennen", "Der offizielle Rechner beschreibt DDP mit enthaltenen Zöllen und Steuern, normalerweise ohne Handlung des Empfängers. Bei Nicht-DDP können Dokumente und Zahlungen nötig werden. Zollprüfungen können dennoch verzögern. Flüssigkeiten, Pulver, Pasten, Gele, Glas, Keramik, Bildschirme, lose oder starke Batterien, Lebensmittel, Ergänzungsmittel, Verderbliches, illegale oder rechtsverletzende Waren und unsichere Verpackung können die Route und Versicherung verändern. Kläre dies vor dem Kauf."],
        ["Schätzung und Endbetrag abgleichen", "USFans nennt für eigene Linien üblicherweise etwa ±5–10 Prozent Schwankung und verweist auf Real- oder Volumengewicht, Endmaße, Verfügbarkeit und Anpassungen des Transporteurs. Das ist ein Planungshinweis, keine Garantie. Speichere Eingaben, Zeit, Ziel, Route, Dienste und Preis. Vergleiche nach dem Packen Maße und Gewicht. Bleibt eine Differenz, frage nach Abrechnungsgewicht, Rundung und Zusatzdiensten. Nur gespeicherte Annahmen machen eine Abweichung prüfbar."],
        ["Konsolidierung mit Paketprobe wählen", "Der Einsteigerleitfaden nennt 90 Tage kostenlose Lagerung. Konsolidierung kann Grundgebühren reduzieren, ist aber nicht automatisch günstiger: Schuhkartons erhöhen Volumen, ein beschränkter Artikel kann Routen ausschließen und Verstärkung verändert Maße. Liste Gewicht, Komprimierbarkeit, Schutzbedarf und Einschränkungen je Artikel. Rechne eine realistische Außenbox sowie Alternativen wie Kartonentfernung oder Aufteilung. Beachte Ankunftsdaten. Optimal ist die Balance aus Abrechnungsgewicht, Schutz, Eignung, Zoll und Dringlichkeit."],
      ],
      "how-to-read-usfans-qc-photos": [
        ["Den Fünf-Tage-Hinweis als Uhr nutzen", "Ein aktueller Produkthinweis beschreibt einen Rückgabeantrag innerhalb von fünf Tagen nach Lagereingang; Verkäuferregeln, Ausschlüsse und Rückfracht bleiben relevant. Prüfe deshalb sofort Variante, Menge, Gesamtansichten, Größe, Schäden und Konstruktion. Fordere fehlende entscheidende Ansichten am selben Tag präzise an und datiere Annahme, Nachweisforderung oder Rückgabeantrag. „Lineal über Brustweite“ ist handlungsfähiger als „Qualität prüfen“. Verschiebe einen ungeklärten Mangel nicht bis zur Paketeinreichung."],
        ["Messvorlagen je Kategorie verwenden", "Bei Kleidung sind Brustweite, Länge, Schulter und Ärmel wichtig; flache Breite ist nicht automatisch Umfang. Hosen brauchen Taillenmethode, Leibhöhe, Innenbein und Öffnung. Bei Schuhen Größen­system und möglichst Innenlänge, bei Taschen Breite, Höhe, Tiefe und Riemenfall erfassen. Stelle Zielmaß, Verkäuferwert und Lagerbeleg nebeneinander. Berücksichtige Toleranz und Material. Ein Linealfoto ist nur aussagekräftig, wenn Start, Ende und Lage sichtbar sind."],
        ["Ein Belegpaket für Reklamationen", "Speichere Variante, Quellseite, Größentabelle, QC-Satz, Zusatzanfrage, Antwort und Zeitpunkte gemeinsam. Nutze paarweise Belege: Referenz neben Lagerfoto oder Sollmaß neben sichtbarem Lineal. Beschreibe Beobachtbares wie Fleck, abweichende Absatzhöhe oder falsche Farbe statt eine unbeweisbare Ursache. Vergleichbare Winkel helfen Support und Verkäuferverhandlung und schützen vor Erinnerungslücken. Licht, Objektiv, Kompression und Perspektive bleiben Grenzen der Fotografie."],
        ["Grenzen der QC-Fotos kennen", "Aktuelle Produktseiten werben mit drei bis sieben kostenlosen HD-Fotos. Sie können sichtbare Identität, Farbe, Menge, Form, Nähte, Beschläge und Schäden dokumentieren. Sie bestätigen nicht automatisch Echtheit, Faser, Geruch, versteckte Mängel, innere Elektronik, Batterie oder Haltbarkeit. Ein eingeschalteter Bildschirm ist nur eine Momentaufnahme. QC ist deshalb ein Bildbeleg vor der Entscheidung, kein Zertifikat. Ehrlicher Inhalt beschreibt diese engere, aber nützliche Funktion."],
      ],
      "usfans-review-what-to-check": [
        ["Fakten von Schlussfolgerungen trennen", "Offizielle Seiten beschreiben Einkauf über Taobao, 1688 und Weidian, Lagereingang, Fotos, Lagerung und internationalen Versand. Produktseiten nennen drei bis sieben QC-Fotos und 09:00–18:00 UTC+8 als Bearbeitungsfenster nach Zahlung. Der Leitfaden nennt 90 Tage Lagerung; ein Hinweis beschreibt fünf Tage für den Rückgabeantrag. Diese Prozessfakten garantieren weder schnellen Verkäufer­versand noch vollständige Fehlererkennung, Rückgabeannahme oder problemlose Zollabfertigung."],
        ["Bewertungen mit aktuellem Warnhinweis lesen", "Am 01.09.2026 zeigte Trustpilot für USFans wegen eines Richtlinienverstoßes keinen normalen Score und erklärte, gefälschte Bewertungen entfernt zu haben. Sichtbar waren 716 Bewertungen, davon 691 in zwölf Monaten, mit 76 Prozent fünf und 14 Prozent einem Stern. Der App Store zeigte 3,3 von 5 bei 97 Bewertungen. Texte berichteten positiv über Support, QC, Verpackung und Lieferung sowie negativ über Kosten, Erstattungen, Verzögerungen und Retouren. Das sind datierte, zugeschriebene Erfahrungen, keine verifizierten Bestellfakten."],
        ["Mit einer kleinen Bestellung selbst testen", "Teste zuerst einen ersetzbaren, klar messbaren und nicht beschränkten Artikel. Speichere Quelle, Variante, Inlandsfracht und Rückgabehinweis. Messe tatsächliche Zeiten, prüfe Fotos, fordere bei Bedarf ein Maß an und vergleiche Schätzung, Endbetrag und Tracking. Bewerte Verkäufer, Agentenkauf, Lager, Verpackung, Transporteur und Zoll getrennt. Der Test garantiert keine Zukunft, liefert aber eigene Daten statt geliehener Sicherheit."],
        ["Ein bedingtes Urteil formulieren", "Die sinnvolle Frage lautet, ob der aktuelle Ablauf zu Ziel, Kategorie, Paket, Termin und Risikotoleranz passt. Fotos und Konsolidierung können nützlich sein; wer den ersten Inlandsversand als Haustürpreis, automatische Retouren oder Sicherheit durch Sterne erwartet, kann enttäuscht werden. Vergleiche Alternativen mit identischem Warenkorb und prüfe Bedingungen erneut. Die Belege stützen einen vorsichtigen Prozess: Verkäufer prüfen, klein beginnen, QC gezielt nutzen, Abrechnungsgewicht rechnen und Reserve einplanen—not ein universelles Gut- oder Schlechturteil."],
      ],
    },
    visuals: {
      "usfans-spreadsheet-guide-2026": ["Prüfzeile mit fünf Feldern", [["Quelle","Route + Verkäufer"],["Variante","Farbe · Größe · Version"],["Maß","Physische Maße"],["Beleg","Benötigte QC-Ansicht"],["Kosten","Inland + internationale Annahmen"]]],
      "usfans-shipping-cost-guide": ["Beispiel Abrechnungsgewicht", [["Paketmaß","40 × 30 × 20 cm"],["Realgewicht","2,50 kg"],["Volumengewicht","40 × 30 × 20 ÷ 6000 = 4,00 kg"],["Planungsgewicht","4,00 kg vor Rundung"]]],
      "how-to-read-usfans-qc-photos": ["QC-Belegmatrix", [["Schuhe","Form · Symmetrie · Innenlänge"],["Kleidung","Brust · Länge · Nähte"],["Taschen","Kanten · Hardware · Innenraum"],["Elektronik","Nur sichtbarer Zustand"]]],
      "usfans-review-what-to-check": ["Beleghierarchie", [["Offizielle Seite","Prozess und aktuelle Regeln"],["Lagerfoto","Sichtbare erhaltene Einheit"],["Kundenbericht","Zugeschrieben, nicht verifiziert"],["Eigener Test","Auftragsspezifischer Beleg"]]],
    },
  },
  es: {
    sourceNote: "Base de investigación comprobada el 01/09/2026: guía inicial, estimador de envío, centro de ayuda y avisos de producto actuales de USFans. Los comentarios de clientes se identifican aparte y no se presentan como hechos verificados del servicio.",
    dives: {
      "usfans-spreadsheet-guide-2026": [
        ["Crea una hoja que otro comprador pueda auditar", "Usa una fila para cada variante exacta. Registra URL, marketplace, vendedor, precio, transporte nacional, color, talla, medidas, fecha de revisión y prueba que necesitarás del almacén. Un estado —descubierto, seleccionado, pedido, recibido, aceptado, devuelto o archivado— evita mezclar rutas antiguas con candidatos vivos. Separa lo que afirma el vendedor de lo que tú has comprobado y anota también el motivo de descarte. Una imagen ayuda a identificar, pero no demuestra cómo será la unidad recibida. La hoja se convierte así en una trazabilidad desde la búsqueda hasta la decisión de almacén."],
        ["Calcula dos etapas antes de llamar barato a un producto", "Un pedido con agente suele incluir transporte nacional del vendedor al almacén y, después, paquete internacional. El primer importe de envío no siempre llega a casa. Separa cifras conocidas y estimaciones: artículo, envío nacional, servicio, embalaje, transporte internacional, seguro e impuestos posibles. Compara con la misma fecha de cambio, destino y supuestos. Un artículo barato con caja grande puede salir peor que otro compacto porque una línea puede cobrar peso volumétrico. Recalcula antes del pago y antes de presentar el paquete; el objetivo es no confundir precio visible con coste puesto en destino."],
        ["Convierte cada alerta en una acción", "Si una tabla no tiene unidades, pregunta o elimina la ficha. Si la variante elegida no aparece, exige una foto de almacén que la identifique. Si cambian precio o vendedor, marca la fila para nueva revisión. El calzado necesita base de talla e idealmente plantilla; la ropa, medidas físicas; los bolsos, interior y herrajes. Una foto exterior de electrónica no confirma batería o componentes. Evita etiquetas sin prueba como “1:1” o “verificado”. Los campos prueba disponible, duda restante y siguiente acción son más útiles y defendibles."],
        ["Mantén la página como índice vivo", "Revisa con más frecuencia las fichas populares o promocionales. Confirma ruta, vendedor, variante, precio y restricciones, y fecha los cambios relevantes. Archiva rutas muertas en vez de redirigirlas silenciosamente a otro producto. Para la calidad de búsqueda, un índice pequeño, actual y explicado con texto propio supera a miles de títulos copiados. Agrupa por intención real del comprador y explica qué revisar en cada grupo. Las visitas repetidas se ganan con mantenimiento, no prometiendo una lista permanente de “mejores hallazgos”."],
      ],
      "usfans-shipping-cost-guide": [
        ["Ejemplo real de peso volumétrico", "Un paquete de 40 × 30 × 20 cm y 2,5 kg produce, con la fórmula actual, 40 × 30 × 20 ÷ 6000 = 4,0 kg. Como 4,0 supera 2,5, se planifica con 4,0 kg antes del redondeo de la ruta. Si mide 36 × 28 × 16 cm, el resultado baja a unos 2,69 kg. El ejemplo muestra el valor de quitar espacio vacío sin sacrificar protección. No lo apliques ciegamente: divisor, incrementos mínimos y elegibilidad pueden variar. Si la cifra sorprende, revisa dimensiones, caja y regla de cobro antes de culpar al peso real."],
        ["Separa DDP, no DDP y artículos restringidos", "El estimador describe DDP con aranceles e impuestos incluidos y normalmente sin acción del destinatario. En no DDP pueden exigirse documentos o pagos. Una inspección aduanera todavía puede retrasar. Líquidos, polvos, pastas, geles, vidrio o cerámica, pantallas, baterías sueltas o potentes, comida, suplementos, perecederos, mercancía ilegal o infractora y embalaje inseguro pueden alterar ruta y seguro. Confírmalo antes de comprar, porque descubrir la limitación cuando el artículo ya está en almacén deja opciones más caras."],
        ["Concilia estimación y factura final", "USFans indica que el coste final de líneas propias suele fluctuar alrededor de ±5–10% por peso real o volumétrico, dimensiones finales, disponibilidad y ajustes del transportista. Es una referencia de planificación, no una garantía universal. Guarda entradas, fecha, destino, ruta, servicios y precio. Tras embalar, compara largo, ancho, alto y peso. Si la diferencia no se explica, pide peso facturado, redondeo y servicios añadidos. Una estimación sin supuestos guardados es difícil de auditar."],
        ["Decide la consolidación con un ensayo de paquete", "La guía actual indica 90 días de almacenaje gratuito. Consolidar puede reducir cargos base repetidos, pero no siempre abarata: las cajas ocupan volumen, un artículo restringido puede eliminar rutas y el refuerzo cambia medidas. Lista peso, compresibilidad, protección y restricciones de cada pieza. Calcula una caja exterior realista y alternativas como quitar cajas o separar un artículo frágil. Controla fechas de llegada. El mejor paquete equilibra peso facturable, protección, elegibilidad, aduanas y urgencia."],
      ],
      "how-to-read-usfans-qc-photos": [
        ["Usa el aviso de cinco días como reloj", "Un aviso de producto actual describe una solicitud de devolución dentro de cinco días tras la llegada; siguen importando reglas del vendedor, exclusiones y coste de retorno. Revisa de inmediato variante, cantidad, vistas generales, talla, daño y construcción. Pide el mismo día las imágenes decisivas que falten y registra aceptación, solicitud adicional o devolución con fecha. “Regla sobre el pecho” permite actuar mejor que “revisa la calidad”. No pospongas un defecto sin resolver hasta el envío internacional."],
        ["Utiliza plantillas de medida por categoría", "En ropa registra pecho, largo, hombro y manga según la definición del vendedor; ancho plano no siempre significa contorno. En pantalón, método de cintura, tiro, entrepierna y bajo. En calzado, sistema de talla y plantilla cuando proceda. En bolsos, ancho, alto, fondo y caída de correa. Coloca objetivo, dato del vendedor y prueba de almacén juntos. Considera tolerancia y tejido. Una regla solo ayuda si se ven inicio, final y posición de la prenda."],
        ["Prepara un expediente visual para incidencias", "Guarda variante, captura de fuente, tabla, fotos QC, petición extra, respuesta y fechas. Presenta pruebas emparejadas: referencia junto a foto de almacén o medida esperada junto a regla visible. Describe diferencias observables —mancha, alturas distintas, color equivocado— sin inventar la causa. Ángulos comparables ayudan al soporte y a la negociación con el vendedor. Luz, lente, compresión y perspectiva siguen limitando una fotografía."],
        ["Conoce lo que QC no puede certificar", "Las fichas actuales anuncian entre tres y siete fotos HD gratuitas. Pueden documentar identidad visible, color, cantidad, forma, costuras, herrajes y daño obvio. No prueban por sí solas autenticidad, fibra, olor, moho oculto, electrónica interna, batería o duración. Una pantalla encendida solo muestra un momento. QC aporta prueba visual antes de decidir; no es un certificado. Esa promesa más estrecha es también más honesta y útil."],
      ],
      "usfans-review-what-to-check": [
        ["Separa hechos oficiales de conclusiones", "Las fuentes oficiales describen compra desde Taobao, 1688 y Weidian, recepción, fotos, almacenamiento y paquete internacional. Las fichas anuncian 3–7 fotos QC y gestión de compra de 09:00 a 18:00 UTC+8 tras pagar. La guía indica 90 días gratuitos y un aviso actual habla de cinco días para solicitar devolución. Son hechos de proceso; no garantizan despacho rápido del vendedor, detección de todo defecto, retorno aceptado ni aduana sin retrasos."],
        ["Lee valoraciones con su advertencia actual", "El 01/09/2026 Trustpilot no mostraba una puntuación normal para USFans por incumplimiento de sus normas y decía haber retirado reseñas falsas. Mostraba 716 reseñas, 691 de los doce meses anteriores, con 76% de cinco estrellas y 14% de una. App Store mostraba 3,3/5 con 97 valoraciones. Los textos incluían experiencias positivas sobre soporte, QC, embalaje y entrega, y negativas sobre costes, reembolsos, demoras o devoluciones. Son testimonios atribuidos y fechados, no resultados verificados."],
        ["Haz una prueba pequeña que produzca pruebas", "Empieza con un artículo reemplazable, medible y sin restricción especial. Guarda fuente, variante, transporte nacional y aviso de retorno. Mide los tiempos reales, revisa las fotos, pide una medida precisa y compara estimación, factura y seguimiento. Evalúa por separado vendedor, compra del agente, almacén, embalaje, transportista y aduanas. No garantiza otro pedido, pero sustituye confianza prestada por datos propios."],
        ["Formula un veredicto condicionado", "Pregunta si el flujo actual encaja con destino, categoría, tamaño, plazo y tolerancia al riesgo. Fotos y consolidación pueden ayudar; quien espere que el primer envío nacional llegue a casa, devoluciones automáticas o certeza de una estrella media puede decepcionarse. Compara alternativas con la misma cesta y revisa condiciones al pagar y enviar. La evidencia apoya un proceso prudente: verificar vendedor, empezar pequeño, usar QC, calcular peso facturable y reservar margen; no una etiqueta universal."],
      ],
    },
    visuals: {
      "usfans-spreadsheet-guide-2026": ["Fila de verificación en cinco campos", [["Fuente","Ruta + vendedor"],["Variante","Color · talla · versión"],["Medida","Dimensiones físicas"],["Prueba","Vista QC necesaria"],["Coste","Supuestos nacionales e internacionales"]]],
      "usfans-shipping-cost-guide": ["Ejemplo de peso facturable", [["Paquete","40 × 30 × 20 cm"],["Peso real","2,50 kg"],["Peso volumen","40 × 30 × 20 ÷ 6000 = 4,00 kg"],["Peso de cálculo","4,00 kg antes del redondeo"]]],
      "how-to-read-usfans-qc-photos": ["Matriz de pruebas QC", [["Calzado","Forma · simetría · plantilla"],["Ropa","Pecho · largo · costuras"],["Bolsos","Bordes · herrajes · interior"],["Electrónica","Solo estado visible"]]],
      "usfans-review-what-to-check": ["Jerarquía de pruebas", [["Página oficial","Proceso y condiciones"],["Foto almacén","Unidad visible recibida"],["Reseña cliente","Experiencia atribuida"],["Pedido propio","Prueba de ese pedido"]]],
    },
  },
  fr: {
    sourceNote: "Base de recherche vérifiée le 01/09/2026 : guide débutant, estimateur, centre d’aide et avis produit actuels de USFans. Les témoignages clients sont signalés séparément et ne sont pas traités comme des faits vérifiés.",
    dives: {
      "usfans-spreadsheet-guide-2026": [
        ["Construire une feuille qu’un autre acheteur peut auditer", "Utilisez une ligne par variante exacte. Notez URL, marketplace, vendeur, prix, transport national, couleur, taille, mesures, date de contrôle et preuve attendue de l’entrepôt. Un statut — découvert, retenu, commandé, reçu, accepté, retourné ou archivé — sépare les candidats actifs des anciennes routes. Distinguez les affirmations vendeur de vos confirmations et consignez aussi le motif de rejet. Une image aide à identifier mais ne prouve pas l’unité qui sera reçue. La feuille crée ainsi une trace de la recherche à la décision en entrepôt."],
        ["Modéliser deux étapes avant de dire bon marché", "Une commande via agent comporte généralement le transport national vers l’entrepôt puis le colis international. Le premier montant n’est donc pas toujours la livraison à domicile. Séparez valeurs connues et estimations : article, fret national, service, emballage, international, assurance et taxes possibles. Comparez avec la même date de change, destination et hypothèses. Un article peu cher mais volumineux peut coûter plus qu’un produit compact en raison du poids volumétrique. Recalculez avant paiement et avant soumission du colis pour ne pas confondre prix affiché et coût rendu."],
        ["Associer chaque signal d’alerte à une action", "Si le guide des tailles n’a pas d’unités, demandez ou éliminez la fiche. Si la variante choisie n’est pas montrée, exigez une photo identifiable. Si prix ou vendeur changent, marquez la ligne pour nouvelle vérification. Les chaussures demandent base de pointure et idéalement semelle intérieure ; les vêtements, mesures physiques ; les sacs, intérieur et pièces métalliques. Une photo d’électronique ne confirme ni batterie ni composants. Évitez « 1:1 » ou « vérifié » sans test ; preuve disponible, doute restant et action suivante sont plus utiles."],
        ["Maintenir la page comme un index vivant", "Contrôlez plus souvent les fiches populaires ou promotionnelles. Confirmez route, vendeur, variante, prix et restrictions, puis datez les changements importants. Archivez une route morte au lieu de la rediriger silencieusement. Pour la recherche, un index réduit, actuel et expliqué avec un texte original vaut mieux que des milliers de titres copiés. Regroupez selon l’intention réelle et expliquez les contrôles propres à chaque groupe. La fidélité vient de la maintenance, pas d’une promesse permanente de « meilleures trouvailles »."],
      ],
      "usfans-shipping-cost-guide": [
        ["Calculer un exemple réel de poids volumétrique", "Un colis de 40 × 30 × 20 cm pesant 2,5 kg donne 40 × 30 × 20 ÷ 6000 = 4,0 kg selon la formule actuelle. Comme 4,0 dépasse 2,5, on planifie 4,0 kg avant l’arrondi de la ligne. À 36 × 28 × 16 cm, le volume serait environ 2,69 kg. L’exemple montre l’intérêt de réduire le vide sans sacrifier la protection. Diviseur, incréments et admissibilité peuvent varier : vérifiez la ligne. Si le prix surprend, examinez dimensions, boîte et règle de facturation avant le poids de balance."],
        ["Séparer DDP, non-DDP et restrictions", "L’estimateur décrit DDP droits et taxes inclus, normalement sans action du destinataire. En non-DDP, documents ou paiements peuvent être requis. Une inspection douanière peut toujours retarder. Liquides, poudres, pâtes, gels, verre, céramique, écrans, batteries libres ou puissantes, aliments, compléments, périssables, biens illégaux ou contrefaisants et emballage dangereux peuvent modifier ligne et assurance. Vérifiez avant achat, car une restriction découverte en entrepôt laisse moins d’options."],
        ["Rapprocher estimation et facture finale", "USFans indique une fluctuation habituelle d’environ ±5–10% sur ses lignes propres, liée au poids réel ou volumétrique, dimensions finales, disponibilité et ajustements transporteur. C’est une indication, pas une garantie. Sauvegardez entrées, date, destination, ligne, services et prix. Après emballage, comparez les quatre mesures. Si l’écart demeure, demandez poids facturé, arrondi et services ajoutés. Sans hypothèses enregistrées, une estimation est difficile à auditer."],
        ["Choisir la consolidation après répétition du colis", "Le guide indique 90 jours de stockage gratuit. Consolider peut réduire des frais de base répétés, sans être toujours moins cher : boîtes volumineuses, article restreint et renfort changent les options. Listez poids, compressibilité, protection et restrictions. Calculez un carton extérieur réaliste et des alternatives comme retrait de boîte ou séparation d’un objet fragile. Suivez les dates d’arrivée. Le bon colis équilibre poids facturable, protection, admissibilité, douane et urgence."],
      ],
      "how-to-read-usfans-qc-photos": [
        ["Utiliser l’avis de cinq jours comme horloge", "Un avis produit actuel décrit une demande de retour sous cinq jours après arrivée ; règles vendeur, exclusions et fret retour restent applicables. Vérifiez immédiatement variante, quantité, vues générales, taille, dommages et construction. Demandez le jour même les images décisives manquantes et datez acceptation, demande ou retour. « Règle sur la poitrine » est plus exploitable que « vérifiez la qualité ». Ne reportez pas un défaut irrésolu jusqu’au colis international."],
        ["Employer des modèles de mesure par catégorie", "Pour les vêtements, notez poitrine, longueur, épaules et manches selon la définition vendeur ; une largeur à plat n’est pas toujours le tour. Pour pantalon : taille, fourche, entrejambe et ouverture. Pour chaussures : système de pointure et semelle intérieure si utile. Pour sacs : largeur, hauteur, profondeur et tombé de sangle. Placez cible, valeur vendeur et preuve d’entrepôt ensemble. Tenez compte des tolérances. Une règle n’aide que si départ, arrivée et position sont visibles."],
        ["Préparer un dossier visuel pour litige", "Conservez variante, capture source, tableau, photos QC, demande supplémentaire, réponse et dates. Présentez des paires : référence à côté de l’entrepôt ou mesure attendue à côté de la règle. Décrivez un écart observable — tache, talons différents, mauvaise couleur — sans inventer sa cause. Des angles comparables aident support et négociation. Lumière, objectif, compression et perspective restent les limites d’une photo."],
        ["Connaître ce que le QC ne certifie pas", "Les fiches actuelles annoncent trois à sept photos HD gratuites. Elles peuvent documenter identité visible, couleur, quantité, forme, coutures, pièces et dommages évidents. Elles ne prouvent pas seules authenticité, fibre, odeur, moisissure cachée, électronique interne, batterie ou durée. Un écran allumé est un instant. Le QC apporte une preuve visuelle avant décision ; ce n’est pas un certificat. Cette promesse limitée est plus honnête et utile."],
      ],
      "usfans-review-what-to-check": [
        ["Séparer faits officiels et conclusions", "Les sources officielles décrivent achat depuis Taobao, 1688 et Weidian, réception, photos, stockage et colis international. Les fiches annoncent 3–7 photos QC et un traitement des achats de 09:00 à 18:00 UTC+8 après paiement. Le guide indique 90 jours gratuits et un avis actuel cinq jours pour demander un retour. Ce sont des faits de processus ; ils ne garantissent ni expédition vendeur rapide, ni détection de tout défaut, ni retour accepté, ni douane sans retard."],
        ["Lire les notes avec leur avertissement actuel", "Le 01/09/2026, Trustpilot n’affichait pas de score normal pour USFans à cause d’une violation de ses règles et disait avoir supprimé de faux avis. La page montrait 716 avis, dont 691 sur douze mois, avec 76% cinq étoiles et 14% une étoile. L’App Store affichait 3,3/5 pour 97 notes. Les textes comprenaient des expériences positives sur support, QC, emballage et livraison, et négatives sur coût, remboursement, retard ou retour. Ce sont des témoignages datés et attribués, pas des résultats vérifiés."],
        ["Faire un petit test qui produit des preuves", "Commencez par un article remplaçable, mesurable et non restreint. Sauvegardez source, variante, fret national et avis de retour. Mesurez les délais, examinez les photos, demandez une mesure précise et comparez estimation, facture et suivi. Évaluez séparément vendeur, achat agent, entrepôt, emballage, transporteur et douane. Le test ne garantit pas l’avenir, mais remplace une confiance empruntée par vos propres données."],
        ["Formuler un verdict conditionnel", "Demandez si le parcours actuel convient à la destination, catégorie, taille, délai et tolérance au risque. Photos et consolidation peuvent aider ; attendre du premier fret national une livraison à domicile, un retour automatique ou la certitude d’une note peut décevoir. Comparez avec le même panier et revérifiez les conditions. Les preuves soutiennent un processus prudent : vérifier le vendeur, commencer petit, utiliser le QC, calculer le poids facturable et garder une marge, pas une étiquette universelle."],
      ],
    },
    visuals: {
      "usfans-spreadsheet-guide-2026": ["Ligne de vérification en cinq champs", [["Source","Route + vendeur"],["Variante","Couleur · taille · version"],["Mesure","Dimensions physiques"],["Preuve","Vue QC nécessaire"],["Coût","Hypothèses nationales et internationales"]]],
      "usfans-shipping-cost-guide": ["Exemple de poids facturable", [["Colis","40 × 30 × 20 cm"],["Poids réel","2,50 kg"],["Poids volume","40 × 30 × 20 ÷ 6000 = 4,00 kg"],["Poids planifié","4,00 kg avant arrondi"]]],
      "how-to-read-usfans-qc-photos": ["Matrice de preuves QC", [["Chaussures","Forme · symétrie · semelle"],["Vêtements","Poitrine · longueur · coutures"],["Sacs","Bords · pièces · intérieur"],["Électronique","État visible uniquement"]]],
      "usfans-review-what-to-check": ["Hiérarchie des preuves", [["Page officielle","Parcours et règles"],["Photo entrepôt","Unité reçue visible"],["Avis client","Expérience attribuée"],["Votre test","Preuve de cette commande"]]],
    },
  },
  it: {
    sourceNote: "Base di ricerca verificata il 01/09/2026: guida iniziale, calcolatore spedizione, centro assistenza e avvisi prodotto USFans attuali. Le esperienze dei clienti sono indicate separatamente e non diventano fatti verificati.",
    dives: {
      "usfans-spreadsheet-guide-2026": [
        ["Crea un foglio verificabile da un altro acquirente", "Usa una riga per variante esatta. Registra URL, marketplace, venditore, prezzo, trasporto nazionale, colore, taglia, misure, data e prova necessaria dal magazzino. Uno stato — scoperto, selezionato, ordinato, ricevuto, accettato, reso o archiviato — separa candidati vivi e vecchi percorsi. Distingui le affermazioni del venditore dalle tue conferme e annota anche il motivo di esclusione. Un’immagine aiuta a identificare ma non prova l’unità che arriverà. Il foglio crea così una traccia dalla ricerca alla decisione in magazzino."],
        ["Modella due fasi prima di dire conveniente", "Un ordine tramite agente comprende di solito trasporto nazionale al magazzino e poi pacco internazionale. Il primo costo visibile non è necessariamente la consegna a casa. Separa valori noti e stime: articolo, spedizione interna, servizio, imballaggio, internazionale, assicurazione e possibili imposte. Confronta con stessa data di cambio, destinazione e ipotesi. Un articolo economico ma voluminoso può costare più di uno compatto a causa del peso volumetrico. Ricalcola prima del pagamento e prima dell’invio; non confondere prezzo esposto e costo finale."],
        ["Collega ogni segnale a un’azione", "Se la tabella taglie non ha unità, chiedi o elimina la scheda. Se la variante non è mostrata, richiedi una foto che la identifichi. Se prezzo o venditore cambiano, marca la riga da ricontrollare. Le scarpe richiedono base taglia e possibilmente soletta; gli abiti misure fisiche; le borse interno e ferramenta. Foto esterne dell’elettronica non confermano batteria o componenti. Evita “1:1” o “verificato” senza test: prova disponibile, dubbio residuo e prossima azione sono più utili."],
        ["Mantieni la pagina come indice vivo", "Controlla più spesso schede popolari o promozionali. Conferma percorso, venditore, variante, prezzo e restrizioni e data ogni modifica rilevante. Archivia i link morti invece di reindirizzarli in silenzio. Per la qualità di ricerca, un indice più piccolo, attuale e spiegato con testo originale vale più di migliaia di titoli copiati. Raggruppa per intento reale e spiega i controlli di ogni gruppo. Le visite ripetute derivano dalla manutenzione, non dalla promessa di una lista eterna dei migliori prodotti."],
      ],
      "usfans-shipping-cost-guide": [
        ["Calcola un esempio reale di peso volumetrico", "Un pacco da 40 × 30 × 20 cm e 2,5 kg produce 40 × 30 × 20 ÷ 6000 = 4,0 kg con la formula attuale. Poiché 4,0 supera 2,5, si pianificano 4,0 kg prima dell’arrotondamento della linea. A 36 × 28 × 16 cm il volume scende a circa 2,69 kg. L’esempio mostra il valore di eliminare spazio senza sacrificare protezione. Divisore, incrementi ed eleggibilità possono variare; controlla la linea. Se la cifra sorprende, verifica dimensioni, scatola e regola di fatturazione."],
        ["Separa DDP, non-DDP e restrizioni", "Il calcolatore descrive DDP con dazi e imposte inclusi, normalmente senza azione del destinatario. Con non-DDP possono servire documenti o pagamenti. Un controllo doganale può comunque ritardare. Liquidi, polveri, paste, gel, vetro, ceramica, schermi, batterie libere o potenti, cibo, integratori, deperibili, beni illegali o lesivi e imballaggio insicuro possono modificare linea e assicurazione. Verifica prima dell’acquisto: scoprirlo in magazzino lascia meno opzioni."],
        ["Riconcilia stima e fattura finale", "USFans indica per le linee proprie una variazione abituale di circa ±5–10%, legata a peso reale o volume, dimensioni finali, disponibilità e adeguamenti del vettore. È un riferimento, non garanzia. Salva dati, data, destinazione, linea, servizi e prezzo. Dopo l’imballaggio confronta le quattro misure. Se resta una differenza, chiedi peso fatturato, arrotondamento e servizi aggiunti. Senza ipotesi salvate, una stima non è verificabile."],
        ["Scegli il consolidamento con una prova del pacco", "La guida indica 90 giorni di deposito gratuito. Consolidare può ridurre costi base ripetuti ma non sempre conviene: scatole grandi, un articolo limitato o il rinforzo cambiano le opzioni. Elenca peso, comprimibilità, protezione e restrizioni. Calcola una scatola esterna realistica e alternative come togliere scatole o separare un oggetto fragile. Controlla le date di arrivo. Il pacco migliore bilancia peso fatturabile, protezione, eleggibilità, dogana e urgenza."],
      ],
      "how-to-read-usfans-qc-photos": [
        ["Usa l’avviso di cinque giorni come orologio", "Un avviso attuale descrive la domanda di reso entro cinque giorni dall’arrivo; restano regole del venditore, esclusioni e costo del reso. Controlla subito variante, quantità, viste generali, taglia, danno e costruzione. Chiedi lo stesso giorno le immagini decisive mancanti e data accettazione, richiesta o reso. “Righello sul petto” è più pratico di “controlla qualità”. Non rimandare un difetto irrisolto alla spedizione internazionale."],
        ["Usa modelli di misura per categoria", "Per gli abiti registra petto, lunghezza, spalla e manica secondo la definizione del venditore; la larghezza piatta non è sempre circonferenza. Per pantaloni: vita, cavallo, interno gamba e fondo. Per scarpe: sistema taglia e soletta quando utile. Per borse: larghezza, altezza, profondità e caduta tracolla. Metti insieme obiettivo, valore venditore e prova del magazzino. Considera tolleranza e tessuto. Un righello aiuta solo se inizio, fine e posizione sono visibili."],
        ["Prepara un dossier visivo per contestazioni", "Conserva variante, fonte, tabella, foto QC, richiesta extra, risposta e date. Usa prove abbinate: riferimento vicino alla foto del magazzino o misura attesa vicino al righello. Descrivi differenze osservabili — macchia, talloni diversi, colore errato — senza inventare la causa. Angoli comparabili aiutano assistenza e negoziazione. Luce, lente, compressione e prospettiva restano limiti della fotografia."],
        ["Conosci ciò che il QC non certifica", "Le schede attuali pubblicizzano da tre a sette foto HD gratuite. Possono documentare identità visibile, colore, quantità, forma, cuciture, ferramenta e danno evidente. Non provano da sole autenticità, fibra, odore, muffa nascosta, elettronica interna, batteria o durata. Uno schermo acceso mostra un solo momento. Il QC fornisce prove visive prima della decisione; non è un certificato. Questo limite è più onesto e utile."],
      ],
      "usfans-review-what-to-check": [
        ["Separa fatti ufficiali e conclusioni", "Le fonti ufficiali descrivono acquisto da Taobao, 1688 e Weidian, ricezione, foto, deposito e pacco internazionale. Le schede annunciano 3–7 foto QC e gestione acquisti 09:00–18:00 UTC+8 dopo il pagamento. La guida indica 90 giorni gratis e un avviso attuale cinque giorni per chiedere il reso. Sono fatti di processo; non garantiscono spedizione rapida del venditore, rilevazione di ogni difetto, reso accettato o dogana senza ritardi."],
        ["Leggi le valutazioni con l’avviso attuale", "Il 01/09/2026 Trustpilot non mostrava un punteggio normale per USFans a causa di una violazione delle linee guida e dichiarava di aver rimosso recensioni false. Mostrava 716 recensioni, 691 nei dodici mesi precedenti, con 76% cinque stelle e 14% una. L’App Store mostrava 3,3/5 su 97 valutazioni. I testi includevano esperienze positive su assistenza, QC, imballaggio e consegna e negative su costi, rimborsi, ritardi o resi. Sono testimonianze attribuite e datate, non risultati verificati."],
        ["Esegui un piccolo test che produca prove", "Inizia con un articolo sostituibile, misurabile e senza restrizioni. Salva fonte, variante, trasporto nazionale e avviso di reso. Misura tempi reali, esamina foto, chiedi una misura e confronta stima, fattura e tracking. Valuta separatamente venditore, acquisto agente, magazzino, imballaggio, vettore e dogana. Il test non garantisce il futuro, ma sostituisce fiducia presa in prestito con dati propri."],
        ["Formula un giudizio condizionato", "Chiedi se il flusso attuale è adatto a destinazione, categoria, dimensione, scadenza e tolleranza al rischio. Foto e consolidamento possono aiutare; chi si aspetta consegna a casa dal primo trasporto nazionale, resi automatici o certezza da una media può restare deluso. Confronta con lo stesso carrello e ricontrolla le condizioni. Le prove sostengono un processo prudente: verificare venditore, iniziare piccolo, usare QC, calcolare peso fatturabile e tenere margine; non un’etichetta universale."],
      ],
    },
    visuals: {
      "usfans-spreadsheet-guide-2026": ["Riga di verifica in cinque campi", [["Fonte","Percorso + venditore"],["Variante","Colore · taglia · versione"],["Misura","Dimensioni fisiche"],["Prova","Vista QC necessaria"],["Costo","Ipotesi nazionali e internazionali"]]],
      "usfans-shipping-cost-guide": ["Esempio di peso fatturabile", [["Pacco","40 × 30 × 20 cm"],["Peso reale","2,50 kg"],["Peso volume","40 × 30 × 20 ÷ 6000 = 4,00 kg"],["Peso pianificato","4,00 kg prima dell’arrotondamento"]]],
      "how-to-read-usfans-qc-photos": ["Matrice prove QC", [["Scarpe","Forma · simmetria · soletta"],["Abiti","Petto · lunghezza · cuciture"],["Borse","Bordi · ferramenta · interno"],["Elettronica","Solo stato visibile"]]],
      "usfans-review-what-to-check": ["Gerarchia delle prove", [["Pagina ufficiale","Processo e regole"],["Foto magazzino","Unità ricevuta visibile"],["Recensione cliente","Esperienza attribuita"],["Tuo test","Prova di quell’ordine"]]],
    },
  },
};

const articleExtensions = {
  en: {
    "usfans-spreadsheet-guide-2026": [
      ["Separate seller evidence from agent evidence", "Two businesses can influence one order. The marketplace seller controls the listing, stock, product supplied, seller dispatch and willingness to accept a return. The purchasing agent controls order handling, warehouse intake, the inspection service it offers, storage, packing and international parcel submission. Build two evidence columns so a useful spreadsheet does not blame or credit the wrong layer. Seller evidence can include source-page measurements, variant text, dispatch history shown by the marketplace and return conditions. Agent evidence can include order timestamps, warehouse photos, measured weight, support messages and parcel records. If the wrong color arrives, the records should show whether the order instruction was correct and what the warehouse received. If tracking slows after export, a seller rating has little explanatory value. This separation makes customer reports comparable and improves editorial accuracy. It also stops an independent directory from implying that every listed item is supplied, inspected or guaranteed by the directory itself."],
      ["Run a ten-minute gate immediately before payment", "Open the exact source route from the shortlist and confirm that it still points to the intended seller and variant. Read the selected color, size, quantity, version and seller note aloud against the worksheet. Compare the latest physical measurements with the reference item you used. Check domestic freight and whether the displayed shipping label refers only to the warehouse stage. Review the current return notice and note any seller-specific exclusion. Then update the item price, currency date and one realistic landed-cost range. Define the two warehouse views that will decide acceptance. Finally, ask whether you would still buy if international freight finishes at the high end of the range or if a return requires domestic postage. If the answer is no, pause rather than letting a promotional timer make the decision. This gate is simple, repeatable and suitable for every link in a maintained USFans spreadsheet."],
    ],
    "usfans-shipping-cost-guide": [
      ["Optimize in the right order", "Start with route eligibility, because no packaging trick can make a prohibited item acceptable. Next identify which items require rigid protection and which can safely compress. Remove avoidable retail volume only after deciding what damage risk that creates. Sketch the consolidated carton and calculate volumetric weight with realistic outer dimensions. Compare it with the sum of item weights plus packing material. If volume dominates, test one change at a time: remove an empty presentation box, fold soft clothing into unused spaces, select a more closely fitted outer carton, or split an awkward item. Recalculate after each change so you know what produced the saving. Then compare eligible routes with the same final parcel data, DDP assumption and optional services. Choosing the lowest headline route first and changing the parcel later reverses the logic; the quoted option may no longer apply. A disciplined sequence produces a price you can explain and a package whose protection has not been sacrificed accidentally."],
      ["Create a route-comparison record", "For each eligible route, record the name, date, destination, DDP or non-DDP status, estimated transit range, actual-versus-volumetric rule, divisor, rounding increment, minimum or maximum weight, category restrictions, insurance conditions, tracking level and quoted amount. Leave a field for what is unknown. Use current route detail rather than copying an old community spreadsheet, because availability and carrier pricing can move. Compare cost per chargeable kilogram only as a secondary measure: a route with better customs treatment, protection eligibility or tracking may be more suitable even when the simple ratio is higher. Also note the consequence of delay. A replaceable hoodie and a time-sensitive gift do not have the same decision threshold. Once selected, save a screenshot or dated text record beside the final package measurements. This creates a clean baseline for support questions and later article updates without promising that a transit estimate is a delivery guarantee."],
    ],
    "how-to-read-usfans-qc-photos": [
      ["Follow one inspection order every time", "Begin with identity: product, quantity, color, size tag and selected version. Move to structure: overall silhouette, left-right symmetry, straightness, proportions and obvious distortion. Then examine construction: seams, bonding, edge finish, closures, hardware and attachment points. Check cosmetic details only after those higher-impact layers pass. Next verify category measurements and compare them with the reference values saved before payment. Finish with packaging or transit concerns such as crushed shape, exposed fragile areas or moisture. Mark each layer pass, question or fail. This order reduces confirmation bias because a convincing logo or attractive close-up cannot compensate for a wrong size or damaged structure. It also lets another person reproduce your conclusion. If the supplied three to seven photos do not cover a layer, the checklist identifies exactly which missing view matters instead of producing a generic request for more pictures."],
      ["Turn accept or return into explicit thresholds", "Before the photos arrive, write the conditions that require a query or return attempt. Examples include a chest width outside an allowed range, wrong color code, missing part, visible crack, badly unequal heels, non-functioning closure or a stain above a defined size. Also list imperfections you are prepared to accept, such as a loose thread that can be trimmed or minor box damage when the item is unaffected. Apply those thresholds to comparable evidence and avoid changing them merely because the item has already been paid for. If a result is uncertain, request the smallest additional proof that can change the decision. If it cannot be resolved visually, recognize the residual risk rather than requesting endless photographs. Document the final reason and time. Explicit thresholds make the five-day application notice more manageable and produce review content based on a repeatable method instead of hindsight."],
    ],
    "usfans-review-what-to-check": [
      ["Audit the two shipping charges", "Several App Store complaints reviewed for this article described confusion between an initial charge associated with getting an item to the warehouse and the later international parcel cost. The existence and wording of any individual charge must be checked on the current order page, but the underlying two-stage workflow is visible in the official guide. A fair review should therefore test disclosure at both moments. Before product payment, can the buyer tell which destination the shipping amount covers? Before parcel submission, can the buyer enter destination and realistic weight or dimensions, see route type, and understand that the final packed data can change the quote? Record the labels and totals rather than paraphrasing from memory. If a reviewer calls the second stage a hidden fee, examine what the interface displayed; if a promoter calls shipping cheap, demand the same basket and destination. This audit turns a common disagreement into a factual comparison."],
      ["Score evidence quality before using a claim", "Give the strongest weight to current first-party terms for what the service officially offers, while recognizing that official pages do not establish customer satisfaction. Give high weight to order-specific records such as timestamps, invoices, parcel measurements, complete support threads and comparable photographs. Treat detailed independent reviews as attributed experience, with more value when they state recent date, destination, route and stage. Give little weight to star-only ratings, referral posts, cropped screenshots or claims that confuse seller product quality with carrier delay. A platform warning about manipulated reviews should reduce confidence in the aggregate score, not automatically invalidate every detailed account. Look for convergence across independent, well-documented cases and for a plausible mechanism. Publish the check date because counts and notices can change. Revisit numerical snapshots before every material update, and remove conclusions that no longer match the visible evidence. Where accounts conflict, show the disagreement and the missing context instead of choosing the more dramatic story. This hierarchy allows an article to discuss real customer experience while remaining clear about what has and has not been independently proven."],
    ],
  },
  de: {
    "usfans-spreadsheet-guide-2026": [["Verkäufer- und Agentenbelege trennen","Der Verkäufer steuert Angebot, Bestand, Produkt, Versand zum Lager und Rückgabeakzeptanz. Der Agent steuert Bestellbearbeitung, Lagereingang, angebotene Fotos, Lagerung, Verpackung und internationalen Versand. Führe getrennte Spalten für Quellmaße, Varianten und Verkäuferregeln sowie für Zeitstempel, Lagerfotos, Gewicht, Support und Paketdaten. So lässt sich ein Fehler der richtigen Phase zuordnen und die Tabelle suggeriert keine eigene Produktgarantie."],["Zehn-Minuten-Prüfung vor Zahlung","Öffne die exakte Quelle erneut und gleiche Verkäufer, Variante, Farbe, Größe, Menge und Hinweise mit der Zeile ab. Prüfe Maße, Inlandsfracht, Rückgabehinweis, aktuelles Preisdatum und eine realistische Gesamtkostenspanne. Definiere zwei entscheidende Lageransichten. Frage zuletzt, ob du auch beim oberen Versandwert oder möglicher Rückfracht kaufen würdest. Falls nicht, pausiere statt unter Zeitdruck zu bestellen."]],
    "usfans-shipping-cost-guide": [["In der richtigen Reihenfolge optimieren","Beginne mit Routen­eignung, dann Schutzbedarf und Komprimierbarkeit. Entferne Volumen erst nach der Risikoprüfung. Rechne eine realistische Außenbox und ändere bei dominierendem Volumengewicht jeweils nur einen Faktor: leere Box, Faltung, engerer Karton oder Aufteilung. Vergleiche danach Routen mit denselben Enddaten, DDP-Annahmen und Diensten. So bleibt die Ersparnis erklärbar und der Schutz bewusst."],["Einen Routenvergleich dokumentieren","Notiere je Route Datum, Ziel, DDP-Status, Laufzeitspanne, Gewichtsregel, Teiler, Rundung, Grenzen, Einschränkungen, Versicherung, Tracking und Preis sowie offene Punkte. Nutze aktuelle Details statt alter Community-Tabellen. Preis pro Kilogramm ist nur sekundär; Zollbehandlung, Schutz und Tracking können wichtiger sein. Speichere die gewählte Route neben den Endmaßen, ohne eine Laufzeit zu garantieren."]],
    "how-to-read-usfans-qc-photos": [["Immer dieselbe Prüfreihenfolge","Prüfe Identität, dann Struktur, Konstruktion, kosmetische Details, Maße und schließlich Verpackungsrisiken. Markiere jede Ebene als bestanden, fraglich oder nicht bestanden. Diese Reihenfolge verhindert, dass ein gutes Detail falsche Größe oder Schaden überdeckt. Fehlt eine Ebene in den drei bis sieben Fotos, ergibt sich daraus eine präzise Zusatzanfrage."],["Grenzwerte vorab festlegen","Definiere vor Ankunft, welche Abweichung eine Frage oder Retouren­anfrage auslöst: Maß außerhalb der Toleranz, falsche Farbe, fehlendes Teil, Riss, ungleiche Absätze oder defekter Verschluss. Notiere auch akzeptable Kleinigkeiten. Fordere nur Belege an, die die Entscheidung ändern können, erkenne nicht visuell lösbare Risiken an und dokumentiere Grund und Zeit."]],
    "usfans-review-what-to-check": [["Die zwei Versandbeträge prüfen","Mehrere App-Store-Berichte erwähnten Verwirrung zwischen Versand zum Lager und späterem internationalem Paket. Prüfe die konkrete Beschriftung im aktuellen Auftrag. Vor Artikelzahlung sollte erkennbar sein, welches Ziel der Betrag abdeckt; vor Paketeinreichung sollten Ziel, Gewicht, Maße, Route und mögliche Anpassung verständlich sein. Nur identische Warenkörbe und Ziele erlauben faire Aussagen über versteckte oder günstige Kosten."],["Belegqualität vor einer Aussage bewerten","Aktuelle offizielle Bedingungen belegen das Angebot, nicht die Zufriedenheit. Auftragsspezifische Zeitstempel, Rechnungen, Maße, vollständige Chats und vergleichbare Fotos wiegen stark. Detaillierte unabhängige Berichte bleiben zugeschriebene Erfahrungen; Sterne, Referral-Posts und beschnittene Bilder wiegen wenig. Eine Manipulationswarnung senkt Vertrauen in den Gesamtscore, widerlegt aber nicht automatisch jeden Einzelfall. Datiere den Check."]],
  },
  es: {
    "usfans-spreadsheet-guide-2026": [["Separa pruebas del vendedor y del agente","El vendedor controla ficha, stock, producto, despacho nacional y aceptación de retorno. El agente controla gestión, recepción, fotos ofrecidas, depósito, embalaje y paquete internacional. Usa columnas distintas para medidas, variante y reglas del vendedor, y para tiempos, QC, peso, soporte y paquete. Así asignas cada incidencia a la fase correcta y la hoja no promete garantizar el producto."],["Control de diez minutos antes de pagar","Reabre la fuente exacta y confirma vendedor, variante, color, talla, cantidad y notas. Revisa medidas, envío nacional, aviso de retorno, precio actualizado y un rango realista de coste total. Define dos vistas decisivas de almacén. Pregunta si comprarías con el envío en la parte alta o pagando el retorno. Si no, pausa."]],
    "usfans-shipping-cost-guide": [["Optimiza en el orden correcto","Empieza por elegibilidad de ruta, después protección y compresibilidad. Quita volumen solo tras valorar daño. Calcula una caja realista y, si domina el volumen, cambia un factor cada vez: caja vacía, plegado, cartón ajustado o división. Después compara rutas con los mismos datos finales, DDP y servicios. El ahorro queda explicable y la protección sigue siendo deliberada."],["Registra la comparación de rutas","Anota nombre, fecha, destino, DDP, tránsito, regla de peso, divisor, redondeo, límites, restricciones, seguro, seguimiento y precio, además de dudas. Usa información actual. El precio por kilo es secundario frente a aduanas, protección o tracking. Guarda la ruta elegida con las medidas finales sin convertir el plazo estimado en garantía."]],
    "how-to-read-usfans-qc-photos": [["Sigue siempre el mismo orden","Comprueba identidad, estructura, construcción, cosmética, medidas y finalmente riesgo de embalaje. Marca cada capa como pasa, duda o falla. Así un detalle atractivo no oculta talla errónea o daño. Si las tres a siete fotos no cubren una capa, la lista genera una petición precisa."],["Define umbrales antes de recibir","Escribe qué diferencia exige consulta o devolución: medida fuera de rango, color erróneo, pieza ausente, grieta, talones desiguales o cierre defectuoso. Anota también defectos menores aceptables. Pide solo pruebas que cambien la decisión, reconoce lo que una foto no resuelve y registra razón y hora."]],
    "usfans-review-what-to-check": [["Audita los dos cargos de transporte","Varias reseñas de App Store mencionaron confusión entre traslado al almacén y paquete internacional. Comprueba la etiqueta del pedido actual. Antes de pagar debe entenderse el destino del primer cargo; antes de enviar, destino, peso, dimensiones, ruta y posible ajuste. Para afirmar “oculto” o “barato”, compara la misma cesta y destino y conserva etiquetas y totales."],["Puntúa la calidad de la prueba","Las condiciones oficiales prueban qué ofrece el servicio, no satisfacción. Tiempos, facturas, medidas, chats completos y fotos comparables pesan más. Reseñas detalladas siguen siendo experiencias atribuidas; estrellas solas, referidos y capturas recortadas pesan poco. Un aviso de manipulación reduce confianza en el agregado sin anular cada caso. Busca coincidencia entre casos documentados y fecha el control."]],
  },
  fr: {
    "usfans-spreadsheet-guide-2026": [["Séparer preuves vendeur et agent","Le vendeur contrôle fiche, stock, produit, expédition nationale et acceptation du retour. L’agent contrôle traitement, réception, photos proposées, stockage, emballage et colis international. Créez des colonnes distinctes pour mesures, variante et règles vendeur, puis délais, QC, poids, support et colis. Ainsi chaque problème est attribué à la bonne phase et le tableur ne suggère pas une garantie du produit."],["Contrôle de dix minutes avant paiement","Rouvrez la source exacte et confirmez vendeur, variante, couleur, taille, quantité et notes. Vérifiez mesures, fret national, avis de retour, prix daté et fourchette de coût rendu. Définissez deux vues décisives d’entrepôt. Demandez si vous achèteriez encore avec le fret haut ou un retour payant. Sinon, mettez en pause."]],
    "usfans-shipping-cost-guide": [["Optimiser dans le bon ordre","Commencez par l’admissibilité, puis protection et compressibilité. Retirez du volume après analyse du risque. Calculez un carton réaliste et, si le volume domine, changez un facteur à la fois : boîte vide, pliage, carton ajusté ou séparation. Comparez ensuite les lignes avec mêmes données finales, DDP et services. L’économie devient explicable et la protection reste volontaire."],["Conserver une comparaison des lignes","Notez nom, date, destination, DDP, transit, règle de poids, diviseur, arrondi, limites, restrictions, assurance, suivi et prix, plus les inconnues. Utilisez les détails actuels. Le prix au kilo est secondaire face à douane, protection et tracking. Sauvegardez la ligne choisie avec les dimensions finales sans promettre le délai."]],
    "how-to-read-usfans-qc-photos": [["Suivre toujours le même ordre","Vérifiez identité, structure, construction, cosmétique, mesures puis risque d’emballage. Marquez chaque couche conforme, question ou échec. Un détail séduisant ne masque plus mauvaise taille ou dommage. Si les trois à sept photos omettent une couche, la liste produit une demande précise."],["Fixer des seuils avant réception","Écrivez les écarts qui déclenchent question ou retour : mesure hors plage, mauvaise couleur, pièce absente, fissure, talons inégaux ou fermeture défectueuse. Notez aussi les petits défauts acceptables. Demandez seulement la preuve pouvant changer la décision, reconnaissez les limites visuelles et datez la raison."]],
    "usfans-review-what-to-check": [["Auditer les deux frais de transport","Plusieurs avis App Store évoquaient une confusion entre envoi à l’entrepôt et colis international. Vérifiez le libellé actuel. Avant paiement, la destination du premier montant doit être comprise ; avant soumission, destination, poids, dimensions, ligne et ajustement possible. Pour qualifier un coût de caché ou bon marché, comparez même panier et même destination et gardez les libellés."],["Noter la qualité des preuves","Les conditions officielles établissent l’offre, pas la satisfaction. Horodatages, factures, mesures, conversations complètes et photos comparables pèsent plus. Les avis détaillés restent des expériences attribuées ; étoiles seules, parrainage et captures coupées pèsent peu. Un avertissement de manipulation réduit la confiance dans l’agrégat sans annuler chaque cas. Cherchez convergence et datez le contrôle."]],
  },
  it: {
    "usfans-spreadsheet-guide-2026": [["Separa prove del venditore e dell’agente","Il venditore controlla scheda, scorte, prodotto, invio nazionale e accettazione del reso. L’agente controlla gestione, ricezione, foto offerte, deposito, imballaggio e pacco internazionale. Usa colonne distinte per misure, variante e regole del venditore, e per tempi, QC, peso, assistenza e pacco. Così ogni problema appartiene alla fase corretta e il foglio non suggerisce una garanzia propria."],["Controllo di dieci minuti prima di pagare","Riapri la fonte esatta e conferma venditore, variante, colore, taglia, quantità e note. Verifica misure, trasporto nazionale, avviso di reso, prezzo datato e intervallo realistico di costo finale. Definisci due viste decisive del magazzino. Chiedi se compreresti anche con spedizione alta o reso a carico. Se no, fermati."]],
    "usfans-shipping-cost-guide": [["Ottimizza nell’ordine corretto","Inizia dall’eleggibilità, poi protezione e comprimibilità. Togli volume dopo aver valutato il rischio. Calcola una scatola realistica e, se domina il volume, cambia un fattore alla volta: scatola vuota, piega, cartone aderente o divisione. Poi confronta linee con stessi dati finali, DDP e servizi. Il risparmio resta spiegabile e la protezione consapevole."],["Registra il confronto delle linee","Annota nome, data, destinazione, DDP, transito, regola peso, divisore, arrotondamento, limiti, restrizioni, assicurazione, tracking e prezzo, oltre ai dubbi. Usa dettagli attuali. Il costo per kg è secondario rispetto a dogana, protezione o tracking. Salva la linea con le misure finali senza trasformare il tempo stimato in garanzia."]],
    "how-to-read-usfans-qc-photos": [["Segui sempre lo stesso ordine","Controlla identità, struttura, costruzione, cosmetica, misure e infine rischio di imballaggio. Marca ogni livello come passa, dubbio o fallisce. Un bel dettaglio non nasconde taglia errata o danno. Se le tre-sette foto non coprono un livello, la lista produce una richiesta precisa."],["Definisci soglie prima dell’arrivo","Scrivi quali differenze richiedono domanda o reso: misura fuori intervallo, colore errato, pezzo mancante, crepa, talloni diversi o chiusura guasta. Annota anche difetti minori accettabili. Chiedi solo prove che cambiano la decisione, riconosci i limiti visivi e registra motivo e orario."]],
    "usfans-review-what-to-check": [["Controlla i due costi di trasporto","Varie recensioni App Store citavano confusione tra invio al magazzino e pacco internazionale. Controlla l’etichetta attuale. Prima del pagamento deve essere chiara la destinazione del primo costo; prima dell’invio, destinazione, peso, dimensioni, linea e possibile adeguamento. Per dire nascosto o economico, usa stesso carrello e destinazione e conserva le voci."],["Valuta la qualità delle prove","Le condizioni ufficiali provano l’offerta, non la soddisfazione. Tempi, fatture, misure, chat complete e foto comparabili pesano di più. Recensioni dettagliate restano esperienze attribuite; sole stelle, referral e ritagli pesano poco. Un avviso di manipolazione riduce fiducia nell’aggregato senza annullare ogni caso. Cerca convergenza e data il controllo."]],
  },
};

export function getArticleResearch(language, slug) {
  const active = articleResearch[language] || articleResearch.en;
  const extension = articleExtensions[language] || articleExtensions.en;
  return {
    sourceNote: active.sourceNote,
    sections: [...(active.dives[slug] || []), ...(extension[slug] || [])],
    visual: active.visuals[slug] || null,
  };
}
