export const uveAngleArticleBlueprint = {
  slug: "usfans-warehouse-photo-angle-map",
  title: {
    en: "USFans Warehouse Photo Angle Map: Check Coverage Before Condition",
    de: "USFans-Fotowinkel im Lager: Erst Abdeckung, dann Zustand prüfen",
    es: "Mapa de ángulos de fotos USFans: revisa la cobertura antes del estado",
    fr: "Carte des angles photo USFans : vérifier la couverture avant l’état",
    it: "Mappa degli angoli foto USFans: prima la copertura, poi le condizioni",
  },
  dek: {
    en: "Map each supplied warehouse view to a specific question, find repeated or missing angles and avoid turning an incomplete gallery into a confident condition verdict.",
    de: "Ordne jede Lageraufnahme einer konkreten Frage zu, erkenne wiederholte oder fehlende Winkel und vermeide ein sicheres Zustandsurteil aus einer unvollständigen Galerie.",
    es: "Relaciona cada vista de almacén con una pregunta concreta, detecta ángulos repetidos o ausentes y evita convertir una galería incompleta en un veredicto seguro.",
    fr: "Reliez chaque vue d’entrepôt à une question précise, repérez les angles répétés ou absents et évitez de transformer une galerie incomplète en verdict certain.",
    it: "Collega ogni vista di magazzino a una domanda precisa, individua angoli ripetuti o mancanti ed evita di trasformare una galleria incompleta in un verdetto sicuro.",
  },
  topics: [],
};

const localized = {
  en: {
    meta: ["Photo-angle method", "Checked 09 Sep 2026", "Independent"],
    sourceNote: "Research basis: the current USFans Beginner’s Guide, Help Center and public product-page inspection statements checked 09 Sep 2026. Official public pages say items are checked and photographed after warehouse arrival; current product pages advertise 3–7 HD inspection photos. A count is not a promise that every decision-relevant angle will be covered.",
    visual: ["Angle-to-question map", [["Overview", "front · back · left · right"], ["Identity", "tag · option marker · quantity"], ["Detail", "closure · print · edge · hardware"], ["Result", "covered · partial · repeated · missing"]]],
    related: [["Start with the warehouse evidence-gap map", "/articles/usfans-warehouse-evidence-gap-map"], ["Open the general warehouse-photo guide", "/qc"]],
    sections: [
      ["Count answered questions, not uploaded images", "USFans currently describes a warehouse stage in which an arrived item is checked and photographed, and public product pages advertise 3–7 HD inspection photos. That range is useful context, but it is not a coverage specification. Three different files can repeat one useful front view, while seven files can still omit the back, a size label or the underside. Begin by listing the questions that could change your decision, then attach one supplied image to each question it actually answers. Use four status labels: covered, partial, repeated and missing. Covered means the decision area is clearly visible at a workable scale. Partial means the area appears but is cropped, blocked, distant or angled. Repeated means another image shows substantially the same evidence. Missing means no supplied view answers the question. This changes the review from “I received enough photos” to “I can see the surfaces and markers that matter.” Keep the official image count separate from your own coverage result. Never infer that a standard gallery is complete merely because it falls within an advertised range."],
      ["Build an orientation key before zooming", "Open every image once at normal scale and identify the item’s orientation. Label the front, back, left side, right side, top and underside only when a stable feature proves which face you are seeing. A shoe’s toe, heel and opening usually provide that key; a garment may need the neckline, closure or care-label position; a bag may need the flap, handle anchors or pocket layout. Do not assume two side photographs show opposite sides. They may show the same side from slightly different distances. Record uncertain orientation as unknown rather than forcing a label. Then arrange the views in a consistent sequence and note whether the whole item remains inside the frame. This first pass reveals duplicates and blind zones before attractive close-ups distract you. It also prevents a mirrored image, rotated item or folded garment from creating false asymmetry. Orientation is not condition evidence by itself. It is the coordinate system that lets later observations refer to a precise surface, edge or component."],
      ["Match wide views to shape and placement questions", "Wide photographs are best for questions about silhouette, proportion, overall alignment and the position of a feature within the complete item. Use a straight front view to compare the left and right sides, a straight back view to inspect rear construction, and paired side views to check whether corresponding panels, soles, seams or straps appear in comparable positions. For clothing, a full flat view can reveal twisting, uneven hems or print placement, but folds can hide seams and change apparent length. For footwear, a pair shown together can support a symmetry check, although perspective may make the shoe closer to the camera appear larger. For bags, an upright overview can show shape and handle placement without proving the interior or base. Mark a wide view partial when a corner leaves the frame, packaging blocks an edge, the item is folded or the camera is strongly oblique. A wide photograph should not be stretched into a fine-detail conclusion: visible overall placement does not establish stitch quality, label text or a tiny surface mark."],
      ["Use close views only for located details", "A close photograph is useful when you can connect it to a location established by a wider view. Record both the detail and its position: upper-left print edge, outer right shoe panel, lower rear seam or front clasp. Without that connection, an isolated mark may belong to packaging, another surface or an area whose importance cannot be judged. For a suspected defect, the strongest pair is usually one wider image that locates it and one close image that shows texture and boundaries. A close-up can support observations about visible stitching, print edges, surface scuffs, chips, hardware finish or readable label text. It cannot prove hidden construction, material composition, authenticity, waterproofing, durability or electronic function. Digital zoom also has limits. Enlarging a compressed file may magnify blocks and sharpening halos rather than reveal new evidence. If the detail disappears at normal size or changes character between files, mark confidence lower and describe only what remains consistently visible."],
      ["Audit labels, quantity and included parts separately", "Identity and completeness often need their own angle plan. For a label, ask whether the entire label is shown straight on, whether every relevant line is readable and whether the image can be tied to this exact unit. A visible size value supports what the tag states, not the item’s physical measurements or real-world fit. For a set, count pieces only in a frame that makes distinct units visible, or reconcile several views carefully so the same piece is not counted twice. Create an expected-parts row from the saved order option, then mark each part visible, partly visible or not shown. Packaging photos may reveal an external model code while leaving internal accessories unconfirmed. Likewise, a closed pocket or sealed pouch does not prove its contents. Separate these questions from surface condition so a clean-looking main item does not hide an unresolved quantity, accessory or variant issue. If the order reference itself is ambiguous, record that upstream uncertainty rather than using warehouse photos to guess which option should have been supplied."],
      ["Control perspective, light and obstruction", "An angle can change apparent shape without the object changing. Compare like with like: similar camera distance, similar rotation and the same side of the item. Converging edges often indicate perspective; the nearer side may look wider, a circular opening may look oval and a straight print may appear slanted. Lighting can shift colour, deepen shadows and make glossy surfaces look marked. Packaging film can add reflections, folds and false lines. Hands, rulers, tissue, stuffing or another item can block the exact boundary you need. Record these as image conditions, not product defects. When two views conflict, ask which one is closer to straight-on, better lit and less obstructed. If neither is reliable, keep the question unresolved. Do not “average” two uncertain views into a confident conclusion. A useful note names the limitation—strong side perspective, warm light, reflective bag, folded fabric or hidden edge—and explains which alternative orientation would resolve it. This preserves the difference between a suspicious appearance and a supported observation."],
      ["Request the smallest angle that changes the decision", "Once the map is complete, do not request a generic extra gallery. Choose the highest-impact missing or partial row and specify one reproducible view. Name the item, surface, camera direction and framing. Examples include: full rear view square to the item with all edges visible; both shoe heels together at the same distance; underside from directly above; complete size tag photographed flat; bag interior opened with the base and pockets visible; or a wider view locating a suspected mark followed by a close view. If scale matters, state the measurement endpoints and ask that both ends of the ruler remain visible. Request all set pieces in one frame when practical. Avoid asking a photograph to answer a nonvisual question such as internal material, battery health, authenticity or future durability. Also avoid importing an old service promise, price or response time into the request. Use the current interface and terms. The goal is not more images; it is one missing observation that could move the status from hold or clarify to an evidence-supported decision."],
      ["Archive an angle map with an honest boundary", "Save a compact record containing the order reference, selected option text, review date, supplied image identifiers, orientation sequence, question-to-image rows and any follow-up view. Keep private addresses and payment information out of a shareable copy. End with two statements: what the gallery supports and what remains outside it. For example, it may support that the photographed unit shows a readable size tag, both exterior sides and no visible mark at the specified edge, while leaving actual garment measurements, interior construction and real-world fit unproven. That boundary is more valuable than a broad pass label. Reopen the map if a new image arrives, but do not silently replace the original assessment; add the new file and update the affected row. A later unit or batch needs a separate map because one item’s angles do not prove another item’s condition. This disciplined archive turns a variable photo set into a traceable visual review without claiming that a gallery, however large, removes every product, seller or shipment risk."],
    ],
  },
  de: {
    meta: ["Fotowinkel-Methode", "Geprüft am 09.09.2026", "Unabhängig"],
    sourceNote: "Recherchegrundlage: aktueller USFans-Einsteigerleitfaden, Hilfebereich und öffentliche Inspektionshinweise auf Produktseiten, geprüft am 09.09.2026. Offizielle öffentliche Seiten sagen, dass Artikel nach Lagerankunft geprüft und fotografiert werden; aktuelle Produktseiten nennen 3–7 HD-Prüffotos. Die Zahl verspricht keine Abdeckung jedes entscheidungsrelevanten Winkels.",
    visual: ["Winkel-zu-Frage-Karte", [["Übersicht", "vorn · hinten · links · rechts"], ["Identität", "Etikett · Optionsmerkmal · Menge"], ["Detail", "Verschluss · Druck · Kante · Beschlag"], ["Ergebnis", "abgedeckt · teilweise · wiederholt · fehlend"]]],
    related: [["Mit der Karte der Lagerbeleglücken beginnen", "/articles/usfans-warehouse-evidence-gap-map"], ["Allgemeinen Leitfaden für Lagerfotos öffnen", "/qc"]],
    sections: [
      ["Beantwortete Fragen statt hochgeladener Bilder zählen", "USFans beschreibt derzeit eine Lagerphase, in der ein eingetroffener Artikel geprüft und fotografiert wird; öffentliche Produktseiten nennen 3–7 HD-Prüffotos. Diese Spanne ist ein nützlicher Kontext, aber keine Abdeckungsspezifikation. Drei Dateien können dieselbe Vorderansicht wiederholen, während selbst sieben Bilder Rückseite, Größenetikett oder Unterseite auslassen können. Liste zuerst alle Fragen, die deine Entscheidung ändern könnten, und ordne jeder Frage nur ein Bild zu, das sie tatsächlich beantwortet. Verwende vier Status: abgedeckt, teilweise, wiederholt und fehlend. Abgedeckt bedeutet klar sichtbar in brauchbarem Maßstab. Teilweise bedeutet angeschnitten, verdeckt, zu weit entfernt oder schräg. Wiederholt bedeutet im Wesentlichen derselbe Beleg wie auf einem anderen Bild. Fehlend bedeutet, dass keine gelieferte Ansicht die Frage beantwortet. Trenne die offiziell genannte Bildzahl von deinem Abdeckungsergebnis. Eine Galerie ist nicht automatisch vollständig, nur weil sie innerhalb einer beworbenen Spanne liegt."],
      ["Vor dem Zoomen einen Orientierungsschlüssel erstellen", "Öffne jedes Bild einmal in normaler Größe und bestimme die Ausrichtung. Beschrifte Vorderseite, Rückseite, linke und rechte Seite, Ober- und Unterseite nur, wenn ein stabiles Merkmal die Fläche belegt. Bei Schuhen helfen Zehenpartie, Ferse und Öffnung; bei Kleidung Ausschnitt, Verschluss oder Position des Pflegeetiketts; bei Taschen Klappe, Griffansätze oder Taschenanordnung. Nimm nicht an, dass zwei Seitenfotos Gegenseiten zeigen: Sie können dieselbe Seite aus leicht anderer Entfernung abbilden. Markiere unsichere Ausrichtung als unbekannt. Ordne danach die Ansichten in einer festen Reihenfolge und notiere, ob der ganze Artikel im Bild bleibt. Dieser erste Durchgang zeigt Duplikate und Blindzonen, bevor Nahaufnahmen ablenken. Er verhindert auch falsche Asymmetrie durch Spiegelung, Drehung oder Faltung. Orientierung ist noch kein Zustandsbeleg, sondern das Koordinatensystem für präzise spätere Beobachtungen."],
      ["Weite Ansichten mit Form- und Platzierungsfragen verbinden", "Weite Fotos eignen sich für Silhouette, Proportion, Gesamtausrichtung und die Lage eines Merkmals am vollständigen Artikel. Nutze eine gerade Vorderansicht für den Seitenvergleich, eine gerade Rückansicht für hintere Konstruktion und passende Seitenansichten für Panels, Sohlen, Nähte oder Riemen. Bei Kleidung kann eine flache Gesamtansicht Verdrehung, ungleiche Säume oder Druckplatzierung zeigen, doch Falten verdecken Nähte und verändern scheinbare Längen. Bei Schuhen unterstützt ein gemeinsames Paarfoto die Symmetrieprüfung, obwohl der nähere Schuh größer wirken kann. Bei Taschen zeigt eine aufrechte Übersicht Form und Griffposition, nicht Innenraum oder Boden. Markiere sie als teilweise, wenn Kanten fehlen, Verpackung stört, der Artikel gefaltet oder die Kamera stark schräg ist. Dehne eine Übersicht nie zu einem Detailurteil aus: Gesamtplatzierung beweist weder Stichqualität noch Etikettentext oder kleine Oberflächenspuren."],
      ["Nahansichten nur für verortete Details verwenden", "Eine Nahaufnahme ist nützlich, wenn sie mit einer durch die Übersicht belegten Stelle verbunden wird. Notiere Detail und Position, etwa obere linke Druckkante, äußeres rechtes Schuhpanel, untere Rücknaht oder Frontverschluss. Ohne diese Verbindung kann eine isolierte Spur zur Verpackung oder zu einer anderen Fläche gehören. Bei einem vermuteten Fehler ist die stärkste Kombination meist eine weite Aufnahme zur Lage und eine nahe Aufnahme für Oberfläche und Begrenzung. Nahbilder können sichtbare Nähte, Druckkanten, Kratzer, Abplatzungen, Beschlagfinish oder lesbaren Labeltext stützen. Sie beweisen keine verborgene Konstruktion, Materialzusammensetzung, Echtheit, Wasserdichtigkeit, Haltbarkeit oder Elektronikfunktion. Digitaler Zoom kann Kompressionsblöcke und Schärfungssäume statt neuer Belege vergrößern. Verschwindet ein Detail in Normalgröße oder verändert sich zwischen Dateien, senke die Sicherheit und beschreibe nur konsistent Sichtbares."],
      ["Etiketten, Menge und enthaltene Teile getrennt prüfen", "Identität und Vollständigkeit brauchen oft einen eigenen Winkelplan. Prüfe beim Etikett, ob es vollständig und gerade gezeigt wird, alle relevanten Zeilen lesbar sind und das Bild diesem exakten Stück zugeordnet werden kann. Eine sichtbare Größe belegt die Angabe des Etiketts, nicht reale Maße oder Passform. Zähle Sets nur in einem Bild mit klar getrennten Einheiten oder gleiche mehrere Ansichten sorgfältig ab, damit ein Teil nicht doppelt zählt. Erstelle aus der gespeicherten Bestelloption eine Sollteile-Zeile und markiere jedes Teil sichtbar, teilweise sichtbar oder nicht gezeigt. Verpackungsfotos können einen äußeren Modellcode zeigen, ohne Zubehör im Inneren zu bestätigen. Eine geschlossene Tasche beweist ihren Inhalt ebenfalls nicht. Trenne diese Fragen vom Oberflächenzustand, damit ein sauber wirkender Hauptartikel keine offene Mengen-, Zubehör- oder Variantenfrage verdeckt. Ist schon die Bestellreferenz mehrdeutig, dokumentiere diese vorgelagerte Unsicherheit, statt die gewählte Option aus Lagerfotos zu erraten."],
      ["Perspektive, Licht und Verdeckung kontrollieren", "Ein Winkel kann scheinbare Form verändern. Vergleiche ähnliche Kameradistanz, Drehung und dieselbe Artikelseite. Zusammenlaufende Kanten deuten oft auf Perspektive: Die nähere Seite wirkt breiter, eine runde Öffnung oval und ein gerader Druck schief. Licht verändert Farbe und Schatten; glänzende Flächen können markiert wirken. Verpackungsfolie erzeugt Reflexe, Falten und falsche Linien. Hände, Lineale, Papier oder Füllmaterial können genau die benötigte Grenze verdecken. Notiere solche Bedingungen als Bildmerkmale, nicht als Produktfehler. Bei widersprüchlichen Ansichten frage, welche gerader, besser beleuchtet und weniger verdeckt ist. Ist keine zuverlässig, bleibt die Frage offen. Bilde aus zwei unsicheren Ansichten keinen sicheren Mittelwert. Eine brauchbare Notiz benennt starke Seitenperspektive, warmes Licht, reflektierende Folie, gefalteten Stoff oder verdeckte Kante und sagt, welcher alternative Winkel die Unsicherheit lösen würde."],
      ["Den kleinsten entscheidungswirksamen Winkel anfordern", "Fordere nach Abschluss der Karte keine allgemeine Zusatzgalerie an. Wähle die wichtigste fehlende oder teilweise Zeile und formuliere eine reproduzierbare Ansicht mit Artikel, Fläche, Kamerarichtung und Bildausschnitt. Beispiele: vollständige Rückseite frontal mit allen Kanten; beide Schuhfersen gemeinsam aus gleicher Entfernung; Unterseite direkt von oben; vollständiges flach fotografiertes Größenetikett; geöffneter Tascheninnenraum mit Boden und Fächern; oder eine Übersicht zur Lage einer Spur plus Nahaufnahme. Wenn Maßstab wichtig ist, nenne die Messendpunkte und verlange beide sichtbaren Linealenden. Bitte Sets möglichst gemeinsam ins Bild. Verlange keine Fotobeweise für inneres Material, Akkuzustand, Echtheit oder künftige Haltbarkeit. Übernimm auch keine alte Leistungs-, Preis- oder Zeitangabe; nutze aktuelle Oberfläche und Bedingungen. Ziel sind nicht mehr Bilder, sondern eine fehlende Beobachtung, die einen Halte- oder Klärstatus in eine belegte Entscheidung verwandeln kann."],
      ["Eine Winkelkarte mit ehrlicher Grenze archivieren", "Speichere Bestellreferenz, gewählten Optionstext, Prüftag, Bildkennungen, Orientierungsfolge, Frage-Bild-Zeilen und jede Folgeansicht. Lass private Adressen und Zahlungsdaten aus einer teilbaren Kopie. Beende den Datensatz mit zwei Aussagen: was die Galerie stützt und was außerhalb bleibt. Sie kann etwa ein lesbares Größenetikett, beide Außenseiten und keine sichtbare Spur an einer benannten Kante stützen, während reale Maße, Innenkonstruktion und Passform ungeprüft bleiben. Diese Grenze ist wertvoller als ein pauschales Bestanden. Trifft ein neues Bild ein, ergänze die betroffene Zeile, statt die ursprüngliche Bewertung still zu ersetzen. Eine weitere Einheit oder Charge braucht eine eigene Karte; die Winkel eines Artikels beweisen nicht den Zustand eines anderen. So wird eine variable Fotoserie nachvollziehbar geprüft, ohne zu behaupten, eine noch so große Galerie beseitige jedes Produkt-, Verkäufer- oder Versandrisiko."],
    ],
  },
  es: {
    meta: ["Método de ángulos", "Revisado el 09/09/2026", "Independiente"],
    sourceNote: "Base de investigación: guía para principiantes, centro de ayuda y declaraciones públicas de inspección en páginas de producto de USFans, revisados el 09/09/2026. Las páginas oficiales indican que los artículos se revisan y fotografían al llegar al almacén; las páginas actuales anuncian 3–7 fotos HD. La cifra no garantiza todos los ángulos relevantes.",
    visual: ["Mapa ángulo-pregunta", [["General", "frente · dorso · izquierda · derecha"], ["Identidad", "etiqueta · opción · cantidad"], ["Detalle", "cierre · impresión · borde · herraje"], ["Resultado", "cubierto · parcial · repetido · ausente"]]],
    related: [["Empezar por el mapa de lagunas de prueba", "/articles/usfans-warehouse-evidence-gap-map"], ["Abrir la guía general de fotos de almacén", "/qc"]],
    sections: [
      ["Cuenta preguntas respondidas, no imágenes subidas", "USFans describe actualmente una fase de almacén en la que el artículo recibido se revisa y fotografía, y las páginas públicas de producto anuncian 3–7 fotos HD de inspección. Ese rango aporta contexto, pero no define cobertura. Tres archivos pueden repetir un mismo frente y siete pueden omitir el dorso, una etiqueta o la base. Enumera primero las preguntas que podrían cambiar tu decisión y asigna a cada una solo una imagen que realmente la responda. Usa cuatro estados: cubierto, parcial, repetido y ausente. Cubierto significa visible con claridad y escala útil. Parcial significa recortado, tapado, lejano o inclinado. Repetido significa prácticamente la misma prueba que otra imagen. Ausente significa que ninguna vista responde. Separa la cantidad oficial del resultado de tu auditoría. No consideres completa una galería solo porque su número esté dentro del rango anunciado."],
      ["Crea una clave de orientación antes de ampliar", "Abre cada imagen una vez a escala normal e identifica la orientación. Etiqueta frente, dorso, lado izquierdo, lado derecho, parte superior y base solo cuando un rasgo estable lo demuestre. En calzado sirven puntera, talón y abertura; en prendas, cuello, cierre o posición de la etiqueta; en bolsos, solapa, anclajes del asa o bolsillos. No supongas que dos fotos laterales muestran lados opuestos: pueden repetir el mismo lado a otra distancia. Marca como desconocida una orientación dudosa. Ordena después las vistas en una secuencia fija y anota si todo el artículo queda dentro del cuadro. Este pase descubre duplicados y puntos ciegos antes de que distraigan los primeros planos. También evita falsas asimetrías por espejo, giro o plegado. La orientación no es prueba del estado; es el sistema de coordenadas para describir una superficie, borde o pieza con precisión."],
      ["Relaciona vistas amplias con forma y posición", "Las fotos amplias responden mejor sobre silueta, proporción, alineación y posición de un rasgo en el artículo completo. Usa un frente recto para comparar ambos lados, un dorso recto para la construcción trasera y laterales equivalentes para paneles, suelas, costuras o correas. En ropa, una vista plana completa puede mostrar torsión, bajos desiguales o colocación de impresión, aunque los pliegues oculten costuras y alteren la longitud aparente. En zapatos, el par junto ayuda a revisar simetría, pero el más cercano puede parecer mayor. En bolsos, una vista vertical muestra forma y asas, no interior ni base. Marca parcial si falta un borde, el embalaje tapa, la pieza está doblada o la cámara es muy oblicua. No conviertas una vista general en conclusión de detalle: la posición global no demuestra calidad de puntada, texto de etiqueta ni una marca minúscula."],
      ["Usa primeros planos solo para detalles localizados", "Un primer plano sirve cuando puedes unirlo a una ubicación establecida por una vista amplia. Registra detalle y posición: borde superior izquierdo del estampado, panel exterior del zapato derecho, costura trasera inferior o cierre frontal. Sin esa conexión, una marca aislada puede pertenecer al embalaje o a otra superficie. Para un posible defecto, la mejor pareja suele ser una foto amplia que lo ubique y otra cercana que muestre textura y límites. Un acercamiento puede apoyar observaciones sobre costuras, bordes de impresión, roces, desconchados, acabado de herrajes o texto legible. No prueba construcción oculta, composición, autenticidad, impermeabilidad, duración ni función electrónica. El zoom digital puede ampliar bloques y halos, no nueva evidencia. Si el detalle desaparece a tamaño normal o cambia entre archivos, reduce la confianza y describe solo lo visible de forma consistente."],
      ["Audita por separado etiquetas, cantidad y piezas", "Identidad e integridad suelen necesitar su propio plan. Para una etiqueta, comprueba si aparece completa y frontal, si se leen las líneas relevantes y si la foto corresponde a esta unidad. Una talla visible prueba lo que dice la etiqueta, no las medidas físicas ni el ajuste. Cuenta un conjunto solo en un cuadro con unidades distintas visibles o reconcilia varias vistas para no contar dos veces la misma pieza. Crea una fila de piezas esperadas desde la opción guardada y marca cada una visible, parcial o no mostrada. Una foto de embalaje puede enseñar un código externo sin confirmar accesorios interiores; un bolsillo cerrado tampoco prueba su contenido. Separa estas cuestiones del estado superficial para que una pieza principal limpia no oculte dudas de cantidad, accesorio o variante. Si la referencia del pedido es ambigua, registra esa incertidumbre previa en vez de adivinar la opción mediante las fotos."],
      ["Controla perspectiva, luz y obstrucción", "Un ángulo altera la forma aparente. Compara distancia, giro y lado semejantes. Bordes convergentes suelen indicar perspectiva: el lado cercano parece más ancho, una abertura circular parece ovalada y una impresión recta parece inclinada. La luz cambia color y sombras; una superficie brillante puede parecer marcada. El plástico crea reflejos, pliegues y líneas falsas. Manos, reglas, papel o relleno pueden tapar el límite necesario. Registra estas condiciones como limitaciones de imagen, no como defectos. Si dos vistas chocan, decide cuál es más frontal, está mejor iluminada y menos obstruida. Si ninguna es fiable, deja la cuestión abierta. No promedies dos vistas dudosas para crear certeza. Una nota útil nombra perspectiva lateral fuerte, luz cálida, envoltorio reflectante, tela doblada o borde oculto e indica qué orientación alternativa resolvería la duda."],
      ["Solicita el ángulo mínimo que cambie la decisión", "Al completar el mapa, no pidas una galería extra genérica. Elige la fila ausente o parcial de mayor impacto y especifica una vista reproducible: artículo, superficie, dirección de cámara y encuadre. Ejemplos: dorso completo de frente con todos los bordes; ambos talones juntos a igual distancia; base desde arriba; etiqueta completa fotografiada plana; interior del bolso abierto con base y bolsillos; o vista amplia que sitúe una marca más acercamiento. Si importa la escala, define los extremos y pide ver ambos extremos de la regla. Muestra juntas las piezas de un conjunto cuando sea posible. No pidas a una foto que pruebe material interno, batería, autenticidad o durabilidad futura. Tampoco copies una promesa antigua de servicio, precio o plazo: usa la interfaz y condiciones actuales. El objetivo no son más imágenes, sino una observación que pueda convertir pausar o aclarar en una decisión sustentada."],
      ["Archiva el mapa con un límite honesto", "Guarda referencia de pedido, opción elegida, fecha, identificadores, secuencia de orientación, filas pregunta-imagen y cualquier vista posterior. Excluye direcciones y pagos de una copia compartible. Termina con dos frases: qué respalda la galería y qué queda fuera. Puede respaldar una etiqueta legible, ambos exteriores y ninguna marca visible en un borde concreto, dejando sin probar medidas reales, construcción interior y ajuste. Ese límite vale más que un aprobado general. Si llega otra imagen, añádela y actualiza la fila sin sustituir silenciosamente la evaluación original. Otra unidad o lote necesita otro mapa porque los ángulos de una pieza no prueban la condición de otra. El archivo convierte un conjunto variable en revisión trazable sin afirmar que una galería, por grande que sea, elimina todos los riesgos del producto, vendedor o envío."],
    ],
  },
  fr: {
    meta: ["Méthode des angles", "Vérifié le 09/09/2026", "Indépendant"],
    sourceNote: "Base de recherche : guide débutant, centre d’aide et mentions publiques d’inspection sur les pages produit USFans, vérifiés le 09/09/2026. Les pages officielles indiquent que les articles sont contrôlés et photographiés après arrivée ; les pages actuelles annoncent 3–7 photos HD. Ce nombre ne garantit pas tous les angles utiles.",
    visual: ["Carte angle-question", [["Vue générale", "face · dos · gauche · droite"], ["Identité", "étiquette · option · quantité"], ["Détail", "fermeture · impression · bord · pièce"], ["Résultat", "couvert · partiel · répété · absent"]]],
    related: [["Commencer par la carte des lacunes de preuve", "/articles/usfans-warehouse-evidence-gap-map"], ["Ouvrir le guide général des photos d’entrepôt", "/qc"]],
    sections: [
      ["Compter les questions résolues, pas les images", "USFans décrit actuellement une étape d’entrepôt où l’article arrivé est contrôlé et photographié, et ses pages produit publiques annoncent 3–7 photos HD d’inspection. Cette plage donne un contexte, pas une spécification de couverture. Trois fichiers peuvent répéter une face avant et sept omettre le dos, une étiquette ou le dessous. Listez d’abord les questions susceptibles de changer votre décision, puis rattachez à chacune une image qui y répond réellement. Utilisez quatre états : couvert, partiel, répété et absent. Couvert signifie clairement visible à une échelle exploitable. Partiel signifie recadré, caché, éloigné ou incliné. Répété signifie essentiellement la même preuve qu’une autre image. Absent signifie qu’aucune vue ne répond. Séparez le nombre officiel de votre résultat de couverture. Une galerie n’est pas complète uniquement parce que son nombre se trouve dans la plage annoncée."],
      ["Créer une clé d’orientation avant de zoomer", "Ouvrez chaque image une fois à taille normale et identifiez l’orientation. Étiquetez face, dos, côté gauche, côté droit, dessus et dessous seulement lorsqu’un repère stable l’établit. Pour une chaussure : pointe, talon et ouverture ; pour un vêtement : encolure, fermeture ou position de l’étiquette ; pour un sac : rabat, attaches de poignée ou poches. Ne supposez pas que deux photos latérales montrent des côtés opposés : elles peuvent répéter le même côté à une autre distance. Marquez une orientation douteuse comme inconnue. Rangez ensuite les vues dans un ordre constant et notez si tout l’article reste cadré. Ce passage révèle doublons et angles morts avant que les gros plans ne distraient. Il évite aussi une fausse asymétrie due au miroir, à la rotation ou au pliage. L’orientation n’est pas une preuve d’état ; c’est le système de coordonnées des observations précises."],
      ["Associer les vues larges aux questions de forme et de placement", "Les vues larges répondent à la silhouette, aux proportions, à l’alignement général et à la position d’un élément dans l’ensemble. Utilisez une face droite pour comparer les côtés, un dos droit pour la construction arrière et des côtés comparables pour panneaux, semelles, coutures ou sangles. Pour un vêtement, une vue à plat révèle torsion, ourlet inégal ou placement d’impression, mais les plis cachent des coutures et modifient la longueur apparente. Pour des chaussures, la paire ensemble aide à vérifier la symétrie, même si la plus proche paraît plus grande. Pour un sac, une vue verticale montre forme et poignées, pas intérieur ou base. Marquez partiel si un bord manque, l’emballage gêne, l’article est plié ou la caméra très oblique. N’utilisez pas une vue générale pour conclure sur un détail : le placement global ne prouve ni qualité du point, ni texte, ni petite marque."],
      ["N’utiliser les gros plans que pour des détails localisés", "Un gros plan est utile s’il se rattache à un emplacement établi par une vue large. Notez détail et position : bord supérieur gauche de l’impression, panneau extérieur de la chaussure droite, couture arrière basse ou fermoir avant. Sans ce lien, une marque isolée peut appartenir à l’emballage ou à une autre surface. Pour un défaut supposé, la meilleure paire est souvent une vue large qui le situe et une proche qui montre texture et limites. Un gros plan peut étayer couture visible, bord d’impression, éraflure, éclat, finition métallique ou texte lisible. Il ne prouve pas structure cachée, composition, authenticité, étanchéité, durabilité ou fonction électronique. Le zoom numérique peut agrandir blocs et halos sans révéler de preuve. Si le détail disparaît à taille normale ou change entre fichiers, baissez la confiance et décrivez seulement ce qui reste visible de façon constante."],
      ["Auditer séparément étiquettes, quantité et pièces incluses", "Identité et complétude exigent souvent leur propre plan. Pour une étiquette, vérifiez qu’elle est entière, de face, lisible et rattachable à cette unité. Une taille visible prouve ce qu’affiche l’étiquette, pas les mesures physiques ni la coupe. Comptez un ensemble dans une image où les unités sont distinctes, ou rapprochez plusieurs vues sans compter deux fois la même pièce. Créez une ligne des pièces attendues à partir de l’option sauvegardée et marquez chacune visible, partielle ou non montrée. Une photo d’emballage peut afficher un code extérieur sans confirmer les accessoires internes ; une poche fermée ne prouve pas son contenu. Séparez ces questions de l’état de surface afin qu’un article principal propre ne masque pas une incertitude de quantité, accessoire ou variante. Si la référence de commande est ambiguë, consignez cette incertitude amont au lieu de deviner l’option avec les photos."],
      ["Contrôler perspective, lumière et obstruction", "Un angle modifie la forme apparente. Comparez distance, rotation et côté semblables. Des bords convergents signalent souvent la perspective : le côté proche paraît plus large, une ouverture ronde devient ovale et une impression droite paraît inclinée. La lumière déplace couleur et ombres ; une surface brillante peut sembler marquée. Le film d’emballage ajoute reflets, plis et fausses lignes. Mains, règles, papier ou rembourrage peuvent cacher la limite nécessaire. Notez ces conditions comme limites de l’image, pas comme défauts. Si deux vues se contredisent, choisissez celle qui est plus frontale, mieux éclairée et moins obstruée. Si aucune n’est fiable, laissez la question ouverte. Ne transformez pas deux vues incertaines en certitude moyenne. Une note utile nomme forte perspective, lumière chaude, film réfléchissant, tissu plié ou bord caché et indique l’orientation qui résoudrait le doute."],
      ["Demander le plus petit angle capable de changer la décision", "Une fois la carte terminée, ne demandez pas une galerie supplémentaire générique. Choisissez la ligne absente ou partielle au plus fort impact et précisez une vue reproductible : article, surface, direction de caméra et cadrage. Exemples : dos complet de face avec tous les bords ; deux talons ensemble à même distance ; dessous vu directement ; étiquette entière à plat ; intérieur du sac ouvert montrant base et poches ; ou vue large situant une marque suivie d’un gros plan. Si l’échelle compte, indiquez les extrémités de mesure et demandez que les deux bouts de la règle soient visibles. Regroupez les pièces d’un ensemble lorsque possible. Ne demandez pas à une photo de prouver matière interne, batterie, authenticité ou durabilité. N’importez pas une ancienne promesse de service, prix ou délai : utilisez l’interface et les conditions actuelles. Le but n’est pas plus d’images, mais l’observation manquante qui peut transformer suspendre ou clarifier en décision étayée."],
      ["Archiver une carte avec une limite honnête", "Conservez référence, option choisie, date, identifiants d’image, séquence d’orientation, lignes question-image et vue de suivi. Excluez adresses et paiements d’une copie partageable. Terminez par deux déclarations : ce que la galerie soutient et ce qui reste hors de portée. Elle peut soutenir une étiquette lisible, les deux côtés extérieurs et aucune marque visible sur un bord nommé, tout en laissant mesures réelles, construction interne et coupe non prouvées. Cette limite vaut plus qu’un succès global. Si une image arrive, ajoutez-la et mettez à jour la ligne sans remplacer silencieusement l’évaluation originale. Une autre unité ou série nécessite une autre carte ; les angles d’un article ne prouvent pas l’état d’un autre. L’archive transforme une série variable en contrôle traçable sans prétendre qu’une galerie, même grande, élimine tous les risques liés au produit, au vendeur ou à l’expédition."],
    ],
  },
  it: {
    meta: ["Metodo degli angoli", "Verificato il 09/09/2026", "Indipendente"],
    sourceNote: "Base di ricerca: guida iniziale, centro assistenza e dichiarazioni pubbliche sulle ispezioni nelle pagine prodotto USFans, verificati il 09/09/2026. Le pagine ufficiali dicono che gli articoli vengono controllati e fotografati dopo l’arrivo; le pagine attuali indicano 3–7 foto HD. Il numero non garantisce tutti gli angoli utili.",
    visual: ["Mappa angolo-domanda", [["Panoramica", "fronte · retro · sinistra · destra"], ["Identità", "etichetta · opzione · quantità"], ["Dettaglio", "chiusura · stampa · bordo · ferramenta"], ["Esito", "coperto · parziale · ripetuto · mancante"]]],
    related: [["Inizia dalla mappa delle lacune probatorie", "/articles/usfans-warehouse-evidence-gap-map"], ["Apri la guida generale alle foto di magazzino", "/qc"]],
    sections: [
      ["Conta le domande risolte, non le immagini caricate", "USFans descrive attualmente una fase di magazzino in cui l’articolo arrivato viene controllato e fotografato; le pagine prodotto pubbliche indicano 3–7 foto HD di ispezione. L’intervallo è un contesto utile, non una specifica di copertura. Tre file possono ripetere lo stesso fronte e sette possono omettere retro, etichetta o fondo. Elenca prima le domande che potrebbero cambiare la decisione e assegna a ciascuna solo un’immagine che risponda davvero. Usa quattro stati: coperto, parziale, ripetuto e mancante. Coperto significa chiaramente visibile a scala utile. Parziale significa tagliato, coperto, lontano o inclinato. Ripetuto significa la stessa prova di un’altra immagine. Mancante significa nessuna vista pertinente. Tieni separato il conteggio ufficiale dal risultato della copertura. Non dichiarare completa una galleria solo perché rientra nell’intervallo annunciato."],
      ["Crea una chiave di orientamento prima dello zoom", "Apri ogni immagine una volta a dimensione normale e identifica l’orientamento. Etichetta fronte, retro, lato sinistro, lato destro, sopra e fondo solo quando un elemento stabile lo dimostra. Nelle scarpe aiutano punta, tallone e apertura; nei capi scollo, chiusura o posizione dell’etichetta; nelle borse patta, attacchi dei manici o tasche. Non presumere che due laterali mostrino lati opposti: possono ripetere lo stesso lato da altra distanza. Segna come sconosciuto un orientamento incerto. Ordina poi le viste in una sequenza fissa e annota se l’oggetto resta interamente nel quadro. Questo passaggio rivela duplicati e zone cieche prima che distraggano i primi piani. Evita inoltre false asimmetrie dovute a specchio, rotazione o piegatura. L’orientamento non prova le condizioni; è il sistema di coordinate per riferire osservazioni precise a superficie, bordo o componente."],
      ["Collega le viste ampie a forma e posizione", "Le foto ampie servono per sagoma, proporzioni, allineamento generale e posizione di un elemento nell’intero articolo. Usa un fronte diritto per confrontare i lati, un retro diritto per la costruzione posteriore e lati equivalenti per pannelli, suole, cuciture o cinghie. Un capo disteso può mostrare torsione, orli disuguali o posizione della stampa, ma le pieghe nascondono cuciture e alterano la lunghezza apparente. Nelle scarpe la coppia insieme aiuta la simmetria, anche se quella più vicina può sembrare più grande. Una borsa verticale mostra forma e manici, non interno o fondo. Marca parziale se manca un bordo, l’imballo copre, l’articolo è piegato o la camera molto obliqua. Non estendere la panoramica a conclusioni fini: la posizione globale non prova qualità dei punti, testo dell’etichetta o un piccolo segno."],
      ["Usa i primi piani solo per dettagli localizzati", "Un primo piano è utile se lo colleghi a una posizione stabilita da una vista ampia. Registra dettaglio e luogo: bordo alto sinistro della stampa, pannello esterno della scarpa destra, cucitura posteriore bassa o chiusura frontale. Senza questo legame, un segno isolato può appartenere all’imballaggio o a un’altra superficie. Per un possibile difetto, la coppia migliore è spesso una foto ampia che lo localizza e una vicina che mostra consistenza e limiti. Il dettaglio può sostenere osservazioni su cuciture, bordi di stampa, graffi, scheggiature, finitura metallica o testo leggibile. Non prova costruzione nascosta, composizione, autenticità, impermeabilità, durata o funzione elettronica. Lo zoom digitale può ampliare blocchi e aloni, non nuova prova. Se il dettaglio scompare a dimensione normale o cambia fra file, riduci la fiducia e descrivi solo ciò che resta coerentemente visibile."],
      ["Controlla separatamente etichette, quantità e parti", "Identità e completezza richiedono spesso un piano proprio. Per un’etichetta verifica che sia intera, frontale, leggibile e collegabile a questa unità. Una taglia visibile prova ciò che dice il cartellino, non misure fisiche o vestibilità. Conta un set in un quadro con unità distinte o riconcilia più viste senza contare due volte la stessa parte. Crea una riga delle parti previste dall’opzione salvata e marca ciascuna visibile, parziale o non mostrata. Una foto dell’imballo può mostrare un codice esterno senza confermare accessori interni; una tasca chiusa non prova il contenuto. Separa questi quesiti dallo stato superficiale, affinché un articolo principale pulito non nasconda dubbi su quantità, accessorio o variante. Se il riferimento d’ordine è ambiguo, registra l’incertezza a monte invece di indovinare l’opzione con le foto."],
      ["Controlla prospettiva, luce e ostacoli", "Un angolo cambia la forma apparente. Confronta distanza, rotazione e lato simili. Bordi convergenti indicano spesso prospettiva: il lato vicino pare più largo, un’apertura rotonda ovale e una stampa diritta inclinata. La luce cambia colore e ombre; una superficie lucida può sembrare segnata. La pellicola crea riflessi, pieghe e linee false. Mani, righelli, carta o imbottitura possono nascondere il confine necessario. Registra tali condizioni come limiti dell’immagine, non difetti. Se due viste contrastano, valuta quale sia più frontale, meglio illuminata e meno coperta. Se nessuna è affidabile, lascia aperta la domanda. Non fare la media di due viste incerte per creare sicurezza. Una nota utile nomina prospettiva forte, luce calda, involucro riflettente, tessuto piegato o bordo nascosto e indica quale orientamento alternativo risolverebbe il dubbio."],
      ["Richiedi l’angolo minimo che cambia la decisione", "Completata la mappa, non chiedere una galleria extra generica. Scegli la riga mancante o parziale di maggior impatto e specifica una vista riproducibile: articolo, superficie, direzione e inquadratura. Esempi: retro intero frontale con tutti i bordi; entrambi i talloni insieme alla stessa distanza; fondo visto dall’alto; etichetta completa stesa; interno della borsa aperto con base e tasche; oppure panoramica che localizzi un segno e primo piano. Se conta la scala, definisci gli estremi e chiedi che entrambe le estremità del righello siano visibili. Riunisci i pezzi di un set quando possibile. Non chiedere alla foto di provare materiale interno, batteria, autenticità o durata futura. Non importare vecchie promesse di servizio, prezzo o tempo: usa interfaccia e termini attuali. L’obiettivo non sono più immagini, ma l’osservazione che può trasformare sospendi o chiarisci in una decisione sostenuta."],
      ["Archivia la mappa con un limite onesto", "Conserva riferimento d’ordine, opzione scelta, data, identificatori, sequenza di orientamento, righe domanda-immagine e viste successive. Escludi indirizzi e pagamenti da una copia condivisibile. Chiudi con due frasi: cosa sostiene la galleria e cosa resta fuori. Può sostenere un’etichetta leggibile, entrambi i lati esterni e nessun segno visibile su un bordo preciso, lasciando non provate misure reali, costruzione interna e vestibilità. Questo limite vale più di un superato generico. Se arriva una nuova immagine, aggiungila e aggiorna la riga senza sostituire in silenzio la valutazione originale. Un’altra unità o lotto richiede una mappa separata, perché gli angoli di un articolo non provano la condizione di un altro. L’archivio rende tracciabile una serie variabile senza affermare che una galleria, per quanto ampia, elimini ogni rischio di prodotto, venditore o spedizione."],
    ],
  },
};

export function getUveAngleArticle(language) {
  const activeLanguage = localized[language] ? language : "en";
  const entry = localized[activeLanguage];
  return {
    ...uveAngleArticleBlueprint,
    title: uveAngleArticleBlueprint.title[activeLanguage],
    dek: uveAngleArticleBlueprint.dek[activeLanguage],
    sections: entry.sections,
    sourceNote: entry.sourceNote,
    visual: entry.visual,
    related: entry.related,
    articleMeta: entry.meta,
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
  };
}
