export const uveArticleBlueprint = {
  slug: "usfans-warehouse-evidence-gap-map",
  title: {
    en: "USFans Warehouse Evidence-Gap Map: Decide What Photos Can Prove",
    de: "USFans-Lagerbelege prüfen: Was Fotos wirklich beweisen",
    es: "Mapa de pruebas de almacén USFans: qué pueden demostrar las fotos",
    fr: "Carte des preuves d’entrepôt USFans : ce que les photos peuvent prouver",
    it: "Mappa delle prove di magazzino USFans: cosa possono dimostrare le foto",
  },
  dek: {
    en: "Inventory the views you have, name the evidence you still need and separate visible facts from assumptions before accepting, holding or clarifying an item.",
    de: "Erfasse vorhandene Ansichten, benenne fehlende Belege und trenne sichtbare Fakten von Annahmen, bevor du einen Artikel annimmst, zurückstellst oder klärst.",
    es: "Inventaría las vistas disponibles, define las pruebas que faltan y separa hechos visibles de suposiciones antes de aceptar, pausar o aclarar un artículo.",
    fr: "Inventoriez les vues disponibles, nommez les preuves manquantes et séparez les faits visibles des hypothèses avant d’accepter, suspendre ou clarifier un article.",
    it: "Censisci le viste disponibili, definisci le prove mancanti e separa i fatti visibili dalle ipotesi prima di accettare, sospendere o chiarire un articolo.",
  },
  topics: [],
};

const localized = {
  en: {
    meta: ["Evidence-gap method", "Checked 07 Sep 2026", "Independent"],
    sourceNote: "Research basis: current USFans homepage, Beginner’s Guide and public product-page inspection statements checked 07 Sep 2026. The official pages describe warehouse inspection and photos; the useful coverage for a particular item still has to be judged from the images actually supplied.",
    visual: ["Evidence-gap map", [["Identity", "item · option · quantity · visible labels"], ["Coverage", "front · back · sides · detail · scale"], ["Limits", "hidden · blurred · untested · not measurable"], ["Decision", "accept · hold · clarify"]]],
    related: [["Open the warehouse-photo inspection guide", "/qc"], ["Read the category-by-category QC method", "/articles/how-to-read-usfans-qc-photos"]],
    sections: [
      ["Begin with a decision question, not a defect hunt", "A warehouse evidence-gap map is a short record of what the supplied images answer, what they leave unresolved and whether the missing information could change your decision. Start by writing one decision question: “Does this unit match the ordered option and my non-negotiable visible requirements?” That question is narrower and more useful than “Is it good?” It also prevents a striking close-up from dominating the review while identity, quantity or scale remains uncertain. The current USFans public workflow says that items are inspected and photographed after reaching the warehouse. That establishes a review stage, but it does not mean every possible angle, measurement or function will appear for every product. Build the map from the actual evidence in front of you. List each supplied view, connect it to a question and mark the answer as observed, partly observed or not observed. Do not grade workmanship until the item identity is reasonably aligned with the order. If the wrong option may have arrived, a detailed cosmetic review of that unit does not resolve the first problem."],
      ["Lock identity before interpreting condition", "Create an identity row using the order name, selected color, size, style, quantity and any option-level wording saved before payment. Then look for corresponding visible markers: a size tag, color code, model text, packaging label, repeated units or included pieces. A marker is evidence only for what it visibly states. A photographed label can support that the label shows a certain size; it cannot prove the garment’s real measurements or fit. A box code may support the packaged model identity; it cannot prove that every component inside matches. When text is cropped, translated ambiguously or too soft to read, mark it unresolved rather than completing it from memory. For sets, count all visible pieces and note which expected parts never appear. For two similar variants, identify the feature that distinguishes them before zooming into general finish. This sequence protects against a common reasoning error: finding several attractive details and then assuming the product must therefore be the ordered version. Identity confidence should come from matching decision-relevant markers, not from the total number of photographs."],
      ["Inventory coverage by question and angle", "Make one row for every question that matters: overall shape, front and back, both sides, label, closure, print, hardware, included parts, measurement point or visible damage area. Beside it, record the best supporting image and whether that image is direct, partial or unusable. A direct view shows the relevant area at a workable scale and angle. A partial view may show only one side, hide an edge or lack a reference for size. An unusable view may be blurred, strongly compressed, blocked by packaging or distorted by perspective. Do not treat five photographs as five answers; several images can repeat the same angle while one critical surface remains unseen. Likewise, one wide image can answer overall shape but not fine stitching, and one close-up can show thread or print edges but not placement on the whole item. Coverage is therefore about question-to-image matching, not image count. When two images conflict, note the lighting, camera distance and orientation before deciding that the product itself changed."],
      ["Separate observation, comparison and inference", "Use three columns in your notes. “Observed” contains only what the image visibly supports: a mark appears near an edge, two sides look unequal in this angle, the tag displays a value, or a component is not visible in the supplied set. “Compared” records the reference used, such as the selected option image, a saved measurement requirement or the opposite side of the same unit. “Inferred” contains conclusions that may be plausible but are not proven, such as material composition, authenticity, internal construction, waterproofing, battery health, durability, odor or real-world fit. Never move an inference into the observed column merely because a seller description repeats it. Photos can reveal surface evidence and some measurable geometry; they cannot establish many hidden or functional properties. Careful wording matters. “The part is missing” is stronger than the evidence when that part could be outside the frame. “The part is not visible in the supplied images” is accurate and tells you exactly what clarification could close the gap."],
      ["Rank gaps by decision impact", "Not every missing view deserves another request. Give each gap an impact level. Critical means the answer could change identity, usability, completeness or your accept-versus-return decision: the selected size is unreadable, a fragile edge is hidden, a required part is not shown or a decision-critical measurement is absent. Important means the answer affects preference or confidence but may not make the item unusable, such as print alignment within your personal tolerance. Minor means the gap is unlikely to change the decision, such as a packaging corner when the product itself is fully visible. Add a confidence label—high, medium or low—based on evidence quality, not optimism. High confidence needs a direct and readable view. Medium confidence may rely on a partial but consistent view. Low confidence means blur, obstruction, perspective or missing scale prevents a stable conclusion. This ranking keeps the review proportionate. It also avoids requesting many generic photos that create more data without answering the one question that matters."],
      ["Write a clarification request that can close one gap", "A useful request names the item, the exact area, the required orientation and the evidence format. Instead of “more photos please,” write: “Please photograph the full size tag straight on so every line is readable,” or “Please place a ruler from the left chest seam to the right chest seam with the garment flat and show both ruler endpoints.” For a mark, ask for one wider image that locates it and one close image that shows its surface. For quantity, request all pieces in one frame when practical. Do not request a visual test for something photographs cannot prove. If electronic function, internal material or authenticity is the real question, acknowledge that the image workflow may not close it. Keep one request tied to one decision gap, and record when it was made. When new evidence arrives, add it to the same row rather than restarting the review. The result is an auditable chain: original question, initial evidence, identified gap, precise request and updated conclusion."],
      ["Use an accept, hold or clarify matrix", "Choose “accept” only when the visible identity and all decision-critical requirements are supported at the confidence level you set in advance. Accept does not mean the item is guaranteed authentic, durable, functional or perfect; it means the available visual evidence meets your stated threshold. Choose “clarify” when one bounded missing view or measurement could realistically change the decision and can be requested precisely. Choose “hold” when the evidence is contradictory, a critical question remains outside visual proof, or several unresolved gaps make a confident decision impossible. If the site presents a time-sensitive action, verify the current interface and policy rather than importing an old deadline into your notes. The matrix should also record acceptable imperfections. A loose thread, small packaging dent or slight photographic color shift may be within one buyer’s tolerance and outside another’s. Define those limits before inspecting, so prior payment does not quietly lower the standard. A short reason beside the final status is more useful than a bare pass or fail."],
      ["Archive the map as a compact decision record", "Save the order reference, option text, review date, supplied image identifiers, critical requirements, coverage rows, clarification request and final reason together. Avoid storing private addresses, payment details or unrelated account data in a shareable record. If you later compare another unit, begin a new map instead of assuming the first item’s evidence applies to a different batch. The archive is useful even when the item is accepted: it shows which characteristics were actually visible and which remained unknown. It also keeps a later product review honest, because you can distinguish the seller listing, the exact warehouse unit and the conclusions you personally inferred. Reopen the record before parcel submission to confirm that every accepted item is the one you intended to include. The method is deliberately modest. It does not turn photographs into certainty. It turns a loose gallery into a traceable decision by naming the question, matching each answer to an image, exposing uncertainty and requesting only evidence capable of changing the outcome."],
    ],
  },
  de: {
    meta: ["Methode für Beleglücken", "Geprüft am 07.09.2026", "Unabhängig"],
    sourceNote: "Recherchegrundlage: aktuelle USFans-Startseite, Einsteigerleitfaden und öffentliche Hinweise zur Inspektion auf Produktseiten, geprüft am 07.09.2026. Die offiziellen Seiten beschreiben Lagerprüfung und Fotos; die brauchbare Abdeckung eines konkreten Artikels muss dennoch anhand der tatsächlich gelieferten Bilder bewertet werden.",
    visual: ["Karte der Beleglücken", [["Identität", "Artikel · Option · Menge · sichtbare Labels"], ["Abdeckung", "Vorn · Hinten · Seiten · Detail · Maßstab"], ["Grenzen", "verdeckt · unscharf · ungetestet · nicht messbar"], ["Entscheidung", "annehmen · halten · klären"]]],
    related: [["Leitfaden zur Prüfung von Lagerfotos öffnen", "/qc"], ["QC-Methode nach Produktkategorie lesen", "/articles/how-to-read-usfans-qc-photos"]],
    sections: [
      ["Mit einer Entscheidungsfrage beginnen, nicht mit der Fehlersuche", "Eine Karte der Lagerbeleglücken ist ein kurzer Datensatz darüber, was die gelieferten Bilder beantworten, was offenbleibt und ob die fehlende Information deine Entscheidung ändern könnte. Formuliere zuerst eine Frage: „Entspricht dieses Stück der bestellten Option und meinen unverzichtbaren sichtbaren Anforderungen?“ Das ist enger und nützlicher als „Ist es gut?“. Außerdem verhindert es, dass eine auffällige Nahaufnahme die Prüfung dominiert, während Identität, Menge oder Maßstab unklar bleiben. Der aktuelle öffentliche USFans-Ablauf beschreibt, dass Artikel nach Ankunft im Lager geprüft und fotografiert werden. Damit gibt es eine Prüfphase, aber nicht zwingend jeden möglichen Winkel, jedes Maß oder jede Funktion für jedes Produkt. Erstelle die Karte ausschließlich aus den Belegen vor dir. Liste jede Ansicht auf, ordne ihr eine Frage zu und markiere die Antwort als beobachtet, teilweise beobachtet oder nicht beobachtet. Bewerte die Verarbeitung erst, wenn die Identität ausreichend mit der Bestellung übereinstimmt. Ist möglicherweise die falsche Option angekommen, löst eine kosmetische Detailprüfung dieses Stücks das erste Problem nicht."],
      ["Identität sichern, bevor der Zustand bewertet wird", "Lege eine Identitätszeile mit Bestellname, gewählter Farbe, Größe, Ausführung, Menge und vor der Zahlung gespeicherter Optionsbezeichnung an. Suche dann nach entsprechenden sichtbaren Merkmalen: Größenetikett, Farbcode, Modelltext, Verpackungslabel, wiederholte Einheiten oder enthaltene Teile. Ein Merkmal belegt nur, was sichtbar darauf steht. Ein fotografiertes Label kann zeigen, dass dort eine bestimmte Größe genannt wird; es beweist weder reale Maße noch Passform. Ein Kartoncode kann die verpackte Modellidentität stützen, bestätigt aber nicht automatisch jeden Inhalt. Ist Text abgeschnitten, mehrdeutig übersetzt oder unleserlich, markiere ihn als offen, statt ihn aus dem Gedächtnis zu ergänzen. Zähle bei Sets alle sichtbaren Teile und notiere erwartete, aber nie gezeigte Komponenten. Bestimme bei ähnlichen Varianten zuerst das unterscheidende Merkmal. So vermeidest du den Fehler, aus mehreren schönen Details auf die bestellte Version zu schließen. Identitätsvertrauen entsteht durch passende entscheidungsrelevante Merkmale, nicht durch die Zahl der Fotos."],
      ["Abdeckung nach Frage und Winkel inventarisieren", "Erstelle eine Zeile für jede wichtige Frage: Gesamtform, Vorder- und Rückseite, beide Seiten, Label, Verschluss, Druck, Beschläge, enthaltene Teile, Messpunkt oder sichtbarer Schadensbereich. Notiere daneben das beste unterstützende Bild und ob es direkt, teilweise oder unbrauchbar ist. Eine direkte Ansicht zeigt die relevante Stelle in brauchbarem Maßstab und Winkel. Eine Teilansicht zeigt vielleicht nur eine Seite, verdeckt eine Kante oder besitzt keinen Größenbezug. Unbrauchbar sind Bilder etwa bei Unschärfe, starker Kompression, verdeckender Verpackung oder verzerrender Perspektive. Fünf Fotos sind nicht automatisch fünf Antworten; mehrere können denselben Winkel wiederholen, während eine kritische Fläche fehlt. Eine Weitaufnahme kann die Gesamtform beantworten, aber keine feinen Nähte. Eine Nahaufnahme kann Faden- oder Druckkanten zeigen, aber nicht die Platzierung am ganzen Artikel. Abdeckung bedeutet deshalb Zuordnung von Frage zu Bild, nicht Bildanzahl. Widersprechen sich zwei Ansichten, notiere Licht, Kameradistanz und Ausrichtung, bevor du eine Veränderung am Produkt annimmst."],
      ["Beobachtung, Vergleich und Schlussfolgerung trennen", "Nutze drei Spalten. „Beobachtet“ enthält nur, was das Bild sichtbar stützt: Eine Markierung liegt nahe einer Kante, zwei Seiten wirken in diesem Winkel ungleich, ein Etikett zeigt einen Wert oder eine Komponente erscheint in der gelieferten Bildserie nicht. „Verglichen“ nennt die Referenz, etwa das gewählte Optionsbild, eine gespeicherte Maßanforderung oder die Gegenseite desselben Stücks. „Gefolgert“ enthält plausible, aber unbelegte Aussagen wie Materialzusammensetzung, Authentizität, innerer Aufbau, Wasserdichtigkeit, Batteriezustand, Haltbarkeit, Geruch oder reale Passform. Verschiebe eine Schlussfolgerung nie zu den Beobachtungen, nur weil eine Verkäuferbeschreibung sie wiederholt. Fotos zeigen Oberflächenbelege und teilweise messbare Geometrie, können aber viele verborgene oder funktionale Eigenschaften nicht bestätigen. Präzise Sprache ist wichtig. „Das Teil fehlt“ geht zu weit, wenn es außerhalb des Bildes liegen könnte. „Das Teil ist auf den gelieferten Bildern nicht sichtbar“ ist korrekt und benennt genau, welche Klärung die Lücke schließen kann."],
      ["Lücken nach Entscheidungswirkung ordnen", "Nicht jede fehlende Ansicht rechtfertigt eine weitere Anfrage. Weise jeder Lücke eine Wirkung zu. Kritisch bedeutet, dass die Antwort Identität, Nutzbarkeit, Vollständigkeit oder die Annahmeentscheidung ändern könnte: Die gewählte Größe ist unleserlich, eine zerbrechliche Kante verdeckt, ein erforderliches Teil nicht gezeigt oder ein entscheidendes Maß fehlt. Wichtig betrifft Vorlieben oder Vertrauen, ohne den Artikel zwingend unbrauchbar zu machen, etwa eine Druckausrichtung innerhalb deiner persönlichen Toleranz. Geringfügig bedeutet, dass die Lücke die Entscheidung wahrscheinlich nicht ändert, zum Beispiel eine Verpackungsecke bei vollständig sichtbarem Produkt. Ergänze ein Vertrauensniveau – hoch, mittel oder niedrig – nach Belegqualität, nicht Optimismus. Hohes Vertrauen braucht eine direkte lesbare Ansicht. Mittleres kann auf einer teilweisen, aber konsistenten Ansicht beruhen. Niedrig bedeutet, dass Unschärfe, Verdeckung, Perspektive oder fehlender Maßstab keine stabile Aussage zulassen. Diese Ordnung hält die Prüfung verhältnismäßig und verhindert viele allgemeine Fotoanfragen, die mehr Daten erzeugen, aber die entscheidende Frage nicht beantworten."],
      ["Eine Klärungsanfrage formulieren, die genau eine Lücke schließt", "Eine brauchbare Anfrage nennt Artikel, genaue Stelle, erforderliche Ausrichtung und Belegformat. Statt „Bitte mehr Fotos“ schreibe: „Bitte das vollständige Größenetikett gerade fotografieren, sodass jede Zeile lesbar ist“, oder: „Bitte das Kleidungsstück flach hinlegen, ein Lineal von der linken zur rechten Brustnaht führen und beide Endpunkte zeigen.“ Frage bei einer Markierung nach einer Weitaufnahme zur Position und einer Nahaufnahme der Oberfläche. Bitte bei Mengenfragen wenn möglich um alle Teile in einem Bild. Verlange keinen visuellen Test für etwas, das Fotos nicht beweisen können. Ist Elektronikfunktion, inneres Material oder Authentizität die eigentliche Frage, erkenne an, dass die Bildprüfung sie möglicherweise nicht schließt. Verbinde eine Anfrage mit genau einer Entscheidungslücke und notiere den Zeitpunkt. Kommen neue Belege, ergänze sie in derselben Zeile, statt die Prüfung neu zu beginnen. So entsteht eine nachvollziehbare Kette aus Ausgangsfrage, erstem Beleg, erkannter Lücke, präziser Anfrage und aktualisierter Schlussfolgerung."],
      ["Eine Matrix aus Annehmen, Halten und Klären verwenden", "Wähle „annehmen“ nur, wenn sichtbare Identität und alle entscheidungskritischen Anforderungen das vorher festgelegte Vertrauensniveau erreichen. Annehmen bedeutet nicht garantiert echt, haltbar, funktionsfähig oder perfekt; es bedeutet nur, dass die verfügbaren visuellen Belege deinen Schwellenwert erfüllen. Wähle „klären“, wenn eine begrenzte fehlende Ansicht oder Messung die Entscheidung realistisch verändern und präzise angefordert werden kann. Wähle „halten“, wenn Belege widersprüchlich sind, eine kritische Frage außerhalb visueller Beweise liegt oder mehrere offene Lücken keine belastbare Entscheidung erlauben. Zeigt die Seite eine zeitkritische Aktion, prüfe aktuelle Oberfläche und Richtlinie, statt eine alte Frist zu übernehmen. Die Matrix sollte akzeptable Unvollkommenheiten festhalten. Loser Faden, kleine Verpackungsdelle oder leichte fotografische Farbverschiebung können für einen Käufer innerhalb und für einen anderen außerhalb der Toleranz liegen. Definiere Grenzen vor der Prüfung, damit eine bereits erfolgte Zahlung den Standard nicht heimlich senkt. Ein kurzer Grund neben dem Endstatus ist wertvoller als bloß bestanden oder nicht bestanden."],
      ["Die Karte als kompakten Entscheidungsnachweis archivieren", "Speichere Bestellreferenz, Optionstext, Prüfdatum, Bildkennungen, kritische Anforderungen, Abdeckungszeilen, Klärungsanfrage und Endgrund zusammen. Vermeide private Adressen, Zahlungsdetails oder fremde Kontodaten in einem teilbaren Datensatz. Wenn du später ein anderes Stück vergleichst, beginne eine neue Karte, statt Belege des ersten Artikels auf eine andere Charge zu übertragen. Das Archiv hilft auch bei Annahme: Es zeigt, welche Merkmale sichtbar und welche unbekannt waren. Eine spätere Bewertung bleibt ehrlich, weil du Verkäuferangebot, konkrete Lagereinheit und persönliche Schlussfolgerungen trennen kannst. Öffne den Datensatz vor Paketeinreichung erneut und bestätige, dass jeder angenommene Artikel wirklich aufgenommen werden soll. Die Methode bleibt bewusst bescheiden. Sie verwandelt Fotos nicht in Gewissheit. Sie macht aus einer losen Galerie eine nachvollziehbare Entscheidung, indem sie die Frage benennt, jede Antwort einem Bild zuordnet, Unsicherheit offenlegt und nur Belege anfordert, die das Ergebnis verändern können."],
    ],
  },
  es: {
    meta: ["Método de lagunas probatorias", "Revisado el 07-09-2026", "Independiente"],
    sourceNote: "Base de investigación: página principal, guía para principiantes y textos públicos de inspección en páginas de producto de USFans, revisados el 07-09-2026. Las páginas oficiales describen inspección y fotografías en almacén; la cobertura útil de cada artículo debe juzgarse con las imágenes realmente entregadas.",
    visual: ["Mapa de lagunas probatorias", [["Identidad", "artículo · opción · cantidad · etiquetas visibles"], ["Cobertura", "frente · dorso · laterales · detalle · escala"], ["Límites", "oculto · borroso · no probado · no medible"], ["Decisión", "aceptar · pausar · aclarar"]]],
    related: [["Abrir la guía de inspección de fotos de almacén", "/qc"], ["Leer el método QC por categoría", "/articles/how-to-read-usfans-qc-photos"]],
    sections: [
      ["Empieza por una pregunta de decisión, no por cazar defectos", "Un mapa de lagunas de pruebas de almacén es un registro breve de lo que responden las imágenes, lo que dejan sin resolver y si la información ausente podría cambiar tu decisión. Escribe primero una pregunta: «¿Coincide esta unidad con la opción pedida y con mis requisitos visibles no negociables?». Es más concreta y útil que «¿Es buena?». También evita que un primer plano atractivo domine la revisión mientras identidad, cantidad o escala siguen dudosas. El flujo público actual de USFans indica que los artículos se inspeccionan y fotografían al llegar al almacén. Eso establece una fase de revisión, pero no implica que cada producto incluya todos los ángulos, medidas o pruebas posibles. Construye el mapa solo con la evidencia que tienes. Enumera cada vista, vincúlala a una pregunta y marca la respuesta como observada, observada en parte o no observada. No valores acabados hasta alinear razonablemente la identidad con el pedido. Si pudo llegar otra opción, revisar su cosmética en detalle no resuelve el primer problema."],
      ["Fija la identidad antes de interpretar el estado", "Crea una fila de identidad con nombre del pedido, color, talla, estilo, cantidad y cualquier texto de opción guardado antes del pago. Después busca marcadores visibles correspondientes: etiqueta de talla, código de color, texto de modelo, etiqueta del embalaje, unidades repetidas o piezas incluidas. Un marcador prueba solo lo que muestra. Una etiqueta fotografiada puede apoyar que indica cierta talla; no demuestra las medidas reales ni el ajuste. Un código de caja puede apoyar el modelo embalado, pero no confirma cada componente interior. Si el texto está recortado, traducido de forma ambigua o ilegible, déjalo sin resolver en lugar de completarlo de memoria. En un conjunto, cuenta todas las piezas visibles y anota cuáles se esperaban pero nunca aparecen. Entre variantes parecidas, identifica primero el rasgo que las distingue. Así evitas concluir que es la versión pedida solo porque ves varios detalles atractivos. La confianza en la identidad nace de marcadores relevantes coincidentes, no del número total de fotografías."],
      ["Inventaría la cobertura por pregunta y ángulo", "Crea una fila para cada pregunta importante: forma general, frente y dorso, ambos laterales, etiqueta, cierre, estampado, herrajes, piezas incluidas, punto de medición o zona dañada. Registra la mejor imagen de apoyo y si es directa, parcial o inutilizable. Una vista directa muestra la zona a escala y ángulo útiles. Una parcial puede enseñar solo un lado, ocultar un borde o carecer de referencia de tamaño. Una inutilizable puede estar borrosa, muy comprimida, tapada por embalaje o deformada por perspectiva. No trates cinco fotos como cinco respuestas; varias pueden repetir el mismo ángulo mientras queda una superficie crítica sin ver. Una imagen amplia puede responder sobre la forma, no sobre costuras finas. Un primer plano muestra bordes del hilo o impresión, pero no su colocación en el artículo entero. La cobertura es correspondencia entre pregunta e imagen, no cantidad de imágenes. Si dos fotos parecen contradecirse, anota iluminación, distancia de cámara y orientación antes de decidir que cambió el producto."],
      ["Separa observación, comparación e inferencia", "Usa tres columnas. «Observado» contiene solo lo que sostiene la imagen: una marca aparece junto a un borde, dos lados parecen desiguales desde ese ángulo, la etiqueta muestra un valor o un componente no es visible en la serie entregada. «Comparado» registra la referencia empleada, como la imagen de la opción elegida, una medida requerida o el lado opuesto de la misma unidad. «Inferido» contiene conclusiones plausibles no demostradas: composición, autenticidad, construcción interna, impermeabilidad, salud de batería, durabilidad, olor o ajuste real. No conviertas una inferencia en observación porque la repita la descripción del vendedor. Las fotos muestran superficies y cierta geometría medible, pero no muchas propiedades ocultas o funcionales. El lenguaje preciso importa. «Falta la pieza» es más fuerte que la evidencia si podría estar fuera del encuadre. «La pieza no es visible en las imágenes suministradas» es correcto y define exactamente qué aclaración cerraría la laguna."],
      ["Ordena las lagunas por impacto en la decisión", "No toda vista ausente merece otra solicitud. Asigna a cada laguna un nivel de impacto. Crítico significa que la respuesta puede cambiar identidad, utilidad, integridad o la decisión de aceptar o devolver: talla ilegible, borde frágil oculto, pieza obligatoria no mostrada o medida decisiva ausente. Importante significa que afecta a preferencia o confianza, pero quizá no inutiliza el artículo, como la alineación de un estampado dentro de tu tolerancia. Menor significa que probablemente no cambia la decisión, como una esquina del embalaje cuando el producto se ve entero. Añade confianza alta, media o baja según calidad de prueba, no optimismo. Alta exige una vista directa y legible. Media puede basarse en una vista parcial pero coherente. Baja indica que desenfoque, obstrucción, perspectiva o falta de escala impiden una conclusión estable. Esta jerarquía mantiene proporcional la revisión y evita pedir muchas fotos genéricas que aportan datos sin responder a la única pregunta decisiva."],
      ["Redacta una solicitud que cierre una sola laguna", "Una solicitud útil nombra artículo, zona exacta, orientación y formato de evidencia. En vez de «más fotos», escribe: «Fotografía toda la etiqueta de talla de frente para que se lea cada línea», o «Coloca la prenda plana, extiende una regla desde la costura izquierda del pecho hasta la derecha y muestra ambos extremos». Para una marca, pide una imagen amplia que la ubique y otra cercana de la superficie. Para cantidad, solicita todas las piezas en un mismo cuadro cuando sea práctico. No pidas una prueba visual de algo que una foto no puede demostrar. Si la cuestión real es función electrónica, material interno o autenticidad, reconoce que el flujo de imágenes quizá no la resuelva. Vincula cada solicitud a una sola laguna y registra cuándo se hizo. Cuando llegue nueva prueba, añádela a la misma fila en vez de reiniciar. Obtendrás una cadena auditable: pregunta original, evidencia inicial, laguna, petición precisa y conclusión actualizada."],
      ["Usa una matriz de aceptar, pausar o aclarar", "Elige «aceptar» solo cuando la identidad visible y todos los requisitos críticos estén apoyados al nivel de confianza fijado de antemano. Aceptar no significa que el artículo esté garantizado como auténtico, duradero, funcional o perfecto; significa que la evidencia visual disponible alcanza tu umbral. Elige «aclarar» cuando una vista o medida ausente y acotada pueda cambiar de verdad la decisión y se pueda pedir con precisión. Elige «pausar» cuando la evidencia sea contradictoria, una pregunta crítica esté fuera de la prueba visual o varias lagunas impidan decidir con confianza. Si la interfaz presenta una acción con plazo, verifica la política actual y no copies una fecha antigua. La matriz también debe registrar imperfecciones aceptables. Un hilo suelto, una pequeña abolladura de caja o un cambio de color fotográfico pueden entrar en la tolerancia de una persona y no de otra. Define límites antes de inspeccionar para que el pago previo no rebaje silenciosamente el estándar. Un motivo breve junto al estado final es más útil que aprobado o fallido sin explicación."],
      ["Archiva el mapa como registro compacto de decisión", "Guarda juntos referencia de pedido, texto de opción, fecha, identificadores de imágenes, requisitos críticos, filas de cobertura, solicitud de aclaración y motivo final. Evita direcciones privadas, pagos o datos de cuenta ajenos en un registro compartible. Si comparas otra unidad, abre un mapa nuevo en vez de asumir que la evidencia de la primera sirve para otro lote. El archivo es útil incluso al aceptar: muestra qué rasgos fueron visibles y cuáles quedaron desconocidos. También mantiene honesta una reseña posterior, pues separa ficha del vendedor, unidad exacta de almacén y conclusiones personales. Reabre el registro antes de enviar el paquete para confirmar que cada artículo aceptado es el que querías incluir. El método es deliberadamente modesto. No convierte fotos en certeza. Convierte una galería suelta en una decisión trazable al nombrar la pregunta, asignar cada respuesta a una imagen, mostrar incertidumbre y pedir únicamente pruebas capaces de cambiar el resultado."],
    ],
  },
  fr: {
    meta: ["Méthode des lacunes de preuve", "Vérifié le 07/09/2026", "Indépendant"],
    sourceNote: "Base de recherche : accueil, guide débutant et mentions publiques d’inspection sur les pages produit USFans, vérifiés le 07/09/2026. Les pages officielles décrivent l’inspection et les photos en entrepôt ; la couverture utile d’un article donné doit néanmoins être évaluée d’après les images réellement fournies.",
    visual: ["Carte des lacunes de preuve", [["Identité", "article · option · quantité · étiquettes visibles"], ["Couverture", "face · dos · côtés · détail · échelle"], ["Limites", "caché · flou · non testé · non mesurable"], ["Décision", "accepter · suspendre · clarifier"]]],
    related: [["Ouvrir le guide d’inspection des photos d’entrepôt", "/qc"], ["Lire la méthode QC par catégorie", "/articles/how-to-read-usfans-qc-photos"]],
    sections: [
      ["Commencer par une question de décision, pas par la chasse aux défauts", "Une carte des lacunes de preuve d’entrepôt est un court relevé de ce que les images fournies répondent, de ce qui reste irrésolu et de la possibilité que l’information manquante change votre décision. Écrivez d’abord une question : « Cette unité correspond-elle à l’option commandée et à mes exigences visibles non négociables ? » Elle est plus précise et plus utile que « Est-elle bonne ? ». Elle empêche aussi un gros plan séduisant de dominer l’examen alors que l’identité, la quantité ou l’échelle restent incertaines. Le parcours public actuel de USFans indique que les articles sont inspectés et photographiés après leur arrivée à l’entrepôt. Cela établit une étape de contrôle, sans signifier que tous les angles, mesures ou fonctions apparaissent pour chaque produit. Construisez la carte uniquement à partir des preuves présentes. Listez chaque vue, reliez-la à une question et marquez la réponse comme observée, partiellement observée ou non observée. N’évaluez la finition qu’après avoir raisonnablement aligné l’identité sur la commande. Si la mauvaise option a pu arriver, un examen cosmétique détaillé de cette unité ne résout pas le premier problème."],
      ["Verrouiller l’identité avant d’interpréter l’état", "Créez une ligne d’identité avec le nom commandé, la couleur, la taille, le style, la quantité et le libellé d’option sauvegardé avant paiement. Cherchez ensuite les marqueurs visibles correspondants : étiquette de taille, code couleur, texte de modèle, étiquette d’emballage, unités répétées ou pièces incluses. Un marqueur ne prouve que ce qu’il affiche. Une étiquette photographiée peut établir qu’elle indique une taille ; elle ne prouve ni les mesures réelles ni la coupe. Un code de boîte peut étayer le modèle emballé, mais ne confirme pas chaque composant intérieur. Si le texte est recadré, traduit de façon ambiguë ou illisible, laissez-le irrésolu plutôt que de le compléter de mémoire. Pour un ensemble, comptez toutes les pièces visibles et notez les éléments attendus qui n’apparaissent jamais. Pour deux variantes proches, identifiez d’abord le trait distinctif. Cette séquence évite de supposer qu’il s’agit de la version commandée parce que plusieurs détails sont séduisants. La confiance d’identité vient de marqueurs décisionnels concordants, pas du nombre de photographies."],
      ["Inventorier la couverture par question et par angle", "Créez une ligne pour chaque question importante : forme générale, face et dos, deux côtés, étiquette, fermeture, impression, quincaillerie, pièces incluses, point de mesure ou zone endommagée. Notez l’image la plus utile et indiquez si elle est directe, partielle ou inutilisable. Une vue directe montre la zone à une échelle et sous un angle exploitables. Une vue partielle peut montrer un seul côté, cacher un bord ou manquer de repère de taille. Une vue inutilisable peut être floue, très compressée, bloquée par l’emballage ou déformée par la perspective. Ne traitez pas cinq photos comme cinq réponses : plusieurs peuvent répéter le même angle pendant qu’une surface critique reste invisible. Une image large peut répondre sur la forme, pas sur une couture fine. Un gros plan montre un bord de fil ou d’impression, mais pas son emplacement sur l’ensemble. La couverture est donc une correspondance question-image, non un nombre d’images. Si deux vues semblent se contredire, notez lumière, distance et orientation avant de conclure à une différence du produit."],
      ["Séparer observation, comparaison et inférence", "Utilisez trois colonnes. « Observé » contient uniquement ce que l’image étaye : une marque apparaît près d’un bord, deux côtés semblent inégaux sous cet angle, l’étiquette affiche une valeur ou un composant n’est pas visible dans la série fournie. « Comparé » enregistre la référence, par exemple l’image de l’option choisie, une mesure exigée ou le côté opposé de la même unité. « Inféré » contient les conclusions plausibles mais non prouvées : composition, authenticité, construction interne, imperméabilité, état de batterie, durabilité, odeur ou coupe réelle. Ne déplacez jamais une inférence vers l’observation parce que la description vendeur la répète. Les photos montrent une surface et une partie de la géométrie mesurable, mais pas beaucoup de propriétés cachées ou fonctionnelles. Les mots précis comptent. « La pièce manque » dépasse la preuve si elle peut être hors cadre. « La pièce n’est pas visible sur les images fournies » est exact et indique précisément quelle clarification peut fermer la lacune."],
      ["Classer les lacunes selon leur effet sur la décision", "Toute vue manquante ne mérite pas une nouvelle demande. Attribuez un impact à chaque lacune. Critique signifie que la réponse peut changer l’identité, l’usage, l’intégralité ou la décision d’accepter ou retourner : taille illisible, bord fragile caché, pièce nécessaire non montrée ou mesure décisive absente. Important signifie que la réponse influence la préférence ou la confiance sans forcément rendre l’article inutilisable, telle une impression alignée dans votre tolérance personnelle. Mineur signifie que la lacune changera peu la décision, comme un coin d’emballage quand le produit est entièrement visible. Ajoutez une confiance haute, moyenne ou faible selon la qualité de preuve, pas l’optimisme. Une confiance haute exige une vue directe lisible. Moyenne peut reposer sur une vue partielle mais cohérente. Faible signifie que flou, obstruction, perspective ou absence d’échelle empêchent une conclusion stable. Ce classement garde le contrôle proportionné et évite de demander de nombreuses photos génériques qui ajoutent des données sans répondre à la seule question déterminante."],
      ["Rédiger une demande qui ferme une seule lacune", "Une demande utile nomme l’article, la zone précise, l’orientation et le format de preuve. Au lieu de « plus de photos », écrivez : « Photographiez toute l’étiquette de taille de face afin que chaque ligne soit lisible », ou « Posez le vêtement à plat, placez une règle de la couture gauche à la couture droite de poitrine et montrez les deux extrémités ». Pour une marque, demandez une vue large qui la situe et une vue proche de sa surface. Pour la quantité, demandez si possible toutes les pièces dans un cadre. Ne demandez pas un test visuel pour ce qu’une photo ne prouve pas. Si la fonction électronique, la matière interne ou l’authenticité est la vraie question, reconnaissez que les images peuvent ne pas la résoudre. Reliez chaque demande à une seule lacune et datez-la. Quand une nouvelle preuve arrive, ajoutez-la à la même ligne au lieu de recommencer. Vous obtenez une chaîne vérifiable : question initiale, première preuve, lacune, demande précise et conclusion mise à jour."],
      ["Utiliser une matrice accepter, suspendre ou clarifier", "Choisissez « accepter » seulement si l’identité visible et toutes les exigences critiques sont soutenues au niveau de confiance défini d’avance. Accepter ne signifie pas que l’article est garanti authentique, durable, fonctionnel ou parfait ; cela signifie que la preuve visuelle disponible atteint votre seuil. Choisissez « clarifier » lorsqu’une vue ou mesure manquante et limitée peut réellement changer la décision et être demandée précisément. Choisissez « suspendre » si les preuves se contredisent, si une question critique échappe à la preuve visuelle ou si plusieurs lacunes empêchent une décision confiante. Si l’interface présente une action urgente, vérifiez la politique actuelle au lieu de reprendre un ancien délai. La matrice doit aussi noter les imperfections acceptables. Un fil lâche, une petite bosse d’emballage ou une légère variation photographique de couleur peuvent entrer dans la tolérance d’un acheteur et pas d’un autre. Fixez ces limites avant l’examen afin qu’un paiement déjà effectué ne réduise pas discrètement le standard. Une courte raison près du statut final vaut mieux qu’un simple succès ou échec."],
      ["Archiver la carte comme relevé de décision compact", "Conservez ensemble référence de commande, texte d’option, date, identifiants d’image, exigences critiques, lignes de couverture, demande de clarification et motif final. Évitez adresses privées, paiements ou données de compte inutiles dans un document partageable. Si vous comparez ensuite une autre unité, créez une nouvelle carte au lieu de supposer que la preuve du premier article vaut pour un autre lot. L’archive reste utile lorsque l’article est accepté : elle montre les caractéristiques réellement visibles et celles qui demeurent inconnues. Elle garde aussi un futur avis honnête, car vous pouvez séparer la fiche vendeur, l’unité d’entrepôt exacte et vos propres inférences. Rouvrez le relevé avant la soumission du colis pour confirmer que chaque article accepté est bien celui à inclure. La méthode reste volontairement modeste. Elle ne transforme pas les photos en certitude. Elle transforme une galerie dispersée en décision traçable en nommant la question, reliant chaque réponse à une image, exposant l’incertitude et ne demandant que les preuves capables de changer le résultat."],
    ],
  },
  it: {
    meta: ["Metodo delle lacune probatorie", "Verificato il 07/09/2026", "Indipendente"],
    sourceNote: "Base di ricerca: homepage, guida iniziale e indicazioni pubbliche sull’ispezione nelle pagine prodotto USFans, verificate il 07/09/2026. Le pagine ufficiali descrivono ispezione e foto in magazzino; la copertura utile di un articolo va comunque valutata sulle immagini realmente fornite.",
    visual: ["Mappa delle lacune probatorie", [["Identità", "articolo · opzione · quantità · etichette visibili"], ["Copertura", "fronte · retro · lati · dettaglio · scala"], ["Limiti", "nascosto · sfocato · non testato · non misurabile"], ["Decisione", "accetta · sospendi · chiarisci"]]],
    related: [["Apri la guida alle foto di magazzino", "/qc"], ["Leggi il metodo QC per categoria", "/articles/how-to-read-usfans-qc-photos"]],
    sections: [
      ["Inizia da una domanda decisionale, non dalla caccia ai difetti", "Una mappa delle lacune nelle prove di magazzino è un breve registro di ciò a cui rispondono le immagini, di ciò che resta irrisolto e della possibilità che l’informazione mancante cambi la decisione. Scrivi prima una domanda: «Questa unità corrisponde all’opzione ordinata e ai miei requisiti visibili irrinunciabili?». È più precisa e utile di «È buona?». Evita anche che un primo piano attraente domini l’esame mentre identità, quantità o scala restano incerte. L’attuale flusso pubblico di USFans indica che gli articoli vengono ispezionati e fotografati dopo l’arrivo in magazzino. Questo stabilisce una fase di controllo, ma non implica che per ogni prodotto compaiano tutti gli angoli, le misure o le funzioni possibili. Costruisci la mappa solo con le prove disponibili. Elenca ogni vista, collegala a una domanda e marca la risposta come osservata, parzialmente osservata o non osservata. Non giudicare la finitura finché l’identità non è ragionevolmente allineata all’ordine. Se può essere arrivata l’opzione sbagliata, una revisione cosmetica dettagliata di quell’unità non risolve il primo problema."],
      ["Blocca l’identità prima di interpretare la condizione", "Crea una riga identità con nome dell’ordine, colore, taglia, stile, quantità e testo dell’opzione salvato prima del pagamento. Cerca poi i marcatori visibili corrispondenti: etichetta taglia, codice colore, testo modello, etichetta dell’imballo, unità ripetute o pezzi inclusi. Un marcatore prova soltanto ciò che mostra. Una foto dell’etichetta può sostenere che vi è scritta una taglia; non dimostra misure reali o vestibilità. Un codice sulla scatola può sostenere l’identità del modello confezionato, ma non conferma ogni componente interno. Se il testo è tagliato, tradotto ambiguamente o illeggibile, segnalo irrisolto invece di completarlo a memoria. Per i set conta tutti i pezzi visibili e annota quelli attesi ma mai mostrati. Fra varianti simili individua prima il tratto distintivo. Questa sequenza evita di assumere che il prodotto sia la versione ordinata solo perché mostra vari dettagli piacevoli. La fiducia nell’identità nasce da marcatori decisivi coerenti, non dal numero totale di fotografie."],
      ["Inventaria la copertura per domanda e angolo", "Crea una riga per ogni domanda importante: forma generale, fronte e retro, entrambi i lati, etichetta, chiusura, stampa, ferramenta, pezzi inclusi, punto di misura o area danneggiata. Registra l’immagine migliore e classificala diretta, parziale o inutilizzabile. Una vista diretta mostra l’area con scala e angolo utili. Una parziale può mostrare un solo lato, nascondere un bordo o mancare di riferimento dimensionale. Una vista inutilizzabile può essere sfocata, molto compressa, bloccata dall’imballo o distorta dalla prospettiva. Non considerare cinque foto come cinque risposte: molte possono ripetere lo stesso angolo mentre una superficie critica resta invisibile. Un’immagine ampia può rispondere sulla forma, non sulla cucitura fine. Un primo piano mostra bordi di filo o stampa, non il loro posizionamento sull’intero articolo. La copertura è quindi corrispondenza domanda-immagine, non quantità. Se due foto sembrano contraddirsi, annota luce, distanza e orientamento prima di concludere che il prodotto sia diverso."],
      ["Separa osservazione, confronto e inferenza", "Usa tre colonne. «Osservato» contiene solo ciò che l’immagine sostiene: un segno appare vicino a un bordo, due lati sembrano diversi da quell’angolo, l’etichetta mostra un valore o un componente non è visibile nella serie fornita. «Confrontato» registra il riferimento, come l’immagine dell’opzione scelta, una misura richiesta o il lato opposto della stessa unità. «Inferito» contiene conclusioni plausibili ma non provate: composizione, autenticità, costruzione interna, impermeabilità, stato della batteria, durata, odore o vestibilità reale. Non spostare un’inferenza fra le osservazioni solo perché la descrizione del venditore la ripete. Le foto mostrano superfici e parte della geometria misurabile, non molte proprietà nascoste o funzionali. Le parole precise contano. «Il pezzo manca» supera la prova se può trovarsi fuori inquadratura. «Il pezzo non è visibile nelle immagini fornite» è accurato e indica quale chiarimento potrebbe chiudere la lacuna."],
      ["Ordina le lacune per impatto sulla decisione", "Non ogni vista mancante merita una nuova richiesta. Assegna a ogni lacuna un livello di impatto. Critico significa che la risposta può cambiare identità, utilità, completezza o decisione di accettare o rendere: taglia illeggibile, bordo fragile nascosto, parte necessaria non mostrata o misura decisiva assente. Importante significa che influenza preferenza o fiducia senza rendere necessariamente inutilizzabile l’articolo, come l’allineamento di una stampa entro la tua tolleranza. Minore significa che difficilmente cambia la scelta, per esempio un angolo dell’imballo con prodotto interamente visibile. Aggiungi fiducia alta, media o bassa secondo la qualità della prova, non l’ottimismo. Alta richiede una vista diretta e leggibile. Media può usare una vista parziale ma coerente. Bassa significa che sfocatura, ostacolo, prospettiva o assenza di scala impediscono una conclusione stabile. Questa priorità mantiene proporzionato l’esame ed evita molte richieste generiche che aggiungono dati senza rispondere alla domanda determinante."],
      ["Scrivi una richiesta che chiuda una sola lacuna", "Una richiesta utile nomina articolo, area esatta, orientamento e formato della prova. Invece di «altre foto», scrivi: «Fotografare l’intera etichetta della taglia frontalmente affinché ogni riga sia leggibile», oppure «Stendere il capo, porre un righello dalla cucitura sinistra del petto alla destra e mostrare entrambe le estremità». Per un segno chiedi una foto larga che lo localizzi e una ravvicinata della superficie. Per la quantità chiedi tutti i pezzi nella stessa inquadratura quando pratico. Non chiedere una prova visiva di ciò che una foto non può dimostrare. Se la vera domanda riguarda funzione elettronica, materiale interno o autenticità, riconosci che le immagini potrebbero non chiuderla. Collega ogni richiesta a una sola lacuna e registra quando è stata fatta. Quando arriva nuova prova, aggiungila alla stessa riga invece di ricominciare. Otterrai una catena verificabile: domanda iniziale, prova, lacuna, richiesta precisa e conclusione aggiornata."],
      ["Usa una matrice accetta, sospendi o chiarisci", "Scegli «accetta» solo quando identità visibile e requisiti critici sono sostenuti al livello di fiducia fissato in anticipo. Accettare non significa prodotto garantito autentico, durevole, funzionante o perfetto; significa che la prova visiva disponibile raggiunge la tua soglia. Scegli «chiarisci» quando una vista o misura mancante circoscritta può davvero cambiare la decisione e si può richiedere con precisione. Scegli «sospendi» quando le prove sono contraddittorie, una domanda critica è fuori dalla prova visiva o varie lacune impediscono una decisione affidabile. Se l’interfaccia mostra un’azione a scadenza, verifica politica e interfaccia correnti invece di importare un vecchio termine. La matrice deve anche registrare imperfezioni accettabili. Un filo lento, una piccola ammaccatura della confezione o una lieve variazione fotografica del colore possono rientrare nella tolleranza di una persona e non di un’altra. Definisci i limiti prima dell’ispezione affinché il pagamento già effettuato non abbassi silenziosamente lo standard. Un motivo breve accanto allo stato finale è più utile di un semplice superato o fallito."],
      ["Archivia la mappa come registro decisionale compatto", "Conserva insieme riferimento d’ordine, testo opzione, data, identificatori delle immagini, requisiti critici, righe di copertura, richiesta di chiarimento e motivo finale. Evita indirizzi privati, pagamenti o dati di account non pertinenti in un registro condivisibile. Se confronti un’altra unità, crea una nuova mappa invece di presumere che la prova del primo articolo valga per un lotto diverso. L’archivio serve anche se accetti: mostra quali caratteristiche erano visibili e quali restavano ignote. Mantiene onesta anche una futura recensione, perché separa la scheda venditore, l’esatta unità di magazzino e le conclusioni personali. Riapri il registro prima dell’invio del pacco per confermare che ogni articolo accettato sia quello da includere. Il metodo è volutamente modesto. Non trasforma fotografie in certezza. Trasforma una galleria libera in una decisione tracciabile, nominando la domanda, associando ogni risposta a un’immagine, esponendo l’incertezza e chiedendo soltanto prove capaci di cambiare l’esito."],
    ],
  },
};

export function getUveArticle(language) {
  const activeLanguage = localized[language] ? language : "en";
  const entry = localized[activeLanguage];
  return {
    ...uveArticleBlueprint,
    title: uveArticleBlueprint.title[activeLanguage],
    dek: uveArticleBlueprint.dek[activeLanguage],
    sections: entry.sections,
    sourceNote: entry.sourceNote,
    visual: entry.visual,
    related: entry.related,
    articleMeta: entry.meta,
    datePublished: "2026-09-07",
    dateModified: "2026-09-07",
  };
}
