export const uveMeasurementArticleBlueprint = {
  slug: "usfans-warehouse-measurement-photo-evidence",
  title: {
    en: "USFans Measurement Photos: Read Reference Points, Scale and Uncertainty",
    de: "USFans-Messfotos: Bezugspunkte, Maßstab und Unsicherheit lesen",
    es: "Fotos de medición USFans: puntos de referencia, escala e incertidumbre",
    fr: "Photos de mesure USFans : repères, échelle et incertitude",
    it: "Foto di misurazione USFans: riferimenti, scala e incertezza",
  },
  dek: {
    en: "Turn a warehouse ruler photo into bounded evidence by checking endpoints, item position, camera angle, readable scale and the uncertainty that remains.",
    de: "Mache aus einem Lagerfoto mit Lineal einen begrenzten Beleg, indem du Endpunkte, Artikellage, Kamerawinkel, lesbare Skala und verbleibende Unsicherheit prüfst.",
    es: "Convierte una foto de almacén con regla en evidencia limitada comprobando extremos, posición, ángulo, escala legible e incertidumbre restante.",
    fr: "Transformez une photo d’entrepôt avec règle en preuve limitée en vérifiant extrémités, position, angle, échelle lisible et incertitude restante.",
    it: "Trasforma una foto di magazzino con righello in una prova limitata controllando estremi, posizione, angolo, scala leggibile e incertezza residua.",
  },
  topics: [],
};

const localized = {
  en: {
    meta: ["Measurement evidence", "Checked 13 Sep 2026", "Independent"],
    sourceNote: "Research basis: the current USFans Beginner’s Guide and a current public product page were checked 13 Sep 2026. The guide says arrived items are inspected and photographed; the product page currently advertises 3–7 HD inspection photos and displays selectable size and specification fields. The public pages do not promise a fixed measurement-photo accuracy or tolerance, so this note treats every reading as bounded visual evidence.",
    visual: ["Measurement-photo evidence ladder", [["Defined", "same named endpoints"], ["Visible", "item, ruler and marks in one frame"], ["Readable", "scale viewed close to square"], ["Bounded", "reading plus stated uncertainty"]]],
    related: [["Open the general warehouse-photo guide", "/qc"], ["Check which photo angles are covered", "/articles/usfans-warehouse-photo-angle-map"], ["Separate size-tag identity from fit", "/articles/usfans-warehouse-size-tag-evidence"]],
    sections: [
      ["Treat the photo as a measurement claim, not a number", `A warehouse photo with a ruler can support a useful claim, but only after you can answer five questions: what dimension was measured, where both endpoints sit, how the item was positioned, whether the scale is readable and how much uncertainty remains. Start by writing the claim in full. “Chest width appears about 56 cm from underarm seam to underarm seam while the garment is laid flat” is auditable; “size 56” is not. USFans currently says that arrived items are inspected and photographed, while a public product page advertises 3–7 HD inspection photos. Neither statement guarantees that a supplied image uses the endpoints you intended or that a ruler photograph has laboratory precision. Count the image as evidence only for the dimension actually shown. A tag, listing chart and ruler view are separate records: the tag names the variant, the chart states a seller specification, and the photo may show the received unit. Agreement among them raises confidence, but one cannot silently replace another.`],
      ["Define both endpoints before reading the ruler", `Most measurement disagreements begin before anyone reads a mark. Name the start and finish using visible construction features. For a garment width, specify whether the line runs between underarm seams, outer edges or another point. For body length, state the shoulder point and lower hem, and say whether a collar is excluded. For trousers, distinguish a straight waistband width from a doubled circumference estimate; for shoes, separate removable insole length, outsole length and internal fit. Record the convention beside the value. Then check whether the ruler begins at the chosen first endpoint. Some rulers have blank space before zero, and a metal hook can sit outside the scale. Confirm that the second endpoint is visible rather than hidden by a hand, fold or crop. If an endpoint lands between marks, preserve that fact. Do not slide it mentally toward a seller-chart value. When the requested and photographed conventions differ, mark the result non-comparable and ask for the named line again instead of calculating a false discrepancy.`],
      ["Check the item’s plane, tension and natural boundaries", `A number can be sharply photographed while the object is poorly prepared. For soft garments, note whether the fabric lies flat, whether seams are aligned and whether wrinkles, elastic or stretching change the span. A waistband measured under tension is not comparable with one resting naturally. A sleeve pulled diagonally can look longer; a curved hem can yield different lengths at the centre and edge. For bags and structured items, decide whether dimensions refer to the empty exterior, a filled shape, a rigid base or a flexible opening. For footwear, a curved sole photographed beside a straight ruler does not automatically equal internal usable length. Never infer circumference by doubling a flat width unless that convention is explicitly the one you chose and the construction makes it meaningful. The image should show enough of the object to verify preparation, not only a close crop of two digits. When preparation is uncertain, state the observed setup and lower confidence rather than correcting the result by intuition.`],
      ["Make sure the ruler supplies a real, readable scale", `A nearby ruler is not automatically a scale for the object. It should lie in the same plane as the measured line, remain straight, show the unit and include enough consecutive marks to confirm orientation. Check whether the image uses centimetres, millimetres or inches; do not guess from familiar-looking spacing. Watch for a tape that curls upward, bows around a product or disappears beneath fabric. A rigid ruler can bridge a curve and measure a chord rather than the surface path. Image resolution matters too. Digital zoom enlarges pixels but does not recover an unreadable mark. Prefer a frame that shows the full line plus a closer view of the final reading, while keeping both views traceable to the same setup. If only the end value is visible, the starting offset may be unknowable. If only a wide view exists, the smallest marks may merge. Classify the scale as verified, partly readable or unusable and report only the precision the file can actually support.`],
      ["Control perspective and parallax before comparing values", `The camera should look as close to perpendicular to the ruler and item plane as practical. At an oblique angle, the nearer end appears larger and spacing compresses toward the far end. Parallax occurs when the ruler sits above or below the boundary being read: the endpoint seems to meet a different mark depending on camera position. You can screen for these effects without pretending to calibrate the image. Look for converging ruler edges, unequal mark spacing, a visible height gap between tape and fabric, or one endpoint much closer to the lens. Compare repeated views only when orientation, endpoints and preparation match. Do not average two numbers produced by different conventions or perspectives. If one square, unobstructed image supports 56 cm and a slanted view seems to show 55 cm, keep the stronger observation and record why the second is weaker. When both are oblique, the evidence remains unresolved; pixels should not be converted into centimetres unless a reliable same-plane reference and imaging method exist.`],
      ["Report an interval that matches the photograph", `A ruler photo rarely justifies more precision than its visible marks, endpoint clarity and setup allow. Read the smallest clearly distinguishable interval, then include uncertainty from placement. If the endpoint appears between 55.5 and 56 cm because the hem is soft and the frame is slightly angled, report “approximately 55.5–56 cm in this setup,” not 55.73 cm. Separate reading uncertainty from product variation. Reading uncertainty belongs to the image; manufacturing variation, fabric relaxation and seller tolerances are different questions that the photo alone cannot quantify. Do not invent a universal plus-or-minus allowance or assume a platform guarantee. For a comparison with a listing chart, preserve both values and their conventions: seller chart 56 cm, received-item photo approximately 55.5–56 cm, both measured flat at named points. A small apparent gap inside the image’s uncertainty is not automatically a mismatch. A larger gap may justify clarification, but the current order interface and applicable after-sales terms determine available action.`],
      ["Use category-specific lines without mixing their meanings", `Build a short field list before requesting evidence. For tops, common lines include pit-to-pit width, shoulder seam to shoulder seam, back length and sleeve length, but each needs named endpoints. For trousers, record waistband state, rise, inseam and leg opening independently. For footwear, identify whether the request concerns the removable insole, outsole or another visible component; none alone guarantees comfort or real-world fit. For bags, name width, height and depth at defined exterior points and note whether the bag is empty or shaped. Accessories may need usable strap range, hole spacing or internal opening rather than total length. Place only like-for-like values in one comparison row. A listing’s body recommendation must not be compared directly with a finished garment width, and a size tag must not be treated as a centimetre reading. If the relevant boundary cannot be seen, mark the line missing. One precise requested line is more useful than several unlabeled ruler photographs.`],
      ["Finish with a traceable decision and an honest boundary", `Archive the order identifier, saved option, listing-chart date, image identifier, named dimension, endpoints, unit, setup, visible reading, uncertainty range and review date. Keep private addresses, payments and account details out of any shareable record. Use three outcomes. Accept the measurement evidence when the correct unit is shown, endpoints and preparation match the chosen convention, scale and angle are usable, and the range answers the decision. Hold when the photo is too cropped, slanted, stretched or unreadable. Clarify with one reproducible request when a new image can close the gap: “lay the sweatshirt flat without stretching; place a centimetre tape from the left underarm seam to the right underarm seam; show zero, both seams and the final mark in one square frame.” End the record with what remains unproven. A sound ruler image can support an approximate received-item dimension. It cannot prove personal fit, hidden construction, material composition, authenticity, durability or measurement accuracy beyond what the photograph shows.`],
    ],
  },
  de: {
    meta: ["Messbeleg", "Geprüft am 13.09.2026", "Unabhängig"],
    sourceNote: "Recherchegrundlage: Der aktuelle USFans-Einsteigerleitfaden und eine aktuelle öffentliche Produktseite wurden am 13.09.2026 geprüft. Laut Leitfaden werden eingetroffene Artikel kontrolliert und fotografiert; die Produktseite nennt derzeit 3–7 HD-Prüffotos und zeigt wählbare Größen sowie Spezifikationsfelder. Die öffentlichen Seiten versprechen keine feste Genauigkeit oder Toleranz für Messfotos, daher behandelt dieser Hinweis jeden Wert als begrenzten visuellen Beleg.",
    visual: ["Belegleiter für Messfotos", [["Definiert", "dieselben benannten Endpunkte"], ["Sichtbar", "Artikel, Lineal und Marken in einem Bild"], ["Lesbar", "Skala möglichst rechtwinklig betrachtet"], ["Begrenzt", "Wert plus genannte Unsicherheit"]]],
    related: [["Allgemeinen Leitfaden für Lagerfotos öffnen", "/qc"], ["Abdeckung der Fotowinkel prüfen", "/articles/usfans-warehouse-photo-angle-map"], ["Größenetikett von Passform trennen", "/articles/usfans-warehouse-size-tag-evidence"]],
    sections: [
      ["Das Foto als Messbehauptung behandeln, nicht als Zahl", `Ein Lagerfoto mit Lineal kann eine nützliche Aussage stützen, aber erst nach fünf Fragen: Welche Dimension wurde gemessen, wo liegen beide Endpunkte, wie lag der Artikel, ist die Skala lesbar und welche Unsicherheit bleibt? Schreibe die Aussage vollständig: „Die Brustweite erscheint bei flach liegendem Kleidungsstück von Achselnaht zu Achselnaht etwa 56 cm.“ „Größe 56“ ist nicht prüfbar. USFans beschreibt derzeit Kontrolle und Fotos nach der Lagerankunft; eine öffentliche Produktseite nennt 3–7 HD-Prüffotos. Beides garantiert weder deine gewünschten Endpunkte noch Laborpräzision. Nutze das Bild nur für die tatsächlich gezeigte Dimension. Etikett, Angebotstabelle und Linealfoto sind getrennte Datensätze: Das Etikett benennt die Variante, die Tabelle eine Verkäuferangabe, das Foto kann die eingetroffene Einheit zeigen. Übereinstimmung erhöht Sicherheit, doch kein Datensatz ersetzt stillschweigend einen anderen.`],
      ["Beide Endpunkte vor dem Ablesen festlegen", `Die meisten Abweichungen entstehen vor dem Ablesen. Benenne Start und Ende mit sichtbaren Konstruktionsmerkmalen. Bei Oberteilen muss klar sein, ob zwischen Achselnähten, Außenkanten oder anderen Punkten gemessen wird. Für die Rückenlänge nenne Schulterpunkt und Saum und ob der Kragen ausgeschlossen ist. Bei Hosen unterscheide gerade Bundbreite von einer verdoppelten Umfangsschätzung; bei Schuhen herausnehmbare Innensohle, Außensohle und Innenpassform. Notiere die Konvention neben dem Wert. Prüfe, ob das Lineal am ersten Punkt wirklich bei null beginnt: Vor der Null kann Leerraum liegen, ein Metallhaken außerhalb der Skala. Auch der zweite Punkt muss sichtbar sein, nicht von Hand, Falte oder Bildrand verdeckt. Liegt er zwischen Marken, bleibt das so. Schiebe ihn nicht gedanklich zum Tabellenwert. Weichen angeforderte und fotografierte Konvention ab, ist das Ergebnis nicht vergleichbar; fordere dieselbe benannte Linie erneut an.`],
      ["Ebene, Spannung und natürliche Grenzen prüfen", `Eine Zahl kann scharf sein, obwohl das Objekt schlecht vorbereitet ist. Bei weicher Kleidung prüfe flache Lage, ausgerichtete Nähte sowie Falten, Elastik oder Zug. Ein gespannter Bund ist nicht mit einem entspannten vergleichbar. Ein diagonal gezogenes Ärmelteil wirkt länger; ein gebogener Saum liefert in Mitte und Rand andere Längen. Bei Taschen und festen Artikeln muss klar sein, ob leere Außenmaße, gefüllte Form, fester Boden oder flexible Öffnung gemeint sind. Eine gebogene Sohle neben einem geraden Lineal ist nicht automatisch nutzbare Innenlänge. Verdopple eine Flachbreite nur dann zu einem Umfang, wenn genau diese Konvention gewählt wurde und die Konstruktion es sinnvoll macht. Das Foto muss genug Artikel zeigen, um die Vorbereitung zu prüfen, nicht nur zwei Ziffern. Ist die Lage unklar, beschreibe sie und senke die Sicherheit, statt den Wert nach Gefühl zu korrigieren.`],
      ["Sicherstellen, dass das Lineal einen echten lesbaren Maßstab liefert", `Ein Lineal in der Nähe ist nicht automatisch der Maßstab des Objekts. Es muss möglichst in derselben Ebene liegen, gerade bleiben, die Einheit zeigen und genug aufeinanderfolgende Marken enthalten. Prüfe Zentimeter, Millimeter oder Zoll; rate nicht anhand vertrauter Abstände. Ein Maßband kann sich aufwölben, um ein Produkt biegen oder unter Stoff verschwinden. Ein starres Lineal überbrückt eine Kurve und misst dann eine Sehne, nicht den Oberflächenweg. Auch die Auflösung begrenzt den Beleg: Digitaler Zoom vergrößert Pixel, macht aber keine unlesbare Marke lesbar. Ideal sind eine Gesamtansicht der ganzen Linie und eine nähere Endablesung, beide eindeutig derselben Anordnung zugeordnet. Ist nur der Endwert sichtbar, bleibt ein Startversatz unbekannt; bei nur weiter Ansicht verschmelzen kleine Marken. Klassifiziere die Skala als geprüft, teilweise lesbar oder unbrauchbar und melde nur die vom Bild gestützte Genauigkeit.`],
      ["Perspektive und Parallaxe vor dem Vergleich kontrollieren", `Die Kamera sollte möglichst senkrecht auf Lineal- und Artikelebene blicken. Bei schräger Sicht wirkt das nahe Ende größer, die Abstände zum fernen Ende werden gestaucht. Parallaxe entsteht, wenn Lineal und abgelesene Kante auf unterschiedlicher Höhe liegen: Je nach Kameraposition trifft die Kante scheinbar eine andere Marke. Prüfe ohne Scheinkalibrierung auf zusammenlaufende Linealkanten, ungleiche Markenabstände, einen sichtbaren Höhenversatz oder ein deutlich näheres Ende. Vergleiche Wiederholungen nur bei gleicher Orientierung, gleichen Endpunkten und gleicher Vorbereitung. Mittlere keine Zahlen aus verschiedenen Konventionen oder Perspektiven. Zeigt ein gerades freies Bild 56 cm und ein schräges scheinbar 55 cm, behalte die stärkere Beobachtung und begründe die schwächere. Sind beide schräg, bleibt die Frage offen. Pixel werden nicht in Zentimeter umgerechnet, sofern kein zuverlässiger Bezug in derselben Ebene und keine passende Bildmethode vorhanden sind.`],
      ["Ein zum Foto passendes Intervall angeben", `Ein Linealfoto rechtfertigt selten mehr Genauigkeit als sichtbare Marken, klare Endpunkte und Aufbau erlauben. Lies das kleinste sicher unterscheidbare Intervall und ergänze die Platzierungsunsicherheit. Liegt ein weicher Saum bei leicht schrägem Bild zwischen 55,5 und 56 cm, schreibe „in dieser Anordnung ungefähr 55,5–56 cm“, nicht 55,73 cm. Trenne Ableseunsicherheit von Produktstreuung. Erstere gehört zum Bild; Fertigungsstreuung, Stoffentspannung und Verkäufer-Toleranzen sind andere Fragen, die das Foto nicht beziffert. Erfinde kein allgemeines Plus-minus und keine Plattformgarantie. Für den Tabellenvergleich bleiben beide Werte samt Konvention erhalten: Verkäufer 56 cm, Foto der Einheit ungefähr 55,5–56 cm, beide flach an benannten Punkten. Eine kleine Differenz innerhalb der Bildunsicherheit ist nicht automatisch ein Mangel. Eine größere kann Klärung rechtfertigen; mögliche Schritte richten sich nach aktuellem Konto und geltenden Bedingungen.`],
      ["Kategoriespezifische Linien nutzen, ohne Bedeutungen zu mischen", `Lege vor der Anfrage eine kurze Feldliste an. Bei Oberteilen können Achselbreite, Schulterbreite, Rückenlänge und Ärmellänge sinnvoll sein, jeweils mit Endpunkten. Bei Hosen werden Bundzustand, Leibhöhe, Innenbein und Beinöffnung getrennt erfasst. Bei Schuhen muss klar sein, ob Innensohle, Außensohle oder ein anderes sichtbares Teil gemeint ist; keines garantiert Komfort oder reale Passform. Bei Taschen benenne Breite, Höhe und Tiefe an festgelegten Außenpunkten und ob sie leer oder geformt ist. Zubehör braucht eventuell nutzbaren Riemenbereich, Lochabstand oder Innenöffnung statt Gesamtlänge. Nur Gleiches gehört in eine Vergleichszeile. Eine Körperempfehlung aus dem Angebot ist keine fertige Kleidungsbreite, ein Größenetikett kein Zentimeterwert. Ist die Grenze nicht sichtbar, markiere die Linie fehlend. Eine präzise angeforderte Linie ist wertvoller als mehrere unbeschriftete Linealfotos.`],
      ["Mit nachvollziehbarer Entscheidung und ehrlicher Grenze abschließen", `Archiviere Bestellkennung, gespeicherte Option, Datum der Angebotstabelle, Bildkennung, Dimension, Endpunkte, Einheit, Aufbau, sichtbaren Wert, Unsicherheitsbereich und Prüftag. Entferne Adressen, Zahlungen und Kontodaten aus teilbaren Kopien. Nutze drei Ergebnisse: Akzeptieren, wenn Einheit, Endpunkte, Vorbereitung, Skala und Winkel zur gewählten Konvention passen und der Bereich die Frage beantwortet. Halten bei Beschnitt, Schräglage, Zug oder Unlesbarkeit. Klären mit einer reproduzierbaren Bitte, wenn ein neues Bild die Lücke schließen kann: „Sweatshirt flach ohne Zug; Zentimeterband von linker zu rechter Achselnaht; null, beide Nähte und Endmarke in einem geraden Bild zeigen.“ Beende den Eintrag mit dem Unbewiesenen. Ein solides Linealfoto kann ein ungefähres Maß der eingetroffenen Einheit stützen. Es beweist weder persönliche Passform noch verborgene Konstruktion, Material, Echtheit, Haltbarkeit oder höhere Genauigkeit als sichtbar.`],
    ],
  },
  es: {
    meta: ["Evidencia de medición", "Comprobado 13 sep. 2026", "Independiente"],
    sourceNote: "Base de investigación: se comprobaron el 13 de septiembre de 2026 la guía actual para principiantes de USFans y una página pública actual de producto. La guía indica que los artículos recibidos se inspeccionan y fotografían; la página anuncia actualmente 3–7 fotos HD de inspección y muestra tallas y especificaciones seleccionables. Las páginas públicas no prometen precisión ni tolerancia fija para fotos de medición, por lo que cada lectura se trata como evidencia visual limitada.",
    visual: ["Escala de evidencia de una foto de medición", [["Definida", "mismos extremos nombrados"], ["Visible", "artículo, regla y marcas en un encuadre"], ["Legible", "escala vista casi perpendicular"], ["Limitada", "lectura más incertidumbre declarada"]]],
    related: [["Abrir la guía general de fotos de almacén", "/qc"], ["Comprobar ángulos cubiertos", "/articles/usfans-warehouse-photo-angle-map"], ["Separar etiqueta de talla y ajuste", "/articles/usfans-warehouse-size-tag-evidence"]],
    sections: [
      ["Trata la foto como una afirmación de medida, no como un número", `Una foto de almacén con regla puede sostener una afirmación útil solo después de responder cinco preguntas: qué dimensión se midió, dónde están ambos extremos, cómo se colocó el artículo, si la escala se lee y qué incertidumbre queda. Escribe la afirmación completa: «el ancho de pecho parece de unos 56 cm entre costuras de axila con la prenda extendida». «Talla 56» no es auditable. USFans dice actualmente que los artículos llegados se inspeccionan y fotografían, y una página pública anuncia 3–7 fotos HD de inspección. Ninguna frase garantiza tus extremos previstos ni precisión de laboratorio. Usa la imagen solo para la dimensión mostrada. Etiqueta, tabla del anuncio y foto con regla son registros distintos: la etiqueta nombra la variante, la tabla recoge una especificación del vendedor y la foto puede mostrar la unidad recibida. Su concordancia mejora la confianza, pero uno no sustituye silenciosamente a otro.`],
      ["Define ambos extremos antes de leer la regla", `La mayoría de desacuerdos comienza antes de leer una marca. Nombra inicio y final con rasgos visibles de construcción. En un ancho de prenda, aclara si va entre costuras de axila, bordes exteriores u otros puntos. Para el largo, indica hombro y bajo y si excluye el cuello. En pantalones, separa ancho recto de cintura de una circunferencia estimada al duplicarlo; en calzado, distingue plantilla extraíble, suela exterior y ajuste interno. Guarda la convención junto al valor. Comprueba que la regla comienza en el primer extremo: puede haber espacio antes del cero o un gancho fuera de escala. El segundo extremo debe verse, no quedar tapado por mano, pliegue o recorte. Si cae entre marcas, conserva ese hecho; no lo acerques mentalmente a la tabla. Cuando la convención solicitada y la fotografiada difieren, marca el resultado como no comparable y pide de nuevo la línea nombrada.`],
      ["Comprueba plano, tensión y límites naturales del artículo", `Un número puede verse nítido aunque el objeto esté mal preparado. En prendas blandas, observa si están planas, si las costuras se alinean y si arrugas, elástico o estiramiento cambian el tramo. Una cintura tensa no se compara con otra relajada. Una manga tirada en diagonal parece más larga; un bajo curvo da valores distintos en centro y borde. En bolsos y artículos estructurados, define si se miden exteriores vacíos, forma rellena, base rígida o abertura flexible. Una suela curva junto a una regla recta no equivale automáticamente a longitud interior útil. No deduzcas circunferencia duplicando un ancho plano salvo que esa sea la convención elegida y la construcción lo permita. La foto debe enseñar suficiente objeto para comprobar la preparación, no solo dos cifras. Si la posición es incierta, descríbela y reduce la confianza en vez de corregir el resultado por intuición.`],
      ["Asegura que la regla ofrece una escala real y legible", `Una regla cercana no siempre escala el objeto. Debe estar en el mismo plano, mantenerse recta, mostrar la unidad y suficientes marcas consecutivas para verificar orientación. Comprueba centímetros, milímetros o pulgadas; no lo adivines por el espaciado. Vigila una cinta arqueada, enrollada alrededor del producto o escondida bajo tela. Una regla rígida que salva una curva mide una cuerda, no el recorrido superficial. La resolución también limita: el zoom digital agranda píxeles, no recupera una marca ilegible. Conviene una vista de toda la línea y otra cercana del valor final, ambas ligadas a la misma preparación. Si solo aparece el final, puede desconocerse el desplazamiento inicial; si solo hay vista amplia, se mezclan marcas pequeñas. Clasifica la escala como verificada, parcialmente legible o inútil y comunica únicamente la precisión que el archivo sostiene.`],
      ["Controla perspectiva y paralaje antes de comparar", `La cámara debería mirar casi perpendicular al plano de regla y artículo. Con ángulo oblicuo, el extremo cercano parece mayor y el espaciado se comprime hacia el fondo. Hay paralaje si la regla está por encima o debajo del borde leído: el extremo parece tocar otra marca según la cámara. Busca bordes convergentes, marcas con separación desigual, diferencia de altura o un extremo mucho más cerca del objetivo. Compara repeticiones solo con orientación, extremos y preparación iguales. No promedies números de convenciones o perspectivas distintas. Si una foto recta y libre sostiene 56 cm y otra inclinada parece 55 cm, conserva la observación fuerte y documenta por qué la otra es débil. Si ambas son oblicuas, queda sin resolver. No conviertas píxeles a centímetros sin una referencia fiable en el mismo plano y un método de imagen apropiado.`],
      ["Informa un intervalo acorde con la fotografía", `Una foto con regla rara vez justifica más precisión que sus marcas visibles, extremos claros y preparación. Lee el menor intervalo distinguible e incorpora incertidumbre de colocación. Si un bajo blando cae entre 55,5 y 56 cm con la imagen algo inclinada, escribe «aprox. 55,5–56 cm en esta preparación», no 55,73 cm. Separa incertidumbre de lectura y variación del producto. La primera pertenece a la imagen; fabricación, relajación del tejido y tolerancias del vendedor son cuestiones distintas que la foto no cuantifica. No inventes un margen universal ni una garantía de plataforma. Para comparar la tabla, conserva valores y convenciones: tabla 56 cm; foto de unidad aprox. 55,5–56 cm; ambos planos y en puntos nombrados. Una pequeña diferencia dentro de la incertidumbre no es automáticamente un error. Una mayor puede requerir aclaración, pero la cuenta y condiciones actuales determinan las acciones disponibles.`],
      ["Usa líneas por categoría sin mezclar significados", `Prepara una lista breve antes de pedir pruebas. En tops: ancho entre axilas, hombros, largo de espalda y manga, cada uno con extremos. En pantalones: estado de cintura, tiro, entrepierna y abertura por separado. En calzado, identifica plantilla, suela u otro componente visible; ninguno garantiza comodidad o ajuste. En bolsos, nombra ancho, alto y fondo en puntos exteriores y si están vacíos o formados. Los accesorios pueden necesitar rango útil de correa, distancia entre agujeros o abertura interior en vez de largo total. Compara solo elementos equivalentes. Una recomendación corporal del anuncio no se compara directamente con el ancho terminado, y una etiqueta no es una medida en centímetros. Si el límite no se ve, marca la línea como ausente. Una línea precisa solicitada vale más que varias fotos con regla sin etiquetas.`],
      ["Termina con una decisión rastreable y un límite honesto", `Archiva identificador de pedido, opción, fecha de la tabla, imagen, dimensión, extremos, unidad, preparación, lectura, rango de incertidumbre y revisión. Excluye direcciones, pagos y cuenta de copias compartibles. Usa tres resultados. Acepta la evidencia si unidad, extremos, preparación, escala y ángulo coinciden con la convención y el rango responde la decisión. Retén si hay recorte, inclinación, tensión o ilegibilidad. Aclara con una petición reproducible cuando otra foto cierre la laguna: «sudadera plana sin estirar; cinta en centímetros entre ambas costuras de axila; mostrar cero, costuras y marca final en un encuadre perpendicular». Finaliza con lo no probado. Una foto sólida puede sostener una dimensión aproximada de la unidad recibida. No prueba ajuste personal, construcción oculta, composición, autenticidad, durabilidad ni precisión superior a lo visible.`],
    ],
  },
  fr: {
    meta: ["Preuve de mesure", "Vérifié le 13 sept. 2026", "Indépendant"],
    sourceNote: "Base de recherche : le guide USFans actuel pour débutants et une page produit publique actuelle ont été contrôlés le 13 septembre 2026. Le guide indique que les articles arrivés sont inspectés et photographiés ; la page produit annonce actuellement 3–7 photos HD d’inspection et affiche tailles et spécifications sélectionnables. Les pages publiques ne promettent ni précision ni tolérance fixe des photos de mesure : chaque lecture reste une preuve visuelle limitée.",
    visual: ["Échelle de preuve d’une photo de mesure", [["Définie", "mêmes extrémités nommées"], ["Visible", "article, règle et graduations dans un cadre"], ["Lisible", "échelle vue presque perpendiculairement"], ["Limitée", "lecture avec incertitude déclarée"]]],
    related: [["Ouvrir le guide général des photos d’entrepôt", "/qc"], ["Vérifier les angles couverts", "/articles/usfans-warehouse-photo-angle-map"], ["Séparer identité de taille et coupe", "/articles/usfans-warehouse-size-tag-evidence"]],
    sections: [
      ["Traiter la photo comme une affirmation de mesure, pas un nombre", `Une photo d’entrepôt avec règle peut soutenir une affirmation utile après cinq questions : quelle dimension, où sont les deux extrémités, comment l’article est placé, l’échelle est-elle lisible et quelle incertitude reste ? Écrivez l’affirmation complète : « largeur poitrine d’environ 56 cm de couture d’aisselle à couture d’aisselle, vêtement posé à plat ». « Taille 56 » n’est pas vérifiable. USFans indique actuellement que les articles arrivés sont inspectés et photographiés ; une page publique annonce 3–7 photos HD d’inspection. Cela ne garantit ni vos repères ni une précision de laboratoire. L’image ne prouve que la dimension montrée. Étiquette, tableau de l’annonce et photo avec règle sont trois dossiers : l’étiquette nomme la variante, le tableau donne la spécification vendeur, la photo peut montrer l’unité reçue. Leur accord augmente la confiance sans permettre à l’un de remplacer silencieusement l’autre.`],
      ["Définir les deux extrémités avant de lire la règle", `La plupart des désaccords commencent avant la lecture. Nommez début et fin avec des éléments de construction visibles. Pour une largeur, précisez entre coutures d’aisselle, bords extérieurs ou autres points. Pour la longueur, indiquez point d’épaule et ourlet, col exclu ou inclus. Pour un pantalon, séparez largeur droite de ceinture et estimation de circonférence doublée ; pour une chaussure, semelle intérieure amovible, semelle extérieure et espace intérieur. Conservez la convention avec la valeur. Vérifiez que la règle commence bien au premier point : il peut exister un blanc avant zéro ou un crochet hors échelle. Le second point doit être visible, non caché par main, pli ou recadrage. S’il tombe entre deux marques, gardez cette information ; ne le déplacez pas mentalement vers le tableau. Si conventions demandée et photographiée diffèrent, notez non comparable et redemandez la ligne nommée.`],
      ["Contrôler plan, tension et limites naturelles", `Un nombre peut être net alors que l’objet est mal préparé. Pour un vêtement souple, vérifiez pose à plat, alignement des coutures, plis, élastique et traction. Une ceinture étirée ne se compare pas à une ceinture au repos. Une manche tirée en diagonale paraît plus longue ; un ourlet courbe donne plusieurs longueurs. Pour sacs et objets structurés, distinguez extérieur vide, forme remplie, base rigide ou ouverture souple. Une semelle courbe près d’une règle droite n’égale pas automatiquement la longueur intérieure utile. Ne doublez une largeur à plat en circonférence que si cette convention est choisie et pertinente pour la construction. L’image doit montrer assez de l’objet pour vérifier la préparation, pas seulement deux chiffres. Si la préparation est incertaine, décrivez-la et baissez la confiance au lieu de corriger le résultat par intuition.`],
      ["Vérifier que la règle fournit une échelle réelle et lisible", `Une règle voisine n’est pas automatiquement l’échelle de l’objet. Elle doit rester droite, dans le même plan que la ligne, afficher l’unité et assez de graduations consécutives. Vérifiez centimètres, millimètres ou pouces sans deviner. Attention au ruban qui se courbe, contourne l’article ou passe sous le tissu. Une règle rigide pontant une courbe mesure une corde, pas le trajet de surface. La résolution limite aussi la preuve : zoomer agrandit les pixels sans récupérer une marque illisible. Préférez un cadre montrant toute la ligne et une vue rapprochée de la lecture finale, reliés au même montage. Si seule la fin apparaît, le décalage initial est inconnu ; si seule une vue large existe, les petites marques fusionnent. Classez l’échelle vérifiée, partiellement lisible ou inutilisable et ne rapportez que la précision réellement soutenue.`],
      ["Contrôler perspective et parallaxe avant comparaison", `La caméra devrait regarder presque perpendiculairement le plan de la règle et de l’article. En biais, l’extrémité proche paraît plus grande et l’espacement se comprime au loin. La parallaxe apparaît si règle et bord lu ne sont pas à la même hauteur : le point semble toucher une autre marque selon la caméra. Cherchez bords convergents, graduations inégales, écart de hauteur visible ou extrémité très proche de l’objectif. Comparez des vues répétées seulement si orientation, repères et préparation concordent. Ne moyennez pas des nombres issus de conventions ou perspectives différentes. Si une vue droite soutient 56 cm et une vue inclinée semble donner 55 cm, conservez l’observation la plus forte et notez la faiblesse de l’autre. Si les deux sont obliques, la question reste ouverte. Ne transformez pas des pixels en centimètres sans référence fiable dans le même plan et méthode adaptée.`],
      ["Rapporter un intervalle adapté à la photo", `Une photo avec règle justifie rarement davantage de précision que graduations, extrémités et montage visibles. Lisez le plus petit intervalle distinct et incluez l’incertitude de placement. Si un ourlet souple tombe entre 55,5 et 56 cm dans une vue légèrement inclinée, écrivez « environ 55,5–56 cm dans ce montage », pas 55,73 cm. Séparez incertitude de lecture et variation du produit. La première appartient à l’image ; fabrication, détente du tissu et tolérances vendeur sont d’autres questions que la photo ne quantifie pas. N’inventez ni marge universelle ni garantie de plateforme. Pour comparer un tableau, gardez les deux valeurs et conventions : tableau vendeur 56 cm ; photo de l’unité environ 55,5–56 cm ; mêmes points à plat. Un petit écart dans l’incertitude n’est pas automatiquement une non-conformité. Un grand écart peut justifier une clarification, selon l’interface et les conditions actuelles.`],
      ["Employer des lignes propres à chaque catégorie sans les confondre", `Préparez une liste courte avant la demande. Pour les hauts : largeur aisselle, épaules, longueur dos et manche, avec extrémités. Pour les pantalons : état de ceinture, fourche, entrejambe et ouverture séparément. Pour les chaussures, précisez semelle intérieure, extérieure ou autre composant visible ; aucun ne garantit confort ou coupe réelle. Pour un sac, nommez largeur, hauteur et profondeur à des points extérieurs et indiquez s’il est vide ou mis en forme. Un accessoire peut demander plage utile de sangle, espacement des trous ou ouverture intérieure plutôt que longueur totale. Comparez uniquement des valeurs de même sens. Une recommandation corporelle de l’annonce n’est pas une largeur finie ; une étiquette n’est pas une lecture en centimètres. Si la limite n’est pas visible, marquez la ligne absente. Une ligne précise vaut mieux que plusieurs photos non étiquetées.`],
      ["Conclure par une décision traçable et une limite honnête", `Archivez identifiant de commande, option, date du tableau, image, dimension, extrémités, unité, montage, lecture, plage d’incertitude et date de contrôle. Retirez adresses, paiements et compte des copies partageables. Trois résultats : accepter si unité, repères, préparation, échelle et angle correspondent à la convention et si la plage répond à la décision ; suspendre si l’image est recadrée, oblique, étirée ou illisible ; clarifier par une demande reproductible si une image ferme l’écart : « sweat posé à plat sans étirer ; ruban en centimètres de couture d’aisselle gauche à droite ; montrer zéro, les deux coutures et la marque finale dans un cadre perpendiculaire ». Terminez par ce qui reste non prouvé. Une bonne photo peut soutenir une dimension approximative de l’unité reçue. Elle ne prouve ni coupe personnelle, construction cachée, matière, authenticité, durabilité ni précision supérieure à ce que l’image montre.`],
    ],
  },
  it: {
    meta: ["Prova di misurazione", "Verificato 13 set 2026", "Indipendente"],
    sourceNote: "Base di ricerca: la guida USFans attuale per principianti e una pagina prodotto pubblica attuale sono state controllate il 13 settembre 2026. La guida indica che gli articoli arrivati vengono ispezionati e fotografati; la pagina annuncia attualmente 3–7 foto HD di controllo e mostra taglie e specifiche selezionabili. Le pagine pubbliche non promettono precisione o tolleranza fissa delle foto di misura, quindi ogni lettura resta una prova visiva limitata.",
    visual: ["Scala delle prove per foto di misurazione", [["Definita", "stessi estremi nominati"], ["Visibile", "articolo, righello e tacche nello stesso scatto"], ["Leggibile", "scala vista quasi perpendicolarmente"], ["Limitata", "lettura più incertezza dichiarata"]]],
    related: [["Apri la guida generale alle foto di magazzino", "/qc"], ["Controlla gli angoli coperti", "/articles/usfans-warehouse-photo-angle-map"], ["Separa etichetta taglia e vestibilità", "/articles/usfans-warehouse-size-tag-evidence"]],
    sections: [
      ["Tratta la foto come un’affermazione di misura, non come un numero", `Una foto di magazzino con righello può sostenere un’affermazione utile solo dopo cinque domande: quale dimensione, dove sono i due estremi, come è posto l’articolo, la scala è leggibile e quale incertezza resta? Scrivi la frase completa: «larghezza torace circa 56 cm da cucitura ascellare a cucitura ascellare con capo disteso». «Taglia 56» non è verificabile. USFans indica oggi che gli articoli arrivati vengono ispezionati e fotografati; una pagina pubblica annuncia 3–7 foto HD di controllo. Nessuna frase garantisce gli estremi richiesti o precisione di laboratorio. Usa l’immagine solo per la dimensione mostrata. Etichetta, tabella dell’inserzione e foto con righello sono registri distinti: l’etichetta nomina la variante, la tabella riporta la specifica del venditore, la foto può mostrare l’unità ricevuta. L’accordo aumenta fiducia, ma un registro non sostituisce tacitamente l’altro.`],
      ["Definisci entrambi gli estremi prima di leggere il righello", `Molte differenze nascono prima della lettura. Nomina inizio e fine con elementi visibili. Per la larghezza di un capo, specifica tra cuciture ascellari, bordi esterni o altri punti. Per la lunghezza, indica punto spalla e orlo e se il colletto è escluso. Per pantaloni, separa larghezza diritta della vita da circonferenza stimata raddoppiandola; per scarpe, soletta estraibile, suola esterna e spazio interno. Salva la convenzione accanto al valore. Controlla che il righello parta davvero dal primo punto: può esserci spazio prima dello zero o un gancio fuori scala. Il secondo estremo deve vedersi, non essere coperto da mano, piega o ritaglio. Se cade tra due tacche, conserva il fatto senza spostarlo mentalmente verso la tabella. Se convenzione richiesta e fotografata differiscono, segna non confrontabile e richiedi la stessa linea nominata.`],
      ["Controlla piano, tensione e confini naturali", `Un numero può essere nitido mentre l’oggetto è preparato male. Per indumenti morbidi verifica posa piatta, cuciture allineate, pieghe, elastico e trazione. Una vita tesa non si confronta con una rilassata. Una manica tirata in diagonale appare più lunga; un orlo curvo dà valori diversi al centro e al bordo. Per borse e oggetti strutturati, decidi se si misurano esterno vuoto, forma riempita, base rigida o apertura flessibile. Una suola curva fotografata vicino a un righello diritto non equivale alla lunghezza interna utile. Non ricavare una circonferenza raddoppiando la larghezza piatta salvo che la convenzione sia scelta e la costruzione lo consenta. L’immagine deve mostrare abbastanza oggetto da verificare la preparazione, non solo due cifre. Se la posa è incerta, descrivila e riduci la fiducia invece di correggere il risultato per intuito.`],
      ["Verifica che il righello offra una scala reale e leggibile", `Un righello vicino non è automaticamente una scala dell’oggetto. Deve stare nello stesso piano, restare diritto, mostrare l’unità e abbastanza tacche consecutive. Controlla centimetri, millimetri o pollici senza indovinare. Attenzione a un metro che si solleva, curva intorno al prodotto o sparisce sotto il tessuto. Un righello rigido sopra una curva misura una corda, non il percorso della superficie. Anche la risoluzione limita: lo zoom digitale ingrandisce pixel, non recupera una tacca illeggibile. Meglio uno scatto dell’intera linea e uno vicino della lettura finale, entrambi collegati allo stesso allestimento. Se si vede solo la fine, lo scarto iniziale può restare ignoto; se c’è solo una vista ampia, le tacche piccole si fondono. Classifica la scala come verificata, parzialmente leggibile o inutilizzabile e comunica solo la precisione sostenuta dal file.`],
      ["Controlla prospettiva e parallasse prima del confronto", `La fotocamera dovrebbe guardare quasi perpendicolare al piano di righello e articolo. Con angolo obliquo l’estremo vicino appare più grande e gli intervalli si comprimono verso il fondo. La parallasse nasce quando righello e bordo letto sono a diversa altezza: l’estremo sembra toccare un’altra tacca cambiando posizione della camera. Cerca bordi convergenti, tacche con distanza disuguale, dislivello visibile o un estremo molto più vicino all’obiettivo. Confronta ripetizioni solo con orientamento, estremi e preparazione uguali. Non fare la media di numeri da convenzioni o prospettive diverse. Se uno scatto diritto sostiene 56 cm e uno inclinato sembra 55, conserva l’osservazione più forte e spiega perché l’altra è debole. Se entrambi sono obliqui, la prova resta irrisolta. Non convertire pixel in centimetri senza riferimento affidabile nello stesso piano e metodo adatto.`],
      ["Riporta un intervallo coerente con la fotografia", `Una foto con righello raramente giustifica più precisione di tacche, estremi e posa visibili. Leggi l’intervallo minimo distinguibile e includi l’incertezza di posizionamento. Se un orlo morbido cade tra 55,5 e 56 cm con immagine leggermente inclinata, scrivi «circa 55,5–56 cm in questa posa», non 55,73 cm. Separa incertezza di lettura e variazione del prodotto. La prima appartiene all’immagine; produzione, rilassamento del tessuto e tolleranze del venditore sono domande diverse che la foto non quantifica. Non inventare un margine universale o una garanzia della piattaforma. Per confrontare una tabella, conserva valori e convenzioni: tabella 56 cm; foto unità circa 55,5–56 cm; entrambi piatti tra punti nominati. Una piccola differenza entro l’incertezza non è automaticamente errore. Una maggiore può richiedere chiarimento, ma interfaccia e condizioni correnti definiscono le azioni.`],
      ["Usa linee specifiche per categoria senza confonderne il senso", `Prepara una lista breve prima della richiesta. Per top: larghezza ascelle, spalle, lunghezza schiena e manica, sempre con estremi. Per pantaloni: stato della vita, cavallo, interno gamba e apertura separati. Per calzature, indica soletta, suola o altro componente visibile; nessuno garantisce comodità o vestibilità. Per borse, nomina larghezza, altezza e profondità in punti esterni e se la borsa è vuota o formata. Gli accessori possono richiedere intervallo utile della cinghia, distanza dei fori o apertura interna anziché lunghezza totale. Confronta solo valori equivalenti. Una raccomandazione corporea dell’inserzione non è larghezza finita, e un’etichetta non è lettura in centimetri. Se il confine non appare, segna la linea mancante. Una linea precisa richiesta è più utile di varie foto con righello senza etichette.`],
      ["Concludi con decisione tracciabile e limite onesto", `Archivia identificatore ordine, opzione, data tabella, immagine, dimensione, estremi, unità, posa, lettura, intervallo d’incertezza e data. Elimina indirizzi, pagamenti e dati conto dalle copie condivisibili. Usa tre esiti. Accetta se unità, estremi, preparazione, scala e angolo coincidono con la convenzione e l’intervallo risponde alla decisione. Sospendi se la foto è tagliata, inclinata, tesa o illeggibile. Chiarisci con una richiesta riproducibile se un nuovo scatto chiude il vuoto: «felpa piatta senza tirare; metro in centimetri da cucitura ascellare sinistra a destra; mostrare zero, entrambe le cuciture e tacca finale in uno scatto perpendicolare». Termina con ciò che non è provato. Una foto solida può sostenere una dimensione approssimativa dell’unità ricevuta. Non prova vestibilità personale, costruzione nascosta, materiale, autenticità, durata o precisione oltre ciò che si vede.`],
    ],
  },
};

export function getUveMeasurementArticle(language) {
  const activeLanguage = localized[language] ? language : "en";
  const entry = localized[activeLanguage];
  return {
    ...uveMeasurementArticleBlueprint,
    title: uveMeasurementArticleBlueprint.title[activeLanguage],
    dek: uveMeasurementArticleBlueprint.dek[activeLanguage],
    sections: entry.sections,
    sourceNote: entry.sourceNote,
    visual: entry.visual,
    related: entry.related,
    articleMeta: entry.meta,
    datePublished: "2026-09-13",
    dateModified: "2026-09-13",
  };
}
