export const uveSizeTagArticleBlueprint = {
  slug: "usfans-warehouse-size-tag-evidence",
  title: {
    en: "USFans Warehouse Size Tags: Verify the Label Without Assuming Fit",
    de: "USFans-Größenetiketten im Lager: Label prüfen, Passform nicht annehmen",
    es: "Etiquetas de talla de USFans: verifica la etiqueta sin asumir el ajuste",
    fr: "Étiquettes de taille USFans : vérifier sans supposer la coupe",
    it: "Etichette taglia USFans: verifica il dato senza presumere la vestibilità",
  },
  dek: {
    en: "A size tag can confirm one visible marker on the received item. It cannot prove that the item follows the listing chart, matches another brand, or will fit a particular body.",
    de: "Ein Größenetikett bestätigt ein sichtbares Merkmal des eingelagerten Artikels. Es beweist weder die Maßtabelle noch die Vergleichbarkeit mit einer anderen Marke oder die persönliche Passform.",
    es: "Una etiqueta de talla confirma un dato visible del artículo recibido. No demuestra que siga la tabla del anuncio, equivalga a otra marca o vaya a quedarle bien a una persona.",
    fr: "Une étiquette de taille confirme un repère visible sur l’article reçu. Elle ne prouve ni la conformité au tableau de l’annonce, ni l’équivalence entre marques, ni la coupe sur une personne.",
    it: "Un’etichetta di taglia conferma un indicatore visibile sull’articolo ricevuto. Non prova la corrispondenza alla tabella dell’inserzione, a un altro marchio o al corpo di una persona.",
  },
};

const localized = {
  en: {
    sourceNote: "Fact-check note: USFans public guidance and a current public product specification page were checked on September 11, 2026. The guide says buyers select color, size and quantity before ordering, and that warehouse inspection and photos follow arrival. A live product page displayed selectable size values and a QC-photo notice. Interface labels, photo availability and service scope can change; the current order and warehouse record remain authoritative.",
    meta: ["Warehouse label evidence", "Checked 11 Sep 2026", "Independent"],
    visual: ["Size-tag evidence ladder", [["Ordered", "Exact option saved before payment"], ["Visible", "Readable tag on the received unit"], ["Compared", "Tag checked against the saved option"], ["Unresolved", "Measurements and real-world fit"]]],
    related: [["Read the general QC evidence guide", "/qc"], ["Map missing warehouse evidence", "/articles/usfans-warehouse-evidence-gap-map"], ["Check photo-angle coverage", "/articles/usfans-warehouse-photo-angle-map"]],
    sections: [
      ["Start with a narrower question than ‘Will it fit?’", `A warehouse size-tag photo can answer a small but important question: what size marker is visibly attached to the unit that arrived? It cannot answer the much larger question of whether the item will fit a particular person. Keep those two questions separate from the first glance. The USFans public buying guide currently describes selecting color, size and quantity before submitting an order, followed later by warehouse inspection and photographs. That sequence creates three records: the option selected before payment, the seller’s item that reaches the warehouse, and the visible label in the warehouse image. Your first task is to compare those records for identity. If the order says size L and a clear sewn label says M, there is a decision-changing mismatch. If both say L, you have only confirmed label agreement. You have not confirmed chest width, garment length, shrinkage, cut, stretch, comfort or the way the item sits on a body. Treat the label as one piece of evidence, not a fitting-room result. This disciplined scope prevents both false reassurance and unnecessary rejection.`],
      ["Build the evidence chain before zooming in", `Open the saved order record before judging the tag. Record the source URL or product identifier, selected color, selected size, quantity, order number and the date the option was captured. Keep a dated copy of the listing’s size chart when sizing materially affects the purchase, because sellers can edit options or replace images after an order. Then identify the warehouse photo that actually shows the item’s label. A package sticker, handwritten warehouse note, seller barcode and sewn garment tag are different objects; do not treat them as interchangeable. Write one row for each relevant marker: where it appears, what characters are legible, which photo shows it and whether the marker belongs to the product, retail packaging or warehouse handling. This chain matters when two labels disagree. It lets you say, for example, ‘the order option is 32, the waistband tag is 32, and the outer bag sticker is 34’ without guessing which one defines the item. Preserve the contradiction and ask a precise question instead of silently choosing the number you expected.`],
      ["Read the tag as an image, not as a promise", `Assess the photograph before interpreting the text. Is the full tag inside the frame? Is the image sharp enough to distinguish 6 from 8, M from W, or EU 42 from 47? Is glare hiding a printed line? Has the label folded over, or does a seam cover the final character? A close-up can make a code legible while removing the context that proves where the tag is attached, so use one orientation view and one detail view when both are available. Note every visible field separately: nominal size, regional system, model or style code, material wording, care information and any secondary measurement. Do not infer an unreadable character from the ordered option. Mark it ‘unclear.’ Do not treat a seller’s chart printed on loose packaging as proof that the sewn label matches. Likewise, a readable hangtag may identify a retail option but not the size printed inside the garment or shoe. The strongest label evidence shows readable text and its physical relationship to the received unit. If either legibility or context is missing, the correct result is hold or clarify, not pass.`],
      ["Do not translate size systems by intuition", `Nominal sizes are not universal units. The same letters can represent different measurements across sellers, cuts and product categories, while number systems may refer to different regional conventions. A visible XL therefore proves only that the item carries XL in that labeling system. It does not prove equivalence to an XL already in your wardrobe. For numeric labels, preserve the system exactly as shown: EU, US, UK, CN, centimeters, waist inches or an unexplained seller code. Never convert one system into another unless the current listing provides a direct mapping that can be saved and checked. Even then, describe it as the seller’s mapping, not a global conversion rule. Watch for paired values such as EU and US shoe sizes, because one line can be misread when the image is angled. Also distinguish body-size advice from finished-garment dimensions. A chart recommending a size for a height or weight range is not the same as a flat measurement of the product. Your evidence record should keep the original tag value, the listing’s stated system and any mapping in separate fields so an assumption cannot masquerade as observation.`],
      ["Use category-specific markers without drifting into a full measurement audit", `Different products place size evidence in different locations. For a T-shirt or hoodie, look for the neck or side-seam label and confirm whether a separate wash label repeats the same size. For trousers, compare the waistband marker with the ordered waist option while remembering that a nominal waist number may not equal the finished waistband measurement. For shoes, inspect the tongue, inner lining or insole marking and compare both shoes when the photos permit; a box sticker alone is packaging evidence. Hats, belts, gloves and adjustable accessories may use ranges, circumference values or one-size wording, each of which needs its own interpretation. The goal here is still label identity, not exact dimensional verification. If the label agrees but sizing remains critical, move the unresolved question to a targeted measurement request with named reference points. Do not invent precision from the camera, a ruler visible at an angle or the apparent scale of another object. That later measurement is a separate evidence layer. The tag tells you what the item says it is; a properly framed measurement can help test what dimensions the item actually has.`],
      ["Classify disagreement before choosing an action", `Not every inconsistency has the same weight. A direct mismatch exists when the paid order shows one size and a clearly attached product label shows another. A contextual conflict exists when the product label matches but a box or outer-bag sticker differs. An ambiguity exists when the relevant character is blurred, cropped or hidden. An incompleteness exists when the photos show no relevant size marker at all. Record the class before contacting support. For a direct mismatch, preserve the order selection and the label image together and ask whether the received unit is the ordered variant. For a contextual conflict, ask for a view that connects the packaging and product or confirms which marker belongs to the unit. For ambiguity, request one readable close-up that includes enough surrounding material to locate the tag. For incompleteness, name the expected label location instead of asking staff to ‘check size.’ This wording keeps the request observable and bounded. It also avoids claims about authenticity, quality or fit that a warehouse photo cannot establish. One precise question is more useful than a general complaint because the response can be attached to the evidence chain and reviewed.`],
      ["Choose accept, hold or clarify with explicit limits", `Use a three-way decision rather than a vague confidence score. Accept the label evidence when the paid option and clearly attached marker agree, no conflicting marker remains unexplained, and real-world fit is not being inferred from the tag. Hold when the image is unreadable, the tag location is uncertain, or packaging and product markers disagree. Clarify when one specific new photo or staff confirmation could resolve the gap. The outcome should state both what passed and what did not. A useful note reads: ‘Accepted for label identity: order size 32 matches the attached waistband tag. Fit remains unverified because no garment measurement was used.’ A hold note might read: ‘Order says EU 42; visible image shows only a cropped 4. Request a full tongue-label view.’ If the evidence shows a wrong variant and an after-sales action is available, follow the current order interface promptly; warehouse storage time must not be assumed to equal a seller return period. The warehouse account and current terms determine available actions. This matrix helps prevent a matching label from becoming an unjustified guarantee and prevents a poor photograph from becoming an automatic rejection.`],
      ["Leave a record another person can audit", `Finish with a compact evidence record that survives after the listing or interface changes. Store the order identifier, selected size, captured listing system, warehouse photo reference, exact visible tag text, tag location, conflicting markers, decision and date. Add a short limitation sentence: ‘Label identity checked; measurements and personal fit not established.’ If a new close-up arrives, append it rather than overwriting the first interpretation. That preserves why the item moved from hold to accept or from ambiguity to mismatch. Exclude private addresses, payment details and unrelated account information from any shareable copy. This method also scales to multi-item orders: give every unit its own row, because one clear size tag does not prove the size of a similar second unit. The durable principle is modest but powerful. A tag is evidence of a visible label on one received object. Agreement with the order reduces identity uncertainty; it does not eliminate measurement, construction or fit uncertainty. By recording both the confirmed fact and the remaining boundary, you can ask better questions, avoid false conversions and make a warehouse decision that is understandable later.`],
    ],
  },
  de: {
    sourceNote: "Faktenhinweis: Die öffentliche USFans-Anleitung und eine aktuelle öffentliche Produktspezifikationsseite wurden am 11. September 2026 geprüft. Laut Anleitung wählen Käufer vor der Bestellung Farbe, Größe und Menge; nach der Ankunft folgen Lagerprüfung und Fotos. Eine aktuelle Produktseite zeigte auswählbare Größen und einen Hinweis auf QC-Fotos. Oberfläche, Bildverfügbarkeit und Leistungsumfang können sich ändern; maßgeblich bleiben Bestellung und Lageransicht.",
    meta: ["Größenetikett als Beleg", "Geprüft am 11.09.2026", "Unabhängig"],
    visual: ["Belegstufen für Größenetiketten", [["Bestellt", "Genaue Option vor Zahlung gespeichert"], ["Sichtbar", "Lesbares Etikett am eingegangenen Artikel"], ["Verglichen", "Etikett mit gespeicherter Option abgeglichen"], ["Offen", "Maße und reale Passform"]]],
    related: [["Allgemeinen QC-Leitfaden lesen", "/qc"], ["Fehlende Lagerbelege kartieren", "/articles/usfans-warehouse-evidence-gap-map"], ["Abdeckung der Fotoansichten prüfen", "/articles/usfans-warehouse-photo-angle-map"]],
    sections: [
      ["Mit einer engeren Frage als „Passt es?“ beginnen", `Ein Foto des Größenetiketts kann eine kleine, wichtige Frage beantworten: Welche Größenangabe ist sichtbar am eingegangenen Artikel befestigt? Es beantwortet nicht, ob der Artikel einer bestimmten Person passt. Trenne beides beim ersten Blick. Die öffentliche USFans-Anleitung beschreibt derzeit die Auswahl von Farbe, Größe und Menge vor der Bestellung sowie die spätere Lagerprüfung mit Fotos. Dadurch entstehen drei Belege: die bezahlte Option, der eingegangene Artikel und das sichtbare Etikett. Zuerst prüfst du ihre Identität. Steht in der Bestellung L und auf einem klaren, angenähten Label M, liegt eine entscheidende Abweichung vor. Steht auf beiden L, ist nur die Übereinstimmung des Labels bestätigt. Brustweite, Länge, Einlaufen, Schnitt, Dehnung, Komfort und Sitz am Körper bleiben offen. Das Etikett ist ein Belegstück, kein Ergebnis einer Anprobe. Diese Begrenzung verhindert falsche Sicherheit ebenso wie eine unnötige Ablehnung.`],
      ["Die Belegkette vor dem Zoomen aufbauen", `Öffne vor der Etikettprüfung den gespeicherten Bestelldatensatz. Halte Quell-URL oder Produktkennung, Farbe, Größe, Menge, Bestellnummer und Erfassungsdatum fest. Speichere eine datierte Kopie der Größentabelle, wenn sie kaufentscheidend war, denn Verkäufer können Optionen und Bilder ändern. Bestimme dann, welches Lagerfoto wirklich das Produktetikett zeigt. Paketaufkleber, handschriftliche Lagernotiz, Verkäuferbarcode und angenähtes Label sind verschiedene Gegenstände. Erfasse für jede Markierung Position, lesbare Zeichen, Foto und Zugehörigkeit zu Produkt, Verkaufsverpackung oder Lagerprozess. Das ist wichtig, wenn zwei Angaben widersprechen. So lässt sich festhalten: „Bestelloption 32, Bundetikett 32, Außenbeutel 34“, ohne willkürlich eine Zahl zur Wahrheit zu erklären. Bewahre den Widerspruch und stelle eine genaue Frage, statt still die erwartete Größe zu wählen.`],
      ["Das Etikett als Bild, nicht als Versprechen lesen", `Prüfe zuerst die Aufnahme. Ist das ganze Label im Bild? Reicht die Schärfe, um 6 und 8, M und W oder EU 42 und 47 zu unterscheiden? Verdeckt Glanz eine Zeile, ist das Etikett umgefaltet oder liegt eine Naht über dem letzten Zeichen? Ein Nahfoto macht Codes lesbar, kann aber den Befestigungsort verbergen. Nutze daher, soweit vorhanden, eine Übersichts- und eine Detailansicht. Notiere jedes Feld getrennt: Nenngröße, Regionalsystem, Modellcode, Materialtext, Pflegehinweis und Nebenmaß. Ergänze kein unlesbares Zeichen aus der Bestellung, sondern markiere es als unklar. Eine lose Verpackungstabelle beweist nicht die Übereinstimmung des angenähten Labels. Auch ein Anhänger kann die Verkaufsvariante nennen, nicht zwingend die Innenkennzeichnung. Starke Belege zeigen lesbaren Text und die physische Verbindung zum Artikel. Fehlt Lesbarkeit oder Kontext, lautet das Ergebnis halten oder klären, nicht freigeben.`],
      ["Größensysteme nicht nach Gefühl übersetzen", `Nenngrößen sind keine universellen Einheiten. Dieselben Buchstaben können je nach Verkäufer, Schnitt und Kategorie andere Maße bedeuten; Zahlensysteme können verschiedene Regionen meinen. Ein sichtbares XL beweist nur, dass der Artikel in diesem System XL trägt. Es beweist keine Gleichheit mit einem XL im eigenen Schrank. Bewahre Zahlen mit dem sichtbaren System auf: EU, US, UK, CN, Zentimeter, Zoll oder ungeklärter Verkäufercode. Wandle nur um, wenn das aktuelle Angebot eine direkte, speicherbare Zuordnung liefert, und nenne sie Zuordnung des Verkäufers, nicht allgemeine Regel. Bei Schuhen können gekoppelte EU- und US-Werte durch Schrägansicht verwechselt werden. Trenne außerdem Körperempfehlungen von Fertigmaßen. Eine Größenempfehlung nach Körperhöhe oder Gewicht ist keine flache Produktmessung. Der Datensatz braucht getrennte Felder für Originalwert, Listensystem und angebotene Zuordnung, damit Annahmen nicht wie Beobachtungen aussehen.`],
      ["Kategoriespezifische Marker nutzen, ohne eine Messprüfung vorwegzunehmen", `T-Shirts und Hoodies tragen Größenhinweise häufig am Hals oder in der Seitennaht; prüfe, ob ein Pflegeetikett denselben Wert wiederholt. Bei Hosen vergleichst du das Bundlabel mit der bestellten Taillenoption, ohne die Nenngröße mit dem realen Bundmaß gleichzusetzen. Bei Schuhen kommen Zunge, Innenfutter oder Einlegesohle infrage; vergleiche beide Schuhe, wenn die Fotos es erlauben. Ein Kartonaufkleber bleibt Verpackungsbeleg. Hüte, Gürtel, Handschuhe und verstellbare Accessoires können Bereiche, Umfangswerte oder Einheitsgröße nutzen. Ziel bleibt die Identität des Labels, nicht die genaue Dimension. Stimmt das Label, bleibt Größe aber kritisch, formuliere eine gezielte Messanfrage mit benannten Referenzpunkten. Erfinde keine Genauigkeit aus Perspektive, schrägem Lineal oder einem Vergleichsobjekt. Die spätere Messung ist eine eigene Belegschicht: Das Etikett sagt, was der Artikel nennt; ein korrektes Messfoto kann prüfen, welche Dimension er tatsächlich hat.`],
      ["Widersprüche vor der Aktion einordnen", `Nicht jede Unstimmigkeit hat dasselbe Gewicht. Eine direkte Abweichung liegt vor, wenn die bezahlte Größe und das klar befestigte Produktlabel verschieden sind. Ein Kontextkonflikt liegt vor, wenn das Produktlabel passt, Verpackung oder Außenbeutel aber abweichen. Mehrdeutig ist ein verschwommenes, abgeschnittenes oder verdecktes Zeichen. Unvollständig ist die Galerie, wenn kein relevantes Größenmerkmal sichtbar ist. Notiere die Klasse vor einer Anfrage. Bei direkter Abweichung verbindest du Bestellauswahl und Labelbild und fragst, ob die eingegangene Einheit der bestellten Variante entspricht. Bei Kontextkonflikt verlangst du eine Ansicht, die Verpackung und Produkt verbindet. Bei Mehrdeutigkeit genügt ein lesbares Nahfoto mit Ortskontext. Bei Unvollständigkeit benennst du die erwartete Stelle statt „Größe prüfen“ zu schreiben. So bleibt die Frage beobachtbar und vermeidet Behauptungen zu Echtheit, Qualität oder Passform. Eine präzise Frage lässt sich in die Belegkette aufnehmen und später überprüfen.`],
      ["Mit klaren Grenzen annehmen, halten oder klären", `Nutze drei Entscheidungen statt eines vagen Vertrauenswerts. Nimm den Labelbeleg an, wenn bezahlte Option und befestigte Markierung übereinstimmen, kein Konflikt offen bleibt und keine reale Passform aus dem Label abgeleitet wird. Halte, wenn Bild, Ort oder widersprechende Marker unklar sind. Kläre, wenn ein bestimmtes Foto oder eine Bestätigung die Lücke schließen kann. Notiere sowohl Bestehen als auch Grenze: „Labelidentität angenommen: Bestellung 32 entspricht Bundetikett; Passform nicht geprüft, weil keine Produktmessung vorliegt.“ Ein Haltevermerk kann lauten: „Bestellung EU 42; Bild zeigt nur abgeschnittene 4. Vollständige Zungenansicht anfordern.“ Zeigt der Beleg eine falsche Variante und ist eine After-Sales-Aktion sichtbar, handle in der aktuellen Bestellansicht zeitnah. Lagerdauer ist nicht automatisch Rückgabefrist. Konto und aktuelle Bedingungen bestimmen die Optionen. Die Matrix verhindert, dass ein passendes Label zur Garantie oder ein schlechtes Foto zur automatischen Ablehnung wird.`],
      ["Einen später prüfbaren Datensatz hinterlassen", `Schließe mit einem kompakten Nachweis ab: Bestellkennung, gewählte Größe, gespeichertes Listensystem, Fotoreferenz, exakter Labeltext, Position, Konflikte, Entscheidung und Datum. Ergänze: „Labelidentität geprüft; Maße und persönliche Passform nicht festgestellt.“ Kommt ein neues Nahfoto, hänge es an, statt die erste Bewertung zu überschreiben. So bleibt nachvollziehbar, warum aus Halten eine Annahme oder aus Mehrdeutigkeit eine Abweichung wurde. Entferne private Adressen, Zahlungsdaten und irrelevante Kontoinformationen aus teilbaren Kopien. Bei mehreren Artikeln erhält jede Einheit eine eigene Zeile, denn ein klares Etikett beweist nicht die Größe einer ähnlichen zweiten Einheit. Das dauerhafte Prinzip ist bescheiden: Ein Tag belegt eine sichtbare Kennzeichnung auf einem empfangenen Objekt. Übereinstimmung senkt Identitätsunsicherheit, beseitigt aber weder Maß-, Konstruktions- noch Passformunsicherheit. Wer bestätigte Tatsache und verbleibende Grenze dokumentiert, stellt bessere Fragen und trifft eine später verständliche Lagerentscheidung.`],
    ],
  },
  es: {
    sourceNote: "Nota de verificación: la guía pública de USFans y una página pública actual de especificaciones se revisaron el 11 de septiembre de 2026. La guía indica que se eligen color, talla y cantidad antes del pedido y que después de la llegada hay inspección y fotos. Una página actual mostró tallas seleccionables y un aviso de fotos QC. Las etiquetas, la disponibilidad y el alcance pueden cambiar; mandan el pedido y el almacén actuales.",
    meta: ["Prueba de etiqueta de talla", "Revisado 11 sep 2026", "Independiente"],
    visual: ["Escalera de evidencia de talla", [["Pedido", "Opción exacta guardada antes del pago"], ["Visible", "Etiqueta legible en la unidad recibida"], ["Comparado", "Etiqueta contrastada con la opción guardada"], ["Pendiente", "Medidas y ajuste real"]]],
    related: [["Leer la guía general de evidencia QC", "/qc"], ["Mapear pruebas ausentes", "/articles/usfans-warehouse-evidence-gap-map"], ["Comprobar cobertura de ángulos", "/articles/usfans-warehouse-photo-angle-map"]],
    sections: [
      ["Empieza con una pregunta más estrecha que «¿me quedará bien?»", `Una foto de la etiqueta de talla puede responder una cuestión pequeña e importante: qué marcador lleva de forma visible la unidad recibida. No puede decir si le quedará bien a una persona. Separa ambas preguntas. La guía pública de USFans describe actualmente la selección de color, talla y cantidad antes del pedido y, más tarde, la inspección y las fotos de almacén. Así aparecen tres registros: la opción pagada, el artículo que llega y la etiqueta visible. Primero compara su identidad. Si el pedido dice L y una etiqueta cosida y clara dice M, existe una discrepancia decisiva. Si ambas dicen L, solo confirmas concordancia de etiqueta. No confirmas pecho, largo, encogimiento, corte, elasticidad, comodidad ni ajuste corporal. Trata la etiqueta como una prueba, no como un probador. Este límite evita tanto la falsa seguridad como el rechazo innecesario.`],
      ["Construye la cadena de evidencia antes de ampliar", `Abre el registro del pedido antes de valorar la etiqueta. Guarda URL o identificador, color, talla, cantidad, número de pedido y fecha de captura. Conserva una copia fechada de la tabla si fue decisiva, porque el vendedor puede editar opciones e imágenes. Identifica después qué foto muestra realmente la etiqueta del producto. Pegatina del paquete, nota del almacén, código del vendedor y etiqueta cosida son objetos distintos. Registra para cada marcador su ubicación, caracteres legibles, foto y relación con producto, embalaje comercial o manipulación. Esto importa cuando dos datos chocan. Permite escribir: «opción 32, etiqueta de cintura 32, bolsa exterior 34» sin elegir a ciegas una cifra como verdad. Conserva la contradicción y formula una pregunta concreta en vez de imponer la talla esperada.`],
      ["Lee la etiqueta como imagen, no como promesa", `Evalúa primero la fotografía. ¿Entra toda la etiqueta? ¿La nitidez distingue 6 de 8, M de W o EU 42 de 47? ¿Hay reflejo, pliegue o costura tapando caracteres? Un primer plano puede aclarar un código y ocultar dónde está unido; usa una vista de orientación y otra de detalle cuando existan. Anota por separado talla nominal, sistema regional, modelo, material, cuidado y medida secundaria. No completes un carácter ilegible con la opción del pedido: marca «no claro». Una tabla suelta en el embalaje no prueba la etiqueta cosida. Un colgante puede identificar la variante comercial sin coincidir con la marca interior. La prueba más fuerte combina texto legible y relación física con la unidad. Si falta legibilidad o contexto, el resultado correcto es retener o aclarar, no aprobar.`],
      ["No traduzcas sistemas de talla por intuición", `Las tallas nominales no son unidades universales. Las mismas letras cambian según vendedor, corte y categoría; los números pueden pertenecer a regiones distintas. Un XL visible solo prueba que el artículo lleva XL en ese sistema, no que equivalga al XL de tu armario. Conserva el sistema tal como aparece: EU, US, UK, CN, centímetros, pulgadas o código sin explicar. Convierte únicamente si el anuncio actual ofrece una correspondencia directa que puedas guardar, y llámala correspondencia del vendedor, no regla global. En calzado, valores EU y US emparejados pueden confundirse por el ángulo. Distingue también recomendación corporal y dimensiones terminadas. Una sugerencia por altura o peso no es una medida plana de la prenda. Guarda valor original, sistema y correspondencia en campos separados para que una suposición no parezca observación.`],
      ["Usa marcadores por categoría sin convertirlo en una auditoría de medidas", `En camisetas y sudaderas revisa cuello o costura lateral y si la etiqueta de lavado repite talla. En pantalones compara cintura nominal y opción pedida, sin asumir que el número sea la medida terminada. En zapatos mira lengüeta, forro o plantilla y ambos pies si las fotos lo permiten; la caja solo prueba embalaje. Gorras, cinturones, guantes y accesorios ajustables pueden usar rangos, circunferencias o talla única. El objetivo sigue siendo identidad de etiqueta, no dimensión exacta. Si coincide pero el tamaño sigue siendo crítico, traslada la duda a una medición dirigida con puntos de referencia nombrados. No inventes precisión por perspectiva, regla inclinada u objeto de escala. Esa medida posterior es otra capa: la etiqueta dice cómo se denomina el artículo; una medición bien encuadrada puede comprobar sus dimensiones reales.`],
      ["Clasifica el desacuerdo antes de actuar", `Una discrepancia directa aparece cuando el pedido pagado y la etiqueta unida muestran tallas distintas. Hay conflicto contextual cuando el producto coincide pero caja o bolsa difieren. Hay ambigüedad si el carácter está borroso, cortado u oculto, e información incompleta si no aparece ningún marcador relevante. Registra la clase antes de contactar. Para discrepancia directa, une selección y foto y pregunta si la unidad es la variante pedida. Para conflicto contextual, pide una vista que conecte embalaje y producto. Para ambigüedad, solicita un primer plano legible con suficiente entorno. Para ausencia, nombra la ubicación esperada en vez de decir «comprobar talla». La pregunta queda observable y no hace afirmaciones sobre autenticidad, calidad o ajuste. Una pregunta precisa puede incorporarse a la cadena y revisarse después.`],
      ["Acepta, retén o aclara con límites explícitos", `Acepta la evidencia cuando opción pagada y marcador unido coinciden, no queda conflicto y no deduces ajuste real. Retén cuando la imagen, la ubicación o los marcadores sean inciertos. Aclara cuando una foto o confirmación concreta cierre la laguna. Expresa lo aprobado y lo pendiente: «Identidad aceptada: talla 32 del pedido coincide con cintura; ajuste no verificado porque no hay medida». Para retener: «Pedido EU 42; imagen solo muestra un 4 cortado. Pedir lengüeta completa». Si aparece variante incorrecta y la interfaz ofrece posventa, actúa pronto; el almacenamiento no equivale automáticamente a plazo de devolución. La cuenta y las condiciones vigentes definen acciones. Esta matriz evita convertir una etiqueta correcta en garantía o una foto mala en rechazo automático.`],
      ["Deja un registro que otra persona pueda auditar", `Guarda identificador, talla elegida, sistema capturado, referencia de foto, texto exacto, ubicación, conflictos, decisión y fecha. Añade: «Identidad de etiqueta comprobada; medidas y ajuste personal no establecidos». Si llega otra imagen, agrégala sin borrar la interpretación inicial. Así se entiende por qué una retención pasó a aceptación o una duda a discrepancia. Elimina direcciones, pagos y datos irrelevantes de cualquier copia compartible. En pedidos múltiples, cada unidad necesita su fila: una etiqueta clara no prueba otra unidad parecida. El principio duradero es limitado: la etiqueta evidencia un marcador visible en un objeto recibido. La coincidencia reduce incertidumbre de identidad, no de medidas, construcción o ajuste. Documentar el hecho confirmado y su frontera permite preguntar mejor, evitar conversiones falsas y tomar una decisión comprensible.`],
    ],
  },
  fr: {
    sourceNote: "Note de vérification : le guide public USFans et une page publique actuelle de spécifications ont été contrôlés le 11 septembre 2026. Le guide indique que couleur, taille et quantité sont choisies avant la commande, puis que l’entrepôt inspecte et photographie. Une page actuelle affichait des tailles sélectionnables et un avis de photos QC. L’interface et le service peuvent évoluer ; la commande et l’entrepôt actifs font foi.",
    meta: ["Preuve d’étiquette de taille", "Vérifié le 11 sept. 2026", "Indépendant"],
    visual: ["Échelle de preuve de taille", [["Commandé", "Option exacte conservée avant paiement"], ["Visible", "Étiquette lisible sur l’unité reçue"], ["Comparé", "Étiquette rapprochée de l’option conservée"], ["Non résolu", "Mesures et coupe réelle"]]],
    related: [["Lire le guide QC général", "/qc"], ["Cartographier les preuves manquantes", "/articles/usfans-warehouse-evidence-gap-map"], ["Vérifier les angles couverts", "/articles/usfans-warehouse-photo-angle-map"]],
    sections: [
      ["Commencer par une question plus étroite que « Est-ce que cela m’ira ? »", `Une photo d’étiquette peut répondre à une petite question importante : quel repère de taille est visiblement fixé à l’unité arrivée ? Elle ne dit pas si l’article ira à une personne. Séparez ces deux questions. Le guide public USFans décrit actuellement la sélection de la couleur, de la taille et de la quantité avant commande, puis l’inspection et les photos en entrepôt. Trois traces existent donc : l’option payée, l’article reçu et l’étiquette visible. Comparez d’abord leur identité. Si la commande indique L et qu’une étiquette cousue nette indique M, l’écart change la décision. Si les deux indiquent L, seule la concordance du label est établie. Largeur, longueur, retrait, coupe, élasticité, confort et rendu sur le corps restent inconnus. L’étiquette est une preuve, pas une cabine d’essayage. Cette limite évite à la fois la fausse assurance et le rejet inutile.`],
      ["Construire la chaîne de preuve avant de zoomer", `Ouvrez le dossier de commande avant de juger l’étiquette. Conservez URL ou identifiant, couleur, taille, quantité, numéro et date de capture. Sauvegardez le tableau de tailles daté s’il a compté, car le vendeur peut modifier options et images. Identifiez ensuite la photo qui montre réellement le label du produit. Autocollant de colis, note d’entrepôt, code vendeur et étiquette cousue sont des objets différents. Pour chaque repère, notez emplacement, caractères lisibles, photo et rattachement au produit, à l’emballage ou au traitement logistique. Cette chaîne est essentielle si deux valeurs se contredisent. Vous pouvez écrire : « option 32, étiquette de ceinture 32, sachet extérieur 34 » sans choisir arbitrairement. Conservez la contradiction et posez une question précise au lieu d’imposer le chiffre attendu.`],
      ["Lire l’étiquette comme une image, pas comme une promesse", `Évaluez d’abord la photo. L’étiquette entière est-elle cadrée ? La netteté distingue-t-elle 6 de 8, M de W ou EU 42 de 47 ? Un reflet, un pli ou une couture masque-t-il un caractère ? Un gros plan rend le code lisible mais peut supprimer le contexte d’attache ; utilisez une vue d’orientation et une vue de détail quand elles existent. Relevez séparément taille nominale, système régional, modèle, matière, entretien et mesure secondaire. Ne complétez jamais un caractère illisible avec l’option commandée : indiquez « incertain ». Un tableau posé dans l’emballage ne prouve pas le label cousu. Une étiquette volante peut décrire la variante commerciale sans confirmer le marquage intérieur. La preuve la plus forte associe texte lisible et lien physique avec l’unité. Sans lisibilité ou contexte, la bonne décision est suspendre ou clarifier, pas valider.`],
      ["Ne pas convertir les systèmes de taille à l’intuition", `Les tailles nominales ne sont pas des unités universelles. Les mêmes lettres varient selon vendeur, coupe et catégorie ; les nombres peuvent appartenir à des systèmes régionaux différents. Un XL visible prouve seulement que l’article porte XL dans ce système, pas qu’il égale un XL de votre garde-robe. Conservez le système exact : EU, US, UK, CN, centimètres, pouces ou code vendeur non expliqué. Ne convertissez que si l’annonce actuelle fournit une correspondance directe enregistrable, et nommez-la correspondance du vendeur, pas règle générale. Pour les chaussures, les valeurs EU et US accolées peuvent être mal lues selon l’angle. Distinguez aussi conseil morphologique et dimensions finies. Une recommandation basée sur taille ou poids du corps n’est pas une mesure à plat. Séparez valeur originale, système et correspondance afin qu’une hypothèse ne ressemble pas à une observation.`],
      ["Utiliser les repères propres à la catégorie sans anticiper l’audit des mesures", `Pour un T-shirt ou un sweat, cherchez le col ou la couture latérale et voyez si l’étiquette d’entretien répète la taille. Pour un pantalon, rapprochez le marquage de ceinture de l’option commandée sans confondre taille nominale et tour fini. Pour les chaussures, contrôlez languette, doublure ou semelle et les deux pieds si possible ; l’autocollant de boîte reste une preuve d’emballage. Chapeaux, ceintures, gants et accessoires réglables peuvent utiliser plages, circonférences ou taille unique. L’objectif reste l’identité du label, pas la dimension exacte. Si le label concorde mais que la taille est critique, transférez la question vers une mesure ciblée avec points de référence nommés. N’inventez pas de précision à partir de perspective, règle inclinée ou objet voisin. La mesure ultérieure est une couche distincte : le label dit comment l’article se nomme ; une photo bien cadrée peut tester ses dimensions.`],
      ["Classer le désaccord avant d’agir", `Il y a écart direct lorsque la commande payée et le label fixé portent des tailles différentes. Il y a conflit contextuel si le produit concorde mais pas la boîte ou le sachet. Il y a ambiguïté si le caractère est flou, coupé ou caché, et incomplétude si aucun repère pertinent n’apparaît. Notez la classe avant de contacter le support. Pour un écart direct, joignez sélection et photo et demandez si l’unité est bien la variante commandée. Pour un conflit, demandez une vue reliant emballage et produit. Pour une ambiguïté, demandez un gros plan lisible avec assez de contexte. Pour une absence, nommez l’emplacement attendu plutôt que « vérifier la taille ». La demande reste observable et évite des affirmations sur authenticité, qualité ou coupe. Une question précise rejoint la chaîne de preuve et peut être vérifiée ensuite.`],
      ["Accepter, suspendre ou clarifier avec des limites explicites", `Acceptez la preuve lorsque l’option payée et le repère fixé concordent, qu’aucun conflit ne subsiste et que vous ne déduisez pas la coupe réelle. Suspendez si image, emplacement ou marqueurs restent incertains. Clarifiez si une photo ou confirmation précise peut fermer l’écart. Dites ce qui passe et ce qui reste ouvert : « Identité acceptée : taille 32 de la commande conforme à l’étiquette de ceinture ; coupe non vérifiée faute de mesure. » Pour suspendre : « Commande EU 42 ; l’image ne montre qu’un 4 coupé. Demander la languette entière. » Si une mauvaise variante est visible et qu’une action après-vente existe, agissez rapidement ; durée de stockage et délai vendeur ne sont pas identiques. Le compte et les conditions actuels déterminent les choix. Cette matrice empêche de transformer un bon label en garantie ou une mauvaise photo en rejet automatique.`],
      ["Laisser un dossier qu’un tiers peut auditer", `Conservez identifiant, taille choisie, système capturé, référence photo, texte exact, emplacement, conflits, décision et date. Ajoutez : « Identité du label contrôlée ; mesures et coupe personnelle non établies. » Si un nouveau gros plan arrive, ajoutez-le sans écraser l’interprétation initiale. On comprend alors le passage de suspendre à accepter ou d’ambiguïté à écart. Retirez adresses, paiements et données de compte inutiles des copies partageables. Dans une commande multiple, chaque unité a sa ligne : un label clair ne prouve pas la taille d’un second article ressemblant. Le principe est volontairement modeste : une étiquette prouve un marquage visible sur un objet reçu. La concordance réduit l’incertitude d’identité, pas celle des mesures, de la construction ou de la coupe. Documenter le fait et sa frontière permet de poser de meilleures questions et de prendre une décision compréhensible plus tard.`],
    ],
  },
  it: {
    sourceNote: "Nota di verifica: la guida pubblica USFans e una pagina pubblica attuale di specifiche sono state controllate l’11 settembre 2026. La guida indica la scelta di colore, taglia e quantità prima dell’ordine, seguita da ispezione e foto in magazzino. Una pagina attuale mostrava taglie selezionabili e un avviso sulle foto QC. Interfaccia e servizi possono cambiare; fanno fede ordine e magazzino attuali.",
    meta: ["Prova dell’etichetta taglia", "Verificato 11 set 2026", "Indipendente"],
    visual: ["Scala delle prove di taglia", [["Ordinato", "Opzione esatta salvata prima del pagamento"], ["Visibile", "Etichetta leggibile sull’unità ricevuta"], ["Confrontato", "Etichetta verificata con l’opzione salvata"], ["Irrisolto", "Misure e vestibilità reale"]]],
    related: [["Leggi la guida generale QC", "/qc"], ["Mappa le prove mancanti", "/articles/usfans-warehouse-evidence-gap-map"], ["Controlla la copertura degli angoli", "/articles/usfans-warehouse-photo-angle-map"]],
    sections: [
      ["Inizia con una domanda più stretta di «Mi starà bene?»", `Una foto dell’etichetta può rispondere a una domanda piccola ma importante: quale indicazione di taglia è visibilmente fissata all’unità arrivata? Non può dire se l’articolo starà bene a una persona. Separa le due domande. La guida pubblica USFans descrive oggi la selezione di colore, taglia e quantità prima dell’ordine, seguita da ispezione e foto in magazzino. Esistono quindi tre registri: opzione pagata, articolo ricevuto ed etichetta visibile. Confronta prima l’identità. Se l’ordine dice L e un’etichetta cucita chiara dice M, c’è una discrepanza decisiva. Se entrambe dicono L, hai confermato solo la concordanza. Larghezza, lunghezza, restringimento, taglio, elasticità, comfort e resa sul corpo restano ignoti. L’etichetta è una prova, non un camerino. Questo limite evita sia falsa sicurezza sia rifiuti inutili.`],
      ["Costruisci la catena delle prove prima di ingrandire", `Apri il registro dell’ordine prima di giudicare il tag. Salva URL o identificatore, colore, taglia, quantità, numero ordine e data di acquisizione. Conserva la tabella taglie datata se era decisiva, perché il venditore può modificare opzioni e immagini. Individua poi la foto che mostra davvero l’etichetta del prodotto. Adesivo del pacco, nota del magazzino, codice venditore ed etichetta cucita sono oggetti differenti. Per ogni marcatore annota posizione, caratteri leggibili, foto e appartenenza a prodotto, confezione o gestione logistica. La catena conta quando due valori discordano. Permette di scrivere: «opzione 32, etichetta cintura 32, busta esterna 34» senza scegliere a caso. Conserva la contraddizione e fai una domanda precisa invece di imporre il numero atteso.`],
      ["Leggi l’etichetta come immagine, non come promessa", `Valuta prima la fotografia. L’intero tag è nell’inquadratura? La nitidezza distingue 6 da 8, M da W o EU 42 da 47? Riflessi, pieghe o cuciture coprono caratteri? Un primo piano rende leggibile il codice ma può eliminare il contesto di fissaggio; usa una vista d’insieme e una di dettaglio quando disponibili. Registra separatamente taglia nominale, sistema regionale, modello, materiale, cura e misura secondaria. Non completare un carattere illeggibile usando l’ordine: scrivi «non chiaro». Una tabella libera nella confezione non prova il label cucito. Un cartellino può identificare la variante commerciale senza confermare il marchio interno. La prova più forte unisce testo leggibile e relazione fisica con l’unità. Se manca leggibilità o contesto, il risultato corretto è sospendere o chiarire, non approvare.`],
      ["Non tradurre i sistemi di taglia per intuizione", `Le taglie nominali non sono unità universali. Le stesse lettere cambiano con venditore, vestibilità e categoria; i numeri possono riferirsi a regioni diverse. Un XL visibile prova solo che l’articolo porta XL in quel sistema, non che equivalga a un XL già posseduto. Conserva il sistema esatto: EU, US, UK, CN, centimetri, pollici o codice non spiegato. Converti solo se l’inserzione attuale offre una corrispondenza diretta salvabile e chiamala mappatura del venditore, non regola globale. Nelle scarpe, valori EU e US affiancati possono essere confusi dall’angolo. Distingui anche consiglio corporeo e dimensioni finite. Una raccomandazione per altezza o peso non è una misura piatta del capo. Separa valore originale, sistema e mappatura così un’ipotesi non sembra osservazione.`],
      ["Usa marcatori specifici senza anticipare una verifica completa delle misure", `Per T-shirt e felpe cerca collo o cucitura laterale e verifica se l’etichetta di lavaggio ripete la taglia. Nei pantaloni confronta il marcatore in vita con l’opzione ordinata senza equiparare numero nominale e misura finita. Nelle scarpe controlla linguetta, fodera o soletta e entrambe le scarpe se possibile; l’adesivo della scatola resta prova della confezione. Cappelli, cinture, guanti e accessori regolabili possono usare intervalli, circonferenze o taglia unica. L’obiettivo è l’identità del label, non la dimensione esatta. Se coincide ma la misura è critica, trasferisci il dubbio a una richiesta mirata con punti di riferimento nominati. Non inventare precisione da prospettiva, righello inclinato o oggetto vicino. La misura successiva è un’altra prova: il tag dice come l’articolo è chiamato; una foto ben impostata può verificarne le dimensioni.`],
      ["Classifica il disaccordo prima di scegliere l’azione", `Una discrepanza diretta esiste quando ordine pagato ed etichetta fissata mostrano taglie diverse. Un conflitto di contesto esiste se il prodotto concorda ma scatola o busta differiscono. C’è ambiguità se il carattere è sfocato, tagliato o nascosto; incompletezza se manca ogni marcatore rilevante. Registra la classe prima di contattare l’assistenza. Per discrepanza, unisci selezione e foto e chiedi se l’unità è la variante ordinata. Per conflitto, chiedi una vista che colleghi confezione e prodotto. Per ambiguità, richiedi un primo piano leggibile con contesto. Per assenza, nomina il punto previsto invece di dire «controlla taglia». La domanda resta osservabile ed evita affermazioni su autenticità, qualità o vestibilità. Una richiesta precisa entra nella catena e può essere rivista.`],
      ["Accetta, sospendi o chiarisci con limiti espliciti", `Accetta la prova se opzione pagata e marcatore fissato coincidono, nessun conflitto resta e non deduci vestibilità reale. Sospendi se immagine, posizione o marcatori sono incerti. Chiarisci se una foto o conferma specifica può chiudere il vuoto. Dichiara ciò che passa e ciò che resta: «Identità accettata: ordine 32 coincide con etichetta in vita; vestibilità non verificata senza misura». Per sospendere: «Ordine EU 42; immagine mostra solo un 4 tagliato. Chiedere linguetta completa». Se è visibile una variante errata e l’interfaccia offre assistenza post-vendita, agisci presto; deposito e finestra di reso non coincidono automaticamente. Conto e condizioni correnti determinano le azioni. La matrice evita che un tag corretto diventi garanzia o una foto scarsa diventi rifiuto automatico.`],
      ["Lascia un record verificabile da un’altra persona", `Salva identificatore, taglia scelta, sistema catturato, riferimento foto, testo esatto, posizione, conflitti, decisione e data. Aggiungi: «Identità dell’etichetta controllata; misure e vestibilità personale non stabilite». Se arriva un nuovo primo piano, aggiungilo senza sovrascrivere l’interpretazione iniziale. Così si capisce perché una sospensione è diventata accettazione o un dubbio discrepanza. Rimuovi indirizzi, pagamenti e dati conto inutili dalle copie condivisibili. Negli ordini multipli ogni unità ha la propria riga: un’etichetta chiara non prova un secondo articolo simile. Il principio è volutamente limitato: un tag prova un indicatore visibile su un oggetto ricevuto. La concordanza riduce l’incertezza d’identità, non quella di misura, costruzione o vestibilità. Registrare fatto confermato e confine restante consente domande migliori e una decisione comprensibile in seguito.`],
    ],
  },
};

export function getUveSizeTagArticle(language) {
  const activeLanguage = localized[language] ? language : "en";
  const entry = localized[activeLanguage];
  return {
    ...uveSizeTagArticleBlueprint,
    title: uveSizeTagArticleBlueprint.title[activeLanguage],
    dek: uveSizeTagArticleBlueprint.dek[activeLanguage],
    sections: entry.sections,
    sourceNote: entry.sourceNote,
    visual: entry.visual,
    related: entry.related,
    articleMeta: entry.meta,
    datePublished: "2026-09-11",
    dateModified: "2026-09-11",
  };
}
