import type { Article } from "./article-data";

type ArticleKey = "qcArticle" | "shippingArticle" | "storageArticle";

export const itArticleSections: Record<ArticleKey, Article["sections"]> = {
  qcArticle: [
    ["Cosa deve fare davvero un foglio Kakobuy", [
      "Molte persone cercano un «foglio Kakobuy» aspettandosi un elenco enorme di prodotti. La quantità, da sola, non indica qualità. Un foglio utile collega una descrizione chiara a una destinazione attiva, registra il prezzo visibile e il contesto della variante e consente di tornare in seguito alle prove originali. Non dovrebbe mai suggerire che un annuncio sia sicuro, autentico o di alta qualità solo perché qualcuno lo ha inserito in una tabella. Il foglio aiuta a scoprire e documentare; la decisione di acquisto resta dell’acquirente.",
      "La nostra regola d’inclusione è quindi semplice: quando vengono controllati, immagine della scheda, nome del prodotto e destinazione devono descrivere lo stesso articolo. Una rotta viene rimossa o ricontrollata se la destinazione cambia, scompare o mostra un prodotto diverso. I prezzi sono fotografie di un momento, non promesse, perché i venditori modificano gli annunci e i cambi valutari si muovono. Questo metodo più ristretto può offrire meno risultati di una lista social non filtrata, ma assegna a ogni risultato una funzione tracciabile nel percorso d’acquisto.",
    ]],
    ["Separare il flusso ufficiale Kakobuy in decisioni", [
      "Il materiale pubblico Kakobuy per principianti descrive il consueto flusso di un agente: scegliere un prodotto su un marketplace cinese, copiarne il link, incollarlo in Kakobuy, selezionare le opzioni, pagare l’articolo, attendere arrivo e controllo qualità in magazzino e poi inviare un pacco internazionale. La sequenza conta perché articolo e trasporto internazionale vengono pagati in fasi diverse. Trattare tutto come un unico checkout rende più difficile capire a quale decisione appartengano costi e ritardi.",
      "Un acquirente disciplinato si ferma a quattro passaggi. Primo, l’annuncio di origine: prodotto, venditore e opzione sono comprensibili? Secondo, il registro dell’ordine: taglia, colore, quantità e variante sono corretti? Terzo, le prove del magazzino: l’articolo fotografato corrisponde visibilmente al registro? Quarto, il pacco: imballaggio, linea, dichiarazione e stima finale sono accettabili? Il foglio dà il massimo valore quando porta informazioni corrette da un passaggio al successivo.",
    ]],
    ["Creare il registro dell’ordine prima di pagare", [
      "Salva l’URL esatto, il titolo dell’annuncio, la variante selezionata, la quantità, il prezzo mostrato dal venditore e qualsiasi tabella taglie o immagine di opzione che abbia influenzato la scelta. Aggiungi una data perché gli annunci attivi cambiano. Se un colore è indicato solo da un numero o da una miniatura, conserva anche quel dettaglio. Quando arrivano le foto del magazzino, la memoria è un riferimento debole; un registro compatto permette di confrontare ciò che è arrivato con ciò che è stato davvero scelto, non con un post simile visto giorni prima.",
      "Presta particolare attenzione alle opzioni tradotte. La traduzione automatica può rendere ambigui materiali, set e colorazioni. Non indovinare quando due varianti sembrano simili. Apri la pagina di origine, confronta le immagini delle opzioni e usa una nota d’ordine solo se risolve una reale ambiguità. Note lunghe o contraddittorie possono creare nuovi errori. Se il venditore non fornisce una misura necessaria, considera l’assenza come incertezza invece di inventare una previsione precisa della vestibilità.",
    ]],
    ["Leggere il prezzo come una pila di costi", [
      "Il prezzo del prodotto è solo il primo livello. Un acquisto tramite agente può includere consegna nazionale dal venditore al magazzino, costo del canale di pagamento, servizi opzionali e in seguito spedizione internazionale. La pagina Services & Fees di Kakobuy afferma attualmente che il servizio base dell’agente non aggiunge una commissione di gestione oltre a prodotto e spedizione, mentre i servizi facoltativi possono costare di più. La guida ai pagamenti mostra oggi per PayPal il 3,5% più 0,30 USD. Sono condizioni attuali, non costanti permanenti.",
      "La distinzione è importante per i contenuti SEO: ripetere un prezzo attraente senza il resto dei costi fuorvia il lettore. I nostri importi in USD sono conversioni approssimative da prezzi visibili in CNY ed escludono servizi e trasporto. Prima di pagare controlla il checkout Kakobuy in tempo reale e il metodo scelto. Prima di inviare il pacco, consulta di nuovo lo stimatore. Se una condizione attuale di Kakobuy contraddice una vecchia guida, deve prevalere la pagina in diretta.",
    ]],
    ["Cosa dice Kakobuy sul controllo all’arrivo", [
      "La pagina pubblica di Kakobuy afferma che, dopo l’arrivo dei prodotti in magazzino, il controllo qualità copre elementi visibili come difetti, taglia e colore. È utile, ma non significa che vengano verificati ogni materiale, misura o dettaglio nascosto di costruzione. Le fotografie del magazzino provano ciò che la fotocamera può mostrare. Non certificano durata, comfort, composizione o autenticità e non rivelano un difetto nascosto dentro una suola, una fodera o un componente elettronico.",
      "L’avviso della piattaforma del 10 maggio 2026 sui recenti problemi di visualizzazione di alcune immagini QC ricorda di separare l’articolo fisico dall’interfaccia che lo presenta. L’avviso indicava che il problema non influiva sullo stoccaggio né sul normale invio dei pacchi. Se un’immagine manca o non si carica, non trattare l’assenza come approvazione o rifiuto. Ricontrolla la pagina, contatta l’assistenza quando serve e attendi le prove necessarie alla decisione.",
    ]],
    ["Usare una revisione QC su tre livelli", [
      "Il primo livello è l’identità. Conferma quantità, colore ordinato, etichetta taglia, variante, accessori visibili e forma generale. Se appare l’opzione sbagliata, fermati e documentala. Il secondo livello è la costruzione. Per le scarpe confronta punta, altezza del tacco, allineamento dei pannelli, forma della suola, cuciture e colla evidente. Per l’abbigliamento esamina davanti, dietro, collo, maniche, posizione di stampa o ricamo, cuciture, macchie e buchi. Per borse e accessori verifica misure, colore della ferramenta, chiusure, angoli e finitura dei bordi.",
      "Il terzo livello riguarda le prove specifiche per decidere. Chiedi cosa potrebbe cambiare la risposta da accettare a restituire. Se la vestibilità dipende dalla larghezza del petto, una foto con righello vale più di un’altra immagine estetica. Se preoccupa la chiusura di una borsa, chiedi quell’angolazione e non un primo piano generico. La prospettiva può deformare le proporzioni, quindi confronta più viste prima di dichiarare un’asimmetria. Descrivi il problema per posizione e caratteristica osservabile — «tacco destro, bordo esterno, cucitura aperta» — invece di dire solo «scarsa qualità».",
    ]],
    ["Non confondere durata dello stoccaggio e tempo di reso", [
      "Le informazioni pubbliche Kakobuy pubblicizzano attualmente 100 giorni di stoccaggio gratuito. Questo offre tempo per attendere altri articoli e pianificare un pacco consolidato, ma non crea una finestra di reso del venditore di 100 giorni. Reso e cambio dipendono dal venditore specifico, dallo stato dell’ordine, dalle condizioni del prodotto e dalla procedura della piattaforma. Kakobuy pubblica anche una «5-Day Return/Exchange Guarantee», descritta come servizio post-vendita del venditore per prodotti supportati di marketplace terzi. Non va presentata come copertura universale.",
      "Ispeziona subito quando l’ordine arriva in magazzino. Se è visibile una differenza, conserva l’immagine pertinente, indica l’opzione selezionata e spiega lo scarto mentre l’ordine è ancora facile da rintracciare. Evita modifiche irreversibili prima dell’accettazione. Rifiuto del venditore, spedizione nazionale di ritorno e viaggio del sostituto al magazzino possono influire sull’esito. L’aiuto Kakobuy osserva che un prodotto cambiato può impiegare circa 7–20 giorni per rientrare in stoccaggio, a seconda del venditore.",
    ]],
    ["Una regola pratica per ogni risultato del foglio", [
      "Accetta quando l’articolo fotografato corrisponde alla variante registrata, non compare alcun difetto visibile decisivo e l’incertezza rimanente è accettabile rispetto al prezzo. Chiedi altre prove quando un’angolazione o una misura assente potrebbe davvero cambiare la decisione. Apri una richiesta post-vendita quando esiste una discrepanza chiara e documentabile o un difetto visibile e l’ordine è ancora idoneo. Rifiutare per un’angolazione poco gradevole spreca tempo; accettare senza controllare l’identità annulla lo scopo del QC.",
      "Dopo l’accettazione aggiorna il foglio con data di arrivo, peso stimato, esigenze di imballaggio e scadenza personale per il pacco. Controlla di nuovo il link prima di condividerlo. Il foglio passa così da elenco statico a piccolo registro di verifica. Sostiene anche contenuti Google migliori: ogni raccomandazione può essere spiegata con metodo, limiti e fonti attuali, anziché con affermazioni vuote come «miglior venditore», «qualità 1:1» o «sicuro garantito».",
    ]],
  ],
  shippingArticle: [
    ["Perché lo stimatore serve a pianificare, non è un prezzo finale", [
      "Kakobuy offre una pagina per stimare le spese di spedizione, il luogo corretto per confrontare le linee disponibili prima che esista il pacco finale. Una stima dipende comunque dai dati inseriti e dalle regole della linea, non dalla scatola già imballata. Confezione del venditore, reimballaggio del magazzino, categoria dell’articolo e metodo di fatturazione del vettore possono cambiare il risultato. Usala per confrontare scenari e creare un intervallo di budget; non pubblicare un numero come prezzo permanente per un paese.",
      "Un confronto utile parte da destinazione, peso imballato realistico e dimensioni approssimative. Poi annota disponibilità, restrizioni, tracciamento, condizioni di compensazione e valuta mostrata. Ripeti il controllo subito prima dell’invio perché nomi delle linee, sconti e avvisi operativi possono cambiare. La cronologia degli aggiornamenti Kakobuy — compresi avvisi su linee e tracking — dimostra perché un articolo duraturo deve spiegare il metodo e rinviare ai dati in tempo reale per la scelta finale.",
    ]],
    ["Capire peso reale e peso volumetrico", [
      "Il peso reale è il valore sulla bilancia dopo l’imballaggio. Il peso volumetrico trasforma lo spazio occupato in una cifra fatturabile, spesso moltiplicando lunghezza per larghezza per altezza e dividendo per un divisore specifico della linea. Alcune linee addebitano il maggiore tra peso reale e volumetrico; altre usano soglie, arrotondamenti o regole di categoria diverse. Il divisore esatto deve provenire dai dettagli attuali della linea, non da una vecchia schermata sui social.",
      "Prodotti densi come indumenti piegati tendono ad avvicinarsi al peso reale. Scarpe ingombranti, scatole rigide, cappotti imbottiti e riempitivo protettivo possono occupare molto più spazio di quanto suggerisca la massa. Ecco perché due pacchi con lo stesso peso sulla bilancia possono produrre stime diverse. Registra peso e dimensioni nel confronto. Se l’interfaccia mostra solo una stima iniziale, lascia margine per la misurazione finale del magazzino e gli scaglioni di fatturazione del vettore.",
    ]],
    ["Mappare l’intera struttura dei costi prima della spedizione", [
      "Il costo internazionale si aggiunge alle spese precedenti: prezzo del prodotto, possibile consegna nazionale del venditore, commissioni di pagamento e servizi opzionali del magazzino. La pagina Services & Fees di Kakobuy afferma attualmente che il servizio base dell’agente non prevede una commissione di gestione separata da articolo e spedizione, mentre si possono scegliere servizi aggiuntivi. La stessa sezione ufficiale dice che la dichiarazione doganale del pacco costa in genere 8 RMB, secondo il metodo. Verifica queste condizioni sulla pagina attiva al momento dell’invio.",
      "Non sommare numeri estranei in un’unica «percentuale di commissione». Un costo di pagamento non è lo spread di cambio; la consegna nazionale non è il trasporto internazionale; il rinforzo opzionale non è una commissione dell’agente; i dazi riscossi a destinazione non sono necessariamente inclusi nella stima. Un budget trasparente separa ogni livello e segnala i valori ignoti. Questo semplifica il confronto delle linee e impedisce che un prezzo attraente nasconda il costo totale a destinazione.",
    ]],
    ["L’imballaggio è una decisione di costo e protezione", [
      "Rimuovere una scatola da scarpe può ridurre le dimensioni, ma elimina struttura e può diminuire il valore di regalo o rivendita. Il sottovuoto comprime gli indumenti morbidi, ma non è adatto a prodotti che si sgualciscono molto o dipendono dalla forma. Un rinforzo aggiunge peso e talvolta volume, ma può avere senso per contenuti fragili o un viaggio con molti passaggi. Non esiste una regola universale «rimuovi tutto l’imballaggio»; la scelta dipende dall’articolo e dalle conseguenze del danno.",
      "Dividi l’imballaggio in tre gruppi. Quello essenziale protegge forma, vetro, ferramenta o materiale sensibile all’umidità. Quello utile raggruppa piccole parti o identifica la variante. Quello decorativo migliora la presentazione ma protegge poco nel trasporto. Rimuovi prima il terzo gruppo se il problema è il volume. Se richiedi un servizio, controllane il prezzo attuale e specifica il risultato. «Rimuovere scatole da vendita; tenere supporti interni» è più attuabile di «renderlo economico ma sicuro».",
    ]],
    ["Consolidare con criterio durante la finestra di stoccaggio", [
      "Le informazioni ufficiali Kakobuy annunciano 100 giorni di stoccaggio gratuito e collegano espressamente questo periodo all’acquisto di più articoli e alla spedizione congiunta. Consolidare può ridurre gli imballaggi esterni ripetuti ed evitare diversi piccoli pacchi internazionali. Offre anche tempo per attendere prodotti compatibili. Ma più grande non significa automaticamente più economico: una scatola sovradimensionata può attivare il peso volumetrico, superare un limite o mescolare prodotti soggetti a restrizioni e comuni, riducendo le linee disponibili.",
      "Raggruppa i prodotti per destinazione, urgenza, fragilità e compatibilità della linea. Un ordine lento ed economico di abbigliamento non deve sempre viaggiare con un articolo urgente o fragile. Quando possibile confronta almeno due scenari: una scatola consolidata e una divisione logica. Includi le preferenze di imballaggio in entrambi. L’obiettivo non è il minor numero di pacchi, ma il costo totale accettabile più basso per protezione, velocità e rischio davvero necessari.",
    ]],
    ["L’idoneità della linea cambia con prodotto e destinazione", [
      "Batterie, liquidi, magneti, beni di marca, prodotti simili ad alimenti e altre categorie sensibili possono ridurre le linee mostrate o richiedere gestione speciale. La disponibilità varia anche con la destinazione e le operazioni correnti. Non promettere mai che una rotta accetterà un articolo solo perché una spedizione precedente ha funzionato. Usa lo stimatore attuale e l’interfaccia del pacco dopo la classificazione in magazzino. Se sembra errata, chiedi all’assistenza prima di pagare anziché presumere che comparirà una nuova linea.",
      "Gli avvisi legati al tempo vanno trattati come prove datate. Kakobuy ha pubblicato, per esempio, un aggiornamento sulle linee EU Duty-Free il 30 giugno 2026. Conferma un cambiamento operativo di quel momento, non giustifica l’affermazione permanente che ogni futuro pacco europeo sarà esente da dazi. Nei contenuti SEO indica la data, spiega che le condizioni possono cambiare e non trasformare una promozione o un aggiornamento temporaneo in caratteristica eterna della piattaforma.",
    ]],
    ["Dogana, dichiarazione e imposte a destinazione", [
      "Una linea può aiutare con trasporto e procedure doganali, ma l’acquirente resta responsabile di capire le regole della destinazione e fornire informazioni veritiere. Valore dichiarato, descrizione, quantità e soglie locali possono influire sulla valutazione. Le etichette tax-free o duty-paid devono essere lette secondo le condizioni correnti. Nessuna guida indipendente può garantire che un pacco eviti ispezioni, costi o ritardi, e la sottovalutazione non va presentata come trucco di spedizione.",
      "Controlla l’autorità doganale della destinazione quando contano valore o restrizioni. Conserva prove di acquisto e pagamento, usa dati esatti del destinatario e rivedi la dichiarazione prima dell’invio. Se Kakobuy mostra un servizio opzionale o istruzioni specifiche della linea, leggi cosa comprendono. Services & Fees indica oggi che la dichiarazione costa in genere 8 RMB secondo il metodo; è un servizio di piattaforma, non il dazio che l’autorità di destinazione può imporre.",
    ]],
    ["La checklist finale del pacco", [
      "Prima di pagare verifica nome, indirizzo, telefono e codice postale del destinatario; elenco e quantità; classificazione di prodotti soggetti a restrizioni; imballaggio richiesto; dimensioni misurate o stimate; regola del peso fatturabile; tracking e compensazione; dichiarazione; totale mostrato. Salva il numero del pacco e una schermata della linea selezionata. Questo registro vale più di una promessa generica se il tracking si ferma o serve parlare con l’assistenza.",
      "Scegli la linea più adatta alla tua tolleranza per costo, ritardo e perdita, non semplicemente quella con la stima più breve. Le finestre di consegna sono stime perché dogana, capacità dei voli, volume stagionale e passaggio locale non sono completamente sotto il controllo dell’agente. Una buona guida Kakobuy insegna a confrontare opzioni attuali. Non dichiara una linea universalmente più economica, un numero garantito di giorni o un divisore valido per ogni destinazione.",
      "Dopo il pagamento segui gli eventi anziché aggiornare aspettandoti un movimento quotidiano. Partenza export, assegnazione del volo, dogana e consegna al vettore locale possono creare periodi silenziosi. Confronta l’ultimo evento con il modello di tracking dichiarato e contatta l’assistenza con il numero del pacco se la pausa supera chiaramente le indicazioni attuali. Non usare i tempi di un altro acquirente come scadenza: linee con lo stesso nome possono partire in date diverse, incontrare carichi doganali differenti ed entrare in reti locali diverse.",
    ]],
  ],
  storageArticle: [
    ["Cosa significa la dichiarazione sui 100 giorni di stoccaggio", [
      "La presentazione pubblica del servizio e il materiale Kakobuy per principianti pubblicizzano attualmente 100 giorni di stoccaggio gratuito nel magazzino. Lo stesso materiale invita ad acquistare altri prodotti e spedirli insieme per risparmiare sul trasporto internazionale. È una dichiarazione concreta della piattaforma, verificata il 29 agosto 2026. Va comunque confermata nell’account e nella guida attuali, perché le politiche di magazzino possono cambiare dopo la pubblicazione di un articolo.",
      "Lo stoccaggio inizia quando il magazzino accetta l’articolo, non quando lo scopri o paghi il venditore. Prodotti diversi possono quindi avere date di arrivo e giorni rimanenti differenti. Crea un semplice registro con numero d’ordine, prodotto, data di magazzino, stato QC, decisione sul reso, peso stimato e scadenza personale per il pacco. Imposta la tua scadenza prima del limite della piattaforma, così un articolo dimenticato o un ritardo dell’assistenza non obbliga a decidere di fretta.",
    ]],
    ["Separare i diversi orologi prima di decidere", [
      "Esistono almeno quattro orologi. Quello della spedizione del venditore corre tra acquisto e consegna a Kakobuy. Quello post-vendita controlla l’idoneità per annullamento, reso o cambio. Quello di magazzino stabilisce quanto può restare un articolo accettato. Quello del transito internazionale inizia solo dopo l’invio del pacco e la consegna alla linea scelta. Possono sovrapporsi, ma uno non estende automaticamente l’altro.",
      "L’errore più comune è pensare che 100 giorni di stoccaggio creino 100 giorni per restituire. Non è così. Lo stoccaggio è un servizio di magazzino; il reso dipende dal venditore, dallo stato dell’ordine, dalle condizioni dell’articolo e dalla procedura Kakobuy. Ispeziona presto anche se vuoi conservare per settimane. Il periodo lungo è utile soprattutto per consolidare e pianificare le linee dopo che l’articolo ha superato la revisione.",
    ]],
    ["L’annullamento dipende dallo stato dell’ordine", [
      "Le indicazioni di annullamento pubblicate da Kakobuy distinguono gli stati. La guida dice che quando l’ordine mostra «paid» l’acquirente può contattare il servizio clienti per annullare. Quando mostra «Processing», l’addetto potrebbe aver già completato l’acquisto anche se il commerciante non ha spedito, quindi l’annullamento diventa una diversa richiesta operativa. Dopo la spedizione del venditore o l’arrivo del prodotto, non equivale più ad annullare un pagamento intatto.",
      "Agisci rapidamente con informazioni precise: numero d’ordine, azione richiesta e motivo. Non creare un ordine duplicato prima della conferma. Se il venditore ha già accettato o spedito, possono esserci un costo nazionale di reso o un rifiuto. Per questo una guida dovrebbe descrivere gli stati, non promettere «annullamento gratuito». Il registro in tempo reale e la risposta dell’assistenza determinano cosa è possibile per quella transazione.",
    ]],
    ["Ispezionare subito all’arrivo in magazzino", [
      "La pagina pubblica Kakobuy dice che il controllo in magazzino copre elementi visibili, compresi difetti, taglia e colore, dopo l’arrivo del prodotto. Usa quel momento per confermare prima l’identità: quantità, opzione ordinata, colore, etichetta taglia e accessori visibili. Poi esamina forma, costruzione e danni. Conserva misure o immagini del venditore che contano. Un confronto rapido è più affidabile che ricostruire l’ordine dopo l’arrivo di molti altri prodotti.",
      "Le foto QC riducono l’incertezza visibile; non certificano autenticità, composizione, comfort, funzionamento elettrico o durata. Se manca una vista o misura essenziale, chiedi solo ciò che potrebbe cambiare la decisione. Se l’interfaccia non mostra un’immagine, ricorda che l’avviso Kakobuy del 10 maggio 2026 separava un problema di visualizzazione dalle funzioni di stoccaggio e invio. Conferma le prove invece di presumere che l’articolo fisico sia perso.",
    ]],
    ["Capire l’etichetta 5-Day Return/Exchange", [
      "Kakobuy ha una pagina ufficiale intitolata «What is 5-Day Return/Exchange Guarantee?». La descrive come uno speciale servizio post-vendita offerto dai venditori su prodotti supportati di marketplace terzi. Le parole contano: è una copertura legata al venditore, non la prova che ogni annuncio possa essere restituito per qualsiasi motivo. Controlla se l’articolo dispone del servizio e leggi le condizioni attuali prima di includere l’etichetta nella decisione d’acquisto.",
      "Un cambio aggiunge un secondo viaggio nazionale. La guida Kakobuy dice che il prodotto torna al venditore e viene spedito di nuovo e che il rientro in magazzino può richiedere circa 7–20 giorni secondo il venditore. Non è un tempo garantito. Disponibilità, risposta, trasporto e un altro controllo possono influire. Se il tempo conta più del mantenere l’articolo, confronta separatamente cambio, reso e riacquisto, e accettazione.",
    ]],
    ["Mantenere l’idoneità e descrivere i fatti", [
      "Evita lavori irreversibili a valore aggiunto, rimozione di etichette o smaltimento di imballaggi importanti prima della decisione. L’idoneità può dipendere da condizioni e regole del venditore. Quando segnali un problema, identifica variante ordinata, variante fotografata, immagine esatta e differenza osservabile. «L’etichetta dice 42; l’ordine dice 44» è attuabile. «Sembra falso» non è un rapporto preciso e chiede all’assistenza di dedurre fatti che una fotografia potrebbe non dimostrare.",
      "Prevedi possibili costi nazionali, rifiuto del venditore o servizi non rimborsabili. Se il problema è un errore visibile del venditore, documentalo; se riguarda preferenza personale o una scelta di taglia contraria all’annuncio, l’esito può cambiare. Non affermare mai che il link di un foglio garantisca un reso gratuito. Una selezione può solo conservare la rotta originale e facilitare il confronto finché la procedura di piattaforma è aperta.",
    ]],
    ["Usare lo stoccaggio per costruire un pacco migliore", [
      "Una volta accettato l’articolo, lo stoccaggio diventa spazio di pianificazione. Attendi prodotti compatibili, confronta la stima combinata, decidi quali confezioni commerciali sono necessarie e controlla le linee. Il materiale Kakobuy per principianti collega i 100 giorni alla combinazione degli articoli. Il possibile risparmio deriva dall’evitare scatole esterne ripetute e componenti fissi, non dalla garanzia che ogni pacco più grande costi meno.",
      "Prova almeno due scenari se la spedizione è ingombrante o mista: consolidata e separata con logica. Dividi fragili da comprimibili, urgenti da quelli che possono attendere e prodotti sensibili se bloccano linee ordinarie. Monitora la data di magazzino più vecchia e lascia tempo per reimballaggio o assistenza. Una scadenza personale circa due settimane prima del limite annunciato crea un margine pratico senza cambiare la regola ufficiale.",
    ]],
    ["Una semplice routine settimanale di magazzino", [
      "Una volta a settimana, dividi gli articoli in cinque stati: in attesa di QC, servono altre prove, post-vendita aperto, accettato per il pacco o tenuto per consolidamento. Annota prossima azione e data. Controlla più spesso i casi post-vendita perché le scadenze del venditore possono essere più brevi dello stoccaggio. Riapri lo stimatore quando cambia il pacco probabile. Rimuovi i link morti dai fogli pubblici invece di lasciare che una guida porti a destinazioni non correlate.",
      "Questa routine trasforma l’attesa passiva in operazioni controllate. Produce anche contenuti editoriali migliori: i fatti hanno date, le affermazioni sono attribuite, le condizioni variabili vengono indicate e le decisioni spiegate. È più utile a un visitatore da ricerca di un centro assistenza copiato o di una recensione inventata. Account attivo, stato dell’ordine e guida Kakobuy corrente restano l’autorità per la transazione; l’articolo fornisce il quadro per leggerli con attenzione.",
      "Quando un articolo si avvicina alla scadenza personale, decidi in base alle prove già disponibili invece di attendere un pacco futuro perfetto. Chiudi le domande QC, controlla se il post-vendita è ancora aperto e confronta la spedizione con e senza l’articolo. Se un prodotto economico blocca tutte le linee adatte, una decisione separata può costare meno che forzarlo nella scatola principale. Invia gli articoli accettati con tempo sufficiente per imballaggio e misurazione prima del limite annunciato e conserva schermate del magazzino e della richiesta per recuperare date e istruzioni durante l’assistenza.",
    ]],
  ],
};
