import type { Language } from "./site-content";
import { localizedArticleExtras } from "./article-localized-extras";
import { localizedArticleExpansions } from "./article-localized-expansions";
import { localizedArticleFourths, localizedArticleSeconds } from "./article-localized-seconds";

export type Article = { title: string; deck: string; read: string; sections: { title: string; paragraphs: string[]; bullets?: string[] }[]; sources: { label: string; href: string }[] };

const spreadsheetEn: Article = {
  title: "How to use a LoveGoBuy spreadsheet without saving weak links",
  deck: "A practical search-to-shortlist method for comparing product routes, images, measurements, prices and likely shipping impact.", read: "16 minute read · checked 1 Sep 2026",
  sections: [
    { title: "A spreadsheet is a starting point", paragraphs: ["A LoveGoBuy spreadsheet can make a large product directory easier to browse, but it should not make the decision for you. Each row is a lead: a title, image, price reference, category or destination that still needs to be checked. Product pages change, options move, prices are updated and sellers can replace images. Treat the sheet as an index rather than a permanent catalogue.", "This distinction matters because the cleanest spreadsheet can still contain stale or mismatched routes. A large item count is not proof of current stock, reliable sizing or useful quality-control evidence. The value of the sheet is the time it saves while narrowing your search—not any guarantee attached to the row.", "LoveGoBuy’s indexed homepage currently presents three discovery inputs—product name, link and photo—and separates Guide and Estimation as their own entry points. That is a useful clue for search behaviour: a spreadsheet works best as one route into a broader research process. It can supply a name or link, but the live product page, warehouse evidence and current shipping estimate remain separate checkpoints. A row should therefore be written so another person could reproduce the search without trusting the spreadsheet author." ]},
    { title: "Choose the category before the product", paragraphs: ["Start with the object you need: shoes, hoodie, jacket, jersey, bag, accessory or electronics. A mixed page encourages unfair comparisons. A watch looks novel after several shirts, and a low-priced T-shirt can make a heavy jacket seem expensive even though the products answer completely different needs.", "Category-first browsing gives every candidate the same questions. For garments, compare chest, length, shoulder, fabric and print or embroidery details. For shoes, compare profile, toe, heel, outsole, tongue and an insole reference. For bags, inspect dimensions, interior, closures, straps, hardware and empty weight.", "Build a category brief before opening dozens of tabs. Write the intended use, the size or dimensions that must work, the maximum source-price range, the details that would cause rejection and the likely shipping sensitivity. A jersey brief might prioritise chest width, print placement and selected version; a footwear brief might prioritise insole length, pair symmetry and whether the box is worth its volume. This prevents a visually exciting result from silently changing the original requirements."], bullets: ["One category", "Three nearby candidates", "One unanswered question", "One date checked"]},
    { title: "Open the destination and inspect the handoff", paragraphs: ["After selecting a promising row, open its destination and place the two views side by side. Does the title still describe the same item? Does the main image match? Is the intended colour or size option visible? Do the measurements belong to the selected variant? A converted link can make a source page easier to reach, but it cannot confirm the option, seller, stock or current price.", "If the destination displays many unrelated products, stop and identify the exact option before proceeding. If the image or title has changed, remove the row until the relationship can be explained. A weak handoff creates uncertainty in every later step, including QC review and parcel planning.", "Capture only fields that remain useful after the page changes: destination URL, source marketplace when visible, selected variant text, displayed price and check date. Do not copy a promotional badge as if it were a product specification. If a row redirects, lands on a different image or opens an option group that cannot be mapped to the spreadsheet, mark it unresolved instead of guessing. Search quality improves when weak routes are removed quickly rather than preserved to make the sheet look larger." ]},
    { title: "Score visible evidence, not enthusiasm", paragraphs: ["Give one point for each useful field: the route matches; the item is in the right category; QC images show relevant details; measurements or sizing are present; the price makes sense beside similar candidates; shipping weight is considered; and you can explain why the item remains on the shortlist. Six or seven points justify more research. Four or five indicate missing information. Three or fewer usually means a stronger candidate should be found first.", "Labels such as best, must buy, popular or verified do not earn a point by themselves. They describe attention or marketing, not evidence. A low price also cannot compensate for an unclear variant, missing measurements or a destination that no longer matches.", "Keep the score diagnostic rather than decorative. A five-point candidate missing only a packed-weight estimate is different from a five-point candidate with a mismatched route and no measurements. Record the missing fields beside the score so the next action is obvious. The aim is not to manufacture a ranking number; it is to reveal which candidate can be checked efficiently and which one depends on assumptions. This also produces more credible page copy because each recommendation has a visible reason." ]},
    { title: "Read photos for a specific job", paragraphs: ["QC photos are useful only when they answer category-specific questions. First confirm identity and variant. Second inspect construction details such as seams, edges, closures, print placement, hardware or sole shape. Third look for fit, dimensions or another stable scale reference.", "Repeated wide shots do not replace a close-up, and a dramatic angle can hide proportion. If colour is important, remember that warehouse lighting and camera processing can shift it. Images can reveal visible mismatches, but they cannot prove material composition, function, authenticity or long-term durability.", "LoveGoBuy product pages currently advertise three to eight free high-definition quality-inspection photos. The number is helpful, but coverage matters more than count. Three sharp views that establish the variant, both important sides and a measurement can be more useful than eight distant angles. When a spreadsheet includes a QC note, say which question the set answers—such as insole length, print alignment or bag hardware—instead of writing the vague label ‘good QC’." ]},
    { title: "Add price and shipping context", paragraphs: ["The source price is only one component of the decision. Heavy footwear, structured bags, thick outerwear and boxed products can create more chargeable weight than a thin shirt. Estimate item weight, likely packaging and parcel volume before comparing value.", "LoveGoBuy’s public shipping estimator describes dimensional weight and shows a commonly published calculation of length × width × height in centimetres divided by 6000. The applicable divisor, route, restrictions and price can change, so use the current official estimator for real planning rather than copying a figure from an old guide.", "The estimator also warns that parcel size matters as much as weight and recommends entering length, width and height accurately. For a shortlist, add a simple shipping-risk label: low for compact garments, medium for ordinary footwear or bags, and high for bulky outerwear, rigid boxes or restricted goods. This label is not a quote. It is a reminder to compare the live route before a cheap source price is allowed to decide the ranking." ]},
    { title: "Write a short decision note", paragraphs: ["A reusable note is more valuable than a collection of open tabs. Record keep or remove, the visible evidence, the most important unanswered question, the closest alternative and the date checked. The note forces a reason for saving the row and makes later rechecking faster.", "An example might read: Keep for comparison; route and colour match; useful front, back and measurement views; chest size still needs confirmation; closest alternative is slightly cheaper but has no size chart; checked 31 August 2026.", "Use neutral language in the note. ‘The available views show even print placement’ is evidence; ‘premium quality’ is an unsupported conclusion. ‘Displayed source price was X on the check date’ is traceable; ‘cheapest’ requires a defined comparison set. If an affiliate, referral or converted link is used, keep that separate from the evidence statement. Clear wording helps both the buyer and search engine understand that the page is a research guide, not a seller guarantee." ]},
    { title: "Recheck at the moment that matters", paragraphs: ["Before an order or parcel action, open the live destination again. Confirm selected option, price, availability, measurements and any product restrictions. Use current official channels for accounts, payments, support, returns and shipping lines. A well-researched shortlist reduces avoidable uncertainty, but it does not transfer responsibility away from the buyer or the current transaction service.", "The best spreadsheet workflow is deliberately small: one category, three candidates, the same evidence questions and a final recheck. It is slower than saving every attractive thumbnail and much faster than resolving mistakes after payment or international shipment.", "LoveGoBuy’s indexed order interface shows multiple states, including pending, paid, purchasing, shipped, completed, cancelled and in-warehouse stages. Those labels reinforce why a spreadsheet should stop at discovery: transaction state belongs to the live account, not to an external guide. Recheck the row before payment, review warehouse evidence before parcel submission and use the current parcel interface for delivery decisions. A static article should never claim an order state, deadline or refund outcome it cannot see." ]},
  ],
  sources: [{label:"LoveGoBuy official site and search entry",href:"https://www.lovegobuy.com/"},{label:"LoveGoBuy warehouse interface",href:"https://www.lovegobuy.com/warehouse/index"},{label:"LoveGoBuy order interface",href:"https://www.lovegobuy.com/order/index"},{label:"Live product directory",href:"https://cnfansge.com/AllProducts/"}],
};

const qcEn: Article = {
  title: "LoveGoBuy QC photo guide: read warehouse images in three passes", deck: "A category-specific method for confirming the item, inspecting construction and finding useful measurement evidence.", read: "15 minute read · checked 1 Sep 2026",
  sections: [
    {title:"What QC photos can—and cannot—do",paragraphs:["Quality-control photos show the item that reached a warehouse at a particular moment. They can help reveal a wrong colour, incorrect option, visible damage, uneven print, missing part or measurement problem before an international parcel is submitted. That makes them one of the most useful checkpoints in an agent workflow.","They are still photographs, not guarantees. They cannot prove fibre content, authenticity, electronic function, internal construction, long-term durability or successful delivery. The right goal is to reduce visible uncertainty, not to turn an image set into a promise.","LoveGoBuy’s indexed product pages advertise three to eight free high-definition inspection photos. That is the strongest official fact to build this guide around: buyers should expect a photo set, but the page does not say that every possible defect or measurement will appear automatically. Read the supplied set first, identify the one missing view that could change the decision and keep any request specific. ‘Show the zipper teeth and slider straight on’ is actionable; ‘check quality’ is not."]},
    {title:"Pass one: confirm identity and variant",paragraphs:["Place the listing, spreadsheet row and QC set beside one another. Check product type, colour, pattern, selected size or option and the features that distinguish one variant from another. A photo set can look excellent while belonging to the wrong colour or a generic sample.","Look for consistency across all views. The left and right shoe should belong to the same pair; a garment label should agree with the selected size; a bag interior should match the exterior style. Stop if images appear reused or the destination has changed.","Write the expected identity before opening the gallery: product type, colour, selected size, version and two distinguishing features. Then test every frame against that short list. This protects against confirmation bias, because you are not deciding what matters after seeing the photos. If the listing contains several variants, record the exact option text rather than relying on a thumbnail. A correct product in the wrong size or version is still an identity failure, even if its construction looks clean."]},
    {title:"Pass two: inspect construction",paragraphs:["Choose inspection points that matter for the category. Clothing needs seams, hems, cuffs, collar, print or embroidery, fabric texture and lining where relevant. Shoes need both side profiles, toe shape, heel, outsole, tongue and stitching. Bags need edges, closures, straps, hardware and interior. Electronics need ports, labels, included components and visible condition.","Zooming is useful only when the original image is sharp enough. Repeated distant views do not answer detail questions. If a critical area is missing, identify the exact view or measurement needed instead of requesting a vague additional photo.","Separate cosmetic variation from a decision-changing problem. A loose thread, small surface mark, uneven pair, damaged closure or missing component should be described by location and visibility. Avoid diagnosing causes from a photograph. ‘The left heel appears higher in the rear view’ is more accurate than declaring a manufacturing defect. When two frames disagree, use the straighter, sharper view and ask for one controlled comparison rather than treating the most alarming angle as definitive."]},
    {title:"Pass three: find scale and measurements",paragraphs:["Size labels vary. A stable measurement is more useful than a familiar label alone. For garments, compare chest, length, shoulder, sleeve, waist or inseam with an item that fits you. For shoes, look for an insole length or size reference. For bags and accessories, use dimensions or a ruler rather than visual scale.","Check that the chart belongs to the current product and option. Seller charts, spreadsheet notes and warehouse measurements may use different methods. Record whether a measure is laid flat, circumference, internal length or external dimension.","A ruler only helps when its endpoints and measurement path are visible. For a flat chest measure, check that the garment is not folded and that the tape runs from one underarm point to the other. For insole length, confirm the insert is flat and both ends are shown. For a bag, distinguish external width from usable internal space. Small method differences can create several centimetres of disagreement, so record the method with the number instead of copying the number alone."]},
    {title:"Account for lighting and perspective",paragraphs:["Warehouse lighting can shift colour temperature, and phone processing can increase contrast or sharpness. Compare several images and treat small colour differences cautiously. Perspective also changes shape: a wide-angle view from close range can exaggerate the front of a shoe or the depth of a bag.","Ask whether the image angle helps comparison. A straight-on front, side and back view usually creates a more stable reference than one dramatic diagonal image. Use measurements when proportion matters.","Use repeated visual anchors. White paper, a neutral wall, a ruler or the same warehouse surface across frames can help reveal whether the colour shift comes from lighting. Do not use your phone screen at maximum warmth or a heavily compressed social-media repost as the final reference. If colour is essential, compare the original high-resolution frames and describe uncertainty honestly. A QC page gains credibility by saying ‘appears warmer under warehouse lighting’ instead of asserting an exact shade the image cannot prove."]},
    {title:"A category checklist",paragraphs:["For clothing, inspect front and back, seams, print or embroidery, labels where relevant, fabric texture and measurements. For footwear, inspect both sides, toe, heel, sole, tongue, interior and size reference. For bags, inspect exterior, interior, base, closures, straps, edges, hardware and dimensions. For electronics, inspect model information, compatibility, ports, condition, included parts and shipping restrictions.","Keep the checklist short enough to use. Five category-specific questions are usually better than a generic list of twenty. Prioritise the details that affect fit, identity, visible condition or shipping. For example, a jersey checklist can focus on selected version, chest width, front print, back name set and stitching around badges. A structured bag checklist can focus on dimensions, base shape, closure alignment, hardware condition and interior. The questions should change when the product changes."],bullets:["Identity matches", "Important surfaces are in focus", "Measurements use a clear method", "Selected option is visible", "Missing evidence is named"]},
    {title:"Decide before parcel submission",paragraphs:["Photo review is most useful while the item can still be assessed as an individual warehouse item. Complete inspection and any permitted requests before submitting the parcel, because packed goods may not remain available for additional views under the same process.","If a visible problem changes your decision, use the current official order or support workflow. Do not rely on an independent guide for account-specific actions, deadlines, fees or return eligibility.","The indexed LoveGoBuy warehouse interface separates items into areas including refund, expiring soon, QC updated and QC updating. Those labels show why timing belongs to the live account: an external article cannot know whether a particular item is still eligible for an action. Review the current warehouse state, preserve the relevant images and communicate through official support when needed. Never publish a universal return window or fee unless the current official policy states it clearly and can be linked directly."]},
    {title:"Keep the conclusion proportional",paragraphs:["A good conclusion states what the photos show and what they do not. For example: colour and selected size match; stitching appears consistent in the available views; chest measurement is visible; fabric composition and long-term wear cannot be confirmed. That is more useful than calling an item perfect or verified.","The three-pass method—identity, construction and scale—keeps the review focused. It turns a gallery into a set of questions and prevents the most attractive image from dominating the whole decision.","A useful QC article should also preserve the evidence trail: check date, product route, selected option, the views inspected and any unresolved question. If the destination later changes, readers can understand what the conclusion applied to. Do not label a seller or whole product line ‘verified’ from one gallery. The defensible conclusion is narrower: this photo set, for this listed option, showed or did not show specific visible details at the time of review."]},
  ], sources:[{label:"LoveGoBuy product pages — free QC photo statement",href:"https://www.lovegobuy.com/"},{label:"LoveGoBuy warehouse interface",href:"https://www.lovegobuy.com/warehouse/index"},{label:"Browse live product routes",href:"https://cnfansge.com/AllProducts/"}],
};

const shippingEn: Article = {
  title:"LoveGoBuy shipping weight guide: actual, dimensional and chargeable weight",deck:"Plan a parcel with product weight, packed dimensions, route eligibility and current official estimates in the right order.",read:"15 minute read · checked 1 Sep 2026",
  sections:[
    {title:"Why the item price is incomplete",paragraphs:["A low product price can be attractive while the completed parcel is expensive. International delivery depends on more than the goods themselves: packed weight, carton dimensions, route, destination, restrictions, service fees and carrier rules can all change the amount.","Compare products with a delivered-cost mindset. A thin garment and a boxed pair of shoes may have similar source prices but very different effects on chargeable weight and parcel volume.","Plan with three separate numbers: source price, warehouse-item weight and estimated parcel charge. Do not merge them into one vague ‘cheap’ label. The source price helps compare similar listings; item weight helps estimate consolidation; the parcel quote belongs to a chosen destination and route at a specific time. A guide can explain the relationship among those numbers, but it cannot publish one permanent cost per kilogram that applies to every country, line, item type and package size."]},
    {title:"Actual weight",paragraphs:["Actual weight is the mass measured on a scale. Start with the listed or measured weight of every warehouse item, then allow for cartons, protective material and consolidation. Product-only figures may exclude the seller box or later parcel packaging.","Treat generic weight ranges as early planning aids, not facts about a specific item. The warehouse measurement and final packed parcel provide better information than a category average.","When comparing candidates, record whether a displayed weight describes the product, the seller package or the warehouse item. A shoe pair may include a retail box; a garment may arrive in light plastic; a fragile item may need extra protection. Add the known weights first and keep packaging as an explicit allowance instead of hiding it inside a rounded guess. After rehearsal or final packing, replace the estimate with the measured parcel data rather than continuing to use the early worksheet figure."]},
    {title:"Dimensional weight",paragraphs:["Dimensional weight estimates the space a parcel occupies. LoveGoBuy’s public estimator explains the logistics concept and displays a common calculation: length × width × height in centimetres divided by 6000 to produce dimensional kilograms.","That published formula is useful for understanding the concept, but the applicable divisor and comparison method can vary by route. Always use the current official estimate for the chosen destination and parcel rather than treating one formula as universal.","For example, a 40 × 30 × 20 cm parcel occupies 24,000 cubic centimetres. Dividing by 6000 gives 4 dimensional kilograms. That example teaches the calculation; it is not a quote for that parcel. A different route may use different billing increments, limits or methods. Enter the packed dimensions accurately, because rounding each side upward can compound. Measure the longest points, including any bulge or outer protection, rather than the nominal size of the item inside."]},
    {title:"Chargeable weight",paragraphs:["A shipping line may calculate its charge using the larger relevant figure or another route-specific method. This is why bulky outerwear, structured bags and shoe boxes can cost more than expected even when scale weight seems reasonable.","Reducing unnecessary volume may help, but protection and product condition still matter. Any packaging request should balance space savings against the risk of damage.","Do not assume that removing a box always creates the best outcome. The decision depends on how much volume the box adds, whether the item needs structural protection and whether keeping the packaging matters to you. Vacuum packing may reduce soft-goods volume, while rigid products need a different approach. Ask what change you are trying to achieve—lower dimensions, lower actual weight or better protection—and then verify the final parcel measurement. A service request is useful only if the resulting data is checked."]},
    {title:"Route eligibility",paragraphs:["The cheapest visible line is not useful if the item is ineligible. Batteries, liquids, magnets, powders and other restricted categories can affect which routes appear. Size limits, destination coverage and declared product properties also matter.","Check eligibility before comparing prices. Route names and service conditions can change, and an old screenshot or review may not describe the options available for the current parcel.","LoveGoBuy’s indexed estimator guidance says that an overweight or oversized parcel may be impossible to submit or may show no available route; it recommends splitting into smaller parcels and refers users to rehearsal-parcel service. Treat that as a decision tree, not a universal command. First confirm whether the absence of routes comes from weight, dimensions, item properties or destination. Then compare the cost and protection consequences of splitting. A smaller parcel can restore eligibility while creating two base charges or two customs events."]},
    {title:"A practical estimate workflow",paragraphs:["First add likely item weight. Second estimate packed dimensions and packaging. Third enter the current destination and parcel information into the official estimator. Fourth compare eligible routes, restrictions and service terms. Fifth recheck the final parcel data before payment.","Build the comparison table around the final decision: route name as currently displayed, eligible item types, actual weight, dimensions, dimensional weight where shown, estimated charge, included or optional protection and check time. Compare only routes that can carry the same parcel. If one quote assumes a smaller package or excludes an item, it is not a like-for-like comparison. Save a screenshot or note for your own records, but reopen the live estimator immediately before payment because rates and availability are time-sensitive."],bullets:["Item weights", "Likely packaging", "Packed dimensions", "Destination", "Eligible routes", "Current restrictions"]},
    {title:"What customer reviews can and cannot tell you",paragraphs:["Reviews can identify recurring topics such as packaging, speed, support, missing items or high shipping costs. They can help you decide which questions to ask, but they do not quote the price of your future parcel. Countries, routes, weights and dates differ.","Use review platforms for context and current official tools for calculation. Keep positive and negative experiences in view rather than selecting only examples that support a predetermined conclusion.","As of 1 September 2026, Trustpilot displayed a 4.4 score and roughly 576 reviews for lovegobuy.com, with both recent positive experiences and a visible minority of one-star ratings. Reddit results are also mixed: some users report smooth purchases and responsive communication, while others describe slow QC, refund or shipping problems. These signals justify questions about processing, packaging and support. They do not prove how a future order will perform, and the review count or rating should always carry a check date."]},
    {title:"Final verification",paragraphs:["Immediately before parcel payment, confirm destination, actual and dimensional data, chargeable weight, route, restrictions, protection, optional services and current terms. Save the date and the values used so later comparisons have context.","The reliable sequence is evidence first, calculation second and payment last. No independent static guide can replace the live official estimate or account-specific support response.","A final check should be reproducible. Write: destination, parcel count, actual weight, length, width, height, dimensional calculation if applicable, selected route, amount displayed and timestamp. If the quote changes, compare the inputs before assuming the platform changed the price. A different dimension, item classification, route or billing step can explain the difference. When the reason is still unclear, use official support with the exact parcel data rather than relying on a generic article or another user’s invoice.","Keep taxes, customs decisions and last-mile carrier charges outside any unsupported promise. They can depend on destination, declaration, carrier and current law, and the estimator result may not answer every downstream question. A responsible shipping article tells the reader exactly what was entered and what the official tool returned at the check time. It does not convert an estimate into a delivery guarantee or claim that one route will always clear customs, arrive within a fixed number of days or avoid additional charges."]},
  ],sources:[{label:"LoveGoBuy official shipping estimator",href:"https://www.lovegobuy.com/shipping/estimation/index"},{label:"LoveGoBuy official parcel interface",href:"https://www.lovegobuy.com/parcel/index"},{label:"LoveGoBuy official platform",href:"https://www.lovegobuy.com/"},{label:"Trustpilot — LoveGoBuy customer reviews",href:"https://www.trustpilot.com/review/lovegobuy.com"}],
};

const localizedMeta: Record<Exclude<Language,"en">,Record<string,[string,string,string]>> = {
  de:{"lovegobuy-spreadsheet-guide":["LoveGoBuy-Spreadsheet nutzen, ohne schwache Links zu speichern","Methode vom Suchergebnis zur begründeten Auswahlliste.","16 Minuten · geprüft 1. Sep. 2026"],"lovegobuy-qc-photo-guide":["LoveGoBuy QC-Fotos in drei Durchgängen lesen","Variante, Verarbeitung und Maße systematisch prüfen.","15 Minuten · geprüft 1. Sep. 2026"],"lovegobuy-shipping-weight":["LoveGoBuy Versandgewicht: Waage, Volumen und Abrechnung","Paketplanung mit Gewicht, Maßen und Routeneignung.","15 Minuten · geprüft 1. Sep. 2026"]},
  es:{"lovegobuy-spreadsheet-guide":["Usar una hoja LoveGoBuy sin guardar enlaces débiles","Método desde la búsqueda hasta una lista corta explicable.","16 minutos · revisado 1 sep 2026"],"lovegobuy-qc-photo-guide":["Fotos QC de LoveGoBuy en tres pasos","Confirma variante, construcción y medidas.","15 minutos · revisado 1 sep 2026"],"lovegobuy-shipping-weight":["Peso de envío LoveGoBuy: real, volumétrico y facturable","Planifica con peso, dimensiones y elegibilidad.","15 minutos · revisado 1 sep 2026"]},
  fr:{"lovegobuy-spreadsheet-guide":["Utiliser une feuille LoveGoBuy sans garder les liens faibles","Méthode de la recherche à une présélection justifiable.","16 minutes · vérifié 1 sept. 2026"],"lovegobuy-qc-photo-guide":["Lire les photos QC LoveGoBuy en trois étapes","Confirmer variante, fabrication et mesures.","15 minutes · vérifié 1 sept. 2026"],"lovegobuy-shipping-weight":["Poids d’expédition LoveGoBuy : réel, volumétrique et facturable","Planifier avec poids, dimensions et éligibilité.","15 minutes · vérifié 1 sept. 2026"]},
  it:{"lovegobuy-spreadsheet-guide":["Usare un foglio LoveGoBuy senza salvare link deboli","Metodo dalla ricerca a una lista breve spiegabile.","16 minuti · verificato 1 set 2026"],"lovegobuy-qc-photo-guide":["Leggere le foto QC LoveGoBuy in tre passaggi","Confermare variante, costruzione e misure.","15 minuti · verificato 1 set 2026"],"lovegobuy-shipping-weight":["Peso di spedizione LoveGoBuy: reale, volumetrico e fatturabile","Pianificare con peso, misure e idoneità.","15 minuti · verificato 1 set 2026"]},
};

const sectionTitles: Record<Exclude<Language,"en">,Record<string,string[]>> = {
  de:{"lovegobuy-spreadsheet-guide":["Ein Spreadsheet ist der Anfang","Zuerst die Kategorie wählen","Zielseite und Weiterleitung prüfen","Sichtbare Nachweise bewerten","Fotos mit Aufgabe lesen","Preis und Versand ergänzen","Entscheidungsnotiz schreiben","Im richtigen Moment neu prüfen"],"lovegobuy-qc-photo-guide":["Was QC-Fotos leisten","1: Identität und Variante","2: Verarbeitung prüfen","3: Maße und Maßstab","Licht und Perspektive","Kategorie-Checkliste","Vor Paketabgabe entscheiden","Fazit angemessen halten"],"lovegobuy-shipping-weight":["Warum der Artikelpreis unvollständig ist","Tatsächliches Gewicht","Volumengewicht","Abrechnungsgewicht","Routeneignung","Praktischer Ablauf","Bewertungen richtig nutzen","Letzte Prüfung"]},
  es:{"lovegobuy-spreadsheet-guide":["La hoja es el punto de partida","Elegir categoría primero","Revisar el destino","Puntuar pruebas visibles","Leer fotos con una función","Añadir precio y envío","Escribir una nota","Revisar al final"],"lovegobuy-qc-photo-guide":["Qué pueden mostrar las fotos","1: Identidad y variante","2: Construcción","3: Escala y medidas","Luz y perspectiva","Lista por categoría","Decidir antes del paquete","Conclusión proporcional"],"lovegobuy-shipping-weight":["Por qué el precio está incompleto","Peso real","Peso volumétrico","Peso facturable","Elegibilidad de ruta","Flujo de estimación","Cómo usar reseñas","Verificación final"]},
  fr:{"lovegobuy-spreadsheet-guide":["La feuille est un point de départ","Choisir la catégorie","Inspecter la destination","Noter les preuves visibles","Lire les photos avec un objectif","Ajouter prix et livraison","Écrire une note","Revérifier au bon moment"],"lovegobuy-qc-photo-guide":["Ce que montrent les photos","1 : identité et variante","2 : fabrication","3 : échelle et mesures","Lumière et perspective","Liste par catégorie","Décider avant le colis","Conclusion proportionnée"],"lovegobuy-shipping-weight":["Pourquoi le prix est incomplet","Poids réel","Poids volumétrique","Poids facturable","Éligibilité des lignes","Méthode d’estimation","Utiliser les avis","Vérification finale"]},
  it:{"lovegobuy-spreadsheet-guide":["Il foglio è un punto di partenza","Scegliere la categoria","Controllare la destinazione","Valutare le prove visibili","Leggere le foto con uno scopo","Aggiungere prezzo e spedizione","Scrivere una nota","Ricontrollare al momento giusto"],"lovegobuy-qc-photo-guide":["Cosa mostrano le foto","1: identità e variante","2: costruzione","3: scala e misure","Luce e prospettiva","Lista per categoria","Decidere prima del pacco","Conclusione proporzionata"],"lovegobuy-shipping-weight":["Perché il prezzo è incompleto","Peso reale","Peso volumetrico","Peso fatturabile","Idoneità delle rotte","Flusso di stima","Usare le recensioni","Verifica finale"]},
};

const localizedParagraphs: Record<Exclude<Language,"en">,string[]> = {
  de:["Prüfe die sichtbaren Angaben auf der aktuellen Zielseite und trenne belegte Details von Annahmen. Titel, Bild, Option, Maße, Preis und Datum bilden den Mindestkontext. Eine attraktive Bezeichnung oder hohe Popularität ist noch kein Qualitätsnachweis.","Vergleiche immer ähnliche Produkte mit denselben Fragen. Benenne fehlende Informationen ausdrücklich und entferne einen Kandidaten, wenn Weiterleitung, Variante oder wichtige Maße nicht erklärbar sind. Nutze offizielle aktuelle Werkzeuge für Konto, Zahlung, Support und Versand."],
  es:["Comprueba los datos visibles en el destino actual y separa detalles demostrables de suposiciones. Título, imagen, opción, medidas, precio y fecha forman el contexto mínimo. Una etiqueta atractiva o popularidad no demuestra calidad.","Compara productos similares con las mismas preguntas. Nombra la información ausente y elimina un candidato cuando la ruta, variante o medidas importantes no puedan explicarse. Usa herramientas oficiales actuales para cuenta, pago, soporte y envío."],
  fr:["Vérifiez les informations visibles sur la destination actuelle et séparez les faits des suppositions. Titre, image, option, mesures, prix et date constituent le contexte minimum. Une étiquette séduisante ou la popularité ne prouvent pas la qualité.","Comparez des produits similaires avec les mêmes questions. Nommez les informations manquantes et retirez un candidat si le lien, la variante ou les mesures restent inexplicables. Utilisez les outils officiels actuels pour compte, paiement, support et livraison."],
  it:["Controlla i dati visibili sulla destinazione attuale e separa i dettagli dimostrabili dalle ipotesi. Titolo, immagine, opzione, misure, prezzo e data formano il contesto minimo. Un’etichetta attraente o la popolarità non dimostrano qualità.","Confronta prodotti simili con le stesse domande. Indica le informazioni mancanti e rimuovi un candidato quando rotta, variante o misure importanti non sono spiegabili. Usa strumenti ufficiali aggiornati per account, pagamento, supporto e spedizione."],
};

const localizedBodies: Record<Exclude<Language,"en">,Record<string,string[]>> = {
  de:{
    "lovegobuy-spreadsheet-guide":[
      "Ein LoveGoBuy-Spreadsheet ordnet die Suche, entscheidet aber nicht für dich. Jede Zeile ist ein Hinweis, dessen Titel, Bild, Preis, Option und Zielseite erneut geprüft werden müssen. Seiten und Bestände können sich ändern; die Stärke der Liste liegt im Eingrenzen, nicht in einer Garantie.",
      "Beginne mit einer Produktkategorie, damit ähnliche Dinge nach denselben Kriterien verglichen werden. Bei Kleidung zählen Maße und Materialhinweise, bei Schuhen Profil, Sohle und Größenreferenz, bei Taschen Abmessungen, Innenraum, Verschlüsse und Leergewicht.",
      "Öffne Zeile und Zielseite nebeneinander. Titel, Hauptbild, Farbe, Größe und Variante müssen noch zusammenpassen. Ein konvertierter Link erleichtert den Zugang, bestätigt aber weder Verkäufer, Bestand noch aktuellen Preis. Bei einer unklaren Weiterleitung sollte der Kandidat vorerst entfernt werden.",
      "Bewerte sichtbare Nachweise: passende Route, richtige Kategorie, nützliche QC-Bilder, Maße, Preisvergleich, Versandkontext und ein erklärbarer Grund zum Speichern. Begriffe wie best, beliebt oder verifiziert erhalten ohne Beleg keinen eigenen Wert.",
      "QC-Fotos sollten eine Aufgabe erfüllen. Prüfe zuerst Identität und Variante, danach Verarbeitung wie Nähte, Kanten, Druck oder Hardware und zuletzt Maße oder Maßstab. Schöne Weitwinkelbilder ersetzen keine scharfen Details und beweisen weder Material noch Echtheit.",
      "Der Artikelpreis ist nur ein Teil der Entscheidung. Schuhe mit Karton, strukturierte Taschen und dicke Jacken können mehr abrechenbares Gewicht erzeugen. Ergänze wahrscheinliches Packgewicht und Volumen und nutze den aktuellen offiziellen Rechner statt alter Pauschalwerte.",
      "Eine kurze Notiz macht die Auswahl wiederverwendbar: behalten oder entfernen, sichtbarer Nachweis, wichtigste offene Frage, nächster Vergleich und Prüfdatum. So bleibt nachvollziehbar, warum ein Produkt stärker war als ähnliche Alternativen.",
      "Unmittelbar vor Bestellung oder Paketabgabe muss das Live-Ziel erneut geöffnet werden. Kontrolliere Option, Preis, Bestand, Maße und Einschränkungen. Konto-, Zahlungs-, Rückgabe- und Versandentscheidungen gehören zu den aktuellen offiziellen Abläufen.",
    ],
    "lovegobuy-qc-photo-guide":[
      "QC-Fotos zeigen ein bestimmtes Lagerstück zu einem bestimmten Zeitpunkt. Sie können falsche Farbe, Option, sichtbare Schäden oder fehlende Teile erkennbar machen, garantieren aber weder Faserzusammensetzung, Funktion, Echtheit, Haltbarkeit noch erfolgreiche Zustellung.",
      "Lege Listing, Spreadsheet-Zeile und Fotoreihe nebeneinander. Produktart, Farbe, Muster, Größe und unterscheidende Merkmale müssen übereinstimmen. Achte darauf, dass alle Ansichten zur selben Variante gehören und nicht aus einem anderen Angebot wiederverwendet wurden.",
      "Wähle Prüfstellen nach Kategorie: Kleidung benötigt Nähte, Säume, Druck, Stoff und Maße; Schuhe beide Profile, Zehenform, Ferse, Sohle und Größenreferenz; Taschen Kanten, Verschlüsse, Gurte, Hardware und Innenraum; Elektronik Modell, Anschlüsse und Lieferumfang.",
      "Ein Größenetikett allein reicht selten. Vergleiche Brust, Länge, Schulter oder Innenbein mit einem passenden eigenen Kleidungsstück. Bei Schuhen zählt eine Innensohlenreferenz, bei Taschen und Accessoires sind reale Abmessungen zuverlässiger als die optische Größe.",
      "Lagerlicht und Kameraverarbeitung können Farben verschieben, während Nähe und Weitwinkel Proportionen verändern. Vergleiche mehrere gerade Ansichten und nutze Maße, wenn Form oder Größe entscheidend sind. Ein dramatischer Winkel ist kein stabiler Vergleich.",
      "Eine vollständige Prüfung bestätigt Identität, scharfe wichtige Flächen, nachvollziehbare Maße und die ausgewählte Option. Fehlende Nachweise sollten konkret benannt werden, etwa beide Schuhfronten, Reißverschlussdetail oder flach gemessene Brustweite.",
      "Prüfe Bilder und erlaubte Zusatzanforderungen, solange das Stück einzeln im Lager bearbeitet werden kann. Nach einer Paketabgabe kann es bereits verpackt sein. Bei einem relevanten Problem nutze den aktuellen offiziellen Bestell- oder Supportweg.",
      "Ein gutes Fazit bleibt proportional: Farbe und Größe passen, sichtbare Nähte wirken gleichmäßig, Brustmaß ist erkennbar; Material und Langzeitnutzung bleiben offen. Diese Form ist genauer als pauschale Aussagen wie perfekt oder vollständig verifiziert.",
    ],
    "lovegobuy-shipping-weight":[
      "Ein niedriger Artikelpreis beschreibt nicht die fertigen Kosten. Packgewicht, Kartonmaße, Ziel, Linie, Einschränkungen und aktuelle Gebühren verändern das Ergebnis. Zwei gleich teure Produkte können wegen Volumen und Verpackung sehr unterschiedliche Paketkosten erzeugen.",
      "Tatsächliches Gewicht wird auf der Waage gemessen. Addiere zunächst die Lagergewichte und plane Kartons, Schutzmaterial sowie Konsolidierung ein. Allgemeine Kategorieangaben helfen nur früh; das gemessene und endgültig verpackte Paket ist aussagekräftiger.",
      "Volumengewicht schätzt den beanspruchten Raum. Der öffentliche LoveGoBuy-Rechner zeigt als häufiges Beispiel Länge × Breite × Höhe in Zentimetern geteilt durch 6000. Divisor und Methode können je nach Linie variieren, weshalb die aktuelle Route maßgeblich bleibt.",
      "Eine Linie kann den größeren relevanten Wert oder eine eigene Methode abrechnen. Deshalb überraschen Kartonschuhe, Pufferjacken und strukturierte Taschen trotz moderatem Waagengewicht. Weniger Volumen kann helfen, darf aber notwendigen Schutz nicht ersetzen.",
      "Die billigste sichtbare Linie nützt nichts, wenn der Artikel nicht zulässig ist. Batterien, Flüssigkeiten, Magnete, Größenlimits und deklarierte Eigenschaften beeinflussen die Auswahl. Prüfe zuerst die Eignung und vergleiche danach Preise.",
      "Arbeite in Reihenfolge: Artikelgewichte addieren, Verpackung und Maße schätzen, Ziel im offiziellen Rechner eingeben, zulässige Linien vergleichen und unmittelbar vor Zahlung die endgültigen Paketdaten kontrollieren.",
      "Bewertungen zeigen wiederkehrende Themen wie Verpackung, Tempo, Support oder hohe Kosten, berechnen aber nicht dein Paket. Länder, Linien, Gewichte und Zeitpunkte unterscheiden sich. Nutze Reviews für Fragen und offizielle Werkzeuge für Beträge.",
      "Vor Zahlung bestätige Ziel, tatsächliches und volumetrisches Gewicht, Abrechnung, Linie, Einschränkungen, Schutz und Zusatzleistungen. Speichere Datum und verwendete Werte. Ein unabhängiger Leitfaden ersetzt nie die Live-Schätzung oder kontospezifischen Support.",
    ],
  },
  es:{
    "lovegobuy-spreadsheet-guide":[
      "Una hoja LoveGoBuy organiza la búsqueda, pero no decide por ti. Cada fila es una pista cuyo título, imagen, precio, opción y destino deben revisarse. Las páginas y el stock cambian; el valor de la hoja está en reducir la búsqueda, no en garantizar el resultado.",
      "Empieza con una sola categoría para comparar productos parecidos con las mismas preguntas. En ropa importan medidas y tejido; en calzado, perfil, suela y referencia de talla; en bolsos, dimensiones, interior, cierres, herrajes y peso vacío.",
      "Abre la fila y la página de destino lado a lado. Título, imagen principal, color, talla y variante deben coincidir. Un enlace convertido facilita el acceso, pero no confirma vendedor, disponibilidad o precio. Si la transferencia es confusa, elimina el candidato temporalmente.",
      "Puntúa pruebas visibles: ruta correcta, categoría adecuada, fotos QC útiles, medidas, contexto de precio, efecto del envío y un motivo explicable para conservar. Palabras como mejor, popular o verificado no valen sin evidencia concreta.",
      "Las fotos QC necesitan una función. Confirma identidad y variante, revisa construcción —costuras, bordes, impresión o hardware— y busca medidas o escala. Una foto atractiva no demuestra material, autenticidad, funcionamiento ni durabilidad.",
      "El precio del artículo es solo una parte. Zapatos con caja, bolsos estructurados y chaquetas gruesas pueden aumentar peso facturable y volumen. Añade embalaje probable y utiliza el estimador oficial actual en lugar de cifras antiguas.",
      "Escribe una nota breve: conservar o eliminar, prueba visible, principal pregunta abierta, alternativa más cercana y fecha. Así puedes explicar por qué un producto sigue por delante de opciones similares y revisar más rápido después.",
      "Antes de pedir o enviar el paquete, vuelve al destino vivo. Confirma opción, precio, stock, medidas y restricciones. Las decisiones de cuenta, pago, devolución y envío deben usar los procesos oficiales actuales.",
    ],
    "lovegobuy-qc-photo-guide":[
      "Las fotos QC muestran un artículo concreto que llegó al almacén en un momento determinado. Pueden revelar color equivocado, opción incorrecta, daño visible o piezas ausentes, pero no garantizan composición, autenticidad, funcionamiento, duración o entrega.",
      "Coloca anuncio, fila y fotos juntas. Tipo, color, patrón, talla y rasgos distintivos deben coincidir. Comprueba que todas las vistas pertenezcan a la misma variante y que no se reutilicen imágenes de otra ficha.",
      "Elige puntos según categoría: ropa necesita costuras, bordes, impresión, tejido y medidas; calzado ambos perfiles, puntera, talón, suela y talla; bolsos bordes, cierres, correas, herrajes e interior; electrónica modelo, puertos y piezas incluidas.",
      "Una etiqueta de talla no basta. Compara pecho, largo, hombro o entrepierna con una prenda conocida. En zapatos busca longitud interior; en bolsos y accesorios utiliza dimensiones reales en lugar de depender de la escala visual.",
      "La iluminación del almacén puede alterar el color y una lente cercana cambia las proporciones. Compara varias vistas rectas y usa medidas cuando forma o tamaño importen. Un ángulo dramático no es una referencia estable.",
      "Una revisión completa confirma identidad, superficies importantes enfocadas, medidas con método claro y opción visible. Nombra la prueba ausente con precisión: frontal de ambos zapatos, detalle de cremallera o pecho medido en plano.",
      "Revisa imágenes y solicitudes permitidas mientras el artículo siga disponible como pieza individual. Después de enviar el paquete puede estar embalado. Si un problema cambia tu decisión, utiliza el flujo oficial de pedido o soporte.",
      "Una conclusión proporcional dice qué muestran las fotos y qué no: color y talla coinciden, costuras visibles parecen regulares y hay medida de pecho; material y desgaste futuro siguen sin confirmar. Es mejor que decir perfecto o verificado.",
    ],
    "lovegobuy-shipping-weight":[
      "Un precio bajo no describe el coste terminado. Peso embalado, dimensiones, destino, línea, restricciones y tarifas actuales cambian el resultado. Dos productos con igual precio pueden generar envíos muy diferentes por volumen y caja.",
      "El peso real se mide en una báscula. Suma los pesos de almacén y deja margen para cartón, protección y consolidación. Los rangos genéricos solo orientan al principio; la medición del paquete final es más útil.",
      "El peso volumétrico estima el espacio ocupado. El estimador público LoveGoBuy muestra como ejemplo largo × ancho × alto en centímetros dividido entre 6000. Divisor y método pueden variar según línea, por lo que manda la opción actual.",
      "Una línea puede cobrar el mayor valor relevante o aplicar su propio método. Por eso calzado con caja, chaquetas acolchadas y bolsos estructurados sorprenden aunque la báscula parezca razonable. Reducir volumen no debe eliminar protección necesaria.",
      "La línea más barata no sirve si el artículo no es elegible. Baterías, líquidos, imanes, límites de tamaño y propiedades declaradas afectan las opciones. Comprueba elegibilidad antes de comparar precios.",
      "Sigue este orden: suma pesos, estima embalaje y dimensiones, introduce destino en el estimador oficial, compara líneas válidas y revisa los datos finales inmediatamente antes de pagar.",
      "Las reseñas muestran temas repetidos como embalaje, velocidad, soporte o costes altos, pero no calculan tu paquete. Países, líneas, pesos y fechas difieren. Usa reseñas para contexto y herramientas oficiales para cifras.",
      "Antes del pago confirma destino, peso real y volumétrico, peso facturable, línea, restricciones, protección y servicios opcionales. Guarda fecha y valores. Ninguna guía estática sustituye la estimación viva o el soporte de cuenta.",
    ],
  },
  fr:{} as any,
  it:{} as any,
};

localizedBodies.fr={
  "lovegobuy-spreadsheet-guide":[
    "Une feuille LoveGoBuy organise la recherche sans décider à votre place. Chaque ligne reste une piste dont le titre, l’image, le prix, l’option et la destination doivent être revérifiés. Pages et stocks évoluent ; la feuille sert à réduire la recherche, pas à garantir un résultat.",
    "Commencez par une seule catégorie afin de poser les mêmes questions à des produits comparables. Pour les vêtements, vérifiez mesures et tissu ; pour les chaussures, profil, semelle et référence de taille ; pour les sacs, dimensions, intérieur, fermetures, quincaillerie et poids à vide.",
    "Ouvrez la ligne et la destination côte à côte. Titre, image principale, couleur, taille et variante doivent correspondre. Un lien converti facilite l’accès mais ne confirme ni vendeur, ni stock, ni prix actuel. Retirez temporairement tout candidat dont le transfert reste ambigu.",
    "Notez les preuves visibles : lien correspondant, bonne catégorie, photos QC utiles, mesures, contexte de prix, effet de la livraison et raison explicable de conserver. Les mots meilleur, populaire ou vérifié ne comptent pas sans élément concret.",
    "Les photos QC doivent remplir une fonction. Confirmez identité et variante, inspectez fabrication — coutures, bords, impression ou matériel — puis trouvez mesures ou échelle. Une belle image ne prouve ni composition, authenticité, fonctionnement ou durabilité.",
    "Le prix produit n’est qu’une composante. Chaussures en boîte, sacs structurés et manteaux épais peuvent augmenter poids facturable et volume. Ajoutez l’emballage probable et utilisez l’estimateur officiel actuel plutôt qu’un chiffre ancien.",
    "Écrivez une courte note : garder ou retirer, preuve visible, question principale, alternative la plus proche et date. Vous pourrez expliquer pourquoi un candidat reste devant des options voisines et le revérifier plus vite.",
    "Juste avant commande ou colis, rouvrez la destination en direct. Confirmez option, prix, stock, mesures et restrictions. Compte, paiement, retour et expédition doivent suivre les processus officiels actuels.",
  ],
  "lovegobuy-qc-photo-guide":[
    "Les photos QC montrent un article précis arrivé à l’entrepôt à un moment donné. Elles peuvent révéler mauvaise couleur, option incorrecte, dommage visible ou pièce manquante, mais ne garantissent pas composition, authenticité, fonctionnement, durée ou livraison.",
    "Placez annonce, ligne et photos ensemble. Type, couleur, motif, taille et signes distinctifs doivent correspondre. Vérifiez que toutes les vues appartiennent à la même variante et ne proviennent pas d’une autre fiche.",
    "Choisissez les points selon la catégorie : vêtements — coutures, bords, impression, tissu et mesures ; chaussures — profils, pointe, talon, semelle et taille ; sacs — bords, fermetures, sangles, quincaillerie et intérieur ; électronique — modèle, ports et accessoires.",
    "Une étiquette de taille ne suffit pas. Comparez poitrine, longueur, épaule ou entrejambe avec un vêtement connu. Pour les chaussures cherchez la longueur intérieure ; pour sacs et accessoires, utilisez des dimensions réelles plutôt que l’échelle visuelle.",
    "L’éclairage d’entrepôt peut déplacer la couleur et une prise de vue proche déforme les proportions. Comparez plusieurs vues droites et utilisez des mesures lorsque forme ou taille comptent. Un angle spectaculaire n’est pas une référence stable.",
    "Un contrôle complet confirme identité, surfaces importantes nettes, méthode de mesure claire et option visible. Nommez précisément la vue manquante : face des deux chaussures, détail de fermeture ou poitrine mesurée à plat.",
    "Examinez images et demandes autorisées pendant que l’article reste disponible individuellement. Après soumission du colis, il peut être emballé. Si un défaut change votre décision, utilisez le parcours officiel de commande ou de support.",
    "Une conclusion proportionnée dit ce que montrent les images et leurs limites : couleur et taille correspondent, coutures visibles régulières, mesure de poitrine présente ; matière et usure future restent inconnues. C’est plus précis que parfait ou vérifié.",
  ],
  "lovegobuy-shipping-weight":[
    "Un prix produit bas ne décrit pas le coût final. Poids emballé, dimensions, destination, ligne, restrictions et frais actuels modifient le résultat. Deux articles au même prix peuvent produire des livraisons très différentes selon volume et boîte.",
    "Le poids réel est mesuré sur une balance. Additionnez les poids d’entrepôt et prévoyez carton, protection et consolidation. Les moyennes de catégorie aident au début ; la mesure du colis final est plus fiable.",
    "Le poids volumétrique estime l’espace occupé. L’estimateur public LoveGoBuy affiche comme exemple longueur × largeur × hauteur en centimètres ÷ 6000. Le diviseur et la méthode pouvant varier, la ligne actuelle reste déterminante.",
    "Une ligne peut facturer la valeur pertinente la plus élevée ou sa propre méthode. Chaussures en boîte, doudounes et sacs structurés surprennent donc malgré un poids réel raisonnable. Réduire le volume ne doit pas supprimer la protection nécessaire.",
    "La ligne la moins chère est inutile si l’article n’est pas éligible. Batteries, liquides, aimants, limites de taille et propriétés déclarées influencent les options. Contrôlez l’éligibilité avant les prix.",
    "Suivez cet ordre : additionner les poids, estimer emballage et dimensions, entrer la destination dans l’outil officiel, comparer les lignes admises puis revérifier les données finales juste avant paiement.",
    "Les avis révèlent des thèmes comme emballage, rapidité, support ou coût élevé, mais ne calculent pas votre colis. Pays, lignes, poids et dates diffèrent. Utilisez les avis pour le contexte et les outils officiels pour les chiffres.",
    "Avant paiement, confirmez destination, poids réel et volumétrique, poids facturable, ligne, restrictions, protection et options. Conservez date et valeurs. Aucun guide statique ne remplace l’estimation en direct ou le support du compte.",
  ],
};

localizedBodies.it={
  "lovegobuy-spreadsheet-guide":[
    "Un foglio LoveGoBuy organizza la ricerca ma non decide al posto tuo. Ogni riga è una pista di cui ricontrollare titolo, immagine, prezzo, opzione e destinazione. Pagine e disponibilità cambiano; il foglio riduce la ricerca, non garantisce il risultato.",
    "Inizia da una sola categoria per porre le stesse domande a prodotti simili. Per l’abbigliamento contano misure e tessuto; per le scarpe profilo, suola e riferimento taglia; per le borse dimensioni, interno, chiusure, hardware e peso vuoto.",
    "Apri riga e destinazione affiancate. Titolo, immagine principale, colore, taglia e variante devono coincidere. Un link convertito facilita l’accesso ma non conferma venditore, stock o prezzo. Rimuovi temporaneamente un candidato con passaggio poco chiaro.",
    "Valuta le prove visibili: rotta corretta, categoria, foto QC utili, misure, contesto di prezzo, effetto della spedizione e motivo spiegabile per conservare. Parole come migliore, popolare o verificato non contano senza prove.",
    "Le foto QC devono avere uno scopo. Conferma identità e variante, esamina costruzione — cuciture, bordi, stampa o hardware — e trova misure o scala. Una bella immagine non prova materiale, autenticità, funzionamento o durata.",
    "Il prezzo del prodotto è solo una parte. Scarpe con scatola, borse strutturate e giacche spesse possono aumentare peso fatturabile e volume. Aggiungi l’imballaggio probabile e usa lo stimatore ufficiale attuale.",
    "Scrivi una nota breve: conserva o rimuovi, prova visibile, domanda principale, alternativa vicina e data. Potrai spiegare perché un candidato supera opzioni simili e ricontrollarlo più rapidamente.",
    "Subito prima di ordine o pacco, riapri la destinazione live. Conferma opzione, prezzo, stock, misure e restrizioni. Account, pagamento, reso e spedizione devono seguire i processi ufficiali aggiornati.",
  ],
  "lovegobuy-qc-photo-guide":[
    "Le foto QC mostrano un articolo specifico arrivato in magazzino in un dato momento. Possono rivelare colore errato, opzione sbagliata, danni visibili o parti mancanti, ma non garantiscono composizione, autenticità, funzionamento, durata o consegna.",
    "Metti insieme annuncio, riga e foto. Tipo, colore, motivo, taglia e caratteristiche distintive devono coincidere. Controlla che tutte le viste appartengano alla stessa variante e non siano riutilizzate da un’altra scheda.",
    "Scegli i punti per categoria: abbigliamento — cuciture, bordi, stampa, tessuto e misure; scarpe — profili, punta, tallone, suola e taglia; borse — bordi, chiusure, cinghie, hardware e interno; elettronica — modello, porte e componenti.",
    "Un’etichetta taglia non basta. Confronta petto, lunghezza, spalla o interno gamba con un capo noto. Per le scarpe cerca la lunghezza interna; per borse e accessori usa dimensioni reali invece della sola scala visiva.",
    "La luce del magazzino può spostare il colore e una ripresa ravvicinata altera le proporzioni. Confronta più viste dritte e usa misure quando forma o dimensione contano. Un angolo drammatico non è un riferimento stabile.",
    "Un controllo completo conferma identità, superfici importanti nitide, metodo di misura chiaro e opzione visibile. Indica con precisione la vista mancante: fronte di entrambe le scarpe, dettaglio cerniera o petto misurato in piano.",
    "Controlla immagini e richieste consentite mentre l’articolo resta disponibile singolarmente. Dopo l’invio del pacco può essere già imballato. Se un problema cambia la decisione, usa il flusso ufficiale di ordine o supporto.",
    "Una conclusione proporzionata dice cosa mostrano le foto e cosa no: colore e taglia coincidono, cuciture visibili regolari, misura del petto presente; materiale e usura futura restano sconosciuti. È più preciso di perfetto o verificato.",
  ],
  "lovegobuy-shipping-weight":[
    "Un prezzo basso non descrive il costo finale. Peso imballato, dimensioni, destinazione, linea, restrizioni e tariffe attuali cambiano il risultato. Due prodotti allo stesso prezzo possono generare spedizioni molto diverse per volume e scatola.",
    "Il peso reale si misura su una bilancia. Somma i pesi del magazzino e considera cartone, protezione e consolidamento. Le medie di categoria orientano all’inizio; la misura del pacco finale è più affidabile.",
    "Il peso volumetrico stima lo spazio occupato. Lo stimatore pubblico LoveGoBuy mostra come esempio lunghezza × larghezza × altezza in centimetri ÷ 6000. Divisore e metodo possono variare, quindi conta la linea attuale.",
    "Una linea può addebitare il valore pertinente maggiore o applicare un metodo proprio. Scarpe con scatola, piumini e borse strutturate sorprendono anche con peso reale moderato. Ridurre il volume non deve eliminare la protezione necessaria.",
    "La linea più economica è inutile se l’articolo non è idoneo. Batterie, liquidi, magneti, limiti dimensionali e proprietà dichiarate influenzano le opzioni. Controlla l’idoneità prima del prezzo.",
    "Segui l’ordine: somma i pesi, stima imballaggio e dimensioni, inserisci la destinazione nello strumento ufficiale, confronta le linee idonee e ricontrolla i dati finali subito prima del pagamento.",
    "Le recensioni mostrano temi come imballaggio, velocità, supporto o costi elevati, ma non calcolano il tuo pacco. Paesi, linee, pesi e date differiscono. Usa le recensioni per contesto e gli strumenti ufficiali per le cifre.",
    "Prima di pagare conferma destinazione, peso reale e volumetrico, peso fatturabile, linea, restrizioni, protezione e servizi opzionali. Salva data e valori. Nessuna guida statica sostituisce la stima live o il supporto account.",
  ],
};

const localizedBullets: Record<Exclude<Language,"en">,Record<string,string[]>>={
  de:{"lovegobuy-spreadsheet-guide":["Eine Kategorie","Drei ähnliche Kandidaten","Eine offene Frage","Ein Prüfdatum"],"lovegobuy-qc-photo-guide":["Identität stimmt","Wichtige Flächen scharf","Messmethode klar","Option sichtbar","Fehlender Nachweis benannt"],"lovegobuy-shipping-weight":["Artikelgewichte","Verpackung","Paketmaße","Ziel","Zulässige Linien","Aktuelle Einschränkungen"]},
  es:{"lovegobuy-spreadsheet-guide":["Una categoría","Tres candidatos similares","Una pregunta abierta","Una fecha"],"lovegobuy-qc-photo-guide":["Identidad coincide","Superficies enfocadas","Medición clara","Opción visible","Prueba ausente nombrada"],"lovegobuy-shipping-weight":["Pesos","Embalaje","Dimensiones","Destino","Rutas válidas","Restricciones actuales"]},
  fr:{"lovegobuy-spreadsheet-guide":["Une catégorie","Trois candidats proches","Une question ouverte","Une date"],"lovegobuy-qc-photo-guide":["Identité correspondante","Surfaces nettes","Mesure claire","Option visible","Preuve manquante nommée"],"lovegobuy-shipping-weight":["Poids articles","Emballage","Dimensions","Destination","Lignes éligibles","Restrictions actuelles"]},
  it:{"lovegobuy-spreadsheet-guide":["Una categoria","Tre candidati simili","Una domanda aperta","Una data"],"lovegobuy-qc-photo-guide":["Identità corretta","Superfici nitide","Misura chiara","Opzione visibile","Prova mancante indicata"],"lovegobuy-shipping-weight":["Pesi articoli","Imballaggio","Dimensioni","Destinazione","Rotte idonee","Restrizioni attuali"]},
};

const englishArticles: Record<string,Article> = {"lovegobuy-spreadsheet-guide":spreadsheetEn,"lovegobuy-qc-photo-guide":qcEn,"lovegobuy-shipping-weight":shippingEn};

export function getArticle(lang: Language, slug: string): Article | null {
  const base=englishArticles[slug]; if(!base) return null; if(lang==="en") return base;
  const meta=localizedMeta[lang][slug]; const titles=sectionTitles[lang][slug]; const bodies=localizedBodies[lang][slug]; const seconds=localizedArticleSeconds[lang][slug]; const extras=localizedArticleExtras[lang][slug]; const expansions=localizedArticleExpansions[lang][slug];
  return { title:meta[0], deck:meta[1], read:meta[2], sources:base.sources, sections:base.sections.map((section,i)=>{
    const paragraphs = section.paragraphs.length === 2
      ? [bodies[i] + expansions.bodies[i], extras[i] + expansions.extras[i]]
      : [bodies[i] + expansions.bodies[i], seconds[i], extras[i] + expansions.extras[i]];
    const fourth = localizedArticleFourths[lang][slug]?.[0];
    if (section.paragraphs.length === 4 && fourth) paragraphs.push(fourth);
    return {title:titles[i], paragraphs, bullets:section.bullets?localizedBullets[lang][slug]:undefined};
  }) };
}
