import type { Language } from "./site-content";
import { enrichPageCopy } from "./page-enrichment";
import { applyPageLocalizedParity } from "./page-localized-parity";

export type ContentSection = { title: string; body: string[]; points?: string[] };
export type ContentRecord = { title: string; deck: string; eyebrow: string; sections: ContentSection[] };

const en: Record<string, ContentRecord> = {
  spreadsheet: { eyebrow: "SPREADSHEET / START HERE", title: "Use a LoveGoBuy spreadsheet as a shortlist, not a promise.", deck: "A spreadsheet is useful when it reduces a huge directory to a few product routes that you can explain, compare and re-check.", sections: [
    { title: "Start with one category", body: ["A mixed sheet can make an average item look interesting simply because it follows ten unrelated products. Pick one category first so price, sizing, photos and likely weight can be compared on equal terms.", "For clothing, begin with measurements and fabric clues. For shoes, check profiles, outsole, insole reference and pair weight. For bags, focus on dimensions, interior, straps, hardware and empty weight."] },
    { title: "Treat every row as a lead", body: ["A row is an invitation to investigate, not proof of quality, stock or seller reliability. Open the destination and compare the title, main image, selected option, size information and source price with the spreadsheet entry."], points: ["Matching route and variant", "Useful QC angles", "Relevant measurements", "Current price context", "Likely packed weight"] },
    { title: "Keep evidence separate from assumptions", body: ["Write down what is visible and what remains unknown. A clear product photo is evidence of appearance, not material composition, function or authenticity. A popular label shows attention, not quality.", "Save a candidate only when you can state why it remains stronger than two similar alternatives."] },
    { title: "Recheck before action", body: ["Product pages, options, prices and shipping rules change. Re-open the live destination before placing an order and use current official account, payment and route information for transaction decisions."] },
  ]},
  finds: { eyebrow: "FINDS / PRODUCT ROUTES", title: "Find fewer products—and understand each one better.", deck: "Good discovery is not the number of tabs you open. It is the number of candidates that survive the same comparison method.", sections: [
    { title: "Search with an unanswered question", body: ["Use a category plus the detail that could change your decision: hoodie chest measurement, sneaker outsole, bag interior, jacket packed weight or electronics plug type. Specific searches remove unrelated noise."], points: ["Product type", "Missing detail", "Optional source name", "Date checked"] },
    { title: "Compare like with like", body: ["Place three nearby products beside one another. Compare visible construction, size information, source price and estimated shipping impact. Do not compare a heavy jacket with a thin shirt simply because both appear on the same sheet."] },
    { title: "Inspect the handoff", body: ["When a product card opens another site, confirm the destination still matches. Converted links can make access easier, but they cannot validate the selected option, seller, stock or current price."] },
    { title: "Remove weak candidates early", body: ["A missing size chart, one generic image, unclear variant or mismatched destination is a reason to pause. A smaller list of explainable finds is more useful than a large collection of uncertain links."] },
  ]},
  guide: { eyebrow: "GUIDE / FOUR PASSES", title: "A repeatable research method from search to shortlist.", deck: "Use the same four passes on every product so excitement does not replace evidence.", sections: [
    { title: "Pass 1 — Identity", body: ["Confirm product type, colour, selected option and main features across the spreadsheet row and destination. Stop if the handoff leads to a different item or a confusing group of variants."] },
    { title: "Pass 2 — Construction and fit", body: ["Look for category-specific QC evidence. Garments need measurements and seam or print detail. Shoes need both profiles, heel, toe, sole and an insole reference. Bags need scale, interior, closures and hardware."] },
    { title: "Pass 3 — Price and shipping", body: ["Compare the source price with similar finds, then add likely packed weight and volume. International shipping can change the apparent value of bulky or heavy products."] },
    { title: "Pass 4 — Decision note", body: ["Record keep or remove, the evidence used, the most important unresolved question, the closest alternative and the date checked. This turns a pile of tabs into a reusable shortlist."], points: ["Keep/remove", "Evidence", "Open question", "Closest alternative", "Checked date"] },
  ]},
  qc: { eyebrow: "QC / PHOTO METHOD", title: "Read LoveGoBuy QC photos in three deliberate passes.", deck: "More photos do not automatically mean better evidence. Each view should answer a product-specific question.", sections: [
    { title: "1. Identity and variant", body: ["Check colour, shape, option and defining details against the listing you intended to use. Make sure the photo set belongs to the current item rather than a generic sample or another variant."] },
    { title: "2. Construction and details", body: ["Inspect seams, edges, closures, print placement, hardware, sole shape, lining, ports or included parts according to the category. Repeated wide shots cannot replace focused close-ups."] },
    { title: "3. Fit, dimensions or scale", body: ["Find a size chart, ruler, garment measurement, insole length, bag dimension or another stable reference. Visual scale alone can be misleading, especially when camera distance changes."] },
    { title: "What photos cannot prove", body: ["QC images can help detect mismatches or visible defects, but they cannot guarantee material composition, performance, authenticity, long-term durability or a successful delivery. Keep photo evidence within its limits."] },
  ]},
  shipping: { eyebrow: "SHIPPING / WEIGHT", title: "Plan with chargeable weight, not the item price alone.", deck: "The cheapest find can become the weaker choice after packaging, route restrictions and dimensional weight are considered.", sections: [
    { title: "Actual and dimensional weight", body: ["Actual weight is measured on a scale. Dimensional weight estimates how much space a parcel occupies. LoveGoBuy’s public estimator displays a common dimensional calculation of length × width × height in centimetres divided by 6000.", "The applicable rule can vary by route, so use the current official estimator rather than treating one formula as permanent."] },
    { title: "Build a realistic parcel estimate", body: ["Add the likely item weights, then allow for cartons, protective material and consolidation. Shoes with boxes, puffer jackets and structured bags can create more volume than their product price suggests."] },
    { title: "Check eligibility before price", body: ["Batteries, liquids, magnets, branded goods and other restricted categories can affect available routes. A low quoted rate is irrelevant if the product cannot use that line or exceeds its size limits."] },
    { title: "Verify at the last responsible moment", body: ["Before parcel payment, recheck destination country, line restrictions, chargeable weight, declared options, protection and current service terms. Route prices and timing are snapshots, not promises."] },
  ]},
  faq: { eyebrow: "FAQ / BOUNDARIES", title: "Direct answers before you follow a product route.", deck: "Know what a spreadsheet can help with—and which questions require current official support.", sections: [
    { title: "What is a LoveGoBuy spreadsheet?", body: ["It is a directory that organizes product links, categories, images, prices or notes. It helps discovery and comparison but does not guarantee every row is current, accurate or suitable."] },
    { title: "Is this an official LoveGoBuy service?", body: ["No. This independent site does not create accounts, take payment, buy products, store goods, track parcels or resolve refunds. Use the verified official platform for account and transaction actions."] },
    { title: "Does a product card mean verified?", body: ["No. It means a route was available when checked. Reconfirm the current destination, option, seller information, QC evidence, measurements, price, stock and restrictions yourself."] },
    { title: "How much does shipping cost?", body: ["There is no permanent universal figure. Destination, route, actual weight, dimensions, product restrictions, fees, customs and carrier handoffs can all change the result. Use current official planning tools."] },
  ]},
  articles: { eyebrow: "ARTICLES / RESEARCH DESK", title: "Practical LoveGoBuy research notes.", deck: "Long-form guides built around spreadsheet use, QC evidence and shipping decisions—not unsupported promises.", sections: [] },
};

const translated: Record<Exclude<Language,"en">, Record<string, ContentRecord>> = {
  de: {
    spreadsheet:{eyebrow:"SPREADSHEET / START",title:"Nutze ein LoveGoBuy-Spreadsheet als Auswahlliste, nicht als Versprechen.",deck:"Ein gutes Spreadsheet reduziert ein großes Verzeichnis auf wenige erklärbare und erneut prüfbare Produktrouten.",sections:[{title:"Mit einer Kategorie beginnen",body:["Gemischte Listen verzerren den Vergleich. Wähle zuerst eine Kategorie, damit Preis, Größe, Fotos und Gewicht unter ähnlichen Produkten bewertet werden."]},{title:"Jede Zeile ist nur ein Hinweis",body:["Öffne das Ziel und vergleiche Titel, Bild, Option, Größenangaben und Quellpreis. Eine Zeile beweist weder Qualität noch Bestand."]},{title:"Nachweise von Annahmen trennen",body:["Notiere sichtbare Fakten und offene Fragen. Popularität und attraktive Bilder ersetzen keine prüfbaren Details."]},{title:"Vor jeder Aktion neu prüfen",body:["Seiten, Optionen, Preise und Routen ändern sich. Nutze für Transaktionen aktuelle offizielle Informationen."]}]},
    finds:{eyebrow:"FUNDE / ROUTEN",title:"Finde weniger Produkte und verstehe jedes besser.",deck:"Gute Suche misst sich an Kandidaten, die denselben Vergleich überstehen.",sections:[{title:"Mit einer offenen Frage suchen",body:["Kombiniere Kategorie und entscheidendes Detail, etwa Brustmaß, Sohle, Innenansicht oder Packgewicht."]},{title:"Gleiches mit Gleichem vergleichen",body:["Vergleiche drei ähnliche Produkte nach Verarbeitung, Größe, Preis und Versandwirkung."]},{title:"Weiterleitung prüfen",body:["Titel, Bild und Variante müssen am Ziel noch passen. Linkkonverter verifizieren keine Verkäufer oder Bestände."]},{title:"Schwache Kandidaten früh entfernen",body:["Fehlende Maße, generische Bilder oder unklare Varianten sind Gründe zum Stoppen."]}]},
    guide:{eyebrow:"LEITFADEN / VIER SCHRITTE",title:"Eine wiederholbare Methode von der Suche zur Auswahlliste.",deck:"Wende dieselben vier Prüfungen auf jedes Produkt an.",sections:[{title:"1 — Identität",body:["Produktart, Farbe, Option und Hauptmerkmale zwischen Zeile und Ziel abgleichen."]},{title:"2 — Verarbeitung und Passform",body:["Kategoriebezogene QC-Bilder und Maße prüfen."]},{title:"3 — Preis und Versand",body:["Quellpreis neben ähnliche Produkte stellen und Packgewicht sowie Volumen ergänzen."]},{title:"4 — Entscheidungsnotiz",body:["Behalten oder entfernen, Nachweise, offene Frage, Alternative und Datum festhalten."]}]},
    qc:{eyebrow:"QC / FOTOMETHODE",title:"LoveGoBuy-QC-Fotos in drei Durchgängen lesen.",deck:"Jede Ansicht sollte eine konkrete Produktfrage beantworten.",sections:[{title:"1. Identität und Variante",body:["Farbe, Form und gewählte Option mit dem vorgesehenen Eintrag vergleichen."]},{title:"2. Verarbeitung und Details",body:["Nähte, Kanten, Verschlüsse, Druck, Hardware, Sohle oder Anschlüsse je nach Kategorie prüfen."]},{title:"3. Maße und Maßstab",body:["Größentabelle, Lineal, Kleidungsmaß oder andere stabile Referenz suchen."]},{title:"Grenzen von Fotos",body:["Fotos garantieren weder Material, Funktion, Echtheit, Haltbarkeit noch erfolgreiche Lieferung."]}]},
    shipping:{eyebrow:"VERSAND / GEWICHT",title:"Plane mit abrechenbarem Gewicht, nicht nur mit dem Artikelpreis.",deck:"Verpackung, Einschränkungen und Volumengewicht können den günstigsten Fund verändern.",sections:[{title:"Gewicht und Volumen",body:["Der offizielle Rechner zeigt als verbreitetes Beispiel Länge × Breite × Höhe in Zentimetern ÷ 6000. Die konkrete Route bleibt maßgeblich."]},{title:"Realistisch schätzen",body:["Artikelgewichte addieren und Karton, Schutzmaterial sowie Konsolidierung berücksichtigen."]},{title:"Zulässigkeit zuerst",body:["Batterien, Flüssigkeiten, Magnete und andere Kategorien können Routen begrenzen."]},{title:"Vor Zahlung prüfen",body:["Land, Linie, Gewicht, Maße, Einschränkungen und aktuelle Bedingungen erneut kontrollieren."]}]},
    faq:{eyebrow:"FAQ / GRENZEN",title:"Klare Antworten vor dem Produktlink.",deck:"Verstehe, was ein Spreadsheet leistet und was offiziellen Support braucht.",sections:[{title:"Was ist ein LoveGoBuy-Spreadsheet?",body:["Ein Verzeichnis aus Links, Kategorien, Bildern, Preisen oder Notizen – keine Garantie."]},{title:"Ist dies offiziell?",body:["Nein. Diese Seite führt keine Konten, Zahlungen, Bestellungen, Lagerung oder Erstattungen aus."]},{title:"Bedeutet eine Karte verifiziert?",body:["Nein. Ziel, Option, Verkäuferangaben, QC, Maße, Preis und Bestand erneut prüfen."]},{title:"Was kostet Versand?",body:["Ziel, Route, Gewicht, Maße, Einschränkungen und Gebühren verändern den Betrag."]}]},
    articles:{eyebrow:"ARTIKEL / RECHERCHE",title:"Praktische LoveGoBuy-Rechercheartikel.",deck:"Ausführliche Anleitungen zu Spreadsheet, QC und Versand ohne unbelegte Versprechen.",sections:[]},
  },
  es: {
    spreadsheet:{eyebrow:"HOJA / INICIO",title:"Usa una hoja LoveGoBuy como lista corta, no como promesa.",deck:"Una buena hoja reduce un directorio enorme a pocas rutas comparables y revisables.",sections:[{title:"Empieza por una categoría",body:["Elige primero un tipo de producto para comparar precio, talla, fotos y peso entre artículos parecidos."]},{title:"Cada fila es una pista",body:["Abre el destino y compara título, imagen, opción, talla y precio. Una fila no demuestra calidad ni stock."]},{title:"Separa pruebas y suposiciones",body:["Anota lo visible y lo desconocido. Popularidad e imágenes atractivas no sustituyen datos."]},{title:"Revisa antes de actuar",body:["Páginas, opciones, precios y rutas cambian. Para transacciones usa información oficial actual."]}]},
    finds:{eyebrow:"HALLAZGOS / RUTAS",title:"Encuentra menos productos y entiende mejor cada uno.",deck:"Una buena búsqueda conserva solo candidatos que superan el mismo método.",sections:[{title:"Busca con una pregunta",body:["Combina categoría con el detalle decisivo: medidas, suela, interior, peso o enchufe."]},{title:"Compara productos similares",body:["Pon tres opciones cercanas juntas y revisa construcción, talla, precio y envío."]},{title:"Comprueba el destino",body:["Título, imagen y variante deben seguir coincidiendo tras abrir el enlace."]},{title:"Elimina candidatos débiles",body:["Medidas ausentes, imagen genérica o variante confusa justifican detenerse."]}]},
    guide:{eyebrow:"GUÍA / CUATRO PASOS",title:"Un método repetible desde la búsqueda hasta la lista corta.",deck:"Aplica las mismas cuatro comprobaciones a cada producto.",sections:[{title:"1 — Identidad",body:["Compara producto, color, opción y características entre hoja y destino."]},{title:"2 — Construcción y ajuste",body:["Revisa fotos QC y medidas específicas de la categoría."]},{title:"3 — Precio y envío",body:["Compara precio con artículos parecidos y añade peso y volumen probables."]},{title:"4 — Nota de decisión",body:["Registra conservar/eliminar, prueba, pregunta, alternativa y fecha."]}]},
    qc:{eyebrow:"QC / MÉTODO",title:"Lee las fotos QC de LoveGoBuy en tres pasos.",deck:"Cada imagen debe responder una pregunta concreta.",sections:[{title:"1. Identidad y variante",body:["Comprueba color, forma y opción frente a la ficha prevista."]},{title:"2. Construcción",body:["Revisa costuras, bordes, cierres, impresión, hardware, suela o conexiones."]},{title:"3. Medidas y escala",body:["Busca tabla, regla, medida de prenda u otra referencia estable."]},{title:"Límites de las fotos",body:["No prueban composición, función, autenticidad, durabilidad ni entrega."]}]},
    shipping:{eyebrow:"ENVÍO / PESO",title:"Planifica con peso facturable, no solo con el precio.",deck:"Embalaje, restricciones y volumen pueden cambiar el valor real.",sections:[{title:"Peso real y volumétrico",body:["El estimador oficial muestra como ejemplo largo × ancho × alto en cm ÷ 6000. La ruta actual manda."]},{title:"Estimación realista",body:["Suma artículos y deja margen para caja, protección y consolidación."]},{title:"Elegibilidad antes del precio",body:["Baterías, líquidos, imanes y otras categorías pueden limitar rutas."]},{title:"Verifica antes de pagar",body:["País, línea, peso, dimensiones, restricciones y condiciones deben revisarse de nuevo."]}]},
    faq:{eyebrow:"FAQ / LÍMITES",title:"Respuestas directas antes del enlace.",deck:"Distingue lo que ayuda una hoja y lo que exige soporte oficial.",sections:[{title:"¿Qué es una hoja LoveGoBuy?",body:["Un directorio de enlaces, categorías, imágenes, precios o notas; no una garantía."]},{title:"¿Es un servicio oficial?",body:["No. No crea cuentas, cobra, compra, almacena ni tramita reembolsos."]},{title:"¿Tarjeta significa verificado?",body:["No. Revisa destino, opción, vendedor, QC, medidas, precio y stock."]},{title:"¿Cuánto cuesta enviar?",body:["Destino, ruta, peso, volumen, restricciones y tasas cambian el total."]}]},
    articles:{eyebrow:"ARTÍCULOS / INVESTIGACIÓN",title:"Notas prácticas de investigación LoveGoBuy.",deck:"Guías sobre hojas, QC y envío sin promesas no demostradas.",sections:[]},
  },
  fr: {} as any,
  it: {} as any,
};

translated.fr = JSON.parse(JSON.stringify(translated.es));
translated.it = JSON.parse(JSON.stringify(translated.es));
const frTitles: Record<string,[string,string,string]> = {spreadsheet:["FEUILLE / DÉPART","Utilisez une feuille LoveGoBuy comme présélection, pas comme promesse.","Réduisez un vaste annuaire à quelques liens comparables et revérifiables."],finds:["TROUVAILLES / LIENS","Trouvez moins de produits et comprenez mieux chacun.","Une bonne recherche ne garde que les candidats qui passent la même méthode."],guide:["GUIDE / QUATRE ÉTAPES","Une méthode répétable de la recherche à la présélection.","Appliquez quatre contrôles identiques à chaque produit."],qc:["QC / MÉTHODE PHOTO","Lisez les photos QC LoveGoBuy en trois étapes.","Chaque image doit répondre à une question précise."],shipping:["LIVRAISON / POIDS","Planifiez avec le poids facturable, pas seulement le prix.","Emballage, restrictions et volume peuvent changer la valeur."],faq:["FAQ / LIMITES","Des réponses directes avant de suivre un lien.","Distinguez le rôle d’une feuille de celui du support officiel."],articles:["ARTICLES / RECHERCHE","Notes pratiques de recherche LoveGoBuy.","Guides sur feuilles, QC et livraison sans promesses non vérifiées."]};
const itTitles: Record<string,[string,string,string]> = {spreadsheet:["FOGLIO / INIZIO","Usa un foglio LoveGoBuy come lista breve, non come promessa.","Riduci una directory enorme a poche rotte confrontabili e ricontrollabili."],finds:["PRODOTTI / ROTTE","Trova meno prodotti e comprendi meglio ciascuno.","Una buona ricerca conserva solo candidati che superano lo stesso metodo."],guide:["GUIDA / QUATTRO PASSAGGI","Un metodo ripetibile dalla ricerca alla lista breve.","Applica quattro controlli uguali a ogni prodotto."],qc:["QC / METODO FOTO","Leggi le foto QC LoveGoBuy in tre passaggi.","Ogni immagine deve rispondere a una domanda precisa."],shipping:["SPEDIZIONE / PESO","Pianifica con il peso fatturabile, non solo con il prezzo.","Imballaggio, restrizioni e volume possono cambiare il valore."],faq:["FAQ / LIMITI","Risposte dirette prima di seguire un link.","Distingui ciò che fa un foglio da ciò che richiede supporto ufficiale."],articles:["ARTICOLI / RICERCA","Note pratiche di ricerca LoveGoBuy.","Guide su fogli, QC e spedizione senza promesse non verificate."]};
for (const key of Object.keys(frTitles)) { translated.fr[key].eyebrow=frTitles[key][0]; translated.fr[key].title=frTitles[key][1]; translated.fr[key].deck=frTitles[key][2]; }
for (const key of Object.keys(itTitles)) { translated.it[key].eyebrow=itTitles[key][0]; translated.it[key].title=itTitles[key][1]; translated.it[key].deck=itTitles[key][2]; }

translated.fr.spreadsheet.sections=[{title:"Commencer par une catégorie",body:["Une liste mélangée fausse la comparaison. Choisissez d’abord un type de produit afin d’évaluer prix, taille, photos et poids entre articles comparables."]},{title:"Chaque ligne reste une piste",body:["Ouvrez la destination et comparez titre, image, option, mesures et prix source. Une ligne ne prouve ni qualité ni stock."]},{title:"Séparer preuves et suppositions",body:["Notez ce qui est visible et ce qui reste inconnu. Popularité et belles images ne remplacent pas les détails vérifiables."]},{title:"Revérifier avant d’agir",body:["Pages, options, prix et lignes changent. Utilisez les informations officielles actuelles pour toute transaction."]}];
translated.fr.finds.sections=[{title:"Chercher avec une question",body:["Associez la catégorie au détail décisif : tour de poitrine, semelle, intérieur, poids emballé ou type de prise."]},{title:"Comparer des produits similaires",body:["Placez trois options proches côte à côte et examinez fabrication, mesures, prix et effet sur la livraison."]},{title:"Contrôler la destination",body:["Titre, image et variante doivent toujours correspondre après l’ouverture du lien. Un convertisseur ne valide ni vendeur ni stock."]},{title:"Retirer tôt les candidats faibles",body:["Mesures absentes, image générique, option ambiguë ou destination différente justifient l’arrêt."]}];
translated.fr.guide.sections=[{title:"1 — Identité",body:["Comparez type, couleur, option et caractéristiques principales entre la feuille et la destination."]},{title:"2 — Fabrication et ajustement",body:["Examinez les photos QC et les mesures propres à la catégorie."]},{title:"3 — Prix et livraison",body:["Comparez le prix à des articles proches puis ajoutez poids et volume probables."]},{title:"4 — Note de décision",body:["Inscrivez garder/retirer, preuves, question ouverte, alternative et date de contrôle."]}];
translated.fr.qc.sections=[{title:"1. Identité et variante",body:["Vérifiez couleur, forme et option par rapport à la fiche prévue."]},{title:"2. Fabrication et détails",body:["Contrôlez coutures, bords, fermetures, impression, quincaillerie, semelle ou ports selon la catégorie."]},{title:"3. Mesures et échelle",body:["Cherchez tableau, règle, mesure du vêtement ou autre référence stable."]},{title:"Limites des images",body:["Les photos ne garantissent ni composition, fonction, authenticité, durabilité ou livraison."]}];
translated.fr.shipping.sections=[{title:"Poids réel et volumétrique",body:["L’estimateur officiel affiche comme exemple longueur × largeur × hauteur en cm ÷ 6000. La règle de la ligne actuelle reste déterminante."]},{title:"Construire une estimation réaliste",body:["Additionnez les poids puis prévoyez carton, protection et consolidation."]},{title:"Vérifier l’éligibilité d’abord",body:["Batteries, liquides, aimants et autres catégories peuvent limiter les lignes disponibles."]},{title:"Contrôler avant paiement",body:["Pays, ligne, poids, dimensions, restrictions et conditions doivent être revérifiés."]}];
translated.fr.faq.sections=[{title:"Qu’est-ce qu’une feuille LoveGoBuy ?",body:["Un annuaire de liens, catégories, images, prix ou notes ; pas une garantie."]},{title:"Est-ce un service officiel ?",body:["Non. Ce site ne crée pas de compte, ne prend pas de paiement, n’achète pas et ne gère pas les remboursements."]},{title:"Une carte signifie-t-elle vérifié ?",body:["Non. Revérifiez destination, option, vendeur, QC, mesures, prix et disponibilité."]},{title:"Quel est le coût de livraison ?",body:["Destination, ligne, poids, volume, restrictions et frais modifient le montant."]}];

translated.it.spreadsheet.sections=[{title:"Inizia da una categoria",body:["Un elenco misto altera il confronto. Scegli prima un tipo di prodotto per valutare prezzo, taglia, foto e peso tra articoli simili."]},{title:"Ogni riga è solo una pista",body:["Apri la destinazione e confronta titolo, immagine, opzione, misure e prezzo. Una riga non dimostra qualità o disponibilità."]},{title:"Separa prove e ipotesi",body:["Annota ciò che è visibile e ciò che resta sconosciuto. Popolarità e immagini attraenti non sostituiscono i dettagli verificabili."]},{title:"Ricontrolla prima di agire",body:["Pagine, opzioni, prezzi e rotte cambiano. Per le transazioni usa informazioni ufficiali aggiornate."]}];
translated.it.finds.sections=[{title:"Cerca con una domanda",body:["Combina la categoria con il dettaglio decisivo: misura del petto, suola, interno, peso imballato o tipo di spina."]},{title:"Confronta prodotti simili",body:["Metti tre opzioni vicine a confronto e controlla costruzione, misure, prezzo e impatto sulla spedizione."]},{title:"Controlla la destinazione",body:["Titolo, immagine e variante devono ancora coincidere dopo l’apertura del link. Un convertitore non verifica venditore o stock."]},{title:"Rimuovi presto i candidati deboli",body:["Misure mancanti, immagine generica, variante confusa o destinazione diversa sono motivi per fermarsi."]}];
translated.it.guide.sections=[{title:"1 — Identità",body:["Confronta tipo, colore, opzione e caratteristiche principali tra foglio e destinazione."]},{title:"2 — Costruzione e vestibilità",body:["Esamina foto QC e misure specifiche della categoria."]},{title:"3 — Prezzo e spedizione",body:["Confronta il prezzo con articoli simili e aggiungi peso e volume probabili."]},{title:"4 — Nota decisionale",body:["Registra conserva/rimuovi, prove, domanda aperta, alternativa e data."]}];
translated.it.qc.sections=[{title:"1. Identità e variante",body:["Controlla colore, forma e opzione rispetto alla scheda prevista."]},{title:"2. Costruzione e dettagli",body:["Esamina cuciture, bordi, chiusure, stampa, hardware, suola o porte secondo la categoria."]},{title:"3. Misure e scala",body:["Cerca tabella, righello, misura del capo o altro riferimento stabile."]},{title:"Limiti delle immagini",body:["Le foto non garantiscono composizione, funzione, autenticità, durata o consegna."]}];
translated.it.shipping.sections=[{title:"Peso reale e volumetrico",body:["Lo stimatore ufficiale mostra come esempio lunghezza × larghezza × altezza in cm ÷ 6000. La regola della rotta attuale resta decisiva."]},{title:"Costruisci una stima realistica",body:["Somma i pesi e considera scatola, protezione e consolidamento."]},{title:"Controlla prima l’idoneità",body:["Batterie, liquidi, magneti e altre categorie possono limitare le rotte disponibili."]},{title:"Verifica prima del pagamento",body:["Paese, linea, peso, dimensioni, restrizioni e condizioni devono essere ricontrollati."]}];
translated.it.faq.sections=[{title:"Cos’è un foglio LoveGoBuy?",body:["Una directory di link, categorie, immagini, prezzi o note; non una garanzia."]},{title:"È un servizio ufficiale?",body:["No. Il sito non crea account, incassa, acquista, immagazzina o gestisce rimborsi."]},{title:"Una scheda significa verificato?",body:["No. Ricontrolla destinazione, opzione, venditore, QC, misure, prezzo e disponibilità."]},{title:"Quanto costa la spedizione?",body:["Destinazione, rotta, peso, volume, restrizioni e tariffe cambiano il totale."]}];

const pageCopyBase: Record<Language, Record<string, ContentRecord>> = { en, ...translated };
applyPageLocalizedParity(pageCopyBase);
enrichPageCopy(pageCopyBase);
export const pageCopy = pageCopyBase;
