export const languages = ["en", "de", "es", "fr", "it"] as const;
export type Language = (typeof languages)[number];

export const languageNames: Record<Language, string> = {
  en: "English", de: "Deutsch", es: "Español", fr: "Français", it: "Italiano",
};

export const ui: Record<Language, any> = {
  en: {
    locale: "EN", ticker: ["INDEPENDENT LOVEGOBUY RESEARCH DESK", "FACT CHECKED 31 AUG 2026", "PRICES & ROUTES CAN CHANGE"],
    nav: ["Finds", "QC guide", "Shipping", "Articles"], eyebrow: "QC evidence and measurements, not hype", edition: "2026 edition",
    hero: ["Inspect it.", "Measure it.", "Then plan it."], lead: "A focused LoveGoBuy QC and product-measurement guide for comparing variants, sizing evidence, construction details and chargeable weight before you commit.",
    searchLabel: "Search the live product directory", searchPlaceholder: "Try hoodie, jersey, shoes…", searchButton: "Search ↗", searchNote: "Results open on the product source. Always re-check the live listing.",
    board: ["Does the product route match?", "Are size and QC details useful?", "Does packed weight change value?"], check: "CHECK",
    findsKicker: "LIVE ROUTES / USD REFERENCE", findsTitle: "Fresh finds, with a reason to click.", browse: "Browse all products ↗", inspect: "Inspect route ↗",
    priceNote: "*USD references are approximate conversions of source prices checked on 31 Aug 2026. The live destination controls current price, stock and options.",
    workflowKicker: "THE FOUR-PASS METHOD", workflowTitle: "Every promising find has to earn the next click.", workflowLead: "Unlike a simple link wall, this guide separates the product evidence from the excitement around it.",
    checks: [["Match the route", "Confirm the title, image and selected option still agree after the handoff."], ["Read the QC set", "Check identity, construction and measurements—not just the cleanest photo."], ["Add shipping context", "Compare actual and dimensional weight before a low item price wins."], ["Save with a reason", "Keep the find only when you can explain why it beats nearby alternatives."]],
    shippingKicker: "OFFICIAL PLANNING CONCEPT", shippingTitle: "Volume can outweigh the scale.", shippingText: "LoveGoBuy’s public estimator explains that many routes compare scale weight with dimensional weight. One published dimensional formula is:", estimator: "Check the current official estimator ↗", estimateTitle: "Estimate in this order", estimateSteps: ["Add likely item weight.", "Consider the packed dimensions.", "Compare eligible routes and restrictions.", "Recheck official terms before payment."],
    articlesKicker: "RESEARCH NOTES", articlesTitle: "Read the question you have now.", faqKicker: "STRAIGHT ANSWERS", faqTitle: "Before you follow a link.",
    faqIntro: "This is an independent research and browsing guide. Account, payment, order and parcel questions belong to current official support.",
    faqs: [["Is this the official LoveGoBuy website?", "No. This independent site explains spreadsheet research and sends product discovery to the listed external destination. It does not process orders or payments."], ["Are the products verified?", "A visible route is not a guarantee. Recheck the destination, selected option, seller information, QC photos, sizing, price and current availability."], ["How much will shipping cost?", "There is no permanent answer. Destination, packed weight, dimensions, route, restrictions, fees and current service terms can all change the total."], ["Why show prices in USD?", "USD references make initial comparison faster. They are approximate and never replace the live destination price or checkout total."]],
    footer: "Independent product-research notes for LoveGoBuy spreadsheet users. No sales, payments, seller verification or shipping services are provided here.",
  },
  de: {
    locale: "DE", ticker: ["UNABHÄNGIGE LOVEGOBUY-RECHERCHE", "GEPRÜFT AM 31. AUGUST 2026", "PREISE UND ROUTEN KÖNNEN SICH ÄNDERN"], nav: ["Fundstücke", "QC-Ratgeber", "Versand", "Artikel"], eyebrow: "QC-Nachweise und Maße statt Werbeversprechen", edition: "Ausgabe 2026",
    hero: ["Prüfen.", "Messen.", "Planen."], lead: "Ein fokussierter LoveGoBuy-Ratgeber zum Vergleichen von QC-Nachweisen, Varianten, Größen, Produktmaßen und abrechenbarem Gewicht.", searchLabel: "Im aktuellen Produktverzeichnis suchen", searchPlaceholder: "Hoodie, Trikot, Schuhe…", searchButton: "Suchen ↗", searchNote: "Ergebnisse öffnen an der Produktquelle. Prüfe den aktuellen Eintrag erneut.",
    board: ["Passt die Produktroute?", "Sind Größe und QC aussagekräftig?", "Verändert das Packgewicht den Wert?"], check: "PRÜFEN", findsKicker: "AKTUELLE ROUTEN / USD-REFERENZ", findsTitle: "Neue Fundstücke mit einem Grund zum Klicken.", browse: "Alle Produkte öffnen ↗", inspect: "Route prüfen ↗", priceNote: "*USD-Werte sind ungefähre Umrechnungen der am 31. August 2026 geprüften Quellpreise. Preis, Bestand und Optionen der Zielseite sind maßgeblich.",
    workflowKicker: "DIE VIER PRÜFSCHRITTE", workflowTitle: "Jedes Fundstück muss sich den nächsten Klick verdienen.", workflowLead: "Dieser Leitfaden trennt sichtbare Produktnachweise von bloßer Begeisterung.", checks: [["Route abgleichen", "Titel, Bild und gewählte Variante müssen nach der Weiterleitung noch übereinstimmen."], ["QC-Bilder lesen", "Identität, Verarbeitung und Maße prüfen – nicht nur das schönste Foto."], ["Versand einrechnen", "Tatsächliches und volumetrisches Gewicht vergleichen, bevor der Artikelpreis entscheidet."], ["Begründet speichern", "Nur behalten, wenn der Vorteil gegenüber ähnlichen Treffern erklärbar ist."]],
    shippingKicker: "OFFIZIELLES PLANUNGSPRINZIP", shippingTitle: "Volumen kann schwerer wiegen als die Waage.", shippingText: "Der öffentliche LoveGoBuy-Rechner erklärt, dass viele Routen Waagengewicht und Volumengewicht vergleichen. Eine veröffentlichte Formel lautet:", estimator: "Aktuellen offiziellen Rechner öffnen ↗", estimateTitle: "In dieser Reihenfolge planen", estimateSteps: ["Voraussichtliches Artikelgewicht addieren.", "Verpackungsmaße berücksichtigen.", "Zulässige Routen und Einschränkungen vergleichen.", "Vor Zahlung offizielle Bedingungen prüfen."],
    articlesKicker: "RECHERCHE-NOTIZEN", articlesTitle: "Lies zuerst die Frage, die du gerade hast.", faqKicker: "KLARE ANTWORTEN", faqTitle: "Bevor du einem Link folgst.", faqIntro: "Unabhängiger Rechercheleitfaden. Konto-, Zahlungs-, Bestell- und Paketfragen gehören zum offiziellen Support.", faqs: [["Ist dies die offizielle LoveGoBuy-Seite?", "Nein. Diese unabhängige Seite erklärt Spreadsheet-Recherche und verarbeitet weder Bestellungen noch Zahlungen."], ["Sind die Produkte verifiziert?", "Eine sichtbare Route ist keine Garantie. Zielseite, Variante, Verkäuferangaben, QC-Fotos, Größen, Preis und Verfügbarkeit erneut prüfen."], ["Wie hoch sind die Versandkosten?", "Es gibt keinen dauerhaften Festpreis. Ziel, Packgewicht, Maße, Route, Einschränkungen und Gebühren verändern das Ergebnis."], ["Warum Preise in USD?", "USD-Referenzen erleichtern den ersten Vergleich, ersetzen aber nie den aktuellen Zielpreis oder Checkout-Betrag."]], footer: "Unabhängige Produktrecherche für LoveGoBuy-Spreadsheet-Nutzer. Kein Verkauf, keine Zahlung, Verkäuferprüfung oder Versanddienstleistung.",
  },
  es: {
    locale: "ES", ticker: ["MESA INDEPENDIENTE DE INVESTIGACIÓN LOVEGOBUY", "VERIFICADO EL 31 AGO 2026", "PRECIOS Y RUTAS PUEDEN CAMBIAR"], nav: ["Hallazgos", "Guía QC", "Envío", "Artículos"], eyebrow: "Información útil, no publicidad", edition: "edición 2026",
    hero: ["Inspecciona.", "Mide.", "Planifica."], lead: "Una guía LoveGoBuy centrada en comparar pruebas QC, variantes, tallas, medidas del producto y peso facturable antes de decidir.", searchLabel: "Buscar en el directorio de productos", searchPlaceholder: "Sudadera, camiseta, zapatillas…", searchButton: "Buscar ↗", searchNote: "Los resultados se abren en la fuente. Comprueba siempre la ficha actual.",
    board: ["¿Coincide la ruta del producto?", "¿Sirven la talla y las fotos QC?", "¿Cambia el valor con el peso embalado?"], check: "REVISAR", findsKicker: "RUTAS ACTIVAS / REFERENCIA USD", findsTitle: "Hallazgos recientes con motivos para abrirlos.", browse: "Ver todos los productos ↗", inspect: "Revisar ruta ↗", priceNote: "*Las cifras en USD son conversiones aproximadas de los precios revisados el 31 de agosto de 2026. El destino determina precio, stock y opciones actuales.",
    workflowKicker: "MÉTODO DE CUATRO PASOS", workflowTitle: "Cada hallazgo debe ganarse el siguiente clic.", workflowLead: "La guía separa las pruebas visibles del entusiasmo que rodea al producto.", checks: [["Comparar la ruta", "Título, imagen y variante deben seguir coincidiendo después del enlace."], ["Leer las fotos QC", "Revisa identidad, construcción y medidas, no solo la foto más bonita."], ["Añadir el envío", "Compara peso real y volumétrico antes de elegir por precio."], ["Guardar con motivo", "Conserva el hallazgo solo si puedes explicar por qué supera alternativas cercanas."]],
    shippingKicker: "CONCEPTO OFICIAL DE PLANIFICACIÓN", shippingTitle: "El volumen puede pesar más que la báscula.", shippingText: "El estimador público de LoveGoBuy explica que muchas rutas comparan peso real y volumétrico. Una fórmula publicada es:", estimator: "Abrir estimador oficial actual ↗", estimateTitle: "Calcula en este orden", estimateSteps: ["Suma el peso probable.", "Considera las medidas embaladas.", "Compara rutas y restricciones válidas.", "Revisa las condiciones oficiales antes de pagar."],
    articlesKicker: "NOTAS DE INVESTIGACIÓN", articlesTitle: "Lee la respuesta a tu pregunta actual.", faqKicker: "RESPUESTAS DIRECTAS", faqTitle: "Antes de seguir un enlace.", faqIntro: "Guía independiente. Las consultas de cuenta, pago, pedido y paquete corresponden al soporte oficial.", faqs: [["¿Es la web oficial de LoveGoBuy?", "No. Es una guía independiente y no procesa pedidos ni pagos."], ["¿Están verificados los productos?", "Una ruta visible no garantiza nada. Revisa destino, variante, vendedor, fotos QC, talla, precio y disponibilidad."], ["¿Cuánto cuesta el envío?", "No existe una respuesta fija. Destino, peso, volumen, ruta, restricciones y tasas cambian el total."], ["¿Por qué precios en USD?", "Las referencias USD agilizan la comparación inicial, pero no sustituyen el precio vivo ni el total final."]], footer: "Notas independientes para usuarios de hojas LoveGoBuy. No vendemos, cobramos, verificamos vendedores ni prestamos servicios de envío.",
  },
  fr: {
    locale: "FR", ticker: ["BUREAU DE RECHERCHE LOVEGOBUY INDÉPENDANT", "VÉRIFIÉ LE 31 AOÛT 2026", "PRIX ET ITINÉRAIRES PEUVENT CHANGER"], nav: ["Trouvailles", "Guide QC", "Livraison", "Articles"], eyebrow: "Des preuves, pas du battage", edition: "édition 2026",
    hero: ["Inspectez.", "Mesurez.", "Planifiez."], lead: "Un guide LoveGoBuy axé sur la comparaison des preuves QC, variantes, tailles, mesures produit et poids facturable avant de décider.", searchLabel: "Rechercher dans l’annuaire produit", searchPlaceholder: "Sweat, maillot, chaussures…", searchButton: "Rechercher ↗", searchNote: "Les résultats s’ouvrent à la source. Vérifiez toujours la fiche actuelle.",
    board: ["Le lien correspond-il au produit ?", "La taille et les photos QC sont-elles utiles ?", "Le poids emballé change-t-il la valeur ?"], check: "VÉRIFIER", findsKicker: "LIENS ACTIFS / RÉFÉRENCE USD", findsTitle: "Des trouvailles récentes qui méritent le clic.", browse: "Voir tous les produits ↗", inspect: "Inspecter le lien ↗", priceNote: "*Les montants USD sont des conversions approximatives des prix vérifiés le 31 août 2026. La page de destination fait foi pour le prix, le stock et les options.",
    workflowKicker: "LA MÉTHODE EN QUATRE PASSES", workflowTitle: "Chaque trouvaille doit mériter le clic suivant.", workflowLead: "Ce guide sépare les preuves produit de l’enthousiasme qui l’entoure.", checks: [["Comparer le lien", "Titre, image et variante doivent encore correspondre après le transfert."], ["Lire les photos QC", "Contrôlez identité, fabrication et mesures, pas seulement la meilleure image."], ["Ajouter l’expédition", "Comparez poids réel et volumétrique avant de choisir sur le prix."], ["Enregistrer avec raison", "Gardez l’article seulement si son avantage sur les alternatives est explicable."]],
    shippingKicker: "PRINCIPE OFFICIEL DE PLANIFICATION", shippingTitle: "Le volume peut peser plus lourd que la balance.", shippingText: "L’estimateur public LoveGoBuy indique que de nombreuses lignes comparent poids réel et poids volumétrique. Une formule publiée est :", estimator: "Ouvrir l’estimateur officiel ↗", estimateTitle: "Estimer dans cet ordre", estimateSteps: ["Additionner le poids probable.", "Considérer les dimensions emballées.", "Comparer lignes et restrictions éligibles.", "Revérifier les conditions officielles avant paiement."],
    articlesKicker: "NOTES DE RECHERCHE", articlesTitle: "Lisez la réponse à votre question actuelle.", faqKicker: "RÉPONSES DIRECTES", faqTitle: "Avant de suivre un lien.", faqIntro: "Guide de recherche indépendant. Les questions de compte, paiement, commande et colis relèvent du support officiel.", faqs: [["Est-ce le site officiel LoveGoBuy ?", "Non. Ce site indépendant explique la recherche et ne traite ni commande ni paiement."], ["Les produits sont-ils vérifiés ?", "Un lien visible n’est pas une garantie. Revérifiez destination, option, vendeur, photos QC, taille, prix et disponibilité."], ["Combien coûte la livraison ?", "Il n’existe pas de montant permanent. Destination, poids, volume, ligne, restrictions et frais changent le total."], ["Pourquoi afficher des prix USD ?", "Les références USD facilitent la comparaison initiale mais ne remplacent jamais le prix en direct."]], footer: "Notes indépendantes pour utilisateurs de feuilles LoveGoBuy. Aucune vente, paiement, vérification vendeur ou prestation d’expédition.",
  },
  it: {
    locale: "IT", ticker: ["DESK INDIPENDENTE DI RICERCA LOVEGOBUY", "VERIFICATO IL 31 AGO 2026", "PREZZI E ROTTE POSSONO CAMBIARE"], nav: ["Prodotti", "Guida QC", "Spedizione", "Articoli"], eyebrow: "Informazioni utili, non clamore", edition: "edizione 2026",
    hero: ["Controlla.", "Misura.", "Pianifica."], lead: "Una guida LoveGoBuy focalizzata sul confronto di prove QC, varianti, taglie, misure prodotto e peso tassabile prima di decidere.", searchLabel: "Cerca nella directory prodotti", searchPlaceholder: "Felpa, maglia, scarpe…", searchButton: "Cerca ↗", searchNote: "I risultati si aprono alla fonte. Ricontrolla sempre la scheda attuale.",
    board: ["La rotta corrisponde al prodotto?", "Taglia e foto QC sono utili?", "Il peso imballato cambia il valore?"], check: "CONTROLLA", findsKicker: "ROTTE ATTIVE / RIFERIMENTO USD", findsTitle: "Nuovi prodotti con un motivo per aprirli.", browse: "Vedi tutti i prodotti ↗", inspect: "Controlla rotta ↗", priceNote: "*I valori USD sono conversioni approssimative dei prezzi verificati il 31 agosto 2026. La destinazione determina prezzo, disponibilità e opzioni correnti.",
    workflowKicker: "IL METODO IN QUATTRO PASSAGGI", workflowTitle: "Ogni prodotto deve meritare il clic successivo.", workflowLead: "La guida separa le prove visibili dall’entusiasmo che circonda il prodotto.", checks: [["Confronta la rotta", "Titolo, immagine e variante devono ancora coincidere dopo il passaggio."], ["Leggi le foto QC", "Controlla identità, costruzione e misure, non soltanto la foto migliore."], ["Aggiungi la spedizione", "Confronta peso reale e volumetrico prima di scegliere in base al prezzo."], ["Salva con un motivo", "Conserva il prodotto solo se sai spiegare perché supera alternative simili."]],
    shippingKicker: "CONCETTO UFFICIALE DI PIANIFICAZIONE", shippingTitle: "Il volume può pesare più della bilancia.", shippingText: "Lo stimatore pubblico LoveGoBuy spiega che molte rotte confrontano peso reale e volumetrico. Una formula pubblicata è:", estimator: "Apri lo stimatore ufficiale ↗", estimateTitle: "Calcola in questo ordine", estimateSteps: ["Somma il peso probabile.", "Considera le dimensioni imballate.", "Confronta rotte e restrizioni idonee.", "Ricontrolla le condizioni ufficiali prima del pagamento."],
    articlesKicker: "NOTE DI RICERCA", articlesTitle: "Leggi la risposta alla domanda che hai ora.", faqKicker: "RISPOSTE DIRETTE", faqTitle: "Prima di seguire un link.", faqIntro: "Guida di ricerca indipendente. Le domande su account, pagamenti, ordini e pacchi spettano al supporto ufficiale.", faqs: [["È il sito ufficiale LoveGoBuy?", "No. È una guida indipendente e non gestisce ordini o pagamenti."], ["I prodotti sono verificati?", "Una rotta visibile non è una garanzia. Ricontrolla destinazione, opzione, venditore, foto QC, taglia, prezzo e disponibilità."], ["Quanto costa la spedizione?", "Non c’è una risposta fissa. Destinazione, peso, volume, rotta, restrizioni e costi cambiano il totale."], ["Perché prezzi in USD?", "I riferimenti USD velocizzano il primo confronto ma non sostituiscono il prezzo live o il totale finale."]], footer: "Note indipendenti per utenti dei fogli LoveGoBuy. Nessuna vendita, pagamento, verifica venditore o servizio di spedizione.",
  },
};

export const categories = [
  { name: "Shoes", note: "shape · sole · sizing", href: "https://cnfansge.com/shoes/", tone: "blue" },
  { name: "Hoodies", note: "fit · fabric · weight", href: "https://cnfansge.com/hoodies-sweaters/", tone: "orange" },
  { name: "Jackets", note: "lining · hardware · volume", href: "https://cnfansge.com/jackets/", tone: "lime" },
  { name: "Jerseys", note: "size · print · variant", href: "https://cnfansge.com/jersey/", tone: "pink" },
  { name: "Accessories", note: "scale · finish · details", href: "https://cnfansge.com/accessories/", tone: "violet" },
  { name: "Electronics", note: "spec · plug · restrictions", href: "https://cnfansge.com/electronics/", tone: "cyan" },
];

export const products = [
  { name: "Sweatshirt 01", price: "$23.60*", image: "https://cnfansge.com/uploads/allimg/20260506/1-260506103535537.webp", href: "https://cnfansge.com/AllProducts/6681.html", tag: "Latest" },
  { name: "Pants / Shorts 01", price: "$26.40*", image: "https://cnfansge.com/uploads/allimg/20260506/1-26050610331M37.webp", href: "https://cnfansge.com/AllProducts/6680.html", tag: "Latest" },
  { name: "Jersey 55", price: "$18.30*", image: "https://cnfansge.com/uploads/allimg/20260422/1-2604222250014B.jpg", href: "https://cnfansge.com/AllProducts/6679.html", tag: "Popular" },
  { name: "Jersey 54", price: "$18.30*", image: "https://cnfansge.com/uploads/allimg/20260422/1-260422225000a6.jpg", href: "https://cnfansge.com/AllProducts/6678.html", tag: "Popular" },
  { name: "Jersey 53", price: "$18.30*", image: "https://cnfansge.com/uploads/allimg/20260422/1-260422224959349.jpg", href: "https://cnfansge.com/AllProducts/6677.html", tag: "New route" },
  { name: "Jersey 52", price: "$10.50*", image: "https://cnfansge.com/uploads/allimg/20260422/1-260422224959462.jpg", href: "https://cnfansge.com/AllProducts/6676.html", tag: "Value" },
];

export const articleCards = {
  en: [["START HERE · 16 MIN", "How to use a LoveGoBuy spreadsheet without saving weak links", "Move from a broad category to three explainable candidates with a repeatable evidence checklist."], ["QC · 15 MIN", "Read warehouse photos in three passes", "Confirm the variant, inspect construction, then find measurements or stable scale."], ["SHIPPING · 15 MIN", "Actual weight vs dimensional weight", "Understand why two equal-price finds can create very different parcel totals."]],
  de: [["START · 16 MIN", "Ein LoveGoBuy-Spreadsheet nutzen, ohne schwache Links zu speichern", "Von der Kategorie zu drei begründbaren Kandidaten."], ["QC · 15 MIN", "Lagerfotos in drei Durchgängen lesen", "Variante, Verarbeitung und Maße systematisch prüfen."], ["VERSAND · 15 MIN", "Tatsächliches Gewicht und Volumengewicht", "Warum gleich teure Artikel unterschiedliche Paketkosten erzeugen."]],
  es: [["EMPEZAR · 16 MIN", "Usar una hoja LoveGoBuy sin guardar enlaces débiles", "Pasa de una categoría amplia a tres candidatos explicables."], ["QC · 15 MIN", "Leer fotos de almacén en tres pasos", "Confirma variante, construcción y medidas."], ["ENVÍO · 15 MIN", "Peso real frente a peso volumétrico", "Por qué dos artículos similares crean costes de paquete distintos."]],
  fr: [["DÉBUT · 16 MIN", "Utiliser une feuille LoveGoBuy sans garder les liens faibles", "Passez d’une catégorie large à trois candidats justifiables."], ["QC · 15 MIN", "Lire les photos d’entrepôt en trois étapes", "Confirmez variante, fabrication et mesures."], ["LIVRAISON · 15 MIN", "Poids réel et poids volumétrique", "Pourquoi deux articles au même prix peuvent coûter différemment."]],
  it: [["INIZIA · 16 MIN", "Usare un foglio LoveGoBuy senza salvare link deboli", "Passa da una categoria ampia a tre candidati spiegabili."], ["QC · 15 MIN", "Leggere le foto di magazzino in tre passaggi", "Conferma variante, costruzione e misure."], ["SPEDIZIONE · 15 MIN", "Peso reale e peso volumetrico", "Perché due articoli simili possono generare costi diversi."]],
};

export const articleSlugs = ["lovegobuy-spreadsheet-guide", "lovegobuy-qc-photo-guide", "lovegobuy-shipping-weight"];
