import type { Locale } from "@/lib/site";

type TranslatedLocale = Exclude<Locale, "en">;

export const localizedArticleParity: Record<TranslatedLocale, Record<string, string[]>> = {
  de: {
    "oopbuy-beginner-guide-2026": [
      "Führe zum Abschluss eine vollständige Übergabeprüfung durch. Die gespeicherte Produkt-ID und Variante müssen mit dem eingelagerten Artikel, der finalen Paketliste und dem Waybill verknüpft bleiben. Notiere nicht nur den Gesamtbetrag, sondern auch, welche Werte damals nur Schätzungen waren: Verkäufergewicht, mögliches Paketvolumen, Wechselkurs und Routenpreis. Nach der Lieferung ersetzt du diese Annahmen durch den beobachteten Wert. So entsteht aus einer Bestellung ein datierter Datensatz, ohne dass eine einzelne schnelle oder langsame Sendung zur allgemeinen Aussage über OOPBUY, einen Verkäufer oder eine Route wird.",
      "Auch beim Einsteigerablauf bleiben die Beweisgrenzen wichtig. Eine Live-Produktseite belegt das aktuelle Angebot, nicht den später erhaltenen Artikel. Die Bestellung belegt die gewählte Option, nicht deren Passform. Lagerfotos belegen sichtbare Merkmale, aber keine Echtheit, Faserzusammensetzung, interne Funktion oder Haltbarkeit. Ein Trackingereignis belegt einen Scan, nicht die Ursache jeder Verzögerung. Wenn du diese Grenzen zusammen mit Datum, Referenz und Quelle dokumentierst, kannst du konkrete Probleme beschreiben, aktuelle Hilferegeln rechtzeitig anwenden und spätere Entscheidungen auf stärkere Belege statt Erinnerung stützen." ],
    "oopbuy-spreadsheet-workflow": [
      "Prüfe zusätzlich die Wartbarkeit der Tabelle. Eine zweite Person sollte aus jeder aktiven Zeile verstehen können, welche Option gemeint ist, was bereits bestätigt wurde und welche Frage offen bleibt. Verwende keine private Kurzschrift ohne Legende. Halte Originalwährung und Prüfdatum neben der ungefähren USD-Umrechnung, damit Wechselkursbewegung und Preisänderung nicht verwechselt werden. Eine Zeile bleibt nur aktiv, wenn die Route funktioniert, die Kategorie noch stimmt und das Risiko sichtbar beschrieben ist. Entferne tote Einträge, statt die Anzahl als Qualitätsmerkmal zu behandeln.",
      "Schließe nach der Lieferung die Lernschleife. Vergleiche geplantes und tatsächliches Lagergewicht, Packmaß, Route, Belastung, Laufzeit und Zustand. Wenn die Abweichung groß ist, ordne sie einer veränderten Eingabe zu: Gewicht, Volumen, Verpackung, Service oder Preisstand. Diese Erklärung verbessert die nächste Kategorieschätzung stärker als eine isolierte Endsumme. Bewahre außerdem die ursprüngliche Zeile, die QC-Entscheidung und die Paketzuordnung zusammen auf. So bleibt der Produktpfad auch dann rekonstruierbar, wenn die Verkäuferseite später umgebaut oder gelöscht wird." ],
    "oopbuy-qc-photo-checklist": [
      "Bildqualität ist selbst Teil der Prüfung. Weitwinkel kann Formen am Rand übertreiben, automatischer Weißabgleich kann Farben verschieben und Kompression kann feine Struktur oder kleine Spuren verdecken. Wenn ein möglicher Mangel nur in einer Aufnahme erscheint, vergleiche weitere Winkel, bevor du ihn als bestätigt notierst. Bei Messungen muss klar sein, ob Einlegesohle, Außensohle oder nutzbare Innenlänge gemeint ist; diese Werte sind nicht austauschbar. Dasselbe gilt bei Kleidungsbreite, Länge und Schultermaß: Anfangs- und Endpunkt müssen zur gespeicherten Verkäufermethode passen.",
      "Der Abschlussstatus sollte knapp, aber vollständig sein: akzeptiert, gezielte Zusatzansicht benötigt, Aftersales versucht oder vom Paket ausgeschlossen. Ergänze Datum, objektiven Grund und den entscheidenden Bildausschnitt. Bewahre Referenz, Lagerbilder und Ergebnis zusammen auf. Ein früher erfolgreich geprüfter Artikel ist keine Garantie für eine spätere Charge; IDs, Varianten, Verkäufer, Fertigung und Fotografie können sich ändern. Alte Datensätze helfen, die richtigen Fragen schneller zu stellen, ersetzen aber niemals die visuelle Prüfung des aktuell eingelagerten Einzelstücks." ],
    "oopbuy-fees-returns-policy": [
      "Erstelle vor jeder Zahlung eine Belegmappe statt einer pauschalen Gebührenaussage. Speichere Produktpreis, chinesische Inlandsfracht, im Checkout sichtbare Zahlungs- oder Plattformpositionen, optionale Leistungen, Verpackung, internationalen Versand und mögliche Zielabgaben getrennt mit Datum und Währung. Wenn offizielle Texte weiterhin unterschiedlich formuliert sind, zeige beide, ohne eine Erklärung zu erfinden. Die aktuelle aufgeschlüsselte Zahlung und eine schriftliche Antwort mit Bestellreferenz sind für den konkreten Vorgang stärker als ein alter Werbesatz oder eine nicht datierte Zusammenfassung.",
      "Fristen benötigen ebenfalls zwei getrennte Kalender. Das veröffentlichte Rückgabe- oder Umtauschfenster wird für die QC-Entscheidung genutzt, während die längere Lagerdauer nur Konsolidierung und Paketplanung betrifft. Ein rechtzeitig eingereichter Antrag ist keine automatische Genehmigung; Verkäuferregeln, Artikelzustand, Verantwortung, Rücktransport und aktuelle Servicebedingungen können das Ergebnis beeinflussen. Dokumentiere deshalb Einlagerungszeit, sichtbare Abweichung, Variantentext, Fotos und Anfrageweg. Prüfe vor jeder Handlung die aktuelle offizielle Seite, weil eine am 1. September 2026 bestätigte Zahl keine dauerhafte Garantie ist." ],
    "oopbuy-shipping-cost-planner": [
      "Plane das Volumen nach Form, nicht durch blindes Addieren von Einzelmaßen. Weiche Kleidung kann Lücken um einen starren Gegenstand füllen, zwei starre Kartons lassen sich dagegen möglicherweise nicht ineinander packen. Halte für alle verglichenen Routen dieselben plausiblen Paketannahmen konstant; nur dann wird sichtbar, ob eine Preisabweichung aus Berechnung, Größenlimit, enthaltenem Tracking oder Service entsteht. Verwende die aktuelle Regel der konkreten Route und keinen universellen Divisor. Endgültige Lager- und Packmaße ersetzen später die grobe Vorbestellannahme.",
      "Nach der Lieferung dokumentierst du tatsächliche Belastung, Laufzeit, Trackingqualität, Zustand und jede besondere Packentscheidung wie Teilung, Vakuumierung, Boxentfernung oder zusätzlichen Schutz. Vergleiche das Ergebnis mit dem erwarteten Szenario und benenne den größten Schätzfehler. Mehrere vergleichbare Pakete erlauben später eine Spanne und einen Median; ein einzelner Bestfall ist keine belastbare Norm. Datum und Währung bleiben neben historischen Summen, damit eine Routenpreisänderung nicht mit einer verbesserten Packschätzung verwechselt wird." ],
  },
  es: {
    "oopbuy-beginner-guide-2026": [
      "Termina con una auditoría completa de los traspasos. El ID del producto y la variante guardados deben quedar unidos al artículo de almacén, a la lista final del paquete y a la guía de envío. No registres solo el total: indica qué valores eran estimaciones, como peso del vendedor, volumen probable, tipo de cambio o tarifa de ruta. Después de la entrega sustituye esas hipótesis por datos observados. Así una compra se convierte en registro fechado sin transformar un envío rápido o lento en una afirmación universal sobre OOPBUY, un vendedor o una línea.",
      "Los límites de prueba siguen siendo esenciales. La página activa demuestra la oferta actual, no el artículo futuro. El pedido demuestra la opción elegida, no el ajuste. Las fotos muestran rasgos visibles, no autenticidad, fibras, función interna o duración. Un evento de seguimiento demuestra un escaneo, no la causa de cada retraso. Si documentas estos límites junto con fecha, referencia y fuente, podrás describir problemas concretos, usar a tiempo el proceso vigente y apoyar la siguiente decisión en evidencia más fuerte que la memoria.",
      "Utiliza una matriz sencilla para que ninguna etapa quede huérfana: anuncio y opción antes de comprar; referencia e importe después del pago; estado, imágenes y reloj al entrar; contenido, medidas y protección al crear el paquete; seguimiento y condición al recibir. Si falta uno de esos enlaces, anótalo como hueco en vez de reconstruirlo con una suposición. La matriz también distingue hechos variables que deben volver a consultarse en la pantalla vigente de los principios que siguen siendo útiles entre pedidos." ],
    "oopbuy-spreadsheet-workflow": [
      "Audita también si la hoja puede mantenerse. Otra persona debe entender en cada fila qué opción se eligió, qué se confirmó y qué pregunta sigue abierta. Evita abreviaturas privadas sin leyenda. Conserva moneda original y fecha junto a la conversión aproximada en USD para no confundir variación del cambio con cambio de precio. Una fila permanece activa solo si funciona la ruta, la categoría sigue siendo correcta y los riesgos están visibles. Retira enlaces muertos en lugar de usar el volumen total como señal de calidad.",
      "Cierra el ciclo tras la entrega. Compara peso previsto y real, medidas del paquete, línea, cargo, tránsito y estado. Si hay una diferencia amplia, atribúyela a una entrada modificada: peso, volumen, embalaje, servicio o fecha de precio. Esa explicación mejora la próxima estimación por categoría más que un total aislado. Guarda juntos la fila original, la decisión QC y la composición del paquete. El recorrido podrá reconstruirse aunque el vendedor cambie o elimine la página.",
      "Aplica exclusiones antes de comparar estética: elimina rutas fuera de categoría, presupuesto, talla o especificación esencial. Así una imagen atractiva no empuja a justificar un producto que ya incumple el encargo. En una hoja compartida, las notas deben ser comprensibles sin códigos privados. El ID sirve como clave estable y una descripción breve explica la variante de un vistazo. La transparencia de esos campos importa más que un gran recuento de filas." ],
    "oopbuy-qc-photo-checklist": [
      "La calidad de imagen forma parte del análisis. Un gran angular puede exagerar proporciones, el balance automático desplaza colores y la compresión oculta textura o marcas finas. Si un posible defecto aparece en un solo fotograma, compáralo con otros ángulos antes de confirmarlo. En una medición hay que distinguir longitud de plantilla, suela exterior y espacio interior útil; no son equivalentes. Lo mismo ocurre con ancho, largo y hombros de una prenda: los puntos inicial y final deben coincidir con el método del vendedor guardado en la referencia.",
      "El estado final debe ser breve pero completo: aceptado, falta una vista concreta, se intentó posventa o quedó fuera del paquete. Añade fecha, razón objetiva e imagen decisiva. Conserva referencia, galería y resultado juntos. Un artículo correcto anterior no garantiza otro lote; pueden cambiar ID, opción, vendedor, fabricación y fotografía. Los registros antiguos ayudan a formular mejores preguntas, pero nunca sustituyen la revisión del ejemplar que está ahora en el almacén.",
      "En prendas, compara impresión con costuras, cuello y bajo, porque la escala puede variar por talla sin estar descentrada. En herrajes, busca una marca desde varios ángulos para separar reflejo, película protectora y arañazo. En calzado, no confundas una diferencia creada por perspectiva con una asimetría constante. Estas comprobaciones específicas convierten la lista en una lectura de evidencia y evitan una conclusión general basada en una sola imagen comprimida." ],
    "oopbuy-fees-returns-policy": [
      "Antes de pagar, crea un expediente y evita una afirmación general sobre comisiones. Guarda por separado precio, transporte nacional chino, conceptos de pago o plataforma visibles, servicios opcionales, embalaje, envío internacional y posibles cargos de destino con fecha y moneda. Si los textos oficiales mantienen formulaciones diferentes, muestra ambos sin inventar una reconciliación. Para esa transacción concreta, el desglose actual y una respuesta escrita con la referencia del pedido pesan más que una frase promocional antigua o un resumen sin fecha.",
      "Los plazos requieren dos calendarios. La ventana publicada de devolución o cambio sirve para decidir tras el QC; el almacenamiento más largo solo ayuda a consolidar y preparar el paquete. Presentar la solicitud a tiempo no significa aprobación automática: normas del vendedor, estado, responsabilidad, retorno y condiciones vigentes influyen. Documenta hora de entrada, diferencia visible, opción, fotos y canal usado. Vuelve a leer la fuente oficial antes de actuar, porque un número confirmado el 1 de septiembre de 2026 no es una garantía permanente.",
      "Mantén tres escenarios de coste —compacto, esperado y voluminoso— con las mismas hipótesis al comparar servicios. Sustituye estimaciones por medidas cuando aparezcan y no apliques una fórmula universal. Las reseñas públicas pueden sugerir qué preguntas investigar sobre costes, QC o soporte, pero no sustituyen una política ni una muestra controlada. Una comparación justa usa el mismo carrito, destino, fecha de moneda y supuesto de embalaje, y declara qué conceptos siguen desconocidos." ],
    "oopbuy-shipping-cost-planner": [
      "Planifica el volumen según la forma, no sumando dimensiones sin criterio. La ropa blanda puede llenar huecos alrededor de un objeto rígido; dos cajas duras quizá no encajen. Mantén constantes las mismas hipótesis plausibles al comparar rutas. Solo así se verá si la diferencia procede del cálculo, límites de tamaño, seguimiento incluido o nivel de servicio. Aplica la regla actual de cada línea y no un divisor universal. Las medidas finales de almacén y embalaje sustituirán después la estimación inicial.",
      "Tras la entrega registra cargo, tránsito, calidad del seguimiento, estado y decisiones especiales como división, vacío, retirada de caja o protección. Compara con el escenario esperado y señala el mayor error. Varios paquetes comparables permiten usar rango y mediana; un único mejor caso no es norma. Mantén fecha y moneda con los totales históricos para separar un cambio de tarifa de una mejora en la estimación del embalaje.",
      "Vincula cada protección con un riesgo visible. Un protector de esquina puede servir a una estructura rígida; una barrera de humedad, a textiles; conservar una caja puede proteger forma y añadir volumen. Decide qué daño intentas evitar y registra el efecto probable sobre peso y medidas. Si un artículo restringido elimina líneas preferidas, modela el paquete completo y una división bajo los mismos supuestos antes del pago, sin asumir que una opción será siempre elegible." ],
  },
  fr: {
    "oopbuy-beginner-guide-2026": [
      "Terminez par un audit complet des passages. L’identifiant produit et l’option enregistrés doivent rester liés à l’article en stock, à la liste finale du colis et au bordereau. Ne conservez pas seulement le total : indiquez les valeurs encore estimées, comme poids vendeur, volume probable, change ou tarif. Après livraison, remplacez-les par les données observées. Une commande devient alors un dossier daté sans transformer un envoi rapide ou lent en conclusion générale sur OOPBUY, un vendeur ou une route.",
      "Les limites de preuve restent essentielles. La fiche active prouve l’offre actuelle, pas l’article futur. La commande prouve l’option choisie, pas la taille réelle. Les photos montrent des éléments visibles, pas authenticité, fibres, fonction interne ou durée. Un événement de suivi prouve un scan, pas la cause de chaque retard. En documentant ces limites avec date, référence et source, vous décrivez les problèmes précisément, utilisez le processus à temps et fondez la décision suivante sur des preuves plus solides que la mémoire.",
      "Utilisez une matrice simple : annonce et option avant achat ; référence et montant après paiement ; statut, images et délai à l’entrée ; contenu, mesures et protection au colis ; suivi et état à la réception. Si un lien manque, notez la lacune au lieu de la reconstruire par supposition. Cette matrice sépare aussi les faits variables à revérifier dans l’écran actuel des principes de preuve qui restent utiles d’une commande à l’autre." ],
    "oopbuy-spreadsheet-workflow": [
      "Vérifiez aussi la maintenabilité du tableau. Une autre personne doit comprendre quelle option est visée, ce qui a été confirmé et quelle question reste ouverte. Évitez les abréviations privées sans légende. Gardez devise d’origine et date près de la conversion USD afin de ne pas confondre change et variation du prix. Une ligne reste active seulement si la route fonctionne, la catégorie correspond et les risques sont visibles. Retirez les liens morts au lieu de présenter la quantité comme un signe de qualité.",
      "Fermez la boucle après livraison. Comparez poids prévu et réel, dimensions, route, montant, durée et état. Si l’écart est important, rattachez-le à une entrée modifiée : poids, volume, emballage, service ou date tarifaire. Cette explication améliore la prochaine estimation par catégorie davantage qu’un total isolé. Conservez ensemble la ligne initiale, la décision QC et la composition du colis. Le parcours reste reconstruisible même si le vendeur modifie ou supprime sa page.",
      "Appliquez d’abord des exclusions : retirez les routes hors catégorie, budget, taille ou spécification essentielle avant de comparer l’esthétique. Une belle image ne pousse alors pas à justifier un produit qui échoue déjà au besoin. Dans un tableau partagé, les notes doivent se comprendre sans code privé. L’identifiant reste la clé stable et une courte description explique l’option. La clarté de ces champs vaut davantage qu’un nombre spectaculaire de lignes." ],
    "oopbuy-qc-photo-checklist": [
      "La qualité de l’image fait partie du contrôle. Un grand-angle exagère les proportions, la balance automatique déplace les couleurs et la compression masque texture ou petites marques. Si un défaut possible n’apparaît que sur une vue, comparez les autres avant de le confirmer. Pour une mesure, distinguez semelle intérieure, semelle extérieure et longueur intérieure utile ; elles ne sont pas interchangeables. Pour un vêtement, largeur, longueur et épaules doivent utiliser les mêmes points de départ et d’arrivée que la méthode vendeur enregistrée.",
      "Le statut final reste bref mais complet : accepté, vue ciblée nécessaire, après-vente tentée ou exclu du colis. Ajoutez date, raison objective et image décisive. Conservez référence, galerie et résultat. Un article antérieur réussi ne garantit pas un nouveau lot ; identifiants, options, vendeur, fabrication et photos évoluent. Les anciens dossiers aident à poser de meilleures questions, mais ne remplacent jamais l’examen de l’unité actuellement stockée.",
      "Pour les vêtements, alignez l’impression avec coutures, col et ourlet, car son échelle peut varier selon la taille sans être décentrée. Pour les pièces métalliques, cherchez une marque sous plusieurs angles afin de distinguer reflet, film protecteur et rayure. Pour les chaussures, séparez l’effet de perspective d’une asymétrie constante. Ces contrôles ciblés empêchent une conclusion générale fondée sur une seule image compressée." ],
    "oopbuy-fees-returns-policy": [
      "Avant paiement, créez un dossier plutôt qu’une déclaration générale sur les frais. Séparez prix produit, transport national chinois, postes de paiement ou plateforme visibles, services optionnels, emballage, international et éventuels frais de destination avec date et devise. Si les textes officiels restent différents, présentez les deux sans inventer de conciliation. Pour la transaction, le détail actuel et une réponse écrite liée à la commande sont plus forts qu’une ancienne phrase promotionnelle ou un résumé non daté.",
      "Les délais exigent deux calendriers. La fenêtre publiée de retour ou échange sert à la décision QC ; le stockage plus long sert seulement à consolider et préparer. Une demande à temps n’est pas une approbation automatique : règles vendeur, état, responsabilité, transport retour et conditions actuelles comptent. Documentez heure d’entrée, écart visible, option, photos et canal. Relisez la source officielle avant d’agir, car un nombre confirmé le 1er septembre 2026 n’est pas une garantie permanente.",
      "Conservez trois scénarios —compact, attendu et volumineux— avec les mêmes hypothèses lorsque vous comparez les services. Remplacez les estimations par les mesures disponibles et n’utilisez aucune formule universelle. Les avis publics peuvent suggérer des questions sur coût, QC ou support, mais ne remplacent ni politique ni échantillon contrôlé. Une comparaison juste garde panier, destination, date de change et hypothèse d’emballage identiques et signale les postes encore inconnus." ],
    "oopbuy-shipping-cost-planner": [
      "Planifiez le volume selon la forme plutôt qu’en additionnant mécaniquement les dimensions. Des vêtements souples remplissent les espaces autour d’un objet rigide ; deux boîtes dures peuvent ne pas s’emboîter. Gardez les mêmes hypothèses de colis pour comparer les routes. La différence révèle alors calcul, limite de taille, suivi inclus ou service. Appliquez la règle actuelle de chaque ligne, jamais un diviseur universel. Les mesures finales remplacent ensuite l’estimation initiale.",
      "Après livraison, notez montant, durée, qualité du suivi, état et choix spéciaux : division, vide, retrait de boîte ou protection. Comparez au scénario attendu et identifiez la plus grande erreur. Plusieurs colis comparables permettent une fourchette et une médiane ; un seul meilleur cas ne devient pas la norme. Gardez date et devise auprès des historiques pour distinguer changement de tarif et meilleure estimation d’emballage.",
      "Reliez chaque protection à un risque visible. Un renfort d’angle peut convenir à une structure rigide, une barrière d’humidité à un textile ; conserver une boîte protège parfois la forme tout en ajoutant du volume. Identifiez le dommage visé et notez l’effet probable sur poids et dimensions. Si un article restreint élimine des lignes, modélisez colis complet et séparation avec les mêmes hypothèses avant paiement, sans supposer qu’une option restera disponible." ],
  },
  it: {
    "oopbuy-beginner-guide-2026": [
      "Concludi con un controllo completo dei passaggi. ID e variante salvati devono restare collegati all’articolo in magazzino, alla lista finale del pacco e alla lettera di vettura. Non registrare solo il totale: indica quali valori erano stime, come peso del venditore, volume probabile, cambio o tariffa. Dopo la consegna sostituisci le ipotesi con i dati osservati. Un ordine diventa così un registro datato senza trasformare una spedizione veloce o lenta in un’affermazione generale su OOPBUY, venditore o rotta.",
      "I limiti della prova restano essenziali. La pagina attiva dimostra l’offerta corrente, non l’articolo futuro. L’ordine dimostra l’opzione, non la vestibilità. Le foto mostrano caratteristiche visibili, non autenticità, fibre, funzione interna o durata. Un evento di tracking dimostra una scansione, non la causa di ogni ritardo. Documentando limiti, data, riferimento e fonte puoi descrivere problemi concreti, usare in tempo il processo corrente e basare la decisione successiva su evidenze più forti della memoria.",
      "Usa una matrice semplice: annuncio e opzione prima dell’acquisto; riferimento e importo dopo il pagamento; stato, immagini e scadenza all’ingresso; contenuto, misure e protezione al pacco; tracking e condizione alla consegna. Se manca un collegamento, segnalo come lacuna invece di ricostruirlo con un’ipotesi. La matrice distingue anche i fatti variabili da verificare nello schermo corrente dai principi probatori utili tra un ordine e l’altro." ],
    "oopbuy-spreadsheet-workflow": [
      "Controlla anche la manutenzione del foglio. Un’altra persona deve capire quale opzione è stata scelta, cosa è confermato e quale domanda resta aperta. Evita abbreviazioni private senza legenda. Conserva valuta originale e data accanto alla conversione USD per non confondere cambio e prezzo. Una riga resta attiva solo se il percorso funziona, la categoria è corretta e i rischi sono visibili. Rimuovi collegamenti morti invece di trattare il numero complessivo come indice di qualità.",
      "Chiudi il ciclo dopo la consegna. Confronta peso previsto e reale, dimensioni, rotta, addebito, transito e stato. Se la differenza è ampia, collegala a un input cambiato: peso, volume, imballaggio, servizio o data del prezzo. Questa spiegazione migliora la prossima stima per categoria più di un totale isolato. Conserva insieme riga originale, decisione QC e composizione del pacco. Il percorso resta ricostruibile anche se il venditore modifica o elimina la pagina.",
      "Applica prima regole di esclusione: elimina percorsi fuori categoria, budget, taglia o specifica essenziale prima di confrontare l’estetica. Una bella immagine non spinge così a giustificare un prodotto già inadatto. In un foglio condiviso le note devono essere comprensibili senza codici privati. L’ID è la chiave stabile e una descrizione breve chiarisce l’opzione. La trasparenza di questi campi conta più di un grande numero di righe." ],
    "oopbuy-qc-photo-checklist": [
      "La qualità dell’immagine fa parte del controllo. Un grandangolo esagera le proporzioni, il bilanciamento automatico cambia i colori e la compressione nasconde texture o piccoli segni. Se un possibile difetto compare in una sola foto, confronta altri angoli prima di confermarlo. Nelle misure distingui soletta, suola esterna e lunghezza interna utile; non sono equivalenti. Per un capo, larghezza, lunghezza e spalle devono usare gli stessi punti del metodo del venditore salvato.",
      "Lo stato finale deve essere breve ma completo: accettato, vista mirata necessaria, post-vendita tentato o escluso dal pacco. Aggiungi data, ragione oggettiva e immagine decisiva. Conserva riferimento, galleria e risultato. Un articolo precedente riuscito non garantisce un nuovo lotto; possono cambiare ID, opzione, venditore, produzione e foto. I vecchi registri aiutano a porre domande migliori, ma non sostituiscono mai il controllo dell’unità attualmente in magazzino.",
      "Per i capi confronta la grafica con cuciture, collo e orlo: la scala può cambiare tra taglie senza essere fuori centro. Per l’hardware osserva un segno da più angoli per distinguere riflesso, pellicola e graffio. Nelle scarpe separa l’effetto della prospettiva da un’asimmetria costante. Questi controlli specifici evitano una conclusione generale basata su una sola immagine compressa." ],
    "oopbuy-fees-returns-policy": [
      "Prima di pagare crea un fascicolo, non un’affermazione generale sulle commissioni. Separa prezzo, trasporto nazionale cinese, voci di pagamento o piattaforma visibili, servizi opzionali, imballaggio, spedizione internazionale e possibili oneri di destinazione con data e valuta. Se i testi ufficiali restano differenti, mostrali entrambi senza inventare una conciliazione. Per quella transazione, il dettaglio corrente e una risposta scritta legata all’ordine valgono più di una vecchia frase promozionale o di un riepilogo senza data.",
      "Le scadenze richiedono due calendari. La finestra pubblicata di reso o cambio serve alla decisione QC; lo stoccaggio più lungo serve solo a consolidare e preparare. Una richiesta tempestiva non è approvazione automatica: regole del venditore, stato, responsabilità, trasporto di ritorno e condizioni attuali incidono. Documenta ora d’ingresso, differenza visibile, opzione, foto e canale. Rileggi la fonte ufficiale prima di agire, perché un numero confermato il 1° settembre 2026 non è garanzia permanente.",
      "Mantieni tre scenari —compatto, atteso e ingombrante— con le stesse ipotesi quando confronti i servizi. Sostituisci le stime con le misure disponibili e non applicare formule universali. Le recensioni pubbliche possono suggerire domande su costi, QC o supporto, ma non sostituiscono politica o campione controllato. Un confronto corretto usa lo stesso carrello, destinazione, data di cambio e ipotesi d’imballaggio e segnala le voci ancora ignote." ],
    "oopbuy-shipping-cost-planner": [
      "Pianifica il volume in base alla forma, non sommando meccanicamente le dimensioni. I tessuti morbidi possono riempire spazi intorno a un oggetto rigido; due scatole dure potrebbero non incastrarsi. Mantieni le stesse ipotesi plausibili per confrontare le rotte. Solo così la differenza rivela calcolo, limite di misura, tracking incluso o servizio. Applica la regola corrente di ogni linea, mai un divisore universale. Le misure finali sostituiranno poi la stima iniziale.",
      "Dopo la consegna registra addebito, transito, qualità del tracking, stato e scelte speciali come divisione, sottovuoto, rimozione scatola o protezione. Confronta con lo scenario atteso e indica l’errore maggiore. Più pacchi comparabili consentono intervallo e mediana; un singolo caso migliore non è la norma. Conserva data e valuta con i totali storici per distinguere una tariffa cambiata da una stima d’imballaggio migliorata.",
      "Collega ogni protezione a un rischio visibile. Un rinforzo d’angolo può servire a una struttura rigida, una barriera d’umidità ai tessuti; conservare una scatola può proteggere la forma e aggiungere volume. Identifica il danno da evitare e annota l’effetto probabile su peso e dimensioni. Se un articolo limitato elimina rotte preferite, modella pacco completo e divisione con le stesse ipotesi prima del pagamento, senza presumere idoneità permanente." ],
  },
};
