export type QvlArticle = {
  slug: string;
  title: string;
  deck: string;
  readTime: string;
  published: string;
  sourceNote: string;
  related: { label: string; kind: "qc" | "article"; slug?: string }[];
  sections: { heading: string; paragraphs: string[] }[];
};

const slug = "oopbuy-qc-photos-visual-evidence-guide";

export const qvlC01Articles: Record<"en" | "de" | "es" | "fr" | "it", QvlArticle> = {
  en: {
    slug,
    title: "What OOPBuy QC Photos Can and Cannot Prove: A Visual Evidence Guide",
    deck: "A disciplined method for separating visible warehouse evidence from assumptions about material, fit, function, authenticity and future performance.",
    readTime: "12 min read",
    published: "2026-09-03",
    sourceNote: "Process boundaries checked against current OOPBuy inspection, beginner and returns information on 3 September 2026.",
    related: [
      { label: "Use the OOPBuy warehouse-photo QC method", kind: "qc" },
      { label: "Open the existing OOPBuy QC photo checklist", kind: "article", slug: "oopbuy-qc-photo-checklist" }
    ],
    sections: [
      { heading: "Start with the claim, not the photograph", paragraphs: [
        "A warehouse photograph is useful only when the question is precise. Before opening the gallery, write the claim you need to test: the received item appears to be the selected color, the size label is present, two pieces are visible, or a surface mark appears near a seam. This prevents a general feeling about quality from replacing an observable test. OOPBuy’s current inspection information describes checks of quantity, color, size, specifications and visible appearance damage. Those categories define a practical starting point, not a promise that every hidden or technical property has been tested.",
        "Use three labels for every conclusion: visible, uncertain or not testable from the supplied images. Visible means the feature can be located consistently in one or more frames. Uncertain means lighting, angle, compression, obstruction or missing scale prevents a firm reading. Not testable covers claims such as fiber composition, internal electronics, waterproof performance, smell, long-term durability or authenticity when no appropriate evidence is shown. This vocabulary makes a QC decision defensible and stops a photograph from carrying more meaning than it contains."
      ]},
      { heading: "Rebuild the reference before comparing", paragraphs: [
        "The warehouse gallery does not identify the intended product by itself. Reopen the saved destination listing or order record and recover the exact option text, quantity, size, color, model and included-parts description selected at purchase. Treat the order identifier and seller option as the reference layer; treat the QC gallery as the received-item layer. If the listing has changed, preserve the dated record you actually used rather than silently comparing the warehouse item with a newer image or a similar product from another seller.",
        "Create a compact comparison sheet with four columns: expected feature, visible evidence, confidence and action. A row might say ‘navy option selected,’ ‘dark blue fabric appears in three frames,’ ‘medium confidence because lighting is warm,’ and ‘request neutral-light view if exact shade matters.’ Another row might record ‘size 42 selected,’ ‘label shows 42 clearly,’ ‘high confidence,’ and ‘no follow-up.’ This structure separates identity checks from aesthetic judgment and reveals exactly which missing view would change the decision."
      ]},
      { heading: "Read angle, light and compression as evidence limits", paragraphs: [
        "Camera position changes apparent proportion. Objects near a wide-angle frame edge may look stretched, a tilted shoe can appear longer on one side, and a garment photographed with folds can look asymmetrical. Compare stable landmarks across several images: seams, panel intersections, eyelets, edges or hardware positions. A concern that disappears when the angle changes is weaker evidence than a feature that stays in the same physical location. Never infer a measurement from perspective alone unless a ruler and clear endpoints are visible in the same plane.",
        "Color is equally conditional. Automatic white balance, mixed warehouse lighting, exposure and reflective materials can shift hue or brightness. Compare neutral objects in the frame and check whether the same shift affects the whole image. Compression can erase fine weave, shallow embossing or tiny surface marks, while sharpening can exaggerate edges. A photo may prove that a red-family item arrived; it may not prove an exact shade match. When exact color controls acceptance, ask for a targeted neutral-light comparison rather than declaring an error from one frame."
      ]},
      { heading: "Separate visible construction from material claims", paragraphs: [
        "QC images can support observations about construction that is actually shown: a seam is open, a panel is visibly misaligned, a print crosses a fold, a zipper pull is present, or a sole edge has a mark. They can also show texture at the photographed surface when resolution is sufficient. Record the location and image number so another person can find the same feature. Prefer language such as ‘a loose thread is visible at the left cuff’ over ‘the item is badly made,’ which converts one observation into an unsupported judgment about the whole product.",
        "Ordinary photographs cannot establish fiber percentages, leather type, fill weight, chemical treatment, tensile strength or long-term wear. A visible label may document what the label states, but it does not independently verify the material. Gloss and texture can also come from lighting or protective film. If a material property is essential, identify the evidence that would actually address it, such as a readable label, seller specification, measurement or functional test that the current service explicitly supports. Otherwise keep the field marked unknown rather than filling it with expectation."
      ]},
      { heading: "Use category-specific visual tests", paragraphs: [
        "For clothing, check the front and back identity, size label, graphic placement relative to collar and seams, obvious stains, open stitching and any provided measurements. For shoes, compare the pair, labels, panel layout, sole shape, eyelet count, symmetry and visible surface condition. Perspective often makes the nearer shoe look larger, so use repeated landmarks rather than a single diagonal shot. For bags and accessories, count detachable pieces, inspect closures, straps, handles and hardware, and distinguish a removable protective film from the finished surface before calling it damage.",
        "For multi-piece products, quantity must be proved by a frame that shows all expected parts or by separate images that can be matched without duplication. A box in the background does not prove its contents. Likewise, a closed pocket does not prove that an accessory is inside. Build the check around the seller’s included-parts description and mark every unseen component as unverified. This is especially important when one listing contains several configurations; the correct main item can arrive with the wrong accessory set."
      ]},
      { heading: "Ask for one targeted view at a time", paragraphs: [
        "A useful follow-up request names the object, view and decision. ‘Show the rear print straight-on so its alignment with the center seam can be checked’ is actionable. ‘Take more photos’ is not. If measurement matters, name both endpoints and ask that the ruler remain visible along the same plane. If a mark may be reflection, request the same location from another angle. If color is uncertain, request a neutral-light overview with a stable reference. The request should test a defined uncertainty rather than invite an open-ended second inspection.",
        "Prioritize requests by decision value. First address identity, selected option, quantity and serious visible damage. Next address fit-related measurements or components that determine usability. Cosmetic details come last. Do not request a photograph merely because it is available; request it because the result could change acceptance, after-sales action or packing. Keep the original gallery, request text, new image and decision together. That sequence proves what was known at each step without inventing a private conversation or a guaranteed outcome."
      ]},
      { heading: "Act within the current order window", paragraphs: [
        "Visual analysis matters only while the order remains actionable. OOPBuy’s current return information describes a five-day, 120-hour window after the item reaches the stored status, counted from the next full hour. Confirm the live order timestamp and current policy before relying on that number because rules can change. Review photos when they appear rather than waiting for every future item. A longer warehouse storage period does not automatically extend the shorter after-sales decision window.",
        "If the evidence shows a wrong option, missing quantity or visible damage, use the current order after-sales route and describe the mismatch objectively. A timely request is not automatic approval: seller rules, product eligibility, condition, responsibility and current process can affect the result. Preserve the selected option, stored timestamp, relevant images and submitted explanation. Do not publish private order numbers, addresses, payment records or support identities. The goal is a complete private case file, not a public accusation."
      ]},
      { heading: "Close with a calibrated decision record", paragraphs: [
        "Finish each item with one of four outcomes: accept on visible evidence, request a targeted view, open after-sales, or exclude from the planned parcel while the issue remains unresolved. Add the date, decisive image, verified facts and remaining unknowns. A useful conclusion might state that color family, label and quantity match, exact material is unverified, and no visible damage appears in the supplied angles. That sentence is more informative than a quality score because it preserves both evidence and limits.",
        "Past QC records can improve future questions, but they do not prove that a later seller batch or similar-looking listing is identical. Match product identifier, option, seller context and visible construction before reusing a conclusion. After delivery, compare the received condition with the accepted warehouse views when possible and record any new difference without guessing where it occurred. Over time this creates a disciplined visual archive: specific enough to guide decisions, restrained enough to avoid false certainty, and distinct from cost, product-discovery and order-status advice on the other OOPBuy resources."
      ]}
    ]
  },
  de: {
    slug,
    title: "Was OOPBuy-QC-Fotos beweisen können – und was nicht: Leitfaden für visuelle Belege",
    deck: "Eine disziplinierte Methode, die sichtbare Lagerbelege von Annahmen über Material, Passform, Funktion, Echtheit und spätere Leistung trennt.",
    readTime: "12 Min.",
    published: "2026-09-03",
    sourceNote: "Prozessgrenzen am 3. September 2026 mit aktuellen OOPBuy-Informationen zu Inspektion, Einstieg und Rückgabe geprüft.",
    related: [
      { label: "Die OOPBuy-Methode für Lagerfotos verwenden", kind: "qc" },
      { label: "Die bestehende OOPBuy-QC-Fotocheckliste öffnen", kind: "article", slug: "oopbuy-qc-photo-checklist" }
    ],
    sections: [
      { heading: "Mit der Behauptung beginnen, nicht mit dem Foto", paragraphs: [
        "Ein Lagerfoto ist nur dann nützlich, wenn die Frage präzise ist. Formuliere vor dem Öffnen der Galerie die zu prüfende Aussage: Der erhaltene Artikel scheint die gewählte Farbe zu haben, das Größenetikett ist vorhanden, zwei Teile sind sichtbar oder nahe einer Naht erscheint eine Oberflächenmarke. So ersetzt ein allgemeines Qualitätsgefühl keinen beobachtbaren Test. Die aktuellen OOPBuy-Inspektionsinformationen nennen Menge, Farbe, Größe, Spezifikationen und sichtbare äußere Schäden als Prüfbereiche. Sie sind ein praktischer Ausgangspunkt, aber kein Versprechen, dass jede verborgene oder technische Eigenschaft getestet wurde.",
        "Kennzeichne jedes Ergebnis als sichtbar, unsicher oder mit den Bildern nicht prüfbar. Sichtbar bedeutet, dass das Merkmal in einem oder mehreren Bildern eindeutig auffindbar ist. Unsicher gilt bei störendem Licht, Winkel, Kompression, Verdeckung oder fehlendem Maßstab. Nicht prüfbar sind etwa Faserzusammensetzung, interne Elektronik, Wasserdichtigkeit, Geruch, Langzeithaltbarkeit oder Echtheit ohne passende Belege. Diese Begriffe machen die Entscheidung nachvollziehbar und verhindern, dass ein Foto mehr Bedeutung tragen muss, als tatsächlich enthalten ist."
      ]},
      { heading: "Vor dem Vergleich die Referenz rekonstruieren", paragraphs: [
        "Die Lagergalerie identifiziert das beabsichtigte Produkt nicht allein. Öffne den gespeicherten Zielartikel oder Bestelldatensatz und hole den exakten Optionstext, Menge, Größe, Farbe, Modell und die Beschreibung der enthaltenen Teile zurück. Bestellkennung und Verkäuferoption bilden die Referenzebene; die QC-Galerie bildet die Ebene des eingegangenen Artikels. Wurde die Angebotsseite geändert, bewahre den datierten Datensatz auf, den du tatsächlich verwendet hast, statt unbemerkt mit einem neueren Bild oder einem ähnlichen Produkt eines anderen Verkäufers zu vergleichen.",
        "Erstelle eine kompakte Tabelle mit vier Spalten: erwartetes Merkmal, sichtbarer Beleg, Sicherheit und Handlung. Eine Zeile kann lauten: Marineblau gewählt; dunkelblauer Stoff in drei Bildern; mittlere Sicherheit wegen warmem Licht; neutrale Beleuchtung anfordern, falls der genaue Ton wichtig ist. Eine andere Zeile hält Größe 42, klar sichtbares Etikett 42, hohe Sicherheit und keine Nachfrage fest. Diese Struktur trennt Identitätsprüfung von ästhetischem Urteil und zeigt genau, welche fehlende Ansicht die Entscheidung verändern würde."
      ]},
      { heading: "Winkel, Licht und Kompression als Beleggrenzen lesen", paragraphs: [
        "Die Kameraposition verändert scheinbare Proportionen. Objekte am Rand eines Weitwinkelbildes können gestreckt wirken, ein geneigter Schuh auf einer Seite länger und ein gefaltetes Kleidungsstück asymmetrisch. Vergleiche stabile Bezugspunkte über mehrere Bilder: Nähte, Paneelübergänge, Ösen, Kanten oder Beschlagpositionen. Ein Problem, das bei verändertem Winkel verschwindet, ist schwächer belegt als ein Merkmal am selben physischen Ort. Leite niemals allein aus Perspektive eine Messung ab, sofern Lineal und klare Endpunkte nicht in derselben Ebene sichtbar sind.",
        "Auch Farbe ist abhängig von Bedingungen. Automatischer Weißabgleich, gemischtes Lagerlicht, Belichtung und reflektierende Materialien können Farbton und Helligkeit verschieben. Vergleiche neutrale Objekte im Bild und prüfe, ob dieselbe Verschiebung das gesamte Foto betrifft. Kompression kann feine Webung, flache Prägung oder kleine Spuren löschen, während Schärfung Kanten übertreibt. Ein Foto kann eine rote Farbfamilie belegen, aber nicht unbedingt den exakten Ton. Wenn die genaue Farbe entscheidend ist, fordere einen gezielten Vergleich unter neutralem Licht an."
      ]},
      { heading: "Sichtbare Konstruktion von Materialbehauptungen trennen", paragraphs: [
        "QC-Bilder können Beobachtungen über tatsächlich gezeigte Konstruktion stützen: Eine Naht ist offen, ein Paneel sichtbar versetzt, ein Druck läuft über eine Falte, ein Reißverschlussgriff ist vorhanden oder eine Sohlenkante zeigt eine Spur. Bei ausreichender Auflösung können sie auch Oberflächentextur zeigen. Notiere Ort und Bildnummer, damit eine andere Person dasselbe Merkmal findet. Formulierungen wie „ein loser Faden ist an der linken Manschette sichtbar“ sind besser als „schlecht verarbeitet“, denn Letzteres macht aus einer Beobachtung ein unbelegtes Urteil über den gesamten Artikel.",
        "Normale Fotos belegen keine Faseranteile, Lederart, Füllgewicht, chemische Behandlung, Reißfestigkeit oder langfristigen Verschleiß. Ein sichtbares Etikett dokumentiert dessen Aussage, überprüft das Material aber nicht unabhängig. Glanz und Struktur können zudem durch Licht oder Schutzfolie entstehen. Ist eine Materialeigenschaft wesentlich, bestimme den passenden Beleg, etwa ein lesbares Etikett, eine Verkäuferspezifikation, eine Messung oder einen ausdrücklich unterstützten Funktionstest. Fehlt dieser, bleibt das Feld unbekannt, statt es mit Erwartung zu füllen."
      ]},
      { heading: "Kategorienspezifische Sichtprüfungen verwenden", paragraphs: [
        "Bei Kleidung prüfst du Vorder- und Rückseite, Größenetikett, Druckposition zu Kragen und Nähten, deutliche Flecken, offene Nähte und bereitgestellte Maße. Bei Schuhen vergleichst du Paar, Etiketten, Paneele, Sohlenform, Ösenanzahl, Symmetrie und sichtbaren Zustand. Perspektive lässt den näheren Schuh oft größer wirken; nutze wiederkehrende Bezugspunkte statt eines einzelnen Diagonalbildes. Bei Taschen und Zubehör zählst du abnehmbare Teile, prüfst Verschlüsse, Riemen, Griffe und Beschläge und unterscheidest Schutzfolie von der fertigen Oberfläche, bevor du Schaden meldest.",
        "Bei mehrteiligen Produkten muss die Menge durch ein Bild aller erwarteten Teile oder eindeutig zuordenbare Einzelbilder belegt sein. Eine Schachtel im Hintergrund beweist ihren Inhalt nicht, eine geschlossene Tasche kein darin liegendes Zubehör. Richte die Prüfung an der Teilebeschreibung des Verkäufers aus und markiere jede ungesehene Komponente als ungeprüft. Das ist besonders wichtig, wenn ein Angebot mehrere Konfigurationen enthält: Der richtige Hauptartikel kann zusammen mit dem falschen Zubehörsatz ankommen."
      ]},
      { heading: "Jeweils eine gezielte Ansicht anfordern", paragraphs: [
        "Eine brauchbare Nachfrage nennt Objekt, Ansicht und Entscheidung. „Zeige den Rückendruck gerade, damit seine Ausrichtung zur Mittelnaht geprüft werden kann“ ist umsetzbar; „mehr Fotos“ nicht. Für Maße müssen beide Endpunkte benannt sein und das Lineal in derselben Ebene sichtbar bleiben. Könnte eine Spur eine Reflexion sein, bitte um denselben Ort aus anderem Winkel. Bei unsicherer Farbe hilft eine neutrale Gesamtansicht mit stabilem Bezug. Die Anfrage soll eine definierte Unsicherheit testen, nicht eine offene zweite Inspektion auslösen.",
        "Priorisiere nach Entscheidungswert. Zuerst kommen Identität, gewählte Option, Menge und ernste sichtbare Schäden. Danach folgen passformrelevante Maße oder Komponenten, die die Nutzung bestimmen; kosmetische Details zuletzt. Fordere kein Bild nur deshalb an, weil es möglich ist, sondern weil das Ergebnis Annahme, Aftersales oder Verpackung ändern kann. Bewahre ursprüngliche Galerie, Anfragetext, neues Bild und Entscheidung zusammen auf. Diese Folge zeigt den jeweiligen Wissensstand, ohne ein privates Gespräch oder garantiertes Ergebnis zu erfinden."
      ]},
      { heading: "Innerhalb des aktuellen Bestellfensters handeln", paragraphs: [
        "Visuelle Analyse hilft nur, solange die Bestellung bearbeitbar bleibt. Die aktuellen OOPBuy-Rückgabeinformationen beschreiben ein fünftägiges Fenster von 120 Stunden nach dem Status „Stored“, gezählt ab der nächsten vollen Stunde. Prüfe Live-Zeitstempel und aktuelle Regel, bevor du dich darauf verlässt, denn Vorgaben können sich ändern. Kontrolliere die Fotos bei Erscheinen und warte nicht auf alle späteren Artikel. Eine längere Lagerzeit verlängert nicht automatisch das kürzere Aftersales-Entscheidungsfenster.",
        "Zeigen die Belege falsche Option, fehlende Menge oder sichtbaren Schaden, nutze den aktuellen Aftersales-Weg der Bestellung und beschreibe die Abweichung objektiv. Eine rechtzeitige Anfrage bedeutet keine automatische Zustimmung; Verkäuferregeln, Produktberechtigung, Zustand, Verantwortung und aktueller Ablauf können das Ergebnis beeinflussen. Bewahre Option, Einlagerungszeit, relevante Bilder und eingereichte Erklärung auf. Veröffentliche keine Bestellnummern, Adressen, Zahlungsdaten oder Supportidentitäten. Ziel ist eine vollständige private Fallakte, keine öffentliche Anschuldigung."
      ]},
      { heading: "Mit einem abgestuften Entscheidungsprotokoll schließen", paragraphs: [
        "Beende jeden Artikel mit einem von vier Ergebnissen: nach sichtbaren Belegen akzeptieren, gezielte Ansicht anfordern, Aftersales öffnen oder bis zur Klärung vom geplanten Paket ausschließen. Ergänze Datum, entscheidendes Bild, bestätigte Fakten und offene Punkte. Eine gute Schlussfolgerung lautet etwa: Farbfamilie, Etikett und Menge stimmen; genaues Material bleibt ungeprüft; in den gelieferten Winkeln ist kein sichtbarer Schaden erkennbar. Das ist aussagekräftiger als eine Qualitätsnote, weil Beleg und Grenze erhalten bleiben.",
        "Frühere QC-Akten verbessern spätere Fragen, beweisen aber nicht, dass eine neue Verkäufercharge oder ein ähnlich aussehendes Angebot identisch ist. Gleiche Produktkennung, Option, Verkäuferkontext und sichtbare Konstruktion ab, bevor du eine Schlussfolgerung wiederverwendest. Vergleiche nach Lieferung den Zustand mit den akzeptierten Lagerbildern und notiere neue Unterschiede, ohne die Ursache zu erraten. So entsteht ein diszipliniertes visuelles Archiv: konkret genug für Entscheidungen, zurückhaltend gegenüber falscher Gewissheit und klar getrennt von Kosten-, Produktsuche- und Bestellstatus-Themen der anderen OOPBuy-Ressourcen."
      ]}
    ]
  },
  es: {
    slug,
    title: "Qué pueden demostrar las fotos QC de OOPBuy y qué no: guía de evidencia visual",
    deck: "Un método disciplinado para separar la evidencia visible del almacén de suposiciones sobre material, talla, función, autenticidad y rendimiento futuro.",
    readTime: "12 min",
    published: "2026-09-03",
    sourceNote: "Límites del proceso verificados el 3 de septiembre de 2026 con la información actual de inspección, inicio y devoluciones de OOPBuy.",
    related: [
      { label: "Usar el método QC de fotos de almacén OOPBuy", kind: "qc" },
      { label: "Abrir la lista existente de fotos QC OOPBuy", kind: "article", slug: "oopbuy-qc-photo-checklist" }
    ],
    sections: [
      { heading: "Empieza por la afirmación, no por la fotografía", paragraphs: [
        "Una fotografía de almacén solo es útil cuando la pregunta es precisa. Antes de abrir la galería, escribe la afirmación que debes comprobar: el artículo recibido parece del color seleccionado, la etiqueta de talla está presente, se ven dos piezas o aparece una marca cerca de una costura. Así evitas que una impresión general de calidad sustituya una prueba observable. La información actual de inspección de OOPBuy menciona cantidad, color, talla, especificaciones y daños visibles de apariencia. Son un punto de partida práctico, no una promesa de que se haya probado cada propiedad oculta o técnica.",
        "Etiqueta cada conclusión como visible, incierta o no comprobable con las imágenes. Visible significa que la característica puede localizarse de forma consistente en uno o más fotogramas. Incierta indica que luz, ángulo, compresión, obstrucción o falta de escala impiden una lectura firme. No comprobable incluye composición de fibras, electrónica interna, impermeabilidad, olor, durabilidad o autenticidad sin evidencia adecuada. Este vocabulario hace defendible la decisión y evita exigir a una foto más significado del que realmente contiene."
      ]},
      { heading: "Reconstruye la referencia antes de comparar", paragraphs: [
        "La galería del almacén no identifica por sí sola el producto previsto. Reabre el anuncio guardado o el registro del pedido y recupera el texto exacto de opción, cantidad, talla, color, modelo y piezas incluidas seleccionados. El identificador y la opción del vendedor forman la capa de referencia; la galería QC forma la capa del artículo recibido. Si el anuncio cambió, conserva el registro fechado que utilizaste en vez de comparar silenciosamente con una imagen nueva o con un producto parecido de otro vendedor.",
        "Crea una tabla de cuatro columnas: característica esperada, evidencia visible, confianza y acción. Una fila puede decir: azul marino elegido; tejido azul oscuro en tres fotos; confianza media por luz cálida; pedir una vista neutra si importa el tono exacto. Otra puede registrar talla 42, etiqueta 42 clara, confianza alta y sin seguimiento. Esta estructura separa la identidad del juicio estético y muestra exactamente qué vista ausente podría cambiar la decisión."
      ]},
      { heading: "Lee ángulo, luz y compresión como límites", paragraphs: [
        "La posición de la cámara altera las proporciones aparentes. Un objeto junto al borde de un gran angular puede verse estirado, un zapato inclinado parecer más largo en un lado y una prenda doblada parecer asimétrica. Compara referencias estables entre varias imágenes: costuras, uniones de paneles, ojales, bordes o herrajes. Una preocupación que desaparece al cambiar el ángulo es una evidencia más débil que una característica que permanece en el mismo punto físico. No deduzcas medidas por perspectiva salvo que regla y extremos claros estén visibles en el mismo plano.",
        "El color también depende de las condiciones. Balance de blancos automático, luces mezcladas, exposición y materiales reflectantes pueden desplazar tono y brillo. Compara objetos neutros y comprueba si el cambio afecta a toda la foto. La compresión puede borrar tejido fino, relieves bajos o marcas pequeñas, y el enfoque exagerar bordes. Una imagen puede demostrar que llegó un artículo de familia roja, pero no una coincidencia exacta de tono. Si el color exacto decide la aceptación, pide una comparación dirigida con luz neutra."
      ]},
      { heading: "Separa construcción visible de afirmaciones materiales", paragraphs: [
        "Las imágenes QC pueden respaldar observaciones sobre construcción realmente mostrada: una costura está abierta, un panel desalineado, un estampado cruza un pliegue, existe un tirador o aparece una marca en la suela. También pueden mostrar textura superficial si hay resolución suficiente. Anota lugar y número de imagen para que otra persona encuentre la misma característica. Es mejor decir «hay un hilo suelto en el puño izquierdo» que «está mal fabricado», porque lo segundo convierte una observación en un juicio sin respaldo sobre todo el producto.",
        "Las fotografías normales no establecen porcentajes de fibra, tipo de cuero, peso de relleno, tratamiento químico, resistencia o desgaste futuro. Una etiqueta visible documenta lo que declara, pero no verifica el material de forma independiente. Brillo y textura pueden deberse a iluminación o película protectora. Si una propiedad es esencial, identifica la prueba pertinente: etiqueta legible, especificación del vendedor, medida o ensayo funcional que el servicio actual admita expresamente. Si no existe, mantén el campo como desconocido en lugar de llenarlo con expectativas."
      ]},
      { heading: "Aplica pruebas visuales según la categoría", paragraphs: [
        "En ropa comprueba identidad frontal y trasera, etiqueta de talla, posición del gráfico respecto a cuello y costuras, manchas, puntos abiertos y medidas aportadas. En calzado compara el par, etiquetas, paneles, forma de la suela, número de ojales, simetría y estado visible. La perspectiva hace que el zapato cercano parezca mayor, así que usa referencias repetidas. En bolsas y accesorios cuenta piezas desmontables, cierres, correas, asas y herrajes, y distingue película protectora de superficie final antes de declarar daño.",
        "En productos con varias piezas, la cantidad exige una foto con todos los componentes esperados o imágenes separadas que puedan relacionarse sin duplicación. Una caja al fondo no prueba su contenido y un bolsillo cerrado no demuestra que el accesorio esté dentro. Basa el control en la descripción de piezas del vendedor y marca cada componente no visto como no verificado. Esto importa cuando un anuncio ofrece varias configuraciones: puede llegar el artículo principal correcto con el conjunto de accesorios equivocado."
      ]},
      { heading: "Solicita una vista dirigida cada vez", paragraphs: [
        "Una solicitud útil nombra objeto, vista y decisión. «Muestra el estampado trasero de frente para revisar su alineación con la costura central» es ejecutable; «haz más fotos» no. Si importa una medida, nombra ambos extremos y pide que la regla quede visible en el mismo plano. Si una marca puede ser reflejo, pide el mismo punto desde otro ángulo. Si el color es incierto, solicita una vista general con luz neutra y referencia estable. La petición debe probar una incertidumbre definida, no abrir una segunda inspección sin límite.",
        "Prioriza por valor para la decisión. Primero identidad, opción seleccionada, cantidad y daños visibles serios. Después medidas de ajuste o componentes que determinan el uso; los detalles cosméticos al final. No pidas una foto solo porque sea posible, sino porque el resultado cambiaría aceptación, posventa o embalaje. Guarda juntos galería original, texto de solicitud, nueva imagen y decisión. Esa secuencia prueba qué se sabía en cada paso sin inventar una conversación privada ni un resultado garantizado."
      ]},
      { heading: "Actúa dentro de la ventana vigente", paragraphs: [
        "El análisis visual solo importa mientras el pedido siga siendo accionable. La información actual de devoluciones de OOPBuy describe cinco días, 120 horas, desde el estado almacenado, contados desde la siguiente hora completa. Confirma el sello temporal y la política vigente antes de depender de ese dato, porque las reglas pueden cambiar. Revisa las fotos al aparecer y no esperes a futuros artículos. Un almacenamiento más largo no amplía automáticamente la ventana corta de decisión posventa.",
        "Si la evidencia muestra opción errónea, cantidad faltante o daño visible, usa la ruta posventa actual del pedido y describe la diferencia con objetividad. Una solicitud a tiempo no es aprobación automática: normas del vendedor, elegibilidad, estado, responsabilidad y proceso pueden afectar el resultado. Conserva opción, hora de almacén, imágenes relevantes y explicación enviada. No publiques números de pedido, direcciones, pagos ni identidades del soporte. El objetivo es un expediente privado completo, no una acusación pública."
      ]},
      { heading: "Cierra con un registro de decisión calibrado", paragraphs: [
        "Termina cada artículo con uno de cuatro resultados: aceptar por evidencia visible, pedir vista dirigida, abrir posventa o excluir del paquete mientras el problema siga abierto. Añade fecha, imagen decisiva, hechos verificados e incógnitas. Una conclusión útil puede decir que familia de color, etiqueta y cantidad coinciden, el material exacto no está verificado y no aparece daño visible en los ángulos suministrados. Es más informativa que una puntuación porque conserva tanto la evidencia como sus límites.",
        "Los registros anteriores mejoran preguntas futuras, pero no demuestran que otro lote o anuncio parecido sea idéntico. Comprueba identificador, opción, vendedor y construcción visible antes de reutilizar una conclusión. Tras la entrega, compara el estado con las vistas aceptadas y registra cualquier diferencia nueva sin adivinar dónde ocurrió. Con el tiempo se forma un archivo visual disciplinado: concreto para decidir, prudente frente a falsa certeza y distinto de los consejos de costes, descubrimiento de productos y estado de pedidos de los otros recursos OOPBuy."
      ]}
    ]
  },
  fr: {
    slug,
    title: "Ce que les photos QC OOPBuy peuvent prouver — et ce qu’elles ne prouvent pas",
    deck: "Une méthode rigoureuse pour séparer les preuves visibles de l’entrepôt des suppositions sur la matière, la taille, la fonction, l’authenticité et la performance future.",
    readTime: "12 min",
    published: "2026-09-03",
    sourceNote: "Limites du processus vérifiées le 3 septembre 2026 dans les informations OOPBuy actuelles sur l’inspection, le démarrage et les retours.",
    related: [
      { label: "Utiliser la méthode QC des photos d’entrepôt OOPBuy", kind: "qc" },
      { label: "Ouvrir la liste de contrôle photo QC OOPBuy existante", kind: "article", slug: "oopbuy-qc-photo-checklist" }
    ],
    sections: [
      { heading: "Commencer par l’affirmation, pas par la photographie", paragraphs: [
        "Une photographie d’entrepôt n’est utile que si la question est précise. Avant d’ouvrir la galerie, écrivez l’affirmation à tester : l’article reçu semble être de la couleur choisie, l’étiquette de taille est présente, deux pièces sont visibles ou une marque apparaît près d’une couture. Cela empêche une impression générale de qualité de remplacer un test observable. Les informations d’inspection OOPBuy actuelles citent quantité, couleur, taille, spécifications et dommages d’apparence visibles. Elles donnent un point de départ pratique, sans promettre que chaque propriété cachée ou technique a été testée.",
        "Attribuez trois étiquettes aux conclusions : visible, incertain ou non testable avec les images fournies. Visible signifie que la caractéristique se retrouve dans une ou plusieurs vues. Incertain s’applique lorsque lumière, angle, compression, obstruction ou absence d’échelle empêchent une lecture ferme. Non testable couvre composition des fibres, électronique interne, étanchéité, odeur, durabilité ou authenticité sans preuve adaptée. Ce vocabulaire rend la décision défendable et évite de faire porter à une photo plus de sens qu’elle n’en contient."
      ]},
      { heading: "Reconstruire la référence avant de comparer", paragraphs: [
        "La galerie d’entrepôt n’identifie pas seule le produit voulu. Rouvrez la fiche enregistrée ou la commande et récupérez le texte exact de l’option, la quantité, la taille, la couleur, le modèle et les pièces incluses choisis à l’achat. Identifiant de commande et option vendeur forment la couche de référence ; la galerie QC décrit l’article reçu. Si la fiche a changé, conservez le dossier daté réellement utilisé au lieu de comparer silencieusement avec une image récente ou un produit proche d’un autre vendeur.",
        "Créez un tableau de quatre colonnes : caractéristique attendue, preuve visible, confiance et action. Une ligne peut indiquer bleu marine choisi, tissu bleu foncé dans trois vues, confiance moyenne en raison d’une lumière chaude, puis demander une vue neutre si la nuance exacte compte. Une autre peut noter taille 42, étiquette 42 lisible, confiance élevée et aucun suivi. Cette structure sépare identité et appréciation esthétique et révèle précisément quelle vue manquante modifierait la décision."
      ]},
      { heading: "Lire angle, lumière et compression comme des limites", paragraphs: [
        "La position de l’appareil change les proportions apparentes. Un objet près du bord d’un grand-angle peut sembler étiré, une chaussure inclinée plus longue d’un côté et un vêtement plié asymétrique. Comparez des repères stables sur plusieurs images : coutures, jonctions de panneaux, œillets, bords ou positions des pièces métalliques. Un défaut qui disparaît quand l’angle change est moins solide qu’une caractéristique restant au même endroit physique. Ne déduisez jamais une mesure de la perspective seule sans règle et extrémités nettes dans le même plan.",
        "La couleur dépend aussi des conditions. Balance des blancs automatique, lumières mélangées, exposition et matières réfléchissantes peuvent déplacer teinte et luminosité. Comparez les objets neutres et vérifiez si le changement touche toute l’image. La compression efface parfois tissage fin, embossage faible ou petites marques ; l’accentuation exagère les bords. Une photo peut prouver qu’un article de famille rouge est arrivé, pas nécessairement la nuance exacte. Si celle-ci décide l’acceptation, demandez une comparaison ciblée sous lumière neutre."
      ]},
      { heading: "Séparer construction visible et affirmations sur la matière", paragraphs: [
        "Les images QC peuvent soutenir des observations sur ce qui est réellement montré : une couture ouverte, un panneau décalé, un imprimé traversant un pli, une tirette présente ou une marque sur le bord d’une semelle. Elles peuvent montrer la texture de surface si la résolution suffit. Notez l’emplacement et le numéro de l’image pour qu’une autre personne retrouve le même point. « Un fil lâche est visible au poignet gauche » vaut mieux que « mauvaise fabrication », qui transforme une observation en jugement non prouvé sur tout le produit.",
        "Des photos ordinaires n’établissent ni pourcentages de fibres, type de cuir, poids du rembourrage, traitement chimique, résistance ni usure future. Une étiquette visible documente sa déclaration sans vérifier indépendamment la matière. Brillance et texture peuvent venir de la lumière ou d’un film protecteur. Si une propriété est essentielle, déterminez la preuve adaptée : étiquette lisible, spécification vendeur, mesure ou test fonctionnel explicitement pris en charge par le service actuel. Sinon, gardez le champ inconnu au lieu de le remplir par attente."
      ]},
      { heading: "Appliquer des tests visuels propres à la catégorie", paragraphs: [
        "Pour les vêtements, contrôlez identité avant et arrière, étiquette, position du graphisme par rapport au col et aux coutures, taches évidentes, points ouverts et mesures disponibles. Pour les chaussures, comparez la paire, les étiquettes, panneaux, semelles, œillets, symétrie et état visible. La perspective agrandit souvent la chaussure la plus proche ; utilisez des repères répétés. Pour sacs et accessoires, comptez les pièces amovibles, inspectez fermetures, sangles, poignées et métal et distinguez film protecteur et surface finie avant de conclure à un dommage.",
        "Pour un produit en plusieurs pièces, la quantité doit être prouvée par une vue montrant tous les éléments ou par des images séparées attribuables sans doublon. Une boîte en arrière-plan ne prouve pas son contenu ; une poche fermée ne prouve pas l’accessoire. Appuyez le contrôle sur la description des pièces du vendeur et marquez chaque composant invisible comme non vérifié. C’est crucial lorsque la fiche offre plusieurs configurations : le bon article principal peut arriver avec le mauvais ensemble d’accessoires."
      ]},
      { heading: "Demander une seule vue ciblée à la fois", paragraphs: [
        "Une demande utile nomme l’objet, la vue et la décision. « Montrer l’imprimé arrière de face pour vérifier son alignement avec la couture centrale » est exploitable ; « prendre plus de photos » ne l’est pas. Pour une mesure, nommez les deux extrémités et gardez la règle visible dans le même plan. Si une trace peut être un reflet, demandez le même endroit sous un autre angle. Si la couleur est incertaine, demandez une vue neutre avec repère stable. La demande teste une incertitude définie au lieu d’ouvrir une seconde inspection vague.",
        "Classez les demandes selon leur valeur décisionnelle. D’abord identité, option choisie, quantité et dommages visibles graves ; ensuite mesures liées à la taille ou composants déterminant l’usage ; détails cosmétiques en dernier. Ne demandez pas une image seulement parce qu’elle est possible, mais parce que le résultat peut changer acceptation, après-vente ou emballage. Conservez ensemble galerie initiale, texte demandé, nouvelle vue et décision. Cette séquence montre ce qui était connu sans inventer une conversation privée ni garantir le résultat."
      ]},
      { heading: "Agir dans la fenêtre de commande actuelle", paragraphs: [
        "L’analyse visuelle ne sert que tant que la commande reste actionnable. Les informations de retour OOPBuy actuelles décrivent cinq jours, soit 120 heures, après le statut stocké, comptés depuis l’heure pleine suivante. Confirmez l’horodatage en direct et la règle présente avant de vous y fier, car les politiques évoluent. Examinez les photos dès leur apparition plutôt que d’attendre les futurs articles. Une durée de stockage plus longue ne prolonge pas automatiquement la courte fenêtre de décision après-vente.",
        "Si les preuves montrent mauvaise option, quantité manquante ou dommage visible, utilisez la voie après-vente actuelle et décrivez l’écart objectivement. Une demande à temps n’est pas une approbation automatique : règles vendeur, éligibilité, état, responsabilité et processus peuvent influencer le résultat. Conservez option, heure de stockage, images et explication envoyée. Ne publiez ni numéro de commande, adresse, paiement ni identité du support. Le but est un dossier privé complet, pas une accusation publique."
      ]},
      { heading: "Terminer par un dossier de décision calibré", paragraphs: [
        "Clôturez chaque article par l’un de quatre résultats : accepter sur preuves visibles, demander une vue ciblée, ouvrir l’après-vente ou exclure du colis tant que le problème reste ouvert. Ajoutez date, image décisive, faits vérifiés et inconnues. Une conclusion utile peut dire que famille de couleur, étiquette et quantité correspondent, que la matière exacte n’est pas vérifiée et qu’aucun dommage n’apparaît sous les angles fournis. Elle informe mieux qu’une note de qualité, car elle conserve preuve et limite.",
        "Les anciens dossiers QC améliorent les questions futures mais ne prouvent pas qu’un autre lot ou une fiche semblable est identique. Vérifiez identifiant, option, vendeur et construction visible avant de réutiliser une conclusion. Après livraison, comparez l’état aux vues acceptées et notez toute différence sans deviner son origine. Au fil du temps se crée une archive visuelle disciplinée : assez précise pour décider, assez prudente pour éviter la fausse certitude et distincte des conseils de coûts, découverte de produits et statuts de commande des autres ressources OOPBuy."
      ]}
    ]
  },
  it: {
    slug,
    title: "Cosa possono provare le foto QC OOPBuy e cosa no: guida alle prove visive",
    deck: "Un metodo disciplinato per separare le prove visibili del magazzino dalle ipotesi su materiale, vestibilità, funzione, autenticità e prestazioni future.",
    readTime: "12 min",
    published: "2026-09-03",
    sourceNote: "Limiti del processo verificati il 3 settembre 2026 con le informazioni OOPBuy correnti su ispezione, guida iniziale e resi.",
    related: [
      { label: "Usa il metodo QC per le foto di magazzino OOPBuy", kind: "qc" },
      { label: "Apri la checklist esistente delle foto QC OOPBuy", kind: "article", slug: "oopbuy-qc-photo-checklist" }
    ],
    sections: [
      { heading: "Inizia dall’affermazione, non dalla fotografia", paragraphs: [
        "Una fotografia di magazzino è utile solo quando la domanda è precisa. Prima di aprire la galleria, scrivi l’affermazione da verificare: l’articolo ricevuto sembra del colore selezionato, l’etichetta della taglia è presente, sono visibili due pezzi oppure compare un segno vicino a una cucitura. Così una sensazione generale di qualità non sostituisce un test osservabile. Le informazioni correnti sull’ispezione OOPBuy citano quantità, colore, taglia, specifiche e danni visibili all’aspetto. Sono un punto di partenza pratico, non la promessa che ogni proprietà nascosta o tecnica sia stata testata.",
        "Classifica ogni conclusione come visibile, incerta o non verificabile dalle immagini. Visibile significa che la caratteristica è localizzabile in una o più foto. Incerta indica che luce, angolo, compressione, ostacolo o mancanza di scala impediscono una lettura sicura. Non verificabile comprende fibre, elettronica interna, impermeabilità, odore, durata o autenticità senza prove adeguate. Questo vocabolario rende la decisione difendibile e impedisce a una fotografia di assumere più significato di quello che contiene."
      ]},
      { heading: "Ricostruisci il riferimento prima del confronto", paragraphs: [
        "La galleria del magazzino non identifica da sola il prodotto previsto. Riapri l’inserzione salvata o il registro dell’ordine e recupera testo esatto dell’opzione, quantità, taglia, colore, modello e pezzi inclusi scelti. Identificativo e opzione del venditore formano il livello di riferimento; la galleria QC descrive l’articolo arrivato. Se l’inserzione è cambiata, conserva il record datato usato davvero invece di confrontare in silenzio con un’immagine nuova o con un prodotto simile di un altro venditore.",
        "Crea una tabella con quattro colonne: caratteristica attesa, prova visibile, fiducia e azione. Una riga può dire blu navy selezionato, tessuto blu scuro in tre immagini, fiducia media per luce calda, chiedere vista neutra se conta la tonalità. Un’altra registra taglia 42, etichetta 42 chiara, fiducia alta e nessun seguito. La struttura separa l’identità dal giudizio estetico e mostra quale vista mancante cambierebbe la decisione."
      ]},
      { heading: "Leggi angolo, luce e compressione come limiti", paragraphs: [
        "La posizione della camera cambia le proporzioni apparenti. Un oggetto al bordo di un grandangolo può sembrare allungato, una scarpa inclinata più lunga da un lato e un capo piegato asimmetrico. Confronta riferimenti stabili in più foto: cuciture, giunzioni dei pannelli, occhielli, bordi o hardware. Un dubbio che scompare cambiando angolo è più debole di una caratteristica che resta nello stesso punto fisico. Non dedurre una misura dalla prospettiva se righello ed estremi chiari non sono visibili sullo stesso piano.",
        "Anche il colore dipende dalle condizioni. Bilanciamento automatico, luci miste, esposizione e materiali riflettenti possono cambiare tinta e luminosità. Confronta oggetti neutri e verifica se lo spostamento interessa tutta l’immagine. La compressione può cancellare trama fine, rilievo leggero o piccoli segni, mentre la nitidezza accentua i bordi. Una foto può provare la famiglia rossa, non sempre una tonalità esatta. Se il colore decide l’accettazione, chiedi un confronto mirato con luce neutra."
      ]},
      { heading: "Separa costruzione visibile e dichiarazioni sui materiali", paragraphs: [
        "Le immagini QC possono sostenere osservazioni sulla costruzione mostrata: una cucitura è aperta, un pannello è disallineato, una stampa attraversa una piega, un tirazip è presente o il bordo della suola ha un segno. Possono mostrare texture superficiale con risoluzione sufficiente. Annota posizione e numero della foto perché un’altra persona trovi lo stesso dettaglio. «Un filo libero è visibile sul polsino sinistro» è meglio di «è fatto male», che trasforma una singola osservazione in un giudizio senza prova sull’intero articolo.",
        "Fotografie normali non stabiliscono percentuali di fibra, tipo di pelle, peso dell’imbottitura, trattamenti chimici, resistenza o usura futura. Un’etichetta visibile documenta ciò che dichiara, ma non verifica il materiale. Lucentezza e texture possono dipendere da luce o pellicola protettiva. Se una proprietà è essenziale, identifica la prova adatta: etichetta leggibile, specifica del venditore, misura o test funzionale esplicitamente supportato dal servizio corrente. In assenza, mantieni il campo sconosciuto invece di riempirlo con aspettative."
      ]},
      { heading: "Usa test visivi specifici per categoria", paragraphs: [
        "Per l’abbigliamento controlla fronte e retro, etichetta taglia, posizione della grafica rispetto a collo e cuciture, macchie, punti aperti e misure disponibili. Per le scarpe confronta paio, etichette, pannelli, forma della suola, occhielli, simmetria e condizione visibile. La prospettiva ingrandisce spesso la scarpa vicina, quindi usa riferimenti ripetuti. Per borse e accessori conta pezzi rimovibili, controlla chiusure, tracolle, manici e hardware e distingui pellicola protettiva e superficie finita prima di dichiarare un danno.",
        "Nei prodotti composti la quantità deve essere provata da una foto di tutti i pezzi attesi o da immagini separabili senza duplicazione. Una scatola sullo sfondo non prova il contenuto e una tasca chiusa non prova l’accessorio interno. Basa il controllo sulla descrizione dei componenti del venditore e segna ogni parte non vista come non verificata. È fondamentale quando una pagina offre configurazioni diverse: può arrivare l’articolo principale corretto con il set di accessori sbagliato."
      ]},
      { heading: "Chiedi una vista mirata alla volta", paragraphs: [
        "Una richiesta utile indica oggetto, vista e decisione. «Mostra la stampa posteriore frontalmente per controllare l’allineamento con la cucitura centrale» è eseguibile; «fai altre foto» non lo è. Se serve una misura, indica entrambi gli estremi e chiedi il righello visibile sullo stesso piano. Se un segno può essere un riflesso, richiedi lo stesso punto da un altro angolo. Se il colore è incerto, chiedi una panoramica con luce neutra e riferimento stabile. La richiesta deve testare un’incertezza definita.",
        "Dai priorità in base al valore decisionale. Prima identità, opzione scelta, quantità e danni seri visibili; poi misure di vestibilità o componenti che determinano l’uso; dettagli cosmetici per ultimi. Non chiedere una foto solo perché è disponibile, ma perché il risultato può cambiare accettazione, post-vendita o imballaggio. Conserva insieme galleria originale, testo della richiesta, nuova immagine e decisione. La sequenza prova cosa era noto in ogni passaggio senza inventare conversazioni private o risultati garantiti."
      ]},
      { heading: "Agisci entro la finestra corrente dell’ordine", paragraphs: [
        "L’analisi visiva conta solo mentre l’ordine è ancora gestibile. Le informazioni correnti sui resi OOPBuy descrivono cinque giorni, 120 ore, dallo stato in magazzino, conteggiati dall’ora intera successiva. Conferma timestamp e regola attuale prima di dipendere dal numero, perché le politiche cambiano. Controlla le foto quando compaiono e non aspettare tutti gli articoli futuri. Un periodo di stoccaggio più lungo non estende automaticamente la finestra breve per la decisione post-vendita.",
        "Se le prove mostrano opzione errata, quantità mancante o danno visibile, usa il percorso post-vendita corrente e descrivi la differenza in modo oggettivo. Una richiesta tempestiva non è approvazione automatica: regole del venditore, idoneità, stato, responsabilità e processo possono influire. Conserva opzione, ora di ingresso, immagini e spiegazione inviata. Non pubblicare numeri d’ordine, indirizzi, pagamenti o identità del supporto. L’obiettivo è un fascicolo privato completo, non un’accusa pubblica."
      ]},
      { heading: "Chiudi con un registro decisionale calibrato", paragraphs: [
        "Concludi ogni articolo con uno di quattro esiti: accettare sulla prova visibile, chiedere una vista mirata, aprire il post-vendita o escludere dal pacco finché il problema resta aperto. Aggiungi data, immagine decisiva, fatti verificati e incognite. Una conclusione utile può dire che famiglia di colore, etichetta e quantità coincidono, il materiale esatto non è verificato e non compare danno negli angoli forniti. È più informativa di un voto perché conserva prova e limiti.",
        "I vecchi registri QC migliorano le domande future, ma non provano che un lotto successivo o un’inserzione simile siano identici. Verifica identificatore, opzione, venditore e costruzione visibile prima di riutilizzare una conclusione. Dopo la consegna confronta lo stato con le viste accettate e registra nuove differenze senza indovinare la causa. Nel tempo nasce un archivio visivo disciplinato: concreto per decidere, prudente contro la falsa certezza e distinto dai consigli su costi, scoperta dei prodotti e stato degli ordini delle altre risorse OOPBuy."
      ]}
    ]
  }
};
