import { localizedArticleExpansions, splitArticleExpansion } from "@/lib/localized-article-expansions";
import { qvlC01Articles } from "@/lib/qvl-c01";

type Locale = "en" | "de" | "es" | "fr" | "it";
type Article = { slug: string; title: string; deck: string; readTime: string; published?: string; sourceNote?: string; related?: { label: string; kind: "qc" | "article"; slug?: string }[]; sections: { heading: string; paragraphs: string[] }[]; sources?: { label: string; href: string }[] };

const officialSources = {
  beginner: [
    { label: "OOPBUY beginner guide", href: "https://m.oopbuy.com/pages/article-details/index?id=1739829963819945985" },
    { label: "OOPBUY tutorial", href: "https://m.oopbuy.com/notice/1740653409764216834" },
    { label: "Returns and refunds", href: "https://m.oopbuy.com/notice/1740656181012172801" },
    { label: "Warehouse inspection", href: "https://m.oopbuy.com/notice/1740664942636404738" },
  ],
  fees: [
    { label: "Service & Fees", href: "https://m.oopbuy.com/notice/1740653781924810754" },
    { label: "User Registration Agreement", href: "https://m.oopbuy.com/notice/1772892211576897537" },
    { label: "Returns and refunds", href: "https://m.oopbuy.com/notice/1740656181012172801" },
    { label: "Prohibited and restricted items", href: "https://m.oopbuy.com/notice/1772880724846247937" },
  ],
} as const;

const beginnerEnglish: Article = {
  slug: "oopbuy-beginner-guide-2026",
  title: "OOPBUY visual evidence guide 2026: preserve proof from listing to parcel",
  deck: "A fact-checked workflow for keeping listing, order, warehouse and parcel evidence connected without overclaiming what each source proves.",
  readTime: "11 min read",
  sources: [...officialSources.beginner],
  sections: [
    { heading: "Understand the two-stage purchase", paragraphs: [
      "Using OOPBUY is not the same as buying from a conventional store that owns the product and quotes one delivered price. OOPBUY describes itself as a shopping service for Chinese marketplaces including Taobao, 1688 and Weidian. In practice, the workflow has two commercial stages: first the product is purchased from a domestic seller and delivered to an OOPBUY warehouse; later, one or more warehouse items are packed and sent internationally. Keeping those stages separate explains why the product total is not the final landed cost.",
      "A beginner should therefore create two budgets before opening a listing. The first covers product price, domestic seller delivery and any order-stage charge shown at checkout. The second covers packing, value-added services, international transport and possible destination taxes or customs charges. The exact total cannot be known from a product thumbnail alone. A useful budget is a range with a safety margin, not a promise based on the cheapest visible number."
    ]},
    { heading: "Find a current product route", paragraphs: [
      "OOPBUY’s tutorial begins with registration and product selection. A spreadsheet can shorten discovery, but every candidate must still be opened on its current destination page. Confirm that the page loads, the title and first image describe the expected item, and the required color, size or configuration is actually selectable. Product pages can change after a spreadsheet is published, so the live route—not the old thumbnail—controls the decision.",
      "Save the product URL, product ID, selected option, quantity and date. If sizing matters, record the seller’s measurement method rather than only the nominal label. If a page offers several visually similar variants, capture the exact option text. This product trail will later be used to review warehouse photos. Without it, a buyer is forced to compare the received item with memory, which is especially unreliable after several sellers and variants have been combined."
    ]},
    { heading: "Place the order with useful instructions", paragraphs: [
      "At the order stage, verify the selected variation, quantity and domestic delivery charge shown by the seller. Use order remarks only for information the purchasing team can realistically communicate or check, such as a required color name or seller option. Vague instructions such as ‘best quality’ do not create a measurable standard. A specific note is more useful: confirm the selected size, request the listed accessory count, or avoid substitution when the chosen color is unavailable.",
      "Payment method availability and charges can change, so use the live checkout as the controlling source. OOPBUY has an official PayPal instruction page, but the existence of one payment guide does not mean every method, currency or fee is permanently available in every account. Save the order reference and paid amount. If a payment appears pending or duplicated, stop and use the platform’s current support route before submitting another payment."
    ]},
    { heading: "Read order status as a chain of evidence", paragraphs: [
      "After payment, OOPBUY purchases from the seller and waits for domestic delivery. A delayed seller shipment is different from a warehouse processing delay, and both are different from international transit. Keep those states separate when assessing progress. The warehouse cannot photograph an item it has not received, while a seller dispatch notification does not prove that the correct variant arrived.",
      "OOPBUY’s inspection information says warehouse staff open qualifying incoming packages for prohibited-item inspection, then weigh and store them. Its beginner guide also says that goods arriving at the warehouse are quality-inspected and photographed for the user. These are useful checkpoints, but they are not a guarantee of authenticity, material composition, fit or long-term durability. The photos document visible evidence from the received item."
    ]},
    { heading: "Review QC photos before the clock becomes the problem", paragraphs: [
      "Compare the warehouse images against the record created at purchase. Start with objective identity checks: color family, size label, model, quantity and included pieces. Then inspect category-specific details. For clothing, review front, back, graphic placement, stains, open seams and any supplied measurements. For shoes, compare the pair, size, panel layout, sole shape, symmetry and visible surface marks. For bags, inspect overall structure, handles, straps, closures and obvious hardware differences.",
      "OOPBUY’s current return and exchange material states a five-day window—120 hours—after the order becomes stored in the warehouse, counted from the next full hour. That deadline is much shorter than the storage period. Review photos when they arrive, not when the rest of a future parcel is ready. If a critical point is unclear, ask a targeted question through the current service flow while the order remains actionable."
    ]},
    { heading: "Treat returns as a request, not an automatic result", paragraphs: [
      "The official aftersales page directs users to open the relevant order and select the aftersales option. OOPBUY then requests a return or exchange from the seller. Seller approval, item eligibility, condition, timing and domestic return costs can affect the result. The five-day window should not be interpreted as a guarantee that every seller accepts every reason. Preserve photos and describe the mismatch objectively: wrong size label, missing quantity, different option or visible damage.",
      "The official shopping notice states that warehouse storage runs for 90 days from the in-storage status. Storage and return eligibility serve different purposes. Ninety days may provide time to consolidate compatible items, but it does not extend the 120-hour decision period. A sensible routine is to inspect every arrival immediately, resolve aftersales questions, then use the remaining storage time only for planned consolidation."
    ]},
    { heading: "Build the parcel from measurements, not hope", paragraphs: [
      "When the accepted items are ready, choose which ones belong in the same parcel. Note rigid boxes, padded jackets, fragile structures and items with transport restrictions. A low-price item can make a parcel disproportionately expensive if it creates unused volume or removes access to an otherwise suitable shipping line. Combining everything is not automatically cheaper; compare the whole parcel with a possible split.",
      "OOPBUY provides a shipping estimation page that asks for destination and weight. Use it as a planning tool and enter realistic packed assumptions. International carriers may compare actual scale weight with volumetric weight derived from package dimensions and charge under the route’s own rule. Do not apply one universal divisor to every service. The selected line’s current definition, size limits and eligible contents should control the comparison."
    ]},
    { heading: "Pay, track and close the record", paragraphs: [
      "OOPBUY’s tutorial distinguishes estimated shipping payment from the actual cost calculated after packing. That is why an estimate should not be presented as a final invoice. At parcel submission, recheck the destination address, included warehouse items, packaging choices, route, restrictions, tracking level, estimated transit and final amount. Save the parcel or waybill reference and the exact items placed inside.",
      "The tutorial says tracking can be checked in ‘My Waybill’ after shipment, while the delivery notice says a tracking number is provided. Transit estimates remain ranges because third-party carriers, customs and local delivery partners control parts of the journey. After delivery, compare actual charge, packed weight, transit and condition with the plan. Recording the difference improves the next estimate and completes the product trail that began with the spreadsheet row.",
      "Do not judge the entire service from a single fast or slow scan. Tracking systems can update in batches, and a quiet interval can represent movement, customs processing or a delayed data handoff. Use the latest carrier event, parcel identifier and support response as evidence, and avoid publishing a delivery claim that cannot be tied to a dated shipment. For future planning, record the route, submission date, dispatch date, packed measurements, final charge and delivery date in one line. After several comparable parcels, this small history becomes more useful than an anonymous timing promise: it reveals the normal range for your destinations and parcel shapes while preserving the fact that the next shipment can still differ."
    ]},
  ]
};

const feesEnglish: Article = {
  slug: "oopbuy-fees-returns-policy",
  title: "OOPBUY warehouse deadlines: protect the QC evidence window",
  deck: "A careful reading of the 8% agreement language, the service page, the 120-hour return window and 90-day storage rule.",
  readTime: "11 min read",
  sources: [...officialSources.fees],
  sections: [
    { heading: "Why one headline cannot explain OOPBUY fees", paragraphs: [
      "OOPBUY’s official documents do not support a simple blanket statement such as ‘there are no service fees.’ The current Service & Fees page says no other fees are charged beyond product fees, international shipping and customs clearance, apart from optional value-added services. However, the official User Registration Agreement separately says users need to pay logistics costs and a platform service fee and states that the specific platform service fee is calculated at 8%. Those statements need to be shown together rather than silently choosing the more attractive one.",
      "The safest interpretation is operational: official documents can describe different scopes, dates or transactions, and the live order or parcel checkout is the controlling amount for a specific purchase. Before payment, examine the itemized total and save it. Do not calculate landed cost from a promotional phrase. If a line is unclear, ask support which agreement or campaign applies to that order before committing funds."
    ]},
    { heading: "Build a complete cost map", paragraphs: [
      "A transparent OOPBUY budget separates product price, seller-side domestic freight, order-stage platform or payment charges shown at checkout, optional services, packing, international freight and possible destination customs or tax. Some components may be zero in a particular transaction, but they should remain visible in the model. Leaving a category out because it was free last time turns a planning assumption into a hidden surprise.",
      "The approximate USD prices on this site cover the product conversion only. They are not delivered prices and they are not OOPBUY checkout quotes. Exchange rates move, product pages change and payment providers may use their own conversion. Use a current rate, retain a margin and compare the final charged currency with the estimate. For higher-value orders, a small percentage difference can matter more than a small difference between product listings."
    ]},
    { heading: "Estimated shipping is not the packed-parcel total", paragraphs: [
      "OOPBUY offers a shipping estimation tool based on destination and weight. Its tutorial also makes an important distinction: payment at one stage is for estimated shipping, while the actual shipping cost is determined after the parcel is packed and shown in the shipment area. That sequence explains why a rough item-weight estimate can differ from a packed result. Packaging adds mass, and parcel dimensions may trigger a volumetric calculation.",
      "Use three scenarios instead of one number: compact, expected and bulky. Update them when warehouse weights or measurements become available. Compare actual and volumetric concepts under each eligible route, but use the route’s own current rule rather than assuming every carrier divides volume by the same factor. A shipping estimate is useful when it exposes the variables; it becomes misleading when it is presented as a guaranteed final charge."
    ]},
    { heading: "The 120-hour return and exchange clock", paragraphs: [
      "OOPBUY’s official return and exchange page states that a no-reason request may be made within five days, or 120 hours, after the order status changes to stored in the warehouse, calculated from the next full hour. This is the deadline that should shape the QC routine. Record the storage time, review the photos promptly and flag any objective mismatch before waiting for other items.",
      "A request is not identical to a completed return. The aftersales page says OOPBUY asks the seller for an exchange and processes it with the seller’s approval. Eligibility, seller response, item condition and return freight may affect the outcome. Use the order’s aftersales function, preserve the listing reference and warehouse images, and state the reason precisely. Always verify the live rule because policy text can be updated."
    ]},
    { heading: "Ninety-day storage does not extend aftersales", paragraphs: [
      "The official pre-shopping notice says goods are stored for 90 days from the time the order status becomes in storage. This longer period supports consolidation and parcel planning; it should not be confused with the five-day return and exchange window. An item can remain stored while the easier aftersales opportunity has already expired.",
      "Use a two-calendar system. Calendar one counts down the 120-hour QC and aftersales decision. Calendar two tracks warehouse storage and planned parcel submission. Inspect and resolve each item under the first calendar, then combine accepted items under the second. Avoid using the full storage allowance by default. Policies can change, and an old warehouse item may no longer be easy to return even though it remains physically stored."
    ]},
    { heading: "Restricted goods can change both cost and eligibility", paragraphs: [
      "OOPBUY maintains a prohibited and restricted items page. The published examples include tobacco, alcohol, contraband, knives and sharp objects, while the pre-shopping notice also flags categories such as food and medicine. A warehouse inspection can identify prohibited items, but a product reaching storage does not prove that every destination or transport line will accept it.",
      "Mark batteries, liquids, magnets, food, medicine and other potentially restricted goods before ordering. Then check the current destination and route rules before parcel consolidation. One restricted item can remove lower-cost lines from an entire parcel. If necessary, compare a separate parcel against the extra fixed cost. Do not publish permanent ‘safe line’ claims because carrier and customs rules can change."
    ]},
    { heading: "Use reviews as signals, not policy", paragraphs: [
      "Public reviews and community posts show both positive and negative experiences. Recent review excerpts mention successful purchases and fast delivery, while other posts raise concerns about shipping estimates, QC timing or support. Trustpilot itself states that it does not fact-check individual reviews, and community posts are self-selected accounts without a controlled sample. They can reveal questions worth investigating but cannot replace official terms or a buyer’s own checkout evidence.",
      "A useful review article should therefore describe method, date and sample. Separate verified policy from user allegation, avoid turning one shipment into a universal performance claim and include criticism as well as praise. The first research priority remains the official workflow; review analysis belongs later, after the site already explains costs, QC, returns and shipping in a way readers can verify."
    ]},
    { heading: "A pre-payment audit that prevents most confusion", paragraphs: [
      "Before paying for a product, save the option, seller route, domestic freight, displayed charges and exchange-rate assumption. Before accepting a warehouse item, compare identity and condition, note the 120-hour deadline and use aftersales promptly if needed. Before paying for a parcel, check contents, packed measurements, chargeable-weight rule, route eligibility, packaging, tracking and the actual amount shown.",
      "Keep screenshots or receipts for the figures that matter, but do not expose private account information publicly. If an official page conflicts with another official document, record both and ask which controls the transaction. This disciplined audit is more valuable than a confident slogan. It produces a traceable decision, makes support questions specific and gives the next parcel better evidence for cost planning.",
      "For a fair comparison with another buying route, use the same basket, destination, currency date and packaging assumption. Comparing one platform’s product-only price with another platform’s delivered total produces a meaningless winner. Separate required charges from optional protection, then compare both the expected case and a higher-cost case. When the live checkout differs from a published guide, keep the dated checkout evidence and treat the guide as background rather than a guarantee. This method also makes future updates honest: an article can state what the official documents said on the review date, identify the unresolved conflict and tell the reader exactly which screen needs confirmation. Accuracy is not pretending that every cost is stable; it is showing which number was observed, when it was observed and which variables can still change before delivery."
    ]},
  ]
};

function localizedArticle(locale: Exclude<Locale, "en">, kind: "beginner" | "fees"): Article {
  const data = {
    de: {
      beginner: ["OOPBUY-Guide zu visuellen Belegen 2026: vom Angebot bis zum Paket", "Ein faktisch geprüfter Ablauf, der Angebot, Bestellung, Lager und Paket verbindet, ohne die Aussagekraft einer Quelle zu übertreiben.", ["Den zweistufigen Kauf verstehen", "Eine aktuelle Produktroute prüfen", "Mit klaren Angaben bestellen", "Bestellstatus als Belegkette lesen", "QC-Fotos rechtzeitig prüfen", "Rückgabe ist ein Antrag", "Das Paket nach Messdaten bauen", "Bezahlen, verfolgen und dokumentieren"]],
      fees: ["OOPBUY-Lagerfristen: das QC-Belegfenster schützen", "8%-Vertragstext, Serviceseite, 120-Stunden-Frist und 90-Tage-Lagerung im Kontext einer rechtzeitigen Belegentscheidung.", ["Warum eine Überschrift Gebühren nicht erklärt", "Vollständige Kostenkarte", "Versandschätzung ist kein Endbetrag", "Die 120-Stunden-Frist", "90 Tage verlängern Aftersales nicht", "Eingeschränkte Waren verändern Kosten", "Bewertungen sind Signale", "Audit vor der Zahlung"]]
    },
    es: {
      beginner: ["Guía de evidencia visual OOPBUY 2026: del anuncio al paquete", "Un proceso verificado que conecta anuncio, pedido, almacén y paquete sin exagerar lo que prueba cada fuente.", ["Entender la compra en dos etapas", "Comprobar una ruta actual", "Pedir con instrucciones útiles", "Leer los estados como evidencias", "Revisar QC dentro del plazo", "La devolución es una solicitud", "Crear el paquete con medidas", "Pagar, seguir y cerrar el registro"]],
      fees: ["Plazos de almacén OOPBUY: protege la ventana de evidencia QC", "Lectura del 8%, servicios, 120 horas y 90 días dentro de una decisión de evidencia a tiempo.", ["Un titular no explica las tarifas", "Mapa completo de costes", "La estimación no es el total final", "El reloj de 120 horas", "90 días no amplían la posventa", "Las restricciones cambian el coste", "Las reseñas son señales", "Auditoría antes de pagar"]]
    },
    fr: {
      beginner: ["Guide des preuves visuelles OOPBUY 2026 : de l’annonce au colis", "Un parcours vérifié reliant annonce, commande, entrepôt et colis sans exagérer ce que chaque source prouve.", ["Comprendre l’achat en deux étapes", "Vérifier une route actuelle", "Commander avec des instructions utiles", "Lire les statuts comme des preuves", "Contrôler les photos dans le délai", "Le retour reste une demande", "Construire le colis avec les mesures", "Payer, suivre et fermer le dossier"]],
      fees: ["Délais d’entrepôt OOPBUY : protéger la fenêtre de preuve QC", "Lecture du texte à 8 %, des services, des 120 heures et des 90 jours pour une décision de preuve à temps.", ["Un slogan n’explique pas les frais", "Cartographier tous les coûts", "L’estimation n’est pas le total final", "Le délai de 120 heures", "90 jours ne prolongent pas le retour", "Les restrictions changent le coût", "Les avis sont des signaux", "Audit avant paiement"]]
    },
    it: {
      beginner: ["Guida alle prove visive OOPBUY 2026: dall’annuncio al pacco", "Un flusso verificato che collega annuncio, ordine, magazzino e pacco senza esagerare ciò che ogni fonte prova.", ["Capire l’acquisto in due fasi", "Verificare un percorso attuale", "Ordinare con istruzioni utili", "Leggere gli stati come prove", "Controllare il QC entro il termine", "Il reso è una richiesta", "Creare il pacco con misure", "Pagare, tracciare e chiudere il registro"]],
      fees: ["Scadenze di magazzino OOPBUY: proteggi la finestra di evidenza QC", "Lettura dell’8%, dei servizi, delle 120 ore e dei 90 giorni per una decisione di evidenza tempestiva.", ["Un titolo non spiega i costi", "Mappa completa dei costi", "La stima non è il totale finale", "La finestra di 120 ore", "90 giorni non estendono il reso", "Le restrizioni cambiano il costo", "Le recensioni sono segnali", "Controllo prima del pagamento"]]
    }
  } as const;
  const selected = data[locale][kind];
  const source = kind === "beginner" ? beginnerEnglish : feesEnglish;
  const summaries: Record<Exclude<Locale, "en">, Record<"beginner" | "fees", string[]>> = {
    de: {
      beginner: ["OOPBUY ist ein Einkaufsdienst für Marktplätze wie Taobao, 1688 und Weidian. Produktkauf und internationaler Versand sind zwei getrennte Kostenstufen. Plane Produkt, Inlandsfracht, mögliche Checkout-Gebühren, Verpackung, internationalen Transport und Zielabgaben getrennt.", "Öffne jede Route aktuell und speichere URL, Produkt-ID, Variante, Größe, Farbe und Datum. Die Live-Seite entscheidet, nicht ein alter Tabellen-Screenshot. Präzise Bestellhinweise sind messbar; Aussagen wie ‘beste Qualität’ sind es nicht.", "Zahlungsmethoden und Gebühren können sich ändern. Nutze den Live-Checkout, speichere Referenz und Betrag und wiederhole keine unklare Zahlung. Der offizielle Ablauf beginnt mit Registrierung, Auswahl und Bezahlung.", "Lagerprüfung, Verkäufertransport und internationaler Versand sind verschiedene Status. Offizielle OOPBUY-Texte sagen, dass Wareneingänge auf verbotene Inhalte geprüft, gewogen, gelagert und fotografiert werden. Fotos sind sichtbare Belege, keine Echtheits- oder Haltbarkeitsgarantie.", "Vergleiche Farbe, Größenetikett, Menge und Kategorie-Details sofort. Die offizielle Rückgaberegel nennt fünf Tage oder 120 Stunden ab Einlagerung, gerechnet ab der nächsten vollen Stunde. Warte nicht bis zur Paketeinreichung.", "Aftersales wird im Auftrag geöffnet; OOPBUY fragt den Verkäufer an. Zustimmung, Zustand, Frist und Rücktransport beeinflussen das Ergebnis. Die offiziellen 90 Tage Lagerung verlängern die 120-Stunden-Frist nicht.", "Nutze Ziel, realistisches Packgewicht und Volumen für den Versandrechner. Tatsächliches und volumetrisches Gewicht sowie Routenbeschränkungen können den Preis bestimmen. Eine Aufteilung kann sinnvoller als automatische Konsolidierung sein.", "Das Tutorial unterscheidet geschätzte und nach dem Packen tatsächliche Versandkosten. Prüfe Adresse, Inhalt, Route, Schutz und Endbetrag. Nach Versand steht Tracking laut Tutorial unter ‘My Waybill’ zur Verfügung."],
      fees: ["Die Serviceseite nennt Produkt, internationalen Versand, Zoll und optionale Dienste; die Registrierungsvereinbarung nennt zugleich eine Plattformgebühr von 8 %. Beide offiziellen Aussagen müssen zusammen gezeigt werden. Der aktuelle Checkout entscheidet für die konkrete Transaktion.", "Trenne Produkt, Inlandsfracht, Checkout- oder Zahlungsgebühr, Zusatzservice, Verpackung, internationalen Versand und Zielabgaben. Ungefähre USD-Produktpreise sind keine Lieferpreise.", "Der offizielle Rechner liefert eine Planung. Das Tutorial sagt, dass zunächst geschätzt und der tatsächliche Versand nach dem Packen ausgewiesen wird. Verpackung, Maße und Volumengewicht können die Differenz erklären.", "Die Rückgabeseite nennt fünf Tage oder 120 Stunden nach Einlagerung ab der nächsten vollen Stunde. Prüfe QC sofort und sichere Produktreferenz und Bilder.", "90 Tage Lagerung dienen der Konsolidierung, verlängern Aftersales aber nicht. Führe einen kurzen Rückgabe- und einen separaten Lagerkalender.", "Offizielle Listen nennen unter anderem Tabak, Alkohol, Schmuggelware, Messer, Lebensmittel und Medizin. Lagerung beweist nicht, dass jede Route oder jedes Zielland den Artikel akzeptiert.", "Trustpilot und Community-Posts zeigen positive und negative Erfahrungen, werden aber nicht als kontrollierte Stichprobe verifiziert. Sie liefern Fragen, nicht verbindliche Regeln.", "Speichere vor Produkt-, Lager- und Paketzahlung die jeweiligen Optionen, Beträge, Fristen und Messdaten. Bei Konflikten zwischen offiziellen Texten beide dokumentieren und den aktuellen Checkout beziehungsweise Support klären lassen."]
    },
    es: {
      beginner: ["OOPBUY presta servicio para mercados como Taobao, 1688 y Weidian. La compra nacional y el envío internacional son dos fases distintas; separa producto, transporte nacional, servicios, embalaje, envío y posibles cargos de destino.", "Abre la ruta vigente y guarda URL, ID, opción, talla, color y fecha. La página actual manda sobre una captura antigua. Las instrucciones deben ser concretas y comprobables.", "Los métodos y cargos de pago cambian. Usa el checkout actual, conserva referencia e importe y no repitas un pago incierto sin verificarlo.", "Los estados de vendedor, almacén y envío internacional son distintos. OOPBUY indica inspección de artículos prohibidos, pesaje, almacenamiento, control y fotos. Las fotos son evidencia visible, no garantía de autenticidad o duración.", "Compara color, talla, cantidad y detalles por categoría al llegar. La norma oficial indica cinco días o 120 horas desde el almacenamiento, contados desde la siguiente hora completa.", "La posventa solicita devolución o cambio al vendedor; aprobación, estado, plazo y transporte pueden afectar el resultado. Los 90 días de almacén no amplían las 120 horas.", "Usa destino, peso embalado y volumen realistas. El peso real, el volumétrico y las restricciones de la ruta pueden controlar el precio; dividir el paquete también debe compararse.", "El tutorial diferencia coste estimado y coste real tras embalar. Revisa dirección, contenido, ruta y total; después usa ‘My Waybill’ para el seguimiento."],
      fees: ["La página de servicios habla de producto, envío, aduana y servicios opcionales, mientras el acuerdo de registro menciona una tarifa de plataforma del 8 %. Deben leerse juntas; el checkout vigente controla la compra concreta.", "Separa producto, transporte nacional, cargos de checkout o pago, servicios, embalaje, envío internacional y destino. El USD aproximado de esta web no es precio entregado.", "El estimador sirve para planificar. El tutorial distingue el pago estimado del coste real tras embalar; peso, dimensiones y volumen explican diferencias.", "La página oficial indica cinco días o 120 horas desde almacén, a partir de la siguiente hora completa. Revisa QC y conserva pruebas de inmediato.", "Los 90 días ayudan a consolidar, pero no prolongan la devolución. Usa dos calendarios distintos.", "Las listas oficiales incluyen tabaco, alcohol, contrabando, cuchillos, alimentos y medicinas. Estar en almacén no garantiza que una ruta o país lo admita.", "Las reseñas públicas mezclan experiencias positivas y negativas y no forman una muestra verificada. Úsalas para descubrir preguntas, no como política.", "Antes de cada pago guarda opción, importe, plazo y medición. Si dos textos oficiales difieren, documenta ambos y confirma qué regla aplica al pedido actual."]
    },
    fr: {
      beginner: ["OOPBUY intervient pour Taobao, 1688 et Weidian. Achat national et livraison internationale sont deux étapes de coût; séparez produit, transport local, services, emballage, fret et frais de destination.", "Ouvrez la route actuelle et gardez URL, identifiant, option, taille, couleur et date. La page active prime sur une ancienne capture; les instructions doivent être précises et vérifiables.", "Méthodes et frais de paiement évoluent. Utilisez le paiement en direct, gardez référence et montant et ne répétez pas une opération incertaine sans contrôle.", "Les statuts vendeur, entrepôt et international sont distincts. OOPBUY mentionne contrôle des interdits, pesée, stockage, inspection et photos. Les images prouvent le visible sans garantir authenticité ou durée.", "Comparez couleur, taille, quantité et détails dès l’arrivée. La règle officielle indique cinq jours ou 120 heures après stockage, à partir de l’heure complète suivante.", "L’après-vente demande retour ou échange au vendeur; accord, état, délai et transport influencent le résultat. Les 90 jours de stockage n’étendent pas les 120 heures.", "Utilisez destination, poids emballé et volume réalistes. Poids réel, volumétrique et restrictions peuvent déterminer le tarif; comparez aussi un colis séparé.", "Le tutoriel distingue estimation et coût réel après emballage. Vérifiez adresse, contenu, route et total puis suivez dans ‘My Waybill’."],
      fees: ["La page services cite produit, livraison, douane et options; l’accord d’inscription mentionne aussi 8 % de frais de plateforme. Les deux textes doivent être lus ensemble et le paiement actuel contrôle la transaction.", "Séparez produit, transport local, frais de paiement, services, emballage, international et destination. Le prix USD indicatif n’est pas livré.", "L’estimateur sert à planifier. Le tutoriel distingue montant estimé et coût réel après emballage; poids, dimensions et volume expliquent les écarts.", "La page officielle indique cinq jours ou 120 heures dès le stockage, à compter de l’heure complète suivante. Contrôlez le QC immédiatement.", "Les 90 jours facilitent la consolidation sans prolonger le retour. Suivez deux calendriers.", "Les listes officielles mentionnent tabac, alcool, contrebande, couteaux, aliments et médicaments. Le stockage ne garantit pas l’acceptation par une route ou un pays.", "Les avis publics mêlent expériences positives et négatives sans échantillon contrôlé. Ils révèlent des questions, pas des règles.", "Avant chaque paiement, conservez option, montant, délai et mesure. En cas de conflit officiel, documentez les deux textes et confirmez la règle applicable au dossier actuel."]
    },
    it: {
      beginner: ["OOPBUY opera per mercati come Taobao, 1688 e Weidian. Acquisto nazionale e spedizione internazionale sono due fasi; separa prodotto, trasporto interno, servizi, imballaggio, spedizione e oneri a destinazione.", "Apri il percorso attuale e salva URL, ID, opzione, taglia, colore e data. La pagina live prevale su una vecchia immagine; le istruzioni devono essere precise e verificabili.", "Metodi e costi di pagamento cambiano. Usa il checkout attuale, conserva riferimento e importo e non ripetere un pagamento incerto senza verifica.", "Stato del venditore, magazzino e trasporto internazionale sono distinti. OOPBUY cita controllo dei divieti, pesatura, stoccaggio, ispezione e foto. Le immagini provano il visibile, non autenticità o durata.", "Confronta colore, taglia, quantità e dettagli appena arriva. La regola ufficiale indica cinque giorni o 120 ore dallo stoccaggio, dalla successiva ora completa.", "Il post-vendita chiede reso o cambio al venditore; approvazione, stato, termine e trasporto incidono sul risultato. I 90 giorni non estendono le 120 ore.", "Usa destinazione, peso imballato e volume realistici. Peso reale, volumetrico e restrizioni possono determinare il prezzo; confronta anche la divisione del pacco.", "Il tutorial distingue stima e costo reale dopo l’imballaggio. Controlla indirizzo, contenuto, rotta e totale; poi usa ‘My Waybill’ per il tracking."],
      fees: ["La pagina servizi cita prodotto, spedizione, dogana e opzioni; l’accordo di registrazione menziona anche un costo piattaforma dell’8%. Vanno letti insieme e il checkout corrente controlla la transazione.", "Separa prodotto, trasporto interno, costi di pagamento, servizi, imballaggio, internazionale e destinazione. Il prezzo USD indicativo non è consegnato.", "Lo stimatore serve alla pianificazione. Il tutorial distingue importo stimato e costo reale dopo l’imballaggio; peso, dimensioni e volume spiegano gli scostamenti.", "La pagina ufficiale indica cinque giorni o 120 ore dallo stoccaggio, dalla successiva ora completa. Controlla subito il QC.", "I 90 giorni aiutano il consolidamento ma non estendono il reso. Usa due calendari.", "Gli elenchi ufficiali citano tabacco, alcol, contrabbando, coltelli, alimenti e medicine. Lo stoccaggio non garantisce accettazione da rotta o paese.", "Le recensioni pubbliche uniscono esperienze positive e negative senza campione controllato. Servono a trovare domande, non regole.", "Prima di ogni pagamento conserva opzione, importo, termine e misura. Se due testi ufficiali differiscono, documentali e conferma la regola per l’ordine attuale."]
    }
  };
  return { slug: source.slug, title: selected[0], deck: selected[1], readTime: locale === "de" ? "11 Min." : "11 min", sections: selected[2].map((heading, index) => ({ heading, paragraphs: [summaries[locale][kind][index], ...splitArticleExpansion(localizedArticleExpansions[locale][source.slug][index])] })), sources: [...officialSources[kind]] };
}

export const researchedArticles: Record<Locale, Article[]> = {
  en: [beginnerEnglish, feesEnglish, qvlC01Articles.en],
  de: [localizedArticle("de", "beginner"), localizedArticle("de", "fees"), qvlC01Articles.de],
  es: [localizedArticle("es", "beginner"), localizedArticle("es", "fees"), qvlC01Articles.es],
  fr: [localizedArticle("fr", "beginner"), localizedArticle("fr", "fees"), qvlC01Articles.fr],
  it: [localizedArticle("it", "beginner"), localizedArticle("it", "fees"), qvlC01Articles.it],
};
