import type { Locale, Section } from "@/lib/site";

export type DepthSection = Exclude<Section, "faq">;
export type SectionDepthBlock = { title: string; text: string };

export const sectionDepth: Record<Locale, Record<DepthSection, SectionDepthBlock[]>> = {
  en: {
    spreadsheet: [
      { title: "Read each row as an evidence record", text: "A spreadsheet row should preserve the route you opened, the product ID, the option you meant to order, the date checked and the visual details that will matter later. Those fields turn a product card into a reference rather than a promise. Record color wording, size method, quantity and any defining part before checkout. When warehouse photos arrive, compare them with this saved record instead of relying on memory or a thumbnail that may have changed. A useful row makes the handoff from discovery to visual inspection traceable." },
      { title: "Separate a live match from an unresolved claim", text: "Open the destination page and confirm that its current title, first image and selectable options still correspond to the row. A working link alone is not enough if the listing now describes another version. Mark material, authenticity, real-world fit and hidden function as unverified unless current evidence directly supports them. The aim is not to collect the largest number of links; it is to keep a smaller index in which known facts, estimates and unknowns are visibly different. That separation reduces false confidence when the item reaches the warehouse." },
      { title: "Maintain the sheet after warehouse evidence arrives", text: "A row remains useful after ordering only if it can absorb new evidence. Add the stock-in date, visible QC outcome, confirmed label or measurement, and a short decision note. Remove or flag routes that disappear, change item identity or no longer offer the recorded option. Recheck a sample on a regular schedule and date every review. Do not turn one successful unit into a permanent seller rating: batches, options and pages can change. Maintenance should improve the evidence trail while leaving the original order reference intact for later comparison." },
      { title: "Add confidence, not a decorative score", text: "Label each important field as confirmed, estimated or still unknown. A current product ID may be confirmed while weight remains seller-stated and color remains uncertain until warehouse lighting can be compared. Explain what would upgrade the confidence level. This small discipline prevents a neat spreadsheet from making weak data look equally reliable and gives the later QC reviewer a ready-made list of the facts that still need visual support." },
    ],
    finds: [
      { title: "Shortlist by the evidence you will need", text: "A find is worth opening when it fits a defined category, use, option and risk tolerance. Before choosing on appearance, write the visual questions the warehouse record must answer: correct size label, matching color, expected number of pieces, compatible model marker, or an undamaged structural part. This changes the shortlist from a gallery into a preparation step. Two visually similar products may require different checks because one has several variants, a rigid shape or an option that cannot be distinguished from the main image." },
      { title: "Compare like with like before ranking options", text: "Use the same evidence fields for every candidate in a category. For footwear, compare option, size method, pair symmetry and the parts visible from equivalent angles. For apparel, keep the chosen size, seller measurement method, print placement and customization details together. For bags or accessories, note dimensions, included parts and closures. A candidate with a slightly higher product price may carry less identity uncertainty; a cheap route with unclear options may require more follow-up. Keep those tradeoffs visible instead of hiding them behind one score." },
      { title: "Use a stop rule, not endless browsing", text: "Stop adding candidates when a small group satisfies the brief and each route has enough current information to be checked. Exclude a find when its page no longer matches, the required option is absent, a decisive specification cannot be identified, or the remaining uncertainty is unacceptable for the item. Record why a route was kept or dropped. A dated reason is more useful than a vague badge because another reader can repeat the check. This site curates starting points; availability, options and transaction details still belong to the current destination page." },
      { title: "Date every image-led comparison", text: "A thumbnail is only a snapshot of what the editor saw. Keep the review date beside the route and reopen the destination before acting. If the first image, option set or identifying text has changed, do not silently reuse the old conclusion. Record the change and restart the identity check. This protects the shortlist from appearing current merely because its cards still load and keeps later warehouse comparisons anchored to the version that was actually selected." },
    ],
    guide: [
      { title: "Build one evidence trail across every handoff", text: "Keep the listing route, exact option, payment reference, warehouse record and parcel record connected. Each handoff answers a different question: the listing describes what was offered, the order records what was selected, and QC photos show only the received item from available angles. None can substitute for the others. Use stable identifiers and dates so that a changed product page does not erase the comparison. When a mismatch appears, describe the precise difference between two records rather than making a general claim about quality." },
      { title: "Review warehouse evidence while the decision is actionable", text: "OOPBUY’s current help material checked on 1 September 2026 describes inspection and photos after warehouse arrival and a five-day or 120-hour standard return window. Verify the live rule and order status again when acting because policy and eligibility may change. Review identity first, then visible condition, measurements and included parts. If a missing angle could change the decision, state the exact view or measurement needed. Do not wait until parcel submission to discover that the useful after-sales period has passed." },
      { title: "Close the loop with a dated decision record", text: "Finish each item with a concise state such as accepted, held for missing evidence, or escalated through the current order flow. Include the date, the feature examined and the evidence that supports the choice. Later, connect the packed parcel and delivered outcome to that item record. This does not convert one order into a universal review; it creates a local audit trail that improves the next comparison. Keep uncertainty explicit, especially for authenticity, material, internal electronics, durability and fit, which ordinary warehouse images cannot prove." },
    ],
    qc: [
      { title: "Use an evidence ladder before making a claim", text: "Start with what is directly visible: a label, quantity, printed marker, measurement endpoints, surface condition or the relationship between two parts. Then record what the image suggests but does not confirm, such as apparent color under uncertain lighting. Keep non-visual claims outside the conclusion. Material composition, authenticity, smell, internal construction, waterproofing, electronic function and real-world fit require other evidence. This ladder prevents a plausible impression from being written as a fact and makes the remaining gap clear to the reader." },
      { title: "Map angles, scale and image limits", text: "List the available views before judging the product. Check whether front, back, sides, labels, included parts and any critical measurement are actually shown. Perspective can exaggerate an edge, wide-angle distortion can change symmetry, compression can hide fine marks and automatic white balance can shift color. Compare equivalent angles and look for a concern in more than one frame. When scale matters, confirm where a ruler begins and ends. A measurement photo without defined reference points can look precise while answering the wrong question." },
      { title: "Choose accept, hold or escalate from confidence", text: "Accept only when the visible evidence matches the ordered identity and the unresolved gaps are tolerable for that item. Hold when a decisive view, label, quantity or measurement is absent. Escalate through the current platform flow when the available record shows an objective mismatch or damage and the order remains eligible. State the observation, not an accusation. The decision should identify which fact changed the outcome and which limitations remain. This creates a repeatable visual-inspection method without pretending that QC photos are a product certification." },
      { title: "Write a one-sentence confidence note", text: "End the review with one sentence that names the strongest visible match, the most important remaining gap and the resulting action. For example, identity may be supported by model and size labels while color remains uncertain under warehouse lighting. A concise confidence note makes the decision auditable without hiding limitations behind a pass badge. It also gives a future reviewer the exact reason to reopen the evidence instead of repeating the entire inspection." },
    ],
    shipping: [
      { title: "Let visible condition guide packing priorities", text: "Warehouse evidence can identify the parts that need protection before a parcel is submitted. A rigid edge, delicate print, structured toe box, exposed clasp or fragile accessory may justify a specific packing choice. Describe the risk that the protection is meant to address instead of adding every service automatically. Photos cannot predict every transit event, but they can show which visible features would be vulnerable to compression, abrasion or loose movement. Keep the original condition record so the delivered result can be compared with the pre-shipment state." },
      { title: "Distinguish product damage from packaging damage", text: "Review the product and its outer packaging as separate layers. A dented retail box does not automatically prove that the item inside is damaged, while an intact outer box does not rule out a visible product defect already present at the warehouse. Note chips, cracks, scuffs, crushed corners and missing protective pieces with their location and angle. When deciding whether to retain, remove or reinforce packaging, balance visible fragility, presentation value and parcel volume without claiming a guaranteed shipping outcome." },
      { title: "Preserve a before-and-after parcel record", text: "Before shipping, save the accepted QC views, included-parts count, packaging request, measured parcel information and date. After delivery, compare condition using the same parts and angles when possible. Record what changed and avoid attributing cause when the evidence cannot distinguish seller condition, warehouse handling, international transit or local delivery. This record supports better future packing decisions and clearer problem descriptions. It also keeps the site’s shipping material focused on visible evidence rather than competing for broad rate or route keywords owned by other OOPBUY resources." },
      { title: "Keep packing evidence separate from a price estimate", text: "This page does not turn a visible risk into a guaranteed rate, route or insurance result. Record protection choices and parcel measurements here, then use the current transaction screen for availability and price. Separating those records lets the visual argument stay stable even when carrier options change. It also reveals whether a later cost difference came from packaging, measured dimensions or a route update rather than from the condition assessment itself." },
    ],
    articles: [
      { title: "Use the library as a visual-evidence curriculum", text: "Begin with the general QC framework, then move to the guide that matches the object or evidence gap in front of you. The core sequence is consistent: preserve the ordered reference, map the available images, separate observation from inference, identify what is missing and make a confidence-based decision. Spreadsheet, workflow and packing articles remain available as supporting context, but this site’s primary editorial role is OOPBUY QC photo analysis and visual literacy after warehouse images already exist." },
      { title: "Check sources, dates and the limit of each claim", text: "Platform policies and service screens can change, so every article states a review date and links to the official material used for variable facts. A source can support that a workflow or window was published; it cannot prove a particular seller item, photograph or future outcome. Editorial explanations should label official statements, direct visual observations and uncertainty separately. When an older article conflicts with the current platform page, the current official source and live account flow control the practical decision." },
      { title: "Choose the article that matches the decision", text: "Use the QC photo framework for visible identity and condition, the spreadsheet workflow for preserving a reference trail, the deadline article for keeping the evidence review actionable, and the packing article for translating visible risk into protection choices. Do not use a broad guide as a substitute for a missing measurement, unshown component or current policy check. Each article is designed to answer one decision with evidence; the planned QVL series will add narrower guides without repeating broad spreadsheet, fee, route or after-sales topics assigned to sibling resources." },
    ],
  },
  de: {
    spreadsheet: [
      { title: "Jede Zeile als Belegdatensatz lesen", text: "Eine Tabellenzeile sollte die geöffnete Route, die Produkt-ID, die beabsichtigte Variante, das Prüfdatum und die später wichtigen sichtbaren Merkmale festhalten. So wird aus einer Produktkarte eine Referenz und kein Versprechen. Notiere vor dem Bezahlen Farbbezeichnung, Größenmethode, Stückzahl und kennzeichnende Teile. Wenn Lagerfotos erscheinen, vergleichst du sie mit diesem gespeicherten Stand statt mit dem Gedächtnis oder einem inzwischen geänderten Vorschaubild. Eine gute Zeile macht den Übergang von der Entdeckung zur visuellen Prüfung nachvollziehbar." },
      { title: "Live-Treffer und offene Behauptung trennen", text: "Öffne die Zielseite und bestätige, dass aktueller Titel, erstes Bild und auswählbare Optionen noch zur Zeile passen. Ein funktionierender Link genügt nicht, wenn die Seite inzwischen eine andere Version beschreibt. Material, Echtheit, reale Passform und verborgene Funktion bleiben ungeklärt, solange aktuelle Belege sie nicht direkt stützen. Ziel ist kein möglichst großer Linkbestand, sondern ein kleinerer Index, in dem Fakten, Schätzungen und Unbekanntes klar getrennt sind. Das vermindert falsche Sicherheit beim Lagereingang." },
      { title: "Die Tabelle mit Lagerbelegen pflegen", text: "Nach der Bestellung bleibt eine Zeile nur nützlich, wenn neue Belege ergänzt werden. Trage Einlagerungsdatum, sichtbares QC-Ergebnis, bestätigtes Etikett oder Maß und eine kurze Entscheidung ein. Markiere Routen, die verschwinden, die Produktidentität wechseln oder die notierte Option nicht mehr anbieten. Prüfe regelmäßig eine Stichprobe und datiere jede Kontrolle. Ein erfolgreiches Einzelstück ist keine dauerhafte Verkäuferbewertung: Chargen, Varianten und Seiten ändern sich. Die Pflege soll die Belegspur verbessern und die ursprüngliche Bestellreferenz für spätere Vergleiche erhalten." },
      { title: "Belegsicherheit statt dekorativer Punktzahl", text: "Kennzeichne wichtige Felder als bestätigt, geschätzt oder weiterhin unbekannt. Eine aktuelle Produkt-ID kann bestätigt sein, während das Gewicht nur vom Verkäufer stammt und die Farbe bis zum Vergleich unter Lagerlicht offen bleibt. Notiere, welcher Beleg die Sicherheit erhöhen würde. Damit wirken schwache Daten in einer ordentlichen Tabelle nicht so zuverlässig wie direkte Beobachtungen, und die spätere QC-Prüfung erhält automatisch eine Liste der noch offenen visuellen Fragen." },
    ],
    finds: [
      { title: "Nach dem benötigten Beleg auswählen", text: "Ein Fund lohnt sich, wenn er zu Kategorie, Zweck, Variante und Risikogrenze passt. Schreibe vor der optischen Auswahl auf, welche Fragen die Lagerbilder beantworten müssen: korrektes Größenetikett, passende Farbe, richtige Stückzahl, Modellkennung oder unbeschädigtes Strukturteil. Damit wird die Auswahl zu einer Vorbereitung statt zu einer Galerie. Zwei ähnlich aussehende Produkte können unterschiedliche Prüfungen erfordern, etwa wegen zahlreicher Varianten, starrer Form oder einer Option, die im Hauptbild nicht unterscheidbar ist." },
      { title: "Gleiches mit Gleichem vergleichen", text: "Nutze innerhalb einer Kategorie dieselben Belegfelder. Bei Schuhen vergleichst du Variante, Größenmethode, Paarsymmetrie und entsprechende Blickwinkel. Bei Kleidung gehören gewählte Größe, Messmethode, Druckposition und Personalisierung zusammen. Bei Taschen oder Zubehör notierst du Maße, enthaltene Teile und Verschlüsse. Ein etwas teureres Produkt kann weniger Identitätsrisiko haben; eine billige Route mit unklarer Auswahl kann mehr Nacharbeit verlangen. Diese Unterschiede bleiben sichtbar, statt in einer einzigen Punktzahl zu verschwinden." },
      { title: "Mit einer Stoppregel arbeiten", text: "Füge keine weiteren Kandidaten hinzu, sobald eine kleine Gruppe den Bedarf erfüllt und jede Route genügend aktuelle Informationen für eine Prüfung besitzt. Schließe einen Fund aus, wenn die Seite nicht mehr passt, die benötigte Option fehlt, ein entscheidendes Merkmal nicht identifizierbar ist oder die Unsicherheit für den Artikel zu groß bleibt. Dokumentiere den Grund für Behalten oder Entfernen. Eine datierte Begründung lässt sich wiederholen und ist wertvoller als ein unscharfes Badge. Verfügbarkeit, Optionen und Kaufdetails werden weiterhin auf der aktuellen Zielseite bestätigt." },
      { title: "Jeden bildbasierten Vergleich datieren", text: "Ein Vorschaubild ist nur der Stand, den die Redaktion gesehen hat. Speichere das Prüfdatum und öffne die Zielseite vor einer Handlung erneut. Haben sich erstes Bild, Optionen oder Identitätstext geändert, darf das alte Ergebnis nicht still weiterverwendet werden. Dokumentiere die Änderung und beginne die Identitätsprüfung neu. So wirkt eine Karte nicht allein deshalb aktuell, weil sie noch lädt, und der spätere Lagervergleich bleibt an der tatsächlich gewählten Version verankert." },
    ],
    guide: [
      { title: "Eine Belegspur über alle Übergaben führen", text: "Verbinde Produktseite, genaue Variante, Zahlungsreferenz, Lagerdatensatz und Paketdatensatz. Jede Übergabe beantwortet eine andere Frage: Das Angebot beschreibt das Versprochene, die Bestellung das Gewählte und QC-Fotos nur den erhaltenen Artikel aus vorhandenen Winkeln. Keiner dieser Belege ersetzt die anderen. Nutze stabile IDs und Daten, damit eine veränderte Produktseite den Vergleich nicht löscht. Bei einer Abweichung beschreibst du den präzisen Unterschied zwischen zwei Datensätzen statt eines allgemeinen Qualitätsurteils." },
      { title: "Lagerbelege rechtzeitig prüfen", text: "Die am 1. September 2026 geprüften OOPBUY-Hinweise beschreiben Kontrolle und Fotos nach Lagereingang sowie ein übliches Fenster von fünf Tagen beziehungsweise 120 Stunden. Prüfe beim Handeln die aktuelle Regel und den Bestellstatus erneut, weil Richtlinie und Berechtigung sich ändern können. Zuerst Identität, danach sichtbaren Zustand, Maße und enthaltene Teile kontrollieren. Fehlt ein entscheidender Winkel, benenne genau die benötigte Ansicht oder Messung. Warte nicht bis zur Paketeinreichung, wenn der nutzbare Aftersales-Zeitraum dann abgelaufen sein kann." },
      { title: "Die Entscheidung datiert abschließen", text: "Beende jeden Artikel mit einem klaren Zustand: akzeptiert, wegen fehlendem Beleg gehalten oder über den aktuellen Bestellweg eskaliert. Ergänze Datum, geprüftes Merkmal und tragenden Beleg. Verbinde später gepacktes Paket und Lieferergebnis mit diesem Datensatz. Eine Bestellung wird dadurch nicht zur allgemeinen Bewertung, aber zu einer lokalen Prüfspur, die den nächsten Vergleich verbessert. Unsicherheit bleibt ausdrücklich sichtbar, vor allem bei Echtheit, Material, interner Elektronik, Haltbarkeit und Passform, die normale Lagerbilder nicht beweisen." },
    ],
    qc: [
      { title: "Vor jeder Aussage eine Belegleiter nutzen", text: "Beginne mit direkt Sichtbarem: Etikett, Stückzahl, Druckkennung, Messpunkte, Oberfläche oder Verhältnis zweier Bauteile. Danach notierst du, was das Bild nur nahelegt, etwa eine scheinbare Farbe bei unsicherem Licht. Nicht visuelle Behauptungen gehören nicht in die Schlussfolgerung. Material, Echtheit, Geruch, innere Konstruktion, Wasserdichtigkeit, elektronische Funktion und reale Passform benötigen andere Belege. Die Leiter verhindert, dass ein plausibler Eindruck als Tatsache erscheint, und zeigt die verbleibende Lücke deutlich." },
      { title: "Winkel, Maßstab und Bildgrenzen kartieren", text: "Liste vor dem Urteil die verfügbaren Ansichten. Sind Vorderseite, Rückseite, Seiten, Etiketten, Zubehör und wichtige Maße wirklich sichtbar? Perspektive kann Kanten übertreiben, Weitwinkel Symmetrie verändern, Kompression feine Spuren verbergen und Weißabgleich Farben verschieben. Vergleiche entsprechende Winkel und suche ein Problem in mehr als einem Bild. Bei Maßen muss klar sein, wo ein Lineal beginnt und endet. Ein Messfoto ohne definierte Referenzpunkte kann präzise aussehen und dennoch die falsche Frage beantworten." },
      { title: "Akzeptieren, halten oder eskalieren", text: "Akzeptiere nur, wenn die sichtbaren Belege zur bestellten Identität passen und offene Lücken für diesen Artikel tragbar sind. Halte, wenn eine entscheidende Ansicht, Kennzeichnung, Stückzahl oder Messung fehlt. Eskaliere über den aktuellen Plattformweg, wenn der Datensatz eine objektive Abweichung oder Beschädigung zeigt und die Bestellung noch berechtigt ist. Formuliere die Beobachtung statt eines Vorwurfs. Die Entscheidung benennt, welcher Beleg das Ergebnis verändert hat und welche Grenzen bleiben. So entsteht eine wiederholbare visuelle Prüfung ohne vorgetäuschte Zertifizierung." },
      { title: "Einen Satz zur Belegsicherheit schreiben", text: "Beende die Prüfung mit einem Satz, der stärkste Übereinstimmung, wichtigste Lücke und Handlung nennt. Modell- und Größenetikett können etwa die Identität stützen, während die Farbe unter Lagerlicht offen bleibt. Eine solche Notiz macht die Entscheidung prüfbar, ohne Grenzen hinter einem Bestanden-Badge zu verstecken. Spätere Prüfer sehen sofort, warum der Datensatz erneut geöffnet werden sollte, und müssen nicht die gesamte Kontrolle wiederholen." },
    ],
    shipping: [
      { title: "Sichtbaren Zustand in Verpackungsprioritäten übersetzen", text: "Lagerbilder zeigen, welche Teile vor der Paketeinreichung Schutz benötigen können. Starre Kanten, empfindliche Drucke, strukturierte Zehenboxen, offene Verschlüsse oder zerbrechliches Zubehör rechtfertigen eventuell eine konkrete Maßnahme. Beschreibe das Risiko, das der Schutz abdecken soll, statt jeden Service automatisch zu wählen. Fotos sagen nicht jedes Transportereignis voraus, können aber sichtbare Druck-, Reibungs- oder Bewegungsrisiken markieren. Bewahre den Ausgangszustand auf, damit das Lieferergebnis später vergleichbar bleibt." },
      { title: "Produkt- und Verpackungsschaden trennen", text: "Prüfe Produkt und Außenverpackung als getrennte Ebenen. Ein eingedrückter Verkaufskarton beweist nicht automatisch einen Produktschaden; ein intakter Karton schließt einen bereits im Lager sichtbaren Fehler nicht aus. Notiere Abplatzer, Risse, Scheuerstellen, gequetschte Ecken und fehlende Schutzteile mit Ort und Blickwinkel. Beim Behalten, Entfernen oder Verstärken der Verpackung werden sichtbare Empfindlichkeit, Präsentationswert und Paketvolumen abgewogen, ohne ein bestimmtes Transportergebnis zu versprechen." },
      { title: "Vorher-Nachher-Datensatz erhalten", text: "Speichere vor Versand akzeptierte QC-Ansichten, Stückzahl der Teile, Verpackungswunsch, gemessene Paketdaten und Datum. Vergleiche nach Lieferung möglichst dieselben Stellen und Winkel. Dokumentiere Veränderungen, ohne eine Ursache zu behaupten, wenn die Belege Verkäuferzustand, Lagerhandling, internationalen Transport und lokale Zustellung nicht unterscheiden. Dieser Datensatz verbessert spätere Verpackungsentscheidungen und Problembeschreibungen. Gleichzeitig bleibt der Versandinhalt dieser Seite auf sichtbare Belege begrenzt und konkurriert nicht um breite Preis- oder Routenbegriffe anderer OOPBUY-Ressourcen." },
      { title: "Verpackungsbeleg und Preisschätzung trennen", text: "Ein sichtbares Risiko wird hier nicht in einen garantierten Tarif, eine Route oder Versicherungsleistung umgerechnet. Speichere Schutzentscheidung und Paketmaße, prüfe Verfügbarkeit und Preis aber im aktuellen Transaktionsfenster. Getrennte Datensätze halten die visuelle Begründung stabil, wenn sich Dienste ändern. Später wird außerdem sichtbar, ob eine Kostendifferenz aus Verpackung, gemessenen Dimensionen oder einem Routenupdate und nicht aus der Zustandsbewertung stammt." },
    ],
    articles: [
      { title: "Die Bibliothek als visuelles Lernprogramm nutzen", text: "Beginne mit dem allgemeinen QC-Rahmen und wechsle danach zum Guide für das konkrete Objekt oder die vorhandene Beleglücke. Die Reihenfolge bleibt: bestellte Referenz sichern, Bilder kartieren, Beobachtung und Schluss trennen, Fehlendes benennen und nach Belegsicherheit entscheiden. Tabellen-, Ablauf- und Verpackungsartikel bleiben unterstützend verfügbar; die redaktionelle Hauptrolle dieser Website ist jedoch die Analyse von OOPBUY-QC-Fotos, nachdem Lagerbilder bereits vorliegen." },
      { title: "Quellen, Daten und Aussagegrenzen prüfen", text: "Plattformrichtlinien und Oberflächen können sich ändern. Deshalb nennt jeder Artikel ein Prüfdatum und verlinkt die offiziellen Quellen für variable Fakten. Eine Quelle kann zeigen, dass ein Ablauf oder Zeitraum veröffentlicht war; sie beweist kein bestimmtes Verkäuferprodukt, Foto oder künftiges Ergebnis. Offizielle Angaben, direkte Bildbeobachtung und Unsicherheit müssen getrennt bleiben. Widerspricht ein älterer Beitrag der aktuellen Plattformseite, steuern aktuelle offizielle Quelle und Live-Kontoablauf die praktische Entscheidung." },
      { title: "Den Guide passend zur Entscheidung wählen", text: "Nutze den QC-Fotorahmen für sichtbare Identität und Zustand, den Tabellenablauf für eine erhaltene Referenzspur, den Fristenbeitrag für eine rechtzeitige Prüfung und den Verpackungsartikel für den Übergang von sichtbarem Risiko zu Schutzoptionen. Ein breiter Guide ersetzt kein fehlendes Maß, unsichtbares Teil oder aktuelle Richtlinienprüfung. Jeder Beitrag beantwortet eine Entscheidung mit Belegen; die geplante QVL-Reihe ergänzt schmalere Themen, ohne breite Tabellen-, Gebühren-, Routen- oder Aftersales-Suchabsichten anderer Ressourcen zu wiederholen." },
    ],
  },
  es: {
    spreadsheet: [
      { title: "Lee cada fila como un registro de evidencia", text: "Una fila debe conservar la ruta abierta, el ID del producto, la variante que se pretendía pedir, la fecha de comprobación y los detalles visibles que importarán después. Así la tarjeta se convierte en referencia, no en promesa. Anota color, método de talla, cantidad y cualquier pieza distintiva antes del pago. Cuando aparezcan las fotos del almacén, compáralas con ese registro y no con la memoria o una miniatura que pudo cambiar. Una buena fila hace trazable el paso del descubrimiento a la inspección visual." },
      { title: "Separa la coincidencia actual de una afirmación pendiente", text: "Abre la página de destino y confirma que su título, primera imagen y opciones seleccionables todavía corresponden a la fila. Un enlace activo no basta si ahora describe otra versión. Material, autenticidad, ajuste real y función oculta siguen sin verificar salvo que exista evidencia directa y vigente. El objetivo no es reunir la mayor cantidad de enlaces, sino mantener un índice menor donde hechos, estimaciones e incógnitas sean distintos. Esa separación reduce la falsa seguridad cuando el artículo entra en el almacén." },
      { title: "Mantén la hoja con la evidencia del almacén", text: "Una fila solo sigue siendo útil después del pedido si admite nueva evidencia. Añade fecha de entrada, resultado QC visible, etiqueta o medida confirmada y una nota breve de decisión. Marca las rutas que desaparecen, cambian la identidad del artículo o pierden la opción guardada. Revisa periódicamente una muestra y fecha cada control. Una unidad correcta no crea una valoración permanente del vendedor: lotes, variantes y páginas cambian. El mantenimiento debe mejorar el rastro sin borrar la referencia original del pedido." },
      { title: "Añade confianza, no una puntuación decorativa", text: "Etiqueta cada campo importante como confirmado, estimado o desconocido. Un ID actual puede estar confirmado mientras el peso sigue declarado por el vendedor y el color queda pendiente de la luz del almacén. Explica qué evidencia elevaría la confianza. Esta disciplina evita que una hoja ordenada haga parecer iguales datos débiles y observaciones directas, y entrega al revisor QC una lista preparada de preguntas visuales pendientes." },
    ],
    finds: [
      { title: "Selecciona según la evidencia que necesitarás", text: "Un hallazgo merece abrirse si encaja con categoría, uso, variante y tolerancia al riesgo. Antes de elegir por aspecto, escribe qué preguntas deben responder las fotos: etiqueta de talla, color, número de piezas, marcador de modelo o parte estructural sin daño. La lista corta se convierte así en preparación, no en galería. Dos productos muy parecidos pueden exigir controles distintos porque uno tiene muchas variantes, una forma rígida o una opción imposible de distinguir en la imagen principal." },
      { title: "Compara con los mismos campos", text: "Usa las mismas evidencias para cada candidato de una categoría. En calzado, compara variante, método de talla, simetría del par y partes vistas desde ángulos equivalentes. En ropa, reúne talla elegida, método de medición, posición del estampado y personalización. En bolsos o accesorios, anota dimensiones, piezas incluidas y cierres. Un candidato algo más caro puede tener menos incertidumbre de identidad; una ruta barata con opciones confusas puede requerir más trabajo. Mantén visibles esos intercambios en vez de esconderlos en una puntuación." },
      { title: "Aplica una regla de parada", text: "Deja de añadir candidatos cuando un grupo pequeño cumple el encargo y cada ruta posee información actual suficiente para revisarse. Excluye un hallazgo si la página ya no coincide, falta la opción necesaria, no se puede identificar una especificación decisiva o la incertidumbre no resulta aceptable. Registra por qué se conserva o descarta. Una razón fechada puede repetirse y vale más que una insignia vaga. Este sitio ofrece puntos de partida; disponibilidad, variantes y detalles de compra deben confirmarse en el destino actual." },
      { title: "Fecha cada comparación basada en imágenes", text: "Una miniatura solo representa lo que vio el editor. Guarda la fecha y reabre el destino antes de actuar. Si cambian primera imagen, opciones o texto de identidad, no reutilices en silencio la conclusión anterior. Registra el cambio y reinicia la comprobación. Así una tarjeta no parece actual solo porque todavía carga y la comparación del almacén queda vinculada a la versión que realmente se seleccionó." },
    ],
    guide: [
      { title: "Construye un único rastro entre traspasos", text: "Mantén unidos anuncio, opción exacta, referencia de pago, registro del almacén y registro del paquete. Cada etapa responde a otra pregunta: el anuncio describe la oferta, el pedido lo elegido y las fotos solo muestran el artículo recibido desde los ángulos disponibles. Ninguna sustituye a las demás. Usa identificadores y fechas para que una página modificada no borre la comparación. Si aparece una diferencia, describe el contraste preciso entre dos registros y evita una acusación general de calidad." },
      { title: "Revisa mientras la decisión sigue abierta", text: "La ayuda de OOPBUY comprobada el 1 de septiembre de 2026 describe inspección y fotos tras la entrada y una ventana normal de cinco días o 120 horas. Verifica de nuevo la regla y el estado al actuar, porque pueden cambiar política y elegibilidad. Revisa primero identidad, después estado visible, medidas y piezas. Si falta un ángulo decisivo, especifica la vista o medición necesaria. No esperes al envío del paquete para descubrir que el periodo útil ya terminó." },
      { title: "Cierra con una decisión fechada", text: "Termina cada artículo con un estado conciso: aceptado, retenido por falta de evidencia o escalado por el flujo vigente. Añade fecha, rasgo examinado y prueba que sostiene la elección. Después conecta paquete y resultado de entrega. Una compra no se convierte en reseña universal, pero sí en un rastro local que mejora la siguiente comparación. Mantén explícitas las dudas sobre autenticidad, material, electrónica interna, durabilidad y ajuste, que las imágenes ordinarias de almacén no pueden demostrar." },
    ],
    qc: [
      { title: "Usa una escala de evidencia antes de afirmar", text: "Empieza por lo directamente visible: etiqueta, cantidad, marcador impreso, extremos de una medida, superficie o relación entre piezas. Después anota lo que la imagen sugiere sin confirmar, como el color aparente con luz incierta. Las afirmaciones no visuales quedan fuera de la conclusión. Material, autenticidad, olor, construcción interior, impermeabilidad, función electrónica y ajuste real exigen otras pruebas. Esta escala evita transformar una impresión plausible en hecho y deja clara la laguna restante." },
      { title: "Mapea ángulos, escala y límites", text: "Enumera las vistas antes de juzgar. Comprueba si se muestran frente, reverso, laterales, etiquetas, componentes y medidas críticas. La perspectiva exagera bordes, el gran angular altera simetría, la compresión oculta marcas y el balance de blancos cambia colores. Compara ángulos equivalentes y busca la preocupación en más de un fotograma. Cuando importe la escala, confirma dónde empieza y termina la regla. Una foto de medición sin puntos de referencia definidos puede parecer exacta y responder a otra pregunta." },
      { title: "Decide aceptar, retener o escalar", text: "Acepta solo cuando la evidencia coincide con la identidad pedida y las lagunas son tolerables para ese artículo. Retén si falta una vista, etiqueta, cantidad o medida decisiva. Escala por el flujo vigente cuando el registro muestre una diferencia o daño objetivo y el pedido siga siendo elegible. Expresa la observación, no una acusación. La decisión debe señalar qué hecho cambió el resultado y qué limitaciones siguen abiertas. Así se crea una inspección visual repetible sin fingir que las fotos son una certificación." },
      { title: "Escribe una nota de confianza", text: "Cierra la revisión con una frase que nombre la coincidencia más fuerte, la laguna principal y la acción. Modelo y talla pueden sostener la identidad mientras el color sigue dudoso bajo la luz del almacén. La nota hace auditable la decisión sin esconder límites tras un aprobado. También permite que otro revisor sepa exactamente por qué debe volver a abrir la evidencia sin repetir toda la inspección." },
    ],
    shipping: [
      { title: "Convierte el estado visible en prioridad de embalaje", text: "La evidencia del almacén permite identificar las partes que pueden necesitar protección: borde rígido, impresión delicada, puntera estructurada, cierre expuesto o accesorio frágil. Describe el riesgo que pretende cubrir la protección en vez de añadir todos los servicios. Las fotos no predicen cada incidente, pero muestran qué elementos son vulnerables a compresión, roce o movimiento. Conserva el registro de estado inicial para comparar el resultado entregado con la situación anterior al envío." },
      { title: "Distingue producto y embalaje", text: "Examina el producto y su caja como capas distintas. Una caja comercial abollada no demuestra por sí sola daño interior, y una caja intacta no descarta un defecto ya visible en el almacén. Anota grietas, roces, golpes, esquinas aplastadas y protección ausente con ubicación y ángulo. Al conservar, retirar o reforzar embalaje, equilibra fragilidad visible, valor de presentación y volumen del paquete sin prometer un resultado de transporte." },
      { title: "Guarda un antes y un después", text: "Antes de enviar, conserva vistas QC aceptadas, cantidad de piezas, petición de embalaje, datos medidos y fecha. Después compara las mismas zonas y ángulos cuando sea posible. Registra cambios sin atribuir causa si las pruebas no distinguen vendedor, almacén, transporte internacional o reparto local. El historial mejora decisiones de protección y descripciones de incidencias. También mantiene esta página centrada en evidencia visible, sin competir por palabras generales de tarifas o rutas asignadas a otros recursos OOPBUY." },
      { title: "Separa evidencia de embalaje y precio", text: "Un riesgo visible no se convierte aquí en tarifa, ruta o seguro garantizados. Guarda protección y medidas, pero consulta disponibilidad y precio en la transacción actual. Los registros separados mantienen estable el argumento visual cuando cambian los servicios. Después también muestran si una diferencia de coste procedió del embalaje, de las dimensiones medidas o de una actualización de ruta y no de la evaluación del estado." },
    ],
    articles: [
      { title: "Usa la biblioteca como recorrido de alfabetización visual", text: "Empieza por el marco QC general y continúa con la guía del objeto o laguna concreta. La secuencia se mantiene: guardar la referencia, mapear imágenes, separar observación e inferencia, identificar lo ausente y decidir por confianza. Los artículos de hoja, proceso y embalaje siguen como contexto, pero la función editorial principal de este sitio es analizar fotos QC de OOPBUY cuando las imágenes de almacén ya existen." },
      { title: "Comprueba fuentes, fechas y límites", text: "Las políticas y pantallas pueden cambiar; cada artículo muestra fecha de revisión y enlaza el material oficial usado para hechos variables. Una fuente respalda que se publicó un proceso o plazo, no un producto, una foto o un resultado futuro concretos. Separa siempre afirmación oficial, observación visual y duda. Si un artículo antiguo contradice la página actual, la fuente oficial vigente y el flujo de la cuenta controlan la decisión práctica." },
      { title: "Elige la guía según la decisión", text: "Usa el marco QC para identidad y estado visibles, el flujo de hoja para conservar referencias, el artículo de plazos para mantener abierta la revisión y el de embalaje para traducir riesgo visual en protección. Una guía amplia no sustituye una medida ausente, una pieza no mostrada ni una norma actual. Cada texto responde a una decisión con evidencia; la serie QVL añadirá temas estrechos sin repetir búsquedas generales de hojas, tarifas, rutas o posventa de otros recursos." },
    ],
  },
  fr: {
    spreadsheet: [
      { title: "Lire chaque ligne comme un dossier de preuve", text: "Une ligne doit conserver la route ouverte, l’identifiant produit, l’option prévue, la date du contrôle et les détails visuels utiles plus tard. La carte devient ainsi une référence, pas une promesse. Notez couleur, méthode de taille, quantité et pièce distinctive avant paiement. Lorsque les photos d’entrepôt arrivent, comparez-les à ce dossier plutôt qu’à votre mémoire ou à une miniature modifiée. Une bonne ligne rend traçable le passage de la découverte au contrôle visuel." },
      { title: "Séparer correspondance actuelle et affirmation ouverte", text: "Ouvrez la destination et confirmez que titre, première image et options sélectionnables correspondent encore à la ligne. Un lien actif ne suffit pas si la fiche décrit maintenant une autre version. Matière, authenticité, taille réelle et fonction cachée restent non vérifiées sans preuve directe actuelle. L’objectif n’est pas d’accumuler le plus de liens, mais de maintenir un index plus petit où faits, estimations et inconnues sont différents. Cette séparation réduit la fausse confiance quand l’article entre en stock." },
      { title: "Entretenir le tableau après le QC", text: "Après la commande, une ligne reste utile si elle accueille les nouvelles preuves. Ajoutez date d’entrée, résultat QC visible, étiquette ou mesure confirmée et note de décision. Signalez les routes disparues, les changements d’identité ou l’option devenue indisponible. Contrôlez régulièrement un échantillon et datez chaque révision. Une unité réussie n’est pas une note permanente du vendeur : lots, options et pages changent. La maintenance améliore la trace sans effacer la référence initiale de commande." },
      { title: "Ajouter la confiance, pas une note décorative", text: "Marquez chaque champ comme confirmé, estimé ou inconnu. Un identifiant actuel peut être confirmé tandis que le poids reste déclaré par le vendeur et que la couleur attend le contrôle sous lumière d’entrepôt. Indiquez la preuve qui augmenterait la confiance. Cette discipline empêche un tableau propre de donner la même apparence aux données faibles et aux observations directes, et prépare la liste des questions QC encore ouvertes." },
    ],
    finds: [
      { title: "Sélectionner selon la preuve nécessaire", text: "Une trouvaille mérite l’ouverture lorsqu’elle correspond à la catégorie, l’usage, l’option et la tolérance au risque. Avant de choisir l’esthétique, écrivez les questions que les images devront résoudre : étiquette de taille, couleur, nombre de pièces, marqueur de modèle ou partie structurée intacte. La sélection devient une préparation, pas une galerie. Deux produits proches peuvent exiger des contrôles différents à cause de nombreuses variantes, d’une forme rigide ou d’une option invisible sur l’image principale." },
      { title: "Comparer avec les mêmes champs", text: "Utilisez les mêmes preuves pour chaque candidat d’une catégorie. Pour les chaussures, comparez option, méthode de taille, symétrie et pièces sous des angles équivalents. Pour les vêtements, réunissez taille choisie, méthode de mesure, placement et personnalisation. Pour sacs et accessoires, notez dimensions, pièces et fermetures. Un produit un peu plus cher peut avoir moins d’incertitude d’identité ; une route bon marché mais confuse demande davantage de suivi. Gardez ces compromis visibles au lieu de les cacher dans une note unique." },
      { title: "Appliquer une règle d’arrêt", text: "Cessez d’ajouter des candidats lorsqu’un petit groupe satisfait le besoin et que chaque route contient assez d’informations actuelles. Écartez une trouvaille si la page ne correspond plus, si l’option manque, si une spécification décisive reste non identifiable ou si l’incertitude est excessive. Notez la raison de conserver ou retirer. Une justification datée est reproductible et vaut mieux qu’un badge vague. Ce site propose des points de départ ; disponibilité, options et transaction se confirment toujours sur la destination actuelle." },
      { title: "Dater chaque comparaison par image", text: "Une miniature n’est que l’état vu par l’éditeur. Gardez la date et rouvrez la destination avant d’agir. Si première image, options ou texte d’identité changent, ne réutilisez pas silencieusement l’ancienne conclusion. Notez le changement et recommencez le contrôle. La carte ne paraît alors pas actuelle simplement parce qu’elle charge encore, et la comparaison d’entrepôt reste attachée à la version réellement choisie." },
    ],
    guide: [
      { title: "Construire une seule trace entre les étapes", text: "Reliez la fiche, l’option exacte, la référence de paiement, le dossier d’entrepôt et le colis. Chaque étape répond à une question : l’annonce décrit l’offre, la commande le choix et les photos seulement l’article reçu sous les angles disponibles. Aucune ne remplace les autres. Utilisez identifiants et dates pour qu’une fiche modifiée n’efface pas la comparaison. En cas d’écart, décrivez la différence précise entre deux dossiers plutôt qu’un jugement général de qualité." },
      { title: "Contrôler pendant que la décision reste possible", text: "L’aide OOPBUY vérifiée le 1er septembre 2026 décrit inspection et photos après entrée ainsi qu’une fenêtre habituelle de cinq jours ou 120 heures. Revérifiez règle et statut au moment d’agir, car politique et éligibilité peuvent évoluer. Contrôlez d’abord identité, puis état visible, mesures et pièces. Si un angle décisif manque, nommez la vue ou mesure nécessaire. N’attendez pas la soumission du colis pour découvrir que la période utile est terminée." },
      { title: "Clore par une décision datée", text: "Terminez chaque article par un état concis : accepté, retenu pour preuve manquante ou escaladé par le flux actuel. Ajoutez date, caractéristique et élément probant. Reliez ensuite colis emballé et résultat livré. Un achat ne devient pas un avis universel, mais crée une trace locale qui améliore la comparaison suivante. L’incertitude reste explicite pour authenticité, matière, électronique interne, durabilité et taille réelle, que des images d’entrepôt ordinaires ne prouvent pas." },
    ],
    qc: [
      { title: "Utiliser une échelle de preuve", text: "Commencez par le directement visible : étiquette, quantité, marque imprimée, extrémités d’une mesure, surface ou relation entre pièces. Notez ensuite ce que l’image suggère sans confirmer, comme une couleur sous lumière incertaine. Les affirmations non visuelles restent hors de la conclusion. Matière, authenticité, odeur, construction interne, étanchéité, fonction électronique et taille réelle exigent d’autres preuves. Cette échelle empêche une impression plausible de devenir un fait et montre clairement la lacune restante." },
      { title: "Cartographier angles, échelle et limites", text: "Listez les vues avant de juger : avant, arrière, côtés, étiquettes, pièces et mesures critiques sont-ils visibles ? Perspective, grand-angle, compression et balance des blancs peuvent modifier bord, symétrie, détail et couleur. Comparez des angles équivalents et cherchez le problème dans plusieurs images. Lorsque l’échelle compte, vérifiez où commence et finit la règle. Une photo de mesure sans points de référence définis peut sembler précise tout en répondant à la mauvaise question." },
      { title: "Accepter, retenir ou escalader selon la confiance", text: "Acceptez lorsque la preuve correspond à l’identité commandée et que les lacunes sont tolérables. Retenez si une vue, une étiquette, une quantité ou une mesure décisive manque. Escaladez par le flux actuel si le dossier montre un écart ou dommage objectif et si la commande reste éligible. Décrivez l’observation, pas une accusation. La décision doit identifier le fait qui change le résultat et les limites restantes. Vous obtenez ainsi un contrôle visuel répétable sans prétendre à une certification." },
      { title: "Écrire une note de confiance", text: "Terminez par une phrase nommant la correspondance la plus forte, la lacune principale et l’action. Modèle et taille peuvent soutenir l’identité tandis que la couleur reste incertaine sous l’éclairage. Cette note rend la décision vérifiable sans cacher les limites derrière un badge. Un futur lecteur sait exactement pourquoi rouvrir les preuves sans recommencer tout le contrôle." },
    ],
    shipping: [
      { title: "Transformer l’état visible en priorité d’emballage", text: "Les images d’entrepôt révèlent les parties pouvant nécessiter une protection : bord rigide, impression fragile, bout structuré, fermoir exposé ou accessoire cassable. Décrivez le risque visé au lieu d’ajouter tous les services. Les photos ne prédisent pas tous les incidents, mais indiquent ce qui résiste mal à la compression, au frottement ou au mouvement. Conservez l’état initial afin de comparer le produit livré à sa condition avant expédition." },
      { title: "Séparer dommage produit et dommage d’emballage", text: "Examinez produit et emballage extérieur comme deux couches. Une boîte cabossée ne prouve pas automatiquement un dommage intérieur, et une boîte intacte n’exclut pas un défaut déjà visible à l’entrepôt. Notez éclats, fissures, marques, coins écrasés et protections absentes avec emplacement et angle. Pour garder, retirer ou renforcer l’emballage, équilibrez fragilité visible, valeur de présentation et volume sans promettre un résultat de transport." },
      { title: "Conserver un dossier avant-après", text: "Avant l’envoi, sauvegardez vues QC acceptées, quantité de pièces, demande d’emballage, mesures et date. Après livraison, comparez si possible les mêmes zones et angles. Notez les changements sans attribuer une cause lorsque les preuves ne distinguent pas vendeur, entrepôt, transport international et livraison locale. Le dossier améliore les protections futures et les descriptions d’incident. Il garde aussi cette page centrée sur les preuves visuelles plutôt que sur les mots-clés généraux de tarifs ou routes d’autres ressources OOPBUY." },
      { title: "Séparer preuve d’emballage et prix", text: "Un risque visible ne devient pas ici un tarif, une route ou une assurance garantis. Gardez protection et mesures, mais vérifiez disponibilité et prix dans la transaction actuelle. Des dossiers distincts préservent l’argument visuel lorsque les services changent. Ils révèlent ensuite si un écart de coût vient de l’emballage, des dimensions mesurées ou d’une mise à jour de route plutôt que de l’évaluation de l’état." },
    ],
    articles: [
      { title: "Utiliser la bibliothèque comme parcours visuel", text: "Commencez par le cadre QC général, puis choisissez le guide correspondant à l’objet ou à la lacune. La séquence reste la même : conserver la référence, cartographier les images, séparer observation et déduction, nommer ce qui manque et décider selon la confiance. Les articles tableau, processus et emballage restent disponibles comme contexte ; le rôle éditorial principal du site est l’analyse des photos QC OOPBUY une fois les images d’entrepôt existantes." },
      { title: "Vérifier sources, dates et limites", text: "Les politiques et écrans peuvent changer. Chaque article affiche donc une date et relie la documentation officielle utilisée pour les faits variables. Une source soutient qu’un flux ou délai a été publié ; elle ne prouve pas un produit, une photo ou un résultat futur précis. Séparez déclaration officielle, observation visuelle et incertitude. Si un ancien article contredit la page actuelle, la source officielle présente et le flux du compte dirigent la décision pratique." },
      { title: "Choisir le guide selon la décision", text: "Utilisez le cadre QC pour identité et état visibles, le flux du tableau pour préserver la référence, l’article sur les délais pour agir à temps et celui sur l’emballage pour traduire un risque visuel en protection. Un guide général ne remplace ni mesure absente, ni pièce cachée, ni règle actuelle. Chaque texte répond à une décision avec des preuves ; la série QVL ajoutera des sujets étroits sans répéter les intentions générales de tableurs, frais, routes ou après-vente des autres ressources." },
    ],
  },
  it: {
    spreadsheet: [
      { title: "Leggi ogni riga come registro di evidenza", text: "Una riga dovrebbe conservare percorso aperto, ID prodotto, variante prevista, data del controllo e dettagli visivi utili in seguito. La scheda diventa così un riferimento, non una promessa. Annota colore, metodo di taglia, quantità e parti distintive prima del pagamento. Quando arrivano le foto del magazzino, confrontale con questo registro invece che con la memoria o una miniatura modificata. Una buona riga rende tracciabile il passaggio dalla scoperta all’ispezione visiva." },
      { title: "Separa la corrispondenza attuale da un’affermazione aperta", text: "Apri la destinazione e verifica che titolo, prima immagine e opzioni selezionabili corrispondano ancora alla riga. Un link funzionante non basta se ora descrive un’altra versione. Materiale, autenticità, vestibilità reale e funzione nascosta restano non verificati senza prova diretta e corrente. L’obiettivo non è accumulare più link, ma mantenere un indice minore in cui fatti, stime e incognite siano distinti. Questa separazione riduce la falsa sicurezza quando l’articolo entra in magazzino." },
      { title: "Aggiorna il foglio con le prove del magazzino", text: "Dopo l’ordine una riga resta utile se accoglie nuove evidenze. Aggiungi data d’ingresso, risultato QC visibile, etichetta o misura confermata e breve nota decisionale. Segnala percorsi scomparsi, identità cambiate o opzioni non più disponibili. Ricontrolla periodicamente un campione e data ogni revisione. Una singola unità riuscita non crea una valutazione permanente: lotti, varianti e pagine cambiano. La manutenzione deve migliorare il tracciato conservando il riferimento originale dell’ordine." },
      { title: "Aggiungi fiducia, non un punteggio decorativo", text: "Segna i campi come confermati, stimati o ignoti. Un ID attuale può essere confermato mentre il peso resta dichiarato dal venditore e il colore attende il confronto sotto luce di magazzino. Indica quale prova aumenterebbe la fiducia. Questa disciplina impedisce a un foglio ordinato di far sembrare equivalenti dati deboli e osservazioni dirette e prepara l’elenco delle domande QC ancora aperte." },
    ],
    finds: [
      { title: "Seleziona in base alla prova necessaria", text: "Un prodotto merita di essere aperto se rispetta categoria, uso, variante e tolleranza al rischio. Prima dell’estetica, scrivi le domande che le foto dovranno risolvere: etichetta di taglia, colore, numero di pezzi, marcatore del modello o parte strutturale integra. La selezione diventa preparazione, non galleria. Due prodotti simili possono richiedere controlli diversi per molte varianti, forma rigida o un’opzione non distinguibile dalla foto principale." },
      { title: "Confronta con gli stessi campi", text: "Usa le stesse evidenze per ogni candidato della categoria. Per le scarpe confronta variante, metodo di taglia, simmetria e parti da angoli equivalenti. Per l’abbigliamento riunisci taglia, metodo di misura, posizione grafica e personalizzazione. Per borse e accessori annota dimensioni, componenti e chiusure. Un articolo un po’ più caro può avere meno incertezza d’identità; un percorso economico con opzioni confuse può richiedere più lavoro. Mantieni visibili questi compromessi invece di nasconderli in un punteggio." },
      { title: "Applica una regola di arresto", text: "Smetti di aggiungere candidati quando un piccolo gruppo soddisfa il bisogno e ogni percorso contiene informazioni attuali sufficienti. Escludi un prodotto se la pagina non corrisponde più, manca l’opzione necessaria, non è identificabile una specifica decisiva o l’incertezza è eccessiva. Registra perché resta o viene rimosso. Una ragione datata è ripetibile e vale più di un badge vago. Questo sito offre punti di partenza; disponibilità, opzioni e acquisto vanno sempre confermati sulla destinazione corrente." },
      { title: "Data ogni confronto basato sulle immagini", text: "Una miniatura rappresenta solo ciò che l’editor ha visto. Salva la data e riapri la destinazione prima di agire. Se cambiano prima immagine, opzioni o testo d’identità, non riutilizzare in silenzio la conclusione precedente. Registra il cambiamento e ripeti il controllo. La scheda non appare attuale solo perché carica ancora e il confronto del magazzino resta collegato alla versione realmente scelta." },
    ],
    guide: [
      { title: "Costruisci un’unica traccia tra tutti i passaggi", text: "Mantieni collegati annuncio, opzione esatta, riferimento di pagamento, registro del magazzino e pacco. Ogni passaggio risponde a una domanda diversa: l’annuncio descrive l’offerta, l’ordine la scelta e le foto solo l’articolo ricevuto dagli angoli disponibili. Nessuno sostituisce gli altri. Usa identificatori e date perché una pagina cambiata non cancelli il confronto. Se emerge una differenza, descrivi il contrasto preciso tra due registri invece di formulare un giudizio generale sulla qualità." },
      { title: "Controlla mentre la decisione è ancora possibile", text: "L’assistenza OOPBUY verificata il 1° settembre 2026 descrive ispezione e foto dopo l’ingresso e una finestra normale di cinque giorni o 120 ore. Verifica di nuovo regola e stato al momento dell’azione, perché politica e idoneità possono cambiare. Controlla prima identità, poi stato visibile, misure e parti. Se manca un angolo decisivo, indica la vista o misura necessaria. Non aspettare l’invio del pacco per scoprire che il periodo utile è terminato." },
      { title: "Chiudi con una decisione datata", text: "Termina ogni articolo con uno stato conciso: accettato, sospeso per evidenza mancante o inoltrato nel flusso corrente. Aggiungi data, caratteristica esaminata e prova. In seguito collega pacco e risultato di consegna. Un ordine non diventa una recensione universale, ma crea una traccia locale che migliora il confronto successivo. Mantieni esplicita l’incertezza su autenticità, materiale, elettronica interna, durata e vestibilità, che normali immagini del magazzino non possono dimostrare." },
    ],
    qc: [
      { title: "Usa una scala di evidenza prima di affermare", text: "Parti dal direttamente visibile: etichetta, quantità, marcatore stampato, estremi di misura, superficie o relazione tra parti. Poi annota ciò che l’immagine suggerisce senza confermare, come il colore con luce incerta. Le affermazioni non visive restano fuori dalla conclusione. Materiale, autenticità, odore, costruzione interna, impermeabilità, funzione elettronica e vestibilità reale richiedono altre prove. Questa scala impedisce che un’impressione plausibile diventi fatto e rende chiara la lacuna restante." },
      { title: "Mappa angoli, scala e limiti", text: "Elenca le viste prima di giudicare. Sono mostrati fronte, retro, lati, etichette, componenti e misure critiche? Prospettiva, grandangolo, compressione e bilanciamento del bianco possono cambiare bordi, simmetria, dettagli e colore. Confronta angoli equivalenti e cerca il problema in più di un’immagine. Quando conta la scala, verifica inizio e fine del righello. Una foto di misura senza riferimenti definiti può sembrare precisa e rispondere alla domanda sbagliata." },
      { title: "Accetta, sospendi o inoltra secondo la fiducia", text: "Accetta solo quando l’evidenza coincide con l’identità ordinata e le lacune sono tollerabili. Sospendi se manca vista, etichetta, quantità o misura decisiva. Inoltra nel flusso corrente se il registro mostra differenza o danno oggettivo e l’ordine è ancora idoneo. Descrivi l’osservazione, non un’accusa. La decisione deve indicare quale fatto ha cambiato l’esito e quali limiti restano. Si ottiene così un’ispezione visiva ripetibile senza fingere una certificazione." },
      { title: "Scrivi una nota di fiducia", text: "Chiudi la revisione con una frase che nomina la corrispondenza più forte, la lacuna principale e l’azione. Modello e taglia possono sostenere l’identità mentre il colore resta incerto sotto la luce del magazzino. La nota rende verificabile la decisione senza nascondere limiti dietro un badge e dice a un futuro revisore perché riaprire le prove senza ripetere tutto." },
    ],
    shipping: [
      { title: "Trasforma lo stato visibile in priorità d’imballaggio", text: "Le prove del magazzino identificano le parti che possono richiedere protezione: bordo rigido, stampa delicata, punta strutturata, chiusura esposta o accessorio fragile. Descrivi il rischio coperto invece di aggiungere ogni servizio. Le foto non prevedono ogni incidente, ma mostrano ciò che è vulnerabile a compressione, abrasione o movimento. Conserva il registro della condizione iniziale per confrontare il risultato consegnato con lo stato prima della spedizione." },
      { title: "Distingui danno al prodotto e all’imballaggio", text: "Esamina prodotto e confezione come due livelli. Una scatola ammaccata non dimostra automaticamente danno interno, mentre una scatola integra non esclude un difetto già visibile in magazzino. Annota schegge, crepe, graffi, angoli schiacciati e protezioni mancanti con posizione e angolo. Nel conservare, rimuovere o rinforzare la confezione, bilancia fragilità visibile, valore di presentazione e volume senza promettere un risultato di trasporto." },
      { title: "Conserva un registro prima e dopo", text: "Prima dell’invio salva viste QC accettate, quantità di parti, richiesta d’imballaggio, dati misurati e data. Dopo la consegna confronta le stesse zone e angolazioni quando possibile. Registra i cambiamenti senza attribuire la causa se le prove non distinguono venditore, magazzino, trasporto internazionale e consegna locale. Il registro migliora protezioni future e descrizioni dei problemi. Mantiene inoltre questa pagina sulle evidenze visive, senza competere per parole generiche su tariffe o rotte assegnate ad altre risorse OOPBUY." },
      { title: "Separa prova d’imballaggio e prezzo", text: "Un rischio visibile non diventa qui tariffa, rotta o assicurazione garantite. Salva protezione e misure, ma verifica disponibilità e prezzo nella transazione corrente. Registri separati mantengono stabile l’argomento visivo quando cambiano i servizi. In seguito mostrano anche se una differenza di costo deriva da imballaggio, dimensioni misurate o aggiornamento della rotta e non dalla valutazione dello stato." },
    ],
    articles: [
      { title: "Usa la biblioteca come percorso di alfabetizzazione visiva", text: "Inizia dal quadro QC generale e passa alla guida dell’oggetto o della lacuna concreta. La sequenza resta: conservare il riferimento, mappare le immagini, separare osservazione e inferenza, indicare ciò che manca e decidere in base alla fiducia. Gli articoli su foglio, processo e imballaggio restano come contesto; il ruolo editoriale principale del sito è l’analisi delle foto QC OOPBUY quando le immagini del magazzino esistono già." },
      { title: "Controlla fonti, date e limiti", text: "Politiche e schermate possono cambiare. Ogni articolo mostra quindi la data e collega il materiale ufficiale usato per i fatti variabili. Una fonte sostiene che un flusso o termine è stato pubblicato; non prova uno specifico prodotto, foto o esito futuro. Separa dichiarazione ufficiale, osservazione visiva e incertezza. Se un articolo precedente contraddice la pagina corrente, la fonte ufficiale attuale e il flusso dell’account controllano la decisione pratica." },
      { title: "Scegli la guida secondo la decisione", text: "Usa il quadro QC per identità e stato visibili, il flusso del foglio per preservare il riferimento, l’articolo sulle scadenze per agire in tempo e quello sull’imballaggio per tradurre il rischio visivo in protezione. Una guida ampia non sostituisce misura assente, parte nascosta o regola attuale. Ogni testo risponde a una decisione con prove; la serie QVL aggiungerà temi stretti senza ripetere intenzioni generali su fogli, tariffe, rotte o post-vendita di altre risorse." },
    ],
  },
};
