import type { Article, ArticleSlug } from "./seo-articles";

export type ParityLanguage = "en" | "de" | "es" | "fr" | "it";
type ExtraSection = Article["sections"][number];

const paritySections: Record<ParityLanguage, Record<ArticleSlug, ExtraSection>> = {
  en: {
    "oopbuy-spreadsheet-guide": { heading: "A maintenance audit you can repeat every two weeks", paragraphs: [
      "Take a dated snapshot before editing the list, then reopen each current route in a clean browser session. Compare item ID, option names, seller price, domestic delivery and the image used in the row. Mark a field changed only when the live page shows evidence; a missing page should become paused, not silently replaced by a similar product.",
      "Deduplicate by the underlying item route rather than by title. Two cards can use different wording or photographs while pointing to the same listing, and one listing can expose options with very different prices. Preserve the original route in a change log so readers can tell whether an editor corrected a value, replaced a dead link or introduced a genuinely new candidate.",
      "Recheck weight with the same evidence hierarchy each time: warehouse measurement first, seller-stated weight second and an editorial estimate only when clearly labelled. If a number cannot be traced, remove the number rather than inventing precision. Record the checking date beside the value because a valid observation can become outdated without having been false when first published.",
      "Finish with a stop rule. A row remains in the active sheet only when its route works, its category still matches and its unresolved risks are visible. This procedure favors a smaller, auditable index over an impressive total that no editor can maintain, and it gives later shipping and QC decisions a clean evidence trail."
    ]},
    "oopbuy-qc-checklist": { heading: "Escalate a QC doubt with a usable evidence packet", paragraphs: [
      "Start the packet with the order number, item ID, selected option and stock-in date. Add the specific listing image or measurement that created the expectation. This prevents support from having to guess whether the problem concerns identity, quantity, visible damage or a preference change, and it preserves the return-window context without an emotional narrative.",
      "Name one observable difference at a time. For example, state that the size tag shows one value while the order shows another, or that the left heel appears misaligned in two numbered photographs. Avoid claims about authenticity or hidden material properties that warehouse images cannot prove. A narrow, visible claim is easier to verify and resolve.",
      "Ask for the smallest extra evidence that can change the decision: a ruler across a named point, both sides under similar lighting, a connector label or a complete accessory layout. Before paying for an extra photo, confirm that the result would genuinely determine keep, return or exchange. Otherwise the request adds cost without reducing uncertainty.",
      "Archive the response, new image and final outcome together. If the seller refuses a return, record the reason and the charges displayed for that case. If the item is approved, record which doubt was resolved. This packet later distinguishes a seller mismatch from warehouse handling or carrier damage and improves the next category checklist."
    ]},
    "oopbuy-shipping-planning": { heading: "Run a parcel pre-mortem before choosing the route", paragraphs: [
      "Imagine the final quote exceeds the budget and identify the likely cause before submitting the parcel. Common causes include a rigid shoe box, uncompressed soft goods, protective materials, a restricted product that removes economy lines or a weight increment just above a route threshold. Assign each cause an action that can still be taken without misdescribing the parcel.",
      "Build three current scenarios: the parcel as packed, a safer split and a packaging alternative that remains suitable for the products. Use the same destination, currency and quote date for all three. Record actual weight, dimensions, chargeable-weight result, transit range, tracking, insurance and restrictions so the comparison is broader than price alone.",
      "Reject any scenario that requires inaccurate declarations, unsuitable compression or removal of packaging that the buyer values. Savings are not real when they create unacceptable damage risk or violate route rules. If a sensitive item blocks several lines, compare moving only that item rather than weakening the protection for the entire parcel.",
      "Save the selected quote with the final warehouse measurements and repeat the comparison if packing changes. The decision record should explain why the chosen route fit this parcel on this date, not claim that it is always the best OOPBuy line. That distinction keeps a useful case study from becoming stale universal advice."
    ]},
    "oopbuy-fees-total-cost": { heading: "Reconcile the estimate with the amounts actually charged", paragraphs: [
      "Create one ledger for the product stage and another for the parcel stage. In the first, record seller price, domestic delivery, every checkout service line, payment conversion and any return or exchange. In the second, record measured parcel data, route quote, packaging, insurance, coupon, refund and destination charge. Never force both stages into one unexplained percentage.",
      "For each row, store status and evidence: estimated, displayed, paid, refunded or disputed. A displayed amount is not yet a payment, and a freight deposit later corrected after measurement should be replaced by the final amount rather than counted twice. Keep the original value in the audit trail so the difference can be explained instead of erased.",
      "When public fee statements disagree, add a note identifying the agreement wording, the Service & Fees wording and the app-store wording checked on the same date. Then record what the actual checkout showed and, if necessary, the written support answer. This separates a documentation conflict from a transaction-specific charge without pretending the conflict has disappeared.",
      "Close the ledger only after refunds and final parcel adjustments settle. Calculate delivered cost per usable item and state whether taxes, insurance and failed-purchase costs are included. That boundary makes two orders comparable and prevents a promotional discount or unresolved balance from being presented as permanent platform pricing."
    ]},
    "is-oopbuy-legit-review": { heading: "Use a review matrix instead of one reputation score", paragraphs: [
      "Create separate rows for ordering, warehouse intake, QC usefulness, return handling, quote accuracy, dispatch, tracking, delivery and support. For each row, distinguish the platform's published promise, what the live account displayed and what a dated customer report claimed. A star rating cannot show which part of the workflow produced the outcome.",
      "Weight evidence by what it can prove. Current terms are strong for declared rules but weak for performance; an account screenshot is strong for one transaction; a detailed review identifies possible failure modes but cannot establish a general rate. Referral incentives, missing route details, copied language and deleted-review warnings reduce confidence and should be disclosed.",
      "Define red flags before the test order: unclear charges that support will not explain, pressure to bypass written terms, missing warehouse evidence, an unresolved item mismatch or a route description that conflicts with the parcel. Also define positive evidence, such as consistent records, traceable adjustments and a documented resolution. Predetermined criteria reduce hindsight bias.",
      "Update the conclusion when a material source changes, not merely when a new enthusiastic or angry comment appears. A responsible verdict remains conditional on seller, destination, product type, route and support outcome. Publishing the matrix and dates lets readers inspect the reasoning without turning one successful parcel into a guarantee."
    ]},
  },
  de: {
    "oopbuy-spreadsheet-guide": { heading: "Ein Wartungsaudit, das sich alle zwei Wochen wiederholen lässt", paragraphs: [
      "Sichere vor jeder Änderung einen datierten Stand und öffne danach jede aktive Route in einer sauberen Browsersitzung. Vergleiche Artikel-ID, Optionsnamen, Verkäuferpreis, Inlandsversand und das verwendete Bild. Ändere ein Feld nur bei sichtbarem Beleg; eine fehlende Seite wird pausiert und nicht still durch ein ähnlich aussehendes Produkt ersetzt.",
      "Entferne Dubletten anhand der zugrunde liegenden Route, nicht anhand des Titels. Zwei Karten können anders heißen und dennoch auf dasselbe Angebot führen, während Optionen desselben Angebots unterschiedliche Preise haben. Bewahre die alte Route im Änderungsprotokoll, damit Korrektur, Ersatz eines toten Links und wirklich neuer Kandidat unterscheidbar bleiben.",
      "Prüfe Gewicht immer in derselben Rangfolge: Lagermessung zuerst, Verkäuferangabe danach und redaktionelle Schätzung nur mit klarer Kennzeichnung. Ohne nachvollziehbare Quelle wird die Zahl entfernt statt präzise erfunden. Das Datum gehört direkt zum Wert, weil eine damals richtige Beobachtung später veralten kann.",
      "Beende das Audit mit einer klaren Regel. Eine Zeile bleibt aktiv, wenn die Route funktioniert, die Kategorie passt und offene Risiken sichtbar sind. Dieses Verfahren bevorzugt einen kleineren prüfbaren Index gegenüber einer unwartbaren Mengenbehauptung und schafft eine saubere Grundlage für spätere QC- und Versandentscheidungen.",
      "Prüfe anschließend eine Stichprobe wie ein neuer Leser. Beginne ohne interne Notizen, öffne die Kategorie, finde die Zeile über Suche und Filter und versuche, Preis, Gewicht, Prüfdatum und offenen Risikohinweis nachzuvollziehen. Scheitert diese Kette, fehlt nicht mehr Volumen, sondern verständlicher Kontext. Korrigiere zuerst Beschriftung, Quelle oder Status, bevor weitere Produkte aufgenommen werden.",
      "Veröffentliche im Änderungsverlauf auch negative Wartungsereignisse: entfernte Route, unklare Variante, nicht mehr bestätigtes Gewicht oder verschobene Nachprüfung. Gerade diese Einträge zeigen, dass die Tabelle aktiv gepflegt wird. Ein nur wachsender Zähler ohne dokumentierte Abgänge wirkt dagegen wie ein Archiv, dessen Aktualität sich weder Nutzer noch Suchmaschine vernünftig erschließen können."
    ]},
    "oopbuy-qc-checklist": { heading: "Einen QC-Zweifel mit einem brauchbaren Belegpaket eskalieren", paragraphs: [
      "Beginne mit Bestellnummer, Artikel-ID, gewählter Option und Einlagerungsdatum. Ergänze genau das Angebotsbild oder die Maßangabe, die die Erwartung begründet. So muss der Support nicht raten, ob Identität, Menge, sichtbarer Schaden oder Meinungsänderung gemeint ist, und die Rückgabefrist bleibt nachvollziehbar.",
      "Benenne jeweils nur eine sichtbare Abweichung. Schreibe etwa, dass das Größenetikett einen anderen Wert als die Bestellung zeigt oder dass die linke Ferse auf zwei nummerierten Fotos schief wirkt. Behauptungen über Echtheit oder verborgene Materialeigenschaften sind ungeeignet, weil Lagerbilder sie nicht beweisen können.",
      "Fordere den kleinsten zusätzlichen Beleg an, der die Entscheidung ändern kann: ein Lineal an einer benannten Stelle, beide Seiten bei ähnlichem Licht, das Anschlusslabel oder die vollständige Zubehörübersicht. Prüfe vor einer kostenpflichtigen Zusatzaufnahme, ob ihr Ergebnis tatsächlich über Behalten, Rückgabe oder Umtausch entscheidet.",
      "Archiviere Antwort, neues Bild und Endstatus gemeinsam. Bei abgelehnter Rückgabe werden Begründung und angezeigte Fallkosten notiert; bei Freigabe wird dokumentiert, welcher Zweifel geklärt wurde. Dieses Paket trennt später Verkäuferabweichung, Lagerbehandlung und Transportschaden und verbessert die nächste Kategorienprüfung.",
      "Lege vor der Prüfung Toleranzen fest. Bei Kleidung können Messpunkte und fotografische Perspektive kleine Abweichungen erzeugen; bei Elektronik ist eine Modellnummer wichtiger als eine ähnlich geformte Hülle. Schreibe deshalb auf, welche Abweichung noch akzeptabel ist und welche die Nutzung verhindert. Die Entscheidung folgt dann einem vorherigen Kriterium statt dem Wunsch, einen bereits bezahlten Artikel unbedingt zu behalten.",
      "Wenn mehrere Artikel gleichzeitig eintreffen, bearbeite zuerst kurze Rückgabefristen und Identitätsfragen. Optische Kleinigkeiten können danach folgen. Markiere jeden Fall mit offen, zusätzlicher Beleg angefordert, Rückgabe beantragt oder freigegeben. Diese einfache Warteschlange verhindert, dass ein unklarer Artikel versehentlich mit konsolidiert wird, während eine Supportanfrage noch läuft."
    ]},
    "oopbuy-shipping-planning": { heading: "Vor der Routenwahl einen Paket-Pre-Mortem durchführen", paragraphs: [
      "Stelle dir vor, die finale Quote überschreitet das Budget, und suche die wahrscheinlichste Ursache vor der Paketeinreichung. Typische Gründe sind starre Schuhboxen, nicht komprimierte Textilien, Schutzmaterial, ein eingeschränkter Artikel ohne Economy-Linie oder ein Gewicht knapp über einer Preisstufe. Ordne jeder Ursache eine erlaubte Gegenmaßnahme zu.",
      "Erstelle drei aktuelle Szenarien: das Paket wie gepackt, eine sichere Teilung und eine weiterhin produkttaugliche Verpackungsalternative. Verwende gleiches Ziel, gleiche Währung und dasselbe Quote-Datum. Erfasse Gewicht, Maße, abrechenbares Ergebnis, Laufzeit, Tracking, Versicherung und Einschränkungen, damit nicht nur der Preis verglichen wird.",
      "Verwirf jedes Szenario, das falsche Angaben, ungeeignete Kompression oder den unerwünschten Verlust wertvoller Verpackung verlangt. Ersparnis ist nicht real, wenn sie Schadensrisiko erhöht oder Routenregeln verletzt. Blockiert ein sensibler Artikel mehrere Linien, prüfe dessen getrennten Versand statt den Schutz des Gesamtpakets zu schwächen.",
      "Speichere die gewählte Quote mit den finalen Lagermaßen und vergleiche erneut, wenn sich die Verpackung ändert. Der Datensatz soll erklären, warum diese Route an diesem Datum zu diesem Paket passte, nicht behaupten, sie sei dauerhaft die beste OOPBuy-Linie.",
      "Prüfe außerdem, ob die Laufzeitangabe nur den Transport oder auch Bearbeitung und Übergabe umfasst. Zwei Linien mit ähnlicher Werktageszahl können sich bei Trackingbeginn, Übergabepartner und Nachweis im Schadenfall unterscheiden. Notiere deshalb nicht nur Tage, sondern auch den Startpunkt der Frist und den letzten Status, ab dem ein Nachforschungs- oder Entschädigungsprozess laut aktueller Linie möglich wird.",
      "Nach Zustellung wird aus der Planung ein Datensatz. Trage tatsächliche Versandkosten, endgültiges Gewicht, Übergabedatum, ersten Scan, Zustellung und eventuelle Abweichungen ein. Ein einzelner Fall ist keine allgemeine Erfolgsquote, verbessert aber die nächste Schätzung für dasselbe Ziel und einen ähnlichen Produktmix erheblich, weil die Differenz zwischen Vorhersage und Ergebnis sichtbar wird."
    ]},
    "oopbuy-fees-total-cost": { heading: "Schätzung und tatsächlich belastete Beträge abstimmen", paragraphs: [
      "Führe ein Ledger für die Produktstufe und eines für die Paketstufe. Das erste enthält Verkäuferpreis, Inlandsversand, jede Checkout-Servicezeile, Zahlungsumrechnung und mögliche Rückgabe. Das zweite enthält Paketmaße, Route, Verpackung, Versicherung, Coupon, Erstattung und Zielkosten. Beide Stufen dürfen nicht in einem unerklärten Prozentsatz verschwinden.",
      "Speichere zu jeder Zeile Status und Beleg: geschätzt, angezeigt, bezahlt, erstattet oder strittig. Ein angezeigter Betrag ist noch keine Zahlung; eine nach Endmessung korrigierte Fracht ersetzt den vorläufigen Wert statt doppelt gezählt zu werden. Der alte Wert bleibt im Verlauf, damit die Differenz erklärbar ist.",
      "Bei widersprüchlichen Gebührenangaben notiere Vereinbarung, Service & Fees und App-Store-Text vom gleichen Prüftag. Ergänze danach die tatsächliche Checkout-Anzeige und bei Bedarf die schriftliche Supportantwort. So bleibt der Dokumentationskonflikt sichtbar, ohne ihn mit einer konkreten Transaktionsgebühr zu verwechseln.",
      "Schließe das Ledger erst nach Erstattungen und finalen Paketanpassungen. Berechne gelieferte Kosten pro brauchbarem Artikel und erkläre, ob Steuern, Versicherung und Fehlkaufkosten enthalten sind. Diese Grenze macht Bestellungen vergleichbar und verhindert, dass Rabatt oder ungeklärtes Guthaben als dauerhafter Plattformpreis erscheint.",
      "Baue für unklare Gebühren eine kleine Abweichungsprüfung ein. Vergleiche den erwarteten Betrag mit der Checkout-Summe, suche zuerst nach Variante, Inlandsfracht, Umrechnung und optionalem Dienst und dokumentiere erst danach eine ungeklärte Differenz. So wird nicht jede Abweichung vorschnell als versteckte Gebühr bezeichnet, während ein echter Widerspruch trotzdem sichtbar bleibt und schriftlich geklärt werden kann.",
      "Verteile gemeinsame Paketkosten nur mit einer benannten Methode. Gewicht eignet sich für schwere Artikel, Volumenbeitrag für große leichte Ware und Warenwert eher für bestimmte Versicherungsfragen. Keine Methode ist immer richtig. Entscheidend ist, dass dieselbe Methode bei zwei Vergleichsbestellungen angewendet und eine spätere Erstattung an der ursprünglichen Kostenzeile berichtigt wird."
    ]},
    "is-oopbuy-legit-review": { heading: "Eine Bewertungsmatrix statt einer einzigen Reputationsnote verwenden", paragraphs: [
      "Erstelle getrennte Zeilen für Bestellung, Lagereingang, QC-Nutzen, Rückgabe, Quote-Genauigkeit, Versandstart, Tracking, Zustellung und Support. Trenne je Zeile veröffentlichtes Versprechen, Anzeige im Live-Konto und Aussage eines datierten Kundenberichts. Eine Sternnote zeigt nicht, welcher Prozessabschnitt das Ergebnis verursacht hat.",
      "Gewichte Belege nach ihrer Aussagekraft. Aktuelle Bedingungen sind stark für Regeln, aber schwach für Leistung; ein Konto-Screenshot belegt eine Transaktion; ein detaillierter Bericht zeigt mögliche Fehler, aber keine allgemeine Quote. Referral-Anreize, fehlende Routendaten, kopierter Text und Hinweise auf gelöschte Bewertungen senken das Vertrauen.",
      "Definiere Warnzeichen vor dem Testkauf: unerklärte Kosten, Druck zum Umgehen schriftlicher Regeln, fehlende Lagerbelege, ungeklärte Artikelabweichung oder ein Routenhinweis im Widerspruch zum Paket. Lege ebenso positive Kriterien fest, etwa konsistente Datensätze, nachvollziehbare Anpassungen und dokumentierte Problemlösung. Das reduziert Rückschaufehler.",
      "Ändere das Fazit, wenn sich eine wesentliche Quelle ändert, nicht bei jedem neuen begeisterten oder wütenden Kommentar. Eine verantwortliche Bewertung bleibt abhängig von Verkäufer, Ziel, Produkt, Route und Supportergebnis. Veröffentlichte Kriterien und Daten machen die Begründung prüfbar, ohne ein erfolgreiches Paket zur Garantie zu erklären.",
      "Trenne in der Auswertung Häufigkeit und Schwere. Viele kleine Beschwerden über Bedienung sind nicht dasselbe wie ein seltener, aber großer Verlustfall; gleichzeitig beweist eine dramatische Einzelgeschichte keine allgemeine Rate. Notiere deshalb Thema, belegbaren Betrag, Zeitachse, Reaktion des Supports und Ergebnis. Diese Felder erlauben eine nüchterne Priorisierung, ohne die Erfahrung der betroffenen Person abzuwerten.",
      "Kennzeichne unbekannte Punkte ausdrücklich. Fehlen Zielland, Linie, Bestellnachweis oder vollständiger Nachrichtenverlauf, bleibt die Ursache offen. Eine gute Bewertung muss nicht jede Lücke schließen, sondern darf sagen, welche Aussage sich nicht überprüfen lässt. Genau diese Grenze unterscheidet eine faktenbasierte Risikoprüfung von einer pauschalen Empfehlung oder einem pauschalen Betrugsvorwurf."
    ]},
  },
  es: {
    "oopbuy-spreadsheet-guide": { heading: "Una auditoría de mantenimiento repetible cada dos semanas", paragraphs: [
      "Guarda una copia fechada antes de editar y vuelve a abrir cada ruta activa en una sesión limpia. Compara ID, nombres de opciones, precio del vendedor, entrega nacional e imagen usada. Cambia un campo solo cuando la página activa lo demuestre; una página ausente queda en pausa, no se sustituye en silencio por un producto parecido.",
      "Elimina duplicados por la ruta subyacente, no por el título. Dos tarjetas con textos o fotos distintos pueden llevar al mismo anuncio, y un anuncio puede ofrecer variantes con precios muy diferentes. Conserva la ruta anterior en el historial para distinguir corrección, reemplazo de enlace muerto y candidato realmente nuevo.",
      "Revisa el peso con la misma jerarquía: medición de almacén primero, dato del vendedor después y estimación editorial solo si está claramente marcada. Si una cifra no tiene origen, retírala en vez de inventar precisión. Asocia la fecha al valor porque un dato válido puede quedar obsoleto sin haber sido falso.",
      "Termina con una regla de permanencia. Una fila sigue activa cuando funciona, mantiene la categoría correcta y muestra los riesgos pendientes. El método favorece un índice menor pero auditable frente a una cifra imposible de mantener y deja un rastro limpio para decisiones posteriores de QC y envío."
    ]},
    "oopbuy-qc-checklist": { heading: "Escalar una duda de QC con un paquete de pruebas útil", paragraphs: [
      "Empieza con número de pedido, ID, opción elegida y fecha de entrada. Añade la imagen o medida del anuncio que creó la expectativa. Así soporte no tiene que adivinar si el problema es identidad, cantidad, daño visible o cambio de preferencia, y queda claro el contexto de la ventana de devolución.",
      "Describe una diferencia observable cada vez. Indica, por ejemplo, que la etiqueta muestra una talla distinta al pedido o que el talón izquierdo parece desalineado en dos fotos numeradas. Evita afirmar autenticidad o propiedades internas que las imágenes de almacén no pueden demostrar. Una afirmación estrecha se resuelve mejor.",
      "Pide la prueba mínima que pueda cambiar la decisión: una regla en un punto concreto, ambos lados con luz similar, la etiqueta del conector o el conjunto completo de accesorios. Antes de pagar una foto extra, confirma que el resultado decidiría conservar, devolver o cambiar; de lo contrario aumenta coste sin reducir incertidumbre.",
      "Archiva respuesta, nueva imagen y resultado juntos. Si el vendedor rechaza la devolución, registra el motivo y los cargos mostrados; si apruebas el producto, indica qué duda quedó resuelta. El expediente diferencia después error del vendedor, manipulación del almacén y daño de transporte, y mejora la siguiente lista de control."
    ]},
    "oopbuy-shipping-planning": { heading: "Hacer un pre-mortem del paquete antes de elegir ruta", paragraphs: [
      "Imagina que la cotización final supera el presupuesto e identifica la causa probable antes de enviar el paquete. Puede ser una caja rígida, prendas sin comprimir, protección adicional, un artículo restringido que elimina líneas económicas o un peso apenas superior al tramo. Asigna a cada causa una acción permitida que no falsee el paquete.",
      "Crea tres escenarios vigentes: paquete tal como está, división segura y alternativa de embalaje adecuada. Usa mismo destino, moneda y fecha. Registra peso, medidas, peso facturable, plazo, seguimiento, seguro y restricciones para que la comparación no se limite al precio y permita explicar por qué cambia una ruta.",
      "Descarta escenarios que exijan declaraciones inexactas, compresión inadecuada o retirar un embalaje valioso para el comprador. El ahorro no es real si crea riesgo de daño o infringe reglas. Si un producto sensible bloquea líneas, compara separar solo ese artículo antes de reducir la protección de todo el paquete.",
      "Guarda la opción elegida junto con las medidas finales y repite el cálculo si cambia el embalaje. El registro debe explicar por qué esa ruta servía para ese paquete y esa fecha, no proclamar que siempre es la mejor línea de OOPBuy. Así un caso útil no se convierte en consejo obsoleto."
    ]},
    "oopbuy-fees-total-cost": { heading: "Conciliar la estimación con los importes realmente cobrados", paragraphs: [
      "Crea un libro para la fase de producto y otro para la fase de paquete. El primero incluye precio, entrega nacional, cada línea de servicio del checkout, conversión y devoluciones. El segundo contiene medidas, ruta, embalaje, seguro, cupón, reembolso y cargo de destino. No reduzcas ambas fases a un porcentaje sin explicar.",
      "Asigna estado y prueba a cada fila: estimado, mostrado, pagado, reembolsado o disputado. Un importe mostrado aún no es pago; un depósito de flete corregido tras la medición debe sustituirse por el valor final, no sumarse dos veces. Conserva el dato inicial en el historial para explicar la diferencia.",
      "Cuando las fuentes de comisiones se contradigan, anota acuerdo, Service & Fees y texto de la tienda de aplicaciones revisados el mismo día. Añade lo que mostró el checkout real y, si hace falta, la respuesta escrita de soporte. Así separas conflicto documental y cargo específico sin fingir que el conflicto desapareció.",
      "Cierra el libro solo después de reembolsos y ajustes finales. Calcula coste entregado por artículo útil e indica si incluye impuestos, seguro y compras fallidas. Ese límite permite comparar pedidos y evita presentar una promoción temporal o un saldo pendiente como precio permanente de la plataforma."
    ]},
    "is-oopbuy-legit-review": { heading: "Usar una matriz de revisión en vez de una sola nota", paragraphs: [
      "Separa pedido, entrada, utilidad del QC, devoluciones, precisión de cotización, despacho, seguimiento, entrega y soporte. Para cada etapa distingue promesa publicada, pantalla de la cuenta y relato fechado de un cliente. Una estrella no revela qué parte del proceso produjo un resultado bueno o malo.",
      "Pondera la evidencia por lo que puede demostrar. Los términos sirven para reglas, no para rendimiento; una captura prueba una transacción; una reseña detallada identifica fallos posibles, no una tasa general. Referidos, falta de datos de ruta, lenguaje copiado y avisos sobre reseñas eliminadas reducen la confianza y deben declararse.",
      "Define alertas antes del pedido de prueba: cargos que soporte no explica, presión para eludir términos escritos, ausencia de evidencia de almacén, diferencia de producto sin resolver o ruta incompatible con el paquete. Define también señales positivas, como registros consistentes, ajustes trazables y resolución documentada. Los criterios previos reducen sesgo retrospectivo.",
      "Actualiza la conclusión cuando cambie una fuente material, no con cada comentario nuevo. El veredicto responsable depende de vendedor, destino, producto, ruta y respuesta de soporte. Publicar matriz y fechas permite revisar el razonamiento sin convertir un paquete entregado en garantía general."
    ]},
  },
  fr: {
    "oopbuy-spreadsheet-guide": { heading: "Un audit d'entretien à répéter toutes les deux semaines", paragraphs: [
      "Conservez une copie datée avant toute modification, puis rouvrez chaque route active dans une session propre. Comparez identifiant, options, prix vendeur, livraison locale et image utilisée. Modifiez un champ seulement si la page active l'atteste ; une page absente est mise en pause, pas remplacée discrètement par un produit ressemblant.",
      "Dédupliquez selon la route sous-jacente, pas selon le titre. Deux fiches différentes peuvent mener à la même offre, tandis qu'une offre peut contenir des variantes à des prix éloignés. Gardez l'ancienne route dans le journal afin de distinguer correction, remplacement d'un lien mort et véritable nouveau candidat.",
      "Contrôlez le poids avec la même hiérarchie : mesure d'entrepôt, donnée vendeur, puis estimation éditoriale clairement signalée. Sans origine traçable, retirez le nombre au lieu d'inventer une précision. Associez la date à la valeur, car une observation valide peut devenir obsolète sans avoir été fausse lors de sa publication.",
      "Terminez par une règle de maintien. Une ligne reste active si sa route fonctionne, si la catégorie correspond et si les risques ouverts sont visibles. Ce processus privilégie un index plus petit mais auditable plutôt qu'un volume impossible à entretenir et fournit une base propre aux décisions de QC et d'expédition."
    ]},
    "oopbuy-qc-checklist": { heading: "Faire remonter un doute QC avec un dossier exploitable", paragraphs: [
      "Commencez par le numéro de commande, l'identifiant, l'option choisie et la date d'entrée. Ajoutez l'image ou la mesure de l'offre qui a créé l'attente. Le support sait ainsi si le problème concerne identité, quantité, dommage visible ou préférence, et la fenêtre de retour reste documentée.",
      "Nommez une différence observable à la fois. Indiquez par exemple que l'étiquette affiche une taille différente de la commande ou que le talon gauche semble décalé sur deux photos numérotées. Évitez les affirmations d'authenticité ou de propriété interne que les images d'entrepôt ne peuvent pas prouver.",
      "Demandez la plus petite preuve capable de changer la décision : règle sur un point nommé, deux côtés sous lumière comparable, étiquette du connecteur ou vue complète des accessoires. Avant de payer une photo supplémentaire, vérifiez que son résultat décidera réellement de garder, retourner ou échanger le produit.",
      "Archivez réponse, nouvelle image et décision ensemble. Si le vendeur refuse le retour, notez motif et frais affichés ; si l'article est accepté, précisez quel doute a été levé. Ce dossier distingue ensuite erreur vendeur, manipulation d'entrepôt et dommage transport, tout en améliorant la prochaine checklist."
    ]},
    "oopbuy-shipping-planning": { heading: "Effectuer un pré-mortem du colis avant de choisir la ligne", paragraphs: [
      "Imaginez que le devis final dépasse le budget et recherchez la cause avant la soumission : boîte rigide, textile non compressé, protection ajoutée, produit restreint supprimant les lignes économiques ou poids juste au-dessus d'un palier. Associez chaque cause à une action autorisée qui ne fausse pas la description du colis.",
      "Construisez trois scénarios actuels : colis tel qu'emballé, division sûre et alternative d'emballage adaptée. Utilisez même destination, monnaie et date. Notez poids, dimensions, poids facturable, délai, suivi, assurance et restrictions afin que la comparaison dépasse le seul tarif et explique les différences entre lignes.",
      "Écartez tout scénario nécessitant déclaration inexacte, compression inadaptée ou retrait d'un emballage auquel l'acheteur tient. Une économie n'est pas réelle si elle accroît le dommage ou viole les règles. Si un produit sensible bloque plusieurs lignes, comparez son envoi séparé avant d'affaiblir tout le colis.",
      "Conservez le devis choisi avec les mesures finales et recommencez si l'emballage change. Le dossier doit expliquer pourquoi cette ligne convenait à ce colis ce jour-là, pas affirmer qu'elle reste toujours la meilleure chez OOPBuy. Cette limite empêche une étude de cas utile de devenir un conseil périmé."
    ]},
    "oopbuy-fees-total-cost": { heading: "Rapprocher l'estimation des montants réellement débités", paragraphs: [
      "Tenez un registre pour l'étape produit et un autre pour l'étape colis. Le premier contient prix vendeur, livraison locale, chaque ligne de service au checkout, conversion et éventuel retour. Le second contient mesures, ligne, emballage, assurance, coupon, remboursement et frais de destination. Ne réduisez pas les deux étapes à un pourcentage inexpliqué.",
      "Associez statut et preuve à chaque ligne : estimé, affiché, payé, remboursé ou contesté. Un montant affiché n'est pas encore payé ; un dépôt de fret corrigé après mesure doit être remplacé par la valeur finale, pas compté deux fois. Gardez l'ancienne valeur dans l'historique pour expliquer l'écart.",
      "Lorsque les sources se contredisent, notez l'accord, Service & Fees et le texte de la boutique d'applications vérifiés le même jour. Ajoutez ensuite ce que le checkout réel a affiché et, si nécessaire, la réponse écrite du support. Cela sépare conflit documentaire et frais propres à la transaction sans masquer le désaccord.",
      "Fermez le registre après remboursements et ajustements finaux. Calculez le coût livré par article utilisable et précisez si taxes, assurance et achats échoués sont inclus. Cette frontière rend les commandes comparables et empêche qu'une promotion ou un solde non réglé devienne un prix permanent de plateforme."
    ]},
    "is-oopbuy-legit-review": { heading: "Utiliser une matrice d'avis plutôt qu'une seule note", paragraphs: [
      "Créez des lignes distinctes pour commande, entrée, utilité du QC, retour, précision du devis, départ, suivi, livraison et support. Pour chaque étape, séparez promesse publiée, écran du compte et témoignage client daté. Une étoile ne montre pas quelle partie du parcours a produit le résultat.",
      "Pondérez chaque preuve selon sa portée. Les conditions sont fortes pour les règles, faibles pour la performance ; une capture prouve une transaction ; un avis détaillé signale des modes d'échec, pas un taux général. Parrainage, données de route absentes, texte copié et alerte sur des avis supprimés réduisent la confiance.",
      "Définissez les alertes avant la commande test : frais inexpliqués, pression pour contourner les conditions, preuves d'entrepôt manquantes, article différent non résolu ou route incompatible avec le colis. Définissez aussi les signes positifs, comme dossiers cohérents, ajustements traçables et résolution documentée. Des critères préalables limitent le biais rétrospectif.",
      "Actualisez la conclusion lorsqu'une source importante change, pas après chaque commentaire enthousiaste ou furieux. Un verdict responsable dépend du vendeur, de la destination, du produit, de la ligne et du support. Publier matrice et dates permet d'inspecter le raisonnement sans transformer un colis réussi en garantie générale."
    ]},
  },
  it: {
    "oopbuy-spreadsheet-guide": { heading: "Un audit di manutenzione da ripetere ogni due settimane", paragraphs: [
      "Salva una copia datata prima di modificare e riapri ogni percorso attivo in una sessione pulita. Confronta ID, nomi delle opzioni, prezzo venditore, consegna locale e immagine usata. Cambia un campo solo quando la pagina live offre una prova; una pagina assente va sospesa, non sostituita in silenzio con un prodotto simile.",
      "Rimuovi i duplicati in base al percorso reale, non al titolo. Due schede con testo o foto diversi possono portare alla stessa offerta, mentre una sola offerta può avere varianti con prezzi molto lontani. Conserva il vecchio percorso nel registro per distinguere correzione, sostituzione di link morto e candidato davvero nuovo.",
      "Ricontrolla il peso con la stessa gerarchia: misura di magazzino, dato del venditore e solo dopo stima editoriale chiaramente etichettata. Se un numero non è tracciabile, eliminalo invece di inventare precisione. Associa la data al valore perché un'osservazione valida può diventare obsoleta senza essere stata falsa alla pubblicazione.",
      "Chiudi con una regola di permanenza. Una riga resta attiva se il percorso funziona, la categoria corrisponde e i rischi irrisolti sono visibili. Questo processo preferisce un indice più piccolo ma verificabile a un volume impossibile da mantenere e crea una base pulita per QC e spedizione.",
      "Esegui poi un controllo come se fossi un nuovo lettore, senza note interne. Apri la categoria, trova la riga con ricerca e filtri e prova a ricostruire prezzo, peso, data e rischio aperto. Se la catena si interrompe, manca contesto comprensibile, non quantità. Correggi etichetta, provenienza o stato prima di aggiungere nuovi prodotti alla tabella.",
      "Nel registro delle modifiche pubblica anche gli eventi negativi: percorso rimosso, variante ambigua, peso non più confermato o revisione rinviata. Queste uscite dimostrano manutenzione reale. Un contatore che cresce soltanto, senza elementi rimossi e senza date, assomiglia invece a un archivio in cui né il lettore né il motore di ricerca possono valutare bene l'attualità. Conserva inoltre il motivo della decisione, così una futura revisione non ripete lo stesso errore e può distinguere un problema temporaneo da una rimozione definitiva."
    ]},
    "oopbuy-qc-checklist": { heading: "Segnalare un dubbio QC con un dossier utilizzabile", paragraphs: [
      "Inizia con numero d'ordine, ID, opzione scelta e data d'ingresso. Aggiungi l'immagine o la misura dell'offerta che ha creato l'aspettativa. Il supporto non deve così indovinare se il problema riguarda identità, quantità, danno visibile o cambio di preferenza, e la finestra di reso resta documentata.",
      "Descrivi una differenza osservabile alla volta. Indica per esempio che l'etichetta mostra una taglia diversa dall'ordine o che il tallone sinistro appare disallineato in due foto numerate. Evita affermazioni su autenticità o proprietà interne che le immagini di magazzino non possono dimostrare. Un reclamo stretto è più verificabile.",
      "Chiedi la prova minima capace di cambiare la decisione: righello su un punto preciso, entrambi i lati con luce simile, etichetta del connettore o panoramica completa degli accessori. Prima di pagare una foto aggiuntiva, verifica che il risultato decida davvero tra tenere, rendere o cambiare il prodotto.",
      "Archivia risposta, nuova immagine ed esito insieme. Se il venditore rifiuta il reso, annota motivo e costi mostrati; se approvi l'articolo, registra quale dubbio è stato risolto. Il dossier distingue poi errore del venditore, gestione di magazzino e danno di trasporto, migliorando la checklist successiva.",
      "Stabilisci le tolleranze prima di guardare le foto. Nei capi il punto di misura e la prospettiva possono creare piccole differenze; nell'elettronica un numero di modello vale più di una custodia simile. Scrivi quale scarto è accettabile e quale impedisce l'uso. La scelta segue così un criterio precedente, non il desiderio di tenere comunque un articolo già pagato.",
      "Se arrivano più articoli, controlla prima finestre di reso brevi e dubbi d'identità, lasciando i dettagli estetici minori per dopo. Assegna a ogni caso uno stato: aperto, prova aggiuntiva richiesta, reso richiesto o approvato. Questa coda semplice evita che un prodotto ancora contestato venga consolidato per errore mentre il supporto non ha concluso la verifica."
    ]},
    "oopbuy-shipping-planning": { heading: "Eseguire un pre-mortem del pacco prima della rotta", paragraphs: [
      "Immagina che il preventivo finale superi il budget e individua la causa probabile prima dell'invio: scatola rigida, tessuti non compressi, protezione aggiunta, prodotto limitato che elimina linee economiche o peso appena oltre uno scaglione. Associa a ogni causa un'azione consentita che non descriva il pacco in modo inesatto.",
      "Crea tre scenari attuali: pacco così com'è, divisione sicura e alternativa d'imballaggio adatta ai prodotti. Usa la stessa destinazione, valuta e data. Registra peso, dimensioni, peso addebitabile, tempi, tracking, assicurazione e restrizioni affinché il confronto non si limiti al prezzo e resti riproducibile.",
      "Scarta scenari che richiedono dichiarazioni false, compressione inadatta o rimozione di imballaggi a cui l'acquirente attribuisce valore. Il risparmio non è reale se aumenta il danno o viola le regole. Se un articolo sensibile blocca molte linee, confronta il suo invio separato prima di indebolire l'intero pacco.",
      "Salva il preventivo scelto con le misure finali e ripeti il confronto se cambia l'imballo. Il documento deve spiegare perché quella rotta andava bene per quel pacco in quella data, non affermare che sia sempre la migliore linea OOPBuy. Così un caso utile non diventa consiglio scaduto.",
      "Verifica se l'intervallo di consegna parte dal pagamento, dalla lavorazione, dalla consegna al vettore o dal primo tracking. Due linee con gli stessi giorni dichiarati possono differire per partner finale, scansioni e procedura di rimborso. Registra il punto iniziale e lo stato dal quale le condizioni correnti permettono una ricerca o una richiesta di compensazione.",
      "Dopo la consegna trasforma il piano in un dato storico: costo reale, peso finale, data di consegna al vettore, prima scansione, arrivo ed eventuali problemi. Un singolo pacco non crea una percentuale generale, ma rende molto più utile la prossima stima per la stessa destinazione e un mix simile, perché mostra la distanza tra previsione e risultato. Se la linea cambia regole o nome, conserva comunque il vecchio dato come storico datato e non presentarlo come preventivo attuale per un nuovo ordine."
    ]},
    "oopbuy-fees-total-cost": { heading: "Riconciliare la stima con gli importi realmente addebitati", paragraphs: [
      "Crea un registro per la fase prodotto e uno per la fase pacco. Nel primo inserisci prezzo venditore, consegna locale, ogni voce di servizio al checkout, conversione e resi. Nel secondo registra misure, rotta, imballo, assicurazione, coupon, rimborso e oneri a destinazione. Non comprimere entrambe le fasi in una percentuale non spiegata.",
      "Assegna stato e prova a ogni riga: stimato, mostrato, pagato, rimborsato o contestato. Un importo visualizzato non è ancora un pagamento; un deposito di trasporto corretto dopo la misura va sostituito dal valore finale, non contato due volte. Conserva il valore precedente nello storico per spiegare la differenza.",
      "Quando le fonti sulle commissioni si contraddicono, annota accordo, Service & Fees e testo dello store verificati nello stesso giorno. Aggiungi poi ciò che ha mostrato il checkout reale e, se serve, la risposta scritta del supporto. In questo modo separi conflitto documentale e addebito specifico senza fingere che il conflitto sia sparito.",
      "Chiudi il registro dopo rimborsi e rettifiche finali. Calcola il costo consegnato per articolo utilizzabile e dichiara se include tasse, assicurazione e acquisti falliti. Questo confine rende confrontabili gli ordini e impedisce che una promozione o un saldo irrisolto diventi un prezzo permanente della piattaforma.",
      "Per una differenza non spiegata, confronta prima importo previsto e totale checkout, poi cerca variante, consegna locale, conversione e servizio opzionale. Solo la parte ancora priva di causa diventa una voce contestata. Il metodo evita di chiamare commissione nascosta ogni variazione, ma conserva una discrepanza reale e prepara una domanda scritta precisa per il supporto.",
      "Ripartisci i costi comuni con una regola dichiarata. Il peso può servire per articoli pesanti, il volume per prodotti grandi e leggeri, il valore per alcune domande assicurative. Nessuna base è sempre corretta. Usa la stessa nei due ordini confrontati e registra ogni rimborso come correzione della voce originale, non come risparmio separato."
    ]},
    "is-oopbuy-legit-review": { heading: "Usare una matrice di recensione invece di un solo voto", paragraphs: [
      "Crea righe separate per ordine, ingresso, utilità del QC, reso, precisione del preventivo, partenza, tracking, consegna e supporto. Per ogni fase distingui promessa pubblicata, schermata dell'account e report cliente datato. Una stella non mostra quale parte del flusso abbia prodotto il risultato positivo o negativo.",
      "Pesa le prove per ciò che possono dimostrare. I termini sono forti sulle regole ma deboli sulle prestazioni; uno screenshot prova una transazione; una recensione dettagliata indica possibili guasti ma non un tasso generale. Referral, dati di rotta mancanti, testo copiato e avvisi su recensioni rimosse riducono la fiducia.",
      "Definisci segnali d'allarme prima dell'ordine test: addebiti non spiegati, pressione per aggirare termini scritti, prove di magazzino assenti, prodotto diverso non risolto o rotta incompatibile col pacco. Definisci anche segnali positivi, come registri coerenti, rettifiche tracciabili e soluzione documentata. I criteri precedenti riducono il bias retrospettivo.",
      "Aggiorna la conclusione quando cambia una fonte materiale, non dopo ogni nuovo commento entusiasta o arrabbiato. Un verdetto responsabile dipende da venditore, destinazione, prodotto, rotta e supporto. Pubblicare matrice e date rende verificabile il ragionamento senza trasformare un pacco riuscito in garanzia generale.",
      "Separa frequenza e gravità. Molte lamentele minori sull'interfaccia non equivalgono a un raro caso di perdita importante; allo stesso tempo una storia drammatica non dimostra una percentuale generale. Registra tema, importo documentabile, sequenza temporale, risposta del supporto ed esito. Questi campi permettono di dare priorità ai rischi senza ignorare l'esperienza della persona coinvolta.",
      "Segna apertamente ciò che resta sconosciuto. Se mancano paese, linea, prova d'ordine o conversazione completa, la causa non è determinata. Una recensione corretta non deve riempire ogni vuoto: deve spiegare quale conclusione non è verificabile. Questo limite distingue l'analisi basata sui fatti da una raccomandazione assoluta o da un'accusa assoluta di truffa."
    ]},
  },
};

export function addParitySections(language: ParityLanguage, articles: Record<ArticleSlug, Article>): Record<ArticleSlug, Article> {
  return Object.fromEntries(Object.entries(articles).map(([slug, article]) => [slug, {
    ...article,
    sections: [...article.sections, paritySections[language][slug as ArticleSlug]],
  }])) as Record<ArticleSlug, Article>;
}
