import { longArticle, longArticleSlug, type Topic } from "./topics";
import { articleTranslations } from "./article-translations";
import type { Lang } from "./site-data";

export type ResearchArticle = Topic & {
  slug: string;
  deck: string;
  readingTime: string;
  sourceBasis: string;
  published: string;
  modified: string;
};

const checked = "31 August 2026";

const spreadsheet: ResearchArticle = {
  ...longArticle("en"),
  title: "How to use a LoveGoBuy spreadsheet from search to shortlist",
  slug: longArticleSlug,
  deck: "A maintenance-first method for turning product routes into a shortlist that can be checked again before ordering.",
  readingTime: "9 min",
  sourceBasis: `Research basis: the live LoveGoBuy search and account workflow, current product-page labels, the shipping estimator, and destination checks in the product index. Checked ${checked}.`,
  published: "2026-08-31",
  modified: "2026-08-31",
};

const howToBuy: ResearchArticle = {
  slug: "how-to-buy-with-lovegobuy-2026",
  title: "How to Buy with LoveGoBuy in 2026: Search, Warehouse, QC and Parcel Workflow",
  intro: "LoveGoBuy presents itself as a shopping-agent interface for Chinese marketplaces including Taobao, 1688 and Weidian. The useful way to understand it is not as a normal one-step online shop, but as a sequence: find a source item, submit or search the listing, pay for the purchase, wait for warehouse intake, inspect the available evidence, and then create an international parcel. This guide explains that sequence without turning changing fees, routes or delivery estimates into promises.",
  deck: "A practical, evidence-led walkthrough from source listing to international parcel submission.",
  readingTime: "10 min",
  sourceBasis: `Research basis: LoveGoBuy homepage search labels, current product pages, order and warehouse account states, the official shipping estimator, and public user reports. Checked ${checked}.`,
  published: "2026-08-31",
  modified: "2026-08-31",
  sections: [
    { h: "Understand the two purchases inside one order", p: ["A shopping-agent order has two separate legs. The first is the domestic purchase from a marketplace seller to the agent warehouse. The second is the international parcel from that warehouse to your address. Product price belongs to the first leg; international shipping belongs to the second. Treating them as one checkout total is the easiest way to underestimate the decision.", "LoveGoBuy’s public interface reflects this separation. Its account area distinguishes orders, warehouse items and parcels, while its product pages place international shipping estimation beside the item workflow. Before spending anything, create a simple budget with separate lines for the source item, possible domestic movement, optional handling shown in your account, packed parcel cost and possible destination charges."], bullets: ["Source item and selected option", "Domestic purchase stage", "Warehouse and inspection stage", "International parcel stage", "Destination taxes or handling when applicable"] },
    { h: "Begin with a source listing or a precise search", p: ["The official homepage currently offers search by product name, link or photo. Those inputs solve different problems. A direct marketplace link is best when you already know the exact listing. A text search helps explore a category but can produce visually similar alternatives. Photo search is useful for discovery, yet image similarity is not proof that the seller, material, option or batch is the same.", "LoveGoBuy identifies Taobao, 1688 and Weidian in its public positioning. Each marketplace can structure options and seller information differently, so record the source before comparing candidates. If you use the product index on this guide, open no more than three candidates from one category and write down why each deserves another check. A shorter comparison is easier to maintain than a large list of unexplained links."], bullets: ["Keep the original destination", "Record marketplace and seller context", "Capture the visible option name", "Date the price observation", "Reject visually similar substitutes that do not match"] },
    { h: "Verify the listing before submitting it", p: ["Match at least four things: destination title, first product image, selected color or model, and displayed price. Then check whether the size or specification you need is actually selectable. A converted route only transports the listing into an agent interface. It does not verify the seller, material, measurements, stock or authenticity.", "Pay special attention to listings that reuse one image across many options. A low headline price may belong to an accessory, deposit or different variant rather than the item shown first. If the source is unavailable or a necessary option cannot be explained, stop. Replacing missing facts with details from a similar listing creates a clean-looking spreadsheet and a weak purchase record."], bullets: ["Title matches the intended product", "First image matches the recorded route", "Exact color, size or model is selectable", "Price belongs to that option", "Seller and source remain available"] },
    { h: "Write order notes that can actually be checked", p: ["Order notes should describe observable requirements, not broad wishes. Useful notes identify the exact option, a size based on stated measurements, a color code, or a seller instruction that appears on the source listing. Requests such as best quality or make it perfect cannot be verified and may create false confidence.", "Save a screenshot or text record of the option selected at submission. Marketplace pages can change after payment, and the warehouse item may arrive days later. A dated record gives you something concrete to compare with warehouse photos. If the agent account shows a warning, price adjustment or seller question, resolve that state before assuming the purchase is moving normally."], bullets: ["Exact option wording", "Measurement or specification used", "Any seller-approved customization", "Date submitted", "Unresolved warning or price change"] },
    { h: "Use the order and warehouse states as separate checkpoints", p: ["The official account interface separates order status from warehouse and parcel status. That distinction matters. A purchased item has not completed warehouse intake; a delivered-to-warehouse item is not automatically approved; an approved warehouse item is not yet an international parcel. Read the current status label instead of estimating progress from the number of days alone.", "When an item reaches the warehouse, confirm that it is attached to the correct order and option. Check the recorded weight if shown, but label it as item or warehouse weight rather than final chargeable weight. Packaging, consolidation and route rules can change the parcel calculation. If the item state appears stuck, use current official support with the order identifier rather than relying on an old timeline from a forum post."], bullets: ["Purchase status", "Domestic tracking or seller state", "Warehouse intake", "Inspection evidence", "Parcel eligibility"] },
    { h: "Read QC photos as limited evidence", p: ["Current LoveGoBuy product-page snippets state that several high-definition inspection photos are provided. The exact views that appear can vary by item, and a count alone is not a quality standard. First confirm identity: model, color, size label, number of pieces and obvious option markers. Then move to category-specific construction and measurements.", "QC photos show visible condition at a particular moment. They cannot establish comfort, hidden construction, long-term durability, material composition or authenticity by themselves. Mark each important question answered, unclear or not shown. If a required angle or measurement is missing, use the current account options to request clarification before the parcel stage, when choices may be more limited."], bullets: ["Correct item and option", "Visible defects or mismatch", "Category-specific construction", "Useful scale or measurement", "Missing evidence requiring follow-up"] },
    { h: "Build the parcel from current measurements", p: ["Do not copy a shipping price from another buyer. The official estimator asks for destination and parcel inputs, and its search results explicitly note that dimensions can matter as much as weight. The final parcel may include boxes, protective material and consolidation packaging. That makes a product-page weight useful for planning but insufficient for a final quote.", "Create a working case with expected packed weight and dimensions, then a higher case for bulky packaging or uncertain measurements. If available for your parcel, the official estimator references a rehearsal-parcel service intended to refine weight and volume. Recheck the live route list and restrictions when the parcel is ready because availability, calculation rules and service conditions can change."], bullets: ["Destination country", "Packed weight", "Length, width and height", "Packaging choice", "Current route and restrictions"] },
    { h: "Treat restrictions and destination rules as live data", p: ["LoveGoBuy’s estimator warns that some goods are prohibited and that other categories can face shipping restrictions. Electronics, batteries, liquids, food, branded goods and unusual materials may be treated differently by route and destination. A product being purchasable does not mean every international line will accept it.", "Use the current estimator and account warnings for the exact parcel. Then check import rules for the destination country. This guide cannot predict customs assessment, carrier handling or local taxes. If the parcel contains mixed restricted and unrestricted items, compare the routes shown for the actual combination rather than assuming the route used for an earlier clothing parcel will remain available."], bullets: ["Item category restrictions", "Battery, liquid or food content", "Route-specific rules", "Destination import requirements", "Current declaration and support guidance"] },
    { h: "Run a final audit before paying international shipping", p: ["Reopen the recorded source destination and confirm that the warehouse item still corresponds to the intended product and option. Review QC evidence, weight, dimensions, packaging choice, delivery address and every unresolved question. Remove a candidate from the parcel if its identity or necessary condition is still unclear. International shipping should not be used to escape an unresolved warehouse decision.", "For a first order, a small test parcel produces more useful evidence than a large haul built from assumptions. Keep the order record, parcel inputs and tracking state together. After delivery, compare expected and observed outcomes: product match, packaging, chargeable weight, transit updates and any support case. That record is more valuable for the next order than a generic rating or promotional claim."], bullets: ["Live item match", "QC decision", "Final packed inputs", "Address and route", "Saved transaction record"] },
  ],
};

const qcGuide: ResearchArticle = {
  slug: "lovegobuy-qc-photos-guide",
  title: "LoveGoBuy QC Photos Guide: What to Check Before You Submit a Parcel",
  intro: "LoveGoBuy product pages currently describe a set of high-definition quality-inspection photos as part of the warehouse workflow. The number of images is less important than the questions they answer. A useful QC review confirms identity first, then examines category-specific construction, measurements and visible condition. It also records what the photos cannot prove. This guide turns a folder of warehouse images into a repeatable decision rather than a quick approval based on one flattering angle.",
  deck: "A category-by-category method for reading warehouse photos without inventing certainty.",
  readingTime: "10 min",
  sourceBasis: `Research basis: current LoveGoBuy product-page inspection wording, the warehouse-to-parcel workflow, product evidence in the index, Trustpilot themes, and independent haul reviews. Checked ${checked}.`,
  published: "2026-08-31",
  modified: "2026-08-31",
  sections: [
    { h: "Start with the official claim, then inspect the actual set", p: ["Current LoveGoBuy product-page search snippets state that three to eight high-definition quality-inspection photos are provided. Treat that as a description of the present product-page workflow, not a promise that every category will receive the same views forever. Open the images attached to your exact warehouse item and judge their coverage, clarity and relevance.", "A set of eight repeated angles can answer less than three well-chosen images. Before zooming into stitching, count the questions you need to resolve: correct product, correct option, complete set, visible condition, important measurements and category-specific details. If a question is not shown, label it missing. Do not interpret a high photo count as automatic approval."], bullets: ["Exact warehouse item", "Number of distinct useful views", "Image clarity", "Visible order or option markers", "Missing critical evidence"] },
    { h: "Pass one: confirm identity before quality", p: ["Compare the photographed item with the source record and order note. Check model, color, size label, option text, number of pieces and any feature that distinguishes similar variants. For a two-piece set, both pieces should be identifiable. For shoes, both shoes should appear. Packaging labels can help, but a label does not override a visual mismatch.", "This first pass prevents a common mistake: spending time judging the construction of the wrong item. If the identity is uncertain, stop the review and request clarification through the current account workflow. Do not borrow details from another buyer’s QC album or from a similar listing. Your decision must be tied to the item in your warehouse record."], bullets: ["Model or style", "Color", "Size or specification", "Quantity and included pieces", "Variant-specific details"] },
    { h: "Pass two: look for visible condition, not imagined performance", p: ["Scan the full item for stains, tears, scratches, crushed areas, missing parts, obvious asymmetry and damage to closures or hardware. Use close-ups for suspicious areas, but return to the full view to understand scale. Lighting and compression can change color, so compare several images before calling a shade wrong.", "QC can document what is visible at intake. It cannot prove how the product feels, how long it will last, whether a hidden seam is reinforced, or whether the material matches a marketing description. Phrase the decision precisely: no visible stain in the supplied views is supportable; flawless material is not. This language keeps the record useful if a later problem appears."], bullets: ["Surface damage", "Missing parts", "Obvious asymmetry", "Closure or hardware condition", "Color consistency across views"] },
    { h: "Shoes: profile, symmetry, sole and size context", p: ["For footwear, compare the outside and inside profiles, toe shape, heel alignment and overall symmetry. Check that both shoes are the same size and color. The outsole view can reveal the pattern, obvious marks and whether the pair is complete. A top view helps compare toe boxes, while a rear view makes heel alignment easier to judge.", "Sizing needs evidence beyond a printed label. When fit is uncertain, a clear internal or outsole-length measurement is more useful than a generic chart. Compare it with a pair you already own, measured using the same method. Photos cannot confirm comfort or width under load, so keep the fit conclusion probabilistic and allow tolerance for the measuring technique."], bullets: ["Both shoes and labels", "Side profiles", "Toe and heel symmetry", "Outsole view", "Useful length measurement"] },
    { h: "Clothing: measurements before logos and small details", p: ["For T-shirts, hoodies, jackets and bottoms, begin with flat measurements that answer fit: chest or waist, body length, sleeve, rise and inseam where relevant. Compare them with a garment that already fits, not only with body measurements or a marketplace size chart. Make sure both items were measured flat and from equivalent points.", "Then review construction: collar shape, cuffs, hem, seams, zipper or buttons, print placement and embroidery. A close-up can reveal a visible flaw but should not replace a full front and back view. Fabric weight shown in a listing or warehouse record may help comparison, yet it does not establish composition or hand feel."], bullets: ["Flat fit measurements", "Front and back", "Collar, cuff and hem", "Print or embroidery placement", "Closures and visible seams"] },
    { h: "Bags, accessories and electronics need different evidence", p: ["A bag review should cover full scale, front and back, base, interior, hardware, zipper, strap and attachment points. For hats, check overall shape, circumference context, brim or visor alignment and stitching. Small accessories need a useful scale reference because a clean close-up can make dimensions impossible to judge.", "Electronics require specification and route questions in addition to appearance. Confirm model, plug, included accessories and visible condition, then check whether batteries or restricted components affect the available parcel route. A warehouse photo cannot test every function unless the current service explicitly records a test. Do not describe an unshown functional result as verified."], bullets: ["Useful scale", "Interior or included parts", "Hardware and attachment", "Model and plug", "Shipping restriction check"] },
    { h: "Measurements must show both endpoints", p: ["A measurement photo is useful only when the measuring tool, starting point and ending point are visible. Watch for a tape that begins after zero, bends around the item, follows a diagonal line or uses an unclear reference point. For clothing, note whether the item is stretched. For shoes, note whether the insole was removed and whether the tape follows the curve.", "Record the observed value and a reasonable uncertainty rather than a perfectly exact number. If the image is unreadable, ask for clarification while the item is still in the warehouse. A generic size chart may help choose an option, but it is not a measurement of the photographed piece and should be stored as a separate kind of evidence."], bullets: ["Visible zero point", "Visible endpoint", "Straight measuring path", "Comparable method", "Reasonable tolerance"] },
    { h: "Use an answered, unclear, missing decision table", p: ["For each necessary question, assign one of three states: answered, unclear or missing. Answered means the supplied evidence supports a limited conclusion. Unclear means an image exists but cannot resolve the question. Missing means no relevant view or data exists. This small table is more reliable than a single pass or fail label.", "Prioritize follow-up by consequence. A missing decorative close-up may not block a low-risk purchase, while an unclear size, wrong model or absent component should. Use current account and support options for additional evidence or order resolution. Policies and available actions can change, so avoid copying a return timeline or photo fee from an old post."], bullets: ["Answered with evidence", "Unclear despite evidence", "Not shown", "Decision consequence", "Current follow-up route"] },
    { h: "Approve only the visible decision, not the whole future", p: ["A warehouse approval should mean that the item matches the intended option closely enough and that no blocking visible issue remains in the supplied evidence. It should not be interpreted as a guarantee of authenticity, durability, comfort, exact color under daylight or condition after international transit.", "Save the photo set, measurement notes and approval reason before parcel submission. If a later claim is needed, a dated record is more useful than remembering that the pictures looked fine. Public reviews of LoveGoBuy are mixed on QC consistency: some users praise the evidence, while others describe uneven angles or delays. That makes your own written checklist more important than any platform-wide score."], bullets: ["Identity accepted", "Visible condition accepted", "Fit evidence reviewed", "Unknowns recorded", "Decision saved before parcel"] },
  ],
};

const shippingGuide: ResearchArticle = {
  slug: "lovegobuy-shipping-cost-guide",
  title: "LoveGoBuy Shipping Cost Guide: Weight, Volume, Rehearsal and Route Checks",
  intro: "A product price is not a parcel price. LoveGoBuy’s official estimator asks buyers to work with destination and parcel inputs, and its indexed guidance states that dimensions can matter as much as weight. The estimator also references rehearsal-parcel service and warns about restricted goods. This guide explains how to prepare useful inputs, compare scenarios and avoid turning another user’s historic cost into a promise for a different parcel.",
  deck: "A practical framework for estimating international shipping without relying on copied rates.",
  readingTime: "10 min",
  sourceBasis: `Research basis: the current LoveGoBuy shipping estimator and restriction labels, account parcel states, product weights, and mixed public reports about parcel cost and handling. Checked ${checked}.`,
  published: "2026-08-31",
  modified: "2026-08-31",
  sections: [
    { h: "Separate product cost from parcel cost", p: ["The source item moves to a warehouse before it becomes part of an international parcel. That means the item price, domestic movement, optional services, packaging and international shipping belong on separate lines. A low source price can be outweighed by bulky dimensions; a slightly more expensive compact item can be the better total decision.", "Build the cost sheet before ordering, not after warehouse intake. Use a working estimate for every candidate and record the date. Do not include a coupon or temporary route unless it is visible and applicable in the current account context. Promotional claims and past checkout screenshots can expire, and a static guide cannot guarantee that the same calculation will appear for your destination."], bullets: ["Source item price", "Domestic purchase costs shown live", "Optional handling selected", "Packed international parcel", "Possible destination charges"] },
    { h: "Know which weight you are looking at", p: ["A product index or warehouse record may show an item-weight estimate. The parcel can add shoe boxes, protective wrap, cartons, void fill and consolidation materials. The weight used by a route may therefore differ from the sum of catalogue weights. Label every number: listing estimate, warehouse item weight, expected packed weight or final chargeable weight.", "If one item has no weight, use a range based on comparable products and mark it uncertain. Do not silently substitute another item’s weight. The eight example routes in this guide show how varied clothing and footwear can be, but those values belong to those exact records. Your parcel estimate should be rebuilt from the items actually selected."], bullets: ["Listing estimate", "Warehouse item record", "Packaging allowance", "Expected packed total", "Final route calculation"] },
    { h: "Dimensions can change the calculation", p: ["LoveGoBuy’s indexed shipping-estimator guidance explicitly says that parcel size matters as much as weight and asks for length, width and height as accurately as possible. This is the practical reason a light but bulky jacket or shoe box can cost more than expected. Some routes compare actual weight with a dimensional or volumetric calculation.", "The divisor and rounding rules can differ by route, so do not hard-code one universal formula as the final quote. You can still use a dimensional-weight scenario to identify risk: multiply length, width and height, then apply only the current route rule shown in the estimator. Keep the input dimensions beside the result so the estimate can be repeated."], bullets: ["Packed length", "Packed width", "Packed height", "Current route rule", "Rounding or minimum unit"] },
    { h: "Use three scenarios instead of one exact guess", p: ["Create a lower case, working case and higher case. The lower case uses the lightest realistic packaging that is actually available. The working case uses expected packed weight and measured dimensions. The higher case allows for a larger carton, retained retail boxes or uncertain measurements. Run each case for the same destination and compare the currently available routes.", "This range is more honest than a single cost-per-kilogram claim. Public reviews include both users who considered pricing reasonable and users who felt shipping approached or exceeded product value. Those experiences can both be real because parcel composition, dimensions, destination, route, date and expectations differ. Scenario planning explains the variables instead of selecting the anecdote that supports a preferred conclusion."], bullets: ["Lower realistic case", "Working expected case", "Higher uncertainty case", "Same destination", "Same date and route set"] },
    { h: "Rehearsal is for better inputs, not a guaranteed saving", p: ["The official estimator currently refers to a rehearsal-parcel service for refining weight and volume. Its purpose is better information: the warehouse can prepare the intended parcel configuration so the packed measurements are closer to the final submission. Whether it changes the price depends on the packaging outcome and the rules of the selected route.", "Use rehearsal when uncertainty is material, such as several shoe boxes, bulky outerwear or a parcel near a route threshold. Record what packaging instructions were requested and compare the resulting measurements with the earlier working case. Do not promise that rehearsal will reduce a charge. A smaller volume can help on some calculations, while actual-weight routes may respond differently."], bullets: ["Planned item set", "Packaging instructions", "Rehearsed weight", "Rehearsed dimensions", "Route recalculation"] },
    { h: "Packaging decisions involve trade-offs", p: ["Removing a retail box may reduce bulk but also removes structure and collector value. Vacuum packing can reduce soft-goods volume but may crease items. Protective corners, moisture protection or extra wrapping can increase weight and dimensions. The best choice depends on the item, route and your tolerance for damage or deformation.", "Write item-specific instructions rather than a broad request to make everything compact. Independent user reports include both successful compact packing and complaints that special packing requests were not followed exactly. Treat those accounts as signals to document the request and verify the resulting parcel inputs, not as proof that every future parcel will be handled the same way."], bullets: ["Retail packaging value", "Compression tolerance", "Protection needs", "Resulting dimensions", "Written instruction record"] },
    { h: "Check restrictions before combining items", p: ["LoveGoBuy’s estimator warns that cigarettes, alcohol and medicine are prohibited and flags other categories such as food and liquids for restrictions. The exact route treatment of batteries, electronics, cosmetics, branded goods and other sensitive items can vary. Check the live estimator and account warnings for the actual destination and parcel.", "A route shown for clothing may disappear when a restricted category is added. If the mixed parcel has few options, compare separate-parcel scenarios before paying. Do not copy a route name from a foreign destination or an older haul review. Availability is live data, and acceptance by an agent route does not remove destination-country import rules or customs discretion."], bullets: ["Prohibited category check", "Sensitive-item check", "Mixed-parcel route set", "Destination rules", "Current support guidance"] },
    { h: "Compare routes beyond the headline price", p: ["For each live route, record the calculation basis, accepted categories, tracking level, compensation or insurance terms shown, expected service window and exclusions. Do not add coverage that is not explicitly offered in the current transaction. A cheap route with an unsuitable restriction or weak handling fit is not automatically the best-value route.", "Transit estimates are planning ranges, not delivery guarantees. Processing before carrier acceptance, customs checks, remote-area handling, peak seasons and tracking gaps can change the observed timeline. Public reports on LoveGoBuy range from smooth delivery and useful updates to frustration with delays. Compare the live terms, then choose based on the cost of delay and loss for your parcel."], bullets: ["Calculation basis", "Accepted contents", "Tracking and service terms", "Current estimate", "Exclusions and destination fit"] },
    { h: "Run the estimator again at parcel submission", p: ["When the parcel is ready, replace every estimate with the current packed record. Confirm the destination, weight, dimensions, contents, packaging and address. Run the official estimator again and compare the result with the working and higher cases. A large difference should be explained before payment rather than dismissed as normal.", "Save the final input record, selected route, amount and date. After delivery, compare estimated and observed milestones, any adjustments and the condition of the packaging. This creates personal evidence for the next parcel. It also prevents one unusually cheap or expensive shipment from becoming a universal rule for LoveGoBuy shipping cost."], bullets: ["Final packed record", "Live route result", "Difference from plan", "Saved transaction evidence", "Post-delivery review"] },
  ],
};

const reviewGuide: ResearchArticle = {
  slug: "is-lovegobuy-legit-review-2026",
  title: "Is LoveGoBuy Legit? Evidence-Based Review for 2026",
  intro: "LoveGoBuy is an active shopping-agent service with a public website, product search, warehouse and parcel account states, a shipping estimator and a substantial body of public user feedback. Those are stronger signals than a landing page alone, but they do not make every order low-risk or every user report reliable. This review separates observable platform features from review-site statistics and individual anecdotes, then turns the mixed evidence into a practical test plan for a first order.",
  deck: "A balanced review based on observable workflow, a dated review snapshot and mixed independent reports.",
  readingTime: "11 min",
  sourceBasis: `Research basis: LoveGoBuy public workflow pages, Trustpilot profile snapshot (578 reviews), and recent independent Reddit review discussions containing both positive and negative reports. Checked ${checked}.`,
  published: "2026-08-31",
  modified: "2026-08-31",
  sections: [
    { h: "What legit can and cannot mean", p: ["For a shopping agent, legitimate should mean that an operating service exists, accepts source-item requests, records orders, receives warehouse items and offers international parcel handling. It should not be stretched to mean that every seller is reliable, every item matches, every route is cheap, every claim succeeds or every review is genuine. The marketplace seller, agent and carrier are separate risk points.", "LoveGoBuy has observable service infrastructure: a public search interface, product pages, account states for orders, warehouse and parcels, a shipping estimator, and current user activity. These features support the conclusion that it is an operating agent platform. They do not replace transaction-level checks. The useful question is therefore not only is the website real, but which risks can be verified before money moves to the next stage."], bullets: ["Operating website and account workflow", "Source purchase stage", "Warehouse evidence", "International parcel stage", "Transaction-specific support record"] },
    { h: "Observable facts from the official site", p: ["LoveGoBuy publicly positions itself for buying from Chinese marketplaces including Taobao, 1688 and Weidian. Its homepage currently exposes search by product name, link or photo. Product pages describe a seller-to-agent, warehouse and parcel sequence and currently mention several high-definition inspection photos. The account interface separates orders, warehouse records and parcels.", "The official shipping estimator asks for parcel inputs, notes that dimensions matter, references rehearsal-parcel service and warns about prohibited or restricted goods. These are concrete features that can be checked. This review does not treat promotional discounts, fixed storage periods, universal photo counts, route prices or delivery times as permanent facts because those values can be tied to an event, account, route or date."], bullets: ["Taobao, 1688 and Weidian positioning", "Name, link and photo search", "Order, warehouse and parcel states", "QC-photo workflow", "Shipping estimator and restriction warnings"] },
    { h: "What the Trustpilot snapshot shows", p: ["On 31 August 2026, Trustpilot displayed 578 reviews for lovegobuy.com, a 4.4 overall score, an 80 percent five-star share and a 13 percent one-star share. Trustpilot also stated that the company had no history of asking for reviews on that profile and warned that the reviews might not be representative. These figures are a dated snapshot, not a permanent rating.", "The distribution matters more than the headline. A large majority of high ratings coexists with a meaningful one-star minority. That pattern suggests many users report successful outcomes while a smaller group reports serious dissatisfaction. Review platforms cannot verify every order detail, and users have different destinations, products and expectations. Use the snapshot to identify recurring themes, not to calculate the probability that your order will succeed."], bullets: ["578 displayed reviews", "4.4 overall display", "80% five-star share", "13% one-star share", "Representativeness warning"] },
    { h: "Positive themes in recent public feedback", p: ["Recent positive Trustpilot reviews commonly mention an easy process, responsive support, products arriving as expected, useful photos and acceptable shipping experience. Independent Reddit comments also include users describing multiple successful parcels, friendly communication and workable packing. These are individual reports rather than audited performance statistics.", "The most useful positive signal is not a superlative such as best agent. It is a detailed report that names the parcel, destination, stage and outcome. A review explaining that support answered a warehouse question is more informative than a five-star line with no order context. When reading feedback, prefer dated accounts with photos, parcel weights or specific workflow details, while still treating them as one user’s experience."], bullets: ["Process clarity", "Support responsiveness", "QC usefulness", "Parcel handling", "Delivered-order evidence"] },
    { h: "Negative themes deserve equal attention", p: ["Negative public reports raise issues including slow QC or warehouse processing, inconsistent photo angles, packing instructions not followed, shipping cost frustration, delayed support and disputes around refunds or wallet balances. Some posts use strong labels such as scam, but the underlying claims are individual and often cannot be independently verified from the post alone.", "Do not dismiss these reports because the average rating is high, and do not generalize them to every transaction. Convert them into controls: save order notes, keep screenshots of balances and statuses, request necessary evidence before parcel submission, compare packed inputs with estimates, and use current official support channels with identifiers. A risk theme is valuable when it changes your process."], bullets: ["Processing delays", "QC inconsistency", "Packing execution", "Shipping expectation gaps", "Refund or balance disputes"] },
    { h: "QC quality appears variable, so use your own standard", p: ["One recent independent review rated the supplied QC evidence as inconsistent in angle and standardization, while other public reviewers praised photo quality. Those positions can both describe different items or periods. The official product-page wording confirms that inspection photos are part of the workflow, but it does not guarantee that every default set will answer the same category-specific questions.", "Create a checklist before the item arrives. Confirm identity, option, completeness, visible condition and necessary measurements. Mark questions answered, unclear or missing. If a blocking detail is absent, use the account’s current options while the item remains in the warehouse. This turns platform variability into a transaction-level decision instead of relying on a global QC rating."], bullets: ["Identity first", "Category-specific views", "Measurements", "Missing-evidence state", "Dated approval record"] },
    { h: "Shipping reviews are not directly comparable", p: ["Public feedback ranges from buyers who considered shipping fair and delivery smooth to buyers who felt parcel cost approached the value of the goods or did not change as expected after rehearsal. Weight alone cannot reconcile these stories. Destination, dimensions, retained boxes, route rules, date, restricted contents and promotional conditions can all change the result.", "Use the official estimator with a lower, working and higher packed scenario. When actual warehouse inputs become available, replace the estimate. If rehearsal is used, compare the new measurements and live route calculation rather than assuming a discount. Save the result at payment. This process is more reliable than copying a cost-per-kilogram figure from a review written for another parcel."], bullets: ["Destination", "Packed weight and dimensions", "Packaging choice", "Route and date", "Live final calculation"] },
    { h: "Refund and support risk should be documented early", p: ["LoveGoBuy’s account search results include refund and return states, showing that these processes exist in the interface. That does not establish the eligibility, timing or payment destination for a specific case. Public comments include both users who report successful cancellation or refund handling and users who describe long waits or difficulty moving wallet funds.", "Before ordering, read the current terms shown for the item and account. Preserve the source listing, selected option, payment record, status changes and support messages. Ask precise questions tied to an order identifier. If access to funds, return eligibility or a deadline is material, confirm it in the current official workflow before relying on an old forum answer. Do not make a large first order that depends on a disputed policy interpretation."], bullets: ["Current eligibility", "Payment and balance record", "Status history", "Support case identifier", "Deadline evidence"] },
    { h: "A sensible verdict: operating service, transaction-level caution", p: ["The available evidence supports describing LoveGoBuy as an operating shopping-agent platform rather than a fictitious storefront. Its official workflow is visible, and many public users report completed orders. The same evidence also shows a non-trivial body of complaints about service consistency, delays, shipping expectations and resolution. A balanced review should preserve both facts.", "For a first use, choose one or two low-risk items with clear options, keep the parcel small, capture every stage and avoid time-sensitive purchases. Verify source, QC, packed inputs and route before each payment. Judge the platform using your documented test order, not only a rating, influencer link or isolated accusation. That conclusion is less dramatic than a yes-or-no headline, but it is more useful for an actual buying decision."], bullets: ["Start small", "Avoid deadline-critical goods", "Save every stage", "Resolve unknowns before parcel", "Scale only after observed delivery"] },
  ],
};

export const researchArticles: ResearchArticle[] = [
  spreadsheet,
  howToBuy,
  qcGuide,
  shippingGuide,
  reviewGuide,
];

export const articleSlugs = researchArticles.map((article) => article.slug);

export function getArticle(slug: string, lang: Lang = "en") {
  const article = researchArticles.find((item) => item.slug === slug);
  if (!article || lang === "en") return article;
  const translation = articleTranslations[lang][slug];
  return translation ? { ...article, ...translation } : undefined;
}

export function getResearchArticles(lang: Lang) {
  return researchArticles
    .map((article) => getArticle(article.slug, lang))
    .filter((article): article is ResearchArticle => Boolean(article));
}
