import { copy, type Lang } from "./site-data";

export type Topic = {
  title: string;
  intro: string;
  sections: { h: string; p: string[]; bullets?: string[] }[];
};

const finds: Record<Lang, Topic> = {
  en: { title: "LoveGoBuy finds: build a shortlist that survives checking", intro: "A useful find is not a picture, a price or a popular label. It is a route whose destination, option, evidence and likely parcel impact can still be explained after the excitement is removed.", sections: [
    { h: "Start with one product lane", p: ["Mixed spreadsheets encourage weak comparisons. A jacket should be compared with jackets that answer the same sizing and construction questions; a shoe should be checked for profile, sole, symmetry and size context.", "Open one category, collect no more than three plausible candidates, and record why each one deserves another click."] },
    { h: "Confirm the route before the product", p: ["Match the spreadsheet label to the destination title, selected variant and first image. A converted link is only a transport mechanism; it does not prove that the destination still matches.", "If the option changes, the images are reused or the source page is unavailable, mark the gap instead of inventing certainty."] },
    { h: "Keep evidence beside the link", p: ["Write down the visible price date, expected item weight, useful measurements, missing views and the source marketplace. This makes future rechecking faster and exposes when an old row has stopped being useful."], bullets: ["Exact product and option", "Current source destination", "Useful QC or listing photos", "Measurements relevant to the category", "Likely packed weight and dimensions"] },
  ]},
  de: { title: "LoveGoBuy-Funde: eine Auswahl, die Prüfungen standhält", intro: "Ein guter Fund ist nicht nur Bild, Preis oder beliebtes Etikett. Er ist eine Route, deren Ziel, Variante, Belege und Paketwirkung auch nach genauer Prüfung erklärbar bleiben.", sections: [
    { h: "Mit einer Produktkategorie beginnen", p: ["Gemischte Tabellen fördern schlechte Vergleiche. Jacken gehören neben Jacken mit denselben Größen- und Verarbeitungsfragen; Schuhe brauchen Profil, Sohle, Symmetrie und Größenbezug.", "Öffne eine Kategorie, sammle höchstens drei Kandidaten und notiere, warum jeder einen weiteren Klick verdient."] },
    { h: "Erst die Route, dann das Produkt", p: ["Vergleiche Tabellenbezeichnung, Zieltitel, gewählte Variante und erstes Bild. Ein konvertierter Link beweist keine Übereinstimmung.", "Wenn Optionen wechseln, Bilder wiederverwendet werden oder die Quelle fehlt, notiere die Lücke statt Sicherheit vorzutäuschen."] },
    { h: "Belege beim Link speichern", p: ["Notiere Preisdatum, erwartetes Gewicht, sinnvolle Maße, fehlende Ansichten und Quellplattform. So werden spätere Prüfungen schneller."], bullets: ["Exaktes Produkt und Variante", "Aktuelles Quellenziel", "Nützliche QC- oder Angebotsbilder", "Kategoriespezifische Maße", "Wahrscheinliches Packgewicht und Maße"] },
  ]},
  es: { title: "Hallazgos LoveGoBuy: una selección que resiste la revisión", intro: "Un hallazgo útil no es solo una foto, un precio o una etiqueta popular. Es una ruta cuyo destino, variante, pruebas e impacto en el paquete siguen siendo explicables tras revisarla.", sections: [
    { h: "Empieza por una categoría", p: ["Las hojas mezcladas provocan comparaciones débiles. Compara chaquetas con chaquetas y zapatillas con opciones que respondan a las mismas preguntas de forma, suela, simetría y talla.", "Abre una categoría, reúne un máximo de tres candidatos y anota por qué cada uno merece otro clic."] },
    { h: "Confirma la ruta antes que el producto", p: ["Compara la etiqueta, el título de destino, la variante y la primera imagen. Un enlace convertido no demuestra coincidencia.", "Si cambia la opción, se reutilizan imágenes o falta la fuente, registra el vacío sin inventar certeza."] },
    { h: "Guarda las pruebas junto al enlace", p: ["Anota fecha del precio, peso esperado, medidas útiles, vistas ausentes y mercado de origen. Así detectarás antes una fila obsoleta."], bullets: ["Producto y variante exactos", "Destino actual", "Fotos útiles", "Medidas relevantes", "Peso y dimensiones probables"] },
  ]},
  fr: { title: "Trouvailles LoveGoBuy : une sélection qui résiste aux vérifications", intro: "Une trouvaille utile n'est ni une photo, ni un prix, ni une étiquette populaire. C'est une route dont la destination, l'option, les preuves et l'impact sur le colis restent explicables après contrôle.", sections: [
    { h: "Commencer par une catégorie", p: ["Les tableaux mélangés produisent de mauvaises comparaisons. Comparez les vestes entre elles et les chaussures selon les mêmes questions de profil, semelle, symétrie et pointure.", "Ouvrez une catégorie, gardez au maximum trois candidats et notez pourquoi chacun mérite un clic supplémentaire."] },
    { h: "Confirmer la route avant le produit", p: ["Faites correspondre libellé, titre de destination, option et première image. Un lien converti ne prouve pas la correspondance.", "Si l'option change, si les images sont réutilisées ou si la source manque, notez le doute au lieu d'inventer une certitude."] },
    { h: "Conserver les preuves avec le lien", p: ["Notez la date du prix, le poids prévu, les mesures utiles, les vues manquantes et la place de marché source. Une ligne périmée devient alors visible."], bullets: ["Produit et option exacts", "Destination actuelle", "Photos utiles", "Mesures pertinentes", "Poids et dimensions probables"] },
  ]},
  it: { title: "Prodotti LoveGoBuy: una selezione che supera i controlli", intro: "Un buon prodotto non è solo una foto, un prezzo o un'etichetta popolare. È un percorso la cui destinazione, variante, prove e impatto sul pacco restano spiegabili dopo il controllo.", sections: [
    { h: "Inizia da una categoria", p: ["I fogli misti favoriscono confronti deboli. Confronta giacche con giacche e scarpe secondo le stesse domande su profilo, suola, simmetria e taglia.", "Apri una categoria, raccogli al massimo tre candidati e annota perché ciascuno merita un altro clic."] },
    { h: "Conferma il percorso prima del prodotto", p: ["Abbina etichetta, titolo di destinazione, variante e prima immagine. Un link convertito non dimostra la corrispondenza.", "Se cambia l'opzione, le immagini sono riutilizzate o manca la fonte, registra il dubbio senza inventare certezze."] },
    { h: "Conserva le prove accanto al link", p: ["Annota data del prezzo, peso previsto, misure utili, viste mancanti e marketplace di origine. In questo modo una riga obsoleta diventa evidente."], bullets: ["Prodotto e variante esatti", "Destinazione attuale", "Foto utili", "Misure pertinenti", "Peso e dimensioni probabili"] },
  ]},
};

const guide: Record<Lang, Topic> = {
  en: { title: "How to use a LoveGoBuy spreadsheet from search to shortlist", intro: "The job of a spreadsheet is to reduce uncertainty. Use this repeatable workflow to move from a broad query to a small group of candidates that can be checked again later.", sections: [
    { h: "Write the decision before searching", p: ["Define product type, intended use, size needs, budget for the item and realistic tolerance for shipping weight. A precise brief prevents attractive but irrelevant rows from taking over the search."], bullets: ["Product category and use", "Measurements from an item that already fits", "Maximum item budget", "Destination country", "Packaging or size sensitivities"] },
    { h: "Compare like with like", p: ["Open three candidates from the same category. Check whether the destination, selected option and first image match. Then compare measurements, photo coverage and source clarity.", "Remove a candidate as soon as a necessary question cannot be answered. A smaller set with clear evidence is more useful than a long list of uncertain links."] },
    { h: "Recheck at the handoff", p: ["Before ordering, open the live destination again. Prices, variants, seller pages and route availability can change. Use the current official checkout and account pages for transaction-specific terms."] },
  ]},
  de: { title: "LoveGoBuy-Tabelle: von der Suche zur Auswahlliste", intro: "Eine Tabelle soll Unsicherheit reduzieren. Dieser wiederholbare Ablauf führt von einer breiten Suche zu wenigen Kandidaten, die später erneut geprüft werden können.", sections: [
    { h: "Entscheidung vor der Suche definieren", p: ["Lege Produkttyp, Einsatzzweck, Maße, Artikelbudget und realistische Gewichtstoleranz fest. Ein klares Briefing verhindert irrelevante Funde."], bullets: ["Kategorie und Zweck", "Maße eines gut passenden Artikels", "Maximales Artikelbudget", "Zielland", "Verpackungs- oder Größenrisiken"] },
    { h: "Gleiches mit Gleichem vergleichen", p: ["Öffne drei Kandidaten derselben Kategorie. Prüfe Zielseite, Variante und erstes Bild, danach Maße, Fotoabdeckung und Quellenklarheit.", "Entferne Kandidaten, sobald eine notwendige Frage unbeantwortet bleibt. Wenige klare Belege sind besser als viele unsichere Links."] },
    { h: "Beim Übergang erneut prüfen", p: ["Öffne vor der Bestellung die Live-Seite erneut. Preise, Varianten, Verkäuferseiten und Routen ändern sich. Transaktionsbedingungen gehören auf die aktuelle offizielle Konto- oder Checkout-Seite."] },
  ]},
  es: { title: "Cómo usar una hoja LoveGoBuy desde la búsqueda hasta la selección", intro: "La función de una hoja es reducir la incertidumbre. Este proceso repetible lleva una búsqueda amplia a pocos candidatos que pueden revisarse de nuevo.", sections: [
    { h: "Define la decisión antes de buscar", p: ["Fija tipo de producto, uso, talla, presupuesto del artículo y tolerancia realista al peso. Un objetivo preciso evita filas atractivas pero irrelevantes."], bullets: ["Categoría y uso", "Medidas de una prenda que ya sirve", "Presupuesto máximo", "País de destino", "Riesgos de tamaño o embalaje"] },
    { h: "Compara elementos equivalentes", p: ["Abre tres candidatos de la misma categoría. Verifica destino, opción e imagen y después compara medidas, cobertura fotográfica y claridad de la fuente.", "Descarta un candidato cuando una pregunta necesaria no tenga respuesta. Tres opciones claras valen más que una lista larga e incierta."] },
    { h: "Vuelve a comprobar antes de pedir", p: ["Abre de nuevo la página en vivo. Precios, variantes, vendedor y rutas cambian. Para condiciones de la transacción usa las páginas oficiales actuales de cuenta y pago."] },
  ]},
  fr: { title: "Utiliser un tableau LoveGoBuy de la recherche à la sélection", intro: "Le rôle d'un tableau est de réduire l'incertitude. Ce processus reproductible transforme une recherche large en quelques candidats vérifiables.", sections: [
    { h: "Définir la décision avant la recherche", p: ["Précisez type de produit, usage, mesures, budget article et tolérance réaliste au poids. Un brief précis écarte les lignes séduisantes mais inutiles."], bullets: ["Catégorie et usage", "Mesures d'un article qui vous va", "Budget article maximal", "Pays de destination", "Risques de taille ou d'emballage"] },
    { h: "Comparer des éléments équivalents", p: ["Ouvrez trois candidats de la même catégorie. Vérifiez destination, option et première image, puis mesures, couverture photo et clarté de la source.", "Écartez un candidat dès qu'une question essentielle reste sans réponse. Quelques preuves claires valent mieux qu'une longue liste incertaine."] },
    { h: "Revérifier au moment du transfert", p: ["Rouvrez la page en direct avant de commander. Prix, options, vendeurs et routes changent. Les conditions de transaction doivent être vérifiées dans le compte ou le paiement officiel actuel."] },
  ]},
  it: { title: "Usare un foglio LoveGoBuy dalla ricerca alla selezione", intro: "Il compito di un foglio è ridurre l'incertezza. Questo processo porta da una ricerca ampia a pochi candidati che possono essere ricontrollati.", sections: [
    { h: "Definisci la decisione prima della ricerca", p: ["Stabilisci tipo di prodotto, uso, misure, budget articolo e tolleranza realistica al peso. Un obiettivo preciso elimina le righe attraenti ma irrilevanti."], bullets: ["Categoria e uso", "Misure di un articolo che veste bene", "Budget massimo", "Paese di destinazione", "Rischi di dimensione o imballaggio"] },
    { h: "Confronta elementi equivalenti", p: ["Apri tre candidati della stessa categoria. Controlla destinazione, opzione e prima immagine, poi misure, copertura fotografica e chiarezza della fonte.", "Elimina un candidato appena manca una risposta necessaria. Poche prove chiare valgono più di molti link incerti."] },
    { h: "Ricontrolla prima dell'ordine", p: ["Riapri la pagina live. Prezzi, varianti, venditore e rotte cambiano. Per le condizioni della transazione usa le pagine ufficiali aggiornate di account e checkout."] },
  ]},
};

const qc: Record<Lang, Topic> = {
  en: { title: "LoveGoBuy QC photo guide: what each image must answer", intro: "QC photos are evidence about visible condition at one moment. They help identify mismatches and missing details, but they do not guarantee authenticity, comfort, durability or final delivery condition.", sections: [
    { h: "Pass one: identity", p: ["Match the photographed item to the ordered title, color, size and option. Look for packaging labels or a visible order reference when available. Reused or ambiguous photos should be treated as unresolved."], bullets: ["Correct model and color", "Correct size or selected option", "Both sides or pieces present", "No unexplained variant change"] },
    { h: "Pass two: construction", p: ["Use category-specific questions. Shoes need profile, sole, heel and symmetry; clothing needs seams, print or embroidery, collar, cuffs and closures; bags need hardware, interior and strap attachment.", "A large photo count can still be weak when every image repeats the same flattering angle."] },
    { h: "Pass three: fit or scale", p: ["For clothing, compare clear flat measurements with an item you already own. For bags, accessories and electronics, request a useful scale reference where dimensions matter. A generic size chart is not the same as measuring the photographed item."] },
    { h: "Decide before parcel submission", p: ["If a critical angle or measurement is missing, resolve it while the item is still in the warehouse. Once parcel handling begins, options may be more limited. Use the current account workflow for any request, return or exchange terms."] },
  ]},
  de: { title: "LoveGoBuy-QC-Fotos: Welche Frage jedes Bild beantworten muss", intro: "QC-Fotos zeigen den sichtbaren Zustand zu einem bestimmten Zeitpunkt. Sie helfen bei Abweichungen, garantieren aber weder Echtheit, Komfort, Haltbarkeit noch Lieferzustand.", sections: [
    { h: "Prüfung eins: Identität", p: ["Vergleiche fotografierten Artikel mit Titel, Farbe, Größe und Variante der Bestellung. Verpackungsetiketten oder Bestellbezug sind hilfreich. Mehrdeutige Bilder bleiben ungeklärt."], bullets: ["Richtiges Modell und Farbe", "Richtige Größe oder Option", "Alle Teile vorhanden", "Kein unerklärter Variantenwechsel"] },
    { h: "Prüfung zwei: Verarbeitung", p: ["Nutze produktspezifische Fragen. Schuhe brauchen Profil, Sohle, Ferse und Symmetrie; Kleidung Nähte, Druck, Kragen, Bündchen und Verschlüsse; Taschen Hardware, Innenraum und Riemenbefestigung.", "Viele Fotos sind trotzdem schwach, wenn sie denselben vorteilhaften Winkel wiederholen."] },
    { h: "Prüfung drei: Passform oder Maßstab", p: ["Vergleiche flache Kleidungsmaße mit einem passenden eigenen Artikel. Bei Taschen, Zubehör und Elektronik braucht es einen sinnvollen Größenbezug. Eine allgemeine Tabelle misst nicht das fotografierte Stück."] },
    { h: "Vor der Paketeinreichung entscheiden", p: ["Fehlende kritische Ansichten oder Maße sollten geklärt werden, solange der Artikel im Lager liegt. Nutze den aktuellen Kontoablauf für Anfragen, Rückgaben oder Umtauschbedingungen."] },
  ]},
  es: { title: "Guía de fotos QC LoveGoBuy: qué debe responder cada imagen", intro: "Las fotos QC muestran el estado visible en un momento. Ayudan a detectar diferencias, pero no garantizan autenticidad, comodidad, duración ni condición final de entrega.", sections: [
    { h: "Primera revisión: identidad", p: ["Compara el artículo fotografiado con título, color, talla y opción del pedido. Las etiquetas o referencias visibles ayudan. Una foto ambigua queda sin resolver."], bullets: ["Modelo y color correctos", "Talla u opción correctas", "Todas las piezas presentes", "Sin cambio de variante inexplicable"] },
    { h: "Segunda revisión: construcción", p: ["Usa preguntas de la categoría. Calzado: perfil, suela, talón y simetría. Ropa: costuras, impresión, cuello, puños y cierres. Bolsos: herrajes, interior y uniones.", "Muchas fotos siguen siendo débiles si repiten el mismo ángulo favorable."] },
    { h: "Tercera revisión: ajuste o escala", p: ["Compara medidas planas con una prenda propia. Para bolsos, accesorios y electrónica pide una referencia útil. Una tabla genérica no mide el artículo fotografiado."] },
    { h: "Decide antes de enviar el paquete", p: ["Resuelve ángulos o medidas críticas mientras el artículo siga en el almacén. Usa el flujo actual de la cuenta para solicitudes, devoluciones o cambios."] },
  ]},
  fr: { title: "Guide des photos QC LoveGoBuy : ce que chaque image doit répondre", intro: "Les photos QC documentent un état visible à un moment donné. Elles révèlent des écarts mais ne garantissent ni authenticité, confort, durabilité ou état final à la livraison.", sections: [
    { h: "Premier passage : identité", p: ["Comparez l'article photographié au titre, à la couleur, à la taille et à l'option commandés. Étiquettes et références visibles aident. Une photo ambiguë reste non résolue."], bullets: ["Bon modèle et bonne couleur", "Bonne taille ou option", "Toutes les pièces présentes", "Aucun changement inexpliqué"] },
    { h: "Deuxième passage : construction", p: ["Posez les questions de la catégorie. Chaussures : profil, semelle, talon, symétrie. Vêtements : coutures, impression, col, poignets, fermetures. Sacs : quincaillerie, intérieur, attaches.", "Un grand nombre d'images reste faible si toutes répètent le même angle flatteur."] },
    { h: "Troisième passage : taille ou échelle", p: ["Comparez les mesures à plat avec un vêtement qui vous va. Pour sacs, accessoires et électronique, utilisez une référence d'échelle. Un tableau générique ne mesure pas l'objet photographié."] },
    { h: "Décider avant le colis", p: ["Résolvez les angles ou mesures critiques pendant que l'article est encore à l'entrepôt. Utilisez le parcours de compte actuel pour demandes, retours ou échanges."] },
  ]},
  it: { title: "Guida foto QC LoveGoBuy: cosa deve mostrare ogni immagine", intro: "Le foto QC documentano una condizione visibile in un momento. Aiutano a trovare differenze, ma non garantiscono autenticità, comfort, durata o condizioni finali di consegna.", sections: [
    { h: "Primo controllo: identità", p: ["Abbina l'articolo fotografato a titolo, colore, taglia e opzione ordinati. Etichette o riferimenti visibili aiutano. Una foto ambigua resta irrisolta."], bullets: ["Modello e colore corretti", "Taglia o opzione corrette", "Tutti i pezzi presenti", "Nessun cambio inspiegabile"] },
    { h: "Secondo controllo: costruzione", p: ["Usa domande specifiche. Scarpe: profilo, suola, tallone, simmetria. Abbigliamento: cuciture, stampa, collo, polsi, chiusure. Borse: ferramenta, interno, attacchi.", "Molte foto restano deboli se ripetono lo stesso angolo favorevole."] },
    { h: "Terzo controllo: vestibilità o scala", p: ["Confronta misure piane con un capo che possiedi. Per borse, accessori ed elettronica usa un riferimento di scala. Una tabella generica non misura l'oggetto fotografato."] },
    { h: "Decidi prima del pacco", p: ["Risolvi angoli o misure critiche mentre l'articolo è in magazzino. Usa il flusso account aggiornato per richieste, resi o cambi."] },
  ]},
};

const shipping: Record<Lang, Topic> = {
  en: { title: "LoveGoBuy shipping planning: weight, volume, route and destination", intro: "Product price is only one part of the decision. Shipping becomes clearer when item weight, packed dimensions, destination and a currently available route are kept separate instead of compressed into one guess.", sections: [
    { h: "Separate item weight from chargeable weight", p: ["The product index may show an item-weight estimate. The parcel can include boxes, protective materials and consolidation packaging. Some routes charge by actual weight; others may use dimensional or volumetric rules.", "Do not turn a historical example into a promise. Use the current official estimator with the current route rules."] },
    { h: "Build three planning cases", p: ["A lower case uses the lightest realistic packaging that is actually available. A working case uses expected packed weight and measured dimensions. A higher case accounts for bulky packaging or uncertain measurements."], bullets: ["Item weight and date", "Expected packaging", "Packed length, width and height", "Destination country", "Available route and restrictions"] },
    { h: "Compare total landed decisions", p: ["A lower-priced bulky item can be worse value than a slightly higher-priced compact alternative. Keep product cost, domestic movement, optional services, international shipping and possible destination charges as separate lines."] },
    { h: "Use live official data at the final step", p: ["Rates, routes, restrictions, coupons and processing conditions can change. Recheck them when the parcel is ready, and use official support for account-specific tracking, refunds or claims."] },
  ]},
  de: { title: "LoveGoBuy-Versand planen: Gewicht, Volumen, Route und Ziel", intro: "Der Produktpreis ist nur ein Teil der Entscheidung. Trenne Artikelgewicht, Packmaße, Ziel und aktuell verfügbare Route, statt alles in eine Schätzung zu pressen.", sections: [
    { h: "Artikelgewicht und Abrechnungsgewicht trennen", p: ["Der Index kann ein Artikelgewicht zeigen. Kartons, Schutzmaterial und Sammelverpackung kommen hinzu. Manche Routen rechnen nach Ist-Gewicht, andere nach Volumenregeln.", "Historische Beispiele sind keine Versprechen. Nutze den aktuellen offiziellen Rechner."] },
    { h: "Drei Planungsfälle bilden", p: ["Der niedrige Fall nutzt die leichteste real verfügbare Verpackung. Der Arbeitsfall nutzt erwartetes Packgewicht und gemessene Maße. Der hohe Fall berücksichtigt sperrige Verpackung oder unsichere Maße."], bullets: ["Artikelgewicht und Datum", "Erwartete Verpackung", "Länge, Breite, Höhe", "Zielland", "Verfügbare Route und Einschränkungen"] },
    { h: "Gesamtentscheidung vergleichen", p: ["Ein billiger, sperriger Artikel kann schlechter sein als eine kompakte Alternative. Halte Artikelpreis, Inlandsbewegung, Zusatzdienste, internationalen Versand und mögliche Zielkosten getrennt."] },
    { h: "Am Ende Live-Daten nutzen", p: ["Preise, Routen, Regeln, Gutscheine und Bearbeitung ändern sich. Prüfe sie beim fertigen Paket erneut und nutze offiziellen Support für Tracking, Erstattung oder Reklamation."] },
  ]},
  es: { title: "Planificar el envío LoveGoBuy: peso, volumen, ruta y destino", intro: "El precio del producto es solo una parte. Separa peso del artículo, dimensiones embaladas, destino y ruta disponible en vez de resumir todo en una cifra.", sections: [
    { h: "Separa peso del artículo y peso facturable", p: ["El índice puede mostrar un peso estimado. Cajas, protección y consolidación lo aumentan. Algunas rutas cobran peso real y otras aplican reglas volumétricas.", "Un ejemplo histórico no es una promesa. Usa el estimador oficial actual."] },
    { h: "Construye tres escenarios", p: ["El bajo usa el embalaje real más ligero disponible. El de trabajo usa peso y medidas esperados. El alto contempla embalaje voluminoso o medidas inciertas."], bullets: ["Peso y fecha", "Embalaje esperado", "Largo, ancho y alto", "País de destino", "Ruta y restricciones actuales"] },
    { h: "Compara el coste total", p: ["Un producto barato y voluminoso puede ser peor que uno compacto. Separa coste del artículo, movimiento nacional, servicios opcionales, envío internacional y posibles cargos de destino."] },
    { h: "Usa datos oficiales en vivo al final", p: ["Tarifas, rutas, restricciones, cupones y procesos cambian. Revísalos cuando el paquete esté listo y usa soporte oficial para casos de cuenta."] },
  ]},
  fr: { title: "Planifier la livraison LoveGoBuy : poids, volume, route et destination", intro: "Le prix du produit n'est qu'une partie de la décision. Séparez poids de l'article, dimensions emballées, destination et route disponible plutôt que de tout réduire à une estimation.", sections: [
    { h: "Séparer poids article et poids facturé", p: ["L'index peut afficher un poids estimé. Boîtes, protection et consolidation l'augmentent. Certaines routes facturent le poids réel, d'autres appliquent une règle volumétrique.", "Un exemple ancien n'est pas une promesse. Utilisez l'estimateur officiel actuel."] },
    { h: "Construire trois scénarios", p: ["Le cas bas utilise l'emballage réellement disponible le plus léger. Le cas de travail utilise poids et mesures attendus. Le cas haut prévoit un emballage volumineux ou des mesures incertaines."], bullets: ["Poids et date", "Emballage prévu", "Longueur, largeur, hauteur", "Pays de destination", "Route et restrictions actuelles"] },
    { h: "Comparer la décision totale", p: ["Un article bon marché mais volumineux peut être moins intéressant qu'une alternative compacte. Séparez prix, mouvement national, services, livraison internationale et frais possibles à destination."] },
    { h: "Utiliser les données officielles en direct", p: ["Tarifs, routes, restrictions, coupons et traitement changent. Revérifiez quand le colis est prêt et utilisez le support officiel pour les cas de compte."] },
  ]},
  it: { title: "Pianificare la spedizione LoveGoBuy: peso, volume, rotta e destinazione", intro: "Il prezzo del prodotto è solo una parte. Separa peso articolo, dimensioni imballate, destinazione e rotta disponibile invece di ridurre tutto a una stima.", sections: [
    { h: "Separa peso articolo e peso addebitabile", p: ["L'indice può mostrare un peso stimato. Scatole, protezione e consolidamento lo aumentano. Alcune rotte usano il peso reale, altre regole volumetriche.", "Un esempio storico non è una promessa. Usa lo stimatore ufficiale aggiornato."] },
    { h: "Costruisci tre scenari", p: ["Il caso basso usa l'imballaggio reale più leggero. Il caso di lavoro usa peso e misure previsti. Il caso alto considera imballaggi voluminosi o misure incerte."], bullets: ["Peso e data", "Imballaggio previsto", "Lunghezza, larghezza, altezza", "Paese di destinazione", "Rotta e restrizioni attuali"] },
    { h: "Confronta la decisione totale", p: ["Un prodotto economico ma voluminoso può convenire meno di uno compatto. Separa prezzo, movimento nazionale, servizi, spedizione internazionale e possibili costi a destinazione."] },
    { h: "Usa dati ufficiali live alla fine", p: ["Tariffe, rotte, restrizioni, coupon e processi cambiano. Ricontrolla quando il pacco è pronto e usa l'assistenza ufficiale per casi specifici dell'account."] },
  ]},
};

export const topics = { finds, guide, qc, shipping };
export const longArticleSlug = "lovegobuy-spreadsheet-research-workflow";

export function longArticle(lang: Lang): Topic {
  const extra: Record<Lang, Topic["sections"]> = {
    en: [
      { h: "Why spreadsheet size is a weak quality signal", p: ["A sheet can contain thousands of rows and still waste time if products are duplicated, destinations no longer match, images come from the wrong option or sizing notes are missing. Count measures inventory, not usefulness.", "A stronger evaluation samples a category and tests real rows. Open several destinations, check that the product and option match, then note how many rows answer the questions needed for a decision. This produces evidence you can repeat rather than a claim based on a headline number."] },
      { h: "Read source links as a handoff", p: ["Taobao, Weidian, 1688 and other source pages can change independently of a spreadsheet. A route may be reformatted or converted for an agent, but conversion does not verify the seller, item, option or availability.", "At the handoff, compare the spreadsheet label with the destination title, first image, selected color or model, displayed price and seller context. If the source is unavailable, treat that row as unresolved. Do not replace missing facts with details from a similar-looking item."] },
      { h: "Use category-specific evidence", p: ["For shoes, useful evidence includes side profile, toe shape, heel alignment, sole, size label and a length measurement when fit is uncertain. For clothing, check construction, print or embroidery, closures and flat measurements. For bags, inspect scale, interior, hardware and strap attachment.", "This approach is more reliable than a single universal verified badge. Verification should state what was checked and when. A destination match does not verify material; a clear photo does not verify comfort; a measurement does not guarantee the intended fit."] },
      { h: "Add shipping before ranking candidates", p: ["A spreadsheet usually presents product price first, but parcel cost may change the comparison. Record the available item-weight estimate, then distinguish it from expected packed weight. Boxes, protective materials and consolidation packaging can matter, especially for footwear, bags and bulky jackets.", "Use current packed dimensions, destination and an available route in the official estimator. Keep the date with the result. A static guide should explain the inputs and trade-offs, not promise a universal cost or delivery time."] },
      { h: "Create a recheckable decision record", p: ["Save the destination URL, product or option identifier, date checked, visible price, useful measurements, unresolved questions and expected shipping case. A short note makes it easier to detect when a seller page or spreadsheet row has changed.", "Before the final handoff, reopen every candidate. Remove anything that no longer matches. The winning row is not necessarily the cheapest or most popular; it is the one whose identity, evidence, fit context and parcel impact are clear enough for the decision you are making."] },
    ],
    de: [
      { h: "Warum die Tabellenlänge wenig über Qualität sagt", p: ["Tausende Zeilen helfen nicht, wenn Produkte doppelt sind, Ziele nicht mehr passen, Bilder zur falschen Variante gehören oder Größenangaben fehlen. Die Anzahl misst Bestand, nicht Nutzen.", "Teste stattdessen echte Zeilen einer Kategorie. Öffne Ziele, gleiche Produkt und Option ab und notiere, wie viele Zeilen die notwendigen Entscheidungsfragen beantworten."] },
      { h: "Quellenlinks als Übergabe lesen", p: ["Taobao-, Weidian- und 1688-Seiten ändern sich unabhängig von Tabellen. Eine Konvertierung prüft weder Verkäufer, Artikel, Variante noch Verfügbarkeit.", "Vergleiche beim Übergang Tabellenbezeichnung, Zieltitel, erstes Bild, gewählte Variante, sichtbaren Preis und Verkäuferkontext. Eine nicht erreichbare Quelle bleibt ungeklärt."] },
      { h: "Kategoriespezifische Belege nutzen", p: ["Bei Schuhen zählen Profil, Zehenform, Ferse, Sohle, Größenetikett und gegebenenfalls Innenlänge. Kleidung braucht Verarbeitung, Druck, Verschlüsse und flache Maße. Taschen brauchen Maßstab, Innenraum, Hardware und Riemenbefestigung.", "Ein einzelnes Verified-Siegel ersetzt diese Arbeit nicht. Jede Prüfung sollte sagen, was wann geprüft wurde."] },
      { h: "Versand vor der Rangfolge einbeziehen", p: ["Der Artikelpreis steht meist zuerst, doch Paketkosten können den Vergleich drehen. Trenne angezeigtes Artikelgewicht von erwartetem Packgewicht. Kartons und Schutzmaterial zählen besonders bei Schuhen, Taschen und Jacken.", "Nutze aktuelle Maße, Zielland und verfügbare Route im offiziellen Rechner. Eine statische Anleitung erklärt Eingaben, verspricht aber keine festen Kosten oder Zeiten."] },
      { h: "Eine erneut prüfbare Entscheidung speichern", p: ["Speichere Ziel-URL, Artikel- oder Optionskennung, Prüfdatum, sichtbaren Preis, Maße, offene Fragen und Versandfall. So fallen spätere Änderungen auf.", "Öffne vor der Übergabe jeden Kandidaten erneut. Gewinner ist nicht automatisch der billigste, sondern der mit klarer Identität, Belegen, Passformkontext und Paketwirkung."] },
    ],
    es: [
      { h: "Por qué el tamaño de la hoja no demuestra calidad", p: ["Miles de filas sirven poco si hay duplicados, destinos desactualizados, imágenes de otra variante o falta de tallas. El número mide inventario, no utilidad.", "Prueba filas reales de una categoría. Abre destinos, comprueba producto y opción y cuenta cuántas filas responden a las preguntas necesarias."] },
      { h: "Lee los enlaces fuente como una entrega", p: ["Taobao, Weidian y 1688 cambian por separado. Convertir una ruta no verifica vendedor, artículo, variante ni disponibilidad.", "Compara etiqueta, título de destino, primera imagen, opción, precio y contexto del vendedor. Si la fuente no está disponible, la fila sigue sin resolver."] },
      { h: "Usa pruebas específicas de la categoría", p: ["En calzado revisa perfil, puntera, talón, suela, etiqueta y longitud cuando haga falta. En ropa: construcción, impresión, cierres y medidas planas. En bolsos: escala, interior, herrajes y correas.", "Una insignia genérica no sustituye estos controles. Toda verificación debe indicar qué se comprobó y cuándo."] },
      { h: "Añade el envío antes de ordenar candidatos", p: ["El precio aparece primero, pero el paquete puede cambiar el resultado. Separa peso del artículo y peso embalado. Cajas y protección importan en calzado, bolsos y chaquetas.", "Usa medidas actuales, destino y ruta disponible en el estimador oficial. Una guía estática explica entradas, no promete coste ni tiempo universal."] },
      { h: "Guarda una decisión que pueda revisarse", p: ["Conserva URL, identificador, fecha, precio visible, medidas, dudas y escenario de envío. Así detectarás cambios posteriores.", "Antes del pedido, vuelve a abrir cada candidato. Gana el que tenga identidad, pruebas, contexto de talla e impacto del paquete suficientemente claros."] },
    ],
    fr: [
      { h: "Pourquoi la taille du tableau ne prouve pas sa qualité", p: ["Des milliers de lignes ne servent pas si les produits sont dupliqués, les destinations obsolètes, les images liées à une autre option ou les tailles absentes. Le compte mesure l'inventaire, pas l'utilité.", "Testez des lignes réelles d'une catégorie. Ouvrez les destinations, contrôlez produit et option, puis notez combien répondent aux questions nécessaires."] },
      { h: "Lire les liens sources comme un transfert", p: ["Taobao, Weidian et 1688 évoluent indépendamment des tableaux. Convertir une route ne vérifie ni vendeur, ni article, ni option, ni disponibilité.", "Comparez libellé, titre, première image, option, prix et contexte vendeur. Si la source est inaccessible, la ligne reste non résolue."] },
      { h: "Utiliser des preuves propres à la catégorie", p: ["Pour les chaussures : profil, forme, talon, semelle, étiquette et longueur. Pour les vêtements : construction, impression, fermetures et mesures à plat. Pour les sacs : échelle, intérieur, quincaillerie et attaches.", "Un badge générique ne remplace pas ces contrôles. Toute vérification doit dire ce qui a été contrôlé et quand."] },
      { h: "Ajouter la livraison avant le classement", p: ["Le prix produit apparaît d'abord, mais le colis peut inverser le choix. Séparez poids article et poids emballé. Boîtes et protections comptent pour chaussures, sacs et vestes.", "Utilisez dimensions actuelles, destination et route disponible dans l'estimateur officiel. Un guide statique explique les données sans promettre prix ou délai."] },
      { h: "Créer une décision revérifiable", p: ["Conservez URL, identifiant, date, prix visible, mesures, questions et scénario d'envoi. Les changements futurs deviennent visibles.", "Avant la commande, rouvrez chaque candidat. Le meilleur n'est pas forcément le moins cher, mais celui dont identité, preuves, taille et impact colis sont assez clairs."] },
    ],
    it: [
      { h: "Perché la grandezza del foglio non prova la qualità", p: ["Migliaia di righe aiutano poco se ci sono duplicati, destinazioni obsolete, immagini di un'altra variante o taglie mancanti. Il conteggio misura l'inventario, non l'utilità.", "Prova righe reali di una categoria. Apri le destinazioni, controlla prodotto e opzione e annota quante rispondono alle domande necessarie."] },
      { h: "Leggi i link fonte come un passaggio", p: ["Taobao, Weidian e 1688 cambiano indipendentemente dai fogli. Convertire un percorso non verifica venditore, articolo, variante o disponibilità.", "Confronta etichetta, titolo, prima immagine, opzione, prezzo e contesto del venditore. Se la fonte non è disponibile, la riga resta irrisolta."] },
      { h: "Usa prove specifiche per categoria", p: ["Per le scarpe: profilo, punta, tallone, suola, etichetta e lunghezza. Per l'abbigliamento: costruzione, stampa, chiusure e misure piane. Per le borse: scala, interno, ferramenta e attacchi.", "Un badge generico non sostituisce questi controlli. Ogni verifica deve dire cosa è stato controllato e quando."] },
      { h: "Aggiungi la spedizione prima della classifica", p: ["Il prezzo prodotto appare per primo, ma il pacco può cambiare il confronto. Separa peso articolo e peso imballato. Scatole e protezioni contano per scarpe, borse e giacche.", "Usa misure attuali, destinazione e rotta disponibile nello stimatore ufficiale. Una guida statica spiega gli input, non promette costo o tempo universale."] },
      { h: "Crea una decisione ricontrollabile", p: ["Salva URL, identificatore, data, prezzo visibile, misure, dubbi e scenario di spedizione. I cambiamenti futuri diventano evidenti.", "Prima dell'ordine riapri ogni candidato. Il migliore non è sempre il più economico, ma quello con identità, prove, taglia e impatto sul pacco abbastanza chiari."] },
    ],
  };
  const advanced: Record<Lang, Topic["sections"]> = {
    en: [
      { h: "Design columns for decisions, not decoration", p: ["Every column should support a later decision. A compact working row can include category, plain-language product name, source destination, selected option, visible price with date, item-weight estimate, sizing evidence, QC status, unresolved question and last-check date. Color, popularity and trend labels are secondary unless they change the choice.", "Separate observed facts from your own judgment. A visible price is an observation; good value is a conclusion. A photographed measurement is evidence; will fit is an estimate. Keeping those fields apart prevents a confident note from being mistaken for a verified fact when the sheet is shared or revisited weeks later."] },
      { h: "Use a consistent status system", p: ["A simple status vocabulary makes a large sheet easier to scan: unchecked, destination matched, evidence reviewed, needs follow-up and archived. Define each label in a short note. For example, destination matched should mean that the title, first image and selected option were compared on a stated date, not that the product is guaranteed.", "Avoid turning cell color into the only signal because colors can be misunderstood, lost in exports or inaccessible to some readers. Pair color with a written status and date. Archive a failed row instead of silently deleting it; the failure reason can prevent the same broken route from being added again."] },
      { h: "Sample the sheet before trusting the category", p: ["When a category has many rows, review a small spread from the beginning, middle and recent additions. This is not a statistical audit, but it exposes common maintenance problems quickly: duplicate destinations, renamed options, repeated images, blank measurements and prices without dates. Record the sample and result so another reader can repeat it.", "If several sampled rows fail the same check, lower confidence in the category and verify more entries before using it. Do not transfer a positive result from one row to its neighbors. Sellers may reuse titles and images, and two visually similar products can have different options, measurements or parcel impact."] },
      { h: "Handle price and currency without false precision", p: ["Keep the source currency and visible source price whenever possible. If you add a dollar estimate for easier comparison, label it approximate and store the conversion date or rate source. Exchange rates move, and the displayed product price may exclude domestic movement, optional services, international shipping or destination charges.", "Round comparison estimates to sensible values instead of showing unnecessary decimals. The purpose is to compare candidates, not imitate a final invoice. At the order stage, reopen the destination and use the current checkout values. A spreadsheet price is a dated research observation, never a guarantee that a future transaction will use the same amount."] },
      { h: "Treat QC as a question set", p: ["Before reviewing photos, write the questions that matter for that category and option. For a sweatshirt those might cover color, size label, chest width, length, print placement, cuffs and visible damage. For footwear, profile, toe shape, heel alignment, outsole, size label and internal length may matter more. This keeps attention on decision evidence rather than photo count.", "Mark each question answered, unclear or not shown. If a necessary detail is missing, request clarification through the current account workflow while options are still available. Do not infer hidden construction, authenticity, long-term durability or comfort from clean photos. QC records visible condition at a moment; it does not remove every source or delivery risk."] },
      { h: "Run a final pre-order audit", p: ["The final audit should be deliberately boring. Reopen the live destination, confirm the exact option, compare the first image, recheck the visible price, review sizing evidence, update weight assumptions and list every unresolved question. Then compare only the candidates that still pass. This step catches more avoidable errors than adding another hundred unreviewed rows.", "Keep transaction-specific decisions outside static promises. Current routes, restrictions, service terms, coupons and support processes belong to the live official account or checkout context. A good research sheet brings the user to that handoff with a clear record; it does not pretend that a historical snapshot can replace the current transaction details."] },
    ],
    de: [
      { h: "Spalten für Entscheidungen gestalten", p: ["Jede Spalte sollte eine spätere Entscheidung stützen: Kategorie, Klarname, Ziel, Option, datierter Preis, Gewicht, Größenbeleg, QC-Status, offene Frage und Prüfdatum.", "Trenne beobachtete Fakten von Bewertungen. Sichtbarer Preis und Messung sind Belege; gutes Preis-Leistungs-Verhältnis und Passform sind Schlussfolgerungen."] },
      { h: "Ein einheitliches Statussystem nutzen", p: ["Nutze wenige definierte Stati: ungeprüft, Ziel abgeglichen, Belege geprüft, Rückfrage nötig und archiviert. Ziel abgeglichen ist keine Produktgarantie.", "Kombiniere Farben mit Text und Datum. Archiviere Fehler mit Grund, damit dieselbe defekte Route nicht erneut aufgenommen wird."] },
      { h: "Die Kategorie stichprobenartig prüfen", p: ["Prüfe Einträge vom Anfang, aus der Mitte und aus neuen Ergänzungen. So werden Duplikate, geänderte Optionen, wiederholte Bilder und undatierte Preise sichtbar.", "Scheitern mehrere Zeilen gleich, prüfe mehr. Übertrage ein positives Ergebnis nie automatisch auf ähnliche Nachbarzeilen."] },
      { h: "Preis und Währung ohne Scheingenauigkeit", p: ["Bewahre Quellwährung und sichtbaren Preis. Dollarwerte sind als Näherung mit Datum oder Kursquelle zu kennzeichnen; weitere Kosten bleiben getrennt.", "Runde sinnvoll und öffne vor der Bestellung die Zielseite erneut. Ein Tabellenpreis ist eine datierte Beobachtung, keine spätere Rechnungsgarantie."] },
      { h: "QC als Fragenliste behandeln", p: ["Formuliere vor der Fotoprüfung kategoriespezifische Fragen zu Option, Maß, Konstruktion und sichtbaren Schäden. Fotoanzahl allein ist kein Qualitätsmaß.", "Markiere beantwortet, unklar oder nicht gezeigt. Fotos belegen einen sichtbaren Moment, nicht Echtheit, Komfort oder Langzeithaltbarkeit."] },
      { h: "Abschließende Prüfung vor der Bestellung", p: ["Öffne das Live-Ziel, bestätige Option und Bild, prüfe Preis, Maße, Gewicht und offene Fragen. Vergleiche nur Kandidaten, die noch bestehen.", "Aktuelle Routen, Regeln, Gutscheine und Supportprozesse gehören in den offiziellen Konto- oder Checkout-Kontext, nicht in statische Versprechen."] },
    ],
    es: [
      { h: "Diseña columnas para decidir", p: ["Cada columna debe apoyar una decisión: categoría, nombre claro, destino, opción, precio fechado, peso, pruebas de talla, estado QC, dudas y última revisión.", "Separa hechos observados de opiniones. Un precio o una medida son pruebas; buen valor o servirá son conclusiones."] },
      { h: "Usa estados coherentes", p: ["Define pocos estados: sin revisar, destino coincidente, pruebas revisadas, seguimiento y archivado. Coincidencia no significa garantía.", "Acompaña el color con texto y fecha. Archiva el fallo con su motivo para no reincorporar la misma ruta rota."] },
      { h: "Muestrea la categoría", p: ["Revisa filas iniciales, intermedias y recientes. Así aparecen duplicados, opciones cambiadas, imágenes repetidas, medidas ausentes y precios sin fecha.", "Si varias fallan igual, revisa más. Nunca extiendas el resultado positivo de una fila a productos vecinos parecidos."] },
      { h: "Gestiona precio y moneda sin falsa precisión", p: ["Guarda moneda y precio fuente. Marca el dólar como aproximado con fecha o referencia del cambio y separa los demás costes.", "Redondea con sentido y vuelve a abrir el destino antes de pedir. El precio de la hoja es una observación fechada, no una factura prometida."] },
      { h: "Trata el QC como preguntas", p: ["Antes de las fotos escribe preguntas concretas sobre opción, medidas, construcción y daños. La cantidad de imágenes no sustituye las respuestas.", "Marca respondido, dudoso o no mostrado. Las fotos no prueban autenticidad, comodidad ni duración futura."] },
      { h: "Haz una auditoría final", p: ["Reabre el destino, confirma opción e imagen, revisa precio, talla, peso y dudas. Compara solo candidatos que aún superan el control.", "Rutas, reglas, cupones y soporte actuales deben comprobarse en la cuenta o pago oficial, no en promesas estáticas."] },
    ],
    fr: [
      { h: "Concevoir les colonnes pour décider", p: ["Chaque colonne doit servir une décision : catégorie, nom clair, destination, option, prix daté, poids, preuves de taille, statut QC, question et date de contrôle.", "Séparez faits observés et jugement. Prix et mesure sont des preuves ; bonne valeur et conviendra sont des conclusions."] },
      { h: "Utiliser des statuts cohérents", p: ["Définissez quelques statuts : non vérifié, destination concordante, preuves contrôlées, suivi et archivé. Une concordance n'est pas une garantie.", "Associez couleur, texte et date. Archivez l'échec avec sa raison pour éviter le retour de la même route cassée."] },
      { h: "Échantillonner la catégorie", p: ["Contrôlez des lignes du début, du milieu et des ajouts récents. Vous verrez doublons, options modifiées, images répétées, mesures absentes et prix non datés.", "Si plusieurs lignes échouent pareillement, vérifiez davantage. N'étendez jamais un résultat positif aux produits voisins."] },
      { h: "Gérer prix et devise sans fausse précision", p: ["Conservez devise et prix source. Marquez l'estimation en dollars avec sa date ou sa référence de change et séparez les autres coûts.", "Arrondissez raisonnablement et rouvrez la destination avant commande. Le prix du tableau est une observation datée, pas une facture promise."] },
      { h: "Traiter le QC comme des questions", p: ["Avant les photos, écrivez les questions propres à l'option, aux mesures, à la construction et aux défauts. Le nombre d'images ne suffit pas.", "Marquez répondu, incertain ou absent. Les photos ne prouvent ni authenticité, ni confort, ni durabilité future."] },
      { h: "Faire un audit final", p: ["Rouvrez la destination, confirmez option et image, puis prix, taille, poids et questions. Comparez seulement les candidats encore valides.", "Routes, règles, coupons et support actuels doivent être contrôlés dans le compte ou paiement officiel, pas dans une promesse statique."] },
    ],
    it: [
      { h: "Progetta colonne per decidere", p: ["Ogni colonna deve sostenere una decisione: categoria, nome chiaro, destinazione, opzione, prezzo datato, peso, prove di taglia, stato QC, dubbi e ultimo controllo.", "Separa fatti osservati e giudizi. Prezzo e misura sono prove; buon valore e vestirà bene sono conclusioni."] },
      { h: "Usa stati coerenti", p: ["Definisci pochi stati: non controllato, destinazione abbinata, prove riviste, seguito necessario e archiviato. L'abbinamento non è una garanzia.", "Affianca al colore testo e data. Archivia il fallimento con il motivo per evitare di reinserire la stessa rotta rotta."] },
      { h: "Campiona la categoria", p: ["Controlla righe iniziali, centrali e recenti. Emergeranno duplicati, opzioni cambiate, immagini ripetute, misure assenti e prezzi senza data.", "Se più righe falliscono allo stesso modo, verifica di più. Non estendere il risultato positivo ai prodotti vicini."] },
      { h: "Gestisci prezzo e valuta senza falsa precisione", p: ["Conserva valuta e prezzo fonte. Etichetta il dollaro come approssimativo con data o riferimento del cambio e separa gli altri costi.", "Arrotonda con criterio e riapri la destinazione prima dell'ordine. Il prezzo nel foglio è un'osservazione datata, non una fattura promessa."] },
      { h: "Tratta il QC come domande", p: ["Prima delle foto scrivi domande su opzione, misure, costruzione e difetti. Il numero di immagini non sostituisce le risposte.", "Segna risposto, incerto o non mostrato. Le foto non provano autenticità, comfort o durata futura."] },
      { h: "Esegui un controllo finale", p: ["Riapri la destinazione, conferma opzione e immagine, ricontrolla prezzo, taglia, peso e dubbi. Confronta solo i candidati ancora validi.", "Rotte, regole, coupon e assistenza correnti vanno verificati nell'account o checkout ufficiale, non in promesse statiche."] },
    ],
  };
  return {
    ...guide[lang],
    title: `${copy[lang].nav[5]}: ${guide[lang].title}`,
    sections: [...guide[lang].sections, ...extra[lang], ...advanced[lang]],
  };
}
