export const esArticles = {
  "use-usfans-spreadsheet": {
    sourceLabel: "Fuentes oficiales comprobadas el 2 de septiembre de 2026: Beginner’s Guide, Help Center, estimador de envío y avisos de compra actuales de USFans.",
    sections: [
      ["Qué hace realmente una spreadsheet útil de USFans", "Una spreadsheet de USFans funciona mejor como índice de investigación, no como catálogo garantizado. Reúne enlaces, categorías, precios orientativos e imágenes de Taobao, Weidian y 1688, pero el vendedor sigue controlando la ficha, las variantes, el stock, el envío nacional y las devoluciones. Abre cada candidato y vuelve a comprobar título, imagen principal, vendedor, menú y precio en vivo. Una fila puede quedar antigua aunque la URL todavía cargue. La hoja ahorra tiempo de búsqueda, pero no sustituye la descripción actual ni el control posterior en almacén. Esta distinción evita tratar una miniatura atractiva como prueba de disponibilidad, versión o precio final."],
      ["Empezar con una intención, no con desplazamiento infinito", "Antes de abrir decenas de pestañas, define producto, presupuesto, color, medidas necesarias y límites de paquete. En calzado puede importar la longitud de plantilla; en una chaqueta, pecho, espalda, hombro y manga. Busca con dos o tres términos precisos y conserva solo un pequeño grupo comparable. En móvil, las categorías claras y las rutas directas son más útiles que una tabla ancha con desplazamiento horizontal. El objetivo no es reunir el mayor número de enlaces, sino encontrar dos o tres fichas activas que puedan juzgarse con los mismos criterios. Esta preparación también facilita detectar una variante incorrecta cuando la mercancía llegue al almacén."],
      ["Revalidar la ficha en vivo", "Los vendedores cambian fotografías, precios, existencias, colores y combinaciones sin cambiar la URL. Compara la fila con la página actual: título, imagen, tienda, opciones y precio deben seguir describiendo el producto buscado. Si el destino redirige a una búsqueda general o a otro artículo, elimina ese candidato. Cuando la ruta sea válida, guarda el texto exacto de la variante, las medidas y cualquier aviso sobre personalización, devoluciones o servicio posventa limitado. Un agente puede comunicarse con el vendedor, pero no puede reescribir sus condiciones. La página en vivo y la opción seleccionada son la especificación real; el nombre guardado en una spreadsheet solo sirve para descubrirla."],
      ["Tratar el precio mostrado como una instantánea", "El valor orientativo en USD ayuda a ordenar, pero no representa el coste final. El precio del marketplace suele estar en CNY y puede variar por talla, color, cantidad o promoción. El primer pago puede incluir artículo y transporte nacional; el paquete internacional se calcula después de recibir, embalar y elegir ruta. Conversión, procesamiento del pago, servicios opcionales y flete cambian el total. Mantén producto y paquete en columnas separadas: precio CNY actual, variante y envío dentro de China por un lado; presupuesto de transporte internacional por otro. El importe autorizado siempre es el de la pantalla de pago de la etapa correspondiente, no una conversión antigua de la hoja."],
      ["Relacionar variantes con medidas", "Una etiqueta M, 42 o talla única no demuestra que el artículo se ajuste como otro que ya tienes. Compara centímetros de la ficha actual con una prenda o zapato de referencia. Para tops suelen servir pecho, hombros, mangas y largo; para pantalones, método de cintura, tiro y entrepierna; para calzado, longitud interior. Guarda el texto exacto del color y la variante, porque algunos vendedores usan números o abreviaturas. Si falta una medida decisiva, esa ausencia es un riesgo que debe quedar visible. La spreadsheet puede llevarte al producto, pero no inventa datos objetivos que el vendedor nunca publicó ni convierte una etiqueta familiar en una equivalencia universal."],
      ["Llevar la selección hasta el almacén", "USFans explica que recibe, inspecciona y fotografía la mercancía en almacén. Los avisos actuales anuncian entre tres y siete fotos QC gratuitas en alta definición. Compáralas con la especificación guardada: variante exacta, color esperado, forma visible, accesorios y medidas solicitadas. La miniatura de la spreadsheet no es la referencia principal; lo son la ficha viva y la opción pagada. Revisa las imágenes con rapidez y conserva la evidencia si aparece una diferencia. Una buena lista de candidatos no solo acelera el descubrimiento: crea un estado esperado que puede verificarse tras el transporte nacional, cuando todavía podría existir una opción de devolución según los términos concretos del vendedor."],
      ["Saber qué puede resolver el QC", "Las fotos de almacén pueden mostrar color recibido, talla marcada, cantidad, forma, costuras visibles, posición de estampado y accesorios. No demuestran autenticidad, durabilidad, comodidad, estructura interna o composición exacta. La iluminación altera colores, la compresión deforma prendas y los ángulos estándar pueden ocultar detalles. Úsalas como punto de decisión, no como certificado. Compara partes simétricas, busca defectos visibles y solicita medidas objetivas cuando el servicio esté disponible y el ajuste sea importante. Si la evidencia queda incompleta, decide si esa incertidumbre es aceptable antes de aprobar. Una guía responsable limita sus conclusiones a lo que realmente puede observarse en las imágenes."],
      ["Planificar el impacto del paquete", "Un producto barato en la hoja puede ser caro de transportar por caja, protección o forma voluminosa. El peso volumétrico puede superar al real, y baterías, líquidos o imanes pueden limitar rutas. Antes de añadir más artículos, calcula si la combinación mejora la eficiencia o solo crea un cartón mayor. USFans ofrece un estimador y aclara que trabaja con rutas y datos históricos; el coste final puede cambiar tras el embalaje. Usa el resultado como rango. Considera protección probable, peso, dimensiones, destino y restricciones. Así la spreadsheet deja de ser una lista de compra y se convierte en una herramienta para decidir si el producto sigue teniendo sentido una vez incluido el transporte."],
      ["Mantener un pequeño registro de pruebas", "Para cada candidato serio guarda URL, fecha, vendedor, variante, precio CNY, medidas clave y motivo de aceptación o descarte. Después añade fecha de almacén, resultado QC y plazo visible de devolución. No hace falta una base de datos compleja; unos campos constantes bastan. El registro evita confundir fichas con imágenes similares, revela cambios de variantes y ayuda cuando los artículos llegan en días distintos. También muestra enlaces antiguos que deben retirarse. Una experiencia fiable no depende de afirmar que existen miles de finds, sino de que rutas, imágenes y detalles actuales puedan revisarse sin perder el historial que llevó a la decisión."],
      ["El estándar práctico de una spreadsheet en 2026", "Una buena spreadsheet acelera el descubrimiento manteniendo visibles los límites. Debe ofrecer categorías claras, imágenes actuales, rutas directas, referencias USD bien etiquetadas y diseño móvil sin obligar a deslizar de lado. Más importante: recordar que hay que comprobar la ficha viva, comparar medidas, revisar QC pronto, respetar plazos y estimar el paquete antes de aprobar. Ninguna hoja garantiza conducta del vendedor, ajuste, autenticidad, legalidad o aduanas. Su tarea es más concreta: organizar la evidencia que el comprador sí puede verificar. Utilizada así, es el comienzo de un proceso de investigación y no un atajo para evitar la debida diligencia." ]
    ]
  },
  "beginner-ordering-guide": {
    sourceLabel: "Fuentes oficiales comprobadas el 2 de septiembre de 2026: Beginner’s Guide, Help Center, estimador de envío y páginas de producto actuales de USFans.",
    sections: [
      ["Comprender las dos etapas de la compra", "Comprar mediante un agente de China no equivale al checkout de una tienda internacional convencional. La primera etapa cubre ficha, pedido y transporte al almacén. La segunda empieza al recibir: revisar fotos QC, elegir artículos del paquete, decidir embalaje y pagar flete internacional. Separarlas es la mejor regla presupuestaria para principiantes. Un precio bajo del marketplace no es el coste puesto en destino, y una compra confirmada no significa envío internacional. Usa cada pantalla como puerta de decisión: validar producto antes del primer pago, validar mercancía antes de aprobar el paquete y validar ruta y peso facturable antes del segundo pago."],
      ["Empezar con una ruta de producto completa", "USFans indica soporte para Taobao, Weidian y 1688. Un pedido útil empieza con una URL activa que todavía muestre vendedor, variantes y precio. Compara la vista del agente con la ficha original: imagen, título, color y talla deben coincidir. Si el sistema no interpreta la página, no adivines usando un título antiguo de spreadsheet. El pedido manual solo es razonable cuando existe información suficiente para describir objetivamente el artículo exacto. Cuanto más completa sea la ficha, más fácil será comprar la opción correcta y demostrar después qué se esperaba si el almacén registra otra cosa. Guarda el enlace y la selección antes de pagar."],
      ["Elegir la variante exacta antes del pago", "Los menús de color, talla, lote y cantidad usan etiquetas cortas que solo tienen sentido junto a las imágenes. Conserva el texto exacto y compara medidas, en vez de traducir automáticamente una talla conocida. En 1688 el precio puede depender de cantidad; en Taobao o Weidian una opción promocional puede ser distinta. Lee avisos sobre personalización, devoluciones y accesorios vendidos por separado. Una nota debe ser breve y objetiva, y nunca sustituir la selección del menú. Antes del primer pago revisa producto, transporte nacional y resumen. El envío internacional se calcula más tarde, por lo que esa pantalla no representa el coste completo hasta tu dirección."],
      ["Saber cuándo se procesa la compra", "Los avisos actuales de USFans indican que los pedidos pagados se gestionan entre las 09:00 y las 18:00, hora de China UTC+8. Es una ventana operativa, no una promesa de expedición inmediata del vendedor. Stock, respuesta, fines de semana, festivos y logística nacional pueden ampliar el plazo. Consulta confirmación de compra y seguimiento en lugar de interpretar unas horas sin cambios como fallo. Si una opción no está disponible o se propone reemplazo, compárala con la ficha original antes de aceptar. Mantén la decisión en el historial cuando sea posible. El agente compra por tu cuenta, pero el vendedor sigue controlando existencias, preparación y despacho dentro de China."],
      ["Separar despacho del vendedor y recepción", "Un número de seguimiento nacional solo demuestra movimiento hacia el almacén. El producto todavía no está inspeccionado ni listo para el paquete internacional. Espera a recepción, registro y conjunto de fotos. Un pedido con varias piezas puede llegar separado, y distintos vendedores rara vez coinciden. Utiliza la cronología para distinguir recibido y en tránsito. Si un envío se detiene, revisa el último evento antes de abrir una incidencia. El hito útil no es simplemente enviado, sino recibido y relacionado con el pedido. Preparar el paquete antes de que lleguen todos los artículos previstos puede obligar a dividirlo o dejar una compra atrás."],
      ["Revisar las tres a siete fotos QC", "Las páginas actuales anuncian entre tres y siete fotos QC gratuitas en alta definición. Primero confirma color, talla marcada, modelo y cantidad. Después revisa forma, simetría, costuras, estampado, herrajes y accesorios. Finalmente compara medidas visibles con la tabla del vendedor y una prenda propia. Las fotos estándar son control visual, no prueba de laboratorio: no demuestran autenticidad, comodidad, interior o vida útil. Si falta un ángulo esencial, comprueba opciones de foto adicional o medición en el pedido. Revisa pronto, porque el plazo del vendedor puede empezar con la entrada en almacén, no cuando decidas abrir las imágenes días más tarde."],
      ["Tomar rápido la decisión de devolución", "Muchas páginas actuales mencionan solicitar devolución dentro de cinco días tras la llegada y que el agente negociará con el vendedor. También pueden excluir productos personalizados o devoluciones sin motivo de calidad. Trata los cinco días como máximo solo cuando el pedido concreto lo muestre; no es un derecho universal. Si la variante es incorrecta o hay defecto visible, envía opción, foto y diferencia precisa. No esperes al embalaje. La solicitud no garantiza aprobación: influyen vendedor, plazo, condición y transporte nacional de retorno. El flujo más seguro revisa cada producto inmediatamente al registrarse y conserva la evidencia necesaria antes de que finalice cualquier ventana aplicable."],
      ["Construir el paquete según peso facturable", "Después de aprobar, combina solo mercancías compatibles y compara rutas para destino y contenido. Una línea puede cobrar el mayor valor entre peso real y cálculo volumétrico. Cajas de zapatos, prendas acolchadas y protección pueden costar más de lo esperado por masa. Decide si conservar cajas, añadir refuerzo o separar contenido sensible. Consolidar reduce cargos repetidos, pero un cartón demasiado grande aumenta el volumen. El paquete correcto no siempre es el más pesado posible. Revisa dimensiones estimadas, reglas y restricciones y reserva margen entre depósito y medición final. Así el ahorro en una etapa no se convierte en una factura imprevista en la siguiente."],
      ["Tratar el pago de envío como depósito", "La guía de USFans explica que el depósito internacional se calcula con peso estimado, método y destino, y que el total se determina después del embalaje. El estimador público señala una variación frecuente aproximada de más o menos cinco a diez por ciento debido a peso, volumen y datos reales. Un reembolso pequeño o pago adicional no demuestra por sí mismo un error. Compara peso, dimensiones y ruta finales con los valores estimados. Si la diferencia es mucho mayor, solicita los datos registrados. Nunca presentes la cotización de una persona como precio permanente: destino, contenido, disponibilidad, combustible, temporada y opciones aduaneras pueden cambiar el resultado."],
      ["Terminar con registros y expectativas realistas", "Conserva pedido, variante, fotos de almacén, declaración, medidas finales, ruta y seguimiento hasta la entrega y el fin de cualquier reclamación. El tracking internacional puede quedar quieto entre exportación y primer escaneo del destino. Aduanas puede inspeccionar, gravar, devolver, confiscar o destruir según la ley local; el agente no garantiza el resultado. Lo controlable es elegir una ficha viva, registrar la variante, revisar QC pronto, respetar las condiciones del vendedor, presupuestar el coste completo y escoger una ruta adecuada al paquete real. Es menos impulsivo que comprar un find viral, pero produce menos sorpresas y un historial mucho más claro si hace falta soporte." ]
    ]
  },
  "qc-photo-checklist": {
    sourceLabel: "Fuentes oficiales comprobadas el 2 de septiembre de 2026: Beginner’s Guide, Help Center y avisos actuales de inspección y devolución de USFans.",
    sections: [
      ["Usar QC como punto de decisión visual", "USFans indica que inspecciona y fotografía después de la llegada; las páginas actuales anuncian tres a siete imágenes HD gratuitas. Esto permite comparar lo recibido con lo pagado antes del envío internacional. No es certificación ni autenticación. Las fotos estándar muestran condición visible desde pocos ángulos y bajo luz de almacén. Funcionan mejor cuando ya se guardaron variante, ficha y medidas clave. Formula una pregunta concreta: ¿la evidencia coincide lo suficiente para aprobar, o existe una diferencia específica que justifica devolución o foto adicional? Mantener el objetivo estrecho evita juicios vagos basados únicamente en si el producto parece atractivo en la primera imagen."],
      ["Confirmar identidad antes de calidad", "La primera revisión es administrativa: color, talla marcada, modelo, cantidad y piezas incluidas. Un producto puede verse perfecto y ser la variante equivocada. Compara etiquetas y embalaje con el texto exacto del pedido, pero no uses la etiqueta como prueba de ajuste o composición. Distingue versiones similares mediante rasgos visibles y cuenta pares y conjuntos. Si aparece una tarjeta de pedido o referencia de medida, confirma que corresponde al artículo correcto. Las asociaciones de fotos pueden fallar y es más fácil resolverlas antes del embalaje. Solo cuando la identidad sea razonable debes pasar a silueta, construcción y estado cosmético."],
      ["Leer forma general y simetría", "Usa vistas amplias frontal, posterior y lateral antes de ampliar detalles. En zapatos compara punteras, talones, paneles y simetría; en prendas, cuello, hombros, longitud y mangas; en bolsos, asas, estructura y alineación. La compresión puede deformar temporalmente y el ángulo cambia proporciones, así que consulta más de una vista. Una nota QC fuerte señala lugar y diferencia, por ejemplo bolsillo izquierdo claramente más alto, en lugar de escribir mala forma. Las observaciones específicas pueden transmitirse al vendedor y separan un problema visible de una impresión subjetiva. No conviertas un solo ángulo extraño en una conclusión cuando otras imágenes muestran una perspectiva distinta."],
      ["Inspeccionar costuras, estampado y acabado", "Amplía zonas de tensión: hombros, entrepierna, esquinas de bolsillos, uniones de suela, correas y cremalleras. Busca puntadas saltadas, hilos sueltos, costuras abiertas, pegamento, bordes levantados y espaciado irregular. Compara estampado o bordado en centrado, escala y distancia a las costuras con las imágenes actuales. La luz puede cambiar color y materiales reflectantes, por lo que una diferencia pequeña en una foto no basta. Las imágenes muestran superficie, no resistencia interna ni duración del adhesivo. El objetivo es detectar defectos visibles y divergencias claras, no pronosticar toda la vida útil de una prenda a partir de una imagen comprimida."],
      ["Convertir las medidas en parte del QC", "Las medidas transforman una opinión subjetiva en comprobación útil. Compara pecho, largo, hombro y manga con una prenda propia siguiendo el mismo método. En pantalones aclara si cintura está plana, estirada o en contorno. Para zapatos, la plantilla suele ser más útil que la etiqueta. Bolsos y accesorios pueden requerir ancho, alto o correa. Si las fotos gratuitas no incluyen lo necesario, revisa el servicio adicional disponible. No estimes centímetros por la mesa o por objetos del encuadre: la perspectiva engaña. Una medición objetiva puede respaldar rápidamente una devolución cuando la tabla del vendedor y la unidad recibida muestran una diferencia material."],
      ["Contar herrajes y accesorios", "Cuenta correas, cordones, bolsitas, colgantes, botones, repuestos y cualquier accesorio prometido en la variante. Revisa cremalleras, hebillas, broches, ganchos y metal visible en busca de faltas o daños evidentes. Una cremallera cerrada no demuestra funcionamiento suave y una película protectora cambia la apariencia, así que limita la conclusión. En electrónica confirma modelo visible, enchufe y accesorios, no capacidad de batería o rendimiento interno. Si una pieza esencial está oculta, solicita una imagen enfocada antes de que termine el plazo. Los componentes faltantes se documentan con mucha más claridad al llegar al almacén que después del transporte internacional."],
      ["Reconocer los límites de la evidencia", "Las fotos QC no prueban autenticidad, composición, comodidad, olor, impermeabilidad, batería, construcción interna o durabilidad. Tampoco garantizan legalidad o admisión aduanera. Incluso las imágenes HD dependen de luz, foco, compresión y ángulos. Expresa cada conclusión con su límite: la talla marcada coincide y no aparece un defecto superficial claro, pero el ajuste sigue incierto sin medida de pecho. Esta redacción es más honesta que perfecto y evita que una guía independiente parezca aval del vendedor. Una buena checklist ayuda a decidir bajo incertidumbre; no elimina esa incertidumbre ni convierte un conjunto visual limitado en garantía de comportamiento futuro."],
      ["Actuar dentro de la ventana posventa", "Los avisos actuales suelen mencionar solicitud en cinco días después de llegada y negociación con el vendedor. La ficha concreta puede excluir productos personalizados o devoluciones sin motivo de calidad, por lo que mandan los términos en vivo. Revisa las fotos al aparecer y no esperes al resto del haul. Si hay problema visible, presenta variante, imagen y descripción corta de la diferencia. Evita exageraciones y quejas no relacionadas. Una solicitud no equivale a reembolso aprobado: política, tiempo, condición y coste nacional afectan el desenlace. La evidencia clara y temprana facilita que el agente comunique un caso concreto al vendedor mientras todavía existe una opción práctica."],
      ["Mantener un registro repetible de aprobación", "Antes de aprobar registra cuatro puntos: identidad confirmada, medidas comprobadas o aceptadas como desconocidas, defectos visibles revisados y accesorios contados. Guarda las imágenes con el pedido y explica por qué aceptaste una variación en artículos caros. El registro evita confusión al consolidar productos similares y separa problema de vendedor, daño de tránsito o fallo de embalaje. También hace más rápidas compras futuras al comparar resultados. Una checklist solo vale si cambia la conducta: revisar pronto, hacer preguntas dirigidas, devolver mercancía claramente incorrecta cuando los términos lo permitan y aprobar únicamente si la incertidumbre restante cabe dentro de tu tolerancia al riesgo."],
      ["Aprobar la evidencia, no la emoción", "La decisión final debe ser específica: confirmar variante, comparar dimensiones importantes, inspeccionar construcción visible, contar accesorios y evaluar puntos pendientes. Imágenes virales y comentarios positivos no sustituyen el proceso, porque la unidad de almacén es la que recibirás. Tampoco exijas a las fotos demostrar lo imposible. Si autenticidad, rendimiento interno o composición exacta son esenciales, quizá un flujo visual mediante agente no sea adecuado. Una guía QC sólida conecta la etapa real de fotografías con límites disciplinados. Ayuda a detectar errores visibles antes de pagar flete internacional sin presentar imágenes limitadas como garantía de calidad, legalidad o duración." ]
    ]
  },
  "international-shipping-cost": {
    sourceLabel: "Fuentes oficiales comprobadas el 2 de septiembre de 2026: estimador de envío, Beginner’s Guide, Help Center y avisos de rutas actuales de USFans.",
    sections: [
      ["Usar el estimador como rango de planificación", "El estimador público de USFans se basa en rutas disponibles y datos históricos. Es útil antes de comprar, pero no es factura. No conoce dimensiones embaladas, protección, disponibilidad futura ni peso medido de mercancía aún no recibida. Introduce destino, peso realista y medidas probables, compara rutas y guarda rango y fecha. Tarifas y líneas cambian. No copies un valor y lo presentes como precio universal por kilo: país, contenido, tamaño, servicios y restricciones influyen. Una estimación responsable ayuda a decidir si la compra sigue siendo razonable con transporte. No debe crear precisión falsa antes de que el almacén pueda preparar y medir el paquete real."],
      ["Distinguir peso real y volumétrico", "El peso real sale de la báscula. El volumétrico transforma el espacio del cartón mediante largo por ancho por alto dividido por un factor de ruta. Muchas líneas cobran el mayor. Accesorios densos suelen seguir el peso real; cajas de zapatos, abrigos acolchados y protección pueden producir mayor volumen. Un objeto ligero no es automáticamente barato. Estima masa y forma embalada. Divisores y redondeos varían según línea, así que consulta condiciones actuales en vez de copiar un número antiguo. Comprender esta comparación explica por qué dos paquetes con el mismo peso en báscula pueden recibir precios diferentes y evita atribuir automáticamente la diferencia a un error del agente."],
      ["Separar depósito y cargo medido", "La guía describe un depósito internacional calculado con peso estimado, método y destino. El total se determina después de embalar y medir. El estimador afirma que el coste final suele fluctuar aproximadamente más o menos cinco a diez por ciento por peso volumétrico y datos reales. Un pequeño reembolso o suplemento puede ser conciliación normal. Compara peso, dimensiones y línea finales con los valores usados para el depósito. Si la diferencia supera claramente ese rango, solicita datos registrados y cualquier cambio de servicio. La comparación correcta no es solo depósito frente a total, sino entradas estimadas frente a entradas medidas bajo la misma ruta y opciones de embalaje."],
      ["Tratar el embalaje como decisión de coste", "El embalaje protege, pero modifica peso facturable. Cajas comerciales, esquineras, refuerzo, protección contra humedad y relleno añaden masa o volumen. Quitar una caja puede reducir medidas y también protección. Envasar al vacío prendas blandas baja volumen, pero no conviene para artículos estructurados. Decide selectivamente: qué riesgo controla cada servicio y cómo cambia probablemente el cartón. Si existe ensayo de paquete, el resultado útil es peso y dimensiones medidos, no una garantía contra toda remedición del transportista. Una buena explicación muestra el intercambio entre coste y protección y no promete que retirar todo o conservarlo todo sea universalmente la mejor opción."],
      ["Consolidar artículos compatibles, no todo", "Combinar mercancía puede reducir cargos base y simplificar seguimiento, pero un producto grande o restringido distorsiona el conjunto. Compara un cartón común con dos paquetes menores. Ropa densa y accesorios consolidan bien; cajas voluminosas pueden activar un nivel superior. Baterías, líquidos o imanes pueden eliminar rutas atractivas para todos los artículos. También importa el tiempo: esperar a un vendedor atrasado retiene productos ya aprobados. La mejor consolidación agrupa dimensiones, restricciones y plazos compatibles y no persigue el peso máximo. Registra qué entra antes de enviar la solicitud para no descubrir un artículo ausente después de que el almacén haya cerrado el paquete."],
      ["Comparar rutas por algo más que precio", "Incluye método de peso, restricciones, tracking, compensación o seguro, rango de entrega y gestión en destino. Una línea barata puede usar divisor desfavorable o excluir el contenido. Una más rápida no ayuda si aduanas o entrega local dominan el tiempo. Lee el aviso actual y confirma elegibilidad. Si existe seguro, revisa eventos cubiertos y límites; asegurado no significa reembolso por toda demora, pérdida o acción aduanera. Precio y rendimiento cambian. Publica un marco de decisión, no una supuesta mejor línea permanente. El comprador necesita comprender por qué una ruta encaja con su paquete específico, país y tolerancia al riesgo, no seguir un nombre desactualizado."],
      ["Presupuestar el coste puesto en destino", "El flete es una parte. El presupuesto completo puede incluir producto, transporte nacional, conversión, pago, servicios, envío internacional, seguro, impuestos, aranceles y gestión local. Umbrales y tratamiento aduanero dependen del destino y cambian; por eso el Help Center separa temas de tarifas, facturación y referencia arancelaria. No aconsejes infradeclarar ni describir falsamente. Utiliza información correcta y respeta normas. Una tarifa baja puede ser mala si excluye servicios necesarios o usa una ruta inadecuada. Compara el coste completo al pagar y conserva margen para moneda y conciliación final. El objetivo es una decisión total, no una cifra de transporte aislada de todo lo demás."],
      ["Comprender restricciones antes del paquete", "Las líneas pueden restringir baterías, líquidos, polvos, imanes, alimentos, presión y otros productos sensibles. Que el marketplace venda algo no prueba que viaje por una ruta o entre legalmente al destino. Comprueba el aviso para el contenido exacto y no ocultes la categoría. Si un artículo reduce opciones, compara enviarlo separado, devolverlo si se permite o no comprar. La legalidad y admisibilidad siguen siendo responsabilidad del comprador aunque el agente acepte el pedido nacional. Un enlace válido no equivale a un plan de paquete válido. El contenido SEO útil conecta descubrimiento con elegibilidad a tiempo para evitar pagar por mercancía difícil o imposible de transportar."],
      ["Leer tracking y aduanas con realismo", "El seguimiento pasa por salida de almacén, exportación, transporte internacional, aduanas y entrega local. Algunas etapas generan muchos escaneos y otras quedan quietas hasta el siguiente operador. Una pausa no prueba pérdida; excepciones repetidas merecen revisión. Aduanas puede inspeccionar, gravar, devolver, confiscar o destruir bajo ley local. Guarda declaración, condiciones, fotos disponibles y pago. Si surge un problema, usa el último evento y el procedimiento de compensación aplicable, no una media de días prometida. Ninguna guía responsable puede garantizar despacho aduanero o fecha exacta antes de conocer paquete, línea y decisión de las autoridades del país de destino."],
      ["Crear un registro de envío reutilizable", "Después de entregar, anota peso real, dimensiones, ruta, flete pagado, fecha de salida, fecha de llegada y cualquier tasa local. Tu historial es más útil que una captura ajena porque refleja país, mezcla y embalaje propios. Con varios paquetes muestra si cajas o refuerzo cambian el coste y qué artículos generan volumen. También revela cambios estacionales sin afirmar que el precio pasado se repetirá. Úsalo para mejorar la siguiente estimación, no para publicar una garantía. El mejor contenido enseña a comparar entradas, conciliar depósito y total y evaluar el coste puesto en destino con condiciones actuales en lugar de perseguir una cifra permanente inexistente." ]
    ]
  },
  "warehouse-returns-guide": {
    sourceLabel: "Fuentes oficiales comprobadas el 2 de septiembre de 2026: Help Center, Beginner’s Guide y avisos actuales de almacén y devolución de USFans.",
    sections: [
      ["Tratar la llegada como plazo, no descanso", "La recepción inicia la etapa para comparar mercancía, conservar, devolver o investigar. No es un estado pasivo. Abre el pedido al registrarse, confirma que las fotos corresponden y anota la hora. Las ventanas del vendedor pueden ser breves. Los avisos actuales suelen citar cinco días para solicitar devolución, sujetos a condiciones. Esperar al último artículo de un haul puede eliminar opciones para el primero. Utiliza la llegada como activador: inspeccionar, medir, documentar y decidir. La política de almacenamiento puede permitir guardar el producto más tiempo, pero eso no amplía automáticamente el plazo posventa del vendedor ni reemplaza la revisión temprana."],
      ["Comprobar variante antes que condición", "Empieza con color, talla marcada, modelo, cantidad y accesorios. Una variante incorrecta es incidencia aunque esté impecable. Compara opción exacta con etiquetas y rasgos en las fotos. Cuenta piezas de conjuntos; en zapatos revisa ambos lados y talla; en ropa usa medidas para ajuste. Si el menú usaba números, conserva la captura que los relaciona con la versión. Esta evidencia facilita la solicitud y evita centrarse en detalles pequeños mientras se ignora que llegó otro producto. El registro del pedido es la especificación; la miniatura de la spreadsheet solo fue una referencia de descubrimiento y no debe sustituir el texto exacto pagado."],
      ["Usar con cuidado el aviso de cinco días", "Muchas páginas dicen que el comprador puede solicitar dentro de cinco días y que el agente negociará. No significa aprobación automática. También pueden excluir personalización, cambios o devoluciones sin calidad. Política del vendedor, condición, tiempo y flete nacional influyen. Lee el aviso del artículo exacto y presenta pronto. Identifica opción, diferencia visible y foto. Frases generales como mala calidad son más débiles que color incorrecto, accesorio ausente o medida demostrable. La evidencia específica permite al agente formular un caso claro. Trata la cifra de cinco días como un aviso operativo condicionado, no como derecho universal que elimina todas las reglas del vendedor."],
      ["Separar devolución, reembolso y retirada", "Son procesos distintos. La devolución envía el artículo al vendedor si se acepta. El reembolso registra el dinero cuando vendedor o plataforma finalizan el proceso. La retirada mueve un saldo disponible por un método compatible según reglas actuales. El Help Center coloca reembolsos y retiradas bajo cuenta y pago, recordando que aceptar una devolución no equivale a dinero externo instantáneo. Comprueba cronología, recepción del vendedor y saldo por separado. Guarda referencias hasta que los fondos lleguen. No prometas un número fijo de días sin política vigente del método: respuesta del vendedor, liquidación del marketplace y procesamiento financiero pueden sumar tiempos diferentes."],
      ["Documentar problemas sin exagerar", "Una solicitud sólida es estrecha y factual. Relaciona opción con una o dos fotos, describe la diferencia visible y pide resolución. Una medición apoya discrepancia de tabla; una vista amplia muestra color o modelo; un primer plano muestra costura o pieza faltante. No afirmes falsedad, daño interno o composición si las fotos no lo demuestran. Exagerar distrae de un problema visible que el vendedor sí puede resolver. Guarda la ficha original porque puede cambiar. Si no se ve en fotos estándar, utiliza una opción adicional antes del plazo. La evidencia debe ser comprensible para alguien que no hizo el pedido y no conoce el contexto privado."],
      ["Leer exclusiones antes de comprar", "La planificación de devoluciones comienza en la ficha. Productos personalizados, de higiene, liquidación o hechos bajo pedido pueden tener condiciones estrechas. Algunos vendedores aceptan defectos visibles, no cambio de opinión o ajuste subjetivo. El transporte nacional de retorno puede reducir el importe. Si una exclusión no es aceptable, elige otro vendedor antes de pagar. Un agente negocia y transmite pruebas, pero no garantiza aprobación fuera de términos. Por eso una spreadsheet no debe llamar sin riesgo a un artículo solo porque el enlace carga. El comprador necesita el aviso en vivo, medidas y comprensión realista de lo que cuenta como problema de calidad en esa ficha concreta."],
      ["Usar almacenamiento para planificar", "USFans mantiene una política de almacén, pero duración, periodo gratuito y tratamiento deben leerse en la cuenta actual, no en una afirmación externa sin fecha. Almacenamiento y devolución resuelven cosas distintas. El producto puede seguir almacenado cuando la ventana del vendedor ya terminó. Planifica compras para que artículos relacionados lleguen lo bastante cerca como para revisar y consolidar sin olvidar los primeros. Registra recepción y fecha límite de cada uno. Si uno se retrasa, decide si el resto debe esperar. Guardar demasiado también puede dificultar recuperar una ficha cambiante o resolver pruebas, aunque el artículo físico continúe en almacén."],
      ["Consolidar solo artículos aprobados", "No envíes paquete solo porque todo aparece almacenado. Marca cada artículo como aprobado, devolución solicitada, pendiente de prueba o excluido. El embalaje inicia otra etapa y puede complicar la devolución. Confirma cantidades y accesorios. Si falta medida o foto, solicítala mientras el producto sigue asociado al pedido individual. Agrupa restricciones y dimensiones compatibles y decide sobre cajas después. Un registro limpio evita incluir accidentalmente algo dudoso y reduce discusiones sobre qué debía enviarse. La lista del paquete debe ser consecuencia de decisiones individuales ya cerradas, no un sustituto de la inspección ni una forma de acelerar sin revisar."],
      ["Conservar la cadena de evidencia", "Guarda URL, aviso del vendedor, variante, pago, fotos, fecha, solicitud y mensajes. Si se aprueba reembolso, conserva seguimiento de retorno y asiento del saldo. Esta cadena diferencia negativa del vendedor de retraso de plataforma y ayuda si un proveedor de pago pide documentación. Las capturas deben mostrar pedido y opción, no fragmentos sin contexto. No publiques números privados ni conversaciones del personal en contenido público. El objetivo es un expediente personal que respalde la transacción. Una guía responsable enseña qué conservar sin convertir una disputa privada en una afirmación general sobre todos los pedidos, vendedores o resultados de USFans."],
      ["Seguir una secuencia práctica", "La secuencia repetible es: abrir al llegar, confirmar identidad, revisar fotos gratuitas, pedir medida esencial, comparar términos y aprobar o solicitar devolución documentada. Después anota límite de almacén, agrupa compatibles y estima paquete. El vendedor controla producto y condiciones; USFans gestiona compra, evidencia y comunicación; el comprador decide qué incertidumbre acepta. Ninguna guía garantiza reembolso o resultado. Sí puede evitar plazos perdidos, pruebas débiles y envío accidental. Ese es el valor de tratar el almacén como etapa activa de investigación en vez de sala de espera entre checkout y transporte internacional." ]
    ]
  },
  "taobao-weidian-1688": {
    sourceLabel: "Fuentes oficiales comprobadas el 2 de septiembre de 2026: página principal y Beginner’s Guide de USFans, que identifican Taobao, Weidian y 1688 como fuentes compatibles.",
    sections: [
      ["Qué cambia el agente y qué no", "USFans se presenta como agente para Taobao, Weidian y 1688. Puede interpretar enlaces, comprar, recibir, fotografiar y organizar el paquete. No convierte a todos los vendedores en una misma tienda. Calidad de ficha, stock, variantes, despacho y posventa siguen dependiendo del origen. Lee la página para saber exactamente qué se compra. Una URL válida no basta: comprueba tienda, imágenes, menú, base de precio, cantidad mínima y devoluciones. Cuanto mejor se entienda el anuncio original, más fácil será seleccionar la opción correcta y comparar la llegada. El agente ejecuta el proceso, pero no crea información que falta ni sustituye la decisión del comprador."],
      ["Leer Taobao como ficha de consumo", "Taobao agrupa muchos colores, tallas y estilos en una página. La imagen puede mostrar colección y el precio promocional solo una opción. Lee secuencia de imágenes, atributos y menú juntos. Busca medidas y comprueba si los accesorios están incluidos. Los indicadores de tienda dan contexto, no sustituyen evidencia del producto. Elige opción exacta y guarda la relación entre texto e imagen. Si la traducción de un color es ambigua, usa rasgos objetivos y una nota breve donde sea compatible. Nunca confíes en el título de una spreadsheet para resolver un menú vivo que ha cambiado desde que se guardó el enlace."],
      ["Leer Weidian como ruta del vendedor", "Weidian es común en catálogos especializados. Una ficha puede usar nombres cortos de lote, notas de stock o pocas medidas porque presupone conocimiento previo. Confirma que tienda y producto sigan activos y compara opciones con imágenes actuales. Si hay varios precios, identifica la versión correcta en vez de elegir el menor. Medidas o posventa ausentes son incertidumbre, no permiso para inventar. Guarda la URL exacta porque el mismo vendedor puede publicar productos parecidos cerca. El agente puede comprar lo seleccionado, pero antes del pago el comprador necesita una especificación clara de variante, talla, cantidad y rasgos visibles que luego pueda comparar con el almacén."],
      ["Leer 1688 como ficha mayorista", "1688 está orientado a mayoristas y fábricas, por lo que precio y cantidad se interpretan distinto. Un precio bajo puede corresponder a tramo de cantidad, componente, muestra o variante. Comprueba pedido mínimo, mezcla de colores, unidades, precio y envío nacional. Si existen rangos, calcula el total de la cantidad real, no copies el menor valor unitario. Las especificaciones para comercio pueden incluir diferencias de lote o embalaje. El agente realiza la transacción, pero no elimina una condición mayorista. Un comprador de una sola unidad debe confirmar que el vendedor acepta esa cantidad antes de declarar que 1688 es más barato que una alternativa de consumo."],
      ["Comparar el precio sobre la misma base", "Compara variante, cantidad y envío dentro de China, no solo el titular. Promociones de Taobao, lotes de Weidian y tramos de 1688 pueden representar productos distintos. Convierte a USD después de conocer CNY real y etiqueta el resultado como orientativo. Mantén el impacto del paquete aparte. Un precio menor puede exigir más unidades, más volumen o reglas más estrictas. No existe un marketplace siempre más barato. Compara el pedido nacional completo para una especificación idéntica y valora si medidas, fotos y condiciones justifican el riesgo. Una tabla transparente con bases iguales es mucho más útil que números predeterminados que en realidad describen selecciones diferentes."],
      ["Controlar errores de variante y cantidad", "Antes de pagar escribe una especificación que otra persona pueda seguir: producto, color, talla o medidas, cantidad y versión. Compárala con el resumen. En 1688 confirma si la cantidad se aplica por color, talla o mezcla. En Weidian relaciona nombre de lote con la fotografía. En Taobao comprueba que un accesorio barato no sea el valor predeterminado. Evita notas largas que contradigan el menú; la opción en vivo debe controlar el pedido y la nota solo aclarar un detalle objetivo. Esta disciplina reduce el caso en que el agente compra exactamente lo seleccionado, pero lo seleccionado por el comprador era la versión equivocada."],
      ["Usar señales del vendedor sin garantía", "Historial, imágenes de compradores, antigüedad y publicaciones repetidas ayudan a priorizar, pero no garantizan la unidad. Busca consistencia entre descripción, tabla y evidencia reciente. Desconfía cuando las fotos se copian, faltan especificaciones o el menú no corresponde. Una spreadsheet organiza y elimina enlaces muertos, pero no verifica todas las afirmaciones. El QC documenta el artículo recibido y aun así no prueba autenticidad, interior o duración. Las señales del vendedor sirven para decidir qué investigar más, no para llamar seguro o genuino a un producto sin prueba. La confianza debe aumentar por información coherente y comprobable, no por una sola métrica de tienda."],
      ["Comprobar devoluciones antes del pedido", "Los términos del marketplace y vendedor definen las opciones del agente. Personalización, liquidación, mayorista o ausencia de devoluciones sin calidad dificultan el retorno. Los avisos actuales suelen citar cinco días tras almacén, pero siguen las exclusiones y aprobación. Lee antes de pagar, especialmente sin medidas o con muchas unidades. Si el riesgo no encaja, un vendedor claro es mejor que esperar que las fotos creen un derecho inexistente. El agente negocia y maneja logística nacional, pero no anula todas las políticas. Una guía factual separa servicio del agente y obligación del vendedor y evita convertir un aviso operativo en promesa absoluta."],
      ["Conectar el enlace con QC y transporte", "Conserva ficha y opción hasta inspeccionar. Al llegar compara identidad, medidas, construcción y accesorios. Después evalúa el paquete: cajas, baterías, líquidos o tamaño pueden cambiar rutas y peso. Un producto fácil de comprar en China puede ser ineficiente o restringido internacionalmente. Investiga el transporte antes del checkout con peso y medidas realistas, y lee restricciones actuales. No supongas que cada artículo puede enviarse a cada país. El recorrido se completa cuando ficha, evidencia de almacén y ruta son compatibles. Separar estas etapas solo en la interfaz no significa que deban decidirse sin relación entre sí."],
      ["Elegir marketplace por calidad de evidencia", "Los tres pueden producir buenos finds. La mejor fuente es la que ofrece ruta activa, variante requerida, precio comprensible, medidas suficientes y términos aceptables. Taobao suele favorecer elección de consumo; Weidian, catálogos especializados; 1688, compras por cantidad. Son tendencias, no promesas. Compara páginas concretas y no hagas un ranking abstracto. El flujo funciona cuando la especificación es clara antes del pago y verificable al recibir. Utiliza spreadsheets para descubrir, USFans para compra y paquete, y un registro para conectarlo todo sin inventar certeza cuando la ficha del vendedor queda incompleta." ]
    ]
  }
};

export default esArticles;
