export const frArticles = {
  "use-usfans-spreadsheet": {
    sourceLabel: "Sources officielles vérifiées le 2 septembre 2026 : Beginner’s Guide, Help Center, estimation des frais et avis d’achat actuels de USFans.",
    sections: [
      ["Ce qu’une spreadsheet USFans utile accomplit réellement", "Une spreadsheet USFans sert surtout d’index de recherche, pas de catalogue garanti. Elle regroupe liens, catégories, prix indicatifs et images de Taobao, Weidian ou 1688, tandis que le vendeur contrôle toujours la fiche, les variantes, le stock, l’expédition chinoise et les retours. Ouvrez chaque candidat et vérifiez le titre, l’image principale, la boutique, le menu et le prix en direct. Une ligne peut être obsolète même si son URL fonctionne encore. La feuille réduit le temps de recherche, mais ne remplace ni la description actuelle ni le contrôle en entrepôt. Cette distinction évite de prendre une vignette séduisante pour une preuve de disponibilité, de version ou de prix final."],
      ["Commencer par une intention, pas par un défilement sans fin", "Définissez d’abord le type de produit, le budget, la couleur, les mesures nécessaires et les contraintes du colis. Pour des chaussures, la longueur intérieure compte souvent davantage qu’une conversion de pointure ; pour une veste, largeur de poitrine, longueur, épaules et manches sont utiles. Recherchez avec quelques mots précis et ne gardez qu’un petit groupe comparable. Sur mobile, catégories et routes directes valent mieux qu’un tableau horizontal. L’objectif n’est pas de collectionner le plus de liens possible, mais de trouver deux ou trois fiches actives évaluables selon les mêmes critères. Cette préparation crée aussi une référence claire pour la vérification lorsque l’article arrive en entrepôt."],
      ["Revalider la fiche en direct", "Un vendeur peut modifier photos, prix, stock, couleurs ou variantes sans changer l’URL. Comparez donc la ligne enregistrée avec la page actuelle. Le titre, l’image, la boutique, les options et le tarif correspondent-ils toujours au produit recherché ? Si le lien aboutit à une recherche générale ou à un autre article, écartez-le. Pour une route valide, conservez le texte exact de la variante, les mesures et les avis sur personnalisation ou retours limités. L’agent peut communiquer avec le vendeur, mais il ne peut pas réécrire ses conditions. La fiche en direct et l’option payée constituent la véritable spécification ; le titre de la spreadsheet reste seulement un moyen de découverte."],
      ["Traiter le prix affiché comme un instantané", "Une référence en USD aide au tri, mais ne garantit pas le coût total. Le prix du marketplace est souvent en CNY et varie selon taille, couleur, quantité ou promotion. Le premier paiement peut inclure l’article et la livraison chinoise ; le colis international est calculé après réception, emballage et choix de route. Conversion, traitement du paiement, services et fret modifient le total. Séparez donc coût produit et coût colis. Notez le CNY en direct, la variante et le transport intérieur, puis prévoyez un budget distinct pour l’international. Le montant faisant foi est celui de l’écran de paiement de l’étape concernée, jamais une conversion ancienne affichée dans la feuille."],
      ["Relier les variantes aux mesures", "Une taille M, 42 ou unique ne prouve pas qu’un article ira comme celui que vous possédez. Comparez les centimètres de la fiche actuelle avec un vêtement ou une chaussure de référence. Pour un haut, poitrine, épaules, manches et longueur ; pour un pantalon, méthode de taille, fourche et entrejambe ; pour une chaussure, longueur intérieure. Conservez le libellé exact de couleur et de variante, car certains vendeurs emploient numéros ou abréviations. Si une mesure essentielle manque, cette absence est un risque à reconnaître. La spreadsheet trouve une route, mais elle ne peut pas fournir des données objectives que le vendeur n’a jamais publiées ni transformer une étiquette en équivalence universelle."],
      ["Suivre la sélection jusqu’à l’entrepôt", "USFans décrit la réception, l’inspection et la photographie en entrepôt. Les fiches actuelles annoncent trois à sept photos QC HD gratuites. Comparez-les à la spécification sauvegardée : variante exacte, couleur attendue, forme visible, accessoires et mesures demandées. La vignette de la spreadsheet n’est pas la référence principale ; la fiche en direct et l’option choisie le sont. Examinez rapidement et conservez les preuves d’une différence. Une bonne sélection ne fait donc pas que raccourcir la recherche : elle crée un état attendu vérifiable après la livraison chinoise, au moment où un retour au vendeur peut encore être envisageable selon les conditions propres au produit."],
      ["Comprendre ce que le QC peut établir", "Les photos peuvent montrer couleur reçue, taille marquée, quantité, silhouette, coutures visibles, emplacement d’un motif et accessoires. Elles ne prouvent ni authenticité, ni durabilité, ni confort, ni structure interne, ni composition exacte. L’éclairage déplace les couleurs, la compression déforme et les angles standard cachent parfois un détail. Utilisez-les comme étape de décision, pas comme certificat. Comparez les éléments symétriques, recherchez des défauts visibles et demandez des mesures objectives lorsque cette option existe et que l’ajustement est important. Si la preuve reste incomplète, décidez si l’incertitude est acceptable avant approbation. Une analyse responsable ne conclut jamais au-delà de ce que l’image démontre vraiment."],
      ["Planifier l’impact du colis", "Un article bon marché peut coûter cher à expédier à cause de sa boîte, de sa protection ou de sa forme. Le poids volumétrique peut dépasser le poids réel, et batteries, liquides ou aimants peuvent réduire les routes. Avant d’ajouter d’autres produits, estimez si la combinaison améliore l’efficacité ou agrandit seulement le carton. USFans fournit un estimateur fondé sur routes et données historiques, mais le montant final peut changer après emballage. Utilisez une fourchette et tenez compte de la protection, du poids, des dimensions, de la destination et des restrictions. La spreadsheet devient alors un outil de planification produit-colis, pas seulement une liste d’achats classée par prix."],
      ["Tenir un petit registre de preuves", "Pour chaque candidat sérieux, gardez URL en direct, date, vendeur, variante, prix CNY, mesures clés et raison de conservation ou rejet. Ajoutez ensuite date d’arrivée, résultat QC et délai de retour visible. Quelques champs constants suffisent ; nul besoin d’une base complexe. Le registre évite de confondre des annonces aux images similaires, révèle les changements de variantes et aide lorsque les commandes arrivent à des dates différentes. Il permet aussi de retirer les entrées anciennes. La fiabilité vient moins d’un nombre spectaculaire de finds que de routes actuelles, d’images contrôlables et d’un historique de décision qui ne disparaît pas entre recherche, commande et entrepôt."],
      ["Le standard pratique d’une spreadsheet en 2026", "Une bonne spreadsheet accélère la découverte sans cacher l’incertitude. Elle propose catégories claires, images actuelles, routes directes, références USD bien identifiées et une mise en page mobile sans défilement latéral imposé. Elle rappelle surtout de vérifier la fiche, comparer les mesures, examiner rapidement les photos, respecter les délais et estimer le colis. Aucune feuille ne garantit comportement du vendeur, taille, authenticité, légalité ou douane. Sa mission est plus étroite et plus utile : organiser les éléments que le client peut réellement contrôler. Utilisée ainsi, elle ouvre un processus de recherche traçable au lieu de remplacer la diligence nécessaire par une collection de vignettes." ]
    ]
  },
  "beginner-ordering-guide": {
    sourceLabel: "Sources officielles vérifiées le 2 septembre 2026 : Beginner’s Guide, Help Center, estimation des frais et fiches produit actuelles de USFans.",
    sections: [
      ["Comprendre le parcours en deux étapes", "Acheter via un agent chinois ne ressemble pas au paiement d’une boutique internationale classique. La première étape couvre la fiche, la commande et la livraison à l’entrepôt. La seconde commence après réception : contrôler les photos QC, choisir les articles du colis, décider l’emballage et payer le fret international. Les séparer est la meilleure habitude budgétaire. Un prix marketplace faible n’est pas le coût rendu, et une commande confirmée n’est pas encore un envoi international. Considérez chaque écran comme une porte de décision : valider l’annonce avant le premier paiement, l’article reçu avant le colis, puis la route et le poids facturable avant le second paiement."],
      ["Commencer avec une route produit complète", "USFans indique prendre en charge Taobao, Weidian et 1688. Une commande exploitable commence par une URL active montrant encore vendeur, variantes et prix. Comparez la vue de l’agent à la fiche d’origine : image, titre, couleur et taille doivent correspondre. Si la page n’est pas correctement interprétée, ne devinez pas à partir d’un ancien titre de spreadsheet. Une commande manuelle n’est raisonnable que si l’article exact peut être décrit objectivement. Plus la fiche est complète, plus l’agent peut sélectionner correctement et plus il sera facile de démontrer ce qui était attendu si l’entrepôt enregistre un produit différent. Conservez toujours lien et sélection avant paiement."],
      ["Choisir la variante exacte avant de payer", "Les menus de couleur, taille, lot et quantité utilisent des libellés courts compris avec les images. Gardez le texte exact et comparez les mesures plutôt que de traduire automatiquement une taille familière. Sur 1688, le tarif peut dépendre du volume ; sur Taobao ou Weidian, une option promotionnelle peut désigner autre chose. Lisez les avis sur personnalisation, retours et accessoires séparés. Une remarque doit être courte et objective et ne remplace jamais l’option du menu. Avant le premier paiement, vérifiez produit, livraison en Chine et récapitulatif. Le transport international est calculé plus tard ; le montant produit n’est donc pas le coût complet jusqu’à votre adresse."],
      ["Savoir quand l’achat est traité", "Les avis actuels indiquent un traitement des commandes payées entre 09:00 et 18:00, heure de Chine UTC+8. Il s’agit d’une fenêtre de service, pas d’une promesse d’expédition immédiate. Stock, réponse du vendeur, week-end, congés et transport intérieur prolongent parfois le délai. Consultez la confirmation d’achat et le suivi au lieu d’interpréter quelques heures sans changement comme un échec. Si une option manque ou si un remplacement est proposé, comparez-le à l’annonce d’origine. Conservez la décision dans l’historique. L’agent achète en votre nom, mais le vendeur garde la maîtrise du stock, de la préparation et de l’expédition domestique."],
      ["Séparer expédition vendeur et arrivée au dépôt", "Un numéro de suivi chinois montre un déplacement vers l’entrepôt ; l’article n’est pas encore inspecté ni prêt pour l’international. Attendez réception, enregistrement et photos QC. Une commande multiple peut arriver en plusieurs colis, et différents vendeurs livrent rarement ensemble. Utilisez la chronologie pour séparer reçu et en transit. Si un colis semble bloqué, examinez le dernier scan avant d’ouvrir une demande. Le jalon utile n’est pas seulement expédié, mais reçu et associé au bon ordre. Préparer le colis avant toutes les arrivées prévues peut forcer une division inutile ou laisser un produit derrière, avec un coût et une attente supplémentaires."],
      ["Contrôler les trois à sept photos QC", "Les pages actuelles annoncent trois à sept photos QC HD gratuites. Confirmez d’abord couleur, taille marquée, modèle et quantité. Examinez ensuite forme, symétrie, coutures, motif, quincaillerie et accessoires. Comparez enfin les mesures visibles avec le tableau du vendeur et une référence personnelle. Ces images constituent un contrôle visuel, pas un test de laboratoire : elles ne prouvent pas authenticité, confort, intérieur ou longévité. Si un angle essentiel manque, vérifiez les options de photo ou mesure supplémentaire. Agissez vite, car un délai vendeur peut commencer à l’arrivée et non le jour où vous ouvrez finalement les images."],
      ["Décider rapidement d’un retour", "De nombreuses fiches mentionnent une demande dans les cinq jours suivant l’arrivée et une négociation de l’agent avec le vendeur. Elles peuvent aussi exclure les articles personnalisés ou les retours sans problème de qualité. Considérez cinq jours comme une limite possible uniquement si la commande l’affiche ; ce n’est pas un droit universel. Pour une mauvaise variante ou un défaut visible, envoyez option, photo et écart précis. N’attendez pas l’emballage. Une demande n’est pas une approbation garantie : vendeur, délai, état et frais de retour chinois influencent le résultat. La méthode la plus sûre examine chaque article dès son enregistrement."],
      ["Construire le colis autour du poids facturable", "Après approbation, combinez seulement des produits compatibles et comparez les routes selon destination et contenu. Une ligne peut facturer le plus élevé entre poids réel et calcul volumétrique. Boîtes de chaussures, vêtements gonflants et protection peuvent coûter davantage que leur masse. Décidez de garder les boîtes, renforcer ou séparer les contenus sensibles. La consolidation réduit des frais de base, mais un grand carton augmente le volume. Le bon colis n’est pas toujours la combinaison maximale. Vérifiez dimensions estimées, règles et restrictions et gardez une marge entre dépôt et mesure finale. Cette planification empêche une économie sur l’article de devenir une mauvaise surprise au stade du fret."],
      ["Traiter le paiement d’expédition comme un dépôt", "Le guide explique que le dépôt international repose sur poids estimé, méthode et destination, puis que le total est fixé après emballage. L’estimateur indique une variation fréquente d’environ plus ou moins cinq à dix pour cent liée au poids, au volume et aux données réelles. Un petit remboursement ou supplément n’est donc pas automatiquement une erreur. Comparez poids, dimensions et route finaux aux valeurs prévues. Si l’écart est beaucoup plus important, demandez les données enregistrées. Ne publiez jamais le devis d’un utilisateur comme prix durable : destination, contenu, saison, disponibilité des lignes et options douanières peuvent modifier le montant."],
      ["Finir avec des preuves et des attentes réalistes", "Conservez commande, variante, photos, déclaration, dimensions, route et suivi jusqu’à la livraison et la fin de toute réclamation. Le tracking peut rester silencieux entre export et premier scan du pays. La douane peut contrôler, taxer, retourner, saisir ou détruire selon la loi locale ; l’agent ne garantit pas ce résultat. Ce qui peut être contrôlé : choisir une fiche active, documenter la variante, vérifier rapidement, respecter les conditions vendeur, prévoir le coût complet et choisir une route adaptée au colis réel. Cette méthode est moins impulsive qu’un find viral, mais produit moins de surprises et un dossier bien plus clair si l’assistance devient nécessaire." ]
    ]
  },
  "qc-photo-checklist": {
    sourceLabel: "Sources officielles vérifiées le 2 septembre 2026 : Beginner’s Guide, Help Center et avis QC et retours actuels de USFans.",
    sections: [
      ["Utiliser le QC comme point de décision visuel", "USFans indique inspecter et photographier après réception ; les pages actuelles annoncent trois à sept images HD gratuites. Elles permettent de comparer ce qui est arrivé avec ce qui a été commandé avant l’international. Ce n’est ni une certification ni une authentification. Les photos standard montrent un état visible depuis peu d’angles et sous éclairage d’entrepôt. Elles fonctionnent mieux lorsque variante, fiche et mesures importantes ont été sauvegardées. Posez une question étroite : les preuves correspondent-elles suffisamment pour approuver, ou existe-t-il un écart précis justifiant retour ou photo complémentaire ? Cette approche évite les jugements vagues fondés seulement sur une première impression esthétique."],
      ["Confirmer l’identité avant la qualité", "Le premier contrôle est administratif : couleur, taille marquée, modèle, quantité et éléments inclus. Un article parfait peut être la mauvaise variante. Comparez étiquettes et emballage au texte exact de la commande, sans prendre l’étiquette pour preuve de taille ou matière. Distinguez les versions proches par leurs signes visibles et comptez paires ou ensembles. Si une carte de commande ou une mesure apparaît, vérifiez qu’elle appartient au bon produit. Une attribution photo peut être erronée et se corrige plus facilement avant l’emballage. Ce n’est qu’après une identité raisonnablement établie qu’il faut juger silhouette, construction et état cosmétique."],
      ["Lire la forme générale et la symétrie", "Utilisez les vues larges de face, dos et côté avant d’agrandir. Pour des chaussures, comparez bouts, talons, panneaux et symétrie ; pour les vêtements, col, épaules, longueur et manches ; pour les sacs, anses, structure et alignement. La compression peut déformer temporairement et l’angle change les proportions. Consultez plusieurs vues. Une bonne note nomme l’emplacement et la différence, par exemple poche gauche nettement plus haute, plutôt que mauvaise forme. Une observation précise peut être transmise au vendeur et distingue un défaut visible d’une impression subjective. Ne concluez pas sur un seul angle étrange lorsque les autres vues racontent une histoire différente."],
      ["Inspecter coutures, motifs et finition", "Agrandissez les zones sollicitées : épaules, entrejambe, coins de poche, jonctions de semelle, sangles et extrémités de zip. Cherchez points sautés, fils, coutures ouvertes, colle, bords décollés et espacement irrégulier. Comparez motif ou broderie en centrage, échelle et position avec les images actuelles. La lumière déplace les couleurs et modifie les matières réfléchissantes ; un petit écart sur une seule photo reste faible. Les images montrent la surface, pas la résistance intérieure ou la tenue après usage. Le but est de détecter des anomalies visibles, non de prévoir toute la durée de vie d’un produit à partir d’une photo compressée."],
      ["Intégrer les mesures au QC", "Les mesures transforment une impression en contrôle utile. Comparez poitrine, longueur, épaules et manches avec un vêtement possédé en utilisant la même méthode. Pour un pantalon, précisez si la taille est à plat, étirée ou en tour. Pour les chaussures, la longueur intérieure est souvent plus informative que l’étiquette. Sacs et accessoires peuvent demander largeur, hauteur ou sangle. Si les photos gratuites n’incluent pas la mesure nécessaire, regardez les services supplémentaires. N’estimez jamais des centimètres d’après la table du dépôt : la perspective trompe. Une mesure objective peut soutenir rapidement un retour lorsqu’elle diffère matériellement du tableau du vendeur."],
      ["Compter quincaillerie et accessoires", "Comptez sangles, lacets, pochettes, breloques, boutons, pièces de rechange et tout accessoire promis par la variante. Examinez zips, boucles, pressions, crochets et métal visible pour repérer absence ou dommage évident. Un zip fermé ne prouve pas qu’il glisse bien et un film protecteur change l’aspect ; limitez la conclusion. Pour l’électronique, vérifiez modèle visible, prise et accessoires, pas la batterie ou les performances internes. Si un élément essentiel est caché, demandez une photo ciblée avant la fin du délai. Un accessoire manquant est beaucoup plus facile à documenter en entrepôt qu’après le transport international."],
      ["Reconnaître les limites de la preuve", "Les photos QC ne prouvent pas authenticité, composition, confort, odeur, étanchéité, batterie, construction interne ou durabilité. Elles ne garantissent pas non plus légalité ou admission douanière. Même une image HD dépend de l’éclairage, de la mise au point, de la compression et de l’angle. Formulez chaque conclusion avec sa limite : la taille marquée correspond et aucun défaut de surface évident n’apparaît, mais l’ajustement reste incertain sans mesure de poitrine. Cette formulation est plus honnête que parfait et empêche qu’un guide indépendant paraisse garantir le vendeur. Une checklist aide à décider sous incertitude ; elle ne supprime pas cette incertitude."],
      ["Agir dans la fenêtre après-vente", "Les avis actuels mentionnent souvent une demande sous cinq jours après arrivée et une négociation avec le vendeur. La fiche précise peut exclure les articles personnalisés ou le simple changement d’avis ; les termes en direct prévalent. Contrôlez dès l’apparition des photos, sans attendre le reste du haul. En cas de problème visible, fournissez variante, image et description courte. Évitez l’exagération et les plaintes sans rapport. Une demande n’est pas un remboursement validé : politique, temps, état et frais intérieurs comptent. Des preuves rapides et claires donnent à l’agent un cas précis à présenter pendant qu’une solution reste pratiquement possible."],
      ["Conserver un enregistrement d’approbation", "Avant approbation, notez : identité confirmée, mesures contrôlées ou acceptées comme inconnues, défauts visibles examinés et accessoires comptés. Gardez les images avec la commande et expliquez l’acceptation d’une variation pour un produit coûteux. Ce dossier évite les confusions lors de la consolidation et sépare problème vendeur, dommage de transport et erreur d’emballage. Il facilite aussi les achats futurs. Une checklist n’a de valeur que si elle change le comportement : vérifier vite, poser des questions ciblées, retourner un article clairement incorrect lorsque les conditions le permettent et approuver seulement si l’incertitude restante correspond à votre tolérance."],
      ["Approuver les preuves, pas l’enthousiasme", "La décision finale doit être précise : variante, dimensions importantes, construction visible, accessoires et points non résolus. Images virales et commentaires positifs ne remplacent pas le processus, car l’unité en entrepôt est celle que vous recevrez. N’exigez pas non plus des photos une preuve impossible. Si authenticité, performance interne ou composition exacte est essentielle, un parcours visuel via agent peut être inadéquat. Un guide QC solide relie la vraie étape photographique à des limites strictes. Il aide à détecter des erreurs visibles avant le fret sans présenter un ensemble d’images limité comme garantie de qualité, légalité ou longévité." ]
    ]
  },
  "international-shipping-cost": {
    sourceLabel: "Sources officielles vérifiées le 2 septembre 2026 : estimation des frais, Beginner’s Guide, Help Center et avis de route actuels de USFans.",
    sections: [
      ["Utiliser l’estimateur comme fourchette", "L’estimateur public USFans repose sur les routes disponibles et des données historiques. Il aide avant l’achat, mais n’est pas une facture. Il ignore dimensions emballées, protection, disponibilité future et poids mesuré d’un produit non reçu. Entrez destination, poids réaliste et dimensions probables, comparez et sauvegardez date et fourchette. Les tarifs changent. Ne présentez pas une valeur comme prix universel au kilo : pays, contenu, volume, services et restrictions comptent. Une estimation responsable détermine si le produit reste pertinent avec le fret ; elle ne doit pas créer une précision fictive avant que l’entrepôt ne prépare et mesure le colis réel."],
      ["Distinguer poids réel et volumétrique", "Le poids réel vient de la balance. Le poids volumétrique convertit l’espace par longueur multipliée par largeur et hauteur, divisée par un facteur de route. Beaucoup de lignes facturent le plus élevé. Les accessoires denses suivent souvent le réel ; boîtes de chaussures, doudounes et protection produisent du volume. Un article léger n’est donc pas toujours économique. Estimez masse et forme emballée. Diviseurs et arrondis varient ; consultez la règle actuelle plutôt qu’un ancien chiffre. Cette distinction explique pourquoi deux colis du même poids réel peuvent recevoir des tarifs différents et évite d’attribuer automatiquement l’écart à une erreur de facturation."],
      ["Séparer dépôt et mesure finale", "Le guide décrit un dépôt international calculé sur poids estimé, méthode et destination. Le montant final est déterminé après emballage et mesure. L’estimateur indique une fluctuation habituelle d’environ plus ou moins cinq à dix pour cent, influencée par le volume et les données réelles. Un petit remboursement ou supplément peut être normal. Comparez poids, dimensions et ligne finaux aux valeurs du dépôt. Si l’écart dépasse nettement la fourchette, demandez les données enregistrées et tout changement de service. La bonne comparaison n’est pas simplement dépôt contre total, mais entrées estimées contre entrées mesurées sous la même route et le même choix d’emballage."],
      ["Traiter l’emballage comme décision de coût", "L’emballage protège mais modifie le poids facturable. Boîtes, coins, renfort, humidité et rembourrage ajoutent masse ou volume. Retirer une boîte réduit parfois les dimensions mais aussi la protection. Le vide convient aux textiles souples, pas à tous les produits structurés. Décidez sélectivement : quel risque chaque option contrôle-t-elle et comment change-t-elle probablement le carton ? Lorsqu’un essai de colis existe, le résultat utile est la mesure, pas la garantie qu’un transporteur ne remesurera jamais. Une bonne explication montre le compromis entre coût et protection plutôt que de prétendre que tout retirer ou tout conserver est toujours optimal."],
      ["Consolider les articles compatibles", "Regrouper peut réduire les frais de base et simplifier le suivi, mais un article volumineux ou restreint peut déséquilibrer le colis. Comparez un carton commun à deux petits. Vêtements denses et accessoires se consolident souvent bien ; grandes boîtes augmentent le volume. Batteries, liquides ou aimants peuvent supprimer des routes pour tous les produits. Le calendrier compte aussi : attendre un vendeur tardif retient les articles prêts. La meilleure consolidation associe dimensions, restrictions et délais compatibles et ne vise pas le poids maximum. Notez le contenu avant soumission pour ne pas découvrir un produit absent seulement après la fermeture et la mesure du colis."],
      ["Comparer les routes au-delà du prix", "Comparez méthode de poids, restrictions, suivi, indemnisation ou assurance, délai et traitement à destination. Une ligne moins chère peut utiliser un diviseur défavorable ou exclure le contenu. Une ligne rapide apporte peu si douane ou livraison locale dominent. Lisez l’avis actuel et confirmez l’éligibilité. Pour l’assurance, contrôlez événements couverts et plafonds : assurée ne signifie pas remboursement de tout retard, perte ou action douanière. Les performances changent. Publiez un cadre de décision plutôt qu’une meilleure ligne permanente. Le lecteur doit comprendre pourquoi une route correspond à son colis, son pays et son risque, et non mémoriser un nom susceptible de devenir obsolète."],
      ["Budgéter le coût rendu complet", "Le fret n’est qu’une composante. Le budget peut inclure produit, livraison chinoise, conversion, paiement, services, transport international, assurance, taxe, droit et traitement local. Les seuils dépendent du pays et évoluent ; le Help Center sépare donc frais, facturation et tarifs. Ne conseillez jamais une sous-déclaration ou une description fausse. Utilisez des informations exactes et respectez les règles. Un fret bas peut être mauvais s’il exclut un service nécessaire ou une route adaptée. Comparez la décision complète au paiement et gardez une marge pour devise et ajustement final. Le but est le coût rendu, pas une valeur de transport isolée de toutes les autres obligations."],
      ["Comprendre les restrictions avant soumission", "Les lignes peuvent limiter batteries, liquides, poudres, aimants, aliments, pression et autres contenus sensibles. La vente sur le marketplace ne prouve pas la transportabilité ni l’admission au pays. Vérifiez l’avis exact et ne masquez pas la catégorie. Si un article réduit les options, comparez envoi séparé, retour permis ou abandon de l’achat. Légalité et douane restent sous la responsabilité de l’acheteur même si l’agent accepte la commande chinoise. Un lien valide n’est pas un plan de colis valide. Un contenu utile relie découverte et éligibilité assez tôt pour éviter de payer un article ensuite difficile ou impossible à expédier."],
      ["Lire suivi et douane avec réalisme", "Le tracking passe par départ, export, transport, douane et livraison locale. Certaines étapes ont beaucoup de scans ; d’autres restent silencieuses jusqu’au transporteur suivant. Une pause ne prouve pas une perte, mais des exceptions répétées méritent une vérification. La douane peut inspecter, taxer, retourner, saisir ou détruire selon la loi. Gardez déclaration, conditions, photos et paiement. En cas de problème, utilisez le dernier événement et la procédure d’indemnisation, pas une moyenne de jours. Aucun guide responsable ne garantit dédouanement ou date exacte avant de connaître colis, ligne et décision des autorités de destination."],
      ["Créer un historique de transport réutilisable", "Après livraison, notez poids réel, dimensions, route, fret, date d’envoi, date de réception et frais locaux. Votre historique est plus utile qu’une capture d’un autre acheteur car il reflète votre pays, vos produits et vos emballages. Plusieurs colis montrent l’impact des boîtes et les catégories volumétriques. Ils révèlent aussi les changements saisonniers sans promettre la répétition du prix. Utilisez ces données pour améliorer la prochaine estimation, non pour garantir un tarif. Le meilleur contenu apprend à comparer les entrées, rapprocher dépôt et final et évaluer le coût rendu selon des conditions actuelles plutôt que chercher un prix permanent qui n’existe pas." ]
    ]
  },
  "warehouse-returns-guide": {
    sourceLabel: "Sources officielles vérifiées le 2 septembre 2026 : Help Center, Beginner’s Guide et avis d’entrepôt et de retour actuels de USFans.",
    sections: [
      ["Traiter l’arrivée comme un délai, pas une pause", "La réception ouvre l’étape de comparaison et de décision : conserver, retourner ou enquêter. Ce n’est pas un statut passif. Ouvrez la commande dès l’enregistrement, vérifiez l’association des photos et notez l’heure. Les fenêtres vendeur peuvent être courtes. Les avis actuels mentionnent souvent cinq jours pour demander un retour, selon produit et vendeur. Attendre le dernier article d’un haul peut supprimer les options du premier. Utilisez donc l’arrivée comme déclencheur : inspecter, mesurer, documenter et décider. Une politique de stockage plus longue ne prolonge pas automatiquement le droit après-vente et ne remplace jamais une révision rapide."],
      ["Vérifier la variante avant l’état", "Commencez par couleur, taille marquée, modèle, quantité et accessoires. Une mauvaise variante est un problème même sans défaut. Comparez le texte exact aux étiquettes et signes visibles. Comptez les ensembles ; pour les chaussures, examinez les deux côtés ; pour les vêtements, utilisez les mesures. Si le menu utilisait des numéros, gardez la capture reliant numéro et option. Ces preuves clarifient la demande et empêchent de se concentrer sur un petit défaut en oubliant que le produit est fondamentalement différent. La commande définit la spécification ; la vignette de spreadsheet n’était qu’une aide à la découverte et ne doit pas remplacer l’option effectivement payée."],
      ["Employer prudemment la mention de cinq jours", "De nombreuses pages indiquent une demande sous cinq jours et une négociation de l’agent. Cela ne signifie pas approbation automatique. Les articles personnalisés ou les retours sans raison de qualité peuvent être exclus. Politique vendeur, état, moment et fret intérieur influencent la suite. Lisez l’avis exact et soumettez tôt. Identifiez option, différence visible et image correspondante. Mauvaise qualité est plus faible que mauvaise couleur, accessoire absent ou mesure démontrée. Une preuve précise permet à l’agent de présenter un cas clair. Les cinq jours sont une indication opérationnelle conditionnelle, pas un droit universel annulant toutes les règles."],
      ["Séparer retour, remboursement et retrait", "Ce sont trois processus. Le retour renvoie l’article au vendeur s’il est accepté. Le remboursement crédite l’argent après traitement par vendeur ou marketplace. Le retrait déplace un solde disponible via une méthode prise en charge. Le Help Center place remboursements et retraits dans compte et paiement, rappelant qu’un retour approuvé n’est pas un remboursement externe instantané. Vérifiez chronologie, réception vendeur et solde séparément. Conservez les références jusqu’à réception. Ne promettez pas de délai fixe sans règle actuelle pour le moyen de paiement : réponse du vendeur, règlement marketplace et traitement financier peuvent chacun ajouter du temps."],
      ["Documenter sans suraffirmer", "Une demande forte est étroite et factuelle. Associez option à une ou deux photos, décrivez la différence visible et demandez une solution. Une mesure prouve l’écart de tableau ; une vue large montre couleur ou modèle ; un gros plan montre couture ou pièce absente. N’affirmez pas fausseté, dommage interne ou composition si l’image ne le démontre pas. L’exagération détourne d’un problème visible. Gardez la fiche d’origine car elle peut évoluer. Si le défaut n’apparaît pas, utilisez une photo supplémentaire avant la limite. La preuve doit être compréhensible par une personne qui n’a pas passé la commande et ne connaît pas la discussion privée."],
      ["Lire les exclusions avant l’achat", "La planification du retour commence sur la fiche. Personnalisation, hygiène, déstockage ou fabrication peuvent avoir des règles étroites. Certains vendeurs acceptent un défaut visible mais pas un changement d’avis ou de taille ; le retour chinois peut réduire la somme. Si une exclusion est inacceptable, choisissez un autre vendeur avant paiement. L’agent négocie et transmet les preuves, mais ne garantit pas l’accord hors conditions. Une spreadsheet ne doit donc pas qualifier un article de sans risque parce que son lien fonctionne. Il faut l’avis en direct, des mesures et une compréhension réaliste de ce qui constitue un problème de qualité pour cette annonce précise."],
      ["Utiliser le stockage pour planifier", "USFans maintient une politique de stockage, mais durée, gratuité et règles doivent venir du compte actuel, pas d’une source non datée. Stockage et retour vendeur répondent à des questions différentes. Un produit peut rester stockable après la fermeture de son retour. Planifiez les achats pour recevoir les produits associés assez proches sans oublier les premiers. Notez date d’arrivée et limite de chaque ordre. Si l’un tarde, décidez consciemment si les autres attendent. Un stockage long peut aussi compliquer la récupération d’une fiche modifiée ou la résolution des preuves, même si l’objet physique se trouve toujours au dépôt."],
      ["Consolider uniquement les produits approuvés", "Ne soumettez pas un colis parce que tout apparaît stocké. Marquez chaque article : approuvé, retour demandé, preuve en attente ou exclu. L’emballage ouvre une autre étape et peut compliquer le retour. Confirmez quantités et accessoires. Si une mesure ou une photo manque, demandez-la tant que le produit est lié à son ordre individuel. Regroupez restrictions et dimensions compatibles, puis décidez des boîtes. Un registre propre évite l’inclusion accidentelle d’un article douteux et réduit les litiges. La liste du colis doit résulter de décisions individuelles terminées, non remplacer l’inspection dans le seul but d’aller plus vite."],
      ["Conserver la chaîne de preuves", "Gardez URL, avis vendeur, variante, paiement, photos, date, demande et messages. Si le remboursement est accepté, conservez suivi de retour et écriture du solde. Cette chaîne distingue refus vendeur et retard de traitement et aide si un prestataire de paiement demande des documents. Les captures doivent montrer commande et option, pas des fragments isolés. Ne publiez ni numéro privé ni conversation du personnel dans un article public. Le but est un dossier personnel soutenant la transaction. Un bon guide explique quoi conserver sans transformer un litige privé en déclaration générale sur toutes les commandes, tous les vendeurs ou tous les résultats."],
      ["Suivre une séquence pratique", "La séquence répétable est : ouvrir à l’arrivée, confirmer identité, examiner photos gratuites, demander une mesure essentielle, comparer les termes, puis approuver ou documenter le retour. Ensuite notez la limite de stockage, regroupez les produits compatibles et estimez le colis. Le vendeur contrôle produit et retour ; USFans organise achat, preuves et communication ; l’acheteur décide quelle incertitude il accepte. Aucun guide ne garantit remboursement ou produit. Il peut éviter délai manqué, preuve faible et envoi accidentel. C’est la valeur de traiter l’entrepôt comme une étape active de recherche et non comme une salle d’attente entre paiement et transport." ]
    ]
  },
  "taobao-weidian-1688": {
    sourceLabel: "Sources officielles vérifiées le 2 septembre 2026 : accueil et Beginner’s Guide de USFans, qui citent Taobao, Weidian et 1688 comme sources compatibles.",
    sections: [
      ["Comprendre ce que l’agent change", "USFans se présente comme agent pour Taobao, Weidian et 1688. Il peut interpréter le lien, acheter, recevoir, photographier et organiser le colis. Il ne transforme pas tous les vendeurs en une même boutique. Qualité de fiche, stock, variantes, expédition et retours restent propres au vendeur. Lisez la source pour savoir exactement ce qui est demandé. Une URL valide ne suffit pas : contrôlez boutique, images, menu, base tarifaire, quantité minimale et avis de retour. Plus l’annonce est comprise, plus il est simple de sélectionner correctement et de comparer l’arrivée. L’agent exécute le processus, mais ne crée pas les informations absentes de la fiche."],
      ["Lire Taobao comme une fiche consommateur", "Taobao réunit souvent couleurs, tailles et styles sur une page. L’image principale peut présenter une collection et le prix promotionnel seulement une option. Lisez ensemble images, attributs et menu. Cherchez les mesures et vérifiez si les accessoires sont inclus. Les indicateurs de boutique donnent du contexte, sans remplacer une preuve produit. Sélectionnez l’option exacte et gardez la relation texte-image. Si la traduction d’une couleur est ambiguë, utilisez des signes objectifs et une remarque courte lorsque c’est permis. Ne comptez jamais sur le titre d’une spreadsheet pour expliquer un menu qui a changé depuis l’enregistrement du lien."],
      ["Lire Weidian comme une route vendeur", "Weidian est courant dans les catalogues spécialisés. Une page peut employer des noms de lot courts, des notes de stock ou peu de mesures et supposer que le client connaît la gamme. Confirmez boutique et produit actifs, puis comparez options et images actuelles. S’il existe plusieurs prix, identifiez la bonne version au lieu de choisir le minimum. Mesures et conditions absentes constituent une incertitude, pas une invitation à inventer. Sauvegardez l’URL exacte car le vendeur peut avoir des produits très proches. L’agent achète l’option choisie, mais le client doit définir variante, taille, quantité et signes visibles avant paiement pour pouvoir ensuite vérifier."],
      ["Lire 1688 comme une fiche de gros", "1688 vise le gros et les usines, ce qui change la lecture du prix et de la quantité. Un tarif bas peut appartenir à un palier, un composant, un échantillon ou une variante. Vérifiez minimum, mélange de couleurs, unités, prix et livraison chinoise. Pour une plage tarifaire, calculez le total réel de votre quantité au lieu de copier le plus petit prix. Les spécifications commerciales rendent emballage et différences de lot importants. L’agent effectue la transaction, mais n’annule pas les conditions de gros. Un acheteur à l’unité doit confirmer l’acceptation de sa quantité avant de déclarer 1688 moins cher qu’une alternative de détail."],
      ["Comparer le prix sur la même base", "Comparez variante, quantité et livraison chinoise, pas seulement le titre. Promotions Taobao, lots Weidian et paliers 1688 peuvent décrire des produits différents. Convertissez en USD après confirmation des CNY et indiquez que c’est estimatif. Séparez l’impact du colis. Un prix unitaire faible peut demander davantage d’unités, de volume ou des retours plus stricts. Aucun marketplace n’est toujours le moins cher. Comparez la commande nationale complète pour la même spécification et jugez si mesures, images et conditions rendent le risque acceptable. Un tableau aux bases identiques est plus utile qu’une collection de prix par défaut non comparables."],
      ["Contrôler les erreurs de variante et quantité", "Avant paiement, écrivez une spécification exécutable par une autre personne : produit, couleur, taille ou mesure, quantité et version. Comparez au récapitulatif. Sur 1688, confirmez si la quantité vaut par couleur, taille ou mélange. Sur Weidian, reliez le nom du lot à la photo. Sur Taobao, vérifiez qu’un accessoire bon marché n’est pas sélectionné par défaut. Évitez les longues remarques en contradiction avec le menu ; l’option en direct porte la commande et la note ne clarifie qu’un fait. Cette discipline réduit le risque que l’agent achète correctement ce que le client avait sélectionné par erreur."],
      ["Utiliser les signaux vendeur sans garantie", "Historique, images clients, ancienneté et annonces répétées aident à prioriser, mais ne garantissent pas l’unité. Cherchez la cohérence entre description, mesures et preuves récentes. Soyez prudent si les images sont copiées, les spécifications absentes ou le menu incohérent. Une spreadsheet organise et retire les liens morts, mais ne vérifie pas chaque affirmation. Le QC documente l’article reçu et ne prouve toujours ni authenticité, ni intérieur, ni durée. Les signaux servent à décider quoi approfondir, pas à appeler sûr ou authentique un produit sans preuve. La confiance doit venir de plusieurs éléments cohérents et vérifiables."],
      ["Vérifier les retours avant la commande", "Les règles du marketplace et du vendeur définissent les options. Personnalisation, déstockage, gros ou absence de retour sans défaut compliquent le processus. Les avis actuels mentionnent souvent cinq jours après arrivée, mais exclusions et accord vendeur restent applicables. Lisez avant paiement, surtout sans mesures ou pour une grande quantité. Si le risque est inacceptable, un vendeur plus clair vaut mieux que l’espoir que les photos créent un droit inexistant. L’agent négocie et aide la logistique chinoise, sans annuler toute politique. Un guide factuel sépare service de l’agent et obligation du vendeur et n’en fait pas une promesse absolue."],
      ["Relier le lien au QC et au transport", "Conservez annonce et option jusqu’au contrôle. À l’arrivée, comparez identité, mesures, construction visible et accessoires. Ensuite évaluez le colis : boîtes, batteries, liquides et volume changent routes et poids. Un produit facile à acheter en Chine peut être inefficace ou restreint à l’international. Étudiez le transport avant le checkout avec poids et dimensions réalistes et lisez les restrictions. Ne supposez pas que chaque produit part vers chaque pays. Le parcours n’est cohérent que lorsque annonce source, preuve d’entrepôt et route internationale sont compatibles. Ces étapes sont séparées dans l’interface, mais leurs décisions restent liées."],
      ["Choisir le marketplace selon les preuves", "Les trois plateformes peuvent fournir de bons finds. La meilleure source offre une route active, la variante requise, un prix compréhensible, assez de mesures et des conditions acceptables. Taobao favorise souvent le choix grand public ; Weidian, les vendeurs spécialisés ; 1688, l’approvisionnement par quantité. Ce sont des tendances, pas des promesses. Comparez des fiches concrètes plutôt qu’un classement abstrait. Le processus fonctionne lorsque la spécification est claire avant paiement et vérifiable à l’arrivée. Utilisez la spreadsheet pour découvrir, USFans pour acheter et expédier, et un registre pour relier les étapes sans inventer de certitude quand le vendeur laisse des zones inconnues." ]
    ]
  }
};

export default frArticles;
