export const itArticles = {
  "use-usfans-spreadsheet": {
    sourceLabel: "Fonti ufficiali verificate il 2 settembre 2026: Beginner’s Guide, Help Center, stima delle spedizioni e avvisi di acquisto attuali di USFans.",
    sections: [
      ["Che cosa fa davvero uno spreadsheet USFans utile", "Uno spreadsheet USFans funziona soprattutto come indice di ricerca, non come catalogo garantito. Riunisce link, categorie, prezzi indicativi e immagini da Taobao, Weidian e 1688, mentre il venditore continua a controllare inserzione, varianti, disponibilità, spedizione nazionale e resi. Apri ogni candidato e ricontrolla titolo, immagine principale, negozio, menu e prezzo live. Una riga può essere obsoleta anche se l’URL carica ancora. Il foglio riduce il tempo di ricerca, ma non sostituisce la descrizione attuale o il controllo in magazzino. Questa distinzione evita di scambiare una bella miniatura per prova di stock, versione o costo finale."],
      ["Partire da un intento, non dallo scorrimento infinito", "Definisci prima prodotto, budget, colore, misure necessarie e limiti del pacco. Per le scarpe può contare la lunghezza della soletta; per una giacca, torace, schiena, spalle e maniche. Cerca con pochi termini precisi e conserva un gruppo ridotto e confrontabile. Su mobile, categorie chiare e rotte dirette sono più utili di una tabella larga con scorrimento laterale. L’obiettivo non è raccogliere più link possibile, ma arrivare a due o tre inserzioni attive valutabili con gli stessi criteri. Questa preparazione crea anche un riferimento concreto da usare quando il prodotto entra in magazzino e deve essere confrontato con quanto ordinato."],
      ["Riconvalidare l’inserzione live", "I venditori possono modificare foto, prezzo, stock, colori e combinazioni senza cambiare URL. Confronta la riga salvata con la pagina corrente. Titolo, immagine, negozio, opzioni e prezzo descrivono ancora l’articolo cercato? Se il link porta a una ricerca generica o a un prodotto diverso, scartalo. Per una rotta valida, conserva il testo esatto della variante, le misure e gli avvisi su personalizzazione o resi limitati. L’agente può comunicare con il venditore, ma non può riscriverne le condizioni. La pagina live e l’opzione pagata sono la specifica reale; il titolo nello spreadsheet rimane soltanto uno strumento di scoperta."],
      ["Considerare il prezzo come un’istantanea", "Un riferimento in USD aiuta a ordinare, ma non garantisce il costo complessivo. Il marketplace mostra spesso CNY e il prezzo cambia per taglia, colore, quantità o promozione. Il primo pagamento può includere articolo e trasporto in Cina; il pacco internazionale viene calcolato dopo ricezione, imballaggio e scelta della linea. Conversione, gestione del pagamento, servizi e trasporto modificano il totale. Separa quindi costo prodotto e costo pacco. Registra CNY live, variante e spedizione nazionale e crea un budget distinto per l’internazionale. L’importo autorevole è quello della schermata di pagamento della fase corrente, non una vecchia conversione del foglio."],
      ["Abbinare varianti e misure", "Una taglia M, 42 o unica non dimostra che il capo vestirà come quello che possiedi. Confronta i centimetri della pagina attuale con un articolo di riferimento. Per un top servono spesso torace, spalle, maniche e lunghezza; per i pantaloni, metodo della vita, cavallo e interno gamba; per le scarpe, la misura interna. Conserva i testi esatti di colore e variante perché alcuni venditori usano numeri o abbreviazioni. Se manca una misura essenziale, quella mancanza è un rischio da riconoscere. Lo spreadsheet trova la pagina, ma non inventa dati oggettivi mai pubblicati e non trasforma un’etichetta familiare in equivalenza universale."],
      ["Portare la selezione fino al magazzino", "USFans descrive ricezione, ispezione e fotografie in magazzino. Le pagine attuali indicano da tre a sette foto QC HD gratuite. Confrontale con la specifica salvata: variante esatta, colore atteso, forma visibile, accessori e misure richieste. La miniatura dello spreadsheet non è il riferimento principale; lo sono l’inserzione live e l’opzione scelta. Esamina presto e conserva le prove di una differenza. Una buona shortlist non accelera solo la ricerca: crea uno stato atteso verificabile dopo il trasporto nazionale, quando un reso al venditore potrebbe ancora essere possibile in base alle condizioni specifiche del prodotto."],
      ["Capire ciò che il QC può dimostrare", "Le foto possono mostrare colore ricevuto, taglia segnata, quantità, forma, cuciture visibili, posizione della stampa e accessori. Non dimostrano autenticità, durata, comodità, struttura interna o composizione esatta. La luce altera i colori, la compressione deforma e gli angoli standard possono nascondere dettagli. Usale come punto decisionale, non come certificato. Confronta parti simmetriche, cerca difetti evidenti e richiedi misure oggettive se il servizio è disponibile e la vestibilità conta. Se la prova resta incompleta, decidi se l’incertezza è accettabile prima di approvare. Una guida responsabile limita sempre le conclusioni a ciò che l’immagine mostra davvero."],
      ["Pianificare l’impatto del pacco", "Un articolo economico può risultare costoso da spedire per scatola, protezione o forma ingombrante. Il peso volumetrico può superare quello reale e batterie, liquidi o magneti possono ridurre le linee disponibili. Prima di aggiungere altri prodotti, stima se la combinazione migliora l’efficienza o crea solo un cartone maggiore. USFans offre uno stimatore basato su rotte e dati storici, ma il totale può cambiare dopo l’imballaggio. Tratta il risultato come intervallo. Considera protezione, peso, dimensioni, destinazione e restrizioni. Così lo spreadsheet diventa uno strumento di pianificazione prodotto-pacco e non una semplice lista ordinata per prezzo."],
      ["Tenere un piccolo registro delle prove", "Per ogni candidato serio conserva URL live, data, venditore, variante, prezzo CNY, misure chiave e motivo di accettazione o scarto. Aggiungi poi data di arrivo, esito QC e termine di reso visibile. Non serve un database complesso; bastano campi costanti. Il registro evita confusione tra inserzioni con immagini simili, segnala cambi di variante e aiuta quando gli articoli arrivano in giorni diversi. Mostra anche i link vecchi da rimuovere. L’affidabilità dipende meno da un numero spettacolare di finds e più da rotte, immagini e dettagli controllabili senza perdere la cronologia che ha portato alla decisione."],
      ["Lo standard pratico di uno spreadsheet nel 2026", "Un buon spreadsheet accelera la scoperta mantenendo visibile l’incertezza. Dovrebbe offrire categorie chiare, immagini attuali, rotte dirette, riferimenti USD ben etichettati e layout mobile senza scorrimento laterale obbligatorio. Soprattutto, deve ricordare di verificare la pagina live, confrontare misure, controllare presto il QC, rispettare i termini e stimare il pacco. Nessun foglio garantisce comportamento del venditore, vestibilità, autenticità, legalità o dogana. Il suo compito è più ristretto e utile: organizzare le prove che l’acquirente può controllare. Usato così, avvia una ricerca tracciabile invece di sostituire la dovuta cautela con una raccolta di miniature." ]
    ]
  },
  "beginner-ordering-guide": {
    sourceLabel: "Fonti ufficiali verificate il 2 settembre 2026: Beginner’s Guide, Help Center, stima delle spedizioni e pagine prodotto attuali di USFans.",
    sections: [
      ["Comprendere il percorso in due fasi", "Acquistare tramite un agente cinese non equivale al checkout di un negozio internazionale. La prima fase comprende inserzione, ordine e consegna al magazzino. La seconda inizia alla ricezione: foto QC, selezione del pacco, imballaggio e pagamento della spedizione internazionale. Separarle è la migliore abitudine di budget. Un prezzo basso sul marketplace non è il costo a destinazione e una conferma d’acquisto non è una spedizione internazionale. Tratta ogni schermata come un controllo: validare la pagina prima del primo pagamento, l’articolo ricevuto prima del pacco e la rotta con il peso fatturabile prima del secondo pagamento."],
      ["Iniziare con una rotta prodotto completa", "USFans dichiara supporto per Taobao, Weidian e 1688. Un ordine utile parte da un URL attivo che mostra venditore, varianti e prezzo. Confronta la vista dell’agente con la pagina originale: immagine, titolo, colore e taglia devono coincidere. Se il sistema non interpreta la pagina, non indovinare da un vecchio titolo dello spreadsheet. Un ordine manuale è ragionevole solo se l’articolo esatto può essere descritto in modo oggettivo. Più completa è l’inserzione, più facile sarà acquistare correttamente e mostrare cosa ci si aspettava se il magazzino registra qualcosa di diverso. Conserva link e selezione prima del pagamento."],
      ["Scegliere la variante esatta prima di pagare", "I menu di colore, taglia, lotto e quantità usano etichette brevi comprensibili accanto alle immagini. Salva il testo esatto e confronta le misure invece di tradurre automaticamente una taglia. Su 1688 il prezzo può dipendere dalla quantità; su Taobao o Weidian un’opzione promozionale può indicare altro. Leggi avvisi su personalizzazione, resi e accessori separati. Una nota deve essere corta e oggettiva e non sostituisce mai il menu. Prima del primo pagamento controlla prodotto, trasporto nazionale e riepilogo. La spedizione internazionale viene calcolata più tardi, quindi quel valore non è il costo completo fino all’indirizzo finale."],
      ["Sapere quando viene gestito l’acquisto", "Gli avvisi attuali indicano che gli ordini pagati vengono gestiti dalle 09:00 alle 18:00, ora cinese UTC+8. È una finestra di servizio, non una promessa di spedizione immediata. Stock, risposta del venditore, weekend, festività e logistica nazionale possono estendere i tempi. Controlla conferma e tracking invece di considerare alcune ore senza cambiamenti come errore. Se un’opzione non è disponibile o viene proposto un sostituto, confrontalo con l’inserzione originale. Mantieni la decisione nella cronologia. L’agente acquista per tuo conto, ma il venditore continua a controllare disponibilità, preparazione e consegna interna."],
      ["Separare partenza dal venditore e ricezione", "Un numero di tracking cinese mostra soltanto movimento verso il magazzino. Il prodotto non è ancora ispezionato o pronto per l’internazionale. Attendi ricezione, registrazione e foto. Un ordine multiplo può arrivare in pacchi diversi e venditori differenti raramente consegnano insieme. Usa la cronologia per distinguere ricevuto e in transito. Se una spedizione sembra ferma, leggi l’ultimo evento prima di aprire una pratica. Il traguardo utile non è solo spedito, ma ricevuto e abbinato all’ordine. Creare il pacco prima che arrivino tutti gli articoli previsti può costringere a dividerlo o lasciare un acquisto indietro."],
      ["Controllare le tre-sette foto QC", "Le pagine attuali annunciano da tre a sette foto QC HD gratuite. Prima conferma colore, taglia segnata, modello e quantità. Poi guarda forma, simmetria, cuciture, stampa, metallo e accessori. Infine confronta le misure visibili con la tabella e un capo personale. Le immagini standard sono un controllo visivo, non un test di laboratorio: non provano autenticità, comfort, interno o durata. Se manca un angolo essenziale, verifica le opzioni di foto o misura aggiuntiva. Agisci presto, perché il termine del venditore può iniziare all’arrivo e non il giorno in cui decidi di aprire le fotografie."],
      ["Decidere rapidamente su un reso", "Molte pagine menzionano una richiesta entro cinque giorni dall’arrivo e la negoziazione dell’agente. Possono anche escludere prodotti personalizzati o resi senza motivo di qualità. Considera cinque giorni un limite possibile solo quando compare nell’ordine concreto, non un diritto universale. Per variante errata o difetto visibile, invia opzione, foto e differenza precisa. Non aspettare l’imballaggio. La richiesta non garantisce approvazione: venditore, tempistica, condizione e costo di ritorno nazionale influiscono. Il metodo più sicuro controlla ogni prodotto subito dopo la registrazione e conserva le prove prima che la finestra applicabile si chiuda."],
      ["Costruire il pacco sul peso fatturabile", "Dopo l’approvazione combina solo merci compatibili e confronta le linee per destinazione e contenuto. Una rotta può fatturare il maggiore tra peso reale e volumetrico. Scatole di scarpe, capi imbottiti e protezione possono costare più della massa. Decidi se tenere scatole, rinforzare o separare contenuti sensibili. Consolidare riduce costi ripetuti, ma un cartone grande aumenta il volume. Il pacco giusto non è sempre la combinazione massima. Controlla dimensioni stimate, regole e restrizioni e lascia margine tra deposito e misura finale. In questo modo il risparmio sul prodotto non diventa una sorpresa nella fase del trasporto."],
      ["Trattare il pagamento come deposito", "La guida spiega che il deposito internazionale deriva da peso stimato, metodo e destinazione e che il totale viene determinato dopo l’imballaggio. Lo stimatore indica una variazione frequente di circa più o meno cinque-dieci per cento dovuta a peso, volume e dati reali. Un piccolo rimborso o supplemento non dimostra automaticamente un errore. Confronta peso, dimensioni e rotta finali con la stima. Se lo scarto è molto maggiore, richiedi i dati registrati. Non presentare mai il preventivo di un utente come prezzo permanente: destinazione, contenuto, stagione, disponibilità delle linee e opzioni doganali possono cambiare l’importo."],
      ["Concludere con registri e aspettative realistiche", "Conserva ordine, variante, foto, dichiarazione, dimensioni, rotta e tracking fino alla consegna e alla fine di eventuali reclami. Il tracciamento può restare fermo tra esportazione e primo evento locale. La dogana può ispezionare, tassare, restituire, sequestrare o distruggere secondo la legge; l’agente non garantisce l’esito. Ciò che puoi controllare è scegliere una pagina live, documentare la variante, verificare presto, rispettare i termini, prevedere il costo completo e usare una linea adatta al pacco reale. È meno impulsivo di un find virale, ma produce meno sorprese e un dossier più chiaro se serve assistenza." ]
    ]
  },
  "qc-photo-checklist": {
    sourceLabel: "Fonti ufficiali verificate il 2 settembre 2026: Beginner’s Guide, Help Center e avvisi QC e reso attuali di USFans.",
    sections: [
      ["Usare il QC come decisione visiva", "USFans indica ispezione e foto dopo la ricezione; le pagine attuali annunciano tre-sette immagini HD gratuite. Consentono di confrontare ciò che è arrivato con ciò che è stato pagato prima dell’internazionale. Non sono certificazione o autenticazione. Le foto standard mostrano condizioni visibili da pochi angoli e sotto luce di magazzino. Funzionano meglio quando variante, pagina e misure importanti sono già salvate. Poni una domanda ristretta: le prove corrispondono abbastanza per approvare oppure esiste una differenza specifica che giustifica reso o foto aggiuntiva? Questo metodo evita giudizi vaghi basati solo sull’impressione estetica della prima immagine."],
      ["Confermare l’identità prima della qualità", "Il primo controllo è amministrativo: colore, taglia segnata, modello, quantità e parti incluse. Un articolo perfetto può essere la variante sbagliata. Confronta etichette e confezione con il testo esatto dell’ordine senza trattarle come prova di vestibilità o materiale. Distingui versioni simili tramite elementi visibili e conta coppie e set. Se compare una scheda ordine o misura, verifica che appartenga al prodotto corretto. Le foto possono essere associate male e risolvere prima dell’imballaggio è più semplice. Solo dopo aver stabilito ragionevolmente l’identità passa a forma, costruzione e condizione cosmetica."],
      ["Leggere forma generale e simmetria", "Usa viste ampie davanti, dietro e di lato prima di ingrandire. Per scarpe confronta punta, tallone, pannelli e simmetria; per capi, collo, spalle, lunghezza e maniche; per borse, manici, struttura e allineamento. La compressione può deformare temporaneamente e l’angolo cambia proporzioni, quindi guarda più viste. Una nota QC efficace indica posizione e differenza, come tasca sinistra chiaramente più alta, invece di scrivere forma scarsa. Un’osservazione specifica può essere inoltrata al venditore e distingue un difetto visibile da una sensazione soggettiva. Non concludere da un solo angolo strano se le altre foto mostrano prospettive diverse."],
      ["Ispezionare cuciture, stampe e finiture", "Ingrandisci le zone sotto stress: spalle, cavallo, angoli delle tasche, giunzioni della suola, cinghie e estremità delle zip. Cerca punti saltati, fili, cuciture aperte, colla, bordi sollevati e spazi irregolari. Confronta stampa o ricamo per centratura, dimensione e posizione con le immagini attuali. La luce altera colore e materiali riflettenti, perciò una piccola differenza in una foto è prova debole. Le immagini mostrano la superficie, non la resistenza interna o la durata dell’adesivo. L’obiettivo è trovare anomalie visibili, non prevedere l’intera vita utile da una foto compressa."],
      ["Integrare le misure nel QC", "Le misure trasformano un’impressione in controllo utile. Confronta torace, lunghezza, spalle e maniche con un capo tuo usando lo stesso metodo. Per i pantaloni chiarisci se la vita è piatta, tesa o circonferenza. Per le scarpe, la lunghezza interna è spesso più utile dell’etichetta. Borse e accessori possono richiedere larghezza, altezza o tracolla. Se le immagini gratuite non includono la misura necessaria, verifica i servizi aggiuntivi. Non stimare centimetri dal tavolo del magazzino: la prospettiva inganna. Una misura oggettiva può sostenere rapidamente un reso quando differisce in modo rilevante dalla tabella del venditore."],
      ["Contare ferramenta e accessori", "Conta cinghie, lacci, pochette, charm, bottoni, ricambi e ogni accessorio promesso dalla variante. Controlla zip, fibbie, bottoni a pressione, ganci e metallo visibile per assenze o danni evidenti. Una zip chiusa non prova che scorra bene e una pellicola cambia l’aspetto; limita le conclusioni. Per elettronica verifica modello visibile, spina e accessori, non batteria o prestazioni interne. Se una parte essenziale è nascosta, chiedi una foto mirata prima del termine. Un accessorio mancante è molto più semplice da documentare all’arrivo in magazzino che dopo il trasporto internazionale."],
      ["Riconoscere i limiti della prova", "Le foto QC non dimostrano autenticità, composizione, comodità, odore, impermeabilità, capacità della batteria, costruzione interna o durata. Non garantiscono neppure legalità o ammissione doganale. Anche l’HD dipende da luce, fuoco, compressione e angoli. Formula ogni conclusione con il limite: la taglia indicata coincide e non appare un difetto superficiale evidente, ma la vestibilità è incerta senza misura del torace. È più onesto di perfetto e impedisce che una guida indipendente sembri garantire il venditore. Una checklist aiuta a decidere nell’incertezza; non elimina quell’incertezza né trasforma immagini limitate in prova di prestazioni future."],
      ["Agire nella finestra post-vendita", "Gli avvisi attuali citano spesso una richiesta entro cinque giorni dall’arrivo e una negoziazione col venditore. La pagina precisa può escludere articoli personalizzati o ripensamenti; prevalgono i termini live. Controlla appena compaiono le foto e non aspettare il resto del haul. Per un problema visibile presenta variante, immagine e descrizione breve. Evita esagerazioni e lamentele non correlate. Una richiesta non è un rimborso approvato: politica, tempo, condizione e costo nazionale incidono. Prove chiare e tempestive consentono all’agente di presentare un caso preciso mentre una soluzione pratica è ancora possibile."],
      ["Conservare un registro di approvazione", "Prima di approvare annota identità confermata, misure verificate o accettate come ignote, difetti visibili controllati e accessori contati. Conserva le foto con l’ordine e spiega l’accettazione di una variazione per articoli costosi. Il registro evita confusione durante il consolidamento e separa problema del venditore, danno di transito ed errore di imballaggio. Facilita anche acquisti futuri. Una checklist vale solo se cambia il comportamento: controllare presto, fare domande mirate, restituire merce chiaramente errata quando i termini lo permettono e approvare soltanto se l’incertezza rimasta rientra nella propria tolleranza."],
      ["Approvare le prove, non l’entusiasmo", "La decisione finale deve essere specifica: variante, dimensioni importanti, costruzione visibile, accessori e punti non risolti. Immagini virali e commenti positivi non sostituiscono il processo perché l’unità in magazzino è quella che riceverai. Non chiedere neppure alle foto prove impossibili. Se autenticità, prestazione interna o composizione esatta sono essenziali, un flusso visivo tramite agente può non essere adatto. Una guida QC solida collega la fase fotografica reale a limiti disciplinati. Aiuta a trovare errori visibili prima del trasporto senza presentare un set limitato come garanzia di qualità, legalità o durata." ]
    ]
  },
  "international-shipping-cost": {
    sourceLabel: "Fonti ufficiali verificate il 2 settembre 2026: stima delle spedizioni, Beginner’s Guide, Help Center e avvisi di rotta attuali di USFans.",
    sections: [
      ["Usare lo stimatore come intervallo", "Lo stimatore pubblico USFans si basa su linee disponibili e dati storici. Aiuta prima dell’acquisto, ma non è una fattura. Non conosce dimensioni imballate, protezione, disponibilità futura o peso misurato di merce non ricevuta. Inserisci destinazione, peso realistico e misure probabili, confronta e salva data e intervallo. Le tariffe cambiano. Non presentare un valore come prezzo universale per chilogrammo: paese, contenuto, volume, servizi e restrizioni contano. Una stima responsabile decide se il prodotto resta sensato con il trasporto; non deve creare precisione fittizia prima che il magazzino prepari e misuri il pacco reale."],
      ["Distinguere peso reale e volumetrico", "Il peso reale viene dalla bilancia. Il volumetrico converte lo spazio con lunghezza per larghezza per altezza diviso un fattore della linea. Molte rotte fatturano il maggiore. Accessori densi seguono spesso il reale; scatole di scarpe, piumini e protezione generano volume. Un articolo leggero non è sempre economico. Stima massa e forma imballata. Divisori e arrotondamenti cambiano; consulta la regola corrente invece di copiare un numero vecchio. Questa distinzione spiega perché due pacchi con lo stesso peso reale ricevono prezzi diversi e impedisce di attribuire automaticamente lo scarto a un errore di fatturazione."],
      ["Separare deposito e misura finale", "La guida descrive un deposito internazionale calcolato su peso stimato, metodo e destinazione. Il totale viene determinato dopo imballaggio e misura. Lo stimatore indica una fluttuazione tipica di circa più o meno cinque-dieci per cento, influenzata da volume e dati reali. Un piccolo rimborso o supplemento può essere normale. Confronta peso, dimensioni e linea finali con i valori del deposito. Se lo scarto supera chiaramente l’intervallo, chiedi i dati registrati e gli eventuali cambi di servizio. Il confronto giusto non è soltanto deposito contro totale, ma input stimati contro input misurati sulla stessa rotta e con lo stesso imballaggio."],
      ["Trattare l’imballaggio come decisione di costo", "L’imballaggio protegge ma modifica il peso fatturabile. Scatole, paraspigoli, rinforzi, protezione dall’umidità e imbottitura aggiungono massa o volume. Rimuovere una scatola riduce talvolta le dimensioni ma anche la protezione. Il sottovuoto va bene per tessuti morbidi, non per ogni oggetto strutturato. Decidi selettivamente: quale rischio controlla l’opzione e come cambia il cartone? Se esiste una prova pacco, il risultato utile è la misura, non la garanzia contro ogni ripesatura del vettore. Una buona spiegazione mostra il compromesso tra costo e protezione invece di dire che togliere tutto o tenere tutto è sempre ottimale."],
      ["Consolidare articoli compatibili", "Raggruppare può ridurre costi base e semplificare tracking, ma un articolo grande o ristretto può sbilanciare il pacco. Confronta un cartone unico con due minori. Abbigliamento denso e accessori spesso si consolidano bene; scatole grandi aumentano il volume. Batterie, liquidi o magneti possono eliminare linee per tutti. Conta anche il tempo: aspettare un venditore tardivo trattiene merce pronta. Il miglior consolidamento combina dimensioni, restrizioni e scadenze compatibili e non punta al peso massimo. Annota il contenuto prima dell’invio per non scoprire un articolo assente dopo la chiusura e la misura del pacco."],
      ["Confrontare le linee oltre il prezzo", "Confronta metodo di peso, restrizioni, tracking, risarcimento o assicurazione, tempi e gestione a destinazione. Una linea economica può usare un divisore sfavorevole o escludere il contenuto. Una linea rapida serve poco se dogana o consegna locale dominano. Leggi l’avviso corrente e conferma l’idoneità. Per l’assicurazione controlla eventi coperti e limiti: assicurato non significa rimborso per ogni ritardo, perdita o azione doganale. Prestazioni e tariffe cambiano. Pubblica un criterio decisionale, non una presunta linea migliore per sempre. Il lettore deve capire perché una rotta si adatta al suo pacco, paese e rischio."],
      ["Preventivare il costo completo a destinazione", "Il trasporto è solo una parte. Il budget può includere prodotto, consegna cinese, conversione, pagamento, servizi, spedizione internazionale, assicurazione, imposta, dazio e gestione locale. Le soglie dipendono dal paese e cambiano; l’Help Center separa quindi costi, fatturazione e riferimenti tariffari. Non consigliare mai sottodichiarazioni o descrizioni false. Usa informazioni accurate e rispetta le regole. Un prezzo di trasporto basso può essere una scelta peggiore se esclude servizi o usa una rotta inadatta. Confronta la decisione completa al pagamento e lascia margine per valuta e conguaglio finale. L’obiettivo è il costo a destinazione, non una cifra isolata."],
      ["Comprendere le restrizioni prima dell’invio", "Le linee possono limitare batterie, liquidi, polveri, magneti, cibo, pressione e altri contenuti sensibili. La vendita sul marketplace non prova trasportabilità o ammissione nel paese. Controlla l’avviso esatto e non nascondere la categoria. Se un articolo riduce le opzioni, confronta invio separato, reso permesso o rinuncia all’acquisto. Legalità e dogana restano responsabilità dell’acquirente anche se l’agente accetta l’ordine nazionale. Un link valido non è un piano pacco valido. Un contenuto utile collega scoperta e idoneità abbastanza presto da evitare di pagare merce poi difficile o impossibile da spedire."],
      ["Leggere tracking e dogana realisticamente", "Il tracking passa da uscita, esportazione, trasporto, dogana e consegna locale. Alcune fasi hanno molti eventi, altre restano ferme fino al vettore successivo. Una pausa non prova perdita, ma eccezioni ripetute meritano controllo. La dogana può ispezionare, tassare, restituire, sequestrare o distruggere secondo legge. Conserva dichiarazione, condizioni, foto e pagamento. Se nasce un problema, usa l’ultimo evento e la procedura di risarcimento, non una media di giorni. Nessuna guida responsabile garantisce sdoganamento o data esatta prima di conoscere pacco, linea e decisione delle autorità del paese di destinazione."],
      ["Creare uno storico di spedizione riutilizzabile", "Dopo la consegna annota peso reale, dimensioni, rotta, costo, data di partenza, arrivo e tasse locali. Il tuo storico è più utile di uno screenshot altrui perché riflette paese, prodotti e imballaggi personali. Più pacchi mostrano l’impatto delle scatole e quali categorie producono volume. Rivelano anche cambi stagionali senza promettere che il vecchio prezzo torni. Usa i dati per migliorare la stima successiva, non per garantire una tariffa. Il miglior contenuto insegna a confrontare input, riconciliare deposito e finale e valutare il costo completo con condizioni attuali invece di inseguire un prezzo permanente inesistente." ]
    ]
  },
  "warehouse-returns-guide": {
    sourceLabel: "Fonti ufficiali verificate il 2 settembre 2026: Help Center, Beginner’s Guide e avvisi attuali di magazzino e reso di USFans.",
    sections: [
      ["Trattare l’arrivo come scadenza, non pausa", "La ricezione apre la fase di confronto e decisione: tenere, restituire o indagare. Non è uno stato passivo. Apri l’ordine appena registrato, verifica l’abbinamento delle foto e annota l’orario. Le finestre del venditore possono essere brevi. Gli avvisi attuali citano spesso cinque giorni per chiedere un reso, soggetti a condizioni. Aspettare l’ultimo articolo di un haul può eliminare le opzioni del primo. Usa quindi l’arrivo come attivatore: ispezionare, misurare, documentare e decidere. Una politica di deposito più lunga non estende automaticamente il termine post-vendita e non sostituisce mai una revisione tempestiva."],
      ["Verificare la variante prima della condizione", "Parti da colore, taglia segnata, modello, quantità e accessori. Una variante errata è un problema anche senza difetti. Confronta il testo esatto con etichette e tratti visibili. Conta i set; per le scarpe controlla entrambi i lati; per l’abbigliamento usa le misure. Se il menu usava numeri, conserva lo screenshot che collega numero e opzione. Queste prove chiariscono la richiesta ed evitano di concentrarsi su piccoli dettagli dimenticando che il prodotto è diverso. Il record dell’ordine definisce la specifica; la miniatura dello spreadsheet era solo un aiuto alla scoperta e non sostituisce l’opzione effettivamente pagata."],
      ["Usare con cautela l’avviso dei cinque giorni", "Molte pagine indicano una richiesta entro cinque giorni e una negoziazione dell’agente. Non significa approvazione automatica. Prodotti personalizzati o resi senza ragione di qualità possono essere esclusi. Politica, condizione, tempo e trasporto nazionale influenzano l’esito. Leggi l’avviso esatto e invia presto. Identifica opzione, differenza visibile e foto corrispondente. Qualità scarsa è più debole di colore errato, accessorio mancante o misura dimostrata. Una prova precisa consente all’agente di presentare un caso chiaro. I cinque giorni sono un’indicazione operativa condizionata, non un diritto universale che annulla ogni regola del venditore."],
      ["Separare reso, rimborso e prelievo", "Sono processi diversi. Il reso invia l’articolo al venditore se accettato. Il rimborso accredita il denaro dopo la gestione di venditore o marketplace. Il prelievo sposta un saldo disponibile attraverso un metodo supportato. L’Help Center colloca rimborsi e prelievi nell’area account e pagamenti, ricordando che un reso approvato non è denaro esterno immediato. Controlla cronologia, ricezione del venditore e saldo separatamente. Conserva i riferimenti fino all’arrivo dei fondi. Non promettere giorni fissi senza una regola corrente del metodo: risposta del venditore, regolamento del marketplace ed elaborazione finanziaria possono aggiungere tempi diversi."],
      ["Documentare senza esagerare", "Una richiesta forte è ristretta e fattuale. Abbina l’opzione a una o due foto, descrivi la differenza visibile e chiedi una soluzione. Una misura prova lo scarto dalla tabella; una vista ampia mostra colore o modello; un dettaglio mostra cucitura o parte mancante. Non affermare falsità, danno interno o composizione se l’immagine non lo dimostra. L’esagerazione distrae da un problema risolvibile. Conserva l’inserzione originale perché può cambiare. Se il difetto non appare, usa una foto aggiuntiva prima della scadenza. La prova deve essere comprensibile a una persona che non ha fatto l’ordine e non conosce conversazioni private."],
      ["Leggere le esclusioni prima dell’acquisto", "La pianificazione del reso inizia nell’inserzione. Personalizzazione, igiene, saldo o produzione su richiesta possono avere regole strette. Alcuni venditori accettano difetti visibili, non ripensamenti o vestibilità soggettiva; il ritorno in Cina può ridurre la somma. Se un’esclusione è inaccettabile, scegli un altro venditore prima di pagare. L’agente negozia e trasmette le prove, ma non garantisce approvazione fuori dai termini. Uno spreadsheet non deve quindi chiamare un prodotto senza rischio solo perché il link funziona. Servono avviso live, misure e comprensione realistica di ciò che conta come problema per quella specifica inserzione."],
      ["Usare il deposito per pianificare", "USFans mantiene una politica di magazzino, ma durata, periodo gratuito e regole devono venire dall’account attuale, non da una fonte non datata. Deposito e reso del venditore risolvono problemi diversi. Un prodotto può essere ancora conservabile dopo la chiusura del termine di reso. Pianifica gli acquisti perché i prodotti collegati arrivino abbastanza vicini senza dimenticare i primi. Annota data e limite di ogni ordine. Se uno ritarda, decidi consapevolmente se gli altri devono aspettare. Un deposito lungo può anche rendere più difficile recuperare una pagina cambiata o risolvere le prove, anche se l’oggetto fisico resta in magazzino."],
      ["Consolidare solo articoli approvati", "Non inviare un pacco solo perché tutto appare immagazzinato. Segna ogni prodotto come approvato, reso richiesto, prova in attesa o escluso. L’imballaggio apre una fase diversa e può complicare il ritorno. Conferma quantità e accessori. Se manca una misura o foto, chiedila finché il prodotto è legato all’ordine individuale. Raggruppa restrizioni e dimensioni compatibili e poi decidi le scatole. Un registro pulito evita l’inclusione accidentale di merce dubbia e riduce contestazioni. La lista del pacco deve derivare da decisioni individuali già completate, non sostituire l’ispezione per andare più veloce."],
      ["Conservare la catena delle prove", "Salva URL, avviso del venditore, variante, pagamento, foto, data, richiesta e messaggi. Se il rimborso viene approvato, conserva tracking di ritorno e movimento del saldo. Questa catena distingue rifiuto del venditore e ritardo della piattaforma e aiuta se un fornitore di pagamento chiede documenti. Gli screenshot devono mostrare ordine e opzione, non frammenti isolati. Non pubblicare numeri privati o conversazioni dello staff in un articolo pubblico. L’obiettivo è un dossier personale che sostenga la transazione. Una buona guida spiega cosa conservare senza trasformare una disputa privata in un’affermazione generale su ogni ordine o venditore."],
      ["Seguire una sequenza pratica", "La sequenza ripetibile è: aprire all’arrivo, confermare identità, esaminare foto gratuite, chiedere una misura essenziale, confrontare i termini e approvare o documentare il reso. Poi annota il limite di deposito, raggruppa prodotti compatibili e stima il pacco. Il venditore controlla prodotto e reso; USFans organizza acquisto, prove e comunicazione; il compratore decide quale incertezza accettare. Nessuna guida garantisce rimborso o risultato. Può però evitare scadenze perse, prove deboli e invio accidentale. Questo è il valore di trattare il magazzino come fase attiva di ricerca e non sala d’attesa tra pagamento e trasporto." ]
    ]
  },
  "taobao-weidian-1688": {
    sourceLabel: "Fonti ufficiali verificate il 2 settembre 2026: homepage e Beginner’s Guide di USFans, che citano Taobao, Weidian e 1688 come fonti supportate.",
    sections: [
      ["Capire cosa cambia l’agente", "USFans si presenta come agente per Taobao, Weidian e 1688. Può interpretare il link, acquistare, ricevere, fotografare e organizzare il pacco. Non trasforma tutti i venditori nello stesso negozio. Qualità dell’inserzione, stock, varianti, spedizione e resi restano specifici del venditore. Leggi la fonte per sapere esattamente cosa chiedi di comprare. Un URL valido non basta: controlla negozio, immagini, menu, base di prezzo, quantità minima e reso. Più la pagina è compresa, più è semplice scegliere correttamente e confrontare l’arrivo. L’agente esegue il processo, ma non crea informazioni mancanti nell’inserzione."],
      ["Leggere Taobao come inserzione consumer", "Taobao spesso riunisce colori, taglie e stili in una pagina. L’immagine principale può mostrare una collezione e il prezzo promozionale solo un’opzione. Leggi insieme immagini, attributi e menu. Cerca le misure e verifica gli accessori inclusi. Gli indicatori del negozio offrono contesto ma non sostituiscono prove del prodotto. Seleziona l’opzione esatta e salva la relazione testo-immagine. Se la traduzione di un colore è ambigua, usa caratteristiche oggettive e una nota breve quando consentita. Non affidarti mai al titolo dello spreadsheet per spiegare un menu live che è cambiato dopo il salvataggio del link."],
      ["Leggere Weidian come rotta del venditore", "Weidian è comune nei cataloghi specializzati. Una pagina può usare nomi brevi di lotto, note di stock o poche misure e presupporre conoscenza della gamma. Conferma negozio e prodotto attivi e confronta opzioni e immagini correnti. Se ci sono prezzi multipli, individua la versione giusta invece di scegliere il minimo. Misure o condizioni assenti sono incertezza, non invito a inventare. Salva l’URL esatto perché lo stesso venditore può pubblicare articoli simili. L’agente compra l’opzione scelta, ma prima del pagamento il cliente deve definire variante, taglia, quantità e tratti visibili che possa poi verificare."],
      ["Leggere 1688 come inserzione all’ingrosso", "1688 è orientato a ingrosso e fabbriche, quindi prezzo e quantità vanno letti diversamente. Un prezzo basso può appartenere a fascia, componente, campione o variante. Controlla minimo, colori misti, unità, prezzo e spedizione in Cina. Per un intervallo, calcola il totale della tua quantità invece di copiare il valore più basso. Le specifiche commerciali rendono importanti imballaggio e differenze di lotto. L’agente effettua la transazione, ma non elimina i termini all’ingrosso. Un acquirente di una sola unità deve confermare che la quantità è accettata prima di dichiarare 1688 più economico di un’alternativa retail."],
      ["Confrontare i prezzi sulla stessa base", "Confronta variante, quantità e spedizione cinese, non solo il titolo. Promozioni Taobao, lotti Weidian e fasce 1688 possono descrivere prodotti diversi. Converti in USD dopo aver confermato il CNY ed etichetta il risultato come indicativo. Separa l’impatto del pacco. Un prezzo unitario basso può richiedere più pezzi, volume o resi severi. Nessun marketplace è sempre il più economico. Confronta l’ordine nazionale completo per la stessa specifica e valuta se misure, immagini e condizioni giustificano il rischio. Una tabella su basi uguali è più utile di numeri predefiniti che non sono realmente confrontabili."],
      ["Controllare errori di variante e quantità", "Prima di pagare scrivi una specifica eseguibile da un’altra persona: prodotto, colore, taglia o misura, quantità e versione. Confrontala col riepilogo. Su 1688 conferma se la quantità vale per colore, taglia o mix. Su Weidian collega il nome del lotto alla foto. Su Taobao verifica che un accessorio economico non sia selezionato di default. Evita note lunghe in conflitto col menu; l’opzione live guida l’ordine e la nota chiarisce solo un fatto. Questa disciplina riduce il rischio che l’agente acquisti correttamente ciò che il cliente aveva selezionato per errore."],
      ["Usare i segnali del venditore senza garanzia", "Storico, immagini dei clienti, anzianità e inserzioni ripetute aiutano a dare priorità, ma non garantiscono l’unità. Cerca coerenza tra descrizione, misure e prove recenti. Sii prudente con foto copiate, specifiche assenti o menu incoerenti. Uno spreadsheet organizza e rimuove link morti, ma non verifica ogni affermazione. Il QC documenta l’articolo ricevuto e ancora non prova autenticità, interno o durata. I segnali servono a decidere cosa approfondire, non a definire sicuro o autentico un prodotto senza prova. La fiducia deve nascere da più elementi coerenti e controllabili."],
      ["Verificare i resi prima dell’ordine", "Le regole del marketplace e del venditore definiscono le opzioni. Personalizzazione, saldo, ingrosso o assenza di reso senza difetto complicano il processo. Gli avvisi attuali citano spesso cinque giorni dall’arrivo, ma esclusioni e approvazione restano. Leggi prima di pagare, soprattutto senza misure o per quantità grandi. Se il rischio non è accettabile, un venditore più chiaro è meglio della speranza che le foto creino un diritto inesistente. L’agente negozia e gestisce logistica nazionale, ma non annulla ogni politica. Una guida fattuale separa servizio dell’agente e obbligo del venditore e non trasforma un avviso in promessa assoluta."],
      ["Collegare il link a QC e trasporto", "Conserva inserzione e opzione fino al controllo. All’arrivo confronta identità, misure, costruzione visibile e accessori. Poi valuta il pacco: scatole, batterie, liquidi e volume cambiano linee e peso. Un prodotto facile da comprare in Cina può essere inefficiente o ristretto internazionalmente. Studia il trasporto prima del checkout con peso e dimensioni realistici e leggi le limitazioni. Non presumere che ogni articolo possa andare in ogni paese. Il percorso è coerente solo quando inserzione, prova di magazzino e rotta internazionale sono compatibili. Le fasi sono separate nell’interfaccia, ma le decisioni rimangono collegate."],
      ["Scegliere il marketplace in base alle prove", "Tutti e tre possono produrre buoni finds. La fonte migliore offre rotta attiva, variante richiesta, prezzo comprensibile, misure sufficienti e condizioni accettabili. Taobao favorisce spesso la scelta consumer; Weidian, i venditori specializzati; 1688, l’approvvigionamento per quantità. Sono tendenze, non promesse. Confronta pagine concrete invece di creare classifiche astratte. Il flusso funziona quando la specifica è chiara prima del pagamento e verificabile all’arrivo. Usa lo spreadsheet per scoprire, USFans per acquistare e spedire e un registro per collegare le fasi senza inventare certezza quando il venditore lascia informazioni incomplete." ]
    ]
  }
};

export default itArticles;
