import type { Article } from "../article-copy";
import type { Language } from "../site-content";
import { SiteFooter, SiteHeader } from "./SiteHeader";

export function ArticlePage({ lang, slug, article }: { lang: Language; slug: string; article: Article }) {
  const path=`/articles/${slug}`;
  const labels={en:["FIELD NOTE","Independent research","Official facts rechecked before publication","No transaction services","ARTICLE MAP","Sources checked","Facts, product routes and service terms can change. These links were rechecked on 1 September 2026."],de:["FELDNOTIZ","Unabhängige Recherche","Offizielle Fakten vor Veröffentlichung neu geprüft","Keine Transaktionsdienste","ARTIKELÜBERSICHT","Geprüfte Quellen","Fakten, Produktrouten und Bedingungen können sich ändern. Diese Links wurden am 1. September 2026 geprüft."],es:["NOTA DE CAMPO","Investigación independiente","Datos oficiales revisados antes de publicar","Sin servicios de transacción","MAPA DEL ARTÍCULO","Fuentes revisadas","Datos, rutas y condiciones pueden cambiar. Estos enlaces se revisaron el 1 de septiembre de 2026."],fr:["NOTE DE TERRAIN","Recherche indépendante","Faits officiels revérifiés avant publication","Aucun service de transaction","PLAN DE L’ARTICLE","Sources vérifiées","Faits, liens et conditions peuvent changer. Ces liens ont été vérifiés le 1er septembre 2026."],it:["NOTA SUL CAMPO","Ricerca indipendente","Fatti ufficiali ricontrollati prima della pubblicazione","Nessun servizio di transazione","MAPPA DELL’ARTICOLO","Fonti controllate","Fatti, rotte e condizioni possono cambiare. Questi link sono stati verificati il 1 settembre 2026."]}[lang];
  const relatedBySlug:Record<string,string[]>={"lovegobuy-spreadsheet-guide":["spreadsheet","finds"],"lovegobuy-qc-photo-guide":["qc","guide"],"lovegobuy-shipping-weight":["shipping","qc"]};
  const relatedLabels:Record<Language,Record<string,string>>={en:{spreadsheet:"Product evidence table",finds:"Product routes",qc:"QC photo guide",guide:"Four-pass guide",shipping:"Chargeable-weight guide",articles:"Research articles"},de:{spreadsheet:"Produkt-Nachweistabelle",finds:"Produktrouten",qc:"QC-Fotoratgeber",guide:"Vier-Schritte-Ratgeber",shipping:"Ratgeber zum Abrechnungsgewicht",articles:"Rechercheartikel"},es:{spreadsheet:"Tabla de pruebas",finds:"Rutas de producto",qc:"Guía de fotos QC",guide:"Guía de cuatro pasos",shipping:"Guía de peso facturable",articles:"Artículos de investigación"},fr:{spreadsheet:"Tableau de preuves",finds:"Liens produit",qc:"Guide des photos QC",guide:"Guide en quatre passes",shipping:"Guide du poids facturable",articles:"Articles de recherche"},it:{spreadsheet:"Tabella delle prove",finds:"Rotte prodotto",qc:"Guida alle foto QC",guide:"Guida in quattro passaggi",shipping:"Guida al peso tassabile",articles:"Articoli di ricerca"}};
  const relatedTitle={en:"Related on-site guides",de:"Passende Leitfäden auf dieser Website",es:"Guías relacionadas del sitio",fr:"Guides associés sur ce site",it:"Guide correlate sul sito"}[lang];
  const articleUrl=`https://lovegobuys.shop/${lang}/articles/${slug}`;
  const schema={"@context":"https://schema.org","@graph":[{"@type":"Article",headline:article.title,description:article.deck,dateModified:"2026-09-01",inLanguage:lang,url:articleUrl,author:{"@type":"Organization",name:"LoveGoBuy Field Guide"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"LoveGoBuy Field Guide",item:`https://lovegobuys.shop/${lang}`},{"@type":"ListItem",position:2,name:relatedLabels[lang].articles,item:`https://lovegobuys.shop/${lang}/articles`},{"@type":"ListItem",position:3,name:article.title,item:articleUrl}]}]};
  return <main><SiteHeader lang={lang} path={path} /><article className="long-article"><header className="article-hero shell"><div className="eyebrow"><span>{labels[0]}</span> {article.read}</div><h1>{article.title}</h1><p>{article.deck}</p><div className="article-meta"><span>{labels[1]}</span><span>{labels[2]}</span><span>{labels[3]}</span></div></header><div className="article-body shell"><aside><span>{labels[4]}</span>{article.sections.map((section,i)=><a href={`#a-${i+1}`} key={section.title}><b>0{i+1}</b>{section.title}</a>)}</aside><div className="article-prose">{article.sections.map((section,i)=><section id={`a-${i+1}`} key={section.title}><div className="prose-number">0{i+1}</div><div><h2>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}{section.bullets&&<ul>{section.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</div></section>)}<section className="article-sources"><h2>{labels[5]}</h2><p>{labels[6]}</p>{article.sources.map(source=><a key={source.href} href={source.href} target="_blank" rel="noopener noreferrer">{source.label} ↗</a>)}</section><nav className="article-related" aria-label={relatedTitle}><span>{relatedTitle}</span>{(relatedBySlug[slug]??["guide","articles"]).map(path=><a key={path} href={`/${lang}/${path}`}>{relatedLabels[lang][path]??path} →</a>)}</nav></div></div></article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} /><SiteFooter lang={lang} /></main>;
}
