import type { Article } from "../article-copy";
import type { Language } from "../site-content";
import { SiteFooter, SiteHeader } from "./SiteHeader";

export function ArticlePage({ lang, slug, article }: { lang: Language; slug: string; article: Article }) {
  const path=`/articles/${slug}`;
  const labels={en:["FIELD NOTE","Independent research","Official facts rechecked before publication","No transaction services","ARTICLE MAP","Sources checked","Facts, product routes and service terms can change. These links were rechecked on 1 September 2026."],de:["FELDNOTIZ","Unabhängige Recherche","Offizielle Fakten vor Veröffentlichung neu geprüft","Keine Transaktionsdienste","ARTIKELÜBERSICHT","Geprüfte Quellen","Fakten, Produktrouten und Bedingungen können sich ändern. Diese Links wurden am 1. September 2026 geprüft."],es:["NOTA DE CAMPO","Investigación independiente","Datos oficiales revisados antes de publicar","Sin servicios de transacción","MAPA DEL ARTÍCULO","Fuentes revisadas","Datos, rutas y condiciones pueden cambiar. Estos enlaces se revisaron el 1 de septiembre de 2026."],fr:["NOTE DE TERRAIN","Recherche indépendante","Faits officiels revérifiés avant publication","Aucun service de transaction","PLAN DE L’ARTICLE","Sources vérifiées","Faits, liens et conditions peuvent changer. Ces liens ont été vérifiés le 1er septembre 2026."],it:["NOTA SUL CAMPO","Ricerca indipendente","Fatti ufficiali ricontrollati prima della pubblicazione","Nessun servizio di transazione","MAPPA DELL’ARTICOLO","Fonti controllate","Fatti, rotte e condizioni possono cambiare. Questi link sono stati verificati il 1 settembre 2026."]}[lang];
  const schema={"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.deck,dateModified:"2026-09-01",inLanguage:lang,author:{"@type":"Organization",name:"LoveGoBuy Field Guide"}};
  return <main><SiteHeader lang={lang} path={path} /><article className="long-article"><header className="article-hero shell"><div className="eyebrow"><span>{labels[0]}</span> {article.read}</div><h1>{article.title}</h1><p>{article.deck}</p><div className="article-meta"><span>{labels[1]}</span><span>{labels[2]}</span><span>{labels[3]}</span></div></header><div className="article-body shell"><aside><span>{labels[4]}</span>{article.sections.map((section,i)=><a href={`#a-${i+1}`} key={section.title}><b>0{i+1}</b>{section.title}</a>)}</aside><div className="article-prose">{article.sections.map((section,i)=><section id={`a-${i+1}`} key={section.title}><div className="prose-number">0{i+1}</div><div><h2>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}{section.bullets&&<ul>{section.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</div></section>)}<section className="article-sources"><h2>{labels[5]}</h2><p>{labels[6]}</p>{article.sources.map(source=><a key={source.href} href={source.href} target="_blank" rel="noopener noreferrer">{source.label} ↗</a>)}</section></div></div></article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} /><SiteFooter lang={lang} /></main>;
}
