import type { ContentRecord } from "../page-copy";
import { articleCards, articleSlugs, products, type Language } from "../site-content";
import { SiteFooter, SiteHeader } from "./SiteHeader";

const pathLabels:Record<Language,Record<string,string>>={
  en:{spreadsheet:"Product evidence table",finds:"Product routes",guide:"Four-pass product guide",qc:"QC photo guide",shipping:"Chargeable-weight guide",faq:"Questions and boundaries",articles:"Research articles","articles/lovegobuy-spreadsheet-guide":"Spreadsheet evidence article","articles/lovegobuy-qc-photo-guide":"QC photo article","articles/lovegobuy-shipping-weight":"Shipping-weight article"},
  de:{spreadsheet:"Produkt-Nachweistabelle",finds:"Produktrouten",guide:"Vier-Schritte-Produktratgeber",qc:"QC-Fotoratgeber",shipping:"Ratgeber zum Abrechnungsgewicht",faq:"Fragen und Grenzen",articles:"Rechercheartikel","articles/lovegobuy-spreadsheet-guide":"Artikel zu Spreadsheet-Nachweisen","articles/lovegobuy-qc-photo-guide":"Artikel zu QC-Fotos","articles/lovegobuy-shipping-weight":"Artikel zum Versandgewicht"},
  es:{spreadsheet:"Tabla de pruebas de producto",finds:"Rutas de producto",guide:"Guía de producto en cuatro pasos",qc:"Guía de fotos QC",shipping:"Guía de peso facturable",faq:"Preguntas y límites",articles:"Artículos de investigación","articles/lovegobuy-spreadsheet-guide":"Artículo sobre pruebas de la hoja","articles/lovegobuy-qc-photo-guide":"Artículo sobre fotos QC","articles/lovegobuy-shipping-weight":"Artículo sobre peso de envío"},
  fr:{spreadsheet:"Tableau de preuves produit",finds:"Liens produit",guide:"Guide produit en quatre passes",qc:"Guide des photos QC",shipping:"Guide du poids facturable",faq:"Questions et limites",articles:"Articles de recherche","articles/lovegobuy-spreadsheet-guide":"Article sur les preuves du tableau","articles/lovegobuy-qc-photo-guide":"Article sur les photos QC","articles/lovegobuy-shipping-weight":"Article sur le poids d’expédition"},
  it:{spreadsheet:"Tabella delle prove prodotto",finds:"Rotte prodotto",guide:"Guida prodotto in quattro passaggi",qc:"Guida alle foto QC",shipping:"Guida al peso tassabile",faq:"Domande e limiti",articles:"Articoli di ricerca","articles/lovegobuy-spreadsheet-guide":"Articolo sulle prove del foglio","articles/lovegobuy-qc-photo-guide":"Articolo sulle foto QC","articles/lovegobuy-shipping-weight":"Articolo sul peso di spedizione"},
};
const relatedPaths:Record<string,string[]>={spreadsheet:["finds","articles/lovegobuy-spreadsheet-guide"],finds:["spreadsheet","guide"],guide:["qc","articles/lovegobuy-qc-photo-guide"],qc:["guide","articles/lovegobuy-qc-photo-guide"],shipping:["qc","articles/lovegobuy-shipping-weight"],faq:["guide","articles"]};
const evidenceCopy:Record<Language,{title:string;intro:string;checked:string;price:string;focus:string;weight:string;open:string;related:string;focuses:string[]}>= {
  en:{title:"Current product routes in an evidence table",intro:"These six existing product routes are shown with the same images, USD references and destinations already used on this site. No unavailable weight or material claim has been invented; verify those fields on the live listing and in current QC evidence.",checked:"Route checked 31 Aug 2026",price:"USD reference",focus:"Review focus",weight:"Weight: verify on the live listing or QC record",open:"Open current product route",related:"Continue with a related guide",focuses:["size · fabric · construction","waist · inseam · variant","size · print · variant"]},
  de:{title:"Aktuelle Produktrouten als Nachweistabelle",intro:"Diese sechs bestehenden Produktrouten verwenden dieselben Bilder, USD-Referenzen und Ziele wie bisher. Nicht verfügbare Gewichts- oder Materialangaben wurden nicht erfunden; prüfe sie im aktuellen Eintrag und in den QC-Nachweisen.",checked:"Route geprüft am 31. August 2026",price:"USD-Referenz",focus:"Prüffokus",weight:"Gewicht: im aktuellen Eintrag oder QC-Nachweis prüfen",open:"Aktuelle Produktroute öffnen",related:"Mit einem passenden Ratgeber fortfahren",focuses:["Größe · Stoff · Verarbeitung","Bund · Innenbein · Variante","Größe · Druck · Variante"]},
  es:{title:"Rutas de producto actuales en una tabla de pruebas",intro:"Estas seis rutas existentes conservan las mismas imágenes, referencias USD y destinos del sitio. No se inventan datos de peso o material no disponibles; compruébalos en la ficha actual y en las pruebas QC.",checked:"Ruta revisada el 31 de agosto de 2026",price:"Referencia USD",focus:"Punto de revisión",weight:"Peso: comprobar en la ficha actual o registro QC",open:"Abrir ruta de producto actual",related:"Continuar con una guía relacionada",focuses:["talla · tejido · construcción","cintura · entrepierna · variante","talla · estampado · variante"]},
  fr:{title:"Liens produit actuels dans un tableau de preuves",intro:"Ces six liens existants conservent les mêmes images, références USD et destinations que le site. Aucun poids ou matériau indisponible n’est inventé ; vérifiez ces champs sur la fiche actuelle et dans les preuves QC.",checked:"Lien vérifié le 31 août 2026",price:"Référence USD",focus:"Point à contrôler",weight:"Poids : vérifier sur la fiche actuelle ou le relevé QC",open:"Ouvrir le lien produit actuel",related:"Continuer avec un guide associé",focuses:["taille · tissu · fabrication","tour de taille · entrejambe · variante","taille · impression · variante"]},
  it:{title:"Rotte prodotto attuali in una tabella di prove",intro:"Queste sei rotte esistenti mantengono le stesse immagini, referenze USD e destinazioni del sito. Non vengono inventati peso o materiali non disponibili; verificali nella scheda corrente e nelle prove QC.",checked:"Rotta controllata il 31 agosto 2026",price:"Riferimento USD",focus:"Punto di controllo",weight:"Peso: verifica nella scheda corrente o nel record QC",open:"Apri la rotta prodotto attuale",related:"Continua con una guida correlata",focuses:["taglia · tessuto · costruzione","vita · interno gamba · variante","taglia · stampa · variante"]},
};

export function ContentPage({ lang, slug, copy }: { lang: Language; slug: string; copy: ContentRecord }) {
  const isArticles=slug==="articles";
  const isSpreadsheet=slug==="spreadsheet";
  const labels={en:["INDEPENDENT GUIDE","ON THIS PAGE","Open product directory","Read full article","Research boundary","This independent guide does not process orders, payments, refunds or parcels. Recheck current product destinations and official platform information before acting."],de:["UNABHÄNGIGER LEITFADEN","AUF DIESER SEITE","Produktverzeichnis öffnen","Artikel lesen","Grenzen der Recherche","Dieser unabhängige Leitfaden verarbeitet keine Bestellungen, Zahlungen, Erstattungen oder Pakete. Prüfe aktuelle Zielseiten und offizielle Informationen vor jeder Aktion."],es:["GUÍA INDEPENDIENTE","EN ESTA PÁGINA","Abrir directorio","Leer artículo","Límite de la investigación","Esta guía independiente no procesa pedidos, pagos, reembolsos ni paquetes. Revisa destinos actuales e información oficial antes de actuar."],fr:["GUIDE INDÉPENDANT","SUR CETTE PAGE","Ouvrir l’annuaire","Lire l’article","Limite de recherche","Ce guide indépendant ne traite ni commandes, paiements, remboursements ou colis. Revérifiez les destinations et informations officielles avant d’agir."],it:["GUIDA INDIPENDENTE","IN QUESTA PAGINA","Apri directory","Leggi articolo","Limite della ricerca","Questa guida indipendente non gestisce ordini, pagamenti, rimborsi o pacchi. Ricontrolla destinazioni e informazioni ufficiali prima di agire."]}[lang];
  const breadcrumbs={"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"LoveGoBuy Field Guide",item:`https://lovegobuys.shop/${lang}`},{"@type":"ListItem",position:2,name:copy.title,item:`https://lovegobuys.shop/${lang}/${slug}`}]};
  const schema={"@context":"https://schema.org","@graph":[{"@type":slug==="faq"?"FAQPage":"WebPage",name:copy.title,description:copy.deck,inLanguage:lang,url:`https://lovegobuys.shop/${lang}/${slug}`},breadcrumbs]};
  const evidence=evidenceCopy[lang];
  const related=relatedPaths[slug]??[];
  return <main><SiteHeader lang={lang} path={`/${slug}`} />
    <section className="inner-hero"><div className="shell"><div className="eyebrow"><span>{copy.eyebrow}</span> {labels[0]}</div><h1>{copy.title}</h1><p>{copy.deck}</p></div></section>
    {isArticles ? <section className="section shell"><div className="article-index">{articleCards[lang].map((card:string[],i:number)=><a href={`/${lang}/articles/${articleSlugs[i]}`} className={i===0?"index-card featured":"index-card"} key={card[1]}><span>{card[0]}</span><h2>{card[1]}</h2><p>{card[2]}</p><b>{labels[3]} →</b></a>)}</div></section> :
    <><section className="content-layout section shell"><aside><span>{labels[1]}</span>{copy.sections.map((section,i)=><a key={section.title} href={`#section-${i+1}`}><b>0{i+1}</b>{section.title}</a>)}<a className="source-button" href="https://cnfansge.com/AllProducts/" target="_blank" rel="noopener noreferrer">{labels[2]} ↗</a></aside><article className="prose-card">{copy.sections.map((section,i)=><section id={`section-${i+1}`} key={section.title}><div className="prose-number">0{i+1}</div><div><h2>{section.title}</h2>{section.body.map((p)=><p key={p}>{p}</p>)}{section.points&&<ul>{section.points.map(point=><li key={point}>{point}</li>)}</ul>}</div></section>)}<div className="source-note"><b>{labels[4]}</b><p>{labels[5]}</p></div></article></section>
    {isSpreadsheet&&<section className="evidence-section section shell"><div className="evidence-heading"><span className="kicker">PRODUCT ROUTES / EVIDENCE</span><h2>{evidence.title}</h2><p>{evidence.intro}</p></div><div className="evidence-grid">{products.map((product,i)=>{const focus=i===0?evidence.focuses[0]:i===1?evidence.focuses[1]:evidence.focuses[2];return <a className="evidence-card" key={product.href} href={product.href} target="_blank" rel="noopener noreferrer"><img src={product.image} alt={product.name} width="480" height="480" loading="lazy" decoding="async"/><div><small>{evidence.checked}</small><h3>{product.name}</h3><dl><div><dt>{evidence.price}</dt><dd>{product.price}</dd></div><div><dt>{evidence.focus}</dt><dd>{focus}</dd></div></dl><p>{evidence.weight}</p><b>{evidence.open} ↗</b></div></a>})}</div></section>}
    {related.length>0&&<nav className="related-guides shell" aria-label={evidence.related}><span>{evidence.related}</span>{related.map(path=><a key={path} href={`/${lang}/${path}`}>{pathLabels[lang][path]} →</a>)}</nav>}</>}
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} /><SiteFooter lang={lang} /></main>;
}
