import type { ContentRecord } from "../page-copy";
import { articleCards, articleSlugs, type Language } from "../site-content";
import { SiteFooter, SiteHeader } from "./SiteHeader";

export function ContentPage({ lang, slug, copy }: { lang: Language; slug: string; copy: ContentRecord }) {
  const isArticles=slug==="articles";
  const labels={en:["INDEPENDENT GUIDE","ON THIS PAGE","Open product directory","Read full article","Research boundary","This independent guide does not process orders, payments, refunds or parcels. Recheck current product destinations and official platform information before acting."],de:["UNABHÄNGIGER LEITFADEN","AUF DIESER SEITE","Produktverzeichnis öffnen","Artikel lesen","Grenzen der Recherche","Dieser unabhängige Leitfaden verarbeitet keine Bestellungen, Zahlungen, Erstattungen oder Pakete. Prüfe aktuelle Zielseiten und offizielle Informationen vor jeder Aktion."],es:["GUÍA INDEPENDIENTE","EN ESTA PÁGINA","Abrir directorio","Leer artículo","Límite de la investigación","Esta guía independiente no procesa pedidos, pagos, reembolsos ni paquetes. Revisa destinos actuales e información oficial antes de actuar."],fr:["GUIDE INDÉPENDANT","SUR CETTE PAGE","Ouvrir l’annuaire","Lire l’article","Limite de recherche","Ce guide indépendant ne traite ni commandes, paiements, remboursements ou colis. Revérifiez les destinations et informations officielles avant d’agir."],it:["GUIDA INDIPENDENTE","IN QUESTA PAGINA","Apri directory","Leggi articolo","Limite della ricerca","Questa guida indipendente non gestisce ordini, pagamenti, rimborsi o pacchi. Ricontrolla destinazioni e informazioni ufficiali prima di agire."]}[lang];
  const schema={"@context":"https://schema.org","@type":slug==="faq"?"FAQPage":"WebPage",name:copy.title,description:copy.deck,inLanguage:lang};
  return <main><SiteHeader lang={lang} path={`/${slug}`} />
    <section className="inner-hero"><div className="shell"><div className="eyebrow"><span>{copy.eyebrow}</span> {labels[0]}</div><h1>{copy.title}</h1><p>{copy.deck}</p></div></section>
    {isArticles ? <section className="section shell"><div className="article-index">{articleCards[lang].map((card:string[],i:number)=><a href={`/${lang}/articles/${articleSlugs[i]}`} className={i===0?"index-card featured":"index-card"} key={card[1]}><span>{card[0]}</span><h2>{card[1]}</h2><p>{card[2]}</p><b>{labels[3]} →</b></a>)}</div></section> :
    <section className="content-layout section shell"><aside><span>{labels[1]}</span>{copy.sections.map((section,i)=><a key={section.title} href={`#section-${i+1}`}><b>0{i+1}</b>{section.title}</a>)}<a className="source-button" href="https://cnfansge.com/AllProducts/" target="_blank" rel="noopener noreferrer">{labels[2]} ↗</a></aside><article className="prose-card">{copy.sections.map((section,i)=><section id={`section-${i+1}`} key={section.title}><div className="prose-number">0{i+1}</div><div><h2>{section.title}</h2>{section.body.map((p)=><p key={p}>{p}</p>)}{section.points&&<ul>{section.points.map(point=><li key={point}>{point}</li>)}</ul>}</div></section>)}<div className="source-note"><b>{labels[4]}</b><p>{labels[5]}</p></div></article></section>}
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} /><SiteFooter lang={lang} /></main>;
}
