"use client";

import { useEffect, useState } from "react";

type Lang = "en" | "de" | "fr" | "es" | "it";
type Copy = { title:string; lead:string; checked:string; contents:string; intro:string[]; sections:Array<{h:string;p:string[];bullets?:string[]}>; checklistTitle:string; checklist:string[]; ending:string[] };

const copy: Record<Lang, Copy> = {
  en: {
    title:"Turn a Product Idea Into a Precise Hipobuy Spreadsheet Search Query",
    lead:"Translate a shopping need into observable category, construction and identifier terms, then change one variable at a time so every result set can be reproduced and corrected.",
    checked:"Checked 31 August 2026",
    contents:"In this guide",
    intro:[
      "A precise Hipobuy spreadsheet search query begins before the search box. Write what the product must do, which features can be observed on a listing and which conditions would make you reject a result. This prevents a vague style idea from turning into a long trail of unrelated links.",
      "HipoBuy currently presents itself as a shopping agent for Chinese marketplaces, including Taobao, 1688 and Weidian. That supports the marketplace context of a spreadsheet search, but it does not mean the query method below is an official feature or ranking system. It is an independent retrieval workflow: search produces candidates, not recommendations, quality findings or authenticity conclusions."
    ],
    sections:[
      {h:"1. Write a search brief with hard and soft requirements",p:[
        "Start with one sentence describing the job: for example, ‘a lightweight black zip hoodie for layering, with two front pockets and no large back graphic.’ Separate the sentence into required attributes, preferences and exclusions. The garment type and zip may be required. Black may be a preference if another neutral colour is acceptable. A large back graphic may be an exclusion. This hierarchy matters because a result should not survive by matching several preferences while failing one requirement.",
        "Use only details that a source page can reasonably show: product category, cut, closure, material claim, dimensions, visible construction, model code or compatible device. Words such as best, premium, viral, perfect and must-have do not describe a retrievable object. They add title noise and encourage comparison by marketing strength. Keep fit, quality and durability as later questions unless current measurements or evidence can support them."
      ],bullets:["Required: product category and non-negotiable construction","Preferred: colour, finish or secondary detail","Excluded: a feature that ends the comparison","Unknown: a fact that must be verified on the live page"]},
      {h:"2. Build a compact query in a deliberate order",p:[
        "Begin with the category noun, then add the most discriminating observable attribute. ‘Hoodie’ is broad; ‘two-way zip hoodie’ tests a specific closure. Add a third token only when the result set is still overloaded. Category first usually gives the search enough context to interpret a word such as zip, shell, low-top or messenger. A model code can move earlier when it is exact and central to identity.",
        "Do not paste the entire shopping brief. Long sentences often contain filler, conflicting concepts and rare wording that a product index never stored. A good first query is usually two to four meaningful tokens. Save the exact punctuation and spacing. If the result changes after a hyphen is removed or a model code is split, that difference belongs in the query log rather than being dismissed as random."
      ]},
      {h:"3. Diagnose the result set before editing the query",p:[
        "Label the outcome as useful, overloaded, zero-result or wrong-category. Useful means at least a few results preserve the required product identity. Overloaded means the category is right but noise dominates. Zero-result means one or more tokens may be absent, too specific or expressed differently. Wrong-category means a token is ambiguous or seller titles use it in another context. Naming the failure prevents several simultaneous edits that hide the cause.",
        "For overload, add one discriminating attribute. For zero results, remove the least essential token before trying a genuine spelling or synonym variant. For wrong-category results, move the category noun to the front and remove style language. Change only one thing per test. If ‘two-way zip hoodie’ works and ‘cropped two-way zip hoodie’ fails, you now know the added cut term caused the loss; replacing every word would teach nothing."
      ],bullets:["Overloaded → add one observable discriminator","Zero results → remove the least essential token","Wrong category → lead with the product noun","Useful results → stop editing and inspect candidate identity"]},
      {h:"4. Expand vocabulary without changing the original intent",p:[
        "Use true variants carefully: zip and zipper, trainers and sneakers, colour and color, or a model code with and without its hyphen. Keep each variant as a separate query so you can see which form retrieved the page. Near-synonyms may change the object. A sweatshirt is not automatically a hoodie; a tote is not every shoulder bag; leather-look is not leather. Never merge result sets merely because the words feel related.",
        "Translate concrete nouns and construction terms before translating style labels. If a source title contains an unfamiliar phrase, preserve the original beside the working translation. Do not translate brand-like identifiers, item numbers or technical model codes unless the source provides an established alternative. A translation that makes the phrase sound natural but changes product identity weakens retrieval."
      ]},
      {h:"5. Use a before-and-after query ledger",p:[
        "A useful log needs five fields: the exact query, the result count or outcome label, one representative destination, the failure diagnosis and the next single change. It does not need names, account details, orders or payment information. Store a timestamp because spreadsheet rows and live listings can change. When a saved destination redirects, preserve both the original and final URL without declaring that the new page is equivalent.",
        "Consider a shoe search. ‘Running shoes’ is overloaded. ‘Low-top running shoes gum sole’ may narrow by silhouette and visible outsole. If it returns nothing, test ‘low top running shoe gum outsole’ as one vocabulary branch, then return to the strongest earlier query. The ledger keeps the failed branch useful: it shows which term to omit next time without erasing the original need."
      ],bullets:["Before: black hoodie streetwear best quality → marketing-heavy and untestable","After: black two-way zip hoodie → category, colour and closure","Before: everyday shoulder bag trendy → vague use and hype","After: nylon messenger bag zip closure → form, material claim and closure"]},
      {h:"6. Inspect candidates without turning retrieval into endorsement",p:[
        "Open the final source page and record its current title, destination URL, selected option, visible seller or shop identity, price timestamp and the evidence that matches the query. Mark every unsupported detail unknown. Search relevance does not prove stock, seller reliability, composition, fit, quality or authenticity. It only explains why the page appeared in a result set.",
        "Compare the page with the original hard requirements. Reject a candidate that fails one, even if its thumbnail, promotion or popularity signal is persuasive. When two pages look similar, keep them separate until the exact SKU, option labels and specifications can be matched. A search workflow is successful when it creates a small, explainable set of pages for later verification—not when it produces the largest collection."
      ]}
    ],
    checklistTitle:"Reusable query QA checklist",
    checklist:["Write the product job in one sentence.","Separate required, preferred, excluded and unknown details.","Start with category plus one discriminating observable term.","Save the exact query before editing it.","Name the failure state and change only one token.","Keep true variants separate from near-synonyms.","Open the final source page and preserve the selected option.","Treat every result as a candidate, never as a recommendation."],
    ending:["The best query is not the longest one. It is the shortest expression that preserves the real product need and can be adjusted without losing the reason for each change. A small ledger makes that process reproducible on desktop or mobile and prevents the same failed wording from being repeated.","Platform context was freshly checked on 31 August 2026 against HipoBuy’s public website and app entry. No ranking behaviour, reverse-image search, recommendation system, seller result or purchasing outcome is claimed. Verify the live page and current account workflow before ordering."]
  },
  de: {
    title:"Aus einer Produktidee eine präzise Hipobuy-Spreadsheet-Suchanfrage machen",
    lead:"Übersetze einen Kaufwunsch in beobachtbare Begriffe für Kategorie, Konstruktion und Kennungen. Ändere danach immer nur eine Variable, damit sich jede Ergebnisliste reproduzieren und korrigieren lässt.",checked:"Geprüft am 31. August 2026",contents:"In diesem Ratgeber",
    intro:["Eine präzise Hipobuy-Spreadsheet-Suchanfrage entsteht vor dem Suchfeld. Notiere, was das Produkt leisten muss, welche Merkmale eine Angebotsseite zeigen kann und wann ein Treffer ausscheidet. So wird aus einer vagen Stilidee keine Kette unpassender Links.","HipoBuy beschreibt sich aktuell als Einkaufsagent für chinesische Marktplätze wie Taobao, 1688 und Weidian. Das bestätigt den Marktplatzkontext, macht die folgende Methode aber nicht zu einer offiziellen Funktion oder Rangfolge. Sie ist ein unabhängiger Suchablauf: Treffer sind Kandidaten, keine Empfehlungen, Qualitätsurteile oder Echtheitsnachweise."],
    sections:[
      {h:"1. Suchbrief mit harten und weichen Anforderungen",p:["Beginne mit einem Satz zum Zweck, etwa: „leichter schwarzer Zip-Hoodie zum Layern, zwei Fronttaschen, keine große Rückengrafik“. Teile ihn in Pflichtmerkmale, Wünsche und Ausschlüsse. Produkttyp und Reißverschluss können Pflicht sein, Schwarz ein Wunsch, eine große Rückengrafik ein Ausschluss. Mehrere Wünsche dürfen kein fehlendes Pflichtmerkmal ausgleichen.","Nutze Angaben, die eine Quellseite zeigen kann: Kategorie, Schnitt, Verschluss, Materialangabe, Maße, sichtbare Konstruktion, Modellcode oder Kompatibilität. Wörter wie „beste“, „premium“ oder „viral“ beschreiben kein auffindbares Objekt. Passform, Qualität und Haltbarkeit bleiben spätere Fragen, solange keine belastbaren Maße oder Belege vorliegen."],bullets:["Pflicht: Kategorie und unverzichtbare Konstruktion","Wunsch: Farbe, Oberfläche oder Nebendetail","Ausschluss: Merkmal, das den Vergleich beendet","Unbekannt: muss auf der Live-Seite geprüft werden"]},
      {h:"2. Kurze Anfrage in bewusster Reihenfolge",p:["Beginne mit dem Kategorienomen und ergänze das stärkste beobachtbare Unterscheidungsmerkmal. „Hoodie“ ist breit, „Two-Way-Zip Hoodie“ prüft einen konkreten Verschluss. Ein drittes Wort kommt erst hinzu, wenn die Menge zu groß bleibt. Ein exakter Modellcode darf früher stehen, wenn er die Identität bestimmt.","Kopiere nicht den ganzen Suchbrief. Lange Sätze enthalten Füllwörter, Konflikte oder seltene Formulierungen, die der Index nicht gespeichert hat. Zwei bis vier bedeutungstragende Tokens reichen meist. Speichere auch Bindestriche und Abstände; ändert sich das Ergebnis dadurch, gehört die Beobachtung ins Suchprotokoll."]},
      {h:"3. Ergebnisart vor der Änderung benennen",p:["Kennzeichne das Ergebnis als brauchbar, überladen, ohne Treffer oder falsche Kategorie. Brauchbar heißt: Einige Treffer bewahren die nötige Produktidentität. Überladen heißt: Kategorie stimmt, Rauschen dominiert. Null Treffer deutet auf fehlende, zu genaue oder anders formulierte Tokens. Falsche Kategorie weist auf Mehrdeutigkeit hin.","Bei Überladung ergänze ein beobachtbares Merkmal. Bei null Treffern entferne zuerst das unwichtigste Wort und teste dann eine echte Schreib- oder Synonymvariante. Bei falscher Kategorie stelle das Produktnomen nach vorn. Ändere pro Test nur ein Element, damit die Ursache sichtbar bleibt."],bullets:["Überladen → ein beobachtbares Merkmal ergänzen","Null Treffer → unwichtigstes Token entfernen","Falsche Kategorie → Produktnomen zuerst","Brauchbar → nicht weiter ändern, Kandidaten prüfen"]},
      {h:"4. Wortschatz erweitern, Absicht bewahren",p:["Teste echte Varianten getrennt: zip und zipper, trainers und sneakers oder Modellcodes mit und ohne Bindestrich. Nahe Begriffe können das Objekt ändern. Sweatshirt ist nicht automatisch Hoodie, Tote nicht jede Schultertasche und Lederoptik kein Leder. Vermische Ergebnislisten nicht nur wegen ähnlicher Wörter.","Übersetze konkrete Nomen und Konstruktionsbegriffe vor Stilbezeichnungen. Bewahre unbekannte Originalphrasen neben der Arbeitsübersetzung. Markenähnliche Kennungen, Artikelnummern und technische Modellcodes bleiben unverändert, sofern die Quelle keine feste Alternative nennt." ]},
      {h:"5. Vorher-nachher-Suchprotokoll führen",p:["Ein gutes Protokoll enthält exakte Anfrage, Ergebnislabel, ein repräsentatives Ziel, Diagnose und die nächste einzelne Änderung. Namen, Konto-, Bestell- oder Zahlungsdaten sind unnötig. Ein Zeitstempel ist wichtig, weil Spreadsheet-Zeilen und Live-Angebote wechseln. Bei Weiterleitung werden ursprüngliche und endgültige URL getrennt erhalten.","Beispiel Schuhe: „Running shoes“ ist überladen. „Low-top running shoes gum sole“ grenzt Silhouette und Sohle ein. Gibt es null Treffer, teste eine echte Wortvariante und kehre danach zur stärksten Anfrage zurück. Auch ein gescheiterter Zweig bleibt nützlich, weil er zeigt, welches Wort später entfallen sollte."],bullets:["Vorher: black hoodie streetwear best quality → Marketing, nicht prüfbar","Nachher: black two-way zip hoodie → Kategorie, Farbe, Verschluss","Vorher: everyday shoulder bag trendy → vage und werblich","Nachher: nylon messenger bag zip closure → Form, Materialangabe, Verschluss"]},
      {h:"6. Kandidaten prüfen, ohne sie zu empfehlen",p:["Öffne die endgültige Quellseite und notiere aktuellen Titel, Ziel-URL, gewählte Option, sichtbare Shopidentität, Preiszeitpunkt und passende Belege. Nicht belegte Details heißen „unbekannt“. Relevanz beweist weder Bestand noch Verkäuferzuverlässigkeit, Material, Passform, Qualität oder Echtheit.","Vergleiche mit den Pflichtmerkmalen und verwerfe einen Treffer, der eines nicht erfüllt. Ähnliche Seiten bleiben getrennt, bis SKU, Optionen und Spezifikationen wirklich passen. Erfolg bedeutet eine kleine, erklärbare Liste für die spätere Prüfung – nicht die größte Sammlung." ]}
    ],checklistTitle:"Wiederverwendbare Query-QA",checklist:["Produktaufgabe in einem Satz notieren.","Pflicht, Wunsch, Ausschluss und Unbekannt trennen.","Mit Kategorie plus einem klaren Merkmal beginnen.","Exakte Anfrage vor jeder Änderung speichern.","Fehlerart benennen und nur ein Token ändern.","Echte Varianten und nahe Synonyme trennen.","Endgültige Quellseite und gewählte Option sichern.","Jeden Treffer als Kandidaten behandeln, nie als Empfehlung."],ending:["Die beste Anfrage ist nicht die längste, sondern die kürzeste Form, die den Bedarf bewahrt und gezielte Änderungen erlaubt. Ein kleines Protokoll macht den Ablauf reproduzierbar und verhindert wiederholte Fehlversuche.","Der Plattformkontext wurde am 31. August 2026 auf der öffentlichen HipoBuy-Website und dem App-Einstieg geprüft. Es werden kein Ranking, keine Bildsuche, kein Empfehlungssystem und kein Kaufresultat behauptet. Prüfe Live-Seite und Kontoablauf vor der Bestellung."]
  },
  fr: {
    title:"Transformer une idée produit en requête précise pour le tableur Hipobuy",lead:"Traduisez un besoin d’achat en termes observables de catégorie, construction et identifiant, puis ne changez qu’une variable pour pouvoir reproduire et corriger chaque série de résultats.",checked:"Vérifié le 31 août 2026",contents:"Dans ce guide",
    intro:["Une requête précise pour le tableur Hipobuy se prépare avant la zone de recherche. Notez la fonction du produit, les caractéristiques visibles sur une fiche et les conditions de rejet. Une idée de style vague ne deviendra ainsi pas une suite de liens sans rapport.","HipoBuy se présente actuellement comme un agent d’achat pour des places de marché chinoises telles que Taobao, 1688 et Weidian. Cela confirme le contexte, mais la méthode ci-dessous n’est ni une fonction officielle ni un classement. C’est un processus éditorial indépendant : les résultats sont des candidats, pas des recommandations, jugements de qualité ou preuves d’authenticité."],
    sections:[
      {h:"1. Rédiger un brief avec exigences fortes et souples",p:["Commencez par une phrase de fonction : « sweat noir léger zippé pour superposer, deux poches avant, sans grand visuel au dos ». Séparez obligations, préférences et exclusions. Le type et la fermeture peuvent être obligatoires, le noir une préférence, le grand visuel une exclusion. Plusieurs préférences ne compensent jamais une exigence manquante.","N’utilisez que des faits qu’une page source peut montrer : catégorie, coupe, fermeture, matière déclarée, dimensions, construction visible, code modèle ou compatibilité. « meilleur », « premium » et « viral » ne décrivent pas un objet récupérable. La coupe réelle, la qualité et la durabilité restent des questions ultérieures sans mesures ou preuves solides."],bullets:["Obligatoire : catégorie et construction non négociable","Préféré : couleur, finition ou détail secondaire","Exclu : caractéristique qui arrête la comparaison","Inconnu : fait à vérifier sur la page en direct"]},
      {h:"2. Construire une requête courte dans un ordre choisi",p:["Commencez par le nom de catégorie, puis ajoutez l’attribut observable le plus discriminant. « Hoodie » est large ; « hoodie zip double sens » teste une fermeture précise. N’ajoutez un troisième terme que si les résultats restent trop nombreux. Un code modèle exact peut venir plus tôt s’il définit l’identité.","Ne collez pas tout le brief. Les phrases longues contiennent du bruit, des concepts incompatibles ou des mots rares absents de l’index. Deux à quatre tokens utiles suffisent souvent. Conservez aussi espaces et tirets : si leur modification change le résultat, inscrivez-la dans le journal." ]},
      {h:"3. Diagnostiquer les résultats avant de modifier",p:["Classez l’issue : utile, surchargée, zéro résultat ou mauvaise catégorie. Utile signifie que quelques pages gardent l’identité obligatoire. Surchargée signifie que la catégorie est juste mais noyée dans le bruit. Zéro indique un terme absent, trop précis ou formulé autrement. Une mauvaise catégorie révèle une ambiguïté.","Pour une surcharge, ajoutez un seul attribut observable. Pour zéro résultat, retirez le terme le moins essentiel puis essayez une vraie variante. Pour une mauvaise catégorie, placez le nom du produit en premier et retirez le vocabulaire de style. Une seule modification par test rend la cause visible."],bullets:["Surchargé → ajouter un discriminant observable","Zéro → retirer le terme le moins essentiel","Mauvaise catégorie → commencer par le nom produit","Utile → arrêter l’édition et vérifier les candidats"]},
      {h:"4. Élargir le vocabulaire sans changer l’intention",p:["Testez séparément les vraies variantes : zip et zipper, trainers et sneakers, code modèle avec ou sans tiret. Les quasi-synonymes peuvent changer l’objet. Un sweatshirt n’est pas toujours un hoodie, un tote n’est pas tout sac d’épaule, et l’aspect cuir n’est pas du cuir.","Traduisez d’abord les noms concrets et termes de construction. Gardez l’expression source à côté de la traduction de travail. Ne traduisez pas les identifiants, numéros d’article ou codes techniques sans variante officielle de la source." ]},
      {h:"5. Tenir un journal avant-après",p:["Le journal contient la requête exacte, le label du résultat, une destination représentative, le diagnostic et la prochaine modification unique. Il ne contient ni nom, compte, commande ni paiement. Ajoutez la date, car lignes et fiches changent. En cas de redirection, gardez séparément URL initiale et finale.","Exemple chaussures : « running shoes » est trop large. « low-top running shoes gum sole » précise silhouette et semelle. Si aucun résultat n’apparaît, testez une vraie variante puis revenez à la meilleure requête. Même l’échec indique quel terme éviter la prochaine fois."],bullets:["Avant : black hoodie streetwear best quality → marketing, invérifiable","Après : black two-way zip hoodie → catégorie, couleur, fermeture","Avant : everyday shoulder bag trendy → vague et promotionnel","Après : nylon messenger bag zip closure → forme, matière déclarée, fermeture"]},
      {h:"6. Examiner sans transformer la recherche en recommandation",p:["Ouvrez la page source finale et notez titre actuel, URL, option choisie, identité visible du vendeur, date du prix et preuves liées à la requête. Tout détail non prouvé reste inconnu. La pertinence ne prouve ni stock, fiabilité, composition, taille, qualité ni authenticité.","Comparez la page aux exigences et rejetez celle qui en échoue une. Deux pages semblables restent distinctes tant que SKU, options et spécifications ne correspondent pas. Le bon résultat est une petite liste explicable à vérifier ensuite, pas la collection la plus grande." ]}
    ],checklistTitle:"Checklist QA réutilisable",checklist:["Décrire la fonction en une phrase.","Séparer obligatoire, préféré, exclu et inconnu.","Commencer par catégorie plus un terme discriminant.","Sauvegarder la requête exacte avant modification.","Nommer l’échec et changer un seul token.","Séparer variantes réelles et quasi-synonymes.","Conserver page finale et option choisie.","Traiter chaque résultat comme candidat, jamais comme recommandation."],ending:["La meilleure requête n’est pas la plus longue. C’est l’expression la plus courte qui préserve le besoin et permet de comprendre chaque correction. Un petit journal rend le processus reproductible sur ordinateur ou mobile.","Le contexte a été vérifié le 31 août 2026 sur le site public et l’entrée de l’application HipoBuy. Aucun classement, recherche d’image, système de recommandation ou résultat d’achat n’est affirmé. Vérifiez la page en direct et votre compte avant de commander."]
  },
  es: {
    title:"Convertir una idea de producto en una consulta precisa para la hoja Hipobuy",lead:"Traduce una necesidad de compra a términos observables de categoría, construcción e identificador; cambia una sola variable para poder reproducir y corregir cada conjunto de resultados.",checked:"Revisado el 31 de agosto de 2026",contents:"En esta guía",
    intro:["Una consulta precisa para la hoja Hipobuy empieza antes del buscador. Escribe qué debe hacer el producto, qué rasgos puede mostrar la ficha y qué condición descarta un resultado. Así una idea de estilo vaga no se convierte en una cadena de enlaces irrelevantes.","HipoBuy se presenta actualmente como agente de compra para mercados chinos como Taobao, 1688 y Weidian. Eso confirma el contexto, pero no convierte este método en una función oficial ni en un ranking. Es un flujo editorial independiente: buscar produce candidatos, no recomendaciones, juicios de calidad ni pruebas de autenticidad."],
    sections:[
      {h:"1. Redacta un encargo con requisitos duros y flexibles",p:["Empieza con una frase de función: «sudadera negra ligera con cremallera para capas, dos bolsillos delanteros y sin gráfico grande atrás». Divide requisitos, preferencias y exclusiones. El tipo y la cremallera pueden ser obligatorios; el negro, preferencia; el gráfico, exclusión. Varias preferencias nunca compensan un requisito fallido.","Usa detalles que una ficha puede mostrar: categoría, corte, cierre, material declarado, dimensiones, construcción visible, código de modelo o compatibilidad. Mejor, premium o viral no describen un objeto recuperable. Ajuste, calidad y duración quedan para una fase posterior sin medidas o evidencia sólida."],bullets:["Obligatorio: categoría y construcción no negociable","Preferido: color, acabado o detalle secundario","Excluido: rasgo que termina la comparación","Desconocido: dato que debe verificarse en vivo"]},
      {h:"2. Construye una consulta breve en orden deliberado",p:["Empieza por el nombre de categoría y añade el atributo observable que más discrimina. «Hoodie» es amplio; «hoodie cremallera doble» prueba un cierre concreto. Añade un tercer término solo si sobra ruido. Un código exacto puede ir antes cuando define la identidad.","No pegues todo el encargo. Las frases largas contienen relleno, conceptos contradictorios o términos raros que el índice no guarda. Dos a cuatro tokens útiles suelen bastar. Guarda espacios y guiones: si al cambiarlos varía el resultado, anótalo en el registro." ]},
      {h:"3. Diagnostica el resultado antes de editar",p:["Etiqueta el estado: útil, saturado, cero resultados o categoría errónea. Útil significa que algunos resultados conservan la identidad requerida. Saturado significa que la categoría es correcta, pero domina el ruido. Cero indica términos ausentes, demasiado precisos o expresados de otro modo. Categoría errónea señala ambigüedad.","Si está saturado, añade un rasgo observable. Si no hay resultados, quita el término menos esencial y luego prueba una variante real. Si la categoría es errónea, coloca el sustantivo del producto primero. Cambia una sola cosa en cada prueba para conservar la causa."],bullets:["Saturado → añadir un discriminador observable","Cero → quitar el token menos esencial","Categoría errónea → empezar por el sustantivo","Útil → dejar de editar y revisar candidatos"]},
      {h:"4. Amplía vocabulario sin cambiar la intención",p:["Prueba por separado variantes reales: zip y zipper, trainers y sneakers, códigos con y sin guion. Los casi sinónimos pueden cambiar el objeto. Una sweatshirt no siempre es hoodie, una tote no es cualquier bandolera y el efecto cuero no es cuero.","Traduce primero nombres concretos y términos de construcción. Conserva la frase original junto a la traducción de trabajo. No traduzcas identificadores, números ni códigos técnicos salvo que la fuente muestre una alternativa establecida." ]},
      {h:"5. Mantén un registro antes-después",p:["El registro necesita consulta exacta, etiqueta de resultado, un destino representativo, diagnóstico y próximo cambio único. No necesita nombres, cuenta, pedidos ni pagos. Añade fecha porque filas y fichas cambian. Si hay redirección, conserva por separado URL original y final.","Ejemplo de calzado: «running shoes» está saturado. «Low-top running shoes gum sole» añade silueta y suela. Si no devuelve nada, prueba una variante auténtica y vuelve a la mejor consulta. La rama fallida sigue siendo útil: muestra qué término evitar."],bullets:["Antes: black hoodie streetwear best quality → marketing, no verificable","Después: black two-way zip hoodie → categoría, color, cierre","Antes: everyday shoulder bag trendy → vago y promocional","Después: nylon messenger bag zip closure → forma, material declarado, cierre"]},
      {h:"6. Revisa candidatos sin convertir búsqueda en recomendación",p:["Abre la fuente final y guarda título actual, URL, opción elegida, identidad visible de la tienda, fecha del precio y evidencia que coincide. Todo dato sin apoyo queda desconocido. La relevancia no demuestra stock, fiabilidad, composición, ajuste, calidad ni autenticidad.","Compara con los requisitos y rechaza cualquier candidato que falle uno. Dos páginas parecidas siguen separadas hasta coincidir SKU, opciones y especificaciones. El éxito es una lista pequeña y explicable para verificar después, no la colección más grande." ]}
    ],checklistTitle:"Lista QA reutilizable",checklist:["Escribir la función en una frase.","Separar obligatorio, preferido, excluido y desconocido.","Empezar con categoría y un término discriminador.","Guardar la consulta exacta antes de editar.","Nombrar el fallo y cambiar un token.","Separar variantes reales de casi sinónimos.","Conservar la fuente final y la opción elegida.","Tratar cada resultado como candidato, nunca recomendación."],ending:["La mejor consulta no es la más larga. Es la expresión más corta que conserva la necesidad y permite entender cada cambio. Un registro pequeño vuelve el proceso reproducible en ordenador o móvil.","El contexto se comprobó el 31 de agosto de 2026 en el sitio público y la entrada de la app HipoBuy. No se afirma ningún ranking, búsqueda por imagen, recomendación ni resultado de compra. Verifica la página y la cuenta antes de pedir."]
  },
  it: {
    title:"Trasformare un’idea prodotto in una query precisa per il foglio Hipobuy",lead:"Traduci un’esigenza in termini osservabili di categoria, costruzione e identificatore; modifica una variabile alla volta per poter riprodurre e correggere ogni gruppo di risultati.",checked:"Verificato il 31 agosto 2026",contents:"In questa guida",
    intro:["Una query precisa per il foglio Hipobuy nasce prima del campo di ricerca. Scrivi la funzione del prodotto, gli attributi visibili in una pagina e le condizioni di esclusione. Così un’idea di stile vaga non diventa una catena di link irrilevanti.","HipoBuy si presenta oggi come agente d’acquisto per marketplace cinesi quali Taobao, 1688 e Weidian. Questo conferma il contesto, ma non rende il metodo seguente una funzione ufficiale o una classifica. È un flusso editoriale indipendente: la ricerca genera candidati, non raccomandazioni, giudizi di qualità o prove di autenticità."],
    sections:[
      {h:"1. Scrivi un brief con requisiti rigidi e flessibili",p:["Inizia con una frase funzionale: «felpa nera leggera con zip per vestirsi a strati, due tasche anteriori e nessuna grande grafica posteriore». Dividi requisiti, preferenze ed esclusioni. Tipo e zip possono essere obbligatori, nero una preferenza, la grafica un’esclusione. Più preferenze non compensano un requisito mancante.","Usa dati che una fonte può mostrare: categoria, taglio, chiusura, materiale dichiarato, dimensioni, costruzione visibile, codice modello o compatibilità. Migliore, premium e virale non descrivono un oggetto recuperabile. Vestibilità, qualità e durata restano domande successive senza misure o prove."],bullets:["Obbligatorio: categoria e costruzione non negoziabile","Preferito: colore, finitura o dettaglio secondario","Escluso: caratteristica che chiude il confronto","Sconosciuto: fatto da verificare sulla pagina live"]},
      {h:"2. Costruisci una query breve in ordine consapevole",p:["Parti dal nome della categoria e aggiungi l’attributo osservabile più discriminante. «Hoodie» è ampio; «two-way zip hoodie» prova una chiusura precisa. Aggiungi un terzo termine solo se i risultati sono ancora troppi. Un codice esatto può venire prima se definisce l’identità.","Non incollare tutto il brief. Le frasi lunghe contengono rumore, concetti in conflitto o parole rare non presenti nell’indice. Due-quattro token utili spesso bastano. Salva spazi e trattini: se cambiarli modifica i risultati, annota il fatto nel registro." ]},
      {h:"3. Diagnostica i risultati prima di modificare",p:["Etichetta l’esito: utile, sovraccarico, zero risultati o categoria errata. Utile significa che alcune pagine mantengono l’identità richiesta. Sovraccarico significa categoria corretta ma troppo rumore. Zero indica termini assenti, troppo precisi o espressi diversamente. Categoria errata indica ambiguità.","Con sovraccarico aggiungi un attributo osservabile. Con zero risultati rimuovi il termine meno essenziale e prova una vera variante. Con categoria errata metti prima il nome del prodotto. Cambia una sola cosa per test per rendere visibile la causa."],bullets:["Sovraccarico → aggiungi un discriminante osservabile","Zero → rimuovi il token meno essenziale","Categoria errata → inizia dal nome prodotto","Utile → smetti di modificare e controlla i candidati"]},
      {h:"4. Espandi il vocabolario senza cambiare intenzione",p:["Prova separatamente varianti reali: zip e zipper, trainers e sneakers, codici con e senza trattino. I quasi sinonimi possono cambiare oggetto. Una sweatshirt non è sempre hoodie, una tote non è ogni tracolla e similpelle non è pelle.","Traduci prima nomi concreti e termini costruttivi. Conserva la frase originale accanto alla traduzione di lavoro. Non tradurre identificatori, numeri o codici tecnici se la fonte non offre un’alternativa stabilita." ]},
      {h:"5. Mantieni un registro prima-dopo",p:["Il registro contiene query esatta, etichetta dell’esito, una destinazione rappresentativa, diagnosi e prossimo singolo cambiamento. Non servono nomi, account, ordini o pagamenti. Aggiungi la data perché righe e inserzioni cambiano. Con un redirect conserva separatamente URL originale e finale.","Esempio scarpe: «running shoes» è sovraccarico. «Low-top running shoes gum sole» aggiunge forma e suola. Se non trova nulla, prova una variante autentica e torna poi alla query più forte. Anche il ramo fallito mostra quale termine evitare."],bullets:["Prima: black hoodie streetwear best quality → marketing, non verificabile","Dopo: black two-way zip hoodie → categoria, colore, chiusura","Prima: everyday shoulder bag trendy → vago e promozionale","Dopo: nylon messenger bag zip closure → forma, materiale dichiarato, chiusura"]},
      {h:"6. Controlla senza trasformare il recupero in consiglio",p:["Apri la fonte finale e registra titolo attuale, URL, opzione scelta, identità visibile del negozio, data del prezzo e prove coerenti. Ogni dettaglio non supportato resta sconosciuto. La rilevanza non prova disponibilità, affidabilità, composizione, vestibilità, qualità o autenticità.","Confronta con i requisiti e scarta il candidato che ne fallisce uno. Due pagine simili restano separate finché SKU, opzioni e specifiche non coincidono. Il successo è una piccola lista spiegabile da verificare dopo, non la raccolta più grande." ]}
    ],checklistTitle:"Checklist QA riutilizzabile",checklist:["Scrivi la funzione in una frase.","Separa obbligatorio, preferito, escluso e sconosciuto.","Inizia con categoria più un termine discriminante.","Salva la query esatta prima di modificarla.","Nomina l’errore e cambia un token.","Separa vere varianti e quasi sinonimi.","Conserva fonte finale e opzione scelta.","Tratta ogni risultato come candidato, mai come consiglio."],ending:["La query migliore non è la più lunga. È la formula più breve che conserva il bisogno e permette di capire ogni correzione. Un piccolo registro rende il processo riproducibile su desktop o mobile.","Il contesto è stato verificato il 31 agosto 2026 sul sito pubblico e sull’ingresso app di HipoBuy. Non si affermano ranking, ricerca per immagine, sistema di raccomandazione o risultato d’acquisto. Controlla pagina live e account prima di ordinare."]
  }
};

export default function QueryArticle(){
  const [lang,setLang]=useState<Lang>("en");
  useEffect(()=>{
    const saved=localStorage.getItem("hipobuy-language") as Lang|null;
    if(saved&&copy[saved])setLang(saved);
    const change=(event:Event)=>{const next=(event as CustomEvent<Lang>).detail;if(copy[next])setLang(next)};
    window.addEventListener("hipobuy-language-change",change);return()=>window.removeEventListener("hipobuy-language-change",change);
  },[]);
  const c=copy[lang];
  return <article className="articleBody wrap"><header><span className="kicker">SEARCH METHOD · 11 MIN READ</span><h1>{c.title}</h1><p className="standfirst">{c.lead}</p><div className="byline"><span>Editorial desk</span><span>{c.checked}</span><span>Independent method</span></div></header><div className="articleLayout"><aside><b>{c.contents}</b>{c.sections.map((s,i)=><a key={s.h} href={`#step-${i+1}`}>{s.h}</a>)}<a href="#qa">{c.checklistTitle}</a></aside><div className="prose">{c.intro.map(p=><p key={p}>{p}</p>)}{c.sections.map((s,i)=><section key={s.h}><h2 id={`step-${i+1}`}>{s.h}</h2>{s.p.map(p=><p key={p}>{p}</p>)}{s.bullets&&<div className="callout"><b>QUERY WORKSHEET</b><span>{s.bullets.map(x=><span key={x} style={{display:"block"}}>• {x}</span>)}</span></div>}</section>)}<h2 id="qa">{c.checklistTitle}</h2><ul>{c.checklist.map(x=><li key={x}>{x}</li>)}</ul>{c.ending.map(p=><p key={p}>{p}</p>)}<div className="articleEnd"><div><b>{c.checklistTitle}</b><span>{c.lead}</span></div><a href="/spreadsheet/">Spreadsheet →</a></div></div></div></article>;
}
