import type { Metadata } from "next";
import GuideLayout from "../components/GuideLayout";

export const metadata: Metadata = { title: "Hipobuy Warehouse QC Checklist: Order-Match Evidence", description: "Use a Hipobuy warehouse QC checklist to reconcile the received item with the submitted color, size, model, quantity and saved source evidence.", alternates: { canonical: "/qc/" } };

export default function QCPage() { return <GuideLayout path="/qc/" kicker="Warehouse decision" title="QC photos are evidence—not a quality guarantee." intro="Hipobuy’s app landing page promotes finding products and viewing QC photos before purchase. Use those images as visual evidence, not as a certification of materials, fit or long-term performance." accent="lime">
  <section className="formula-card"><div><p className="section-kicker">Official feature, practical limit</p><h2>“View QC photos first” helps discovery—but the decision still belongs to the buyer.</h2></div><p>Hipobuy publicly positions QC imagery as part of product search. The official pages do not promise that every listing has the same number of images, every angle is covered or every hidden defect can be detected. Save the selected listing and compare it with the exact warehouse record for your order.</p></section>
  <section className="qc-board"><div className="qc-board-head"><p className="section-kicker">Eight-point check</p><h2>Read the photo set in order</h2></div><div className="qc-grid">{[
    ["01","Order match","Confirm color, size, version and quantity against the order record."],
    ["02","Overall shape","Look for distortion, uneven panels or obvious asymmetry from a straight-on view."],
    ["03","Measurements","Compare photographed measurements with a garment you already own—not only a generic size label."],
    ["04","Stitching","Zoom into seams, hems, loose threads and alignment around high-stress areas."],
    ["05","Color","Remember that warehouse lighting changes color; compare several angles before deciding."],
    ["06","Labels & details","Check whether visible labels, hardware and printed details match the selected version."],
    ["07","Surface defects","Look for stains, scratches, glue marks, dents or damage from domestic transport."],
    ["08","Extra evidence","Request a close-up or measurement photo when the standard set cannot answer a material question."]
  ].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="content-split"><div className="sticky-title"><span>QC</span><h2>What photos cannot tell you</h2><p>A responsible guide separates visible evidence from assumptions.</p></div><div className="prose"><h3>Do not overclaim from images</h3><ul className="cross-list"><li>Exact fabric composition unless a reliable label or test confirms it</li><li>Comfort, fit or sizing consistency across different sellers</li><li>Long-term durability after washing or repeated use</li><li>Whether screen color exactly matches the item in natural light</li><li>Internal electronics performance, battery health or waterproofing</li><li>Authenticity or brand authorization</li></ul><h3>Use a red, yellow and green decision</h3><p><strong>Red:</strong> the wrong option, missing part, clear damage or an unacceptable measurement. <strong>Yellow:</strong> an important area is hidden, the color may be affected by lighting or the measurement is close to your limit. <strong>Green:</strong> the visible evidence matches the order and your predefined tolerance. Green still means “no visible reason to reject,” not “guaranteed quality.”</p><div className="callout lime-callout"><b>Request another photo when:</b><p>A suspected defect is partly hidden, the measurement is missing, or the selected option cannot be confirmed from the available photo set. Name the exact area, angle and measurement points instead of asking only for “more QC.”</p></div></div></section>
  <section className="action-banner"><div><p className="section-kicker">Next decision</p><h2>Approved the QC set?</h2><p>Now compare parcel weight, shipping-line restrictions, insurance and destination taxes.</p></div><a href="/shipping/">Plan shipping →</a></section>
  </GuideLayout>; }
