import type { NewFindsSlug } from "./new-finds-articles";

export const newFindsAddenda: Record<NewFindsSlug, {heading:string;body:string}[]> = {
  "check-kakobuy-product-links": [
    {heading:"Audit the price shown in a public directory",body:"A directory's USD amount is a reference conversion, not a checkout promise. The seller can change the CNY price, charge different amounts for size or color, or add domestic freight. The conversion itself may change between the day a card was written and the day a buyer funds an order. Compare the selected seller option with the destination item page, then check the actual amount in the agent account. Keep a dated record of all three figures instead of overwriting an old price without explanation. This is especially useful when a surprisingly cheap thumbnail points to a small accessory rather than the garment pictured. If a card and destination disagree, the route should be reviewed before it appears as a current find."},
    {heading:"Distinguish listing evidence from a review",body:"A photograph, seller title and size chart are product information; they are not proof that independent buyers received the same item. Do not convert a seller's claim into a customer rating, verified QC history or authenticity statement without an identifiable source. Even real customer photos may come from a different variant or production run. State exactly what was checked: the page opened, a specified option was visible, and the item image corresponded at a particular date. The warehouse stage can later add evidence about one physical arrival, but that observation does not validate every item offered by the seller. This distinction keeps a product index honest and makes a buyer's later comparison easier."},
    {heading:"Check restricted items before consolidating",body:"A valid marketplace listing does not guarantee that every international shipping line accepts the item. Batteries, liquids, magnets and other sensitive categories may face route restrictions that depend on destination and current carrier conditions. Read the live line rules rather than inferring eligibility from a product card. If an item cannot travel with the rest of the intended parcel, separate the budget and packing plan before buying more products. Do not assume a seller's domestic ability to dispatch to a Chinese warehouse says anything about international import rules. A link check establishes product identity; the later route check establishes whether the purchased item can be shipped under the available terms."},
    {heading:"Maintain the sheet after publication",body:"Every public link needs an owner and a review date. Revisit the most visited categories and any route reported as broken; compare title, primary image, selected option, target URL and price reference with the current destination. Mark an unavailable item as unavailable instead of sending a visitor to a homepage. Retain a limited change log so a changed item ID is not confused with a routine price update. If a product card points to a live detail page, keep that exact relationship intact. This maintenance work is more likely to help readers than adding hundreds of unverified entries, because every visible recommendation retains a plausible connection to a real page."}
  ],
  "kakobuy-shoes-spreadsheet-checks": [
    {heading:"Check width and shape separately from length",body:"A shoe can have enough length yet feel narrow around the forefoot or tight at the instep. Seller charts may omit those dimensions entirely. Compare pictures of toe box and side profile with footwear you already own, while treating appearance only as a clue. If width is essential, ask for a meaningful measurement or accept that the listing leaves uncertainty. Do not assume adding a full size will solve a shape mismatch; an oversized length may introduce heel slip. Record the specific fit risk in the spreadsheet instead of labeling the product broadly as small or large. This is particularly important when a shoe's visual proportions differ from the everyday pair used as a reference."},
    {heading:"Evaluate condition at normal scale",body:"Zoomed images help locate glue marks, uneven stitching and finish differences, but they can make a trivial detail look decisive. First judge the pair at a scale similar to ordinary use, then inspect the areas likely to affect structure or appearance. Distinguish a photograph's shadow from a repeated asymmetry visible in more than one angle. Note where the camera position or stuffing may alter shape. If a stain, torn seam or wrong outsole would change the decision, request a focused image and keep the item at the warehouse while reviewing it. A disciplined inspection avoids both automatic acceptance and a return request based on compression artifacts."},
    {heading:"Compare seller promises with packaging contents",body:"Check whether the selected option includes spare laces, inserts, a box or another accessory. A marketing photograph may show extras that belong to a different bundle. Use the actual option text as the reference before describing a missing piece. At warehouse receipt, count only what the purchased variant promised and keep a photo of the package contents when available. If an accessory matters to you but the listing is unclear, resolve that question before checkout. A claim that an item arrived incomplete is easier to assess when the saved order specifies each component. Keep optional packaging separate from a necessary functional part of the shoe."},
    {heading:"Revisit the selected candidate before payment",body:"A shortlist can become stale in a few days. Open the exact seller route again, confirm the selected size, current price, color and stock indication, and compare them with the stored row. Do not migrate a favorable warehouse photo from a different seller or older batch into this decision. If the item disappears, create a new comparison rather than quietly substituting a similar-looking pair. Your final record should explain what was known before purchase, what appeared at the warehouse and what remained uncertain. That transparency helps another reader understand the limits of the finding and helps you avoid repeating a size or packing mistake."}
  ],
  "kakobuy-hoodie-size-qc-guide": [
    {heading:"Check the selected color against real constraints",body:"A color name such as ash, oatmeal or faded black can conceal a wide range of appearances. Compare the seller's current option thumbnail with several images in the same listing, preferably under different lighting. Screens differ in brightness and white balance, and a warehouse picture may be shot under cool lights. Ask whether an apparent mismatch persists across multiple views before calling it wrong. If precise color matching is necessary for a uniform or set, an online photograph may not provide enough evidence. Record that limitation before purchase, rather than treating the most attractive promotional image as a guaranteed color standard."},
    {heading:"Separate sizing from shrinkage claims",body:"A garment that measures correctly at warehouse intake may change after washing, but a photograph cannot predict that change. Use only the seller's stated care and shrinkage information as a claim to verify, not as a universal property of cotton or fleece. If no care information is available, include uncertainty in the fit decision. Do not automatically size up based on an anecdote about another seller's hoodie. For a relaxed fit, document how much extra width and length you want using a reference garment. This makes the choice repeatable and protects against vague advice that ignores the wearer's actual preferences."},
    {heading:"Prioritize structural defects",body:"Look at shoulder joins, pocket attachment, zipper alignment, hem symmetry and stress points before fixating on small loose threads. A thread can sometimes be trimmed, while a twisted body panel or broken zipper can affect everyday use. Photographs should be read in context: a folded hem may look uneven until the garment is laid flat. Request a flat front or back view if a structural question is unresolved. Note the specific location of a defect and compare it to the saved seller image. That description is more useful in a time-sensitive after-sale request than an unsupported statement that the hoodie is poor quality."},
    {heading:"Use product cards as navigational evidence",body:"The current find directory includes a knitwear card and a hoodie category route, but neither substitutes for checking the seller's exact hoodie option. Follow a category to shortlist products, then open the individual detail destination and inspect current images, title and selected options. A directory price belongs to a moment in time and should never be described as the final delivered amount. If a detail page changes, record the new state and date before recommending it. Readers benefit when every route is explicit about its level of evidence: category browsing, individual listing review or warehouse photo inspection."}
  ],
  "kakobuy-jersey-listing-measurements": [
    {heading:"Consider print durability as an open question",body:"A warehouse photograph can show whether a name or number is present and visibly aligned. It cannot establish how a heat-applied print will withstand washing, friction or repeated wear. Seller wording about print technique should be recorded as a claim unless there is verifiable documentation. A clean close-up may help identify obvious lifting at arrival but cannot forecast future use. Do not transform one buyer's anecdote into a lifespan estimate for all jerseys. If print durability is a deciding factor, acknowledge that the standard purchasing evidence may leave it unresolved and choose a source whose terms and materials you can verify."},
    {heading:"Account for changing seasons and versions",body:"A seller may retain a familiar image while changing badges, trim or season labels in the option menu. The design in a directory thumbnail might no longer represent the version currently selected. Record season or version only when it is stated on the live listing and connected to the chosen option. Keep images of front and back together; a front view alone cannot confirm a name or number. If the item changes, update the sheet as a new dated listing or remove an outdated claim. These small checks matter because a jersey purchase is often motivated by one exact combination of colors, details and personalization."},
    {heading:"Compare the whole set if multiple pieces are included",body:"Some listings show matching shorts, patches or accessories around a jersey. Confirm whether the selected price buys the jersey alone or a bundle. If a complete set is ordered, list each promised piece and size separately. At the warehouse, check the count and visible identity of every piece before consolidating the parcel. A missing option in a product selector is not evidence that a matching item will be added by the seller. If the listing is ambiguous, seek clarification before checkout. The distinction between a styled photograph and a contractual bundle prevents a common mismatch between expectation and received contents."},
    {heading:"Keep the item decision distinct from fan identity",body:"A buyer may care about a team, athlete or season, but product research still needs concrete evidence. Compare ordered text, placement, measurements and visible condition without claiming an affiliation or official endorsement. Do not use another site's licensed product photo as if it documented the marketplace seller's item. If your decision depends on an exact official specification, check that specification with an authoritative source and ensure the listing actually promises the same version. The warehouse can document one physical item; it cannot determine licensing merely by photographing a logo. This boundary protects both readers and the clarity of the review."}
  ],
  "kakobuy-weidian-taobao-links": [
    {heading:"Record how the URL was obtained",body:"A URL copied from a seller page, a social post or a third-party sheet can have different reliability. Write down the source and date, and verify the final marketplace destination yourself. A public share link may expire or redirect through an app; a canonical item page with a visible identifier is easier to audit. Avoid exposing referral parameters as though they prove product quality. If a seller provides a new link, compare its item ID and options rather than assuming the short link merely changed format. Provenance makes it possible to revisit a questionable entry and correct it without guessing what the original contributor meant."},
    {heading:"Do not confuse agent rendering with seller inventory",body:"An agent's imported page can fail to load an image or option even while the original seller page remains accessible. The reverse can also happen: a cached agent thumbnail may survive after the seller edits or removes the listing. Compare both views and prioritize the current seller option for product identity. If an import mismatch persists, use official support or the platform's fill-in procedure rather than manually modifying an encoded URL. The aim is to preserve the exact ordered item, not simply to produce a page that displays a similar picture. Treat technical rendering and seller stock as separate questions."},
    {heading:"Respect the different decision stages",body:"The marketplace controls the listing and seller options, Kakobuy handles purchasing and warehouse intake, and an international carrier handles the later parcel movement. A good link guide attributes evidence to the right stage. A seller image can help identify an option; a warehouse image can show a physical arrival; a carrier scan can show one shipping milestone. None of those alone proves the other two. Keep domestic shipping, return eligibility and international freight in distinct fields. When something goes wrong, this separation identifies the relevant record and support channel without inventing a single all-purpose guarantee."},
    {heading:"Maintain a clean public link history",body:"A product directory should have a routine for broken and changed links. Record last verification, selected option, destination item ID and a short note describing any material change. When a marketplace page is removed, label the entry accordingly; when a new seller is chosen, make a new row with a new evidence trail. Preserve a current primary image only if it corresponds to that destination. Do not silently switch a card to a different seller while retaining the old name and price. Readers can then use a concise sheet as a navigation aid, and editors can identify which facts need fresh checking before a page is indexed again."}
  ],
  "kakobuy-product-link-not-working": [
    {heading:"Use the page's own error wording",body:"A blank area, unsupported link notice, seller removal message and sign-in screen require different next steps. Record the exact wording and the page where it appeared. A temporary rendering failure is not proof that the product has been withdrawn; a seller removal notice is stronger evidence about availability. Do not treat a 404 on an unrelated redirector as a Kakobuy policy decision. If the site presents a security warning, stop rather than bypassing it to recover an item. This approach keeps troubleshooting tied to what was observed instead of diagnosing every failed link as the same problem."},
    {heading:"Check for a variant that disappeared",body:"Sometimes the item page still loads while the particular size or color originally saved no longer appears. That is a changed product decision even if the URL is technically working. Compare the original order screenshot with the current selector, price and gallery. Do not choose the nearest color or size automatically. A different variant can affect fit, material, bundled accessories and after-sale conditions. Mark the row as partially changed and explain which option is missing. If the item is essential, wait for a verified restock or investigate a new seller listing from scratch. A live URL alone is not enough for a reliable spreadsheet entry."},
    {heading:"Avoid exposing private data during support",body:"A support request may need the original listing URL, item ID and a description of the import error. It rarely requires publishing your full address, payment screenshot, password, access token or parcel tracking to a public forum. Use the official account's private support channel for order-specific details and hide unrelated fields on screenshots. Keep the timestamp and exact error so the agent can reproduce the issue. An unverified person offering to fix a link outside the official flow is not a substitute for the platform's visible support route. The objective is to recover a traceable product decision without creating an account-security problem."},
    {heading:"Recheck search and category fallbacks",body:"A directory's search box and category links can help locate a different item, but they should not pretend to reopen the vanished listing. Search using descriptive attributes such as item type, color, measurements and distinctive construction, then verify each candidate's own seller and variant. If a search returns no matching product, say so. A generic category landing page is appropriate for browsing, not as the replacement for an exact product-card link. Keep any new choice separated from the former item ID and photographs. That boundary makes both the site's navigation and the eventual warehouse comparison more dependable."}
  ]
};
