import type { ArticleRecord } from "./article-data";

export type NewFindsSlug =
  | "check-kakobuy-product-links"
  | "kakobuy-shoes-spreadsheet-checks"
  | "kakobuy-hoodie-size-qc-guide"
  | "kakobuy-jersey-listing-measurements"
  | "kakobuy-weidian-taobao-links"
  | "kakobuy-product-link-not-working";

type Content = Pick<ArticleRecord, "tag" | "title" | "description" | "sourceNote" | "sections" | "takeaways">;
export const newFindsArticles: Record<NewFindsSlug, Content> = {
  "check-kakobuy-product-links": {
    tag: "PRODUCT LINK RESEARCH", title: "How to Check a Kakobuy Product Link Before Saving It",
    description: "A practical Kakobuy product-link checklist for seller identity, variants, image matching and the warehouse decision.",
    sourceNote: "Kakobuy's public purchase flow and warehouse inspection guidance were checked on September 23, 2026. A link in this independent directory is a starting point, not a verified seller, stock or authenticity guarantee.",
    sections: [
      { heading: "Identify the source before copying a link", body: "A useful product link points to a specific seller listing, not merely a screenshot, search result or category homepage. Kakobuy's public purchasing page describes submitting a marketplace product link, then receiving the seller's item at its warehouse for inspection. Record the original marketplace and listing identifier alongside any agent-facing URL. Open the original page and confirm that its title, main image and seller name refer to the item you intend to research. If a redirect lands on a different item or generic storefront, stop. Product databases can change their presentation, while the seller may edit, replace or remove a listing. A saved link without the original item identity is a poor record for comparing the eventual warehouse arrival." },
      { heading: "Read the selected option rather than the hero image", body: "Many listings show several colors, sizes or versions beneath one attractive hero photo. The displayed lowest price may belong to a small accessory or a different option. Select the intended variant and write down its exact label, quantity, seller-side price and any domestic delivery charge shown at the time. Save a private screenshot showing those choices. Translate unfamiliar option labels cautiously: the first thumbnail need not represent the first selectable version. Do not infer stock from an old spreadsheet entry. The live seller page and the current checkout screen should agree before you submit the order. If they do not, ask the seller or agent for clarification instead of hoping the warehouse will resolve an ambiguous purchase." },
      { heading: "Match images to the exact destination", body: "Compare the first image in a directory with the actual destination's first product image, then inspect the remaining listing gallery. Similar product photos are frequently reused by sellers; matching colors alone do not prove identical materials, construction or included accessories. Look for distinctive seams, graphic placement, hardware and option text. A directory photo can be a useful clue but is not a substitute for the destination's current information. On the site you are reading, the six recently added product cards lead to exact item pages; use that final item page to confirm the current picture and price. If a link points to a category instead, treat it as browsing, not a claim that a particular product has been checked." },
      { heading: "Create a small comparison record", body: "For two candidate listings, make columns for marketplace, seller, item ID, selected variant, size chart, photos, price, domestic freight and unanswered questions. Record the date because a listing can change tomorrow. A lower price is not enough to establish a better choice if the size chart is missing or the selected option differs. Flag photographs that appear identical across sellers without assuming fraud; shared catalog images are common. Note whether the product is a set or a single piece. A concise comparison prevents a familiar failure: ordering from one link while saving reference photographs from another. It also gives you a clear baseline when the warehouse images arrive and the item must be accepted, clarified or returned." },
      { heading: "Plan the warehouse check before paying", body: "Decide which visible features would change your decision. For clothing that may be size and color; for shoes, pair identity and measured dimensions; for a jersey, print position and ordered name or number. Kakobuy's published inspection description says garments receive checks for color, size and major visible damage, while electronic functions are not tested as part of the standard inspection. Therefore an image can support a visual comparison but cannot certify the item's material, durability or electronic performance. Save the listing option, size chart and key seller images so you can compare them with the actual item at intake. If a critical measurement is absent, request it while the item is still at the warehouse." },
      { heading: "Keep shipping and after-sale decisions separate", body: "A link that works today says nothing about final international freight. The seller must first deliver to the warehouse; the parcel's packed weight, dimensions, destination, route and packaging determine a later shipping decision. A seller-side return may also have eligibility conditions and domestic freight consequences. Do not publish a fixed delivered price derived only from the product card. Keep a separate parcel budget and check current route information after intake. If the item is wrong, work through the warehouse issue before placing it in an international parcel. The goal of checking a link is to preserve a traceable chain from listing to ordered variant to photographed item, rather than to imply that the purchase is risk-free." },
      { heading: "Use a clear stop-or-save rule", body: "Save the link when the original listing opens, the selected option is explicit, the photo and category match, and you have enough information to decide what warehouse evidence matters. Pause when the page redirects unexpectedly, selected size changes the item, images are inconsistent, an important measurement is missing, or the seller's terms cannot be understood. Never turn a broken route into an invented substitute. Record the unresolved question and revisit the live page later. A smaller sheet of traceable links is more useful than thousands of entries that cannot be connected to a specific product and variant. Rechecking the destination immediately before purchase remains necessary even after a link has passed this checklist." }
    ],
    takeaways: ["Keep the original marketplace item ID.", "Confirm the selected option and current seller price.", "Compare the actual destination image, not only a directory thumbnail.", "Define a warehouse photo decision before paying.", "Stop when the route or variant cannot be verified."]
  },
  "kakobuy-shoes-spreadsheet-checks": {
    tag: "SHOE FINDS", title: "Kakobuy Shoes Spreadsheet: Compare Size, Listing Photos and QC",
    description: "Compare Kakobuy shoe finds using actual listing options, sizing evidence, pair photos and a sensible warehouse checklist.",
    sourceNote: "This is an independent product-research method, checked against Kakobuy's public purchase and inspection descriptions on September 23, 2026. No seller, fit, material or authenticity is guaranteed.",
    sections: [
      { heading: "Use the spreadsheet to shortlist, not to select a size", body: "A shoes spreadsheet is useful when it narrows many listings to a few routes with visible images and clear categories. It cannot measure your foot or guarantee that a seller's size label matches a particular national standard. Open the current product destination for each candidate. Check whether the displayed price belongs to the selected size and version, and whether the listing still carries the same colors and photographs. Save the original item ID and seller name. Avoid treating two similar thumbnails as interchangeable listings; one may have a different outsole, upper or option structure. A short list of two or three traceable candidates makes the subsequent size and warehouse checks manageable." },
      { heading: "Compare measurements using one method", body: "Start with a shoe you actually wear comfortably and measure its insole when possible. Compare that figure with the seller's current sizing guidance while noting that insole length, foot length and external sole length are different measurements. Do not convert a size label using an unrelated brand chart and assume the result is exact. Fit also depends on width, toe shape, sock thickness and personal preference. If the seller does not publish a useful measurement, mark the gap. A size printed on a box can support the ordered option, but it does not prove internal fit. The best spreadsheet row records the seller's method and the date it was checked, rather than a single unexplained size number." },
      { heading: "Inspect the seller gallery critically", body: "Look for both shoes, the outsole, toe shape, heel, side panels and any accessories stated in the selected option. Promotional images may show a sample rather than the specific pair that will be sent. Distinguish styling photographs from actual seller detail images. If a listing uses a famous reference design, do not infer licensed origin or authenticity from a logo or product name. Check the option text for differences between a shoe-only purchase, a boxed set or a size-dependent price. Save the pictures that matter for later comparison. If key details appear only in a different seller's gallery, do not borrow them as evidence for the route you chose." },
      { heading: "Prepare a pair-specific warehouse checklist", body: "When shoes reach the warehouse, verify that both shoes correspond to the ordered color and size, and that the left and right are a matching pair. Compare toe shapes, heel height, outsole pattern, panel placement and visible damage. Ask for a readable size label or insole measurement when that evidence would change your decision. The angle of a photo can exaggerate asymmetry, so compare several views before deciding that a defect is structural. Kakobuy's standard inspection description concerns visible attributes and major issues; it does not promise laboratory material checks or proof of authenticity. A photo of a shoe cannot tell you how it will feel after hours of wear." },
      { heading: "Consider the package separately from the shoe", body: "A seller box may protect shape or matter to a collector, but it can increase parcel volume. Removing it may lower a later shipping estimate while increasing risk of deformation. Decide what packaging you actually need, then compare current route estimates using realistic packed dimensions. Do not compute a universal per-pair freight price from the spreadsheet's product price. Shoe materials and accessories can also affect line eligibility, so check the live parcel options. A light pair in a large box may be billed differently from compact footwear of similar weight. The packing decision belongs after warehouse intake, not in the initial product listing comparison." },
      { heading: "Resolve a mismatch before international dispatch", body: "If the pair, size or color differs from the saved order, record the discrepancy using the seller option, warehouse photos and order number. Ask for clarification while a domestic after-sale path may still be available. A missing photograph is a request for evidence, not necessarily a defective item; a physically incorrect size is a different issue. Return eligibility and costs depend on the seller and current Kakobuy terms, so do not assume every shoe can be returned without charge. Keep the item out of the parcel until the decision is settled. Once it crosses the border, a straightforward warehouse correction can become an expensive international return problem." },
      { heading: "Choose with a dated decision record", body: "Record the candidate URL, seller, option, size evidence, photo comparisons, warehouse outcome and final decision in a compact sheet. Mark uncertain claims as uncertain. If the first candidate disappears, re-evaluate a substitute from the beginning instead of attaching old photographs to a new item ID. The spreadsheet should help a buyer remember why one route was selected and what still needs checking. It cannot certify stock, originality, comfort or final delivered cost. Reopen the current listing immediately before any order, and treat the warehouse photos as an additional checkpoint rather than retroactive proof that all seller claims were true." }
    ],
    takeaways: ["Use an insole or foot measurement with a clear method.", "Keep each seller's photos with its own item ID.", "Check both shoes and the ordered size at the warehouse.", "Decide whether the seller box is worth its parcel volume.", "Resolve mismatches before international shipping."]
  },
  "kakobuy-hoodie-size-qc-guide": {
    tag: "HOODIE FINDS", title: "Kakobuy Hoodie Finds: Size Chart and QC Photo Checklist",
    description: "Research Kakobuy hoodie listings with measured garment dimensions, variant checks, fabric evidence and warehouse photos.",
    sourceNote: "Kakobuy's public purchase flow and garment-inspection scope were checked September 23, 2026. This guide is editorial advice about visible evidence, not a fabric or fit guarantee.",
    sections: [
      { heading: "Start with the specific hoodie listing", body: "A category page can suggest styles, but the specific seller listing determines the selectable color, size, material description and current price. Open the original route and keep its item identifier. Check whether a pullover, zip-up and matching set are represented by separate options under one gallery. A hero photograph may show an outfit even when the priced option is only a hoodie. Record the selected option before comparing prices with another seller. If an old spreadsheet row contains a photograph that no longer appears at the destination, flag it for recheck. The listing and its selected variant are the actual evidence available before the warehouse receives anything." },
      { heading: "Use garment measurements instead of size letters", body: "Measure a hoodie you own while it lies flat, then compare chest width, body length, shoulder width and sleeve length with the seller's chart. Check whether the seller reports flat width or full circumference. An M from one factory need not match an M from another, and a model's height tells little without garment dimensions. Account for the fit you want: a relaxed layer needs different ease from a close-fitting top. Ask for clarification if a size chart is missing or inconsistent with option labels. Save the chart as it appears at purchase; listings can be edited. A measurement method is more useful than an unsourced claim that a hoodie fits true to size." },
      { heading: "Separate fabric claims from visible clues", body: "A seller may describe cotton percentage, fleece weight or wash treatment, but photographs cannot verify fiber composition or long-term pilling. Look for visible construction: hood shape, drawcords, ribbed cuffs, pocket placement, zipper type and print location. Treat texture in heavily processed marketing images cautiously. If composition matters, seek a specific seller label or documentation and accept that a warehouse image still has limits. Avoid ranking two items by a claimed fabric weight when one seller has not stated its measurement method. Note which claims can be checked visually and which remain seller assertions. This protects the final article and the buyer's decision from false certainty." },
      { heading: "Map the warehouse photos to your questions", body: "Kakobuy says garment inspection addresses color, size and major visible damage. Compare front and back shape with the saved listing; check hood, pocket, cuff and hem construction. Look for a readable size label and a flat measurement if the fit is uncertain. A folded hoodie can hide side seams or a print defect, so request the angle that would change the keep-or-return decision. Do not mistake lighting differences for a definite color mismatch without comparing multiple views. A photograph can reveal obvious damage, but cannot establish comfort, exact fiber content or behavior after washing. Identify the limit of each picture in your notes." },
      { heading: "Judge print and embroidery in context", body: "For graphic hoodies, compare position, scale and alignment against the seller's selected variant. Ask whether the print is visibly centered relative to the neckline and pocket, not whether every pixel matches a promotional mockup. Embroidery can look different under angled lighting; check close-ups for gaps or loose sections that matter at normal viewing distance. Tiny threads are different from an open seam or a missing panel. If a design is associated with a brand, avoid inferring authorization from a photograph. Save the actual item evidence and describe visible features precisely. That makes a support request stronger than a vague statement that the garment looks wrong." },
      { heading: "Plan packing without assuming savings", body: "Soft clothing can often be packed compactly, yet compressing a thick print or structured hood may leave creases. The seller's packaging, other items in the parcel and protective instructions affect final dimensions. Compare current route conditions after intake rather than quoting a universal shipping cost per hoodie. If you combine several garments, keep the oldest warehouse receipt date and make sure every size and variant has been checked first. Packing should follow a completed product decision. A lower volumetric estimate has little value if an incorrect size was consolidated into a parcel that has already left the warehouse." },
      { heading: "Keep a fit-and-evidence worksheet", body: "Record your reference garment's measurements, the seller's method, the chosen option, saved size chart and the warehouse results. Separate confirmed measurements from estimates and missing angles. If two listings share a model image, do not merge their size data without proof they use the same pattern. When a hoodie arrives with a materially different measurement, document the method and request a timely review of the applicable seller terms. A good worksheet tells the buyer what to check next and why. It does not promise that a photographed garment will fit a particular body or survive a particular washing routine." }
    ],
    takeaways: ["Compare flat garment measurements using the same method.", "Record whether the option is a hoodie or a set.", "Distinguish visible construction from unverified fabric claims.", "Request a photo only when it can change the decision.", "Resolve fit evidence before packing."]
  },
  "kakobuy-jersey-listing-measurements": {
    tag: "JERSEY FINDS", title: "Kakobuy Jersey Finds: Compare Listings, Names and Measurements",
    description: "Check Kakobuy jersey product routes, selected print options, size charts and warehouse evidence before choosing a parcel.",
    sourceNote: "Kakobuy's public shopping-agent and visible garment inspection descriptions were checked on September 23, 2026. Customization and return terms vary by seller and must be checked on the live order.",
    sections: [
      { heading: "Check which jersey the option actually buys", body: "A listing gallery may contain a home jersey, an away jersey and several seasons while the starting price belongs to only one selection. Open the original seller route and choose the exact color, size, name, number and patch configuration. Determine whether customization is an optional service, a separate variant or absent from the listing. A directory title such as basketball jersey describes a category, not a promise about the final print. Record the seller item ID and variant text before ordering. A screenshot of a different fan's finished jersey cannot replace the selected option. Current seller data is more useful than an old promotional image when details change between seasons or batches." },
      { heading: "Treat size charts as garment data", body: "Compare chest width and length against a jersey you already wear, using the same flat-measurement method. Jerseys can have different intended fits for casual wear, training or layering over another shirt. A size letter alone cannot tell you the intended circumference. Verify whether measurements include a tolerance and whether a personalized item uses the same base garment. If the seller offers only model photographs, mark the fit as uncertain instead of inventing a true-to-size rating. Keep a copy of the size chart and the chosen variant so warehouse measurements can be compared with the same source. Avoid using a chart from a separate listing simply because the design appears similar." },
      { heading: "Inspect print instructions before submitting", body: "If a name, number or badge is selectable, spell it exactly and check punctuation, capitalization and placement. Do not rely on a generic photo of a player to communicate the intended text. A buyer-provided instruction should be concise enough for the purchasing agent and seller to interpret without guessing. Save the final text privately with the order. Ask whether custom items have different after-sale conditions before paying, because returning a personalized product may be restricted. If the page uses translated labels, compare the actual option values once more before submission. A simple transcription error can be hard to solve once the item has been produced and sent to the warehouse." },
      { heading: "Use warehouse photos for visible comparison", body: "Check front, back, sleeves and any selected badges against the saved listing. Count and read the name and number if visible, then compare their position and orientation. Look for obvious print lifting, major stains, wrong colors or missing pieces. A distant image may not allow a reliable judgment about fine stitching or fabric; request a close-up when that fact would decide acceptance. Kakobuy's published garment-inspection scope covers color, size and major visible damage, not authentication or long-term print durability. A promotional listing can differ in lighting from a warehouse photo, so separate actual wrong variants from reasonable camera differences." },
      { heading: "Separate design resemblance from official licensing", body: "A familiar team color or crest in a marketplace photo is not proof of an officially licensed product. If licensing matters, seek verifiable seller documentation and use authorized channels. This independent directory does not certify authenticity. Likewise, a visible number does not prove that a design matches every season's official specification. Compare the item to the exact seller promise you saved, not an unrelated image found later. Describe warehouse evidence in plain terms, such as the selected number appears on the back, rather than claiming a jersey is genuine or identical to a retail release. Accurate limits make product research more useful." },
      { heading: "Understand returns before combining jerseys", body: "A wrong selected variant, a seller production error and a buyer typo are different situations. Keep the order screenshot and warehouse evidence together when asking about a problem. Check the seller's current return or exchange eligibility and any cost responsibility; do not assume a personalized jersey receives the same treatment as an unmodified garment. Put a disputed item on hold rather than consolidating it into an international parcel. Packaging multiple thin jerseys may save space, but only after every name, number and size is reviewed. Estimate the international route from actual packed weight and dimensions rather than adding a fixed freight surcharge to each product card." },
      { heading: "Build a decision record for each jersey", body: "Make separate rows for seller, listing ID, team or style description, season if claimed, selected color, size, name, number, patches, chart, saved images and QC outcome. Mark a missing back view as missing evidence, not proof that a number is absent. If a link expires, reopen a new listing and repeat the checks rather than inheriting old option values. A concise record lets the buyer tell whether an issue arose in selection, seller production, warehouse inspection or shipping. The spreadsheet's job is to keep these facts connected. It should not turn an attractive gallery into a guarantee of fit, authenticity or delivery." }
    ],
    takeaways: ["Record every selected name, number and patch.", "Compare the seller's own size chart using flat measurements.", "Check front and back warehouse views.", "Do not infer licensing from a photo.", "Settle customization disputes before parcel submission."]
  },
  "kakobuy-weidian-taobao-links": {
    tag: "MARKETPLACE LINKS", title: "Kakobuy Weidian and Taobao Links: Verify the Original Listing",
    description: "Keep Kakobuy Weidian and Taobao product routes traceable when links, seller options and marketplace images change.",
    sourceNote: "Kakobuy's public purchase page identifies Chinese marketplace purchasing through submitted product links. The link-check method is editorial and was reviewed September 23, 2026.",
    sections: [
      { heading: "Keep the marketplace and item identifier", body: "Weidian and Taobao are separate marketplaces with different seller pages and option layouts. A Kakobuy-facing URL may wrap an original marketplace address. Save the original seller URL and its item ID alongside the agent route; never rely solely on a shortened sharing URL or copied image. Kakobuy's public purchase flow says buyers can submit product links from Chinese marketplaces and later inspect warehouse arrivals. A directory can help discovery, but only the live original listing shows the seller's current options. When a route fails, the original item ID helps determine whether the link format broke, the seller removed the item or an intermediary redirect changed." },
      { heading: "Check the seller page after a redirect", body: "Open the destination and verify the marketplace domain, seller identity, listing title, primary image and selectable variants. Some links may open an app prompt or translated agent page; that is not evidence that the item is gone. Use the visible original item details rather than guessing from a URL parameter alone. If the destination displays a different item, do not order it under the old spreadsheet title. Record the exact mismatch and date. A seller can reuse photos, replace a listing or change its option structure. Treat every redirect as a route to inspect, not an endorsement of the content that appears after it." },
      { heading: "Preserve option text and price context", body: "Marketplace listings often show one starting price while size, color, material or bundle choices change the total. Select the intended variant and keep its original label, a cautious translation and a screenshot. Check whether the listing refers to one product or a deposit, accessory or multiple-item bundle. Seller domestic freight may be separate from the visible item amount; international freight is a later parcel cost. Avoid publishing a single fixed USD price as if it were guaranteed for every option. Record the seller's local-currency amount and the directory's dated conversion as separate fields. If the option cannot be understood with confidence, pause instead of substituting a nearby thumbnail." },
      { heading: "Compare evidence without merging sellers", body: "Two sellers can use nearly identical catalog images even when their options, inventory or service differ. Keep each image set tied to its own item ID. Compare product shape, construction details, size chart, accessories and price, but do not assume matching photographs prove matching production. If one source provides a detailed size chart and another does not, the evidence gap matters. A spreadsheet row should link to the seller whose images and option details were recorded. When the buyer later reviews Kakobuy warehouse photos, the relevant baseline is the purchased seller's listing, not a cleaner photo from another page." },
      { heading: "Understand what agent inspection can resolve", body: "After seller dispatch, Kakobuy's warehouse can provide visible inspection evidence. Its public description says garment checks focus on color, size and major visible damage; electronics do not receive a functional test as part of standard inspection. A warehouse image may reveal an incorrect variant or obvious physical problem, but cannot restore a removed listing or prove every seller claim. Save the seller information before ordering, then compare it with the item that actually arrives. Request a precise additional angle if an essential detail is hidden. The agent's ability to purchase and photograph an item is different from certifying that every marketplace description is accurate." },
      { heading: "Plan a replacement link as a new decision", body: "When a seller removes an item, search for alternatives using the product characteristics you recorded: dimensions, option labels, color, material description and price range. Do not replace the URL in an old spreadsheet row while leaving the previous title and images untouched. Give the substitute a new item ID and recheck its current page from the beginning. This prevents an old QC photograph or seller rating from being attached to an unrelated product. If the product is no longer available, mark it unavailable rather than quietly routing visitors to a generic category or another merchant. Accurate broken-link handling builds more trust than a large sheet of ambiguous redirects." },
      { heading: "Use a final pre-order audit", body: "Before submitting through Kakobuy, compare the original marketplace URL, agent route, selected size and color, quantity, seller price, domestic delivery charge and saved images. Verify that the target item still opens and that any warning or restriction shown in the live account has been read. Budget separately for later international shipping. Keep the order screenshot privately; do not post personal account or tracking details in a public sheet. If any critical field differs, stop and resolve it. The buyer can then use warehouse photographs for a genuine comparison rather than attempting to reconstruct what was ordered from memory." }
    ],
    takeaways: ["Save the original marketplace item ID beside the agent link.", "Verify the seller and selected option after redirects.", "Keep images and size charts tied to one seller.", "Treat a substitute URL as a new listing.", "Audit the live page immediately before submitting an order."]
  },
  "kakobuy-product-link-not-working": {
    tag: "LINK TROUBLESHOOTING", title: "Kakobuy Product Link Not Working? Diagnose the Route Safely",
    description: "Check an expired, redirected or mismatched Kakobuy product link without confusing an agent-page error with a seller listing change.",
    sourceNote: "Kakobuy's public purchasing flow and marketplace-link format were checked September 23, 2026. Examples are diagnostic categories, not a guarantee that any unavailable seller listing can be restored.",
    sections: [
      { heading: "Describe the failure before searching for a replacement", body: "A product link can fail in several ways: the browser cannot open it, the agent import shows an error, the seller listing has been removed, an app prompt obscures the page, or the destination displays an unrelated item. These are different problems. Save the original URL, time, device context and visible error without sharing account details. Compare what happens at the original marketplace address with what happens at the Kakobuy-facing route. Kakobuy's public flow starts from a product link, so a broken source should be examined before an order is submitted. Repeatedly pasting a corrupted URL can obscure which seller and item were intended." },
      { heading: "Inspect the original URL structure", body: "Find the original marketplace domain and item identifier in the saved route. A sharing link may contain tracking parameters, while an agent URL may contain an encoded marketplace URL. Do not randomly remove characters from a product ID or substitute a search result with a similar title. If the original address opens the correct item but the imported route does not, the issue may be with parsing or page access; use the current platform's supported import or fill-in flow and retain the original link. If the original page itself shows removed stock or a different product, treat the listing as changed. Never claim a broken item is available merely because an old thumbnail survives." },
      { heading: "Check redirects against the saved record", body: "When a link opens, compare the title, primary image, seller, selected options and local-currency price with your saved screenshot. A redirect to a generic store or category is not a verified product match. A seller may change a listing while its item ID remains recognizable, so the actual options deserve a fresh review. If an intermediate site shortens or rewrites a URL, prefer the original marketplace item page as the reference. Note exactly which field changed. That record helps distinguish an expired shortcut from a seller substitution. It also prevents a directory card from promising one product while leading buyers to a different one." },
      { heading: "Avoid accidental double encoding and copied fragments", body: "An agent route may store a marketplace URL inside a query parameter. Copying an already encoded parameter into a second wrapper can change characters such as question marks and ampersands twice, making the destination unreadable. Similarly, a copied fragment may omit the item ID or include only an app-specific share code. Use the platform's visible product-link input with the original marketplace URL rather than manually assembling a nested address. If the route still fails, document the exact error and contact official support through the order or help interface. Do not ask a stranger to log into your account or send them a private order screenshot." },
      { heading: "Separate availability from accessibility", body: "A page that will not render on one device is not necessarily sold out, and an old search result is not proof of stock. Try the visible official route and check whether the source listing still offers the chosen variant. Region, login requirements and marketplace app behavior can affect page access. Do not bypass a security warning to inspect an item. If verification remains impossible, mark the entry unverified and postpone the purchase. A directory should not send users to a generic homepage as though it were the exact replacement product. Correctly labeling uncertainty helps readers avoid a wrong order more than guessing a new seller link." },
      { heading: "Evaluate a substitute from scratch", body: "If the original seller listing has disappeared, compare a new candidate's item ID, seller, option structure, measurements, gallery and price independently. Reused promotional images are not enough to transfer confidence from the old listing. Keep the replacement as a new row or clearly dated revision with its own evidence. If the prior item had a specific color or size, confirm that the substitute actually offers it. Any existing warehouse QC photos belong to the original order unless a direct record proves otherwise. A replacement may solve a discovery problem but creates a new product decision and a new set of seller terms." },
      { heading: "Close with a route status", body: "Mark the link working only when the original seller item, selected variant and agent destination can be reconciled. Mark it changed when the page opens but the product or options differ; expired when the seller has removed it; and unverified when access prevents a reliable conclusion. Record the check date and the next action. Before paying, reopen the live item and confirm price, quantity and option once more. At the warehouse, compare the physical arrival with the order record, not with an outdated directory picture. No diagnosis can guarantee future stock, but an explicit status keeps a spreadsheet useful when marketplace content moves." }
    ],
    takeaways: ["Distinguish import errors from removed seller listings.", "Keep the original item ID and a dated screenshot.", "Never replace a broken route with an unchecked lookalike.", "Treat inaccessible pages as unverified, not in stock.", "Reopen the current listing before payment."]
  }
};

export const newFindsSlugs = Object.keys(newFindsArticles) as NewFindsSlug[];
