import type { ArticleRecord } from "./article-data";
import type { Lang } from "./site-data";

type LocalizedArticle = Pick<ArticleRecord, "tag" | "title" | "description" | "sourceNote" | "sections" | "takeaways">;

export const usaAddressArticleTranslations: Record<Lang, LocalizedArticle> = {
  en: {
    tag: "US ADDRESS GUIDE",
    title: "How to Format a US Delivery Address for a Kakobuy Parcel",
    description: "Format a US delivery address for a Kakobuy parcel with USPS-standard fields, apartment details, ZIP Code checks and a private label-preview audit.",
    sourceNote: "Kakobuy's parcel-submission sequence and current USPS addressing resources were checked on September 4, 2026. A standardized address can reduce preventable label errors, but it cannot guarantee route eligibility, carrier acceptance or delivery.",
    sections: [
      { heading: "Treat the address as a matched data record", body: "A Kakobuy US delivery address is not one free-form sentence. It is a set of fields that must describe the same destination in the buyer's private record, the Kakobuy parcel form, the shipping label and the last-mile carrier's system. Start with an address that the recipient already uses successfully. Separate the recipient name, organization when genuinely required, street number and name, secondary unit, city, two-letter state abbreviation, ZIP Code and country. Keep the reachable phone number in its own account field rather than adding it to an address line. Kakobuy's public process shows that the shipping address and logistics method are selected when a parcel is submitted, after items reach the warehouse. That timing gives the buyer a final verification point, not permission to improvise. A neat-looking address can still be wrong if one digit, unit or ZIP Code belongs to another delivery point." },
      { heading: "Build a private source-of-truth record first", body: "Before typing into Kakobuy, collect the address from a reliable private source: a recent carrier label that reached the recipient, the recipient's lease or utility record, an employer's receiving instructions, or the address standardized through the USPS ZIP Code Lookup tool. Do not copy a public map pin or a marketplace autofill result without checking it. Create one row per field and record who confirmed the address and when. If the building has changed unit numbering, street spelling or delivery access, resolve that difference before parcel submission. Keep the complete record private. Public screenshots, shared spreadsheets and support posts should hide the name, apartment, phone, email, order number and tracking code. The objective is a stable reference against which every later form and label preview can be compared, not a document to circulate." },
      { heading: "Use a USPS-style line order", body: "For a normal domestic delivery point, put the recipient on the first line. Use a business or receiving organization on a separate line only when the location requires it. Put the delivery address on the next line: street number, directional when applicable, street name and suffix, followed by the apartment, suite or unit designator and number when the form permits. Put city, two-letter state abbreviation and ZIP Code on the last domestic line, then select United States as the destination country in the dedicated country field. A generic example is: ALEX MORGAN; 245 W PINE ST APT 7B; DENVER CO 80203; UNITED STATES. It is an invented example, not a customer address. Capital letters are readable but not mandatory in every online form. Accuracy and field mapping matter more than decorative punctuation." },
      { heading: "Preserve apartment, suite and unit identity", body: "USPS Publication 28 lists approved secondary unit designators such as APT, STE, UNIT, BLDG and FL. Use the designator that describes the real delivery point, followed by the exact identifier. Do not replace Apartment 4 with Suite 4 because the words seem interchangeable; a building's directory or mailroom may distinguish them. If Kakobuy provides a dedicated address-line-two field, place the secondary unit there while keeping the street on line one. If the form offers only one delivery line, append the unit after the street address without deleting essential street data. Publication 28 permits the pound sign as a secondary-number indicator in limited cases when the correct designator is not available, but a known APT or STE label should be retained. Never invent a unit to bypass a validation warning. Resolve the warning against the recipient and current USPS result." },
      { heading: "Verify city, state and ZIP Code together", body: "A city name, state abbreviation and ZIP Code form a connected group. Check all three in the current USPS lookup instead of validating each from memory. Use the standardized city name returned for the address when it differs from a neighborhood or informal place name. Enter the official two-letter state abbreviation without guessing. A five-digit ZIP Code may be sufficient in many forms; ZIP+4 can identify a more specific delivery segment when USPS supplies it. Do not fabricate the extra four digits or copy them from another apartment in the building. USPS lookup results can standardize an address, but they do not prove that the named recipient lives there, that a private mailroom will accept the parcel or that a particular international route serves the location. Keep those as separate questions." },
      { heading: "Handle managed delivery points explicitly", body: "Apartments, campuses, offices, hotels, military addresses, lockers, commercial mail-receiving agencies and forwarding services may have rules beyond postal syntax. This article covers ordinary US address formatting, not whether every special address is accepted by a Kakobuy route. Ask the receiving location for its required recipient name, department, mailbox or unit, street address and pickup procedure. Confirm whether it accepts international parcels, oversized boxes, signature services and deliveries under the carrier name rather than the resident's name. A carrier scan at a front desk can precede the recipient's possession, so record the internal handoff method. Do not insert access codes, door codes or detailed delivery instructions into public notes. Use the private field intended for necessary carrier instructions, and only after confirming that the location wants those details included." },
      { heading: "Map the source record into Kakobuy fields", body: "Open the parcel-submission address form and transfer one field at a time. Select the country first if that choice controls which state or ZIP fields appear. Match the recipient name exactly enough for the receiving location and any required identity check. Put the street and secondary unit in their intended fields, choose or enter the state, add the ZIP Code, and place the phone number only in the contact field. Do not translate an English street name, expand a directional incorrectly, or remove a leading zero from an identifier. If the interface changes case or spacing automatically, compare meaning rather than typography. If it rejects a verified address, stop and preserve the error message with private details redacted. Recheck the USPS-standardized form and use the platform's official support path instead of repeatedly submitting invented variations." },
      { heading: "Audit the shipping-label preview before payment", body: "The decisive check is the final address as it will be used for the parcel, not the draft saved earlier. Read the label or confirmation preview character by character against the private source-of-truth record. Confirm recipient, street number, street name, unit designator and number, city, state, ZIP Code and United States. Check that no field was truncated, duplicated or moved into the wrong line. Long organization names and combined street-unit lines deserve extra attention. Verify the phone country code and digits in the contact area without exposing them in a screenshot. Save a redacted confirmation that shows the field structure, date and parcel reference, while keeping the unredacted version private. If the address cannot be corrected at this stage, do not assume support or a carrier can fix it after dispatch. Pause before paying for international shipment and resolve the record." },
      { heading: "Freeze changes and record who controls the next step", body: "Once the parcel is submitted, treat the approved address as frozen unless the live Kakobuy workflow explicitly offers a safe correction. Do not assume an address can be changed after packing, label creation, export handoff or US carrier acceptance. Record the last verified address version, submission timestamp and any later change request. When tracking eventually identifies a US carrier, compare the carrier's destination summary without publishing private data. A label-created event proves that electronic information exists; it does not prove physical acceptance or successful delivery. If an exception appears, identify whether the missing fact belongs to Kakobuy, the international carrier, the US last-mile carrier or the receiving location. This separation keeps an address-format issue from being confused with customs, route or delivery-access problems." },
      { heading: "Use a final stop-or-submit checklist", body: "Submit only when the recipient name matches the receiving rules; street number and street name are verified; apartment, suite or unit is present and correctly labeled; city, state and ZIP Code agree with current USPS results; the country is United States; the contact number is in the correct private field; and the final preview contains no truncation or duplication. For a managed mailroom, confirm the internal recipient identifier and pickup procedure. For any unresolved mismatch, choose stop. Do not choose a nearby ZIP Code, omit a required unit or move private access data into a public note just to make a form accept the parcel. Save the verification date and a redacted audit record. This process reduces avoidable address errors. It does not guarantee Kakobuy route availability, customs release, carrier performance, signature completion or possession by the final recipient." },
    ],
    takeaways: ["Keep one private source-of-truth address record.", "Use the real secondary-unit designator and exact number.", "Verify city, state and ZIP Code as one group with USPS.", "Compare the final label preview field by field before payment.", "Stop on unresolved mismatches; standardization is not a delivery guarantee."],
  },
  de: {
    tag: "US-ADRESSRATGEBER", title: "Eine US-Lieferadresse für ein Kakobuy-Paket richtig formatieren", description: "US-Lieferadressen für Kakobuy mit USPS-Feldern, Wohnungsangabe, ZIP-Prüfung und privater Etikettenkontrolle formatieren.", sourceNote: "Kakobuys Paketeinreichung und aktuelle USPS-Adressquellen wurden am 4. September 2026 geprüft. Standardisierung verringert vermeidbare Fehler, garantiert aber weder Route noch Zustellung.",
    sections: [
      {heading:"Die Adresse als übereinstimmenden Datensatz behandeln",body:"Eine US-Adresse ist kein freier Satz, sondern ein Feldsatz, der im privaten Datensatz, Kakobuy-Formular, Etikett und Carriersystem dasselbe Ziel bezeichnen muss. Trenne Name, nötige Organisation, Straße, Wohneinheit, Stadt, Bundesstaat, ZIP Code und Land; Telefon gehört ins Kontaktfeld. Kakobuy lässt Adresse und Logistik bei der Paketeinreichung wählen. Dieser Zeitpunkt ist die letzte Kontrolle, kein Anlass zum Raten."},
      {heading:"Zuerst eine private Referenz anlegen",body:"Nutze eine kürzlich erfolgreich zugestellte Sendung, einen verlässlichen Empfängernachweis, offizielle Empfangsanweisungen oder USPS ZIP Code Lookup. Öffentliche Kartenpins und Autofill werden nicht ungeprüft kopiert. Halte pro Feld Bestätigung und Datum fest und kläre geänderte Haus- oder Wohnungsnummern vorher. Vollständiger Name, Einheit, Telefon, E-Mail, Bestellung und Tracking bleiben privat; geteilte Ansichten werden geschwärzt."},
      {heading:"USPS-typische Zeilenreihenfolge verwenden",body:"Empfänger steht oben, eine erforderliche Firma oder Annahmestelle separat. Danach folgen Hausnummer, Richtung, Straßenname und -typ sowie APT, STE oder UNIT mit genauer Nummer. Die letzte US-Zeile enthält Stadt, zweistelligen Bundesstaat und ZIP Code; United States wird im Länderfeld gewählt. Das Muster ALEX MORGAN; 245 W PINE ST APT 7B; DENVER CO 80203; UNITED STATES ist erfunden. Inhalt und Feldzuordnung sind wichtiger als Großschreibung oder Schmuckzeichen."},
      {heading:"Apartment, Suite und Unit exakt erhalten",body:"USPS Publication 28 führt Bezeichnungen wie APT, STE, UNIT, BLDG und FL. Verwende die tatsächlich zutreffende Bezeichnung und Kennung; Apartment 4 wird nicht zu Suite 4. Bei einer zweiten Adresszeile gehört die Einheit dorthin, sonst hinter die vollständige Straße. Das Nummernzeichen ist nur eine begrenzte Ausweichform, wenn keine passende Bezeichnung verfügbar ist. Erfinde niemals eine Einheit, um eine Warnung zu umgehen."},
      {heading:"Stadt, Bundesstaat und ZIP gemeinsam prüfen",body:"Prüfe die drei Werte gemeinsam im aktuellen USPS-Lookup. Nutze den standardisierten Ortsnamen und den offiziellen zweistelligen Bundesstaat. ZIP+4 darf übernommen werden, wenn USPS ihn für genau diese Adresse liefert; die vier Stellen werden nicht von einer Nachbarwohnung kopiert. Standardisierung beweist weder den Wohnsitz des Empfängers noch die Annahme durch einen privaten Mailroom oder die Verfügbarkeit einer internationalen Route."},
      {heading:"Verwaltete Empfangsorte ausdrücklich behandeln",body:"Campus, Büro, Hotel, Militäradresse, Locker, Mailbox-Dienst und Weiterleiter haben zusätzliche Regeln. Frage nach erforderlichem Namen, Abteilung, Einheit, Straße und Abholung und kläre internationale, große oder unterschriftspflichtige Pakete. Ein Frontdesk-Scan kann vor dem Besitz des Empfängers liegen. Zugangscodes gehören nicht in öffentliche Notizen, sondern nur in einen vorgesehenen privaten Hinweis, wenn die Annahmestelle dies verlangt."},
      {heading:"Referenz in die Kakobuy-Felder übertragen",body:"Wähle zunächst das Land, falls dadurch Bundesstaat- oder ZIP-Felder erscheinen, und übertrage dann jedes Feld einzeln. Name, Straße, Einheit, Staat, ZIP und Telefon bleiben an ihrem vorgesehenen Platz. Übersetze keine englische Straße, ändere keine Richtung und entferne keine führende Null. Bei einer Ablehnung speichere die geschwärzte Fehlermeldung, prüfe die USPS-Form erneut und nutze offiziellen Support statt erfundener Varianten."},
      {heading:"Etikettenvorschau vor Zahlung prüfen",body:"Vergleiche die endgültige Vorschau Zeichen für Zeichen mit der privaten Referenz: Empfänger, Hausnummer, Straße, Einheit, Stadt, Staat, ZIP und Land. Suche nach Kürzung, Dopplung oder falscher Zeile, besonders bei langen Firmen- oder kombinierten Straßenangaben. Prüfe die Telefonnummer privat und speichere eine geschwärzte Bestätigung mit Datum. Kann der Fehler nicht sicher korrigiert werden, wird vor internationaler Zahlung pausiert."},
      {heading:"Änderungen einfrieren und Zuständigkeit notieren",body:"Nach Einreichung gilt die bestätigte Adresse als eingefroren, sofern der Live-Ablauf keine sichere Korrektur anbietet. Unterstelle keine Änderung nach Verpackung, Etikett, Export oder Carrierannahme. Speichere Version und Zeitpunkt. Label created belegt nur elektronische Daten, nicht physische Annahme. Bei einer Ausnahme trenne Kakobuy, internationalen Carrier, US-Carrier und Empfangsstelle als mögliche nächste Verantwortliche."},
      {heading:"Mit Stop-oder-Einreichen-Check abschließen",body:"Einreichen nur, wenn Name, Straße, echte Einheit, Stadt, Staat, ZIP, Land, privates Kontaktfeld und Vorschau übereinstimmen. Beim Mailroom müssen interne Kennung und Abholung geklärt sein. Bei Widerspruch gilt Stop: keinen nahen ZIP wählen, keine Einheit weglassen und keine Zugangsdaten öffentlich machen. Die datierte, geschwärzte Prüfung reduziert Fehler, garantiert aber weder Route, Zoll, Carrierleistung noch Empfang."},
    ], takeaways:["Eine private Referenzadresse führen.","Echte Einheitsbezeichnung und Nummer erhalten.","Stadt, Staat und ZIP gemeinsam mit USPS prüfen.","Die endgültige Vorschau Feld für Feld vergleichen.","Bei offenen Widersprüchen stoppen; Standardisierung garantiert keine Zustellung."],
  },
  es: {
    tag:"GUÍA DE DIRECCIÓN EE. UU.",title:"Cómo dar formato a una dirección de entrega de EE. UU. para un paquete Kakobuy",description:"Da formato a una dirección estadounidense con campos USPS, apartamento, ZIP y auditoría privada de la etiqueta.",sourceNote:"El envío de paquetes de Kakobuy y las fuentes actuales de USPS se revisaron el 4 de septiembre de 2026. Estandarizar reduce errores evitables, pero no garantiza ruta ni entrega.",
    sections:[
      {heading:"Tratar la dirección como un registro coincidente",body:"Una dirección no es una frase libre: sus campos deben representar el mismo destino en el registro privado, Kakobuy, la etiqueta y el transportista. Separa nombre, organización necesaria, calle, unidad, ciudad, estado, ZIP y país; el teléfono va en contacto. Kakobuy permite elegir dirección y logística al presentar el paquete. Es un control final, no permiso para improvisar."},
      {heading:"Crear primero una referencia privada",body:"Parte de una etiqueta reciente entregada, un documento fiable del destinatario, instrucciones del receptor o USPS ZIP Code Lookup. No copies sin comprobar un mapa o autocompletado. Anota quién confirmó cada campo y la fecha; resuelve cambios de calle o unidad antes del envío. Nombre, apartamento, teléfono, correo, pedido y tracking completos siguen privados y se ocultan en cualquier copia compartida."},
      {heading:"Usar el orden de líneas de USPS",body:"Primero va el destinatario y, solo si es necesaria, la empresa receptora. Después van número, dirección, calle y tipo, con APT, STE o UNIT y su número. La última línea nacional lleva ciudad, abreviatura estatal de dos letras y ZIP; United States se selecciona como país. ALEX MORGAN; 245 W PINE ST APT 7B; DENVER CO 80203; UNITED STATES es un ejemplo inventado. La exactitud importa más que mayúsculas o puntuación."},
      {heading:"Conservar apartamento, suite y unidad",body:"Publication 28 enumera APT, STE, UNIT, BLDG y FL. Usa el designador real y el identificador exacto; no conviertas Apartment 4 en Suite 4. Si existe línea dos, coloca allí la unidad; si no, añádela después de la calle sin borrar datos. El símbolo # es una alternativa limitada cuando falta un designador disponible. Nunca inventes una unidad para eludir una advertencia."},
      {heading:"Comprobar juntos ciudad, estado y ZIP",body:"Consulta los tres valores en el USPS actual. Usa la ciudad estandarizada y la abreviatura oficial del estado. Añade ZIP+4 solo cuando USPS lo devuelve para esa dirección exacta; no copies cuatro dígitos de otro apartamento. La estandarización no prueba residencia, aceptación por un mailroom privado ni disponibilidad de una ruta internacional. Esas preguntas se verifican aparte."},
      {heading:"Tratar expresamente puntos de recepción gestionados",body:"Campus, oficina, hotel, dirección militar, locker, agencia postal y reenviador añaden reglas. Confirma nombre, departamento, buzón, calle y recogida, además de paquetes internacionales, grandes o con firma. Un escaneo de recepción puede preceder la posesión del destinatario. Los códigos de acceso nunca van en notas públicas; usa un campo privado aprobado solo cuando el receptor lo solicite."},
      {heading:"Mapear la referencia a los campos de Kakobuy",body:"Selecciona primero el país si activa estado o ZIP y transfiere un campo cada vez. Mantén nombre, calle, unidad, estado, ZIP y teléfono en su lugar. No traduzcas la calle, cambies una dirección cardinal ni elimines un cero inicial. Si la interfaz rechaza una dirección verificada, guarda el error ocultando datos, vuelve a revisar USPS y usa soporte oficial en vez de probar variantes inventadas."},
      {heading:"Auditar la vista de la etiqueta antes de pagar",body:"Compara carácter por carácter el destinatario, número, calle, unidad, ciudad, estado, ZIP y país con la referencia privada. Busca texto cortado, duplicado o movido, especialmente en nombres largos. Revisa teléfono y prefijo en privado y guarda una confirmación oculta con fecha. Si no puede corregirse con seguridad, pausa antes de pagar el transporte internacional; no presupongas que se arreglará tras el despacho."},
      {heading:"Congelar cambios y registrar el siguiente responsable",body:"Tras presentar el paquete, congela la dirección salvo que el flujo activo ofrezca una corrección segura. No supongas cambios después de embalaje, etiqueta, exportación o aceptación. Guarda versión y hora. Label created confirma datos electrónicos, no recepción física. Ante una excepción, separa Kakobuy, transportista internacional, última milla estadounidense y punto receptor para determinar quién controla el siguiente hecho."},
      {heading:"Terminar con una lista de parar o enviar",body:"Envía solo si coinciden nombre, calle, unidad real, ciudad, estado, ZIP, país, contacto privado y vista final. En un mailroom confirma identificador y recogida. Si existe una discrepancia, para: no elijas otro ZIP, omitas la unidad ni publiques acceso. La auditoría fechada y oculta reduce fallos, pero no garantiza ruta, aduana, transportista, firma o posesión final."},
    ],takeaways:["Mantén una referencia privada única.","Conserva designador y número de unidad reales.","Comprueba ciudad, estado y ZIP juntos con USPS.","Revisa la vista final campo por campo.","Para ante discrepancias; estandarizar no garantiza entrega."],
  },
  fr: {
    tag:"GUIDE ADRESSE ÉTATS-UNIS",title:"Comment formater une adresse de livraison américaine pour un colis Kakobuy",description:"Formatez une adresse américaine avec les champs USPS, l'unité, le ZIP Code et un contrôle privé de l'étiquette.",sourceNote:"Le dépôt de colis Kakobuy et les ressources USPS actuelles ont été vérifiés le 4 septembre 2026. La normalisation réduit les erreurs évitables sans garantir l'itinéraire ni la livraison.",
    sections:[
      {heading:"Traiter l'adresse comme un jeu de données concordant",body:"Une adresse américaine n'est pas une phrase libre : le dossier privé, Kakobuy, l'étiquette et le transporteur doivent désigner le même lieu. Séparez nom, organisation requise, rue, unité, ville, État, ZIP et pays ; le téléphone reste dans le champ contact. Kakobuy demande adresse et logistique lors du dépôt du colis. C'est un dernier contrôle, pas une autorisation d'improviser."},
      {heading:"Créer d'abord une référence privée",body:"Partez d'une étiquette récemment livrée, d'un document fiable, des consignes du lieu ou de USPS ZIP Code Lookup. Ne copiez pas une carte ou une saisie automatique sans contrôle. Notez qui a confirmé chaque champ et la date, puis résolvez les changements d'unité. Nom, appartement, téléphone, e-mail, commande et suivi restent privés et sont masqués sur toute copie partagée."},
      {heading:"Suivre l'ordre des lignes USPS",body:"Le destinataire vient d'abord, puis l'organisation seulement si elle est exigée. La ligne suivante porte numéro, direction, rue et suffixe, avec APT, STE ou UNIT et le numéro. Ville, abréviation d'État et ZIP suivent, puis United States dans le champ pays. ALEX MORGAN; 245 W PINE ST APT 7B; DENVER CO 80203; UNITED STATES est fictif. Exactitude et correspondance des champs priment sur la ponctuation."},
      {heading:"Conserver exactement apartment, suite ou unit",body:"Publication 28 reconnaît notamment APT, STE, UNIT, BLDG et FL. Utilisez le vrai indicateur et identifiant ; ne changez pas Apartment 4 en Suite 4. Placez l'unité sur la deuxième ligne disponible ou après la rue sans supprimer celle-ci. Le signe # n'est qu'une solution limitée si aucun indicateur correct n'est disponible. N'inventez jamais une unité pour contourner une alerte."},
      {heading:"Vérifier ensemble ville, État et ZIP",body:"Contrôlez les trois dans l'outil USPS actuel. Utilisez la ville normalisée et l'abréviation officielle à deux lettres. Ajoutez ZIP+4 uniquement si USPS le renvoie pour cette adresse précise ; ne copiez pas les quatre chiffres d'un voisin. La normalisation ne prouve ni la résidence, ni l'acceptation par un mailroom privé, ni la disponibilité d'une route internationale."},
      {heading:"Traiter explicitement les lieux gérés",body:"Campus, bureau, hôtel, adresse militaire, consigne, agence postale et réexpéditeur ont des règles supplémentaires. Confirmez nom, service, boîte, rue et retrait ainsi que l'acceptation des colis internationaux, volumineux ou signés. Un scan à l'accueil peut précéder la possession. Les codes d'accès ne vont jamais dans une note publique ; utilisez seulement le champ privé approuvé demandé par le lieu."},
      {heading:"Reporter la référence dans Kakobuy",body:"Choisissez d'abord le pays s'il active État ou ZIP, puis copiez chaque champ. Gardez nom, rue, unité, État, ZIP et téléphone à leur place. Ne traduisez pas la rue, ne modifiez pas une direction et ne supprimez pas un zéro initial. En cas de refus, conservez l'erreur masquée, revérifiez USPS et utilisez l'assistance officielle plutôt que des variantes inventées."},
      {heading:"Contrôler l'aperçu de l'étiquette avant paiement",body:"Comparez caractère par caractère destinataire, numéro, rue, unité, ville, État, ZIP et pays avec la référence privée. Repérez texte tronqué, doublé ou déplacé, surtout pour une longue organisation. Vérifiez le téléphone en privé et gardez une confirmation masquée datée. Si la correction n'est pas sûre, arrêtez avant le paiement international ; ne supposez pas une correction après départ."},
      {heading:"Geler les changements et noter le prochain responsable",body:"Après dépôt, considérez l'adresse comme figée sauf correction sûre offerte par le parcours actif. Ne présumez aucune modification après emballage, étiquette, export ou acceptation. Conservez version et heure. Label created prouve des données électroniques, pas la réception physique. En cas d'exception, distinguez Kakobuy, transporteur international, dernier kilomètre américain et lieu de réception."},
      {heading:"Finir par une décision arrêter ou soumettre",body:"Soumettez seulement si nom, rue, vraie unité, ville, État, ZIP, pays, contact privé et aperçu concordent. Pour un mailroom, confirmez identifiant et retrait. En cas d'écart, arrêtez : ne choisissez pas un ZIP voisin, n'omettez pas l'unité et ne publiez pas l'accès. Le contrôle daté réduit les erreurs sans garantir route, douane, transporteur, signature ou possession finale."},
    ],takeaways:["Conserver une référence privée unique.","Préserver le vrai indicateur et numéro d'unité.","Vérifier ville, État et ZIP ensemble avec USPS.","Contrôler l'aperçu final champ par champ.","Arrêter en cas d'écart ; la normalisation ne garantit pas la livraison."],
  },
  it: {
    tag:"GUIDA INDIRIZZO USA",title:"Come formattare un indirizzo di consegna USA per un pacco Kakobuy",description:"Formatta un indirizzo statunitense con campi USPS, unità, ZIP Code e controllo privato dell'etichetta.",sourceNote:"La presentazione pacco Kakobuy e le fonti USPS correnti sono state controllate il 4 settembre 2026. La standardizzazione riduce errori evitabili, ma non garantisce rotta o consegna.",
    sections:[
      {heading:"Trattare l'indirizzo come dati corrispondenti",body:"Un indirizzo USA non è una frase libera: registro privato, Kakobuy, etichetta e vettore devono indicare lo stesso luogo. Separa nome, organizzazione necessaria, via, unità, città, stato, ZIP e paese; il telefono resta nel campo contatto. Kakobuy chiede indirizzo e logistica quando si presenta il pacco. È un controllo finale, non il momento di improvvisare."},
      {heading:"Creare prima un riferimento privato",body:"Parti da un'etichetta consegnata di recente, un documento affidabile, istruzioni del ricevente o USPS ZIP Code Lookup. Non copiare mappe o completamenti automatici senza verifica. Registra chi ha confermato ogni campo e la data e risolvi cambi di numero o unità. Nome, appartamento, telefono, e-mail, ordine e tracking completi restano privati e vengono oscurati nelle copie condivise."},
      {heading:"Usare l'ordine delle righe USPS",body:"Prima viene il destinatario, poi l'eventuale organizzazione richiesta. Seguono numero, direzione, via e suffisso con APT, STE o UNIT e numero. L'ultima riga nazionale contiene città, abbreviazione statale e ZIP; United States va nel campo paese. ALEX MORGAN; 245 W PINE ST APT 7B; DENVER CO 80203; UNITED STATES è inventato. Precisione e mappatura contano più di maiuscole o punteggiatura."},
      {heading:"Conservare apartment, suite e unit",body:"Publication 28 elenca APT, STE, UNIT, BLDG e FL. Usa il designatore reale e l'identificatore esatto; Apartment 4 non diventa Suite 4. Inserisci l'unità nella seconda riga o dopo la via senza cancellare dati. Il simbolo # è un'alternativa limitata quando manca un designatore corretto. Non inventare mai un'unità per superare un avviso."},
      {heading:"Verificare insieme città, stato e ZIP",body:"Controlla tutti e tre nello strumento USPS corrente. Usa la città standardizzata e l'abbreviazione ufficiale di due lettere. Aggiungi ZIP+4 solo se USPS lo restituisce per quell'indirizzo esatto; non copiare quattro cifre da un'altra unità. La standardizzazione non dimostra residenza, accettazione di un mailroom privato o disponibilità di una rotta internazionale."},
      {heading:"Gestire espressamente i punti amministrati",body:"Campus, ufficio, hotel, indirizzo militare, locker, agenzia postale e inoltratore hanno regole ulteriori. Conferma nome, reparto, casella, via e ritiro, oltre all'accettazione di pacchi internazionali, grandi o con firma. Una scansione alla reception può precedere il possesso. I codici d'accesso non vanno in note pubbliche; usa solo un campo privato approvato quando richiesto."},
      {heading:"Mappare il riferimento nei campi Kakobuy",body:"Scegli prima il paese se attiva stato o ZIP, poi trasferisci un campo alla volta. Mantieni nome, via, unità, stato, ZIP e telefono nel posto previsto. Non tradurre la via, cambiare un'indicazione direzionale o togliere uno zero iniziale. Se l'interfaccia rifiuta un indirizzo verificato, salva l'errore oscurato, ricontrolla USPS e usa il supporto ufficiale invece di varianti inventate."},
      {heading:"Controllare l'anteprima etichetta prima del pagamento",body:"Confronta carattere per carattere destinatario, numero, via, unità, città, stato, ZIP e paese con il riferimento privato. Cerca testo troncato, duplicato o spostato, soprattutto con organizzazioni lunghe. Verifica il telefono privatamente e conserva una conferma oscurata con data. Se non puoi correggere in sicurezza, fermati prima del pagamento internazionale; non presumere una modifica dopo la partenza."},
      {heading:"Bloccare le modifiche e registrare il prossimo responsabile",body:"Dopo l'invio considera l'indirizzo bloccato salvo correzione sicura nel flusso attivo. Non presumere cambi dopo imballaggio, etichetta, export o accettazione. Salva versione e orario. Label created prova dati elettronici, non presa fisica. In caso di eccezione separa Kakobuy, vettore internazionale, ultimo miglio USA e punto ricevente per capire chi controlla il passaggio successivo."},
      {heading:"Concludere con stop o invio",body:"Invia solo se nome, via, unità reale, città, stato, ZIP, paese, contatto privato e anteprima coincidono. Per un mailroom conferma identificatore e ritiro. Se resta una discrepanza, stop: non scegliere uno ZIP vicino, omettere l'unità o pubblicare accessi. L'audit datato riduce errori ma non garantisce rotta, dogana, vettore, firma o possesso finale."},
    ],takeaways:["Mantieni un unico riferimento privato.","Conserva designatore e numero reali dell'unità.","Controlla insieme città, stato e ZIP con USPS.","Verifica l'anteprima finale campo per campo.","Fermati sulle discrepanze; standardizzare non garantisce la consegna."],
  },
};
