import type { ArticleRecord } from "./article-data";
import type { Lang } from "./site-data";

type LocalizedArticle = Pick<ArticleRecord, "tag" | "title" | "description" | "sourceNote" | "sections" | "takeaways">;

export const usaUnitZip4ArticleTranslations: Record<Lang, LocalizedArticle> = {
  en: {
    tag: "US ADDRESS DETAIL",
    title: "Apartment, Suite, Unit and ZIP+4 Checks Before International Dispatch",
    description: "Check apartment, suite, unit and ZIP+4 details for a US-bound Kakobuy parcel without inventing address data or treating postal standardization as a delivery guarantee.",
    sourceNote: "Kakobuy's public parcel flow and current USPS Publication 28 and ZIP Code Lookup resources were checked on September 10, 2026. Address rules and platform fields can change; a standardized result does not guarantee carrier access or delivery.",
    sections: [
      { heading: "Why secondary address details deserve a separate check", body: "A street address can identify the correct building while still failing to identify the correct delivery point inside it. Apartment, suite, unit, building, floor and room information is therefore not optional decoration when the recipient's location uses it. For a US-bound Kakobuy parcel, the goal is to make the same destination appear in the buyer's private reference, the parcel-submission fields, the final shipping label and the receiving location's records. USPS Publication 28 says secondary unit designators such as APT or STE are required on mailpieces for addresses that contain them, with the preferred position at the end of the delivery-address line. That rule supports a field check; it does not prove that Kakobuy, an international carrier or a private mailroom will accept every address. Keep syntax, platform compatibility and delivery access as three separate questions." },
      { heading: "Use the real designator, not a convenient substitute", body: "Record the designation used by the building or receiving organization. USPS lists common forms including APT for apartment, STE for suite, UNIT for unit, BLDG for building, FL for floor, RM for room and DEPT for department. These labels are not interchangeable. A residential apartment should not become a suite because STE is shorter, and a private mailbox should not be relabeled as an apartment. Ask the recipient or building management when the designation is uncertain. Keep the exact secondary number, including meaningful letters or hyphens. Do not remove a leading zero, change 7B to B7 or translate a building name. If an earlier successful label uses a standardized version, compare it with the current USPS lookup and the location's instructions rather than assuming the old label is permanently correct." },
      { heading: "Place the unit where the form and label can preserve it", body: "If the Kakobuy address form provides two delivery-address lines, put the street number and street name on the first line and the apartment, suite or unit on the second, unless the live form gives a different explicit instruction. Then inspect the final label preview because some systems combine the fields. USPS prefers the unit at the end of the delivery-address line; Publication 28 also allows secondary information on the line immediately above when the full delivery line cannot fit. The important result is that the street and unit remain connected and legible. Avoid putting the unit only in a general note, company field or phone field. Those fields may not reach the label or the last-mile carrier. Do not repeat the unit on two lines, because duplication can create a different address or trigger manual correction." },
      { heading: "Use the pound sign only as a limited fallback", body: "Publication 28 says a pound sign should not replace the correct designator when APT, STE or another known term is available. If the sign is used, a space is required between # and the secondary number. The publication also warns that # may be prohibited for a commercial mail receiving agency address that uses private-mailbox information. In practice, prefer the actual building designation. Do not convert APT 12 into #12 merely because an online form appears shorter, and never use # to hide that the address is a mailbox or forwarding service. If Kakobuy rejects a verified designator, capture the error privately, recheck the current form requirements and use the official support path. Testing invented variants until one is accepted can produce a label that no longer matches the recipient's real delivery point." },
      { heading: "Verify ZIP+4 for the exact delivery point", body: "ZIP+4 adds four digits to a five-digit ZIP Code and can identify a more specific delivery segment. Use it only when the current USPS lookup returns it for the exact street and secondary address you intend to ship to. Do not copy the +4 from another apartment, business suite or online directory entry, because nearby units can produce different results. Enter street, city and state together in the official lookup, review the standardized address, and compare every unit character before saving the result. USPS expressly notes that a ZIP Code lookup does not confirm that a person or company is located at the address. It also does not confirm that a Kakobuy route accepts the destination. Treat the result as postal standardization evidence, while recipient identity, platform eligibility and receiving permission remain separately verified facts." },
      { heading: "Decide whether five digits or ZIP+4 belongs in the record", body: "When USPS returns ZIP+4 for the exact address and the Kakobuy form accepts the format, preserve the full result in the private source-of-truth record. If the form accepts only five digits, do not force the extra digits into another field. Save the full USPS result privately, enter the supported five-digit ZIP Code and check the final label. If the live form accepts either format, use the one that matches the current standardized address and receiving instructions. Never invent +4 digits to make an address look complete. Also avoid stripping a valid +4 without noting the change when a building or mailroom specifically asks for it. The decision should be reproducible: record the lookup date, input address, standardized output and the exact form limitation that affected what was submitted." },
      { heading: "Handle multi-building and managed properties carefully", body: "Large apartment communities, campuses, office parks and mixed-use buildings may share a street address while relying on building, floor, department or internal recipient codes. Confirm which details belong in the postal address and which belong in a private delivery instruction. A property name is not a substitute for a numbered unit. Ask the receiving location whether it accepts international parcels, packages addressed to residents rather than leaseholders, oversized boxes and signature services. Record where carrier possession normally ends: doorstep, parcel locker, front desk or mailroom. A delivery scan at a managed desk can be valid even though the recipient has not collected the parcel. This is a last-mile evidence issue, not a reason to distort the address. Never place door codes, locker PINs or access credentials in public screenshots, spreadsheets or article examples." },
      { heading: "Run a character-by-character pre-dispatch audit", body: "Compare the private reference, Kakobuy saved address and final parcel preview in a fixed order: recipient name; street number; directional; street name and suffix; building, apartment, suite or unit designator; secondary number; city; two-letter state; five-digit ZIP and +4 when used; country; and the private contact field. Check for truncation, duplicated units, missing letters, dropped hyphens and autofill changes. Long organization names can push essential address data out of a constrained line, so verify the rendered label rather than trusting the edit form. If the preview hides part of the address, pause. Do not assume the exported label contains characters that the confirmation screen omits. Save a redacted audit showing structure and date, while the unredacted record stays private." },
      { heading: "Use stop conditions instead of clever workarounds", body: "Stop parcel submission when the recipient cannot confirm the unit, USPS returns a materially different address, the ZIP+4 belongs to another delivery point, the platform removes or duplicates a field, or the receiving location's rules conflict with the planned address. Also stop when an apartment number is known to be required but cannot be preserved in the preview. Do not select a nearby ZIP Code, move the unit into the recipient name, shorten an identifier without permission or reuse another tenant's +4. A support request should describe the narrow mismatch, include a redacted view of the standardized address and state which field the live form will not retain. Address workarounds made before dispatch become difficult to diagnose after an international handoff, so an unresolved conflict is a reason to wait rather than a reason to guess." },
      { heading: "Freeze the approved version and keep the claim narrow", body: "After submission, retain the exact approved address version, verification date, USPS result and redacted label preview. Do not assume the address can be changed after packing, label creation or carrier handoff unless the live Kakobuy workflow explicitly provides a safe correction. When a US carrier later appears, compare its destination summary without exposing personal information. A standardized unit and ZIP+4 reduce preventable ambiguity, but they cannot guarantee customs release, route availability, carrier access, signature, mailroom processing or possession by the recipient. If a delivery exception occurs, distinguish the address printed on the label from access conditions and carrier events. The defensible conclusion is limited: the submitted label preserved the recipient's verified secondary unit and current USPS-standardized postal code at the time checked." },
    ],
    takeaways: ["Use the building's real APT, STE, UNIT or other designator.", "Keep the secondary number exact and visible on the final label.", "Use ZIP+4 only when USPS returns it for the exact delivery point.", "Compare saved fields and the final preview character by character.", "Stop on an unresolved mismatch; standardization is not a delivery guarantee."],
  },
  de: {
    tag:"US-ADRESSDETAIL",title:"Apartment, Suite, Unit und ZIP+4 vor internationalem Versand prüfen",description:"Sekundäre US-Adressangaben und ZIP+4 für Kakobuy prüfen, ohne Daten zu erfinden oder Zustellung zu garantieren.",sourceNote:"Kakobuys öffentlicher Paketablauf sowie USPS Publication 28 und ZIP-Lookup wurden am 10. September 2026 geprüft. Felder und Regeln können sich ändern; Standardisierung garantiert keine Zustellung.",
    sections:[
      {heading:"Warum sekundäre Adressdaten separat geprüft werden",body:"Eine Straße kann das richtige Gebäude, aber nicht die richtige Stelle darin bezeichnen. Apartment, Suite, Unit, Gebäude, Etage oder Raum müssen in privater Referenz, Kakobuy-Feldern, Etikett und Empfangsakte dasselbe Ziel beschreiben. USPS bevorzugt die Bezeichnung am Ende der Lieferadresszeile. Syntax, Plattformkompatibilität und Zugang bleiben getrennte Fragen."},
      {heading:"Die echte Bezeichnung verwenden",body:"Nutzen Sie die vom Gebäude verwendete Form: APT, STE, UNIT, BLDG, FL, RM oder DEPT. Sie sind nicht austauschbar. Verändern Sie weder Buchstaben noch Bindestriche und entfernen Sie keine führende Null. Bei Unsicherheit bestätigt Empfänger oder Verwaltung die genaue Bezeichnung; ein altes Etikett wird mit aktuellem USPS-Ergebnis verglichen."},
      {heading:"Die Einheit so platzieren, dass sie erhalten bleibt",body:"Bei zwei Adresszeilen steht die Straße gewöhnlich zuerst und die Einheit separat, sofern das Live-Formular nichts anderes verlangt. Prüfen Sie die Vorschau, da Systeme Zeilen zusammenführen können. Einheit und Straße müssen verbunden und lesbar bleiben. Die Einheit gehört nicht nur in Notiz, Firma oder Telefon und wird nicht doppelt eingetragen."},
      {heading:"Das Nummernzeichen nur begrenzt nutzen",body:"USPS empfiehlt # nicht als Ersatz, wenn APT oder STE bekannt ist; bei Verwendung braucht es ein Leerzeichen. Für private Mailbox-Adressen kann # unzulässig sein. Verbergen Sie damit weder Mailbox noch Weiterleitung. Lehnt Kakobuy die geprüfte Form ab, speichern Sie den Fehler privat und nutzen Sie offiziellen Support statt erfundener Varianten."},
      {heading:"ZIP+4 für den exakten Zustellpunkt prüfen",body:"Übernehmen Sie ZIP+4 nur, wenn der aktuelle USPS-Lookup es für genau Straße und Einheit liefert. Kopieren Sie keine vier Stellen von Nachbarwohnung oder Firma. Prüfen Sie Straße, Stadt und Staat gemeinsam. Das Ergebnis standardisiert die Postadresse, bestätigt aber weder Empfänger, Kakobuy-Route noch Annahme durch den Empfangsort."},
      {heading:"Fünf Stellen oder ZIP+4 dokumentiert entscheiden",body:"Akzeptiert das Formular das vollständige USPS-Ergebnis, speichern Sie es. Unterstützt es nur fünf Stellen, drücken Sie +4 nicht in ein anderes Feld; bewahren Sie das volle Ergebnis privat auf und prüfen Sie das Etikett. Protokollieren Sie Datum, Eingabe, Ausgabe und Formulargrenze. Zusatzziffern werden nie erfunden."},
      {heading:"Große und verwaltete Anlagen sorgfältig behandeln",body:"Wohnanlagen, Campus und Büroparks benötigen eventuell Gebäude, Etage, Abteilung oder interne Kennung. Klären Sie, was Postadresse und was private Anweisung ist, sowie Annahme internationaler, großer oder unterschriftspflichtiger Pakete. Ein Frontdesk-Scan kann vor Abholung erfolgen. Türcodes und PINs bleiben vollständig privat."},
      {heading:"Vor Versand Zeichen für Zeichen prüfen",body:"Vergleichen Sie Name, Hausnummer, Richtung, Straße, Einheit, Nummer, Stadt, Staat, ZIP/+4, Land und Kontaktfeld. Suchen Sie Kürzung, Dopplung, fehlende Buchstaben, entfernte Bindestriche und Autofill-Änderungen. Maßgeblich ist die endgültige Vorschau. Speichern Sie nur eine geschwärzte Prüfkopie."},
      {heading:"Stop-Regeln statt Tricks",body:"Stoppen Sie bei unbestätigter Einheit, abweichendem USPS-Ergebnis, fremdem +4, verlorenen oder doppelten Feldern und Konflikt mit Empfangsregeln. Wählen Sie keinen nahen ZIP, verschieben Sie die Einheit nicht in den Namen und kürzen Sie nichts ohne Zustimmung. Support erhält die enge, geschwärzte Feldfrage."},
      {heading:"Freigegebene Version einfrieren",body:"Nach Einreichung bleiben freigegebene Adresse, Datum, USPS-Ergebnis und Vorschau erhalten. Unterstellen Sie keine spätere Änderung. Die korrekte Einheit und ZIP+4 reduzieren Mehrdeutigkeit, garantieren aber weder Zoll, Route, Zugang, Unterschrift noch Besitz. Die Aussage bleibt: Das Etikett bewahrte die geprüften Daten zum Kontrollzeitpunkt."},
    ],takeaways:["Echte APT-, STE- oder UNIT-Bezeichnung nutzen.","Sekundärnummer exakt auf dem Etikett erhalten.","ZIP+4 nur für den exakten USPS-Treffer verwenden.","Felder und Vorschau Zeichen für Zeichen vergleichen.","Bei Widerspruch stoppen; Standardisierung garantiert nichts."],
  },
  es: {
    tag:"DETALLE DE DIRECCIÓN EE. UU.",title:"Revisar apartamento, suite, unidad y ZIP+4 antes del envío internacional",description:"Comprueba unidad secundaria y ZIP+4 para un paquete Kakobuy sin inventar datos ni prometer entrega.",sourceNote:"El flujo público de Kakobuy, Publication 28 y USPS ZIP Lookup se revisaron el 10 de septiembre de 2026. Los campos cambian y la normalización no garantiza entrega.",
    sections:[
      {heading:"Por qué revisar aparte los datos secundarios",body:"La calle puede identificar el edificio pero no el punto interior. Apartamento, suite, unidad, edificio, planta o habitación deben coincidir en referencia privada, Kakobuy, etiqueta y receptor. USPS prefiere el designador al final de la línea. Sintaxis, compatibilidad y acceso se comprueban por separado."},
      {heading:"Usar el designador real",body:"Utiliza APT, STE, UNIT, BLDG, FL, RM o DEPT según el edificio. No son intercambiables. Conserva letras, guiones y ceros iniciales. Si hay duda, confirma con el destinatario o administración y contrasta cualquier etiqueta antigua con el resultado actual de USPS."},
      {heading:"Colocar la unidad donde se conserve",body:"Con dos líneas, normalmente calle va en la primera y unidad en la segunda, salvo instrucción expresa del formulario. Revisa la etiqueta porque el sistema puede unirlas. Calle y unidad deben seguir legibles. No pongas la unidad solo en notas, empresa o teléfono ni la dupliques."},
      {heading:"Usar # solo como alternativa limitada",body:"USPS no recomienda # cuando se conoce APT o STE y exige espacio antes del número. Puede prohibirse en direcciones de buzón privado. No lo uses para ocultar un buzón o reenviador. Si Kakobuy rechaza una forma verificada, guarda el error privado y consulta soporte oficial."},
      {heading:"Verificar ZIP+4 para el punto exacto",body:"Usa ZIP+4 solo si el USPS actual lo devuelve para esa calle y unidad. No copies cuatro cifras de otro apartamento o negocio. Consulta calle, ciudad y estado juntos. El resultado estandariza la dirección, pero no demuestra residencia, ruta Kakobuy ni permiso del mailroom."},
      {heading:"Decidir entre cinco cifras y ZIP+4",body:"Si el formulario acepta el resultado completo, consérvalo. Si admite cinco cifras, no fuerces +4 en otro campo; guarda el resultado completo en privado y revisa la etiqueta. Registra fecha, entrada, salida y límite del formulario. Nunca inventes los cuatro dígitos."},
      {heading:"Tratar con cuidado propiedades gestionadas",body:"Complejos, campus y oficinas pueden requerir edificio, planta, departamento o código interno. Distingue dirección postal de instrucción privada y confirma paquetes internacionales, grandes o con firma. Un escaneo de recepción puede preceder la recogida. Códigos y PIN permanecen privados."},
      {heading:"Auditar carácter por carácter",body:"Compara nombre, número, dirección, calle, unidad, identificador, ciudad, estado, ZIP/+4, país y contacto. Busca cortes, duplicados, letras perdidas, guiones eliminados y cambios de autofill. La vista final manda. Guarda solo una copia censurada con fecha."},
      {heading:"Usar condiciones de parada",body:"Detén el envío si la unidad no está confirmada, USPS difiere, +4 pertenece a otro punto, el formulario elimina o duplica datos o el receptor no acepta el formato. No elijas un ZIP cercano ni muevas la unidad al nombre. Plantea a soporte una pregunta limitada y censurada."},
      {heading:"Congelar la versión aprobada",body:"Conserva dirección, fecha, resultado USPS y vista aprobada. No supongas cambios posteriores. Unidad y ZIP+4 reducen ambigüedad, pero no garantizan aduana, ruta, acceso, firma ni posesión. La conclusión solo afirma que la etiqueta conservaba los datos verificados en esa fecha."},
    ],takeaways:["Usa el designador real APT, STE o UNIT.","Conserva exacto el número secundario.","Usa ZIP+4 solo para el resultado USPS exacto.","Compara campos y vista carácter por carácter.","Detente ante diferencias; normalizar no garantiza entrega."],
  },
  fr: {
    tag:"DÉTAIL ADRESSE USA",title:"Vérifier appartement, suite, unité et ZIP+4 avant l’expédition internationale",description:"Contrôlez l’unité secondaire et le ZIP+4 d’un colis Kakobuy sans inventer de données ni garantir la livraison.",sourceNote:"Le parcours public Kakobuy, Publication 28 et USPS ZIP Lookup ont été vérifiés le 10 septembre 2026. Les champs évoluent et la normalisation ne garantit pas la livraison.",
    sections:[
      {heading:"Pourquoi contrôler séparément les données secondaires",body:"La rue peut identifier le bâtiment sans identifier le point intérieur. Appartement, suite, unité, bâtiment, étage ou chambre doivent correspondre dans la référence privée, Kakobuy, l’étiquette et le registre de réception. USPS préfère l’indicateur en fin de ligne. Syntaxe, compatibilité et accès restent trois contrôles."},
      {heading:"Utiliser le véritable indicateur",body:"Utilisez APT, STE, UNIT, BLDG, FL, RM ou DEPT selon le lieu. Ils ne sont pas interchangeables. Conservez lettres, traits d’union et zéros initiaux. En cas de doute, demandez au destinataire ou au gestionnaire et comparez toute ancienne étiquette au résultat USPS actuel."},
      {heading:"Placer l’unité là où elle sera conservée",body:"Avec deux lignes, la rue va généralement sur la première et l’unité sur la seconde, sauf instruction explicite. Vérifiez l’étiquette finale car le système peut les fusionner. Rue et unité doivent rester lisibles. Ne placez pas l’unité seulement dans note, société ou téléphone et ne la dupliquez pas."},
      {heading:"Utiliser # seulement en dernier recours",body:"USPS déconseille # si APT ou STE est connu et exige un espace avant le numéro. Il peut être interdit pour une boîte privée. Ne l’utilisez pas pour masquer une boîte ou un réexpéditeur. Si Kakobuy refuse une forme vérifiée, conservez l’erreur en privé et utilisez le support officiel."},
      {heading:"Vérifier ZIP+4 pour le point exact",body:"Utilisez ZIP+4 uniquement si le USPS actuel le renvoie pour cette rue et cette unité. Ne copiez pas quatre chiffres d’un voisin ou d’une entreprise. Recherchez rue, ville et État ensemble. Le résultat normalise l’adresse mais ne prouve ni résident, ni route Kakobuy, ni permission du mailroom."},
      {heading:"Choisir cinq chiffres ou ZIP+4",body:"Si le formulaire accepte le résultat complet, conservez-le. S’il accepte cinq chiffres, ne forcez pas +4 ailleurs; gardez le résultat complet en privé et vérifiez l’étiquette. Notez date, saisie, sortie et limite du formulaire. N’inventez jamais les quatre chiffres."},
      {heading:"Traiter soigneusement les sites gérés",body:"Résidences, campus et bureaux peuvent demander bâtiment, étage, service ou code interne. Distinguez adresse postale et instruction privée et confirmez colis internationaux, volumineux ou signés. Un scan d’accueil peut précéder le retrait. Codes et PIN restent privés."},
      {heading:"Contrôler caractère par caractère",body:"Comparez nom, numéro, direction, rue, unité, identifiant, ville, État, ZIP/+4, pays et contact. Cherchez coupure, doublon, lettre perdue, trait retiré et modification automatique. La prévisualisation finale est décisive. Ne sauvegardez qu’une copie masquée datée."},
      {heading:"Appliquer des conditions d’arrêt",body:"Arrêtez si l’unité n’est pas confirmée, USPS diffère, +4 vise un autre point, le formulaire supprime ou double un champ, ou le site refuse l’adresse. Ne choisissez pas un ZIP proche et ne déplacez pas l’unité dans le nom. Posez au support une question précise et masquée."},
      {heading:"Figer la version approuvée",body:"Conservez adresse, date, résultat USPS et aperçu approuvé. Ne supposez aucune correction ultérieure. Unité et ZIP+4 réduisent l’ambiguïté sans garantir douane, route, accès, signature ou possession. La conclusion affirme seulement que l’étiquette gardait les données vérifiées à cette date."},
    ],takeaways:["Utiliser le vrai indicateur APT, STE ou UNIT.","Conserver exactement le numéro secondaire.","Utiliser ZIP+4 seulement pour le résultat USPS exact.","Comparer champs et aperçu caractère par caractère.","Arrêter en cas d’écart; normaliser ne garantit pas livrer."],
  },
  it: {
    tag:"DETTAGLIO INDIRIZZO USA",title:"Controllare appartamento, suite, unità e ZIP+4 prima della spedizione internazionale",description:"Verifica unità secondaria e ZIP+4 per un pacco Kakobuy senza inventare dati o garantire consegna.",sourceNote:"Il flusso pubblico Kakobuy, Publication 28 e USPS ZIP Lookup sono stati verificati il 10 settembre 2026. Campi e regole cambiano; la standardizzazione non garantisce consegna.",
    sections:[
      {heading:"Perché controllare separatamente i dettagli secondari",body:"La strada può indicare l’edificio ma non il punto interno. Appartamento, suite, unità, edificio, piano o stanza devono coincidere in riferimento privato, Kakobuy, etichetta e ricezione. USPS preferisce il designatore alla fine della riga. Sintassi, compatibilità e accesso restano verifiche separate."},
      {heading:"Usare il designatore reale",body:"Usa APT, STE, UNIT, BLDG, FL, RM o DEPT secondo l’edificio. Non sono intercambiabili. Conserva lettere, trattini e zeri iniziali. In caso di dubbio, conferma con destinatario o amministrazione e confronta una vecchia etichetta con il risultato USPS attuale."},
      {heading:"Posizionare l’unità dove viene conservata",body:"Con due righe, la strada va di solito sulla prima e l’unità sulla seconda, salvo istruzioni live diverse. Controlla l’etichetta perché il sistema può unirle. Strada e unità devono restare leggibili. Non mettere l’unità solo in note, azienda o telefono e non duplicarla."},
      {heading:"Usare # solo come ripiego limitato",body:"USPS sconsiglia # quando APT o STE è noto e richiede uno spazio prima del numero. Può essere vietato per caselle private. Non usarlo per nascondere casella o inoltro. Se Kakobuy rifiuta la forma verificata, salva l’errore in privato e usa il supporto ufficiale."},
      {heading:"Verificare ZIP+4 per il punto esatto",body:"Usa ZIP+4 solo se USPS lo restituisce per quella strada e unità. Non copiare quattro cifre da appartamento o attività vicina. Cerca insieme strada, città e stato. Il risultato standardizza l’indirizzo ma non prova destinatario, rotta Kakobuy o permesso della reception."},
      {heading:"Decidere tra cinque cifre e ZIP+4",body:"Se il modulo accetta il risultato completo, conservalo. Se accetta cinque cifre, non forzare +4 in un altro campo; salva il risultato completo privatamente e verifica l’etichetta. Registra data, input, output e limite del modulo. Non inventare mai le cifre aggiuntive."},
      {heading:"Gestire con cura proprietà amministrate",body:"Complessi, campus e uffici possono richiedere edificio, piano, reparto o codice interno. Distingui indirizzo postale e istruzione privata e conferma pacchi internazionali, grandi o firmati. Una scansione alla reception può precedere il ritiro. Codici e PIN restano privati."},
      {heading:"Controllare carattere per carattere",body:"Confronta nome, numero, direzione, strada, unità, identificatore, città, stato, ZIP/+4, paese e contatto. Cerca tagli, duplicati, lettere perse, trattini rimossi e modifiche automatiche. Conta l’anteprima finale. Salva solo una copia oscurata e datata."},
      {heading:"Usare condizioni di stop",body:"Ferma se l’unità non è confermata, USPS differisce, +4 appartiene a un altro punto, il modulo elimina o duplica dati o la reception rifiuta l’indirizzo. Non scegliere ZIP vicini né spostare l’unità nel nome. Invia al supporto una domanda precisa e oscurata."},
      {heading:"Congelare la versione approvata",body:"Conserva indirizzo, data, risultato USPS e anteprima approvata. Non presumere correzioni successive. Unità e ZIP+4 riducono ambiguità ma non garantiscono dogana, rotta, accesso, firma o possesso. La conclusione afferma solo che l’etichetta preservava i dati verificati in quella data."},
    ],takeaways:["Usa il vero designatore APT, STE o UNIT.","Conserva esatto il numero secondario.","Usa ZIP+4 solo per il risultato USPS esatto.","Confronta campi e anteprima carattere per carattere.","Fermati davanti a conflitti; standardizzare non garantisce consegna."],
  },
};

const parityAdditions: Record<Exclude<Lang, "en">, string[]> = {
  de: [
    "USPS Publication 28 verlangt solche Sekundärbezeichnungen, wenn die Adresse sie enthält. Das ist jedoch nur eine Regel für die Adressstruktur: Weder die Annahme durch ein internationales Transportunternehmen noch der Zutritt zu einem privaten Empfangsraum folgt daraus. Das Ziel muss in der privaten Ausgangsnotiz, im gespeicherten Kakobuy-Datensatz, in der endgültigen Etikettenvorschau und in den Unterlagen des Empfangsorts identisch bleiben.",
    "Eine Wohnung wird nicht zur Suite, nur weil STE kürzer ist, und ein privates Postfach darf nicht als Apartment erscheinen. Bewahren Sie die genaue Nummer samt aussagekräftigen Buchstaben oder Bindestrichen auf: 7B ist nicht B7, und eine führende Null kann Teil der Kennung sein. Wird eine frühere erfolgreiche Schreibweise verwendet, ist sie lediglich ein Vergleichsbeleg und keine dauerhafte Bestätigung.",
    "Publication 28 erlaubt die Sekundärangabe unmittelbar über der Lieferzeile, wenn die vollständige Zeile nicht passt. Entscheidend ist die gerenderte Ausgabe, nicht allein das Bearbeitungsformular. Allgemeine Notizen, Firmen- oder Telefonfelder können bei der Etikettenerstellung entfallen. Eine doppelte Eintragung auf mehreren Zeilen kann dagegen als andere Anschrift gelesen oder manuell korrigiert werden.",
    "Steht keine bekannte Bezeichnung zur Verfügung und wird das Nummernzeichen verwendet, muss zwischen # und Nummer ein Leerzeichen stehen. Bei Adressen einer Commercial Mail Receiving Agency kann diese Form unzulässig sein. Wiederholtes Ausprobieren erfundener Varianten bis zur Formularannahme löst das Problem nicht; es kann eine technisch akzeptierte, aber sachlich falsche Zieladresse erzeugen.",
    "Geben Sie im offiziellen Lookup Straße, Stadt und Bundesstaat gemeinsam ein und vergleichen Sie anschließend jedes Zeichen der standardisierten Einheit. Nahe Wohnungen oder Büros können andere Zusatzziffern erhalten. USPS weist ausdrücklich darauf hin, dass ein Lookup-Treffer nicht beweist, dass eine Person oder Firma dort ansässig ist. Plattformberechtigung, Empfängeridentität und Annahmeerlaubnis bleiben eigene Prüfungen.",
    "Wenn beide Formate möglich sind, verwenden Sie die aktuelle standardisierte Form, die zugleich den Anweisungen des Empfangsorts entspricht. Wird ein gültiger ZIP+4 auf Wunsch einer Verwaltung nicht übernommen, dokumentieren Sie auch diese Abweichung. Eine reproduzierbare Entscheidung enthält Prüfdatum, eingegebene Anschrift, USPS-Ausgabe, eingereichten Wert und die konkrete Beschränkung des Live-Formulars.",
    "Ein Anlagenname ersetzt niemals die nummerierte Einheit. Klären Sie außerdem, ob Pakete für Bewohner akzeptiert werden, deren Name nicht im Mietvertrag steht, und ob Größe oder Unterschrift besondere Übergaben auslösen. Notieren Sie, ob Carrier-Besitz normalerweise an Tür, Locker, Rezeption oder Mailroom endet. Ein Zustellscan dort beweist noch nicht die persönliche Abholung.",
    "Die Prüfreihenfolge lautet Empfängername, Hausnummer, Richtungsangabe, Straßenname und -suffix, Gebäude- oder Einheitsbezeichnung, Sekundärnummer, Ort, zweistelliger Staat, ZIP mit optionalem +4, Land und privates Kontaktfeld. Lange Organisationsnamen können wesentliche Daten abschneiden. Ist die Vorschau unvollständig, pausieren Sie; unterstellen Sie keine Zeichen in der exportierten Version.",
    "Weitere Stop-Gründe sind ein ZIP+4 für einen anderen Zustellpunkt oder widersprechende Vorgaben des Empfangsorts. Verschieben Sie die Einheit nicht in den Empfängernamen, kürzen Sie keine Kennung ohne Erlaubnis und verwenden Sie keine Daten eines anderen Mieters. Eine Supportanfrage nennt nur die genaue Feldabweichung und zeigt eine geschwärzte Standardansicht, niemals unnötige persönliche Angaben.",
    "Bewahren Sie nach Einreichung die vollständige freigegebene Fassung privat und eine geschwärzte Prüfkopie auf. Eine nachträgliche Änderung darf nur angenommen werden, wenn der aktuelle Kakobuy-Ablauf sie ausdrücklich sicher ermöglicht. Bei späterer Zustellstörung werden gedruckte Anschrift, Zugangslage und Carrier-Ereignisse getrennt bewertet. Die Prüfung belegt nur den Stand zum dokumentierten Datum.",
  ],
  es: [
    "Publication 28 exige un designador secundario cuando la dirección lo contiene, pero esa norma solo respalda la estructura postal. No demuestra que Kakobuy, el transportista internacional o un mailroom privado acepten el destino. La misma ubicación debe conservarse en la referencia privada del comprador, los campos de envío, la etiqueta final y el registro del lugar receptor.",
    "Un apartamento no se convierte en suite porque STE sea más corto, ni un buzón privado debe presentarse como apartamento. Conserva exactamente el número y sus letras o guiones significativos: 7B no equivale a B7 y un cero inicial puede formar parte de la unidad. Una etiqueta antigua sirve para comparar, no para asumir que la normalización sigue vigente.",
    "Publication 28 permite colocar la información secundaria en la línea inmediatamente superior si toda la dirección no cabe. Lo decisivo es el resultado renderizado, no solo la pantalla de edición. Una nota general, el campo de empresa o el teléfono pueden no llegar al transportista. Duplicar la unidad en dos líneas también puede crear una dirección distinta o provocar corrección manual.",
    "Si se usa el signo # porque no existe un designador conocido, debe haber un espacio antes del número. Además, esa forma puede estar prohibida para una Commercial Mail Receiving Agency. Probar variantes inventadas hasta que el formulario acepte una no es verificación: puede producir una etiqueta técnicamente válida que ya no coincide con el punto real de entrega.",
    "Introduce calle, ciudad y estado juntos en la herramienta oficial y compara cada carácter de la unidad normalizada. Apartamentos o negocios cercanos pueden recibir otros cuatro dígitos. USPS advierte expresamente que el resultado no confirma que una persona o empresa resida allí. Identidad, elegibilidad en la plataforma y permiso del receptor siguen siendo hechos separados.",
    "Cuando ambos formatos son admitidos, usa el que coincide con la dirección estandarizada actual y con las instrucciones del receptor. Si se omite un +4 válido solicitado por el edificio, deja constancia del cambio. Una decisión reproducible guarda fecha, dirección consultada, salida USPS, valor enviado y la limitación exacta del formulario que determinó la elección.",
    "El nombre del complejo no sustituye una unidad numerada. Confirma también si se aceptan paquetes internacionales para residentes cuyo nombre difiere del contrato, cajas grandes y servicios con firma. Registra dónde termina normalmente la custodia del transportista: puerta, locker, recepción o mailroom. Un escaneo en el mostrador puede ser válido antes de que el destinatario recoja el paquete.",
    "Sigue siempre este orden: nombre, número de calle, orientación, nombre y tipo de vía, edificio o designador, número secundario, ciudad, estado de dos letras, ZIP con +4 cuando proceda, país y contacto privado. Los nombres largos pueden ocultar datos esenciales. Si la vista previa los corta, pausa; no supongas que aparecerán en la etiqueta exportada.",
    "También debes parar si el +4 corresponde a otro punto o si las reglas del receptor contradicen la dirección prevista. No muevas la unidad al nombre, no acortes un identificador sin permiso ni reutilices los datos de otro inquilino. La solicitud de soporte debe describir únicamente el campo que no se conserva y adjuntar una imagen censurada.",
    "Tras enviar, guarda la versión aprobada completa en privado y una copia censurada para auditoría. No presupongas que puede cambiarse después de embalar o entregar al transportista, salvo que el flujo actual lo permita expresamente. Ante una excepción, separa dirección impresa, condiciones de acceso y eventos del carrier. La comprobación solo acredita el estado en la fecha registrada.",
  ],
  fr: [
    "Publication 28 exige un indicateur secondaire quand l’adresse en comporte un, mais cette règle ne concerne que la structure postale. Elle ne prouve pas que Kakobuy, le transporteur international ou un mailroom privé acceptera la destination. Le même point doit rester identique dans la référence privée, les champs de soumission, l’étiquette finale et le registre du lieu de réception.",
    "Un appartement ne devient pas une suite parce que STE est plus court, et une boîte privée ne doit pas être décrite comme appartement. Conservez le numéro exact, y compris lettres et traits d’union utiles : 7B n’est pas B7 et un zéro initial peut faire partie de l’identifiant. Une ancienne étiquette est un élément de comparaison, jamais une validation permanente.",
    "Publication 28 autorise l’information secondaire sur la ligne immédiatement supérieure si la ligne de livraison complète ne tient pas. Le rendu final est donc décisif, pas seulement le formulaire d’édition. Note générale, société ou téléphone peuvent disparaître avant le dernier kilomètre. Répéter l’unité sur deux lignes peut aussi créer une autre adresse ou déclencher une correction manuelle.",
    "Lorsqu’aucun indicateur connu n’est disponible et que # est utilisé, un espace doit séparer le signe du numéro. Cette notation peut aussi être interdite pour une Commercial Mail Receiving Agency. Tester des variantes inventées jusqu’à acceptation du formulaire n’est pas une vérification : l’étiquette pourrait être techniquement acceptée mais ne plus correspondre au vrai point de remise.",
    "Saisissez rue, ville et État ensemble dans l’outil officiel, puis comparez chaque caractère de l’unité normalisée. Des logements ou bureaux voisins peuvent recevoir d’autres chiffres complémentaires. USPS précise qu’un résultat ne confirme pas la présence d’une personne ou société à cette adresse. Identité, éligibilité de plateforme et autorisation de réception restent trois faits distincts.",
    "Si les deux formats sont acceptés, retenez celui qui correspond à l’adresse normalisée actuelle et aux instructions du destinataire. Si un ZIP+4 valable demandé par l’immeuble est retiré, documentez cet écart. La décision reproductible conserve date, saisie, résultat USPS, valeur soumise et limite exacte du formulaire qui a dicté ce choix.",
    "Le nom d’une résidence ne remplace jamais une unité numérotée. Vérifiez aussi l’acceptation des colis internationaux, des destinataires différents du titulaire, des grands formats et de la signature. Notez où se termine normalement la garde du transporteur : porte, casier, accueil ou mailroom. Un scan à l’accueil peut précéder le retrait personnel.",
    "Suivez l’ordre fixe : nom, numéro, direction, nom et suffixe de rue, bâtiment ou indicateur, numéro secondaire, ville, État à deux lettres, ZIP avec +4 si utilisé, pays et contact privé. Les noms d’organisation longs peuvent tronquer l’essentiel. Si l’aperçu masque une partie, arrêtez-vous et ne supposez pas que l’export la contiendra.",
    "Arrêtez aussi si le +4 correspond à un autre point ou si les règles de réception contredisent l’adresse prévue. Ne déplacez pas l’unité dans le nom, ne raccourcissez rien sans accord et ne réutilisez pas le +4 d’un autre occupant. Le support reçoit une question étroite, accompagnée d’une vue masquée sans données personnelles superflues.",
    "Après soumission, gardez la version complète approuvée en privé et une copie masquée pour l’audit. Ne supposez aucune modification après emballage ou remise au transporteur sans fonction explicite actuelle. En cas d’exception, distinguez l’adresse imprimée, les conditions d’accès et les événements du transporteur. Le contrôle prouve uniquement l’état à la date documentée.",
  ],
  it: [
    "Publication 28 richiede un designatore secondario quando l’indirizzo lo contiene, ma questa norma riguarda solo la struttura postale. Non dimostra che Kakobuy, il vettore internazionale o un mailroom privato accettino la destinazione. Lo stesso punto deve restare identico nel riferimento privato, nei campi di invio, sull’etichetta finale e nei registri del luogo ricevente.",
    "Un appartamento non diventa suite perché STE è più corto e una casella privata non va descritta come appartamento. Conserva il numero esatto con lettere e trattini significativi: 7B non è B7 e uno zero iniziale può appartenere all’identificativo. Una vecchia etichetta è solo un confronto, non la prova che la forma sia ancora corretta.",
    "Publication 28 permette di collocare l’informazione secondaria nella riga subito sopra quando la riga completa non entra. Conta quindi il risultato renderizzato, non solo il modulo di modifica. Nota generica, azienda o telefono possono sparire prima dell’ultimo miglio. Ripetere l’unità su due righe può invece creare un indirizzo diverso o richiedere correzione manuale.",
    "Se manca un designatore noto e si usa #, deve esserci uno spazio tra segno e numero. La forma può inoltre essere vietata per una Commercial Mail Receiving Agency. Provare varianti inventate finché il modulo ne accetta una non è verifica: può creare un’etichetta tecnicamente ammessa ma non più corrispondente al vero punto di consegna.",
    "Inserisci insieme via, città e stato nello strumento ufficiale, poi confronta ogni carattere dell’unità standardizzata. Appartamenti o attività vicine possono ricevere altre quattro cifre. USPS avverte che il risultato non conferma la presenza di una persona o impresa. Identità, idoneità della piattaforma e autorizzazione della reception restano fatti distinti.",
    "Quando entrambi i formati sono ammessi, usa quello coerente con l’indirizzo standardizzato attuale e con le istruzioni del ricevente. Se viene omesso un +4 valido richiesto dall’edificio, registra anche questa differenza. Una decisione riproducibile conserva data, input, risultato USPS, valore inviato e limite preciso del modulo che ha determinato la scelta.",
    "Il nome del complesso non sostituisce mai un’unità numerata. Verifica anche pacchi internazionali, destinatari diversi dall’intestatario, colli grandi e firma. Registra dove termina normalmente la custodia del corriere: porta, locker, reception o mailroom. Una scansione al banco può essere valida prima che il destinatario ritiri il pacco.",
    "Segui l’ordine fisso: nome, numero civico, direzione, nome e suffisso della strada, edificio o designatore, numero secondario, città, sigla dello stato, ZIP con +4 se usato, paese e contatto privato. Nomi aziendali lunghi possono troncare dati essenziali. Se l’anteprima li nasconde, fermati e non presumere che compaiano nell’esportazione.",
    "Fermati anche se il +4 riguarda un altro punto o se le regole della reception contrastano con l’indirizzo previsto. Non spostare l’unità nel nome, non abbreviare senza permesso e non riusare i dati di un altro residente. Il supporto riceve una domanda circoscritta e una vista oscurata, senza dati personali non necessari.",
    "Dopo l’invio conserva la versione completa approvata in privato e una copia oscurata per l’audit. Non dare per possibile una modifica dopo imballaggio o passaggio al vettore senza funzione esplicita corrente. In caso di eccezione, separa indirizzo stampato, condizioni di accesso ed eventi del corriere. Il controllo prova solo lo stato alla data registrata.",
  ],
};

for (const lang of ["de", "es", "fr", "it"] as const) {
  usaUnitZip4ArticleTranslations[lang] = {
    ...usaUnitZip4ArticleTranslations[lang],
    sections: usaUnitZip4ArticleTranslations[lang].sections.map((section, index) => ({
      ...section,
      body: `${section.body} ${parityAdditions[lang][index]}`,
    })),
  };
}
