import type { ArticleRecord } from "./article-data";
import type { Lang } from "./site-data";

type LocalizedArticle = Pick<ArticleRecord, "tag" | "title" | "description" | "sourceNote" | "sections" | "takeaways">;

export const usaBillingDeliveryArticleTranslations: Record<Lang, LocalizedArticle> = {
  en: {
    tag: "US ADDRESS CONTROL",
    title: "Billing Address vs Delivery Address: What US Kakobuy Buyers Should Verify",
    description: "Separate the payment billing address from the US parcel destination, verify each against its proper source and stop before an address mismatch becomes a payment or delivery problem.",
    sourceNote: "Kakobuy's public parcel flow, USPS Publication 28 and current payment-processor AVS documentation were reviewed on September 12, 2026. Live checkout fields, issuer decisions and route eligibility can change; this guide makes no promise that a payment or delivery will be accepted.",
    sections: [
      { heading: "Two addresses serve two different systems", body: "A billing address belongs to the payment record. A delivery address describes where the parcel should go. They may be identical, but neither should be copied into the other field merely to make a form accept it. In card-not-present payments, an address-verification service may compare address information entered at checkout with data held by the card issuer; the processor, issuer and merchant configuration determine what is checked and how a result is handled. USPS addressing standards instead describe the structure of a deliverable US postal address. Kakobuy's public buying flow places destination and logistics selection at parcel submission after warehouse receipt, but the public pages available for this review did not expose every live checkout field. Treat each current screen as the authority for what it requests. This distinction prevents a payment-source question from becoming an altered parcel destination, and prevents a valid postal address from being presented as proof that a card payment must succeed." },
      { heading: "Build two private source-of-truth records", body: "Before entering either address, create two clearly labeled private records. The billing record should come from the payment account or statement information supplied by the card issuer or payment provider. The delivery record should come from the intended recipient and, where useful, current USPS standardization. Record each field separately: full name, organization when genuinely required, street number, street name, directional, suffix, apartment or suite, city, state, ZIP Code, country and contact field. Not every billing system uses every postal component, and not every delivery form asks for the same layout. Do not publish screenshots containing these values. A safe audit copy can show field names, character counts and redacted endings while the complete values remain private. Add a checked-at date and the source consulted. The important control is not whether the two addresses match each other; it is whether each matches the right authoritative source for its purpose." },
      { heading: "Verify billing data against the payment source", body: "Use the exact billing details associated with the selected payment method. Do not substitute the shipping destination, a forwarding address or a recently moved-to address unless the issuer or provider record has actually been updated. Preserve meaningful apartment numbers, ZIP Codes and name spelling, but follow the live form's instructions for punctuation and spacing. Some processors describe AVS as a comparison of submitted billing-address data with issuer records. A match is not a payment guarantee, and a mismatch does not reveal the cause of every decline. Funds, fraud controls, card status, authentication and merchant policy can be separate factors. Kakobuy's JavaScript-dependent public pages did not allow this review to verify a universal Kakobuy AVS workflow or error wording, so this article does not invent one. If checkout rejects the billing information, capture the displayed message privately, confirm the payment-source record and use the current support channel instead of repeatedly testing fabricated address variants." },
      { heading: "Verify delivery data as a postal destination", body: "For the parcel destination, start with the recipient's real receiving location. USPS Publication 28 organizes a US address around the recipient line, delivery-address line and last line containing city, state and ZIP Code. Its detailed standards cover directionals, street suffixes and secondary-unit designators such as APT or STE. Use USPS lookup results to compare the exact delivery point, not a nearby building or another unit. Postal standardization cannot prove that the person lives there, that a private mailroom will accept the parcel or that an international route serves the location. Confirm those separately with the recipient or property. Preserve unit letters, leading zeros and meaningful hyphens. If Kakobuy's live parcel form changes a field or omits part of the address in the preview, stop and resolve that conflict. A technically accepted form is not useful if the final label no longer identifies the intended receiving point." },
      { heading: "Understand when different addresses are legitimate", body: "Different billing and delivery addresses can be ordinary: a buyer may send a parcel to a workplace, family member, campus, staffed mailroom or other authorized receiving point while paying with a card registered at home. That difference is not evidence of fraud, nor is it a reason to force the delivery address into the billing record. It can, however, create two independent verification duties. The payer should be authorized to use the payment method and should enter its current billing details. The recipient should authorize the delivery location and confirm its formatting and access conditions. Do not invent a matching address to reduce perceived risk, and do not use another person's billing details without permission. This article cannot determine Kakobuy's, a processor's or an issuer's acceptance policy for a particular transaction. It provides a documentation method: label the two records, identify the owner and source of each, and keep the reason for any difference in a private note." },
      { heading: "Map each live form field before submission", body: "Read the field label and helper text before pasting. A checkout may ask for billing details during payment and later ask for recipient details during parcel submission. Autofill can place the most recently used shipping address into a billing form, or a browser can overwrite a carefully prepared unit number. Enter one section at a time, then compare every rendered field with its proper private record. Watch for a use shipping address as billing address control: select it only when the two authoritative records are truly identical. If the form offers a saved-address selector, verify which record it loaded rather than trusting the nickname. Do not put a unit number in the phone, company or name field to bypass a length limit. If a required destination component has no durable place, pause and ask the narrow question through the current official support route. Clever field workarounds create labels and payment records that are difficult to diagnose later." },
      { heading: "Diagnose a mismatch without guessing the system", body: "When a payment screen reports an address-related problem, write down the exact visible message, payment method, checked-at time and which billing fields were submitted—using redaction in any shared copy. Confirm the issuer-side address through a trusted account or issuer contact, then compare spelling, postal code and recent address changes. Do not assume that a generic decline is an AVS failure. When a parcel form or label preview shows a destination problem, compare it with the recipient record and current USPS result instead. These are separate troubleshooting branches. Changing the delivery address cannot repair an issuer record, and changing the billing address cannot make an incomplete unit appear on a shipping label. Limit retries: repeated experimental submissions can complicate fraud controls or leave several saved addresses. Stop when the live message is ambiguous, a correct field is being truncated or the required source cannot be confirmed. Ask support to identify the specific field or record needing correction." },
      { heading: "Audit the final parcel label independently", body: "A successful product payment does not prove that the later parcel label is correct. Before international dispatch, reopen the approved delivery record and compare it character by character with the final label or address preview: recipient, street number, directional, street name and suffix, secondary-unit designator and number, city, two-letter state, ZIP or verified ZIP+4, country and contact field. The billing address does not belong on this checklist unless the interface unexpectedly copied it into the destination. Check for truncation, duplicated lines, stripped unit characters and browser-autofill changes. Save a redacted preview and the approval date. Do not assume the destination can be edited after packing, label creation or carrier handoff unless the live workflow explicitly offers that correction. A clean billing match and a standardized delivery address reduce two different kinds of preventable error; neither guarantees customs release, route availability, carrier access, signature or possession by the recipient." },
      { heading: "Protect address evidence and control changes", body: "Full billing and delivery addresses are sensitive personal data. Keep them out of public spreadsheets, screenshots, article examples, filenames and support posts. Store only what is needed, restrict access and redact account identifiers, payment details, phone numbers, door codes and tracking references before sharing. In the working log, preserve the source and date for each address version. If the cardholder updates a billing address or the recipient changes the destination, create a new version rather than overwriting the one used for an earlier payment or parcel. Link each transaction to the exact version submitted. That history explains why a later statement or USPS result differs without falsely claiming that the older entry was always wrong. Delete temporary exports when they are no longer required. A privacy-safe audit proves field structure, comparison method and timing while keeping the complete addresses only where the payer and recipient actually need them." },
      { heading: "Use a final two-address stop checklist", body: "For billing, stop if the payment-source address cannot be confirmed, the account has an unresolved recent change, autofill replaces the prepared fields or the live screen returns an unexplained mismatch. For delivery, stop if the recipient cannot confirm the location, a required apartment or suite is missing, USPS returns a materially different destination, the parcel preview truncates essential characters or the receiving location rejects the planned parcel type. For both, verify that the right person's name and contact data are in the right record and that no private information appears in shared evidence. Then freeze the version used, date it and record the outcome without overstating it. The defensible conclusion is not payment approved forever or address guaranteed deliverable. It is narrower: the billing fields matched the payer's confirmed source at submission, and the parcel destination matched the recipient's approved, currently standardized delivery record before dispatch." },
    ],
    takeaways: ["Treat billing and delivery addresses as separate records.", "Verify billing details against the payment source, not the parcel destination.", "Verify the delivery address against the recipient and current postal structure.", "Audit autofill and the final parcel preview character by character.", "Stop on unresolved mismatches; neither verification guarantees acceptance or delivery."],
  },
  de: {
    tag:"US-ADRESSKONTROLLE", title:"Rechnungs- oder Lieferadresse: Was US-Kakobuy-Käufer prüfen sollten", description:"Trennen Sie Zahlungsadresse und US-Paketziel, prüfen Sie beide an der richtigen Quelle und stoppen Sie bei ungeklärten Abweichungen.", sourceNote:"Kakobuys öffentlicher Paketablauf, USPS Publication 28 und aktuelle AVS-Dokumentation eines Zahlungsdienstleisters wurden am 12. September 2026 geprüft. Live-Felder und Entscheidungen können sich ändern; Zahlung oder Zustellung werden nicht garantiert.",
    sections:[
      {heading:"Zwei Adressen für zwei Systeme",body:"Die Rechnungsadresse gehört zum Zahlungsdatensatz, die Lieferadresse beschreibt das Paketziel. Sie können gleich sein, dürfen aber nicht nur zur Formularannahme ineinander kopiert werden. AVS kann Zahlungsdaten mit Ausstellerdaten vergleichen; USPS beschreibt dagegen Postadressstrukturen. Der aktuelle Kakobuy-Bildschirm bleibt für seine verlangten Felder maßgeblich."},
      {heading:"Zwei private Ausgangsdatensätze erstellen",body:"Führen Sie klar getrennte Datensätze. Die Rechnungsdaten stammen vom Kartenaussteller oder Zahlungsanbieter, die Lieferdaten vom Empfänger und gegebenenfalls aktueller USPS-Standardisierung. Erfassen Sie Name, Straße, Einheit, Ort, Staat, ZIP, Land und Kontakt feldweise. Vollständige Werte bleiben privat; eine Auditkopie zeigt nur geschwärzte Struktur, Datum und Quelle."},
      {heading:"Rechnungsdaten an der Zahlungsquelle prüfen",body:"Verwenden Sie die Daten des gewählten Zahlungsmittels und ersetzen Sie sie nicht durch Paket- oder Weiterleitungsadresse. Bewahren Sie Einheit, ZIP und Namensschreibweise nach den Live-Hinweisen. Ein AVS-Match garantiert keine Zahlung; ein Fehler erklärt nicht jede Ablehnung. Diese Prüfung konnte keinen universellen Kakobuy-AVS-Ablauf bestätigen und erfindet daher keinen."},
      {heading:"Lieferdaten als Postziel prüfen",body:"Beginnen Sie mit dem echten Empfangsort. USPS gliedert Empfängerzeile, Lieferzeile und letzte Zeile mit Ort, Staat und ZIP; Publication 28 behandelt Richtungsangaben, Suffixe und APT oder STE. Standardisierung beweist weder Wohnsitz noch Annahme oder Routenverfügbarkeit. Bleibt ein Pflichtteil nicht in der Vorschau, pausieren Sie."},
      {heading:"Legitime Unterschiede verstehen",body:"Arbeitsplatz, Familie, Campus oder Mailroom können ein anderes Lieferziel als die Rechnungsadresse rechtfertigen. Das beweist keinen Betrug und erlaubt keine erfundene Angleichung. Der Zahler bestätigt Berechtigung und Zahlungsdaten; der Empfänger Ziel und Zugang. Die Annahmeregel eines konkreten Vorgangs kann dieser Leitfaden nicht bestimmen."},
      {heading:"Jedes Live-Feld vor dem Senden zuordnen",body:"Lesen Sie Label und Hilfetext, bevor Sie einfügen. Autofill kann eine Versandadresse ins Rechnungsformular oder eine alte Einheit ins Paketformular schreiben. Vergleichen Sie jeden Bereich mit seinem eigenen Datensatz. Gleichsetzen nur bei wirklich identischen Quellen. Einheit oder Straße werden nicht in Name, Telefon oder Firma verschoben."},
      {heading:"Abweichungen ohne Systemraten untersuchen",body:"Notieren Sie genaue Meldung, Methode, Prüfzeit und geschwärzte Rechnungsfelder. Bestätigen Sie Ausstellerdaten; behandeln Sie eine allgemeine Ablehnung nicht automatisch als AVS-Fehler. Bei Paketproblemen vergleichen Sie Empfänger- und USPS-Datensatz. Änderungen in einem Zweig reparieren den anderen nicht. Begrenzen Sie Versuche und fragen Sie nach dem konkreten Feld."},
      {heading:"Das endgültige Paketetikett separat prüfen",body:"Eine erfolgreiche Produktzahlung beweist kein korrektes Etikett. Vergleichen Sie Empfänger, Straße, Richtung, Suffix, Einheit, Ort, Staat, ZIP, Land und Kontakt zeichenweise mit dem freigegebenen Lieferdatensatz. Suchen Sie Kürzung, Doppelung und Autofill-Änderung. Rechnungsdaten gehören nur dann in diese Prüfung, wenn sie unerwartet kopiert wurden."},
      {heading:"Adressbelege schützen und Änderungen steuern",body:"Vollständige Adressen sind sensible Daten und gehören nicht in öffentliche Tabellen, Dateinamen oder Posts. Schwärzen Sie Konten, Zahlung, Telefon, Zugangscodes und Tracking. Jede neue Rechnungs- oder Lieferfassung erhält Datum und Quelle; alte Transaktionen bleiben mit ihrer damals verwendeten Version verknüpft."},
      {heading:"Mit einer Zwei-Adressen-Stoppcheckliste enden",body:"Stoppen Sie Rechnungsdaten bei unbestätigter Quelle, ungeklärtem Umzug, Autofill-Überschreibung oder Meldung. Stoppen Sie Lieferdaten bei unbestätigtem Empfänger, fehlender Einheit, abweichendem USPS-Ergebnis oder gekürzter Vorschau. Die Schlussaussage bestätigt nur den geprüften Stand bei Einreichung, niemals dauerhafte Zahlung oder garantierte Zustellung."},
    ],takeaways:["Rechnungs- und Lieferadresse getrennt führen.","Rechnungsdaten an der Zahlungsquelle prüfen.","Lieferziel mit Empfänger und Poststruktur prüfen.","Autofill und Vorschau zeichenweise prüfen.","Bei ungeklärten Abweichungen stoppen."],
  },
  es: {
    tag:"CONTROL DE DIRECCIONES EE. UU.",title:"Dirección de facturación o entrega: qué verificar en Kakobuy",description:"Separa la dirección del pago del destino del paquete, verifica cada una con su fuente y detente ante diferencias sin resolver.",sourceNote:"El flujo público de Kakobuy, USPS Publication 28 y documentación AVS actual de un procesador se revisaron el 12 de septiembre de 2026. Campos y decisiones pueden cambiar; no se garantiza pago ni entrega.",
    sections:[
      {heading:"Dos direcciones para dos sistemas",body:"La dirección de facturación pertenece al registro de pago y la de entrega al destino del paquete. Pueden coincidir, pero no deben copiarse para forzar el formulario. AVS puede comparar datos de facturación con el emisor; USPS describe estructura postal. La pantalla Kakobuy actual manda sobre los campos que solicita."},
      {heading:"Crear dos fuentes privadas",body:"Mantén dos registros etiquetados. Facturación procede del emisor o proveedor; entrega, del destinatario y, cuando sirva, de USPS actual. Guarda nombre, calle, unidad, ciudad, estado, ZIP, país y contacto por separado. Los valores completos son privados; una copia de auditoría muestra estructura censurada, fuente y fecha."},
      {heading:"Verificar facturación con la fuente de pago",body:"Usa los datos del método elegido y no los sustituyas por la dirección de envío o reenvío. Conserva unidad, ZIP y nombre según instrucciones vivas. Un resultado AVS no garantiza pago y una discrepancia no explica todo rechazo. Esta revisión no pudo confirmar un flujo AVS universal de Kakobuy y no inventa uno."},
      {heading:"Verificar entrega como destino postal",body:"Empieza con el lugar receptor real. USPS organiza destinatario, línea de entrega y ciudad/estado/ZIP, y Publication 28 trata orientaciones, sufijos, APT y STE. Estandarizar no prueba residencia, aceptación privada o ruta. Si la vista previa elimina un componente necesario, pausa y resuelve."},
      {heading:"Entender diferencias legítimas",body:"Trabajo, familia, campus o mailroom pueden justificar un destino distinto. No es prueba de fraude ni razón para fabricar coincidencia. El pagador confirma autorización y facturación; el receptor confirma destino y acceso. Este artículo no determina la política de aceptación de una transacción concreta."},
      {heading:"Asignar cada campo vivo",body:"Lee etiqueta y ayuda antes de pegar. Autofill puede poner entrega en facturación o una unidad antigua en el paquete. Compara cada bloque con su fuente. Selecciona igualdad solo si los registros son idénticos. No muevas unidad o calle a nombre, teléfono o empresa para evitar límites."},
      {heading:"Diagnosticar sin adivinar el sistema",body:"Registra mensaje exacto, método, hora y campos censurados. Confirma la dirección con el emisor y no llames AVS a un rechazo genérico. Los problemas de etiqueta se comparan con destinatario y USPS. Cambiar un ramo no repara el otro. Limita intentos y pregunta qué campo necesita corrección."},
      {heading:"Auditar aparte la etiqueta final",body:"Un pago correcto no demuestra una etiqueta correcta. Compara nombre, calle, orientación, sufijo, unidad, ciudad, estado, ZIP, país y contacto carácter por carácter con el destino aprobado. Busca recortes, duplicados y cambios de autofill. La facturación solo aparece si fue copiada por error."},
      {heading:"Proteger pruebas y versiones",body:"Las direcciones completas son datos sensibles. No las publiques en hojas, nombres o mensajes. Censura cuenta, pago, teléfono, acceso y tracking. Una nueva dirección crea una versión con fecha y fuente; cada pago o paquete permanece unido a la versión exacta usada."},
      {heading:"Aplicar una lista de parada doble",body:"Detén facturación si no confirmas la fuente, hay cambio abierto, autofill reemplaza campos o el mensaje no se explica. Detén entrega si falta confirmación, unidad, coincide mal USPS o la vista corta datos. La conclusión solo acredita la verificación al enviar, no pago perpetuo o entrega garantizada."},
    ],takeaways:["Separa facturación y entrega.","Comprueba facturación con la fuente de pago.","Comprueba entrega con receptor y estructura postal.","Audita autofill y vista final.","Detente ante diferencias sin resolver."],
  },
  fr: {
    tag:"CONTRÔLE ADRESSE USA",title:"Adresse de facturation ou de livraison : contrôles Kakobuy aux USA",description:"Séparez l’adresse de paiement de la destination du colis, vérifiez chacune auprès de sa source et arrêtez-vous sur tout écart non résolu.",sourceNote:"Le parcours public Kakobuy, USPS Publication 28 et la documentation AVS actuelle d’un prestataire ont été consultés le 12 septembre 2026. Champs et décisions peuvent changer; aucun paiement ni livraison n’est garanti.",
    sections:[
      {heading:"Deux adresses pour deux systèmes",body:"L’adresse de facturation relève du paiement; celle de livraison décrit le colis. Elles peuvent coïncider, mais ne se copient pas pour forcer un formulaire. AVS peut comparer la facturation avec l’émetteur, tandis que USPS décrit la structure postale. L’écran Kakobuy actuel fait foi pour ses champs."},
      {heading:"Créer deux références privées",body:"Gardez deux dossiers libellés. La facturation vient de l’émetteur ou du prestataire; la livraison, du destinataire et éventuellement de USPS actuel. Consignez nom, rue, unité, ville, État, ZIP, pays et contact séparément. Les valeurs complètes restent privées; l’audit ne montre que structure masquée, source et date."},
      {heading:"Vérifier la facturation auprès du paiement",body:"Utilisez les données du moyen choisi, pas l’adresse d’envoi ou de transfert. Conservez unité, ZIP et nom selon les instructions en direct. Un résultat AVS ne garantit pas le paiement et un écart n’explique pas tout refus. Cette recherche n’a pas confirmé de parcours AVS Kakobuy universel et n’en invente aucun."},
      {heading:"Vérifier la livraison comme destination postale",body:"Partez du vrai lieu de réception. USPS organise destinataire, ligne de livraison et ville/État/ZIP; Publication 28 couvre direction, suffixe, APT et STE. La normalisation ne prouve ni résidence, acceptation privée ou route. Si l’aperçu supprime un élément requis, arrêtez et résolvez."},
      {heading:"Comprendre les différences légitimes",body:"Travail, famille, campus ou mailroom peuvent expliquer une autre destination. Ce n’est ni une preuve de fraude ni une raison d’inventer l’égalité. Le payeur confirme autorisation et facturation; le destinataire confirme lieu et accès. Ce guide ne décide pas la politique d’une transaction particulière."},
      {heading:"Mapper chaque champ en direct",body:"Lisez libellé et aide avant de coller. L’autoremplissage peut mettre livraison dans facturation ou une ancienne unité dans le colis. Comparez chaque bloc à sa source. Cochez l’égalité seulement si les dossiers le sont. Ne déplacez pas l’unité vers nom, téléphone ou société pour contourner une limite."},
      {heading:"Diagnostiquer sans deviner",body:"Notez message exact, méthode, heure et champs masqués. Confirmez auprès de l’émetteur et ne qualifiez pas tout refus d’AVS. Un problème de colis se compare au destinataire et à USPS. Modifier une branche ne répare pas l’autre. Limitez les essais et demandez quel champ doit être corrigé."},
      {heading:"Auditer séparément l’étiquette finale",body:"Un paiement accepté ne prouve pas une bonne étiquette. Comparez nom, rue, direction, suffixe, unité, ville, État, ZIP, pays et contact caractère par caractère au dossier approuvé. Cherchez troncature, doublon et autoremplissage. La facturation n’intervient que si elle a été copiée par erreur."},
      {heading:"Protéger preuves et versions",body:"Les adresses complètes sont sensibles. Ne les publiez pas dans tableurs, noms de fichiers ou posts. Masquez compte, paiement, téléphone, accès et suivi. Toute nouvelle adresse crée une version datée et sourcée; chaque paiement ou colis reste lié à la version réellement utilisée."},
      {heading:"Terminer par une double liste d’arrêt",body:"Arrêtez la facturation si source non confirmée, changement ouvert, autoremplissage ou message inexpliqué. Arrêtez la livraison si destinataire incertain, unité absente, résultat USPS différent ou aperçu tronqué. La conclusion prouve seulement le contrôle à la soumission, jamais un paiement durable ou une livraison garantie."},
    ],takeaways:["Séparer facturation et livraison.","Vérifier la facturation auprès de sa source.","Vérifier la livraison avec le destinataire et USPS.","Contrôler autoremplissage et aperçu final.","Arrêter tout écart non résolu."],
  },
  it: {
    tag:"CONTROLLO INDIRIZZI USA",title:"Indirizzo di fatturazione o consegna: controlli Kakobuy negli USA",description:"Separa l’indirizzo del pagamento dalla destinazione, verifica ciascuno con la propria fonte e fermati davanti a differenze irrisolte.",sourceNote:"Il flusso pubblico Kakobuy, USPS Publication 28 e documentazione AVS corrente di un processore sono stati verificati il 12 settembre 2026. Campi e decisioni possono cambiare; pagamento e consegna non sono garantiti.",
    sections:[
      {heading:"Due indirizzi per due sistemi",body:"L’indirizzo di fatturazione appartiene al pagamento; quello di consegna descrive il pacco. Possono coincidere, ma non vanno copiati per forzare il modulo. AVS può confrontare la fatturazione con l’emittente, USPS descrive la struttura postale. La schermata Kakobuy corrente governa i campi richiesti."},
      {heading:"Creare due fonti private",body:"Mantieni due record etichettati. Fatturazione viene dall’emittente o provider; consegna dal destinatario e, se utile, da USPS attuale. Registra separatamente nome, via, unità, città, stato, ZIP, paese e contatto. I valori completi restano privati; l’audit mostra struttura oscurata, fonte e data."},
      {heading:"Verificare la fatturazione alla fonte",body:"Usa i dati del metodo scelto, non l’indirizzo di spedizione o inoltro. Conserva unità, ZIP e nome secondo le istruzioni live. Un risultato AVS non garantisce pagamento e una differenza non spiega ogni rifiuto. Questa ricerca non ha confermato un processo AVS Kakobuy universale e non ne inventa uno."},
      {heading:"Verificare la consegna come destinazione postale",body:"Parti dal luogo reale. USPS organizza destinatario, riga di consegna e città/stato/ZIP; Publication 28 tratta direzioni, suffissi, APT e STE. Standardizzare non prova residenza, accettazione privata o rotta. Se l’anteprima elimina un componente necessario, fermati e risolvi."},
      {heading:"Capire differenze legittime",body:"Lavoro, famiglia, campus o mailroom possono giustificare una destinazione diversa. Non è prova di frode né motivo per inventare una coincidenza. Il pagante conferma autorizzazione e fatturazione; il destinatario luogo e accesso. La guida non decide la policy di una transazione specifica."},
      {heading:"Mappare ogni campo live",body:"Leggi etichetta e aiuto prima di incollare. Autofill può mettere consegna nella fatturazione o una vecchia unità nel pacco. Confronta ogni blocco con la sua fonte. Seleziona uguaglianza solo se i record sono identici. Non spostare unità in nome, telefono o azienda per aggirare limiti."},
      {heading:"Diagnosticare senza indovinare",body:"Registra messaggio esatto, metodo, ora e campi oscurati. Conferma con l’emittente e non definire AVS ogni rifiuto. Un problema del pacco si confronta con destinatario e USPS. Cambiare un ramo non ripara l’altro. Limita i tentativi e chiedi quale campo richiede correzione."},
      {heading:"Controllare separatamente l’etichetta finale",body:"Un pagamento riuscito non prova un’etichetta corretta. Confronta nome, via, direzione, suffisso, unità, città, stato, ZIP, paese e contatto carattere per carattere con il record approvato. Cerca troncamenti, duplicazioni e autofill. La fatturazione entra solo se copiata per errore."},
      {heading:"Proteggere prove e versioni",body:"Gli indirizzi completi sono dati sensibili. Non pubblicarli in fogli, nomi file o post. Oscura account, pagamento, telefono, accesso e tracking. Ogni nuovo indirizzo crea una versione con data e fonte; ogni pagamento o pacco resta collegato alla versione esatta usata."},
      {heading:"Usare una checklist finale di arresto",body:"Ferma fatturazione con fonte non confermata, modifica aperta, autofill o messaggio inspiegato. Ferma consegna con destinatario incerto, unità assente, risultato USPS diverso o anteprima troncata. La conclusione dimostra solo il controllo all’invio, non pagamento permanente o consegna garantita."},
    ],takeaways:["Separa fatturazione e consegna.","Verifica fatturazione alla fonte di pagamento.","Verifica consegna con destinatario e USPS.","Controlla autofill e anteprima finale.","Fermati davanti a differenze irrisolte."],
  },
};

const parityAdditions: Record<Exclude<Lang, "en">, string[]> = {
  de:[
    "Bei Kartenzahlungen kann ein Adressprüfdienst eingereichte Rechnungsdaten mit den Daten des Ausstellers vergleichen; Anbieter, Aussteller und Händlerkonfiguration bestimmen Ergebnis und Folgen. Eine postalisch korrekte Lieferadresse beweist deshalb keine Zahlungsannahme. Umgekehrt sagt eine bestätigte Zahlungsadresse nichts darüber aus, ob das spätere Paketetikett vollständig und zustellbar ist.",
    "Nicht jedes Zahlungssystem verwendet alle Postbestandteile und nicht jedes Versandformular zeigt dieselbe Aufteilung. Entscheidend ist nicht die Gleichheit beider Datensätze, sondern die Übereinstimmung jedes Datensatzes mit seiner zuständigen Quelle. Eine sichere Freigabekopie kann Feldnamen, Zeichenlängen und geschwärzte Enden enthalten, niemals komplette Adressen oder Karteninformationen.",
    "Auch Kartenstatus, Mittel, Authentifizierung, Betrugsprüfung und Händlerregeln können unabhängig wirken. Fotografieren Sie die sichtbare Meldung nur privat, bestätigen Sie die Daten über einen vertrauenswürdigen Zugang und nutzen Sie den aktuellen Supportweg. Wiederholtes Testen erfundener Straßen- oder ZIP-Varianten verschlechtert die Beweislage und kann zusätzliche Sicherheitsprüfungen auslösen.",
    "Prüfen Sie Richtungsangaben, Straßensuffix, APT oder STE, Buchstaben, führende Nullen und Bindestriche. Ein USPS-Ergebnis bestätigt nicht, dass die Person dort wohnt oder ein privater Mailroom internationale Pakete annimmt. Diese Punkte werden mit Empfänger oder Verwaltung geklärt. Ein vom Formular akzeptierter Text ist wertlos, wenn er den tatsächlichen Empfangspunkt nicht mehr bezeichnet.",
    "Dokumentieren Sie privat den Grund der Abweichung und die zuständige Person jeder Quelle. Verwenden Sie niemals fremde Rechnungsdaten ohne Erlaubnis. Dieser Ablauf bewertet weder Betrugsrisiko noch Annahmewahrscheinlichkeit; er zeigt nur, dass Zahlungs- und Empfangsdaten getrennt, autorisiert und zeitlich nachvollziehbar geprüft wurden.",
    "Eine Option Rechnungsadresse entspricht Lieferadresse wird nur gewählt, wenn beide bestätigten Datensätze tatsächlich identisch sind. Gespeicherte Spitznamen sind kein Beweis für den geladenen Inhalt. Bleibt ein notwendiger Zielbestandteil ohne dauerhafte Position, ist eine enge Supportfrage sicherer als das Verschieben in ein Feld, das später nicht auf dem Etikett erscheint.",
    "Ändern Sie nicht die Lieferadresse, um einen Ausstellerdatensatz zu reparieren, und nicht die Rechnungsadresse, um eine fehlende Einheit auf das Etikett zu bringen. Stoppen Sie bei unklarer Meldung, abgeschnittenem korrekten Feld oder unbestätigter Quelle. Die Supportfrage bittet um Benennung des betroffenen Feldes, ohne unnötige persönliche Daten offenzulegen.",
    "Speichern Sie eine geschwärzte Vorschau samt Freigabedatum und unterstellen Sie keine nachträgliche Bearbeitbarkeit nach Packen oder Carrier-Übergabe. Beide Kontrollen reduzieren verschiedene vermeidbare Fehler, garantieren aber weder Zollfreigabe, Linie, Zugang, Unterschrift noch persönliche Übernahme. Das Etikett bleibt ein eigener freizugebender Datensatz.",
    "Überschreiben Sie frühere Versionen nicht. Verknüpfen Sie jede Transaktion mit der exakten damals eingereichten Fassung und löschen Sie unnötige temporäre Exporte. So erklärt die Historie spätere Unterschiede zu Kontoauszug oder USPS, ohne rückwirkend eine frühere Beobachtung umzudeuten. Der Audit beweist Methode und Zeitpunkt, nicht öffentlich die Privatadresse.",
    "Prüfen Sie bei beiden Datensätzen zusätzlich, dass Name und Kontakt der richtigen Person im richtigen Feld stehen und keine privaten Daten in geteilten Belegen verbleiben. Frieren Sie danach die verwendete Version mit Datum und Ergebnis ein. Belastbar ist nur: Rechnungsfelder passten bei Einreichung zur bestätigten Zahlungsquelle und das Paketziel zur freigegebenen aktuellen Empfangsadresse.",
  ],
  es:[
    "En pagos sin tarjeta presente, AVS puede comparar información con el emisor; procesador, emisor y configuración comercial deciden cómo se usa. Una dirección postal correcta no demuestra aceptación del pago. Del mismo modo, una dirección de facturación confirmada no prueba que la etiqueta posterior esté completa o sea entregable.",
    "No todos los pagos usan cada componente postal ni cada formulario de envío presenta el mismo diseño. Lo importante no es que ambos registros sean iguales, sino que cada uno coincida con su fuente adecuada. Una copia segura puede mostrar nombres de campo, longitud y finales censurados, nunca la dirección completa o información de la tarjeta.",
    "Estado de tarjeta, fondos, autenticación, controles de fraude y política comercial también pueden intervenir. Guarda el mensaje solo en privado, confirma mediante acceso de confianza y usa soporte actual. Probar repetidamente calles o ZIP inventados degrada la evidencia y puede activar controles adicionales.",
    "Comprueba orientaciones, sufijo, APT o STE, letras, ceros iniciales y guiones. USPS no confirma residencia ni que un mailroom acepte paquetes internacionales; eso se pregunta al receptor o administración. Un formulario técnicamente aceptado no sirve si ya no identifica el punto real de entrega.",
    "Documenta en privado la razón de la diferencia y el responsable de cada fuente. Nunca uses datos de facturación ajenos sin permiso. El método no puntúa fraude o probabilidad de aceptación; solo demuestra que pago y recepción se verificaron por separado, con autorización y fecha.",
    "La casilla usar entrega como facturación se activa solo si los dos registros confirmados son idénticos. Un apodo guardado no prueba el contenido cargado. Si un componente esencial no tiene campo duradero, pregunta a soporte en vez de moverlo a un lugar que quizá no llegue a la etiqueta.",
    "No cambies entrega para arreglar el registro del emisor ni facturación para poner una unidad en la etiqueta. Detente ante mensaje ambiguo, campo correcto recortado o fuente no confirmada. Pide a soporte identificar el campo concreto sin exponer datos personales innecesarios.",
    "Guarda una vista censurada y la fecha de aprobación. No supongas que puede editarse tras embalaje o entrega al carrier. Las dos verificaciones reducen errores distintos, pero no garantizan aduana, ruta, acceso, firma o posesión del receptor. La etiqueta es un registro independiente.",
    "No sobrescribas versiones anteriores. Vincula cada transacción con la versión exacta enviada y elimina exportaciones temporales cuando sobren. El historial explica diferencias posteriores con el emisor o USPS sin reinterpretar el pasado. La auditoría prueba método y momento, no publica la dirección privada.",
    "Para ambos registros confirma también que nombre y contacto correctos estén en su campo y que ninguna prueba compartida revele privacidad. Congela versión, fecha y resultado. Solo es defendible que facturación coincidía con la fuente confirmada y entrega con el destino aprobado al momento de enviar.",
  ],
  fr:[
    "Pour un paiement à distance, AVS peut comparer les données soumises à celles de l’émetteur; prestataire, émetteur et configuration marchande déterminent l’usage du résultat. Une bonne adresse postale ne prouve donc pas l’acceptation du paiement. Une facturation confirmée ne prouve pas non plus que l’étiquette ultérieure sera complète ou livrable.",
    "Tous les systèmes de paiement n’utilisent pas chaque composant postal et tous les formulaires d’envoi n’ont pas la même structure. L’objectif n’est pas l’égalité des deux dossiers, mais la conformité de chacun à sa propre source. Une copie sûre montre libellés, longueurs et fins masquées, jamais adresse complète ou carte.",
    "État de carte, fonds, authentification, contrôles de fraude et règle marchande peuvent agir séparément. Gardez le message en privé, confirmez par un accès fiable et utilisez le support actuel. Tester des rues ou ZIP inventés détériore les preuves et peut déclencher d’autres contrôles.",
    "Contrôlez directions, suffixe, APT ou STE, lettres, zéros initiaux et traits d’union. USPS ne prouve ni résidence ni acceptation d’un colis international par un mailroom; confirmez avec le destinataire ou la gestion. Un formulaire accepté n’est pas utile si le point réel disparaît.",
    "Conservez en privé la raison de l’écart et le responsable de chaque source. N’utilisez jamais les données de facturation d’autrui sans accord. La méthode ne note ni fraude ni chance d’acceptation; elle établit seulement deux vérifications séparées, autorisées et datées.",
    "La case identique à l’adresse de livraison n’est choisie que si les deux dossiers confirmés sont réellement identiques. Un surnom enregistré ne prouve pas le contenu chargé. Sans champ durable pour un élément essentiel, interrogez le support au lieu de le déplacer vers une zone absente de l’étiquette.",
    "Ne changez pas la livraison pour réparer le dossier de l’émetteur, ni la facturation pour ajouter une unité à l’étiquette. Arrêtez-vous sur message ambigu, champ juste tronqué ou source incertaine. Demandez au support de nommer le champ précis sans divulguer de données inutiles.",
    "Gardez un aperçu masqué et sa date d’approbation. Ne supposez aucune modification après emballage ou remise au transporteur. Les deux contrôles réduisent des erreurs différentes sans garantir douane, route, accès, signature ou possession. L’étiquette reste un dossier autonome à approuver.",
    "N’écrasez pas les anciennes versions. Reliez chaque transaction à la version exacte soumise et supprimez les exports temporaires inutiles. L’historique explique un écart ultérieur avec l’émetteur ou USPS sans réécrire le passé. L’audit prouve méthode et moment, pas l’adresse publique.",
    "Pour les deux dossiers, confirmez aussi le bon nom et contact dans le bon champ et l’absence de données privées dans les preuves partagées. Figez version, date et résultat. Seule conclusion défendable : facturation conforme à sa source et livraison conforme au destinataire lors de la soumission.",
  ],
  it:[
    "Nei pagamenti a distanza, AVS può confrontare i dati con quelli dell’emittente; processore, emittente e configurazione del commerciante decidono l’uso del risultato. Un indirizzo postale corretto non prova quindi l’accettazione del pagamento. Una fatturazione confermata non prova che l’etichetta successiva sia completa o consegnabile.",
    "Non tutti i sistemi di pagamento usano ogni componente postale e non tutti i moduli di spedizione hanno lo stesso layout. Conta non l’uguaglianza dei due record, ma la conformità di ciascuno alla propria fonte. Una copia sicura mostra campi, lunghezze e finali oscurati, mai indirizzo completo o carta.",
    "Stato della carta, fondi, autenticazione, controlli antifrode e regola del commerciante possono agire separatamente. Conserva il messaggio in privato, verifica con accesso affidabile e usa il supporto corrente. Tentare vie o ZIP inventati indebolisce le prove e può attivare ulteriori controlli.",
    "Controlla direzioni, suffisso, APT o STE, lettere, zeri iniziali e trattini. USPS non prova residenza né accettazione di pacchi internazionali da parte di un mailroom; conferma con destinatario o gestione. Un modulo accettato non serve se non identifica più il punto reale.",
    "Documenta in privato il motivo della differenza e il responsabile di ogni fonte. Non usare dati di fatturazione altrui senza permesso. Il metodo non valuta frode o probabilità di accettazione; dimostra soltanto verifiche separate, autorizzate e datate.",
    "La casella usa consegna come fatturazione si seleziona solo se i due record confermati sono davvero identici. Un soprannome salvato non prova il contenuto caricato. Se manca un campo durevole per un elemento essenziale, chiedi al supporto invece di spostarlo dove potrebbe non raggiungere l’etichetta.",
    "Non cambiare la consegna per riparare il record dell’emittente né la fatturazione per inserire un’unità sull’etichetta. Fermati davanti a messaggio ambiguo, campo corretto troncato o fonte incerta. Chiedi al supporto il campo preciso senza esporre dati personali non necessari.",
    "Salva un’anteprima oscurata e la data di approvazione. Non presumere modifiche dopo imballaggio o passaggio al corriere. I due controlli riducono errori diversi senza garantire dogana, rotta, accesso, firma o possesso. L’etichetta resta un record autonomo da approvare.",
    "Non sovrascrivere versioni precedenti. Collega ogni transazione alla versione esatta inviata ed elimina esportazioni temporanee inutili. La cronologia spiega differenze successive con emittente o USPS senza riscrivere il passato. L’audit prova metodo e momento, non pubblica l’indirizzo.",
    "Per entrambi conferma anche nome e contatto corretti nel campo giusto e nessun dato privato nelle prove condivise. Congela versione, data e risultato. La sola conclusione difendibile è che fatturazione e consegna corrispondevano alle rispettive fonti al momento dell’invio.",
  ],
};

for (const lang of ["de", "es", "fr", "it"] as const) {
  usaBillingDeliveryArticleTranslations[lang] = {
    ...usaBillingDeliveryArticleTranslations[lang],
    sections: usaBillingDeliveryArticleTranslations[lang].sections.map((section, index) => ({
      ...section,
      body: `${section.body} ${parityAdditions[lang][index]}`,
    })),
  };
}
