import type { ArticleRecord } from "./article-data";
import type { Lang } from "./site-data";

type LocalizedArticle = Pick<ArticleRecord, "tag" | "title" | "description" | "sourceNote" | "sections" | "takeaways">;

export const usaArticleTranslations:Record<Lang,LocalizedArticle>={
  en:{
    tag:"US BUYER GUIDE",
    title:"Kakobuy USA Guide 2026: A Pre-Order Readiness Checklist for US Buyers",
    description:"Prepare a Kakobuy order for the United States with an address, product-description, import-record and last-mile evidence checklist that avoids stale customs promises.",
    sourceNote:"Platform workflow facts were checked on Kakobuy on September 2, 2026. US import guidance was checked on current CBP and USITC pages. Rules, carrier eligibility, duties and account screens can change; current official sources and the live order remain controlling.",
    sections:[
      {heading:"Start with destination readiness, not a route promise",body:"A Kakobuy USA guide should begin before the product order, when mistakes can still be corrected without an international parcel. Confirm that the recipient can receive the item at the intended US address, that the product can be described accurately, and that current import and carrier rules have been checked. Kakobuy’s public flow separates product purchase, warehouse receipt, parcel submission and international transport. That sequence supports a readiness checklist, but it does not prove that every product, route or delivery method is available for every US address. Do not choose an item because an old post names a fast line or a duty-free threshold. Save the current date, destination state and ZIP Code, then check the live options at the relevant stage. The goal is not to predict clearance or delivery. It is to create a record that shows what was checked before money and personal data were committed."},
      {heading:"Verify the recipient and address fields exactly",body:"Write the recipient record in a private worksheet before entering it into an account. Keep full legal recipient name, street line, apartment or unit, city, state abbreviation, ZIP Code, country, reachable phone number and email in separate fields. Do not combine the apartment with an unsupported comment or translate a street name. Compare the completed account form with a trusted address record, then save a redacted snapshot that shows field placement without exposing the full details publicly. A carrier may require a phone number for delivery questions, but that does not make it safe to publish. If the recipient uses a dormitory, mailroom, commercial receiving service or building concierge, verify the site’s own acceptance rules and hours. This checklist does not guarantee delivery; it reduces preventable mismatches between the account, label and location that will receive the parcel."},
      {heading:"Create an accurate product identity record",body:"For every intended item, save the live source page, seller, selected variant, quantity, displayed price, check date and a neutral product description. A description should identify what the object is and what it is made of when known, not rely on a brand nickname, social-media title or vague word such as accessory. Record supporting labels or seller-stated material claims separately from facts you personally verified. If the exact composition is unknown, mark it unknown rather than guessing. Add a photo or screenshot of the selected option for your private file, but never treat seller images as proof of the warehouse arrival. Accurate identity matters because US admissibility, classification and carrier eligibility can depend on the item, material, intended use and quantity. This is an import-readiness record, not a product-recommendation spreadsheet, so keep the list limited to items actually being considered for the same destination."},
      {heading:"Check whether the product raises an import question",body:"US Customs and Border Protection tells internet purchasers that they are responsible for understanding whether merchandise is prohibited, restricted or subject to other agency requirements. Use that as a prompt to classify questions, not as permission to make your own legal guarantee. Flag food, medicine, cosmetics, plants, animal products, weapons, chemicals, batteries, radio devices, counterfeit goods and other regulated categories for official review before ordering. The list is illustrative, not complete. Search the current CBP guidance and the responsible federal agency when the item falls into a regulated category. If the answer depends on facts the seller cannot provide, reject or postpone the item. Do not assume that a marketplace listing, warehouse acceptance or available shipping line proves US admissibility. Those are different checkpoints run by different parties."},
      {heading:"Use current classification sources without self-certifying",body:"The US International Trade Commission publishes the Harmonized Tariff Schedule, while CBP explains importing responsibilities. These sources can help identify the questions a buyer should ask about material, construction, use and value. They do not make a casual keyword search a binding classification ruling. Save the HTS page, revision date, search terms and candidate heading only as research notes unless a competent authority confirms the classification. Avoid publishing a fixed duty rate from an undated screenshot. Rates, exclusions and special programs can change, and a product may fit a different provision after its actual composition is known. For ordinary readiness, the useful output is a list of missing classification facts and a current official source pointer. A buyer who cannot describe the item well enough to search the current schedule should resolve that gap before parcel submission."},
      {heading:"Do not rely on a stale de minimis shortcut",body:"US low-value shipment processing has changed materially, and current CBP pages and 2026 notices should be consulted rather than repeating an old universal threshold. Do not state that a parcel will be duty-free merely because its value is below a number remembered from previous years. Record the purchase value, currency, item quantities, current rule source and access date, then budget for possible duties, fees or carrier processing without inventing the amount. Gifts, personal purchases and commercial quantities can be treated differently, and special rules may apply to particular origins or products. The readiness decision is simple: if the order only makes sense under an unverified no-duty assumption, pause. A flexible budget and an accurate record are safer than a customs promise that a content site cannot make."},
      {heading:"Separate seller, warehouse, export, customs and carrier checks",body:"A product passes through several gates. The seller must supply the selected item. The warehouse must receive and record it. The parcel workflow must accept it for packing. A shipping line must consider it eligible under current transport rules. US authorities may review admissibility, value and documentation. A last-mile carrier then attempts delivery. Success at one gate is not approval at the next. Add a column for each gate with confirmed, unresolved, not yet checked or not applicable. Keep the source and date beside every confirmed entry. If a line is absent from the live account, record that it was not displayed for the current input set; do not rename the absence a legal prohibition. This layered model prevents an available buy button or warehouse status from being presented as evidence that US import and delivery are guaranteed."},
      {heading:"Prepare a privacy-safe import document folder",body:"Create a folder with the source listing, selected variant, seller receipt, payment record, warehouse record, parcel contents list, declared description, value support, route terms and tracking page. Use filenames that contain a redacted object label, document type and date rather than a full order or tracking number. Keep originals private and share only what a legitimate support, carrier or government channel requests. Remove account tokens, QR codes, full addresses, phone numbers and payment credentials from any public copy. Maintain a short index that says which file supports product identity, value, quantity, address and transport event. Good documentation does not ensure clearance, but it makes it possible to answer a request consistently without reconstructing the order from memory or sending an unfiltered screen recording."},
      {heading:"Plan the US last-mile handoff before dispatch",body:"Check whether the delivery address can receive parcels during the likely service conditions without assuming a specific carrier. Record access codes through the approved private channel, not in public notes. Decide who will monitor tracking, who can collect a signature if required, and how the recipient will document visible damage. When a final carrier appears, save its official tracking page and any last-mile reference shown. Do not treat a label-created event as physical acceptance or a foreign tracking number as proof of a particular US carrier. If delivery is to a mailroom, campus or forwarding service, record the internal handoff rule because carrier delivery and recipient possession may occur at different times. The plan should describe responsibilities and evidence, not promise an arrival date."},
      {heading:"Run a final pre-order stop check",body:"Before paying for any item, confirm that the source and variant are current, the recipient fields are complete, the product can be described accurately, regulated-category questions have been resolved, current CBP and USITC sources have been saved, and the budget does not depend on an unverified duty exemption. Mark restricted or unclear items as pause, not maybe. Keep route choice, packed measurements and final customs data for later stages because they do not yet exist at pre-order. The strongest Kakobuy USA guide is willing to conclude that an item is not ready. A documented stop avoids later pressure to force an unsuitable product through warehouse, shipping and customs checkpoints. If every mandatory field is supported, retain the dated checklist with the private order record and revisit changing official rules before international parcel submission."},
    ],
    takeaways:["Verify recipient and address fields before ordering.","Describe each item accurately and flag regulated categories.","Use current CBP and USITC sources instead of a stale threshold.","Treat seller, warehouse, route, customs and carrier as separate gates.","Keep a private, redacted evidence folder and a pre-order stop rule."]
  },
  de:{tag:"USA-KAUFRATGEBER",title:"Kakobuy USA 2026: Bereitschaftscheck vor der Bestellung",description:"Bereite eine Kakobuy-Bestellung für die USA mit Adress-, Warenbeschreibungs-, Import- und Zustellbelegen vor, ohne veraltete Zollversprechen.",sourceNote:"Kakobuy-Ablauf sowie aktuelle CBP- und USITC-Seiten wurden am 2. September 2026 geprüft. Regeln, Pflichten und Linien können sich ändern.",sections:[
    {heading:"Mit Zielbereitschaft statt Linienversprechen beginnen",body:"Prüfe vor dem Warenkauf, ob Empfänger und US-Adresse geeignet sind, die Ware korrekt beschrieben werden kann und aktuelle Import- sowie Carrier-Regeln recherchiert wurden. Kakobuy trennt Kauf, Lager, Paketeinreichung und internationalen Transport, garantiert aber keine Verfügbarkeit für jede Ware oder Adresse. Speichere Datum, Bundesstaat und ZIP Code und wiederhole die Live-Prüfung in der passenden Phase."},
    {heading:"Empfänger- und Adressfelder exakt prüfen",body:"Führe Name, Straße, Einheit, Stadt, Bundesstaat, ZIP Code, Land, Telefon und E-Mail in getrennten privaten Feldern. Vergleiche das Konto mit einer verlässlichen Adressquelle. Bei Wohnheim, Mailroom oder Empfangsdienst werden Annahmeregeln und Öffnungszeiten geprüft. Teile nur geschwärzte Ansichten; Telefonnummer und Volladresse bleiben privat."},
    {heading:"Einen genauen Produktdatensatz erstellen",body:"Speichere aktuelle Quellseite, Verkäufer, Variante, Menge, Preis, Prüfdatum und eine neutrale Warenbeschreibung. Trenne Händlerangaben zu Material von selbst bestätigten Fakten. Unbekannte Zusammensetzung bleibt unbekannt. Identität, Material, Nutzung und Menge können Einfuhr- und Carrierfragen beeinflussen; die Liste enthält nur tatsächlich erwogene Artikel."},
    {heading:"Importfragen vorab markieren",body:"CBP weist Onlinekäufer auf eigene Verantwortung für verbotene, beschränkte oder anderweitig regulierte Waren hin. Lebensmittel, Medikamente, Kosmetik, Pflanzen, Tierprodukte, Waffen, Chemikalien, Batterien, Funkgeräte und Fälschungen benötigen aktuelle Behördenprüfung; die Liste ist nicht vollständig. Marketplace-, Lager- oder Linienannahme beweist keine US-Zulässigkeit."},
    {heading:"Aktuelle Klassifikationsquellen richtig verwenden",body:"Der USITC-HTS und CBP helfen, Fragen zu Material, Aufbau, Nutzung und Wert zu strukturieren. Eine Stichwortsuche ist keine verbindliche Einstufung. Speichere Revision, Suchbegriffe und mögliche Position nur als Recherche. Keine feste Zollrate aus altem Screenshot veröffentlichen; fehlende Fakten werden vor der Paketeinreichung geklärt."},
    {heading:"Keinen veralteten De-minimis-Kurzschluss nutzen",body:"Die US-Behandlung niedrigwertiger Sendungen hat sich geändert. Prüfe aktuelle CBP-Seiten und 2026-Hinweise statt eine alte universelle Schwelle zu wiederholen. Erfasse Kaufwert, Währung, Menge, Quelle und Abrufdatum und plane mögliche Abgaben, ohne Beträge zu erfinden. Hängt der Kauf von einer unbelegten Zollfreiheit ab, wird pausiert."},
    {heading:"Prüfstellen voneinander trennen",body:"Verkäufer, Lager, Paketablauf, Linie, US-Behörden und letzte Meile prüfen unterschiedliche Dinge. Lege pro Gate bestätigt, offen, noch nicht geprüft oder nicht anwendbar fest, jeweils mit Quelle und Datum. Eine nicht angezeigte Linie ist für die Eingabe nicht verfügbar; sie ist damit nicht automatisch gesetzlich verboten."},
    {heading:"Datenschutzsicheren Dokumentordner vorbereiten",body:"Ordner enthält Angebot, Variante, Beleg, Zahlung, Lagerrecord, Inhaltsliste, Beschreibung, Wertnachweis, Linienbedingungen und Tracking. Dateinamen nutzen geschwärzte Objektkennung, Dokumenttyp und Datum. Originale bleiben privat; Tokens, QR, Adresse, Telefon und Zahlungsdaten werden nicht öffentlich geteilt. Ein Index ordnet jede Datei einer Aussage zu."},
    {heading:"US-Zustellung vor Versand planen",body:"Prüfe private Zugangshinweise, Zuständigkeit fürs Tracking, mögliche Unterschrift und Dokumentation sichtbarer Schäden, ohne einen Carrier vorauszusetzen. Speichere später die offizielle Carrier-Seite und letzte Meile. Label erstellt ist keine physische Annahme. Bei Mailroom oder Campus wird der interne Übergang separat dokumentiert."},
    {heading:"Abschließenden Stop-Check ausführen",body:"Vor Zahlung müssen Quelle, Variante, Empfänger, Beschreibung, regulatorische Fragen, aktuelle CBP-/USITC-Quellen und ein Budget ohne unbelegte Zollfreiheit stimmen. Unklare Ware erhält Pause. Route, Packmaße und endgültige Zolldaten gehören in spätere Phasen. Die datierte Liste wird vor internationaler Einreichung erneut geprüft."},
  ],takeaways:["Empfänger und Adresse zuerst prüfen.","Ware korrekt beschreiben und regulierte Kategorien markieren.","Aktuelle CBP- und USITC-Quellen nutzen.","Alle Prüfstellen getrennt halten.","Privaten Belegordner und Stop-Regel führen."]},
  es:{tag:"GUÍA PARA EE. UU.",title:"Guía Kakobuy USA 2026: lista previa al pedido",description:"Prepara un pedido Kakobuy para Estados Unidos con controles de dirección, descripción, importación y entrega sin promesas aduaneras obsoletas.",sourceNote:"El flujo de Kakobuy y las páginas actuales de CBP y USITC se revisaron el 2 de septiembre de 2026. Las reglas y opciones pueden cambiar.",sections:[
    {heading:"Empezar por el destino, no por una promesa de ruta",body:"Antes de comprar, confirma que el destinatario puede recibir en la dirección estadounidense, que el artículo puede describirse y que se revisaron reglas actuales. Kakobuy separa compra, almacén, paquete y transporte, pero no garantiza disponibilidad para todo producto o ZIP. Guarda fecha, estado y código postal y repite la revisión en la fase adecuada."},
    {heading:"Verificar cada campo del destinatario",body:"Separa nombre, calle, unidad, ciudad, estado, ZIP, país, teléfono y correo en un registro privado. Compara el formulario con una fuente fiable. Para residencia, conserjería o servicio receptor, confirma horario y reglas. Comparte solo capturas ocultas; la dirección y el teléfono completos siguen privados."},
    {heading:"Crear una identidad exacta del producto",body:"Guarda ficha vigente, vendedor, variante, cantidad, precio, fecha y descripción neutral. Separa declaraciones del vendedor sobre material de hechos confirmados. Lo desconocido se marca desconocido. Identidad, material, uso y cantidad pueden afectar importación y transporte; incluye solo artículos realmente considerados."},
    {heading:"Detectar preguntas de importación",body:"CBP indica que el comprador por internet debe entender prohibiciones, restricciones y requisitos de otras agencias. Alimentos, medicinas, cosméticos, plantas, productos animales, armas, químicos, baterías, radios y falsificaciones requieren revisión oficial; la lista no es completa. La aceptación por marketplace, almacén o línea no prueba admisibilidad estadounidense."},
    {heading:"Usar fuentes de clasificación actuales",body:"El HTS de USITC y CBP ayudan a formular preguntas sobre material, construcción, uso y valor. Una búsqueda no es una clasificación vinculante. Guarda revisión, términos y posible partida como investigación. No publiques una tasa fija desde una captura antigua; resuelve los datos faltantes antes de presentar el paquete."},
    {heading:"No depender de un atajo de minimis antiguo",body:"El tratamiento estadounidense de envíos de bajo valor ha cambiado. Consulta CBP actual y avisos de 2026 en vez de repetir un umbral universal. Registra valor, moneda, cantidades, fuente y fecha, y reserva posibles cargos sin inventar el importe. Si el pedido solo funciona con exención no verificada, pausa."},
    {heading:"Separar vendedor, almacén, ruta, aduana y transportista",body:"Cada puerta confirma algo diferente. Marca confirmada, pendiente, aún no revisada o no aplicable con fuente y fecha. Que una línea no aparezca significa que no se mostró para esos datos, no que exista una prohibición legal universal. Un botón de compra tampoco garantiza importación o entrega."},
    {heading:"Preparar una carpeta privada",body:"Incluye ficha, variante, recibo, pago, almacén, contenido, descripción, valor, condiciones y seguimiento. Nombra archivos con objeto oculto, tipo y fecha. Conserva originales privados y elimina tokens, QR, dirección, teléfono y credenciales de copias públicas. Un índice enlaza cada archivo con identidad, valor, cantidad, dirección o evento."},
    {heading:"Planear la última milla en Estados Unidos",body:"Confirma acceso privado, responsable del seguimiento, posible firma y documentación de daños sin suponer transportista. Cuando aparezca, guarda la página oficial y referencia final. Etiqueta creada no es aceptación física. En campus, mailroom o reenvío, registra por separado el traspaso interno."},
    {heading:"Ejecutar el control final",body:"Antes de pagar confirma fuente, variante, destinatario, descripción, preguntas reguladas, fuentes actuales de CBP/USITC y presupuesto sin exención supuesta. Lo dudoso se pausa. Ruta, medidas embaladas y datos aduaneros finales pertenecen a fases posteriores. Revisa la lista fechada antes de presentar internacionalmente."},
  ],takeaways:["Verifica dirección antes de comprar.","Describe y marca categorías reguladas.","Usa fuentes actuales de CBP y USITC.","Separa todas las puertas del proceso.","Guarda pruebas privadas y una regla de pausa."]},
  fr:{tag:"GUIDE ACHETEUR USA",title:"Guide Kakobuy USA 2026 : contrôle avant commande",description:"Préparez une commande Kakobuy vers les États-Unis avec des contrôles d’adresse, description, importation et dernier kilomètre, sans promesse douanière périmée.",sourceNote:"Le parcours Kakobuy et les pages actuelles du CBP et de l’USITC ont été vérifiés le 2 septembre 2026. Les règles et options évoluent.",sections:[
    {heading:"Commencer par la préparation de la destination",body:"Avant l’achat, confirmez que le destinataire peut recevoir à l’adresse américaine, que l’article peut être décrit et que les règles actuelles ont été consultées. Kakobuy sépare achat, entrepôt, colis et transport sans garantir chaque produit ou ZIP Code. Sauvegardez date, État et code postal, puis revérifiez au bon stade."},
    {heading:"Vérifier exactement les champs d’adresse",body:"Séparez nom, rue, unité, ville, État, ZIP, pays, téléphone et e-mail dans un dossier privé. Comparez le formulaire à une source fiable. Pour résidence, concierge ou service de réception, vérifiez règles et horaires. Ne partagez qu’une copie masquée ; adresse et téléphone complets restent privés."},
    {heading:"Créer une identité produit exacte",body:"Gardez page actuelle, vendeur, variante, quantité, prix, date et description neutre. Séparez les déclarations du vendeur sur la matière des faits confirmés. L’inconnu reste inconnu. Identité, matière, usage et quantité peuvent modifier les questions d’importation et de transport."},
    {heading:"Repérer une question d’importation",body:"Le CBP rappelle aux acheteurs en ligne leur responsabilité pour les produits interdits, restreints ou soumis à une autre agence. Aliments, médicaments, cosmétiques, plantes, produits animaux, armes, produits chimiques, batteries, radios et contrefaçons exigent une vérification officielle ; la liste n’est pas exhaustive. Marketplace, entrepôt ou ligne ne prouvent pas l’admissibilité."},
    {heading:"Utiliser les sources de classement actuelles",body:"Le HTS de l’USITC et le CBP structurent les questions de matière, construction, usage et valeur. Une recherche ne constitue pas un classement opposable. Sauvegardez révision, termes et position candidate comme notes. Ne publiez pas un taux fixe provenant d’une ancienne capture ; résolvez les faits manquants avant le colis."},
    {heading:"Éviter un ancien raccourci de minimis",body:"Le traitement américain des faibles valeurs a beaucoup changé. Consultez les pages CBP actuelles et avis 2026 au lieu de répéter un seuil universel. Notez valeur, devise, quantités, source et date, et prévoyez des charges possibles sans inventer le montant. Si l’achat dépend d’une exemption non vérifiée, mettez en pause."},
    {heading:"Séparer les différents contrôles",body:"Vendeur, entrepôt, flux colis, ligne, autorités américaines et dernier transporteur vérifient des éléments différents. Marquez confirmé, non résolu, non vérifié ou non applicable avec source et date. Une ligne absente n’est pas automatiquement une interdiction légale ; un bouton d’achat ne garantit pas l’importation."},
    {heading:"Préparer un dossier documentaire privé",body:"Rassemblez annonce, variante, reçu, paiement, entrepôt, contenu, description, valeur, conditions et suivi. Les noms de fichiers utilisent objet masqué, type et date. Les originaux restent privés ; jetons, QR, adresse, téléphone et paiement disparaissent des copies publiques. Un index relie chaque fichier au fait prouvé."},
    {heading:"Planifier le dernier kilomètre américain",body:"Confirmez accès privé, responsable du suivi, signature possible et preuve des dommages sans présumer du transporteur. Lorsqu’il apparaît, gardez la page officielle et la référence locale. Étiquette créée ne signifie pas acceptation physique. Pour campus, mailroom ou réexpéditeur, notez séparément la remise interne."},
    {heading:"Effectuer le contrôle d’arrêt final",body:"Avant paiement, confirmez source, variante, destinataire, description, questions réglementaires, sources CBP/USITC actuelles et budget sans exemption supposée. Tout article flou est mis en pause. Route, dimensions emballées et données douanières finales appartiennent aux étapes suivantes. Revérifiez la liste avant la soumission internationale."},
  ],takeaways:["Vérifier adresse et destinataire.","Décrire précisément et signaler les catégories réglementées.","Employer les sources CBP et USITC actuelles.","Séparer chaque contrôle du parcours.","Conserver preuves privées et règle d’arrêt."]},
  it:{tag:"GUIDA ACQUIRENTE USA",title:"Guida Kakobuy USA 2026: controllo prima dell’ordine",description:"Prepara un ordine Kakobuy verso gli Stati Uniti con controlli su indirizzo, descrizione, importazione e ultimo miglio senza promesse doganali obsolete.",sourceNote:"Il flusso Kakobuy e le pagine correnti CBP e USITC sono stati verificati il 2 settembre 2026. Regole e opzioni possono cambiare.",sections:[
    {heading:"Partire dalla preparazione della destinazione",body:"Prima dell’acquisto conferma che il destinatario riceva all’indirizzo USA, che l’articolo sia descrivibile e che le regole correnti siano state controllate. Kakobuy separa acquisto, magazzino, pacco e trasporto, senza garantire ogni prodotto o ZIP. Salva data, stato e codice postale e ricontrolla nella fase corretta."},
    {heading:"Verificare esattamente i campi destinatario",body:"Separa nome, strada, unità, città, stato, ZIP, paese, telefono ed e-mail in un registro privato. Confronta il modulo con una fonte affidabile. Per dormitorio, portineria o servizio ricezione, verifica regole e orari. Condividi solo copie oscurate; indirizzo e telefono completi restano privati."},
    {heading:"Creare un’identità prodotto accurata",body:"Salva pagina attuale, venditore, variante, quantità, prezzo, data e descrizione neutra. Separa le dichiarazioni del venditore sul materiale dai fatti confermati. L’ignoto resta ignoto. Identità, materiale, uso e quantità possono influire su importazione e vettore; includi solo articoli realmente considerati."},
    {heading:"Individuare domande di importazione",body:"CBP ricorda agli acquirenti online la responsabilità per merci vietate, limitate o soggette ad altre agenzie. Cibo, farmaci, cosmetici, piante, prodotti animali, armi, chimici, batterie, radio e contraffazioni richiedono verifica ufficiale; l’elenco non è completo. Marketplace, magazzino o linea non provano ammissibilità USA."},
    {heading:"Usare fonti di classificazione correnti",body:"HTS USITC e CBP aiutano con domande su materiale, costruzione, uso e valore. Una ricerca non è una classificazione vincolante. Salva revisione, termini e voce possibile come note. Non pubblicare un’aliquota fissa da vecchie schermate; risolvi i fatti mancanti prima di inviare il pacco."},
    {heading:"Non dipendere da una vecchia scorciatoia de minimis",body:"Il trattamento USA delle spedizioni di basso valore è cambiato. Consulta CBP corrente e avvisi 2026 invece di ripetere una soglia universale. Registra valore, valuta, quantità, fonte e data e prevedi possibili oneri senza inventare importi. Se l’ordine funziona solo con esenzione non verificata, sospendi."},
    {heading:"Separare venditore, magazzino, rotta, dogana e vettore",body:"Ogni passaggio verifica cose diverse. Segna confermato, irrisolto, non controllato o non applicabile con fonte e data. Una linea assente non è automaticamente vietata dalla legge; il pulsante di acquisto non garantisce importazione o consegna."},
    {heading:"Preparare una cartella privata",body:"Raccogli inserzione, variante, ricevuta, pagamento, magazzino, contenuto, descrizione, valore, condizioni e tracking. I nomi file usano oggetto oscurato, tipo e data. Gli originali restano privati e token, QR, indirizzo, telefono e pagamento sono rimossi dalle copie pubbliche. Un indice collega ogni file al fatto."},
    {heading:"Pianificare l’ultimo miglio USA",body:"Conferma accesso privato, responsabile del tracking, firma possibile e prove dei danni senza presumere il vettore. Quando appare, salva la pagina ufficiale e il riferimento locale. Etichetta creata non significa accettazione fisica. Per campus, mailroom o inoltro, registra separatamente il passaggio interno."},
    {heading:"Eseguire il controllo finale",body:"Prima del pagamento conferma fonte, variante, destinatario, descrizione, domande regolatorie, fonti CBP/USITC correnti e budget senza esenzione presunta. Gli articoli dubbi vengono sospesi. Rotta, misure imballate e dati doganali finali appartengono alle fasi successive. Ricontrolla la lista prima dell’invio internazionale."},
  ],takeaways:["Verifica destinatario e indirizzo.","Descrivi bene e segnala categorie regolate.","Usa fonti CBP e USITC correnti.","Separa ogni passaggio di controllo.","Conserva prove private e una regola di stop."]}
};
